Add tls_certificate_distributor implementation
grpc/grpc pull request #23572
Opened 2020-07-22 00:26 UTC by ZhenLian

2020-07-31 06:33 UTC, ZhenLian commented
@markdroth Thank you so much for the review! The tests are almost done, but after I turned this PR to reviewable state I noticed that it was failing on `Bazel RBE MSAN C/C++`, so I made some pushes today to debug it. I will work on resolving your comments once I figure out what's the problem. Thanks!

2020-07-31 19:32 UTC, markdroth commented
If you're seeing a lot of MSAN errors, they are probably related to the absl synchronization change that @veblush was working on.  I think he was going to revert that change, but you can ask him for the current status.

2020-07-31 20:19 UTC, ZhenLian commented
> If you're seeing a lot of MSAN errors, they are probably related to the absl synchronization change that @veblush was working on. I think he was going to revert that change, but you can ask him for the current status.
Got it! Thanks for the information!

2020-08-03 17:24 UTC, jiangtaoli2016 commented on src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc
> +      bool identity_cert_watched = false;
echo to my other comments. Separate watch_status_callback into two will be the code much cleaner and easy to understand.

2020-08-03 23:12 UTC, sanjaypujare commented
CC @yashykt

2020-09-02 23:19 UTC, JScon01 reviewed
How do you run your script and see if there are any errors?

2020-09-03 01:23 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23572)* status: all files reviewed, 16 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @yashykt)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 85 at r9](https://reviewable.io/reviews/grpc/grpc/23572#-MFqzY8T0X60gbORuxf3:-MGFtA6cC_34PKeWuCay:b-lulsnd) ([raw file](https://github.com/grpc/grpc/blob/ac0cbc1659c6d56fc4014938fbc342d8b472e67d/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'd be fine with splitting it up into three methods.  Or just stick with one method but use `absl::optional<>` for the parameters.
</blockquote></details>

SG. I also made function `SetKeyMaterials` taking  absl::optional parameters here, so that we don't need three functions for setting key materials. 
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 189 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGEHWmn2lZDRZ03-54d:-MGEhPRND0brntc7uJMJ:b5qtmzj) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f6f12dc2c33f68f2dbc86cd91/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L189)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think it's necessary to check `updated_root_certs != 0` or `(*updated_identity_pairs).size() > 0`, because the `absl::optional<>` will not contain any value if the fields are unset.

To say this another way, if we did want to disallow those values, the right place to do it would be on input, not on notification to a watcher.  And I don't really think it's necessary to do that to begin with.
</blockquote></details>

I added this line because the `CertificateInfo` currently combines all the information, and sometimes for example we are inserting a certInfo entry for the `root_cert_error` field, the `pem_root_certs` and `pem_key_cert_pairs` fields will be initiated as well, though currently we don't have any credential available yet. In these cases, the `updated_root_certs` and `updated_identity_pairs` will be zero values, and hence I added this line here.
I also think it's not a good idea to assume "no credential provided" equals to "credential provided with size of 0". The best way I can think of is to add absl::optional around `pem_root_certs` and `pem_key_cert_pairs` in `CertificateInfo`, but we still need to check `updated_root_certs.has_value() || updated_identity_pairs.has_value()` here. Does this look better to you?
___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 1156 at r8](https://reviewable.io/reviews/grpc/grpc/23572#-MFkzHbs-7IrsVKy923q:-MGFW6iE1jjDk7wrl9XX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7e90526dda9c1775f94bc0e412760b03d69b8062/test/core/security/grpc_tls_certificate_distributor_test.cc#L1156)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay, so now that you've created the fixture class, we still need to address my original comment in this thread, which was that we really want to make sure that the watcher is destroyed whenever it is cancelled.  I suggest adding the following method on the test fixture class:

```
void CancelWatch(WatcherState* state) {
  distributor_.CancelTlsCertificatesWatch(state->watcher);
  EXPECT_EQ(state->watcher, nullptr);
}
```

Then change all the tests to use this method instead of calling `CancelTlsCertificatesWatch()` on the distributor.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 101 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGEJ4JTCOqKCFwxhwEP:-MGElLnP2Rb_wAkspYjt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f6f12dc2c33f68f2dbc86cd91/test/core/security/grpc_tls_certificate_distributor_test.cc#L101)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please declare this as `override`.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 106 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGEJEMo01kmIItgc0Sd:-MGElWYsDPfAWJEAegjT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f6f12dc2c33f68f2dbc86cd91/test/core/security/grpc_tls_certificate_distributor_test.cc#L106)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`grpc_tls_certificate_distributor::PemKeyCertPairList updated_identity;`
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 111 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGEJLBkBtWhb6MbGydR:-MGElmu94h3wV5Bon03b:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f6f12dc2c33f68f2dbc86cd91/test/core/security/grpc_tls_certificate_distributor_test.cc#L111)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can use `std::move()` for `updated_identity`.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 114 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGEJ7vd3uzOcROMQP5s:-MGElnnm28rajRjlpBCf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f6f12dc2c33f68f2dbc86cd91/test/core/security/grpc_tls_certificate_distributor_test.cc#L114)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please declare this as `override`.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 144 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGEJ_KI4E5SFmFy2V9Z:-MGEnEwbD-mM_WCo5Klf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f6f12dc2c33f68f2dbc86cd91/test/core/security/grpc_tls_certificate_distributor_test.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why not just make these parameters `absl::optional<>`?  That way, there's no need to convert them below; they can be passed directly to `WatchTlsCertificates()` as-is.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 169 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGEJsKM0N0NCPX6Po46:-MGEnOwK-pLlLdn9GETN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f6f12dc2c33f68f2dbc86cd91/test/core/security/grpc_tls_certificate_distributor_test.cc#L169)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add `of std::vector<>`.  Otherwise, it's not clear what the comment is referring to.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 232 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGEKPAp9JqdZlGs9fnQ:-MGF07gr4tstjHOEi6m2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f6f12dc2c33f68f2dbc86cd91/test/core/security/grpc_tls_certificate_distributor_test.cc#L232)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In general, whenever you are listing every element of the array in literal form (as opposed to dynamically constructing the list), it's easier to use `ElementsAre()` than `ElementsAreArray()`.  This can be written as:

```
testing::ElementsAre(
    CredentialInfo(kRootCert1Contents,
                   MakeCertKeyPairs(kIdentityCert1PrivateKey,
                                    kIdentityCert1Contents)))
```

Same thing throughout.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 260 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGELgSWAt4y4-u9dmaD:-MGFI0a75wCacAOkO0U8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f [...]

2020-09-03 18:07 UTC, markdroth requested changes
This looks really good!  The only really significant issue remaining is the one about using `std::string` instead of `absl::string_view` in `CertificateInfo`, so that the cache has its own copy of the data.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23572#-:-MGK8QbiBVAu3_GPBMQJ:bdta5vs)* status: all files reviewed, 14 unresolved discussions (waiting on @jiangtaoli2016, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 169 at r12](https://reviewable.io/reviews/grpc/grpc/23572#-MGJt7slD0Q8lS_C4gIR:-MGJt7slD0Q8lS_C4gIS:bxavuet) ([raw file](https://github.com/grpc/grpc/blob/5ac1c790cfff7a79577a68bd0c4c357eb012addb/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L169)):*
> ```objc
>   struct CertificateInfo {
>     // The contents of the root certificates.
>     absl::optional<absl::string_view> pem_root_certs;
> ```

Doesn't this need to use `std::string` instead of `absl::string_view`?  Otherwise, the distributor is not actually caching the data; it's just caching a pointer to data that the provider needs to keep alive.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 85 at r9](https://reviewable.io/reviews/grpc/grpc/23572#-MFqzY8T0X60gbORuxf3:-MGJrSsl-0AQK-l3A5jo:b-nvz4sc) ([raw file](https://github.com/grpc/grpc/blob/ac0cbc1659c6d56fc4014938fbc342d8b472e67d/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L85)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

SG. I also made function `SetKeyMaterials` taking  absl::optional parameters here, so that we don't need three functions for setting key materials. 
</blockquote></details>

I like the change to `SetKeyMaterials()`!  That makes things much simpler and more consistent.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 189 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGEHWmn2lZDRZ03-54d:-MGJssXb4Z1qpGeAcj7d:b-6wks7j) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f6f12dc2c33f68f2dbc86cd91/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L189)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I added this line because the `CertificateInfo` currently combines all the information, and sometimes for example we are inserting a certInfo entry for the `root_cert_error` field, the `pem_root_certs` and `pem_key_cert_pairs` fields will be initiated as well, though currently we don't have any credential available yet. In these cases, the `updated_root_certs` and `updated_identity_pairs` will be zero values, and hence I added this line here.
I also think it's not a good idea to assume "no credential provided" equals to "credential provided with size of 0". The best way I can think of is to add absl::optional around `pem_root_certs` and `pem_key_cert_pairs` in `CertificateInfo`, but we still need to check `updated_root_certs.has_value() || updated_identity_pairs.has_value()` here. Does this look better to you?
</blockquote></details>

I don't necessarily object to using `absl::optional<>` in `CertificateInfo`, although it's not strictly necessary.  Instead, we could have just changed the code above that says this:

```
updated_root_certs = cert_info.pem_root_certs;
```

to instead say this:

```
if (!cert_info.pem_roor_certs.empty()) {
  updated_root_certs = cert_info.pem_root_certs;
}
```

And do a similar thing for `updated_identity_pairs`.  I think that would have accomplished the same thing.

But I'm also fine with the way you have this now.  It does perhaps make the logic a little easier to follow if we use `absl::optional<>` everywhere.

---

Let's take a step back here for a moment to discuss the design considerations that might affect whether or not we decide to use `absl::optional<>`.

First, my understanding is that zero values (i.e., the root cert string being empty or the key/cert pair list being empty) are invalid, meaning that there are no valid use-cases where a provider would give us those values and expect them to actually be used.  Assuming that's correct, then we could actually use those zero values to determine if either field is unset.  In principle, this means that we never need to use `absl::optional<>` for these fields, because we can just use the zero value to indicate that the cert data is not present.  However, this is not necessarily the most intuitive representation, and it could cause problems, as we'll see in a moment.

It's worth noting that there are two different contexts in which we can make the decision about whether or not to use `absl::optional<>`: the API (i.e., the parameters for `SetKeyMaterials()` and the watcher's `OnCertificatesChanged()` method) and the underlying data structure (i.e., the fields in `CertificateInfo`).  We don't necessarily have to make the same decision in both places.

In the API, clarity is particularly important, because it will wind up being used by many different caller implementations.  (The top-side API will be used by every provider implementation, and the bottom-side API will be used in at least two places, the security connector code and the xDS code.)  There are a few different things that the API might need to be able to express:

- "Here is valid data for this field."
- "I am not specifying this at all, so please retain whatever value I gave you previously."
- "I am explicitly unsetting this."

That last one is not something we actually need to do right now, but I could imagine cases where it might be needed in the future.  But even for the second one, using an empty value might be a little confusing, whereas an unset `absl::optional<>` makes it very clear.  And it also provides a path for adding the last one if we need it later (i.e., we could set the `absl::optional<>` to contain an empty value).  So in this context, I think it makes complete sense to use `absl::optional<>`.

In the underlying data structure, however, there are really only two states we care about: set and unset.  In addition, while clarity is certainly never a bad thing, it also isn't strictly as important as in the API, because this is purely an internal implementation detail: it's something we can easily change later without affecting any external users of either the top-side or bottom-side API.  So in this context, I don't think it's quite as important to use `absl::optional<>`; instead, we could just treat the empty values as unset.  But there also isn't a huge cost to using `absl::optional<>`, so I don't object to doing so.

So, like I said, this is not strictly necessary, but it's also fine to leave it as-is.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 36 at r12](https://reviewable.io/reviews/grpc/grpc/23572#-MGJs-3YBDz9YsRixF4-:-MGJs-3YBDz9YsRixF40:bgznx8k) ([raw file](https://github.com/grpc/grpc/blob/5ac1c790cfff7a79577a68bd0c4c357eb012addb/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L36)):*
> ```cpp
>   bool identity_updated = pem_key_cert_pairs.has_value();
>   if (root_updated) {
>     cert_info.pem_root_certs = pem_root_certs;
> ```

How about moving these into the blocks below, to be consistent with how we're doing this in `SetErrorForCert()`?
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 43 at r12](https://reviewable.io/reviews/grpc/grpc/23572#-MGJs9I_9xGrtQ7-j1WG:-MGJs9I_9xGrtQ7-j1WH:b-gl1d8d) ([raw file](https://github.com/grpc/grpc/blob/5ac1c790cfff7a79577a68bd0c4c357eb012addb/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L43)):*
> ```cpp
>   // Go through each affected watchers and invoke OnCertificatesChanged.
>   if (root_updated) {
>     cert_info.SetRootError(GRPC_ERROR_NONE);
> ```

Please add a comment here indicating [...]

2020-09-03 21:17 UTC, ZhenLian reviewed
SG! Regarding to that issue, I have some follow-up questions and I directly replied to the comment. Can you please take a look at that? I will resolve other comments at the same time.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23572#-:-MGKoURq-pf2mucLCZAW:b-ye57q0)* status: all files reviewed, 14 unresolved discussions (waiting on @jiangtaoli2016, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 169 at r12](https://reviewable.io/reviews/grpc/grpc/23572#-MGJt7slD0Q8lS_C4gIR:-MGKWvlj9HNUBxTUQjJo:b9yw0on) ([raw file](https://github.com/grpc/grpc/blob/5ac1c790cfff7a79577a68bd0c4c357eb012addb/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L169)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't this need to use `std::string` instead of `absl::string_view`?  Otherwise, the distributor is not actually caching the data; it's just caching a pointer to data that the provider needs to keep alive.
</blockquote></details>

I've talked with @jiangtaoli2016 about this before. Our goal here is to only have one copy of the data inside the core, since sometimes the credential data size can be large and it might be expensive to copy it around. Our assumption is that we have to do at least one copy at the core interface(we used to receive some feedback from Dropbox asking us to not make ownership transfer on the Core API, so that callers could control the lifetime of their own managed data). 

Our original idea was to leave the copied credential at the place where it was, and to use absl::string_view in places like distributor, security connector, etc. However,  since the distributor is actually caching the data, I think it's a good idea to transfer the ownership once the credential get copied on the core API surface. Would change it to a `std::unique_ptr<std::string>`(and the parameter in `SetKeyMaterials` would be `absl::optional<std::unique_ptr<std::string>>`) be a good idea(so that we are explicitly saying we need to acquire the ownership of the credential)?

Also I want to confirm the `PemKeyCertPairList` side as well. Since internally the private key and cert chains are stored in unique pointer already, there is no need to make the whole list unique, right(because copying around the list itself without data wouldn't be that expensive)? 


<!-- Sent from Reviewable.io -->

2020-09-03 22:13 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23572)* status: all files reviewed, 14 unresolved discussions (waiting on @jiangtaoli2016, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 169 at r12](https://reviewable.io/reviews/grpc/grpc/23572#-MGJt7slD0Q8lS_C4gIR:-MGL-7QuAPLWH1_1RADR:b-5zcjvi) ([raw file](https://github.com/grpc/grpc/blob/5ac1c790cfff7a79577a68bd0c4c357eb012addb/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L169)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I've talked with @jiangtaoli2016 about this before. Our goal here is to only have one copy of the data inside the core, since sometimes the credential data size can be large and it might be expensive to copy it around. Our assumption is that we have to do at least one copy at the core interface(we used to receive some feedback from Dropbox asking us to not make ownership transfer on the Core API, so that callers could control the lifetime of their own managed data). 

Our original idea was to leave the copied credential at the place where it was, and to use absl::string_view in places like distributor, security connector, etc. However,  since the distributor is actually caching the data, I think it's a good idea to transfer the ownership once the credential get copied on the core API surface. Would change it to a `std::unique_ptr<std::string>`(and the parameter in `SetKeyMaterials` would be `absl::optional<std::unique_ptr<std::string>>`) be a good idea(so that we are explicitly saying we need to acquire the ownership of the credential)?

Also I want to confirm the `PemKeyCertPairList` side as well. Since internally the private key and cert chains are stored in unique pointer already, there is no need to make the whole list unique, right(because copying around the list itself without data wouldn't be that expensive)? 
</blockquote></details>

I don't think it makes sense for the caller to control the lifetime of their data in this API, because as you point out, the distributor controls how long the data is cached for.  It will be automatically removed when none of the watchers need it anymore.

Using `absl::string_view` here puts the burden on the provider to maintain the object for as long as the distributor needs it, effectively requiring it to be cached twice.  And it does not actually give the provider any more control over the lifetime, because it cannot destroy the underlying data while the distributor still thinks it has the data cached; this would cause a use-after-free bug when the distributor tries to access the data.

Note that `grpc_core::PemKeyCertPair` stores the data directly internally, so we are already making a copy of the identity key/cert pairs.  We should do the same thing for the root cert, which is what I'm suggesting.

All you need to do here is use `absl::optional<std::string>` instead of `absl::optional<absl::string_view>` here in `CertificateInfo`.  We do not need to use `std::unique_ptr<>` in either case, because neither of these objects are dynamically allocated by the caller.  Both `std::string` and `absl::InlinedVector<>` do dynamic allocation internally.

Copies are expensive, which is why we use `std::move()` all over the place.  Moves are much cheaper than copies for most objects, because they can just hand off the internally-allocated memory.


<!-- Sent from Reviewable.io -->

2020-09-06 16:59 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23572)* status: all files reviewed, 14 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @yashykt)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 169 at r12](https://reviewable.io/reviews/grpc/grpc/23572#-MGJt7slD0Q8lS_C4gIR:-MGLTObu0fMrxK-LIMP_:b-dmm3zn) ([raw file](https://github.com/grpc/grpc/blob/5ac1c790cfff7a79577a68bd0c4c357eb012addb/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L169)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think it makes sense for the caller to control the lifetime of their data in this API, because as you point out, the distributor controls how long the data is cached for.  It will be automatically removed when none of the watchers need it anymore.

Using `absl::string_view` here puts the burden on the provider to maintain the object for as long as the distributor needs it, effectively requiring it to be cached twice.  And it does not actually give the provider any more control over the lifetime, because it cannot destroy the underlying data while the distributor still thinks it has the data cached; this would cause a use-after-free bug when the distributor tries to access the data.

Note that `grpc_core::PemKeyCertPair` stores the data directly internally, so we are already making a copy of the identity key/cert pairs.  We should do the same thing for the root cert, which is what I'm suggesting.

All you need to do here is use `absl::optional<std::string>` instead of `absl::optional<absl::string_view>` here in `CertificateInfo`.  We do not need to use `std::unique_ptr<>` in either case, because neither of these objects are dynamically allocated by the caller.  Both `std::string` and `absl::InlinedVector<>` do dynamic allocation internally.

Copies are expensive, which is why we use `std::move()` all over the place.  Moves are much cheaper than copies for most objects, because they can just hand off the internally-allocated memory.
</blockquote></details>

SG! I also made the parameter in `SetKeyMaterials` to  `std::string`. Now the only API taking `absl::string_view` is `OncertificatesChanged`, which notifies watchers about the credential updates. Let me know if this change looks good, thanks!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 189 at r11](https://reviewable.io/reviews/grpc/grpc/23572#-MGEHWmn2lZDRZ03-54d:-MGLSMhD8ZBB2taaxEPD:bfee6qk) ([raw file](https://github.com/grpc/grpc/blob/4eddfcbcff2d566f6f12dc2c33f68f2dbc86cd91/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L189)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't necessarily object to using `absl::optional<>` in `CertificateInfo`, although it's not strictly necessary.  Instead, we could have just changed the code above that says this:

```
updated_root_certs = cert_info.pem_root_certs;
```

to instead say this:

```
if (!cert_info.pem_roor_certs.empty()) {
  updated_root_certs = cert_info.pem_root_certs;
}
```

And do a similar thing for `updated_identity_pairs`.  I think that would have accomplished the same thing.

But I'm also fine with the way you have this now.  It does perhaps make the logic a little easier to follow if we use `absl::optional<>` everywhere.

---

Let's take a step back here for a moment to discuss the design considerations that might affect whether or not we decide to use `absl::optional<>`.

First, my understanding is that zero values (i.e., the root cert string being empty or the key/cert pair list being empty) are invalid, meaning that there are no valid use-cases where a provider would give us those values and expect them to actually be used.  Assuming that's correct, then we could actually use those zero values to determine if either field is unset.  In principle, this means that we never need to use `absl::optional<>` for these fields, because we can just use the zero value to indicate that the cert data is not present.  However, this is not necessarily the most intuitive representation, and it could cause problems, as we'll see in a moment.

It's worth noting that there are two different contexts in which we can make the decision about whether or not to use `absl::optional<>`: the API (i.e., the parameters for `SetKeyMaterials()` and the watcher's `OnCertificatesChanged()` method) and the underlying data structure (i.e., the fields in `CertificateInfo`).  We don't necessarily have to make the same decision in both places.

In the API, clarity is particularly important, because it will wind up being used by many different caller implementations.  (The top-side API will be used by every provider implementation, and the bottom-side API will be used in at least two places, the security connector code and the xDS code.)  There are a few different things that the API might need to be able to express:

- "Here is valid data for this field."
- "I am not specifying this at all, so please retain whatever value I gave you previously."
- "I am explicitly unsetting this."

That last one is not something we actually need to do right now, but I could imagine cases where it might be needed in the future.  But even for the second one, using an empty value might be a little confusing, whereas an unset `absl::optional<>` makes it very clear.  And it also provides a path for adding the last one if we need it later (i.e., we could set the `absl::optional<>` to contain an empty value).  So in this context, I think it makes complete sense to use `absl::optional<>`.

In the underlying data structure, however, there are really only two states we care about: set and unset.  In addition, while clarity is certainly never a bad thing, it also isn't strictly as important as in the API, because this is purely an internal implementation detail: it's something we can easily change later without affecting any external users of either the top-side or bottom-side API.  So in this context, I don't think it's quite as important to use `absl::optional<>`; instead, we could just treat the empty values as unset.  But there also isn't a huge cost to using `absl::optional<>`, so I don't object to doing so.

So, like I said, this is not strictly necessary, but it's also fine to leave it as-is.
</blockquote></details>

This all makes a lot of sense! I don't have a preference over the two, so I will change it back to the implementation which internally stores credential without `absl::optional<>`.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 36 at r12](https://reviewable.io/reviews/grpc/grpc/23572#-MGJs-3YBDz9YsRixF4-:-MGL5AhP2wbq9cwQ8mvs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5ac1c790cfff7a79577a68bd0c4c357eb012addb/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about moving these into the blocks below, to be consistent with how we're doing this in `SetErrorForCert()`?
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 43 at r12](https://reviewable.io/reviews/grpc/grpc/23572#-MGJs9I_9xGrtQ7-j1WG:-MGL5l1--0AW6MMWCSTG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5ac1c790cfff7a79577a68bd0c4c357eb012addb/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment here indicating that setting the cert data implies clearing any pre-existing error.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 63 at r12](https://reviewable.io/reviews/grpc/grpc/23572#-MGJsF3p5o_VMutkW5-i:-MGL5lOLCn4QWa88nMZP:b-89 [...]

2020-09-08 15:24 UTC, markdroth approved these changes
This looks fantastic!  Just one minor nit to fix before you merge.

Please remember to squash commits and flag any known issues before merging.

Thanks!

> Reviewed 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23572#-:-MGiJ7ua9rvQrgEGX0I_:b-d10spu)* status: all files reviewed, 3 unresolved discussions (waiting on @jiangtaoli2016, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 169 at r12](https://reviewable.io/reviews/grpc/grpc/23572#-MGJt7slD0Q8lS_C4gIR:-MGiG-VpBnAY5QKwEeLX:bff5zjv) ([raw file](https://github.com/grpc/grpc/blob/5ac1c790cfff7a79577a68bd0c4c357eb012addb/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L169)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

SG! I also made the parameter in `SetKeyMaterials` to  `std::string`. Now the only API taking `absl::string_view` is `OncertificatesChanged`, which notifies watchers about the credential updates. Let me know if this change looks good, thanks!
</blockquote></details>

This looks good!
___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 59 at r13](https://reviewable.io/reviews/grpc/grpc/23572#-MGiHKqN2kaTxB6r_wCw:-MGiHKqN2kaTxB6r_wCx:b-ta6ra7) ([raw file](https://github.com/grpc/grpc/blob/fa9a813b213e3733ff69a226e5e19380ba6c8055/test/core/security/grpc_tls_certificate_distributor_test.cc#L59)):*
> ```cpp
>       const char* private_key, const char* certs) {
>     if (strcmp(private_key, "") == 0 && strcmp(certs, "") == 0) {
>       return grpc_tls_certificate_distributor::PemKeyCertPairList();
> ```

I think this can just say `return {}`.


<!-- Sent from Reviewable.io -->

2020-09-08 17:36 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23572)* status: all files reviewed, 3 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @yashykt)

___
*[test/core/security/grpc_tls_certificate_distributor_test.cc, line 59 at r13](https://reviewable.io/reviews/grpc/grpc/23572#-MGiHKqN2kaTxB6r_wCw:-MGimYFuDbyqVGOEfqma:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fa9a813b213e3733ff69a226e5e19380ba6c8055/test/core/security/grpc_tls_certificate_distributor_test.cc#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can just say `return {}`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-08 21:09 UTC, ZhenLian reviewed
Done with the squash and all checks passed! I will merge the changes now. Thanks again for the review!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23572#-:-MGjYANh2jAKGaAi3_nn:b7ug5ro)* status: 4 of 21 files reviewed, 3 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @yashykt)



<!-- Sent from Reviewable.io -->

2020-09-08 21:20 UTC, ZhenLian reviewed
@jiangtaoli2016 @markdroth 
It seems there are still comments marked as unresolved and I couldn't merge this PR right now. I think they are all fixed. Could you please take a look at those unresolved comments and see if they can be marked as resolved please? Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23572#-:-MGj_8mpCAUE_zrVTQTh:bktb3jg)* status: 3 of 21 files reviewed, 3 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @yashykt)



<!-- Sent from Reviewable.io -->

2020-09-08 21:22 UTC, markdroth approved these changes
I've already marked this as approved.  @jiangtaoli2016 has it marked as requiring changes.  He can either approve, or you can tell github to disregard his review.

> Reviewed 1 of 3 files at r13, 17 of 17 files at r14.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23572#-:-MGja7QE0odL3stZjvLY:biyhk0v)* status: all files reviewed, 2 unresolved discussions (waiting on @jiangtaoli2016 and @yashykt)



<!-- Sent from Reviewable.io -->

2020-09-09 01:02 UTC, jiangtaoli2016 approved these changes
Looks great! Thanks @ZhenLian for implementation. Thanks @markdroth for thorough reviews.

2020-09-09 06:28 UTC, merged