Moving XDS Routing functionalities from LB policy into XdsConfigSelector
grpc/grpc pull request #23659
Opened 2020-07-28 22:49 UTC by donnadionne

@markdroth

2020-09-03 10:30 UTC, donnadionne reviewed
Got new test working: ClusterState destructed due to on_call_committed unrefing it  to 0.  Cleaned up code and separated out the test into another PR (to be submitted before this one)

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGIViZj9LcrBZr0H0-r:b-98lth9)* status: 8 of 10 files reviewed, 28 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc, line 58 at r5](https://reviewable.io/reviews/grpc/grpc/23659#-MFWUttTAgwR-WBdgWW8:-MGIV_ZQ-ngH14fzQVOD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/61b5d2c47a1dd86a5508efb46bc7d216a1baaf13/src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's use `XdsClusterManagerLb` and xds_cluster_manager.cc.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc, line 222 at r5](https://reviewable.io/reviews/grpc/grpc/23659#-MFWW08O34hX5HZ18KRO:-MG5WDET1Ak1yCYPs29W:b6y0jj3) ([raw file](https://github.com/grpc/grpc/blob/61b5d2c47a1dd86a5508efb46bc7d216a1baaf13/src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc#L222)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In the future, please share the entire TSAN error, because the one line you shared doesn't give me enough information to figure out what's actually happening here.  If the output is too long for a comment, you can always use paste.googleplex.com and point me at it there.

I can't tell where this problem was being triggered, but I'm going to guess that it was in the `ClusterPicker` dtor.   C++ data members get destroyed in the order in which they are declared, which means that `cluster_name_storage_` would be destroyed before `cluster_map_`, which means that the keys would be invalid by the time it goes to destroy `cluster_map_`.  If you declared `cluster_name_storage_` after `cluster_map_` instead of before it, that would probably solve the problem.

That having been said, if the `absl::string_view` keys that are being passed in already have the right lifetime, then there's no need for `cluster_name_storage_` in the first place (and indeed, the way you have this code now, it's not actually being used at all).  Let's just get rid of it and initialize `cluster_map_` directly from the input parameter in the initializer list.
</blockquote></details>

for this PR I am going to ensure cluster_map keys will outlive the Picker; I am still trying to figure out why we got that crash using cluster_name_stroage_ (may be useful for other code I may need to write).  Here is the link to the TSAN error: https://paste.googleplex.com/5698600589852672 if you have a min to take a look.  I did switch the member var declare order but it didn't help.  The problem is the compare we are doing when using the [] operator. but it's not obvious to me why there would be an issue!
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc, line 113 at r15](https://reviewable.io/reviews/grpc/grpc/23659#-MG476Go6o85ARyV4xf9:-MG5SZih7raWY5Hp--kB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6bbdc9e5b93548d949c0fef3169bc88e32bd22f7/src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc#L113)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment documenting that the caller must ensure that the keys of `cluster_map` will live at least as long as the picker does (e.g., by being pointers into `config`).
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc, line 221 at r15](https://reviewable.io/reviews/grpc/grpc/23659#-MG44tXwEGSkhiMO-bts:-MG6BiwtD0YMSIdSwU8N:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6bbdc9e5b93548d949c0fef3169bc88e32bd22f7/src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc#L221)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please rename this to `children_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc, line 357 at r15](https://reviewable.io/reviews/grpc/grpc/23659#-MG44gcwDK60EM-uPk05:-MG6BqI4E8j3TYj8MtXd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6bbdc9e5b93548d949c0fef3169bc88e32bd22f7/src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc#L357)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `p` instead of `action`, since this is a pair.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc, line 368 at r15](https://reviewable.io/reviews/grpc/grpc/23659#-MG4518Q3HzGyMEVsuF5:-MG6TIvl3OiMeif4BrJi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6bbdc9e5b93548d949c0fef3169bc88e32bd22f7/src/core/ext/filters/client_channel/lb_policy/xds/xds_routing.cc#L368)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There is no need to use the picker name here.  We can just use `action.first` directly, since the picker is taking a ref to the config, which means that we know those strings will have the same lifetime as the picker.

Suggest writing this as:

```
RefCountedPtr<ChildPickerWrapper>& picker = cluster_map[action.first];
child_picker = actions_[action.first]->picker_wrapper();
if (child_picker == nullptr) {
  // ...trace logging...
  child_picker = MakeRefCounted<ChildPickerWrapper>(
      action.first, absl::make_unique<QueuePicker>(
           Ref(DEBUG_LOCATION, "QueuePicker")));
}
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 54 at r5](https://reviewable.io/reviews/grpc/grpc/23659#-MFWsDd03GhOGKCEWtgB:-MG6TelG9LtcmRjioqqV:b-5wfh36) ([raw file](https://github.com/grpc/grpc/blob/61b5d2c47a1dd86a5508efb46bc7d216a1baaf13/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this was done.
</blockquote></details>

moved to the right spot now
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 111 at r15](https://reviewable.io/reviews/grpc/grpc/23659#-MG4LmXj0Vxbid0OSm2-:-MG5qXQt3pyKjc7RmCvl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6bbdc9e5b93548d949c0fef3169bc88e32bd22f7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L111)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two types can be private.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 113 at r15](https://reviewable.io/reviews/grpc/grpc/23659#-MG4IpdH4V84UEffk_3X:-MG67zY58gDffCJK6qjE:b9uc5pz) ([raw file](https://github.com/grpc/grpc/blob/6bbdc9e5b93548d949c0fef3169bc88e32bd22f7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L113)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can use `absl::string_view` instead of `std::string`.
</blockquote></details>

sure, i'll just have to make sure we use the string in ClusterState
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 121 at r15](https://reviewable.io/reviews/grpc/grpc/23659#-MG4AtrX6WhinWXAQ9z-:-MG5r7F7EhCJcAHeErTU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6bbdc9e5b93548d949c0fef3169bc88e32bd22f7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L121)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two methods can be private.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 153 at r15](https://reviewable.io/r [...]

2020-09-03 16:10 UTC, markdroth requested changes
This is getting closer!

It looks like there are some conflicts, so you may need to merge master to resolve them.

Please let me know if you have any questions.  Thanks!

> Reviewed 22 of 22 files at r20.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGJi3FD587IZ4NegX9x:b-mqp62i)* status: all files reviewed, 29 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[BUILD, line 1745 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJWCpv2rTT8iaTdtRv:-MGJWCpv2rTT8iaTdtRw:b70bjga) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/BUILD#L1745)):*
> ```Starlark
>     ],
> )
> grpc_cc_library(
> ```

Please add a blank line before this one.
___
*[BUILD, line 1760 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJXj3DCovplIDXwYA-:-MGJXj3DCovplIDXwYA0:bcsdjpm) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/BUILD#L1760)):*
> ```Starlark
>     language = "c++",
>     external_deps = [
>         "absl/functional:bind_front",
> ```

I don't think this is needed anymore.
___
*[BUILD, line 1776 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJXkKn7-qdYu0NqX0e:-MGJXkKn7-qdYu0NqX0f:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/BUILD#L1776)):*
> ```Starlark
>     language = "c++",
>     external_deps = [
>         "absl/functional:bind_front",
> ```

Same here.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 113 at r15](https://reviewable.io/reviews/grpc/grpc/23659#-MG4IpdH4V84UEffk_3X:-MGJWmwR4wsbZxy4MXR2:b3t2buu) ([raw file](https://github.com/grpc/grpc/blob/6bbdc9e5b93548d949c0fef3169bc88e32bd22f7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L113)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

sure, i'll just have to make sure we use the string in ClusterState
</blockquote></details>

This does not need to use the string in `ClusterState`; it's fine to use the string in the `route` field of this struct, since it will have the same lifetime.

I've added a comment below about how to do this.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 21 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJbVs56NvKZstOk1o_:-MGJbVs56NvKZstOk1oa:b-mbwbw7) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L21)):*
> ```cpp
> #include <grpc/support/port_platform.h>
> 
> #include "absl/functional/bind_front.h"
> ```

This doesn't appear to be used.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 76 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJbdFP74Yo5iad3yKJ:-MGJbdFP74Yo5iad3yKK:b-wf3w2f) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L76)):*
> ```cpp
>   }
> 
>   void OnListenerChanged(XdsApi::LdsUpdate listener_data);
> ```

These methods can all be private.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 153 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJXAdpBY3TujJQpdSZ:-MGJXAdpBY3TujJQpdS_:b-bnlckg) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L153)):*
> ```cpp
>   resolver_->OnListenerChanged(listener_data);
> 
>   // Progapage the update by creating XdsConfigSelector, CreateServiceConfig,
> ```

s/Progapage/Propagate/
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 155 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJXGdn1LRGjmsNxuss:-MGJXGdn1LRGjmsNxust:b-hcro5c) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L155)):*
> ```cpp
>   // Progapage the update by creating XdsConfigSelector, CreateServiceConfig,
>   // and ReturnResult.
>   resolver_->PropagateUpdate(*listener_data.rds_update);
> ```

This can be moved into `XdsResolver::OnListenerChanged()`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 162 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJXVA72fHJf4Hla8IO:-MGJXVA72fHJf4Hla8IP:bk20lsz) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L162)):*
> ```cpp
>   gpr_log(GPR_ERROR, "[xds_resolver %p] received error: %s", resolver_.get(),
>           grpc_error_string(error));
>   grpc_arg xds_client_arg = resolver_->xds_client_->MakeChannelArg();
> ```

This should just call `resolver_->OnError(error)` rather than duplicating the code.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 184 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJbr6i7LeI7kMMm8aD:-MGJbr6i7LeI7kMMm8aE:b-358ffx) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L184)):*
> ```cpp
> }
> 
> ///
> ```

Only need two slashes on each of these lines.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 203 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJY6tD-imDqW_vR2R2:-MGJY6tD-imDqW_vR2R3:b-4jrbsn) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L203)):*
> ```cpp
>     } else {
>       uint32_t end = 0;
>       for (const auto& weighted_cluster : route.weighted_clusters) {
> ```

If you change this to loop over `route_entry.route.weighted_clusters` (the copy we just made above), then you can change line 207 from `clusters_[weighted_cluster.name]->cluster()` to just `weighted_cluster.name`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 214 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJYV6ZBneJGWiSBaUF:-MGJYV6ZBneJGWiSBaUG:b-v843xm) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L214)):*
> ```cpp
> 
> XdsResolver::XdsConfigSelector::~XdsConfigSelector() {
>   // No need to call Unref, its automatic with the destructor
> ```

s/its/it's/

What does this comment actually mean?  Which ref are you talking about?
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 397 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJZF-R0Dp39p3N-s9p:-MGJZF-R0Dp39p3N-s9q:b61kfoi) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L397)):*
> ```cpp
>     CallConfig call_config;
>     call_config.call_attributes[kXdsClusterAttribute] = it->first;
>     call_config.on_call_committed = [resolver_ref = std::move(resolver_ref),
> ```

Unfortunately, we can't use `std::move()` lambda captures, because those were introduced in (I believe) C++14, and we can only use C++11 here.  Instead, we'll need to track this ref manually, just like we're doing with `cluster_state`.

(Also, holding a ref in a pre-bound lambda parameter isn't exactly what we want anyway, because it will hold an unnecessary ref in the lambda itself, which will outlive the callback.)
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 401 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJ_R6YA0M27yLpvefX:-MGJ_R6YA0M27yLpvefY:b99bmle) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L401)):*
> ```cpp
>       cluster_state->Unref();
>       XdsResolver* resolver = resolver_ref.get();
>       ExecCtx::Run(
> ```

Please add th [...]

2020-09-08 07:04 UTC, donnadionne reviewed
merged and fixed code review comments

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGgWoQX7tQLb5t5-KyC:b-3lue37)* status: 7 of 25 files reviewed, 29 unresolved discussions (waiting on @markdroth)

___
*[BUILD, line 1745 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJWCpv2rTT8iaTdtRv:-MGfvoKxCd60RLMQzLtX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/BUILD#L1745)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a blank line before this one.
</blockquote></details>

Done.
___
*[BUILD, line 1760 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJXj3DCovplIDXwYA-:-MGfeKCL7CYHBWUEpYhb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/BUILD#L1760)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is needed anymore.
</blockquote></details>

Done.
___
*[BUILD, line 1776 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJXkKn7-qdYu0NqX0e:-MGfeMofBo3h75YZLm67:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/BUILD#L1776)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 21 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJbVs56NvKZstOk1o_:-MGfmPkL7zKER2xOJfJQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L21)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't appear to be used.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 76 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJbdFP74Yo5iad3yKJ:-MGgHZICEwFtL4-wu8wj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L76)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These methods can all be private.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 153 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJXAdpBY3TujJQpdSZ:-MGfqc1U5PmUr3MgmeVc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L153)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/Progapage/Propagate/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 155 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJXGdn1LRGjmsNxuss:-MGfsrBOBYpkXlPmCjSC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L155)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be moved into `XdsResolver::OnListenerChanged()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 162 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJXVA72fHJf4Hla8IO:-MGftbk27uaBLB-eeTKA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L162)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should just call `resolver_->OnError(error)` rather than duplicating the code.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 184 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJbr6i7LeI7kMMm8aD:-MGftmeW75Mj1Ag_Fb5K:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L184)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Only need two slashes on each of these lines.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 203 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJY6tD-imDqW_vR2R2:-MGfuLafCL5zHMXHLegI:b2owqnq) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L203)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you change this to loop over `route_entry.route.weighted_clusters` (the copy we just made above), then you can change line 207 from `clusters_[weighted_cluster.name]->cluster()` to just `weighted_cluster.name`.
</blockquote></details>

weird, this triggered the assert on line 
auto it = clusters_.find(cluster_name);
    GPR_ASSERT(it != clusters_.end());
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 214 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJYV6ZBneJGWiSBaUF:-MGfuh0y9DUF14wNczrz:b-b4kkc7) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L214)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/its/it's/

What does this comment actually mean?  Which ref are you talking about?
</blockquote></details>

it was just a reminder, i will remove
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 397 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJZF-R0Dp39p3N-s9p:-MGgPzhY4-88-ykpHZGK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L397)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Unfortunately, we can't use `std::move()` lambda captures, because those were introduced in (I believe) C++14, and we can only use C++11 here.  Instead, we'll need to track this ref manually, just like we're doing with `cluster_state`.

(Also, holding a ref in a pre-bound lambda parameter isn't exactly what we want anyway, because it will hold an unnecessary ref in the lambda itself, which will outlive the callback.)
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 401 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJ_R6YA0M27yLpvefX:-MGgJFFU46asU58bbJqM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L401)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add the following comment here:

TODO(roth): This hop into the ExecCtx is being done to avoid entering the WorkSerializer while holding the client channel data plane mutex, since that can lead to deadlocks.  However, we should not have to solve this problem in each individual ConfigSelector implementation.  When we have time, we should fix the client channel code to avoid this by not invoking the CallConfig::on_call_committed callback until after it has released the data plane mutex.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 475 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJaQq_AljAr3Jj9DXg:-MGfvOpwBbowiYQVvBUY:b1pexjm) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core [...]

2020-09-08 17:11 UTC, markdroth requested changes
This is getting close!

Please let me know if you have any questions.  Thanks!

> Reviewed 7 of 19 files at r21, 17 of 18 files at r22.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGiggy8CuvJV3MwW0jG:bwk52h1)* status: all files reviewed, 9 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 203 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJY6tD-imDqW_vR2R2:-MGifzzv8Tu_kRw2mf7J:b-w3pqx3) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L203)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

weird, this triggered the assert on line 
auto it = clusters_.find(cluster_name);
    GPR_ASSERT(it != clusters_.end());
</blockquote></details>

I bet this is caused by `std::vector<>` reallocating its internal storage as we add elements.  Try adding this line before the start of the loop:

```
route_table_.reserve(routes.size());
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 397 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJZF-R0Dp39p3N-s9p:-MGie8VD02bKB4P8MMyP:b-zfmhtj) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L397)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now you're not actually holding a ref to the resolver at all; you're just passing in a raw pointer.

You need to take the ref here by saying this:

````
XdsResolver* resolver = resolver_->Ref().release();
```

And then in the callback, you need to explicitly release it, like this:

```
resolver->Unref();
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 475 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJaQq_AljAr3Jj9DXg:-MGif2gcDrXRNQkkh9cP:bvmha5o) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L475)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

since  XdsResolver::ListenerWatcher::OnError just call this method now, leave the check and log in
</blockquote></details>

Please move the this line and the log line back to `ListenerWatcher::OnError()`.  We want this to be logged when the XdsClient reports an error, not when we call `OnError()` from `PropagateUpdate()`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 150 at r22](https://reviewable.io/reviews/grpc/grpc/23659#-MGidkRf6_iM5vL_01ng:-MGidkRf6_iM5vL_01nh:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/d7dd8fecf4aed712234c03f445f97b5d2d281cfc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L150)):*
> ```cpp
>   }
>   // Update entries in cluster state map.
>   resolver_->OnListenerChanged(routes);
> ```

`std::move()`
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 422 at r22](https://reviewable.io/reviews/grpc/grpc/23659#-MGiem8MCHXDeWStsO91:-MGiem8MCHXDeWStsO92:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/d7dd8fecf4aed712234c03f445f97b5d2d281cfc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L422)):*
> ```cpp
>   // Save the update in the resolver in case of rebuild of
>   // XdsConfigSelector.
>   current_update_ = routes;
> ```

`std::move()`
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 423 at r22](https://reviewable.io/reviews/grpc/grpc/23659#-MGievVl85O5FedTq2hd:-MGievVl85O5FedTq2he:b-idloco) ([raw file](https://github.com/grpc/grpc/blob/d7dd8fecf4aed712234c03f445f97b5d2d281cfc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L423)):*
> ```cpp
>   // XdsConfigSelector.
>   current_update_ = routes;
>   // Propagatee the update by creating XdsConfigSelector, CreateServiceConfig,
> ```

s/Propagatee/Propagate/
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 471 at r22](https://reviewable.io/reviews/grpc/grpc/23659#-MGifaCo92GO8ZPprqu8:-MGifaCo92GO8ZPprqu9:b-hjcejy) ([raw file](https://github.com/grpc/grpc/blob/d7dd8fecf4aed712234c03f445f97b5d2d281cfc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L471)):*
> ```cpp
> }
> 
> void XdsResolver::PropagateUpdate(const std::vector<XdsApi::Route>& routes) {
> ```

This method does not need the routes to be passed in; it can just directly look at `current_update_`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_manager.cc, line 52 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJfvrX7byPwTpGJqQb:-MGicyaeET0TxVigOKtu:bsdes7e) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_manager.cc#L52)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I think there may be some google3 files i need to update separately: proxyless_grpc_devcluster_test.py and proxyless_grpc_oss_test_suite_test.py, i will follow up with CLs
</blockquote></details>

I don't see the change in doc/environment_variables.md.


<!-- Sent from Reviewable.io -->

2020-09-09 05:19 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659)* status: all files reviewed, 9 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 203 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJY6tD-imDqW_vR2R2:-MGlCEZnAoQQiZ6HDH6K:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L203)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I bet this is caused by `std::vector<>` reallocating its internal storage as we add elements.  Try adding this line before the start of the loop:

```
route_table_.reserve(routes.size());
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 397 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJZF-R0Dp39p3N-s9p:-MGlF89y22lDjlCct29A:b-iluze3) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L397)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Now you're not actually holding a ref to the resolver at all; you're just passing in a raw pointer.

You need to take the ref here by saying this:

````
XdsResolver* resolver = resolver_->Ref().release();
```

And then in the callback, you need to explicitly release it, like this:

```
resolver->Unref();
```
</blockquote></details>

I tried doing the 1 liner but it gave me an error: Execution platform: @rbe_default//config:platform
src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc:369:18: error: cannot initialize a variable of type 'grpc_core::(anonymous namespace)::XdsResolver *' with an rvalue of type 'grpc_core::Resolver *'
    XdsResolver* resolver = resolver_->Ref().release();
                 ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

XdsResolver is a InternallyRefCounted<Resolver>

I think my 2 line solution is ok, get the raw pointer to be used, and take a ref to be released after done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 475 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJaQq_AljAr3Jj9DXg:-MGl2Cs-46K7W8gHd_-m:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L475)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move the this line and the log line back to `ListenerWatcher::OnError()`.  We want this to be logged when the XdsClient reports an error, not when we call `OnError()` from `PropagateUpdate()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 150 at r22](https://reviewable.io/reviews/grpc/grpc/23659#-MGidkRf6_iM5vL_01ng:-MGjq6g-7BaZ9-9ZXUwz:bb7f2mf) ([raw file](https://github.com/grpc/grpc/blob/d7dd8fecf4aed712234c03f445f97b5d2d281cfc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L150)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

done
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 422 at r22](https://reviewable.io/reviews/grpc/grpc/23659#-MGiem8MCHXDeWStsO91:-MGkyecK3icZ35Bz3xii:bb7f2mf) ([raw file](https://github.com/grpc/grpc/blob/d7dd8fecf4aed712234c03f445f97b5d2d281cfc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L422)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

done
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 423 at r22](https://reviewable.io/reviews/grpc/grpc/23659#-MGievVl85O5FedTq2hd:-MGjlb067ryZV4brq70V:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d7dd8fecf4aed712234c03f445f97b5d2d281cfc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L423)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/Propagatee/Propagate/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 471 at r22](https://reviewable.io/reviews/grpc/grpc/23659#-MGifaCo92GO8ZPprqu8:-MGl-fLc5-UiX2YBy6Qt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d7dd8fecf4aed712234c03f445f97b5d2d281cfc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L471)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This method does not need the routes to be passed in; it can just directly look at `current_update_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_manager.cc, line 52 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJfvrX7byPwTpGJqQb:-MGjlhpZ6e2eoL0fE-Qu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_manager.cc#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see the change in doc/environment_variables.md.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-09 05:46 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659)* status: all files reviewed, 9 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 397 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJZF-R0Dp39p3N-s9p:-MGlLFAYDtpukRn7yWIC:b-cqh62c) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L397)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I tried doing the 1 liner but it gave me an error: Execution platform: @rbe_default//config:platform
src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc:369:18: error: cannot initialize a variable of type 'grpc_core::(anonymous namespace)::XdsResolver *' with an rvalue of type 'grpc_core::Resolver *'
    XdsResolver* resolver = resolver_->Ref().release();
                 ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

XdsResolver is a InternallyRefCounted<Resolver>

I think my 2 line solution is ok, get the raw pointer to be used, and take a ref to be released after done.
</blockquote></details>

one line works too, i just needed to cast...  and i fixed ClusterState too


<!-- Sent from Reviewable.io -->

2020-09-09 15:17 UTC, markdroth requested changes
Just a few comments remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 16 of 16 files at r23.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGnR4L70LAkFBUDNuX6:bvc6col)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 397 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJZF-R0Dp39p3N-s9p:-MGnO6WdCCUOe0fWI9Kc:bh78q3r) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L397)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

one line works too, i just needed to cast...  and i fixed ClusterState too
</blockquote></details>

From the error message, it looks to me like you got that error when you declared the variable as `XdsResolver` instead of `XdsResolver*`.  That part looks right now, so I bet that problem will not recur.

I don't think the `static_cast<>` is actually necessary here.  You don't need it for `cluster_state`, so why would you need it for `resolver`?
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 400 at r23](https://reviewable.io/reviews/grpc/grpc/23659#-MGnO_4JB2NRDyxT-VTe:-MGnO_4JB2NRDyxT-VTf:b-1hotj2) ([raw file](https://github.com/grpc/grpc/blob/c805b053140fae921d0a49cde58ccd52b6c91238/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L400)):*
> ```cpp
>               resolver, nullptr),
>           GRPC_ERROR_NONE);
>       resolver->Unref();
> ```

This needs to go inside of the lambda.  Otherwise, we're giving up the ref to the resolver before the code that actually uses the resolver is run.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1549 at r23](https://reviewable.io/reviews/grpc/grpc/23659#-MGnP2hv-nvGk-FLbFJL:-MGnP2hv-nvGk-FLbFJM:bla17vs) ([raw file](https://github.com/grpc/grpc/blob/c805b053140fae921d0a49cde58ccd52b6c91238/test/cpp/end2end/xds_end2end_test.cc#L1549)):*
> ```cpp
>             "%d succeeded, %d failed, %d dropped.",
>             num_total, num_ok, num_failure, num_drops);
>     // Warm up failures are expected again because we chose the cluster without
> ```

I see a whole bunch of changes to this file that should not be present in this PR.  The only change to this file in this PR should be to address the TODO that you added in #24055.

If anything else needs to change, I'd like to understand why.  This is a refactoring PR, which means that test changes should in general not be necessary.


<!-- Sent from Reviewable.io -->

2020-09-10 09:04 UTC, donnadionne reviewed
A few questions remaining:
1. The XdsConfigSelector final destruction is still a bit tricky to get right: I modified client_channel.cc; let me know if you are ok with the change.
2. Some tests encountered RPC failures during cluster change, let's see if we are ok with that or we need further changes to avoid them
3. Memleaks are fixed for my new tests; however the suite still encounters some in asan runs; I'll try to narrow it down to test and debug them.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGrEX-p4gSfSN2Da2Zg:b-aqojwt)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 397 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJZF-R0Dp39p3N-s9p:-MGr6e7Z-NTMvGAYxN3E:b7dui50) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L397)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

From the error message, it looks to me like you got that error when you declared the variable as `XdsResolver` instead of `XdsResolver*`.  That part looks right now, so I bet that problem will not recur.

I don't think the `static_cast<>` is actually necessary here.  You don't need it for `cluster_state`, so why would you need it for `resolver`?
</blockquote></details>

i think i copy and pasted the incorrect error, even with XdsResolver* it did not work:src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc:397:18: error: cannot initialize a variable of type 'grpc_core::(anonymous namespace)::XdsResolver *' with an rvalue of type 'grpc_core::Resolver *'
    XdsResolver* resolver =
                 ^
I think it's because XdsResolver itself is not InternallyRefCounted; it is inherting from Resolver which is InternallyRefCounted.  So the release will return a raw pointer to Resolver, which needs to be casted
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 400 at r23](https://reviewable.io/reviews/grpc/grpc/23659#-MGnO_4JB2NRDyxT-VTe:-MGrC7--0f5lmoi0QIX1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c805b053140fae921d0a49cde58ccd52b6c91238/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L400)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to go inside of the lambda.  Otherwise, we're giving up the ref to the resolver before the code that actually uses the resolver is run.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1549 at r23](https://reviewable.io/reviews/grpc/grpc/23659#-MGnP2hv-nvGk-FLbFJL:-MGrCKk1CjyLi8Pc_sIg:b-2xm013) ([raw file](https://github.com/grpc/grpc/blob/c805b053140fae921d0a49cde58ccd52b6c91238/test/cpp/end2end/xds_end2end_test.cc#L1549)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I see a whole bunch of changes to this file that should not be present in this PR.  The only change to this file in this PR should be to address the TODO that you added in #24055.

If anything else needs to change, I'd like to understand why.  This is a refactoring PR, which means that test changes should in general not be necessary.
</blockquote></details>

so after the code changes and retesting, some tests will still have RPC failures:
XdsRoutingWeightedClusterUpdateWeights
XdsRoutingWeightedClusterUpdateClusters
XdsRoutingClusterUpdateClusters
RestartsRequestsUponReconnection
ChangeCluster

All of them are failing for the same reason.  Upon a cluster change we will hit error: 
In XdsClusterManagerLb::ClusterPicker::Pick, the cluster specified by XdsConfigSelector is not found.

This is because upon a new update where the clusters change, XdsConfigSelector will move to the new update and start picking from the new list of clusters.

This of course gets translated into a service config (the new list of clusters) and is processed by XdsClusterManager.

But this processing takes time, we basically need to build a new Picker and that Picker is only fully built when all the children pickers are built.  

In the mean time, we are still using the old picker which do not have the new clusters in the update. 

Let me know if this is not acceptable and we should maybe delay using the new config selector until the new picker is ready.


<!-- Sent from Reviewable.io -->

2020-09-10 09:21 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659)* status: 28 of 30 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1810 at r24](https://reviewable.io/reviews/grpc/grpc/23659#-MGrJHVbEdphXYxRnvvL:-MGrJHVcAbuLUcTcre96:bi0j4ch) ([raw file](https://github.com/grpc/grpc/blob/622de338225aaa5416ede7a0230169d336531f08/src/core/ext/filters/client_channel/client_channel.cc#L1810)):*
> ```cpp
>       saved_config_selector_.reset();
>       received_first_resolver_result_ = false;
>     }
> ```

also added the resets here to ensure service config and config selector are both destructed, otherwise we have leaks.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 2007 at r24](https://reviewable.io/reviews/grpc/grpc/23659#-MGrGHdNAvmBB4gkdbj_:-MGrGHdO5cJscqSgIWm7:bmb0unw) ([raw file](https://github.com/grpc/grpc/blob/622de338225aaa5416ede7a0230169d336531f08/src/core/ext/filters/client_channel/client_channel.cc#L2007)):*
> ```cpp
>       UpdateStateAndPickerLocked(GRPC_CHANNEL_SHUTDOWN, absl::Status(),
>                                  "shutdown from API", nullptr);
>     }
> ```

if we don't pass in a null picker, the unref will not happen


<!-- Sent from Reviewable.io -->

2020-09-10 09:26 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659)* status: 28 of 30 files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 512 at r24](https://reviewable.io/reviews/grpc/grpc/23659#-MGrKVe28W84djIwKnwe:-MGrKVe28W84djIwKnwf:bhocgkd) ([raw file](https://github.com/grpc/grpc/blob/622de338225aaa5416ede7a0230169d336531f08/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L512)):*
> ```cpp
>   }
>   if (update_needed && xds_client_ != nullptr) {
>     // Propagate the update by creating XdsConfigSelector, CreateServiceConfig,
> ```

This is my attempt to avoid updates during shutdown


<!-- Sent from Reviewable.io -->

2020-09-10 19:52 UTC, markdroth requested changes
You're definitely right that there's a bug in the client channel code, but I think the fix isn't quite right.  I've suggested a better way to fix it.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r24.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGtZbDe7VEsZ2abmIzd:b1lp6p7)* status: all files reviewed, 6 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1810 at r24](https://reviewable.io/reviews/grpc/grpc/23659#-MGrJHVbEdphXYxRnvvL:-MGtS7zM8WUtb2mp2iUH:b-iqhzmg) ([raw file](https://github.com/grpc/grpc/blob/622de338225aaa5416ede7a0230169d336531f08/src/core/ext/filters/client_channel/client_channel.cc#L1810)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

also added the resets here to ensure service config and config selector are both destructed, otherwise we have leaks.
</blockquote></details>

This change should not be necessary.  If the picker is null, these fields should already be reset by the block on line 1750 above.

Also, even if the block on line 1750 was not being triggered for some reason, this still would not be the right place for these changes, because we don't want to unref these objects while holding the data plane mutex.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 2007 at r24](https://reviewable.io/reviews/grpc/grpc/23659#-MGrGHdNAvmBB4gkdbj_:-MGtUq8M7IYeinoEmXqQ:b-lwlu0a) ([raw file](https://github.com/grpc/grpc/blob/622de338225aaa5416ede7a0230169d336531f08/src/core/ext/filters/client_channel/client_channel.cc#L2007)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

if we don't pass in a null picker, the unref will not happen
</blockquote></details>

Passing in null here isn't quite right, because the code in `PickSubchannelLocked()` assumes that a null picker means that we're in IDLE state, in which case it tries to get the channel connected.  But that's not what we want to do in the SHUTDOWN case.

As an alternative, I suggest leaving this code the way it was and instead changing the code on line 1750 to say `if (picker == nullptr || state == GRPC_CHANNEL_SHUTDOWN)`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 397 at r20](https://reviewable.io/reviews/grpc/grpc/23659#-MGJZF-R0Dp39p3N-s9p:-MGtVvJI2UfgU14tcRM-:bgvm4f) ([raw file](https://github.com/grpc/grpc/blob/fece290b2d204ee4d267fc3d4e6da1038a9ba8f3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L397)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i think i copy and pasted the incorrect error, even with XdsResolver* it did not work:src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc:397:18: error: cannot initialize a variable of type 'grpc_core::(anonymous namespace)::XdsResolver *' with an rvalue of type 'grpc_core::Resolver *'
    XdsResolver* resolver =
                 ^
I think it's because XdsResolver itself is not InternallyRefCounted; it is inherting from Resolver which is InternallyRefCounted.  So the release will return a raw pointer to Resolver, which needs to be casted
</blockquote></details>

Ah, okay -- I was confused by the missing asterisk, but it looks like that's just an artifact of the formatting here.  In the future, when you paste an error, please put a line containing three back-ticks in front of it and another line three back-ticks after it, so that it formats like this:

```
error message that contains a * and another * and they all format fine
```

With regard to the inheritence, you're right, the `Ref()` method is returning the base class type, not the subclass type.  So I guess the cast is needed here.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 400 at r23](https://reviewable.io/reviews/grpc/grpc/23659#-MGnO_4JB2NRDyxT-VTe:-MGtVVNp0StjOSD8jhw6:b-lkqxlf) ([raw file](https://github.com/grpc/grpc/blob/c805b053140fae921d0a49cde58ccd52b6c91238/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L400)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It needs to be inside of the inner lambda, not the outer one.  There are two layers of indirection here (the ExecCtx and the WorkSerializer), and we can't give up the ref until the second one is complete.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 374 at r24](https://reviewable.io/reviews/grpc/grpc/23659#-MGtWlAZ0azKSiqE58H9:-MGtWlAZ0azKSiqE58HA:b-gve7e) ([raw file](https://github.com/grpc/grpc/blob/622de338225aaa5416ede7a0230169d336531f08/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L374)):*
> ```cpp
>     auto it = clusters_.find(cluster_name);
>     GPR_ASSERT(it != clusters_.end());
>     // XdsResolver* resolver = resolver_->Ref().release();
> ```

This line can be removed now.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 512 at r24](https://reviewable.io/reviews/grpc/grpc/23659#-MGrKVe28W84djIwKnwe:-MGtX6NA5cYv5TzSrLp-:bwbm6pg) ([raw file](https://github.com/grpc/grpc/blob/622de338225aaa5416ede7a0230169d336531f08/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L512)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

This is my attempt to avoid updates during shutdown
</blockquote></details>

Yup, that looks right.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1549 at r23](https://reviewable.io/reviews/grpc/grpc/23659#-MGnP2hv-nvGk-FLbFJL:-MGtXDwe0jjIDmvUzomB:b6idok8) ([raw file](https://github.com/grpc/grpc/blob/c805b053140fae921d0a49cde58ccd52b6c91238/test/cpp/end2end/xds_end2end_test.cc#L1549)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

so after the code changes and retesting, some tests will still have RPC failures:
XdsRoutingWeightedClusterUpdateWeights
XdsRoutingWeightedClusterUpdateClusters
XdsRoutingClusterUpdateClusters
RestartsRequestsUponReconnection
ChangeCluster

All of them are failing for the same reason.  Upon a cluster change we will hit error: 
In XdsClusterManagerLb::ClusterPicker::Pick, the cluster specified by XdsConfigSelector is not found.

This is because upon a new update where the clusters change, XdsConfigSelector will move to the new update and start picking from the new list of clusters.

This of course gets translated into a service config (the new list of clusters) and is processed by XdsClusterManager.

But this processing takes time, we basically need to build a new Picker and that Picker is only fully built when all the children pickers are built.  

In the mean time, we are still using the old picker which do not have the new clusters in the update. 

Let me know if this is not acceptable and we should maybe delay using the new config selector until the new picker is ready.
</blockquote></details>

There's definitely a bug here.  When the resolver returns a result, we make sure to not swap in the ConfigSelector until after we've updated the LB policies, specifically to avoid this problem.  The expectation is that updating the LB policy will return a new picker by the time the update returns.

It looks like the problem is that the xds_cluster_manager LB policy is not doing this correctly.  If you fix it to make sure that it always returns a new picker before `UpdateLocked()` returns, I think that should address the problem.


<!-- Sent from Reviewable.io -->

2020-09-11 07:29 UTC, donnadionne reviewed
I fixed the issue with the tests: UpdateLocked needed to call UpdateStateLocked (please see xds_cluster_manager.cc); this fix allowed me to restore all the tests

I have tested your new fix and it works; I have decided to exclude it from this review

I found the cause of the leaks!  

Some tests like LdsRds.Vanilla just does a simple single RPC send.  This RPC will end up in a path where 
1. we ref counted ClusterState and Resolver in GetCallConfig
2.In Cluster manager UpdateStateLocked we are in GRPC_CHANNEL_IDLE so we create a QueuePicker 
3. In PickSubchannelLocked we get LoadBalancingPolicy::PickResult::PICK_QUEUE, so we will do MaybeAddCallToQueuedPicksLocked and not MaybeInvokeConfigSelectorCommitCallback
4. This results in on_call_committed not called so we leak a reference for both a CallState and a resolver.

I added MaybeInvokeConfigSelectorCommitCallback right after MaybeAddCallToQueuedPicksLocked in PickSubchannelLocked; this allowed all the tests to pass except for my new test: LdsRdsTest.XdsRoutingClusterUpdateClustersWithPickingDelays (which seems to be touching freed memory).  So I don't think this is the right fix.  Maybe we can talk about how best to fix this scenario (which we didn't encounter before as we didn't have to worry about unreffing in on_call_committed)

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGw0LUO0r8TSoBwKvUB:b77ko8v)* status: 25 of 31 files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1810 at r24](https://reviewable.io/reviews/grpc/grpc/23659#-MGrJHVbEdphXYxRnvvL:-MGtznG9EAEfGcHeRyeq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/622de338225aaa5416ede7a0230169d336531f08/src/core/ext/filters/client_channel/client_channel.cc#L1810)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This change should not be necessary.  If the picker is null, these fields should already be reset by the block on line 1750 above.

Also, even if the block on line 1750 was not being triggered for some reason, this still would not be the right place for these changes, because we don't want to unref these objects while holding the data plane mutex.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 2007 at r24](https://reviewable.io/reviews/grpc/grpc/23659#-MGrGHdNAvmBB4gkdbj_:-MGtzoJbCbpSk64BbJl4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/622de338225aaa5416ede7a0230169d336531f08/src/core/ext/filters/client_channel/client_channel.cc#L2007)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Passing in null here isn't quite right, because the code in `PickSubchannelLocked()` assumes that a null picker means that we're in IDLE state, in which case it tries to get the channel connected.  But that's not what we want to do in the SHUTDOWN case.

As an alternative, I suggest leaving this code the way it was and instead changing the code on line 1750 to say `if (picker == nullptr || state == GRPC_CHANNEL_SHUTDOWN)`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4107 at r25](https://reviewable.io/reviews/grpc/grpc/23659#-MGw3GvdEa_dZstvu3vo:-MGw3GvdEa_dZstvu3vp:b-lu1wlg) ([raw file](https://github.com/grpc/grpc/blob/1ab3361d9d38d5d5ecd245ed643431a27f4c23af/src/core/ext/filters/client_channel/client_channel.cc#L4107)):*
> ```cpp
>     case LoadBalancingPolicy::PickResult::PICK_QUEUE:
>       MaybeAddCallToQueuedPicksLocked(elem);
>       // MaybeInvokeConfigSelectorCommitCallback();
> ```

This fixes all old tests except for it breaks my new test: LdsRdsTest.XdsRoutingClusterUpdateClustersWithPickingDelays
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 374 at r24](https://reviewable.io/reviews/grpc/grpc/23659#-MGtWlAZ0azKSiqE58H9:-MGu-jmbE5_tnRSeRoD_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/622de338225aaa5416ede7a0230169d336531f08/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L374)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This line can be removed now.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1549 at r23](https://reviewable.io/reviews/grpc/grpc/23659#-MGnP2hv-nvGk-FLbFJL:-MGudcDd4ediiCJR2HkA:btzyvf9) ([raw file](https://github.com/grpc/grpc/blob/c805b053140fae921d0a49cde58ccd52b6c91238/test/cpp/end2end/xds_end2end_test.cc#L1549)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's definitely a bug here.  When the resolver returns a result, we make sure to not swap in the ConfigSelector until after we've updated the LB policies, specifically to avoid this problem.  The expectation is that updating the LB policy will return a new picker by the time the update returns.

It looks like the problem is that the xds_cluster_manager LB policy is not doing this correctly.  If you fix it to make sure that it always returns a new picker before `UpdateLocked()` returns, I think that should address the problem.
</blockquote></details>

needed to call UpdateStateLocked in UpdateLocked; now all tests can be restored.


<!-- Sent from Reviewable.io -->

2020-09-11 07:31 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659)* status: 25 of 30 files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4107 at r25](https://reviewable.io/reviews/grpc/grpc/23659#-MGw3GvdEa_dZstvu3vo:-MGw3nSLAdeKxGGLv084:b-4nscyu) ([raw file](https://github.com/grpc/grpc/blob/1ab3361d9d38d5d5ecd245ed643431a27f4c23af/src/core/ext/filters/client_channel/client_channel.cc#L4107)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

This fixes all old tests except for it breaks my new test: LdsRdsTest.XdsRoutingClusterUpdateClustersWithPickingDelays
</blockquote></details>

If we add "MaybeInvokeConfigSelectorCommitCallback();" here


<!-- Sent from Reviewable.io -->

2020-09-11 14:48 UTC, markdroth requested changes
We definitely do not want to call the on_call_committed callback when we queue a call, because the call is not actually committed at that point.  In this context, "committed" means that the call has finished all attempts at an LB pick -- in other words, once it's committed, we know that the call will never try another LB pick.  However, when we queue a call, that by definition means that we didn't get an answer from the picker yet, so we're going to hold onto it until we get a new picker and then try again.

The scenario you describe is totally normal when you send the first call on a channel.  However, it's not the whole picture, because the call won't finish until the pick is actually complete.  After the call gets queued, we wait for the xds_cluster_manager LB policy to get connected and return a new picker with state READY.  Once that happens, the channel will re-process the queued call with the new picker, and when the picker returns PICK_COMPLETE, the on_call_committed callback will be invoked.

I think you need to trace the rest of the scenario to determine why the ref is not being released.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 6 files at r25, 2 of 3 files at r26.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGxa5P8AYYYXIzi3hTO:b4n20nn)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne)



<!-- Sent from Reviewable.io -->

2020-09-11 17:21 UTC, donnadionne reviewed
i think i found the solution!  I need to call MaybeInvokeConfigSelectorCommitCallback in the case RPC cancelled and dequed (please see change in client_channel.cc)

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGyAksd6YoChSbbuIlP:b2dye62)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-11 19:10 UTC, markdroth requested changes
This looks fantastic!

I have a few more comments, but they're all minor cosmetic things.  Once these are resolved, we can get this merged!

> Reviewed 1 of 6 files at r25, 1 of 1 files at r27.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGyTyP27ThkNjyrw879:b-3x0hd8)* status: all files reviewed, 7 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 38 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyWK0-99bL3voF7q06:-MGyWK0-99bL3voF7q07:b-upja85) ([raw file](https://github.com/grpc/grpc/blob/0c1ca7b71d731d04c715118278612f59c37c53b3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L38)):*
> ```cpp
> // XdsResolver
> //
> ```

Please re-add this blank line, for consistency with how we format these comments elsewhere.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 91 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyZ2c07w9Jd9dPS4js:-MGyZ2c07w9Jd9dPS4jt:b-ug5lic) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L91)):*
> ```cpp
>       : public RefCounted<ClusterState, PolymorphicRefCount, false> {
>    public:
>     using ClusterStateMap = std::map<std::string, ClusterState*>;
> ```

Suggest changing the value type from `ClusterState*` to `std::unique_ptr<ClusterState>`.  That way, there's no need to explicitly delete the values when we remove them from the map.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 149 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyWDWn9b4Xv7ggXYZr:-MGyWDWn9b4Xv7ggXYZs:ba67dip) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L149)):*
> ```cpp
>             resolver_.get());
>   }
>   // Update entries in cluster state map.
> ```

I think this comment doesn't really make sense.  I suggest just removing it.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 182 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyX-cG8tPZTXLbIRyQ:-MGyX-cG8tPZTXLbIRyR:bb60vzg) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L182)):*
> ```cpp
>     const std::vector<XdsApi::Route>& routes)
>     : resolver_(std::move(resolver)) {
>   // 1. Construct the route table (reserve size to avoid reallocation and allow
> ```

The part in the parens isn't very clear.  I suggest removing it and instead adding a comment right before the `route_table_.reserve()` call that says this:

Reserve the necessary entries up-front to avoid reallocation as we add elements.  This is necessary because the string_view in the entry's weighted_cluster_state field points to the memory in the route field, so moving the entry in a reallocation will cause the string_view to point to invalid data.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 332 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyY21b1Sw9id09mMW8:-MGyY21cB_Y2SMhqasmf:bditumz) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L332)):*
> ```cpp
>     if (!PathMatch(StringViewFromSlice(*args.path),
>                    entry.route.matchers.path_matcher))
>       continue;
> ```

Please put braces around this.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 428 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyYOM46NCIHAvjdQ3a:-MGyYOM46NCIHAvjdQ3b:b-3cu95) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L428)):*
> ```cpp
> 
> void XdsResolver::OnListenerChanged(std::vector<XdsApi::Route> routes) {
>   // Save the update in the resolver in case of rebuild of
> ```

I think you can remove the "in case of rebuild of XdsConfigSelector" part.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 438 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyYfZN8BF9DIU1UcrR:-MGyYfZN8BF9DIU1UcrS:btdqlaa) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L438)):*
> ```cpp
> grpc_error* XdsResolver::CreateServiceConfig(
>     RefCountedPtr<ServiceConfig>* service_config) {
>   std::vector<std::string> actions_vector;
> ```

Suggest calling this `clusters`.


<!-- Sent from Reviewable.io -->

2020-09-11 21:32 UTC, donnadionne reviewed
Thank you for all the thorough reviews! comments addressed!  PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGz3o_R1Nkf6eNyWe25:bofsmzs)* status: all files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 38 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyWK0-99bL3voF7q06:-MGykjXWC9C2GIgIMGha:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c1ca7b71d731d04c715118278612f59c37c53b3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please re-add this blank line, for consistency with how we format these comments elsewhere.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 91 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyZ2c07w9Jd9dPS4js:-MGyw0tk1ARaYK3GCRQV:b-3pjg74) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L91)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest changing the value type from `ClusterState*` to `std::unique_ptr<ClusterState>`.  That way, there's no need to explicitly delete the values when we remove them from the map.
</blockquote></details>

Done.

small change below since insert needs to copy but std::unique_ptr cannot be copied, so we have to do our own find and if-not-found-emplace.  c++17 has try_emplace coming
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 149 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyWDWn9b4Xv7ggXYZr:-MGyw68wDeAOPC9JbCNZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L149)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this comment doesn't really make sense.  I suggest just removing it.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 182 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyX-cG8tPZTXLbIRyQ:-MGyw_7lBsiqpa4GYvtO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L182)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The part in the parens isn't very clear.  I suggest removing it and instead adding a comment right before the `route_table_.reserve()` call that says this:

Reserve the necessary entries up-front to avoid reallocation as we add elements.  This is necessary because the string_view in the entry's weighted_cluster_state field points to the memory in the route field, so moving the entry in a reallocation will cause the string_view to point to invalid data.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 332 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyY21b1Sw9id09mMW8:-MGywlse4umv6CagEqXf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L332)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please put braces around this.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 428 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyYOM46NCIHAvjdQ3a:-MGywt_9-3EeB1nJ-105:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L428)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you can remove the "in case of rebuild of XdsConfigSelector" part.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 438 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyYfZN8BF9DIU1UcrR:-MGz14Q4CiE7tPyNfUF9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L438)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `clusters`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-11 21:39 UTC, markdroth requested changes
Just a couple remaining nits!  Almost there!

> Reviewed 1 of 1 files at r28.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGz5rR95Mk53Fh94MWA:b4ndtj8)* status: all files reviewed, 3 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 91 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyZ2c07w9Jd9dPS4js:-MGz4tRP5ko8HehjOVlj:b-1rtcx4) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L91)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.

small change below since insert needs to copy but std::unique_ptr cannot be copied, so we have to do our own find and if-not-found-emplace.  c++17 has try_emplace coming
</blockquote></details>

We won't ever create this object if it's already present in the map, so I think we can just do the `emplace()` unconditionally.

I think you can just do this in the initialization list:

```
it_(cluster_state_map->emplace(cluster_name, std::unique_ptr<ClusterState>(this)).first)
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 97 at r28](https://reviewable.io/reviews/grpc/grpc/23659#-MGz4jWt1O1Rl4P8ZKG2:-MGz4jWt1O1Rl4P8ZKG3:b-ya5qi) ([raw file](https://github.com/grpc/grpc/blob/c8d630854a0f82cf34a30c1b13ae3f052a0b2ecf/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L97)):*
> ```cpp
>     ClusterState(const std::string& cluster_name,
>                  ClusterStateMap* cluster_state_map) {
>       it_ = cluster_state_map->find(cluster_name.c_str());
> ```

Please do not use `.c_str()` here.  This will cause a new `std::string` to be created, which is an unnecessary allocation.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 100 at r28](https://reviewable.io/reviews/grpc/grpc/23659#-MGz4ngRCZfsbzIMlkDh:-MGz4ngRCZfsbzIMlkDi:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/c8d630854a0f82cf34a30c1b13ae3f052a0b2ecf/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L100)):*
> ```cpp
>       if (it_ == cluster_state_map->end()) {
>         it_ = cluster_state_map
>                   ->emplace(cluster_name.c_str(),
> ```

Same here.


<!-- Sent from Reviewable.io -->

2020-09-11 21:52 UTC, donnadionne reviewed
PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGz9-P063sFiXxzsOmo:b-h8gvr0)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 91 at r27](https://reviewable.io/reviews/grpc/grpc/23659#-MGyZ2c07w9Jd9dPS4js:-MGz8KCeDPnKyMJeXs27:bgb6oud) ([raw file](https://github.com/grpc/grpc/blob/812de7bd6fc52d2dca9901beadfddb7bd7555eb0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L91)):*
> it_(cluster_state_map->emplace(cluster_name, std::unique_ptr<ClusterState>(this)).first)
you are right, coz we checked it once before!  ok this is easier!
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 97 at r28](https://reviewable.io/reviews/grpc/grpc/23659#-MGz4jWt1O1Rl4P8ZKG2:-MGz8PPu2Oep34vT6IDD:b-hfpv0l) ([raw file](https://github.com/grpc/grpc/blob/c8d630854a0f82cf34a30c1b13ae3f052a0b2ecf/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L97)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please do not use `.c_str()` here.  This will cause a new `std::string` to be created, which is an unnecessary allocation.
</blockquote></details>

removed
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 100 at r28](https://reviewable.io/reviews/grpc/grpc/23659#-MGz4ngRCZfsbzIMlkDh:-MGz8QrODRiA6o-ICKx8:brpmqbp) ([raw file](https://github.com/grpc/grpc/blob/c8d630854a0f82cf34a30c1b13ae3f052a0b2ecf/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L100)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

removed 


<!-- Sent from Reviewable.io -->

2020-09-11 22:01 UTC, markdroth approved these changes
This looks great!  Please squash commits before merging.

> Reviewed 1 of 1 files at r29.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23659#-:-MGzAzfA1feODWzvGoES:b-q2nvhu)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-12 00:42 UTC, merged