Change XdsClient to support multiple LDS and RDS watchers
grpc/grpc pull request #23938
Opened 2020-08-21 18:37 UTC by markdroth

Instead of having one special watcher instance for combined LDS/RDS data that has the same lifetime as the XdsClient, we now provide the same type of watcher API for LDS and RDS as we already have for CDS and EDS.

This provides a cleaner separation of concerns between the XdsClient and its watchers: the XdsClient deals exclusively with the transport protocol, and the watchers deal with the data model.

This paves the way for future changes that will (a) add xDS support in the gRPC server and (b) share a single XdsClient instance between channels.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc/23938)

2020-09-12 23:47 UTC, markdroth commented
This is now ready for review.

2020-09-15 04:17 UTC, donnadionne requested changes
> Reviewed 4 of 9 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23938)* status: all files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 347 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEq93GC7rG91WYeoCD:-MHEq93GC7rG91WYeoCE:bsfpssc) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_api.cc#L347)):*
> ```cpp
>   // If the same best matched domain pattern appears in multiple virtual hosts,
>   // the first matched virtual host wins.
>   VirtualHost* target_vhost = nullptr;
> ```

why not keep the const?
___
*[src/core/ext/xds/xds_api.cc, line 352 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEqBxW3UjaO5TZvFb4:-MHEqBxW3UjaO5TZvFb5:bsfpssc) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_api.cc#L352)):*
> ```cpp
>   // Check each domain pattern in each virtual host to determine the best
>   // matched virtual host.
>   for (VirtualHost& vhost : virtual_hosts) {
> ```

why not keep the const?
___
*[src/core/ext/xds/xds_api.cc, line 1755 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEpeyF7anEABjvHKGi:-MHEpeyF7anEABjvHKGj:b-cry265) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_api.cc#L1755)):*
> ```cpp
>     grpc_error* error =
>         RouteConfigParse(client, tracer, route_config, &rds_update);
>     if (error != GRPC_ERROR_NONE) return error;
> ```

The logic here changed a bit: if there is a parsing error, the entry is still already added to rds_update_map; whereas before it's only added after parsing is successful.

This is true for Route, and Cds and Eds below
___
*[src/core/ext/xds/xds_client.cc, line 908 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEwEBR3LPtXH_dYH_-:-MHEwEBR3LPtXH_dYH_0:b-dxm8yq) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_client.cc#L908)):*
> ```cpp
>     }
>     // Ignore identical update.
>     ListenerState& listener_state = xds_client()->listener_map_[listener_name];
> ```

use fine here? so we don't add an entry with no value?
___
*[src/core/ext/xds/xds_client.cc, line 983 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEwVKv0RkqsoF2GM3v:-MHEwVKv0RkqsoF2GM3w:bney5ig) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_client.cc#L983)):*
> ```cpp
>     }
>     RouteConfigState& route_config_state =
>         xds_client()->route_config_map_[route_config_name];
> ```

use find?
___
*[src/core/ext/xds/xds_client.cc, line 1105 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEx6RmDAufVBTGu-ky:-MHEx6RmDAufVBTGu-kz:bney5ig) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_client.cc#L1105)):*
> ```cpp
>     }
>     EndpointState& endpoint_state =
>         xds_client()->endpoint_map_[eds_service_name];
> ```

use find?


<!-- Sent from Reviewable.io -->

2020-09-15 14:43 UTC, markdroth reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23938)* status: all files reviewed, 6 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_api.cc, line 347 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEq93GC7rG91WYeoCD:-MHHBgZuAZ6hQHLQCXy8:bvfux17) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_api.cc#L347)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

why not keep the const?
</blockquote></details>

Making this method return non-const allows us to use `std::move()` in xds_resolver.cc line 517.
___
*[src/core/ext/xds/xds_api.cc, line 352 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEqBxW3UjaO5TZvFb4:-MHHByUb2zpyRNM1NURr:b-q64pkt) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_api.cc#L352)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

why not keep the const?
</blockquote></details>

See above.
___
*[src/core/ext/xds/xds_api.cc, line 1755 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEpeyF7anEABjvHKGi:-MHHCE3h9-aM16JzFHZd:b-3fp6qc) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_api.cc#L1755)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

The logic here changed a bit: if there is a parsing error, the entry is still already added to rds_update_map; whereas before it's only added after parsing is successful.

This is true for Route, and Cds and Eds below
</blockquote></details>

That's true, but it doesn't matter, because the result will be ignored when we return an error anyway.
___
*[src/core/ext/xds/xds_client.cc, line 908 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEwEBR3LPtXH_dYH_-:-MHHChJa09IAv2Rf3g8Y:b-2snvb2) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_client.cc#L908)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

use fine here? so we don't add an entry with no value?
</blockquote></details>

The entry will always already exist at this point, because `XdsApi::ParseAdsResponse()` won't return any resources that we are not subscribed to.
___
*[src/core/ext/xds/xds_client.cc, line 983 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEwVKv0RkqsoF2GM3v:-MHHD-_K03Yh8n3g2U01:b-q64pkt) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_client.cc#L983)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

use find?
</blockquote></details>

See above.
___
*[src/core/ext/xds/xds_client.cc, line 1105 at r2](https://reviewable.io/reviews/grpc/grpc/23938#-MHEx6RmDAufVBTGu-ky:-MHHD1BlD32_aAl-j4J1:b-q64pkt) ([raw file](https://github.com/grpc/grpc/blob/65de07ed685f6356201805d6ab6c93a69bbee637/src/core/ext/xds/xds_client.cc#L1105)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

use find?
</blockquote></details>

See above.


<!-- Sent from Reviewable.io -->

2020-09-15 17:37 UTC, donnadionne approved these changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/23938)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @donnadionne)



<!-- Sent from Reviewable.io -->

2020-09-15 20:06 UTC, markdroth commented
The "Basic Tests Python Windows" failure is an infrastructure timeout.

2020-09-15 20:06 UTC, merged