Add parsing logic for GoogleMeshCaConfig
grpc/grpc pull request #24127
Opened 2020-09-11 16:17 UTC by yashykt

2020-09-11 22:46 UTC, markdroth requested changes
This looks good overall!  Comments are all fairly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24127#-:-MGzLC_z-AoQDdTo9clX:bfnlicm)* status: all files reviewed, 14 unresolved discussions (waiting on @yashykt)

___
*[BUILD, line 1338 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzJ70X0tfwR7ll-wq-:-MGzJ70X0tfwR7ll-wq0:bqgj6cu) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/BUILD#L1338)):*
> ```Starlark
> 
> grpc_cc_library(
>     name = "grpc_google_mesh_ca_certificate_provider",
> ```

This is not the certificate provider itself; it's just the factory.  The provider itself will probably be in a separate target in src/core/lib/security, so that it can be used with TlsCreds if we want.

Please rename accordingly, both the target name and the filenames.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.h, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGygScxC0_CVra02WfK:-MGygScxC0_CVra02WfL:bhnrsqq) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.h#L30)):*
> ```objc
> namespace grpc_core {
> 
> class GoogleMeshCaCertificateProviderFactory : CertificateProviderFactory {
> ```

Inheritence must be `public`, as per style guide.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.h, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGyglqJCJjqkdyAF9jH:-MGyglqJCJjqkdyAF9jI:bs8v1wi) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.h#L34)):*
> ```objc
>   class Config : public CertificateProviderFactory::Config {
>    public:
>     struct StsConfig {
> ```

Instead of redeclaring this, I suggest using the existing struct here:

https://github.com/grpc/grpc/blob/8527ebb47134937e4d59670f816ddeccb320b881/include/grpcpp/security/credentials.h#L271
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGyh2vc8QU85Wxd5UIC:-MGyh2vc8QU85Wxd5UID:btler8m) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.h#L46)):*
> ```objc
>     };
> 
>     const char* name() const override { return "meshCA"; }
> ```

This string exists in two places.  Suggest defining it as a constant (preferably in the .cc file) and using it in both places.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.cc, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzHMBg9ulpyV41wHCN:-MGzHMBg9ulpyV41wHCO:b-bj8ufv) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.cc#L41)):*
> ```cpp
> //
> template <typename NumericType, typename ErrorVectorType>
> bool ExtractJsonType(const Json& json, const std::string& field_name,
> ```

General API suggestion for all of these helper functions: Instead of returning a bool to indicate success and returning the value by parameter, I suggest having the function return `absl::optional<NumericValue>` (or whatever type is appropriate for the function).  If the result has no value, then it was an error.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.cc, line 125 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGyhsvLBplr455fZ1Qg:-MGyhsvLBplr455fZ1Qh:b-8rgz05) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.cc#L125)):*
> ```cpp
> // proto message, as per:
> //   https://developers.google.com/protocol-buffers/docs/proto3#json
> bool ParseDuration(const Json& field, grpc_millis* duration) {
> ```

This function already exists in the client channel code.  Instead of duplicating it, how about moving it into its own module in src/core/lib/json, so that it can be used in both places?
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzH-de6c0bRBKNlX1G:-MGzH-de6c0bRBKNlX1H:b-wflupe) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.cc#L194)):*
> ```cpp
> GoogleMeshCaCertificateProviderFactory::Config::Parse(const Json& config_json,
>                                                       grpc_error** error) {
>   std::vector<grpc_error*> error_list;
> ```

It looks like you're currently using the same `error_list` vector for all errors.  This can make it hard to figure out where the error is actually coming from, because error messages include the inner-most field name only.

I suggest doing the same sort of recursive parsing we do elsewhere (e.g., in the LB policy code and in the xDS bootstrap parser).  Every time you enter a new scope in the JSON, recurse into a new parsing helper function.  Each parsing function has its own error list, and upon return, any errors in that list get grouped underneath one error that indicates the field name from the enclosing scope.  Thus, the structure of the error tree makes it easy to see exactly where in the tree the parsing errors were.
___
*[test/core/client_channel/BUILD, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzJW9cD2JmGw3Hh5T3:-MGzJW9cD2JmGw3Hh5T4:b-xdaicn) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/BUILD#L34)):*
> ```Starlark
> 
> grpc_cc_test(
>     name = "google_mesh_ca_certificate_provider_test",
> ```

Please add "factory" to both the target name and filename.
___
*[test/core/client_channel/BUILD, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzJhawDZf2h95WevFc:-MGzJhawDZf2h95WevFd:bcyuepi) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/BUILD#L34)):*
> ```Starlark
> 
> grpc_cc_test(
>     name = "google_mesh_ca_certificate_provider_test",
> ```

This isn't really client-channel-specific functionality (it will also be used in the server), so this seems like the wrong directory for it.  Suggest creating a new directory test/core/xds.
___
*[test/core/client_channel/google_mesh_ca_certificate_provider_test.cc, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzK7xW39JPqAH95CT4:-MGzK7xW39JPqAH95CT5:b-65admm) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/google_mesh_ca_certificate_provider_test.cc#L32)):*
> ```cpp
> namespace {
> 
> void VerifyRegexMatch(grpc_error* error, const std::regex& e) {
> ```

Can we just use the gmock `ContainsRegex()` matcher instead?
___
*[test/core/client_channel/google_mesh_ca_certificate_provider_test.cc, line 258 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzKc3Z4norH8B-8ffK:-MGzKc3Z4norH8B-8ffL:bcsh79a) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/google_mesh_ca_certificate_provider_test.cc#L258)):*
> ```cpp
> }
> 
> TEST(GoogleMeshCaConfigTest, WrongTypes2) {
> ```

Suggest calling this `GrpcServicesNotAnArray`.
___
*[test/core/client_channel/google_mesh_ca_certificate_provider_test.cc, line 280 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzKgiY9mNq0WwDQVHJ:-MGzKgiY9mNq0WwDQVHK:b62u60j) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/google_mesh_ca_certificate_provider_test.cc#L280)):*
> ```cpp
> }
> 
> TEST(GoogleMeshCaConfigTest, WrongTypes3) {
> ```

`GoogleGrpcNotAnObject`
___
*[test/core/client_channel/google_mesh_ca_certificate_provider_test.cc, line 304 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzKk1u6nREIawX3zx9:-MGzKk1u6nREIawX3zxA:b3deqn8) ([raw file](https://github.co [...]

2020-09-11 23:24 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24127)* status: all files reviewed, 14 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.cc, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzHMBg9ulpyV41wHCN:-MGzQn7v5qM0BZ9MyDXR:b-or8uum) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.cc#L41)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

General API suggestion for all of these helper functions: Instead of returning a bool to indicate success and returning the value by parameter, I suggest having the function return `absl::optional<NumericValue>` (or whatever type is appropriate for the function).  If the result has no value, then it was an error.
</blockquote></details>

I thought of this earlier and went back and forth between the pointer as a parameter and an absl::optional return. The thing I liked about providing the pointer to the helpers is that the main parsing logic is really concise and does not get bloated by if conditions where we check has_value() and then assign the field to value(). 

What do you think?

So,
`ParsedJsonObjectField(json, "field_name", &config->field, ...);`

becomes 

`absl::optional<std::string> parsed_field = ParsedJsonObjectField(...);
if(parsed_field.has_value()) {
  config->field = parsed_field.value();
}
`

what do you think? 


<!-- Sent from Reviewable.io -->

2020-09-11 23:53 UTC, markdroth reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24127)* status: all files reviewed, 13 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.cc, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzHMBg9ulpyV41wHCN:-MGz_Cyf8WIjaoxgUTw-:b-497f1n) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.cc#L41)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I thought of this earlier and went back and forth between the pointer as a parameter and an absl::optional return. The thing I liked about providing the pointer to the helpers is that the main parsing logic is really concise and does not get bloated by if conditions where we check has_value() and then assign the field to value(). 

What do you think?

So,
`ParsedJsonObjectField(json, "field_name", &config->field, ...);`

becomes 

`absl::optional<std::string> parsed_field = ParsedJsonObjectField(...);
if(parsed_field.has_value()) {
  config->field = parsed_field.value();
}
`

what do you think? 
</blockquote></details>

Yeah, that's a good point.  This is counter to our normal style guidance (prefer to return values directly instead of via parameters), but I guess this makes more sense in this case.

Okay, this is fine.


<!-- Sent from Reviewable.io -->

2020-09-15 00:18 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24127)* status: 1 of 24 files reviewed, 13 unresolved discussions (waiting on @markdroth)

___
*[BUILD, line 1338 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzJ70X0tfwR7ll-wq-:-MHE6kod5TZIYYgSSNQq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/BUILD#L1338)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is not the certificate provider itself; it's just the factory.  The provider itself will probably be in a separate target in src/core/lib/security, so that it can be used with TlsCreds if we want.

Please rename accordingly, both the target name and the filenames.
</blockquote></details>

Done.
___
*[test/core/client_channel/BUILD, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzJW9cD2JmGw3Hh5T3:-MHE6y8gEixI2ifvNm-K:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/BUILD#L34)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add "factory" to both the target name and filename.
</blockquote></details>

Done.
___
*[test/core/client_channel/BUILD, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzJhawDZf2h95WevFc:-MHE6yZY5gF5T44qysJc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/BUILD#L34)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This isn't really client-channel-specific functionality (it will also be used in the server), so this seems like the wrong directory for it.  Suggest creating a new directory test/core/xds.
</blockquote></details>

Done.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.h, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGygScxC0_CVra02WfK:-MHE6n3U3SNvALQ6lL_V:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Inheritence must be `public`, as per style guide.
</blockquote></details>

Done.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.h, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGyglqJCJjqkdyAF9jH:-MHDZUHC71s9IwzHCAWL:bogowwp) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.h#L34)):*
> StsCredentialsOptions
I don't think we want a dependency on a C++ header from Core
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGyh2vc8QU85Wxd5UIC:-MHE6pHvBZv3zwZZuI3v:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This string exists in two places.  Suggest defining it as a constant (preferably in the .cc file) and using it in both places.
</blockquote></details>

Done.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.cc, line 125 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGyhsvLBplr455fZ1Qg:-MHE6rKo6BJ8FJSDZ-4i:b-b3mwxw) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.cc#L125)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This function already exists in the client channel code.  Instead of duplicating it, how about moving it into its own module in src/core/lib/json, so that it can be used in both places?
</blockquote></details>

Done. Moved to src/core/lib/json/json_util.h
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzH-de6c0bRBKNlX1G:-MHE6vBN0-jbOFpVUez8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.cc#L194)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like you're currently using the same `error_list` vector for all errors.  This can make it hard to figure out where the error is actually coming from, because error messages include the inner-most field name only.

I suggest doing the same sort of recursive parsing we do elsewhere (e.g., in the LB policy code and in the xDS bootstrap parser).  Every time you enter a new scope in the JSON, recurse into a new parsing helper function.  Each parsing function has its own error list, and upon return, any errors in that list get grouped underneath one error that indicates the field name from the enclosing scope.  Thus, the structure of the error tree makes it easy to see exactly where in the tree the parsing errors were.
</blockquote></details>

Done.
___
*[test/core/client_channel/google_mesh_ca_certificate_provider_test.cc, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzK7xW39JPqAH95CT4:-MHE70YHA6U0sU30OXUX:b4s9rpn) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/google_mesh_ca_certificate_provider_test.cc#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can we just use the gmock `ContainsRegex()` matcher instead?
</blockquote></details>

Yes, we can! Replaced.
___
*[test/core/client_channel/google_mesh_ca_certificate_provider_test.cc, line 258 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzKc3Z4norH8B-8ffK:-MHE72vVC8GRCS2WrH0P:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/google_mesh_ca_certificate_provider_test.cc#L258)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `GrpcServicesNotAnArray`.
</blockquote></details>

Done.
___
*[test/core/client_channel/google_mesh_ca_certificate_provider_test.cc, line 280 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzKgiY9mNq0WwDQVHJ:-MHE73cj9UrYrxhCWoAm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/google_mesh_ca_certificate_provider_test.cc#L280)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`GoogleGrpcNotAnObject`
</blockquote></details>

Done.
___
*[test/core/client_channel/google_mesh_ca_certificate_provider_test.cc, line 304 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzKk1u6nREIawX3zx9:-MHE749z-aLGjgzqifhw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/google_mesh_ca_certificate_provider_test.cc#L304)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`CallCredentialsNotAnArray`
</blockquote></details>

Done.
___
*[test/core/client_channel/google_mesh_ca_certificate_provider_test.cc, line 331 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzKmSU8geN8iqxCsIX:-MHE74bB03h2DWzq6jQp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/test/core/client_channel/google_mesh_ca_certificate_provider_test.cc#L331)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`StsServiceNotAnObject`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-15 15:56 UTC, markdroth requested changes
Looking better and better!  Comments remaining minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 24 of 24 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24127#-:-MHHThEk0eXx3MQGHDuR:boy3bb0)* status: all files reviewed, 7 unresolved discussions (waiting on @yashykt)

___
*[src/core/lib/json/json_util.h, line 24 at r2](https://reviewable.io/reviews/grpc/grpc/24127#-MHHQXcm-xtQFCOvao3x:-MHHQXcm-xtQFCOvao3y:bs422ub) ([raw file](https://github.com/grpc/grpc/blob/979f6243a6055421fa1293332915b6a43f40fdd0/src/core/lib/json/json_util.h#L24)):*
> ```objc
> #include <grpc/support/port_platform.h>
> 
> #include <grpc/support/string_util.h>
> ```

This include and the next one should be moved to the .cc file.
___
*[src/core/lib/json/json_util.h, line 35 at r2](https://reviewable.io/reviews/grpc/grpc/24127#-MHHR9m32y8W3hUmobIW:-MHHR9m32y8W3hUmobIX:b-j9s5tl) ([raw file](https://github.com/grpc/grpc/blob/979f6243a6055421fa1293332915b6a43f40fdd0/src/core/lib/json/json_util.h#L35)):*
> ```objc
> // proto message, as per:
> //   https://developers.google.com/protocol-buffers/docs/proto3#json
> bool ParseDurationFromJson(const Json& field, grpc_millis* duration);
> ```

Please document that it returns true on success.
___
*[src/core/lib/json/json_util.cc, line 54 at r2](https://reviewable.io/reviews/grpc/grpc/24127#-MHHQo1-73q9bZta0xoi:-MHHQo1-73q9bZta0xoj:b-odgzle) ([raw file](https://github.com/grpc/grpc/blob/979f6243a6055421fa1293332915b6a43f40fdd0/src/core/lib/json/json_util.cc#L54)):*
> ```cpp
> }
> 
> }  // namespace grpc_core
> ```

Please add trailing newline.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.h, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGyglqJCJjqkdyAF9jH:-MHHReDW54zWRl98kUGm:b-rkzddh) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.h#L34)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> StsCredentialsOptions
I don't think we want a dependency on a C++ header from Core
</blockquote></details>

Good point.  Then I guess we should use this instead:

https://github.com/grpc/grpc/blob/089d90933a778b9fad65c36848b2843c253cb152/include/grpc/grpc_security.h#L368

This is the form that we'll need anyway in order to create the STS call creds.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzH-de6c0bRBKNlX1G:-MHHSvLw-IcqwcLTZdrp:b-798ilo) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.cc#L194)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you split up the parsing code for each scope into its own helper method?  I think that will make it a lot easier to read and maintain.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider_factory.cc, line 38 at r2](https://reviewable.io/reviews/grpc/grpc/24127#-MHHS_ptA2yAHpZAW0-m:-MHHS_ptA2yAHpZAW0-n:bivjtc9) ([raw file](https://github.com/grpc/grpc/blob/979f6243a6055421fa1293332915b6a43f40fdd0/src/core/ext/xds/google_mesh_ca_certificate_provider_factory.cc#L38)):*
> ```cpp
> namespace {
> 
> const char* kMeshCaPlugin = "meshCA";
> ```

Have we standardized on this string across languages?  It will appear in the bootstrap file, so we'll need to be consistent.

If we haven't yet standardized, I'd prefer to call it `MeshCA`.  But if we have, then this is fine.
___
*[test/core/xds/google_mesh_ca_certificate_provider_factory_test.cc, line 19 at r2](https://reviewable.io/reviews/grpc/grpc/24127#-MHHTL8b2DZ7DMOaIRy4:-MHHTL8c5Kja5eq7FasO:ba8tqiq) ([raw file](https://github.com/grpc/grpc/blob/979f6243a6055421fa1293332915b6a43f40fdd0/test/core/xds/google_mesh_ca_certificate_provider_factory_test.cc#L19)):*
> ```cpp
> //
> 
> #include <regex>
> ```

I don't think this include is needed anymore.


<!-- Sent from Reviewable.io -->

2020-09-15 23:44 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24127)* status: 19 of 24 files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/json/json_util.h, line 24 at r2](https://reviewable.io/reviews/grpc/grpc/24127#-MHHQXcm-xtQFCOvao3x:-MHJ7B1v2Mn1af8iYRu5:b-orkhih) ([raw file](https://github.com/grpc/grpc/blob/979f6243a6055421fa1293332915b6a43f40fdd0/src/core/lib/json/json_util.h#L24)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This include and the next one should be moved to the .cc file.
</blockquote></details>

You are right. Moved
___
*[src/core/lib/json/json_util.h, line 35 at r2](https://reviewable.io/reviews/grpc/grpc/24127#-MHHR9m32y8W3hUmobIW:-MHJ8w286jlRD3nKn0aq:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/979f6243a6055421fa1293332915b6a43f40fdd0/src/core/lib/json/json_util.h#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document that it returns true on success.
</blockquote></details>

Done
___
*[src/core/lib/json/json_util.cc, line 54 at r2](https://reviewable.io/reviews/grpc/grpc/24127#-MHHQo1-73q9bZta0xoi:-MHJ8xeG81rLXcr73V32:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/979f6243a6055421fa1293332915b6a43f40fdd0/src/core/lib/json/json_util.cc#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add trailing newline.
</blockquote></details>

Done
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.h, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGyglqJCJjqkdyAF9jH:-MHJ7f0kAEn55nuI1Rz1:b-a4ql7r) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.h#L34)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Good point.  Then I guess we should use this instead:

https://github.com/grpc/grpc/blob/089d90933a778b9fad65c36848b2843c253cb152/include/grpc/grpc_security.h#L368

This is the form that we'll need anyway in order to create the STS call creds.
</blockquote></details>

Yeah, unfortunately this takes in `const char*`. We could potentially store the config to have the strings backing available to guarantee lifetime, but then we have cases where we need to store defaults and compute the values in some cases so we need them to be modifiable.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGzH-de6c0bRBKNlX1G:-MHJ8ot44jxwpC4SPfRU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.cc#L194)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can you split up the parsing code for each scope into its own helper method?  I think that will make it a lot easier to read and maintain.
</blockquote></details>

Done.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider_factory.cc, line 38 at r2](https://reviewable.io/reviews/grpc/grpc/24127#-MHHS_ptA2yAHpZAW0-m:-MHIq1emBVUvMmqOnPdd:b-8swoes) ([raw file](https://github.com/grpc/grpc/blob/979f6243a6055421fa1293332915b6a43f40fdd0/src/core/ext/xds/google_mesh_ca_certificate_provider_factory.cc#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Have we standardized on this string across languages?  It will appear in the bootstrap file, so we'll need to be consistent.

If we haven't yet standardized, I'd prefer to call it `MeshCA`.  But if we have, then this is fine.
</blockquote></details>

This is what the docs say presently but it is not set in stone, we can change it.
___
*[test/core/xds/google_mesh_ca_certificate_provider_factory_test.cc, line 19 at r2](https://reviewable.io/reviews/grpc/grpc/24127#-MHHTL8b2DZ7DMOaIRy4:-MHJ8z2Q8gaAn31Jal27:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/979f6243a6055421fa1293332915b6a43f40fdd0/test/core/xds/google_mesh_ca_certificate_provider_factory_test.cc#L19)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this include is needed anymore.
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2020-09-16 15:42 UTC, markdroth requested changes
Just a couple of remaining comments about structuring the parsing recursion.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 5 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24127#-:-MHM_2VF2cWv6fcc2H09:b-x2idnk)* status: all files reviewed, 2 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/google_mesh_ca_certificate_provider.h, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24127#-MGyglqJCJjqkdyAF9jH:-MHMVZWD5hvsxRMXFsg0:bszixju) ([raw file](https://github.com/grpc/grpc/blob/4ab5344d070fed050c70f202144ab2cd90a8a93a/src/core/ext/xds/google_mesh_ca_certificate_provider.h#L34)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Yeah, unfortunately this takes in `const char*`. We could potentially store the config to have the strings backing available to guarantee lifetime, but then we have cases where we need to store defaults and compute the values in some cases so we need them to be modifiable.
</blockquote></details>

Ugh, that's really unfortunate.  I hate the fact that we will now have this struct in 3 different places.  But okay.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider_factory.h, line 68 at r4](https://reviewable.io/reviews/grpc/grpc/24127#-MHMWyaLDevN5ayApt7Y:-MHMWyaMEEfdj2GF78pu:bd5idf3) ([raw file](https://github.com/grpc/grpc/blob/b5e205d9d03491f468ea3238ae47bb8a08a8eae2/src/core/ext/xds/google_mesh_ca_certificate_provider_factory.h#L68)):*
> ```objc
>    private:
>     // Helpers for parsing the config
>     void ParseJsonObjectStsService(const Json::Object& parent_object,
> ```

Instead of passing in the parent object, please pass in only the value that this function is responsible for parsing.  It can be passed in as a `const Json&`, and the function can validate its type.
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider_factory.h, line 69 at r4](https://reviewable.io/reviews/grpc/grpc/24127#-MHMZIdQ1mKp5DIrptfV:-MHMZIdQ1mKp5DIrptfW:bqsmh15) ([raw file](https://github.com/grpc/grpc/blob/b5e205d9d03491f468ea3238ae47bb8a08a8eae2/src/core/ext/xds/google_mesh_ca_certificate_provider_factory.h#L69)):*
> ```objc
>     // Helpers for parsing the config
>     void ParseJsonObjectStsService(const Json::Object& parent_object,
>                                    std::vector<grpc_error*>* parent_error_list);
> ```

Instead of passing in the error vector from the parent and having the child populate it, please just have the child return an error vector, which the parent can add to its own.

https://abseil.io/tips/176


<!-- Sent from Reviewable.io -->

2020-09-16 20:00 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24127)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/google_mesh_ca_certificate_provider_factory.h, line 68 at r4](https://reviewable.io/reviews/grpc/grpc/24127#-MHMWyaLDevN5ayApt7Y:-MHNV2Q6CLFPlaqg8VST:bxn8r4u) ([raw file](https://github.com/grpc/grpc/blob/b5e205d9d03491f468ea3238ae47bb8a08a8eae2/src/core/ext/xds/google_mesh_ca_certificate_provider_factory.h#L68)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of passing in the parent object, please pass in only the value that this function is responsible for parsing.  It can be passed in as a `const Json&`, and the function can validate its type.
</blockquote></details>

Restructured, though I'm passing  in `Json::Object` instead of a `Json` letting the helper functions deal with the `Json` instead
___
*[src/core/ext/xds/google_mesh_ca_certificate_provider_factory.h, line 69 at r4](https://reviewable.io/reviews/grpc/grpc/24127#-MHMZIdQ1mKp5DIrptfV:-MHNV1cwDbCpAZ1DN6zS:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/b5e205d9d03491f468ea3238ae47bb8a08a8eae2/src/core/ext/xds/google_mesh_ca_certificate_provider_factory.h#L69)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of passing in the error vector from the parent and having the child populate it, please just have the child return an error vector, which the parent can add to its own.

https://abseil.io/tips/176
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-09-17 15:09 UTC, markdroth approved these changes
This looks great!  Feel free to merge after addressing the one remaining nit.

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24127#-:-MHRbGLR6sIMOGfADgo1:b91m400)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/ext/xds/google_mesh_ca_certificate_provider_factory.cc, line 310 at r5](https://reviewable.io/reviews/grpc/grpc/24127#-MHRb7Ps8wkbiYWnq73C:-MHRb7Pt4oXWbiBKTR3D:b-2jsea0) ([raw file](https://github.com/grpc/grpc/blob/3bb33b2de26782483bbd67a78e3c8c486789acad/src/core/ext/xds/google_mesh_ca_certificate_provider_factory.cc#L310)):*
> ```cpp
> GoogleMeshCaCertificateProviderFactory::Config::Parse(const Json& config_json,
>                                                       grpc_error** error) {
>   std::vector<grpc_error*> error_list;
> ```

Please move this down to line 318, since it's not needed before then.


<!-- Sent from Reviewable.io -->

2020-09-17 20:19 UTC, yashykt commented
Issues:#23597

2020-09-17 20:19 UTC, yashykt commented
Thanks for reviewing!

2020-09-17 20:19 UTC, merged