Cir bre
grpc/grpc pull request #24180
Opened 2020-09-18 06:14 UTC by donnadionne

@nicolasnoble

2020-09-18 06:40 UTC, donnadionne reviewed
This is very drafty, just wanted to get your first review to make sure the approach is correct; for example, taking a ref count of EdsLb in DropPicker.  Thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MHUvU6w58lGftATVmcg:byc125z)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2020-09-18 13:24 UTC, markdroth requested changes
This looks great!  The only significant issue is that the xds_api.cc code is looking at the wrong field in the CDS response.  Otherwise, we just need to add tests.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MHWNW6xE1K3YTdBFOgO:b-c4plzg)* status: all files reviewed, 7 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 230 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWLeMBE7U4TXncYMSk:-MHWLeMBE7U4TXncYMSl:b-x0nsh5) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L230)):*
> ```cpp
>   RefCountedPtr<ChildPickerWrapper> child_picker_;
> 
>   // Current concurrent number of requests;
> ```

Please move these up to line 222, so that they're next to the other data that comes from the EDS update.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 241 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWLs0g2MUzzmJU1_D9:-MHWLs0g2MUzzmJU1_DA:b-slfq4b) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L241)):*
> ```cpp
> EdsLb::DropPicker::DropPicker(RefCountedPtr<EdsLb> eds_policy)
>     : eds_policy_(std::move(eds_policy)) {
>   drop_config_ = eds_policy_->drop_config_;
> ```

These three can still be initialized in the initializer list.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 272 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWMEDq54T-9eytn3Qk:-MHWMEDq54T-9eytn3Ql:b-rlxye5) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L272)):*
> ```cpp
>   // Check and see if we exceeded the max concurrent requests count.
>   uint32_t current = eds_policy_->concurrent_requests_.FetchAdd(1);
>   if (current > eds_policy_->max_concurrent_requests_) {
> ```

In this case, we also need to record the dropped call in `drop_stats_`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 281 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWMnW64qcGadCscCkx:-MHWMnW7AlyPRWknPyvI:bgq9ugh) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L281)):*
> ```cpp
>   EdsLb* eds_policy = static_cast<EdsLb*>(
>       eds_policy_->Ref(DEBUG_LOCATION, "DropPickPicker+call").release());
>   PickResult result = child_picker_->Pick(args);
> ```

Please move this up one line.  We don't need to grab the ref to the EDS policy until after we do the child pick.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 920 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWLG7bDV8P46YdavQv:-MHWLG7bDV8P46YdavQw:b-eg33k) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L920)):*
> ```cpp
>     }
>     // Max concurrent requests.
>     uint32_t max = 1024;
> ```

Please call this `max_concurrent_requests`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 925 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWL7bo4MWptAxN0I6v:-MHWL7bo4MWptAxN0I6w:b-6g0b3q) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L925)):*
> ```cpp
>       if (it->second.type() != Json::Type::NUMBER) {
>         error_list.push_back(GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>             "field:max_concurrent_reqeust error:must be of type number"));
> ```

s/reqeust/requests/
___
*[src/core/ext/xds/xds_api.cc, line 1840 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWKN1iB4pJsPCTxP43:-MHWKN1j2aWLn7GFW_Fv:bpnq7dv) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/xds/xds_api.cc#L1840)):*
> ```cpp
>     }
>     // Record max concurrent requests (if any).
>     if (envoy_config_cluster_v3_Cluster_has_max_requests_per_connection(
> ```

This is the wrong field to look at.  See this section of the gRFC for a pointer to the correct field:

https://github.com/grpc/proposal/blob/master/A32-xds-circuit-breaking.md#overview


<!-- Sent from Reviewable.io -->

2020-09-22 20:23 UTC, donnadionne reviewed
Fixed the code review comments and added tests.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MHrTz3EEP6auUoNMQkN:b-8126nn)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 230 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWLeMBE7U4TXncYMSk:-MHmAVKb0uvfWVHV4x1u:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L230)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move these up to line 222, so that they're next to the other data that comes from the EDS update.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 241 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWLs0g2MUzzmJU1_D9:-MHmGOVt2Big27DV-5U7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L241)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These three can still be initialized in the initializer list.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 272 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWMEDq54T-9eytn3Qk:-MHmKBjo0B_gNVvJz79h:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L272)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In this case, we also need to record the dropped call in `drop_stats_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 281 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWMnW64qcGadCscCkx:-MHmHOgr1-z0DIwb109k:by5iqcv) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L281)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this up one line.  We don't need to grab the ref to the EDS policy until after we do the child pick.
</blockquote></details>

done, also changed the logic to sometimes directly decrement the ref count to prevent leaks
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 920 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWLG7bDV8P46YdavQv:-MHmK_b1-Dz97pFHGIQn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L920)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `max_concurrent_requests`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 925 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWL7bo4MWptAxN0I6v:-MHmK_tm5tsudep1QK4v:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L925)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/reqeust/requests/
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1840 at r1](https://reviewable.io/reviews/grpc/grpc/24180#-MHWKN1iB4pJsPCTxP43:-MHn4j942lKOyDFLBEq9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1b47cc124a7fe70c41ad871ca4de3fe668d21d1a/src/core/ext/xds/xds_api.cc#L1840)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is the wrong field to look at.  See this section of the gRFC for a pointer to the correct field:

https://github.com/grpc/proposal/blob/master/A32-xds-circuit-breaking.md#overview
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-22 21:57 UTC, markdroth requested changes
This looks pretty good.  I have only one significant suggestion, which is about a better way to structure the test.

Please let me know if you have any questions.  Thanks!

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MHroKw24EFSzRunIgxq:b-u1xmg0)* status: all files reviewed, 9 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 267 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrbXmgDLiIrUn3n-ON:-MHrbXmgDLiIrUn3n-OO:b-fv3c1j) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L267)):*
> ```cpp
>     return result;
>   }
>   // Check and see if we exceeded the max concurrent requests count.
> ```

Please move this check up to line 257.  There's no point in checking for a child picker if we're going to drop the call anyway.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 272 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrazpA87KZVAEUPlfT:-MHrazpA87KZVAEUPlfU:b6h9n9g) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L272)):*
> ```cpp
>     eds_policy_->concurrent_requests_.FetchSub(1);
>     if (drop_stats_ != nullptr)
>       drop_stats_->AddCallDropped("max_concurrent_requests_exceeded");
> ```

Whenever the body of an `if` statement is on its own line, it should be enclosed in braces to avoid bugs caused in merges.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 272 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrb4P68YBUmbjIarDe:-MHrb4P68YBUmbjIarDf:ba4b5f4) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L272)):*
> ```cpp
>     eds_policy_->concurrent_requests_.FetchSub(1);
>     if (drop_stats_ != nullptr)
>       drop_stats_->AddCallDropped("max_concurrent_requests_exceeded");
> ```

In this case, we need to record that there was a drop, but it should not count toward any drop category.

In the LRS request, there are two fields that report drops:

- [`total_dropped_requests`](https://github.com/envoyproxy/envoy/blob/5d401ec6240f849701d3d7827dd3d7a7e97ddbc1/api/envoy/config/endpoint/v3/load_report.proto#L156), which indicates the total number of requests dropped for any reason.
- [`dropped_requests`](https://github.com/envoyproxy/envoy/blob/5d401ec6240f849701d3d7827dd3d7a7e97ddbc1/api/envoy/config/endpoint/v3/load_report.proto#L160), which indicates the number of requests dropped for the specific drop categories outlined in the [`drop_overloads`](https://github.com/envoyproxy/envoy/blob/5d401ec6240f849701d3d7827dd3d7a7e97ddbc1/api/envoy/config/endpoint/v3/endpoint.proto#L79) field in the EDS response.

The first field is a superset of the second one.  Any calls dropped for one of the drop categories in the EDS response is recorded in both the first and the second field.  However, any call dropped for some other reason (like, say, a circuit breaker limit :) ) is recorded in the first field but not the second.

Currently, the `XdsClusterDropStats` API supports only calls dropped for one of the EDS drop categories.  When you call `XdsClusterDropStats::AddCallDropped()`, it [always records the drop as a category](https://github.com/grpc/grpc/blob/889ea7cd096b82539842f0b46fe35594a0ac25bd/src/core/ext/xds/xds_client_stats.cc#L59).  Then, when we construct the LRS request, we [populate the drop categories and then set `total_dropped_requests` to the sum of all categories](https://github.com/grpc/grpc/blob/889ea7cd096b82539842f0b46fe35594a0ac25bd/src/core/ext/xds/xds_api.cc#L2341).

We will need to add a mechanism to `XdsClusterDropStats` to track drops that are not associated with an EDS drop category, and then we'll need to add that number in when populating the `total_dropped_requests` field in the LRS request.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 939 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrfTFNChdeyhu8RPYk:-MHrfTFNChdeyhu8RPYl:b8g41pm) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L939)):*
> ```cpp
>       if (it->second.type() != Json::Type::NUMBER) {
>         error_list.push_back(GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>             "field:max_concurrent_request error:must be of type number"));
> ```

s/request/requests/
___
*[src/core/ext/xds/xds_api.cc, line 1850 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHr_xCBDirhaAxKm_Mn:-MHr_xCBDirhaAxKm_Mo:b82tq1r) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/xds/xds_api.cc#L1850)):*
> ```cpp
>       const envoy_config_cluster_v3_CircuitBreakers* circuit_breakers =
>           envoy_config_cluster_v3_Cluster_circuit_breakers(cluster);
>       if (envoy_config_cluster_v3_CircuitBreakers_has_thresholds(
> ```

No need for this check.  If the field is not present, then the call to `envoy_config_cluster_v3_CircuitBreakers_thresholds()` on line 1854 below will set `num_thresholds` to 0, so the loop will never be entered.
___
*[src/core/ext/xds/xds_api.cc, line 1860 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHraCQg5MAmC2Ll90QZ:-MHraCQg5MAmC2Ll90Q_:b-hvpwgt) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/xds/xds_api.cc#L1860)):*
> ```cpp
>           if (envoy_config_cluster_v3_CircuitBreakers_Thresholds_priority(
>                   threshold) == envoy_config_core_v3_DEFAULT &&
>               envoy_config_cluster_v3_CircuitBreakers_Thresholds_has_max_requests(
> ```

Similar comment here.  `envoy_config_cluster_v3_CircuitBreakers_Thresholds_max_requests()` below will return null if the field is not present.
___
*[src/proto/grpc/testing/xds/BUILD, line 38 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHraXU883LqF2LITNKK:-MHraXU92TLQui8QyyRL:b-mtxjvf) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/proto/grpc/testing/xds/BUILD#L38)):*
> ```Starlark
>         "cds_for_test.proto",
>     ],
>     has_services = True,
> ```

This line is not needed.
___
*[src/proto/grpc/testing/xds/cds_for_test.proto, line 70 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHradZ477ZV2ujjxqcp:-MHradZ477ZV2ujjxqcq:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/proto/grpc/testing/xds/cds_for_test.proto#L70)):*
> ```protobuf
>   message Thresholds {
>     RoutingPriority priority = 1;
>     //uint32 max_requests = 4;
> ```

Please remove.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5022 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrlNTo7MCIHDeSDxW_:-MHrlNTp8YatunMQGKMV:b-hb5iby) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/test/cpp/end2end/xds_end2end_test.cc#L5022)):*
> ```cpp
>   const Status status = SendRpc(RpcOptions().set_timeout_ms(0));
>   EXPECT_FALSE(status.ok());
>   // Send a update RouteConfiguration to use backend 1.
> ```

I think the mechanism you're using here to make sure that the RPCs are all in flight at once is likely to be fairly flaky.  If the RPCs finish quickly, I don't think you can guarantee that some of them won't finish before they all start.

I think a better approach would be to send requests that populate the [`client_cancel_after_us` field](https://github.com/grpc/grpc/blob/889ea7cd096b82539842f0b46fe35594a0ac25bd/src/proto/grpc/testing/echo_messages.proto#L37).  That way, the server will basically never finish the request; it will remain in flight until the client cancels.  This will avoid flakiness by eliminating the reliance on timing.  It will also simplify the test, because you can just use a singl [...]

2020-09-24 09:41 UTC, donnadionne reviewed
Will work on the drop stat change separately; did fix the other comments and would like for you to comment on the new test !

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MHzSmdrDSgVt8cgvC46:b5lbeqx)* status: all files reviewed, 9 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 267 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrbXmgDLiIrUn3n-ON:-MHzQi4xAEoSpfA7MLoc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L267)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this check up to line 257.  There's no point in checking for a child picker if we're going to drop the call anyway.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 272 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrazpA87KZVAEUPlfT:-MHzRR6u0ghIVsl3QZhb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L272)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Whenever the body of an `if` statement is on its own line, it should be enclosed in braces to avoid bugs caused in merges.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 272 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrb4P68YBUmbjIarDe:-MHzRRud7W-07H3WFPut:bl7e2wr) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L272)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In this case, we need to record that there was a drop, but it should not count toward any drop category.

In the LRS request, there are two fields that report drops:

- [`total_dropped_requests`](https://github.com/envoyproxy/envoy/blob/5d401ec6240f849701d3d7827dd3d7a7e97ddbc1/api/envoy/config/endpoint/v3/load_report.proto#L156), which indicates the total number of requests dropped for any reason.
- [`dropped_requests`](https://github.com/envoyproxy/envoy/blob/5d401ec6240f849701d3d7827dd3d7a7e97ddbc1/api/envoy/config/endpoint/v3/load_report.proto#L160), which indicates the number of requests dropped for the specific drop categories outlined in the [`drop_overloads`](https://github.com/envoyproxy/envoy/blob/5d401ec6240f849701d3d7827dd3d7a7e97ddbc1/api/envoy/config/endpoint/v3/endpoint.proto#L79) field in the EDS response.

The first field is a superset of the second one.  Any calls dropped for one of the drop categories in the EDS response is recorded in both the first and the second field.  However, any call dropped for some other reason (like, say, a circuit breaker limit :) ) is recorded in the first field but not the second.

Currently, the `XdsClusterDropStats` API supports only calls dropped for one of the EDS drop categories.  When you call `XdsClusterDropStats::AddCallDropped()`, it [always records the drop as a category](https://github.com/grpc/grpc/blob/889ea7cd096b82539842f0b46fe35594a0ac25bd/src/core/ext/xds/xds_client_stats.cc#L59).  Then, when we construct the LRS request, we [populate the drop categories and then set `total_dropped_requests` to the sum of all categories](https://github.com/grpc/grpc/blob/889ea7cd096b82539842f0b46fe35594a0ac25bd/src/core/ext/xds/xds_api.cc#L2341).

We will need to add a mechanism to `XdsClusterDropStats` to track drops that are not associated with an EDS drop category, and then we'll need to add that number in when populating the `total_dropped_requests` field in the LRS request.
</blockquote></details>

I see, i will do this change separately?   but will submit before this PR?
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 939 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrfTFNChdeyhu8RPYk:-MHzRoMC9jW3KzsEaFVl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L939)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/request/requests/
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1850 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHr_xCBDirhaAxKm_Mn:-MHzSRx2AtAQb2qCqHSA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/xds/xds_api.cc#L1850)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this check.  If the field is not present, then the call to `envoy_config_cluster_v3_CircuitBreakers_thresholds()` on line 1854 below will set `num_thresholds` to 0, so the loop will never be entered.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1860 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHraCQg5MAmC2Ll90QZ:-MHzSQlFC63WAPzVGlYc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/xds/xds_api.cc#L1860)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similar comment here.  `envoy_config_cluster_v3_CircuitBreakers_Thresholds_max_requests()` below will return null if the field is not present.
</blockquote></details>

Done.
___
*[src/proto/grpc/testing/xds/BUILD, line 38 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHraXU883LqF2LITNKK:-MHzSf9I3S6liVWty3Iv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/proto/grpc/testing/xds/BUILD#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This line is not needed.
</blockquote></details>

Done.
___
*[src/proto/grpc/testing/xds/cds_for_test.proto, line 70 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHradZ477ZV2ujjxqcp:-MHzSkEZDvArgMLmUM7R:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/proto/grpc/testing/xds/cds_for_test.proto#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5022 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrlNTo7MCIHDeSDxW_:-MHzSlBc2C758h0_9XhO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/test/cpp/end2end/xds_end2end_test.cc#L5022)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the mechanism you're using here to make sure that the RPCs are all in flight at once is likely to be fairly flaky.  If the RPCs finish quickly, I don't think you can guarantee that some of them won't finish before they all start.

I think a better approach would be to send requests that populate the [`client_cancel_after_us` field](https://github.com/grpc/grpc/blob/889ea7cd096b82539842f0b46fe35594a0ac25bd/src/proto/grpc/testing/echo_messages.proto#L37).  That way, the server will basically never finish the request; it will remain in flight until the client cancels.  This will avoid flakiness by eliminating the reliance on timing.  It will also simplify the test, because you can just use a single backend, and there won't be need for an xDS update.

The one thing that will be slightly more complicated is that we'll need a way to cancel the RPCs when the test is done.  I think you can do this by creating a class to contain each RPC.  Each class will spawn its own thread, and it will provide an accessor to let the test access its `ClientContext` object, which the test can use to cancel the RPCs.

With this approach, the test can basically do this:

1. Cr [...]

2020-09-24 10:04 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180)* status: all files reviewed, 9 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5022 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrlNTo7MCIHDeSDxW_:-MHzZE8sAc2_BwdOsRRp:b-682mkp) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/test/cpp/end2end/xds_end2end_test.cc#L5022)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I made this a Drop test, which means it will run with FakeResolver which seem to fail.

I noticed the test file says "CDS depends on XdsResolver"; should this be XdsResolver only?


<!-- Sent from Reviewable.io -->

2020-09-24 18:02 UTC, markdroth requested changes
This is looking pretty good!  Most of my comments are minor; the only significant remaining thing is the drop stats change.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MI0Gh-B3TiNDhh4xT4h:b-pvc8jg)* status: all files reviewed, 12 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 267 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrbXmgDLiIrUn3n-ON:-MI07kaj2-S5XVFWDlLu:bi2zwww) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L267)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, one side effect of this is that if we fail due to the lack of a child picker, we will have incremented the counter but never decremented it.  I guess we need to explicitly decrement it if we fail due to the lack of a child picker.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 272 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrb4P68YBUmbjIarDe:-MI07Tmv7YQRm_9s-cou:b4ruo3g) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L272)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I see, i will do this change separately?   but will submit before this PR?
</blockquote></details>

That sounds good!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5022 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrlNTo7MCIHDeSDxW_:-MI09sq6CAEUbRjP5djX:bjzhkqc) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/test/cpp/end2end/xds_end2end_test.cc#L5022)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I made this a Drop test, which means it will run with FakeResolver which seem to fail.

I noticed the test file says "CDS depends on XdsResolver"; should this be XdsResolver only?
</blockquote></details>

This looks great!

As we discussed, yes, this will not work with the fake resolver, because that's an EDS-only flow, and the circuit breaker setting comes in the CDS response, so there's no way to inject it with the EDS-only flow.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1769 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI09NyN28Q3FctMEDho:-MI09NyOC9YPk2zgbKo2:bo27cu3) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L1769)):*
> ```cpp
> 
>  protected:
>   class TestRpc {
> ```

This class is actually fairly specific to the CircuitBreaking test.  I suggest defining it inside of that test instead of in the test fixture class.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1773 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI08gpM-RE4u1y8mC_N:-MI08gpM-RE4u1y8mC_O:b-6yo29o) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L1773)):*
> ```cpp
>     TestRpc() {}
> 
>     void SendRpc(std::unique_ptr<grpc::testing::EchoTestService::Stub>* stub) {
> ```

This can be passed in as a plain pointer, not a pointer to a `unique_ptr<>`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1775 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI08Zan68ADeIgpxvIF:-MI08Zao0smdblwdKZRv:bbxo7s) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L1775)):*
> ```cpp
>     void SendRpc(std::unique_ptr<grpc::testing::EchoTestService::Stub>* stub) {
>       sender_thread_ = std::thread([this, stub]() {
>         EchoResponse* response = new EchoResponse;
> ```

This doesn't have to be dynamically allocated; it can be a local variable.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1779 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI09-_a5ceRrK3ZPack:-MI09-_a5ceRrK3ZPacl:b-a6bqt) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L1779)):*
> ```cpp
>         request.mutable_param()->set_client_cancel_after_us(1 * 1000 * 1000);
>         request.set_message(kRequestMessage);
>         context_.set_wait_for_ready(true);
> ```

I don't think this is needed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1788 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI0EyAE7e2PJYVF9TjV:-MI0EyAE7e2PJYVF9TjW:b7oykem) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L1788)):*
> ```cpp
>         TestMultipleServiceImpl<::grpc::testing::EchoTestService::Service>*
>             service) {
>       while (!service->signal_client()) {
> ```

This looks like a global signal for the entire RPC service, not something that is set on a per-RPC basis.  Given that, there's no benefit in checking this once per RPC.

An alternative would be to change the RPC service impl to have a counter of the number of RPCs currently waiting for client cancel.  You can then wait for that number to reach `kMaxConcurrentRequests` before continuing.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5020 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI08wckDZMgSyjMVwDM:-MI08wckDZMgSyjMVwDN:bjtarc3) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L5020)):*
> ```cpp
>     rpcs[i].SendRpc(&stub_);
>   }
>   // Wait for all RPCs are in flight.
> ```

s/are/to be/
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5024 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI0927q3Ppy4Jr7knd6:-MI0927q3Ppy4Jr7knd7:b-o0vuwl) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L5024)):*
> ```cpp
>     rpcs[i].WaitForServerSignal(backends_[0]->backend_service());
>   }
>   // Send a non-wait_for_ready RPC which should fail, the error message tell us
> ```

The fact that this is not wait_for_ready is actually not important -- the same thing would happen even if it were wait_for_ready.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5026 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI0AA8e8b6keNbXGMkV:-MI0AA8e8b6keNbXGMkW:butfuk1) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L5026)):*
> ```cpp
>   // Send a non-wait_for_ready RPC which should fail, the error message tell us
>   // we hit the max concurrent requests limit.
>   Status status = SendRpc(RpcOptions().set_timeout_ms(0));
> ```

No need to override the timeout here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5031 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI0ACfJCW7bRrfvW7lF:-MI0ACfJCW7bRrfvW7lG:butfuk1) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L5031)):*
> ```cpp
>   // Cancel one RPC to allow another one through
>   rpcs[0].CancelRpc();
>   status = SendRpc(RpcOptions().set_timeout_ms(0));
> ```

No need to override the timeout here.


<!-- Sent from Reviewable.io -->

2020-09-25 02:22 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180)* status: all files reviewed, 12 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 267 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrbXmgDLiIrUn3n-ON:-MI23GoPAgKSAd7VqdDM:b-7tfmjp) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L267)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hmm, one side effect of this is that if we fail due to the lack of a child picker, we will have incremented the counter but never decremented it.  I guess we need to explicitly decrement it if we fail due to the lack of a child picker.
</blockquote></details>

added
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 272 at r2](https://reviewable.io/reviews/grpc/grpc/24180#-MHrb4P68YBUmbjIarDe:-MI22kZV-kDdef-CvVTa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7d9986989829fd7455a473afd8723d0cec3026e6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L272)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That sounds good!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-25 04:02 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180)* status: all files reviewed, 12 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 1769 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI09NyN28Q3FctMEDho:-MI2A1wL9jBQ8A2ZjNyA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L1769)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This class is actually fairly specific to the CircuitBreaking test.  I suggest defining it inside of that test instead of in the test fixture class.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1773 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI08gpM-RE4u1y8mC_N:-MI29LrK3h53nOpt2OeI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L1773)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be passed in as a plain pointer, not a pointer to a `unique_ptr<>`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1775 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI08Zan68ADeIgpxvIF:-MI29MDz3fxPVb7wc2UO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L1775)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't have to be dynamically allocated; it can be a local variable.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1779 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI09-_a5ceRrK3ZPack:-MI28XSZD_LBuWHyeFe_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L1779)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is needed.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1788 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI0EyAE7e2PJYVF9TjV:-MI29NcR3r11I8uIaCMi:b-7ql1td) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L1788)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This looks like a global signal for the entire RPC service, not something that is set on a per-RPC basis.  Given that, there's no benefit in checking this once per RPC.

An alternative would be to change the RPC service impl to have a counter of the number of RPCs currently waiting for client cancel.  You can then wait for that number to reach `kMaxConcurrentRequests` before continuing.
</blockquote></details>

fixed
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5020 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI08wckDZMgSyjMVwDM:-MI29W3h6Z4Pa7TyvjHO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L5020)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/are/to be/
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5024 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI0927q3Ppy4Jr7knd6:-MI29pAm7W7TXdx9zuqT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L5024)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The fact that this is not wait_for_ready is actually not important -- the same thing would happen even if it were wait_for_ready.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5026 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI0AA8e8b6keNbXGMkV:-MI29wfx215oxaWGaIJy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L5026)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to override the timeout here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5031 at r3](https://reviewable.io/reviews/grpc/grpc/24180#-MI0ACfJCW7bRrfvW7lF:-MI2A0Kp0ji4ftcBaFf-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/95a4692c8a6e615fcc5e7be01d27e98cad3dd51b/test/cpp/end2end/xds_end2end_test.cc#L5031)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to override the timeout here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-25 04:02 UTC, donnadionne reviewed
PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MI2QKP44Z0scEm_4_fs:b-h8gvr0)* status: all files reviewed, 12 unresolved discussions (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2020-09-25 15:50 UTC, markdroth requested changes
Aside from getting the other PR merged in, there are only minor cosmetic issues remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MI4xEcF3adkXOhMy6ts:b-m09xm0)* status: all files reviewed, 7 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 296 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4vXM06thPoEN9_Kw4:-MI4vXM06thPoEN9_Kw5:b-uc7ia2) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L296)):*
> ```cpp
>     eds_policy_->concurrent_requests_.FetchSub(1);
>     if (drop_stats_ != nullptr) {
>       // drop_stats_->AddUncategorizedDrops();
> ```

Need to uncomment this.
___
*[test/cpp/end2end/test_service_impl.h, line 173 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4vLjeDZH9j5k1u7-O:-MI4vLjeDZH9j5k1u7-P:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/test_service_impl.h#L173)):*
> ```objc
>         std::unique_lock<std::mutex> lock(mu_);
>         signal_client_ = true;
>         gpr_log(GPR_INFO, "DONNA did we increment");
> ```

Please remove.
___
*[test/cpp/end2end/test_service_impl.h, line 447 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4vHes--zyAGmz07al:-MI4vHetEvniNDzVaAAZ:b-nvoyj8) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/test_service_impl.h#L447)):*
> ```objc
>   TestServiceSignaller signaller_;
>   std::unique_ptr<std::string> host_;
>   uint64_t rpcs_waiting_for_client_cancel_;
> ```

Can just say `= 0` here, to avoid needing to initialize in each ctor.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2117 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4vpxrAF6sCrA3Os7w:-MI4vpxrAF6sCrA3Os7x:b-mepkb1) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/xds_end2end_test.cc#L2117)):*
> ```cpp
> class XdsResolverOnlyTest : public BasicTest {
>  protected:
>   class TestRpc {
> ```

I think this class can be defined directly inside of the `TEST_P(XdsResolverOnlyTest, CircuitBreaking)` block.  It is not relevant to any of the other tests.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2121 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4wNz4Ey2b5eMrvsMG:-MI4wNz522l4qQaAz2kU:b5jyob1) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/xds_end2end_test.cc#L2121)):*
> ```cpp
>     TestRpc() {}
> 
>     void SendRpc(grpc::testing::EchoTestService::Stub* stub) {
> ```

Suggest calling this `StartRpc()`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2298 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4wRZA0x8fX94wjtOh:-MI4wRZA0x8fX94wjtOi:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/xds_end2end_test.cc#L2298)):*
> ```cpp
>   }
>   // Wait for all RPCs to be in flight.
>   gpr_log(GPR_INFO, "DONNA new num is %d",
> ```

Please remove.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2322 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4x4Hd5apcrBzmfs-w:-MI4x4Hd5apcrBzmfs-x:blfj7wu) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/xds_end2end_test.cc#L2322)):*
> ```cpp
> }
> 
> // Tests that the old LB call is still used after the balancer address update as
> ```

This looks like an accidental paste.


<!-- Sent from Reviewable.io -->

2020-09-28 20:32 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180)* status: all files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 296 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4vXM06thPoEN9_Kw4:-MILKjJiAympIDAR3C3P:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L296)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to uncomment this.
</blockquote></details>

Done.
___
*[test/cpp/end2end/test_service_impl.h, line 173 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4vLjeDZH9j5k1u7-O:-MILKoZs5vhZAYBPywZI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/test_service_impl.h#L173)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[test/cpp/end2end/test_service_impl.h, line 447 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4vHes--zyAGmz07al:-MILL0m1E3xDFnIKJIad:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/test_service_impl.h#L447)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can just say `= 0` here, to avoid needing to initialize in each ctor.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2117 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4vpxrAF6sCrA3Os7w:-MILM-HE3SxDmPVNc4tw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/xds_end2end_test.cc#L2117)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this class can be defined directly inside of the `TEST_P(XdsResolverOnlyTest, CircuitBreaking)` block.  It is not relevant to any of the other tests.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2121 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4wNz4Ey2b5eMrvsMG:-MILM6QWCkAxeVBBhXSt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/xds_end2end_test.cc#L2121)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `StartRpc()`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2298 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4wRZA0x8fX94wjtOh:-MILMBBjCiwLhzuWxHkb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/xds_end2end_test.cc#L2298)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2322 at r4](https://reviewable.io/reviews/grpc/grpc/24180#-MI4x4Hd5apcrBzmfs-w:-MILMGQUExE7rmTl0g9B:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c3414a3032807e7919695dc7011cd86cee10119f/test/cpp/end2end/xds_end2end_test.cc#L2322)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This looks like an accidental paste.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-28 20:32 UTC, donnadionne reviewed
PR20240 merged, addressed code review comments. PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MILPgMWDpesb3VuXQHT:b-qcgoqe)* status: all files reviewed, 7 unresolved discussions (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2020-09-28 20:49 UTC, markdroth requested changes
This looks great!  I did another overall pass and found a few minor issues, but then we should be good to go.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MILTHaf1Uo2gRTFjOy8:b-q8ir50)* status: all files reviewed, 6 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 249 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILRkTd89aO5668M0Zn:-MILRkTd89aO5668M0Zo:by6za51) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L249)):*
> ```cpp
>   // Current concurrent number of requests;
>   Atomic<uint32_t> concurrent_requests_{0};
>   uint32_t max_concurrent_requests_;
> ```

There's no need for this field, since we can directly access it in `config_`, which we're already storing.
___
*[src/core/ext/xds/xds_api.h, line 182 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILSC8n9nRmALUnOOQR:-MILSC8n9nRmALUnOOQS:b-a94vqa) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/src/core/ext/xds/xds_api.h#L182)):*
> ```objc
>     absl::optional<std::string> lrs_load_reporting_server_name;
>     // Maximum number of outstanding requests can be made to the upstream
>     // cluster. If unset, assume std::numeric_limits<uint32_t>::max().
> ```

If unset, we should assume 1024.  In fact, why not make that the default value for this field?  Then it will never be unset in the first place.
___
*[src/core/ext/xds/xds_api.cc, line 1842 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILSMSECjuWJ567He6Y:-MILSMSECjuWJ567He6Z:b-fs79a5) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/src/core/ext/xds/xds_api.cc#L1842)):*
> ```cpp
>       cds_update.lrs_load_reporting_server_name.emplace("");
>     }
>     cds_update.max_concurrent_requests = 1024;
> ```

If you make this the default value for the field, then there's no need to explicitly set it here.
___
*[src/core/ext/xds/xds_api.cc, line 1864 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILS_afArmhMXQD42SQ:-MILS_afArmhMXQD42SR:b9wf8gs) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/src/core/ext/xds/xds_api.cc#L1864)):*
> ```cpp
>             cds_update.max_concurrent_requests =
>                 google_protobuf_UInt32Value_value(max_requests);
>             break;
> ```

I think this should be moved down one line.  Even if `max_requests` is not set in this block, we should still stop at the first block for priority `DEFAULT`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2290 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILQxAv3M6xJY4VG-ta:-MILQxAv3M6xJY4VG-tb:bn9kk6m) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/test/cpp/end2end/xds_end2end_test.cc#L2290)):*
> ```cpp
>   };
> 
>   // Tests switching over from one cluster to another.
> ```

This comment looks like an accidental cut-and-paste.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2325 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILT52D5EoJYMuHPk5X:-MILT52D5EoJYMuHPk5Y:bm4t8g1) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/test/cpp/end2end/xds_end2end_test.cc#L2325)):*
> ```cpp
>   EXPECT_EQ(status.error_message(), "Call dropped by load balancing policy");
>   // Cancel one RPC to allow another one through
>   rpcs[0].CancelRpc();
> ```

It might be a good idea to run this test 1000x under all of the sanitizers to make sure that it won't be flaky.  We need to be sure that the cancellation will have fully gone through and decremented the counter before the next RPC is started.


<!-- Sent from Reviewable.io -->

2020-09-28 23:16 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180)* status: all files reviewed, 6 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 249 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILRkTd89aO5668M0Zn:-MILn8252Y6wTU0_CbdA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L249)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need for this field, since we can directly access it in `config_`, which we're already storing.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 182 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILSC8n9nRmALUnOOQR:-MILpR_WCbbLpWRILigu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/src/core/ext/xds/xds_api.h#L182)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If unset, we should assume 1024.  In fact, why not make that the default value for this field?  Then it will never be unset in the first place.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1842 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILSMSECjuWJ567He6Y:-MILpSCc6hl-R8kQxms2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/src/core/ext/xds/xds_api.cc#L1842)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you make this the default value for the field, then there's no need to explicitly set it here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1864 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILS_afArmhMXQD42SQ:-MILplNB-ses9yiWe4KL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/src/core/ext/xds/xds_api.cc#L1864)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this should be moved down one line.  Even if `max_requests` is not set in this block, we should still stop at the first block for priority `DEFAULT`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-28 23:18 UTC, donnadionne reviewed
cleaned up! PTAL thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MIM-WkxBFUmu1VhTEt1:b-ogfgn3)* status: all files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 2290 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILQxAv3M6xJY4VG-ta:-MIM-MuvBcOCYdcMXr7F:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/test/cpp/end2end/xds_end2end_test.cc#L2290)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment looks like an accidental cut-and-paste.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2325 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILT52D5EoJYMuHPk5X:-MIM-JUICHmYpeNAE0pc:b-52nt2c) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/test/cpp/end2end/xds_end2end_test.cc#L2325)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It might be a good idea to run this test 1000x under all of the sanitizers to make sure that it won't be flaky.  We need to be sure that the cancellation will have fully gone through and decremented the counter before the next RPC is started.
</blockquote></details>

did tsan, msan, asan, all good


<!-- Sent from Reviewable.io -->

2020-09-28 23:41 UTC, markdroth requested changes
Sorry, found one last problem that I hadn't noticed earlier. :(  This is very close, though!

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MIM4qPh-xsawtIT6jGi:b-pdidu6)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 284 at r6](https://reviewable.io/reviews/grpc/grpc/24180#-MIM3v8p2rDdSOijgWgj:-MIM3v8p2rDdSOijgWgk:byt7d7a) ([raw file](https://github.com/grpc/grpc/blob/b3c96d0f083aef2986c4a8c8213a2c2fca6e92d5/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L284)):*
> ```cpp
>   // Check and see if we exceeded the max concurrent requests count.
>   uint32_t current = eds_policy_->concurrent_requests_.FetchAdd(1);
>   if (current >= eds_policy_->config_->max_concurrent_requests()) {
> ```

Hmm, actually, I just noticed one more problem here: The picker is not running in the WorkSerializer, but it's accessing the config from the EDS policy itself, which will change inside the WorkSerializer.  I don't think this is safe.

To fix this, I think that we'll need to have the picker store its own copy of the max_concurrent_requests limit, which can be set in its ctor.  And we'll need to change `UpdateLocked()` to generate a new picker whenever this value changes in a config update.
___
*[src/core/ext/xds/xds_api.h, line 182 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILSC8n9nRmALUnOOQR:-MIM4eN39qe7BZrU8Dmd:b-6nq1sp) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/src/core/ext/xds/xds_api.h#L182)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Given that it has a default value now, I think we can just remove the "If unset, assume 1024" comment.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2325 at r5](https://reviewable.io/reviews/grpc/grpc/24180#-MILT52D5EoJYMuHPk5X:-MIM4mbr5R5uzDT6arn0:b556ppi) ([raw file](https://github.com/grpc/grpc/blob/0040918f8f19907b2858e67f0c97f9fb47f11e83/test/cpp/end2end/xds_end2end_test.cc#L2325)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

did tsan, msan, asan, all good
</blockquote></details>

Awesome, thanks!


<!-- Sent from Reviewable.io -->

2020-09-29 03:07 UTC, donnadionne reviewed
fixed and retested!  Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MIMoyFDBYsUfYK7X0V3:b5djnre)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 284 at r6](https://reviewable.io/reviews/grpc/grpc/24180#-MIM3v8p2rDdSOijgWgj:-MIMkQ8WDMEzuEoQOqs3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3c96d0f083aef2986c4a8c8213a2c2fca6e92d5/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L284)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hmm, actually, I just noticed one more problem here: The picker is not running in the WorkSerializer, but it's accessing the config from the EDS policy itself, which will change inside the WorkSerializer.  I don't think this is safe.

To fix this, I think that we'll need to have the picker store its own copy of the max_concurrent_requests limit, which can be set in its ctor.  And we'll need to change `UpdateLocked()` to generate a new picker whenever this value changes in a config update.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-29 15:04 UTC, markdroth requested changes
The update logic needs one small tweak, then we're set!

> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MIPOEJN4xj2grKdtTve:b7o2j8x)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 521 at r7](https://reviewable.io/reviews/grpc/grpc/24180#-MIPNUsLCwVEOM2IavAS:-MIPNUsLCwVEOM2IavAT:b-oymkej) ([raw file](https://github.com/grpc/grpc/blob/b6d1370d33f9abf3a3a9455c20826c0966754fbe/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L521)):*
> ```cpp
>       config_->lrs_load_reporting_server_name() !=
>           old_config->lrs_load_reporting_server_name() ||
>       config_->max_concurrent_requests() !=
> ```

This doesn't look quite right.  If the `max_concurrent_requests` field changes but the `lrs_load_reporting_server_name` field does not, we want to update the picker, but we don't need to recreate the drop stats object.

I suggest something like this:

```
const bool lrs_server_changed =
    is_initial_update ||
    config_->lrs_load_reporting_server_name() !=
        old_config->lrs_load_reporting_server_name();
const bool max_concurrent_requests_changed =
    is_initial_update ||
    config_->max_concurrent_requests() !=
         old_config->max_concurrent_requests();
if (lrs_server_changed) {
  // replace drop stats
}
if (lrs_server_changed || max_concurrent_requests_changed) {
  MaybeUpdateDropPickerLocked();
}
```


<!-- Sent from Reviewable.io -->

2020-09-29 18:08 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 521 at r7](https://reviewable.io/reviews/grpc/grpc/24180#-MIPNUsLCwVEOM2IavAS:-MIQ2KI_EPcVPbOFzJ7L:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b6d1370d33f9abf3a3a9455c20826c0966754fbe/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L521)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't look quite right.  If the `max_concurrent_requests` field changes but the `lrs_load_reporting_server_name` field does not, we want to update the picker, but we don't need to recreate the drop stats object.

I suggest something like this:

```
const bool lrs_server_changed =
    is_initial_update ||
    config_->lrs_load_reporting_server_name() !=
        old_config->lrs_load_reporting_server_name();
const bool max_concurrent_requests_changed =
    is_initial_update ||
    config_->max_concurrent_requests() !=
         old_config->max_concurrent_requests();
if (lrs_server_changed) {
  // replace drop stats
}
if (lrs_server_changed || max_concurrent_requests_changed) {
  MaybeUpdateDropPickerLocked();
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-29 18:17 UTC, markdroth approved these changes
This looks great!

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MIQ4HotCLUkTwTcMuxd:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-29 21:27 UTC, donnadionne reviewed
need you to take another quick look on the last change.  thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180#-:-MIQkrILEv_RHUzG9b56:b-f8m3sl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2020-09-29 21:31 UTC, markdroth approved these changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24180)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-30 02:20 UTC, donnadionne commented
Basic Tests Python MacOS (also seen in fusion consistently)
Basic Tests Ruby MacOS (seen in fusion intermittently)

2020-09-30 02:21 UTC, merged