[3PI Support] Add base external account credentials class
grpc/grpc pull request #24208
Opened 2020-09-22 09:16 UTC by renkelvin

### Structure of 3PI Support
The implementation of 3PI support is organized as follows:
**1. Base external account credentials class [This PR]**
2. Subclasses to base external account credentials
3. Internal and public apis of external account credentials

### Description of this PR
This PR adds the base external account credentials.
- The base class is **similar** to [STSTokenFetcherCredentials](https://github.com/grpc/grpc/blob/889ea7cd096b82539842f0b46fe35594a0ac25bd/src/core/lib/security/credentials/oauth2/oauth2_credentials.cc#L537), which inherits from `grpc_oauth2_token_fetcher_credentials` and override `fetch_oauth2` to provide an access token.
- The main **difference** between the base class and`STSTokenFetcherCredentials` is that the base class makes a sequence of HTTP calls while `STSTokenFetcherCredentials` makes only one. So there is additional `TokenFetchContext` struct and multiple static methods implemented. Please see [go/grpc-sequenced-https-calls](go/grpc-sequenced-https-calls) for more details.

@ZhenLian Could you please help review this PR at language level? Please let me know if you have any questions. Thanks!

2020-09-24 07:06 UTC, ZhenLian reviewed
LGTM overall. I don't have much context so my review would be limited to the language level. You can find someone who might be more familiar with the context to review now :)

2020-09-24 17:20 UTC, renkelvin commented
Thanks @ZhenLian !

Hey @markdroth, this PR should be ready to review. Please take a look and let me if you have any questions!

2020-09-24 17:20 UTC, renkelvin commented on src/core/lib/security/credentials/external/external_account_credentials.cc
> +  scopes_ = scopes;
I think technically, it can be moved but I'm not sure if it's necessary.

2020-09-28 20:45 UTC, renkelvin reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @markdroth and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 2 at r1](https://reviewable.io/reviews/grpc/grpc/24208#-MILPFjXt3kcU4EX1gxR-r1-2:-MILSYDP2ljhO02yyGjU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6951e91b0482955047f3827f74af52701e092030/src/core/lib/security/credentials/external/external_account_credentials.h#L2)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

s/2019/2020
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-29 01:39 UTC, markdroth requested changes
I'm afraid that I'm not really seeing any significant improvement from the last PR.  This still seems very disorganized and I don't see any structure that tells me how what parts of the code are supposed to be doing what.

I've attempted to add some comments to indicate what you should be thinking about here, but I'm going to once again request that you find someone more senior who is fluent in C++ and can help you with these design issues.  If you can't do that, this is going to take a long time, because I don't have the cycles to put this kind of time into every review iteration.

I haven't reviewed the tests, since there were so many issues with the code itself.  I can do that later, once the code is in good shape.

I hope these comments are helpful.

> Reviewed 16 of 19 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MIMURvx9XC8TAwqnTYD:b-lsyfu7)* status: 18 of 19 files reviewed, 25 unresolved discussions (waiting on @markdroth, @renkelvin, and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 28 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIM7bqs9BDKGJMnPQ1p:-MIM7bqs9BDKGJMnPQ1q:b329lur) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L28)):*
> ```objc
> #include "src/core/lib/security/credentials/oauth2/oauth2_credentials.h"
> 
> using grpc_core::Json;
> ```

This is not allowed by the style guide:

https://google.github.io/styleguide/cppguide.html#Namespaces (see last bullet in that section)

It's also not actually necessary here, because all of your code is inside the `grpc_core` namespace anyway.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 34 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIM87rK8KO_7GXzuLfY:-MIM87rK8KO_7GXzuLfZ:b2tefmg) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L34)):*
> ```objc
> 
> // External account credentials json interface.
> struct ExternalAccountCredentialsOptions {
> ```

This struct can be in the `public` section of `ExternalAccountCredentials`.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 49 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMB33Z564ks01h8mCS:-MIMB33Z564ks01h8mCT:bi88h45) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L49)):*
> ```objc
> // This is a helper struct to pass information between multiple callback based
> // asynchronous calls.
> struct TokenFetchContext {
> ```

I think the design still needs work here.  It still appears to be structured as a single flat struct with a whole slew of fields shoved into it and a bunch of standalone functions that operate on that struct.  That approach would make sense for C code, but C++ code is expected to provide better encapsulation.  In general, you should seek to avoid exposing details where they aren't needed, both in terms of namespace and in terms of access control.

For example, the API currently appears to be exposing this entire struct to subclasses.  Is that actually necessary?  What functionality is going to be the same for all subclasses and what functionality will differ between them?  Can we provide an interface for subclasses to implement that gives the subclass only the information that it needs to do its subclass-specific work, and have the parent class or some other shared code take care of the rest of it?  I'm guessing that the only things that subclasses really need to do are populating the initial HTTP request and specifying the URI to talk to.  Do they actually need access to all of this information in order to do that?  If not, let's provide an interface that lets them do what they need without exposing them to all of the state that they don't care about.

On a related note, this struct seems to actually represent an in-flight token-fetch request, and most of the standalone functions in the .cc file are effectively methods to execute the request.  Given that, I think this should be a class, and I think those standalone functions should be methods of this class.

One option to consider would be to define this class as the thing that subclasses will define, with virtual methods to perform the parts that they need to do.  Another option would be to have the subclass implement a separate interface that is used by this class, and keep this class private within the .cc file.

If this struct does stay as part of the subclass API, it should be a member of `ExternalAccountCredentials`, in the `protected` section.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 58 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMD168CWPFBkjnFJuG:-MIMD168CWPFBkjnFJuH:b-lcfyr2) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L58)):*
> ```objc
>   grpc_millis deadline;
>   // The options and scopes carried from external account credentials.
>   ExternalAccountCredentialsOptions options;
> ```

There is no need to copy these two fields.  Instead, these can be const pointers to the fields in the `ExternalAccountCredentials` object, since we know that object will outlive this one.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 83 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMJSFx2SlTXi9QlhM0:-MIMJSFx2SlTXi9QlhM1:bx9zdo3) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L83)):*
> ```objc
>  protected:
>   // Subclasses of base external account credentials need to override this
>   // method to implement the specific subject token retrieval logic.
> ```

This needs to document exactly what subclasses are required to do.  For example, if there are particular fields that need to be populated or callbacks that need to be invoked when the token is retrieved, please indicate what those are.  The explanation should be clear enough that a reader can tell whether a given subclass implementation meets the requirements.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIM8NUKASbNm42wD6_q:-MIM8NUKASbNm42wD6_r:bsqsodc) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L86)):*
> ```objc
>   virtual void RetrieveSubjectToken(TokenFetchContext* ctx) = 0;
> 
>   ExternalAccountCredentialsOptions options_;
> ```

Data members must be private, as per the style guide.

https://google.github.io/styleguide/cppguide.html#Access_Control

If you want to make these accessible to subclasses, you should provide accessor methods.  Although from the implementation, it's not clear to me why these need to be exposed to begin with.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 97 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMCuoW5jHj-8PP5FWd:-MIMCuoW5jHj-8PP5FWe:b-y4n59) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L97)):*
> ```objc
>                     grpc_millis deadline) override;
> 
>   TokenFetchContext* ctx_;
> ```

This should be initialized to nullptr.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 45 at r1](https://reviewable.io/reviews/grpc/grpc/24208#-MILPFjXt3kcU4EX1gxQ-r1-45:-MIM8qqLCV1rOIZ9Na_5:b-6raswq) ([raw file](ht [...]

2020-09-29 22:04 UTC, renkelvin reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208)* status: 18 of 19 files reviewed, 25 unresolved discussions (waiting on @markdroth, @renkelvin, and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 49 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMB33Z564ks01h8mCS:-MIQiNip0JFue7LswrKe:b-2njely) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L49)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the design still needs work here.  It still appears to be structured as a single flat struct with a whole slew of fields shoved into it and a bunch of standalone functions that operate on that struct.  That approach would make sense for C code, but C++ code is expected to provide better encapsulation.  In general, you should seek to avoid exposing details where they aren't needed, both in terms of namespace and in terms of access control.

For example, the API currently appears to be exposing this entire struct to subclasses.  Is that actually necessary?  What functionality is going to be the same for all subclasses and what functionality will differ between them?  Can we provide an interface for subclasses to implement that gives the subclass only the information that it needs to do its subclass-specific work, and have the parent class or some other shared code take care of the rest of it?  I'm guessing that the only things that subclasses really need to do are populating the initial HTTP request and specifying the URI to talk to.  Do they actually need access to all of this information in order to do that?  If not, let's provide an interface that lets them do what they need without exposing them to all of the state that they don't care about.

On a related note, this struct seems to actually represent an in-flight token-fetch request, and most of the standalone functions in the .cc file are effectively methods to execute the request.  Given that, I think this should be a class, and I think those standalone functions should be methods of this class.

One option to consider would be to define this class as the thing that subclasses will define, with virtual methods to perform the parts that they need to do.  Another option would be to have the subclass implement a separate interface that is used by this class, and keep this class private within the .cc file.

If this struct does stay as part of the subclass API, it should be a member of `ExternalAccountCredentials`, in the `protected` section.
</blockquote></details>

Thanks for your suggestions and I understand that C++ code should provide better encapsulation.

I actually tried to encapsulate the whole logic into `ExternalAccountCredentials`, however it seems not very feasible. The reason is that `grpc_httpcli_post` method accepts a `grpc_closure*` as callback, which must be created with a `grpc_iomgr_cb_func`, so the callback functions have to be standalone to be a type of `grpc_iomgr_cb_func`.

It seems most of the issues are related to this one. So I'd like to know your thoughts before proceed.


<!-- Sent from Reviewable.io -->

2020-09-30 15:07 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208)* status: 18 of 19 files reviewed, 25 unresolved discussions (waiting on @renkelvin and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 49 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMB33Z564ks01h8mCS:-MIUWWlh53Iy1xDf8EsB:b-1vw0xv) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L49)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Thanks for your suggestions and I understand that C++ code should provide better encapsulation.

I actually tried to encapsulate the whole logic into `ExternalAccountCredentials`, however it seems not very feasible. The reason is that `grpc_httpcli_post` method accepts a `grpc_closure*` as callback, which must be created with a `grpc_iomgr_cb_func`, so the callback functions have to be standalone to be a type of `grpc_iomgr_cb_func`.

It seems most of the issues are related to this one. So I'd like to know your thoughts before proceed.
</blockquote></details>

The pre-bound parameter can be `this`, and the callback function can be a static method of the class, like this:

```
class MyClass {
 public:
  void DoHttpRequest() {
    GRPC_CLOSURE_INIT(&closure_, OnHttpRequestComplete, this, nullptr);
    // ...set up HTTP request...
    grpc_httpcli_post(..., &closure_, ...);
  }

 private:
  static void OnHttpRequestComplete(void* arg, grpc_error* error) {
    MyClass* self = static_cast<MyClass*>(arg);
    self->OnHttpRequestCompleteInternal(GRPC_ERROR_REF(error));
  }

  void OnHttpRequestCompleteInternal(grpc_error* error) {
    // handle callback here
  }

  grpc_closure closure_;
};
```


<!-- Sent from Reviewable.io -->

2020-10-01 22:29 UTC, renkelvin reviewed
It seems the diff is a bit inaccurate due to bulk changes. Added a few comments to help locate the changes.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MIaGcnNDAc_y8poLoeQ:b7su0t1)* status: 16 of 19 files reviewed, 25 unresolved discussions (waiting on @markdroth and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 160 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMSKC8EvUUQgc90pDr:-MIaCkOc49WCZPzXKCjh:buqat49) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.cc#L160)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It seems the diff is a bit off. Please search "~TokenFetchContext()" in page to see the new `TokenFetchContext` struct.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 246 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMPsid0SVcBO7QIjtp:-MIaDsIJ9wdHVyCtbPBU:buqat49) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.cc#L246)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It seems the diff is a bit off. Please search "~TokenFetchContext()" in page to see the new `TokenFetchContext` struct.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 263 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMOepm5DK9DWEMDdgo:-MIaDvqh8V6k1P1XEF76:bqul0qz) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.cc#L263)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It seems the diff is a bit off. You can search "TODO(chuanr)" in page to see the fix.


<!-- Sent from Reviewable.io -->

2020-10-01 22:51 UTC, duobianxing reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208)* status: 16 of 19 files reviewed, 40 unresolved discussions (waiting on @markdroth, @renkelvin, and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 97 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMCuoW5jHj-8PP5FWd:-MIa0jYJA3WO7_tjuFYH:b-8zhatq) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L97)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is this ctr_ used anywhere?
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 53 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaHHqBCOmGtq40K_0W:-MIaHHqBCOmGtq40K_0X:b-lmgq0c) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L53)):*
> ```
> scopes
> ```

why this is not part of "options"?
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 61 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaLjoX8r9hV5_nSKhh:-MIaLjoX8r9hV5_nSKhi:b-7crdja) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L61)):*
> ```
> TokenFetchContext
> ```

This looks like purely "HTTPRequestContext"? TokenFetchContext gives me the impression that there is something related the token.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 67 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaHRQr6Pkxq05nuFGs:-MIaHRQr6Pkxq05nuFGt:bj4g8xx) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L67)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> TokenFetchContext(grpc_httpcli_context* httpcli_context,
>                       grpc_polling_entity* pollent, grpc_millis deadline)
>         : httpcli_context(httpcli_context),
>           pollent(pollent),
>           deadline(deadline) {
>       closure = {};
>       response = {};
>     }
> ```
</details>


nit: will this work?

TokenFetchContext(grpc_httpcli_context* httpcli_context,
                      grpc_polling_entity* pollent, grpc_millis deadline)
        : httpcli_context(httpcli_context),
          pollent(pollent),
          deadline(deadline),
          closure({}),
          reponse({}), {
    }
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 89 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaHoD_9A9fd2DwBoYd:-MIaHoD_9A9fd2DwBoYe:bn0cn65) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L89)):*
> ```
> const TokenFetchContext* ctx,
> ```

Does caller need to pass in "ctx", isn't ctr_ already saved in the instance?

Also, can caller pass in nullptr "ctx"? If not, let's use "const TokenFetchContext& ctx" to forbidden that.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 97 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaF2ejAdoNpnfK1ME-:-MIaF2ejAdoNpnfK1ME0:b-z4yzip) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L97)):*
> ```
> fetch_oauth2
> ```

Where this function was referenced or called?
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 103 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIa6rcB8xtaiYtgbgfJ:-MIa6rcB8xtaiYtgbgfK:btnojaq) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L103)):*
> ```
> static void OnTokenExchange
> ```

 Why static here and couple functions below? Is this because of the grpc method we are using?
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 67 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIaEO1N1CHJputwdQtu:-MIaEO1N1CHJputwdQtv:b174ian) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.cc#L67)):*
> ```
> static
> ```
Question: why static here and above couple functions? 
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 42 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIa3dJk5MV0TeA3MKoE:-MIa3dJk5MV0TeA3MKoF:b-7njnro) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.cc#L42)):*
> ```
> GOOGLE_CLOUD_PLATFORM_DEFAULT_SCOPE
> ```

I suggest that when customers provide an empty list, we directly push_back to scopes_ and return here to avoid a copy later on
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 57 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaGsZ5AgypsCUNHKhc:-MIaGsZ5AgypsCUNHKhd:b-hkpc30) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.cc#L57)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> // The token fetching flow:
> // 1. Retrieve subject token - Call RetrieveSubjectToken() and get the subject
> // token in OnRetrieveSubjectToken().
> // 2. Token exchange - Make a token exchange call in TokenExchange() with the
> // subject token in #1. Get the response in OnTokenExchange().
> // 3. (Optional) Service account impersonation - Make a http call in
> // ServiceAccountImpersenate() with the access token in #2. Get an impersonated
> // access token in OnServiceAccountImpersenate().
> // 4. Return back the response that contains an access token in
> // FinishTokenFetch().
> // TODO(chuanr): Avoid starting the remaining requests if the channel gets shut
> // down.
> ```
</details>


Is there a test that does this flow explicitly? Maybe a test will help to demonstrate to reviewer on how to use this class?
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 85 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaFQjB6eolzz4npMY7:-MIaFQjB6eolzz4npMY8:b-mr82eg) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.cc#L85)):*
> ```cpp
> }
> 
> void ExternalAccountCredentials::TokenExchange(std::string subject_token) {
> ```

This function seems extremely long and hard for read later on.

I suggest grouping lines into smaller private functions and give meaningful names.

For example something like:

void ExternalAccountCredentials::TokenExchange(std::string subject_token) {
    
.....
     request.http.hdrs = GenereateHeaderFromTokenExchangeOptions(options_);
     std::string body = GenerateRequestBodyFromTokenExchangeOptions(options_);
....

     


}
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 170 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaKo1I8JVGIuuYLt8l:-MIaKo1I8JVGIuuYLt8m:btnpeba) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.cc#L170)):*
> ```cpp
> }
> 
> void ExternalAccountCredentials::ServiceAccountImpersenate() {
> ```

Nit: break down this function into smaller function so it is easy to ready & maintain?
___
*[src/core/lib/security/credentials/external/external_account_crede [...]

2020-10-01 22:52 UTC, duobianxing reviewed
Hello, this is Will. I took a look at the class first and put some comments. Mostly related to C++ language and plus a bit understanding of the flow from my side.

Feel free to let me know if you want to clarify some of my comments.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MIaMDemEJnarl-qsLaG:b55m3wv)* status: 16 of 19 files reviewed, 40 unresolved discussions (waiting on @markdroth, @renkelvin, and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-10-02 01:45 UTC, renkelvin reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208)* status: 16 of 19 files reviewed, 38 unresolved discussions (waiting on @duobianxing, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 97 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMCuoW5jHj-8PP5FWd:-MIaxcaS2FUifbCzyxhi:b-mh3y6x) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L97)):*
<details><summary><i>Previously, duobianxing (duobianxing) wrote…</i></summary><blockquote>

Is this ctr_ used anywhere?
</blockquote></details>

Yeah, `ctx_` is the http request context that will used in 1. retrieving subject token 2. sts token exchange 3. impersonate service account
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 53 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaHHqBCOmGtq40K_0W:-MIaaChO11kB_jo3NBm3:b3k98bl) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L53)):*
<details><summary><i>Previously, duobianxing (duobianxing) wrote…</i></summary><blockquote>

> ```
> scopes
> ```

why this is not part of "options"?
</blockquote></details>

It's based on the spec defined in go/guac-3pi. `options` is generated by gcloud given the 3rd party credentials. After that, developers can use it with different scopes.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 61 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaLjoX8r9hV5_nSKhh:-MIaw9tu1D9WISU_3KFM:b9y0m2q) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L61)):*
<details><summary><i>Previously, duobianxing (duobianxing) wrote…</i></summary><blockquote>

> ```
> TokenFetchContext
> ```

This looks like purely "HTTPRequestContext"? TokenFetchContext gives me the impression that there is something related the token.
</blockquote></details>

Done. Yeah, sounds better.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 67 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaHRQr6Pkxq05nuFGs:-MIare6eAvW1bfdKOHwG:b-clb0g9) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L67)):*
<details><summary><i>Previously, duobianxing (duobianxing) wrote…</i></summary><blockquote>

> ```
> TokenFetchContext(grpc_httpcli_context* httpcli_context,
>                       grpc_polling_entity* pollent, grpc_millis deadline)
>         : httpcli_context(httpcli_context),
>           pollent(pollent),
>           deadline(deadline) {
>       closure = {};
>       response = {};
>     }
> ```

nit: will this work?

TokenFetchContext(grpc_httpcli_context* httpcli_context,
                      grpc_polling_entity* pollent, grpc_millis deadline)
        : httpcli_context(httpcli_context),
          pollent(pollent),
          deadline(deadline),
          closure({}),
          reponse({}), {
    }

</blockquote></details>

Done. Yeah, seems better.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 89 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaHoD_9A9fd2DwBoYd:-MIawekc0IgNKSETTGHm:b-y1w55j) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L89)):*
<details><summary><i>Previously, duobianxing (duobianxing) wrote…</i></summary><blockquote>

> ```
> const TokenFetchContext* ctx,
> ```

Does caller need to pass in "ctx", isn't ctr_ already saved in the instance?

Also, can caller pass in nullptr "ctx"? If not, let's use "const TokenFetchContext& ctx" to forbidden that.
</blockquote></details>

Yeah, `ctx_` is already in the instance as a private data member. To expose it to the subclasses, we can either make a protected accessor, or pass it as a parameter of the virtual method.
I prefer the later approach since the access seems more limited. What do you think?
It can't be `nullptr`.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 97 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaF2ejAdoNpnfK1ME-:-MIabzHGEQEPo6BtJwlw:befgzha) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L97)):*
<details><summary><i>Previously, duobianxing (duobianxing) wrote…</i></summary><blockquote>

> ```
> fetch_oauth2
> ```

Where this function was referenced or called?
</blockquote></details>

It's called in `grpc_oauth2_token_fetcher_credentials::get_request_metadata` https://github.com/grpc/grpc/blob/cdb3b827a49f2d7b1173fb5c82c85c41ee0d95b1/src/core/lib/security/credentials/oauth2/oauth2_credentials.cc#L319
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 103 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIa6rcB8xtaiYtgbgfJ:-MIacsoW0OMskAIbgkPc:b-tbpis6) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L103)):*
<details><summary><i>Previously, duobianxing (duobianxing) wrote…</i></summary><blockquote>

> ```
> static void OnTokenExchange
> ```

 Why static here and couple functions below? Is this because of the grpc method we are using?
</blockquote></details>

Yeah, `grpc_httpcli_post` requires the callback function to be static. You can see Mark's comments (start with "The pre-bound parameter can be this") above.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 67 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIaEO1N1CHJputwdQtu:-MIauC-l4CVqQtay3CPT:brhc78v) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.cc#L67)):*
<details><summary><i>Previously, duobianxing (duobianxing) wrote…</i></summary><blockquote>

> ```
> static
> ```
Question: why static here and above couple functions? 
</blockquote></details>

Because `grpc_httpcli_post` requires a static function pointer as the callback.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 42 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIa3dJk5MV0TeA3MKoE:-MIaroQ3CvMuflI1Uwdg:b-3uxlk0) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.cc#L42)):*
<details><summary><i>Previously, duobianxing (duobianxing) wrote…</i></summary><blockquote>

> ```
> GOOGLE_CLOUD_PLATFORM_DEFAULT_SCOPE
> ```

I suggest that when customers provide an empty list, we directly push_back to scopes_ and return here to avoid a copy later on

</blockquote></details>

Added `std::move()` on I think so there shouldn't be a copy later on.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 57 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaGsZ5AgypsCUNHKhc:-MIasWv45XyFDnD3WoXI:b-xv5fde) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.cc#L57)):*
<details><summary><i>Previously, duobianxing (duobianxing) wrote…</i></summary><blockquote>

> ```
> // The token fetching flow:
> // 1. Retrieve subject token - Call RetrieveSubjectToken() and get the subject
> // token in OnRetrieveSubjectToken().
> // 2. Token exchange - Make a token exchange call in TokenExchange() with the
> // subject token in #1. Get the response in O [...]

2020-10-05 07:32 UTC, renkelvin reviewed
Thanks Will! I made some improvements based on your comments and our discussions. Please let me know if there is any questions!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MIrejCN9QCRcOPZBQrO:bcs6pv6)* status: 16 of 19 files reviewed, 38 unresolved discussions (waiting on @duobianxing, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 89 at r3](https://reviewable.io/reviews/grpc/grpc/24208#-MIaHoD_9A9fd2DwBoYd:-MIreR9bAi7Ho8IpM_Tb:b-qqdzp2) ([raw file](https://github.com/grpc/grpc/blob/bd4022ce5b12aa62abf46cfef4e81a70aaa72001/src/core/lib/security/credentials/external/external_account_credentials.h#L89)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Yeah, `ctx_` is already in the instance as a private data member. To expose it to the subclasses, we can either make a protected accessor, or pass it as a parameter of the virtual method.
I prefer the later approach since the access seems more limited. What do you think?
It can't be `nullptr`.
</blockquote></details>

Actually, I just realized that `ctx` can be null for local subject token fetch (like file-sourced credentials).


<!-- Sent from Reviewable.io -->

2020-10-07 18:07 UTC, duobianxing reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208)* status: 17 of 19 files reviewed, 25 unresolved discussions (waiting on @markdroth and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-10-07 18:08 UTC, duobianxing reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208)* status: 17 of 19 files reviewed, 25 unresolved discussions (waiting on @markdroth and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-10-07 20:09 UTC, duobianxing reviewed
> Reviewed 16 of 19 files at r1, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208)* status: all files reviewed, 25 unresolved discussions (waiting on @markdroth and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-10-07 20:11 UTC, duobianxing reviewed
LGTM, thanks for taking my input. The callback implementation looks really clean now.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJ3g0MQ5FC9Av7VsjyV:bcpyl4j)* status: all files reviewed, 25 unresolved discussions (waiting on @markdroth and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-10-07 20:11 UTC, duobianxing reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJ3g7Y1BrxvThylMR1a:bnfp4nl)* status: all files reviewed, 25 unresolved discussions (waiting on @markdroth and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-10-08 16:35 UTC, markdroth requested changes
This looks much cleaner now!  Remaining comments are relatively minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJ81pX-CYnkUtkEHjSU:bq6hm8o)* status: all files reviewed, 14 unresolved discussions (waiting on @renkelvin and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 49 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MIMB33Z564ks01h8mCS:-MJ81ldZ3zysfjSX7lGz:by8ldtc) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.h#L49)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done. The approach above looks cool.

Here is a summary of the changes to provide better encapsulation:
1. Eliminate the fields of `TokenFetchContext` that are not necessarily exposed to subclasses. It now only includes the required information to make http requests. Move the definition to `protected` section.
2. Make standalone functions the methods of `ExternalAccountCredentials`. This is a bit different with your suggestion (making them methods of `TokenFetchContext`), because `ExternalAccountCredentials` now holds the full information while `TokenFetchContext` includes the minimum shareable information.
3. Make data fields of `ExternalAccountCredentials` private (and no accessor introduced). Pass const pointers to `TokenFetchContext` and `ExternalAccountCredentialsOptions` to subclasses to retrieve subject token. These two should be the minimum information needed.
</blockquote></details>

Thanks, this looks *much* better!
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 29 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7uD5N2tyYLcByHIOF:-MJ7uD5N2tyYLcByHIOG:ba2rbrq) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.h#L29)):*
> ```objc
> 
> namespace grpc_core {
> namespace experimental {
> ```

No need to use `experimental` namespace for code inside of C-core.  That's only needed for public APIs.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 46 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7uJnq3u7yvcw_fooh:-MJ7uJnq3u7yvcw_fooi:b-4tahit) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.h#L46)):*
> ```objc
>     std::string token_url;
>     std::string token_info_url;
>     grpc_core::Json credential_source;
> ```

No need for `grpc_core::` prefix here, since you're already inside of that namespace.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 66 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7uaak6OnG148Du4uR:-MJ7uaak6OnG148Du4uS:b-vcvzch) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.h#L66)):*
> ```objc
>           pollent(pollent),
>           deadline(deadline),
>           closure({}),
> ```

There's no need to initialize either `closure` or `response` here.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 68 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7yhbb9Zomti-k12Dl:-MJ7yhbb9Zomti-k12Dm:b8lv83x) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.h#L68)):*
> ```objc
>           closure({}),
>           response({}) {}
>     ~HTTPRequestContext() { grpc_http_response_destroy(&response); }
> ```

I think you need to call `grpc_http_response_destroy()` after each individual HTTP request.  Otherwise, each response will just append data the previous response (both headers and body), which I don't think is what you want.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 89 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ82PBGBGrsWopSX_D6:-MJ82PBH-9PPz5jccy-D:b-et56ao) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.h#L89)):*
> ```objc
>       const HTTPRequestContext* ctx,
>       const ExternalAccountCredentialsOptions& options,
>       std::function<void(std::string, grpc_error*)> cb) = 0;
> ```

The subclass implementation of this method is going to do an HTTP request, right?  In that case, it will need to use the `grpc_closure` as a callback when the request is complete, since that's the API of `grpc_httpcli_post()`.  Is the subclass going to have to clean up anything when the HTTP request is done, before it invokes this callback to tell the base class that it's done?  If not, then using `std::function<>` doesn't really make sense, because that will be requiring the subclass to create its own `grpc_closure` callback function just for the purpose of invoking this `std::function<>`.

Instead, I suggest just pre-populating `ctx->closure` to call `OnRetrieveSubjectToken()` and telling the subclass to use that closure as the callback for the HTTP request.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 24 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7vaTD4Galpt7nCbbG:-MJ7vaTD4Galpt7nCbbH:b-gl1ppp) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.cc#L24)):*
> ```cpp
> #include "absl/time/clock.h"
> #include "absl/time/time.h"
> ```

Please re-add this blank line, as per the style guide.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 71 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ80M9G2mmi1215nFaN:-MJ80M9G2mmi1215nFaO:b-nd6rrt) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L71)):*
> ```cpp
>     grpc_httpcli_context* httpcli_context, grpc_polling_entity* pollent,
>     grpc_iomgr_cb_func response_cb, grpc_millis deadline) {
>   ctx_ = new HTTPRequestContext(httpcli_context, pollent, deadline);
> ```

Please check that `ctx_` was null before this.  Otherwise, if we accidentally start a new fetch while the previous one was still in flight, we will wind up causing a memory leak.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 74 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7w65p8SKOWpOZyIdv:-MJ7w65p8SKOWpOZyIdw:bmnslzz) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L74)):*
> ```cpp
>   metadata_req_ = metadata_req;
>   response_cb_ = response_cb;
>   auto cb =
> ```

Suggest writing this as a lambda for clarity:

```
auto cb = [this](std::string token, grpc_error* error) {
  OnRetrieveSubjectTokenInternal(token, error);
};
```
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 93 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7x26U8_8cw5cjueut:-MJ7x26U8_8cw5cjueuu:b-3602z4) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L93)):*
> ```cpp
>   grpc_uri* uri = grpc_uri_parse(options_.token_url, false);
>   if (uri == nullptr) {
>     FinishTokenFetch(GRPC_ERROR_CREATE_FROM_STATIC_STRING(
> ```

Need to use `GRPC_ERROR_CREATE_FROM_COPIED_STRING()` if the string is not actually static.

Same thing throughout.
___
*[src/core/lib/security/credentials/external [...]

2020-10-08 20:25 UTC, renkelvin reviewed
Thanks for your review!

btw, it seems I'm not able to trigger the CI flow because my limited access to grpc/grpc repo. Is there anything should be fixed?

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJ3g2Zg9HWSeczMg9oC:b-cmb11r)* status: all files reviewed, 14 unresolved discussions (waiting on @markdroth and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 29 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7uD5N2tyYLcByHIOF:-MJ8M3MvDSyj1Di2DvrY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.h#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to use `experimental` namespace for code inside of C-core.  That's only needed for public APIs.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 46 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7uJnq3u7yvcw_fooh:-MJ8NuTJ46B_ydc7IrUp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `grpc_core::` prefix here, since you're already inside of that namespace.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 66 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7uaak6OnG148Du4uR:-MJ8OqMP24Xk9f3yIDgQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.h#L66)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need to initialize either `closure` or `response` here.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 68 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7yhbb9Zomti-k12Dl:-MJ8p8CuAfl6L-sP6b7j:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.h#L68)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you need to call `grpc_http_response_destroy()` after each individual HTTP request.  Otherwise, each response will just append data the previous response (both headers and body), which I don't think is what you want.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/external_account_credentials.h, line 89 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ82PBGBGrsWopSX_D6:-MJ8p8ZSDVd_4Wx5nsul:b-xld3kd) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.h#L89)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The subclass implementation of this method is going to do an HTTP request, right?  In that case, it will need to use the `grpc_closure` as a callback when the request is complete, since that's the API of `grpc_httpcli_post()`.  Is the subclass going to have to clean up anything when the HTTP request is done, before it invokes this callback to tell the base class that it's done?  If not, then using `std::function<>` doesn't really make sense, because that will be requiring the subclass to create its own `grpc_closure` callback function just for the purpose of invoking this `std::function<>`.

Instead, I suggest just pre-populating `ctx->closure` to call `OnRetrieveSubjectToken()` and telling the subclass to use that closure as the callback for the HTTP request.
</blockquote></details>

The subclass implementation is a bit more complex than an HTTP request.

For url-sourced credentials, it's mostly making a single HTTP request, and retrieving subject token from the response. What you suggest should work.

For file-sourced credentials, the subject token will be retrieved from a local file so there won't be HTTP calls.

For aws-sourced credentials, there would be multiple HTTP requests. After that, we need to manually construct the subject token and pass it back. So passing the response back via `grpc_closure` may not work.

So I think providing a callback that directly accepts the subject token could be more generic for different types of credentials.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 24 at r2](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7vaTD4Galpt7nCbbG:-MJ8MVDa-Ij_MfnNnZSI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/85d1ec766ca1b6e74875542d9030d494e58c8650/src/core/lib/security/credentials/external/external_account_credentials.cc#L24)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please re-add this blank line, as per the style guide.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 71 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ80M9G2mmi1215nFaN:-MJ8PMfHCtjjoZH3fQ6G:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L71)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please check that `ctx_` was null before this.  Otherwise, if we accidentally start a new fetch while the previous one was still in flight, we will wind up causing a memory leak.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 74 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7w65p8SKOWpOZyIdv:-MJ8MuKe8MW0UAY1gOEs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L74)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as a lambda for clarity:

```
auto cb = [this](std::string token, grpc_error* error) {
  OnRetrieveSubjectTokenInternal(token, error);
};
```
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 93 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ7x26U8_8cw5cjueut:-MJ8Pg6L7GsdjHZTM8_m:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L93)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to use `GRPC_ERROR_CREATE_FROM_COPIED_STRING()` if the string is not actually static.

Same thing throughout.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 183 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ8-2j42DA9A4YOLwMg:-MJ8Qg-z4jdghgtIHWga:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L183)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of just including the string from the original error, you should actually link in the original error object, like this:

```
GRPC_ERROR_CREATE_REFERENCING_FROM_STATIC_STRING(
    "Invalid token exchange response",  &error, 1)
```

Same thing throughout.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, lin [...]

2020-10-09 14:49 UTC, markdroth requested changes
I've triggered the tests to be run.  It looks like credentials_test is crashing in several of the tests.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJCpbMA9GfCusqZCZuD:b-t7uzfl)* status: all files reviewed, 5 unresolved discussions (waiting on @renkelvin and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 71 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ80M9G2mmi1215nFaN:-MJ9QV0WAHNBxscBXwtP:bj7hckt) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L71)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If `ctx_` is not null when we enter this function, it's a bug, and we should probably just fail immediately.  The way you have this code written right now, it will not create a new context, but it will start a new request with the pre-existing context, which may be destroyed at any time.  This is not safe.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 298 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ80DRx0avZxbQITP4D:-MJ9TFV59_hTjLPjBkXf:bzbbtvc) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L298)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

According to rule3 of https://github.com/grpc/grpc/blob/master/doc/core/grpc-error.md#ownership-rules, the ownership of `error` should be passed to `GRPC_LOG_IF_ERROR()`.  Since we still need access to the `error` later, we need to increase the ref count by 1 here. Did I misunderstand something here?
</blockquote></details>

Oh, looks like you're right.  For some reason I didn't think `GRPC_LOG_IF_ERROR()` took a ref.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 148 at r5](https://reviewable.io/reviews/grpc/grpc/24208#-MJ9R39XAPAynkb1G676:-MJ9R39XAPAynkb1G677:b4z4ulz) ([raw file](https://github.com/grpc/grpc/blob/665b69374a871b2bc166f7805ed5cdf235c94ae8/src/core/lib/security/credentials/external/external_account_credentials.cc#L148)):*
> ```cpp
>   grpc_resource_quota* resource_quota =
>       grpc_resource_quota_create("external_account_credentials");
>   grpc_http_response_destroy(&ctx_->response);
> ```

You also need to reset the fields in the response.  If you leave them uninitialized, the next request will try to append to what's there, because it uses the counters there to know to append.

Same thing for every request.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 280 at r5](https://reviewable.io/reviews/grpc/grpc/24208#-MJ9Sxb5EPd-bGTwfFul:-MJ9Sxb5EPd-bGTwfFum:b8p09g4) ([raw file](https://github.com/grpc/grpc/blob/665b69374a871b2bc166f7805ed5cdf235c94ae8/src/core/lib/security/credentials/external/external_account_credentials.cc#L280)):*
> ```cpp
>   if (!absl::ParseTime(absl::RFC3339_full, expire_time, &t, nullptr)) {
>     FinishTokenFetch(GRPC_ERROR_CREATE_FROM_COPIED_STRING(
>         absl::StrFormat("Invalid expire time of service "
> ```

This is a static string.  No need for `absl::StrFormat()`, and you can use `GRPC_ERROR_CREATE_FROM_STATIC_STRING()`.


<!-- Sent from Reviewable.io -->

2020-10-09 23:30 UTC, markdroth requested changes
We don't really use `run_tests.py` anymore.  But in this case, you're only touching code that is used in a single test, so you can just manually run that test with bazel.  Try the following commands:

```
bazel test test/core/security:credentials_test
bazel test -c dbg --config=asan test/core/security:credentials_test
bazel test -c dbg --config=tsan test/core/security:credentials_test
bazel test -c dbg --config=msan test/core/security:credentials_test
bazel test -c dbg --config=ubsan test/core/security:credentials_test
```

With regard to the PR, this is looking very good.  Just one issue remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJEgU-X-5Vh3VMTp9Da:b-z45i3a)* status: all files reviewed, 3 unresolved discussions (waiting on @renkelvin and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 71 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ80M9G2mmi1215nFaN:-MJEfo0M3u78AaZc5WZm:bhko089) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L71)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Good point.

While if `ctx_` is not null, we may want to clean up the previous context and start the new token fetch instead of failing out. Otherwise, the token fetch will be always blocked.
</blockquote></details>

It's not safe to simply delete the existing context, since there may still be callbacks pending that will use it.

I think this should just be an assertion.  `ctx_` must never be non-null when we get here, or we know that there's a serious bug, and we can just crash if that happens.


<!-- Sent from Reviewable.io -->

2020-10-10 07:56 UTC, renkelvin reviewed
There is a failure("MemorySanitizer: use-of-uninitialized-value") with `msan` testing, while it seems to be an existing issue on master branch. The other tests passed locally.

Could you please trigger the CI again? If it passes then this pr should be ready! Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJGU4nRAMDGUd5Itlag:b3hv06a)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth and @ZhenLian)

___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 71 at r4](https://reviewable.io/reviews/grpc/grpc/24208#-MJ80M9G2mmi1215nFaN:-MJGMJWw5ki4MP4kGPh2:b-xrccz2) ([raw file](https://github.com/grpc/grpc/blob/8c0f91c698bd06e9ecbd16a50cff0f3029b1a68b/src/core/lib/security/credentials/external/external_account_credentials.cc#L71)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not safe to simply delete the existing context, since there may still be callbacks pending that will use it.

I think this should just be an assertion.  `ctx_` must never be non-null when we get here, or we know that there's a serious bug, and we can just crash if that happens.
</blockquote></details>

Done. Yeah, make sense.


<!-- Sent from Reviewable.io -->

2020-10-12 18:49 UTC, markdroth approved these changes
The code looks great!  I've triggered the tests again, so let's see what they show.

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJT8NUV3Lq0_yneaUfz:b-vgf9sc)* status: all files reviewed, 2 unresolved discussions (waiting on @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-10-12 21:33 UTC, renkelvin reviewed
It seems there is an assertion failed on Windows specifically, and I think this is what's happening.

There are 4 main checks to make sure the happy flow works as intended:
In `test_external_account_creds_success`:
1.Start token fetch. A valid access token should be returned.
2.Start a second token fetch. The token cached in 1 should be returned and there should be no http calls.

In `test_external_account_creds_success_with_service_account_impersonation`:
3.Start token fetch. A valid impersonated access token should be returned.
4.Start a second token fetch. The token cached in 3 should be returned and there should be no http calls.

The step 4 fails because the step 3 takes longer so step 4 starts before a valid token is cached, so an http call will be made.

To resolve this, I think we can just remove step 4 because its purpose is to make sure the cache mechanism works, which is duplicate with step 2. Please let me know if you have any concerns. Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJTet23AVYh2P4bpT2d:b-72fyl9)* status: all files reviewed, 2 unresolved discussions (waiting on @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-10-12 22:10 UTC, markdroth approved these changes
This looks good.  Please squash your commits.  Once you do that, I'll trigger one more run of the tests, and then we can get this merged.

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJTqqK81F3G6sUUbHG-:bbl2yxz)* status: all files reviewed, 2 unresolved discussions (waiting on @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-10-13 00:06 UTC, renkelvin reviewed
Done, commits squashed.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24208#-:-MJUGomP-LwsIcUZaJC7:bjiqb0x)* status: all files reviewed, 2 unresolved discussions (waiting on @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-10-13 17:27 UTC, markdroth commented
All tests are green!  Merging now.

2020-10-13 17:27 UTC, merged

2020-10-13 18:13 UTC, renkelvin commented
Awesome, thanks!