Wrapping DroppedRequestsMap inside a DroppedRequests strcuture which
grpc/grpc pull request #24240
Opened 2020-09-24 23:58 UTC by donnadionne

contains the map as well as uncategorized drops.

This will be useful for cirucuit breaking drops (separate PR).

@yashykt

2020-09-25 15:33 UTC, markdroth requested changes
Just one issue here, which is about using an atomic for the uncategorized drops.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24240#-:-MI4t5565V0-H06Jwu42:bhy6h5h)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_client_stats.h, line 105 at r1](https://reviewable.io/reviews/grpc/grpc/24240#-MI4qo8n3TUbIpTu97ox:-MI4qo8n3TUbIpTu97oy:bni1bye) ([raw file](https://github.com/grpc/grpc/blob/f9eae8e4187e1bb37901b694b6332a2ce1da33b9/src/core/ext/xds/xds_client_stats.h#L105)):*
> ```objc
>   // uncategorized_drops, and dropped_requests map.
>   struct DroppedRequests {
>     uint64_t uncategorized_drops = 0;
> ```

We want this field to be an atomic in the non-snapshot form, so that we don't need to acquire the mutex in order to increment it.

I suggest the following API:

```
 public:
  using DroppedRequestsCategoryMap = std::map<std::string /* category */, uint64_t>;
  struct Snapshot {
    uint64_t uncategorized_drops = 0;
    DroppedRequestsCategoryMap categorized_drops;
  };

  Snapshot GetSnapshotAndReset();

 private:
  Atomic<uint64_t> uncategorized_drops_{0};
  Mutex mu_;  // Protects categorized_drops_.
  DroppedRequestsCategoryMap categorized_drops_;
```

See similar structure in `XdsClusterLocalityStats` below.
___
*[src/core/ext/xds/xds_client_stats.cc, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/24240#-MI4s-qJ0YzaI3SBIq5w:-MI4s-qK-W8cPTbWdDFK:b-amf5t) ([raw file](https://github.com/grpc/grpc/blob/f9eae8e4187e1bb37901b694b6332a2ce1da33b9/src/core/ext/xds/xds_client_stats.cc#L58)):*
> ```cpp
> 
> void XdsClusterDropStats::AddUncategorizedDrops() {
>   ++dropped_requests_.uncategorized_drops;
> ```

If this is not an atomic, then it's not safe to increment it without holding the mutex.


<!-- Sent from Reviewable.io -->

2020-09-25 20:44 UTC, donnadionne reviewed
PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24240#-:-MI6-evFDydIho01Og2p:bxtaph9)* status: all files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_client_stats.h, line 105 at r1](https://reviewable.io/reviews/grpc/grpc/24240#-MI4qo8n3TUbIpTu97ox:-MI6-SaX0Ajag_6Kr7JL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f9eae8e4187e1bb37901b694b6332a2ce1da33b9/src/core/ext/xds/xds_client_stats.h#L105)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We want this field to be an atomic in the non-snapshot form, so that we don't need to acquire the mutex in order to increment it.

I suggest the following API:

```
 public:
  using DroppedRequestsCategoryMap = std::map<std::string /* category */, uint64_t>;
  struct Snapshot {
    uint64_t uncategorized_drops = 0;
    DroppedRequestsCategoryMap categorized_drops;
  };

  Snapshot GetSnapshotAndReset();

 private:
  Atomic<uint64_t> uncategorized_drops_{0};
  Mutex mu_;  // Protects categorized_drops_.
  DroppedRequestsCategoryMap categorized_drops_;
```

See similar structure in `XdsClusterLocalityStats` below.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client_stats.cc, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/24240#-MI4s-qJ0YzaI3SBIq5w:-MI6-TPRDG_U-0IbyZPe:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f9eae8e4187e1bb37901b694b6332a2ce1da33b9/src/core/ext/xds/xds_client_stats.cc#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If this is not an atomic, then it's not safe to increment it without holding the mutex.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-25 22:46 UTC, markdroth requested changes
Just a couple of minor nits remaining!  This looks really good!

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24240#-:-MI6RP6h649edPkBmhdd:bona5ji)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_client_stats.h, line 104 at r2](https://reviewable.io/reviews/grpc/grpc/24240#-MI6QSWX82gRDakNTZyE:-MI6QSWX82gRDakNTZyF:b-v648h4) ([raw file](https://github.com/grpc/grpc/blob/fac70812d49b2653cf747baec6efc848bc92d1ac/src/core/ext/xds/xds_client_stats.h#L104)):*
> ```objc
>   // The total number of requests dropped for any reason is the sum of
>   // uncategorized_drops, and dropped_requests map.
>   using DroppedRequestsCategoryMap =
> ```

Suggest renaming this to `CategorizedDropsMap`.
___
*[src/core/ext/xds/xds_client_stats.h, line 106 at r2](https://reviewable.io/reviews/grpc/grpc/24240#-MI6QHDF59WMw0CUxFPv:-MI6QHDF59WMw0CUxFPw:b-b1pch2) ([raw file](https://github.com/grpc/grpc/blob/fac70812d49b2653cf747baec6efc848bc92d1ac/src/core/ext/xds/xds_client_stats.h#L106)):*
> ```objc
>   using DroppedRequestsCategoryMap =
>       std::map<std::string /* category */, uint64_t>;
>   struct Snapshot {
> ```

Suggest defining `operator+=()` for this struct, similar to how it's done for `XdsClusterLocalityStats` below.  That will make the code in `XdsClient::BuildLoadReportSnapshotLocked()` a little simpler.


<!-- Sent from Reviewable.io -->

2020-09-28 03:58 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24240)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_client_stats.h, line 104 at r2](https://reviewable.io/reviews/grpc/grpc/24240#-MI6QSWX82gRDakNTZyE:-MIHr9LsBy-qZFbsI-2U:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fac70812d49b2653cf747baec6efc848bc92d1ac/src/core/ext/xds/xds_client_stats.h#L104)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest renaming this to `CategorizedDropsMap`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client_stats.h, line 106 at r2](https://reviewable.io/reviews/grpc/grpc/24240#-MI6QHDF59WMw0CUxFPv:-MIHrA7Q0osL_diQaeMZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fac70812d49b2653cf747baec6efc848bc92d1ac/src/core/ext/xds/xds_client_stats.h#L106)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest defining `operator+=()` for this struct, similar to how it's done for `XdsClusterLocalityStats` below.  That will make the code in `XdsClient::BuildLoadReportSnapshotLocked()` a little simpler.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-28 15:12 UTC, markdroth approved these changes
This looks great!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24240#-:-MIKGMjkDzv-dtU4Ox7I:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-28 19:11 UTC, donnadionne commented
known issue #23822

2020-09-28 19:11 UTC, merged