Setting timeout in method config.
grpc/grpc pull request #24328
Opened 2020-10-06 06:38 UTC by donnadionne

@karthikravis

2020-10-06 06:40 UTC, donnadionne commented
Just an initial review; still to do:
- get max_stream_duration from HttpConnectionManager
- test

2020-10-06 16:23 UTC, markdroth requested changes
This looks like a good start!

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MIyi3DU7bx0IWc8uKsn:bntdxje)* status: all files reviewed, 13 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/service_config.cc, line 198 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyWM4p41aXNoMSoqIH:-MIyWM4p41aXNoMSoqII:bqzals6) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/filters/client_channel/service_config.cc#L198)):*
> ```cpp
>           "field:name error:method name populated without service name");
>     }
>     return "/";
> ```

This change is incorrect and should not be necessary.  When this method returns the empty string, the resulting method config will be saved in `default_method_config_vector_`, and it will be returned by `GetMethodParsedConfigVector()` when there is no more precise match (which there won't be in the case you're adding here).
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 153 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyd6hu1JI1Kz5pRV2A:-MIyd6hu1JI1Kz5pRV2B:b-7pk6n7) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L153)):*
> ```cpp
>     }
> 
>     RefCountedPtr<ServiceConfig> CreateMethodConfig(const std::string& timeout);
> ```

This method should be private.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 317 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIydUulE0m1oyYwhdX-:-MIydUulE0m1oyYwhdX0:b-6h7uc4) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L317)):*
> ```cpp
>       "  } ]\n"
>       "}",
>       timeout.empty() ? "0s" : timeout);
> ```

We should not default to "0s" here.

If the timeout in the route is unset, we should fall back to using the `max_stream_duration` value in the HttpConnectionManager config in the LDS response.  If that is also unset, then we should leave the timeout unset.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 318 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIydL8b0qmBQT-sjY9v:-MIydL8b0qmBQT-sjY9w:b-wv2mtx) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L318)):*
> ```cpp
>       "}",
>       timeout.empty() ? "0s" : timeout);
>   grpc_error* error = GRPC_ERROR_NONE;
> ```

This should be passed in by the caller, so that if the service config creation fails, the error is communicated back to the caller.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 500 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyffhVDssX-zrbT7IH:-MIyffhVDssX-zrbT7II:b-w5kjqq) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L500)):*
> ```cpp
>     ClusterState* cluster_state = it->second->Ref().release();
>     CallConfig call_config;
>     call_config.method_configs =
> ```

There's a lifetime issue here: the config selector may go away before the call is done with the parsed method config vector, in which case the service config will be unreffed and destroyed while the call is still using the vector.

I've sent you #24335 to fix this.  Once that's merged, you'll need to add this line here:

```
call_config.service_config = entry.method_config;
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 502 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIygqi77fTKbf4wbDrW:-MIygqi77fTKbf4wbDrX:b4amb5w) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L502)):*
> ```cpp
>     call_config.method_configs =
>         entry.method_config->GetMethodParsedConfigVector(
>             grpc_slice_from_static_string("/"));
> ```

I think you can just use `grpc_empty_slice()` here.  The value really doesn't matter, since it will never match anything.
___
*[src/core/ext/xds/xds_api.h, line 125 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyNaSB4iqE5IFmqOI1:-MIyNaSB4iqE5IFmqOI2:b-bxq0di) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/xds/xds_api.h#L125)):*
> ```objc
>     };
>     std::vector<ClusterWeight> weighted_clusters;
>     std::string timeout = "";
> ```

No need for `= ""`, since that's the default value.
___
*[src/core/ext/xds/xds_api.h, line 125 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyNsmxEeY8JqsPADQX:-MIyNsmxEeY8JqsPADQY:bj02kej) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/xds/xds_api.h#L125)):*
> ```objc
>     };
>     std::vector<ClusterWeight> weighted_clusters;
>     std::string timeout = "";
> ```

Please add a comment indicating the expected format of the value.
___
*[src/core/ext/xds/xds_api.h, line 126 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyNqXR5Wlnwen0p4Y-:-MIyNcvfDjy77AUrAFH3:b2ue2g) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/xds/xds_api.h#L126)):*
> ```objc
>     std::vector<ClusterWeight> weighted_clusters;
>     std::string timeout = "";
>     //std::string timeout = absl::StrFormat("%.9fs", 1 + 1 / 1.0e9);
> ```

I assume this was just for testing and can be removed.
___
*[src/core/ext/xds/xds_api.cc, line 1577 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyOBOo9Ma2rMZlJlOF:-MIyOBOp0UuWY2I1-BZS:bna98yx) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/xds/xds_api.cc#L1577)):*
> ```cpp
>   }
>   if (!*ignore_route) {
>     if (envoy_config_route_v3_RouteAction_has_max_stream_duration(
> ```

This check isn't necessary, because `envoy_config_route_v3_RouteAction_max_stream_duration()` below will return null if the field is not present.

Same thing for all of the fields here -- don't call the `*_has_*()` method, just get the field and see if it's null.
___
*[src/core/ext/xds/xds_api.cc, line 1589 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyOqcdAMNv-635HZTO:-MIyOqcdAMNv-635HZTP:brtlzv3) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/xds/xds_api.cc#L1589)):*
> ```cpp
>                 max_stream_duration);
>         route->timeout = absl::StrFormat(
>             "%.9fs", google_protobuf_Duration_seconds(duration) +
> ```

Formatting this as a float is going to lose precision, which is exactly what the proto tries to avoid by storing the nanos as an integer.  Instead, please format as an integer, using something like this:

```
absl::StrFormat("%d.%09d", google_protobuf_Duration_seconds(duration), google_protobuf_Duration_nanos(duration))
```
___
*[src/core/ext/xds/xds_api.cc, line 1598 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyWA2f8vvEirVh8MPl:-MIyWA2gDQHdJIff-AF8:blxdb2a) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/xds/xds_api.cc#L1598)):*
> ```cpp
>                 max_stream_duration);
>         route->timeout = absl::StrFormat(
>             "%.9fs", google_protobuf_Duration_seconds(duration) +
> ```

Same floating point issue here.
___
*[src/core/ext/xds/xds_api.cc, line 1738 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyhryc6h0oKvsGYpyc:-MIyhryc6h0oKvsGYpyd:b5tzw7d) ([raw file](https://github.com/grpc/grpc/blob/d64f56638e794f6a4c8d67eb57a7992f13c24889/src/core/ext/xds/xds_api.cc#L1738)):*
> ```cpp
>           "Could not parse HttpConnectionManager config from ApiListener");
>     }
>     // Found inli [...]

2020-10-08 08:55 UTC, donnadionne reviewed
addressed your comments, please let me know if there is any major left.  Working on tests now...  Thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJ6PiW32VyBC0aQEhbP:b-pq05r)* status: all files reviewed, 13 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/service_config.cc, line 198 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyWM4p41aXNoMSoqIH:-MJ5O1ug-081MCJce2-z:b-td0cvs) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/filters/client_channel/service_config.cc#L198)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This change is incorrect and should not be necessary.  When this method returns the empty string, the resulting method config will be saved in `default_method_config_vector_`, and it will be returned by `GetMethodParsedConfigVector()` when there is no more precise match (which there won't be in the case you're adding here).
</blockquote></details>

removed and made a different change in the same file to make sure default_method_config_vector_ is returned in all paths are empty case
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 153 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyd6hu1JI1Kz5pRV2A:-MJ5OaK9C4LrS3icySnk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L153)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This method should be private.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 317 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIydUulE0m1oyYwhdX-:-MJ5d2Y29_3_M0fYPoWz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L317)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should not default to "0s" here.

If the timeout in the route is unset, we should fall back to using the `max_stream_duration` value in the HttpConnectionManager config in the LDS response.  If that is also unset, then we should leave the timeout unset.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 318 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIydL8b0qmBQT-sjY9v:-MJ5tvQiEMwCrqbrlDOQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L318)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be passed in by the caller, so that if the service config creation fails, the error is communicated back to the caller.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 500 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyffhVDssX-zrbT7IH:-MJ5VtmN9bwRYLedlM2M:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L500)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's a lifetime issue here: the config selector may go away before the call is done with the parsed method config vector, in which case the service config will be unreffed and destroyed while the call is still using the vector.

I've sent you #24335 to fix this.  Once that's merged, you'll need to add this line here:

```
call_config.service_config = entry.method_config;
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 502 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIygqi77fTKbf4wbDrW:-MJ5VxAl7bYu7imOxOrI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L502)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you can just use `grpc_empty_slice()` here.  The value really doesn't matter, since it will never match anything.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 125 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyNaSB4iqE5IFmqOI1:-MJ5u3p6-oNq3O0KYWdb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/xds/xds_api.h#L125)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `= ""`, since that's the default value.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 125 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyNsmxEeY8JqsPADQX:-MJ5vRM86Y5K3Hmxys0l:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/xds/xds_api.h#L125)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment indicating the expected format of the value.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 126 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyNqXR5Wlnwen0p4Y-:-MJ6Pd4CASH1Am9j_5iD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/xds/xds_api.h#L126)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume this was just for testing and can be removed.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1577 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyOBOo9Ma2rMZlJlOF:-MJ5x_hE-mT-OFNoicuD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/xds/xds_api.cc#L1577)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check isn't necessary, because `envoy_config_route_v3_RouteAction_max_stream_duration()` below will return null if the field is not present.

Same thing for all of the fields here -- don't call the `*_has_*()` method, just get the field and see if it's null.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1589 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyOqcdAMNv-635HZTO:-MJ60xpd5u6U7MtrpFs-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/xds/xds_api.cc#L1589)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Formatting this as a float is going to lose precision, which is exactly what the proto tries to avoid by storing the nanos as an integer.  Instead, please format as an integer, using something like this:

```
absl::StrFormat("%d.%09d", google_protobuf_Duration_seconds(duration), google_protobuf_Duration_nanos(duration))
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1598 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyWA2f8vvEirVh8MPl:-MJ60y9SATvBR2pEwrX7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/xds/xds_api.cc#L1598)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same floating point issue here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1738 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyhryc6h0oKvsGYpyc:-MJ6Pduw7t6wbwYlWI5u:bhac301) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/xds/xds_api.cc#L1738)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ri [...]

2020-10-08 15:42 UTC, markdroth requested changes
It looks like there are two noteworthy issues remaining, one related to how we handle the case where the timeout field is unset, and another related to how we return the timeout value from LDS.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJ7rwR86OlmTSy7TrUK:b3kg1ia)* status: all files reviewed, 10 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 317 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIydUulE0m1oyYwhdX-:-MJ7dW0CEnNMKvK-RVXJ:b41efmf) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L317)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It looks like the code is still defaulting to "0s".  I see that you've made changes elsewhere to prevent this from being called if the timeout is unset, in which case the "0s" fallback here is not needed.  However, as I mentioned elsewhere, I don't think it makes sense to avoid calling this function if timeout is unset, because this function will ultimately handle other per-route parameters in the method config as well.  So I think that we do need the logic here to check if the timeout field is set, but it should not default to "0s".

I think the logic here should look something like this:

```
grpc_error* error = GRPC_ERROR_NONE;
std::vector<std::string> fields;
if (!timeout.empty()) {
  fields.emplace_back(absl::StrFormat("    \"timeout\": \"%s\"", timeout));
}
// (In the future, we can add other fields here.)
if (!fields.empty()) {
  std::string json = absl::StrCat(
      "{\n"
      "  \"methodConfig\": [ {\n"
      "    \"name\": [\n"
      "      {}\n"
      "    ],\n"
      "    ",
      absl::StrJoin(fields, ",\n"),
      "\n  } ]\n"
      "}");
  *method_config = ServiceConfig::Create(resolver_->args_, json.c_str(), &error);
}
return error;
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 291 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7dtbpBjOqkRS1lx2m:-MJ7dtbpBjOqkRS1lx2n:b3scj2j) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L291)):*
> ```cpp
>     auto& route_entry = route_table_.back();
>     route_entry.route = route;
>     if (!route.timeout.empty()) {
> ```

I think we should call `CreateMethodConfig()` unconditionally and have it return null for the service config if there are no per-route settings that require returning a method config.  That will make it easier to add other per-route settings in the future.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 296 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7dJJJ1dPJNVb2Bhup:-MJ7dJJK7IuSnRfRhUpZ:b-eat7js) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L296)):*
> ```cpp
>       if (error != GRPC_ERROR_NONE) {
>         gpr_log(GPR_ERROR,
>                 "[xds_resolver %p] XdsConfigSelector %p received error while "
> ```

If this happens, I don't think it's sufficient to just log the error, because that will cause us to ignore the timeout setting (and any other per-route settings that we may add in the future).  I think the resolver should return an error to the channel, which will result in the channel going into TRANSIENT_FAILURE.

Basically, I think this case should react as if `OnError()` was called.  To do that, we'll probably need to propagate this error back to the caller.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 316 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7dg3c6JyEog1ikGoc:-MJ7dg3c6JyEog1ikGod:b-loiou7) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L316)):*
> ```cpp
> 
> grpc_error* XdsResolver::XdsConfigSelector::CreateMethodConfig(
>     RefCountedPtr<ServiceConfig>* method_config, const std::string& timeout) {
> ```

Instead of passing in the timeout string here, please pass in the entire `Route` struct.  That way, we won't need to change the API when we add more fields later.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 328 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7hLEY2Jg8gket39lF:-MJ7hLEY2Jg8gket39lG:b-98bjth) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L328)):*
> ```cpp
>       timeout.empty() ? "0s" : timeout);
>   grpc_error* error = GRPC_ERROR_NONE;
>   *method_config = ServiceConfig::Create(nullptr, json.c_str(), &error);
> ```

We need to pass `resolver_->args_` as the first parameter here.
___
*[src/core/ext/xds/xds_api.h, line 150 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7oKxc7VLHyDLLJKwA:-MJ7oKxc7VLHyDLLJKwB:b7pmd19) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/xds/xds_api.h#L150)):*
> ```objc
>     };
> 
>     struct Timeout {
> ```

Suggest calling this `Duration`.
___
*[src/core/ext/xds/xds_api.h, line 158 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7nSnw360sar3ghiBu:-MJ7nSnw360sar3ghiBv:b-u6q3bk) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/xds/xds_api.h#L158)):*
> ```objc
>     // Storing the Http Connection Manager Common Http Protocol Option
>     // max_stream_duration
>     Timeout http_max_stream_duration = {0, 0};
> ```

This field should not be here; it should be in `LdsUpdate`, since this value comes from LDS, not RDS.
___
*[src/core/ext/xds/xds_api.h, line 158 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7pXaW2B-rCWyMzZDx:-MJ7pXaW2B-rCWyMzZDy:b-l94d9n) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/xds/xds_api.h#L158)):*
> ```objc
>     // Storing the Http Connection Manager Common Http Protocol Option
>     // max_stream_duration
>     Timeout http_max_stream_duration = {0, 0};
> ```

Why are we using a struct here when we used a string for the value in the route?  I think we should use the same representation in both places.

Actually, I think the struct is a better representation.  I suggest moving it up to the top-level inside of `XdsApi` and using it in both `LdsUpdate` and `Route`.
___
*[src/core/ext/xds/xds_api.h, line 225 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7q5X--tRhN-4hLPqJ:-MJ7q5X--tRhN-4hLPqK:b-uzp1jb) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/xds/xds_api.h#L225)):*
> ```objc
>     absl::optional<RdsUpdate> rds_update;
> 
>     bool operator==(const LdsUpdate& other) const {
> ```

Note that this will need to be changed to also check the new `max_stream_duration` field once you move it here from `RdsUpdate`.
___
*[src/core/ext/xds/xds_api.cc, line 1738 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyhryc6h0oKvsGYpyc:-MJ7pG4o0PLqt1HrI6EO:bor3iz8) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/xds/xds_api.cc#L1738)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.  Let me know if you like how I stored the value and passed it around
</blockquote></details>

Unfortunately, this doesn't work, because it will use the LDS value only if the RouteConfiguration comes in the LDS response.  If the RouteConfiguration comes separately via RDS, then the value from LDS won't be recorded at all, which is incorrect.

I think the right way to do this is to have the XdsClient return the LDS  [...]

2020-10-12 08:20 UTC, donnadionne reviewed
Fixed and test ready now.  PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJQtJQ06h4sQYH7toCQ:bdb9jgg)* status: all files reviewed, 10 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 317 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIydUulE0m1oyYwhdX-:-MJGQI0aA1M4ThY0XvHO:b-7ql1td) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L317)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like the code is still defaulting to "0s".  I see that you've made changes elsewhere to prevent this from being called if the timeout is unset, in which case the "0s" fallback here is not needed.  However, as I mentioned elsewhere, I don't think it makes sense to avoid calling this function if timeout is unset, because this function will ultimately handle other per-route parameters in the method config as well.  So I think that we do need the logic here to check if the timeout field is set, but it should not default to "0s".

I think the logic here should look something like this:

```
grpc_error* error = GRPC_ERROR_NONE;
std::vector<std::string> fields;
if (!timeout.empty()) {
  fields.emplace_back(absl::StrFormat("    \"timeout\": \"%s\"", timeout));
}
// (In the future, we can add other fields here.)
if (!fields.empty()) {
  std::string json = absl::StrCat(
      "{\n"
      "  \"methodConfig\": [ {\n"
      "    \"name\": [\n"
      "      {}\n"
      "    ],\n"
      "    ",
      absl::StrJoin(fields, ",\n"),
      "\n  } ]\n"
      "}");
  *method_config = ServiceConfig::Create(resolver_->args_, json.c_str(), &error);
}
return error;
```
</blockquote></details>

fixed
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 291 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7dtbpBjOqkRS1lx2m:-MJGQAJt852rNu2U64vt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L291)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we should call `CreateMethodConfig()` unconditionally and have it return null for the service config if there are no per-route settings that require returning a method config.  That will make it easier to add other per-route settings in the future.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 296 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7dJJJ1dPJNVb2Bhup:-MJJvb4H5nbYDtN_CFOc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L296)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If this happens, I don't think it's sufficient to just log the error, because that will cause us to ignore the timeout setting (and any other per-route settings that we may add in the future).  I think the resolver should return an error to the channel, which will result in the channel going into TRANSIENT_FAILURE.

Basically, I think this case should react as if `OnError()` was called.  To do that, we'll probably need to propagate this error back to the caller.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 316 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7dg3c6JyEog1ikGoc:-MJGQGiq0cVUx4yBhECS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L316)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of passing in the timeout string here, please pass in the entire `Route` struct.  That way, we won't need to change the API when we add more fields later.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 328 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7hLEY2Jg8gket39lF:-MJJvo443ofex_OMf6JO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L328)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We need to pass `resolver_->args_` as the first parameter here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 150 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7oKxc7VLHyDLLJKwA:-MJGQKQZ8T3Pmp8J430O:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/xds/xds_api.h#L150)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `Duration`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 158 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7nSnw360sar3ghiBu:-MJGQLTz14kOaJYg9Dp7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/xds/xds_api.h#L158)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This field should not be here; it should be in `LdsUpdate`, since this value comes from LDS, not RDS.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 158 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7pXaW2B-rCWyMzZDx:-MJGQLzt1zBsEqJjGjm_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/xds/xds_api.h#L158)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why are we using a struct here when we used a string for the value in the route?  I think we should use the same representation in both places.

Actually, I think the struct is a better representation.  I suggest moving it up to the top-level inside of `XdsApi` and using it in both `LdsUpdate` and `Route`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 225 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7q5X--tRhN-4hLPqJ:-MJJxO0V94ikZ9Yn9Blf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/xds/xds_api.h#L225)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Note that this will need to be changed to also check the new `max_stream_duration` field once you move it here from `RdsUpdate`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1738 at r1](https://reviewable.io/reviews/grpc/grpc/24328#-MIyhryc6h0oKvsGYpyc:-MJGQOh-D9SqvUHuOkHA:b-ha64yb) ([raw file](https://github.com/grpc/grpc/blob/1753b22c400d97cbcb8adf75aad4717f39515f8c/src/core/ext/xds/xds_api.cc#L1738)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Unfortunately, this doesn't work, because it will use the LDS value only if the RouteConfiguration comes in the LDS response.  If the RouteConfiguration comes separately via RDS, then the value from LDS won't be recorded at all, which is incorrect.

I think the right way to do this is to have the XdsClient return the LDS data to the LDS watcher and the RDS data to the RDS watcher, without trying to join the two up.  The code in the xds resolver should handle using the value from LDS if the route does not specify a value, since the xds resolver has the results from both watchers.
</blockquote></details>

rewrote


<!-- Sent from Reviewable.io -->

2020-10-12 15:12 UTC, markdroth requested changes
This is looking pretty good!  Remaining comments are mostly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJSMWit-sbnAhYygNTP:beyu8ky)* status: all files reviewed, 11 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 296 at r2](https://reviewable.io/reviews/grpc/grpc/24328#-MJ7dJJJ1dPJNVb2Bhup:-MJSC4kO11Y44bI_Kxo7:b-gsm9i0) ([raw file](https://github.com/grpc/grpc/blob/2c999b7bbd325e92b1c7467611483221372eb810/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L296)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We no longer need the log message here.  That will be done in `OnError()`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 293 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSBUFrCmKYPb2FYrge:-MJSBUFs8SVvRicgPyWH:bujj90w) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L293)):*
> ```cpp
>     auto& route_entry = route_table_.back();
>     route_entry.route = route;
>     XdsApi::Duration max_stream_duration = {0, 0};
> ```

No need for `= {0, 0}` if you initialize the fields in the `Duration` struct itself, as I suggested elsewhere.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 305 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSCSvoAeXwf0G6arX_:-MJSCSvoAeXwf0G6arXa:b-wwzndq) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L305)):*
> ```cpp
>     }
>     if (max_stream_duration.seconds != 0 || max_stream_duration.nanos != 0) {
>       route_entry.route.timeout = absl::StrFormat(
> ```

It does not make sense to store this string in the `Route` struct, since we're only ever using it locally in this code.  In effect, this is adding a field to a public struct just to pass a parameter from here to `CreateMethodConfig()`.  The parameter could just as easily be passed directly.

But actually, in this case, we don't even need to pass a parameter.  The `absl::StrFormat()` call here actually belongs inside of `CreateMethodConfig()` anyway, since that's where we're generating the service config.  All of the code to convert between the struct and the JSON form should be in that method.

I suggest the following code here:

```
// If the route doesn't specify a timeout, set its timeout to the global one.
if (route.max_stream_duration.seconds == 0 &&
    route.max_stream_duration.nanos == 0) {
  route_entry.route.max_stream_duration.seconds =
      resolver_->http_max_stream_duration_.seconds;
  route_entry.route.max_stream_duration.nanos =
      resolver_->http_max_stream_duration_.nanos;
}
```

Then inside of `CreateMethodConfig()`, we can do this:

```
if (route.max_stream_duration.seconds != 0  ||
    route.max_stream_duration.nanos != 0)  {
  fields.emplace_back(absl::StrFormat(
      "    \"timeout\": \"%d.%09ds\"",
      route.max_stream_duration.seconds,
      route.max_stream_duration.nanos));
}
```
___
*[src/core/ext/xds/xds_api.h, line 50 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSAV9Z6oYgf-vcORha:-MJSAV9Z6oYgf-vcORhb:b-rea0vg) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/xds/xds_api.h#L50)):*
> ```objc
> 
>   struct Duration {
>     int64_t seconds;
> ```

If you initialize these fields to 0 here, then there won't be any need to do `= {0, 0}` in the two places where you use this struct.
___
*[src/core/ext/xds/xds_api.h, line 140 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSMDLa1GjSLsqIvVaL:-MJSMDLa1GjSLsqIvVaM:bdz4qs4) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/xds/xds_api.h#L140)):*
> ```objc
>     // RouteAction.max_stream_duration.max_stream_duration if the former is
>     // not set.
>     Duration max_stream_duration = {0, 0};
> ```

No need for `= {0, 0}`, as mentioned above.
___
*[src/core/ext/xds/xds_api.h, line 145 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJS9tSiBLu6WUUqTTpW:-MJS9tSiBLu6WUUqTTpX:b-ry7riq) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/xds/xds_api.h#L145)):*
> ```objc
>     // nanoseconds expressed as fractional seconds. For example, 1 second with 1
>     // nanosecond would be expressed as "1.0000000001s"
>     std::string timeout;
> ```

As mentioned above, this field should no longer be necessary.
___
*[src/core/ext/xds/xds_api.h, line 232 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSMGcu11Z2RxgbagJx:-MJSMGcu11Z2RxgbagJy:bdz4qs4) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/xds/xds_api.h#L232)):*
> ```objc
>     // Storing the Http Connection Manager Common Http Protocol Option
>     // max_stream_duration
>     Duration http_max_stream_duration = {0, 0};
> ```

No need for `= {0, 0}`, as mentioned above.
___
*[src/proto/grpc/testing/xds/v3/http_connection_manager.proto, line 30 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSF6rB5lrsmkZBBM3-:-MJSF6rB5lrsmkZBBM30:b8198bj) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/proto/grpc/testing/xds/v3/http_connection_manager.proto#L30)):*
> ```protobuf
> 
> // [#next-free-field: 38]
> message HttpProtocolOptions {
> ```

This should not go in this file, since the real `HttpProtocolOptions` is in a different proto package (`envoy.config.core.v3`).  It will need to go into its own file, which will be imported in this file.
___
*[src/proto/grpc/testing/xds/v3/route.proto, line 186 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSG9UM6jUVwLj2zfS7:-MJSG9UM6jUVwLj2zfS8:b-txazvj) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/proto/grpc/testing/xds/v3/route.proto#L186)):*
> ```protobuf
> message MaxStreamDuration {
>   // Specifies the maximum duration allowed for streams on the route. If not specified, the value
>     // from the :ref:`max_stream_duration
> ```

Please fix indentation in this message.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 3912 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSL4nW34bOlOv3DVvA:-MJSL4nW34bOlOv3DVvB:btmw0cg) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/test/cpp/end2end/xds_end2end_test.cc#L3912)):*
> ```cpp
>             kTimeoutApplicationSecond * 1000000000);
>   // Set up HTTP max_stream_duration of 3.5 seconds
>   http_connection_manager.mutable_common_http_protocol_options()
> ```

A lot of this code is very repetitive.  I suggest using local variables to eliminate duplication.  For example:

```
// Set up HTTP max_stream_duration of 3.5 seconds
auto* duration =
    http_connection_manager.mutable_common_http_protocol_options()
        ->mutable_max_stream_duration();
duration->set_seconds(kTimeoutHttpMaxStreamDurationSecond);
duration->set_nanos(kTimeoutNano);
// Set max_stream_duration of 2.5 seconds
auto* max_stream_duration =
    new_route_config.mutable_virtual_hosts(0)
        ->mutable_routes(0)
        ->mutable_route()
        ->mutable_max_stream_duration();
duration = max_stream_duration->mutable_max_stream_duration();
duration->set_seconds(kTimeoutMaxStreamDurationSecond);
duration->set_nanos(kTimeoutNano);
// ...
```
___
*[test/cpp/end2end/xds_end2end_test.cc, line 3948 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSGxLX-YUl-z54aQXZ:-MJSGxLX-YUl-z54aQX_:b-qjn0rs) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/test/cpp/end2end/xds_end2end_test.cc#L3948)):*
> ```cpp
>       http_connection_manager);
>   balance [...]

2020-10-13 09:36 UTC, donnadionne reviewed
fixed code review comments and fixed tests to be more robust.  PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJWJEWA-wWd6xY883Jv:b-e6n79g)* status: all files reviewed, 11 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 293 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSBUFrCmKYPb2FYrge:-MJWDOBQAznIXjbzGHoi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L293)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `= {0, 0}` if you initialize the fields in the `Duration` struct itself, as I suggested elsewhere.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 305 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSCSvoAeXwf0G6arX_:-MJWGZuaBdBvJz5WKHH6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L305)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It does not make sense to store this string in the `Route` struct, since we're only ever using it locally in this code.  In effect, this is adding a field to a public struct just to pass a parameter from here to `CreateMethodConfig()`.  The parameter could just as easily be passed directly.

But actually, in this case, we don't even need to pass a parameter.  The `absl::StrFormat()` call here actually belongs inside of `CreateMethodConfig()` anyway, since that's where we're generating the service config.  All of the code to convert between the struct and the JSON form should be in that method.

I suggest the following code here:

```
// If the route doesn't specify a timeout, set its timeout to the global one.
if (route.max_stream_duration.seconds == 0 &&
    route.max_stream_duration.nanos == 0) {
  route_entry.route.max_stream_duration.seconds =
      resolver_->http_max_stream_duration_.seconds;
  route_entry.route.max_stream_duration.nanos =
      resolver_->http_max_stream_duration_.nanos;
}
```

Then inside of `CreateMethodConfig()`, we can do this:

```
if (route.max_stream_duration.seconds != 0  ||
    route.max_stream_duration.nanos != 0)  {
  fields.emplace_back(absl::StrFormat(
      "    \"timeout\": \"%d.%09ds\"",
      route.max_stream_duration.seconds,
      route.max_stream_duration.nanos));
}
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 50 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSAV9Z6oYgf-vcORha:-MJWDg0q9p8pLgcZtu6X:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/xds/xds_api.h#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you initialize these fields to 0 here, then there won't be any need to do `= {0, 0}` in the two places where you use this struct.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 140 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSMDLa1GjSLsqIvVaL:-MJWDlIp4LGeRsMqlMHp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/xds/xds_api.h#L140)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `= {0, 0}`, as mentioned above.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 145 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJS9tSiBLu6WUUqTTpW:-MJWEbSXCouqjYTsAJqY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/xds/xds_api.h#L145)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned above, this field should no longer be necessary.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 232 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSMGcu11Z2RxgbagJx:-MJWDrf32i83y4IUciVK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/core/ext/xds/xds_api.h#L232)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `= {0, 0}`, as mentioned above.
</blockquote></details>

Done.
___
*[src/proto/grpc/testing/xds/v3/http_connection_manager.proto, line 30 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSF6rB5lrsmkZBBM3-:-MJWEcoaEP3OD-sKn9tL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/proto/grpc/testing/xds/v3/http_connection_manager.proto#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should not go in this file, since the real `HttpProtocolOptions` is in a different proto package (`envoy.config.core.v3`).  It will need to go into its own file, which will be imported in this file.
</blockquote></details>

Done.
___
*[src/proto/grpc/testing/xds/v3/route.proto, line 186 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSG9UM6jUVwLj2zfS7:-MJWEAj_81BcmxCOhjYP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/proto/grpc/testing/xds/v3/route.proto#L186)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please fix indentation in this message.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 3912 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSL4nW34bOlOv3DVvA:-MJWCvl20pmUwkakN2dp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/test/cpp/end2end/xds_end2end_test.cc#L3912)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

A lot of this code is very repetitive.  I suggest using local variables to eliminate duplication.  For example:

```
// Set up HTTP max_stream_duration of 3.5 seconds
auto* duration =
    http_connection_manager.mutable_common_http_protocol_options()
        ->mutable_max_stream_duration();
duration->set_seconds(kTimeoutHttpMaxStreamDurationSecond);
duration->set_nanos(kTimeoutNano);
// Set max_stream_duration of 2.5 seconds
auto* max_stream_duration =
    new_route_config.mutable_virtual_hosts(0)
        ->mutable_routes(0)
        ->mutable_route()
        ->mutable_max_stream_duration();
duration = max_stream_duration->mutable_max_stream_duration();
duration->set_seconds(kTimeoutMaxStreamDurationSecond);
duration->set_nanos(kTimeoutNano);
// ...
```
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 3948 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSGxLX-YUl-z54aQXZ:-MJWCvLA2v67a_8iZNA8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/test/cpp/end2end/xds_end2end_test.cc#L3948)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This seems likely to lead to flakiness.  Instead, I suggest simply creating a route config with multiple routes, so that you can test all of the cases at once without needing to send a config update to the client.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-13 15:36 UTC, markdroth requested changes
Almost there -- just a few minor issues to clear up.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJXafv21MwLX6i-8Ytn:b-ks71nr)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne)

___
*[src/proto/grpc/testing/xds/v3/http_connection_manager.proto, line 30 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSF6rB5lrsmkZBBM3-:-MJXadS69kbUws5Vl7jj:behgwxy) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/proto/grpc/testing/xds/v3/http_connection_manager.proto#L30)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 3930 at r4](https://reviewable.io/reviews/grpc/grpc/24328#-MJXZM7C73FbSlqoo6xd:-MJXZM7D0vaSw6jelZ1T:b-b3kdx) ([raw file](https://github.com/grpc/grpc/blob/c86040b8fc4d346a8949c331168b636dc1e99a93/test/cpp/end2end/xds_end2end_test.cc#L3930)):*
> ```cpp
>   ShutdownBackend(2);
>   ShutdownBackend(3);
>   // Setup Route and Listener and ensure RDS in inlined LDS,
> ```

This test is part of the `LdsRdsTest` suite, which means it will run once where it expects the RouteConfiguration to be returned in LDS and then again where it expects to use RDS.  However, the code here is hard-coding the RouteConfiguration in LDS, which means that the test will basically run twice exactly the same way.

I think we do actually want to test this with both the LDS-only and the LDS+RDS path.  I suggest using `GetParam().enable_rds_testing()` to set up the resources accordingly.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 3940 at r4](https://reviewable.io/reviews/grpc/grpc/24328#-MJX_fxQ2uv9UC3zcYzC:-MJX_fxQ2uv9UC3zcYzD:bvvnts3) ([raw file](https://github.com/grpc/grpc/blob/c86040b8fc4d346a8949c331168b636dc1e99a93/test/cpp/end2end/xds_end2end_test.cc#L3940)):*
> ```cpp
>       http_connection_manager);
>   balancers_[0]->ads_service()->SetLdsResource(listener);
>   // Test application timeout of 4 seconds applied.
> ```

Let's split this case into its own test.  That way, there will be no need for an LDS update in this test.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4038 at r4](https://reviewable.io/reviews/grpc/grpc/24328#-MJXaV5-DY2N6kCDS6AC:-MJXaV5-DY2N6kCDS6AD:b60dnd4) ([raw file](https://github.com/grpc/grpc/blob/c86040b8fc4d346a8949c331168b636dc1e99a93/test/cpp/end2end/xds_end2end_test.cc#L4038)):*
> ```cpp
>             kTimeoutApplicationSecond * 1000000000);
>   // All RPCs should have timed out.
>   for (int i = 1; i < 4; ++i) {
> ```

I don't think there's any need to check this.  The backends are down, so we know that they didn't get traffic.  And we've already checked that the RPCs above failed with DEADLINE_EXCEEDED.


<!-- Sent from Reviewable.io -->

2020-10-14 20:02 UTC, donnadionne reviewed
PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJchHRa471J4tcNFY0M:bxtaph9)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/proto/grpc/testing/xds/v3/http_connection_manager.proto, line 30 at r3](https://reviewable.io/reviews/grpc/grpc/24328#-MJSF6rB5lrsmkZBBM3-:-MJchCewEOF7ovXSHP9u:b1kcjo3) ([raw file](https://github.com/grpc/grpc/blob/9978aa075c94e3febe6b82061b5d7c83368b5922/src/proto/grpc/testing/xds/v3/http_connection_manager.proto#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see a change here.
</blockquote></details>

missed it last time; there now
___
*[test/cpp/end2end/xds_end2end_test.cc, line 3930 at r4](https://reviewable.io/reviews/grpc/grpc/24328#-MJXZM7C73FbSlqoo6xd:-MJchFLx6bqTRJT95Ocb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c86040b8fc4d346a8949c331168b636dc1e99a93/test/cpp/end2end/xds_end2end_test.cc#L3930)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This test is part of the `LdsRdsTest` suite, which means it will run once where it expects the RouteConfiguration to be returned in LDS and then again where it expects to use RDS.  However, the code here is hard-coding the RouteConfiguration in LDS, which means that the test will basically run twice exactly the same way.

I think we do actually want to test this with both the LDS-only and the LDS+RDS path.  I suggest using `GetParam().enable_rds_testing()` to set up the resources accordingly.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 3940 at r4](https://reviewable.io/reviews/grpc/grpc/24328#-MJX_fxQ2uv9UC3zcYzC:-MJchG713Cyp5BK6HQcq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c86040b8fc4d346a8949c331168b636dc1e99a93/test/cpp/end2end/xds_end2end_test.cc#L3940)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's split this case into its own test.  That way, there will be no need for an LDS update in this test.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4038 at r4](https://reviewable.io/reviews/grpc/grpc/24328#-MJXaV5-DY2N6kCDS6AC:-MJchGWaCg79MSVizPNG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c86040b8fc4d346a8949c331168b636dc1e99a93/test/cpp/end2end/xds_end2end_test.cc#L4038)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think there's any need to check this.  The backends are down, so we know that they didn't get traffic.  And we've already checked that the RPCs above failed with DEADLINE_EXCEEDED.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-14 22:55 UTC, markdroth requested changes
This looks good!  Just a few minor issues remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJdJb5lERd05IWnfUP_:bnb72be)* status: all files reviewed, 6 unresolved discussions (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 4173 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdHG348L_nZAnowj3i:-MJdHG348L_nZAnowj3j:bdkn4bn) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4173)):*
> ```cpp
>       kNewEdsService3Name);
>   balancers_[0]->ads_service()->SetCdsResource(new_cluster3);
>   // Bring down the backends, this will delay route picking time,
> ```

Alternatively, you could just change the `EdsResourceArgs` structs above to use `g_port_saver->GetPort()` instead of `GetBackendPorts()`.  Then there's no need to shut anything down.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4179 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdHrNk8nCvx2b-IL5U:-MJdHrNk8nCvx2b-IL5V:b-dh9u0n) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4179)):*
> ```cpp
>   ShutdownBackend(2);
>   ShutdownBackend(3);
>   RouteConfiguration new_route_config =
> ```

This can be moved down to line 4188.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4227 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdI_LGCoiteeKd1t6b:-MJdI_LGCoiteeKd1t6c:bp3fode) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4227)):*
> ```cpp
>     SetRouteConfiguration(0, new_route_config);
>   } else {
>     *(http_connection_manager.mutable_route_config()) = new_route_config;
> ```

No need for the outer parens here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4233 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdIkmQ7lhU1hF5EK79:-MJdIkmQ7lhU1hF5EK7A:b-1rrns4) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4233)):*
> ```cpp
>     balancers_[0]->ads_service()->SetLdsResource(listener);
>   }
>   // Test default route is working to ensure LDS update is received,
> ```

There's no need for this.  The RPCs will wait for the client to see the config.

(And even if we did need this, it would be easier to just not shut down the backend in the first place until after this step, rather than shutting it down, starting it up, and then shutting it down again.)
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4283 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdJNZU0-QbMWqSuE9d:-MJdJNZVBj54f1q84HGs:bt5e8j7) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4283)):*
> ```cpp
> }
> 
> TEST_P(LdsRdsTest, XdsRoutingWithApplicationTimeout) {
> ```

Please add a comment indicating that this test is ensuring that the application-specified deadline won't be affected if the xDS config does not specify a timeout.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4293 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdJEc9DTbo0FxpOmlB:-MJdJEc9DTbo0FxpOmlC:b-23g2z0) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4293)):*
> ```cpp
>   balancers_[0]->ads_service()->SetEdsResource(
>       AdsServiceImpl::BuildEdsResource(args));
>   // Bring down the current backend: 0, this will delay route picking time,
> ```

Same comment here about using `g_port_saver->GetPort()` to avoid the need to shut down the backend.


<!-- Sent from Reviewable.io -->

2020-10-16 00:09 UTC, donnadionne reviewed
Fixed for Code review comments.  Fixed the logic for unset vs. explicit 0, added tests.  PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJijC1O4o6FElBiQUAO:bi1ika5)* status: all files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 4173 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdHG348L_nZAnowj3i:-MJiSgVF9wkTeoh9qfZY:b-qhxcw1) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4173)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Alternatively, you could just change the `EdsResourceArgs` structs above to use `g_port_saver->GetPort()` instead of `GetBackendPorts()`.  Then there's no need to shut anything down.
</blockquote></details>

Done. cool!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4179 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdHrNk8nCvx2b-IL5U:-MJiPKBI4JhlDE6y2Pny:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4179)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be moved down to line 4188.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4227 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdI_LGCoiteeKd1t6b:-MJiPQo5881n0MbQRJ2u:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4227)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the outer parens here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4233 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdIkmQ7lhU1hF5EK79:-MJiTGvZ90zx1p6HYncF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4233)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need for this.  The RPCs will wait for the client to see the config.

(And even if we did need this, it would be easier to just not shut down the backend in the first place until after this step, rather than shutting it down, starting it up, and then shutting it down again.)
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4283 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdJNZU0-QbMWqSuE9d:-MJiSPIs-fiMPsMK2xiP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4283)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment indicating that this test is ensuring that the application-specified deadline won't be affected if the xDS config does not specify a timeout.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4293 at r5](https://reviewable.io/reviews/grpc/grpc/24328#-MJdJEc9DTbo0FxpOmlB:-MJiSfN5BpVtEaPZA6J1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/045dc8d7900cc3115b90b42887a9a331d8e64169/test/cpp/end2end/xds_end2end_test.cc#L4293)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same comment here about using `g_port_saver->GetPort()` to avoid the need to shut down the backend.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-16 15:07 UTC, markdroth requested changes
This looks great!  Just one remining minor comment.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJlwisG88_rVT7Nspz2:b71nvhp)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 4383 at r6](https://reviewable.io/reviews/grpc/grpc/24328#-MJlwY-J5ILrTT_no5zD:-MJlwY-J5ILrTT_no5zE:bs2tyyv) ([raw file](https://github.com/grpc/grpc/blob/9f7b6f6c13bd1bb210345598eddc0d0f754dea95/test/cpp/end2end/xds_end2end_test.cc#L4383)):*
> ```cpp
> // Test to ensure application-specified deadline won't be affected when
> // the xDS config does not specify a timeout.
> TEST_P(LdsRdsTest, XdsRoutingWithOnlyApplicationTimeout) {
> ```

We should also have a test similiar to this one but where the top-level HttpConnectionManager timeout value is set to 0 instead of being unset.


<!-- Sent from Reviewable.io -->

2020-10-16 17:05 UTC, donnadionne reviewed
PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJmMxqVB68W1JQxdh0z:bxtaph9)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 4383 at r6](https://reviewable.io/reviews/grpc/grpc/24328#-MJlwY-J5ILrTT_no5zD:-MJmMuxvAAJafiVQ5ckM:b-7tfmjp) ([raw file](https://github.com/grpc/grpc/blob/9f7b6f6c13bd1bb210345598eddc0d0f754dea95/test/cpp/end2end/xds_end2end_test.cc#L4383)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should also have a test similiar to this one but where the top-level HttpConnectionManager timeout value is set to 0 instead of being unset.
</blockquote></details>

added


<!-- Sent from Reviewable.io -->

2020-10-16 18:21 UTC, markdroth approved these changes
Looks great!

> Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24328#-:-MJmd9vz98numeMLQ8As:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-16 20:43 UTC, merged