xDS Client-Side Fault Injection
grpc/grpc pull request #24354
Opened 2020-10-07 19:00 UTC by lidizheng

The implementation of fault injection includes several items:
1. Interpret xDS configs and craft service config;
1. Parse service config for fault injection policy;
1. Apply fault injection policy to CallData;
1. Iterate through headers for overriding setting if any;
1. Enforce active faults count;
1. Inject RPC delay;
1. Inject RPC abort;
1. ~~Inject response rate limit.~~

This PR is the first batch that implements 2, 3, 4, 5, 7. I hope to get early feedback, so if I got something very wrong I will have the time to pivot.

---

For item 1, I can go ahead to implement it in the `XdsConfigSelector` if it won't conflict with Donna's work.

For item 6 (RPC delay), is `StartTransportStreamOpBatch` a valid place to hook an extra layer of callback to inject the fixed delay?

For item 8 (response rate limit), I might delay it because now I don't have an elegant solution to throttle the responses.

---

**Update**, this PR implements all items above. It should be sufficient for Core to be ready for upcoming interop tests. 

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc/24354)

2020-10-08 20:35 UTC, lidizheng commented
@markdroth When you got a second, can you take a quick look? Or reassign to someone from Core team who familiar with this portion of code.

2020-10-09 05:02 UTC, markdroth requested changes
This looks like a really good start!

Donna is already working on the `XdsConfigSelector` piece in #24328.  I think you can wait for her to finish that.

As per one of the comments I left here, I think `PickSubchannelLocked()` is the right place to handle the fault injection (both delay and abort).

I don't think it's hard to throttle the responses in C-core.  We would just need to intercept the recv_message callbacks and use timers to delay returning each callback.  But I thought we said that we aren't going to implement that feature for now, since Java and Go don't have an easy way to do it?

Please let me know if you have any questions about any of this.  Thanks!

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MJAhA32CsPAeps0fB-f:b-pt5kpg)* status: all files reviewed, 37 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 808 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJAYPgi4jrTWNASjcNF:-MJAYPgi4jrTWNASjcNG:b2otd75) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/client_channel.cc#L808)):*
> ```cpp
>   std::map<const char*, absl::string_view> call_attributes_;
>   std::function<void()> on_call_committed_;
>   FaultInjectionData fault_injection_data_;
> ```

I don't think we want to allocate this unless fault injection is actually going to be used for the call.  I suggest making this a pointer and allocating it on the call arena only if both (a) the method config enables fault injection and (b) we roll the dice and decide to actually inject a fault for the call.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4015 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJAZhtJ7CBJUjROKCme:-MJAZhtJ7CBJUjROKCmf:b-v9qcg4) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/client_channel.cc#L4015)):*
> ```cpp
>     enable_retries_ = false;
>   }
>   if (method_params_ != nullptr &&
> ```

This block should be moved up to line 406, inside the block where we're setting call attributes when we get a service config.  That way, we don't have to check if method_params is null twice.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4017 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJA_cF3ArbqVzRH4wqr:-MJA_cF4E7ZrPVuKuuzk:b-pseogr) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/client_channel.cc#L4017)):*
> ```cpp
>   if (method_params_ != nullptr &&
>       method_params_->fault_injection_policy() != nullptr) {
>     fault_injection_data_.SetFaultInjectionPolicy(
> ```

Instead of having methods to set the fault injection policy and parse the headers, I suggest just passing both parameters to the `FaultInjectionData` ctor.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4023 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJA_BS25ICB0-3WDpUL:-MJA_BS25ICB0-3WDpUM:b-fr71uk) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/client_channel.cc#L4023)):*
> ```cpp
>     // TODO(lidiz) Figure out how to inject delay. Envoy injects delay before
>     // the RPC abort.
>     grpc_error* fault = fault_injection_data_.MaybeAbort();
> ```

I don't think this should be done in this method.  This method is just for setting the method config parameters for the call; it's not about actually acting on those parameters.

Instead, I suggest doing this in `PickSubchannelLocked()`, right after the call to `ApplyServiceConfigToCallLocked()` (line 4131).  If we have just applied the service config to the call and the call is going to have a fault injection, we can handle both delays and failures.  In the delay case, we'll need to set a timer with a callback that will invoke `PickSubchannel()`, and then we can return false (indicating that `PickSubchannelLocked()` did not actually complete a pick).  In the abort case, we can set an error and return true.

Note that if retries are enabled, `PickSubchannelLocked()` will be invoked once per retry attempt, but we only want to inject faults on the first attempt.  So once the fault injection is done, we need to clear the fault injection state from the call, so that subsequent calls to `PickSubchannelLocked()` don't inject a new fault.
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJASFlD7Iz_PT0KEUyX:-MJASFlD7Iz_PT0KEUyY:bk4ey47) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.h#L1)):*
> ```objc
> /*
> ```

Please use C++-style comments.
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 27 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJASSdPCKrsRv-6ehNb:-MJASSdPCKrsRv-6ehNc:b-udmrjm) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.h#L27)):*
> ```objc
> #include "src/core/lib/transport/metadata_batch.h"
> 
> using grpc_core::internal::ClientChannelMethodParsedConfig;
> ```

The style guide prohibits `using` statements like this in header files, because it pollutes the global namespace.

https://google.github.io/styleguide/cppguide.html#Namespaces
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJASiwd3umTfIscpsOZ:-MJASiwd3umTfIscpsO_:bhofm5k) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.h#L32)):*
> ```objc
> namespace internal {
> 
> class FaultInjectionData {
> ```

Please add a comment describing this class.  What does it represent?  What does it do?  How is it expected to be used?  The intention is not at all obvious from the API.
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 40 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJAUzrc5Z3_eSFLNVOJ:-MJAUzrc5Z3_eSFLNVOK:b8ig16u) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.h#L40)):*
> ```objc
>       const ClientChannelMethodParsedConfig::FaultInjectionPolicy*
>           fault_injection_policy) {
>     fault_injection_policy_ = *fault_injection_policy;
> ```

It seems like the only reason that we need our own copy of this struct is that we might overwrite some of the values based on the request's headers.  However, copying the struct on every RPC seems wasteful in case where we don't actually need to use the headers.  Can we optimize this somehow such that we copy this only if we actually need to?
___
*[src/core/ext/filters/client_channel/fault_injection.cc, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJASrn3Ap-36UAeUU8z:-MJASrn3Ap-36UAeUU9-:bk4ey47) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.cc#L1)):*
> ```cpp
> /*
> ```

Please use C++-style comments.
___
*[src/core/ext/filters/client_channel/fault_injection.cc, line 31 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJAW3jg9F55k5bR3jtx:-MJAW3jhBTVrUjHau3K8:b-g32k4d) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.cc#L31)):*
> ```cpp
> #include "src/core/lib/transport/metadata_batch.h"
> 
> #define X_ENVOY_FAULT_ABORT_GRPC_REQUEST "x-envoy-fault-abort-grpc-request"
> ```

I think we should configure these field names via the service config rather than hard-coding them here.  It doesn't make sense to hard-code Envoy field names in gRPC code.
___
*[src/core/ext/filters/client_channel/fault_injec [...]

2020-10-20 00:06 UTC, lidizheng reviewed
Sorry, I didn't update this PR swiftly. I shouldn't have taken these many parallel projects...

Since there won't be integration tests (TD isn't committed for additional FI features), I think each language can support fault injection features to an exceed that is feasible. As you mentioned, response throttling won't take too much work, so I went ahead and implemented. It is implemented in `CallData::InvokeRecvMessageCallback`. Comparing to what retry does, injecting via this method seems simpler?

Since #24328 is merged, there isn't any blocker for me. Pending items: a) interpret xDS configs and craft service config; b) implement end2end tests.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MK1mMlhDkQFxFGDpqzf:b-v5cz5k)* status: 0 of 21 files reviewed, 37 unresolved discussions (waiting on @lidizheng and @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 808 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJAYPgi4jrTWNASjcNF:-MK1_wKv5gvMQK0kaW--:b13vwiq) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/client_channel.cc#L808)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we want to allocate this unless fault injection is actually going to be used for the call.  I suggest making this a pointer and allocating it on the call arena only if both (a) the method config enables fault injection and (b) we roll the dice and decide to actually inject a fault for the call.
</blockquote></details>

Changed to FaultInjectionData* here. Only if both conditions are met will the client channel instantiate FaultInjectionData in `ApplyServiceConfigToCallLocked`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4015 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJAZhtJ7CBJUjROKCme:-MK1aDbX1l-s9FAqHYGj:b-728yuj) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/client_channel.cc#L4015)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This block should be moved up to line 406, inside the block where we're setting call attributes when we get a service config.  That way, we don't have to check if method_params is null twice.
</blockquote></details>

Not sure which line 406 you are referring to. So, I merged it with the first `method_params_ != nullptr` check in this method.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4017 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJA_cF3ArbqVzRH4wqr:-MK1aRXN6HCrgcFD3qnD:b-60ukmf) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/client_channel.cc#L4017)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of having methods to set the fault injection policy and parse the headers, I suggest just passing both parameters to the `FaultInjectionData` ctor.
</blockquote></details>

Created `MaybeCreateFaultInjectionData` factory method which takes policy, metadata, and arena.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4023 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJA_BS25ICB0-3WDpUL:-MK1b2yqEgVo7AQpR0UF:b-vuvfw5) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/client_channel.cc#L4023)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this should be done in this method.  This method is just for setting the method config parameters for the call; it's not about actually acting on those parameters.

Instead, I suggest doing this in `PickSubchannelLocked()`, right after the call to `ApplyServiceConfigToCallLocked()` (line 4131).  If we have just applied the service config to the call and the call is going to have a fault injection, we can handle both delays and failures.  In the delay case, we'll need to set a timer with a callback that will invoke `PickSubchannel()`, and then we can return false (indicating that `PickSubchannelLocked()` did not actually complete a pick).  In the abort case, we can set an error and return true.

Note that if retries are enabled, `PickSubchannelLocked()` will be invoked once per retry attempt, but we only want to inject faults on the first attempt.  So once the fault injection is done, we need to clear the fault injection state from the call, so that subsequent calls to `PickSubchannelLocked()` don't inject a new fault.
</blockquote></details>

Thanks for the suggestion. I have moved the fault injection checks into `PickSubchannelLocked()`. Also, I put all the fault injection statuses in the `FaultInjectionData` so `CallData` won't take extra overhead.
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJASFlD7Iz_PT0KEUyX:-MJcqlXT6OGIHszhLEdq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.h#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style comments.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 27 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJASSdPCKrsRv-6ehNb:-MJcqjr_-M7HHICYFUc7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.h#L27)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The style guide prohibits `using` statements like this in header files, because it pollutes the global namespace.

https://google.github.io/styleguide/cppguide.html#Namespaces
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJASiwd3umTfIscpsOZ:-MJcvCUN0vfTcJRhL-Cl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.h#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment describing this class.  What does it represent?  What does it do?  How is it expected to be used?  The intention is not at all obvious from the API.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 40 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJAUzrc5Z3_eSFLNVOJ:-MK1bf6cCIWWS7lQMnXy:b-r9t3wl) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.h#L40)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It seems like the only reason that we need our own copy of this struct is that we might overwrite some of the values based on the request's headers.  However, copying the struct on every RPC seems wasteful in case where we don't actually need to use the headers.  Can we optimize this somehow such that we copy this only if we actually need to?
</blockquote></details>

Good idea! Though, on the implementation part, I'm not sure if this is the correct way. I encapsulate the copy of the policy as lambda, so we can be less verbose.
___
*[src/core/ext/filters/client_channel/fault_injection.cc, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJASrn3Ap-36UAeUU8z:-MK1c2LB0taz2Td0X5O7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/fault_injection.cc#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

P [...]

2020-10-20 23:01 UTC, markdroth requested changes
Looks like you're making good progress on this!

Don't worry about not iterating that quickly on this.  I probably have more parallel projects than you do. :)

I think we should be consistent across languages in what we're going to support.  If Java and Go can't easily implement rate limiting, we should not do so either.  And it looks like there is a fair amount of complexity even here in C-core for implementing this feature, so I would suggest deferring this for now.

The other noteworthy issue here is the one about how we handle call cancellation, which is also really a comment about how we represent the state of a call.  I think we need to be doing this more implicitly than explicitly, for both performance and memory usage reasons.

Please let me know if you have any questions.  Thanks!

> Reviewed 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MK6VHUD-bkoSGFO76uf:b-9jmxy0)* status: all files reviewed, 43 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4015 at r1](https://reviewable.io/reviews/grpc/grpc/24354#-MJAZhtJ7CBJUjROKCme:-MK6Y-_iAeHgOxs0YnXT:buoh5t9) ([raw file](https://github.com/grpc/grpc/blob/069015e832ac3af4f678d8b53dacc512415a01aa/src/core/ext/filters/client_channel/client_channel.cc#L4015)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Not sure which line 406 you are referring to. So, I merged it with the first `method_params_ != nullptr` check in this method.
</blockquote></details>

Sorry, that was a typo -- I meant 4006.  But you got exactly the spot I intended. :)
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 21 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK6VvMnAdPB1zTskR94:-MK6VvMnAdPB1zTskR95:b-uwzyd0) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L21)):*
> ```cpp
> #include "src/core/ext/filters/client_channel/client_channel.h"
> 
> #include <grpc/support/alloc.h>
> ```

These gRPC includes should be after the absl includes, as per the style guide.

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3008 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK6Wt2rAGbwXSE5Gfvi:-MK6Wt2rAGbwXSE5Gfvj:b-3z8tjz) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L3008)):*
> ```cpp
>   batch_data->Unref();
>   // Invoke callback.
>   if (calld->fault_injection_data_ != nullptr &&
> ```

The `InvokeRecvMessageCallback()` method is called only in the retry code-path.  In the non-retry code-path, the client channel filter does not currently intercept recv_message ops at all, so we would need to add a separate code-path to do that interception when retries are disabled but fault injection rate limiting is enabled.

Let's confirm whether Java and Go are going to be able to support this.  If they're not, then let's not sink any time into this.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3014 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK6XQfQ3Xujb2jNY5Ol:-MK6XQfQ3Xujb2jNY5Om:bilkx3e) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L3014)):*
> ```cpp
>     calld->fault_injection_data_->ThrottleRecvMessageCallback(
>         (*pending->batch->payload->recv_message.recv_message)->length(),
>         recv_message_ready, error);
> ```

You'll need to ref the error here before passing it into this function, because the function will need to take ownership of a ref.

https://github.com/grpc/grpc/blob/master/doc/core/grpc-error.md#ownership-rules
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4112 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK70nQ_3nH1OriAQstD:-MK70nQ_3nH1OriAQstE:b-xrql1o) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L4112)):*
> ```cpp
>     if (*error != GRPC_ERROR_NONE) return true;
>   }
>   // If fault injection policy presents, check if it wants to inject faults.
> ```

s/presents/is present/
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4118 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK701_nDF_5O4pQ4-N_:-MK701_nDF_5O4pQ4-Na:b-q4jfqy) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L4118)):*
> ```cpp
>       GRPC_CLOSURE_INIT(&pick_closure_, PickSubchannel, elem,
>                         grpc_schedule_on_exec_ctx);
>       fault_injection_data_->ScheduleNextPick(&pick_closure_);
> ```

Once this timer is outstanding, we need some way to cancel it if the call gets cancelled.  We probably need to do something similar to `QueuedPickCanceller` above.

Actually, I think there's actually a broader question here about how we're going to represent a call that is currently being delayed.  I think we have two choices:

Option 1: Queue delayed calls using our existing mechanism for queuing picks.
- Queue the pick using `MaybeAddCallToQueuedPicksLocked()`.  This would allow us to use the existing `QueuedPickCanceller` mechanism; we'd just need to modify the canceller to also cancel the timer for the delay.
- The call would hit this code any time the LB policy updates the picker, even if the delay timer is still pending.  It would also hit this code on every retry attempt.
- `MaybeDelay()` would need to return 3 possible responses: "need to start delay timer now", "delay timer already pending", and "delay finished, no need to start one".  The logic here would have to handle all 3 of those cases.
- We would need to keep a bunch of state in `FaultInjectionData` to know when a delay timer is already pending (which you're already doing now, although it would not be necessary under option 2).

Option 2: Rely on the fact that the delay timer is pending to reflect the state of the call.
- We structure the code here such that we call `MaybeDelay()` only on the first call attempt (probably by moving this block inside of the `if (GPR_LIKELY(!service_config_applied_))` block above).
- Because the call would not come back into `PickSubchannelLocked()` until the delay timer finishes, there would be no need to track the state of each type of fault inside of `FaultInjectionData`.
- We would need to have the delay timer callback be a different function that would duplicate the abort check before calling `PickSubchannel()`.
- When we start a delay timer, we will need something analogous to `QueuedPickCanceller` to cancel the delay timer when the call is cancelled.

My inclination is that option 2 is a bit cleaner, since it minimizes both the memory usage (less state to store inside of `FaultInjectionData`) and CPU overhead (because we won't retry the delayed picks every time the LB policy updates the picker, nor would we need to check the fault injection state on subsequent retry attempts).
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 32 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK6Ns7X7DpO25jWduWS:-MK6Ns7X7DpO25jWduWT:by1n58f) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/fault_injection.h#L32)):*
> ```objc
> namespace internal {
> 
> namespace {
> ```

It does not make sense to use an anonymous namespace in a .h file.  The whole point of an anonymous namespace is that it avoids exporting its contents outside of the individual compilation unit.  But this header file is included in other compilation units, which means that they'll all basically see this class declaration anyway.

It looks like the `TokenBucket` class is no [...]

2020-10-23 02:25 UTC, lidizheng reviewed
All comments addressed :
* Axed the response rate limit feature;
* Refactored header matching logic;
* Applied option 2 (check once);
* Added cancellation logic for deferred picks.

About the response rate limit, I have talked to other language's owner. Java and Golang interceptors operate on message-bases and currently have no access to the bytes count. There are two options: 1) ask transport to propagate byte count along with messages; 2) re-serialize the message (`ByteSize()` method still costs CPU). Both sounds cumbersome, so I think we will be better off if we defer this feature till someone ask for it. Relevant code is removed.

---

This batch of commits also implemented the logic to parse HTTP fault config via config selector.

The Json construction part in config selector wasn't ideal to concat string like that. It will make the state machine very complex (like whether to print the last comma). So, this PR refactored that.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MKBXX5S6GpI7H4LqS3Z:b-bu6occ)* status: 15 of 20 files reviewed, 43 unresolved discussions (waiting on @lidizheng and @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 21 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK6VvMnAdPB1zTskR94:-MKCwOaC4DlA-IZdRi8q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L21)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These gRPC includes should be after the absl includes, as per the style guide.

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3008 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK6Wt2rAGbwXSE5Gfvi:-MKCwPS3C5ZLv_KfqDX4:bt16oxp) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L3008)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `InvokeRecvMessageCallback()` method is called only in the retry code-path.  In the non-retry code-path, the client channel filter does not currently intercept recv_message ops at all, so we would need to add a separate code-path to do that interception when retries are disabled but fault injection rate limiting is enabled.

Let's confirm whether Java and Go are going to be able to support this.  If they're not, then let's not sink any time into this.
</blockquote></details>

The response rate limit feature is deferred.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3014 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK6XQfQ3Xujb2jNY5Ol:-MKCwbvKCA8_YFobF7wT:b-ywjcn0) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L3014)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You'll need to ref the error here before passing it into this function, because the function will need to take ownership of a ref.

https://github.com/grpc/grpc/blob/master/doc/core/grpc-error.md#ownership-rules
</blockquote></details>

Thanks for pointing me to the doc. According to the doc, I thought we can relinquish the ownership, since we won't use this error after passing it?
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4112 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK70nQ_3nH1OriAQstD:-MKBZDnO1hmZD6wg2pDJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L4112)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/presents/is present/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4118 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK701_nDF_5O4pQ4-N_:-MKC_dwn0H8hfrGj38RW:b-wqg6wh) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L4118)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Once this timer is outstanding, we need some way to cancel it if the call gets cancelled.  We probably need to do something similar to `QueuedPickCanceller` above.

Actually, I think there's actually a broader question here about how we're going to represent a call that is currently being delayed.  I think we have two choices:

Option 1: Queue delayed calls using our existing mechanism for queuing picks.
- Queue the pick using `MaybeAddCallToQueuedPicksLocked()`.  This would allow us to use the existing `QueuedPickCanceller` mechanism; we'd just need to modify the canceller to also cancel the timer for the delay.
- The call would hit this code any time the LB policy updates the picker, even if the delay timer is still pending.  It would also hit this code on every retry attempt.
- `MaybeDelay()` would need to return 3 possible responses: "need to start delay timer now", "delay timer already pending", and "delay finished, no need to start one".  The logic here would have to handle all 3 of those cases.
- We would need to keep a bunch of state in `FaultInjectionData` to know when a delay timer is already pending (which you're already doing now, although it would not be necessary under option 2).

Option 2: Rely on the fact that the delay timer is pending to reflect the state of the call.
- We structure the code here such that we call `MaybeDelay()` only on the first call attempt (probably by moving this block inside of the `if (GPR_LIKELY(!service_config_applied_))` block above).
- Because the call would not come back into `PickSubchannelLocked()` until the delay timer finishes, there would be no need to track the state of each type of fault inside of `FaultInjectionData`.
- We would need to have the delay timer callback be a different function that would duplicate the abort check before calling `PickSubchannel()`.
- When we start a delay timer, we will need something analogous to `QueuedPickCanceller` to cancel the delay timer when the call is cancelled.

My inclination is that option 2 is a bit cleaner, since it minimizes both the memory usage (less state to store inside of `FaultInjectionData`) and CPU overhead (because we won't retry the delayed picks every time the LB policy updates the picker, nor would we need to check the fault injection state on subsequent retry attempts).
</blockquote></details>

Thanks for the suggestion. Implemented option 2 because it sounds much better than my state machine approach.

Now, the complex states of {not_started, pending, finished} are gone. Though the resume pick logic is a bit confusing. This function needs to pass a pick closure to `FaultInjectionData`, then in the `FaultInjectionData::ResumePick` it checks for abort, performs pick, and decreases the active fault counter.

About the cancellation path, I found there will only be 1 line of difference between a `QueuedPickCanceller` or an equivalent delayed pick canceller. So, I merged them into `ScheduledPickCanceller` which invokes a cancel callback when the call combinator is cancelled.
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 32 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK6Ns7X7DpO25jWduWS:-MKCqDkTAqQN9Jbrg1q4:b-lkkric) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/fault_injection.h#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It does not make sense to use an anonymous namespace in a .h file.  The whole point of an anonymous namespace is that it avoids exporting its contents outside o [...]

2020-10-29 00:31 UTC, markdroth requested changes
This looks like it's moving in the right direction.

FYI, I'm starting to play around with some ideas for how to add the equivalent of HTTP filter support to the client channel filter.  But I don't think this PR needs to be blocked on that -- once I have that figured out, we can move this code into a separate filter.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r3, 13 of 13 files at r4, 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MKlkn044EWjVqWEln4G:b35f4ha)* status: all files reviewed, 45 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3014 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK6XQfQ3Xujb2jNY5Ol:-MKk1mA0BjlMM-Kr7XQi:b-a21vgf) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L3014)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Thanks for pointing me to the doc. According to the doc, I thought we can relinquish the ownership, since we won't use this error after passing it?
</blockquote></details>

This function (`InvokeRecvMessageCallback()`) is a callback function, which means that it does not own a ref to the error to begin with.  So if it passes the error to something else, it needs to create a new ref to pass.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4118 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK701_nDF_5O4pQ4-N_:-MKlhr5tDyGSD_6BaFgy:b-kbp9cd) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L4118)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Thanks for the suggestion. Implemented option 2 because it sounds much better than my state machine approach.

Now, the complex states of {not_started, pending, finished} are gone. Though the resume pick logic is a bit confusing. This function needs to pass a pick closure to `FaultInjectionData`, then in the `FaultInjectionData::ResumePick` it checks for abort, performs pick, and decreases the active fault counter.

About the cancellation path, I found there will only be 1 line of difference between a `QueuedPickCanceller` or an equivalent delayed pick canceller. So, I merged them into `ScheduledPickCanceller` which invokes a cancel callback when the call combinator is cancelled.
</blockquote></details>

This looks pretty good.

I think the confusing resume-pick logic is because of the way you're splitting the logic between here and fault_injection.cc.  I've made a few comments elsewhere about how to improve that.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 198 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkCqUQ470mhbHuPuo7:-MKkCqUQ470mhbHuPuo8:b-w9w59t) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L198)):*
> ```cpp
>       AsyncConnectivityStateWatcherInterface* watcher);
> 
>   Atomic<uint32_t>* active_faults_pointer() { return &active_faults_; }
> ```

This is a simple accessor.  Just call it `active_faults()`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3870 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkBSr1A8jOVcv3EW00:-MKkBSr1A8jOVcv3EW01:b-7gt05j) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L3870)):*
> ```cpp
>  public:
>   explicit SchdueledPickCanceller(grpc_call_element* elem,
>                                   std::function<void()> cancel_callback)
> ```

`std::function<>` will often allocate memory, which is bad for performance.  You can sometimes avoid this by setting the `std::function<>` to a lambda instead of using `std::bind()`, but even that depends on how many parameters you are capturing.  (Look on stackoverflow for a bunch of related info.)  You may want to play with a stripped-down example using godbolt.org to see if you can make this work without allocating memory.

As an alternative, there's not actually any reason why you need to use `std::function<>` here in the first place.  Instead, you could just hard-code knowledge of the two alternatives in `CancelLocked()` and pass in a bool to indicate which one to execute.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3871 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkBQ2J5u4GcPU2lDJx:-MKkBQ2J5u4GcPU2lDJy:b80rlqt) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L3871)):*
> ```cpp
>   explicit SchdueledPickCanceller(grpc_call_element* elem,
>                                   std::function<void()> cancel_callback)
>       : cancel_callback_(cancel_callback), elem_(elem) {
> ```

Please put the data members in the same order as the parameters.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3936 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkCieI1FaxysaoCMhz:-MKkCieI1FaxysaoCMi-:blhcfrc) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L3936)):*
> ```cpp
>   std::function<void()> remove_queued_picks_func =
>       std::bind(&CallData::MaybeRemoveCallFromQueuedPicksLocked, calld, elem);
>   pick_canceller_ = new SchdueledPickCanceller(elem, remove_queued_picks_func);
> ```

`std::move(remove_queued_picks_func)`
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4037 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkDG2n6g1HSYYosooS:-MKkDG2n6g1HSYYosooT:bluict0) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4037)):*
> ```cpp
> void CallData::PickSubchannel(void* arg, grpc_error* error) {
>   grpc_call_element* elem = static_cast<grpc_call_element*>(arg);
>   if (error != GRPC_ERROR_NONE) {
> ```

This also needs to check some local state, because there can be a race between when the closure is scheduled and when it actually executes.  Internally, see go/grpc-c-core-closure-slides for details.  (The slides are a bit dated, so some of the details may be wrong, but the general principles still apply.  This is problem 4 as identified in the slides.)

As per my comments elsewhere, I think this check probably needs to be moved into a new method that will be invoked when the delay timer finishes.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4124 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkDpCuDaQ5Pq0Ouh9X:-MKkDpCuDaQ5Pq0Ouh9Y:b-dthh33) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4124)):*
> ```cpp
>     if (fault_injection_data_ != nullptr) {
>       if (fault_injection_data_->MaybeDelay()) {
>         GRPC_CLOSURE_INIT(&pick_closure_, PickSubchannel, elem,
> ```

As per my comments elsewhere, this callback should go to a new method that will check whether we need to do an abort before it does a pick.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4128 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKliyHE5x0lQ5KrkQVb:-MKliyHE5x0lQ5KrkQVc:bnm3cfh) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4128)):*
> ```cpp
>         // Other faults will be injected on a separate path.
>         fault_injection_data_->DelayPick(&pick_closure_);
>         pick_canceller_ = new SchdueledPickCanceller(
> ```

Once the delay is done, you need to reset `pick_canceller_` to null, so that if the call is subsequently cancelled, the pick can [...]

2020-11-04 01:41 UTC, lidizheng reviewed
*Clap* The major updates are listed above as commit message. I think we got most of the features and test cases in, thanks again for countless suggestions. PTALAAA.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MLFsn8dEYYOeINVtNft:b-miyp14)* status: 9 of 41 files reviewed, 44 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3014 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK6XQfQ3Xujb2jNY5Ol:-MLA9VDnCX6PH44TEH01:bkbxtdf) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/client_channel.cc#L3014)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This function (`InvokeRecvMessageCallback()`) is a callback function, which means that it does not own a ref to the error to begin with.  So if it passes the error to something else, it needs to create a new ref to pass.
</blockquote></details>

:+1: That makes sense.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 198 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkCqUQ470mhbHuPuo7:-MLA3Xhk4kd20-SPs94G:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L198)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is a simple accessor.  Just call it `active_faults()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3870 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkBSr1A8jOVcv3EW00:-MLAANIx0bYXPTl1BXQF:b-b9vy8d) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L3870)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::function<>` will often allocate memory, which is bad for performance.  You can sometimes avoid this by setting the `std::function<>` to a lambda instead of using `std::bind()`, but even that depends on how many parameters you are capturing.  (Look on stackoverflow for a bunch of related info.)  You may want to play with a stripped-down example using godbolt.org to see if you can make this work without allocating memory.

As an alternative, there's not actually any reason why you need to use `std::function<>` here in the first place.  Instead, you could just hard-code knowledge of the two alternatives in `CancelLocked()` and pass in a bool to indicate which one to execute.
</blockquote></details>

Removed the `std::function` completely, and replaced with `enum` + `if/else`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3871 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkBQ2J5u4GcPU2lDJx:-MLAAWqG5v3fJoUPC-c9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L3871)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please put the data members in the same order as the parameters.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3936 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkCieI1FaxysaoCMhz:-MLAAYUF7k1ao_LNJvML:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L3936)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move(remove_queued_picks_func)`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4037 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkDG2n6g1HSYYosooS:-MLABBxuDRKyuaxJdFGT:bq7lv1k) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4037)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This also needs to check some local state, because there can be a race between when the closure is scheduled and when it actually executes.  Internally, see go/grpc-c-core-closure-slides for details.  (The slides are a bit dated, so some of the details may be wrong, but the general principles still apply.  This is problem 4 as identified in the slides.)

As per my comments elsewhere, I think this check probably needs to be moved into a new method that will be invoked when the delay timer finishes.
</blockquote></details>

Emm... I updated the `CallData::ResumePickAfterDelay` to directly invoke the `PickDone` method, so no change is required in `PickSubchannel`. Is this a valid solution for problem 4?

Discussion about previous version: I was passing the state directly via error. Since the execution order of `ResumePickAfterDelay` and `PickSubchannel` is fixed. In the client_channel, on any given time, there shouldn't be two pending pick. So, there won't be another closure race to finish the pick. In this case, do we still need to worry about the potential race condition?
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4124 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkDpCuDaQ5Pq0Ouh9X:-MLFrj12DLjg53JJmXM-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per my comments elsewhere, this callback should go to a new method that will check whether we need to do an abort before it does a pick.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4128 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKliyHE5x0lQ5KrkQVb:-MLAGp32Du1M5wcSDuso:bfcyatg) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4128)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Once the delay is done, you need to reset `pick_canceller_` to null, so that if the call is subsequently cancelled, the pick canceller will know not to actually do anything.  This will probably need to be done in the new callback I suggested for handling the delay completion.

Note that `pick_canceller_` must be modified while holding the data plane lock.  This probably means that the new callback for delay completion will need to duplicate some of the code from `PickSubchannel()` rather than just calling `PickSubchannel()`, since otherwise we'll wind up acquiring and releasing the mutex twice.

(I suspect that the fact that you're not resetting `pick_canceller_` is the reason for the call combiner problem you mentioned.)
</blockquote></details>

LOL. It's funny that the recurring call combiner problem is not caused by the new logic, but by `WaitForAllBackends` in tests. `WaitForAllBackends` requires all RPC to come back successfully, however, with percentage delay injection, it almost never able to get all RPC return OK. So it retries every 1 second in its while loop.

Back to the reset of canceller, in the new commit, I split the canceller into 2 (queued_pick_canceller and delayed_pick_canceller). So, they can be reset separately, and have less impact on other part of the existing queuing logic.
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 100 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK7CUHY441B0g-NnN7o:-MLAL2GT0Kc7o78kP7LQ:b-w18ucs) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/fault_injection.h#L100)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote> [...]

2020-11-06 03:08 UTC, lidizheng commented
Strangely, I'm observing an resurrection of `XdsClient`, still investigating the root cause:

```
I1106 03:04:25.548652288  843881 client_channel.cc:1436]     chand=0x245dcc8: update: state=IDLE status=(OK) picker=0x7f1008001fe0
I1106 03:04:25.548677208  843881 client_channel.cc:1786]     chand=0x245dcc8: updating subchannel wrapper 0x24590b0 data plane connected_subchannel to (nil)
I1106 03:04:25.548696466  843881 ref_counted.h:165]          SubchannelWrapper:0x24590b8 unref 3 -> 2
I1106 03:04:25.548713454  843881 ref_counted.h:165]          SubchannelWrapper:0x24590b8 unref 2 -> 1
I1106 03:04:25.548736063  843881 ref_counted.h:182]          SubchannelWrapper:0x24590b8 src/core/ext/filters/client_channel/client_channel.cc:1086 unref 1 -> 0 WatcherWrapper
I1106 03:04:25.548752140  843881 client_channel.cc:942]      chand=0x245dcc8: destroying subchannel wrapper 0x24590b0 for subchannel 0x247ac40
I1106 03:04:25.548800871  843877 xds_bootstrap.cc:172]       [xds_client 0x2457ac0] Bootstrap config for creating xds client:
node={
  id="xds_end2end_test",
  cluster="test",
  locality={
    region="corp",
    zone="svl",
    subzone="mp3"
  },
  metadata={"foo":"bar"},
},
servers=[
  {
    uri="fake:///xds_server",
    creds_type=fake,
    server_features=[xds_v3],
  }
],
certificate_providers={
}
I1106 03:04:25.548836410  843877 xds_client.cc:1750]         [xds_client 0x2457ac0] creating xds client
I1106 03:04:25.548853120  843877 dual_ref_counted.h:311]     XdsClient:0x2457ac0 src/core/ext/xds/xds_client.cc:1759 weak_ref 0 -> 1 (refs=1) XdsClient+ChannelState
I1106 03:04:25.548867537  843877 xds_client.cc:468]          [xds_client 0x2457ac0] creating channel to fake:///xds_server
I1106 03:04:25.548968750  843877 client_channel.cc:1668]     chand=0x2436c68: creating client_channel for channel stack 0x2436bb8
I1106 03:04:25.549081385  843877 ref_counted.h:86]           ChannelState:0x247bd58 src/core/ext/xds/xds_client.cc:519 ref 1 -> 2 ChannelState+watch
I1106 03:04:25.549169015  843877 dual_ref_counted.h:262]     XdsClient:0x2457ac0 ref 1 -> 2; (weak_refs=1)
E1106 03:04:25.549194098  843877 eds.cc:317]                 assertion failed: server_uri != nullptr
Stack trace:
    @     0x7f101e97d1ff        112  _ZN9grpc_core20GetCurrentStackTraceB5cxx11Ev
    @     0x7f101e9780bb        400  gpr_default_log()
    @     0x7f101e977839         80  gpr_log_message
    @     0x7f101e977ea0        432  gpr_log
    @     0x7f101f5a8991        304  grpc_core::(anonymous namespace)::EdsLb::EdsLb()
    @     0x7f101f5a85a5        144  grpc_core::MakeOrphanable<>()
    @     0x7f101f5a8499         80  grpc_core::(anonymous namespace)::EdsLbFactory::EdsChildHandler::CreateLoadBalancingPolicy()
    @     0x7f101ed28fe3        608  grpc_core::ChildPolicyHandler::CreateChildPolicy()
    @     0x7f101ed28b4d        416  grpc_core::ChildPolicyHandler::UpdateLocked()
    @     0x7f101f6116cd       4048  grpc_core::(anonymous namespace)::CdsLb::OnClusterChanged()
    @     0x7f101f60fac7        256  grpc_core::(anonymous namespace)::CdsLb::ClusterWatcher::Notifier::RunInWorkSerializer()
    @     0x7f101f60f9ec         32  grpc_core::(anonymous namespace)::CdsLb::ClusterWatcher::Notifier::RunInExecCtx()::$_0::operator()()
    @     0x7f101f60f9ad         32  std::__invoke_impl<>()
    @     0x7f101f60f94d         32  std::__invoke_r<>()
    @     0x7f101f60f84d         32  std::_Function_handler<>::_M_invoke()
    @           0x55ebce         32  std::function<>::operator()()
    @     0x7f101eb19881         96  grpc_core::WorkSerializer::WorkSerializerImpl::DrainQueue()
    @     0x7f101eb19527        160  grpc_core::WorkSerializer::WorkSerializerImpl::Run()
    @     0x7f101eb19a2e        112  grpc_core::WorkSerializer::Run()
    @     0x7f101ece636d        128  grpc_core::(anonymous namespace)::ChannelData::StartTransportOp()
    @     0x7f101eb36243         96  grpc_channel_destroy_internal()
    @     0x7f101eb362af        144  grpc_channel_destroy
    @     0x7f101fa7de34         48  grpc::Channel::~Channel()
    @     0x7f101fa7dfcc         32  grpc::Channel::~Channel()
    @     0x7f101fa876af         32  std::_Sp_counted_ptr<>::_M_dispose()
    @           0x550cb4        160  std::_Sp_counted_base<>::_M_release()
    @           0x550bfa         32  std::__shared_count<>::~__shared_count()
    @           0x580c4e         32  std::__shared_ptr<>::~__shared_ptr()
    @           0x5510f8         32  std::shared_ptr<>::~shared_ptr()
    @           0x4766f3         32  grpc::testing::(anonymous namespace)::XdsEnd2endTest::~XdsEnd2endTest()
    @           0x476448         32  grpc::testing::(anonymous namespace)::BasicTest::~BasicTest()
    @           0x4f3608         32  grpc::testing::(anonymous namespace)::LdsRdsTest_XdsRoutingFaultInjectionAlwaysAbort_Test::~LdsRdsTest_XdsRoutingFaultInjectionAlwaysAbort_Test()

*** SIGABRT received at time=1604631865 ***
PC: @     0x7f101d8dedb1  (unknown)  raise
    @     0x7f101f962fca         48  absl::lts_2020_09_23::WriteFailureInfo()
    @     0x7f101f962c90        240  absl::lts_2020_09_23::AbslFailureSignalHandler()
    @     0x7f101da96140  (unknown)  (unknown)
    @     0x7f101f5a85a5        144  grpc_core::MakeOrphanable<>()
    @     0x7f101f5a8499         80  grpc_core::(anonymous namespace)::EdsLbFactory::EdsChildHandler::CreateLoadBalancingPolicy()
    @     0x7f101ed28fe3        608  grpc_core::ChildPolicyHandler::CreateChildPolicy()
    @     0x7f101ed28b4d        416  grpc_core::ChildPolicyHandler::UpdateLocked()
    @     0x7f101f6116cd       4048  grpc_core::(anonymous namespace)::CdsLb::OnClusterChanged()
    @     0x7f101f60fac7        256  grpc_core::(anonymous namespace)::CdsLb::ClusterWatcher::Notifier::RunInWorkSerializer()
    @     0x7f101f60f9ec         32  grpc_core::(anonymous namespace)::CdsLb::ClusterWatcher::Notifier::RunInExecCtx()::$_0::operator()()
    @     0x7f101f60f9ad         32  std::__invoke_impl<>()
    @     0x7f101f60f94d         32  std::__invoke_r<>()
    @     0x7f101f60f84d         32  std::_Function_handler<>::_M_invoke()
    @           0x55ebce         32  std::function<>::operator()()
    @     0x7f101eb19881         96  grpc_core::WorkSerializer::WorkSerializerImpl::DrainQueue()
    @     0x7f101eb19527        160  grpc_core::WorkSerializer::WorkSerializerImpl::Run()
    @     0x7f101eb19a2e        112  grpc_core::WorkSerializer::Run()
    @     0x7f101ece636d        128  grpc_core::(anonymous namespace)::ChannelData::StartTransportOp()
    @     0x7f101eb36243         96  grpc_channel_destroy_internal()
    @     0x7f101eb362af        144  grpc_channel_destroy
    @     0x7f101fa7de34         48  grpc::Channel::~Channel()
    @     0x7f101fa7dfcc         32  grpc::Channel::~Channel()
    @     0x7f101fa876af         32  std::_Sp_counted_ptr<>::_M_dispose()
    @           0x550cb4        160  std::_Sp_counted_base<>::_M_release()
    @           0x550bfa         32  std::__shared_count<>::~__shared_count()
    @           0x580c4e         32  std::__shared_ptr<>::~__shared_ptr()
    @           0x5510f8         32  std::shared_ptr<>::~shared_ptr()
    @           0x4766f3         32  grpc::testing::(anonymous namespace)::XdsEnd2endTest::~XdsEnd2endTest()
    @           0x476448         32  grpc::testing::(anonymous namespace)::BasicTest::~BasicTest()
    @           0x4f3608         32  grpc::testing::(anonymous namespace)::LdsRdsTest_XdsRoutingFaultInjectionAlwaysAbort_Test::~LdsRdsTest_XdsRoutingFaultInjectionAlwaysAbort_Test()
    @           0x4f362c         32  grpc::testing::(anonymous namespace)::LdsRdsTest_XdsRoutingFaultInjectionAlwaysAbort_Test::~LdsRdsTest_XdsRoutingFaultInjectionAlwaysAbort_Test()
    @     0x7f101db85b7b         32  testing::Test::DeleteSelf_()
    @ ... and at least 12 more frames
```

2020-11-06 03:23 UTC, lidizheng commented
Root cause: Between two locks, some other method invoked `XdsClient::GetOrCreate` and found `g_xds_client` missing...

https://github.com/grpc/grpc/blob/master/src/core/ext/xds/xds_client.cc#L1794

Solution: Grab both the global lock and instance lock to perform the shutdown atomically.

2020-11-06 15:58 UTC, markdroth requested changes
This is shaping up nicely!

The XdsClient is expected be resurrected for each new test.  The old one may not yet have fully shut down yet, so there may be some overlap in their lifetimes; that's normal.  I don't think that's related to the crash you're seeing, nor do I think the locking there needs any changes.

My guess is that the crash you're seeing is related to the use-after-free bug you have in the xds resolver, although I'm not sure.

Please let me know if you have any questions.  Thanks!

> Reviewed 13 of 24 files at r6, 12 of 16 files at r7, 7 of 7 files at r8, 19 of 19 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MLTEMJJ1EkEGOAp5R1-:b-7obg5x)* status: all files reviewed, 61 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3918 at r3](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ5QoE7lsKmRzLWq_C:-MLQ5QoE7lsKmRzLWq_D:b-f15hwu) ([raw file](https://github.com/grpc/grpc/blob/dc7ac5e931aeb12e9408c63e2b81545c426d5f5f/src/core/ext/filters/client_channel/client_channel.cc#L3918)):*
> ```cpp
>   chand->RemoveQueuedPick(&pick_, pollent_);
>   pick_queued_ = false;
>   // Lame the call combiner canceller.
> ```

Please keep this comment.  It's important to understand why the next line is necessary.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4037 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkDG2n6g1HSYYosooS:-MLQDdTq6pMqs6XbrHCu:bkleuch) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4037)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Emm... I updated the `CallData::ResumePickAfterDelay` to directly invoke the `PickDone` method, so no change is required in `PickSubchannel`. Is this a valid solution for problem 4?

Discussion about previous version: I was passing the state directly via error. Since the execution order of `ResumePickAfterDelay` and `PickSubchannel` is fixed. In the client_channel, on any given time, there shouldn't be two pending pick. So, there won't be another closure race to finish the pick. In this case, do we still need to worry about the potential race condition?


</blockquote></details>

No, this does not solve the problem.  The problem here is not a race between `ResumePickAfterDelay()` and `PickSubchannel()`; it's a race between `ResumePickAfterDelay()` and the cancellation callback.

I think if you grab the data plane mutex here to reset `pick_canceller_`, as I suggest below, that will solve the problem.  If `pick_canceller_` is already null when you get here, that means that the canceller has already run, and you can just return without doing anything else.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4128 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKliyHE5x0lQ5KrkQVb:-MLQ6PCyBtlXq0hD_8rE:bwyf6hy) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4128)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

LOL. It's funny that the recurring call combiner problem is not caused by the new logic, but by `WaitForAllBackends` in tests. `WaitForAllBackends` requires all RPC to come back successfully, however, with percentage delay injection, it almost never able to get all RPC return OK. So it retries every 1 second in its while loop.

Back to the reset of canceller, in the new commit, I split the canceller into 2 (queued_pick_canceller and delayed_pick_canceller). So, they can be reset separately, and have less impact on other part of the existing queuing logic.
</blockquote></details>

I don't see how a problem in the test could possibly cause a call combiner problem.  No matter what the client code does, the code here should enforce proper usage of the call combiner.  If you can trigger a call combiner problem by doing something different in a test, then there's a bug here, not in the test.

I don't see how storing the cancellers in two separate fields helps here, and it unnecessarily increases the call data memory size, so I don't think that's a good change.

You still need to change `ResumePickAfterDelay()` to set `pick_canceller_` to nullptr when the delay finishes, so that if the call is cancelled later, the pick canceller knows not to actually do anything.  And resetting `pick_canceller_` to null requires holding the data plane mutex, which means that you need to change `ResumePickAfterDelay()` to duplicate some of the code from `PickSubchannel()` rather than just calling `PickSubchannel()`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 396 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ3jMNEIAgCJQ6xkhl:-MLQ3jMNEIAgCJQ6xkhm:bhk9zrj) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L396)):*
> ```cpp
>  private:
>   // Types of scheduled subchannel pick, used by ScheduledPickCanceller.
>   enum ScheduledPickType {
> ```

This can go inside of `ScheduledPickCanceller`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 398 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ47PzDyzrwgV9oHBB:-MLQ47PzDyzrwgV9oHBC:bbfe4pi) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L398)):*
> ```cpp
>   enum ScheduledPickType {
>     // Default value.
>     UNKNOWN_PICK,
> ```

Is this ever going to be unset?  If not, then this isn't necessary.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 832 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ4FkyB_tzE5hogYPo:-MLQ4FkyB_tzE5hogYPp:b-ty5eyh) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L832)):*
> ```cpp
>   bool service_config_applied_ = false;
>   ScheduledPickCanceller* queued_pick_canceller_ = nullptr;
>   ScheduledPickCanceller* delayed_pick_canceller_ = nullptr;
> ```

Is a pick ever going to be queued and delayed at the same time?  If not, there's no need for a separate data member here -- just use the same pointer in both cases.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 840 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ3t8V4KeG_Ih9Yd_5:-MLQ3t8V4KeG_Ih9Yd_6:b-kvve4t) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L840)):*
> ```cpp
>       lb_recv_trailing_metadata_ready_;
>   grpc_closure pick_closure_;
>   grpc_closure delayed_pick_closure_;
> ```

Why do we need an extra closure here?  Are we ever using `pick_closure_` and this at the same time?  If not, let's just use one closure for both.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3882 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ4mtI6TXIDEpV_U4D:-MLQ4mtI6TXIDEpV_U4E:b-cnj9ws) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L3882)):*
> ```cpp
> class CallData::ScheduledPickCanceller {
>  public:
>   explicit ScheduledPickCanceller(grpc_call_element* elem,
> ```

This no longer needs to be `explicit`, since there are now two arguments.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3910 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ5K911KusJqWKrAdV:-MLQ5K911KusJqWKrAdW:bcg8u55) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L3910)):*
> ```cpp
>         if (calld->queued_pick_canceller_ == self) {
>           // Remove pick from list of queued picks.
>           calld->MaybeInv [...]

2020-11-13 00:16 UTC, lidizheng reviewed
After several days of digging in trace logs and gdb, I finally resolved one of the memory leak issue introduced in this bug. It is caused by a `call_config` not being deallocated, but it unfortunately owns a `ResolverLoadBalancingPolicy` object, which causes the `ClientChannelControlHelper` to linger, and eventually caused channel_stack (or grpc_stream) reference unable to reduce to 0, in turn, all the channel data objects won't be freed.

The ASAN complain is not that helpful at this debugging, because the `ChannelData` owns so many different things that if one channel is leaked, there are also hundreds of objects leaked, and it will produce 7.5MB of text detailing every single object... Also, thanks to Esun (@veblush) and Mark to quickly chat with me, so I can find the right approach to debug.

(Since you mentioned the resurrection is harmless, I didn't dig further. I thought it was the culprit of the leak, but it is not.)

Thanks again for the very thorough review! I have resolved all comments, and found an interesting bug https://github.com/grpc/grpc/pull/24720. PTAL.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MLto2RzD2FT6r1Tbcbj:b-rsmgly)* status: 30 of 42 files reviewed, 61 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3918 at r3](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ5QoE7lsKmRzLWq_C:-MLTpRLW16FTo-bVvukG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dc7ac5e931aeb12e9408c63e2b81545c426d5f5f/src/core/ext/filters/client_channel/client_channel.cc#L3918)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please keep this comment.  It's important to understand why the next line is necessary.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4037 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkDG2n6g1HSYYosooS:-MLoM6tV9zHehhIoGVGy:b-lnlila) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4037)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No, this does not solve the problem.  The problem here is not a race between `ResumePickAfterDelay()` and `PickSubchannel()`; it's a race between `ResumePickAfterDelay()` and the cancellation callback.

I think if you grab the data plane mutex here to reset `pick_canceller_`, as I suggest below, that will solve the problem.  If `pick_canceller_` is already null when you get here, that means that the canceller has already run, and you can just return without doing anything else.
</blockquote></details>

Thanks for the suggestion. I used the data plane mutex in `ResumePickAfterDelay()` to set `pick_canceller_` to `nullptr`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4128 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKliyHE5x0lQ5KrkQVb:-MLoMOfu4vWU4BsLej6g:b5si8v0) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4128)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see how a problem in the test could possibly cause a call combiner problem.  No matter what the client code does, the code here should enforce proper usage of the call combiner.  If you can trigger a call combiner problem by doing something different in a test, then there's a bug here, not in the test.

I don't see how storing the cancellers in two separate fields helps here, and it unnecessarily increases the call data memory size, so I don't think that's a good change.

You still need to change `ResumePickAfterDelay()` to set `pick_canceller_` to nullptr when the delay finishes, so that if the call is cancelled later, the pick canceller knows not to actually do anything.  And resetting `pick_canceller_` to null requires holding the data plane mutex, which means that you need to change `ResumePickAfterDelay()` to duplicate some of the code from `PickSubchannel()` rather than just calling `PickSubchannel()`.
</blockquote></details>

It was not a call combiner problem. I saw the log of multiple call combiner cancellation, but each of them represents different RPC generated by the while loop. My bad.

The canceller is unified into one, and now the delay canceller will be nullify under a data plane mutex.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 396 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ3jMNEIAgCJQ6xkhl:-MLTnKpq5yeQGkxGQojG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L396)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can go inside of `ScheduledPickCanceller`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 398 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ47PzDyzrwgV9oHBB:-MLTnUV0A6a4O9qrcwRB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L398)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this ever going to be unset?  If not, then this isn't necessary.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 832 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ4FkyB_tzE5hogYPo:-MLTndZbBFZIt1bLgi6c:bwzvuxt) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L832)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is a pick ever going to be queued and delayed at the same time?  If not, there's no need for a separate data member here -- just use the same pointer in both cases.
</blockquote></details>

Done. That means we will lost track of the previous canceller. But since the closure will make sure previous canceller's deletion, we should be fine.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 840 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ3t8V4KeG_Ih9Yd_5:-MLTnuwN-uJj0FiPvYZO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L840)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why do we need an extra closure here?  Are we ever using `pick_closure_` and this at the same time?  If not, let's just use one closure for both.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3882 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ4mtI6TXIDEpV_U4D:-MLToeW35d3EnCFyWRYJ:bb741ss) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L3882)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This no longer needs to be `explicit`, since there are now two arguments.
</blockquote></details>

TIL.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3910 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLQ5K911KusJqWKrAdV:-MLTofImDyuD2DcUIxXV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/filters/client_channel/client_channel.cc#L3910)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this needs to be invoked in the delayed-pick case too.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3922 at r8](https://reviewable.i [...]

2020-11-14 00:42 UTC, markdroth requested changes
This is moving in the right direction!

There are two really noteworthy issues here: I think the handling of the callback race condition is still not quite right, and I think we should clean up the way the code is split between the `CallData` and `FaultInjectionData`.

Please let me know if you have any questions.  Thanks!

> Reviewed 11 of 12 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MM3BbMV8B1daaMMnRWF:b4nyl07)* status: all files reviewed, 30 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4037 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkDG2n6g1HSYYosooS:-MM1enzfA11wPSI1k3JJ:b-kv5vii) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4037)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Thanks for the suggestion. I used the data plane mutex in `ResumePickAfterDelay()` to set `pick_canceller_` to `nullptr`.
</blockquote></details>

I think you still need to check whether `pick_canceller_` was already null, because if it was, the batches will already have been failed, and the code here should not do anything else.  Otherwise, you're not solving this race condition.

Also, the way this is written now, you will grab and release the data plane mutex twice, once before resetting `pick_canceller_` and then again inside of `PickSubchannel()`.  This will increase lock contention; it's better to just do this once.

I suggest something like this:

```
bool pick_complete;
{
  MutexLock lock(chand->data_plane_mu());
  // If timer was cancelled or canceller has already run, then we have nothing to do here.
  if (error == GRPC_ERROR_CANCELLED || calld->pick_canceller_ == nullptr) return;
  // Lame the canceller, so that when it runs later, it knows not to do anything.
  calld->pick_canceller_ = nullptr;
  // Finish delay.
  calld->fault_injection_data_->DelayFinished(chand->active_faults());
  // Abort if needed.
  error = calld->fault_injection_data_->MaybeAbort(chand->active_faults());
  if (error != GRPC_ERROR_NONE) {
    calld->MaybeInvokeConfigSelectorCommitCallback();
    pick_complete = true;
  } else {
    pick_complete = calld->PickSubchannelLocked(elem, &error);
  }
}
if (pick_complete) {
  PickDone(elem, error);
  GRPC_ERROR_UNREF(error);
}
```

Note that this approach also means that the active-faults counter will be accessed only while holding the data plane mutex.  This means it no longer needs to be an atomic; it can be a simple integer instead.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3862 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1iOAk7deM6H3Hovm8:-MM1iOAk7deM6H3Hovm9:brw1hsr) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L3862)):*
> ```cpp
>     }
>     calld->PendingBatchesFail(elem, GRPC_ERROR_REF(error),
>                               YieldCallCombinerIfPendingBatchesFound);
> ```


I don't think there should be any case where we get here and there will not be any pending batches.  I suspect that that's happening now only because you're not properly handling the race condition in `ResumePickAfterDelay()`.  Once you fix the logic in `ResumePickAfterDelay()`, as per my comments below, I think this can go back to just using `YieldCallCombiner`. 
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3870 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1dpEy9OarGMGMDAv2:-MM1dpEy9OarGMGMDAv3:b75pj7d) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L3870)):*
> ```cpp
> // A class to handle the call combiner cancellation callback for a
> // schdueled pick (either queued or delayed).
> class CallData::ScheduledPickCanceller {
> ```

This can just be called `PickCanceller`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3873 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1eQWkAeaRceghE0uN:-MM1eQWkAeaRceghE0uO:byd7h8c) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L3873)):*
> ```cpp
>  public:
>   // Types of scheduled subchannel pick, used by ScheduledPickCanceller.
>   enum ScheduledPickType {
> ```

This can just be called `PickType`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3874 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1dfWW1hIs5fB63SzG:-MM1dfWW1hIs5fB63SzH:b2spvtw) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L3874)):*
> ```cpp
>   // Types of scheduled subchannel pick, used by ScheduledPickCanceller.
>   enum ScheduledPickType {
>     // The pick is queued until there is update from upstream.
> ```

This should say "The pick is queued waiting for either name resolution or load balancing.".
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4058 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1pDrX7mjvQFjLMtgV:-MM1pDrX7mjvQFjLMtgW:b-kx1o37) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L4058)):*
> ```cpp
>   }
>   if (error == GRPC_ERROR_NONE) {
>     calld->fault_injection_data_->DelayFinished(chand->active_faults());
> ```

Calling `DelayFinished()` followed by `MaybeAbort()` means that we will decrement and then immediately re-increment the active-faults counter.  This seems like unnecessary churn -- if we've already incremented it for the delay (and verified that there were not too many active faults) and it's already considered an active fault, then we should check whether we want to abort here based solely on the dice roll, not on the counter.  Then we can decrement the counter once we've determined whether we want to abort.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4171 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1hY0WDWiqiSmnEfsG:-MM1hY0WDWiqiSmnEfsH:b-7a1ux5) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L4171)):*
> ```cpp
>       if (*error != GRPC_ERROR_NONE) {
>         // If the RPC is aborted, invoke the config selector callback and end
>         // the pick. The call may or maynot be retried later, but if we don't
> ```

s/maynot/may not/
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 100 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK7CUHY441B0g-NnN7o:-MM1nWYY0Zvofsx6hZKW:b3t6dsi) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/fault_injection.h#L100)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Hard coded the increment and decrement of the active faults in different code paths.

Personally, I found the new method quite error-prone. The logic between `FaultInjectionData` and `CallData` is even more coupled, because operations in `CallData` have to consider the state of `FaultInjectionData` whose methods are not idempotent any more.
</blockquote></details>

I agree with you that the way that the logic is split between `FaultInjectionData` and `CallData` is difficult to follow.  However, I think the right solution to that is move the control logic completely into `CallData`, so that we stop trying to hop back and forth between the two.

I think it's fine for `FaultInjectionData` to contain all of the data members that it currently has.  But I think all of the control-flow logic should be in `CallData`, since that will all be handled as part of the normal flow of the ca [...]

2020-11-17 19:52 UTC, lidizheng reviewed
Thanks for the detailed suggestion for solving the race condition between the resumed pick and the canceller. It was the culprit of the call combiner issue I observed earlier, and never found the right solution.

More tests are added, and existing tests are revamped to use the new xDS resource set method. PTAL.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MMIgmCX7lyYyyKC5ehT:b-triqwj)* status: 16 of 40 files reviewed, 31 unresolved discussions (waiting on @gnossen and @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4037 at r5](https://reviewable.io/reviews/grpc/grpc/24354#-MKkDG2n6g1HSYYosooS:-MMHd5Mb50pz42RXOgob:bruezjs) ([raw file](https://github.com/grpc/grpc/blob/3511adbbd59bdb3535d3df9cbda67dc2ecc48095/src/core/ext/filters/client_channel/client_channel.cc#L4037)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you still need to check whether `pick_canceller_` was already null, because if it was, the batches will already have been failed, and the code here should not do anything else.  Otherwise, you're not solving this race condition.

Also, the way this is written now, you will grab and release the data plane mutex twice, once before resetting `pick_canceller_` and then again inside of `PickSubchannel()`.  This will increase lock contention; it's better to just do this once.

I suggest something like this:

```
bool pick_complete;
{
  MutexLock lock(chand->data_plane_mu());
  // If timer was cancelled or canceller has already run, then we have nothing to do here.
  if (error == GRPC_ERROR_CANCELLED || calld->pick_canceller_ == nullptr) return;
  // Lame the canceller, so that when it runs later, it knows not to do anything.
  calld->pick_canceller_ = nullptr;
  // Finish delay.
  calld->fault_injection_data_->DelayFinished(chand->active_faults());
  // Abort if needed.
  error = calld->fault_injection_data_->MaybeAbort(chand->active_faults());
  if (error != GRPC_ERROR_NONE) {
    calld->MaybeInvokeConfigSelectorCommitCallback();
    pick_complete = true;
  } else {
    pick_complete = calld->PickSubchannelLocked(elem, &error);
  }
}
if (pick_complete) {
  PickDone(elem, error);
  GRPC_ERROR_UNREF(error);
}
```

Note that this approach also means that the active-faults counter will be accessed only while holding the data plane mutex.  This means it no longer needs to be an atomic; it can be a simple integer instead.
</blockquote></details>

Thanks for the rewrite! I did miss the `GRPC_ERROR_CANCELLED` case.

I have updated the `active_faults` to `uint32_t`. Also, combining the next comment, the active-faults quota check is omitted.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3862 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1iOAk7deM6H3Hovm8:-MMHccZZ5MCqQsT_xBjO:bcdhafk) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L3862)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think there should be any case where we get here and there will not be any pending batches.  I suspect that that's happening now only because you're not properly handling the race condition in `ResumePickAfterDelay()`.  Once you fix the logic in `ResumePickAfterDelay()`, as per my comments below, I think this can go back to just using `YieldCallCombiner`. 
</blockquote></details>

Changed back to `YieldCallCombiner`. Yeah, the ref-count issue was indeed due to the race between `ResumePickAfterDelay` and `PickCanceller`, also I didn't handle the `GRPC_ERROR_CANCELLED`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3870 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1dpEy9OarGMGMDAv2:-MMHVXaPCkNOT_TJKvIV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L3870)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can just be called `PickCanceller`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3873 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1eQWkAeaRceghE0uN:-MMHVXwr3U8BcQYp4VM-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L3873)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can just be called `PickType`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3874 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1dfWW1hIs5fB63SzG:-MMHVhPVDiIYQkDtH7vH:b-dasa1f) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L3874)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should say "The pick is queued waiting for either name resolution or load balancing.".
</blockquote></details>

Done. That's nicer.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4058 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1pDrX7mjvQFjLMtgV:-MMHhKsn9Mhu_fsz8fW9:bpckp4a) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L4058)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Calling `DelayFinished()` followed by `MaybeAbort()` means that we will decrement and then immediately re-increment the active-faults counter.  This seems like unnecessary churn -- if we've already incremented it for the delay (and verified that there were not too many active faults) and it's already considered an active fault, then we should check whether we want to abort here based solely on the dice roll, not on the counter.  Then we can decrement the counter once we've determined whether we want to abort.
</blockquote></details>

Done. The active-fault quota check now is skippable, if we supply a `nullptr` to `MaybeAbort()`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 4171 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1hY0WDWiqiSmnEfsG:-MMHW2dw5XXiARqij7Jn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/client_channel.cc#L4171)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/maynot/may not/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection.h, line 100 at r2](https://reviewable.io/reviews/grpc/grpc/24354#-MK7CUHY441B0g-NnN7o:-MMI89-gBrjUE4NHTuFk:b-gihhet) ([raw file](https://github.com/grpc/grpc/blob/f5560216f92a8305e93c85a53b03563706b86428/src/core/ext/filters/client_channel/fault_injection.h#L100)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I agree with you that the way that the logic is split between `FaultInjectionData` and `CallData` is difficult to follow.  However, I think the right solution to that is move the control logic completely into `CallData`, so that we stop trying to hop back and forth between the two.

I think it's fine for `FaultInjectionData` to contain all of the data members that it currently has.  But I think all of the control-flow logic should be in `CallData`, since that will all be handled as part of the normal flow of the callbacks in that code.

Maybe it would make sense to just make `FaultInjectionData` a struct instead of a class and move the code from most of its methods into `CallData`?
</blockquote></details>

Merged FaultInjectionData into `client_channel.cc` as a sub-struct of CallData.
___
*[src/core/ext/filters/client_ [...]

2020-11-18 01:58 UTC, markdroth requested changes
This is pretty close now!  My comments are all fairly minor things.

Please let me know if you have any questions.  Thanks!

> Reviewed 23 of 26 files at r14, 2 of 3 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MMO3lxSD2cn93nkuTKr:b6qj8zh)* status: all files reviewed, 14 unresolved discussions (waiting on @donnadionne, @gnossen, and @lidizheng)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 598 at r15](https://reviewable.io/reviews/grpc/grpc/24354#-MMNtdU_-RWTuge9LWOo:-MMNtdU_-RWTuge9LWOp:b-yl2q0o) ([raw file](https://github.com/grpc/grpc/blob/4246b6146f5ae1be07eefd28f055e64ba6aa1e15/src/core/ext/filters/client_channel/client_channel.cc#L598)):*
> ```cpp
>   //   2. Roll the fault-injection dice;
>   //   3. Maintain the counter of active faults.
>   struct FaultInjectionData {
> ```

You've changed this to be a struct instead of a class, but you're still using class style for it (e.g., using `_` suffixes for data members, having all access go through methods that impose invariants across data members, etc).  See style guide rules for this:

https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes

You can either just make this a class again, or you can move most of the methods into the callers and have this be a real struct.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 626 at r15](https://reviewable.io/reviews/grpc/grpc/24354#-MMNtVXrCZhXV-lljBxG:-MMNtVXrCZhXV-lljBxH:bia362b) ([raw file](https://github.com/grpc/grpc/blob/4246b6146f5ae1be07eefd28f055e64ba6aa1e15/src/core/ext/filters/client_channel/client_channel.cc#L626)):*
> ```cpp
>     // this call will be counted as an active fault. Otherwise, it returns
>     // GRPC_ERROR_NONE.
>     // If the input active_faults is nullptr, then skip the active fault quota
> ```

I don't think it's necessary to make this conditional based on whether the parameter is null.  Instead, you can check whether `delay_request_` is true.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3978 at r15](https://reviewable.io/reviews/grpc/grpc/24354#-MMNvLimAa6O48GvvJwR:-MMNvLimAa6O48GvvJwS:b68m8uk) ([raw file](https://github.com/grpc/grpc/blob/4246b6146f5ae1be07eefd28f055e64ba6aa1e15/src/core/ext/filters/client_channel/client_channel.cc#L3978)):*
> ```cpp
>   }
>   // Roll the dice
>   FaultInjectionData* fi_data = nullptr;
> ```

Suggest having the `FaultInjectionData` ctor take the relevant data members as parameters, and then writing this code like this:

```
const bool delay_request =
    fi_policy->delay != 0 && UnderFraction(fi_policy->delay_per_million);
const bool abort_request =
    fi_policy->abort_code != GRPC_STATUS_OK &&
    UnderFraction(fi_policy->abort_per_million);
if (delay_request || abort_request) {
  return arena->New<FaultInjectionData>(
      fi_policy, /*fi_policy_owned=*/copied_policy != nullptr,
      delay_request, abort_request);
}
if (copied_policy != nullptr) {
  copied_policy->~FaultInjectionPolicy();
}
return nullptr;
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 618 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1b19d8BY8vUHdKaGx:-MMNrW_PAP17AUVhLmrP:bjglt2c) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L618)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

This design seems against the idea that closures will be invoked exactly once to prevent memory leak? Before I came across this part, I wasn't aware this is a responsibility of client channel... This callback needs to be explicitly invoked in multiple code path, and new subchannel picking code paths. It might be a small trap for others.
</blockquote></details>

Actually, this is exactly *because* of the idea that closures will be invoked exactly once.  This callback is being given to the client channel code, and the client channel code is responsible for ensuring that it will invoke the callback exactly once.  If there are code-paths where the client channel code is not invoking this callback, that's a bug, because it's not fulfilling its responsibility.

If your argument here is that we should find a way to simplify the client channel code such that it's easier to verify that there are no code-paths that may accidentally fail to invoke the callback, I agree (and I will try to do something about that as part of supporting HTTP filters).  But putting a TODO here is not going to help that, because it's not the code here that needs to change.

Please remove this TODO.
___
*[src/core/ext/xds/xds_api.cc, line 1281 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLPDfKTAGqOtezPUDmC:-MMNqtlFEK2Jr4t5tYAj:bqnpr4n) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/src/core/ext/xds/xds_api.cc#L1281)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Oh. Clang-Tidy complained about this change, so I changed back to previous version.

```
/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/src/core/ext/xds/xds_api.cc:1289:26: error: std::move of the variable 'fault_config' of the trivially-copyable type 'XdsApi::HTTPFault' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
  *optional_http_fault = std::move(fault_config);
                         ^~~~~~~~~~            ~
Suppressed 3966 warnings (3924 in non-user code, 42 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
1 warning treated as error
```
</blockquote></details>

Interesting!  I didn't think that would happen for a struct, even if it only contained integers, but I guess it does.
___
*[src/core/ext/xds/xds_api.cc, line 1236 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1ZkUJD0lXHp-EhCcy:-MMNoHWE4He93Ow1U2Ud:b-druhct) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/xds/xds_api.cc#L1236)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

This `.c_str()` is converting the result of `absl::StrCat()` for `GRPC_ERROR_CREATE_FROM_COPIED_STRING`.
</blockquote></details>

Ah, you're right -- sorry, I misread that.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4657 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLT9MTI-ndADA9cKohN:-MMO2Yt6CXzviG6-YxsP:b-1b523q) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/test/cpp/end2end/xds_end2end_test.cc#L4657)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

It's an interesting probability issue I missed before. The error tolerance was 20%. I set the expected error rate to 10%, so the acceptance range is 8%-12%, which is 4% in total.

The abort injection is a random process that failing any RPC with `p` possibility. The statistic model for this type of random is a classic binomial distribution. The standard deviation for `p=0.1` binomial distribution is 0.09n (n is the number of RPCs), so the acceptance range 8%-12% map to -0.222 to 0.222 std., which roughly have 60% chance of acceptance. So, it was indeed quite flaky to hit the target constantly. (CC math expert @gnossen)

Since adding the fault tolerance seems sending the wrong message, I have increased the expected error rate to 80% (the probability of acceptance is ~1) and decreased the number of RPCs to 50.

On the other hand, we can lower the error tolerance, but with the increased flakiness, we ain't getting equivalent amount of insight. E.g., a failed run for a 99.99% stable test case is more informative than a failed run for a 99% stable test case.
</blockquote></details>

This is a really interesting analysis.  I may not be grokking all o [...]

2021-01-13 01:45 UTC, lidizheng reviewed
This PR is refactored to fit into the new dynamic filters framework. The major updates are:

1. Now `XdsResolver` returns a set of filters depends on what xDS config it read;
2. `FaultInjectionData` becomes `FaultInjectionFilter` in separate files;
3. Locking changed slightly that `active_faults` changed back to atomic, and there is a call-level mutex to serialize delay, resume and cancellation.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MQtI7mqAwAQ1WuCLySp:bsb3tnl)* status: 10 of 40 files reviewed, 14 unresolved discussions (waiting on @donnadionne, @gnossen, and @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 598 at r15](https://reviewable.io/reviews/grpc/grpc/24354#-MMNtdU_-RWTuge9LWOo:-MMRh-jdEjGZ-TTQM6FS:b-ouleoa) ([raw file](https://github.com/grpc/grpc/blob/4246b6146f5ae1be07eefd28f055e64ba6aa1e15/src/core/ext/filters/client_channel/client_channel.cc#L598)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You've changed this to be a struct instead of a class, but you're still using class style for it (e.g., using `_` suffixes for data members, having all access go through methods that impose invariants across data members, etc).  See style guide rules for this:

https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes

You can either just make this a class again, or you can move most of the methods into the callers and have this be a real struct.
</blockquote></details>

It's refactored into `FaultInjectionFilter`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 626 at r15](https://reviewable.io/reviews/grpc/grpc/24354#-MMNtVXrCZhXV-lljBxG:-MMRhUC71zzeA21LpXLf:b1siewe) ([raw file](https://github.com/grpc/grpc/blob/4246b6146f5ae1be07eefd28f055e64ba6aa1e15/src/core/ext/filters/client_channel/client_channel.cc#L626)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think it's necessary to make this conditional based on whether the parameter is null.  Instead, you can check whether `delay_request_` is true.
</blockquote></details>

Good idea! Changed.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 3978 at r15](https://reviewable.io/reviews/grpc/grpc/24354#-MMNvLimAa6O48GvvJwR:-MMRmbh-A34SHggtq8gC:b-aaw1gw) ([raw file](https://github.com/grpc/grpc/blob/4246b6146f5ae1be07eefd28f055e64ba6aa1e15/src/core/ext/filters/client_channel/client_channel.cc#L3978)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest having the `FaultInjectionData` ctor take the relevant data members as parameters, and then writing this code like this:

```
const bool delay_request =
    fi_policy->delay != 0 && UnderFraction(fi_policy->delay_per_million);
const bool abort_request =
    fi_policy->abort_code != GRPC_STATUS_OK &&
    UnderFraction(fi_policy->abort_per_million);
if (delay_request || abort_request) {
  return arena->New<FaultInjectionData>(
      fi_policy, /*fi_policy_owned=*/copied_policy != nullptr,
      delay_request, abort_request);
}
if (copied_policy != nullptr) {
  copied_policy->~FaultInjectionPolicy();
}
return nullptr;
```
</blockquote></details>

Thanks, this is cleaner. I changed the ctor, but swapped the condition, so the sunny day code path will end at the last line.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 618 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MM1b19d8BY8vUHdKaGx:-MMRhZfq-A84Y_yZnF69:b-yd3593) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L618)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Actually, this is exactly *because* of the idea that closures will be invoked exactly once.  This callback is being given to the client channel code, and the client channel code is responsible for ensuring that it will invoke the callback exactly once.  If there are code-paths where the client channel code is not invoking this callback, that's a bug, because it's not fulfilling its responsibility.

If your argument here is that we should find a way to simplify the client channel code such that it's easier to verify that there are no code-paths that may accidentally fail to invoke the callback, I agree (and I will try to do something about that as part of supporting HTTP filters).  But putting a TODO here is not going to help that, because it's not the code here that needs to change.

Please remove this TODO.
</blockquote></details>

Removed. As it is now part of DynamicTerminationFilter.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4657 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLT9MTI-ndADA9cKohN:-MMSb8cR3zHmn_Awmt6P:b-2re9s) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/test/cpp/end2end/xds_end2end_test.cc#L4657)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is a really interesting analysis.  I may not be grokking all of the math here (statistics are not my strong suit), but is there a way we can lower the error tolerance without causing undo flakiness?  Does increasing the number of RPCs not actually do that at all?  My concern is that if the error tolerance is too high, then the code could potentially be off by up to 20% in a stable way, and the test would never detect the problem.

Can you run this 1000x in RBE with builds for all of opt, dbg, asan, tsan, msan, and ubsan to verify that it won't be flaky?

CC @donnadionne, since this may be relevant to other conversaions we've had about error tolerance.
</blockquote></details>

Previously, we discussed the definition of error tolerance. In the latest change, the error tolerance no longer means how far it deviates from the target but what is the absolute distance from the target, e.g., an abort rate of 30% acceptance range was previously (24%-36%), new acceptance range was (10%-50%). It worked before because we conducts 3000 RPCs per test case per setup, and in new one it only took 100 runs to reach 4 "9"s  (see [cumulative distribution function](https://en.wikipedia.org/wiki/Binomial_distribution) or [chart](https://screenshot.googleplex.com/5wK7GdSdMXGTv7W)).

For delay injections, the large number of RPC runs slow the entire test down, which is the incentive for me to reduce the runs. BTW, LongRunningRpc uses C++ sync API, which uses pluck. So, we can only have limited number of concurrent RPCs before there are too many plucker.

WDYT? Should we:

1. Loosen the error tolerance definition;
2. Or implement C++ Async version of LongRunningRpc.

---

Along the way of deflake, I found several factors for the flakiness:

* Our internal clock is monotonic with rounded down millisecond precision, not exactly matching the "system time" in milliseconds-level;
* `--confg=tsan` demands larger timeout, if there are parallel RPC.

The 1000x RBE builds will be conducted when other changes are good.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1904 at r13](https://reviewable.io/reviews/grpc/grpc/24354#-MMITAkG7o-PqGI7a80q:-MMRbF0m25glXax7-3Lx:beh0mib) ([raw file](https://github.com/grpc/grpc/blob/1d3ff0ae8cef10f51c228d1373fef871958a5f72/test/cpp/end2end/xds_end2end_test.cc#L1904)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Was this comment intentional?  I don't see any question here, just quoted code.
</blockquote></details>

Sorry, this was a misclick.

(Reviewable is pretty good, but it does have this one feature confuses me. If I have copied text in my clipboard, it will automatically add it to the comment as quote. I haven't found a valid usage for it.)
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1873 at r15](https://reviewable.io/reviews/grpc/grpc/24354#-MMNyJxlCL1EsjwiuzLq:-MMRjdPQ-B0Q3ezoty [...]

2021-01-14 23:39 UTC, markdroth requested changes
The new filter looks really nice!

I haven't yet had a chance to review the latest changes in the tests, but I didn't want to delay my feedback on the rest of this, so I'm sending without that.  I'll review the tests in my next review pass.

Please let me know if you have any questions.  Thanks!

> Reviewed 30 of 31 files at r18.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MR2FmAs1KqmuRXdQo-w:b5tzwku)* status: 39 of 40 files reviewed, 25 unresolved discussions (waiting on @donnadionne, @gnossen, @lidizheng, and @markdroth)

___
*[src/core/ext/filters/client_channel/fault_injection_filter.h, line 24 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1thF5B5h6EYvWIL_Q:-MR1thF5B5h6EYvWIL_R:bmktdz3) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.h#L24)):*
> ```objc
> #include "src/core/lib/channel/channel_stack.h"
> 
> extern grpc_core::TraceFlag grpc_fault_injection_filter_trace;
> ```

This shouldn't be needed outside of the .cc file, so no reason to declare it here.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.h, line 29 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1ttYwDSWTWRMCo_Pm:-MR1ttYwDSWTWRMCo_Pn:b-5y4ehs) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.h#L29)):*
> ```objc
> // of the ordinary channel stack. The fault injection filter fetches fault
> // injection policy from the method config of service config returned by the
> // xDS config selector, and enforces the fault injection policy.
> ```

We shouldn't mention xDS here, since there's really nothing xDS-specific about this code.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.h, line 30 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1tl2p0POmPORowN3Z:-MR1tl2p0POmPORowN3_:biwrit2) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.h#L30)):*
> ```objc
> // injection policy from the method config of service config returned by the
> // xDS config selector, and enforces the fault injection policy.
> extern const grpc_channel_filter grpc_fault_injection_filter;
> ```

This can be in the `grpc_core` namespace and can be called something like `FaultInjectionFilter`.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 85 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1ukD0-zh4ws20QVOy:-MR1ukD0-zh4ws20QVOz:byozvig) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L85)):*
> ```cpp
>     ~ChannelData() = default;
> 
>     Atomic<uint32_t> active_faults_{0};
> ```

Storing this here means that every time the filter stack gets recreated (which happens every time the channel gets an update from the LDS resolver), we'll basically reset this counter to 0.  I suspect that's not what we want, although you can check how Envoy handles this.

An alternative might be to make this a true global variable somehow.  Not ideal, but might work for now.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 102 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1wb0t3ad7l5HEk067:-MR1wb0t3ad7l5HEk068:b92knbo) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L102)):*
> ```cpp
>     // Returns true if this RPC needs to be delayed. If so, this call will be
>     // counted as an active fault.
>     bool MaybeDelay();
> ```

All of the remaining methods here can be private.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 191 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1w49p7-brQCUaJzNO:-MR1w49p7-brQCUaJzNP:b1lwcu) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L191)):*
> ```cpp
>       static_cast<FaultInjectionFilter::ChannelData*>(elem->channel_data);
>   auto* calld = new (elem->call_data) FaultInjectionFilter::CallData(args);
>   calld->active_faults_ = chand->active_faults();
> ```

This should be moved into the `CallData` ctor.  You can pass in `chand` as an argument to the ctor.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 199 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1wDOPE76PWF1KvA1k:-MR1wDOPE76PWF1KvA1l:byt1hak) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L199)):*
> ```cpp
>     grpc_closure* then_schedule_closure) {
>   auto* calld = static_cast<FaultInjectionFilter::CallData*>(elem->call_data);
>   if (calld->fi_policy_owned_) calld->fi_policy_->~FaultInjectionPolicy();
> ```

This should be done in the `CallData` dtor.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 201 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1wJvK-bAkyrlNBFGy:-MR1wJvK-bAkyrlNBFGz:bgw8wso) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L201)):*
> ```cpp
>   if (calld->fi_policy_owned_) calld->fi_policy_->~FaultInjectionPolicy();
>   calld->~CallData();
>   ExecCtx::Run(DEBUG_LOCATION, then_schedule_closure, GRPC_ERROR_NONE);
> ```

This should be removed.  Only the bottom filter in the stack needs to worry about this closure.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 204 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1xeIc1a2BLgaw2QxZ:-MR1xeIc1a2BLgaw2Qx_:b-nd5276) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L204)):*
> ```cpp
> }
> 
> void FaultInjectionFilter::CallData::ConsumeFaultInjectionPolicy(
> ```

Suggest calling this `DecideWhetherToInjectFaults()`.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 204 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR22v-A5xiKsHTOX7Ar:-MR22v-A5xiKsHTOX7As:b-x7kyu6) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L204)):*
> ```cpp
> }
> 
> void FaultInjectionFilter::CallData::ConsumeFaultInjectionPolicy(
> ```

Methods should be defined in the same order in which they are declared in the class declaration.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 270 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1yevwA1z7glP0ejr7:-MR1yevwA1z7glP0ejr8:bts6d64) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L270)):*
> ```cpp
>     fi_policy_owned_ = copied_policy != nullptr;
>     if (GRPC_TRACE_FLAG_ENABLED(grpc_fault_injection_filter_trace)) {
>       gpr_log(GPR_INFO, "Fault injection triggered delay=%d abort=%d",
> ```

Please log the values of `chand` and `calld` as well.  Without those, the log isn't really useful, because it's hard to tell which channel or call it's associated with.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 276 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1xzn02jUP3ebUhGqD:-MR1xzn02jUP3ebUhGqE:bapop3f) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L276)):*
> ```cpp
> }
> 
> bool FaultInjectionFilter::CallData::HaveActiveFaultsQuota(bool add_one) {
> ```

Please rename the parameter to `increment`.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 311 at r18] [...]

2021-01-15 21:49 UTC, lidizheng reviewed
Thanks for the thorough review!

Can we discuss the strategy to implement the logic for HTTP filters (see comment below)? There might be some uncertainty for the HTTP filters registry design. We can limit the complexity by checking this PR in first.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MR7-k4G9On4VEGWYKQn:brhnno1)* status: 39 of 40 files reviewed, 25 unresolved discussions (waiting on @donnadionne, @gnossen, @lidizheng, and @markdroth)

___
*[src/core/ext/filters/client_channel/fault_injection_filter.h, line 24 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1thF5B5h6EYvWIL_Q:-MR6Tsgo21jV-UDIXxv-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.h#L24)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This shouldn't be needed outside of the .cc file, so no reason to declare it here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.h, line 29 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1ttYwDSWTWRMCo_Pm:-MR6TtJt9dFiyTiHmAI4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.h#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We shouldn't mention xDS here, since there's really nothing xDS-specific about this code.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.h, line 30 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1tl2p0POmPORowN3Z:-MR6Ttq254pEV7AtGsWH:b-1g1p6h) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be in the `grpc_core` namespace and can be called something like `FaultInjectionFilter`.
</blockquote></details>

Moved into `grpc_core` namespace, what's the rules here? Other channel filters like idle, message size ain't using `grpc_core`.

Can we keep the name `grpc_fault_injection_filter`? The name `FaultInjectionFilter` feels more C++, and it feels more natural to use it to name the implementation class instead of the vtable.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 85 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1ukD0-zh4ws20QVOy:-MR6UWS75PUVJues6Ew3:bg50wv8) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Storing this here means that every time the filter stack gets recreated (which happens every time the channel gets an update from the LDS resolver), we'll basically reset this counter to 0.  I suspect that's not what we want, although you can check how Envoy handles this.

An alternative might be to make this a true global variable somehow.  Not ideal, but might work for now.
</blockquote></details>

Good catch. I misunderstood the life cycle of the channel data. Promoted to global variable.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 102 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1wb0t3ad7l5HEk067:-MR6W-km0VyYJ5hO6fZB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L102)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All of the remaining methods here can be private.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 191 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1w49p7-brQCUaJzNO:-MR6W94x8IdOB6LpPBKw:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L191)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be moved into the `CallData` ctor.  You can pass in `chand` as an argument to the ctor.
</blockquote></details>

Removed.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 199 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1wDOPE76PWF1KvA1k:-MR6X-PF5UgRuPXnlv_s:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L199)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be done in the `CallData` dtor.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 201 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1wJvK-bAkyrlNBFGy:-MR6X32I3jMubT_0nS3o:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L201)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be removed.  Only the bottom filter in the stack needs to worry about this closure.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 204 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1xeIc1a2BLgaw2QxZ:-MR6X5Qs4KKF4gB-cPun:b-dn1265) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L204)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `DecideWhetherToInjectFaults()`.
</blockquote></details>

Name updated.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 204 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR22v-A5xiKsHTOX7Ar:-MR6XrhMAdTCkMVuohas:bbkuwu3) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L204)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Methods should be defined in the same order in which they are declared in the class declaration.
</blockquote></details>

Reordered both the declaration and the implementation.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 270 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1yevwA1z7glP0ejr7:-MR6ZZMlAu--r29y7W2g:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L270)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please log the values of `chand` and `calld` as well.  Without those, the log isn't really useful, because it's hard to tell which channel or call it's associated with.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 276 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1xzn02jUP3ebUhGqD:-MR6ZbJ18PvSGsL6hYDB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.cc#L276)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please rename the parameter to `increment`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 311 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR2-9IQ6ZKdbLDwisxC:-MR6ZbrC0rJLsrMg6SZ7:b-896fix) ([raw file](https [...]

2021-01-19 22:35 UTC, markdroth requested changes
I don't think we can merge the xDS part of the code as-is.  If you want to split the xDS part into a separate PR, I'm okay with that, but I think it might actually wind up being more work that way.  I'd be happy to chat offline about this if you'd like.

Please let me know if you have any questions.  Thanks!

> Reviewed 22 of 22 files at r19.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MRRm3PI0FLQUlZI06gc:b1lflxt)* status: all files reviewed, 14 unresolved discussions (waiting on @donnadionne, @gnossen, and @lidizheng)

___
*[src/core/ext/filters/client_channel/fault_injection_filter.h, line 30 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1tl2p0POmPORowN3Z:-MRRLtNS7bx8EDqnl4-J:b-g4f9o7) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.h#L30)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Moved into `grpc_core` namespace, what's the rules here? Other channel filters like idle, message size ain't using `grpc_core`.

Can we keep the name `grpc_fault_injection_filter`? The name `FaultInjectionFilter` feels more C++, and it feels more natural to use it to name the implementation class instead of the vtable.
</blockquote></details>

Then let's call it `FaultInjectionFilterVtable`.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 44 at r19](https://reviewable.io/reviews/grpc/grpc/24354#-MRRMJt50rPRnfzRUBwv:-MRRMJt50rPRnfzRUBww:b-kkd0em) ([raw file](https://github.com/grpc/grpc/blob/8a2d688846cb96f95a2bb34f106d8dd2af6b7ed4/src/core/ext/filters/client_channel/fault_injection_filter.cc#L44)):*
> ```cpp
> namespace {
> 
> Atomic<uint32_t> g_active_faults{0};
> ```

Note that the style guide prohibits global variables that are not trivially destructible.  Please add a static assert here that `std::is_trivially_desctructible<>` is true for this.

If that assertion fails, then an alternative would be to make this a pointer and have a gRPC plugin that dynamically allocates the atomic at init time and sets this pointer to point to it.  You can find other examples in the code-base where we do things like this.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 379 at r19](https://reviewable.io/reviews/grpc/grpc/24354#-MRRNlrI3mrMQMNLBp2l:-MRRNlrI3mrMQMNLBp2m:b-7u0nlz) ([raw file](https://github.com/grpc/grpc/blob/8a2d688846cb96f95a2bb34f106d8dd2af6b7ed4/src/core/ext/filters/client_channel/fault_injection_filter.cc#L379)):*
> ```cpp
>   }
>   if (GRPC_TRACE_FLAG_ENABLED(grpc_fault_injection_filter_trace)) {
>     gpr_log(GPR_INFO, "chand %p calld %p: Resuming delayed stream op batch %p",
> ```

Please use `chand=%p calld=%p`, for consistency with other log messages.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 393 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1rpMhDJd4mPMc_6uT:-MRRNzVR0Yi8yQrZmxz4:b9do9p2) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L393)):*
> But in order to make these work, we will need a refactor from XdsApi to service config parsers.

I'm not sure what you mean by that.  I don't think any refactoring is needed here.

I think it's important to understand that there are two different mechanisms involved here.  The service config parsing is completely independent of xDS.

The service config parsing mechanism is an existing mechanism to allow C-core filters to get configuration from the service config.  The FI filter is a C-core filter that will use that existing mechanism to get its configuration.  In principle, none of this has anything to do with xDS.

Separately from that, the xDS code needs a mechanism to register an xDS HTTP filter, which is what I'm proposing here.  An xDS HTTP filter definition will include (a) the C-core filter used to provide the functionality required by the xDS HTTP filter and (b) code to convert the xDS HTTP filter config to the corresponding service config format used by that C-core filter.  This is essentially an adapter that converts from xDS configs to the underlying C-core functionality.

These two layers are in principle completely independent.  The xDS layer sits on top of the service config parsing layer, but it does not require any changes to the service config parsing layer in order to work; it just makes use of that layer as-is.  (As an implementation detail, we might choose to have the `XdsApi` code return the config for the xDS HTTP filter in a form that just happens to be the same as the form used by the underlying C-core filter for service config parsing, since that avoids the need for any sort of conversion.  But even if we do that, it's just an implementation detail -- it doesn't actually change the overall structure of the code in any way.)

> I think the HTTP filter registry is a good abstraction, and it needs to achieve the same features Envoy have:
> 1. Per-Listener ordered list for filters (for execution order);
> 2. Per-Listener default filter config;
> 3. Per-Route, per-VH, per-Cluster level filter config override.

There are no per-cluster overrides for HTTP filters in xDS.  Clusters are on the upstream side of xDS, and HTTP filters are on the downstream side.

We don't currently have any use-cases for per-VH overrides.  We may need that at some point, but I don't think we need to worry about it right now; that's something we can add later.

I think my proposal above will support the top-level config at the HCM level (what you called "per-listener") and per-route overrides.

> The HTTP filter registry work itself might be complex enough to worth an individual PR. Can we set the goal of this PR to the first dynamic filter implementation (fault injection)?

If you'd prefer to split this into multiple PRs, then I think the right way to do that is to have this PR be only the non-xDS-specific part (i.e., just the FI filter and the service config parsing, none of the xDS-specific code), and then put together a separate PR that adds the xDS HTTP filter registry and registers the FI xDS HTTP filter.  However, that approach would probably be a bit more work, since we'd need to add a non-xDS test for the FI functionality in this PR.

I'd prefer not to merge a PR that includes supporting any xDS HTTP filter without having the full xDS HTTP filter registry semantics, because that may cause semantic changes in how we handle xDS data later.  For example, see my comment elsewhere about needing to handle the case where a given filter is in the list twice.

Also, keep in mind that we won't be able to actually de-experimentalize and release support for xDS fault injection until we do both parts of this.
___
*[src/core/ext/xds/xds_api.cc, line 1749 at r19](https://reviewable.io/reviews/grpc/grpc/24354#-MRRYkhSD4ZBZXDETLB6:-MRRYkhSD4ZBZXDETLB7:b-xbvdl2) ([raw file](https://github.com/grpc/grpc/blob/8a2d688846cb96f95a2bb34f106d8dd2af6b7ed4/src/core/ext/xds/xds_api.cc#L1749)):*
> ```cpp
>         envoy_extensions_filters_network_http_connection_manager_v3_HttpFilter_name(
>             filters[i]));
>     if (filter_name != "envoy.fault") continue;
> ```

We need to reject any filter that we don't support instead of just ignoring it.  Ideally, this should be determined by checking the xDS HTTP filter registry for each filter name.

Also, even for a filter we do support, that filter might be listed twice in the filter list, in which case we need to invoke that filter twice.  And each invocation might have a different config.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4657 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLT9MTI-ndADA9cKohN:-MRRdmId34lQhr-vzXS2:b-vmm2ft) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/test/cpp/end2end/xds_end2end_test.cc#L4657)):*
Like I said earlier, statistics is not [...]

2021-02-23 16:29 UTC, markdroth requested changes
This is looking much cleaner!

It looks like you still need to address my comments from my previous review pass.  In particular, I think we need to move the FI filter service config parsing into its own service config parser instead of making it part of the client channel filter's service config parser.

Please let me know if you have any questions.  Thanks!

> Reviewed 30 of 30 files at r20.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MUEhyh-B_LLJY3zPyFg:b-3fnwyv)* status: all files reviewed, 22 unresolved discussions (waiting on @donnadionne, @gnossen, and @lidizheng)

___
*[BUILD, line 1104 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUBIlIW1VwgPBdS9V0h:-MUBIlIW1VwgPBdS9V0i:b6yw7vd) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/BUILD#L1104)):*
> ```Starlark
>         "src/core/ext/filters/client_channel/config_selector.cc",
>         "src/core/ext/filters/client_channel/dynamic_filters.cc",
>         "src/core/ext/filters/client_channel/fault_injection_filter.cc",
> ```

Please move the fault injection filter to its own BUILD target, and put the files in a new directory called src/core/ext/filters/fault_injection.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.h, line 30 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1tl2p0POmPORowN3Z:-MUBPMAU8usYk9Kwy_Yp:b-qta88k) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/fault_injection_filter.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Then let's call it `FaultInjectionFilterVtable`.
</blockquote></details>

Still need to address this.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 44 at r19](https://reviewable.io/reviews/grpc/grpc/24354#-MRRMJt50rPRnfzRUBwv:-MUBPP5D4I2nskhmD7Se:b-qta88k) ([raw file](https://github.com/grpc/grpc/blob/8a2d688846cb96f95a2bb34f106d8dd2af6b7ed4/src/core/ext/filters/client_channel/fault_injection_filter.cc#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Note that the style guide prohibits global variables that are not trivially destructible.  Please add a static assert here that `std::is_trivially_desctructible<>` is true for this.

If that assertion fails, then an alternative would be to make this a pointer and have a gRPC plugin that dynamically allocates the atomic at init time and sets this pointer to point to it.  You can find other examples in the code-base where we do things like this.
</blockquote></details>

Still need to address this.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 379 at r19](https://reviewable.io/reviews/grpc/grpc/24354#-MRRNlrI3mrMQMNLBp2l:-MUBPQzU0QWXRWbImQqn:b-qta88k) ([raw file](https://github.com/grpc/grpc/blob/8a2d688846cb96f95a2bb34f106d8dd2af6b7ed4/src/core/ext/filters/client_channel/fault_injection_filter.cc#L379)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `chand=%p calld=%p`, for consistency with other log messages.
</blockquote></details>

Still need to address this.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 167 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUBKgvv4LE1wua2HgAj:-MUBKgvv4LE1wua2HgAk:b-sf3aw0) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/fault_injection_filter.cc#L167)):*
> ```cpp
>   GPR_ASSERT(elem->filter == &grpc_fault_injection_filter);
>   auto* chand = new (elem->channel_data) FaultInjectionFilter::ChannelData();
>   chand->index_ =
> ```

Please initialize this in the ctor instead of here.  You can pass in `elem` and `args` to the ctor.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 224 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUBKIA14N7AieDBsetm:-MUBKIA2EnosgIIP_av4:b-olt68z) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/fault_injection_filter.cc#L224)):*
> ```cpp
>       static_cast<FaultInjectionFilter::ChannelData*>(elem->channel_data);
>   auto* calld = new (elem->call_data) FaultInjectionFilter::CallData(args);
>   // Fetch the fault injection policy from the service config, based on the
> ```

Please move this code back into the `CallData` ctor, which is where we should be setting its members.  You can pass in `chand` as a parameter to the ctor.
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 280 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUBKp1aBvwuZFZkpOJu:-MUBKp1aBvwuZFZkpOJv:b-fq0n02) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/fault_injection_filter.cc#L280)):*
> ```cpp
>   if (fi_policy_owned_) {
>     fi_policy_->~FaultInjectionPolicy();
>     fi_policy_owned_ = false;
> ```

There's no need to reset this to false, since nothing will ever look at it after this.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 37 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1tHTS5UQPS3BPspz-:-MUBPSmM5NW3vBuip6W3:b-qta88k) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/resolver_result_parsing.h#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Now that we've moved the fault injection code to its own filter, I think it should register its own service config parser that looks only at the fields it's interested in rather than doing its parsing in the client_channel parser code.  That way, the FI code is cleanly separated from the rest of the client_channel code.
</blockquote></details>

Still need to address this.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 99 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUEhkUHC2koxvVAL-Cl:-MUEhkUHC2koxvVAL-Cm:bd73se3) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/resolver_result_parsing.h#L99)):*
> ```objc
> 
>   struct FaultInjectionPolicy {
>     uint32_t abort_per_million = 0;
> ```

If we're now passing in the denominator anyway, we might as well pass in the numerator instead of passing in the fraction.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 106 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUEhtsn-_OJXJCXNKWK:-MUEhtsn-_OJXJCXNKWL:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/resolver_result_parsing.h#L106)):*
> ```objc
>     uint32_t abort_percentage_denominator;
> 
>     uint32_t delay_per_million = 0;
> ```

Same here.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 119 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUBMBdX21BsFk49Q6b6:-MUBMBdX21BsFk49Q6b7:ba0lpfg) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/resolver_result_parsing.h#L119)):*
> ```objc
>       grpc_millis timeout, const absl::optional<bool>& wait_for_ready,
>       std::unique_ptr<RetryPolicy> retry_policy,
>       std::unique_ptr<std::vector<FaultInjectionPolicy> >
> ```

Now that this is a vector, it doesn't need to be wrapped in a `unique_ptr<>`, because we can tell if it's missing by the vector being empty.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 119 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUBMVWB2l6kzh570S8v:-MUBMVWB2l6kzh570S8w:b-6nafln) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/resolver_result_parsing.h#L119)):*
> ```objc
>  [...]

2021-02-23 20:02 UTC, markdroth requested changes
> Reviewed 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354)* status: all files reviewed, 24 unresolved discussions (waiting on @donnadionne, @gnossen, and @lidizheng)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 2036 at r21](https://reviewable.io/reviews/grpc/grpc/24354#-MUFTrtI6lohhTDnIAAk:-MUFTrtI6lohhTDnIAAl:bw0ucnr) ([raw file](https://github.com/grpc/grpc/blob/2a75ecf1eeee9c8b4352b63229861e5e2ae50b43/test/cpp/end2end/xds_end2end_test.cc#L2036)):*
> ```cpp
>   // nullptr, then assign an empty filter config. This filter config is required
>   // to enable the fault injection features.
>   static Listener BuildListenerWithFaultInjection(
> ```

These two helper methods can be moved down to the `FaultInjectionTest` class.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8830 at r21](https://reviewable.io/reviews/grpc/grpc/24354#-MUFTbDi40915IGoAgpK:-MUFTbDi40915IGoAgpL:b4mo3bi) ([raw file](https://github.com/grpc/grpc/blob/2a75ecf1eeee9c8b4352b63229861e5e2ae50b43/test/cpp/end2end/xds_end2end_test.cc#L8830)):*
> ```cpp
> 
> // Without the listener config, the fault injection won't be enabled.
> TEST_P(FaultInjectionTest, XdsFaultInjectionWithoutListenerFilter) {
> ```

This test is not setting the env var, so it's not testing what you think it is. :)


<!-- Sent from Reviewable.io -->

2021-02-24 02:28 UTC, lidizheng reviewed
Thanks for the detailed review. I have updated the file structure, split the service config parse, and rewrote the JSON parsing logic again.

The tests could be a bit tricky, the limited pluck issue wasn't obvious in other test cases because they don't require true parallelism. On the other hand, for delay injection, if we want to test 1000 RPCs in parallel, with current logic, we need 1000 threads to poll from one completion queue. This is impossible for pluck based SYNC API, but we could create a completion queue for each RPC thread. I still need to experiment about it.

> Reviewed 3 of 13 files at r4, 2 of 16 files at r7, 3 of 31 files at r18, 21 of 30 files at r20.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MUGpzYC4os0jFYQWD8Z:btsu2ci)* status: 14 of 40 files reviewed, 23 unresolved discussions (waiting on @donnadionne, @gnossen, @lidizheng, and @markdroth)

___
*[BUILD, line 1104 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUBIlIW1VwgPBdS9V0h:-MUFwz9Q1NbCRE2zjl4h:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/BUILD#L1104)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move the fault injection filter to its own BUILD target, and put the files in a new directory called src/core/ext/filters/fault_injection.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 37 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1tHTS5UQPS3BPspz-:-MUGQbzb999agjxwvsja:b-bxac5r) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/resolver_result_parsing.h#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Still need to address this.
</blockquote></details>

Moved to `src/core/ext/filters/fault_injection/service_config_parser`.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 99 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUEhkUHC2koxvVAL-Cl:-MUGpbXw-XizNVrqJsNu:b-l04vwt) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/resolver_result_parsing.h#L99)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're now passing in the denominator anyway, we might as well pass in the numerator instead of passing in the fraction.
</blockquote></details>

Done. Also rewrote the JSON parsing logic with `json_util.h` functions.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 106 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUEhtsn-_OJXJCXNKWK:-MUGph5S6k-U_R_h-eHn:b-l04vwt) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/resolver_result_parsing.h#L106)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done. Also rewrote the JSON parsing logic with `json_util.h` functions.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 119 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUBMBdX21BsFk49Q6b6:-MUG1SyT9DGaaQ8UnqcW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/resolver_result_parsing.h#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Now that this is a vector, it doesn't need to be wrapped in a `unique_ptr<>`, because we can tell if it's missing by the vector being empty.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 119 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUBMVWB2l6kzh570S8v:-MUG-k-m-PfCOeipp6aD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/resolver_result_parsing.h#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the extra space between the two `>` characters.  That was needed in older versions of C++ but is no longer necessary.

Same thing throughout.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.cc, line 298 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MUBN4Ys00bTIbokW_S-:-MUFfDMtCImZkG18T_mP:bpuqqgy) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/resolver_result_parsing.cc#L298)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why did this TODO go away?
</blockquote></details>

In the latest commit, I updated the Json parsing logic to use `json_utils.h` instead.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 393 at r18](https://reviewable.io/reviews/grpc/grpc/24354#-MR1rpMhDJd4mPMc_6uT:-MUGQq8P8lzRjWQ_Wk9k:b4b8ucl) ([raw file](https://github.com/grpc/grpc/blob/a6799284e77a6492dd84d8de45cbfe7df358d69b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L393)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

> But in order to make these work, we will need a refactor from XdsApi to service config parsers.

I'm not sure what you mean by that.  I don't think any refactoring is needed here.

I think it's important to understand that there are two different mechanisms involved here.  The service config parsing is completely independent of xDS.

The service config parsing mechanism is an existing mechanism to allow C-core filters to get configuration from the service config.  The FI filter is a C-core filter that will use that existing mechanism to get its configuration.  In principle, none of this has anything to do with xDS.

Separately from that, the xDS code needs a mechanism to register an xDS HTTP filter, which is what I'm proposing here.  An xDS HTTP filter definition will include (a) the C-core filter used to provide the functionality required by the xDS HTTP filter and (b) code to convert the xDS HTTP filter config to the corresponding service config format used by that C-core filter.  This is essentially an adapter that converts from xDS configs to the underlying C-core functionality.

These two layers are in principle completely independent.  The xDS layer sits on top of the service config parsing layer, but it does not require any changes to the service config parsing layer in order to work; it just makes use of that layer as-is.  (As an implementation detail, we might choose to have the `XdsApi` code return the config for the xDS HTTP filter in a form that just happens to be the same as the form used by the underlying C-core filter for service config parsing, since that avoids the need for any sort of conversion.  But even if we do that, it's just an implementation detail -- it doesn't actually change the overall structure of the code in any way.)

> I think the HTTP filter registry is a good abstraction, and it needs to achieve the same features Envoy have:
> 1. Per-Listener ordered list for filters (for execution order);
> 2. Per-Listener default filter config;
> 3. Per-Route, per-VH, per-Cluster level filter config override.

There are no per-cluster overrides for HTTP filters in xDS.  Clusters are on the upstream side of xDS, and HTTP filters are on the downstream side.

We don't currently have any use-cases for per-VH overrides.  We may need that at some point, but I don't think we need to worry about it right now; that's something we can add later.

I think my proposal above will support the top-level config at the HCM level (what you called "per-listener") and per-route overrides.

> The HTTP filter registry work itself might be complex enough to worth an ind [...]

2021-02-25 15:14 UTC, markdroth requested changes
This is looking really good!

Other than the outstanding comments in the tests, my main comment here is the one about supporting streaming cases.

Also, FYI, the xDS HTTP filter PR is being reverted temporarily due to some test flakiness it introduced.  I'll work on fixing that and getting it rolled forward again, but until then you should probably avoid merging master.

Please let me know if you have any questions.  Thanks!

> Reviewed 22 of 28 files at r22, 6 of 6 files at r23.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MUOk4iw2V3KntdloLgO:b-6g2uxv)* status: all files reviewed, 20 unresolved discussions (waiting on @donnadionne, @gnossen, and @lidizheng)

___
*[BUILD, line 1277 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKWlVS-KIhKeEJ5JsT:-MUKWlVS-KIhKeEJ5JsU:bts2chv) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/BUILD#L1277)):*
> ```Starlark
>     deps = [
>         "grpc_base",
>         "grpc_fault_injection_filter",
> ```

This dependency does not belong here, because it has nothing to do with this target.  It should actually be a dependency of the `grpc_common` target instead.
___
*[src/core/ext/filters/fault_injection/service_config_parser.h, line 29 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKaDao-9hh1miPWxrf:-MUKaDao-9hh1miPWxrg:b-hq6q8i) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.h#L29)):*
> ```objc
> namespace grpc_core {
> 
> struct FaultInjectionPolicy {
> ```

Please move this inside of `FaultInjectionMethodParsedConfig`.
___
*[src/core/ext/filters/fault_injection/service_config_parser.h, line 52 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKaIt53vfsr-FQ5yRQ:-MUKaIt53vfsr-FQ5yRR:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.h#L52)):*
> ```objc
>   explicit FaultInjectionMethodParsedConfig(
>       std::vector<FaultInjectionPolicy> fault_injection_policies)
>       : fault_injection_policies_(fault_injection_policies) {}
> ```

`std::move()`
___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 38 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKhRXY6lNjTdDtzn4x:-MUKhRXY6lNjTdDtzn4y:bt1fv3) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.cc#L38)):*
> ```cpp
> size_t g_fault_injection_parser_index;
> 
> void ParseFaultInjectionPolicy(const Json::Array* policies_json_array,
> ```

The `policies_json_array` argument should be a reference, not a pointer.
___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 39 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKhdaR9zyP1JjDwtCl:-MUKhdaR9zyP1JjDwtCm:b6zoyy1) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.cc#L39)):*
> ```cpp
> 
> void ParseFaultInjectionPolicy(const Json::Array* policies_json_array,
>                                std::vector<FaultInjectionPolicy>* policies,
> ```

This should be the function's return value instead of being populated via a parameter.
___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 41 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKhpN2BsajnbNEJr2K:-MUKhpN2BsajnbNEJr2L:bmi1n57) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.cc#L41)):*
> ```cpp
>                                std::vector<FaultInjectionPolicy>* policies,
>                                std::vector<grpc_error*>* error_list) {
>   for (auto json : *policies_json_array) {
> ```

This should be a reference to avoid an unnecessary copy.
___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 41 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULTtDc8L6pOI72AjyO:-MULTtDd-Mck7pO4lkVh:blewaqj) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.cc#L41)):*
> ```cpp
>                                std::vector<FaultInjectionPolicy>* policies,
>                                std::vector<grpc_error*>* error_list) {
>   for (auto json : *policies_json_array) {
> ```

The entries added to `error_list` in each iteration of this array should indicate which index the problem is in.  Otherwise, it's basically impossible for users to know what a given error message is referring to.

I think the best way to do that is to have a separate error vector for each iteration through the array.  Then, at the end of a given iteration, use the equivalent of `GRPC_ERROR_CREATE_FROM_VECTOR()` to construct a new error whose description indicates the index in the array, and then add that error to the top-level error vector.  (Note that you won't be able to use `GRPC_ERROR_CREATE_FROM_VECTOR()` directly, since the description won't be a static string; there are examples of how to do this in the xds bootstrap parser code.)
___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 43 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKhmS5EAoRos9Rqht_:-MUKhmS5EAoRos9Rqhta:bmi1n57) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.cc#L43)):*
> ```cpp
>   for (auto json : *policies_json_array) {
>     FaultInjectionPolicy fault_injection_policy;
>     const Json::Object json_object = json.object_value();
> ```

This should be a reference to avoid an unnecessary copy.
___
*[src/core/ext/xds/xds_http_fault_filter.h, line 38 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULU__FAG_qmL774AlJ:-MULU__G3z1Lb_U8NaTx:b-vz7rl3) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/xds/xds_http_fault_filter.h#L38)):*
> ```objc
> 
>   // Overrides the GenerateFilterConfig method
>   absl::StatusOr<XdsHttpFilterImpl::FilterConfig> GenerateFilterConfig(
> ```

I think you don't need to say `XdsHttpFilterImpl::` anywhere in this file, since this class inherits from that one.
___
*[src/core/ext/xds/xds_http_fault_filter.cc, line 188 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULVLuP3BU06rboH215:-MULVLuP3BU06rboH216:b-7knn8e) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/xds/xds_http_fault_filter.cc#L188)):*
> ```cpp
>     return parse_result.status();
>   }
>   return XdsHttpFilterImpl::FilterConfig{kXdsHttpFaultFilterConfigName,
> ```

I think there's no need to say `XdsHttpFilterImpl::` here.
___
*[src/core/ext/xds/xds_http_fault_filter.cc, line 224 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULVRJI4YZ4PUledJX-:-MULVRJI4YZ4PUledJX0:b-7knn8e) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/xds/xds_http_fault_filter.cc#L224)):*
> ```cpp
>                          : hcm_filter_config.config;
>   // The policy JSON may be empty, that's allowed.
>   return XdsHttpFilterImpl::ServiceConfigJsonEntry{"faultInjectionPolicy",
> ```

I think there's no need to say `XdsHttpFilterImpl::` here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8756 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUEg2k857fFCO6-iibh:-MUOePGYDdH1TtgbrH4B:b-doagf5) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/test/cpp/end2end/xds_end2end_test.cc#L8756)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Want to have slightly more discussion here:

1. Ultimately, I hope filter config setup should have 4 enum values (VH, Route, WeightedCluster, HCM) that can cover all filter configuring s [...]

2021-02-25 22:05 UTC, lidizheng reviewed
Thanks for the review again. The logic for streaming case is updated. But I didn't touch the xds_end2end_test yet, since there are two outstanding PR that might cause conflicts.

I will update the test after the two PRs are merged:

1. Try to add per-thread completion queue, so we can test delay injection with large number of RPCs;
2. Add streaming RPC testing mechanism (it isn't supported now);
3. Add 200/OK test cases.

> Reviewed 17 of 28 files at r22.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MUQBBKMDBSZN_kCaHCo:b-3qnb3b)* status: all files reviewed, 20 unresolved discussions (waiting on @donnadionne, @gnossen, @lidizheng, and @markdroth)

___
*[BUILD, line 1277 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKWlVS-KIhKeEJ5JsT:-MUPTV3X4Hi6yZc132dF:b-2dvz83) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/BUILD#L1277)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This dependency does not belong here, because it has nothing to do with this target.  It should actually be a dependency of the `grpc_common` target instead.
</blockquote></details>

Moved to `grpc_common`.
___
*[src/core/ext/filters/fault_injection/service_config_parser.h, line 29 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKaDao-9hh1miPWxrf:-MUPrbnq273E2a4RHymP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.h#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this inside of `FaultInjectionMethodParsedConfig`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/fault_injection/service_config_parser.h, line 52 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKaIt53vfsr-FQ5yRQ:-MUPWP294fHdPOB1adE9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.h#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 38 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKhRXY6lNjTdDtzn4x:-MUPsARKBhukahIWtuBK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.cc#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `policies_json_array` argument should be a reference, not a pointer.
</blockquote></details>

Done.
___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 39 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKhdaR9zyP1JjDwtCl:-MUPsQNb3lqTUZIIS9Y1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.cc#L39)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be the function's return value instead of being populated via a parameter.
</blockquote></details>

Done.
___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 41 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKhpN2BsajnbNEJr2K:-MUPs_a69RQziubIGk5M:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.cc#L41)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be a reference to avoid an unnecessary copy.
</blockquote></details>

Done.
___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 41 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULTtDc8L6pOI72AjyO:-MUQ-odk-CfkMvwOm8un:bcey269) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.cc#L41)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The entries added to `error_list` in each iteration of this array should indicate which index the problem is in.  Otherwise, it's basically impossible for users to know what a given error message is referring to.

I think the best way to do that is to have a separate error vector for each iteration through the array.  Then, at the end of a given iteration, use the equivalent of `GRPC_ERROR_CREATE_FROM_VECTOR()` to construct a new error whose description indicates the index in the array, and then add that error to the top-level error vector.  (Note that you won't be able to use `GRPC_ERROR_CREATE_FROM_VECTOR()` directly, since the description won't be a static string; there are examples of how to do this in the xds bootstrap parser code.)
</blockquote></details>

Done as suggested! Good idea.
___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 43 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKhmS5EAoRos9Rqht_:-MUPscwTD1lnX9UOLUWG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/service_config_parser.cc#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be a reference to avoid an unnecessary copy.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_http_fault_filter.h, line 38 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULU__FAG_qmL774AlJ:-MUPWyrv3a1Nlp3JUEBG:bqadwvn) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/xds/xds_http_fault_filter.h#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you don't need to say `XdsHttpFilterImpl::` anywhere in this file, since this class inherits from that one.
</blockquote></details>

In headers, the parent class namespace can be omit, but in the `cc` file the compiler still require it.
___
*[src/core/ext/xds/xds_http_fault_filter.cc, line 188 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULVLuP3BU06rboH215:-MUPt2g9DgMBVYRNDm4D:b-r19ujl) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/xds/xds_http_fault_filter.cc#L188)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think there's no need to say `XdsHttpFilterImpl::` here.
</blockquote></details>

I'm not sure why, but the compiler insists the `.cc` file should include the class prefix.
___
*[src/core/ext/xds/xds_http_fault_filter.cc, line 224 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULVRJI4YZ4PUledJX-:-MUPtCPY0dyhVFOdDzkX:b2nreh6) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/xds/xds_http_fault_filter.cc#L224)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think there's no need to say `XdsHttpFilterImpl::` here.
</blockquote></details>

Same as above.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 117 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKXjuAE7wCyDxrGara:-MUPToTQ274aDa2tcQ5M:b-xy34u1) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L117)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think you need to say `FaultInjectionFilter::` here, since this is inside that scope.
</blockquote></details>

Removed the `FaultInjectionFilter` class entirely, so we can get rid of the namespace prefix. That abstraction seems not providing any value.
___
*[src/core/ext/filters/fault_injection/ [...]

2021-03-02 00:33 UTC, markdroth requested changes
This is looking pretty good!

With regard to the test, I don't think it should be necessary to create multiple CQs.  Please convince me that you actually need to do that before you invest the time in it.

For streaming tests, I think I'd be okay with deferring that to a subsequent PR, just so we can get this one landed.

Please let me know if you have any questions.  Thanks!

> Reviewed 7 of 7 files at r24.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MUkL1bE5lJrBQM5Ggyt:b-jtms4l)* status: all files reviewed, 14 unresolved discussions (waiting on @donnadionne, @gnossen, and @lidizheng)

___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 46 at r24](https://reviewable.io/reviews/grpc/grpc/24354#-MUkJru7ChbDq2Qwl3--:-MUkJru7ChbDq2Qwl3-0:b-ck03da) ([raw file](https://github.com/grpc/grpc/blob/c0169f8a3e91723a2044f5b616063d2946867178/src/core/ext/filters/fault_injection/service_config_parser.cc#L46)):*
> ```cpp
>         fault_injection_policy;
>     std::vector<grpc_error*> sub_error_list;
>     const Json::Object& json_object = policies_json_array[i].object_value();
> ```

We need to check if the array index is actually of type OBJECT.  If not, we should add an error and skip to the next element.
___
*[src/core/ext/xds/xds_http_fault_filter.cc, line 188 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULVLuP3BU06rboH215:-MUkKPTE-0kgQV9JGvhd:b81yboj) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/xds/xds_http_fault_filter.cc#L188)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

I'm not sure why, but the compiler insists the `.cc` file should include the class prefix.
</blockquote></details>

Are you sure that's true on this specific line?

I know in places like the return type of this function on line 180 above, it's required, because there we are not in the scope of the class.  But inside of this function, we are in that scope, so I think it should work here.

If not, that's fine.  It's just not clear to me why it wouldn't work here.
___
*[src/core/ext/xds/xds_http_fault_filter.cc, line 224 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULVRJI4YZ4PUledJX-:-MUkK_9217EFVItW5iL0:b65n1u6) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/xds/xds_http_fault_filter.cc#L224)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Same as above -- I don't think you can remove it from the return type of this function, but I think you should be able to remove it from within the function itself.

If not, no big deal.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 280 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKb-bU8LczHa2Jm3iA:-MUkHJD16LsZ-hHwOzjL:bpotat) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L280)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Thanks for the detailed suggestion. I have updated the logic and filled in the callback injection, but I wonder is it possible that the callback of `recv_trailing_metadata` is invoked before a `send_initial_metadata` op is seen?

> In the unary case, all 6 ops are in the same batch (at least in C++; I'm not sure about wrapped languages), but that's not true for streaming. 

For Python and other gRPC implementations, there is always a hacky approach here. Users can use the streaming RPC API to invoke an unary call method, but only send one message and receive one response. This is valid gRPC traffic, and should success. On the bright side, with the new streaming RPC logic, we should be fine either way.
</blockquote></details>

No, it's not possible for the `recv_trailing_metadata_ready` callback to be invoked before the `send_initial_metadata` op is seen, because the call doesn't actually start on the wire until the `send_initial_metadata` op makes its way down to the transport.

Users in C++ can manually use the generic API to do a similar thing to what you describe, but that's an edge case; it's not what I would normally consider a unary call, even if the underlying method is defined as unary.

In any case, this change looks good!
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 21 at r24](https://reviewable.io/reviews/grpc/grpc/24354#-MUkFXXK-pKkkLKv5zGE:-MUkFXXLEfB11T_pxDuB:b-f827zd) ([raw file](https://github.com/grpc/grpc/blob/c0169f8a3e91723a2044f5b616063d2946867178/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L21)):*
> ```cpp
> #include <grpc/support/alloc.h>
> #include <grpc/support/log.h>
> #include <grpc/support/port_platform.h>
> ```

These two includes were already in the right places.  port_platform.h needs to be the very first one for portability reasons.  And the absl include is from a different project, which should come before the gRPC includes, as per the style guide.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 163 at r24](https://reviewable.io/reviews/grpc/grpc/24354#-MUkGES9-5cdrRexb0d3:-MUkGES9-5cdrRexb0d4:b-t7c9ws) ([raw file](https://github.com/grpc/grpc/blob/c0169f8a3e91723a2044f5b616063d2946867178/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L163)):*
> ```cpp
> 
>   // Delay states
>   grpc_timer delay_timer_;
> ```

We now have the ability to use lock annotations.  Please add `ABSL_GUARDED_BY(delay_mu_)` here, and for any other data member that is protected by that mutex.  That way, if we are accidentally accessing one of these fields without holding the mutex, the compiler will catch the problem.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 248 at r24](https://reviewable.io/reviews/grpc/grpc/24354#-MUkJDzR7L3NKnixQMNt:-MUkJDzS4tVtL7BX_WiP:b-o4toab) ([raw file](https://github.com/grpc/grpc/blob/c0169f8a3e91723a2044f5b616063d2946867178/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L248)):*
> ```cpp
> }
> 
> void CallData::HijackedRecvTrailingMetadataReady(void* arg, grpc_error* error) {
> ```

Please define methods in the same order in which they are declared in the class declaration above.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 286 at r24](https://reviewable.io/reviews/grpc/grpc/24354#-MUkId379hSOrAgPSxIY:-MUkId379hSOrAgPSxIZ:b-eapnuy) ([raw file](https://github.com/grpc/grpc/blob/c0169f8a3e91723a2044f5b616063d2946867178/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L286)):*
> ```cpp
>     }
>   } else {
>     if (batch->recv_trailing_metadata) {
> ```

Please add a comment here:

```
// Intercept recv_trailing_metadata callback so that we can inject the failure
// when aborting streaming calls.
```
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 287 at r24](https://reviewable.io/reviews/grpc/grpc/24354#-MUkHuOhAwXYBZzgB7Y8:-MUkHuOi8g3rzxrsiSCn:bw91zk5) ([raw file](https://github.com/grpc/grpc/blob/c0169f8a3e91723a2044f5b616063d2946867178/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L287)):*
> ```cpp
>   } else {
>     if (batch->recv_trailing_metadata) {
>       batch->payload->recv_trailing_metadata.recv_trailing_metadata_ready =
> ```

Before you overrwite this field in the batch, you need to save its original value in `calld->original_recv_trailing_metadata_ready_`.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 290 at r24](https://reviewable.io/reviews/grpc/grpc/24354#-MUkIaemBSgAdQBH8xXT:-MUkIaemBSgAdQBH8xXU:bv2w2hl) ([raw file](https://github.com/grpc/grpc/blob/c0169f8a3e91723a2044f5b616063d2946867178/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L290)):*
> ```cpp
>           &calld->recv_trailing_metadata_ready_;
>     }
>     if (calld [...]

2021-03-03 01:11 UTC, lidizheng reviewed
Thanks again for the detailed review!

As discussed offline, I will write another PR to reduce the error tolerance (not flakiness). I'm still waiting for the result of 1000x of different builds.

PTAL.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MUpQkcS7zfWOfm1wcsr:b1shp8o)* status: 31 of 40 files reviewed, 14 unresolved discussions (waiting on @donnadionne, @gnossen, @lidizheng, and @markdroth)

___
*[src/core/ext/filters/fault_injection/service_config_parser.cc, line 46 at r24](https://reviewable.io/reviews/grpc/grpc/24354#-MUkJru7ChbDq2Qwl3--:-MUp0grD7VwvFtzXC61l:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c0169f8a3e91723a2044f5b616063d2946867178/src/core/ext/filters/fault_injection/service_config_parser.cc#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We need to check if the array index is actually of type OBJECT.  If not, we should add an error and skip to the next element.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_http_fault_filter.cc, line 188 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULVLuP3BU06rboH215:-MUp4Ji14GyC1iAt5clV:bl2wq8y) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/xds/xds_http_fault_filter.cc#L188)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Are you sure that's true on this specific line?

I know in places like the return type of this function on line 180 above, it's required, because there we are not in the scope of the class.  But inside of this function, we are in that scope, so I think it should work here.

If not, that's fine.  It's just not clear to me why it wouldn't work here.
</blockquote></details>

You are right. I can remove the prefix inside the method body, but can't remove the prefix in signature. TIL another quirk about C++.
___
*[src/core/ext/xds/xds_http_fault_filter.cc, line 224 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MULVRJI4YZ4PUledJX-:-MUp4ZVi9llvnGfaFODJ:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172b767e3ad80c2d49504d5682d2/src/core/ext/xds/xds_http_fault_filter.cc#L224)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as above -- I don't think you can remove it from the return type of this function, but I think you should be able to remove it from within the function itself.

If not, no big deal.
</blockquote></details>

Removed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4657 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLT9MTI-ndADA9cKohN:-MUpbwLv1yTgZDmGwzsc:bna2bk1) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/test/cpp/end2end/xds_end2end_test.cc#L4657)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This still needs to be addressed.
</blockquote></details>

To push for lower error tolerance, we will need more RPC runs. Under current tools, we won't be able to write tests that finishes in reasonable time while very very reliable (think 0.05 tolerance). This constraint is mostly applied to PercentageDelay tests and AlwaysDelayPercentageAbort tests. They injects fixed amount of delay and the RPCs require to be executed sequentially.

In a follow-up PR, I guess I can explore the possibility of 1. using a larger thread pool; 2. try out callback API (if it is throughly tested in OSS).
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4999 at r15](https://reviewable.io/reviews/grpc/grpc/24354#-MMO12PN3yKPgB7tqvif:-MUpQWqk1KMr-5Id-3NY:bt6fiu3) ([raw file](https://github.com/grpc/grpc/blob/4246b6146f5ae1be07eefd28f055e64ba6aa1e15/test/cpp/end2end/xds_end2end_test.cc#L4999)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This approach seems reasonable, assuming that you've verified (by running 1000x on RBE with opt, dbg, asan, tsan, msan, and ubsan) that this approach is not flaky.
</blockquote></details>

The 1000x on RBE with opt, dbg, asan, tsan, msan, and ubsan is still ongoging. Will update once they are finished.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2287 at r19](https://reviewable.io/reviews/grpc/grpc/24354#-MRRbv35AdkWKX_gyiiH:-MUp6YgN0ADjomSDkPKl:b-ydonj4) ([raw file](https://github.com/grpc/grpc/blob/8a2d688846cb96f95a2bb34f106d8dd2af6b7ed4/test/cpp/end2end/xds_end2end_test.cc#L2287)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This still needs to be addressed.
</blockquote></details>

Done. Good idea!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8756 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUEg2k857fFCO6-iibh:-MUpGrFj3gEv8XZMjFJ7:bmootxu) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/test/cpp/end2end/xds_end2end_test.cc#L8756)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's a best practice for each test to run just one test case, and to minimize the amount of conditionals and loops in the test itself.  Individual tests should be as simple and readable as possible.  Whatever parameterization you want here can be added to `TestType`.

If you specifically want a test that covers changes between setups, then let's add such a test separately.

I agree that the `TestType` API is a little ugly; that's something I've been meaning to fix for a while.  I've sent you #25557 to make it easier to see what each invocation is actually doing.
</blockquote></details>

Moved the enum to the new TestType API.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9042 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUEd7FT6NNvPd5-QQN0:-MUpMt3FDbETzAWUhBbI:b1uxlpt) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/test/cpp/end2end/xds_end2end_test.cc#L9042)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why are there clock differences here?

If there are, maybe you can fix them by doing something similar to what @donnadionne did in #25085. I'd prefer to avoid adding another fudge-factor here if possible.
</blockquote></details>

Two factors contributed to the clock difference here:

1. We are rounding at millisecond-level, same as #25085, which will create difference within 0.5ms;
2. To make the test run quickly and stably, we need to sequentially run 100 RPCs with a really short fixed delay (10ms), which makes the 0.5ms significant here.

To remove the delay, there are several directions:

1. Explicitly sleep 0.5ms for every RPCs  (move the difference [-0.5, 0.5] to [0, 1], and we are comparing using greater or equal than);
2. Ensure the same time fetching mechanism in test cases and in Core implementation like #25085;
3. Enable the parallel RPC with per-thread CQ or callback API or larger thread-pool to allow the injection of longer fixed delay (like 2 seconds, which will make 0.5ms negligible).

WDYT?
___
*[src/core/ext/filters/client_channel/fault_injection_filter.cc, line 280 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUBKp1aBvwuZFZkpOJu:-MUp3e7H3lM7QgB9lkcS:b-bt7yc1) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/src/core/ext/filters/client_channel/fault_injection_filter.cc#L280)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is definitely something we need to fix before we merge this PR.  We should never be destroying the same object more than once.
</blockquote></details>

Removed.

Can't reproduce with latest version. Will investigate if it appears again.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 254 at r23](https://reviewable.io/reviews/grpc/grpc/24354#-MUKY6IpAVO2ZOXiQJ_n:-MUoyy3M5oxv3dP7n-fZ:b-im62yv) ([raw file](https://github.com/grpc/grpc/blob/480b56c9bbf6172 [...]

2021-03-03 19:51 UTC, lidizheng reviewed
This PR has passed 1000x of asan, ubsan, tsan. I also found that there is a 1% flake with `~XdsClient` that doesn't seem to be related with this PR: [tsan](https://source.cloud.google.com/results/invocations/7dd1bcb8-5fe5-4889-80a2-0e22ff6c1401).

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MUtZYiC0ra3gh4ecq9o:b-jqh8w2)* status: 31 of 40 files reviewed, 14 unresolved discussions (waiting on @donnadionne, @gnossen, @lidizheng, and @markdroth)



<!-- Sent from Reviewable.io -->

2021-03-04 18:14 UTC, markdroth requested changes
The code looks great!  There are just a few remaining comments in the tests.

Please let me know if you have any questions.  Thanks!

> Reviewed 7 of 9 files at r25, 1 of 1 files at r26, 1 of 1 files at r27.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MUyRRphCTNA-6f9TR9u:b-au7be8)* status: all files reviewed, 7 unresolved discussions (waiting on @donnadionne, @gnossen, and @lidizheng)

___
*[test/cpp/end2end/BUILD, line 509 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyIK7O173Yg0uO2zsb:-MUyIK7O173Yg0uO2zsc:ba1h3gn) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/test/cpp/end2end/BUILD#L509)):*
> ```Starlark
>     args = [
>         # DO NOT SUBMIT: remove before merge into master
>         "--gtest_filter='*Fault*'",
> ```

It's not necessary to set this here.  You can invoke bazel with `--test_arg="--gtest_filter='*Fault*'"`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4657 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLT9MTI-ndADA9cKohN:-MUyPboO3RKvtu3JHq_y:b-a7m3a6) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/test/cpp/end2end/xds_end2end_test.cc#L4657)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

To push for lower error tolerance, we will need more RPC runs. Under current tools, we won't be able to write tests that finishes in reasonable time while very very reliable (think 0.05 tolerance). This constraint is mostly applied to PercentageDelay tests and AlwaysDelayPercentageAbort tests. They injects fixed amount of delay and the RPCs require to be executed sequentially.

In a follow-up PR, I guess I can explore the possibility of 1. using a larger thread pool; 2. try out callback API (if it is throughly tested in OSS).
</blockquote></details>

Okay, I guess I can live with deferring the work of decreasing the error tolerance to a future PR.  Please add a TODO about this.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9042 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUEd7FT6NNvPd5-QQN0:-MUyQVKs9kbCeLgDnjcQ:bsfsfnd) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/test/cpp/end2end/xds_end2end_test.cc#L9042)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Two factors contributed to the clock difference here:

1. We are rounding at millisecond-level, same as #25085, which will create difference within 0.5ms;
2. To make the test run quickly and stably, we need to sequentially run 100 RPCs with a really short fixed delay (10ms), which makes the 0.5ms significant here.

To remove the delay, there are several directions:

1. Explicitly sleep 0.5ms for every RPCs  (move the difference [-0.5, 0.5] to [0, 1], and we are comparing using greater or equal than);
2. Ensure the same time fetching mechanism in test cases and in Core implementation like #25085;
3. Enable the parallel RPC with per-thread CQ or callback API or larger thread-pool to allow the injection of longer fixed delay (like 2 seconds, which will make 0.5ms negligible).

WDYT?
</blockquote></details>

I don't understand your comment about why sequentially running 100 RPCs with really short delays makes a difference.  We're checking the start and end time of each individual RPC, so the sequential nature is irrelevant.

Taking the same approach as #25085 seems clearly easiest and cleanest here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1311 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyLsVjAcyfT1ZMQEcS:-MUyLsVjAcyfT1ZMQEcT:b12wyzv) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/test/cpp/end2end/xds_end2end_test.cc#L1311)):*
> ```cpp
>   enum FilterConfigSetup {
>     // Set the fault injection filter directly from LDS
>     HTTPConnectionManagerOriginal,
> ```

Please use a `k` prefix for these, as per the style guide.

https://google.github.io/styleguide/cppguide.html#Enumerator_Names
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8784 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyQ4ZA4sGcj4L3WyAj:-MUyQ4ZA4sGcj4L3WyAk:b-j06836) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/test/cpp/end2end/xds_end2end_test.cc#L8784)):*
> ```cpp
> 
>  private:
>   TestType::FilterConfigSetup filter_config_setup_;
> ```

There is no need for this data member.  The code can just use `GetParam().filter_config_setup()` anywhere that it might access this.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 262 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyEt2pAAXE7bDbzi6v:-MUyEt2pAAXE7bDbzi6w:b-9eawjd) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L262)):*
> ```cpp
> }
> 
> class CallData::ResumeBatchCanceller {
> ```

This class is inside of `CallData`, but it's a separate class.  Let's move it up above the first method of `CallData`, so that we're not interspersing one class's methods inside of another.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 322 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyFgk1DwxvRhG5ROfA:-MUyFgk1DwxvRhG5ROfB:bvolp9) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L322)):*
> ```cpp
> CallData::~CallData() {
>   // Destroy may have a race with resume canceller on deallocating lock itself.
>   MutexLock lock(&delay_mu_);
> ```

I don't think we need to hold the lock here.  By the time we're destroying the call stack, we know that there are no other outstanding callers using the object, so there's no need to synchronize.


<!-- Sent from Reviewable.io -->

2021-03-08 20:01 UTC, lidizheng reviewed
The time counting mechanism is updated. And it has passed 1000x of various sanitizers.

PTAL. Thanks for the review!

> Reviewed 15 of 18 files at r28.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MVIPe4RAh6U5RO2LvPh:bwyu5ac)* status: 37 of 40 files reviewed, 7 unresolved discussions (waiting on @donnadionne, @gnossen, and @markdroth)

___
*[test/cpp/end2end/BUILD, line 509 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyIK7O173Yg0uO2zsb:-MV2xj768C2L8NeRxRaj:bpmqy0g) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/test/cpp/end2end/BUILD#L509)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not necessary to set this here.  You can invoke bazel with `--test_arg="--gtest_filter='*Fault*'"`.
</blockquote></details>

Done. This was a debug line to let multiple repo running RBE in parallel on the same branch.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4657 at r8](https://reviewable.io/reviews/grpc/grpc/24354#-MLT9MTI-ndADA9cKohN:-MV2x8VhATbat3GKHoNJ:b-wk33ap) ([raw file](https://github.com/grpc/grpc/blob/6957bfe770185fa59cd812ac5e67b0b30222685c/test/cpp/end2end/xds_end2end_test.cc#L4657)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay, I guess I can live with deferring the work of decreasing the error tolerance to a future PR.  Please add a TODO about this.
</blockquote></details>

Done. TODO added.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9042 at r20](https://reviewable.io/reviews/grpc/grpc/24354#-MUEd7FT6NNvPd5-QQN0:-MV307Ud6nr9ym07dnKK:bg0b690) ([raw file](https://github.com/grpc/grpc/blob/53aab8ac769f06a7e03b80b7f299453713ff389d/test/cpp/end2end/xds_end2end_test.cc#L9042)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't understand your comment about why sequentially running 100 RPCs with really short delays makes a difference.  We're checking the start and end time of each individual RPC, so the sequential nature is irrelevant.

Taking the same approach as #25085 seems clearly easiest and cleanest here.
</blockquote></details>

Done. I guess GPR isn't looking at the same clock as C++'s system clock API.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1311 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyLsVjAcyfT1ZMQEcS:-MV2wUeD1cKReXPsVmbi:biduacb) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/test/cpp/end2end/xds_end2end_test.cc#L1311)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use a `k` prefix for these, as per the style guide.

https://google.github.io/styleguide/cppguide.html#Enumerator_Names
</blockquote></details>

Done. Nice to know!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8784 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyQ4ZA4sGcj4L3WyAj:-MV2xVp51GhMD1jQ5cXP:bp45yyx) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/test/cpp/end2end/xds_end2end_test.cc#L8784)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There is no need for this data member.  The code can just use `GetParam().filter_config_setup()` anywhere that it might access this.
</blockquote></details>

Done. I don't know what I was thinking.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 262 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyEt2pAAXE7bDbzi6v:-MV2vucS0RfZubydPMNR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L262)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This class is inside of `CallData`, but it's a separate class.  Let's move it up above the first method of `CallData`, so that we're not interspersing one class's methods inside of another.
</blockquote></details>

Done.
___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 322 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyFgk1DwxvRhG5ROfA:-MV3CIw11DtmNS1eeR3K:bfrlj36) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L322)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need to hold the lock here.  By the time we're destroying the call stack, we know that there are no other outstanding callers using the object, so there's no need to synchronize.
</blockquote></details>

Removed. We might want to resolve the `~XdsClient` flake (~1%) before resolving this Mutex deallocation race (~0.1%).


<!-- Sent from Reviewable.io -->

2021-03-08 23:25 UTC, markdroth approved these changes
This looks great!

> Reviewed 13 of 18 files at r28, 3 of 3 files at r29.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24354#-:-MVJ98u4D4PQzwxkBF5S:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/core/ext/filters/fault_injection/fault_injection_filter.cc, line 322 at r27](https://reviewable.io/reviews/grpc/grpc/24354#-MUyFgk1DwxvRhG5ROfA:-MVJ8N1C1hNwyeHtlui_:b831o8h) ([raw file](https://github.com/grpc/grpc/blob/1eefe9f16eb1561b87bc841f59504733f53506b5/src/core/ext/filters/fault_injection/fault_injection_filter.cc#L322)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Removed. We might want to resolve the `~XdsClient` flake (~1%) before resolving this Mutex deallocation race (~0.1%).
</blockquote></details>

I'm not sure exactly which flake you're referring to, but if it's the same one you mentioned in the CSDS PR, then it was recently fixed by Alex in #25485.


<!-- Sent from Reviewable.io -->

2021-03-09 16:20 UTC, markdroth commented
For future reference, note that it's no longer necessary to manually squash your commits before merging -- that will now happen automatically in the merge process.

2021-03-09 21:14 UTC, lidizheng commented
Known failure: https://github.com/grpc/grpc/issues/25660
(Squashing the commit before rebasing to master makes conflict resolving easier.)

2021-03-09 21:14 UTC, merged

2021-03-09 22:19 UTC, markdroth commented
There's no need to rebase to master.  Just merge master into your branch and push to github.