xDS Bootstrap changes for certificate providers
grpc/grpc pull request #24409
Opened 2020-10-14 00:10 UTC by yashykt

Adds parsing for "certificate_providers" field in xds bootstrap

2020-10-14 17:03 UTC, markdroth requested changes
This looks good overall!  Comments are all relatively minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24409#-:-MJc2xPZEw92OhYOprxo:b-al50jm)* status: all files reviewed, 18 unresolved discussions (waiting on @yashykt)

___
*[BUILD, line 1322 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbfViN5PXYMm5g5GGM:-MJbfViN5PXYMm5g5GGN:b-57rple) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/BUILD#L1322)):*
> ```Starlark
>     deps = [
>         "grpc_base",
>         "grpc_xds_credentials",
> ```

This made me realize that we no longer need the grpc_xds_api_header target.  I've sent out #24414 to remove it.  Once that's merged, this dependency can be added to the grpc_xds_client target instead.
___
*[BUILD, line 1826 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbhyYA1C1Xpasvvt3W:-MJbhyYA1C1Xpasvvt3X:b-e3m0rl) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/BUILD#L1826)):*
> ```Starlark
> 
> grpc_cc_library(
>     name = "grpc_xds_credentials",
> ```

Might be a good idea to move this up next to the other xds-related targets.
___
*[src/core/ext/xds/certificate_provider_store.h, line 37 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbmRASDqbCzNtRXOnT:-MJbmRASDqbCzNtRXOnU:bsurln5) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/certificate_provider_store.h#L37)):*
> ```objc
> class CertificateProviderStore {
>  public:
>   struct CertificateProviderPlugin {
> ```

Suggest calling this `PluginDefinition`.  (No need for the `CertificateProvider` prefix, since that's clear from the name of the surrounding class.)
___
*[src/core/ext/xds/certificate_provider_store.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbh7O7-MBbQqAHZFIq:-MJbh7O86HNWmcGvo1hu:b-gyzl3) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/certificate_provider_store.h#L43)):*
> ```objc
> 
>   CertificateProviderStore(
>       std::map<std::string, CertificateProviderPlugin> plugin_config_map)
> ```

This map type seems to be used in a number of places.  I suggest adding a new `PluginDefinitionMap` type definition for it.
___
*[src/core/ext/xds/certificate_provider_store.h, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbhW3XBuJO_zTBBMHH:-MJbhW3XBuJO_zTBBMHI:b-o3kwbe) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/certificate_provider_store.h#L51)):*
> ```objc
>   // maintains a ref to the grpc_tls_certificate_provider for its entire
>   // lifetime.
>   RefCountedPtr<grpc_tls_certificate_provider> CreateOrGetCertificateProvider(
> ```

Looks like we don't yet have an implementation for this method.  Is that going to be in a separate PR?
___
*[src/core/ext/xds/certificate_provider_store.h, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJblbll1-dx-xnF_t2K:-MJblblm53VmUe02DWWT:b-anjdgl) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/certificate_provider_store.h#L58)):*
> ```objc
>   std::map<std::string, CertificateProviderPlugin> plugin_config_map_;
>   // Underlying map for the providers.
>   std::map<std::string, RefCountedPtr<grpc_tls_certificate_provider>>
> ```

The key here can probably be `absl::string_view` now, pointing to the key in `plugin_config_map_`.  This will make the lookup more efficient, since the parameter to `CreateOrGetCertificateProvider()` is an `absl::string_view`.  (The way this is now, `CreateOrGetCertificateProvider()` will need to instantiate a string from its argument before it can do the map lookup.)
___
*[src/core/ext/xds/xds_bootstrap.h, line 31 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbh-QuCcitcRowB_Fh:-MJbh-QvBEskSIoJOK2M:b-v0wj2d) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.h#L31)):*
> ```objc
> #include <grpc/impl/codegen/slice.h>
> 
> #include "src/core/ext/xds/certificate_provider_factory.h"
> ```

This include doesn't seem to be needed, since we're not using any factories here.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 156 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbn1HU5-FJptXWhE5d:-MJbn1HU5-FJptXWhE5e:b2lkm2b) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L156)):*
> ```cpp
>     }
>   }
>   auto cert_providers_it = json.object_value().find("certificate_providers");
> ```

We can just reuse the existing `it` variable here.  No need to create a new one.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 403 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbnl9s920H_Fdpqn4A:-MJbnl9s920H_Fdpqn4B:bfwxx0k) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L403)):*
> ```cpp
> 
> grpc_error* XdsBootstrap::ParseCertificateProvider(
>     std::pair<std::string, Json> certificate_provider) {
> ```

Suggest passing these down as two different parameters rather than together in a `std::pair<>`.  I think that will make the code here a little easier to follow.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 413 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbo0RD4-8wZO5wfrjr:-MJbo0RD4-8wZO5wfrjs:b-ah2odt) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L413)):*
> ```cpp
>         "\"plugin_name\" field is not a string"));
>   } else {
>     std::string plugin_name = it->second.string_value();
> ```

This can be a const reference.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 433 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJboL6BE8n53rQrT76O:-MJboL6BE8n53rQrT76P:b16ze79) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L433)):*
> ```cpp
>         // "config" is an optional field, so create an empty JSON object.
>         grpc_error* parse_error = GRPC_ERROR_NONE;
>         Json config_json = Json::Parse("{}", &parse_error);
> ```

I think this isn't necessary.  You can just use `Json::Object()` as the first argument to `factory->CreateCertificateProviderConfig()`.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 439 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbo5FK78WU1Mwy67td:-MJbo5FK78WU1Mwy67te:b-9lugp7) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L439)):*
> ```cpp
>         if (parse_error != GRPC_ERROR_NONE) error_list.push_back(parse_error);
>       }
>       certificate_providers_.insert(
> ```

Suggest writing this as:

```
certificate_providers_[certificate_provider.first] = {plugin_name, std::move(config)};
```
___
*[src/core/ext/xds/xds_bootstrap.cc, line 443 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbp57J0YWRkNnb1akt:-MJbp57J0YWRkNnb1aku:b-bx4x41) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L443)):*
> ```cpp
>     }
>   }
>   return GRPC_ERROR_CREATE_FROM_VECTOR(
> ```

`GRPC_ERROR_CREATE_FROM_VECTOR()` assumes its first argument is a static string.  See line 275 for an example of how this should be handled.
___
*[test/core/client_channel/xds_bootstrap_test.cc, line 31 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJc-Guf34k6e1i7FhAl:-MJc-Guf34k6e1i7FhAm:bowa934) ([raw file](https://github.com/grpc/grpc/blob/0f71df865547c63819ade7a26689434c59ee3799/test/core/client_channel/xds_bootstrap_test.cc#L31)):*
> ```cpp
> namespace testing {
> 
> void VerifyRegexMatch(grpc_error* error, const std::regex& e) {
> ```

This reminds me that I've been meaning to make the same change in service_config_test.cc [...]

2020-10-15 19:55 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24409)* status: 4 of 9 files reviewed, 18 unresolved discussions (waiting on @markdroth)

___
*[BUILD, line 1322 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbfViN5PXYMm5g5GGM:-MJhp6qdBGHZQf7upcjD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/BUILD#L1322)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This made me realize that we no longer need the grpc_xds_api_header target.  I've sent out #24414 to remove it.  Once that's merged, this dependency can be added to the grpc_xds_client target instead.
</blockquote></details>

Done.
___
*[BUILD, line 1826 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbhyYA1C1Xpasvvt3W:-MJhp8-03eNCczpyCrlB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/BUILD#L1826)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Might be a good idea to move this up next to the other xds-related targets.
</blockquote></details>

Done.
___
*[src/core/ext/xds/certificate_provider_store.h, line 37 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbmRASDqbCzNtRXOnT:-MJhpB9FDnrjt2FcJ1XE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/certificate_provider_store.h#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `PluginDefinition`.  (No need for the `CertificateProvider` prefix, since that's clear from the name of the surrounding class.)
</blockquote></details>

Done.
___
*[src/core/ext/xds/certificate_provider_store.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbh7O7-MBbQqAHZFIq:-MJhpBea668Rd3Wtpfo5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/certificate_provider_store.h#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This map type seems to be used in a number of places.  I suggest adding a new `PluginDefinitionMap` type definition for it.
</blockquote></details>

Done.
___
*[src/core/ext/xds/certificate_provider_store.h, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbhW3XBuJO_zTBBMHH:-MJhpC7EEBKkbrjp8sZx:b2nhswy) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/certificate_provider_store.h#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like we don't yet have an implementation for this method.  Is that going to be in a separate PR?
</blockquote></details>

Yes
___
*[src/core/ext/xds/certificate_provider_store.h, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJblbll1-dx-xnF_t2K:-MJhpDcR34KuYfLJ3421:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/certificate_provider_store.h#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The key here can probably be `absl::string_view` now, pointing to the key in `plugin_config_map_`.  This will make the lookup more efficient, since the parameter to `CreateOrGetCertificateProvider()` is an `absl::string_view`.  (The way this is now, `CreateOrGetCertificateProvider()` will need to instantiate a string from its argument before it can do the map lookup.)
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.h, line 31 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbh-QuCcitcRowB_Fh:-MJhpFjA4t6U_8nCxM2w:ba3dfob) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.h#L31)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This include doesn't seem to be needed, since we're not using any factories here.
</blockquote></details>

Removed
___
*[src/core/ext/xds/xds_bootstrap.cc, line 156 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbn1HU5-FJptXWhE5d:-MJhf1N-8GvRNXBh9-kP:b1uisp3) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L156)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We can just reuse the existing `it` variable here.  No need to create a new one.
</blockquote></details>

For some reason `it` is based on a mutable object which is not needed here, and hence the new one
___
*[src/core/ext/xds/xds_bootstrap.cc, line 403 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbnl9s920H_Fdpqn4A:-MJhokoa55HMMPHVV5d5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L403)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest passing these down as two different parameters rather than together in a `std::pair<>`.  I think that will make the code here a little easier to follow.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 413 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbo0RD4-8wZO5wfrjr:-MJhom4o6obU5E1grawh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L413)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be a const reference.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 433 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJboL6BE8n53rQrT76O:-MJhonj_EbSFVWrBm013:b-nib5vs) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L433)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this isn't necessary.  You can just use `Json::Object()` as the first argument to `factory->CreateCertificateProviderConfig()`.
</blockquote></details>

I think you meant `Json()`. Didn't know that was allowed. Thanks!
___
*[src/core/ext/xds/xds_bootstrap.cc, line 439 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbo5FK78WU1Mwy67td:-MJhiCUMAKik6LjVCol6:b-tmfj82) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L439)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as:

```
certificate_providers_[certificate_provider.first] = {plugin_name, std::move(config)};
```
</blockquote></details>

Based on https://stackoverflow.com/questions/4286670/what-is-the-preferred-idiomatic-way-to-insert-into-a-map, looks like `insert()` is the preferred and more efficient way of doing an insert.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 443 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbp57J0YWRkNnb1akt:-MJhoMCwC4xhiNGMs9wH:b1c0sb) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L443)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`GRPC_ERROR_CREATE_FROM_VECTOR()` assumes its first argument is a static string.  See line 275 for an example of how this should be handled.
</blockquote></details>

Thanks! I was trying to figure this was the bug causing issues.
___
*[test/core/client_channel/xds_bootstrap_test.cc, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbvbrn2DJvUFnKly4M:-MJhlHnR7Ty38aBLYKrc:bjbk0u6) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/test/core/client_channel/xds_bootstrap_test.cc#L34)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These [...]

2020-10-15 21:58 UTC, markdroth requested changes
This looks very good!  Remaining comments are very minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24409#-:-MJiGQBmEcb3gCYhKSaV:b-okzep)* status: all files reviewed, 3 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_bootstrap.cc, line 156 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbn1HU5-FJptXWhE5d:-MJiEdeV5tTIXmDmX_7n:bipzof9) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L156)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

For some reason `it` is based on a mutable object which is not needed here, and hence the new one
</blockquote></details>

`ParseCertificateProviders()` should probably take a mutable `Json*` instead of `const Json&`, for the same reason that the other parsing helper functions do: it allows the child policy to `std::move()` strings out of the `Json` object instead of copying them.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 433 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJboL6BE8n53rQrT76O:-MJiF7syEorU5b9HED6O:b-m00u0v) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L433)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I think you meant `Json()`. Didn't know that was allowed. Thanks!
</blockquote></details>

I think you actually want `Json::Object()` here.  Note that `Json` has a non-explicit ctor for a `Json::Object` parameter, which will give the empty object type `Json::Type::OBJECT` instead of `Json::Type::JSON_NULL`.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 404 at r3](https://reviewable.io/reviews/grpc/grpc/24409#-MJiF0kkDzQxIaCEgQKH:-MJiF0kkDzQxIaCEgQKI:b8ej1kv) ([raw file](https://github.com/grpc/grpc/blob/49b4c26a67868689283689e74ba4c1cbbcd1070a/src/core/ext/xds/xds_bootstrap.cc#L404)):*
> ```cpp
> 
> grpc_error* XdsBootstrap::ParseCertificateProvider(
>     const std::string& opaque_name, const Json& certificate_provider_json) {
> ```

Suggest calling this parameter `instance_name`.
___
*[test/core/client_channel/xds_bootstrap_test.cc, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbvbrn2DJvUFnKly4M:-MJiG2iS7gty7Qz22d-z:b2ads7y) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/test/core/client_channel/xds_bootstrap_test.cc#L34)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

https://github.com/google/googletest/blob/master/googletest/docs/faq.md#should-i-use-the-constructordestructor-of-the-test-fixture-or-setupteardown-ctorvssetup suggests that ctor/dtor is preferred
</blockquote></details>

Interesting!  I could have sworn that they used to give exactly the opposite recommendation.  Either I'm remembering wrong, or it changed at some point.

Anyway, this is fine.


<!-- Sent from Reviewable.io -->

2020-10-15 22:57 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24409)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_bootstrap.cc, line 156 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJbn1HU5-FJptXWhE5d:-MJiTdVA-bAIzqGMs4r7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L156)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`ParseCertificateProviders()` should probably take a mutable `Json*` instead of `const Json&`, for the same reason that the other parsing helper functions do: it allows the child policy to `std::move()` strings out of the `Json` object instead of copying them.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 433 at r1](https://reviewable.io/reviews/grpc/grpc/24409#-MJboL6BE8n53rQrT76O:-MJiThcFEhuqEa2qBuVe:b-wrpmn8) ([raw file](https://github.com/grpc/grpc/blob/6ac54d486de8dbb53972ada40b901a018e4a4d5a/src/core/ext/xds/xds_bootstrap.cc#L433)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you actually want `Json::Object()` here.  Note that `Json` has a non-explicit ctor for a `Json::Object` parameter, which will give the empty object type `Json::Type::OBJECT` instead of `Json::Type::JSON_NULL`.
</blockquote></details>

Done. Added a test to check for this
___
*[src/core/ext/xds/xds_bootstrap.cc, line 404 at r3](https://reviewable.io/reviews/grpc/grpc/24409#-MJiF0kkDzQxIaCEgQKH:-MJiTeqX8y3Zf10k5aiw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/49b4c26a67868689283689e74ba4c1cbbcd1070a/src/core/ext/xds/xds_bootstrap.cc#L404)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this parameter `instance_name`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-16 14:36 UTC, markdroth approved these changes
This looks great!  Just one minor nit remaining; feel free to merge when that's addressed.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24409#-:-MJlpp6p9R5CfFxQtO1i:b-bogjoj)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/ext/xds/xds_bootstrap.cc, line 413 at r4](https://reviewable.io/reviews/grpc/grpc/24409#-MJlotd42MOwYpTic4qi:-MJlotd54BH9zbRyMm4K:bu1z5eh) ([raw file](https://github.com/grpc/grpc/blob/e285e765337b372a6e6e6b1ca2a4bc49b10076c1/src/core/ext/xds/xds_bootstrap.cc#L413)):*
> ```cpp
>         "\"plugin_name\" field is not a string"));
>   } else {
>     std::string* plugin_name = it->second.mutable_string_value();
> ```

No need for this to be a pointer.  This can just say:

```
std::string plugin_name = std::move(it->second.mutable_string_value());
```


<!-- Sent from Reviewable.io -->

2020-10-16 17:54 UTC, yashykt commented
___
*[src/core/ext/xds/xds_bootstrap.cc, line 413 at r4](https://reviewable.io/reviews/grpc/grpc/24409#-MJlotd42MOwYpTic4qi:-MJmY2rR25AzHseDmNwq:b-ilvfz9) ([raw file](https://github.com/grpc/grpc/blob/e285e765337b372a6e6e6b1ca2a4bc49b10076c1/src/core/ext/xds/xds_bootstrap.cc#L413)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this to be a pointer.  This can just say:

```
std::string plugin_name = std::move(it->second.mutable_string_value());
```
</blockquote></details>

That seems to be an unnecessary move


<!-- Sent from Reviewable.io -->

2020-10-16 22:58 UTC, merged