[3PI Support] Add url-sourced external account credentials
grpc/grpc pull request #24411
Opened 2020-10-14 10:44 UTC by renkelvin

### Structure of 3PI Support
The implementation of 3PI support is organized as follows:
1. Base external account credentials class [#24208]
2. Subclasses to base external account credentials
    **a. url-sourced credentials [This PR]**
    b. file-sourced credentials
    c. aws-sourced credentials
3. Internal and public apis of external account credentials

@markdroth Please take a look and let me know if you have any questions. Thanks!

2020-10-16 15:57 UTC, markdroth requested changes
This looks like a good start!

Please let me know if you have any questions.  Thanks!

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411#-:-MJm7MW2Cn23t7ml27BY:bntdxje)* status: all files reviewed, 18 unresolved discussions (waiting on @jiangtaoli2016 and @renkelvin)

___
*[src/core/lib/security/credentials/external/url_external_account_credentials.h, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm-wRp1kSmMxXJILTK:-MJm-wRp1kSmMxXJILTL:bdbqv7m) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.h#L32)):*
> ```objc
> 
>  protected:
>   void RetrieveSubjectToken(
> ```

This can actually be `private`, since IIUC this class is not going to have any subclasses.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.h, line 44 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm0BW_10thN0RHI1Yj:-MJm0BW_10thN0RHI1Yk:b-vp5w07) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.h#L44)):*
> ```objc
>     std::string url;
>     std::map<std::string, std::string> headers;
>     struct {
> ```

Why put this fields in a nested struct?  Why not just make them top-level fields?
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 28 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm0WGa6T92Oa4dJGpI:-MJm0WGa6T92Oa4dJGpJ:bfxabs7) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L28)):*
> ```cpp
> UrlExternalAccountCredentials::UrlExternalAccountCredentials(
>     ExternalAccountCredentialsOptions options, std::vector<std::string> scopes)
>     : ExternalAccountCredentials(options, scopes) {}
> ```

Please use `std::move()` for both of these parameters.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm0nye6j44O8u1rK-e:-MJm0nye6j44O8u1rK-f:b-o6g9dx) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L41)):*
> ```cpp
>     return;
>   }
>   ctx_ = const_cast<HTTPRequestContext*>(ctx);
> ```

Why are we removing the const-ness here?  If we actually need to modify the context in subclasses, why is the API such that it's passed down as a const pointer to begin with?
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm11QeBHbXMYtUW7HR:-MJm11QeBHbXMYtUW7HS:bnc84fr) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L43)):*
> ```cpp
>   ctx_ = const_cast<HTTPRequestContext*>(ctx);
>   cb_ = cb;
>   grpc_error* error = ParseCredentialSource(options.credential_source);
> ```

This parsing should really be done at the time the credentials are created rather than doing it when a request is actually started, for two reasons.  First, it's better for users for the error to be caught earlier.  And second, there will be many requests over the lifetime of an application process, and it's inefficient to redo this parsing each time a request starts.

I suggest moving this parsing to the ctor and providing a way for the ctor to indicate failure back to the caller.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm1yKY2kq0Vl_qYUAM:-MJm1yKY2kq0Vl_qYUAN:bh2mnoq) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L48)):*
> ```cpp
>     return;
>   }
>   grpc_uri* uri = grpc_uri_parse(credential_source_.url.c_str(), false);
> ```

This can also be done once in the ctor.  It does not need to be done for each request.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 69 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm2JuoE9x8ZFVCgAft:-MJm2JuoE9x8ZFVCgAfu:bapzngd) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L69)):*
> ```cpp
>     headers[i].key = gpr_strdup(header.first.c_str());
>     headers[i].value = gpr_strdup(header.second.c_str());
>     i++;
> ```

Prefer preincrement to postincrement syntax, as per the style guide.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 89 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm2gOPDGNicR4T7LDE:-MJm2gOPDGNicR4T7LDF:b-wc8ks) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L89)):*
> ```cpp
> grpc_error* UrlExternalAccountCredentials::ParseCredentialSource(
>     const Json& json) {
>   CredentialSource credential_source = {};
> ```

No need for `=  {}`.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 95 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm2mIVD0NpjGIqRXJ-:-MJm2mIWAg3cBuDRYaDn:br5gqt2) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L95)):*
> ```cpp
>     return error;
>   } else {
>     credential_source.url = std::string(url);
> ```

No need to explicitly convert to `std::string` here; that will happen automatically.

Same thing throughout.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 99 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm6i0K9Newqt-RBe3D:-MJm6i0K9Newqt-RBe3E:bu09m5k) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L99)):*
> ```cpp
>   auto it = json.object_value().find("headers");
>   if (it != json.object_value().end()) {
>     if (it->second.type() != grpc_core::Json::Type::OBJECT) {
> ```

No need for `grpc_core::` anywhere in this file, since we're already in that namespace.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 113 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm3oqS5omg0jXKVwS0:-MJm3oqS5omg0jXKVwS1:bm4597f) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L113)):*
> ```cpp
>           "The JSON value of credential source format is not an object.");
>     }
>     const char* type = grpc_json_get_string_property(it->second, "type", &error);
> ```

Please do not use `grpc_json_get_string_property()`.  This is legacy code that needlessly allocates a C-style string, which is inefficient here -- we would basically be converting a C++ string to a C string and then back to a C++ string.  Also, this requires you to free the C string, which you're not doing here, so this causes a memory leak.

Instead, just interact with the Json object directly:

```
const Json& format_json = it->second;
auto format_it = format_json.object_value().find("type");
if (format_it == format_json.object_value().end()) {
  return GRPC_ERROR_CREATE_FROM_STATIC_STRING(
      "format.type field not present");
}
if (format_it->second.type() != Json::Type::STRING) {
  return GRPC_ERROR_CREATE_FROM_STATIC_STRING(
      "format.type field must be a string");
}
credential_source.format.type = format_it->second [...]

2020-10-17 10:35 UTC, renkelvin reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411)* status: all files reviewed, 18 unresolved discussions (waiting on @jiangtaoli2016 and @markdroth)

___
*[src/core/lib/security/credentials/external/url_external_account_credentials.h, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm-wRp1kSmMxXJILTK:-MJpZmDX-2cC0wdvSue-:b-l8zj4u) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.h#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can actually be `private`, since IIUC this class is not going to have any subclasses.
</blockquote></details>

Done. Yeah, you're right. Added `final` to the class definition as well.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.h, line 44 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm0BW_10thN0RHI1Yj:-MJpabyt1LEHZlIhpzD-:b8ko6bq) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.h#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why put this fields in a nested struct?  Why not just make them top-level fields?
</blockquote></details>

It's defined this way to match the format of the credentials file that user provides.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 28 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm0WGa6T92Oa4dJGpI:-MJpb0V260TGXuUiG03s:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `std::move()` for both of these parameters.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm0nye6j44O8u1rK-e:-MJpnnIy0ygWpe7vFVS4:b-1difc3) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L41)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why are we removing the const-ness here?  If we actually need to modify the context in subclasses, why is the API such that it's passed down as a const pointer to begin with?
</blockquote></details>

Done. Yeah, we actually need to modify the context in subclasses. Modify the related definitions.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm11QeBHbXMYtUW7HR:-MJq-EaI6QGv-0EgAIb-:b4uqal8) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This parsing should really be done at the time the credentials are created rather than doing it when a request is actually started, for two reasons.  First, it's better for users for the error to be caught earlier.  And second, there will be many requests over the lifetime of an application process, and it's inefficient to redo this parsing each time a request starts.

I suggest moving this parsing to the ctor and providing a way for the ctor to indicate failure back to the caller.
</blockquote></details>

It seems a better way is to have a factory function so that a `nullptr` can be returned when constructing failed. Moved parsing method to the factory function.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm1yKY2kq0Vl_qYUAM:-MJq0rpM7dVl2iDKfuVZ:b-2ovnvg) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can also be done once in the ctor.  It does not need to be done for each request.
</blockquote></details>

Done. Made `url` of `CredentialSource` a type of `grpc_uri` and pass it in the factory function.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 69 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm2JuoE9x8ZFVCgAft:-MJpb2uu96rUAHn455iu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L69)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Prefer preincrement to postincrement syntax, as per the style guide.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 89 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm2gOPDGNicR4T7LDE:-MJpbDiv-yewR2BRDrhR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L89)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `=  {}`.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 95 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm2mIVD0NpjGIqRXJ-:-MJpbXaq6u3ABB5IlRwB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L95)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to explicitly convert to `std::string` here; that will happen automatically.

Same thing throughout.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 99 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm6i0K9Newqt-RBe3D:-MJpbgDh51o-8LGPdTMG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L99)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `grpc_core::` anywhere in this file, since we're already in that namespace.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 113 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm3oqS5omg0jXKVwS0:-MJpkH2s5C_qbt0SOKbD:bjuiqk9) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L113)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please do not use `grpc_json_get_string_property()`.  This is legacy code that needlessly allocates a C-style string, which is inefficient here -- we would basically be converting a C++ string to a C string and then back to a C++ string.  Also, this requires you to free the C string, which you're not doing here, so this causes a memory leak.

Instead, just interact with the Json object directly:

```
const Json& format_json = it->second;
auto format_it = format_json.object_value().find("type");
if (format_it == format_json.object_value().end()) {
  return GRPC_ERROR_CREATE_FROM_STATIC_STRING(
      "format.type field not present");
}
if (format_it->second.type( [...]

2020-10-19 16:08 UTC, markdroth requested changes
Please make sure to run credential_test under ASAN to detect memory leaks.  I think you've got quite a few of them.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411#-:-MK0bBa-EnMmkBR65xLV:b-jw8keh)* status: all files reviewed, 11 unresolved discussions (waiting on @jiangtaoli2016 and @renkelvin)

___
*[src/core/lib/security/credentials/external/url_external_account_credentials.h, line 44 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm0BW_10thN0RHI1Yj:-MK0XMY8Afwxdppt2_t5:bl74qak) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.h#L44)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

It's defined this way to match the format of the credentials file that user provides.
</blockquote></details>

Why is that important?  This is an internal implementation detail, not something that's exposed to the user.  If we know that we are only going to have one instance of these two fields, I don't see the value in putting them in a nested struct.  It seems like this just makes the data structure harder to understand.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.h, line 28 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0X56qExrAROm9n72M:-MK0X56r1zqA62UZ1l9H:b-yia1mj) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.h#L28)):*
> ```objc
> class UrlExternalAccountCredentials final : public ExternalAccountCredentials {
>  public:
>   static UrlExternalAccountCredentials* Create(
> ```

The return type should be a `RefCountedPtr<>` instead of a raw pointer.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.h, line 43 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0Xe5pACO4YGD1ibmH:-MK0Xe5pACO4YGD1ibmI:b-o6wzko) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.h#L43)):*
> ```objc
>   // credential source. It will be parsed and stored when RetrieveSubjectToken()
>   // starts.
>   struct CredentialSource {
> ```

Since this struct now has exactly the same lifetime as the `UrlExternalAccountCredentials` class, there's not really any benefit in making this a separate struct.  I suggest just moving the data members right into the surrounding class.

(If you do keep this struct for some reason, it should be moved up to the top of the `private` section, as per the style guide.)
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 113 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm3oqS5omg0jXKVwS0:-MK0_3qg019eLC9wKSZK:blw3oge) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L113)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done. Do you think it's worth making a helper function?
</blockquote></details>

I wouldn't worry about it.  It's not enough code to matter.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 22 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0_fpVCFJGcNtKH95h:-MK0_fpVCFJGcNtKH95i:b-mvvx3v) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L22)):*
> ```cpp
> #include "absl/strings/str_format.h"
> 
> #include "src/core/lib/security/util/json_util.h"
> ```

I believe this is no longer needed.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 30 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0XsaH7jsAd8cyCRQl:-MK0XsaH7jsAd8cyCRQm:bnltzhr) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L30)):*
> ```cpp
>     std::vector<std::string> scopes) {
>   UrlExternalAccountCredentials* creds =
>       new UrlExternalAccountCredentials(options, scopes);
> ```

This should use `MakeRefCounted()`.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 30 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0ZOznDJepeaJywlVz:-MK0ZOznDJepeaJywlW-:b-96o1lb) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L30)):*
> ```cpp
>     std::vector<std::string> scopes) {
>   UrlExternalAccountCredentials* creds =
>       new UrlExternalAccountCredentials(options, scopes);
> ```

Please use `std::move()` for these parameters.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 31 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0YaQTEYQ7pQW-yFCe:-MK0YaQTEYQ7pQW-yFCf:buvd79n) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L31)):*
> ```cpp
>   UrlExternalAccountCredentials* creds =
>       new UrlExternalAccountCredentials(options, scopes);
>   if (creds->ParseCredentialSource(options.credential_source) ==
> ```

If the result is not `GRPC_ERROR_NONE`, we need to pass the error back to the caller.  I suggest adding a `grpc_error**` parameter to the factory function and setting the error to the result of this function.  (Currently, we're not passing it back but also not unreffing it, so it's a leak.)

I don't think `ParseCredentialSource()` should be a separate method.  Its functionality should be in the ctor,  and the ctor can take the same `grpc_error**` argument to indicate errors.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 116 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0_NWt6CUQec2kqXEw:-MK0_NWt6CUQec2kqXEx:b-8x1hj8) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L116)):*
> ```cpp
>           "The JSON value of credential source format is not an object.");
>     }
>     const Json& format_json = it->second;
> ```

You can move this line up above the preceding `if` block, so that line 112 can use `format_json` instead of `it->second`.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 158 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0aLKV733G9pSOMeab:-MK0aLKV733G9pSOMeac:b-ovf88z) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L158)):*
> ```cpp
>     return;
>   }
>   std::string response_body(ctx_->response.body, ctx_->response.body_length);
> ```

This can be an `absl::string_view` so that we're not needlessly allocating a copy of the string.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 161 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0a7RP4M2Qj4A8-Nk8:-MK0a7RP4M2Qj4A8-Nk9:bthfhkc) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L161)):*
> ```cpp
>   if (credential_source_.format.type == "json") {
>     grpc_error* error = GRPC_ERROR_NONE;
>     Json response_json = Json::Parse(response_body, &error);
> ```

If `error` is set after this, you should call `FinishRetriveSubjectToken()` immediately.
___
*[test/core/security/credentials_test.cc, line 22 [...]

2020-10-19 19:43 UTC, renkelvin reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411)* status: all files reviewed, 11 unresolved discussions (waiting on @jiangtaoli2016 and @markdroth)

___
*[src/core/lib/security/credentials/external/url_external_account_credentials.h, line 44 at r1](https://reviewable.io/reviews/grpc/grpc/24411#-MJm0BW_10thN0RHI1Yj:-MK11ARoBhpQnLZ2GHQK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f07eac818fc9a806909082778d559a9c9abcffca/src/core/lib/security/credentials/external/url_external_account_credentials.h#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is that important?  This is an internal implementation detail, not something that's exposed to the user.  If we know that we are only going to have one instance of these two fields, I don't see the value in putting them in a nested struct.  It seems like this just makes the data structure harder to understand.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.h, line 28 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0X56qExrAROm9n72M:-MK1AHwg0qg0r4zslzwD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.h#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The return type should be a `RefCountedPtr<>` instead of a raw pointer.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.h, line 43 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0Xe5pACO4YGD1ibmH:-MK11AeOAJk2jHmjIbLh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.h#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since this struct now has exactly the same lifetime as the `UrlExternalAccountCredentials` class, there's not really any benefit in making this a separate struct.  I suggest just moving the data members right into the surrounding class.

(If you do keep this struct for some reason, it should be moved up to the top of the `private` section, as per the style guide.)
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 22 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0_fpVCFJGcNtKH95h:-MK11EE99NXV9XHtFeCF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L22)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I believe this is no longer needed.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 30 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0ZOznDJepeaJywlVz:-MK18M5L6g0icZ7VPwbN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `std::move()` for these parameters.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 30 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0XsaH7jsAd8cyCRQl:-MK1AEXPDuAv27PsWSvv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should use `MakeRefCounted()`.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 31 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0YaQTEYQ7pQW-yFCe:-MK1AFuZDBmuKd7yYxfB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L31)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If the result is not `GRPC_ERROR_NONE`, we need to pass the error back to the caller.  I suggest adding a `grpc_error**` parameter to the factory function and setting the error to the result of this function.  (Currently, we're not passing it back but also not unreffing it, so it's a leak.)

I don't think `ParseCredentialSource()` should be a separate method.  Its functionality should be in the ctor,  and the ctor can take the same `grpc_error**` argument to indicate errors.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 116 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0_NWt6CUQec2kqXEw:-MK16LSY1IH_AL5x_NtL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L116)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can move this line up above the preceding `if` block, so that line 112 can use `format_json` instead of `it->second`.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 158 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0aLKV733G9pSOMeab:-MK16eVf93pAggxGX9XU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L158)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be an `absl::string_view` so that we're not needlessly allocating a copy of the string.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 161 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0a7RP4M2Qj4A8-Nk8:-MK17qxN4ZfLeeg2WJZ1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L161)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If `error` is set after this, you should call `FinishRetriveSubjectToken()` immediately.
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2252 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0b3EU-RIYb8MgbTpw:-MK1Egh_68Ki3NdW9VWW:by92a49) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/test/core/security/credentials_test.cc#L2252)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You're allocating a new creds object but not freeing it anywhere.  This is a leak.

Same thing throughout.
</blockquote></details>

The type of `creds` is now `RefCountedPtr<UrlExternalAccountCredentials>`.

I'm a bit surprised that there is no memory leak without calling `creds.reset()` in the end. Is the ref count of `RefCountedPtr` automatically managed or I misunderstand something? Would mind providing me some general information of how to manage the memory of a `RefCountedPtr`? Thanks!


<!-- Sent from Reviewable.io -->

2020-10-19 20:36 UTC, markdroth requested changes
Only one minor comment remaining!  Once you've resolved that, please squash your commits, and I'll trigger the tests.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411#-:-MK1ZoklCZnUjtbv3s4m:b-1p71qb)* status: all files reviewed, 1 unresolved discussion (waiting on @jiangtaoli2016 and @renkelvin)

___
*[test/core/security/credentials_test.cc, line 2252 at r2](https://reviewable.io/reviews/grpc/grpc/24411#-MK0b3EU-RIYb8MgbTpw:-MK1Ygfs4zKel3AkRGIL:b4djem1) ([raw file](https://github.com/grpc/grpc/blob/8fea5e9148c54de3ba15a2e21b209496d294ba56/test/core/security/credentials_test.cc#L2252)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

The type of `creds` is now `RefCountedPtr<UrlExternalAccountCredentials>`.

I'm a bit surprised that there is no memory leak without calling `creds.reset()` in the end. Is the ref count of `RefCountedPtr` automatically managed or I misunderstand something? Would mind providing me some general information of how to manage the memory of a `RefCountedPtr`? Thanks!
</blockquote></details>

The whole point of `RefCountedPtr<>` is that it automatically releases the ref when it goes out of scope, so you don't need to explicitly reset it.

This looks fine now.
___
*[test/core/security/credentials_test.cc, line 2325 at r3](https://reviewable.io/reviews/grpc/grpc/24411#-MK1Z7sVBYHjwn9zvhjy:-MK1Z7sVBYHjwn9zvhjz:b-94n3ta) ([raw file](https://github.com/grpc/grpc/blob/f7f97e1daf93ab772e9098f45f7a7a5d3946c4a8/test/core/security/credentials_test.cc#L2325)):*
> ```cpp
>       grpc_core::UrlExternalAccountCredentials::Create(options, {}, &error);
>   GPR_ASSERT(creds == nullptr);
>   grpc_error* expected_error =
> ```

There's no need to create an expected error, since all you care about here is the description slice, which you can create directly:

```
grpc_slice expected_error_slice =
    grpc_slice_from_static_string("Invalid credential source url.");
```


<!-- Sent from Reviewable.io -->

2020-10-19 21:06 UTC, renkelvin reviewed
Remaining issue fixed and commits squashed. Let's see what the tests show. Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411#-:-MK1f9Wu1lWlcPh6PB1K:b-wjp55o)* status: all files reviewed, 1 unresolved discussion (waiting on @jiangtaoli2016 and @markdroth)

___
*[test/core/security/credentials_test.cc, line 2325 at r3](https://reviewable.io/reviews/grpc/grpc/24411#-MK1Z7sVBYHjwn9zvhjy:-MK1drciALeUdjJ3f1Ml:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f7f97e1daf93ab772e9098f45f7a7a5d3946c4a8/test/core/security/credentials_test.cc#L2325)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need to create an expected error, since all you care about here is the description slice, which you can create directly:

```
grpc_slice expected_error_slice =
    grpc_slice_from_static_string("Invalid credential source url.");
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-19 21:34 UTC, markdroth requested changes
You broke the test when you made that change.  Please try again.  Once that's done, I'll trigger the tests.

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411#-:-MK1m8t77QG3i11JMuQz:ba1468k)* status: all files reviewed, 1 unresolved discussion (waiting on @jiangtaoli2016 and @renkelvin)

___
*[test/core/security/credentials_test.cc, line 2325 at r3](https://reviewable.io/reviews/grpc/grpc/24411#-MK1Z7sVBYHjwn9zvhjy:-MK1lUMY3Te0v1sY_1f7:bvx1771) ([raw file](https://github.com/grpc/grpc/blob/f7f97e1daf93ab772e9098f45f7a7a5d3946c4a8/test/core/security/credentials_test.cc#L2325)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You removed the wrong code here.  Now you're not actually checking the expected error against the actual error.

The code here should be:

```
grpc_slice expected_error_slice =
    grpc_slice_from_static_string("Invalid credential source url.");
grpc_slice actual_error_slice;
GPR_ASSERT(
    grpc_error_get_str(error, GRPC_ERROR_STR_DESCRIPTION, &actual_error_slice));
GPR_ASSERT(grpc_slice_cmp(expected_error_slice, error_slice) == 0);
GRPC_ERROR_UNREF(error);
```


<!-- Sent from Reviewable.io -->

2020-10-19 22:00 UTC, renkelvin reviewed
Fixed it. I misunderstood it somehow. Confirmed the all tests passed locally.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411#-:-MK1rmgh-NQ9WUJAGtjO:bdnbwxo)* status: all files reviewed, 1 unresolved discussion (waiting on @jiangtaoli2016 and @markdroth)



<!-- Sent from Reviewable.io -->

2020-10-19 22:19 UTC, markdroth approved these changes
The code looks good now!

It looks like you have a merge conflict.  Please merge from master and re-squash commits.

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411#-:-MK1wJkf8hYelWvgEdqV:b-xr7iht)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiangtaoli2016)



<!-- Sent from Reviewable.io -->

2020-10-19 22:30 UTC, renkelvin reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411#-:-MK1z5nEAbaNaeECKM3O:b-896fix)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiangtaoli2016)



<!-- Sent from Reviewable.io -->

2020-10-19 22:43 UTC, markdroth commented
I've triggered the tests.  Let's see how they look.

2020-10-20 08:22 UTC, renkelvin reviewed
The CI catches an issue that the `RetrieveSubjectToken()` method of `TestExternalAccountCredentials` lacks the `override` notation. I just fixed it and I think the CI would be green now.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24411#-:-MK431FcErVeEJJ0hkrB:bpkxr5m)* status: 3 of 19 files reviewed, all discussions resolved (waiting on @jiangtaoli2016 and @markdroth)



<!-- Sent from Reviewable.io -->

2020-10-20 17:44 UTC, markdroth commented
I've triggered the tests again.

2020-10-20 21:01 UTC, renkelvin commented
OK, there is another issue saying the macro format of the header file is wrong, which was not raised in the previous try. Just fixed it.

I wonder if there is a way to run the sanity checks locally? or any other recommended local checks before triggering the CI? Thanks a lot for your help!

2020-10-20 21:04 UTC, markdroth commented
You can try running some of the individual sanity checks in tools/run_tests/sanity, but some of them may require additional dependencies to be installed locally.

I've triggered the tests again.

2020-10-21 15:21 UTC, renkelvin commented
The failure of CI seems like tooling issues to me. Can wen rerun those tests specifically?

2020-10-21 15:48 UTC, markdroth commented
The failures are all infrastructure timeouts or failures fetching external dependencies.  I think it's fine to ignore those.

I'll merge this now.

2020-10-21 15:48 UTC, merged

2020-10-21 16:44 UTC, renkelvin commented
Great, thanks!