Add an API to get Timestamp of a File with stat(2) in gpr
grpc/grpc pull request #24431
Opened 2020-10-15 20:20 UTC by ZhenLian

2020-10-16 16:04 UTC, markdroth reviewed
This looks like a good start!

Please let me know if you have any questions.  Thanks!

2020-10-16 16:04 UTC, markdroth commented on src/core/lib/gpr/stat.h
> + * the epoch time(int value 0) will be returned. */
That doesn't seem like a good API for returning the error.  What if a file actually has the epoch as its timestamp?

I suggest making this a C++ API in the ../gprpp directory.  Then we can do something like this:

```
absl::Status GetFileModifyTimestamp(absl::string_view filename, time_t* timestamp);
```

(Ideally, we would use `absl::StatusOr<>` here, but I don't think we can use that yet.)

2020-10-16 16:04 UTC, markdroth commented on test/core/iomgr/load_file_test.cc
> +  time_t ts = gpr_last_modified_timestamp(tmp_name);
The timestamp tests should be in their own file, since they're testing a separate module.

2020-10-19 17:03 UTC, markdroth requested changes
Comments are mostly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 20 files at r1, 23 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24431#-:-MK0o1p65sjpqCpKH5Kw:b-slgirn)* status: all files reviewed, 13 unresolved discussions (waiting on @jiangtaoli2016 and @ZhenLian)

___
*[test/core/gprpp/stat_test.cc, line 20 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0m-IA62xNDUu6XZVH:-MK0m-IA62xNDUu6XZVI:byzbjut) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/test/core/gprpp/stat_test.cc#L20)):*
> ```cpp
> #include <string.h>
> 
> #include <gmock/gmock.h>
> ```

The gmock and gtest includes should be in their own block, right before this one.
___
*[test/core/gprpp/stat_test.cc, line 42 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0mYka9X0uowg1yh5z:-MK0mYka9X0uowg1yh6-:b8xlmcx) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/test/core/gprpp/stat_test.cc#L42)):*
> ```cpp
>   char* tmp_name;
>   tmp = gpr_tmpfile("prefix", &tmp_name);
>   GPR_ASSERT(tmp_name != nullptr);
> ```

Please do not use `GPR_ASSERT()` in gtest tests.  Instead, use the appropriate `EXPECT_*()` or `ASSERT_*()` macro, because that way a test failure will not prevent subsequent tests from running.

Note that the difference between `EXPECT_*()` and `ASSERT_*()` is that the latter causes the individual test case to return, so any subsequent checks in the test case will be skipped.  In general, `EXPECT_*()` is preferred over `ASSERT_*()`, but there are some cases where `ASSERT_*()` makes sense (e.g., if continuing would cause the test binary to crash).

Same thing throughout.
___
*[test/core/gprpp/stat_test.cc, line 51 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0mT6fEyCmJcLJTMjr:-MK0mT6fEyCmJcLJTMjs:b3597jr) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/test/core/gprpp/stat_test.cc#L51)):*
> ```cpp
>   GPR_ASSERT(timestamp > 0);
>   const char* timestamp_str = ctime(&timestamp);
>   GPR_ASSERT(strlen(timestamp_str) > 0);
> ```

What's the value of this check?  When would this fail?
___
*[test/core/gprpp/stat_test.cc, line 58 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0nNh93q_VEKhOaXYb:-MK0nNh93q_VEKhOaXYc:bdrwk8t) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/test/core/gprpp/stat_test.cc#L58)):*
> ```cpp
> 
> TEST(STAT, GetTimestampOnFailure) {
>   // Create a temporary empty file and then remove it right away.
> ```

I don't see what you gain by creating the file and then destroying it.  Once you delete it, any other process could still come along and recreate it by the time you stat it.

It's probably fine to just use something like "/DOES_NOT_EXIST" here.  We can't absolutely guarantee that it won't exist, but the odds are high, and creating the file first doesn't actually increase those odds at all.
___
*[src/core/lib/gprpp/stat.h, line 1 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0gY0v6UzCWAChHHoz:-MK0gY0w5-gEeSYLfvnb:bk4ey47) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat.h#L1)):*
> ```objc
> /*
> ```

Please use C++-style comments.
___
*[src/core/lib/gprpp/stat.h, line 34 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0gkFqA5pGPs7jy4X-:-MK0gkFqA5pGPs7jy4X0:b84c6ui) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat.h#L34)):*
> ```objc
> // returned. Otherwise, timestamp will be untouched and an
> // StatusCode::kCancelled will be returned.
> absl::Status gpr_last_modified_timestamp(const char* filename,
> ```

Please put this function in the `grpc_core` namespace and call it something like `GetFileModificationTime()`.
___
*[src/core/lib/gprpp/stat_posix.cc, line 37 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0hUwg6CwORkNWpdEF:-MK0hUwg6CwORkNWpdEG:bg01z2) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_posix.cc#L37)):*
> ```cpp
>   if (stat(filename, &buf) != 0) {
>     const char* error_msg = strerror(errno);
>     gpr_log(GPR_ERROR, "_stat failed for filename %s with error %s.", filename,
> ```

s/_stat/stat/
___
*[src/core/lib/gprpp/stat_posix.cc, line 39 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0hbNVAhlgM7iHSDUM:-MK0hbNW9IgkKxgPfuoO:btc2d84) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_posix.cc#L39)):*
> ```cpp
>     gpr_log(GPR_ERROR, "_stat failed for filename %s with error %s.", filename,
>             error_msg);
>     return absl::Status(absl::StatusCode::kCancelled,
> ```

I think `kCancelled` is the wrong code to return here, because the operation is not being cancelled; it's failing.

In principle, we should really choose the code based on the value of `errno`.  However, in practice, whatever status code we return here is ultimately going to wind up being used as the status code for RPCs, which means that we need to adhere to the guidelines in https://github.com/grpc/grpc/blob/master/doc/statuscodes.md (especially those around what codes are not allowed to be generated by gRPC itself).

Given that, I think we should just use `kInternal` here.
___
*[src/core/lib/gprpp/stat_posix.cc, line 40 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0lL1l6VDRTTFG7Cpa:-MK0lL1m0Q663i7B62_N:b-55zjzc) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_posix.cc#L40)):*
> ```cpp
>             error_msg);
>     return absl::Status(absl::StatusCode::kCancelled,
>                         absl::string_view(error_msg));
> ```

No need to explicitly convert to `string_view` here.  That should happen automatically.
___
*[src/core/lib/gprpp/stat_posix.cc, line 44 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0lVl10VYq6pLQIC1l:-MK0lVl10VYq6pLQIC1m:b-g4uhwz) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_posix.cc#L44)):*
> ```cpp
>   // Last file/directory modification time.
>   *timestamp = buf.st_mtime;
>   return absl::Status(absl::StatusCode::kOk, "");
> ```

Can just use `absl::OkStatus()` here.
___
*[src/core/lib/gprpp/stat_windows.cc, line 38 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0lkD95mM8l9emw2kQ:-MK0lkD95mM8l9emw2kR:bpvj3mz) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_windows.cc#L38)):*
> ```cpp
>     gpr_log(GPR_ERROR, "_stat failed for filename %s with error %s.", filename,
>             error_msg);
>     return absl::Status(absl::StatusCode::kCancelled,
> ```

As per my comment elsewhere, let's use `kInternal` here.
___
*[src/core/lib/gprpp/stat_windows.cc, line 39 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0lo3k6mW4lRkk65ma:-MK0lo3l0JBwkAqLT7HF:bhu0o6n) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_windows.cc#L39)):*
> ```cpp
>             error_msg);
>     return absl::Status(absl::StatusCode::kCancelled,
>                         absl::string_view(error_msg));
> ```

No need to explicitly convert to `string_view`.
___
*[src/core/lib/gprpp/stat_windows.cc, line 43 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0lq1v4AThuBV7v1bN:-MK0lq1v4AThuBV7v1bO:bco68uh) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_windows.cc#L43)):*
> ```cpp
>   // Last file/directory modification time.
>   *timestamp = buf.st_mtime;
>   return absl::Status(absl::StatusCode::kOk, "");
> ```

Can use `absl::OkStatus()`.


<!-- Sent from Reviewable.io -->

2020-10-22 04:11 UTC, ZhenLian reviewed
Thanks for the review! I've addressed them all. Please take a look, thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24431#-:-MKDV4u10BJBkUbn2Aia:b1bmds3)* status: all files reviewed, 13 unresolved discussions (waiting on @jiangtaoli2016 and @markdroth)

___
*[test/core/gprpp/stat_test.cc, line 20 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0m-IA62xNDUu6XZVH:-MKCJ3A-8pn6RjCvDe6Z:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/test/core/gprpp/stat_test.cc#L20)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The gmock and gtest includes should be in their own block, right before this one.
</blockquote></details>

Done.
___
*[test/core/gprpp/stat_test.cc, line 42 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0mYka9X0uowg1yh5z:-MKCLMM-8lqUsMucZ3Pk:b-x25ar8) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/test/core/gprpp/stat_test.cc#L42)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please do not use `GPR_ASSERT()` in gtest tests.  Instead, use the appropriate `EXPECT_*()` or `ASSERT_*()` macro, because that way a test failure will not prevent subsequent tests from running.

Note that the difference between `EXPECT_*()` and `ASSERT_*()` is that the latter causes the individual test case to return, so any subsequent checks in the test case will be skipped.  In general, `EXPECT_*()` is preferred over `ASSERT_*()`, but there are some cases where `ASSERT_*()` makes sense (e.g., if continuing would cause the test binary to crash).

Same thing throughout.
</blockquote></details>

Thanks for the explanation! Done.
___
*[test/core/gprpp/stat_test.cc, line 51 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0mT6fEyCmJcLJTMjr:-MKCLQJW3n7DpQoS2S36:buw3ppd) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/test/core/gprpp/stat_test.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What's the value of this check?  When would this fail?
</blockquote></details>

Yeah no need to do this check. I will just remove it. 
___
*[test/core/gprpp/stat_test.cc, line 58 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0nNh93q_VEKhOaXYb:-MKCMAlwDwCHT-OKlD18:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/test/core/gprpp/stat_test.cc#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see what you gain by creating the file and then destroying it.  Once you delete it, any other process could still come along and recreate it by the time you stat it.

It's probably fine to just use something like "/DOES_NOT_EXIST" here.  We can't absolutely guarantee that it won't exist, but the odds are high, and creating the file first doesn't actually increase those odds at all.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/stat.h, line 1 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0gY0v6UzCWAChHHoz:-MKCE9_P9f9UOGBG7PMr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat.h#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style comments.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/stat.h, line 34 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0gkFqA5pGPs7jy4X-:-MKCFyE43gEQ_0ECZ1PA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat.h#L34)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please put this function in the `grpc_core` namespace and call it something like `GetFileModificationTime()`.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/stat_posix.cc, line 37 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0hUwg6CwORkNWpdEF:-MKCGYBb8NgN4WMmKo6_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_posix.cc#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/_stat/stat/
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/stat_posix.cc, line 39 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0hbNVAhlgM7iHSDUM:-MKCHYig8yY33JatIqAy:bt7x92g) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_posix.cc#L39)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think `kCancelled` is the wrong code to return here, because the operation is not being cancelled; it's failing.

In principle, we should really choose the code based on the value of `errno`.  However, in practice, whatever status code we return here is ultimately going to wind up being used as the status code for RPCs, which means that we need to adhere to the guidelines in https://github.com/grpc/grpc/blob/master/doc/statuscodes.md (especially those around what codes are not allowed to be generated by gRPC itself).

Given that, I think we should just use `kInternal` here.
</blockquote></details>

SG. The status code guideline is very useful!
___
*[src/core/lib/gprpp/stat_posix.cc, line 40 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0lL1l6VDRTTFG7Cpa:-MKCIBHqA7CynNncu3ql:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_posix.cc#L40)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to explicitly convert to `string_view` here.  That should happen automatically.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/stat_posix.cc, line 44 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0lVl10VYq6pLQIC1l:-MKCIXt32OXqG2krIsUZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_posix.cc#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can just use `absl::OkStatus()` here.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/stat_windows.cc, line 38 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0lkD95mM8l9emw2kQ:-MKCIZkY98YH_uz_TkLu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_windows.cc#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per my comment elsewhere, let's use `kInternal` here.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/stat_windows.cc, line 39 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0lo3k6mW4lRkk65ma:-MKCIfXOA6OVkcsfLhj3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_windows.cc#L39)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to explicitly convert to `string_view`.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/stat_windows.cc, line 43 at r2](https://reviewable.io/reviews/grpc/grpc/24431#-MK0lq1v4AThuBV7v1bN:-MKCIlOh3k-M0lObInll:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a02d33836d36ba64544b66054b337b9173afbd0f/src/core/lib/gprpp/stat_windows.cc#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can use `absl::OkStatus()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-22 16:02 UTC, markdroth requested changes
Only a couple of minor nits remaining!

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24431#-:-MKG1vBu7_PPhAYy1Wl2:b-47bcb5)* status: all files reviewed, 2 unresolved discussions (waiting on @jiangtaoli2016 and @ZhenLian)

___
*[test/core/gprpp/stat_test.cc, line 43 at r3](https://reviewable.io/reviews/grpc/grpc/24431#-MKG1H30EbRmU4Uc2mPt:-MKG1H30EbRmU4Uc2mPu:b-9bi97k) ([raw file](https://github.com/grpc/grpc/blob/fca85feb40cfca0dfe49a1267617a63118ecbef3/test/core/gprpp/stat_test.cc#L43)):*
> ```cpp
>   char* tmp_name;
>   tmp = gpr_tmpfile("prefix", &tmp_name);
>   EXPECT_NE(tmp_name, nullptr);
> ```

These two should probably use `ASSERT_NE()` instead of `EXPECT_NE()`, because if either one is null, the test will crash.
___
*[src/core/lib/gprpp/stat.h, line 34 at r3](https://reviewable.io/reviews/grpc/grpc/24431#-MKG1hU47ZgtMdWTIh5j:-MKG1hU47ZgtMdWTIh5k:b-4h2v3g) ([raw file](https://github.com/grpc/grpc/blob/fca85feb40cfca0dfe49a1267617a63118ecbef3/src/core/lib/gprpp/stat.h#L34)):*
> ```objc
> // returned. Otherwise, timestamp will be untouched and an
> // StatusCode::kInternal will be returned.
> absl::Status GetFileLastModificationTime(const char* filename,
> ```

Is the word `Last` really useful in this name?  Are there any filesystems that store a list of all times at which a file was modified?  Usually "file modification time" implicitly means the last time the file was modified.


<!-- Sent from Reviewable.io -->

2020-10-22 18:23 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24431)* status: all files reviewed, 2 unresolved discussions (waiting on @jiangtaoli2016 and @markdroth)

___
*[test/core/gprpp/stat_test.cc, line 43 at r3](https://reviewable.io/reviews/grpc/grpc/24431#-MKG1H30EbRmU4Uc2mPt:-MKGQeTHD6enQscuxVHq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fca85feb40cfca0dfe49a1267617a63118ecbef3/test/core/gprpp/stat_test.cc#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two should probably use `ASSERT_NE()` instead of `EXPECT_NE()`, because if either one is null, the test will crash.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/stat.h, line 34 at r3](https://reviewable.io/reviews/grpc/grpc/24431#-MKG1hU47ZgtMdWTIh5j:-MKGOuNYEg7yl4dpyig8:b-9zdphu) ([raw file](https://github.com/grpc/grpc/blob/fca85feb40cfca0dfe49a1267617a63118ecbef3/src/core/lib/gprpp/stat.h#L34)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is the word `Last` really useful in this name?  Are there any filesystems that store a list of all times at which a file was modified?  Usually "file modification time" implicitly means the last time the file was modified.
</blockquote></details>

Sounds good. I will update the name.


<!-- Sent from Reviewable.io -->

2020-10-22 18:32 UTC, markdroth approved these changes
Looks great!  You can go ahead and squash commits and merge.

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24431#-:-MKG_Iaf00KQ7LwNGu7R:b-guwqhy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiangtaoli2016)



<!-- Sent from Reviewable.io -->

2020-10-29 21:20 UTC, ZhenLian commented
The commits are squashed and all the tests passed. Thanks again for the review! Merging now...

2020-10-29 21:20 UTC, merged