[3PI Support] Add file-sourced external account credentials
grpc/grpc pull request #24526
Opened 2020-10-22 08:01 UTC by renkelvin

### Structure of 3PI Support
The implementation of 3PI support is organized as follows:
1. Base external account credentials class [#24208]
2. Subclasses to base external account credentials
    a. url-sourced credentials [#24411]
     **b. file-sourced credentials [This PR]**
    c. aws-sourced credentials
3. Internal and public apis

### Description of this PR
This PR adds the file external account credentials, which retrieve the subject token from a local file then send it back to the base class.

@markdroth Please take a look and let me know if you have any questions. Thanks!

2020-10-22 18:47 UTC, markdroth requested changes
This looks like a good start.

Please let me know if you have any questions.  Thanks!

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-MKGcozD3jv4bXc8ZF8k:bhatqfr)* status: all files reviewed, 4 unresolved discussions (waiting on @renkelvin)

___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 93 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGawgHA53uCD39pe_k:-MKGawgHA53uCD39pe_l:b-i4pjc6) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L93)):*
> ```cpp
>     HTTPRequestContext* ctx, const ExternalAccountCredentialsOptions& options,
>     std::function<void(std::string, grpc_error*)> cb) {
>   std::ifstream ifs(file_);
> ```

For portability reasons, please use the API here to read the file:

https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/load_file.h
___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGbEAAB1vyxpwCE5BU:-MKGbEAAB1vyxpwCE5BV:b-l9bwis) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L94)):*
> ```cpp
>     std::function<void(std::string, grpc_error*)> cb) {
>   std::ifstream ifs(file_);
>   std::string content((std::istreambuf_iterator<char>(ifs)),
> ```

What happens if the file read fails?
___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGbHJv6Wag_dcfWAlj:-MKGbHJv6Wag_dcfWAlk:b9nexsn) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L94)):*
> ```cpp
>     std::function<void(std::string, grpc_error*)> cb) {
>   std::ifstream ifs(file_);
>   std::string content((std::istreambuf_iterator<char>(ifs)),
> ```

Is the expected use-case that the file may change periodically, or will it be static for the lifetime of the gRPC process?

If it will be static, then we can read the file just once in the ctor, rather than reading it every time the creds are refreshed.

If it will change, then what happens if the application is in the process of modifying the file when this read occurs?  Couldn't that result in failing to read the file or reading an inconsistent version of the file with some changes half-applied?  How will that be handled?
___
*[test/core/security/credentials_test.cc, line 2421 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGchzL71QLoLm2aaF9:-MKGchzL71QLoLm2aaFA:bm34z19) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/test/core/security/credentials_test.cc#L2421)):*
> ```cpp
> }
> 
> static void test_file_external_account_creds_failure_invalid_json_content(
> ```

We also need to test the case where the file read itself fails (e.g., the file does not exist).


<!-- Sent from Reviewable.io -->

2020-10-22 22:17 UTC, renkelvin reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 93 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGawgHA53uCD39pe_k:-MKH7P754ZfWnSmHk-AX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L93)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

For portability reasons, please use the API here to read the file:

https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/load_file.h
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGbEAAB1vyxpwCE5BU:-MKHL2uj5au-gzqgv0pS:brny89) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L94)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What happens if the file read fails?
</blockquote></details>

Done.

It would return an empty string in that case, but no error generated. Using `grpc_load_file`, we are able to pass back the error once file loading fails.
___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGbHJv6Wag_dcfWAlj:-MKHMmcY1c3_JUdOmEL0:bbrqrxa) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L94)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is the expected use-case that the file may change periodically, or will it be static for the lifetime of the gRPC process?

If it will be static, then we can read the file just once in the ctor, rather than reading it every time the creds are refreshed.

If it will change, then what happens if the application is in the process of modifying the file when this read occurs?  Couldn't that result in failing to read the file or reading an inconsistent version of the file with some changes half-applied?  How will that be handled?
</blockquote></details>

There is no restriction that forbids the file being modified, so it should be treated as non-static.

It seems `grpc_load_file()` retrieves the file content as a whole with `fopen(filename, "rb")`. https://github.com/grpc/grpc/blob/ededb8e173c56ff33d8cde41898722b8eb16130a/src/core/lib/iomgr/load_file.cc#L43 I think there shouldn't be the case that the changes are half-applied, no?
___
*[test/core/security/credentials_test.cc, line 2421 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGchzL71QLoLm2aaF9:-MKHEyQGDce8xUT9flE7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/test/core/security/credentials_test.cc#L2421)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We also need to test the case where the file read itself fails (e.g., the file does not exist).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-27 08:23 UTC, renkelvin reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526)* status: 16 of 18 files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGbHJv6Wag_dcfWAlj:-MKd8l2zEc9Am4kw9Vg3:b-ng74a1) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L94)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

There is no restriction that forbids the file being modified, so it should be treated as non-static.

It seems `grpc_load_file()` retrieves the file content as a whole with `fopen(filename, "rb")`. https://github.com/grpc/grpc/blob/ededb8e173c56ff33d8cde41898722b8eb16130a/src/core/lib/iomgr/load_file.cc#L43 I think there shouldn't be the case that the changes are half-applied, no?
</blockquote></details>

Hey Mark, could you let know your thoughts and how you want to proceed? Thanks!


<!-- Sent from Reviewable.io -->

2020-10-27 21:49 UTC, markdroth requested changes
Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-MKg1ImG-paOovQDjcKz:b-3oqitw)* status: all files reviewed, 4 unresolved discussions (waiting on @renkelvin)

___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGbHJv6Wag_dcfWAlj:-MKfwiom2WUts_2ExQa5:b-gwg25x) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L94)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Hey Mark, could you let know your thoughts and how you want to proceed? Thanks!
</blockquote></details>

It depends on how the file is modified.  If the caller opens the file read/write and then writes to it starting at byte 0, we may not get a consistent read of the file contents.  But if the file is modified by writing a new file under a different name, then removing the old file and renaming the new file to the old name, then it should work fine.

I think it's fine to assume that the application will do the latter, but you should probably document that for users.

In the code here, please add a comment indicating that we read the file every time we make a request because it may have changed since the last request.
___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 97 at r2](https://reviewable.io/reviews/grpc/grpc/24526#-MKg-D-IA3i2Glk4rRfT:-MKg-D-J794psPKSxGCY:b-bkiejw) ([raw file](https://github.com/grpc/grpc/blob/2268cc39b9df38ac6052e1158a23383d87214ded/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L97)):*
> ```cpp
>     std::function<void(std::string, grpc_error*)> cb) {
>   grpc_slice content_slice;
>   grpc_error* error = grpc_load_file(file_.c_str(), 1, &content_slice);
> ```

If this doesn't return an error, then you need to call `grpc_slice_unref_internal(content_slice)` before this function returns, or else there will be a memory leak.

Since this particular function returns from multiple points, the best way to do this is to ensure that it happens automatically whenever we return, like this:

```
class SliceWrapper {
  ~SliceWrapper() { grpc_slice_unref_internal(slice); }
  grpc_slice slice = grpc_empty_slice();
};
SliceWrapper content_slice;
```

Now change `content_slice` to `content_slice.slice` in the rest of the function.
___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/24526#-MKfwcie9Sk4JkgNEQoi:-MKfwcif2B0AMEUbIifn:byza3ag) ([raw file](https://github.com/grpc/grpc/blob/2268cc39b9df38ac6052e1158a23383d87214ded/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L103)):*
> ```cpp
>   }
>   std::string content =
>       std::string(reinterpret_cast<char*>(GRPC_SLICE_START_PTR(content_slice)));
> ```

There are several problems here:

-  The file's contents could have a NUL byte in it, in which case this would cause it to be truncated.  You need to use the slice's length instead of assuming NUL termination.
- Instead of saying `std::string content = std::string(...)`, please just say `std::string content(...)`.  This way you're directly allocating the object once instead of allocating two objects and assigning one to the other.
- In this case, there is no need to allocate a new string here in the first place, because that needlessly creates a new copy.  Instead, you should use an `absl::string_view` here.

I think the right thing to do here is to create an `absl::string_view` using [`StringViewFromSlice()`](https://github.com/grpc/grpc/blob/3c17848cee6b052a71b694e207a7419ebb521163/src/core/lib/slice/slice_utils.h#L192), like this:

```
absl::string_view content = StringViewFromSlice(content_slice);
```
___
*[test/core/security/credentials_test.cc, line 2427 at r2](https://reviewable.io/reviews/grpc/grpc/24526#-MKg0dGL8bvr8yo-WyHV:-MKg0dGL8bvr8yo-WyHW:b4wkoct) ([raw file](https://github.com/grpc/grpc/blob/2268cc39b9df38ac6052e1158a23383d87214ded/test/core/security/credentials_test.cc#L2427)):*
> ```cpp
>   grpc_error* error = GRPC_ERROR_NONE;
>   grpc_core::Json credential_source =
>       grpc_core::Json::Parse("{\"file\":\"non_exsiting_file\"}", &error);
> ```

s/exsiting/existing/


<!-- Sent from Reviewable.io -->

2020-10-28 06:06 UTC, renkelvin reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/24526#-MKGbHJv6Wag_dcfWAlj:-MKhnvOd7VeDbUOKb-o3:b-6o94bh) ([raw file](https://github.com/grpc/grpc/blob/8b66a14724468ccc315b5ba307f7529c2a955095/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L94)):*
> I think it's fine to assume that the application will do the latter, but you should probably document that for users.
Added to my list. Will do this once we start writing the public developer docs.

Done.
___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 97 at r2](https://reviewable.io/reviews/grpc/grpc/24526#-MKg-D-IA3i2Glk4rRfT:-MKhk8riAd7X6IYNrzTP:b-comi9y) ([raw file](https://github.com/grpc/grpc/blob/2268cc39b9df38ac6052e1158a23383d87214ded/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L97)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If this doesn't return an error, then you need to call `grpc_slice_unref_internal(content_slice)` before this function returns, or else there will be a memory leak.

Since this particular function returns from multiple points, the best way to do this is to ensure that it happens automatically whenever we return, like this:

```
class SliceWrapper {
  ~SliceWrapper() { grpc_slice_unref_internal(slice); }
  grpc_slice slice = grpc_empty_slice();
};
SliceWrapper content_slice;
```

Now change `content_slice` to `content_slice.slice` in the rest of the function.
</blockquote></details>

Done.

Declared a `struct` instead of `class`.
___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/24526#-MKfwcie9Sk4JkgNEQoi:-MKhloWk22H1_Fr6EjJz:b-hgwtaa) ([raw file](https://github.com/grpc/grpc/blob/2268cc39b9df38ac6052e1158a23383d87214ded/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L103)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There are several problems here:

-  The file's contents could have a NUL byte in it, in which case this would cause it to be truncated.  You need to use the slice's length instead of assuming NUL termination.
- Instead of saying `std::string content = std::string(...)`, please just say `std::string content(...)`.  This way you're directly allocating the object once instead of allocating two objects and assigning one to the other.
- In this case, there is no need to allocate a new string here in the first place, because that needlessly creates a new copy.  Instead, you should use an `absl::string_view` here.

I think the right thing to do here is to create an `absl::string_view` using [`StringViewFromSlice()`](https://github.com/grpc/grpc/blob/3c17848cee6b052a71b694e207a7419ebb521163/src/core/lib/slice/slice_utils.h#L192), like this:

```
absl::string_view content = StringViewFromSlice(content_slice);
```
</blockquote></details>

Done.

Thanks for pointing this out. I'll pay more attention to the string manipulation.
___
*[test/core/security/credentials_test.cc, line 2427 at r2](https://reviewable.io/reviews/grpc/grpc/24526#-MKg0dGL8bvr8yo-WyHV:-MKhgROj0OeDHkb1vrEy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2268cc39b9df38ac6052e1158a23383d87214ded/test/core/security/credentials_test.cc#L2427)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/exsiting/existing/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 14:59 UTC, markdroth requested changes
This looks good, modulo the one cosmetic comment below.  I'll trigger the tests, so we can see if there are any problems.  Once the tests are green, you can squash commits.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-MKjhvE348mq71wk8Ky6:b-ub100k)* status: all files reviewed, 1 unresolved discussion (waiting on @renkelvin)

___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 94 at r3](https://reviewable.io/reviews/grpc/grpc/24526#-MKjhTU98P12X_Stn4ha:-MKjhTU98P12X_Stn4hb:bz68cvf) ([raw file](https://github.com/grpc/grpc/blob/b5f0c630964edc3be44a2b4bb48a5a5eda29b89a/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L94)):*
> ```cpp
> }
> 
> // To retrieve the subject token, we read the file every time we make a request
> ```

Please move this comment into the body of the function.  It's not a comment about the function as a whole; merely about the first part of the code in the function.


<!-- Sent from Reviewable.io -->

2020-10-28 19:44 UTC, renkelvin reviewed
There is a weird issue on Windows to open the temporary test credentials file.

When testing locally (linux), the test file is created at "/tmp/test_sign_jwt_XXXXXX", which works fine.
But according to the testing log on Windows, the temporary test credentials file is read from "T:\tmp\tesC75A.tmp" which results in an "Invalid argument" error.

Do you know if there is anything special we should take care of the file path for Windows? or is it OK to include some static credentials file for testing? Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-MKkelK-5I-N3lGnAOIx:bjerlkc)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[src/core/lib/security/credentials/external/file_external_account_credentials.cc, line 94 at r3](https://reviewable.io/reviews/grpc/grpc/24526#-MKjhTU98P12X_Stn4ha:-MKkeiak6s7jog4tQzU0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b5f0c630964edc3be44a2b4bb48a5a5eda29b89a/src/core/lib/security/credentials/external/file_external_account_credentials.cc#L94)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this comment into the body of the function.  It's not a comment about the function as a whole; merely about the first part of the code in the function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 22:19 UTC, markdroth commented
I don't know what's causing that problem.  @nicolasnoble or @jtattermusch, can one of you please advise?

The failure in question is here: https://source.cloud.google.com/results/invocations/d8c2251c-5127-4e2d-9cdc-9b67f85db8cc/targets/github%2Fgrpc%2Frun_tests%2Fc_windows_dbg_native/tests

2020-10-28 22:20 UTC, markdroth commented
I've triggered the tests again.  Let's see if maybe that was just a flake.

2020-10-30 10:41 UTC, renkelvin reviewed
The issue seems reproducible. I doubt it's because the file path is somehow incorrectly parsed on windows.

I just made some changes to log more information. Could you please trigger the tests again? Hopefully there are some clues. Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-MKt4hLRCsIViERzyTZp:b-btbhwl)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2020-10-30 15:06 UTC, markdroth commented
I re-triggered the tests.

This problem is very strange, because the test is already writing files using the same code, and it's not having any problems with the existing tests.

2020-10-30 21:44 UTC, renkelvin commented
I think I know the cause to the failures now, although the issue is still strange.

On Windows, the file path is returned as `C:\Users\ContainerAdministrator\AppData\Local\Temp\tes2A41.tmp`. The first backslash `\` gets parsed as an escape character, which results in:
1. `OSError: [Errno 22] Invalid argument` for "Basic Tests C Windows".
2. JSON parse error for "Bazel RBE Windows Debug/Opt C/C++".

It was not a problem for the existing tests maybe because the file path was stored directly, while in this case it's stored then retrieved from a JSON object.

I made a fix that changes all backslash to slash in the file path, since Windows accept both of them. Not sure if the fix works but I think it worth a try. Please re-trigger the tests. Thanks!

2020-10-31 01:07 UTC, markdroth commented
Good find!  I've re-triggered the tests.

2020-11-02 11:45 UTC, renkelvin commented
According to the logs, I believe the file path issue on Windows should be fixed now!

The failures of the lastest CI testing are resulted from an incorrect `GRPC_ERROR_UNREF()`. I just fixed it and please trigger the tests again. Hopefully it could be green this time!

2020-11-02 16:25 UTC, markdroth requested changes
I've triggered the tests, but I think there are some additional changes needed in the test code.

Please let me know if you have any questions.

> Reviewed 1 of 1 files at r4, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-ML8lZS_C_82AF8VGeGw:b-3t1jja)* status: all files reviewed, 11 unresolved discussions (waiting on @renkelvin)

___
*[test/core/security/credentials_test.cc, line 996 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8j95DAAA3tVLSR6u4:-ML8j95DAAA3tVLSR6u5:bcisiwr) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L996)):*
> ```cpp
>   GPR_ASSERT(fwrite(jwt_contents, 1, jwt_length, tmp) == jwt_length);
>   fclose(tmp);
>   gpr_log(GPR_ERROR, "[chuanr-DEBUG] write_tmp_jwt_file path: %s", path);
> ```

Please remove the `[chuanr-DEBUG]`.
___
*[test/core/security/credentials_test.cc, line 2344 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8kWa-EFcV1dSNaNIl:-ML8kWa-EFcV1dSNaNIm:bmb4fo7) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2344)):*
> ```cpp
>   char* subject_token_path = write_tmp_jwt_file("test_subject_token");
>   int i = 0;
>   while (subject_token_path[i]) {
> ```

`for (size_t i = 0; i < strlen(subject_token_path); ++i) {`
___
*[test/core/security/credentials_test.cc, line 2345 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8k_KD-ZAhaqCjRDJn:-ML8k_KD-ZAhaqCjRDJo:b-uktr3o) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2345)):*
> ```cpp
>   int i = 0;
>   while (subject_token_path[i]) {
>     if (subject_token_path[i] == '\\') subject_token_path[i] = '/';
> ```

I don't think we want to subtitute a forward slash here.  We just want to escape the backslashes.

I suggest replacing this loop with the following:

```
absl::StrReplaceAll(subject_token_path, {{"\\", "\\\\"}});
```
___
*[test/core/security/credentials_test.cc, line 2350 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8jLqq3R7zahg0mkWP:-ML8jLqq3R7zahg0mkWQ:b-lilu8a) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2350)):*
> ```cpp
>   grpc_core::Json credential_source = grpc_core::Json::Parse(
>       absl::StrFormat("{\"file\":\"%s\"}", subject_token_path), &error);
>   gpr_log(GPR_ERROR,
> ```

Please remove this statement.
___
*[test/core/security/credentials_test.cc, line 2353 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8jNdDC3XQ5bZ8CWDp:-ML8jNdDC3XQ5bZ8CWDq:bcisiwr) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2353)):*
> ```cpp
>           "[chuanr-DEBUG] test_file_format_text subject_token_path: %s",
>           subject_token_path);
>   GRPC_LOG_IF_ERROR("[chuanr-DEBUG] test_file_format_text",
> ```

Please remove the `[chuanr-DEBUG]`.
___
*[test/core/security/credentials_test.cc, line 2394 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lEcJAsxJAMfcoB-V:-ML8lEcJAsxJAMfcoB-W:bwmesx4) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2394)):*
> ```cpp
>       write_tmp_jwt_file("{\"access_token\":\"test_subject_token\"}");
>   int i = 0;
>   while (subject_token_path[i]) {
> ```

Same comments as above.
___
*[test/core/security/credentials_test.cc, line 2409 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lKie8UK76DE9sWAA:-ML8lKie8UK76DE9sWAB:b-lilu8a) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2409)):*
> ```cpp
>                       subject_token_path),
>       &error);
>   gpr_log(GPR_ERROR,
> ```

Please remove this statement.
___
*[test/core/security/credentials_test.cc, line 2412 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lOslDc7X4zURLLRn:-ML8lOslDc7X4zURLLRo:bcisiwr) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2412)):*
> ```cpp
>           "[chuanr-DEBUG] test_file_format_json subject_token_path: %s",
>           subject_token_path);
>   GRPC_LOG_IF_ERROR("[chuanr-DEBUG] test_file_format_json",
> ```

Please remove the `[chuanr-DEBUG]`.
___
*[test/core/security/credentials_test.cc, line 2451 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lQcP-MUDhZAmzfrp:-ML8lQcP-MUDhZAmzfrq:bcisiwr) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2451)):*
> ```cpp
>   grpc_core::Json credential_source =
>       grpc_core::Json::Parse("{\"file\":\"non_exisiting_file\"}", &error);
>   GRPC_LOG_IF_ERROR("[chuanr-DEBUG] test_file_file_not_found",
> ```

Please remove the `[chuanr-DEBUG]`.
___
*[test/core/security/credentials_test.cc, line 2502 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lS812eZ-H6r2dbJ4:-ML8lS812eZ-H6r2dbJ5:b-lilu8a) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2502)):*
> ```cpp
>                       subject_token_path),
>       &error);
>   gpr_log(
> ```

Please remove this statement.
___
*[test/core/security/credentials_test.cc, line 2506 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lTKg3D7kydAMg-x0:-ML8lTKg3D7kydAMg-x1:bcisiwr) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2506)):*
> ```cpp
>       "[chuanr-DEBUG] test_file_invalid_json_content subject_token_path: %s",
>       subject_token_path);
>   GRPC_LOG_IF_ERROR("[chuanr-DEBUG] test_file_invalid_json_content",
> ```

Please remove the `[chuanr-DEBUG]`.


<!-- Sent from Reviewable.io -->

2020-11-02 18:22 UTC, renkelvin reviewed
I'll remove those logs for debugging once the CI turns green. Seems we need trigger the tests one more time. Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-ML9BONrDEbgs7VGqLbN:b-umxyy4)* status: all files reviewed, 11 unresolved discussions (waiting on @markdroth and @renkelvin)

___
*[test/core/security/credentials_test.cc, line 2344 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8kWa-EFcV1dSNaNIl:-ML9ARntBBKON3MROtHc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2344)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`for (size_t i = 0; i < strlen(subject_token_path); ++i) {`
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2345 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8k_KD-ZAhaqCjRDJn:-ML9ASTc5dyDAqAL8_Lz:b-3m39re) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2345)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we want to subtitute a forward slash here.  We just want to escape the backslashes.

I suggest replacing this loop with the following:

```
absl::StrReplaceAll(subject_token_path, {{"\\", "\\\\"}});
```
</blockquote></details>

Done.

BTW, how about adding these changes to this tmp file creating method `write_tmp_jwt_file` https://github.com/grpc/grpc/blob/04045e227359ae23b5b31fb9e7d14e3b79d3e373/test/core/security/credentials_test.cc#L995
So people won't encounter into the same problem later.
___
*[test/core/security/credentials_test.cc, line 2394 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lEcJAsxJAMfcoB-V:-ML9BJtV0T0lKwgckFVI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2394)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same comments as above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-02 19:25 UTC, markdroth requested changes
There's an obvious bug here that needs to be fixed before I re-run the tests.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-ML9PvNr6OxfdnTRigsP:b-761k7n)* status: all files reviewed, 11 unresolved discussions (waiting on @renkelvin)

___
*[test/core/security/credentials_test.cc, line 2345 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8k_KD-ZAhaqCjRDJn:-ML9P0LH5ldaT8NkBgUz:b-ntogdj) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2345)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done.

BTW, how about adding these changes to this tmp file creating method `write_tmp_jwt_file` https://github.com/grpc/grpc/blob/04045e227359ae23b5b31fb9e7d14e3b79d3e373/test/core/security/credentials_test.cc#L995
So people won't encounter into the same problem later.
</blockquote></details>

The way you've modified this code won't work.  `absl::StrReplaceAll()` does not need to be inside of a loop, because it will handle all substitutions in the entire string.  Also, its return value is the new string to use, so you need to actually save that and use it when passing the name to `absl::StrFormat()` below.

I don't think it makes sense to make this change in `write_tmp_jwt_file()`, because there is no guarantee that the resulting filename will be added to a JSON file.
___
*[test/core/security/credentials_test.cc, line 2394 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lEcJAsxJAMfcoB-V:-ML9PjLc1CIuwcrC3Np5:bwrpyx1) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2394)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same problem here as above.
___
*[test/core/security/credentials_test.cc, line 2488 at r8](https://reviewable.io/reviews/grpc/grpc/24526#-ML9PmHW1xw1y5UlQ9_u:-ML9PmHX5Lm_hTolss1U:bwrpyx1) ([raw file](https://github.com/grpc/grpc/blob/3cc13b5ba52c513758612431d17e76fd09bc2b11/test/core/security/credentials_test.cc#L2488)):*
> ```cpp
>   char* subject_token_path = write_tmp_jwt_file("not_a_valid_json_file");
>   for (size_t i = 0; i < strlen(subject_token_path); ++i) {
>     absl::StrReplaceAll(subject_token_path, {{"\\", "\\\\"}});
> ```

Same problem here as above.


<!-- Sent from Reviewable.io -->

2020-11-02 19:53 UTC, renkelvin reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526)* status: all files reviewed, 11 unresolved discussions (waiting on @markdroth and @renkelvin)

___
*[test/core/security/credentials_test.cc, line 2345 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8k_KD-ZAhaqCjRDJn:-ML9W-2H3hghsIhWTGXF:b-3a7sc5) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2345)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The way you've modified this code won't work.  `absl::StrReplaceAll()` does not need to be inside of a loop, because it will handle all substitutions in the entire string.  Also, its return value is the new string to use, so you need to actually save that and use it when passing the name to `absl::StrFormat()` below.

I don't think it makes sense to make this change in `write_tmp_jwt_file()`, because there is no guarantee that the resulting filename will be added to a JSON file.
</blockquote></details>

Done.

Yeah, it's a very obvious bug..
___
*[test/core/security/credentials_test.cc, line 2488 at r8](https://reviewable.io/reviews/grpc/grpc/24526#-ML9PmHW1xw1y5UlQ9_u:-ML9WBYr-K51BOvKfYNl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3cc13b5ba52c513758612431d17e76fd09bc2b11/test/core/security/credentials_test.cc#L2488)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same problem here as above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-02 19:59 UTC, markdroth commented
That looks better.  I've re-triggered the tests.

2020-11-02 21:54 UTC, renkelvin reviewed
It seems the 2 failures of CI are tooling issues. If that's the case I gonna squash the commits.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-ML9wVeFCyi6-fVMHHa7:b-szt06p)* status: 17 of 18 files reviewed, 11 unresolved discussions (waiting on @markdroth)

___
*[test/core/security/credentials_test.cc, line 996 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8j95DAAA3tVLSR6u4:-ML9wK8-2Q3nJF_6sxnD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L996)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove the `[chuanr-DEBUG]`.
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2350 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8jLqq3R7zahg0mkWP:-ML9wMx93fY0wOO89dAh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2350)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove this statement.
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2353 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8jNdDC3XQ5bZ8CWDp:-ML9wNGh2LIyCmpxuoo4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2353)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove the `[chuanr-DEBUG]`.
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2409 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lKie8UK76DE9sWAA:-ML9wOGcE8JvQXW_k5UD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2409)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove this statement.
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2412 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lOslDc7X4zURLLRn:-ML9wOV-9adGMP_DJG3v:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2412)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove the `[chuanr-DEBUG]`.
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2451 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lQcP-MUDhZAmzfrp:-ML9wP6N19B8LuGUCmuN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2451)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove the `[chuanr-DEBUG]`.
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2502 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lS812eZ-H6r2dbJ4:-ML9wPvvCben4u0_5s8O:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2502)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove this statement.
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2506 at r7](https://reviewable.io/reviews/grpc/grpc/24526#-ML8lTKg3D7kydAMg-x0:-ML9wQAQ3qGd5cuj27BP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dd3e373004f51203e8a0d639e39d8d03652cf673/test/core/security/credentials_test.cc#L2506)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove the `[chuanr-DEBUG]`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-02 22:04 UTC, markdroth approved these changes
Yeah, those two failures look unrelated.  Please go ahead and squash your commits, and we'll run the tests one final time.

> Reviewed 1 of 1 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-ML9zFgx36XuEKY3nvk1:bef23op)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-02 22:14 UTC, renkelvin reviewed
Got it. Commits squashed!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24526#-:-MLA0b7cA0dYsEk4yEk7:biyud55)* status: 3 of 18 files reviewed, all discussions resolved (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2020-11-02 22:17 UTC, markdroth commented
I've re-triggered the tests.

2020-11-03 00:37 UTC, renkelvin commented
CI is green now.

2020-11-03 00:44 UTC, merged