Add XdsCertificateProvider
grpc/grpc pull request #24579
Opened 2020-10-27 03:10 UTC by yashykt

This certificate provider combines results from potentially different certificate providers for root and identity certs.

2020-10-27 21:16 UTC, markdroth requested changes
This looks like a good start!

Please let me know if you have any questions.  Thanks!

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24579#-:-MKfunQx7kd4GqOJec5r:bntdxje)* status: all files reviewed, 18 unresolved discussions (waiting on @yashykt)

___
*[BUILD, line 1382 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKeqBa22PE3AD-PlV-D:-MKeqBa22PE3AD-PlV-E:bd9lz1d) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/BUILD#L1382)):*
> ```Starlark
>     name = "grpc_xds_certificate_provider",
>     srcs = [
>         "src/core/ext/xds/xds_certificate_provider.cc",
> ```

I suggest just adding these files to the existing `grpc_xds_credentials` target rather than adding a new one.
___
*[src/core/ext/xds/xds_certificate_provider.h, line 28 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfNUFc-FiN4hLDsxAr:-MKfNUFc-FiN4hLDsxAs:b-fremcd) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.h#L28)):*
> ```objc
> namespace grpc_core {
> 
> class XdsCertificateProvider : public grpc_tls_certificate_provider {
> ```

I don't think this actually needs to implement the `grpc_tls_certificate_provider` API.  We implemented the TLS security connector such that it can directly take a distributor rather than a provider in the XdsCreds case.

It doesn't actually hurt to use the provider API here, but if we're going to do this, then we can probably eliminate the special-case code that we added to allow using a distributor instead of a provider:

https://github.com/grpc/grpc/blob/76860e48269f975ee7c95fd90e765c8cf0ee4d12/src/core/lib/security/credentials/tls/grpc_tls_credentials_options.h#L119

Instead, we can have `tls_credentials_options` always return a provider, and the TLS security connector can assume that a provider is present.
___
*[src/core/ext/xds/xds_certificate_provider.h, line 31 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVCkZ4cJXixi9BJus:-MKfVCkZ4cJXixi9BJut:b-r7oglb) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.h#L31)):*
> ```objc
>  public:
>   XdsCertificateProvider(
>       RefCountedPtr<grpc_tls_certificate_distributor> root_cert_distributor,
> ```

Whenever we set the root or identity cert distributors (either here in the ctor or via the setter methods below), we also need to set the corresponding certificate name.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 120 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfSTyF1MbS7d8eufr-:-MKfSTyF1MbS7d8eufr0:byv9liv) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L120)):*
> ```cpp
>     }
>     if (root_cert_distributor != nullptr) {
>       root_cert_watcher_ = new RootCertificatesWatcher(distributor());
> ```

Suggest writing this as:

```
auto watcher = absl::make_unique<RootCertificateWatcher>(distributor());
root_cert_watcher_ = watcher.get();
root_cert_distributor->WatchTlsCertificates(
    std::move(watcher), "", absl::nullopt);
```
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 125 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfSPgPAM1oD72tZA51:-MKfSPgPAM1oD72tZA52:b-cqvecp) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L125)):*
> ```cpp
>                               TlsCertificatesWatcherInterface>(
>               root_cert_watcher_),
>           "", absl::nullopt);
> ```

This needs to use the cert name from xDS.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 131 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVsLy4oEPL7HeqycN:-MKfVsLy4oEPL7HeqycO:bgh7nwg) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L131)):*
> ```cpp
>           "",
>           GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>               "No certificate provider available for root certificates"),
> ```

Is this actually an error?  What if we get an xDS update reconfiguring the client from mTLS to TLS?  I guess we'd need to change the channel args in that case, since the options we pass to the TLS security connector will need to be different?
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfV_111uwqe2lsdYTW:-MKfV_111uwqe2lsdYTX:b-eu132l) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L149)):*
> ```cpp
>     }
>     if (identity_cert_distributor != nullptr) {
>       identity_cert_watcher_ = new IdentityCertificatesWatcher(distributor());
> ```

Suggest writing this as:

```
auto watcher = absl::make_unique<IdentityCertificateWatcher>(distributor());
identity_cert_watcher_ = watcher.get();
identity_cert_distributor->WatchTlsCertificates(
    std::move(watcher), absl::nullopt, "");
```
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 154 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVWly8Sy6ORpdyao6:-MKfVWly8Sy6ORpdyao7:b-cqvecp) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L154)):*
> ```cpp
>                               TlsCertificatesWatcherInterface>(
>               identity_cert_watcher_),
>           absl::nullopt, "");
> ```

This needs to use the cert name from xDS.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 160 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfWsjU9ruUALlr6SM4:-MKfWsjU9ruUALlr6SM5:bzc2evn) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L160)):*
> ```cpp
>           "", absl::nullopt,
>           GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>               "No certificate provider available for identity certificates"));
> ```

Same question as on line 131.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 196 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfXCqc-j7cIMtxIRRo:-MKfXCqc-j7cIMtxIRRp:b-lwds84) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L196)):*
> ```cpp
>           absl::nullopt);
>     } else {
>       root_cert_watcher_ = new RootCertificatesWatcher(distributor());
> ```

Same comment as on line 120.

Also, consider refactoring this into a helper method to avoid duplication.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 201 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfY40W4v9ivdJhzMFT:-MKfY40W4v9ivdJhzMFU:b-cqvecp) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L201)):*
> ```cpp
>                               TlsCertificatesWatcherInterface>(
>               root_cert_watcher_),
>           "", absl::nullopt);
> ```

This needs to use the cert name from xDS.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 220 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfXMxb5hWoPCpqnRYt:-MKfXMxb5hWoPCpqnRYu:b-qijcp7) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L220)):*
> ```cpp
>               "No certificate provider available for identity certificates"));
>     } else {
>       identity_cert_watcher_ = new IdentityCertificatesWatcher(distributor());
> ```

Same comment as on line 149.

Also, consider refactoring this into a helper method to avoid duplication.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 225 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfY5S33yxYj1s7QhzN:-MKfY5S33yxYj1s7QhzO:b-cqvecp) ([raw file](https://github.com/grpc/grpc/blob/e63755d [...]

2020-10-27 22:03 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24579)* status: all files reviewed, 18 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_certificate_provider.h, line 28 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfNUFc-FiN4hLDsxAr:-MKfx7WQ1gLLx9qoi7qr:b-j15i06) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.h#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this actually needs to implement the `grpc_tls_certificate_provider` API.  We implemented the TLS security connector such that it can directly take a distributor rather than a provider in the XdsCreds case.

It doesn't actually hurt to use the provider API here, but if we're going to do this, then we can probably eliminate the special-case code that we added to allow using a distributor instead of a provider:

https://github.com/grpc/grpc/blob/76860e48269f975ee7c95fd90e765c8cf0ee4d12/src/core/lib/security/credentials/tls/grpc_tls_credentials_options.h#L119

Instead, we can have `tls_credentials_options` always return a provider, and the TLS security connector can assume that a provider is present.
</blockquote></details>

Yeah, I agree that it doesn't need to implement the `grpc_tls_certificate_provider` API but the API is so lean that there is no downside to using this API.
___
*[src/core/ext/xds/xds_certificate_provider.h, line 31 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVCkZ4cJXixi9BJus:-MKfx-sC68RYzq1pStrz:b7i9wca) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.h#L31)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Whenever we set the root or identity cert distributors (either here in the ctor or via the setter methods below), we also need to set the corresponding certificate name.
</blockquote></details>

We always use a blank name for xds, so I don't really see the benefit
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 125 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfSPgPAM1oD72tZA51:-MKfxO_eCfBLIQcXCuQj:byhev9h) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L125)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to use the cert name from xDS.
</blockquote></details>

We don't really have a cert name from XDS.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 131 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVsLy4oEPL7HeqycN:-MKfxpT5Au8CwJtRiakJ:bfqve01) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L131)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this actually an error?  What if we get an xDS update reconfiguring the client from mTLS to TLS?  I guess we'd need to change the channel args in that case, since the options we pass to the TLS security connector will need to be different?
</blockquote></details>

Yeah, in that case, the TLS security connector needs to be different.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 154 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVWly8Sy6ORpdyao6:-MKfy7Ta7IzwlHvqTl-F:bhxi6gd) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L154)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to use the cert name from xDS.
</blockquote></details>

We don't have a certificate name. We just get an opaque name that we match with the config provided in the bootstrap file.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 160 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfWsjU9ruUALlr6SM4:-MKg2ULz9m-oqpGOsT3e:b3hwena) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L160)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same question as on line 131.
</blockquote></details>

It is an error if the security connector tries to watch over identity certificates if it is not set. If we are switching from mTLS to TLS/fallback, we would need to use a new security connector, and that new security connector would not be watching over these certificates anymore.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 201 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfY40W4v9ivdJhzMFT:-MKg3Rld3kqU-aDZxVP_:b-pw2h86) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L201)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to use the cert name from xDS.
</blockquote></details>

We don't have a cert name from XDS.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 225 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfY5S33yxYj1s7QhzN:-MKg3UTtEEL_RxPECjZy:b-97r5v) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L225)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to use the cert name from xDS.
</blockquote></details>

We don't have a cert name for XDS
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfYUtV1lnu2Kwl3GQ4:-MKg3Ynu3V939us_26UY:bl5i9i1) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this change needed?  Won't this do the right thing anyway if there is no value?
</blockquote></details>

If we don't do this, then in OnCertificatesChanged(), we will need to check if the certificates are empty, and that seems unnecessary if we are already using absl::optional
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 74 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfYXao3M4t0f0LXHr4:-MKg3sAa5JAyqDXI3vBc:bdessah) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L74)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same question here.
</blockquote></details>


If we don't do this, then in OnCertificatesChanged(), we will need to check if the certificates are empty, and that seems unnecessary if we are already using absl::optional
___
*[test/core/xds/xds_certificate_provider_test.cc, line 163 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfpX_y9THz4DOZ7_o3:-MKg4Rs-66U6_atcSSbT:b64u98n) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/test/core/xds/xds_certificate_provider_test.cc#L163)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If the root and identity distributors are different and the root cert gets a new update but the identity cert doesn't, I think we should still record the error for the identity cert.  (And vice-versa.)
</blockquote></details>

I don't understand this. It is possible for the identity certificates to have changed without the root certificates. Why should that be an error?


<!-- Sent from Reviewable.io -->

2020-10-27 22:16 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24579)* status: all files reviewed, 17 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_certificate_provider.h, line 28 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfNUFc-FiN4hLDsxAr:-MKg56oD8YfaI1G5ZUnY:b-yqvviy) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.h#L28)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Yeah, I agree that it doesn't need to implement the `grpc_tls_certificate_provider` API but the API is so lean that there is no downside to using this API.
</blockquote></details>

Okay.  Then let's clean up the TLS code.
___
*[src/core/ext/xds/xds_certificate_provider.h, line 31 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVCkZ4cJXixi9BJus:-MKg5AHvCtXAHrOgRYZX:bwypjz2) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.h#L31)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

We always use a blank name for xds, so I don't really see the benefit
</blockquote></details>

We will get a cert name in the xDS resources.

https://github.com/envoyproxy/envoy/blob/6321e5d95f7e435625d762ea82316b7a9f7071a4/api/envoy/extensions/transport_sockets/tls/v3/tls.proto#L170

We need to use that cert name here.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 125 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfSPgPAM1oD72tZA51:-MKg5W5n25hi0DB6Rjgg:b-bbia4z) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L125)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

We don't really have a cert name from XDS.
</blockquote></details>

Yes we do.  See above.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 131 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVsLy4oEPL7HeqycN:-MKg5wkk9-Af89FpJAWT:b-wxwkyj) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L131)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Yeah, in that case, the TLS security connector needs to be different.
</blockquote></details>

Okay.  And in that case, we won't call `set_root_certificate_distributor()` in the first place?
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 154 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVWly8Sy6ORpdyao6:-MKg5_Ln8fJ_kSU-MPh7:b-bbia4z) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L154)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

We don't have a certificate name. We just get an opaque name that we match with the config provided in the bootstrap file.
</blockquote></details>

Yes we do.  See above.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 160 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfWsjU9ruUALlr6SM4:-MKg6Hl19Mk8Z7jUyX72:b-n5umjt) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L160)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

It is an error if the security connector tries to watch over identity certificates if it is not set. If we are switching from mTLS to TLS/fallback, we would need to use a new security connector, and that new security connector would not be watching over these certificates anymore.
</blockquote></details>

Okay, and we won't call `set_identity_cert_distributor()` in that case?
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 201 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfY40W4v9ivdJhzMFT:-MKg5bPw03tEuT02iwvC:b-bbia4z) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L201)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

We don't have a cert name from XDS.
</blockquote></details>

Yes we do.  See above.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 225 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfY5S33yxYj1s7QhzN:-MKg5dEQ5blb2g9vmNGZ:b-bbia4z) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L225)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

We don't have a cert name for XDS
</blockquote></details>

Yes we do.  See above.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfYUtV1lnu2Kwl3GQ4:-MKg5la6EKPelJ9c6Ibt:b-a5n3hk) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L48)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

If we don't do this, then in OnCertificatesChanged(), we will need to check if the certificates are empty, and that seems unnecessary if we are already using absl::optional
</blockquote></details>

Ah, I see -- the issue is that the underlying storage in the distributor doesn't use `absl::optional<>`.  Okay, that makes sense.

@zhenlian, please make sure this looks right to you as well.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 74 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfYXao3M4t0f0LXHr4:-MKg6uytA2GWs8pH7g9W:bc6vktx) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L74)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

If we don't do this, then in OnCertificatesChanged(), we will need to check if the certificates are empty, and that seems unnecessary if we are already using absl::optional
</blockquote></details>

@zhenlian should look at this change as well.
___
*[test/core/xds/xds_certificate_provider_test.cc, line 163 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfpX_y9THz4DOZ7_o3:-MKg71AR9n_Wz2XGBZd1:b-of6x50) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/test/core/xds/xds_certificate_provider_test.cc#L163)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I don't understand this. It is possible for the identity certificates to have changed without the root certificates. Why should that be an error?
</blockquote></details>

The point is that setting a new root cert clears the root cert error, but it should not clear the identity cert error, and vice-versa.

This test is resetting both certs, which is why their errors are cleared.  What I'm saying is that we should reset the certs one at a time and verify that we clear only the error associated with the cert that gets set.


<!-- Sent from Reviewable.io -->

2020-10-28 17:18 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24579)* status: all files reviewed, 17 unresolved discussions (waiting on @yashykt)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfYUtV1lnu2Kwl3GQ4:-MKkCX6o2fUr0nzIdDg2:b-uoktb3) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ah, I see -- the issue is that the underlying storage in the distributor doesn't use `absl::optional<>`.  Okay, that makes sense.

@zhenlian, please make sure this looks right to you as well.
</blockquote></details>

Yeah, LGTM!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc, line 74 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfYXao3M4t0f0LXHr4:-MKkCoaX-eu3pgiWXfm2:b-85i648) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.cc#L74)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

@zhenlian should look at this change as well.
</blockquote></details>

LGTM!


<!-- Sent from Reviewable.io -->

2020-10-28 22:08 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24579)* status: 1 of 21 files reviewed, 17 unresolved discussions (waiting on @markdroth)

___
*[BUILD, line 1382 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKeqBa22PE3AD-PlV-D:-MKlEB3D3pc2WdlQqijr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/BUILD#L1382)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest just adding these files to the existing `grpc_xds_credentials` target rather than adding a new one.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_certificate_provider.h, line 28 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfNUFc-FiN4hLDsxAr:-MKlECwx3dnMihrczH9z:beao38y) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.h#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  Then let's clean up the TLS code.
</blockquote></details>

https://github.com/grpc/grpc/pull/24597 for cleaning up TLS
___
*[src/core/ext/xds/xds_certificate_provider.h, line 31 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVCkZ4cJXixi9BJus:-MKlEFdr4TuPNNsMXXnW:byd5fgz) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.h#L31)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We will get a cert name in the xDS resources.

https://github.com/envoyproxy/envoy/blob/6321e5d95f7e435625d762ea82316b7a9f7071a4/api/envoy/extensions/transport_sockets/tls/v3/tls.proto#L170

We need to use that cert name here.
</blockquote></details>

Ah, I've been ignoring that since we don't use that as of now. Updated.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 120 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfSTyF1MbS7d8eufr-:-MKlFNmv9b3Rrol2a4b6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L120)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as:

```
auto watcher = absl::make_unique<RootCertificateWatcher>(distributor());
root_cert_watcher_ = watcher.get();
root_cert_distributor->WatchTlsCertificates(
    std::move(watcher), "", absl::nullopt);
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 125 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfSPgPAM1oD72tZA51:-MKlEQRj3oLUdWcLD9-O:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L125)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes we do.  See above.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 131 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVsLy4oEPL7HeqycN:-MKg9Wqg6cZhn6IyqhAD:b-hem68s) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L131)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  And in that case, we won't call `set_root_certificate_distributor()` in the first place?
</blockquote></details>

It would be called if there is a change between the states (mtls, tls, fallback)
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfV_111uwqe2lsdYTW:-MKlERHL5V3CzszOXMtH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L149)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as:

```
auto watcher = absl::make_unique<IdentityCertificateWatcher>(distributor());
identity_cert_watcher_ = watcher.get();
identity_cert_distributor->WatchTlsCertificates(
    std::move(watcher), absl::nullopt, "");
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 154 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVWly8Sy6ORpdyao6:-MKlERvY0defSZLzMzqf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L154)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes we do.  See above.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 160 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfWsjU9ruUALlr6SM4:-MKg9hkv1BPJUZFq7E6w:b-hem68s) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L160)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay, and we won't call `set_identity_cert_distributor()` in that case?
</blockquote></details>

It would be called if there is a change between the states (mtls, tls, fallback)
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 196 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfXCqc-j7cIMtxIRRo:-MKlESfcDJXf3xgP55gs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L196)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same comment as on line 120.

Also, consider refactoring this into a helper method to avoid duplication.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 201 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfY40W4v9ivdJhzMFT:-MKlETKg4Wu2pFpdrCiw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L201)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes we do.  See above.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 220 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfXMxb5hWoPCpqnRYt:-MKlETvaE4CQ6FNKZGJB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L220)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same comment as on line 149.

Also, consider refactoring this into a helper method to avoid duplication.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 225 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfY5S33yxYj1s7QhzN:-MKlEUZh5LpUgnIe7xuo:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L225)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes we do.  See above.
</blockquote></details>

Done.
___
*[test/core/xds/xds_certificate_provider_test.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfZ4uBAZOEGX8mYZkS:-MKlEXLX4_dkhyI1X3SZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/test/core/xds/xds_certificate_provider_test.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this is now `grpc_core::PemKeyCertPairList`, and the `grpc_core::` prefix is not needed here, so you can just say `PemKeyCertPairList`.

Same thing throughout.
</blockquote></details>

Done.
___
*[test/core/xds/xds_certificate_provider_test.cc, line 49 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfZCv-94TrxuMc7Ars:-MKlEe7_CnGnx17tfVC [...]

2020-10-30 15:50 UTC, markdroth approved these changes
This looks great!

> Reviewed 17 of 20 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24579#-:-MKuC4F1DR_Z59YXeXvK:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/core/ext/xds/xds_certificate_provider.cc, line 131 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfVsLy4oEPL7HeqycN:-MKuAAyW7Ei4mRlAlNpl:b-74lxmj) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L131)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

It would be called if there is a change between the states (mtls, tls, fallback)
</blockquote></details>

Then this seems wrong to me, because it could wind up sending an error to the old subchannels (the ones with the old channel arg) before the new ones come up.

I think that in the case where we switch security connectors, we also need to switch to a new `XdsCertificateProvider` instance.

I guess it doesn't really matter if the code here sends an error in this case; my comment here is more to point out that we should never actually hit this code-path in practice.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 160 at r1](https://reviewable.io/reviews/grpc/grpc/24579#-MKfWsjU9ruUALlr6SM4:-MKuAnSIBY5bsNpk33rH:bj7apw7) ([raw file](https://github.com/grpc/grpc/blob/e63755d5bae0834fadc0a0c250ef7f65cb8e1454/src/core/ext/xds/xds_certificate_provider.cc#L160)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

It would be called if there is a change between the states (mtls, tls, fallback)
</blockquote></details>

See discussion above.


<!-- Sent from Reviewable.io -->

2020-10-30 20:01 UTC, yashykt commented
Thanks for reviewing!

2020-11-02 19:28 UTC, merged