Add CertificateWacherProvider
grpc/grpc pull request #24600
Opened 2020-10-29 06:50 UTC by ZhenLian

2020-10-30 20:32 UTC, ZhenLian commented
Right now this only contains the core changes, but I have some questions(I put them in comments) to ask before proceeding, so I think it could be great if I can get some initial feedback.
Currently, this PR also has a MSAN error for certain e2e tests, and I am trying to figure out the cause.
@markdroth @yashykt Feel free to let me know if you have any questions. Thanks!

2020-10-31 00:48 UTC, markdroth requested changes
This looks like a great start!

Please let me know if you have any questions.  Thanks!

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MKw73xQ93rf8_BfEg62:b9kv8rc)* status: all files reviewed, 40 unresolved discussions (waiting on @yashykt and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 826 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvZmFLDHus2ocUZB1F:-MKvZmFM9Z4TbpZbQWAW:b-or432n) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/include/grpc/grpc_security.h#L826)):*
> ```objc
>  * - root_cert_full_path is the full path to the root certificate bundle.
>  * - refresh_interval_sec is the refreshing interval that we will check the
>  * files for updates. All of the path parameters can be nullptr, indicating the
> ```

Please indent this two spaces, since it's a continuation of the bullet on the previous line, and split this second sentence out onto the start of the next line (which does not need to be indented).
___
*[include/grpc/grpc_security.h, line 827 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvanoi1GEschUNdwlA:-MKvanoi1GEschUNdwlB:b-5lp1gj) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/include/grpc/grpc_security.h#L827)):*
> ```objc
>  * - refresh_interval_sec is the refreshing interval that we will check the
>  * files for updates. All of the path parameters can be nullptr, indicating the
>  * corresponding credentials are not needed. But |identity_key_cert_directory|,
> ```

This last sentence is very confusing.  Instead, I suggest the following:

- In the description of identity_key_cert_directory above, say "May be null if no identity cert is needed".
- In the description of both private_key_file_name and identity_certificate_file_name, say "Not used if identity_key_cert_directory is null".
___
*[include/grpc/grpc_security.h, line 830 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvbr3v8MZGUdWGqUfb:-MKvbr3v8MZGUdWGqUfc:be2ej07) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/include/grpc/grpc_security.h#L830)):*
> ```objc
>  * |private_key_file_name| and |identity_certificate_file_name| should be all
>  * nullptr or non-nullptr.
>  * All the path parameters will be copied inside.
> ```

Suggest saying "Does not take ownership of parameters."
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvcAIZ3OF7V_zz4uJR:-MKvcAI_3D_2Mg3LZvha:b5jvd64) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L75)):*
> ```objc
>   };
> 
>   // Sets the key materials based on their certificate name. We will do an
> ```

This change seems incorrect.  The API is passing the parameters in by value.  How can it not take ownership?
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 90 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvg530AQLv7IRuJcKl:-MKvg530AQLv7IRuJcKm:b-iqu6u4) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L90)):*
> ```objc
>   }
> 
>   bool is_shutdown() {
> ```

These two methods are not necessary.  All of the code that is accessing `is_shutdown_` is internal to this class, so it can access the data member directly.

Also, as per my comment elsewhere, I don't think `is_shutdown_` is actually necessary in the first place.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 123 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvg-3d135fW3SuJnzU:-MKvg-3d135fW3SuJnzV:b-sqnier) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L123)):*
> ```objc
>   // Used by refresh_thread_.
>   // Question: the purpose of these fields is just for the use of thread lambda.
>   // I didn't find a way to capture values using grpc_core::Thread and lambda.
> ```

Unfortunately, it looks like `grpc_core::Thread` takes a simple `void (*func)(void*)` parameter, which means that you can't pre-bind parameters.  But the way you're doing this now is fine.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvcqJX6eRIs_4a4FOP:-MKvcqJX6eRIs_4a4FOQ:b-issnx6) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L59)):*
> ```cpp
>     unsigned int refresh_interval_sec)
>     : distributor_(MakeRefCounted<grpc_tls_certificate_distributor>()),
>       identity_key_cert_directory_(identity_key_cert_directory),
> ```

Please use `std::move()` for all of these string parameters.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 64 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKveq8A7x72Kem09ahi:-MKveq8A7x72Kem09ahj:b2zgvwk) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L64)):*
> ```cpp
>       root_cert_full_path_(root_cert_full_path),
>       refresh_interval_sec_(refresh_interval_sec) {
>   auto thread_lambda = [](void* th) {
> ```

Please call the parameter `arg` instead of `th`.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvl5Y8DK0qyuaPcmU0:-MKvl5Y8DK0qyuaPcmU1:b-svo7yz) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L70)):*
> ```cpp
>     while (true) {
>       {
>         grpc_core::MutexLock lock(&provider->mu_);
> ```

I don't think we actually need to acquire the mutex until we access `provider->watcher_info_`.  We don't need the mutex to access the path names, since they are not going to be changed by any other thread.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 78 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvdyPF2K_eRUCRZwOb:-MKvdyPF2K_eRUCRZwOc:bnswy7d) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L78)):*
> ```cpp
>         }
>         if (!provider->identity_key_cert_directory_.empty() &&
>             !provider->private_key_file_name_.empty() &&
> ```

I don't think it's necessary to check the two filename fields here.  As mentioned elsewhere, we should just check whether the directory is null to decide if we should be watching the identity cert, and when we first see the parameters, we should require that if the directory is non-null, the filenames are also non-null.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 85 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvhiva45t1lkwer3O9:-MKvhiva45t1lkwer3OA:bjwmov5) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L85)):*
> ```cpp
>               provider->identity_certificate_file_name_);
>         }
>         if (root_certificate != absl::nullopt ||
> ```

Prefer `foo.has_value()` to `foo != absl::nullopt`.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 87 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvhv4N-4qZWEczbo99:-MKvhv4N-4qZWEczbo9A:b-s6sopp) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L87)):*
> ```cpp
>         i [...]

2020-11-03 07:59 UTC, ZhenLian reviewed
Thanks for the review!
I've also added the C++ wrapper. Feel free to take a look it as well. Thanks again!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLC5vhz1HpWuOseT0yf:b-g1uyt7)* status: all files reviewed, 40 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[include/grpc/grpc_security.h, line 826 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvZmFLDHus2ocUZB1F:-ML6T_bW865ThXy-qKmL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/include/grpc/grpc_security.h#L826)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please indent this two spaces, since it's a continuation of the bullet on the previous line, and split this second sentence out onto the start of the next line (which does not need to be indented).
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 827 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvanoi1GEschUNdwlA:-ML6U9FP66Oap7FSeD3K:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/include/grpc/grpc_security.h#L827)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This last sentence is very confusing.  Instead, I suggest the following:

- In the description of identity_key_cert_directory above, say "May be null if no identity cert is needed".
- In the description of both private_key_file_name and identity_certificate_file_name, say "Not used if identity_key_cert_directory is null".
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 830 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvbr3v8MZGUdWGqUfb:-ML6VBu90oOLXgCJvQva:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/include/grpc/grpc_security.h#L830)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest saying "Does not take ownership of parameters."
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvcAIZ3OF7V_zz4uJR:-ML6XZtd4hgZsOu4o2zd:b-agls84) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L75)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This change seems incorrect.  The API is passing the parameters in by value.  How can it not take ownership?
</blockquote></details>

Ah, my thought was, passing by value was like doing a copy immediately after entering the functional call. But if "passing by value" is so obvious, I guess it's ok to delete the description about the ownership here?
Also, I came across https://abseil.io/tips/163, which seems to discourage the use of absl::optional in function parameters, since it enforces a copy. Do you think this is a potential point that we can improve here?
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 90 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvg530AQLv7IRuJcKl:-MLC6Ezv7LUFrAXiGMaT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L90)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two methods are not necessary.  All of the code that is accessing `is_shutdown_` is internal to this class, so it can access the data member directly.

Also, as per my comment elsewhere, I don't think `is_shutdown_` is actually necessary in the first place.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 123 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvg-3d135fW3SuJnzU:-ML6gSua9EMWr96T8KdX:bcr5s2o) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L123)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Unfortunately, it looks like `grpc_core::Thread` takes a simple `void (*func)(void*)` parameter, which means that you can't pre-bind parameters.  But the way you're doing this now is fine.
</blockquote></details>

Got it, thanks!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvcqJX6eRIs_4a4FOP:-ML6kKan3rZd4yLIxGSG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `std::move()` for all of these string parameters.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 64 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKveq8A7x72Kem09ahi:-ML6kTWW6ClGGamAgL7T:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L64)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call the parameter `arg` instead of `th`.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvl5Y8DK0qyuaPcmU0:-ML6oAW71ecWG5n8QUX-:b-x9nznb) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we actually need to acquire the mutex until we access `provider->watcher_info_`.  We don't need the mutex to access the path names, since they are not going to be changed by any other thread.
</blockquote></details>

Sounds good. I also removed the "Locked" suffix of  `ReadRootCertificatesFromFileLocked` and `ReadIdentityKeyCertPairFromFilesLocked` functions - they will still be surrounded by locks in the distributor callback, but it is no more a requirement for them to always be locked.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 78 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvdyPF2K_eRUCRZwOb:-ML97F8ZCiYvXh9Fq4ta:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L78)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think it's necessary to check the two filename fields here.  As mentioned elsewhere, we should just check whether the directory is null to decide if we should be watching the identity cert, and when we first see the parameters, we should require that if the directory is non-null, the filenames are also non-null.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 85 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvhiva45t1lkwer3O9:-ML97Q248_19nSXsEJ1_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Prefer `foo.has_value()` to `foo != absl::nullopt`.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 87 at r1](https://reviewable.io/reviews/grpc/grpc/2 [...]

2020-11-03 22:19 UTC, markdroth requested changes
This is moving in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLFBMTPD9HF1pOIVz79:b-k1b92a)* status: all files reviewed, 36 unresolved discussions (waiting on @yashykt and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 828 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEsGpG7z3W3-BT2B2O:-MLEsGpG7z3W3-BT2B2P:bhpefuy) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpc/grpc_security.h#L828)):*
> ```objc
>  *   |identity_key_cert_directory| is null.
>  * - root_cert_full_path is the full path to the root certificate bundle. This
>  * may be null if no root certs are needed.
> ```

Please indent two spaces.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 83 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEsaWBEHjydoyHGd79:-MLEsaWBEHjydoyHGd7A:b-8o79hy) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L83)):*
> ```objc
> // 1. This API only supports one key-cert file and hence one set of identity
> // key-cert pair, so SNI(Server Name Indication) is not supported.
> // 2. The private key and identity certificates should always match. This API
> ```

s/certificates/certificate/
___
*[include/grpcpp/security/tls_certificate_provider.h, line 92 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEtAAo2lDvNO35gg4l:-MLEtAAo2lDvNO35gg4m:b-l3l46c) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L92)):*
> ```objc
> //   credential data in a new directory, and change symlink.
> 
> // identity_key_cert_directory is the directory used to store the private key
> ```

This comment should be right above the ctor, not ahead of the class as a whole.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 93 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEsqGo3So-zQ89XOtJ:-MLEsqGo3So-zQ89XOtK:b-ewwgxo) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L93)):*
> ```objc
> 
> // identity_key_cert_directory is the directory used to store the private key
> // and identity certificate chain.
> ```

If empty, no identity cert or private key will be read.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 94 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEsx482FUgyZ3e1l4z:-MLEsx482FUgyZ3e1l5-:b-5tzg01) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L94)):*
> ```objc
> // identity_key_cert_directory is the directory used to store the private key
> // and identity certificate chain.
> // private_key_file_name is the file name of the private key in
> ```

Please document that these two params are ignored if `identity_key_cert_directory` is empty.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 97 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEt1c40s1F63OQfgzq:-MLEt1c40s1F63OQfgzr:b-i63egh) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L97)):*
> ```objc
> // |identity_key_cert_directory|. identity_certificate_file_name is the file
> // name of the identity certificate chain in |identity_key_cert_directory|.
> // root_cert_full_path is the full path to the root certificate bundle.
> ```

If empty, no root cert will be read.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 124 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEtICZ5m_VgxEk9xAp:-MLEtICZ5m_VgxEk9xAq:b-pf21v6) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L124)):*
> ```objc
>                                        refresh_interval_sec) {}
> 
>   ~FileWatcherCertificateProvider();
> ```

This needs to be declared with `override`.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvcAIZ3OF7V_zz4uJR:-MLF6fiq8LYpDKvKqaNE:b3svdca) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L75)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Ah, my thought was, passing by value was like doing a copy immediately after entering the functional call. But if "passing by value" is so obvious, I guess it's ok to delete the description about the ownership here?
Also, I came across https://abseil.io/tips/163, which seems to discourage the use of absl::optional in function parameters, since it enforces a copy. Do you think this is a potential point that we can improve here?
</blockquote></details>

Passing by value means that the function owns the values that are passed in.  It may be that the caller is making a copy of the value (either explicitly or implicitly) before passing it in, but the actual value received by the function is owned by the function.

To better understand how this works, try running the following code:

```
#include <stdio.h>

#include <utility>

class Obj {
 public:
  explicit Obj(int value) : value_(value) {
    printf("Obj[%p]: value=%d\n", this, value_);
  }

  // Copy ctor.
  Obj(const Obj& other) : value_(other.value_) {
    printf("Obj[%p]: copy ctor from %p: value=%d\n", this, &other, value_);
  }

  // Move ctor.
  Obj(Obj&& other) : value_(other.value_) {
    other.value_ = 0;
    printf("Obj[%p]: move ctor from %p: value=%d\n", this, &other, value_);
  }

  ~Obj() { printf("~Obj[%p]: value=%d\n", this, value_); }

  int value() const { return value_; }

 private:
  int value_;
};

void Func(Obj o) {
  printf("Func(): o.value()=%d\n", o.value());
}

int main(int argc, char* argv[]) {
  printf("construct new object to pass in, func takes ownership\n");
  Func(Obj(1));
  printf("back from func\n");

  {
    printf("\nuse local object, copy is made\n");
    Obj o(2);
    Func(o);
    printf("back from func\n");
  }

  {
    printf("\nuse std::move() to pass ownership of contents\n");
    Obj o(3);
    Func(std::move(o));
    printf("back from func\n");
  }

  return 0;
}
```

From the perspective of this API, the caller does not know or care about the fact that this function makes a copy.  All it cares about is whether it is passing ownership of the parameters, and that is obvious from the function signature.  (In general, the only time you need to document ownership semantics in comments is when using raw C-style pointers, because there the ownership transfer is not obvious.)

So yes, please just delete this sentence.

I don't think the absl tip applies here, since we actually want to take ownership in this case.  We do make an extra copy now, but I think once we change `grpc_ssl_pem_key_cert_pair` to use C++-style strings, we'll be able to just move the passed-in value into the structure we're saving it in.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 26 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MLEtNWUDCjzM-ZgieX7:-MLEtNWUDCjzM-ZgieX8:b-ygcb8m) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L26)):*
> ```objc
> 
> #include "absl/container/inlined_vector.h"
> ```

Please put this blank line back.  Includes from absl should be in their own section, ahead of includes from within gRPC.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEtzydBxquYcknxzzt:-MLEtzydBxquYcknxzzu:b-iux2fe) ([raw file](https://github.com/ [...]

2020-11-04 19:54 UTC, markdroth reviewed
@ejona86 pointed out that we can simplify this a bit: we actually don't need to check the timestamp on the directory containing the identity cert and private key; all we really need to do is check the timestamps on the two files.  And given that, there is no longer any reason why the two files need to be in the same directory.  So I guess let's just go ahead and change the parameters such that we're specifying the full path to both files independently.

Please let me know if you have any questions.  Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLJoJdI6dDdSlN_WCGi:b9v1rrk)* status: all files reviewed, 36 unresolved discussions (waiting on @yashykt and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-11-04 21:00 UTC, ZhenLian reviewed
IIUC, we still require the atomic update from the user, right? Just in the path parameters we don't enforce them to put key and cert in one directory, but they are always able to do so and pass the full path of key and cert to our API?

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLK0Otw-llFcyfUFKUi:bcz8tsl)* status: all files reviewed, 36 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 828 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEsGpG7z3W3-BT2B2O:-MLH39jy89fyym9ZmFFp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpc/grpc_security.h#L828)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please indent two spaces.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 83 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEsaWBEHjydoyHGd79:-MLH9h721cl0q2KYRlSk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L83)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/certificates/certificate/
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 92 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEtAAo2lDvNO35gg4l:-MLHA0nd33iZfOIpVQdb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L92)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment should be right above the ctor, not ahead of the class as a whole.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 93 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEsqGo3So-zQ89XOtJ:-MLHA6nQ-7L-yX2iXxDl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L93)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If empty, no identity cert or private key will be read.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 94 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEsx482FUgyZ3e1l4z:-MLHA8rh9Z1ReNwWCs-A:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L94)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document that these two params are ignored if `identity_key_cert_directory` is empty.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 97 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEt1c40s1F63OQfgzq:-MLHBis37naDLf1O_B1r:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L97)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If empty, no root cert will be read.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 124 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEtICZ5m_VgxEk9xAp:-MLHBwoW2xChGa6lj9Zf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/include/grpcpp/security/tls_certificate_provider.h#L124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to be declared with `override`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-05 17:55 UTC, markdroth reviewed
Yes, that's correct.

The user still needs to update the two files atomically (e.g., by using a symlink or renaming the directory).  And if they do that, then this will work fine no matter what we do here -- even if we didn't check timestamps at all.  Checking the timestamps is really about making sure that we have a good failure mode if the user does *not* update the files atomically.

Checking the timestamp on the directory doesn't help detect the failure, because the entire "check timestamps, read files, check timestamps again" cycle could still take place between when one file is updated and when the other file is updated.

This is why I think we should have the file watcher check that the cert and private key actually match each other before we pass them to the distributor.  If they don't match, we can just return an error to the distributor, and the security connector will continue to use the previous cert, if any.  But if we send non-matching data to the distributor, it will overwrite the previous values in the security connector, and we'll start failing connection attempts.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLOWI3G9BINgL0p7qMH:basdmwl)* status: all files reviewed, 29 unresolved discussions (waiting on @yashykt and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-11-05 20:58 UTC, yashykt commented
Yes, we should ideally be making sure that the certs and private keys match. Even if we can't do it now, we should add a TODO for it.





<!-- Sent from Reviewable.io -->

2020-11-05 23:02 UTC, jiangtaoli2016 approved these changes
Even user writes key/cert atomically, reading timestamp does not guarantee consistency. 
Let's say two set of key/cert pairs are generated at the same, in two different directories. User to symlink to change directory when updating key/cert. 

If we read timestamps, then read key file, then read cert file, then re-check timestamp, it won't detect that symlink has been changed in between, since the files are generated at the same time. 

Reading directory timestamp would catch this.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLPclq177V73CU-Mx4W:b3j6m2x)* status: all files reviewed, 29 unresolved discussions (waiting on @yashykt and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-11-06 16:01 UTC, markdroth reviewed
It's extremely unlikely that two sets of files will both be written at exactly the same moment.  But even if they are, if they are the only files in their respective directories, then the directories themselves will also have exactly the same timestamp.  So checking the directory's timestamp does not help.

If you are really worried about this, then let's go ahead and implement the check that the key and cert match using the SSL library.  That way, we can be absolutely sure that the two files are valid and match each other.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLTHJAF6xjV758QL7AU:b-m3oevb)* status: all files reviewed, 29 unresolved discussions (waiting on @yashykt and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-11-06 17:30 UTC, jiangtaoli2016 approved these changes
I am not worry about this. Let's plan on implementing key/cert consistency inside gRPC. 

Given the key rotation frequency (usually days or weeks), the chance of reading inconsistently from filesystem is really low enough. If we do key/cert consistency check, we could avoid timestamp check. Anyway, since timestamp check is already WIP, let's do both for better reliability.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLT_xUl8DW2gFIsgaHV:beuwmdq)* status: all files reviewed, 29 unresolved discussions (waiting on @yashykt and @ZhenLian)



<!-- Sent from Reviewable.io -->

2020-11-06 21:07 UTC, ZhenLian reviewed
Sure. I updated the code to take parameters without directory. Please take a look, thanks!
I am having trouble running `tools/buildgen/generate_projects.sh` locally after rebasing to the latest change, and I am still working on it(it seems related to the recent changes of using python3 in buildgen). You will see a bunch of failed errors, but that's caused by not being able to run `tools/buildgen/generate_projects.sh`. The code itself should be ready for review.
ForceUpdate is not added to C++ yet. I will add it once I fix the `tools/buildgen/generate_projects.sh` problem.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLUMSkNDiumui3ml3nK:b-8mfwpe)* status: all files reviewed, 29 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvcAIZ3OF7V_zz4uJR:-MLKj86n5uOKIformniP:b-gto05n) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L75)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Passing by value means that the function owns the values that are passed in.  It may be that the caller is making a copy of the value (either explicitly or implicitly) before passing it in, but the actual value received by the function is owned by the function.

To better understand how this works, try running the following code:

```
#include <stdio.h>

#include <utility>

class Obj {
 public:
  explicit Obj(int value) : value_(value) {
    printf("Obj[%p]: value=%d\n", this, value_);
  }

  // Copy ctor.
  Obj(const Obj& other) : value_(other.value_) {
    printf("Obj[%p]: copy ctor from %p: value=%d\n", this, &other, value_);
  }

  // Move ctor.
  Obj(Obj&& other) : value_(other.value_) {
    other.value_ = 0;
    printf("Obj[%p]: move ctor from %p: value=%d\n", this, &other, value_);
  }

  ~Obj() { printf("~Obj[%p]: value=%d\n", this, value_); }

  int value() const { return value_; }

 private:
  int value_;
};

void Func(Obj o) {
  printf("Func(): o.value()=%d\n", o.value());
}

int main(int argc, char* argv[]) {
  printf("construct new object to pass in, func takes ownership\n");
  Func(Obj(1));
  printf("back from func\n");

  {
    printf("\nuse local object, copy is made\n");
    Obj o(2);
    Func(o);
    printf("back from func\n");
  }

  {
    printf("\nuse std::move() to pass ownership of contents\n");
    Obj o(3);
    Func(std::move(o));
    printf("back from func\n");
  }

  return 0;
}
```

From the perspective of this API, the caller does not know or care about the fact that this function makes a copy.  All it cares about is whether it is passing ownership of the parameters, and that is obvious from the function signature.  (In general, the only time you need to document ownership semantics in comments is when using raw C-style pointers, because there the ownership transfer is not obvious.)

So yes, please just delete this sentence.

I don't think the absl tip applies here, since we actually want to take ownership in this case.  We do make an extra copy now, but I think once we change `grpc_ssl_pem_key_cert_pair` to use C++-style strings, we'll be able to just move the passed-in value into the structure we're saving it in.
</blockquote></details>

Thanks for the explanation and the excellent code snippet! It also answered a lot of questions I wanted to ask a while ago. I really appreciate the time for writing this beautiful example!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 26 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MLEtNWUDCjzM-ZgieX7:-MLKl0vw01rb25mkIoGu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L26)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please put this blank line back.  Includes from absl should be in their own section, ahead of includes from within gRPC.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEtzydBxquYcknxzzt:-MLKm1KO-ulvwsMs_NyG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L103)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest moving this down such that only the members that are guarded by the mutex are listed after it.  Then you can add a comment here that says "Guards members below".
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 110 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEtnSM7Odj_wtcGqQm:-MLKn0gGB6XTDgHF8LG8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L110)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest moving these parameters up to line 103, since they are set by the ctor.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 54 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEuyNpE25O0lGAo6xJ:-MLPo65NEOhOWMaqHGyI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please put this in an anonymous namespace, since it does not need to be visible outside of this file.

Also, please call it `TimeoutSecondsToDeadline()`.

And please name the parameter `seconds`.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 57 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEubmxAkvrh8_epdt_:-MLPoXKOE2PvmchzDgd0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`gpr_time_from_seconds(time_s, GPR_TIMESPAN)`
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 97 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEvhRUCZaQbyLKUYKC:-MLPq1wZEymY5DBGD7lx:b2ovban) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L97)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

We will need this when later calling `provider->distributor_->SetKeyMaterials`...
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEvk3a9YMaysJM4s1U:-MLPqDHI46hCaXMfRcEF:b-w3fxh) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L103)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Yeah it is also needed later. And it seems we can't move them later when setting key materials to the distributor, since it is in a loop.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 110 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEvybo7kEqVKz2Ssah:-MLPrcZW3Hn [...]

2020-11-06 21:42 UTC, ZhenLian reviewed
Ah, the issue was resolved. Please just give me some time to add the ForceUpdate to C++...

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLUVUaPDF0gxZDKaqFl:bep6xqe)* status: all files reviewed, 29 unresolved discussions (waiting on @markdroth and @yashykt)



<!-- Sent from Reviewable.io -->

2020-11-06 22:37 UTC, markdroth requested changes
This is getting closer!

Please let me know if you have any questions.  Thanks!

> Reviewed 15 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLUhFjU1dz9O3Pq9lfj:b79zqk9)* status: all files reviewed, 20 unresolved discussions (waiting on @yashykt and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 818 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUXca57rXIFPRBoA82:-MLUXca57rXIFPRBoA83:b57heuw) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/include/grpc/grpc_security.h#L818)):*
> ```objc
>  * Indication) is not supported.
>  * - private_key_path is the file path of the private key. This must be set if
>  * |identity_certificate_path| is set. Otherwise, it could be null if no
> ```

Please indent these two lines two spaces.
___
*[include/grpc/grpc_security.h, line 821 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUXWmB36A2qE32R3dd:-MLUXWmC4AfvtbXQ6bAM:b-yg8vjo) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/include/grpc/grpc_security.h#L821)):*
> ```objc
>  * identity credentials are needed.
>  * - identity_certificate_path is the file path of the identity certificate
>  *   chain .This must be set if |private_key_path| is set. Otherwise, it could
> ```

Please move the space to after the first period.
___
*[include/grpc/grpc_security.h, line 822 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUXfM5-TzUc6UXDhkh:-MLUXfM5-TzUc6UXDhki:b-2wilb4) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/include/grpc/grpc_security.h#L822)):*
> ```objc
>  * - identity_certificate_path is the file path of the identity certificate
>  *   chain .This must be set if |private_key_path| is set. Otherwise, it could
>  * be null if no identity credentials are needed.
> ```

Please indent this line two spaces.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 91 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUXpua-8UjtEcCFNTo:-MLUXpua-8UjtEcCFNTp:b-lj5kho) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/include/grpcpp/security/tls_certificate_provider.h#L91)):*
> ```objc
> //   2)  using a symlink for the directory. When need to change, put new
> //   credential data in a new directory, and change symlink.
> // TODO(ZhenLian): remove the second point when the internal key-match mechanism
> ```

No, this TODO should go away.  We will still want people to update the keys atomically, even once we have the key-match check.  That check is just an additional safety check; it's not a substitute for atomic updates.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/24600#-MKvcAIZ3OF7V_zz4uJR:-MLUY_SpEDPvhcMparIM:b-3sygvk) ([raw file](https://github.com/grpc/grpc/blob/4a4be01a3280cd5a9683b4afb6d0d1069b6e1abf/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L75)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Thanks for the explanation and the excellent code snippet! It also answered a lot of questions I wanted to ask a while ago. I really appreciate the time for writing this beautiful example!
</blockquote></details>

You're welcome.  I'm glad you found it useful!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 97 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEvhRUCZaQbyLKUYKC:-MLUZQ-dCF0PYoEcFT48:b-y06bba) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L97)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

We will need this when later calling `provider->distributor_->SetKeyMaterials`...
</blockquote></details>

Sure, but then you can use `provider->root_certificate_`.  There's no reason to keep two copies when you still have access to the place you're moving it to.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEvk3a9YMaysJM4s1U:-MLUZddjAvZFtcI2TVnP:b9mh177) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L103)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Yeah it is also needed later. And it seems we can't move them later when setting key materials to the distributor, since it is in a loop.
</blockquote></details>

You can use `provider->pem_key_cert_pairs_` later, so it's fine to use `std::move()` here.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 33 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUd3pJEaGljGAzjx6f:-MLUd3pK7BgMKLdGwIZX:bha3ncq) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L33)):*
> ```cpp
> namespace {
> 
> gpr_timespec TimeoutSecondsToDeadline(int64_t seconds) {
> ```

These helper functions can each go right above the method that uses them.  It's fine to have anonymous namespace blocks interspersed with the rest of the code.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 50 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUbhus2ehxIj_C6sJt:-MLUbhus2ehxIj_C6sJu:blhuxst) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L50)):*
> ```cpp
> }
> 
> struct SliceWrapper {
> ```

This is only needed inside of `ReadIdentityKeyCertPairFromFiles()`, so you can move it into that method.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 88 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUfDdK83LHFOyN5MPq:-MLUfDdK83LHFOyN5MPr:ba3xa0r) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L88)):*
> ```cpp
>       refresh_interval_sec_(refresh_interval_sec),
>       distributor_(MakeRefCounted<grpc_tls_certificate_distributor>()) {
>   gpr_event_init(&event_);
> ```

I think the input validation should happen here instead of in `grpc_tls_certificate_provider_file_watcher_create()`, because that way it will still be used even if some code inside of core directly instantiates this class.  The logic can be:

```
// Private key and identity cert files must be both set or both unset.
GPR_ASSERT(private_key_path.empty() == identity_certificate_path.empty());
// Must be watching either root or identity certs.
GPR_ASSERT(!private_key_path.empty() || root_cert_path.empty());
```
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 114 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUZuTS6sbO0eqDcsQn:-MLUZuTS6sbO0eqDcsQo:bi3kmhx) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L114)):*
> ```cpp
>     FileWatcherCertificateProvider::WatcherInfo& info =
>         watcher_info_[cert_name];
>     if (!info.root_being_watched && root_being_watched) {
> ```

These two `if` statements can be combined into one.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 120 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLU_iTd-dFBNgfs6LlQ:-MLU_iTd-dFBNgfs6LlR:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L120)):*
> ```cpp
>     }
>     info.root_being_watched = root_being_watched;
>     if (!info.identity_being_watched && identity_being_watched) {
> ```

Same [...]

2020-11-07 16:44 UTC, ZhenLian reviewed
Thanks for the review! Right now for `ForceUpdate`, I am using a dynamic_cast to cast the general provider type, but it fails on a specific target `Artifact Build Linux (internal CI)` with error `error: 'dynamic_cast' not permitted with -fno-rtti`. Is dynamic_cast not allowed here? Shall I change it to something else?

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLYTVXlEV86jhMAwwQR:b-i0vw0t)* status: 10 of 20 files reviewed, 20 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 818 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUXca57rXIFPRBoA82:-MLVBuwK9iNU3BpFHNyk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/include/grpc/grpc_security.h#L818)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please indent these two lines two spaces.
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 821 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUXWmB36A2qE32R3dd:-MLVBvGP8G1qGbRWmtNC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/include/grpc/grpc_security.h#L821)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move the space to after the first period.
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 822 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUXfM5-TzUc6UXDhkh:-MLVBva9001d1VF5psIo:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/include/grpc/grpc_security.h#L822)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please indent this line two spaces.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 91 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUXpua-8UjtEcCFNTo:-MLVC1KX3xvAycC95x3U:b-j1g7yf) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/include/grpcpp/security/tls_certificate_provider.h#L91)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No, this TODO should go away.  We will still want people to update the keys atomically, even once we have the key-match check.  That check is just an additional safety check; it's not a substitute for atomic updates.
</blockquote></details>

Sure. But just to be clear, aren't users able to update the two files separately, if that check is available? We will only update if both of them are updated. So a user can update key file, wait for an hour, and update the cert file. Unless it is the first time, it should be fine. It seems we mitigate the restrictions of atomic updates to some extents? 
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 97 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEvhRUCZaQbyLKUYKC:-MLVHYQEDwpamKVm50Dg:bke75ni) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L97)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Sure, but then you can use `provider->root_certificate_`.  There's no reason to keep two copies when you still have access to the place you're moving it to.
</blockquote></details>

Ah yeah, I missed that. Thanks for reminding this!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEvk3a9YMaysJM4s1U:-MLVHtRlE3C2iyu5XBda:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L103)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can use `provider->pem_key_cert_pairs_` later, so it's fine to use `std::move()` here.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 138 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEweZ22J7rlun2PpCd:-MLV9CwsEUVWd6NxbTb6:bc396hm) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L138)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It seems we still need this... I switched back to the original implementation, because it will fail for some of the h2_tls tests on Kokoro. The log shows the code path designed for `OnBlockInitialHandshaker` is executed, so I guess in some tests, the thread is not fast enough to deliver the updates. The error didn't show up when I ran it locally though.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 33 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUd3pJEaGljGAzjx6f:-MLVDSrG-4xm21I42cTg:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L33)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These helper functions can each go right above the method that uses them.  It's fine to have anonymous namespace blocks interspersed with the rest of the code.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 50 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUbhus2ehxIj_C6sJt:-MLVDUcJ2abtWjCC6pht:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is only needed inside of `ReadIdentityKeyCertPairFromFiles()`, so you can move it into that method.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 88 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUfDdK83LHFOyN5MPq:-MLVGK8rCiOyElQlbsJW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L88)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the input validation should happen here instead of in `grpc_tls_certificate_provider_file_watcher_create()`, because that way it will still be used even if some code inside of core directly instantiates this class.  The logic can be:

```
// Private key and identity cert files must be both set or both unset.
GPR_ASSERT(private_key_path.empty() == identity_certificate_path.empty());
// Must be watching either root or identity certs.
GPR_ASSERT(!private_key_path.empty() || root_cert_path.empty());
```
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 121 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLU_kbK9FZnnk4v00IK:-MLVJ2W7Dn_rxNAidsxn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L121)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned above, we should make sure that both of these paths are empty or both are non-empty at construction time.  After that, we can check just one of them, because we know that they will either both be set or both be unset.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 130 at r4](https://reviewable.io/reviews/grpc/grpc/24600# [...]

2020-11-09 19:13 UTC, markdroth requested changes
This is looking pretty good!

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 10 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLiQIkL4DGE28La7cRC:b-lm5h1l)* status: all files reviewed, 9 unresolved discussions (waiting on @yashykt and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 838 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLi2gaN1oo1UzcpvPTs:-MLi2gaN1oo1UzcpvPTt:bcov8la) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/include/grpc/grpc_security.h#L838)):*
> ```objc
>  * Force update the credential data to the distributor regardless of the
>  * refreshing intervals. It will log an error and directly return, if it is
>  * called on providers not created by
> ```

There is no way to detect this dynamically at run-time without using RTTI, which we can't use.  So this should instead say that it is the caller's responsibility to ensure that this is called only on a provider created by `grpc_tls_certificate_provider_file_watcher_create()`; if they don't do that, the behavior is undefined (i.e., it will probably cause a crash).
___
*[include/grpcpp/security/tls_certificate_provider.h, line 91 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUXpua-8UjtEcCFNTo:-MLiKrV1CEKleW1Ijbbm:b-vam19y) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/include/grpcpp/security/tls_certificate_provider.h#L91)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sure. But just to be clear, aren't users able to update the two files separately, if that check is available? We will only update if both of them are updated. So a user can update key file, wait for an hour, and update the cert file. Unless it is the first time, it should be fine. It seems we mitigate the restrictions of atomic updates to some extents? 
</blockquote></details>

I think we would want to encourage people to always update the two files atomically even if we have the key-match check.  At minimum, having the two files be in an inconsistent state would make us do more work, re-reading the files a number of times before we can actually use them.  And from an operational perspective, it's not really safe, because while an already-running server will continue to use the old cert and key, any new server that starts up while the files are inconsistent will not be able to start properly.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 138 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEweZ22J7rlun2PpCd:-MLiLu3L98tPcLEH2zHm:b643nag) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L138)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

It seems we still need this... I switched back to the original implementation, because it will fail for some of the h2_tls tests on Kokoro. The log shows the code path designed for `OnBlockInitialHandshaker` is executed, so I guess in some tests, the thread is not fast enough to deliver the updates. The error didn't show up when I ran it locally though.
</blockquote></details>

I'd really prefer not to do this, because as I mentioned before, this can result in a whole deluge of read attempts if a large number of cert names are being watched and the update thread takes a while to do the first read.

Instead, I suggest the following:

- Have the ctor call `ForceUpdate()` before starting the update thread or registering the watch-status callback.  That way, we know that the first read attempt has finished by the time we get here.
- Have the update thread call `gpr_event_wait()` to delay for the update interval *before* entering the loop, so that we don't do two reads in a row at startup.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 130 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLU_SvH2T293U8WY0nw:-MLiMV-Z39J1fbpdwZjS:b-4ehap1) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L130)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I am a bit confused about "we should probably return an error for whichever one we don't have". We're in the constructor right now. How are we going to return an error?
</blockquote></details>

We're not in the constructor; we're in the watch status callback.  This might be clearer if you move the callback code into its own private method rather than putting it in a lambda.  Same thing for the update thread.

In any case, what I mean by "return an error" is to set the error on the distributor.  But I don't think the condition you're checking here is quite right: you actually need to know whether the initial read attempt has been made yet or not.  If it hasn't, then we need to wait.  But this problem will go away if you have the ctor call `ForceUpdate()` before starting the watch-status callback, as I suggested above.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 72 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiLamI2unYH0avAGHJ:-MLiLamI2unYH0avAGHK:bu36i7s) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L72)):*
> ```cpp
>       distributor_(MakeRefCounted<grpc_tls_certificate_distributor>()) {
>   // Private key and identity cert files must be both set or both unset.
>   GPR_ASSERT(private_key_path.empty() == identity_certificate_path.empty());
> ```

This needs to use `private_key_path_`  and `identity_certificate_path_` -- i.e., the data members, not the input parameters.  This is because the input params will always be empty here, since the initializer list moved their contents into the data members.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 74 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiLk9g-Pg666KNDnQP:-MLiLk9g-Pg666KNDnQQ:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L74)):*
> ```cpp
>   GPR_ASSERT(private_key_path.empty() == identity_certificate_path.empty());
>   // Must be watching either root or identity certs.
>   GPR_ASSERT(!private_key_path.empty() || root_cert_path.empty());
> ```

Same here.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiPG7s1ObueAK4IF1a:-MLiPG7s1ObueAK4IF1b:b-z70zlk) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L181)):*
> ```cpp
>         private_key_path_, identity_certificate_path_);
>   }
>   if (root_certificate.has_value() || pem_key_cert_pairs.has_value()) {
> ```

If neither one got a successful read, we still need to send an error the watchers.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 227 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiPRFi0A6OsINdK3Gc:-MLiPRFi0A6OsINdK3Gd:b-wf7c8x) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L227)):*
> ```cpp
>         // We will push the updates regardless of whether the
>         // root/identity certificates are being watched right now.
>         distributor_->SetKeyMaterials(cert_name, root_certificate_,
> ```

Won't this clear the errors that we just set via `SetErrorForCert()`?
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 386 at r6](https://reviewable.io/reviews/grpc/grpc/24600#- [...]

2020-11-10 06:42 UTC, ZhenLian reviewed
All comments resolved! Could you please take another look? Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLkso5cC022U7cwkVNu:b20kzd2)* status: 17 of 20 files reviewed, 9 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[include/grpc/grpc_security.h, line 838 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLi2gaN1oo1UzcpvPTs:-MLixA2iDA-2zBSWRE-d:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/include/grpc/grpc_security.h#L838)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There is no way to detect this dynamically at run-time without using RTTI, which we can't use.  So this should instead say that it is the caller's responsibility to ensure that this is called only on a provider created by `grpc_tls_certificate_provider_file_watcher_create()`; if they don't do that, the behavior is undefined (i.e., it will probably cause a crash).
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_provider.h, line 91 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUXpua-8UjtEcCFNTo:-MLixUsR6GHQ93ch_wxY:bc3uh2d) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/include/grpcpp/security/tls_certificate_provider.h#L91)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we would want to encourage people to always update the two files atomically even if we have the key-match check.  At minimum, having the two files be in an inconsistent state would make us do more work, re-reading the files a number of times before we can actually use them.  And from an operational perspective, it's not really safe, because while an already-running server will continue to use the old cert and key, any new server that starts up while the files are inconsistent will not be able to start properly.
</blockquote></details>

Ah that makes sense. Thanks for the explanation!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 138 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEweZ22J7rlun2PpCd:-MLjNRzs74jIFD68p3mK:b86tyr4) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L138)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'd really prefer not to do this, because as I mentioned before, this can result in a whole deluge of read attempts if a large number of cert names are being watched and the update thread takes a while to do the first read.

Instead, I suggest the following:

- Have the ctor call `ForceUpdate()` before starting the update thread or registering the watch-status callback.  That way, we know that the first read attempt has finished by the time we get here.
- Have the update thread call `gpr_event_wait()` to delay for the update interval *before* entering the loop, so that we don't do two reads in a row at startup.
</blockquote></details>

Sure, sounds good! 
For the second point, it seems we can just switch the order of calling ForceUpdate and waiting for the interval inside the loop, to achieve similar behaviors. 
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 114 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLUZuTS6sbO0eqDcsQn:-MLjWzuI90MTtWJrOH3s:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L114)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two `if` statements can be combined into one.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 120 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLU_iTd-dFBNgfs6LlQ:-MLjX-g96zclAdhXhKh0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L120)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 130 at r4](https://reviewable.io/reviews/grpc/grpc/24600#-MLU_SvH2T293U8WY0nw:-MLjPV8G6l9BbgKTAsqU:b-hbzzjn) ([raw file](https://github.com/grpc/grpc/blob/f67362c30b5ce08fa02766f3c99106139bcdb4c9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L130)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We're not in the constructor; we're in the watch status callback.  This might be clearer if you move the callback code into its own private method rather than putting it in a lambda.  Same thing for the update thread.

In any case, what I mean by "return an error" is to set the error on the distributor.  But I don't think the condition you're checking here is quite right: you actually need to know whether the initial read attempt has been made yet or not.  If it hasn't, then we need to wait.  But this problem will go away if you have the ctor call `ForceUpdate()` before starting the watch-status callback, as I suggested above.
</blockquote></details>

OK, got it!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 72 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiLamI2unYH0avAGHJ:-MLiy2T2BNSzsPRdocIy:b-w4ke7q) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L72)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to use `private_key_path_`  and `identity_certificate_path_` -- i.e., the data members, not the input parameters.  This is because the input params will always be empty here, since the initializer list moved their contents into the data members.
</blockquote></details>

Ah yeah. Thanks for the catch!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 74 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiLk9g-Pg666KNDnQP:-MLiy8ic1dWNi_DYMdR6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L74)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiPG7s1ObueAK4IF1a:-MLjQpCiEz08SS1xzRmw:b-8zs2sq) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L181)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If neither one got a successful read, we still need to send an error the watchers.
</blockquote></details>

Sending errors to watchers is already a thing that we will do when we set errors to the distributor, so I guess it's ok to not set it a second time here?
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 227 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiPRFi0A6OsINdK3Gc:-MLjL_pd8R6Dkz7OHQVN:bljcpt5) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L227)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Won't this clear the errors that we just set via `SetErrorForCert()`?
</blockquote></details>

Seems not. We will only  [...]

2020-11-10 17:59 UTC, markdroth requested changes
This is getting close!  The only remaining substantive issue is the one about properly reporting errors when both root and identity cert reads fail.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLnIqF41luLIeTQKGFb:b-wqrbk8)* status: all files reviewed, 4 unresolved discussions (waiting on @yashykt and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 113 at r7](https://reviewable.io/reviews/grpc/grpc/24600#-MLnDJsR7q2_513oofC4:-MLnDJsR7q2_513oofC5:bkq4wi2) ([raw file](https://github.com/grpc/grpc/blob/33c991fa975a92ed93168b5cc968c00de1a1c78c/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L113)):*
> ```objc
>   RefCountedPtr<grpc_tls_certificate_distributor> distributor_;
>   grpc_core::Thread refresh_thread_;
>   gpr_event destruction_event_;
> ```

I suggest calling this `shutdown_event_`.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 138 at r2](https://reviewable.io/reviews/grpc/grpc/24600#-MLEweZ22J7rlun2PpCd:-MLnDqAb6jzeVOJnlVJ9:bwyf942) ([raw file](https://github.com/grpc/grpc/blob/66721fd04a13dfe36d7e6f76fd7fab4f855b4766/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L138)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sure, sounds good! 
For the second point, it seems we can just switch the order of calling ForceUpdate and waiting for the interval inside the loop, to achieve similar behaviors. 
</blockquote></details>

Yup, that looks good!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiPG7s1ObueAK4IF1a:-MLnGszsDgiGoOh0O6Fd:bjmijjt) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L181)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sending errors to watchers is already a thing that we will do when we set errors to the distributor, so I guess it's ok to not set it a second time here?
</blockquote></details>

Let's say that we originally had data for both certs and we delivered that data to the distributor.  But now we're doing another read, and the read fails (e.g., the files have been deleted).  In that case, we should deliver an error to the distributor to let the watchers know that there's a problem.

We should probably change the tests to cover failure cases like this.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 115 at r7](https://reviewable.io/reviews/grpc/grpc/24600#-MLnFGVeD89Vrh9WUMw0:-MLnFGVeD89Vrh9WUMw1:b7x8tr0) ([raw file](https://github.com/grpc/grpc/blob/33c991fa975a92ed93168b5cc968c00de1a1c78c/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L115)):*
> ```cpp
>       watcher_info_.erase(cert_name);
>     }
>     if (root_certificate.has_value() || pem_key_cert_pairs.has_value()) {
> ```

I think the error-handling code below should be outside of this block, because if we fail to read both the root and identity certs, we still need to report errors.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 368 at r7](https://reviewable.io/reviews/grpc/grpc/24600#-MLnI1oD4VVDzv0P6HyX:-MLnI1oD4VVDzv0P6HyY:b-zx9xh) ([raw file](https://github.com/grpc/grpc/blob/33c991fa975a92ed93168b5cc968c00de1a1c78c/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L368)):*
> ```cpp
>   auto* file_watcher_provider =
>       static_cast<grpc_core::FileWatcherCertificateProvider*>(provider);
>   if (file_watcher_provider == nullptr) {
> ```

This will never be null, so there's no point in this check.


<!-- Sent from Reviewable.io -->

2020-11-11 22:34 UTC, ZhenLian reviewed
Thanks for the review! I made several changes. Besides a bunch of added tests, I made the static data provider to also only send credentials at the first time a cert_name is watched(Before it sent credentials regardless of wether it is the first time or not).
Please let me know how it looks now. Thank you so much!
 

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLsP3YG0vx9MhZoZpMW:b-69q9t2)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 113 at r7](https://reviewable.io/reviews/grpc/grpc/24600#-MLnDJsR7q2_513oofC4:-MLnPuBP7jadpi15DGjx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/33c991fa975a92ed93168b5cc968c00de1a1c78c/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L113)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest calling this `shutdown_event_`.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiPG7s1ObueAK4IF1a:-MLoptFJ-EFanPnzu8L5:bcis6nv) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L181)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's say that we originally had data for both certs and we delivered that data to the distributor.  But now we're doing another read, and the read fails (e.g., the files have been deleted).  In that case, we should deliver an error to the distributor to let the watchers know that there's a problem.

We should probably change the tests to cover failure cases like this.
</blockquote></details>

Sure, I've moved the code outside of the block.
I added a bunch of tests in `grpc_tls_certificate_provider_test.cc` and `grpc_tls_credentials_options_test.cc`, including the error case when the certs are watched but not delivered. Please take a look, thanks!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 115 at r7](https://reviewable.io/reviews/grpc/grpc/24600#-MLnFGVeD89Vrh9WUMw0:-MLnZXNc32JmKBjetZ2v:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/33c991fa975a92ed93168b5cc968c00de1a1c78c/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L115)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the error-handling code below should be outside of this block, because if we fail to read both the root and identity certs, we still need to report errors.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 368 at r7](https://reviewable.io/reviews/grpc/grpc/24600#-MLnI1oD4VVDzv0P6HyX:-MLsP2Y03LGEgFjpYKJV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/33c991fa975a92ed93168b5cc968c00de1a1c78c/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L368)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This will never be null, so there's no point in this check.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-12 16:15 UTC, markdroth requested changes
This is looking pretty good!  There are still a couple of edge cases that I think we're not quite handling right, and I have some mostly-cosmetic comments on the tests.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MLxDzaz6A5HVYX7jjnI:b-mekn7u)* status: all files reviewed, 19 unresolved discussions (waiting on @yashykt and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiPG7s1ObueAK4IF1a:-MLteFyg0L42kSqd6Ulh:b-3j70e1) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L181)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sure, I've moved the code outside of the block.
I added a bunch of tests in `grpc_tls_certificate_provider_test.cc` and `grpc_tls_credentials_options_test.cc`, including the error case when the certs are watched but not delivered. Please take a look, thanks!
</blockquote></details>

The logic here still doesn't look quite right.  If `root_certificate_` has a previous value, but `root_certificate` (the new value returned by `ReadRootCertificateFile()`) is empty because the file has been deleted and the new read failed, then we won't clear out the existing value in `root_certificate_`.

Try something like this:

```
const bool root_cert_changed =
    root_certificate_.empty() != root_certificate.has_value() ||
    root_certificate_ != *root_certificate;
root_certificate_ = std::move(*root_certificate);
const bool identity_cert_changed =
    pem_key_cert_pairs_.empty() != pem_key_cert_pairs.has_value() ||
    pem_key_cert_pairs_ != *pem_key_cert_pairs;
pem_key_cert_pairs_ = std::move(*pem_key_cert_pairs);
if (root_changed || identity_changed) {
  ExecCtx exec_ctx;
  grpc_error* root_cert_error = GRPC_ERROR_CREATE_FROM_STATIC_STRING(
      "unable to read root cert");
  grpc_error* identity_cert_error = GRPC_ERROR_CREATE_FROM_STATIC_STRING(
      "unable to read identity cert");
  for (const auto& p : watcher_info) {
    const std::string& cert_name = p.first;
    const WatcherInfo& info = p.second;
    distributor_->SetKeyMaterials(cert_name, root_certificate_,
                                  pem_key_cert_pairs_);
    const bool report_root_error =
        info.root_being_watched && root_certificate_.empty();
    const bool report_identity_error =
        info.identity_being_watched && pem_key_cert_pairs_.empty();
    if (report_root_error || report_identity_error) {
      distributor_->SetErrorForCert(
          cert_name,
          report_root_error ? GRPC_ERROR_REF(root_cert_error) : GRPC_ERROR_NONE,
          report_identity_error ? GRPC_ERROR_REF(identity_cert_error) : GRPC_ERROR_NONE);
    }
  }
  GRPC_ERROR_UNREF(root_cert_error);
  GRPC_ERROR_UNREF(identity_cert_error);
}
```
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 57 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtc9bUCfRbDS4yQxoe:-MLtc9bUCfRbDS4yQxof:b5rkjcn) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L57)):*
> ```cpp
>       watcher_info_.erase(cert_name);
>     }
>     if (root_certificate.has_value() || pem_key_cert_pairs.has_value()) {
> ```

I think this also needs to report an error to the distributor if the root or identity cert is being watched but no corresponding cert has been provided.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 129 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtcrebEIfNodtgcdUk:-MLtcrebEIfNodtgcdUl:b-cywxf) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L129)):*
> ```cpp
>                                     pem_key_cert_pairs);
>     }
>     absl::optional<grpc_error*> root_cert_error;
> ```

I don't think these need to use `absl::optional<>`.  Just initialize the errors to `GRPC_ERROR_NONE` and then check if they have a different value below.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 197 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtigMc9CzHBUK9ctfd:-MLte-Zs9RUCJjvoC4E2:b-di9dgb) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L197)):*
> ```cpp
>       absl::optional<grpc_error*> root_cert_error;
>       absl::optional<grpc_error*> identity_cert_error;
>       if (watcher_info.root_being_watched && !root_certificate.has_value()) {
> ```

I think this needs to look at  `root_certificate_`, not `root_certificate`, because we used `std::move()` to move the latter to the former above.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 202 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtinYTCnKMu30Fuv4V:-MLtinYTCnKMu30Fuv4W:b-g7cxkt) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L202)):*
> ```cpp
>       }
>       if (watcher_info.identity_being_watched &&
>           !pem_key_cert_pairs.has_value()) {
> ```

Similar problem here.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 38 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtj-J2CEHOEo33Y8VG:-MLtj-J2CEHOEo33Y8VH:b-ux15mg) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/test/core/security/grpc_tls_certificate_provider_test.cc#L38)):*
> ```cpp
> #define INVALID_PATH "invalid/path"
> 
> namespace testing {
> ```

Suggest putting this inside of namespace `grpc_core`, so that you don't need to say `grpc_core::` anywhere in this file.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 50 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtjUPC5yuQgtlmlRgA:-MLtjUPC5yuQgtlmlRgB:bvt4p68) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/test/core/security/grpc_tls_certificate_provider_test.cc#L50)):*
> ```cpp
>   class TlsCertificatesTestWatcher;
> 
>   static grpc_core::PemKeyCertPairList MakeCertKeyPairs(const char* private_key,
> ```

Methods should be defined after structs and classes, as per the style guide.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 285 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLx9him6FKK9eWIVYDj:-MLx9him6FKK9eWIVYDk:b-n5696k) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/test/core/security/grpc_tls_certificate_provider_test.cc#L285)):*
> ```cpp
>   EXPECT_THAT(watcher_state_1->GetErrorQueue(),
>               testing::ElementsAre(ErrorInfo(kRootError, kIdentityError)));
>   EXPECT_EQ(watcher_state_1->GetCredentialQueue().size(), 0);
> ```

Suggest writing this as:

```
EXPECT_EQ(watcher_state_1->GetCredentialQueue(), testing::ElementsAre());
```

This will yield a better error message when the expectation fails.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 292 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLx9sE039YbfnFoYWgE:-MLx9sE039YbfnFoYWgF:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/test/core/security/grpc_tls_certificate_provider_test.cc#L292)):*
> ```cpp
>   EXPECT_THAT(watcher_state_2->GetErrorQueue(),
>               testing::ElementsAre(ErrorInfo(kRootError, "")));
>   EXPECT_EQ(watcher_state_2->GetCredentialQueue().size(), 0);
> ```

Same here.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 299 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLx9uFIC-Jq8SdQg_jM:-MLx9uFJBfXs860fZ [...]

2020-11-12 18:22 UTC, yashykt requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: all files reviewed, 20 unresolved discussions (waiting on @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 104 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLxfu5k2RSA9Jyms_MX:-MLxfu5k2RSA9Jyms_MY:b-m4mz46) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L104)):*
> ```cpp
>       "FileWatcherCertificateProvider_refreshing_thread", thread_lambda, this);
>   refresh_thread_.Start();
>   distributor_->SetWatchStatusCallback([this](std::string cert_name,
> ```

I ran into this while debugging my end2end test for xds. We need to make sure that to unset this callback with
`distributor_->SetWatchStatusCallback(nullptr)` otherwise it results in a segfault, since distributors can outlive their certificate providers


<!-- Sent from Reviewable.io -->

2020-11-13 18:04 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: all files reviewed, 20 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiPG7s1ObueAK4IF1a:-MLyWV7K7WcOJvvblQZM:b-u1xtvo) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L181)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The logic here still doesn't look quite right.  If `root_certificate_` has a previous value, but `root_certificate` (the new value returned by `ReadRootCertificateFile()`) is empty because the file has been deleted and the new read failed, then we won't clear out the existing value in `root_certificate_`.

Try something like this:

```
const bool root_cert_changed =
    root_certificate_.empty() != root_certificate.has_value() ||
    root_certificate_ != *root_certificate;
root_certificate_ = std::move(*root_certificate);
const bool identity_cert_changed =
    pem_key_cert_pairs_.empty() != pem_key_cert_pairs.has_value() ||
    pem_key_cert_pairs_ != *pem_key_cert_pairs;
pem_key_cert_pairs_ = std::move(*pem_key_cert_pairs);
if (root_changed || identity_changed) {
  ExecCtx exec_ctx;
  grpc_error* root_cert_error = GRPC_ERROR_CREATE_FROM_STATIC_STRING(
      "unable to read root cert");
  grpc_error* identity_cert_error = GRPC_ERROR_CREATE_FROM_STATIC_STRING(
      "unable to read identity cert");
  for (const auto& p : watcher_info) {
    const std::string& cert_name = p.first;
    const WatcherInfo& info = p.second;
    distributor_->SetKeyMaterials(cert_name, root_certificate_,
                                  pem_key_cert_pairs_);
    const bool report_root_error =
        info.root_being_watched && root_certificate_.empty();
    const bool report_identity_error =
        info.identity_being_watched && pem_key_cert_pairs_.empty();
    if (report_root_error || report_identity_error) {
      distributor_->SetErrorForCert(
          cert_name,
          report_root_error ? GRPC_ERROR_REF(root_cert_error) : GRPC_ERROR_NONE,
          report_identity_error ? GRPC_ERROR_REF(identity_cert_error) : GRPC_ERROR_NONE);
    }
  }
  GRPC_ERROR_UNREF(root_cert_error);
  GRPC_ERROR_UNREF(identity_cert_error);
}
```
</blockquote></details>

I have a few questions about the above snippet. I don't fully understand the logic here so I am not able to make the right change.
1. 
```
const bool root_cert_changed = root_certificate_.empty() != root_certificate.has_value() || root_certificate_ != *root_certificate;
```
if `root_certificate_.empty() != root_certificate.has_value() `, that indicates the root certs are not changed, right? Do we want something like this:
```
const bool root_cert_changed =  (!root_certificate.has_value() && !root_certificate_.empty()) || (root_certificate.has_value() && root_certificate_ != *root_certificate);
```
2.
`root_certificate_ = std::move(*root_certificate);` won't always work, because there are cases when root_certificate is absl::nullopt. should this be
```
if (root_cert_changed) {
      if (root_certificate.has_value()) {
        root_certificate_ = std::move(*root_certificate);
      } else {
        root_certificate_ = "";
      }
    }
``` 
Right now, I am treating `root_certificate_` as the cache of most recent *valid* root cert, but if we go this way, it seems we are treating it as the most recent root cert, no matter whether valid or not. If so, later when we call `SetKeyMaterials`, we might also want to check if `root_certificate_` is reverted back to an empty string.
Anyway, I changed the code a bit so it shouldn't have the `std::move()` problem mentioned below. Could you please take a look please? Also, feel free to let me know if you find better ways to structure the code. Thank you so much!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 57 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtc9bUCfRbDS4yQxoe:-MLxiEB10rc4252BubIP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this also needs to report an error to the distributor if the root or identity cert is being watched but no corresponding cert has been provided.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 104 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLxfu5k2RSA9Jyms_MX:-MLxiVdzECClLvuMOjhY:bqkoz6t) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L104)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I ran into this while debugging my end2end test for xds. We need to make sure that to unset this callback with
`distributor_->SetWatchStatusCallback(nullptr)` otherwise it results in a segfault, since distributors can outlive their certificate providers
</blockquote></details>

Yeah, thanks for reminding! I think we already reset it in `FileWatcherCertificateProvider` but I missed it in `StaticDataCertificateProvider`. I will add it back.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 129 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtcrebEIfNodtgcdUk:-MLxltTLBRPdbCi7UvA9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L129)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think these need to use `absl::optional<>`.  Just initialize the errors to `GRPC_ERROR_NONE` and then check if they have a different value below.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 197 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtigMc9CzHBUK9ctfd:-MLyWkXiEu0vpVsOW4eO:b-7uwc84) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L197)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this needs to look at  `root_certificate_`, not `root_certificate`, because we used `std::move()` to move the latter to the former above.
</blockquote></details>

Sure, I changed the code a bit to avoid this problem. Could you please take a look? Thanks!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 202 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtinYTCnKMu30Fuv4V:-MLyWkqZ9omKa6Loj9eU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L202)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similar problem here.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 38 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLtj-J2CEHOEo33Y8VG:-MLyvIJADdRFlYxnwzvA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/test/core/security/grpc_tls_certificate_provider_test.cc#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest putting this inside of namespace `grpc_core`, so that you don't need to say `grpc_core::` anywhere in this file.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_ [...]

2020-11-13 19:17 UTC, yashykt commented
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 104 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLxfu5k2RSA9Jyms_MX:-MM21Od88_05Sosk12Rq:b-x4iedk) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L104)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Yeah, thanks for reminding! I think we already reset it in `FileWatcherCertificateProvider` but I missed it in `StaticDataCertificateProvider`. I will add it back.
</blockquote></details>

It's fine in that case. I'm doing it as part of my PR https://github.com/grpc/grpc/pull/24643


<!-- Sent from Reviewable.io -->

2020-11-16 01:12 UTC, ZhenLian reviewed
Thanks for the review so far!
I finally solved the TSAN issue in test `FileWatcherCertificateProviderOnCertificateRefreshed` and `ClientOptionsWithCertWatcherProviderOnCertificateRefreshed`. It was not due to the  call to `gpr_sleep_until`. The actual reason is because when we compare the actual certificate contents with the expected ones, it is actually reading the certificate contents, and we have another thread that may change the contents, hence we need to avoid that. 
I've updated the code to reflect to change and it should be good to review again. Please let me know How it looks. Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MMDZVLZ-RovMJ1J9qyi:b-kdo9k7)* status: 17 of 22 files reviewed, 19 unresolved discussions (waiting on @markdroth)

___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 179 at r8](https://reviewable.io/reviews/grpc/grpc/24600#-MLxD1Dk2ppgfJzcM81w:-MMDacMa9izzZlSeTrqw:b-8opby3) ([raw file](https://github.com/grpc/grpc/blob/348ebf2d25b230aee7487f48d85543fde7c773fa/test/core/security/grpc_tls_credentials_options_test.cc#L179)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should add a test that we fall back to system root certs when using mTLS if the provider is not being asked to watch root certs.
</blockquote></details>

Can we also put this in a separate PR?


<!-- Sent from Reviewable.io -->

2020-11-16 17:11 UTC, markdroth requested changes
This is looking really good!  Most of my remaining comments are cosmetic issues in the tests, although there is still one remaining behavioral issue in the code itself.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 5 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MMH1Q_H8OL66jzVwXQ0:b-9wfbym)* status: all files reviewed, 15 unresolved discussions (waiting on @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiPG7s1ObueAK4IF1a:-MMGsQfTDT3ZnTI-o0GD:bc6q6z6) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L181)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I have a few questions about the above snippet. I don't fully understand the logic here so I am not able to make the right change.
1. 
```
const bool root_cert_changed = root_certificate_.empty() != root_certificate.has_value() || root_certificate_ != *root_certificate;
```
if `root_certificate_.empty() != root_certificate.has_value() `, that indicates the root certs are not changed, right? Do we want something like this:
```
const bool root_cert_changed =  (!root_certificate.has_value() && !root_certificate_.empty()) || (root_certificate.has_value() && root_certificate_ != *root_certificate);
```
2.
`root_certificate_ = std::move(*root_certificate);` won't always work, because there are cases when root_certificate is absl::nullopt. should this be
```
if (root_cert_changed) {
      if (root_certificate.has_value()) {
        root_certificate_ = std::move(*root_certificate);
      } else {
        root_certificate_ = "";
      }
    }
``` 
Right now, I am treating `root_certificate_` as the cache of most recent *valid* root cert, but if we go this way, it seems we are treating it as the most recent root cert, no matter whether valid or not. If so, later when we call `SetKeyMaterials`, we might also want to check if `root_certificate_` is reverted back to an empty string.
Anyway, I changed the code a bit so it shouldn't have the `std::move()` problem mentioned below. Could you please take a look please? Also, feel free to let me know if you find better ways to structure the code. Thank you so much!
</blockquote></details>

I think the right way to model this is to say that `root_certificate_` is the most recent data, which will be empty if the most recent read failed.  I think we always want to report the most recent data for any given cert, but if the most recent data is an error, that means we report an error instead of reporting cert data.

To say this another way, I think the function of the provider is to report the most recent data it has.  It is not responsible for caching old data in case of an error; that happens in the distributor layer.

Given that, I think that `root_certificate_.empty() != root_certificate.has_value()` *does* mean that the root cert has changed, because it's gone from a valid value to an error (or vice versa).

If `root_certificate_ = std::move(*root_certificate)` won't work when `root_certificate` does not have a value, then it's fine to expand it into the two cases you suggest.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 53 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGs1-B1Ly3ka3wbclh:-MMGs1-CElNpTYC3DWFz:b-gq2tse) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L53)):*
> ```cpp
>       pem_key_cert_pairs = pem_key_cert_pairs_;
>     }
>     const bool root_has_update = root_certificate.has_value();
> ```

Please move these two lines down to right before they are used (line 59).
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 160 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGvvCAE0zR-94A45lJ:-MMGvvCBDqV-DqDzGPKV:b-ectlqj) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L160)):*
> ```cpp
>    private:
>     WatcherState* state_;
>     Mutex watcher_mu_;
> ```

This mutex should actually live in `WatcherState`, not in the watcher itself, because it's actually guarding the data members of `WatcherState`.

This will eliminate the need for the `WatcherMutex()` method.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 165 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGy5xa8uAm3KhxUKOO:-MMGy5xa8uAm3KhxUKOP:b-8t0xkf) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L165)):*
> ```cpp
>   void SetUp() override {
>     LoadCredentialData(CA_CERT_PATH, 1, &root_cert_);
>     LoadCredentialData(CA_CERT_PATH, 0, &root_cert_no_terminator_);
> ```

Why do we have to read these files twice just to get a copy without the null terminator?  It looks like the only reason we need the copy without the null terminator is to write it back to a file.  But in that case, can't we just write all but the last byte of the data we've already read?
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 187 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGw7fb7irSS3LMcOoG:-MMGw7fb7irSS3LMcOoH:bkkhnp8) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L187)):*
> ```cpp
>   }
> 
>   static void LoadCredentialData(const char* path, int add_null_terminator,
> ```

The `add_null_terminator` argument should be a `bool`, not an `int`.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 187 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGzQ8-7xA0yuZa_7SA:-MMGzQ8-7xA0yuZa_7SB:b-1c9wjc) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L187)):*
> ```cpp
>   }
> 
>   static void LoadCredentialData(const char* path, int add_null_terminator,
> ```

This can return the string instead of providing it via an output parameter.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 320 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGwsrABW6Cqhhwfnbs:-MMGwsrABW6Cqhhwfnbt:bxdy8c1) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L320)):*
> ```cpp
>        FileWatcherCertificateProviderOnCertificateRefreshed) {
>   // Create a temporary file and copy root cert data into it.
>   FILE* root_cert_tmp = nullptr;
> ```

You can probably create a helper function to write these temp files and return the file name.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 363 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGyhNnEFOSGoeLQM2n:-MMGyhNnEFOSGoeLQM2o:b-v5jagb) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L363)):*
> ```cpp
>                   root_cert_, MakeCertKeyPairs(private_key_.c_str(),
>                                                cert_chain_.c_str()))));
>   // Copy new data to files. We copy root cert data into identity key file,
> ```

This seems kind of hacky.  In particular, this will break when we add the check that the private key and the identity cert match.

How about simply using a second set of valid cert data here?
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 366 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGx3do51Kiqb1r7XCv:-MMGx3do51Kiqb1r7XCw:b-o33c2) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_cer [...]

2020-11-17 07:38 UTC, ZhenLian reviewed
All comments resolved! Please let me know how it looks now. Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MMK7oB356R606WB7IRG:b-t6hp95)* status: all files reviewed, 15 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/24600#-MLiPG7s1ObueAK4IF1a:-MMJNlHoCc9q8o18cB8g:b-r34cz6) ([raw file](https://github.com/grpc/grpc/blob/0bd117a367b750d0856df9e3de283d8ee75ec509/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L181)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the right way to model this is to say that `root_certificate_` is the most recent data, which will be empty if the most recent read failed.  I think we always want to report the most recent data for any given cert, but if the most recent data is an error, that means we report an error instead of reporting cert data.

To say this another way, I think the function of the provider is to report the most recent data it has.  It is not responsible for caching old data in case of an error; that happens in the distributor layer.

Given that, I think that `root_certificate_.empty() != root_certificate.has_value()` *does* mean that the root cert has changed, because it's gone from a valid value to an error (or vice versa).

If `root_certificate_ = std::move(*root_certificate)` won't work when `root_certificate` does not have a value, then it's fine to expand it into the two cases you suggest.
</blockquote></details>

OK. Sounds good. I will follow that idea.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 53 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGs1-B1Ly3ka3wbclh:-MMIk8NbECld9ARyVRu4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L53)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move these two lines down to right before they are used (line 59).
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 160 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGvvCAE0zR-94A45lJ:-MMIav9k8SbcCNwm_RMc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L160)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This mutex should actually live in `WatcherState`, not in the watcher itself, because it's actually guarding the data members of `WatcherState`.

This will eliminate the need for the `WatcherMutex()` method.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 165 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGy5xa8uAm3KhxUKOO:-MMHmHxHBoksz1MWWtC5:b-o7518c) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L165)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why do we have to read these files twice just to get a copy without the null terminator?  It looks like the only reason we need the copy without the null terminator is to write it back to a file.  But in that case, can't we just write all but the last byte of the data we've already read?
</blockquote></details>

Yeah, that would be much simpler. Thanks for the suggestion!
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 187 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGw7fb7irSS3LMcOoG:-MMHmawT-Y3sMqDaFFk5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L187)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `add_null_terminator` argument should be a `bool`, not an `int`.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 187 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGzQ8-7xA0yuZa_7SA:-MMHmnsxBZ_J3k-wqJJm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L187)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can return the string instead of providing it via an output parameter.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 320 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGwsrABW6Cqhhwfnbs:-MMIUVhe46QpnEag-p0Z:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L320)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can probably create a helper function to write these temp files and return the file name.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 363 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGyhNnEFOSGoeLQM2n:-MMHtAhd8bnzkjKIkwGh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L363)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This seems kind of hacky.  In particular, this will break when we add the check that the private key and the identity cert match.

How about simply using a second set of valid cert data here?
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 366 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGx3do51Kiqb1r7XCv:-MMIOrudCFQEfv8idQKS:b-58ehbx) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L366)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Note that this is a *very* unclean way of updating these files, because it leaves them in a very inconsistent state.  The call to `fopen()` will truncate the file to 0, and the call to `fwrite()` may be split into multiple writes at the syscall layer.  In between any of those operations, the provider may attempt to reload and get an inconsistent view of the file.

The right way to do this is to (1)  write the file to a different name, (2) remove the original file, then (3) rename the new file to the original name.  The provider may happen to try to read between steps 2 and 3, in which case it will see that the file does not exist, but it will try again in that case.  But it will not get a partial read, which will cause it to report incorrect data.
</blockquote></details>

Sure, I changed the code structure a bit. Please take a look, thanks!
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 372 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGxtR040FVmpJxtvaw:-MMIP9pG1aNQXQjfrzYV:bfubdv1) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L372)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In addition to the above, this is not using the atomic approach to updating the identity and key files.  This should be done by writing both files to a new directory and then either updating a symlink or renaming the directory.
</blockquote></details>

Yeah. I would probably use that way in the e2e tests. We will probably also need to add some more syst [...]

2020-11-17 16:13 UTC, markdroth requested changes
This is very close now!  My only remaining significant comment is the one about atomically writing the private key and identity cert files.  I want to make sure that the way this is being done is not going to cause flakiness.

Please let me know if you have any questions.  Thanks!

> Reviewed 7 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MMLym8UEKHma4cJt-uL:b-66h5nl)* status: all files reviewed, 11 unresolved discussions (waiting on @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 232 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLvBgCA1PaGRrU41LD:-MMLvBgCA1PaGRrU41LE:b-cakyo9) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L232)):*
> ```cpp
>       }
>       if (root_to_report.has_value() || identity_to_report.has_value()) {
>         distributor_->SetKeyMaterials(cert_name, root_to_report,
> ```

Please use `std::move()` for `root_to_report` and `identity_to_report`.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 160 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGvvCAE0zR-94A45lJ:-MMLwZt_77Ans3RHClnC:b-dms67b) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L160)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can delete the mutex here now.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 372 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGxtR040FVmpJxtvaw:-MMLxWc_ED2_CTkKtnfI:b8zzj9) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L372)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Yeah. I would probably use that way in the e2e tests. We will probably also need to add some more system call primitives in gpr to do directory operation, such as `mkdtemp`, like the `mkstemp` we have in `gpr_tmpfile`.
</blockquote></details>

Given the way you're currently doing this, though, how do we know this won't cause test flakiness?

I suggest running this test 1000x on RBE for each of opt, dbg, asan, msan, tsan, and ubsan builds, just to make sure this is not going to be flaky.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 90 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLvSIq1SIZEVWTBEeR:-MMLvSIq1SIZEVWTBEeS:b-6kkexk) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L90)):*
> ```cpp
>     std::deque<CredentialInfo> cert_update_queue;
>     std::deque<ErrorInfo> error_queue;
>     Mutex mu_;
> ```

No need for `_` suffix in a struct.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 108 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLvhz0A1XtNoXxT1hx:-MMLvhz0A1XtNoXxT1hy:b-cq8dmq) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L108)):*
> ```cpp
>   class TmpFile {
>    public:
>     explicit TmpFile(std::string data) {
> ```

This parameter should be `absl::string_view` to avoid making an unnecessary copy.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 125 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLwtWV1gvcRvClhi5k:-MMLwtWV1gvcRvClhi5l:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L125)):*
> ```cpp
> 
>     // Load the new data in an atomic way.
>     void LoadData(std::string data) {
> ```

Same here.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 125 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLx-eZ0hgMzFiINAU7:-MMLx-eZ0hgMzFiINAU8:b-h98rxn) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L125)):*
> ```cpp
> 
>     // Load the new data in an atomic way.
>     void LoadData(std::string data) {
> ```

Suggest calling this something like `RewriteFile()`.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 127 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLwOqQBExvK1Xm_Kv6:-MMLwOqQBExvK1Xm_Kv7:bkvjvq5) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L127)):*
> ```cpp
>     void LoadData(std::string data) {
>       // Create a new file containing new data.
>       FILE* file_descriptor = nullptr;
> ```

A number of lines of code here are duplicated from the ctor.  Consider refactoring into a helper function.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 146 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLw9PZ6M0e7KpwkpZ7:-MMLw9PZ6M0e7KpwkpZ8:b-l7sdih) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L146)):*
> ```cpp
> 
>    private:
>     FILE* file_descriptor_ = nullptr;
> ```

Why does this data member exist?  Its value never seems to pass between functions, so it seems like it could just be a local variable.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 393 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLx7l60nHOnHW3oz9y:-MMLx7l60nHOnHW3oz9z:bazcwyp) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L393)):*
> ```cpp
>   // Clean up.
>   CancelWatch(watcher_state_1);
>   GPR_ASSERT(remove(tmp_root_cert.name()) == 0);
> ```

Removing the file should be done in the `TmpFile` dtor, so that it doesn't have to be done  manually in each individual test.
___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 47 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLyHxC1k5T6_zl4wXf:-MMLyHxC1k5T6_zl4wXg:b-csh4mm) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_credentials_options_test.cc#L47)):*
> ```cpp
> class GrpcTlsCredentialsOptionsTest : public ::testing::Test {
>  protected:
>   class TmpFile {
> ```

Same comments apply to this class as in the other test.

Consider moving this duplicate code into a common library somewhere, where it can be used by both tests.


<!-- Sent from Reviewable.io -->

2020-11-18 08:31 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: all files reviewed, 11 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 232 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLvBgCA1PaGRrU41LD:-MMMa6CE85qbkM6nQ6zP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L232)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `std::move()` for `root_to_report` and `identity_to_report`.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 372 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGxtR040FVmpJxtvaw:-MMPStQR0ddZC0yTLNhK:b-judy7d) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L372)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Given the way you're currently doing this, though, how do we know this won't cause test flakiness?

I suggest running this test 1000x on RBE for each of opt, dbg, asan, msan, tsan, and ubsan builds, just to make sure this is not going to be flaky.
</blockquote></details>

Sure, sounds good! I've verified that none of them are flaky. Please see a invocation list below:

//test/core/security:grpc_tls_certificate_provider_test:
opt: 
https://source.cloud.google.com/results/invocations/6c53dda8-9b14-40b8-b2e9-c948d87eb43a
dbg:
]https://source.cloud.google.com/results/invocations/96c8a66a-4e6a-4f0d-be02-1cedff8f1254
asan:
https://source.cloud.google.com/results/invocations/98fc8f7e-48b0-40e3-b8ba-05fc077f37ba
msan:
https://source.cloud.google.com/results/invocations/71a8e760-6d77-48a0-b217-9d8352fe687d
tsan:
https://source.cloud.google.com/results/invocations/42b13b4b-0814-4ee4-ae61-a45435b26f3e
ubsan:
https://source.cloud.google.com/results/invocations/dbbe3421-0277-46f3-b836-a87fb7395f49

//test/core/security:grpc_tls_credentials_options_test:
opt: 
https://source.cloud.google.com/results/invocations/b8d5c191-28cd-4c60-81ab-7c7881e0fde1
dbg:
https://source.cloud.google.com/results/invocations/69344d8e-641d-41e7-9fde-63650c17ce0e
asan:
https://source.cloud.google.com/results/invocations/e0fafc93-d9b3-4e0a-b1f8-e17aae10f71c
msan:
https://source.cloud.google.com/results/invocations/acd11d10-6817-4b5d-8de6-a0498389d9af
tsan:
https://source.cloud.google.com/results/invocations/b1f2b308-9f6d-4d22-9b2d-89b29c8ad0fa
ubsan:
https://source.cloud.google.com/results/invocations/283d4f11-e130-4e47-9a67-7d7ada81354e
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 90 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLvSIq1SIZEVWTBEeR:-MMMJ1P95PNZJiMSo5ZN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L90)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `_` suffix in a struct.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 108 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLvhz0A1XtNoXxT1hx:-MMMe21T2rJ4k7ijBeUV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L108)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This parameter should be `absl::string_view` to avoid making an unnecessary copy.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 125 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLwtWV1gvcRvClhi5k:-MMMe2h-2s7PRI0L4Vr8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L125)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 125 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLx-eZ0hgMzFiINAU7:-MMMf0J1DoLsTmieVeCB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L125)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this something like `RewriteFile()`.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 127 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLwOqQBExvK1Xm_Kv6:-MMMmBjO7ct-iOqkWOoY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L127)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

A number of lines of code here are duplicated from the ctor.  Consider refactoring into a helper function.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 146 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLw9PZ6M0e7KpwkpZ7:-MMMf9Vu35kQjvtRgdEC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L146)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why does this data member exist?  Its value never seems to pass between functions, so it seems like it could just be a local variable.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 393 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLx7l60nHOnHW3oz9y:-MMMg5yzDU9QF76x-6LA:b-ctgy5f) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L393)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Removing the file should be done in the `TmpFile` dtor, so that it doesn't have to be done  manually in each individual test.
</blockquote></details>

It seems in the error cases, we wanted to remove the files ahead of verifying errors, so I left the use of removing files to the main test functions. 
___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 47 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLyHxC1k5T6_zl4wXf:-MMM_wqPBsCehoiYKuoc:bq3k3uu) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_credentials_options_test.cc#L47)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same comments apply to this class as in the other test.

Consider moving this duplicate code into a common library somewhere, where it can be used by both tests.
</blockquote></details>

SG, that's a good idea!


<!-- Sent from Reviewable.io -->

2020-11-18 16:02 UTC, markdroth requested changes
Just a few minor comments remaining, mostly cosmetic at this point!

Please let me know if you have any questions.  Thanks!

> Reviewed 10 of 10 files at r12.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MMR4tFv7206OCz14Gkl:bm9zonh)* status: all files reviewed, 8 unresolved discussions (waiting on @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 128 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR288HEQhhT0jWgOwS:-MMR288HEQhhT0jWgOwT:b2kuw2b) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L128)):*
> ```objc
>   // Guards members below.
>   grpc_core::Mutex mu_;
>   // The most-recent credential data, no matter valid or not.
> ```

Might be clearer to say "Will be empty if the most recent read attempt failed."
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 372 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGxtR040FVmpJxtvaw:-MMR2sF05nPGGR7H7XfU:b-amriy6) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L372)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sure, sounds good! I've verified that none of them are flaky. Please see a invocation list below:

//test/core/security:grpc_tls_certificate_provider_test:
opt: 
https://source.cloud.google.com/results/invocations/6c53dda8-9b14-40b8-b2e9-c948d87eb43a
dbg:
]https://source.cloud.google.com/results/invocations/96c8a66a-4e6a-4f0d-be02-1cedff8f1254
asan:
https://source.cloud.google.com/results/invocations/98fc8f7e-48b0-40e3-b8ba-05fc077f37ba
msan:
https://source.cloud.google.com/results/invocations/71a8e760-6d77-48a0-b217-9d8352fe687d
tsan:
https://source.cloud.google.com/results/invocations/42b13b4b-0814-4ee4-ae61-a45435b26f3e
ubsan:
https://source.cloud.google.com/results/invocations/dbbe3421-0277-46f3-b836-a87fb7395f49

//test/core/security:grpc_tls_credentials_options_test:
opt: 
https://source.cloud.google.com/results/invocations/b8d5c191-28cd-4c60-81ab-7c7881e0fde1
dbg:
https://source.cloud.google.com/results/invocations/69344d8e-641d-41e7-9fde-63650c17ce0e
asan:
https://source.cloud.google.com/results/invocations/e0fafc93-d9b3-4e0a-b1f8-e17aae10f71c
msan:
https://source.cloud.google.com/results/invocations/acd11d10-6817-4b5d-8de6-a0498389d9af
tsan:
https://source.cloud.google.com/results/invocations/b1f2b308-9f6d-4d22-9b2d-89b29c8ad0fa
ubsan:
https://source.cloud.google.com/results/invocations/283d4f11-e130-4e47-9a67-7d7ada81354e

</blockquote></details>

Okay, thanks.  Please add a TODO here about fixing this to write the files in an atomic way.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 393 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLx7l60nHOnHW3oz9y:-MMR2h5z559PAKYJOI-u:bj3pbz7) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L393)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

It seems in the error cases, we wanted to remove the files ahead of verifying errors, so I left the use of removing files to the main test functions. 
</blockquote></details>

You can handle that by deleting the `TmpFile` object early in those cases.
___
*[test/core/security/tls_utils.h, line 36 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR3Q5T5X-_gokBqPym:-MMR3Q5T5X-_gokBqPyn:bdbx51s) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.h#L36)):*
> ```objc
> 
>  private:
>   void CreateTmpFileAndWriteData(absl::string_view credential_data,
> ```

This can return the filename instead of having it be an output parameter.
___
*[test/core/security/tls_utils.h, line 44 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR35GqDPnQgymx7dWe:-MMR35GqDPnQgymx7dWf:b4kuolc) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.h#L44)):*
> ```objc
> PemKeyCertPairList MakeCertKeyPairs(const char* private_key, const char* certs);
> 
> std::string GetCredentialData(const char* path);
> ```

Suggest calling this `GetFileContents()`.
___
*[test/core/security/tls_utils.cc, line 42 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR4R8o0VIk9eDdo8Ry:-MMR4R8o0VIk9eDdo8Rz:b9ldqbf) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.cc#L42)):*
> ```cpp
>   GPR_ASSERT(rename(name, name_) == 0);
>   gpr_free(name);
>   GPR_ASSERT(name_ != nullptr);
> ```

I don't think this assertion is actually useful here, since (a) we're already using `name_` above this and (b) we know that `name_` will be set by the ctor.
___
*[test/core/security/tls_utils.cc, line 49 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR3YwMC3eV-FHxmDJN:-MMR3YwMC3eV-FHxmDJO:b7nfoy9) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.cc#L49)):*
> ```cpp
>   FILE* file_descriptor =
>       gpr_tmpfile("GrpcTlsCertificateProviderTest", file_name_ptr);
>   // When calling fwrite, we have to read the credential in the size of
> ```

It might make sense to strip this off in the caller rather than doing it here.  That way, this `TmpFile` class is more general-purpose and can be used for other things.
___
*[test/core/security/tls_utils.cc, line 77 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR3nF6Dt93S7ixeq4O:-MMR3nF6Dt93S7ixeq4P:bx4jukw) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.cc#L77)):*
> ```cpp
>   grpc_slice slice = grpc_empty_slice();
>   GPR_ASSERT(GRPC_LOG_IF_ERROR("load_file", grpc_load_file(path, 1, &slice)));
>   std::string credential = std::string(StringViewFromSlice(slice));
> ```

Another thought: Do we actually need this to be null-terminated, since we're returning it as a `std::string` instead of a `char*`?  Maybe we should just read it without adding the null terminator in the first place.


<!-- Sent from Reviewable.io -->

2020-11-18 21:18 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: all files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 128 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR288HEQhhT0jWgOwS:-MMRP6u93ieb577s0Dcm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L128)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Might be clearer to say "Will be empty if the most recent read attempt failed."
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 372 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGxtR040FVmpJxtvaw:-MMRWfR3DCV7FPhTZv5R:b5aqzti) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L372)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay, thanks.  Please add a TODO here about fixing this to write the files in an atomic way.
</blockquote></details>

Sure, sounds good!
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 393 at r11](https://reviewable.io/reviews/grpc/grpc/24600#-MMLx7l60nHOnHW3oz9y:-MMRWeKw9NNer4pkdVP1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/acef9e464410fe2c61caa2574bf960787becd012/test/core/security/grpc_tls_certificate_provider_test.cc#L393)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can handle that by deleting the `TmpFile` object early in those cases.
</blockquote></details>

Done.
___
*[test/core/security/tls_utils.h, line 36 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR3Q5T5X-_gokBqPym:-MMRdHZ89YIwY7k3fGoz:b-ot5b46) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.h#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can return the filename instead of having it be an output parameter.
</blockquote></details>

Sure. I think it might be better to use `std::string` instead of `char*`, and hide C-specific code inside the helper function.
___
*[test/core/security/tls_utils.h, line 44 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR35GqDPnQgymx7dWe:-MMRe3sj2JpxCCZBmzmq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.h#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `GetFileContents()`.
</blockquote></details>

Done.
___
*[test/core/security/tls_utils.cc, line 42 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR4R8o0VIk9eDdo8Ry:-MMReJwfDoZYSFavqC8q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.cc#L42)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this assertion is actually useful here, since (a) we're already using `name_` above this and (b) we know that `name_` will be set by the ctor.
</blockquote></details>

Done.
___
*[test/core/security/tls_utils.cc, line 49 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR3YwMC3eV-FHxmDJN:-MMSDEE96sHjixy3yJTI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.cc#L49)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It might make sense to strip this off in the caller rather than doing it here.  That way, this `TmpFile` class is more general-purpose and can be used for other things.
</blockquote></details>

Done.
___
*[test/core/security/tls_utils.cc, line 77 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR3nF6Dt93S7ixeq4O:-MMRgtfk3CyNn--8z3GN:bwrbxs4) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.cc#L77)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Another thought: Do we actually need this to be null-terminated, since we're returning it as a `std::string` instead of a `char*`?  Maybe we should just read it without adding the null terminator in the first place.
</blockquote></details>

I think the reason we have to add null terminator here is because we are comparing the result of this with the one we got from the provider main logic. In the main logic, we also added a null terminator(because the test credential data doesn't have the null terminator). 
And I think that's why when writing to temp files, we wanted to write n-1 bytes to the file. We are trying to make the tmp file on disk is the same as the test credential file, whose null terminator doesn't exist...


<!-- Sent from Reviewable.io -->

2020-11-18 21:47 UTC, markdroth requested changes
This is getting closer!

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MMSJmNGCMsd_6tA0dDQ:b79zqk9)* status: all files reviewed, 8 unresolved discussions (waiting on @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 97 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSGQ4Y1p8WNlxmg6UN:-MMSGQ4Y1p8WNlxmg6UO:bfphbks) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L97)):*
> ```objc
> 
>   // Force an update from the file system regardless of the interval.
>   void ForceUpdate();
> ```

As per discussion in the design doc, I think we should remove this.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 372 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGxtR040FVmpJxtvaw:-MMSJBsb3nokFCPHwmVt:b-q33tog) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L372)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sure, sounds good!
</blockquote></details>

I don't see the TODO.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 400 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSJGdi3K6ApkxjwHCQ:-MMSJGdi3K6ApkxjwHCR:bijcgtt) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/test/core/security/grpc_tls_certificate_provider_test.cc#L400)):*
> ```cpp
>        FileWatcherCertificateProviderWithGoodAtFirstThenDeletedBothCerts) {
>   // Create temporary files and copy cert data into it.
>   TmpFile* tmp_root_cert = new TmpFile(root_cert_, root_cert_.size() - 1);
> ```

Please use `unique_ptr<>` for these, so that we know there won't be a leak if we forget to delete them.

Same thing throughout.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 463 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSJPzD2FKgrRNHxKiW:-MMSJPzD2FKgrRNHxKiX:b-ao813v) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/test/core/security/grpc_tls_certificate_provider_test.cc#L463)):*
> ```cpp
>   // Clean up.
>   CancelWatch(watcher_state_1);
>   delete tmp_identity_key;
> ```

If these aren't going to be deleted until the end of the test, then they can just be allocated on the stack as local variables.  Only that one that needs to be deleted earlier has to be dynamically allocated.

Same thing throughout.
___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 411 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSJfKD6-hM6kSSWKVY:-MMSJfKD6-hM6kSSWKVZ:b-203xx3) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/test/core/security/grpc_tls_credentials_options_test.cc#L411)):*
> ```cpp
>        ClientOptionsWithCertWatcherProviderOnDeletedFiles) {
>   // Create temporary files and copy cert data into it.
>   TmpFile* tmp_root_cert = new TmpFile(root_cert_, root_cert_.size() - 1);
> ```

Same as in other file: Please use `unique_ptr<>` for these.
___
*[test/core/security/tls_utils.h, line 27 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSGbF59jDGSeCz0JRg:-MMSGbF59jDGSeCz0JRh:bmj6xl6) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/test/core/security/tls_utils.h#L27)):*
> ```objc
>   // Create a tmp file with the first |size_t| bytes of |credential_data|
>   // written in.
>   explicit TmpFile(absl::string_view credential_data, size_t length);
> ```

The additional parameter is not needed here.  The caller can trivially strip off the trailing null by passing in `cred_data.substr(0, cred_data.size() - 1)`.
___
*[test/core/security/tls_utils.h, line 31 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSGoS-5jFr1DT6_FqW:-MMSGoS-5jFr1DT6_FqX:b-38zbod) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/test/core/security/tls_utils.h#L31)):*
> ```objc
>   ~TmpFile();
> 
>   std::string name() { return name_; }
> ```

This should return a const reference, or else it will allocate a new string every time it's called.
___
*[test/core/security/tls_utils.cc, line 77 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR3nF6Dt93S7ixeq4O:-MMSHBvs50NxAyRsmwXs:bp5b5l6) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.cc#L77)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I think the reason we have to add null terminator here is because we are comparing the result of this with the one we got from the provider main logic. In the main logic, we also added a null terminator(because the test credential data doesn't have the null terminator). 
And I think that's why when writing to temp files, we wanted to write n-1 bytes to the file. We are trying to make the tmp file on disk is the same as the test credential file, whose null terminator doesn't exist...
</blockquote></details>

Why does the test's main logic have to add the null byte?  Any time we are representing the data as a string, we don't need the size to include the null byte.  And any time we are comparing a C-style string with a C++ string, we need to convert between them anyway, so we can remove the null byte at that point.

Basically, what I am saying here is that we should never store the null byte.  The only place we are doing that today is in `PemKeyCertPair`, where the key and cert are stored as C-style strings (and we have an existing TODO to fix that), but in that case we can convert to C++ strings to do a comparison.  The C++ string form (whether `absl::string_view` or `std::string`)  encodes the size and thus has no need to encode the null byte.

Note that `grpc_load_file()` actually returns a slice, which encodes the size read and does not need to be null terminated.  If we convert that slice directly to an `absl::string_view` or `std::string`, then we don't need the null terminator at all.  The only reason the null terminator would be needed is if we were going to convert the slice to a C-style string.


<!-- Sent from Reviewable.io -->

2020-11-19 00:09 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: all files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 97 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSGQ4Y1p8WNlxmg6UN:-MMSfV3C5bb-oFram-oy:b-cyjekj) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L97)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per discussion in the design doc, I think we should remove this.
</blockquote></details>

Would it be useful if we keep it in C core, while deleting the C++ API? Core API is not user facing, so it wouldn't have the API problem we mentioned in the discussion thread. 
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 372 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGxtR040FVmpJxtvaw:-MMSfu115VOQg_gsNbco:bv88qvb) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L372)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see the TODO.
</blockquote></details>

Ah, I added it above RewriteFile() function in `tls_utils.h`. If you think this might be a better place, please let me know, and I can surely change it.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 400 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSJGdi3K6ApkxjwHCQ:-MMSjPnX3HJPcZ08eP9K:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/test/core/security/grpc_tls_certificate_provider_test.cc#L400)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `unique_ptr<>` for these, so that we know there won't be a leak if we forget to delete them.

Same thing throughout.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 463 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSJPzD2FKgrRNHxKiW:-MMSjQ2y2iGnTos5icjT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/test/core/security/grpc_tls_certificate_provider_test.cc#L463)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If these aren't going to be deleted until the end of the test, then they can just be allocated on the stack as local variables.  Only that one that needs to be deleted earlier has to be dynamically allocated.

Same thing throughout.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 411 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSJfKD6-hM6kSSWKVY:-MMSkGMc4k0kG1P2xGQX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/test/core/security/grpc_tls_credentials_options_test.cc#L411)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as in other file: Please use `unique_ptr<>` for these.
</blockquote></details>

Done.
___
*[test/core/security/tls_utils.h, line 27 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSGbF59jDGSeCz0JRg:-MMSfOb86hOQURhGvV4c:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/test/core/security/tls_utils.h#L27)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The additional parameter is not needed here.  The caller can trivially strip off the trailing null by passing in `cred_data.substr(0, cred_data.size() - 1)`.
</blockquote></details>

Done.
___
*[test/core/security/tls_utils.h, line 31 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSGoS-5jFr1DT6_FqW:-MMSfNbr-YTgiwUxhjhj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/test/core/security/tls_utils.h#L31)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should return a const reference, or else it will allocate a new string every time it's called.
</blockquote></details>

Done.
___
*[test/core/security/tls_utils.cc, line 77 at r12](https://reviewable.io/reviews/grpc/grpc/24600#-MMR3nF6Dt93S7ixeq4O:-MMSbOxi0xf3vYY_8UzZ:bbwsn6w) ([raw file](https://github.com/grpc/grpc/blob/241b5c7707c3ad093c3992c6831c26c5020656ba/test/core/security/tls_utils.cc#L77)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why does the test's main logic have to add the null byte?  Any time we are representing the data as a string, we don't need the size to include the null byte.  And any time we are comparing a C-style string with a C++ string, we need to convert between them anyway, so we can remove the null byte at that point.

Basically, what I am saying here is that we should never store the null byte.  The only place we are doing that today is in `PemKeyCertPair`, where the key and cert are stored as C-style strings (and we have an existing TODO to fix that), but in that case we can convert to C++ strings to do a comparison.  The C++ string form (whether `absl::string_view` or `std::string`)  encodes the size and thus has no need to encode the null byte.

Note that `grpc_load_file()` actually returns a slice, which encodes the size read and does not need to be null terminated.  If we convert that slice directly to an `absl::string_view` or `std::string`, then we don't need the null terminator at all.  The only reason the null terminator would be needed is if we were going to convert the slice to a C-style string.
</blockquote></details>

Ah, I see. I think I was under the wrong impression that the file contents read by `grpc_load_file()` has to have a null at the end, because I saw some memory issue if we don't add it. That was actually caused by some mis-uses of string pointers when converting `grpc_slice` to std::string in `grpc_tls_certificate_provider.cc`. I've fixed them. Please take a look, thanks!


<!-- Sent from Reviewable.io -->

2020-11-19 15:24 UTC, markdroth requested changes
Only a few minor issues left!

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 5 files at r13, 9 of 9 files at r14.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MMW5iw97nFnVb9dvUxY:b-soxauc)* status: all files reviewed, 4 unresolved discussions (waiting on @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 97 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSGQ4Y1p8WNlxmg6UN:-MMW3gEH8AEynClCu6g-:b-g2stmp) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L97)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Would it be useful if we keep it in C core, while deleting the C++ API? Core API is not user facing, so it wouldn't have the API problem we mentioned in the discussion thread. 
</blockquote></details>

No, let's remove it from C-core as well.  There's no point in having it here if we don't have a use-case for it.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 318 at r14](https://reviewable.io/reviews/grpc/grpc/24600#-MMW3zhj2PM-iBhlz22V:-MMW3zhj2PM-iBhlz22W:b-k07eir) ([raw file](https://github.com/grpc/grpc/blob/082ecd68732826b9c9f3147a459635f4191fe87f/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L318)):*
> ```cpp
>     SliceWrapper key_slice, cert_slice;
>     grpc_error* key_error =
>         grpc_load_file(private_key_path.c_str(), 1, &key_slice.slice);
> ```

Now we should tell `grpc_load_file()` to not add the null byte.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 326 at r14](https://reviewable.io/reviews/grpc/grpc/24600#-MMW4MTJ4TDIww94bO0A:-MMW4MTJ4TDIww94bO0B:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/082ecd68732826b9c9f3147a459635f4191fe87f/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L326)):*
> ```cpp
>     }
>     grpc_error* cert_error =
>         grpc_load_file(identity_certificate_path.c_str(), 1, &cert_slice.slice);
> ```

Same here.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 372 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGxtR040FVmpJxtvaw:-MMW4ZJI6jpph-fxJovV:bb2nbyd) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L372)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Ah, I added it above RewriteFile() function in `tls_utils.h`. If you think this might be a better place, please let me know, and I can surely change it.
</blockquote></details>

I don't think that's the right place for it.  The `TmpFile` class is designed to write a single tempfile, and that functionality works fine.  Anyone that runs into this problem isn't going to be looking there; they'll be looking here in this test.  I think the TODO should be in each of the individual tests in this file that update the identity cert and private key, since that's the place where the coordination needs happen.


<!-- Sent from Reviewable.io -->

2020-11-19 20:16 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h, line 97 at r13](https://reviewable.io/reviews/grpc/grpc/24600#-MMSGQ4Y1p8WNlxmg6UN:-MMWw-RlCTM7arET2V6s:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/38541f64d895cd171e12a8590aab1fd8e4ceed0f/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.h#L97)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No, let's remove it from C-core as well.  There's no point in having it here if we don't have a use-case for it.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 318 at r14](https://reviewable.io/reviews/grpc/grpc/24600#-MMW3zhj2PM-iBhlz22V:-MMWwj8d6v6FB1nOgnWl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/082ecd68732826b9c9f3147a459635f4191fe87f/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L318)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Now we should tell `grpc_load_file()` to not add the null byte.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc, line 326 at r14](https://reviewable.io/reviews/grpc/grpc/24600#-MMW4MTJ4TDIww94bO0A:-MMWwjUFADLP8PJXYhzI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/082ecd68732826b9c9f3147a459635f4191fe87f/src/core/lib/security/credentials/tls/grpc_tls_certificate_provider.cc#L326)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_provider_test.cc, line 372 at r10](https://reviewable.io/reviews/grpc/grpc/24600#-MMGxtR040FVmpJxtvaw:-MMX8N7E9mTR2iN_F9Vq:br3m5we) ([raw file](https://github.com/grpc/grpc/blob/cccff1a8f2e133abe845380a87c42f10c5c941f9/test/core/security/grpc_tls_certificate_provider_test.cc#L372)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think that's the right place for it.  The `TmpFile` class is designed to write a single tempfile, and that functionality works fine.  Anyone that runs into this problem isn't going to be looking there; they'll be looking here in this test.  I think the TODO should be in each of the individual tests in this file that update the identity cert and private key, since that's the place where the coordination needs happen.
</blockquote></details>

Yeah, that makes sense to me!


<!-- Sent from Reviewable.io -->

2020-11-19 20:22 UTC, markdroth approved these changes
This looks fantastic!

Please remember to squash your commits before merging.

Thanks!

> Reviewed 10 of 10 files at r15.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MMXA5-v-AWFqyi7FGI7:b-nt2xp5)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-20 18:50 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: 24 of 26 files reviewed, 1 unresolved discussion (waiting on @markdroth and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 833 at r15](https://reviewable.io/reviews/grpc/grpc/24600#-MMayuGJ9ygZkyHmyraC:-MMayuGK34I5eOwQqnJe:bmo0bd5) ([raw file](https://github.com/grpc/grpc/blob/107d443cd4fbfcec2b66d6d0c0f62662e85de618/include/grpc/grpc_security.h#L833)):*
> ```objc
> grpc_tls_certificate_provider_file_watcher_create(
>     const char* private_key_path, const char* identity_certificate_path,
>     const char* root_cert_path, unsigned int refresh_interval_sec);
> ```

Why is refresh_internval_sec an `unsigned int` rather than something like `gpr_timespec`


<!-- Sent from Reviewable.io -->

2020-11-20 19:05 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: 24 of 26 files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[include/grpc/grpc_security.h, line 833 at r15](https://reviewable.io/reviews/grpc/grpc/24600#-MMayuGJ9ygZkyHmyraC:-MMb0O_H8hEriAZG3UBW:b2rzj8c) ([raw file](https://github.com/grpc/grpc/blob/107d443cd4fbfcec2b66d6d0c0f62662e85de618/include/grpc/grpc_security.h#L833)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Why is refresh_internval_sec an `unsigned int` rather than something like `gpr_timespec`
</blockquote></details>

I haven't thought that before, but it looks like if we want to use `gpr_timespec`, we will also design another core util function like `grpc_max_auth_token_lifetime` that will generate appropriate `gpr_timespec`. It seems core callers are not able to directly use `gpr_timespec`. We want a configurable time representation, instead of something like maximum time, which might make designing the function a bit complicated. In my  opinion, `unsigned int` is enough for our requirement right now.
CC @markdroth in case I missed something. 


<!-- Sent from Reviewable.io -->

2020-11-20 19:27 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: 24 of 26 files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[include/grpc/grpc_security.h, line 833 at r15](https://reviewable.io/reviews/grpc/grpc/24600#-MMayuGJ9ygZkyHmyraC:-MMb7-OJEPZ-FA0OGwLI:b2uhyy) ([raw file](https://github.com/grpc/grpc/blob/107d443cd4fbfcec2b66d6d0c0f62662e85de618/include/grpc/grpc_security.h#L833)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I haven't thought that before, but it looks like if we want to use `gpr_timespec`, we will also design another core util function like `grpc_max_auth_token_lifetime` that will generate appropriate `gpr_timespec`. It seems core callers are not able to directly use `gpr_timespec`. We want a configurable time representation, instead of something like maximum time, which might make designing the function a bit complicated. In my  opinion, `unsigned int` is enough for our requirement right now.
CC @markdroth in case I missed something. 
</blockquote></details>

@markdroth in case I missed something...


<!-- Sent from Reviewable.io -->

2020-11-20 19:28 UTC, markdroth approved these changes
> Reviewed 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[include/grpc/grpc_security.h, line 833 at r15](https://reviewable.io/reviews/grpc/grpc/24600#-MMayuGJ9ygZkyHmyraC:-MMb5U8C1DyIO-tZ27b3:b8t7loc) ([raw file](https://github.com/grpc/grpc/blob/107d443cd4fbfcec2b66d6d0c0f62662e85de618/include/grpc/grpc_security.h#L833)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

@markdroth in case I missed something...
</blockquote></details>

Actually, `gpr_timespec` is part of the C-core API, and we have a bunch of existing functions that use it.  I think it would be fine to take that type here.

That having been said, I would also be okay with leaving this as an int, since I don't think this is a case where anyone would want to configure sub-second granularity.

I will also point out that the type we use in the C-core API is actually not a big deal either way, because we can make non-backward-compatible changes here, so we can always change our mind in the future.  But we do need to be more thoughtful about the type we use in the C++ API, because once we move that out of `experimental`, we won't be able to make breaking changes to it later.  For example, if we want people to be able to pass in `std::chrono` types, we might want something more flexible.

But even that is not something we need to decide as part of this PR, since the C++ API is still experimental.  Let's just remember that we need to think this through before we take the new C++ API out of `experimental`.


<!-- Sent from Reviewable.io -->

2020-11-20 20:16 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[include/grpc/grpc_security.h, line 833 at r15](https://reviewable.io/reviews/grpc/grpc/24600#-MMayuGJ9ygZkyHmyraC:-MMbH01B9mAorIEJu-0f:bvyih77) ([raw file](https://github.com/grpc/grpc/blob/107d443cd4fbfcec2b66d6d0c0f62662e85de618/include/grpc/grpc_security.h#L833)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Actually, `gpr_timespec` is part of the C-core API, and we have a bunch of existing functions that use it.  I think it would be fine to take that type here.

That having been said, I would also be okay with leaving this as an int, since I don't think this is a case where anyone would want to configure sub-second granularity.

I will also point out that the type we use in the C-core API is actually not a big deal either way, because we can make non-backward-compatible changes here, so we can always change our mind in the future.  But we do need to be more thoughtful about the type we use in the C++ API, because once we move that out of `experimental`, we won't be able to make breaking changes to it later.  For example, if we want people to be able to pass in `std::chrono` types, we might want something more flexible.

But even that is not something we need to decide as part of this PR, since the C++ API is still experimental.  Let's just remember that we need to think this through before we take the new C++ API out of `experimental`.
</blockquote></details>

Sounds good. Thanks for the explanation! Let's keep it as the way it is right now. I will document this somewhere and bring it up again at the time when we decide to make C++ API stable. 


<!-- Sent from Reviewable.io -->

2020-11-20 20:18 UTC, ZhenLian reviewed
@yashykt May I know if there is anything else that we we could do better? 

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600#-:-MMbIaIeA7wjb-UuhtY-:b-24p43p)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)



<!-- Sent from Reviewable.io -->

2020-11-20 20:43 UTC, yashykt approved these changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24600)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-20 21:02 UTC, ZhenLian commented
Thank you all for the awesome code review! Merging now...

2020-11-20 21:02 UTC, merged