Xds client security integration
grpc/grpc pull request #24643
Opened 2020-11-03 01:15 UTC by yashykt

@nicolasnoble

2020-11-03 23:57 UTC, markdroth requested changes
This looks like a great start!

I think we should be able to add tests to xds_end2end_test even without the server-side integration being done.  We can configure the servers manually for mTLS and then have the clients get the corresponding mTLS config from the xDS server.

Please let me know if you have any questions.  Thanks!

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643#-:-MLFVY8u6YvezOrmxm3f:b-m1xtvi)* status: all files reviewed, 25 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 440 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFWABi6ja97XpY8-cg:-MLFWABi6ja97XpY8-ch:b198hud) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L440)):*
> ```cpp
> }
> 
> grpc_error* CdsLb::UpdateXdsCertificateProvider(
> ```

I think this method should not modify `args_`, because that could lead to conflicting updates between the args we set here and the ones we get from the resolver.

Instead, we should store the `XdsCertificateProvider` as a data member of the `CdsLb` object, and this method should update or replace it as needed by the CDS update.  Then the code in `OnClusterChanged()` can add the resulting provider to the args before calling the child policy's `UpdateLocked()`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 445 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFKumEC7mS_cfk-0Gx:-MLFKumEC7mS_cfk-0Gy:bfd2xxx) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L445)):*
> ```cpp
>       XdsCertificateProvider::GetFromChannelArgs(args_);
>   // Early out if channel is not configured to use xds security
>   if (!grpc_channel_args_find_bool(args_, GRPC_ARG_XDS_SECURITY, false)) {
> ```

I don't think we need to add a new channel arg for this.  The channel creds object itself will already be in the channel args, so you can find it and check the result of its `type()` method to see if it's "Xds".
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 447 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFTj834RgZacA1rIot:-MLFTj834RgZacA1rIou:b-j7wfvd) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L447)):*
> ```cpp
>   if (!grpc_channel_args_find_bool(args_, GRPC_ARG_XDS_SECURITY, false)) {
>     if (xds_certificate_provider != nullptr) {
>       const char* arg_to_remove = GRPC_ARG_XDS_CERTIFICATE_PROVIDER;
> ```

If you make the change I suggested above to have this function store the provider as a data member instead of storing it in `args_`, then this won't be necessary.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 455 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFQfpz8pmMW1122T9D:-MLFQfpz8pmMW1122T9E:bxcwq04) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L455)):*
> ```cpp
>     return GRPC_ERROR_NONE;
>   }
>   absl::string_view root_update =
> ```

We're getting the instance names here, but not the cert names.

Actually, it looks like we're not even parsing the cert names in the xDS response.  We probably should have taken care of that as part of #24285.  I think we'll need to fix that before we can finish this PR.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 455 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFSq8093rR-VFi2xNU:-MLFSq8093rR-VFi2xNV:b-phhofd) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L455)):*
> ```cpp
>     return GRPC_ERROR_NONE;
>   }
>   absl::string_view root_update =
> ```

Suggest calling this `root_provider_instance_name`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 458 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFStOmDX5aYusp1pgK:-MLFStOmDX5aYusp1pgL:bavj2gr) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L458)):*
> ```cpp
>       cluster_data.common_tls_context.combined_validation_context
>           .validation_context_certificate_provider_instance;
>   absl::string_view identity_update =
> ```

Suggest calling this `identity_provider_instance_name`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 461 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFShQz-jKPI1rVa0fz:-MLFShQz-jKPI1rVa0g-:b-l3u60t) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L461)):*
> ```cpp
>       cluster_data.common_tls_context
>           .tls_certificate_certificate_provider_instance;
>   if (!root_update.empty()) {
> ```

If `root_update` is empty but `root_certificate_provider_` is set from a previous update, we need to clear it.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 477 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFSQ-Y0h4ertiztxoK:-MLFSQ-Y0h4ertiztxoL:b9e04wz) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L477)):*
> ```cpp
>             root_certificate_provider->interested_parties());
>       }
>       if (root_certificate_provider_->interested_parties() != nullptr) {
> ```

On the very first update, `root_certificate_provider_` will be null, so this will crash.

I think adding tests will help catch cases like this.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 485 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFSo4e-3MgtbQ1YnJo:-MLFSo4f9LjWog2b3qPe:b8oqrur) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L485)):*
> ```cpp
>     }
>   }
>   if (!identity_update.empty()) {
> ```

If `identity_update` is empty but `identity_certificate_provider_` is set from a previous update, we need to clear it.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 501 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFT4aG8GwxwnHDKHCS:-MLFT4aG8GwxwnHDKHCT:b-ebhr2k) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L501)):*
> ```cpp
>             identity_certificate_provider->interested_parties());
>       }
>       if (identity_certificate_provider_->interested_parties() != nullptr) {
> ```

On the very first update, `identity_certificate_provider_` will be null, so this will crash.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 516 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFTFzL4wnYFLlf0cnv:-MLFTFzL4wnYFLlf0cnw:b-3o2yv2) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L516)):*
> ```cpp
>         xds_certificate_provider->ProvidesIdentityCerts()) {
>       xds_certificate_provider->UpdateRootCertNameAndDistributor(
>           "", root_certificate_provider_->distributor());
> ```

The cert name here needs to be plumbed in from the xDS data, not hard-coded to the empty string.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 518 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFTI9T1XFwXa2GCeED:-MLFTI9T1XFwXa2GCeEE:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L518)):*
> ```cpp
>           "", root_certificate_provider_->distributor());
>       xds_certific [...]

2020-11-07 00:10 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: 3 of 11 files reviewed, 25 unresolved discussions (waiting on @markdroth and @ZhenLian)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 440 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFWABi6ja97XpY8-cg:-MLV-s_J5RyGap216orl:ba70oi1) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L440)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this method should not modify `args_`, because that could lead to conflicting updates between the args we set here and the ones we get from the resolver.

Instead, we should store the `XdsCertificateProvider` as a data member of the `CdsLb` object, and this method should update or replace it as needed by the CDS update.  Then the code in `OnClusterChanged()` can add the resulting provider to the args before calling the child policy's `UpdateLocked()`.
</blockquote></details>

You are right. Fixed!
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 445 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFKumEC7mS_cfk-0Gx:-MLV1PCb8Np5XTq04hhh:bivktmz) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L445)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need to add a new channel arg for this.  The channel creds object itself will already be in the channel args, so you can find it and check the result of its `type()` method to see if it's "Xds".
</blockquote></details>

oh, yeah, you are right and we will only reach here if the scheme is xds anyway
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 447 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFTj834RgZacA1rIot:-MLV04MSDHRs0ZIbgwJe:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L447)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you make the change I suggested above to have this function store the provider as a data member instead of storing it in `args_`, then this won't be necessary.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 455 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFQfpz8pmMW1122T9D:-MLV06HG-O1K8skSck3u:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L455)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We're getting the instance names here, but not the cert names.

Actually, it looks like we're not even parsing the cert names in the xDS response.  We probably should have taken care of that as part of #24285.  I think we'll need to fix that before we can finish this PR.
</blockquote></details>

Done
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 455 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFSq8093rR-VFi2xNU:-MLV1LGJ854cM_GtEoDV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L455)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `root_provider_instance_name`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 458 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFStOmDX5aYusp1pgK:-MLV1Lhi2f6r8iaCus3m:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L458)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `identity_provider_instance_name`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 461 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFShQz-jKPI1rVa0fz:-MLV0c2t4Xrd0rMzbbm4:b4855pb) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L461)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If `root_update` is empty but `root_certificate_provider_` is set from a previous update, we need to clear it.
</blockquote></details>

Thanks! Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 477 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFSQ-Y0h4ertiztxoK:-MLV0XxH3_zQmDd2MFMQ:buqd8x0) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L477)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

On the very first update, `root_certificate_provider_` will be null, so this will crash.

I think adding tests will help catch cases like this.
</blockquote></details>

On the way
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 485 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFSo4e-3MgtbQ1YnJo:-MLV0fNTCUzuk0F3Fkx9:b70dbzj) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L485)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If `identity_update` is empty but `identity_certificate_provider_` is set from a previous update, we need to clear it.
</blockquote></details>

Thanks! Done
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 501 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFT4aG8GwxwnHDKHCS:-MLV0glA7z-CEBcbLJMj:b-ndezx) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L501)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

On the very first update, `identity_certificate_provider_` will be null, so this will crash.
</blockquote></details>

yeah, you are right. Tests on the way
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 516 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFTFzL4wnYFLlf0cnv:-MLV0jr6-awCYLVntIEM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L516)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The cert name here needs to be plumbed in from the xDS data, not hard-coded to the empty string.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 518 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFTI9T1XFwXa2GCeED:-MLV0kFV4u2NGCt36j6k:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L518)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 524 at r1](https://reviewable.io/reviews/grpc/grpc/24643#-MLFUAAfALd2d2-O5qKo:-MLV0kh07wzdUcc1CgOJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a6d934f72c60ff4c79a2ebe7a9ca0cd42a567add/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L524)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done [...]

2020-11-07 01:20 UTC, markdroth requested changes
This looks really good!  Remaining comments are mostly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 9 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643#-:-MLVHQVUATf3YIzM9X5N:b-eeivja)* status: all files reviewed, 5 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 490 at r3](https://reviewable.io/reviews/grpc/grpc/24643#-MLVFuYh9l6O8t952ofv:-MLVFuYh9l6O8t952ofw:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/e07c0f26c0a891dfdc984dc8e984b69bc420b8ed/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L490)):*
> ```cpp
>             root_certificate_provider_->interested_parties());
>       }
>       root_certificate_provider_ = root_certificate_provider;
> ```

`std::move()`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 493 at r3](https://reviewable.io/reviews/grpc/grpc/24643#-MLVFg1y5EXxJ2y96eUu:-MLVFg1y5EXxJ2y96eUv:bq9w466) ([raw file](https://github.com/grpc/grpc/blob/e07c0f26c0a891dfdc984dc8e984b69bc420b8ed/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L493)):*
> ```cpp
>     }
>   } else {
>     root_certificate_provider_ = nullptr;
> ```

We need to delete the pollset_set here.  (Ugh!)
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 520 at r3](https://reviewable.io/reviews/grpc/grpc/24643#-MLVG0Vx4p_BLSxJj93U:-MLVG0Vx4p_BLSxJj93V:b-7eb9tq) ([raw file](https://github.com/grpc/grpc/blob/e07c0f26c0a891dfdc984dc8e984b69bc420b8ed/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L520)):*
> ```cpp
>     }
>   } else {
>     identity_certificate_provider_ = nullptr;
> ```

Need to delete the pollset_set here too.  (Ugh again!)
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 522 at r3](https://reviewable.io/reviews/grpc/grpc/24643#-MLVGQI85JRTQO09DRzz:-MLVGQI85JRTQO09DS--:b-xqyu8y) ([raw file](https://github.com/grpc/grpc/blob/e07c0f26c0a891dfdc984dc8e984b69bc420b8ed/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L522)):*
> ```cpp
>     identity_certificate_provider_ = nullptr;
>   }
>   bool channel_args_to_be_updated = false;
> ```

I don't think this variable is needed anymore.
___
*[src/core/lib/security/credentials/credentials.h, line 130 at r3](https://reviewable.io/reviews/grpc/grpc/24643#-MLVHEiF-B0_99aFZAdN:-MLVHEiF-B0_99aFZAdO:b-qdr9fr) ([raw file](https://github.com/grpc/grpc/blob/e07c0f26c0a891dfdc984dc8e984b69bc420b8ed/src/core/lib/security/credentials/credentials.h#L130)):*
> ```objc
>   // of the passed-in channel args, and the caller takes ownership
>   // of the returned channel args.
>   virtual const grpc_channel_args* update_arguments(
> ```

I think you can revert the changes to this file, and all the files affected by this.


<!-- Sent from Reviewable.io -->

2020-11-13 10:28 UTC, yashykt reviewed
I have added tests for end to end integration. There is a bit of awkwardness in the code due to a few bugs in the tls security connector. Once they are fixed, we should be able to remove the extra bits.

I also wanted to use ctx->auth_context()->IsPeerAuthenticated() as an additional check, but that seems to be needing fixing too for TLS.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643#-:-MM05tvo9MO0XL7nLHx1:b-v2c1ty)* status: 3 of 20 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 490 at r3](https://reviewable.io/reviews/grpc/grpc/24643#-MLVFuYh9l6O8t952ofv:-MM05U0FEimgj9pTsEZJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e07c0f26c0a891dfdc984dc8e984b69bc420b8ed/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L490)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 493 at r3](https://reviewable.io/reviews/grpc/grpc/24643#-MLVFg1y5EXxJ2y96eUu:-MM05c0M3a5JJDejQHFW:bajq4w5) ([raw file](https://github.com/grpc/grpc/blob/e07c0f26c0a891dfdc984dc8e984b69bc420b8ed/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L493)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We need to delete the pollset_set here.  (Ugh!)
</blockquote></details>

yeah! :(
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 520 at r3](https://reviewable.io/reviews/grpc/grpc/24643#-MLVG0Vx4p_BLSxJj93U:-MM05f27E2BsteGvs2WC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e07c0f26c0a891dfdc984dc8e984b69bc420b8ed/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L520)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to delete the pollset_set here too.  (Ugh again!)
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 522 at r3](https://reviewable.io/reviews/grpc/grpc/24643#-MLVGQI85JRTQO09DRzz:-MM05g-lEhgsirIBQW_7:brpmqbq) ([raw file](https://github.com/grpc/grpc/blob/e07c0f26c0a891dfdc984dc8e984b69bc420b8ed/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L522)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this variable is needed anymore.
</blockquote></details>

removed!
___
*[src/core/lib/security/credentials/credentials.h, line 130 at r3](https://reviewable.io/reviews/grpc/grpc/24643#-MLVHEiF-B0_99aFZAdN:-MM05jvz0gYlLL64bDM_:b-iu07r6) ([raw file](https://github.com/grpc/grpc/blob/e07c0f26c0a891dfdc984dc8e984b69bc420b8ed/src/core/lib/security/credentials/credentials.h#L130)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you can revert the changes to this file, and all the files affected by this.
</blockquote></details>

I guess those const keywords got left back. removed!


<!-- Sent from Reviewable.io -->

2020-11-13 16:59 UTC, markdroth requested changes
The code looks pretty good!

I have two noteworthy concerns about the test:
- I don't think it's actually doing what you think it is, because the server is not configured to actually request the client's cert.  So it's basically always using TLS, not mTLS, regardless of how the client is configured.
- I think we can change the test to use different certs for the different configurations, and we can have the backend report the authenticated identity of the client, which we can then verify in the test.  If we do that, then there's no need to mess with switching backends in order to determine when the client has seen the change.

Please let me know if you have any questions.  Thanks!

> Reviewed 14 of 22 files at r4, 6 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643#-:-MM1XNdHEgS7IMylzDHe:bnf3vie)* status: all files reviewed, 27 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 468 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1Ke87CRXA1hKNCs1w:-MM1Ke87CRXA1hKNCs1x:b-yvk2sg) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L468)):*
> ```cpp
>       cluster_data.common_tls_context
>           .tls_certificate_certificate_provider_instance.certificate_name;
>   if (!root_provider_instance_name.empty()) {
> ```

Suggest writing this as:

```
RefCountedPtr<XdsCertificateProvider> new_root_provider;
if (!root_provider_instance_name.empty()) {
  new_root_provider =
      xds_client_->certificate_provider_store()
           .CreateOrGetCertificateProvider(root_provider_instance_name);
}
if (root_certificate_provider_ != new_root_provider) {
  if (root_certificate_provider_ != nullptr &&
      root_certificate_provider_->interested_parties() != nullptr) {
    grpc_pollset_set_del_pollset_set(
        interested_parties(),
        root_certificate_provider_->interested_parties());
  }
  if (new_root_provider != nullptr &&
      new_root_provider->interested_parties() != nullptr) {
    grpc_pollset_set_add_pollset_set(
        interested_parties(),
        new_root_provider->interested_parties());
  }
  root_certificate_provider_ = std::move(new_root_provider);
}
```

This way, we don't need a separate case for the provider being removed.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 500 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1M-gD-OCC9fryC6sL:-MM1M-gD-OCC9fryC6sM:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L500)):*
> ```cpp
>     root_certificate_provider_ = nullptr;
>   }
>   if (!identity_provider_instance_name.empty()) {
> ```

Same here.
___
*[src/core/ext/xds/certificate_provider_store.h, line 83 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1KPyt988_PIT4n9iO:-MM1KPyt988_PIT4n9iP:bew5c50) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/src/core/ext/xds/certificate_provider_store.h#L83)):*
> ```objc
>     }
> 
>     const absl::string_view& key() const { return key_; }
> ```

It's fine to return `absl::string_view` by value instead of as a const reference.
___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 50 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1JN0r4Do5ZZqKldHm:-MM1JN0r4Do5ZZqKldHn:bva1b28) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/src/core/lib/security/credentials/xds/xds_credentials.cc#L50)):*
> ```cpp
> }  // namespace
> 
> grpc_core::RefCountedPtr<grpc_channel_security_connector>
> ```

There's no need for `grpc_core::` anywhere in this file, since we're already inside of that namespace.
___
*[src/proto/grpc/testing/xds/v3/common.proto, line 1 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1Ip4l6DgGC8cCSXx6:-MM1Ip4l6DgGC8cCSXx7:b5mj7a3) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/src/proto/grpc/testing/xds/v3/common.proto#L1)):*
> ```protobuf
> // Copyright 2020 The gRPC Authors
> ```

This file is no longer needed, since the proto has been moved into tls.proto.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 349 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1NZcEDidx5MU-yHzz:-MM1NZcEDidx5MU-yI--:b5x714f) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L349)):*
> ```cpp
>   }
> 
>   // TODO(yashykt): This currently seems to be broken for the TLS security
> ```

What exactly is broken here?  Do we have an issue open to track this?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 357 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1MZIn6O-NfjblHAtF:-MM1MZIn6O-NfjblHAtG:b-ayh370) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L357)):*
> ```cpp
> 
>  private:
>   void AddClient(const std::string& client) {
> ```

Looks like this is no longer used anywhere.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1363 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1MzS23IQrCIVSJdG0:-MM1MzS23IQrCIVSJdG1:b-taaeb7) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L1363)):*
> ```cpp
>   bool use_xds_credentials() const { return use_xds_credentials_; }
> 
>   std::string AsString() const {
> ```

This needs to be updated to report the new parameter, or else it won't be clear from the test name what's actually being tested.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1394 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1NEtlDMjepxQC3PFa:-MM1NEtlDMjepxQC3PFb:bf0hivm) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L1394)):*
> ```cpp
>   CreateCertificateProviderConfig(const grpc_core::Json& config_json,
>                                   grpc_error** error) override {
>     return grpc_core::MakeRefCounted<Config>();
> ```

I believe this can just be `return nullptr`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2096 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1W9FD9Lv1wNpzTnQM:-MM1W9FD9Lv1wNpzTnQN:b-o9dwkr) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L2096)):*
> ```cpp
>             certificate_provider);
>         options.watch_root_certs();
>         options.watch_identity_key_cert_pairs();
> ```

Also need to call `options.set_cert_request_type(GRPC_SSL_REQUEST_CLIENT_CERTIFICATE_AND_VERIFY)` if you want the server to request and verify the client's cert.  Otherwise, this will always use TLS, even if the client is configured for mTLS, because the server won't actually be requesting the client's cert.

Maybe this is why the `IsPeerAuthenticated()` check is failing above?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5339 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1R0yK9C9fvaK4f9kM:-MM1R0yK9C9fvaK4f9kN:btto4gr) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5339)):*
> ```cpp
>       absl::string_view root_instance_name,
>       bool test_expects_fallback_creds = false) {
>     current_backend_ = 1 - current_backend_;
> ```

It took me a while to understand what this was for.  Please add a comment describing that we want to bounce back and forth between the two backends, since we're using that to know when the cert provider update has been seen by the client.

That having been said, if you take my suggestions below about how to verify that the security changes have actually occurred, then you probably don't need to mess with switching backends at all -- all of these tests should be able to use just one backend.
___
*[te [...]

2020-11-13 20:20 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: all files reviewed, 27 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 349 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1NZcEDidx5MU-yHzz:-MM1y8kG7R2nJwNATewa:b8cx8cx) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L349)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What exactly is broken here?  Do we have an issue open to track this?
</blockquote></details>

as you noted below, the issue was that the server was not actually setting GRPC_SSL_REQUEST_CLIENT_CERTIFICATE_AND_VERIFY. I was messing with this settings earlier and it didn't work but that's probably because something else in the test was broken. Thanks!


<!-- Sent from Reviewable.io -->

2020-11-13 21:05 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: 17 of 21 files reviewed, 27 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 468 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1Ke87CRXA1hKNCs1w:-MM2OZRR8twP9VHVsppi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L468)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as:

```
RefCountedPtr<XdsCertificateProvider> new_root_provider;
if (!root_provider_instance_name.empty()) {
  new_root_provider =
      xds_client_->certificate_provider_store()
           .CreateOrGetCertificateProvider(root_provider_instance_name);
}
if (root_certificate_provider_ != new_root_provider) {
  if (root_certificate_provider_ != nullptr &&
      root_certificate_provider_->interested_parties() != nullptr) {
    grpc_pollset_set_del_pollset_set(
        interested_parties(),
        root_certificate_provider_->interested_parties());
  }
  if (new_root_provider != nullptr &&
      new_root_provider->interested_parties() != nullptr) {
    grpc_pollset_set_add_pollset_set(
        interested_parties(),
        new_root_provider->interested_parties());
  }
  root_certificate_provider_ = std::move(new_root_provider);
}
```

This way, we don't need a separate case for the provider being removed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 500 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1M-gD-OCC9fryC6sL:-MM2O_Xt5NMVrHcDSEXt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L500)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/certificate_provider_store.h, line 83 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1KPyt988_PIT4n9iO:-MM2OaIv6BrYoGDMVVng:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/src/core/ext/xds/certificate_provider_store.h#L83)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's fine to return `absl::string_view` by value instead of as a const reference.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 50 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1JN0r4Do5ZZqKldHm:-MM2OdiiEF_jCAPUN_VM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/src/core/lib/security/credentials/xds/xds_credentials.cc#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need for `grpc_core::` anywhere in this file, since we're already inside of that namespace.
</blockquote></details>

Done.
___
*[src/proto/grpc/testing/xds/v3/common.proto, line 1 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1Ip4l6DgGC8cCSXx6:-MM2OfRq17olJeqge5sR:b-kk9jf5) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/src/proto/grpc/testing/xds/v3/common.proto#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This file is no longer needed, since the proto has been moved into tls.proto.
</blockquote></details>

Forgot to do a `git rm`. Done!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1363 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1MzS23IQrCIVSJdG0:-MM2OqVe9CWXXZ3EwGxB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L1363)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to be updated to report the new parameter, or else it won't be clear from the test name what's actually being tested.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1394 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1NEtlDMjepxQC3PFa:-MM2GSsr8Z_la1pyVUH3:b1r5rwj) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L1394)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I believe this can just be `return nullptr`.
</blockquote></details>

There are assumptions in the code that a non-null Config is returned for successful parsing.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2096 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1W9FD9Lv1wNpzTnQM:-MM2OrzLB7sAL4qGiq8e:bnhtqu4) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L2096)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Also need to call `options.set_cert_request_type(GRPC_SSL_REQUEST_CLIENT_CERTIFICATE_AND_VERIFY)` if you want the server to request and verify the client's cert.  Otherwise, this will always use TLS, even if the client is configured for mTLS, because the server won't actually be requesting the client's cert.

Maybe this is why the `IsPeerAuthenticated()` check is failing above?
</blockquote></details>

You are right. Thanks!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5344 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1SsNL9bHG_aoNTGyW:-MM2PWUmCu1n12nop8Hq:b-cdu18i) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5344)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is setting the instance names but not the cert names.  The test should prove that we are correctly passing the cert names through.

To do this, it may be necessary to have a fake provider that actually uses the requested cert name.  That's probably a good idea anyway, since it will allow us to test cases like an unknown cert name.
</blockquote></details>

I didn't think these tests were useful here since we already have coverage at `xds_certificate_provider_test.cc`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5346 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1Qp0J0mE3PBvjEIIe:-MM2GpqV-lonrWogf3FU:bnc1wz) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5346)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is it necessary to explicitly convert to `std::string` here?  I think it should happen automatically.

Same thing for the next statement.
</blockquote></details>

Yes, it doesn't work otherwise
`no known conversion from 'absl::string_view' to 'const std::string'`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5346 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1Rq50BFCdjjKK7o1Q:-MM2GsVe49TNHg17t3lD:bnc1wz) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5346)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If the string is empty, shouldn't we avoid setting these fields rather than explicitly setting them to the empty string?
</blockquote></details>

Yes, it doesn't work otherwise
`no known conversion from 'absl::string_view' to 'const std::string'`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5395 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1STiMAMBkAReHOikT:-MM2PsUB3l-othhcKGcb:b4muhpo) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5395)):*
<details><summary><i>Previously, markdroth (Mark D. Rot [...]

2020-11-16 17:25 UTC, markdroth requested changes
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: all files reviewed, 18 unresolved discussions (waiting on @yashykt)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 349 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1NZcEDidx5MU-yHzz:-MMH2GKx3jY9ebKz9oC-:b5tq1jr) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L349)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

as you noted below, the issue was that the server was not actually setting GRPC_SSL_REQUEST_CLIENT_CERTIFICATE_AND_VERIFY. I was messing with this settings earlier and it didn't work but that's probably because something else in the test was broken. Thanks!
</blockquote></details>

In that case, I think this TODO can be removed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5344 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1SsNL9bHG_aoNTGyW:-MMH2sKCEiCI5aViU4gs:b-v39z8u) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5344)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I didn't think these tests were useful here since we already have coverage at `xds_certificate_provider_test.cc`
</blockquote></details>

The tests in xds_certificate_provider_test.cc don't prove that we actually honor the cert names passed to us by the xDS server.  This is an e2e test, which is about putting all of the pieces together and making sure that they work on an e2e basis.  I think we need this coverage here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5346 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1Rq50BFCdjjKK7o1Q:-MMH3A5i-Z-QmxhObMi1:bzh19zs) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5346)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Yes, it doesn't work otherwise
`no known conversion from 'absl::string_view' to 'const std::string'`
</blockquote></details>

Looks like you copied your response to my previous comment, but I'm asking something different here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5395 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1STiMAMBkAReHOikT:-MMH3SYmA8iomOVXIuV8:b-7s73vm) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5395)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Any special reason we want to split the tests? Having everything in one test avoids the setup and teardown.. which is not trivial for these tests.
</blockquote></details>

In general, it's considered good practice to keep each test focused on one specific scenario.  Internally, see go/tott/520 for details.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 309 at r6](https://reviewable.io/reviews/grpc/grpc/24643#-MMH2BktBLuBcq-O_ZLt:-MMH2BktBLuBcq-O_ZLu:bn02gm) ([raw file](https://github.com/grpc/grpc/blob/7a5cee15d8f34d77b4c32bde98783ea718255026/test/cpp/end2end/xds_end2end_test.cc#L309)):*
> ```cpp
>         context->client_metadata().end();
>     bool peer_authenticated = context->auth_context()->IsPeerAuthenticated();
>     //TODO: remove this log
> ```

I assume this was added just for debugging and can be removed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1370 at r6](https://reviewable.io/reviews/grpc/grpc/24643#-MMH2RVf666D-KmYFEQf:-MMH2RVf666D-KmYFEQg:b-x1jlo4) ([raw file](https://github.com/grpc/grpc/blob/7a5cee15d8f34d77b4c32bde98783ea718255026/test/cpp/end2end/xds_end2end_test.cc#L1370)):*
> ```cpp
>     if (enable_load_reporting_) retval += "WithLoadReporting";
>     if (enable_rds_testing_) retval += "Rds";
>     if (use_xds_credentials_) retval += "UsingXdsCredentials";
> ```

Suggest just using the string "XdsCreds" here.  Our test names are a little too long as it is. :)


<!-- Sent from Reviewable.io -->

2020-11-17 00:48 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: 19 of 21 files reviewed, 18 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 357 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1MZIn6O-NfjblHAtF:-MMIbyusAsrmyjGWhon5:b-hfpv0l) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L357)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like this is no longer used anywhere.
</blockquote></details>

removed
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5339 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1R0yK9C9fvaK4f9kM:-MMIc9oD7sJn0CCoMrOp:ba3dfob) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5339)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It took me a while to understand what this was for.  Please add a comment describing that we want to bounce back and forth between the two backends, since we're using that to know when the cert provider update has been seen by the client.

That having been said, if you take my suggestions below about how to verify that the security changes have actually occurred, then you probably don't need to mess with switching backends at all -- all of these tests should be able to use just one backend.
</blockquote></details>

Removed
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5344 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1SsNL9bHG_aoNTGyW:-MMIcLd4-VfF-ZU_LjhT:bgolwlc) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5344)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The tests in xds_certificate_provider_test.cc don't prove that we actually honor the cert names passed to us by the xDS server.  This is an e2e test, which is about putting all of the pieces together and making sure that they work on an e2e basis.  I think we need this coverage here.
</blockquote></details>

Ack. Added certificate name update tests
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5346 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1Rq50BFCdjjKK7o1Q:-MMIcRs276bdOLHINA5b:b-4unctn) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5346)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like you copied your response to my previous comment, but I'm asking something different here.
</blockquote></details>

Ah, my bad. The actual response should have been - It does not matter whether we set them or not if the string is empty.
https://github.com/googleapis/google-cloud-python/issues/1402#issuecomment-183009502
Starting proto3, there is no meaningful field presence check for strings, other than simply checking for empty string which is the default.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5395 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1STiMAMBkAReHOikT:-MMIdQ_Y4HzpmlUeA7Tn:bvoq95u) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5395)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In general, it's considered good practice to keep each test focused on one specific scenario.  Internally, see go/tott/520 for details.
</blockquote></details>

Thanks for the link! Divided the tests.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5401 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1SS045YTgyjE_t-iR:-MMIdUVYA58rSXchuml5:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5401)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't appear to actually be verifying that anything has actually changed, since fake_plugin1 and fake_plugin2 provide exactly the same data.  I think that in order to test this properly, we need to provide a different root cert and then see that the reaction is appropriate.

One way of doing this is to set the root cert to one that does not match the server-side cert.  Then we can shutdown and restart the backend, which will force the client to reconnect.  That reconnection should fail, and we can verify that RPCs are failing.
</blockquote></details>

Done
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5404 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1UPHaEjoadBT6RSEk:-MMIdcWy5s6WtAE-CxdM:beo4o41) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5404)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should test this case by changing to a different identity cert and having the backend report the identity of the client, which the test can then verify.
</blockquote></details>

Done, I'm checking that the peer identity changes
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5407 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1VIaQ09vRIRZmoA-I:-MMIdqgk3yGGREoB5jRQ:b-k1fnae) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5407)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This case can be a combination of the two cases above.
</blockquote></details>

I'm testing it slightly differently, by initially keeping certs from "fake_plugin2" which result in a failure due to the bad root certs, and then I switch it to "fake_plugin1".. This is to differentiate it from the root cert plugin update case.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5410 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1VNjhESUH0B6DKFDK:-MMIeKd69ZnEv2MA6jS8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5410)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This case we should be able to verify by having the backend report that the client did not send an identity.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5413 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1VVaI8jkXvit1ijlP:-MMIeLj_54ex_rhxH4b2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5413)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5416 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1VZEc6D91UNmCFm0y:-MMIeMsb1xQdvpxHL5QD:b-q40d05) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5416)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If the fallback creds use a different identity cert, then we can tell that this is happening by having the backend report the client's identity and having the test check it.
</blockquote></details>

Done.  I've also passed in additional metadata with fallback creds as an additional check.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5419 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1X6eQ0U68UtsKGqZi:-MMIeuur9klsm5D5bA4-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L5419)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockqu [...]

2020-11-17 00:49 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: 19 of 21 files reviewed, 18 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 349 at r5](https://reviewable.io/reviews/grpc/grpc/24643#-MM1NZcEDidx5MU-yHzz:-MMIfNGOCeWnFXmr62VN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5c88d822d770976ce5babbe3a05de906adaaa985/test/cpp/end2end/xds_end2end_test.cc#L349)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In that case, I think this TODO can be removed.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1370 at r6](https://reviewable.io/reviews/grpc/grpc/24643#-MMH2RVf666D-KmYFEQf:-MMIfP4O4RPmr2xxvida:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7a5cee15d8f34d77b4c32bde98783ea718255026/test/cpp/end2end/xds_end2end_test.cc#L1370)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest just using the string "XdsCreds" here.  Our test names are a little too long as it is. :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-17 10:57 UTC, yashykt reviewed
The tests are finally in a non-flaky state.. verified with 1000 runs_per_test

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643#-:-MMKqD1D1YWfI_hXtz1w:b-qeb3ow)* status: 10 of 24 files reviewed, 18 unresolved discussions (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2020-11-18 00:30 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: all files reviewed, 16 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/certificate_provider_store.h, line 107 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNEiLu3OAGcQDvCHXo:-MMNk_0wE4v-PXZfADO-:bebrt1w) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/src/core/ext/xds/certificate_provider_store.h#L107)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this change necessary?

If the goal here is for the store to exist for the lifetime of the entries in the store, then it would probably make more sense to make the store `InternallyRefCounted<>` and have each entry hold a ref to the store.  Holding refs to the `XdsClient` itself seems like tighter coupling that what we really need here.
</blockquote></details>

Will do
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5404 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNQN7U9fNHVuwrbXu-:-MMNfrVU5rdjDEauGNuY:b-qywn8d) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5404)):*
> If the URI scheme is not "xds".

We already test that in xds_credentials_end2end_test.cc

> If the URI scheme is "xds" but no TLS config is provided in the CDS resource.

Isn't this what the fallback case is currently testing?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5431 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNOT8V96Yb3tkUJVps:-MMNhhsx0SuaprSA6Nk1:bjy8h7r) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5431)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can we actually check the identity rather than just checking that it's authenticated?

Same thing throughout.
</blockquote></details>

I should be able to but I'm not sure that buys us anything.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5449 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNO5td32tvGKkXlpPj:-MMNiHI6BfXtn1PPeCE7:b39hjfu) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5449)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Are you sure that `auto` here doesn't result in this being a reference?  That would prevent the last expectation from actually working properly, because it would just be comparing it to itself.
</blockquote></details>

I believe for references to work that way, you need to mention `auto &`


<!-- Sent from Reviewable.io -->

2020-11-18 00:44 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: all files reviewed, 15 unresolved discussions (waiting on @yashykt)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5404 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNQN7U9fNHVuwrbXu-:-MMNnMcf-6leRBAL0KDz:b9717lx) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5404)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> If the URI scheme is not "xds".

We already test that in xds_credentials_end2end_test.cc

> If the URI scheme is "xds" but no TLS config is provided in the CDS resource.

Isn't this what the fallback case is currently testing?
</blockquote></details>

You're right on both counts.  Sorry for missing the obvious!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5431 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNOT8V96Yb3tkUJVps:-MMNnRF_1Zrp0yZNemdC:bec6e6o) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5431)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I should be able to but I'm not sure that buys us anything.
</blockquote></details>

I think it makes it clearer to the test reader what's happening.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5449 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNO5td32tvGKkXlpPj:-MMNnc8-A1Lyh-OqEHf8:bmlwyq7) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5449)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I believe for references to work that way, you need to mention `auto &`
</blockquote></details>

Just to make me feel better, let's not use `auto` here. :)


<!-- Sent from Reviewable.io -->

2020-11-18 23:42 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: 17 of 23 files reviewed, 15 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/certificate_provider_store.h, line 69 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNEIZB-uBvDgDLQz21:-MMShydm7UJfDHnmVFDN:b2hawix) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/src/core/ext/xds/certificate_provider_store.h#L69)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be `WeakRefCountedPtr<>`, so that it does not prevent the `XdsClient` from shutting down.
</blockquote></details>

changed store to be internally refcounted
___
*[src/core/ext/xds/certificate_provider_store.h, line 87 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNENbU2_aKKsi1T0J_:-MMSi7U674koKjzxHJFF:b2hawix) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/src/core/ext/xds/certificate_provider_store.h#L87)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

changed store to be internally refcounted
___
*[src/core/ext/xds/certificate_provider_store.h, line 107 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNEiLu3OAGcQDvCHXo:-MMSi9AT6eQsM9NxeQSB:b2hawix) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/src/core/ext/xds/certificate_provider_store.h#L107)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

changed store to be internally refcounted
___
*[src/core/ext/xds/certificate_provider_store.h, line 109 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNF5t7E6xqc5mw-pt8:-MMSiAYv9HKmbh8c8Puv:b2hawix) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/src/core/ext/xds/certificate_provider_store.h#L109)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Storing a raw pointer to the `XdsClient` without actually storing a ref seems a little messy.  Maybe this should be a weak ref as well?

This issue will go away if you take my suggestion above about having the entries hold refs to the store instead of holding refs to the `XdsClient`.
</blockquote></details>

changed store to be internally refcounted
___
*[test/core/util/stack_tracer.cc, line 107 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNFe5_8DYQYua3g799:-MMSG0H1E-hhvPM6gkVX:b7xu9iz) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/core/util/stack_tracer.cc#L107)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This looks unrelated to this PR.
</blockquote></details>

Yeah, the stack trace is annoying when debugging tests. It prints off the stack trace with each error log.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1366 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNGHTfDLVJzX_SHrhz:-MMSiCBtAbbkpk59gccF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L1366)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::string file_contents(grpc_core::StringViewFromSlice(slice));`
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1400 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNGoQf27Cdy_Ty2BuH:-MMSiDNq-3SlG56oitDX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L1400)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of reading these files every time a new cert is requested, how about reading the files in the factory and passing the contents in via params, just like we're doing for the normal root and identity certs?
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1408 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNH4gKB2CXcPjxgU4L:-MMSiG1NC5UPUJvZ6cTa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L1408)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5340 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNcN009By2e1sunWr1:-MMSiHO2DXfX0Fha3Bfw:bq9rmly) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5340)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If `test_expects_fallback_creds` is true, then we don't need to populate this at all -- we can just set the default cluster as-is.
</blockquote></details>

removed `test_expects_fallback_creds` since it was redundant. When both root and identity instance names are empty, it should mean fallback creds are expected.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5366 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNN5Cw63xjvrG4s-uj:-MMSiTj_3_jD5hJ2wKab:bjm7i6l) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5366)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The EDS resource needs to be set initially for each test, but it doesn't need to be reset when we change the change the config.  Maybe just populate this in `SetUpTestCase()`?
</blockquote></details>

I think you meant `SetUp()`. (No object is available in `SetUpTestCase()`. Done!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5401 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNM1Rr8T86b1vVrL-q:-MMSioe_4PSeW6SGQeXk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5401)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't look like it's actually useful for anything anymore.  I think we can just remove it.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5431 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNOT8V96Yb3tkUJVps:-MMSj0bHAjKQbETh-Gca:b-9vaf6a) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5431)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think it makes it clearer to the test reader what's happening.
</blockquote></details>

Done. It is definitely more clear now :)
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5439 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNNg0dBReizb3ufzHL:-MMSiq39BONHeQPAd73F:b56kb8c) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5439)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is needed.
</blockquote></details>

Moved it to `SetUp()` since it was common code
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5442 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNR3pDBrZfOfjtgZO3:-MMSivrJ005pDhy2qXAn:b2dui4k) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5442)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'm a little concerned that all of the changes here are going from a valid cert to a bad cert, since that seems not to really prove that we can migrate from one valid cert to another.  Can we instead have a variety of valid certs  [...]

2020-11-19 16:17 UTC, markdroth requested changes
Just a couple of noteworthy comments left; everything else is cosmetic at this point.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 7 files at r9, 4 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643#-:-MMWHyXHEBjSjwvuBaD1:bi54zjv)* status: all files reviewed, 14 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/certificate_provider_store.h, line 49 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW6tz-A6p9VzxBe1dQ:-MMW6tz-A6p9VzxBe1dR:b-1425p2) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/src/core/ext/xds/certificate_provider_store.h#L49)):*
> ```objc
>   typedef std::map<std::string, PluginDefinition> PluginDefinitionMap;
> 
>   CertificateProviderStore(PluginDefinitionMap plugin_config_map)
> ```

This needs to be `explicit`.
___
*[src/core/ext/xds/certificate_provider_store.h, line 60 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW6iQxBvJqZfMNZa97:-MMW6iQy0BHFg5UZZnXO:b-oio8o1) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/src/core/ext/xds/certificate_provider_store.h#L60)):*
> ```objc
>       absl::string_view key);
> 
>   void Orphan() override { Unref(); }
> ```

Should we trigger some sort of shutdown here?  If we're not going to do that, then it seems a little odd to be using `InternallyRefCounted<>` instead of just `RefCounted<>`, although I guess the former does have the advantage of requiring just one external owner.

As an alternative, what if we do the following:
- Add a method on `CertificateProviderWrapper` to set its `store_` member to null.
- Change `CertificateProviderWrapper` dtor call `ReleaseCertificateProvider()` only if `store_` is non-null.
- Change the store's dtor iterate through the map and call the method on each wrapper to reset its `store_` member.

That way, we won't even need the store to be ref-counted in the first place.
___
*[test/core/util/stack_tracer.cc, line 107 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNFe5_8DYQYua3g799:-MMW6P2n5ceWMLeEjjt2:b-xg7dqm) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/core/util/stack_tracer.cc#L107)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Yeah, the stack trace is annoying when debugging tests. It prints off the stack trace with each error log.
</blockquote></details>

Yeah, I've noticed that too.  I suggest complaining to Esun about that -- I think he's the one that added this.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5340 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNcN009By2e1sunWr1:-MMWAOYU5zXFisRxGRyJ:b-iky5in) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5340)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

removed `test_expects_fallback_creds` since it was redundant. When both root and identity instance names are empty, it should mean fallback creds are expected.
</blockquote></details>

Regardless of how it's passed into this function, I think we should not populate the `transport_socket` field in the proto at all if we're using fallback creds.  I think that's how a typical xDS server would send its resources -- that field would be present only if TLS was being configured in some way.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5439 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNNg0dBReizb3ufzHL:-MMWChOs19b7uqtNK99N:bopvlg6) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5439)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Moved it to `SetUp()` since it was common code
</blockquote></details>

I actually just meant that this particular test was calling it twice.  But I'm fine with moving it to `SetUp()` too.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1391 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW8bbc7TsK2C2IJXrb:-MMW8bbc7TsK2C2IJXrc:bp4z0ww) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L1391)):*
> ```cpp
> }
> 
> // Based on StaticDataCertificateProvider, but provides bad certificates if the
> ```

s/bad/alternate/
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1513 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW94lG8bMnXYZ7Jy3j:-MMW94lG8bMnXYZ7Jy3k:bp76fvr) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L1513)):*
> ```cpp
> };
> 
> // Create a static certificate provider with good root certs but valid identity
> ```

s/but/and/
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1514 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW98-R53z5SSK0fLc6:-MMW98-R53z5SSK0fLc7:b2hrmt) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L1514)):*
> ```cpp
> 
> // Create a static certificate provider with good root certs but valid identity
> // certs. The alternate identity certs are also valid.
> ```

Let's also state that the alternate root cert is the same.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1557 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW9LfJ2v_MJ9Mo4w2V:-MMW9LfJ2v_MJ9Mo4w2W:b62zrhc) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L1557)):*
> ```cpp
>       options, GRPC_TLS_SKIP_HOSTNAME_VERIFICATION);
>   grpc_tls_credentials_options_set_certificate_provider(
>       options, grpc_core::MakeRefCounted<FakeCertificateProvider>(
> ```

Could just use the normal static provider here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5379 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW9T7eCy4q-V4k9NlD:-MMW9T7eCy4q-V4k9NlE:bm8w7t8) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L5379)):*
> ```cpp
>  protected:
>   static void SetUpTestCase() {
>     gpr_setenv("GRPC_XDS_EXPERIMENTAL_SECURITY_SUPPORT", "true");
> ```

We should also unset this in `TearDownTestCase()`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5401 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMWBRdVDfMwDwrpODaj:-MMWBRdVDfMwDwrpODak:b-16iab4) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L5401)):*
> ```cpp
>   }
> 
>   void UpdateAndVerifyXdsSecurityConfiguration(
> ```

Please document that when the instance names are empty, we expect fallback creds.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5406 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMWEW1X7nQKwJDGAIdZ:-MMWEW1X7nQKwJDGAId_:bka3s5f) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L5406)):*
> ```cpp
>       absl::string_view root_instance_name,
>       absl::string_view root_certificate_name,
>       const absl::optional<std::vector<std::string>>&
> ```

It looks like this will only be nullopt in cases where `test_expects_failure` is true, in which case this doesn't get used anyway.  Given that, `absl::optional<>` probably isn't useful; instead, callers can just as easily pass in the empty vector by using `{}`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5453 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMWB6kIADDfHhvNriiw:-MMWB6kIADDfHhvNriix:b-tey7hw) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L5453)):*
> ```cpp
>                 (identity_instance_name.empty() &&
>                  root_instance_name.empty()) &&
>             (backends_[0]->backend_service()-> [...]

2020-11-19 21:20 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: 16 of 21 files reviewed, 14 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/certificate_provider_store.h, line 60 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW6iQxBvJqZfMNZa97:-MMXLQ8L0Uds0FVBe8Yn:b-x2058j) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/src/core/ext/xds/certificate_provider_store.h#L60)):*
> As an alternative, what if we do the following:

> Add a method on CertificateProviderWrapper to set its store_ member to null.
Change CertificateProviderWrapper dtor call ReleaseCertificateProvider() only if store_ is non-null.
Change the store's dtor iterate through the map and call the method on each wrapper to reset its store_ member.
That way, we won't even need the store to be ref-counted in the first place.

That's doable, but we need to refcount something or the other to make sure that we don't run into use-after-free or time-of-check-to-time-of-use bugs. I've updated the code to share the mutex instead. Note that a private mutex for CertificateProviderWrapper does not work because then we need to run into deadlock issues due to lock ordering between this new mutex and the store's mutex.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5340 at r8](https://reviewable.io/reviews/grpc/grpc/24643#-MMNcN009By2e1sunWr1:-MMXKv4I05VuFawRgbvD:bdfdjrs) ([raw file](https://github.com/grpc/grpc/blob/6b493bfb443a5a662927e57adc0db1b0b4127d7a/test/cpp/end2end/xds_end2end_test.cc#L5340)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Regardless of how it's passed into this function, I think we should not populate the `transport_socket` field in the proto at all if we're using fallback creds.  I think that's how a typical xDS server would send its resources -- that field would be present only if TLS was being configured in some way.
</blockquote></details>

I was looking at the wrong line. Updated.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1391 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW8bbc7TsK2C2IJXrb:-MMXNKMkCnJB2rqcbo_X:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L1391)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/bad/alternate/
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1513 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW94lG8bMnXYZ7Jy3j:-MMXNLpR2seLwxLEDauh:b-xvbsib) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L1513)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/but/and/
</blockquote></details>

outdated
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1514 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW98-R53z5SSK0fLc6:-MMXNMgy3EFPb7gyxTfx:b-xvbsib) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L1514)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's also state that the alternate root cert is the same.
</blockquote></details>

outdated
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1557 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW9LfJ2v_MJ9Mo4w2V:-MMXKomB9xjeskVSeit9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L1557)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Could just use the normal static provider here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5379 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW9T7eCy4q-V4k9NlD:-MMXKq8FDSPWaSy0966P:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L5379)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should also unset this in `TearDownTestCase()`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5401 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMWBRdVDfMwDwrpODaj:-MMXKu2NDNrMEpkItOuu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L5401)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document that when the instance names are empty, we expect fallback creds.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5406 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMWEW1X7nQKwJDGAIdZ:-MMXKuTE-anuZl7Ut8CB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L5406)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like this will only be nullopt in cases where `test_expects_failure` is true, in which case this doesn't get used anyway.  Given that, `absl::optional<>` probably isn't useful; instead, callers can just as easily pass in the empty vector by using `{}`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5453 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMWB6kIADDfHhvNriiw:-MMXKysu3b40mxZ0vs8E:ba3dfob) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L5453)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the outer parens on this sub-expression.
</blockquote></details>

Removed
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5481 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMWFPyE1vkSZxeJxl6F:-MMXL-Un9NKf6yvt90Xc:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L5481)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

General comment: I'm finding it really hard to follow these tests, because the actual test data is specified in the certificate provider factories above, but the tests rely on this data.  This is an anti-pattern; internally, see go/tott/608, go/tott/598, and go/tott/529.

Instead, I suggest the following:
- Create a global variable for each factory that points to the cert data to be used by that provider.
- Each test can create the cert data for each provider in a local variable and set the global variable to point to it.
- The provider will return data from local variable pointed to by the global variable.

That way, all of the test data will be present in each individual test, and all of the relevant details will be easy to see just by looking at the individual test cases.
</blockquote></details>

Done
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5496 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMWDGnj80ux9QC5Y804:-MMXL2ut00sXdWJwLptT:b-5dcier) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/test/cpp/end2end/xds_end2end_test.cc#L5496)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In this case, how do we know that we're actually waiting for the update to occur, since the update and the original data are exactly the same?

If we used a different root cert for the updated config, is there any way we could check some property of the connection to tell that we'd used the new root cert, analogously to how we're checking the authenticated identity to tell that the identity cert has changed?  I'm not sure if we actually have and expo [...]

2020-11-19 21:21 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: 16 of 21 files reviewed, 14 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/certificate_provider_store.h, line 49 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW6tz-A6p9VzxBe1dQ:-MMXNZ4a9ksReOFS9IAi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/src/core/ext/xds/certificate_provider_store.h#L49)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to be `explicit`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-20 17:32 UTC, markdroth requested changes
The tests are definitely cleaner now!  I have a few suggestions to make them even more readable.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 6 files at r11, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643#-:-MMahXSLAs6UaMSqDKLd:b-1fqp93)* status: all files reviewed, 15 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/certificate_provider_store.h, line 60 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW6iQxBvJqZfMNZa97:-MMaRnXT778bAKSv9CgC:b-qpte6s) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/src/core/ext/xds/certificate_provider_store.h#L60)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> As an alternative, what if we do the following:

> Add a method on CertificateProviderWrapper to set its store_ member to null.
Change CertificateProviderWrapper dtor call ReleaseCertificateProvider() only if store_ is non-null.
Change the store's dtor iterate through the map and call the method on each wrapper to reset its store_ member.
That way, we won't even need the store to be ref-counted in the first place.

That's doable, but we need to refcount something or the other to make sure that we don't run into use-after-free or time-of-check-to-time-of-use bugs. I've updated the code to share the mutex instead. Note that a private mutex for CertificateProviderWrapper does not work because then we need to run into deadlock issues due to lock ordering between this new mutex and the store's mutex.


</blockquote></details>

Hmm...  I made my suggestion here with the thought that we wouldn't need this kind of synchronization, because the providers would always be destroyed from inside the WorkSerializer.  But I think you're right, that's not true.

In that case, I'd prefer to go back to the `InternallyRefCounted<>` approach.  I think that's much easier to understand than having a ref-counted mutex.

Sorry for steering you wrong here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1393 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaVAWrBp4LJuyxCota:-MMaVAWrBp4LJuyxCotb:b53k4ve) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1393)):*
> ```cpp
>  public:
>   FakeCertificateProvider(
>       std::string root_certificate,
> ```

How about having this take a map from cert name to corresponding root and identity certs?  That way, the tests can be explicit about what names yield what certs.

```
class FakeCertificateProvider final : public grpc_tls_certificate_provider {
 public:
  struct CertData {
    std::string root_certificate;
    grpc_core::PemKeyCertPairList identity_key_cert_pairs;
  };
  using CertDataMap = std::map<std::string /*cert_name*/, CertData>;

  explicit FakeCertificateProvider(CertDataMap cert_data_map)
      : cert_data_map_(std::move(cert_data_map)) {
    // ...
```
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1445 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaTeCJ6pONBDMLzGGo:-MMaTeCJ6pONBDMLzGGp:b-mh68z6) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1445)):*
> ```cpp
> };
> 
> struct FakeCertificateProviderData {
> ```

If you take my suggestion above, this won't be needed, since we can just use  `FakeCertificateProvider::CertDataMap` instead.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1477 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMafSk83gHJS7HpSfSW:-MMafSk92Cu8AOn8X-Y7:bzagxs4) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1477)):*
> ```cpp
>           config) override {
>     return grpc_core::MakeRefCounted<FakeCertificateProvider>(
>         ReadFile(data_.root_certs_path).c_str(),
> ```

Instead of having this factory read the files, we should have the test class read the files, and the tests can pass the resulting contents in here.  That way, if a test wants the same contents for more than one entry in the map, we don't need to read the same file more than once.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1486 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaWr3r2tWJdkwH6wIh:-MMaWr3r2tWJdkwH6wIi:b-czk4iz) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1486)):*
> ```cpp
>   static void set_data(const FakeCertificateProviderData& data) {
>     data_ = data;
>     if (data_.alternate_root_certs_path == nullptr) {
> ```

Let's not have these defaults here.  Instead, let's have the tests just explicitly specify the exact data they want the provider to provide.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1498 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMacg-M5VSD-65TO_lj:-MMaTjWJ7YqFQLBkHCkQ:b-g0fz06) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1498)):*
> ```cpp
> 
>  private:
>   static FakeCertificateProviderData data_;
> ```

This can be a pointer instead of being a copy of the data.  The individual tests can create the map as a local variable and then set this pointer to point to their local variable.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1503 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMafseyDefSuUO803HM:-MMaUCbV5w_3gvdbxkOT:b-o8idn9) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1503)):*
> ```cpp
> FakeCertificateProviderData FakeCertificateProviderFactory1::data_;
> 
> class FakeCertificateProviderFactory2
> ```

There's actually no need for more than one factory implementation.  Instead, we can have just one implementation, and we can pass in the name  ("fake1" vs. "fake2") and a pointer to the global variable that points at the `FakeCertificateProvider::CertDataMap` to be used by the provider.

In other words, something like this:

```
// Global variables for each provider.
FakeCertificateProvider::CertDataMap* g_fake1_cert_data_map = nullptr;
FakeCertificateProvider::CertDataMap* g_fake2_cert_data_map = nullptr;

class XdsSecurityTest : public BasicTest {
 protected:
  static void SetUpTestCase() {
    grpc_core::CertificateProviderRegistry::RegisterCertificateProviderFactory(
        absl::make_unique<FakeCertificateProviderFactory>("fake1", &g_fake1_cert_data_map));
    grpc_core::CertificateProviderRegistry::RegisterCertificateProviderFactory(
        absl::make_unique<FakeCertificateProviderFactory>("fake2", &g_fake2_cert_data_map));
  }
```

Now tests can set `g_fake1_cert_data_map` and `g_fake2_cert_data_map` to point to local variables containing the data to be used for either provider.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1563 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaYTWc36MHjsBUi_gx:-MMaYTWd30wIUvDuSIQI:b1onfx) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1563)):*
> ```cpp
>   grpc_tls_credentials_options_set_server_verification_option(
>       options, GRPC_TLS_SKIP_HOSTNAME_VERIFICATION);
>   std::string root_cert = ReadFile(kCaCertPath);
> ```

I don't think these 8 lines are needed.  They're basically constructing a C++-layer version of the static provider, but then that's not actually being used anywhere, since this code is using the C-core API.

Hmmm... Actually, this makes me wonder why we're using the C-core API here in the first place.  This test in general uses the C++ APIs, so we should probably do the same thing here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1742 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaZwm4857I7KgFdKhe:-MMaZwm4857I7KgFdKhf:b-lpgjh8) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/te [...]

2020-11-20 23:28 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: 16 of 22 files reviewed, 15 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/certificate_provider_store.h, line 60 at r10](https://reviewable.io/reviews/grpc/grpc/24643#-MMW6iQxBvJqZfMNZa97:-MMbyh4JEmOyap-HCoiC:bvxko62) ([raw file](https://github.com/grpc/grpc/blob/f5502e046d660fe09a869c26a6011f6da192edd8/src/core/ext/xds/certificate_provider_store.h#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hmm...  I made my suggestion here with the thought that we wouldn't need this kind of synchronization, because the providers would always be destroyed from inside the WorkSerializer.  But I think you're right, that's not true.

In that case, I'd prefer to go back to the `InternallyRefCounted<>` approach.  I think that's much easier to understand than having a ref-counted mutex.

Sorry for steering you wrong here.
</blockquote></details>

no worries! Reverted!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1393 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaVAWrBp4LJuyxCota:-MMbzBdt5HbQ4tADUENJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1393)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about having this take a map from cert name to corresponding root and identity certs?  That way, the tests can be explicit about what names yield what certs.

```
class FakeCertificateProvider final : public grpc_tls_certificate_provider {
 public:
  struct CertData {
    std::string root_certificate;
    grpc_core::PemKeyCertPairList identity_key_cert_pairs;
  };
  using CertDataMap = std::map<std::string /*cert_name*/, CertData>;

  explicit FakeCertificateProvider(CertDataMap cert_data_map)
      : cert_data_map_(std::move(cert_data_map)) {
    // ...
```
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1445 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaTeCJ6pONBDMLzGGo:-MMbyoWx7_EAt3AyX2aN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1445)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you take my suggestion above, this won't be needed, since we can just use  `FakeCertificateProvider::CertDataMap` instead.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1477 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMafSk83gHJS7HpSfSW:-MMbyq7-5cp002gKlszn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1477)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of having this factory read the files, we should have the test class read the files, and the tests can pass the resulting contents in here.  That way, if a test wants the same contents for more than one entry in the map, we don't need to read the same file more than once.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1486 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaWr3r2tWJdkwH6wIh:-MMbyr5O7XFtcf15-FOG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1486)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's not have these defaults here.  Instead, let's have the tests just explicitly specify the exact data they want the provider to provide.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1498 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMacg-M5VSD-65TO_lj:-MMbyrpm0zSunxoXQeyh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1498)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be a pointer instead of being a copy of the data.  The individual tests can create the map as a local variable and then set this pointer to point to their local variable.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1503 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMafseyDefSuUO803HM:-MMbyt8C3IxXg6TCXcs7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1503)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's actually no need for more than one factory implementation.  Instead, we can have just one implementation, and we can pass in the name  ("fake1" vs. "fake2") and a pointer to the global variable that points at the `FakeCertificateProvider::CertDataMap` to be used by the provider.

In other words, something like this:

```
// Global variables for each provider.
FakeCertificateProvider::CertDataMap* g_fake1_cert_data_map = nullptr;
FakeCertificateProvider::CertDataMap* g_fake2_cert_data_map = nullptr;

class XdsSecurityTest : public BasicTest {
 protected:
  static void SetUpTestCase() {
    grpc_core::CertificateProviderRegistry::RegisterCertificateProviderFactory(
        absl::make_unique<FakeCertificateProviderFactory>("fake1", &g_fake1_cert_data_map));
    grpc_core::CertificateProviderRegistry::RegisterCertificateProviderFactory(
        absl::make_unique<FakeCertificateProviderFactory>("fake2", &g_fake2_cert_data_map));
  }
```

Now tests can set `g_fake1_cert_data_map` and `g_fake2_cert_data_map` to point to local variables containing the data to be used for either provider.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1563 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaYTWc36MHjsBUi_gx:-MMbyucD4SIp-ijH01Xj:b-hpbqky) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1563)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think these 8 lines are needed.  They're basically constructing a C++-layer version of the static provider, but then that's not actually being used anywhere, since this code is using the C-core API.

Hmmm... Actually, this makes me wonder why we're using the C-core API here in the first place.  This test in general uses the C++ APIs, so we should probably do the same thing here.
</blockquote></details>

That's because the C++ API is broken and has refcounting bugs around server authorization callback, and I didn't want to fix it in this PR :)
I removed the extra lines though.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1742 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaZwm4857I7KgFdKhe:-MMbz4yC3OQy8HOwLtOg:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1742)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this TODO can go away now.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1744 at r12](https://reviewable.io/reviews/grpc/grpc/24643#-MMaZvFM4CXkFfmlhiJP:-MMbz5UN27WiBlZ9aHu6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/81eb3e5d5e3a2727878d206a9879f39e7ac2c2a1/test/cpp/end2end/xds_end2end_test.cc#L1744)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per my comment above about using the C++ APIs, I suggest changing this code to something like this:

```
std::shared_ptr<ChannelCredentials> channel_creds =
    GetParam().use_xds_credentials())
        ? experimental::XdsCredentials(CreateTlsFallbackCredentials())
  [...]

2020-11-21 00:27 UTC, markdroth approved these changes
Remaining comments are all cosmetic, and I don't want to keep you from merging this while I'm out of the office next week, so I'll go ahead and approve.

Thanks for doing this -- it looks really good!

> Reviewed 5 of 6 files at r13, 4 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643#-:-MMcBXho-KWCoxQexMTK:bgpqvck)* status: all files reviewed, 9 unresolved discussions (waiting on @yashykt)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 227 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc8Ug86R-wcw9PUCqN:-MMc8Ug86R-wcw9PUCqO:bi7i6zv) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L227)):*
> ```cpp
> char* g_bootstrap_file_v2;
> 
> std::vector<std::string> AuthenticatedIdentity1() { return {"testclient"}; }
> ```

Suggest making these data members of `XdsSecurityTest`, along side the data members for the cert and key contents themselves.  That way, we can use names that make it clear which identity corresponds to which certs, which will make the tests easier to read.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1360 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc8ta05VqzEa9DHyIy:-MMc8ta05VqzEa9DHyIz:beda07z) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1360)):*
> ```cpp
>   grpc_slice slice;
>   GPR_ASSERT(
>       GRPC_LOG_IF_ERROR("load_file", grpc_load_file(file_path, 1, &slice)));
> ```

I think the second parameter can be zero here.  We don't need null termination, since we're not returning the cert as a C-style string.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1398 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc6Acq1B96AowPJybm:-MMc6Acq1B96AowPJybn:b-gzri8j) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1398)):*
> ```cpp
>       absl::optional<grpc_core::PemKeyCertPairList> pem_key_cert_pairs;
>       if (root_being_watched) {
>         root_certificate = cert_data_map_[cert_name].root_certificate;
> ```

This should probably report an error to the distributor if the key is not found in the map.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1401 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc6End5HWUkVENAQdY:-MMc6End5HWUkVENAQdZ:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1401)):*
> ```cpp
>       }
>       if (identity_being_watched) {
>         pem_key_cert_pairs = cert_data_map_[cert_name].identity_key_cert_pairs;
> ```

Same here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1454 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc6Uf35JvsOV2lnAzX:-MMc6Uf35JvsOV2lnAzY:b-9z4aub) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1454)):*
> ```cpp
>           config) override {
>     return grpc_core::MakeRefCounted<FakeCertificateProvider>(
>         *(*cert_data_map_));
> ```

No need for the parens here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1454 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc7HST50p-xdRjST0i:-MMc7HST50p-xdRjST0j:b-qwld99) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1454)):*
> ```cpp
>           config) override {
>     return grpc_core::MakeRefCounted<FakeCertificateProvider>(
>         *(*cert_data_map_));
> ```

If `*cert_data_map_` is null, we should probably return null here.  (Otherwise, there's no point in resetting the global pointers to null in `TearDown()`.)
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1494 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc6wiM4PXTF4FZ9NZe:-MMc6wiM4PXTF4FZ9NZf:bsjaryh) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1494)):*
> ```cpp
>       grpc_tls_credentials_create(options));
>   grpc_tls_server_authorization_check_config_release(check_config);
>   auto call_creds = std::make_shared<SecureCallCredentials>(
> ```

If you have the fallback creds use a different cert with a different client identity, then these call creds won't be needed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2102 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc9I1M-y7OJx1uFZLl:-MMc9I1M-y7OJx1uFZLm:b-pw0itf) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L2102)):*
> ```cpp
> 
>     virtual std::shared_ptr<ServerCredentials> Credentials() {
>       return std::shared_ptr<ServerCredentials>(new SecureServerCredentials(
> ```

This can use `std::make_shared<>`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5328 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc9fRbCU5s8BFRP3Zl:-MMc9fRbCU5s8BFRP3Zm:b-6bkaui) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L5328)):*
> ```cpp
>   // connections are expected to use fallback credentials.
>   void UpdateAndVerifyXdsSecurityConfiguration(
>       absl::string_view identity_instance_name,
> ```

Please swap the order of the params here so that the root params come before the identity params.  If we always use the order root-then-identity throughout, it makes the tests much easier to read.


<!-- Sent from Reviewable.io -->

2020-11-21 01:26 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: 19 of 20 files reviewed, 9 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 227 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc8Ug86R-wcw9PUCqN:-MMcORxG99JFJAsJCjoM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L227)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest making these data members of `XdsSecurityTest`, along side the data members for the cert and key contents themselves.  That way, we can use names that make it clear which identity corresponds to which certs, which will make the tests easier to read.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1360 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc8ta05VqzEa9DHyIy:-MMcOSw81n2XIhdiUbOq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1360)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the second parameter can be zero here.  We don't need null termination, since we're not returning the cert as a C-style string.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1398 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc6Acq1B96AowPJybm:-MMcOcrz2eVwwajKrvaw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1398)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should probably report an error to the distributor if the key is not found in the map.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1401 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc6End5HWUkVENAQdY:-MMcOdAx8cNI1mAxmnWN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1401)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1454 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc6Uf35JvsOV2lnAzX:-MMcOfCW7ZC0HIqNnZGc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1454)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the parens here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1454 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc7HST50p-xdRjST0i:-MMcOfroCRgHt8Snihmn:b-83k61j) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1454)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If `*cert_data_map_` is null, we should probably return null here.  (Otherwise, there's no point in resetting the global pointers to null in `TearDown()`.)
</blockquote></details>

You are right, though to be proper, the nullptr set should be done in the test itself to be safe.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1494 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc6wiM4PXTF4FZ9NZe:-MMcP-VtCARxkfqyYSfR:bnv8f2x) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1494)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you have the fallback creds use a different cert with a different client identity, then these call creds won't be needed.
</blockquote></details>

Yeah, I'm already using different creds for fallback. It was an additional check. Removed anyway
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2102 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc9I1M-y7OJx1uFZLl:-MMcP7IoCYDLO_-gVzWB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L2102)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can use `std::make_shared<>`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5328 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc9fRbCU5s8BFRP3Zl:-MMcP89p2I5XhvCz24Ii:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L5328)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please swap the order of the params here so that the root params come before the identity params.  If we always use the order root-then-identity throughout, it makes the tests much easier to read.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-23 21:28 UTC, yashykt commented
We have an infrastructure issue going on but based on previous test runs, there doesn't seem to be an issue with this PR

2020-11-23 21:38 UTC, merged

2020-11-30 16:38 UTC, markdroth reviewed
Just a few minor cosmetic comments to follow up on in a subsequent PR.

Thanks!

> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643#-:-MNP0INc2jwfeoH6rjDk:b52du7z)* status: all files reviewed, 6 unresolved discussions (waiting on @yashykt)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 1454 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc7HST50p-xdRjST0i:-MNOypTV-Fh1DjrssV4D:b2jn0bi) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1454)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

You are right, though to be proper, the nullptr set should be done in the test itself to be safe.
</blockquote></details>

I think you misinterpretted my comment.  What I meant is to do this:

```
if (*cert_data_map_ == nullptr) return nullptr;
```

Also, I don't think it's actually safer to reset the global pointers to null in the individual tests, because we might forget to do it in a given test.  I think it's better to do it in `TearDown()`, so that we can be sure it's done after every test.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1454 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc6Uf35JvsOV2lnAzX:-MNOz7hE73cXJ3mC8csw:bhtnsbh) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1454)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look like this was done; I still see `*(*cert_data_map_)`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1388 at r16](https://reviewable.io/reviews/grpc/grpc/24643#-MNOzF-39sjGSmWY8ohX:-MNOzF-39sjGSmWY8ohY:b-afkt56) ([raw file](https://github.com/grpc/grpc/blob/33b4911a508cb3ee2d682fa03a107b3cae944604/test/cpp/end2end/xds_end2end_test.cc#L1388)):*
> ```cpp
>         absl::optional<grpc_core::PemKeyCertPairList> pem_key_cert_pairs;
>         if (root_being_watched) {
>           root_certificate = cert_data_map_[cert_name].root_certificate;
> ```

Can use `it->root_certificate` here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1392 at r16](https://reviewable.io/reviews/grpc/grpc/24643#-MNOzHQd6y6DHG1MaZA6:-MNOzHQd6y6DHG1MaZA7:b-yno694) ([raw file](https://github.com/grpc/grpc/blob/33b4911a508cb3ee2d682fa03a107b3cae944604/test/cpp/end2end/xds_end2end_test.cc#L1392)):*
> ```cpp
>         if (identity_being_watched) {
>           pem_key_cert_pairs =
>               cert_data_map_[cert_name].identity_key_cert_pairs;
> ```

`it->identity_key_cert_pairs`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5295 at r16](https://reviewable.io/reviews/grpc/grpc/24643#-MNP03-N43uaJjCHle_R:-MNP03-N43uaJjCHle_S:b7ygkwp) ([raw file](https://github.com/grpc/grpc/blob/33b4911a508cb3ee2d682fa03a107b3cae944604/test/cpp/end2end/xds_end2end_test.cc#L5295)):*
> ```cpp
>     bad_root_cert_ = ReadFile(kBadClientCertPath);
>     identity_pair_1_ = ReadTlsIdentityPair(kClientKeyPath, kClientCertPath);
>     identity_pair_2_ = ReadTlsIdentityPair(kServerKeyPath, kServerCertPath);
> ```

Maybe call this `fallback_identity_pair_`, and change `authenticated_identity_2_` to `fallback_identity_`?  That might make the tests a little easier to follow.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5433 at r16](https://reviewable.io/reviews/grpc/grpc/24643#-MNP-421358EoXouA-F0:-MNP-421358EoXouA-F1:b-rbvp8y) ([raw file](https://github.com/grpc/grpc/blob/33b4911a508cb3ee2d682fa03a107b3cae944604/test/cpp/end2end/xds_end2end_test.cc#L5433)):*
> ```cpp
>                                           "", authenticated_identity_1_);
>   UpdateAndVerifyXdsSecurityConfiguration("fake_plugin2", "",
>                                           "fake_plugin1" /* bad root */, "", {},
> ```

The "bad root" comment is now in the wrong place.


<!-- Sent from Reviewable.io -->

2020-12-01 00:13 UTC, yashykt commented
Thanks for the follow-up! PR - https://github.com/grpc/grpc/pull/24858





<!-- Sent from Reviewable.io -->

2020-12-01 00:13 UTC, yashykt reviewed
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24643)* status: all files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 1454 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc6Uf35JvsOV2lnAzX:-MNQd1szEoLMICWuo5WW:bpi561r) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1454)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this was done; I still see `*(*cert_data_map_)`.
</blockquote></details>

My bad, included in cleanup PR
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1454 at r14](https://reviewable.io/reviews/grpc/grpc/24643#-MMc7HST50p-xdRjST0i:-MNQd6h31l8-P9kdPn5B:b5e337p) ([raw file](https://github.com/grpc/grpc/blob/4cb142f137f9b45e4ece2515a4cb06a314da38bc/test/cpp/end2end/xds_end2end_test.cc#L1454)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you misinterpretted my comment.  What I meant is to do this:

```
if (*cert_data_map_ == nullptr) return nullptr;
```

Also, I don't think it's actually safer to reset the global pointers to null in the individual tests, because we might forget to do it in a given test.  I think it's better to do it in `TearDown()`, so that we can be sure it's done after every test.
</blockquote></details>

Done. reverted!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1388 at r16](https://reviewable.io/reviews/grpc/grpc/24643#-MNOzF-39sjGSmWY8ohX:-MNQd-881N_3XrMIuE_A:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/33b4911a508cb3ee2d682fa03a107b3cae944604/test/cpp/end2end/xds_end2end_test.cc#L1388)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can use `it->root_certificate` here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1392 at r16](https://reviewable.io/reviews/grpc/grpc/24643#-MNOzHQd6y6DHG1MaZA6:-MNQd-Qe7HyA-0eg7NXT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/33b4911a508cb3ee2d682fa03a107b3cae944604/test/cpp/end2end/xds_end2end_test.cc#L1392)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`it->identity_key_cert_pairs`
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5295 at r16](https://reviewable.io/reviews/grpc/grpc/24643#-MNP03-N43uaJjCHle_R:-MNQdB9I7u8JFqqFx9Ak:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/33b4911a508cb3ee2d682fa03a107b3cae944604/test/cpp/end2end/xds_end2end_test.cc#L5295)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Maybe call this `fallback_identity_pair_`, and change `authenticated_identity_2_` to `fallback_identity_`?  That might make the tests a little easier to follow.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5433 at r16](https://reviewable.io/reviews/grpc/grpc/24643#-MNP-421358EoXouA-F0:-MNQdBsK8_dHFqL6TMS7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/33b4911a508cb3ee2d682fa03a107b3cae944604/test/cpp/end2end/xds_end2end_test.cc#L5433)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The "bad root" comment is now in the wrong place.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->