Support null bytes for UNIX Abstract Socket Addresses
grpc/grpc pull request #24701
Opened 2020-11-07 01:16 UTC by drfloob

There are some small, notable changes in the way URIs are parsed:

* Repeated query parameters are not supported.
* All "bare" query parameters such as `?a` and `?a=&b` are stored as
query keys `a` and `b` with empty-string values.

2020-11-09 16:48 UTC, markdroth reviewed
This looks like a great start!

Don't let the number of comments here put you off -- it's mostly just things to learn as part of a new code-base.

Please let me know if you have any questions.  Thanks!

> Reviewed 48 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701#-:-MLhtxxGEh2GTqlnPpXB:blxqpkc)* status: all files reviewed, 48 unresolved discussions (waiting on @drfloob)

___
*[vscode_workspace.code-workspace, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhWO2_2xRJBgvETlsA:-MLhWO2_2xRJBgvETlsB:bne9wfy) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/vscode_workspace.code-workspace#L1)):*
> ```
> {
> ```

Was this file added to the PR by mistake?  I don't know what it's for.
___
*[include/grpcpp/grpcpp.h, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhgOdYC9Z_X6WKPAgq:-MLhgOdYC9Z_X6WKPAgr:b-u6yof8) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/include/grpcpp/grpcpp.h#L62)):*
> ```objc
> #include <grpcpp/server_context.h>
> #include <grpcpp/server_posix.h>
> #include <string>
> ```

This seems unrelated to the rest of this PR.  I suggest splitting it off into a different one.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1684 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhgrlJ6gsHCqkWCJs6:-MLhgrlJ6gsHCqkWCJs7:b-y35rsc) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/client_channel.cc#L1684)):*
> ```cpp
>     return;
>   }
>   const auto& uri = grpc::GrpcURI::Parse(server_uri, true);
> ```

The style guide suggests limiting use of `auto` to places where it actually helps readability, such as writing out an iterator type or declaring the type of a variable declared equal to an expression that inherently defines the type.  In this case, I think `auto` hurts more than it helps, because it's not obvious to the reader that the factory function returns a `unique_ptr<>`.

https://google.github.io/styleguide/cppguide.html#Type_deduction

Also, this is not a reference, it's an actual value, so the `&` is a no-op here.  I believe this works only because of a weird edge case in the compiler, as per https://abseil.io/tips/101.

Please fix throughout this PR.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1685 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhhpHm1rx5h1qBjaKp:-MLhhpHm1rx5h1qBjaKq:b-xu5dtt) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/client_channel.cc#L1685)):*
> ```cpp
>   }
>   const auto& uri = grpc::GrpcURI::Parse(server_uri, true);
>   if (uri != nullptr && uri->path()[0] != '\0') {
> ```

This can be `!uri->path.empty()`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1686 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhhzvb6OuHB6g9yea6:-MLhhzvb6OuHB6g9yea7:b-c5av78) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/client_channel.cc#L1686)):*
> ```cpp
>   const auto& uri = grpc::GrpcURI::Parse(server_uri, true);
>   if (uri != nullptr && uri->path()[0] != '\0') {
>     server_name_.reset(gpr_strdup(
> ```

I suggest changing `server_name_` from `char*` to `std::string`.  Then we can write this as:

```
server_name_  = std::string(absl::StripPrefix(uri->path(), "/"));
```

Note that it's not necessarily safe to access `uri->path()[0]` unless we know the string has at least length 1.  But `absl::StripPrefix()` should do the right thing in any case.
___
*[src/core/ext/filters/client_channel/http_proxy.cc, line 21 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhjKqaAAnvxMkctBrE:-MLhjKqaAAnvxMkctBrF:b7toukx) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/http_proxy.cc#L21)):*
> ```cpp
> #include "src/core/ext/filters/client_channel/http_proxy.h"
> 
> #include <grpc/support/alloc.h>
> ```

The include order and formatting was already correct here the way it was.  The style guide says to include standard C and C++ headers, then external includes like absl, and then includes from this project, which includes the grpc headers:

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

To say this another way, the important distinction here is where the header comes from, not whether it uses angle brackets or quotes.

Also, in C-core, port_platform.h must be the first include in every file for portability reasons.

Please fix throughout this PR.
___
*[src/core/ext/filters/client_channel/http_proxy.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhjsM94qB8tk7bhrAe:-MLhjsM94qB8tk7bhrAf:b-c07v5k) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/http_proxy.cc#L48)):*
> ```cpp
>  * unchanged. It is caller's responsibility to gpr_free user_cred.
>  */
> char* GetHttpProxyServer(const grpc_channel_args* args, char** user_cred) {
> ```

We could also change this to return `std::string` instead of `char*`.  But if that winds up becoming a viral change that spreads out into a lot of other code, it's also fine to leave this as-is for now.
___
*[src/core/ext/filters/client_channel/http_proxy.cc, line 71 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhkeva1htCVQ5Mk6w9:-MLhkeva1htCVQ5Mk6wA:brir4ow) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/http_proxy.cc#L71)):*
> ```cpp
>   if (uri_str[0] == '\0') goto done;
>   uri = grpc::GrpcURI::Parse(uri_str, /*suppress_errors=*/false);
>   if (uri == nullptr || uri->authority() == "") {
> ```

Prefer  `uri->authority().empty()`.
___
*[src/core/ext/filters/client_channel/http_proxy.cc, line 176 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhlKLTEl2ZmDGnJ64O:-MLhlKLTEl2ZmDGnJ64P:b-y0vrvv) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/http_proxy.cc#L176)):*
> ```cpp
>         (char*)GRPC_ARG_HTTP_CONNECT_SERVER,
>         const_cast<char*>(
>             std::string(absl::StripPrefix(uri->path(), "/")).c_str()));
> ```

This is almost certainly not doing what you expect.  The `std::string` object here is a temporary, which means it goes out of scope as soon as this statement is finished, which means you'll be left with a channel arg pointing to an invalid string.

However, since `absl::StripPrefix()` returns an `absl::string_view` pointing to the same memory as the string you pass into it, you can just say something like `absl::StripPrefix(uri->path().c_str(), "/").data()`, which will be properly null-terminated without constructing a new `std::string`.
___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhnxqG2HWYzBkjALUw:-MLhnxqG2HWYzBkjALUx:bqqgepy) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver_factory.h#L51)):*
> ```objc
>   /// Returns a bool indicating whether the input uri is valid to create a
>   /// resolver.
>   virtual bool IsValidUri(const grpc::GrpcURI* uri) const = 0;
> ```

It looks like the resolver registry code will never pass in a null value here.  If so, then this could be a reference instead of a pointer.
___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhmaaDBg-aNaWWOA1X:-MLhmaaDBg-aNaWWOA1Y:b-dy7bqk) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver_factory.h#L58)):*
> ```objc
>   /// Returns a string representing the default authority to use for this
>   /// scheme.
>   virtu [...]

2020-11-09 23:36 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: 7 of 60 files reviewed, 48 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[vscode_workspace.code-workspace, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhWO2_2xRJBgvETlsA:-MLi765W4eBy8KWA9Xxe:b-uhwkju) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/vscode_workspace.code-workspace#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Was this file added to the PR by mistake?  I don't know what it's for.
</blockquote></details>

Yes, this was included by mistake. Removed.
___
*[include/grpcpp/grpcpp.h, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhgOdYC9Z_X6WKPAgq:-MLiOYIyET7ahi_kGIHC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/include/grpcpp/grpcpp.h#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This seems unrelated to the rest of this PR.  I suggest splitting it off into a different one.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1684 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhgrlJ6gsHCqkWCJs6:-MLiOyan900z_FDww0rJ:b-5e0wtc) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/client_channel.cc#L1684)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The style guide suggests limiting use of `auto` to places where it actually helps readability, such as writing out an iterator type or declaring the type of a variable declared equal to an expression that inherently defines the type.  In this case, I think `auto` hurts more than it helps, because it's not obvious to the reader that the factory function returns a `unique_ptr<>`.

https://google.github.io/styleguide/cppguide.html#Type_deduction

Also, this is not a reference, it's an actual value, so the `&` is a no-op here.  I believe this works only because of a weird edge case in the compiler, as per https://abseil.io/tips/101.

Please fix throughout this PR.
</blockquote></details>

Done. Here and elsewhere.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1685 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhhpHm1rx5h1qBjaKp:-MLiVeRSC2raFEb4Us1D:b-r89kae) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/client_channel.cc#L1685)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be `!uri->path.empty()`.
</blockquote></details>

Done. I was questioning if we want to make a distinction here between empty strings and strings that begin with the null byte, but I see that doesn't apply here.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1686 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhhzvb6OuHB6g9yea6:-MLiv7ktDfl-k75B4Unt:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/client_channel.cc#L1686)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest changing `server_name_` from `char*` to `std::string`.  Then we can write this as:

```
server_name_  = std::string(absl::StripPrefix(uri->path(), "/"));
```

Note that it's not necessarily safe to access `uri->path()[0]` unless we know the string has at least length 1.  But `absl::StripPrefix()` should do the right thing in any case.
</blockquote></details>

Done
___
*[src/core/ext/filters/client_channel/http_proxy.cc, line 21 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhjKqaAAnvxMkctBrE:-MLi_iySAcMveWC4emUK:brunuc5) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/http_proxy.cc#L21)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The include order and formatting was already correct here the way it was.  The style guide says to include standard C and C++ headers, then external includes like absl, and then includes from this project, which includes the grpc headers:

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

To say this another way, the important distinction here is where the header comes from, not whether it uses angle brackets or quotes.

Also, in C-core, port_platform.h must be the first include in every file for portability reasons.

Please fix throughout this PR.
</blockquote></details>

Thanks. My IDE is no longer allowed to reorder includes.
___
*[src/core/ext/filters/client_channel/http_proxy.cc, line 71 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhkeva1htCVQ5Mk6w9:-MLiomzIBqy7NiUtNvnN:b-5e0wtc) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/http_proxy.cc#L71)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Prefer  `uri->authority().empty()`.
</blockquote></details>

Done. Here and elsewhere.
___
*[src/core/ext/filters/client_channel/http_proxy.cc, line 176 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhlKLTEl2ZmDGnJ64O:-MLiwH2g8a_0g4wAe328:bfvwl5a) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/http_proxy.cc#L176)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is almost certainly not doing what you expect.  The `std::string` object here is a temporary, which means it goes out of scope as soon as this statement is finished, which means you'll be left with a channel arg pointing to an invalid string.

However, since `absl::StripPrefix()` returns an `absl::string_view` pointing to the same memory as the string you pass into it, you can just say something like `absl::StripPrefix(uri->path().c_str(), "/").data()`, which will be properly null-terminated without constructing a new `std::string`.
</blockquote></details>

Good parsing, and good suggestion! Thanks.
___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhmkvq3PmnytmxBBsK:-MLizqqjDMDujC-SnAJO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver_factory.h#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest using `absl::StripPrefix()` here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 147 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhp-CL-DgXcMs8IjXX:-MLj1BE6DHVL1OmsZbAw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L147)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Prefix `!string.empty()` to `string != ""`.

Please fix throughout the PR.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 91 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhpSH34p5voVnUtkFH:-MLj1j8uE-YUnkDW1rpU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L91)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should use `absl::string_view` instead of `std::string`, to avoid making unnecessary copies.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/res [...]

2020-11-10 01:07 UTC, markdroth reviewed
This is moving in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 55 of 56 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701#-:-MLjg8pr7ZBuBc43N2OL:b-k1b92a)* status: all files reviewed, 40 unresolved discussions (waiting on @drfloob)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1685 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhhpHm1rx5h1qBjaKp:-MLjcyCk-0SU1BTEkXDt:b-ldw8fc) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/client_channel.cc#L1685)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Done. I was questioning if we want to make a distinction here between empty strings and strings that begin with the null byte, but I see that doesn't apply here.
</blockquote></details>

Yeah.  The only reason we were checking the nul byte here was because it was a C-style string.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1684 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjcrg64TDDBt3Puifs:-MLjcrg64TDDBt3Puift:byla3lh) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/ext/filters/client_channel/client_channel.cc#L1684)):*
> ```cpp
>     return;
>   }
>   const std::unique_ptr<grpc::GrpcURI> uri =
> ```

The `const` isn't really useful for `unique_ptr`.

Same thing throughout.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 321 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjdwCC3ofQVWuRimm0:-MLjdwCDA2O2seMF9w1_:bza6eph) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L321)):*
> ```cpp
>       grpc::GrpcURI::Parse(server_uri, /*suppress_errors=*/true);
>   GPR_ASSERT(!uri->path().empty());
>   // DO NOT SUBMIT - were do we need to ultimately have null bytes supported?
> ```

I don't think it's  an issue here.
___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 95 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhpgN323sz66C6Fza5:-MLjf4HM8cDaWxEhyFhX:b-ex931p) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L95)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

I debated this myself. For a sockaddr impl, could we do something like `grpc::URI::Parse(absl::StrCat(uri->scheme(), ":", ith_path)), true)`? Auth, fragment, and query don't mean much in this scenario, right?

I opted for this path-setter approach for efficiency reasons, but I really didn't like the resulting design. Without it, we can make all the members const.
</blockquote></details>

Yes, that would work fine.  These URI schemes don't support authority, query, or fragment.

Making the data members const is probably not a good idea, though.  For details, see https://abseil.io/tips/177.
___
*[src/core/lib/iomgr/parse_address.cc, line 31 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjcPB_9PTm_LCj2GnJ:-MLjcPB_9PTm_LCj2GnK:b-pc5nos) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/lib/iomgr/parse_address.cc#L31)):*
> ```cpp
> #include "src/core/lib/iomgr/sockaddr.h"
> #include "src/core/lib/iomgr/socket_utils.h"
> #ifdef GRPC_HAVE_UNIX_SOCKET
> ```

This block should be moved up next to the other C headers.
___
*[src/core/lib/iomgr/parse_address.cc, line 35 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjcU5FBdx4hGHzi_QI:-MLjcU5FBdx4hGHzi_QJ:bckx80i) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/lib/iomgr/parse_address.cc#L35)):*
> ```cpp
> #endif
> 
> #include <grpc/support/alloc.h>
> ```

These can be moved up to be under the absl headers.
___
*[src/core/lib/iomgr/parse_address.cc, line 42 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjcXwc7BwJsROkZjUr:-MLjcXwc7BwJsROkZjUs:bfv4ref) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/lib/iomgr/parse_address.cc#L42)):*
> ```cpp
> #include "src/core/lib/gprpp/host_port.h"
> 
> #ifdef GRPC_POSIX_SOCKET
> ```

This block can be moved up next to the other C headers.
___
*[src/core/lib/uri/uri_parser.cc, line 238 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhcw7nEkFTW-UD2jjT:-MLj_KbQ9ATc4b-5qB63:blsx23o) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.cc#L238)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

I didn't use MaxSplits here primarily to support cases like `?a====`, but the reasoning is not totally obvious. There is a test for this with expected behavior. With MaxSplits=1, we'd end up with a pair like {{'a', '==='}}, but this is not valid since = is a reserved character in rfc3986. For backwards compatibility as well, `=` was exclusively treated as separator, never part of a value. We could as you suggest use MaxSplits=1 and filter the extra `=` (and other reserved characters) out of the value string, but this seemed like an unnecessary extra step. MaxSplits=2 would work as well to eliminate extraneous `=`, but again that seemed unnecessary.

I'd suggest we leave it as is without using MaxSplits. What do you think? 
</blockquote></details>

It is a reserved character in the RFC, but I don't actually see anything in there about how it should be handled if it appears in multiple places in a query string.  In fact, the RFC doesn't really say much in general about how query strings are supposed to be parsed; presumably, that is defined by each specific URI scheme.  So it's not clear to me what the "right" behavior is.

There's a TODO in the current code questioning whether the current behavior is correct, and my guess is that it was originally done this way just because it was the simplest thing to implement and we didn't need anything else.  I don't think that's much of an argument in favor of the current behavior, and I find it strange that we would just ignore any text after the second `=` in a query param.

What do other URI parser implementations do?
___
*[src/core/lib/uri/uri_parser.cc, line 269 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhfSmz552iNrlS2SAJ:-MLjbrRg1aOeWfa0RL14:b-jsljc2) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.cc#L269)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Done. I expect most modern compilers would avoid unnecessary copies via copy elision, but I realize gRPC supports older compilers as well.
</blockquote></details>

I don't actually know that even modern compilers will do this by default.  You can probably find out by playing with godbolt.org if you want.
___
*[src/core/lib/uri/uri_parser.cc, line 265 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjbear4YB4ibpxT8Xy:-MLjbear4YB4ibpxT8Xz:b-wnlncr) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/lib/uri/uri_parser.cc#L265)):*
> ```cpp
>   }
> 
>   return absl::WrapUnique(new GrpcURI(std::move(scheme), std::move(authority),
> ```

If we are going to return a `unique_ptr` here, then we should use `absl::make_unique<GrpcUri>(...)`.  Using `WrapUnique()` doesn't make sense if the expression you're passing it is `new ClassName(...)`.
___
*[src/objective-c/BoringSSL-GRPC.podspec, line 79 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjc6Vn1Lw0o0a9kOVu:-MLjc6Vn1Lw0o0a9kOVv:b-azshq4) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/objective-c/BoringSSL-GRPC.podspec#L79)):*
> ```Ruby
>   s.source = {
>     :git => 'https:// [...]

2020-11-10 20:43 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: all files reviewed, 40 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1684 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjcrg64TDDBt3Puifs:-MLn_3Js5vwPfc3AD67-:b48mzqv) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/ext/filters/client_channel/client_channel.cc#L1684)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `const` isn't really useful for `unique_ptr`.

Same thing throughout.
</blockquote></details>

I'm going to replace the unique_ptr impl with a `StatusOr<URI>` version as we discussed. But for the sake of discussion, a const uniqe_ptr cannot transfer ownership, which is nice to enforce if that's the intention. There's one place in this code where the unique_ptr is non-const, and that's because ownership needs to be transferred.
___
*[src/core/ext/filters/client_channel/resolver_registry.cc, line 81 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhnMQgC4axNWywYRQn:-MLnaiULCV4gspF9jSWg:b171yjw) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver_registry.cc#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The fact that we're re-parsing the same two URIs that we already parsed here is IMHO a result of the ugly way that the existing API handles errors.  As per my suggestion elsewhere, having `Parse()` return an `absl::StatusOr<>` would make a lot more sense.
</blockquote></details>

Totally in agreement, I'll make that change.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 321 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjdwCC3ofQVWuRimm0:-MLnazuVDe4avBCtf1Da:bbbdvvx) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L321)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think it's  an issue here.
</blockquote></details>

ack, thanks.
___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 95 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhpgN323sz66C6Fza5:-MLnb7dB0hPvsNaS1ls5:bkt45cx) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L95)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes, that would work fine.  These URI schemes don't support authority, query, or fragment.

Making the data members const is probably not a good idea, though.  For details, see https://abseil.io/tips/177.
</blockquote></details>

I'll leave them non-const, no issue. Regarding that ToTW, I hadn't seen this one yet! Thanks. I am in the habit of designing immutable classes when there isn't a great case for mutability, and there's no need for mutability here at the moment. The const-member design makes a lot more sense with a liberal use of smart pointers - copies & moves become quite cheap. But since we're moving away from smart pointers for the URI parser, it makes sense to leave these non-const.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhqn6e1MnqF9ClDE0U:-MLngCkV5WoxYY6hgtS3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/security/credentials/external/external_account_credentials.cc#L127)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the parens here.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/external_account_credentials.cc, line 220 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhqpeb2qAMYSXYUtgl:-MLngCX8EWRBfIF4l-ta:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/security/credentials/external/external_account_credentials.cc#L220)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhrfTiBBPt-Qovxl89:-MLngduuB5QnYA30Fyon:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We could just store the result of the factory function directly into `url_`.  There's not really any benefit to having the local variable `url` here.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 138 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhrr5vBW8nhX-nrdad:-MLnhCH908vnVS4YaaYm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L138)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the parens here.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.h, line 37 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhXTQVE4SGOshTD-dA:-MLnhUdWBr8T5iN_RemG:b-x8y4cx) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Returning `std::string` here means that you're going to make a new copy of the string every time one of these accessors is called, which is wasteful.  Accessor methods like these should return const references instead (i.e., `const std::string&`).
</blockquote></details>

Of course, good catch. Done.
___
*[src/core/lib/uri/uri_parser.h, line 40 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhXdDn3X0ax8wkDKMd:-MLnha6170V1rC_pRzdF:b-aevzw0) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L40)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this needed?  I think it shouldn't be, since the URI is intended to be constructed from the original text, not pieced together by the caller.

If this is needed, then it might be better to just expost the ctor and allow clients to call it directly.
</blockquote></details>

This was needed for one use case, which has been removed. See my previous comment on sockaddr_resolver.
___
*[src/core/lib/uri/uri_parser.h, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhYN5W0lD-6J2EOGUK:-MLniRUU3aNvM7_fplaF:boopsup) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In general, it's not recommended to make ctors private, even when you expect that callers will only use the factory function.  For details, see https://abseil.io/tips/134.
</blockquote></details>

I don't read that as "not recommended" really, but I'm happy to discuss this situation. The issue here is that parsing the URI string can fail, and a valid URI string is essential for creating a URI object. If a public ctor failed, to try to protect against the object being in an invalid or partially constructed state, we'd need something like an "is_valid" flag on the object itself, and clients would need to  [...]

2020-11-10 22:05 UTC, markdroth reviewed
Continuing to move in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 56 files at r2, 12 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701#-:-MLoAzuB7bek_K7EF42K:b-kcw4zu)* status: all files reviewed, 27 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1684 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjcrg64TDDBt3Puifs:-MLoAMkjERAxmZK6rXLi:b-e54qei) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/ext/filters/client_channel/client_channel.cc#L1684)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

I'm going to replace the unique_ptr impl with a `StatusOr<URI>` version as we discussed. But for the sake of discussion, a const uniqe_ptr cannot transfer ownership, which is nice to enforce if that's the intention. There's one place in this code where the unique_ptr is non-const, and that's because ownership needs to be transferred.
</blockquote></details>

This is admittedly a gray area, but I personally don't think that `const` is very valuable in situations like this.  There aren't likely to be bugs caused by accidentally transferring ownership, so it doesn't really protect from much.  And it does add a little cognitive overhead when thinking about the code, because you need to distinguish between the `unique_ptr<>` being `const` or the object it points to being `const`.
___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 95 at r4](https://reviewable.io/reviews/grpc/grpc/24701#-MLo8Ilx9a1jcxYKoGHM:-MLo8Ilx9a1jcxYKoGHN:b-hgsdy4) ([raw file](https://github.com/grpc/grpc/blob/12547afdc91c1e298ff9c2a3ef470b8f6ca0c8ac/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L95)):*
> ```cpp
>   bool errors_found = false;
>   for (const auto& ith_path : path_parts) {
>     std::unique_ptr<grpc::GrpcURI> ith_uri =
> ```

As I mention elsewhere, this is a case where we don't really need to parse a URI string.  If we exposed the URI ctor, then we could instead simply construct the URI from its component parts:

```
URI ith_uri(uri->scheme(), "", ith_path,  {}, "");
```
___
*[src/core/lib/security/credentials/oauth2/oauth2_credentials.cc, line 541 at r4](https://reviewable.io/reviews/grpc/grpc/24701#-MLo8y__1KYbuXTUvPGK:-MLo8y__1KYbuXTUvPGL:b-yyimw5) ([raw file](https://github.com/grpc/grpc/blob/12547afdc91c1e298ff9c2a3ef470b8f6ca0c8ac/src/core/lib/security/credentials/oauth2/oauth2_credentials.cc#L541)):*
> ```cpp
>  public:
>   StsTokenFetcherCredentials(
>       std::unique_ptr<grpc::GrpcURI> sts_url,  // Ownership transferred.
> ```

I think the "ownership transferred" comment is not useful anymore.  Those kind of comments are needed when you're passing around raw pointers, as we do in C-style APIs.  But in C++ APIs, it's usually better to use smart pointers or pass-by-value (letting the caller decide whether to use `std::move()`) to let the compiler enforce ownership semantics.  Then there's no way to use the API *without* obeying the ownership semantics, so there's no need to document them.
___
*[src/core/lib/uri/uri_parser.h, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhYN5W0lD-6J2EOGUK:-MLo0gTaAq3lwTcbb9CM:bgh92pj) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L48)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

I don't read that as "not recommended" really, but I'm happy to discuss this situation. The issue here is that parsing the URI string can fail, and a valid URI string is essential for creating a URI object. If a public ctor failed, to try to protect against the object being in an invalid or partially constructed state, we'd need something like an "is_valid" flag on the object itself, and clients would need to be careful to not rely on the other methods of the object without checking the flag first. Making the ctor private and having a public factory method that can only return fully-constructed/valid objects (or explicit errors) makes it harder to use this class incorrectly. Verification is no longer the client's responsibility.
</blockquote></details>

To be clear, I'm not suggesting that we eliminate the factory method for parsing; I'm just suggesting that we also expose the ctor.

I think there are two use-cases here:
1. Parsing a URI string.  This can fail, and callers can use the factory method for it.
2. Constructing a URI object from component parts.  This cannot fail, and callers can use the ctor for it.

An example of the second case is the sockaddr resolver code, where we're putting together a scheme and a path.  There really is no reason we need to do any parsing there; we should really be able to just instantiate the object with the relevant fields.

Also, consider the fact that in the future, it may be useful to add a method to do the opposite of parsing by converting the components into a URI string.
___
*[src/core/lib/uri/uri_parser.cc, line 271 at r4](https://reviewable.io/reviews/grpc/grpc/24701#-MLo2j7WCiZsjzQCaQMH:-MLo2j7WCiZsjzQCaQMI:bndnh7t) ([raw file](https://github.com/grpc/grpc/blob/12547afdc91c1e298ff9c2a3ef470b8f6ca0c8ac/src/core/lib/uri/uri_parser.cc#L271)):*
> ```cpp
>   }
> 
>   return absl::make_unique<GrpcURI>((std::move(scheme), std::move(authority),
> ```

No need for double parens around the arg list -- a single paren will do.


<!-- Sent from Reviewable.io -->

2020-11-11 16:16 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: all files reviewed, 27 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1684 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjcrg64TDDBt3Puifs:-MLq0ZFbBgStPmYnDNY9:b-trj7m7) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/ext/filters/client_channel/client_channel.cc#L1684)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is admittedly a gray area, but I personally don't think that `const` is very valuable in situations like this.  There aren't likely to be bugs caused by accidentally transferring ownership, so it doesn't really protect from much.  And it does add a little cognitive overhead when thinking about the code, because you need to distinguish between the `unique_ptr<>` being `const` or the object it points to being `const`.
</blockquote></details>

SGTM. const (and unique_ptr) have been removed.
___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 95 at r4](https://reviewable.io/reviews/grpc/grpc/24701#-MLo8Ilx9a1jcxYKoGHM:-MLq105-5ffrkbpF7LDp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12547afdc91c1e298ff9c2a3ef470b8f6ca0c8ac/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L95)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As I mention elsewhere, this is a case where we don't really need to parse a URI string.  If we exposed the URI ctor, then we could instead simply construct the URI from its component parts:

```
URI ith_uri(uri->scheme(), "", ith_path,  {}, "");
```
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/parse_address.cc, line 31 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjcPB_9PTm_LCj2GnJ:-MLnu1yV255ARykJ7Dfy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/lib/iomgr/parse_address.cc#L31)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This block should be moved up next to the other C headers.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/parse_address.cc, line 35 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjcU5FBdx4hGHzi_QI:-MLnu1Tw4b5Wpz24XOxf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/lib/iomgr/parse_address.cc#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These can be moved up to be under the absl headers.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/parse_address.cc, line 42 at r2](https://reviewable.io/reviews/grpc/grpc/24701#-MLjcXwc7BwJsROkZjUr:-MLnu1HAD8oU_P7869QD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2d4bc1a9f2855055a2e326079167f97ec62ba265/src/core/lib/iomgr/parse_address.cc#L42)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This block can be moved up next to the other C headers.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.h, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhWq-IAQ7rENO80q1_:-MLnw7Lz8EbZR31RKVI8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Code inside of C-core should be in the `grpc_core` namespace.  The `grpc` namespace is used only for the C++ layer (i.e., the code under include/grpcpp and src/cpp).
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.h, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhWz1b9A6KbV9U-R5W:-MLnw8864zcY6WWK20Pj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest just calling this `URI`.  The `Grpc` prefix isn't useful, since that's already conveyed by the namespace that this is in.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.h, line 35 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhXuEV0RL2Q0vd3xi5:-MLps4IS65luqJ9vVfxR:bcfl1tj) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This API basically forces the caller to dynamically allocate the object instead of storing it by value.  We should allow callers to decide how they want to do this rather than baking it into the API.

I suggest making this object copyable and movable and having this function return it by value.
</blockquote></details>

Done. It now returns a StatusOr<URI>.
___
*[src/core/lib/uri/uri_parser.h, line 36 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhX5hLAybUOKM6uU5b:-MLpsZ8e18S35ipQkkk7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of mimicking the original interface's error handling, which would optionally log errors but would not return the error to the caller, I suggest just having this method return an `absl::StatusOr<>`.  In general, I find it to be an anti-pattern for utility functions like this to log errors, because it's generally up to the caller as to how to handle the error.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.h, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhYN5W0lD-6J2EOGUK:-MLps_tQ353cPF6FSthY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

To be clear, I'm not suggesting that we eliminate the factory method for parsing; I'm just suggesting that we also expose the ctor.

I think there are two use-cases here:
1. Parsing a URI string.  This can fail, and callers can use the factory method for it.
2. Constructing a URI object from component parts.  This cannot fail, and callers can use the ctor for it.

An example of the second case is the sockaddr resolver code, where we're putting together a scheme and a path.  There really is no reason we need to do any parsing there; we should really be able to just instantiate the object with the relevant fields.

Also, consider the fact that in the future, it may be useful to add a method to do the opposite of parsing by converting the components into a URI string.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.cc, line 235 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhbQTh3uRSyUgwxPHa:-MLpwhBMAFSooi9jxQye:b24ttkq) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.cc#L235)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think there's a pre-existing bug here: by percent-decoding the entire query string before we split on `&` or `=`, it becomes impossible to percent-encode the `&` or `=` characters themselves within an individual query param.  Instead, I think we should first split on `&` and `=`, and then percent-decode the individual query params.

We don't need to fix this as part of this PR, but please add a TODO about it.
</blockquote></details>

I added in and commented out a failing test for the bug, with a TODO.
___
*[src/core/lib/uri/uri_parser.cc, line 238 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhcw7nEkFTW-UD2jjT:-MLpyJVF17eha2zjifoE:b-owti9o) [...]

2020-11-11 17:26 UTC, markdroth reviewed
Getting closer and closer with each iteration!

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 16 files at r4, 43 of 43 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701#-:-MLsKzN68ClN36BVDd87:b60y354)* status: all files reviewed, 26 unresolved discussions (waiting on @drfloob)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1684 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsEQT18yaW1BJuQrzD:-MLsEQT18yaW1BJuQrzE:b-i07wno) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/client_channel.cc#L1684)):*
> ```cpp
>     return;
>   }
>   absl::StatusOr<grpc_core::URI> uri = grpc_core::URI::Parse(server_uri, true);
> ```

We're already in the `grpc_core` namespace here, so the `grpc_core::` is not needed.

Same thing throughout this PR -- a lot of these call sites are already in the `grpc_core` namespace.  (We've generally been moving code into that namespace as we convert it to C++.)
___
*[src/core/ext/filters/client_channel/resolver_registry.cc, line 80 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsErPi0w9mUfpQ0z1I:-MLsErPi0w9mUfpQ0z1J:bl10xpa) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/resolver_registry.cc#L80)):*
> ```cpp
>       return factory;
>     }
> ```

Please remove blank lines within functions.  (This is not strictly required by the style guide -- in fact, they've actually *weakened* their recommendation on this point over time -- but it drives me personally nuts to waste vertical space this way.)

Same thing throughout.
___
*[src/core/ext/filters/client_channel/resolver_registry.cc, line 82 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsFFXO445BfF3hHKdW:-MLsFFXO445BfF3hHKdX:b-8a0q2c) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/resolver_registry.cc#L82)):*
> ```cpp
> 
>     *canonical_target = absl::StrCat(default_prefix_.get(), target);
>     absl::StatusOr<grpc_core::URI> tmp_uri2 =
> ```

I think you can reuse the existing `tmp_uri` instead of declaring another variable of the same type.
___
*[src/core/ext/filters/client_channel/resolver_registry.cc, line 92 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsG9e1BROT4axBvPZC:-MLsG9e1BROT4axBvPZD:b-hkte8i) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/resolver_registry.cc#L92)):*
> ```cpp
> 
>     gpr_log(GPR_ERROR,
>             "Don't know how to resolve '%s' or '%s'. Errors:\n  %s\n  %s",
> ```

Note that it's possible that both of the statuses are OK here if the problem was that the URIs parsed correctly but we do not have a registered factory for the specified scheme.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 934 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsGV6y6A77L0-_dT2z:-MLsGV6y6A77L0-_dT3-:b-qz3hc0) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/subchannel.cc#L934)):*
> ```cpp
>       grpc_core::URI::Parse(uri_str, /*suppress_errors=*/false);
>   GPR_ASSERT(uri.ok());
>   if (!grpc_parse_uri(&(*uri), addr)) memset(addr, 0, sizeof(*addr));
> ```

No need for the parens around `*uri`.

Same thing throughout.  Although this issue will be moot if you change `grpc_parse_uri()` to take the URI as a reference instead of a pointer.
___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 92 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsGuib8YDehYbLXr1x:-MLsGuicBodkf97sBcex:bvzk4oy) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L92)):*
> ```cpp
>   }
>   // Construct addresses.
>   std::vector<std::string> path_parts = absl::StrSplit(uri->path(), ',');
> ```

Why change this from `absl::string_view` back to `std::string`?  If this was because you need to pass a `std::string` to the `URI` ctor, then I don't think that's necessary.  It's fine to pass an `absl::string_view` to a function expecting a `std::string`, because it will be converted automatically at that point.

Note that the way you have this now, you're making an extra copy of the string when you instantiate the `URI` object, because you're passing in a `const` string that can't be moved.  If you want to stick with `std::string` here, then I would suggest changing the loop variable to be non-const and then using `std::move()` when passing the string to the `URI` ctor.
___
*[src/core/lib/iomgr/parse_address.cc, line 36 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsEFgQ9N-jlNaEwsYE:-MLsEFgQ9N-jlNaEwsYF:bk3k351) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/lib/iomgr/parse_address.cc#L36)):*
> ```cpp
> #include <grpc/support/log.h>
> #include <grpc/support/string_util.h>
> #include "absl/strings/str_cat.h"
> ```

The absl includes should move up to be after the C headers and before the gRPC headers.
___
*[src/core/lib/security/credentials/oauth2/oauth2_credentials.h, line 169 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsIvxx7tYfFjCFOCD7:-MLsIvxx7tYfFjCFOCD8:bhrspg8) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/lib/security/credentials/oauth2/oauth2_credentials.h#L169)):*
> ```objc
> grpc_error* ValidateStsCredentialsOptions(
>     const grpc_sts_credentials_options* options,
>     absl::StatusOr<grpc_core::URI>* sts_url);
> ```

Seems a little odd to have this function return some errors via this `StatusOr<>` and others via the returned `grpc_error*`.  It would probably make sense to just change this function to use `Status` instead of `grpc_error*`.  Then the function signature would look like this:

```
absl::StatusOr<URI> ValidateStsCredentialsOptions(
    const grpc_sts_credentials_options* options);
```
___
*[src/core/lib/uri/uri_parser.h, line 36 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhX5hLAybUOKM6uU5b:-MLsBqOh8OmzsCjCK_Mi:b-bp5ade) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L36)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Since this code should no longer be logging errors, there should be no more need for the `suppress_errors` parameter.
___
*[src/core/lib/uri/uri_parser.h, line 36 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsBOgUDhsFS8W1YL5_:-MLsBOgVERzSMr2eqUqm:bgzu7nx) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/lib/uri/uri_parser.h#L36)):*
> ```objc
> class URI {
>  public:
>   URI() = default;
> ```

I think we need copy and move ctors and assignment operators here.  If you add those, then we may not need this default ctor.
___
*[src/core/lib/uri/uri_parser.h, line 44 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsBdO20vdKZsaKjWj8:-MLsBdO20vdKZsaKjWj9:b-wrcg9z) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/lib/uri/uri_parser.h#L44)):*
> ```objc
>   // Creates an instance of GrpcURI by parsing an rfc3986 URI string. Returns
>   // an IllegalArgumentError on failure.
>   static absl::StatusOr<URI> Parse(absl::string_view uri_text,
> ```

As per style guide, factory functions should go above ctors.

https://google.github.io/styleguide/cppguide.html#Declaration_Order
___
*[src/core/lib/uri/uri_parser.cc, line 235 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhbQTh3uRSyUgwxPHa:-MLsCoijBWuNgye8G4GP:b8po58r) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.cc#L235)):*
<detail [...]

2020-11-11 17:28 UTC, markdroth reviewed
> Reviewed 26 of 26 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: all files reviewed, 25 unresolved discussions (waiting on @drfloob)

___
*[src/core/lib/uri/uri_parser.cc, line 185 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsDczf4j8C6Ds3xyR0:-MLsLIwPE7AJKTgY0uT0:b-ehs2j7) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/lib/uri/uri_parser.cc#L185)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The error message generated by `LogBadUri()` should be included in the `Status` that we return instead of being logged.

Same thing throughout.
</blockquote></details>

Looks like you've done this now.


<!-- Sent from Reviewable.io -->

2020-11-13 17:13 UTC, drfloob commented
I encountered an edge-case behavior in the previous implementation that I'm going to suggest we break. I think it's intentional since there's a test for this behavior explicitly. URIs are permissively %-decoded _unless_ the `%[nn]` triplet is at the end of the URI string. This includes reporting errors where the end of string is `%` or `%n`. I'd like to remove the end-of-string exception, and permissively %-decode the string everywhere.

To illustrate: `https://goo.gl/?x%zzy` is decoded and passed through as `https://goo.gl/?x%zzy`, since `%zz` is not a valid percent encoding. However, `https://goo.gl/?x%zz` is considered an invalid URI since `%zz` is at the end of the string.

I found various takes on relaxed/permissive URI parsing, I'm not sure there's a right answer here, but I'm all ears if there is one. For reference, Chrome permissively decodes at the end of the string as well.

```
> midstr_url = new URL('h://g/?x%zz=y')
URL {origin: "null", protocol: "h:", username: "", password: "", host: "", …}

> for ([k,v] of midstr_url.searchParams)
>     console.log(k,v)
 x%zz y

> eos_url = new URL('h://g/?x%zz')
URL {origin: "null", protocol: "h:", username: "", password: "", host: "", …}
> for ([k,v] of eos_url.searchParams)
>     console.log(k,v)
 x%zz 

> eos_url2 = new URL('h://g/?x%z')
URL {origin: "null", protocol: "h:", username: "", password: "", host: "", …}
> for ([k,v] of eos_url2.searchParams)
>     console.log(k,v)
x%z 
```

2020-11-13 17:57 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: all files reviewed, 25 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1684 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsEQT18yaW1BJuQrzD:-MLsv_0L-qCNg9XPkUJZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/client_channel.cc#L1684)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We're already in the `grpc_core` namespace here, so the `grpc_core::` is not needed.

Same thing throughout this PR -- a lot of these call sites are already in the `grpc_core` namespace.  (We've generally been moving code into that namespace as we convert it to C++.)
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver_registry.cc, line 80 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsErPi0w9mUfpQ0z1I:-MLswbqx6T7Mb6zJu2x_:bl3xryh) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/resolver_registry.cc#L80)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank lines within functions.  (This is not strictly required by the style guide -- in fact, they've actually *weakened* their recommendation on this point over time -- but it drives me personally nuts to waste vertical space this way.)

Same thing throughout.
</blockquote></details>

Done. I removed all of the newly-introduced blank lines. There are quite a few all over, which might be worth a separate cleanup effort afterwards.
___
*[src/core/ext/filters/client_channel/resolver_registry.cc, line 82 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsFFXO445BfF3hHKdW:-MLswyu9AINOJiZzrR-x:b-pxs7mp) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/resolver_registry.cc#L82)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you can reuse the existing `tmp_uri` instead of declaring another variable of the same type.
</blockquote></details>

This keeps two separate variables so that both (potential) parsing error messages are available at the end. We don't want to log the first status error if the second URI parsing succeeds.
___
*[src/core/ext/filters/client_channel/resolver_registry.cc, line 92 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsG9e1BROT4axBvPZC:-MLsxaY32cAmGCH5Eenh:boturi1) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/resolver_registry.cc#L92)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Note that it's possible that both of the statuses are OK here if the problem was that the URIs parsed correctly but we do not have a registered factory for the specified scheme.
</blockquote></details>

Right. I didn't want to overthink this one, but it is awkward. I had the phrase "potential parsing errors" in there at one point. The case you're describing would look something like:

```
Don't know how to resolve 'arst://' or 'qwfp://': Errors:
  OK
  OK
```

I'll separate the logging of parsing errors and factory-not-found errors.

We could also make this method return a StatusOr<ResolverFactory> and let clients handle logging, but I had chosen to leave this method as is for now.
___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 92 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsGuib8YDehYbLXr1x:-MLt17qfEzAFPMrjCYGT:b-xp854y) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L92)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why change this from `absl::string_view` back to `std::string`?  If this was because you need to pass a `std::string` to the `URI` ctor, then I don't think that's necessary.  It's fine to pass an `absl::string_view` to a function expecting a `std::string`, because it will be converted automatically at that point.

Note that the way you have this now, you're making an extra copy of the string when you instantiate the `URI` object, because you're passing in a `const` string that can't be moved.  If you want to stick with `std::string` here, then I would suggest changing the loop variable to be non-const and then using `std::move()` when passing the string to the `URI` ctor.
</blockquote></details>

You guessed right, and I reverted it back to using string_view. As the code sits now, with std::string(ith_path) as an r-value, and std::move in the URI constructor, I don't think there aren't any unnecessary copies being made.

N.B., Implicit conversion is not supported from absl::string_view to std::string (See compiler error below when I pass ith_path as an absl::string_view). See also the [absl source](https://github.com/abseil/abseil-cpp/blob/c03c18e7fef8d06eb6c445f5607af533e69cadfe/absl/strings/string_view.h#L364)

```
./src/core/lib/uri/uri_parser.h:40:3: note: candidate constructor not viable: no known conversion from 'const absl::string_view' to 'std::string' (aka 'basic_string<char>') for 3rd argument
  URI(std::string scheme, std::string authority, std::string path,
```
___
*[src/core/lib/iomgr/parse_address.cc, line 36 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsEFgQ9N-jlNaEwsYE:-MLslmEoA39uwyd_LFCz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/lib/iomgr/parse_address.cc#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The absl includes should move up to be after the C headers and before the gRPC headers.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/url_external_account_credentials.cc, line 108 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhrmHi66UsmWo-d8LE:-MLsvAuQAgxr2a8DOCkC:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/security/credentials/external/url_external_account_credentials.cc#L108)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We can just remove this dtor, since it's no longer needed.
</blockquote></details>

Done
___
*[src/core/lib/security/credentials/oauth2/oauth2_credentials.h, line 169 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsIvxx7tYfFjCFOCD7:-MLt5VNnBCHElHbCi0z8:bohqzsr) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/lib/security/credentials/oauth2/oauth2_credentials.h#L169)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Seems a little odd to have this function return some errors via this `StatusOr<>` and others via the returned `grpc_error*`.  It would probably make sense to just change this function to use `Status` instead of `grpc_error*`.  Then the function signature would look like this:

```
absl::StatusOr<URI> ValidateStsCredentialsOptions(
    const grpc_sts_credentials_options* options);
```
</blockquote></details>

Agreed, done.
___
*[src/core/lib/uri/uri_parser.h, line 36 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhX5hLAybUOKM6uU5b:-MLslCJi4bAp5-fCYlXo:b-d18wd5) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/uri/uri_parser.h#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since this code should no longer be logging errors, there should be no more need for the `suppress_errors` parameter.
</blockquote></details>

Done, I had that commit queued up :- [...]

2020-11-14 01:48 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: 17 of 59 files reviewed, 25 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhnxqG2HWYzBkjALUw:-MM31lKk6PyBvttl7cIC:bxxpuvj) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver_factory.h#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like the resolver registry code will never pass in a null value here.  If so, then this could be a reference instead of a pointer.
</blockquote></details>

I'm on the fence with this one. ResolverRegistry::CreateResolver ensures that the ptr is valid today, but if later on, someone unknowingly changes the unenforced contract that ResolverArgs.uri != nullptr in the resolver registry, we would be dealing with a crash instead of an invalid uri, and the crash will be a bit non-local to the problem. Thoughts?
___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhmaaDBg-aNaWWOA1X:-MM3MoITA5A3BarwUA1t:bi4649q) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver_factory.h#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In principle, we should change the return type here from `UniquePtr<char>` to `std::string`.  But this is another thing that you can defer if it becomes too viral.
</blockquote></details>

Done. For GetDefaultAuthority, the new boundary between c-strs and std::string lies with calls to `grpc_channel_arg_string_create`. We're pushing the boundary back, but I'm not sure yet where we can draw the line for this PR.
___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLho2pq0aVWSoh24ZaE:-MM3NjmcA343b0HAzkL4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver_factory.h#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same comment as above about this being a reference instead of a pointer.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 934 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsGV6y6A77L0-_dT2z:-MM3NprtBSddng5mXNTJ:b-7fcw34) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/subchannel.cc#L934)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the parens around `*uri`.

Same thing throughout.  Although this issue will be moot if you change `grpc_parse_uri()` to take the URI as a reference instead of a pointer.
</blockquote></details>

I changed all `&(*uri)` to `&*uri` for now.
___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1336 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhoeW29dhC5G-0AZya:-MM1uR8t69v3774V0GLC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1336)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `absl::StripPrefix()` here.  (I'll stop noting these, but please fix throughout the PR.)

Also, I suggest changing `server_name_` to be a `std::string`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-16 19:48 UTC, markdroth reviewed
This is getting closer!

Please let me know if you have any questions.  Thanks!

> Reviewed 17 of 41 files at r7, 30 of 30 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701#-:-MMHaSn_9ySS-gCXmFvL:b79zqk9)* status: all files reviewed, 24 unresolved discussions (waiting on @drfloob)

___
*[BUILD, line 1009 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMH8fp46dfBGMPtp6CO:-MMH8fp46dfBGMPtp6CP:bwgudtl) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/BUILD#L1009)):*
> ```Starlark
>         "absl/types:optional",
>         "absl/container:flat_hash_map",
>         "re2",
> ```

I think we don't actually want to take a new dependency on re2 from the base gRPC library.  It would increase our binary size quite a bit, and we have a number of customers (e.g., on mobile) that are very sensitive to this.

It looks like there's a fairly simple alternative in both of the cases where we're actually using re2 here.  See my comments in those locations.
___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhnxqG2HWYzBkjALUw:-MMHMqZy3uhEQiFvA6L0:b5biwjs) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver_factory.h#L51)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

I'm on the fence with this one. ResolverRegistry::CreateResolver ensures that the ptr is valid today, but if later on, someone unknowingly changes the unenforced contract that ResolverArgs.uri != nullptr in the resolver registry, we would be dealing with a crash instead of an invalid uri, and the crash will be a bit non-local to the problem. Thoughts?
</blockquote></details>

Structurally, the resolver registry gets a URI as a string and parses it.  It then passes it to this function to see if the URI is valid for the scheme.  If the basic parsing fails (i.e., it does not have a valid URI object), then it doesn't need to call this method in the first place.  So I think it's fine to require this to be non-null.  It doesn't make sense to require every implementation to check if it's null.
___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhmaaDBg-aNaWWOA1X:-MMHQR0I401I_VF3BSIB:b-x4plpi) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver_factory.h#L58)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Done. For GetDefaultAuthority, the new boundary between c-strs and std::string lies with calls to `grpc_channel_arg_string_create`. We're pushing the boundary back, but I'm not sure yet where we can draw the line for this PR.
</blockquote></details>

I think that's the right place.

Currently, `grpc_channel_args` is an exposed part of the C-core API, and it has its fingers everywhere in our code.  I'd *really* like to replace it with a much cleaner C++ API (at least for internal use), but that's a much larger effort, not something we want to tackle as part of this PR.
___
*[src/core/ext/filters/client_channel/resolver_registry.cc, line 80 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsErPi0w9mUfpQ0z1I:-MMHW4mb3Y6e92l4V348:bcapt93) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/ext/filters/client_channel/resolver_registry.cc#L80)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Done. I removed all of the newly-introduced blank lines. There are quite a few all over, which might be worth a separate cleanup effort afterwards.
</blockquote></details>

Thanks.

I think it's fine to just be consistent with the existing style within each file.  But if we're taking the time to rewrite something anyway, we can remove them.
___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1336 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhoeW29dhC5G-0AZya:-MMHXx8g5JX5X0OsCwpU:b-9ecuj2) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1336)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like `server_name_` is still a `const char*`.
___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 93 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHYHGR5ssK1PMoU204:-MMHYHGR5ssK1PMoU205:bx9af4p) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L93)):*
> ```cpp
>   // Construct addresses.
>   bool errors_found = false;
>   for (const absl::string_view& ith_path : absl::StrSplit(uri->path(), ',')) {
> ```

This doesn't need to be a const reference.  An `absl::string_view` is small enough storage-wise that you can treat it like a POD type.
___
*[src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc, line 81 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHYdmR6eVGH5nbiZtw:-MMHYdmR6eVGH5nbiZtx:bh1w4w3) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc#L81)):*
> ```cpp
>     // Otherwise, get it from the server name used to construct the
>     // channel.
> ```

Please remove blank line.
___
*[src/core/lib/transport/authority_override.h, line 30 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHZQCi-aBkcIVq41En:-MMHZQCi-aBkcIVq41Eo:bl056xh) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/transport/authority_override.h#L30)):*
> ```objc
> 
> /// Returns the authority override from \a args or nullptr.
> const std::string FindAuthorityOverrideInArgs(const grpc_channel_args* args);
> ```

This can probably return an `absl::string_view`.  The caller can make a copy if it needs to save the value.
___
*[src/core/lib/uri/uri_parser.cc, line 56 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHBghw443I9RyzGqnn:-MMHBghx9k1Pajc0glv7:bus0ifw) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/uri/uri_parser.cc#L56)):*
> ```cpp
>         !absl::CUnescape(absl::StrCat("\\x", str.substr(i + 1, 2)),
>                          &unescaped)) {
>       out += str[i];
> ```

Don't we want to return an error in this case, since it's an invalid hex code?
___
*[src/core/lib/uri/uri_parser.cc, line 68 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHBqSe6bmIUHcyb9B3:-MMHBqSe6bmIUHcyb9B4:b-7hrmaw) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/uri/uri_parser.cc#L68)):*
> ```cpp
> // See https://tools.ietf.org/html/rfc3986#section-3.4
> absl::Status IsPCharString(absl::string_view fragment) {
>   if (!RE2::FullMatch(std::string(fragment),
> ```

A regexp is actually a fairly inefficient way of doing this.  Instead, I suggest using `std::string::find_first_not_of()`.

https://en.cppreference.com/w/cpp/string/basic_string/find_first_not_of
___
*[src/core/lib/uri/uri_parser.cc, line 86 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHHctL1xlMVhlYQCMP:-MMHHctL1xlMVhlYQCMQ:b-h9qkrn) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/uri/uri_parser.cc#L86)):*
> ```cpp
> 
> absl::StatusOr<URI> URI::Parse(absl::string_view uri_text) {
>   std::string scheme;
> ```

Please declare each variable right where it's first used, rather than declaring them all up-front.
___
*[src/core/lib/uri/uri_parser.cc, line 95 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHIZegD2L6z0p7ZvkM:-MMHIZegD2L6z0p7ZvkN:b-kg [...]

2020-11-17 01:12 UTC, drfloob reviewed
Thank you for the extensive reviews! I just wanted to respond, the "Done" comments are not pushed upstream yet so as to not waste review time.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701#-:-MMIji5j8L6mYI6H13eJ:b-kjm8dc)* status: 48 of 67 files reviewed, 24 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[BUILD, line 1009 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMH8fp46dfBGMPtp6CO:-MMHhWGX5kioROL8GaX7:bn9knfy) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/BUILD#L1009)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we don't actually want to take a new dependency on re2 from the base gRPC library.  It would increase our binary size quite a bit, and we have a number of customers (e.g., on mobile) that are very sensitive to this.

It looks like there's a fairly simple alternative in both of the cases where we're actually using re2 here.  See my comments in those locations.
</blockquote></details>

That makes sense, I hadn't looked for the binary size comparison yet. Thanks
___
*[src/core/ext/filters/client_channel/http_proxy.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhjsM94qB8tk7bhrAe:-MMI0yNN2a87MkpTem_A:b-5lfrrx) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/http_proxy.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We could also change this to return `std::string` instead of `char*`.  But if that winds up becoming a viral change that spreads out into a lot of other code, it's also fine to leave this as-is for now.
</blockquote></details>

I've left a TODO for this change.
___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhnxqG2HWYzBkjALUw:-MMI3FMg1maQRfVdztI3:b-z2hgzg) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver_factory.h#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Structurally, the resolver registry gets a URI as a string and parses it.  It then passes it to this function to see if the URI is valid for the scheme.  If the basic parsing fails (i.e., it does not have a valid URI object), then it doesn't need to call this method in the first place.  So I think it's fine to require this to be non-null.  It doesn't make sense to require every implementation to check if it's null.
</blockquote></details>

Alright. I've made the changes, and added a note in the ResolverArgs struct that this uri pointer is assumed to be valid.
___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 93 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHYHGR5ssK1PMoU204:-MMHiJCX0VAwrbhKwskX:b-joxgq3) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L93)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't need to be a const reference.  An `absl::string_view` is small enough storage-wise that you can treat it like a POD type.
</blockquote></details>

Ah, good catch, and consistent with https://abseil.io/tips/1. This was locally a const std::string& beforehand, I missed that bit of cleanup.
___
*[src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc, line 81 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHYdmR6eVGH5nbiZtw:-MMHjxb22d1Rl-iewYKB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank line.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/parse_address.h, line 31 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhq0HjDJH5ZHIep9fA:-MMIgNJh9l3i0rD2LA18:b-u0e3tf) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/lib/iomgr/parse_address.h#L31)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All of these functions should take this parameter as a reference instead of a pointer.  The caller should never call these functions if the value is null.
</blockquote></details>

Done. Working backwards, callers of grpc_parse_uri and Sockaddr Resolver's ParseURI will need to ensure they have a valid URI.
___
*[src/core/lib/transport/authority_override.h, line 30 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHZQCi-aBkcIVq41En:-MMHmRWE51-o32SuTVFD:b411lh4) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/transport/authority_override.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can probably return an `absl::string_view`.  The caller can make a copy if it needs to save the value.
</blockquote></details>

Done. The one call site for this method creates a copy of the returned string_view now. This is because we're drawing boundaries around the viral spread of std::string, and authority here is exclusively after being converted to c_str().

On a related note, is there any reason that `authority_override` is maintained separately, with GRPC_ARG_AUTHORITY_OVERRIDE not defined in grpc_types? Do we not want to expose that arg type publicly? It seems a bit odd that we have a grpc_channel_args accessor function for this special case, whereas you often see grpc_channel_args_find_string used directly (including just below the one call site for FindAuthorityOverrideInArgs).
___
*[src/core/lib/uri/uri_parser.cc, line 56 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHBghw443I9RyzGqnn:-MMHqs17DYSFumAJhy74:b-zdobqm) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/uri/uri_parser.cc#L56)):*
Not if we want to maintain backwards compatibility. The original parser was designed to permit permissive/relaxed parsing of invalid hex. This parser is not alone in doing so. See documentation in percent_encoding.h, and the associated uri_parser_tests.cc.

For comparison, Chrome has similar behavior:

```
> x = new URL("scheme://path?a=%x&b=%2&c=%24")
URL {origin: "null", protocol: "scheme:", username: "", password: "", host: "", …}
> x.searchParams.get("a")
"%x"
> x.searchParams.get("b")
"%2"
> x.searchParams.get("c")
"$"
```
___
*[src/core/lib/uri/uri_parser.cc, line 68 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHBqSe6bmIUHcyb9B3:-MMHv7alCEhCmVsLXpSV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/uri/uri_parser.cc#L68)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

A regexp is actually a fairly inefficient way of doing this.  Instead, I suggest using `std::string::find_first_not_of()`.

https://en.cppreference.com/w/cpp/string/basic_string/find_first_not_of
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.cc, line 86 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHHctL1xlMVhlYQCMP:-MMHvrUm7IlmehxzejPi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/uri/uri_parser.cc#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please declare each variable right where it's first used, rather than declaring them all up-front.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.cc, line 95 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHIZegD2L6z0p7ZvkM:-MMHczGi0_ZAnzFXEcbK:b-x7z5gm) ([raw file](https [...]

2020-11-18 00:08 UTC, markdroth reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: 48 of 67 files reviewed, 23 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/lib/transport/authority_override.h, line 30 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHZQCi-aBkcIVq41En:-MMNdRwbCwSICFmc2Ycw:b-tc1xd5) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/transport/authority_override.h#L30)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Done. The one call site for this method creates a copy of the returned string_view now. This is because we're drawing boundaries around the viral spread of std::string, and authority here is exclusively after being converted to c_str().

On a related note, is there any reason that `authority_override` is maintained separately, with GRPC_ARG_AUTHORITY_OVERRIDE not defined in grpc_types? Do we not want to expose that arg type publicly? It seems a bit odd that we have a grpc_channel_args accessor function for this special case, whereas you often see grpc_channel_args_find_string used directly (including just below the one call site for FindAuthorityOverrideInArgs).
</blockquote></details>

No, we don't want to expose this arg publicly -- it's purely for internal use.  There are actually a number of cases where we do that, since channel args are an extremely convenient way to pass data down through the stack, and we often (but not always) use the pattern of providing a custom finder method to avoid having to add a public definition of the arg name macro (even just within core).

This is something that I would like to some day clean up as part of a new channel args design, but it's never bubbled up to the top of the priority list.
___
*[src/core/lib/uri/uri_parser.cc, line 56 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHBghw443I9RyzGqnn:-MMNevKZCqGjFyipfLdf:b-x9ntpi) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/uri/uri_parser.cc#L56)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Not if we want to maintain backwards compatibility. The original parser was designed to permit permissive/relaxed parsing of invalid hex. This parser is not alone in doing so. See documentation in percent_encoding.h, and the associated uri_parser_tests.cc.

For comparison, Chrome has similar behavior:

```
> x = new URL("scheme://path?a=%x&b=%2&c=%24")
URL {origin: "null", protocol: "scheme:", username: "", password: "", host: "", …}
> x.searchParams.get("a")
"%x"
> x.searchParams.get("b")
"%2"
> x.searchParams.get("c")
"$"
```
</blockquote></details>

Okay.  In that case, this function does not need to return a `StatusOr<>`, since it will never return a non-OK status.
___
*[test/core/uri/uri_parser_test.cc, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhtnfk2yzU6GjiCD5g:-MMNfU3xBTtgFIcEjCaz:bm5s1ax) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/test/core/uri/uri_parser_test.cc#L75)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Absolutely, debugging failed tests would be much friendlier. I've left a TODO for this, and may leave it for another PR if that's ok.
</blockquote></details>

Yeah, that's okay.


<!-- Sent from Reviewable.io -->

2020-11-18 05:11 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: 48 of 67 files reviewed, 23 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1336 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhoeW29dhC5G-0AZya:-MMNy_ifAYQJLyFD0lPb:bt5fcym) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1336)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like `server_name_` is still a `const char*`.
</blockquote></details>

Uf, right. Now done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 144 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhp9Ym5Y4h6m_ghwYg:-MMOigq08UXVqmZz44R5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest changing `name_to_resolve_` to be `std::string`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 148 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhp5M54Vsg_9J-J86L:-MMOiGKpAUnyo8uV5BoB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L148)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest changing `dns_server_` to be `std::string`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 111 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhpJpuA6Mlo0Lk-T-K:-MMOjVMACIkmRDQ8jCyt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L111)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest changing `name_to_resolve_` to be `std::string`.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.cc, line 56 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMHBghw443I9RyzGqnn:-MMNsqpZ5Lra2I0uyaJI:b-4oxum1) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/uri/uri_parser.cc#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  In that case, this function does not need to return a `StatusOr<>`, since it will never return a non-OK status.
</blockquote></details>

Done. That cleans things up nicely, thanks.


<!-- Sent from Reviewable.io -->

2020-11-18 17:06 UTC, drfloob commented on src/core/lib/security/credentials/external/aws_request_signer.cc
> +  absl::StatusOr<URI> tmp_url = URI::Parse(url);
@renkelvin Please take a look at the changes in this file and let me know if you have any questions.

2020-11-18 17:12 UTC, markdroth reviewed
This is getting closer and closer!  Remaining comments are mostly cosmetic at this point.

Note that this PR will require internal changes, so we'll need to do it as a cherry-pick import.  I can show you how that procedure works, but the main thing to keep in mind for now is that we should not actually merge this PR until we have the corresponding import CL ready to be submitted.  When we're ready, we can coordinate with the current importer and then merge/submit the two changes at the same time.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 41 files at r7, 1 of 19 files at r9, 49 of 52 files at r10.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701#-:-MMRKGgJC5p5nYNpMsvJ:b-a8zbdy)* status: all files reviewed, 25 unresolved discussions (waiting on @drfloob)

___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 38 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRBuv7BJGiPcVqAlQY:-MMRBuv7BJGiPcVqAlQZ:btf993v) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/ext/filters/client_channel/resolver_factory.h#L38)):*
> ```objc
> struct ResolverArgs {
>   /// The parsed URI to resolve. Important notes:
>   /// * ResolverArgs DOES NOT own this pointer.
> ```

A cleaner option here would be to make this not be a pointer.  The only place it's populated is in `ResolverRegistry::CreateResolver()`, and that code could just `std::move()` the URI into this struct.
___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1340 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRCLxp3B61n7FAuL1I:-MMRCLxp3B61n7FAuL1J:b-mqndjs) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1340)):*
> ```cpp
>   absl::StatusOr<URI> uri = URI::Parse(server_uri);
>   GPR_ASSERT(uri.ok() && !uri->path().empty());
>   // TODO: look into making server_name_ a std::string
> ```

This TODO can be removed now.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 144 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhp9Ym5Y4h6m_ghwYg:-MMRCQaW-V3olReE3FJM:bocb2l1) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L144)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 148 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhp5M54Vsg_9J-J86L:-MMRCRfuAyFvDR2x31l4:bocb2l1) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L148)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change.
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 111 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhpJpuA6Mlo0Lk-T-K:-MMRCUTr4tjxnzWjpr73:bocb2l1) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L111)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change.
___
*[src/core/lib/security/credentials/external/aws_request_signer.cc, line 126 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRCxQ50sIacMRCC0V6:-MMRCxQ50sIacMRCC0V7:bndw2g4) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/security/credentials/external/aws_request_signer.cc#L126)):*
> ```cpp
>   // 2. CanonicalURI
>   canonical_request_vector.emplace_back(
>       url_.path().empty() ? "/" : absl::string_view(url_.path()));
> ```

I think this can just use `absl::StripPrefix()`.
___
*[src/core/lib/security/credentials/oauth2/oauth2_credentials.cc, line 578 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRDWphCPEVHIzfeto1:-MMRDWphCPEVHIzfeto2:b-5d25w7) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/security/credentials/oauth2/oauth2_credentials.cc#L578)):*
> ```cpp
>     grpc_httpcli_request request;
>     memset(&request, 0, sizeof(grpc_httpcli_request));
>     char* http_path = const_cast<char*>(sts_url_.path().c_str());
> ```

Why create a separate variable here instead of just in-lining this expression where we set `request.http.path`?
___
*[src/core/lib/transport/authority_override.cc, line 26 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMRDkdK4Tv54I9ZcAL3:-MMRDkdLEOU-fsZCAlvm:b9yr4a9) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/transport/authority_override.cc#L26)):*
> ```cpp
> namespace grpc_core {
> 
> /// Returns a channel argument containing \a authority.
> ```

Why remove the comments here?
___
*[src/core/lib/transport/authority_override.cc, line 33 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMRDmff5qelYm7t4vlP:-MMRDmff5qelYm7t4vlQ:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/transport/authority_override.cc#L33)):*
> ```cpp
> }
> 
> /// Returns the authority override from \a args or nullptr.
> ```

Same here.
___
*[src/core/lib/uri/uri_parser.h, line 34 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMR5Gi6D5bZ4yxWGYIA:-MMR5Gi6D5bZ4yxWGYIB:byle3k4) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.h#L34)):*
> ```objc
> namespace grpc_core {
> 
> struct QueryParam {
> ```

This should go inside of the public section of the `URI` class.
___
*[src/core/lib/uri/uri_parser.cc, line 66 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMR8peM3FKgZJOftgH3:-MMR8peM3FKgZJOftgH4:bq9fou8) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L66)):*
> ```cpp
> // Checks if this string is made up of pchars, '/', '?', and '%' exclusively.
> // See https://tools.ietf.org/html/rfc3986#section-3.4
> absl::Status IsPCharString(absl::string_view fragment) {
> ```

Suggest calling the argument `str`, since it may be some part other than the fragment.
___
*[src/core/lib/uri/uri_parser.cc, line 66 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRA2PT3i8YhMCIWyru:-MMRA2PT3i8YhMCIWyrv:b-r2jzzj) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L66)):*
> ```cpp
> // Checks if this string is made up of pchars, '/', '?', and '%' exclusively.
> // See https://tools.ietf.org/html/rfc3986#section-3.4
> absl::Status IsPCharString(absl::string_view fragment) {
> ```

It might make more sense to just have this return a `bool` and have the caller generate the error.
___
*[src/core/lib/uri/uri_parser.cc, line 83 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMR6RTI6kzfQE57hPya:-MMR6RTI6kzfQE57hPyb:b-8z55sm) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L83)):*
> ```cpp
>       absl::StrFormat("Could not parse '%s' from uri '%s'.", part_name, uri));
> }
> absl::Status MakeInvalidURIStatus(absl::string_view part_name,
> ```

I think in all of the cases where we're calling this, the parsing code already knows what's wrong.  So maybe just have one version of this function that takes a third parameter of a string indicating what the problem was, which we can just unconditionally add to the error message?  That way, there's no need for creating multiple `Status` objects here; we can just directly create the one that we w [...]

2020-11-18 17:27 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: 63 of 65 files reviewed, 26 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 111 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhpJpuA6Mlo0Lk-T-K:-MMRO8uoA5XzaGrnlS5A:buhsdxw) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L111)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

That's odd. I can see the change on both Github and Reviewable.io. Are your reviewable diff bounds set to show the latest commits?


<!-- Sent from Reviewable.io -->

2020-11-18 17:43 UTC, markdroth reviewed
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: all files reviewed, 24 unresolved discussions (waiting on @drfloob)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 144 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhp9Ym5Y4h6m_ghwYg:-MMRRofx6QF4hZpJ3HuD:b-yk7t8l) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

I can see this one now.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 148 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhp5M54Vsg_9J-J86L:-MMRRqQAC0hG6B9q_SWA:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L148)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

Same here.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 144 at r11](https://reviewable.io/reviews/grpc/grpc/24701#-MMRRuHU1cISdy9XNYQb:-MMRRuHU1cISdy9XNYQc:bz2q4ui) ([raw file](https://github.com/grpc/grpc/blob/5a0595d74dd2bbaeef892f5d943afe4d54b9d494/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L144)):*
> ```cpp
>   name_to_resolve_ = std::string(absl::StripPrefix(args.uri->path(), "/"));
>   // Get DNS server from URI authority.
>   dns_server_ = "";
> ```

This line isn't needed.  Empty string is the default value for a `std::string`.
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 111 at r1](https://reviewable.io/reviews/grpc/grpc/24701#-MLhpJpuA6Mlo0Lk-T-K:-MMRReUJ43lZ12_t8IIc:b43k33) ([raw file](https://github.com/grpc/grpc/blob/4731ebe97caa9d5cb24cec8bac7fae397866ad4c/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L111)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

That's odd. I can see the change on both Github and Reviewable.io. Are your reviewable diff bounds set to show the latest commits?
</blockquote></details>

Huh, very weird -- I can see it now.  Not sure what was happening earlier.


<!-- Sent from Reviewable.io -->

2020-11-18 19:37 UTC, renkelvin reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: all files reviewed, 24 unresolved discussions (waiting on @drfloob)

___
*[src/core/lib/security/credentials/external/aws_request_signer.cc, line 97 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMR59_9c1Z7lcuHtcDA-r10-97:-MMRqpvd3KIs-UbpBzAs:bfm5pjt) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/security/credentials/external/aws_request_signer.cc#L97)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

@renkelvin Please take a look at the changes in this file and let me know if you have any questions.
</blockquote></details>

Looks good to me. Thanks for helping with this!


<!-- Sent from Reviewable.io -->

2020-11-18 21:37 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: all files reviewed, 23 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 38 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRBuv7BJGiPcVqAlQY:-MMRr4Kr5B1ehC1u1CgT:b-g1hs46) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/ext/filters/client_channel/resolver_factory.h#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

A cleaner option here would be to make this not be a pointer.  The only place it's populated is in `ResolverRegistry::CreateResolver()`, and that code could just `std::move()` the URI into this struct.
</blockquote></details>

Makes sense, done.
___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1340 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRCLxp3B61n7FAuL1I:-MMRl70K0v6mvb5gSyc6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1340)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This TODO can be removed now.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 144 at r11](https://reviewable.io/reviews/grpc/grpc/24701#-MMRRuHU1cISdy9XNYQb:-MMRlJtK1ouGWdSbwCeX:byt0r0v) ([raw file](https://github.com/grpc/grpc/blob/5a0595d74dd2bbaeef892f5d943afe4d54b9d494/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This line isn't needed.  Empty string is the default value for a `std::string`.
</blockquote></details>

Ah, right. I hadn't noticed this was in the constructor, dns_server_ is already untouched.
___
*[src/core/lib/security/credentials/external/aws_request_signer.cc, line 126 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRCxQ50sIacMRCC0V6:-MMROZzdDrdXcAcuczih:b-d8jk21) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/security/credentials/external/aws_request_signer.cc#L126)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can just use `absl::StripPrefix()`.
</blockquote></details>

This isn't a strip prefix, it sets the path to "/" if the path is empty.
___
*[src/core/lib/security/credentials/oauth2/oauth2_credentials.cc, line 578 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRDWphCPEVHIzfeto1:-MMRQdXzDgM8JBJl3sey:b-udi2so) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/security/credentials/oauth2/oauth2_credentials.cc#L578)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why create a separate variable here instead of just in-lining this expression where we set `request.http.path`?
</blockquote></details>

Cleaned up now, apologies. I was trying to debug some MSAN issues last night, and this was part of that effort.
___
*[src/core/lib/transport/authority_override.cc, line 26 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMRDkdK4Tv54I9ZcAL3:-MMRR5WZ-DVP80G1eWHL:bhm8olh) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/transport/authority_override.cc#L26)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why remove the comments here?
</blockquote></details>

Because they are duplicated from authority_override.h. Convention is usually to document methods in the header.
___
*[src/core/lib/transport/authority_override.cc, line 33 at r8](https://reviewable.io/reviews/grpc/grpc/24701#-MMRDmff5qelYm7t4vlP:-MMRRlPo5jwwj2c8UIb5:b-34vmyd) ([raw file](https://github.com/grpc/grpc/blob/7baa7a71480af7521c081824f076310dc03a7f2c/src/core/lib/transport/authority_override.cc#L33)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

See above
___
*[src/core/lib/uri/uri_parser.h, line 34 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMR5Gi6D5bZ4yxWGYIA:-MMRSH5u644rkufFW_4c:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.h#L34)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should go inside of the public section of the `URI` class.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.cc, line 66 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMR8peM3FKgZJOftgH3:-MMRSRJ9BneTfsupn2fq:bpsqnat) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L66)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling the argument `str`, since it may be some part other than the fragment.
</blockquote></details>

Done. I was going for "component", per rfc3986, but "fragment" slipped in. Even then it's not necessarily a full component. str is better.
___
*[src/core/lib/uri/uri_parser.cc, line 66 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRA2PT3i8YhMCIWyru:-MMRTc8NCQVCL61J8bQ7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L66)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It might make more sense to just have this return a `bool` and have the caller generate the error.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.cc, line 83 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMR6RTI6kzfQE57hPya:-MMRTkjj70unNJDePibV:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L83)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think in all of the cases where we're calling this, the parsing code already knows what's wrong.  So maybe just have one version of this function that takes a third parameter of a string indicating what the problem was, which we can just unconditionally add to the error message?  That way, there's no need for creating multiple `Status` objects here; we can just directly create the one that we want.
</blockquote></details>

Done
___
*[src/core/lib/uri/uri_parser.cc, line 96 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMR6G7m0p86-1byI71w:-MMRVQ7HEJ1djPZn6k-r:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L96)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of saying `std::string foo = std::string(...)`, you can just say `std::string foo(...)`.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.cc, line 97 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMR7ulx8uMa2kgN96HZ:-MMR_9rR9M8iD5Hy6ioM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L97)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This string comparison is unnecessarily inefficient.  Instead, I suggest writing it like this:

```
size_t idx = remaining.find(':');
if (idx == remaining.npos || idx == 0) {
  return MakeInvalidURIStatus("scheme", uri_text, "scheme not found");
}
std::string scheme(remaining.substr(0, idx));
if (scheme.find_first_not_of("ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                             "abcdefghijklmnopqrstuvwxyz"
                             "0123456789+\\-.]") != scheme.npos) {
  return Make [...]

2020-11-18 21:43 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: 58 of 65 files reviewed, 23 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 38 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRBuv7BJGiPcVqAlQY:-MMSIoLOBc5qoV4cSoug:bfo014x) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/ext/filters/client_channel/resolver_factory.h#L38)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Makes sense, done.
</blockquote></details>

Actually I'm still working on this one.


<!-- Sent from Reviewable.io -->

2020-11-18 22:34 UTC, markdroth reviewed
> Reviewed 7 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: all files reviewed, 6 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/lib/security/credentials/external/aws_request_signer.cc, line 126 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRCxQ50sIacMRCC0V6:-MMSP4-vCoBWoCHkX4Pj:bie0v2e) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/security/credentials/external/aws_request_signer.cc#L126)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

This isn't a strip prefix, it sets the path to "/" if the path is empty.
</blockquote></details>

Ah, sorry, you're right -- I misread that.  Sorry for the confusion.
___
*[src/core/lib/uri/uri_parser.cc, line 161 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRAkr02QeIdIpZ5_Ij:-MMSNoVr5jRK4eTVArNd:bfmvl06) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L161)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

I don't think the behavior is specified when there are multiples of the same key. See https://cplusplus.github.io/LWG/issue2844. We had decided that this parser implementation would store the *last* value for a given key, and I think that still makes more sense than having the map story *any* available value, nondeterministically. What do you think?
</blockquote></details>

In practice, I'd be very surprised if any implementation doesn't actually use the last value it sees, since it would have to go out of its way to do otherwise.

Maybe it would make sense for us to say that the behavior is undefined for us as well?  That way, we can do the simple thing here.

But I'm also okay with leaving this as-is if you'd prefer.
___
*[src/core/lib/uri/uri_parser.cc, line 75 at r12](https://reviewable.io/reviews/grpc/grpc/24701#-MMSN-SG7azlvImE0UeX:-MMSN-SH9K-AWDSrvd1r:brrnkgc) ([raw file](https://github.com/grpc/grpc/blob/be7a8bd094e415ee2e1c664c1b811d8af357c6bb/src/core/lib/uri/uri_parser.cc#L75)):*
> ```cpp
> 
> absl::Status MakeInvalidURIStatus(absl::string_view part_name,
>                                   absl::string_view uri, absl::string_view extra = "") {
> ```

Why make the last param optional?  Shouldn't we specify this in all cases, since the caller does know exactly what the problem was?
___
*[src/core/lib/uri/uri_parser.cc, line 116 at r12](https://reviewable.io/reviews/grpc/grpc/24701#-MMSNTT07m8RFtOVDifl:-MMSNTT07m8RFtOVDifm:bfwaxad) ([raw file](https://github.com/grpc/grpc/blob/be7a8bd094e415ee2e1c664c1b811d8af357c6bb/src/core/lib/uri/uri_parser.cc#L116)):*
> ```cpp
>   }
>   // parse query
>   std::vector<URI::QueryParam> query_param_pairs;
> ```

I think the `URI::` prefix is not needed here, since this method is a member of that class, so we're already in that scope.
___
*[test/core/uri/uri_parser_test.cc, line 47 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRI4uq830qd5UEaNxl:-MMSPGZ11ucpbpelSptC:bdovrez) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/test/core/uri/uri_parser_test.cc#L47)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

True, I've re-added that check here. It was previously moved to compare the query pairs, but it's valuable for the map as well.

I do totally agree with you about integrating googletest, this test style is a bit painful. However I don't want to change the test framework while making large changes to the thing it's testing, the safety net should remain stable if we can help it. I do plan to migrate this once we're confident in this impl, so that we can rely the parser impl to vet the test changes.
</blockquote></details>

Sounds great!
___
*[test/core/uri/uri_parser_test.cc, line 86 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRIxRe-wltH-5q9u17:-MMSPRnY3mJ5q3wmJ9sY:b-z882zi) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/test/core/uri/uri_parser_test.cc#L86)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

There was a bug here, the values should have matched. I fixed it and made the purpose (testing specificity) more clear. Please take another look and let me know if you think this needs to be removed.

In case the cleanup doesn't answer your questions as to the purpose, there aren't any sorts happening in this parser, so that is not under examination. You're describing a true positive test: we expect a match and it holds. There are tests for that already. This is a true negative test: we expect things to not match, and that holds in the way we expect. It serves to document the specificity of ordering ... "The result *isn't* this because it *is* that."
</blockquote></details>

Oh, right, because we're using `absl::flat_hash_map<>` instead of `std::map<>`.  The latter would have sorted.  (Hmm... Do we actually need `absl::flat_hash_map<>`?  I'm not sure we're ever likely to see enough elements that the hash performance will matter, so `std::map<>` might actually be good enough -- it might even be better for very small maps.  But feel free to leave this as-is too.)

Getting back to this specific test, though, I don't think it's actually useful.  The `==` operator on vectors ensures that both sides are in the same order, so it's already implicit from the existing tests that the vector will be in the right order.  I don't think we need to explicitly test that it's not equal if it's in a different order.


<!-- Sent from Reviewable.io -->

2020-11-19 00:42 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: 52 of 65 files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver_factory.h, line 38 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRBuv7BJGiPcVqAlQY:-MMSwT_XEme2-zMTBf-S:b-9vi8ig) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/ext/filters/client_channel/resolver_factory.h#L38)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

Actually I'm still working on this one.
</blockquote></details>

This is done now, please take a look.
___
*[src/core/lib/uri/uri_parser.h, line 36 at r5](https://reviewable.io/reviews/grpc/grpc/24701#-MLsBOgUDhsFS8W1YL5_:-MMSdHK3-Dxe7-K72TIT:by0x31z) ([raw file](https://github.com/grpc/grpc/blob/49427231a488487612c19acbc53ef52b1bd64285/src/core/lib/uri/uri_parser.h#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we need copy and move ctors and assignment operators here.  If you add those, then we may not need this default ctor.
</blockquote></details>

I've added the copy/move ctors & assignment operators, but kept the default ctor to simplify the ResolverArgs definition. Please let me know if you have any recommendations there, or would like to see it done differently.
___
*[src/core/lib/uri/uri_parser.cc, line 161 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRAkr02QeIdIpZ5_Ij:-MMSvhT10QJa3zqqWHDo:b-3p971t) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L161)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In practice, I'd be very surprised if any implementation doesn't actually use the last value it sees, since it would have to go out of its way to do otherwise.

Maybe it would make sense for us to say that the behavior is undefined for us as well?  That way, we can do the simple thing here.

But I'm also okay with leaving this as-is if you'd prefer.
</blockquote></details>

I'll leave it as is now, then. This saves us adding more code in QueryParam to support map range construction.
___
*[src/core/lib/uri/uri_parser.cc, line 75 at r12](https://reviewable.io/reviews/grpc/grpc/24701#-MMSN-SG7azlvImE0UeX:-MMS_6QW98WMBfG_JAU9:b-8xww2c) ([raw file](https://github.com/grpc/grpc/blob/be7a8bd094e415ee2e1c664c1b811d8af357c6bb/src/core/lib/uri/uri_parser.cc#L75)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why make the last param optional?  Shouldn't we specify this in all cases, since the caller does know exactly what the problem was?
</blockquote></details>

Done. There is a situation where the error cause is ambiguous, but it now reports an ambiguous problem :-)
___
*[src/core/lib/uri/uri_parser.cc, line 116 at r12](https://reviewable.io/reviews/grpc/grpc/24701#-MMSNTT07m8RFtOVDifl:-MMSY94fAZEDp34fJmS9:bk3axkr) ([raw file](https://github.com/grpc/grpc/blob/be7a8bd094e415ee2e1c664c1b811d8af357c6bb/src/core/lib/uri/uri_parser.cc#L116)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the `URI::` prefix is not needed here, since this method is a member of that class, so we're already in that scope.
</blockquote></details>

fixed. greedy sed.
___
*[test/core/uri/uri_parser_test.cc, line 86 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRIxRe-wltH-5q9u17:-MMSYa34BF4CdJTJn7j0:bh91wl2) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/test/core/uri/uri_parser_test.cc#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Oh, right, because we're using `absl::flat_hash_map<>` instead of `std::map<>`.  The latter would have sorted.  (Hmm... Do we actually need `absl::flat_hash_map<>`?  I'm not sure we're ever likely to see enough elements that the hash performance will matter, so `std::map<>` might actually be good enough -- it might even be better for very small maps.  But feel free to leave this as-is too.)

Getting back to this specific test, though, I don't think it's actually useful.  The `==` operator on vectors ensures that both sides are in the same order, so it's already implicit from the existing tests that the vector will be in the right order.  I don't think we need to explicitly test that it's not equal if it's in a different order.
</blockquote></details>

Ok. Removed the test & changed the storage to std::map.


<!-- Sent from Reviewable.io -->

2020-11-19 16:38 UTC, markdroth approved these changes
This looks fantastic!  All remaining comments are cosmetic, so I'll go ahead and approve.

As I mentioned earlier, we'll need to make some internal changes in order to import this, so let's go ahead and start working on a cherry-pick import CL.  Talk to me offline about how to get started with that.

Thanks for doing this!

> Reviewed 13 of 13 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701#-:-MMWMIqk9LjDmE7wsP2M:b2fttl8)* status: all files reviewed, 5 unresolved discussions (waiting on @drfloob)

___
*[src/core/lib/uri/uri_parser.h, line 44 at r14](https://reviewable.io/reviews/grpc/grpc/24701#-MMWIv3u9WQqHixtC7mX:-MMWIv3u9WQqHixtC7mY:b-hzd4ip) ([raw file](https://github.com/grpc/grpc/blob/1387df375e55ee737e11ecf1056e854678965572/src/core/lib/uri/uri_parser.h#L44)):*
> ```objc
>     }
>   };
>   // Creates an instance of GrpcURI by parsing an rfc3986 URI string. Returns
> ```

Please add a blank line above this.  (I hate them within functions, but for class definitions, I think they improve readability.)
___
*[src/core/lib/uri/uri_parser.h, line 47 at r14](https://reviewable.io/reviews/grpc/grpc/24701#-MMWJ6eg4p4N-OyGMYKT:-MMWJ6ehCZzALqqwHOLF:b4aj9t) ([raw file](https://github.com/grpc/grpc/blob/1387df375e55ee737e11ecf1056e854678965572/src/core/lib/uri/uri_parser.h#L47)):*
> ```objc
>   // an IllegalArgumentError on failure.
>   static absl::StatusOr<URI> Parse(absl::string_view uri_text);
>   URI() = default;
> ```

Suggest moving this down below the "main" ctor, so that it's with the other boilerplate ctors.
___
*[src/core/lib/uri/uri_parser.h, line 57 at r14](https://reviewable.io/reviews/grpc/grpc/24701#-MMWIkSLB_ExRZF1pWwY:-MMWIkSMDE4MpT2NpkkS:bjeg4ok) ([raw file](https://github.com/grpc/grpc/blob/1387df375e55ee737e11ecf1056e854678965572/src/core/lib/uri/uri_parser.h#L57)):*
> ```objc
>   URI(URI&&) = default;
>   URI& operator=(URI&&) = default;
>   ~URI() = default;
> ```

I don't think this is needed, since it will be added by the compiler anyway. :)
___
*[src/core/lib/uri/uri_parser.h, line 58 at r14](https://reviewable.io/reviews/grpc/grpc/24701#-MMWJBwi2URU9G6cfDbB:-MMWJBwi2URU9G6cfDbC:b-prxc9w) ([raw file](https://github.com/grpc/grpc/blob/1387df375e55ee737e11ecf1056e854678965572/src/core/lib/uri/uri_parser.h#L58)):*
> ```objc
>   URI& operator=(URI&&) = default;
>   ~URI() = default;
>   const std::string& scheme() const { return scheme_; }
> ```

Please add a blank line above this.
___
*[src/core/lib/uri/uri_parser.h, line 68 at r14](https://reviewable.io/reviews/grpc/grpc/24701#-MMWJHOwBU_pFp9YpTlP:-MMWJHOwBU_pFp9YpTlQ:b-t008q9) ([raw file](https://github.com/grpc/grpc/blob/1387df375e55ee737e11ecf1056e854678965572/src/core/lib/uri/uri_parser.h#L68)):*
> ```objc
>     return query_parameter_map_;
>   }
>   // An vector of key:value query parameter pairs, kept in order of appearance
> ```

s/An/A/
___
*[src/core/lib/uri/uri_parser.cc, line 161 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRAkr02QeIdIpZ5_Ij:-MMWJuGx4-RSL654Pohq:b-bvv8en) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L161)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

I'll leave it as is now, then. This saves us adding more code in QueryParam to support map range construction.
</blockquote></details>

Just FYI, you could actually reduce the amount of code by using `std::pair<>` instead of `QueryParam`.  But arguably, `QueryParam` is more readable, simply because the field names `key` and  `value` are more descriptive of intent than `first` and `second`, as per the style guide:

https://google.github.io/styleguide/cppguide.html#Structs_vs._Tuples

Anyway, this is fine as-is.


<!-- Sent from Reviewable.io -->

2020-11-19 17:06 UTC, drfloob reviewed
Absolutely, thank you for the guidance on it! I found a situation where an end2end test did not fail in Kokoro as I think it should have, I'll pick your brain about that as well before we ship this.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701#-:-MMWRaxLE4U34F3ZFF-D:b-u3jtpx)* status: all files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/uri/uri_parser.h, line 44 at r14](https://reviewable.io/reviews/grpc/grpc/24701#-MMWIv3u9WQqHixtC7mX:-MMWPNu7AD-NgplPeiC4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1387df375e55ee737e11ecf1056e854678965572/src/core/lib/uri/uri_parser.h#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a blank line above this.  (I hate them within functions, but for class definitions, I think they improve readability.)
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.h, line 47 at r14](https://reviewable.io/reviews/grpc/grpc/24701#-MMWJ6eg4p4N-OyGMYKT:-MMWPOD65j3HnOIzZbk9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1387df375e55ee737e11ecf1056e854678965572/src/core/lib/uri/uri_parser.h#L47)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest moving this down below the "main" ctor, so that it's with the other boilerplate ctors.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.h, line 57 at r14](https://reviewable.io/reviews/grpc/grpc/24701#-MMWIkSLB_ExRZF1pWwY:-MMWPPK97bDfPRvDTAms:b-7b3vqt) ([raw file](https://github.com/grpc/grpc/blob/1387df375e55ee737e11ecf1056e854678965572/src/core/lib/uri/uri_parser.h#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is needed, since it will be added by the compiler anyway. :)
</blockquote></details>

I suppose so. An exception to the rule of 5 :-)
___
*[src/core/lib/uri/uri_parser.h, line 58 at r14](https://reviewable.io/reviews/grpc/grpc/24701#-MMWJBwi2URU9G6cfDbB:-MMWPldjBkZc32W1JUtK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1387df375e55ee737e11ecf1056e854678965572/src/core/lib/uri/uri_parser.h#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a blank line above this.
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.h, line 68 at r14](https://reviewable.io/reviews/grpc/grpc/24701#-MMWJHOwBU_pFp9YpTlP:-MMWPsGD93FKzs53VNvh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1387df375e55ee737e11ecf1056e854678965572/src/core/lib/uri/uri_parser.h#L68)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/An/A/
</blockquote></details>

Done.
___
*[src/core/lib/uri/uri_parser.cc, line 161 at r10](https://reviewable.io/reviews/grpc/grpc/24701#-MMRAkr02QeIdIpZ5_Ij:-MMWPuko1ihieI8S4xbg:b-ijfnno) ([raw file](https://github.com/grpc/grpc/blob/b1b35ad3b6935581517353293db7f515f077d672/src/core/lib/uri/uri_parser.cc#L161)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Just FYI, you could actually reduce the amount of code by using `std::pair<>` instead of `QueryParam`.  But arguably, `QueryParam` is more readable, simply because the field names `key` and  `value` are more descriptive of intent than `first` and `second`, as per the style guide:

https://google.github.io/styleguide/cppguide.html#Structs_vs._Tuples

Anyway, this is fine as-is.
</blockquote></details>

Ack. Thanks, I know of that style guide recommendation. In the spirit of it, I am in the habit of reaching for the more readable, human-friendly alternatives when given the opportunity, but I am growing comfortable with choosing more performant choices for this codebase. This isn't one of those situations, per se, but it's got a bit of that flavor :-)


<!-- Sent from Reviewable.io -->

2020-12-01 20:08 UTC, markdroth requested changes
This looks great!

I think the next step is to prepare a cherry-pick import CL and make the internal changes.  Let's talk about that offline.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r15, 1 of 1 files at r16, 24 of 24 files at r17.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701#-:-MNUtwR50VOolDFB6lb4:bemdq9l)* status: all files reviewed, 3 unresolved discussions (waiting on @drfloob)

___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 165 at r17](https://reviewable.io/reviews/grpc/grpc/24701#-MNUsTLk27YIQLjZ5N4u:-MNUsTLl0uNX1ALb74cY:b-2cglwe) ([raw file](https://github.com/grpc/grpc/blob/5216f516aa0dd4191e0bd378c5ea35ec51b279aa/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L165)):*
> ```cpp
>   request.host = const_cast<char*>(uri->authority().c_str());
>   request.http.path = gpr_strdup(uri->path().c_str());
>   request.handshaker = absl::StartsWith(uri->scheme(), "https")
> ```

I think this should just check `uri->scheme() == "https"`.  We don't want to match a scheme like "https_with_some_other_suffix".
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 216 at r17](https://reviewable.io/reviews/grpc/grpc/24701#-MNUspL27_sZt3h1Aulg:-MNUspL27_sZt3h1Aulh:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/5216f516aa0dd4191e0bd378c5ea35ec51b279aa/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L216)):*
> ```cpp
>   request.host = const_cast<char*>(uri->authority().c_str());
>   request.http.path = gpr_strdup(uri->path().c_str());
>   request.handshaker = absl::StartsWith(uri->scheme(), "https")
> ```

Same here.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 281 at r17](https://reviewable.io/reviews/grpc/grpc/24701#-MNUssapCFKBVNR30R2j:-MNUssapCFKBVNR30R2k:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/5216f516aa0dd4191e0bd378c5ea35ec51b279aa/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L281)):*
> ```cpp
>   request.host = const_cast<char*>(uri->authority().c_str());
>   request.http.path = gpr_strdup(uri->path().c_str());
>   request.handshaker = absl::StartsWith(uri->scheme(), "https")
> ```

Same here.


<!-- Sent from Reviewable.io -->

2020-12-03 00:44 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: 62 of 67 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 165 at r17](https://reviewable.io/reviews/grpc/grpc/24701#-MNUsTLk27YIQLjZ5N4u:-MNa2gPy5Jcxp6kziiIc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5216f516aa0dd4191e0bd378c5ea35ec51b279aa/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L165)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this should just check `uri->scheme() == "https"`.  We don't want to match a scheme like "https_with_some_other_suffix".
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 216 at r17](https://reviewable.io/reviews/grpc/grpc/24701#-MNUspL27_sZt3h1Aulg:-MNa2gsy8rb_qg6hdvaj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5216f516aa0dd4191e0bd378c5ea35ec51b279aa/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L216)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 281 at r17](https://reviewable.io/reviews/grpc/grpc/24701#-MNUssapCFKBVNR30R2j:-MNa2hKl-9A63zDesrkZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5216f516aa0dd4191e0bd378c5ea35ec51b279aa/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L281)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 15:57 UTC, markdroth approved these changes
> Reviewed 5 of 5 files at r18.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24701)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-07 23:30 UTC, merged