File watcher certificate provider config parsing
grpc/grpc pull request #24711
Opened 2020-11-09 22:57 UTC by yashykt

2020-11-10 19:04 UTC, markdroth requested changes
This looks good overall!  Comments are mostly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711#-:-MLnXvvGBNU2t8_aUSFv:bnzmleu)* status: all files reviewed, 12 unresolved discussions (waiting on @yashykt)

___
*[BUILD, line 1388 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnOImrAXTMbQ8thjkU:-MLnOImsD5z2zqkflYhI:b-ma7twb) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/BUILD#L1388)):*
> ```Starlark
>         "grpc_client_channel",
>         "grpc_file_watcher_certificate_provider_factory",
>         "grpc_google_mesh_ca_certificate_provider_factory",
> ```

Not directly related to this PR, but should we just remove the MeshCA plugin code, since we're not pursuing it at this point?  I think the way the code is now, we'll accept the MeshCA code in the bootstrap file, but then it won't actually work at run-time, which seems sub-optimal.

Also, this reminds me that we should probably add an environment variable to protect reading the new fields in the bootstrap file until we've interop tested this functionality.
___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnQxx4-kjpkj_QqUlz:-MLnQxx58yahtfcMi7tT:b4pe3ve) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/ext/xds/file_watcher_certificate_provider_factory.h#L47)):*
> ```objc
>     grpc_millis refresh_interval() const { return refresh_interval_; }
> 
>     static RefCountedPtr<Config> Parse(const Json& config_json,
> ```

As per style guide, factory functions should be listed before methods.
___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.h, line 54 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnX3po-JS4bJSHfiAV:-MLnX3po-JS4bJSHfiAW:b-ff0ghz) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/ext/xds/file_watcher_certificate_provider_factory.h#L54)):*
> ```objc
>     std::string private_key_file_;
>     std::string root_cert_file_;
>     grpc_millis refresh_interval_;
> ```

Suggest calling this `refresh_interval_ms_` and renaming the accessor method and parameters accordingly.
___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnRN1fAoeziSPOhrQC:-MLnRN1fAoeziSPOhrQD:b-beqi3s) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/ext/xds/file_watcher_certificate_provider_factory.cc#L48)):*
> ```cpp
>   parts.push_back("{\n");
>   if (!identity_cert_file_.empty()) {
>     parts.push_back(absl::StrFormat("      certificate_file=\"%s\",\n",
> ```

Seems like most of these strings have too much indentation.
___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.cc, line 89 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnSu0r3yd-J2MxXEbL:-MLnSu0r3yd-J2MxXEbM:b-g4mhyl) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/ext/xds/file_watcher_certificate_provider_factory.cc#L89)):*
> ```cpp
>   if (config->identity_cert_file_.empty() && config->root_cert_file_.empty()) {
>     error_list.push_back(GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>         "Either or both \"certificate_file\" and \"ca_certificate_file\" must "
> ```

Suggest changing "Either or both" to "At least one of".
___
*[src/core/lib/json/json_util.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnOw-h5NIaN1Ny4doa:-MLnOw-h5NIaN1Ny4dob:bjionhu) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L43)):*
> ```objc
> //
> template <typename NumericType, typename ErrorVectorType>
> bool ExtractJsonType(const Json& json, const std::string& field_name,
> ```

Might as well define all of these functions as `inline`.
___
*[src/core/lib/json/json_util.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPAVr6W5InPT4U9On:-MLnPAVr6W5InPT4U9Oo:b1u6v04) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L43)):*
> ```objc
> //
> template <typename NumericType, typename ErrorVectorType>
> bool ExtractJsonType(const Json& json, const std::string& field_name,
> ```

Instead of making all of these helpers overloads of the same function name, how about naming them each according to the type of field they work with (e.g., `ExtractJsonNumber()`, `ExtracJsonBool()`, etc)?  That will make the calling code easier to understand.

Reading further, I now see why you used the same name for all of these: it allows `ParseJsonObjectField()` to automatically call the right function for the underlying field.  We could probably get the best of both worlds by giving these functions their own names and then defining some wrappers, all with the same name, to be used in `ParseJsonObjectField()`.
___
*[src/core/lib/json/json_util.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnOgw-5STXecsKOt4x:-MLnOgw-5STXecsKOt4y:b23xb0z) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L52)):*
> ```objc
>     return false;
>   }
>   std::istringstream ss(json.string_value());
> ```

Instead of using a stringstream, I suggest using `absl::SimpleAtoi()`.
___
*[src/core/lib/json/json_util.h, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPaq6BJNvl_5Fb8Z9:-MLnPaq78fUDGjLN_CTZ:bmcox05) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L127)):*
> ```objc
> bool ExtractJsonType(const Json& json, const std::string& field_name,
>                      grpc_millis* output, ErrorVectorType* error_list) {
>   if (!ParseDurationFromJson(json, output)) {
> ```

Do all callers of `ParseDurationFromJson()` want to add this same error?  If so, I suggest just building this into `ParseDurationFromJson()` instead of splitting this into a separate wrapper function.
___
*[src/core/lib/json/json_util.h, line 142 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPnWo7MvmwNslxnec:-MLnPnWo7MvmwNslxned:b-yug3xf) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L142)):*
> ```objc
> bool ParseJsonObjectField(const Json::Object& object,
>                           const std::string& field_name, T* output,
>                           ErrorVectorType* error_list, bool optional = false) {
> ```

I suggest changing `optional` to `required` and reversing the semantics.  It's a bit easier to understand `required=true` than `optional=false`.
___
*[test/core/xds/file_watcher_certificate_provider_factory_test.cc, line 26 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnW5OF6KUKtXw6xhQR:-MLnW5OF6KUKtXw6xhQS:bwngb5h) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/test/core/xds/file_watcher_certificate_provider_factory_test.cc#L26)):*
> ```cpp
> #include <grpc/grpc.h>
> 
> #include "src/core/ext/xds/file_watcher_certificate_provider_factory.h"
> ```

I believe that this include should come first, as per the style guide.
___
*[test/core/xds/file_watcher_certificate_provider_factory_test.cc, line 139 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnXM-W2nJT3oP_FU6a:-MLnXM-W2nJT3oP_FU6b:b6uceoc) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/test/core/xds/file_watcher_certificate_provider_factory_test.cc#L139)):*
> ```cpp
> }
> 
> TEST(FileWatcherConfigTest, EmptyJsonObject) {
> ```

We should also test that it's valid to specify only the root file or only the identity and private key files.


<!-- Sent from Reviewable.io -->

2020-11-10 19:10 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711)* status: all files reviewed, 12 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[BUILD, line 1388 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnOImrAXTMbQ8thjkU:-MLnYYIj63H7lrgp0PdG:budprbs) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/BUILD#L1388)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Not directly related to this PR, but should we just remove the MeshCA plugin code, since we're not pursuing it at this point?  I think the way the code is now, we'll accept the MeshCA code in the bootstrap file, but then it won't actually work at run-time, which seems sub-optimal.

Also, this reminds me that we should probably add an environment variable to protect reading the new fields in the bootstrap file until we've interop tested this functionality.
</blockquote></details>

No we won't, the meshCA plugin is not registered yet. Ah, yes, we should, I'll do that as a separate PR. 
___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnRN1fAoeziSPOhrQC:-MLnYnHBCjmGZeURzP6g:b-g934ft) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/ext/xds/file_watcher_certificate_provider_factory.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Seems like most of these strings have too much indentation.
</blockquote></details>

That is intentional. I wanted it to look good when printed as part of the bootstrap string.


<!-- Sent from Reviewable.io -->

2020-11-10 20:21 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711)* status: 17 of 23 files reviewed, 12 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnQxx4-kjpkj_QqUlz:-MLnmvh57zxKoDoIEtpF:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/ext/xds/file_watcher_certificate_provider_factory.h#L47)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per style guide, factory functions should be listed before methods.
</blockquote></details>

Done
___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.h, line 54 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnX3po-JS4bJSHfiAV:-MLnmyVZ-wJF_IYTLIil:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/ext/xds/file_watcher_certificate_provider_factory.h#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `refresh_interval_ms_` and renaming the accessor method and parameters accordingly.
</blockquote></details>

Done.
___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.cc, line 89 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnSu0r3yd-J2MxXEbL:-MLnmzDnBFmRXPqmaxz0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/ext/xds/file_watcher_certificate_provider_factory.cc#L89)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest changing "Either or both" to "At least one of".
</blockquote></details>

Done.
___
*[src/core/lib/json/json_util.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnOw-h5NIaN1Ny4doa:-MLnn5xn0ZyPuPTrBUdt:b60gkvx) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Might as well define all of these functions as `inline`.
</blockquote></details>

I'm not sure about making them all inline since they seem to be around the border of the "10 line" recommendation. Made the change anyway. Also, I figure that the compiler would inline these anyway if it thought it was needed. Either way, based on reading, I don't think this should be too big of a deal, since this keyword is just a suggestion to the compiler and not a mandate.
___
*[src/core/lib/json/json_util.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPAVr6W5InPT4U9On:-MLnnO8YAX9uCDNeZ7cS:b-q72082) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of making all of these helpers overloads of the same function name, how about naming them each according to the type of field they work with (e.g., `ExtractJsonNumber()`, `ExtracJsonBool()`, etc)?  That will make the calling code easier to understand.

Reading further, I now see why you used the same name for all of these: it allows `ParseJsonObjectField()` to automatically call the right function for the underlying field.  We could probably get the best of both worlds by giving these functions their own names and then defining some wrappers, all with the same name, to be used in `ParseJsonObjectField()`.
</blockquote></details>

Suggestion taken.
___
*[src/core/lib/json/json_util.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnOgw-5STXecsKOt4x:-MLnnR7h1pk1PXylMnM3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of using a stringstream, I suggest using `absl::SimpleAtoi()`.
</blockquote></details>

Done.
___
*[src/core/lib/json/json_util.h, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPaq6BJNvl_5Fb8Z9:-MLnmER5CYPftvF-EOak:b30g29o) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L127)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Do all callers of `ParseDurationFromJson()` want to add this same error?  If so, I suggest just building this into `ParseDurationFromJson()` instead of splitting this into a separate wrapper function.
</blockquote></details>

I think the wrapper is still useful, but I modified the existing uses of `ParseDurationfromJson()` to use `ExtractJsonDuration()`. I wondered whether to just use `ParseJsonObjectField()` but decided against it since I would prefer using that in the whole file if we were going that route (and if that's the preferred way, I'd prefer doing it in a separate PR)
___
*[src/core/lib/json/json_util.h, line 142 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPnWo7MvmwNslxnec:-MLnnS9EBOcxvFOH97si:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L142)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest changing `optional` to `required` and reversing the semantics.  It's a bit easier to understand `required=true` than `optional=false`.
</blockquote></details>

Done.
___
*[test/core/xds/file_watcher_certificate_provider_factory_test.cc, line 26 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnW5OF6KUKtXw6xhQR:-MLnnT9aB9IN9DZ9qPgG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/test/core/xds/file_watcher_certificate_provider_factory_test.cc#L26)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I believe that this include should come first, as per the style guide.
</blockquote></details>

Done.
___
*[test/core/xds/file_watcher_certificate_provider_factory_test.cc, line 139 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnXM-W2nJT3oP_FU6a:-MLnnWaq8ycYjVFdT8Fw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/test/core/xds/file_watcher_certificate_provider_factory_test.cc#L139)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should also test that it's valid to specify only the root file or only the identity and private key files.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-10 20:56 UTC, markdroth requested changes
Only a couple of minor nits remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711#-:-MLnwWYIB6qLTTbbcXz3:b8ie42r)* status: all files reviewed, 2 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnRN1fAoeziSPOhrQC:-MLnox728mSXe6VS9CG6:b-ih12zp) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/ext/xds/file_watcher_certificate_provider_factory.cc#L48)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

That is intentional. I wanted it to look good when printed as part of the bootstrap string.
</blockquote></details>

That seems a little strange, since this `ToString()` method could be called in other contexts.

Some alternatives to consider:
- Have this method generate the result without any additional indentation, and have the bootstrap printing code add the additional indentation as needed (e.g., via `absl::StrReplace(config_str, "\n", "\n    ")`).
- Sidestep the issue entirely by simply encoding the whole config on a single line.  There are only 4 fields, so this seems reasonable.
___
*[src/core/lib/json/json_util.h, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPaq6BJNvl_5Fb8Z9:-MLnq1470wuuPKsfFVon:bog0vhg) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L127)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I think the wrapper is still useful, but I modified the existing uses of `ParseDurationfromJson()` to use `ExtractJsonDuration()`. I wondered whether to just use `ParseJsonObjectField()` but decided against it since I would prefer using that in the whole file if we were going that route (and if that's the preferred way, I'd prefer doing it in a separate PR)
</blockquote></details>

If we now have no callers of `ParseDurationFromJson()` except for this wrapper, then what's the value in the wrapper being separate?

I don't quite understand how this would work via `ParseJsonObjectField()`.  How would it know to do the duration-specific parsing?


<!-- Sent from Reviewable.io -->

2020-11-10 21:21 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711)* status: all files reviewed, 2 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/lib/json/json_util.h, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPaq6BJNvl_5Fb8Z9:-MLo0nlp5yTzv1Wzfm0T:b-w54cxo) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L127)):*
The only value is that ParseDurationFromJson can stay in the cc file

> I don't quite understand how this would work via ParseJsonObjectField(). How would it know to do the duration-specific parsing?

That is based on the output parameter. If the output parameter is `grpc_millis` it would do Duration parsing


<!-- Sent from Reviewable.io -->

2020-11-10 21:33 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711)* status: all files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnRN1fAoeziSPOhrQC:-MLo3xAX17KGCmEmqM6r:bsaw102) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/ext/xds/file_watcher_certificate_provider_factory.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That seems a little strange, since this `ToString()` method could be called in other contexts.

Some alternatives to consider:
- Have this method generate the result without any additional indentation, and have the bootstrap printing code add the additional indentation as needed (e.g., via `absl::StrReplace(config_str, "\n", "\n    ")`).
- Sidestep the issue entirely by simply encoding the whole config on a single line.  There are only 4 fields, so this seems reasonable.
</blockquote></details>

Second suggestion taken


<!-- Sent from Reviewable.io -->

2020-11-10 22:14 UTC, markdroth approved these changes
Only a couple of minor formatting nits remain.  Feel free to merge after addressing them.

Thanks!

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711#-:-MLoDFJt89vqqamAEL9G:b-td8rje)* status: all files reviewed, 2 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.cc, line 46 at r3](https://reviewable.io/reviews/grpc/grpc/24711#-MLoCbDFCentsO1rflHC:-MLoCbDG216TE2b3DalH:b-4d3vx5) ([raw file](https://github.com/grpc/grpc/blob/2fc8cf7d4158a7bf414d94d7ab6476774b9bd3c1/src/core/ext/xds/file_watcher_certificate_provider_factory.cc#L46)):*
> ```cpp
> std::string FileWatcherCertificateProviderFactory::Config::ToString() const {
>   std::vector<std::string> parts;
>   parts.push_back("{\n");
> ```

I think you want to remove the newline here.
___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.cc, line 61 at r3](https://reviewable.io/reviews/grpc/grpc/24711#-MLoCi6W-WugctAtBlNA:-MLoCi6W-WugctAtBlNB:b-8kjzxr) ([raw file](https://github.com/grpc/grpc/blob/2fc8cf7d4158a7bf414d94d7ab6476774b9bd3c1/src/core/ext/xds/file_watcher_certificate_provider_factory.cc#L61)):*
> ```cpp
>   parts.push_back(
>       absl::StrFormat("refresh_interval=%ldms", refresh_interval_ms_));
>   parts.push_back("}");
> ```

Could add this to the end of the format string on the previous line, to avoid unnecessarily creating another string.
___
*[src/core/lib/json/json_util.h, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPaq6BJNvl_5Fb8Z9:-MLoCqIe4iau3b0QRSlK:broub2y) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L127)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

The only value is that ParseDurationFromJson can stay in the cc file

> I don't quite understand how this would work via ParseJsonObjectField(). How would it know to do the duration-specific parsing?

That is based on the output parameter. If the output parameter is `grpc_millis` it would do Duration parsing
</blockquote></details>

Okay, keeping `ParseDurationFromJson()` in the .cc file makes sense.

I don't think we could trigger this behavior based on the output parameter, because `grpc_millis` is ultimately an integer, and the compiler would not be able to tell whether it should use `ExtractJsonDuration()` or `ExtractJsonNumber()`.


<!-- Sent from Reviewable.io -->

2020-11-10 22:23 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711)* status: all files reviewed, 2 unresolved discussions (waiting on @yashykt)

___
*[src/core/lib/json/json_util.h, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPaq6BJNvl_5Fb8Z9:-MLoExGL9N-JdKHuTJfm:befb3tt) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L127)):*
> I don't think we could trigger this behavior based on the output parameter, because grpc_millis is ultimately an integer, and the compiler would not be able to tell whether it should use ExtractJsonDuration() or ExtractJsonNumber().

It works, and it is already being used in the config parsers.


<!-- Sent from Reviewable.io -->

2020-11-10 22:26 UTC, yashykt reviewed
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711#-:-MLoG-o0B-iM1HnkgaTR:b-9qdoz3)* status: 23 of 24 files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.cc, line 46 at r3](https://reviewable.io/reviews/grpc/grpc/24711#-MLoCbDFCentsO1rflHC:-MLoFx9-0LDmJpWRxDjw:bhwvgg9) ([raw file](https://github.com/grpc/grpc/blob/2fc8cf7d4158a7bf414d94d7ab6476774b9bd3c1/src/core/ext/xds/file_watcher_certificate_provider_factory.cc#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you want to remove the newline here.
</blockquote></details>

removed, Thanks!
___
*[src/core/ext/xds/file_watcher_certificate_provider_factory.cc, line 61 at r3](https://reviewable.io/reviews/grpc/grpc/24711#-MLoCi6W-WugctAtBlNA:-MLoFzeUAgN1cbSpMHYH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fc8cf7d4158a7bf414d94d7ab6476774b9bd3c1/src/core/ext/xds/file_watcher_certificate_provider_factory.cc#L61)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Could add this to the end of the format string on the previous line, to avoid unnecessarily creating another string.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-10 22:28 UTC, markdroth requested changes
Looks like there is actually one remaining problem here.

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711#-:-MLoGXmx2PcizRQ9NMXv:bhlr1ee)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/lib/json/json_util.h, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPaq6BJNvl_5Fb8Z9:-MLoG2NM5Laq9gnP2iSk:bq8tejj) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L127)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> I don't think we could trigger this behavior based on the output parameter, because grpc_millis is ultimately an integer, and the compiler would not be able to tell whether it should use ExtractJsonDuration() or ExtractJsonNumber().

It works, and it is already being used in the config parsers.
</blockquote></details>

So, this looks wrong to me.  I think it works only because the `grpc_millis` template is more specific than the general integer one.  But that means whenever it gets used with the underlying type for a general integer (`int64_t`), it will mistakenly select the duration parser instead of the integer parser.  I don't think that's how we want this to work.


<!-- Sent from Reviewable.io -->

2020-11-10 22:55 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[src/core/lib/json/json_util.h, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPaq6BJNvl_5Fb8Z9:-MLoLcGr91QD6Eh4OG6L:b-a7w2q6) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L127)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

So, this looks wrong to me.  I think it works only because the `grpc_millis` template is more specific than the general integer one.  But that means whenever it gets used with the underlying type for a general integer (`int64_t`), it will mistakenly select the duration parser instead of the integer parser.  I don't think that's how we want this to work.
</blockquote></details>

you are right. So the possible ways I can do think of are -
1) use a separate `ParseJsonObjectFieldAsDuration()` function for duration, while retaining `ParseJsonObjectField()` for others
2) remove `ParseJsonObjectField()` completely and replace it with individual functions like `ParseJsonObjectFieldAsNumber()`
what do you think?


<!-- Sent from Reviewable.io -->

2020-11-10 23:03 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/lib/json/json_util.h, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPaq6BJNvl_5Fb8Z9:-MLoN1cQAsVb9aZTOFqk:b-2lkvdw) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L127)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

you are right. So the possible ways I can do think of are -
1) use a separate `ParseJsonObjectFieldAsDuration()` function for duration, while retaining `ParseJsonObjectField()` for others
2) remove `ParseJsonObjectField()` completely and replace it with individual functions like `ParseJsonObjectFieldAsNumber()`
what do you think?
</blockquote></details>

Another option would be to change the `ParseJsonObjectField()` API such that there's a parameter to pass in the function that we want to use to parse the individual field's value if the field is found.  That parameter could default to the appropriate templated version of `ExtractJsonType()`, so that most callers don't need to deal with it, but it could be explicitly overridden by the caller in rare cases like `ExtractJsonDuration()`.

If that won't work, then your option 1 seems fine.


<!-- Sent from Reviewable.io -->

2020-11-10 23:19 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[src/core/lib/json/json_util.h, line 127 at r1](https://reviewable.io/reviews/grpc/grpc/24711#-MLnPaq6BJNvl_5Fb8Z9:-MLoPaO73Wwa7cxYPAuV:b-frb3vh) ([raw file](https://github.com/grpc/grpc/blob/da6049d1e1c5d99415090d9114f0823b14d0b51d/src/core/lib/json/json_util.h#L127)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Another option would be to change the `ParseJsonObjectField()` API such that there's a parameter to pass in the function that we want to use to parse the individual field's value if the field is found.  That parameter could default to the appropriate templated version of `ExtractJsonType()`, so that most callers don't need to deal with it, but it could be explicitly overridden by the caller in rare cases like `ExtractJsonDuration()`.

If that won't work, then your option 1 seems fine.
</blockquote></details>

That suggestion does seem good if we have many unique JSON types to deal with but we seem to be dealing with a limited set of types. I am preferring option 1 for now.


<!-- Sent from Reviewable.io -->

2020-11-10 23:36 UTC, markdroth approved these changes
This looks great!  Feel free to merge after addressing remaining nit.

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711#-:-MLoW3Ul4fF7lRiwm_QV:by82wmv)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/lib/json/json_util.h, line 126 at r5](https://reviewable.io/reviews/grpc/grpc/24711#-MLoVRcF0OYoEcUY7OGp:-MLoVRcF0OYoEcUY7OGq:b-2qd2bb) ([raw file](https://github.com/grpc/grpc/blob/7489c501032b872001c617233edcc3c848932261/src/core/lib/json/json_util.h#L126)):*
> ```objc
> 
> template <typename ErrorVectorType>
> inline bool ExtractJsonDuration(const Json& json, const std::string& field_name,
> ```

Are there any cases where this is going to be called directly, or will it always be called from `ParseJsonObjectFieldAsDuration()`?  If so, maybe just move this code right into `ParseJsonObjectFieldAsDuration()`.


<!-- Sent from Reviewable.io -->

2020-11-10 23:49 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24711)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[src/core/lib/json/json_util.h, line 126 at r5](https://reviewable.io/reviews/grpc/grpc/24711#-MLoVRcF0OYoEcUY7OGp:-MLoWUdp7vhoavo1Kmd3:b-7n434w) ([raw file](https://github.com/grpc/grpc/blob/7489c501032b872001c617233edcc3c848932261/src/core/lib/json/json_util.h#L126)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Are there any cases where this is going to be called directly, or will it always be called from `ParseJsonObjectFieldAsDuration()`?  If so, maybe just move this code right into `ParseJsonObjectFieldAsDuration()`.
</blockquote></details>

It is being used currently by resolver_result_parsing but that can potentially be removed once the code moves to use `ParseJsonObjectField()`.. Well, let me go ahead and pre-emptively replace it anyway. Done


<!-- Sent from Reviewable.io -->

2020-11-11 10:23 UTC, merged

2025-02-27 06:49 UTC, stasos24 commented on src/core/ext/xds/file_watcher_certificate_provider_factory.cc
> +  if (!identity_cert_file_.empty()) {
Why is cert_file is checked and not private_key?

2025-02-27 06:50 UTC, stasos24 commented on src/core/ext/xds/file_watcher_certificate_provider_factory.cc
> +  if (!identity_cert_file_.empty()) {
Same with ca_cert_file

2025-02-27 16:12 UTC, markdroth commented
@stasos24 Good catch!  I've sent #38872 to fix this.