[Clang-Tidy] google-readability-casting
grpc/grpc pull request #24841
Opened 2020-11-25 21:30 UTC by veblush

https://clang.llvm.org/extra/clang-tidy/checks/google-readability-casting.html

Fix is done with the automatic fix and manual modification.

2020-12-01 07:42 UTC, veblush commented
Mark, forgive me for a massive PR. Mostly mechanical so it shouldn't be too tough than it appears. (hopefully)

2020-12-01 19:50 UTC, markdroth reviewed
Thanks for doing this!

> Reviewed 252 of 252 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24841#-:-MNUqlwB4KDl6lRJGwcs:bxgavm9)* status: all files reviewed, 33 unresolved discussions (waiting on @veblush)

___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 537 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNU7EyPAKUYyQorPkhx:-MNU7EyPAKUYyQorPkhy:b-jkfna1) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L537)):*
> ```cpp
>       gpr_log(GPR_ERROR,
>               "Invalid port '%d' at index %lu of serverlist. Ignoring.",
>               server.port, static_cast<unsigned long>(idx));
> ```

Instead of casting here, let's change the format string to use `PRIuPTR`.
___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 546 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNU7I2f6R4c3Wot5UoZ:-MNU7I2g-anXmslieCXq:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L546)):*
> ```cpp
>               "Expected IP to be 4 or 16 bytes, got %d at index %lu of "
>               "serverlist. Ignoring",
>               server.ip_size, static_cast<unsigned long>(idx));
> ```

Same here.
___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1361 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNU7Ldg6J8lN82y_mgF:-MNU7Ldg6J8lN82y_mgG:b-x6xgqx) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1361)):*
> ```cpp
> 
> GrpcLb::~GrpcLb() {
>   gpr_free(const_cast<char*>(server_name_));
> ```

Consider changing the type of `server_name_` to `std::string` so that this isn't necessary.
___
*[src/core/lib/iomgr/ev_epollex_linux.cc, line 735 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUIcx36mjhpptME5Id:-MNUIcx56S3RdSY9g5rD:bijykvh) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/ev_epollex_linux.cc#L735)):*
> ```cpp
>     gpr_log(GPR_INFO,
>             "PS:%p kick %p tls_pollset=%p tls_worker=%p pollset.root_worker=%p",
>             static_cast<void*>(pollset), specific_worker,
> ```

Is this cast actually needed?  I thought that `%p` could be used with any pointer type.
___
*[src/core/lib/iomgr/lockfree_event.cc, line 218 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUYAYq5qkfxi_eWl8U:-MNUYAYq5qkfxi_eWl8V:bqyai39) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/lockfree_event.cc#L218)):*
> ```cpp
>     if (GRPC_TRACE_FLAG_ENABLED(grpc_polling_trace)) {
>       gpr_log(GPR_DEBUG, "LockfreeEvent::SetReady: %p curr=%p", &state_,
>               reinterpret_cast<void*>(curr));
> ```

Is this cast actually needed?
___
*[src/core/lib/iomgr/python_util.h, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUYN3z1GFQBiTu8CSf:-MNUYN3z1GFQBiTu8CSg:b6r6cry) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/python_util.h#L39)):*
> ```objc
> 
> inline char* grpc_slice_buffer_start(grpc_slice_buffer* buffer, int i) {
>   return reinterpret_cast<char*> GRPC_SLICE_START_PTR(buffer->slices[i]);
> ```

Nit: Please add parens around the "argument" of the cast.
___
*[src/core/lib/iomgr/sockaddr_utils.cc, line 278 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUYors2Z1hpH6GmpqE:-MNUYors2Z1hpH6GmpqF:b-fy1vmd) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/sockaddr_utils.cc#L278)):*
> ```cpp
> }
> 
> int grpc_sockaddr_set_port(const grpc_resolved_address* resolved_addr,
> ```

Given that this function modifies `resolved_addr`, I think that parameter should not be passed in as `const` in the first place.  Can we fix that so that there's no need for the `const_cast<>` below?
___
*[src/core/lib/iomgr/tcp_custom.cc, line 184 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUZiKdA0IgG0vWLdjZ:-MNUZiKdA0IgG0vWLdj_:bfwybax) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/tcp_custom.cc#L184)):*
> ```cpp
>      * to tcp->read_slices and wait for the callback indicating that the
>      * allocation was successful. So slices[0] should always exist here */
>     char* buffer = reinterpret_cast<char*> GRPC_SLICE_START_PTR(
> ```

Please add parens around the "argument" of the cast.
___
*[src/core/lib/iomgr/unix_sockets_posix.cc, line 99 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNU_Vzj1ou2c8RV7TKu:-MNU_Vzj1ou2c8RV7TKv:bhcxk0c) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/unix_sockets_posix.cc#L99)):*
> ```cpp
>     return "";
>   }
>   if ((reinterpret_cast<const struct sockaddr_un*>(addr))->sun_path[0] ==
> ```

It looks like this code is doing the same cast many times.  I suggest writing this as:

```
const auto* unix_addr = reinterpret_cast<const struct sockaddr_un*>(addr);
if (unix_addr->sun_path[0] == '\0' && unix_addr->sun_path[1] != '\0') {
  return absl::StrCat(
      "unix-abstract:",
      absl::string_view(unix_addr->sun_path + 1,
                        resolved_addr->len - sizeof(unix_addr->sun_family) - 1));
}
return absl::StrCat("unix:",  unix_addr->sun_path);
```
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 424 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUbzr14tIpzEVP-3bR:-MNUbzr27CQRhVLH3klz:b-pa4itc) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L424)):*
> ```cpp
>   gpr_free(const_cast<char*>(arg->target_name));
>   gpr_free(const_cast<char*>(arg->peer_cert));
>   if (arg->peer_cert_full_chain) {
> ```

No need for this check -- calling `gpr_free()` on a null pointer is a no-op.
___
*[src/core/lib/surface/call.cc, line 837 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUcHEI1LsFsv-My8jL:-MNUcHEI1LsFsv-My8jM:b-qnatpp) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/surface/call.cc#L837)):*
> ```cpp
>   if (accepted_user_data != nullptr) {
>     *encodings_accepted_by_peer = static_cast<uint32_t>(
>         (reinterpret_cast<uintptr_t>(accepted_user_data)) - 1);
> ```

No need for the parens around the `reinterpret_cast<>`.
___
*[src/core/lib/surface/call.cc, line 878 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUcKkDCKzQdjkfXCUu:-MNUcKkDCKzQdjkfXCUv:b-nswxfj) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/surface/call.cc#L878)):*
> ```cpp
>       mdel, destroy_encodings_accepted_by_peer,
>       reinterpret_cast<void*>(
>           (static_cast<uintptr_t>(*encodings_accepted_by_peer)) + 1));
> ```

No need for the parens around the `static_cast<>`.
___
*[src/core/lib/surface/call.cc, line 892 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUcTWD7LpyHtFPmPyW:-MNUcTWD7LpyHtFPmPyX:bqmzy84) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/surface/call.cc#L892)):*
> ```cpp
> }
> 
> static grpc_linked_mdelem* linked_from_md(const grpc_metadata* md) {
> ```

Why is the input parameter `const` here if we're returning a non-const pointer to its data?
___
*[src/core/lib/surface/completion_queue.cc, line 799 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUd2pK65AnZlNimkUR:-MNUd2pK65AnZlNimkUS:b-yz4cex) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/surface/completion_queue.cc#L799)):*
> ```cpp
>   storage->done = done;
>   storage->done_arg = done_arg;
>   storage->next = (reinterpret_ca [...]

2020-12-01 20:00 UTC, drfloob commented
___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1361 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNU7Ldg6J8lN82y_mgF:-MNUsrZ1AvDzoTJuNm-Y:b-buq5bs) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1361)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Consider changing the type of `server_name_` to `std::string` so that this isn't necessary.
</blockquote></details>

FWIW, this change is already done in the URI Parser rewrite work, to be merged.


<!-- Sent from Reviewable.io -->

2020-12-01 20:10 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24841)* status: all files reviewed, 33 unresolved discussions (waiting on @drfloob and @veblush)

___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1361 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNU7Ldg6J8lN82y_mgF:-MNUv95c0ajGTuO6K16n:b4nyst2) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1361)):*
<details><summary><i>Previously, drfloob (Adam J Heller) wrote…</i></summary><blockquote>

FWIW, this change is already done in the URI Parser rewrite work, to be merged.
</blockquote></details>

Yup.  Whichever PR gets merged first, the other one will need to merge in the changes.


<!-- Sent from Reviewable.io -->

2020-12-02 21:43 UTC, veblush reviewed
Thank you for the thorough review

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24841#-:-MN_Nq7SCorqtH-p_27-:b7gtmjc)* status: all files reviewed, 32 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 537 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNU7EyPAKUYyQorPkhx:-MN_5agE3Jzka8MVtIO6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L537)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of casting here, let's change the format string to use `PRIuPTR`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 546 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNU7I2f6R4c3Wot5UoZ:-MN_5bPcAZ3Z0aBP6nah:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L546)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1361 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNU7Ldg6J8lN82y_mgF:-MN_5glIA6run_lHmIQj:b1kzfkc) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1361)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yup.  Whichever PR gets merged first, the other one will need to merge in the changes.
</blockquote></details>

I'm reluctant to refactor type itself in this PR because this is already really big. Rather, I'll rebase it again once AJ's PR gets merged.
___
*[src/core/lib/iomgr/ev_epollex_linux.cc, line 735 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUIcx36mjhpptME5Id:-MN_M0sn9Eas17W82WFf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/ev_epollex_linux.cc#L735)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this cast actually needed?  I thought that `%p` could be used with any pointer type.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/lockfree_event.cc, line 218 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUYAYq5qkfxi_eWl8U:-MN_71K22wEvyJyn2rTR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/lockfree_event.cc#L218)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this cast actually needed?
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/python_util.h, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUYN3z1GFQBiTu8CSf:-MN_7EZRBTD6c6VT__2q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/python_util.h#L39)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Nit: Please add parens around the "argument" of the cast.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/sockaddr_utils.cc, line 278 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUYors2Z1hpH6GmpqE:-MN_IqxmA31WyPdVb-RD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/sockaddr_utils.cc#L278)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Given that this function modifies `resolved_addr`, I think that parameter should not be passed in as `const` in the first place.  Can we fix that so that there's no need for the `const_cast<>` below?
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/tcp_custom.cc, line 184 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUZiKdA0IgG0vWLdjZ:-MN_Iz0l-e1PPuxdFBV8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/tcp_custom.cc#L184)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add parens around the "argument" of the cast.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/unix_sockets_posix.cc, line 99 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNU_Vzj1ou2c8RV7TKu:-MN_JVmbB3gR5OUbN9AV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/unix_sockets_posix.cc#L99)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like this code is doing the same cast many times.  I suggest writing this as:

```
const auto* unix_addr = reinterpret_cast<const struct sockaddr_un*>(addr);
if (unix_addr->sun_path[0] == '\0' && unix_addr->sun_path[1] != '\0') {
  return absl::StrCat(
      "unix-abstract:",
      absl::string_view(unix_addr->sun_path + 1,
                        resolved_addr->len - sizeof(unix_addr->sun_family) - 1));
}
return absl::StrCat("unix:",  unix_addr->sun_path);
```
</blockquote></details>

Done.
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 424 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUbzr14tIpzEVP-3bR:-MN_Jjsb2huNwC2z2hiZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L424)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this check -- calling `gpr_free()` on a null pointer is a no-op.
</blockquote></details>

Done.
___
*[src/core/lib/surface/call.cc, line 837 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUcHEI1LsFsv-My8jL:-MN_M6EVD5GoetOsByZU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/surface/call.cc#L837)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the parens around the `reinterpret_cast<>`.
</blockquote></details>

Done.
___
*[src/core/lib/surface/call.cc, line 878 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUcKkDCKzQdjkfXCUu:-MN_Jv498ULGZjsUSnOj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/surface/call.cc#L878)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the parens around the `static_cast<>`.
</blockquote></details>

Done.
___
*[src/core/lib/surface/call.cc, line 892 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUcTWD7LpyHtFPmPyW:-MN_KbnRD_8TFEJwdseI:b-uflp3x) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/surface/call.cc#L892)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is the input parameter `const` here if we're returning a non-const pointer to its data?
</blockquote></details>

I changed it to return const T*.
___
*[src/core/lib/surface/completion_queue.cc, line 799 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUd2pK65AnZlNimkUR:-MN_Kkir79FDmUC4SzyM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/surface/completion_queue.cc#L799)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the parens around the `reinterpret_cast<>` or the `static_cast<>`.
</blockquote></details>

Done.
___
*[src/core/lib/surface/completion_queue.cc, line 808 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUd8lADKk-3HjdP0QM:-MN_Kp-0AMOn9aIipkbO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5 [...]

2020-12-02 21:49 UTC, vjpai commented
To make massive code health PRs like this reviewable, consider using //experimental/users/vpai/scripts/commit_splitter.sh which splits a massive commit into 10 file branches that you can farm out to different people.

2020-12-03 15:52 UTC, markdroth requested changes
This looks really good!  Just a few minor comments remaining.

> Reviewed 23 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24841#-:-MNdISMo4SXjVI4U98_7:b-ar8soa)* status: all files reviewed, 6 unresolved discussions (waiting on @veblush)

___
*[src/core/lib/iomgr/lockfree_event.cc, line 218 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUYAYq5qkfxi_eWl8U:-MNdFq_O1_xtjgXjEbBG:b6liz3q) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/iomgr/lockfree_event.cc#L218)):*
<details><summary><i>Previously, veblush (Esun Kim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like you changed it on line 168, but it also needs to be fixed here (and anywhere else I might have missed it).
___
*[src/core/lib/iomgr/unix_sockets_posix.cc, line 101 at r2](https://reviewable.io/reviews/grpc/grpc/24841#-MNdGSV5D1EbeKc6MiBE:-MNdGSV5D1EbeKc6MiBF:b-mtbwi2) ([raw file](https://github.com/grpc/grpc/blob/7d7c3cc7110427a66ee49611a357aca1e9eada0c/src/core/lib/iomgr/unix_sockets_posix.cc#L101)):*
> ```cpp
>   const auto* unix_addr = reinterpret_cast<const struct sockaddr_un*>(addr);
>   if (unix_addr->sun_path[0] == '\0' && unix_addr->sun_path[1] != '\0') {
>     const struct sockaddr_un* un =
> ```

This variable is not needed, since it's exactly the same thing that's stored in `unix_addr`.
___
*[src/core/lib/surface/call.cc, line 892 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUcTWD7LpyHtFPmPyW:-MNdGxWo1m6ZU45omSCD:bki72md) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/lib/surface/call.cc#L892)):*
<details><summary><i>Previously, veblush (Esun Kim) wrote…</i></summary><blockquote>

I changed it to return const T*.
</blockquote></details>

It looks like every place this is being called, we're doing a `const_cast<>` to eliminate the `const` on the return value.  I think it would make more sense to just make the input parameter non-const.

I think that on line 916, we can change `md` to be non-`const`, and this problem will go away.
___
*[src/core/tsi/ssl_transport_security.cc, line 1715 at r1](https://reviewable.io/reviews/grpc/grpc/24841#-MNUefYK1KPaEb0-gACU:-MNdI7zC4OxmSBt7Zuhu:bqyq9z2) ([raw file](https://github.com/grpc/grpc/blob/e0d8c498a60be0b5b5891e280bd441ec4a9d0785/src/core/tsi/ssl_transport_security.cc#L1715)):*
<details><summary><i>Previously, veblush (Esun Kim) wrote…</i></summary><blockquote>

It was surprise to me too. It actually needs it.
https://godbolt.org/z/qsq46r
</blockquote></details>

Interesting.  I wonder if it's somehow related to it being a double pointer...
___
*[src/core/tsi/alts/frame_protector/frame_handler.cc, line 37 at r2](https://reviewable.io/reviews/grpc/grpc/24841#-MNdHSyJ-Y-dgS_TkpCY:-MNdHSyJ-Y-dgS_TkpCZ:becpv26) ([raw file](https://github.com/grpc/grpc/blob/7d7c3cc7110427a66ee49611a357aca1e9eada0c/src/core/tsi/alts/frame_protector/frame_handler.cc#L37)):*
> ```cpp
>          (static_cast<uint32_t>(buffer[2]) << 16) |
>          (static_cast<uint32_t>(buffer[1]) << 8) |
>          (static_cast<uint32_t>(buffer[0]));
> ```

No need for the parens around this.
___
*[src/core/tsi/alts/zero_copy_frame_protector/alts_iovec_record_protocol.cc, line 62 at r2](https://reviewable.io/reviews/grpc/grpc/24841#-MNdHXit136CHAAJJ1xr:-MNdHXit136CHAAJJ1xs:b-vbpgpf) ([raw file](https://github.com/grpc/grpc/blob/7d7c3cc7110427a66ee49611a357aca1e9eada0c/src/core/tsi/alts/zero_copy_frame_protector/alts_iovec_record_protocol.cc#L62)):*
> ```cpp
>          (static_cast<uint32_t>(buffer[2]) << 16) |
>          (static_cast<uint32_t>(buffer[1]) << 8) |
>          (static_cast<uint32_t>(buffer[0]));
> ```

No need for parens around this.
___
*[src/core/tsi/alts/zero_copy_frame_protector/alts_zero_copy_grpc_protector.cc, line 93 at r2](https://reviewable.io/reviews/grpc/grpc/24841#-MNdH_PN6dj_X2DHks2H:-MNdH_PN6dj_X2DHks2I:b-vbpgpf) ([raw file](https://github.com/grpc/grpc/blob/7d7c3cc7110427a66ee49611a357aca1e9eada0c/src/core/tsi/alts/zero_copy_frame_protector/alts_zero_copy_grpc_protector.cc#L93)):*
> ```cpp
>                         (static_cast<uint32_t>(frame_size_buffer[2]) << 16) |
>                         (static_cast<uint32_t>(frame_size_buffer[1]) << 8) |
>                         (static_cast<uint32_t>(frame_size_buffer[0]));
> ```

No need for parens around this.


<!-- Sent from Reviewable.io -->

2020-12-03 19:01 UTC, markdroth approved these changes
Looks great!

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24841#-:-MNdyhra3qK8fiQFyUzN:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-03 22:49 UTC, merged