Added bazel warm-up step to sanity docker image
grpc/grpc pull request #24908
Opened 2020-12-04 22:26 UTC by veblush

Warm-up

2020-12-07 08:41 UTC, jtattermusch requested changes
Because the fix feels fragile and probably also bloats the sanity docker image (entire clone of grpc repo and all the bazel cache), I'd like to understand more.

Where exactly does the `https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz` dependency come from  and how come the download is unreliable? I'd expect there would be 2 URLs for bazel to try (primary download location and a mirror). Is there a way for us to add a mirror? (probably better than resorting to a hack you're proposing).

https://source.cloud.google.com/results/invocations/0c28b27c-6bb2-4a21-8520-b86c6f1750ab/targets/github%2Fgrpc%2Frun_tests%2Fsanity_linux_dbg_native%2Ftools%2Fdistrib%2Fclang_tidy_code.sh/tests

2020-12-07 08:45 UTC, jtattermusch commented
```
ERROR: An error occurred during the fetch of repository 'remotejdk11_linux':
   java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz] to /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/external/remotejdk11_linux/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz: Connection reset
ERROR: /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/external/bazel_tools/tools/jdk/BUILD:494:1: @bazel_tools//tools/jdk:remote_jdk11 depends on @remotejdk11_linux//:jdk in repository @remotejdk11_linux which failed to fetch. no such package '@remotejdk11_linux//': java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz] to /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/external/remotejdk11_linux/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz: Connection reset
```
where is the remotejdk11_linux dependency coming from?

2020-12-23 18:46 UTC, veblush commented
@jtattermusch I guess `remotejdk11_linux` comes from the bazel. [code]( https://github.com/bazelbuild/bazel/blob/b413479d79550f77e2f4f562be1ff71c73230e0d/src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE#L23) I assume that this is required to run to build the compilation database for the clang-tidy. Not sure this file is the only one that failed to download. Since this is on `mirror.bazel.build` (seems to be hosted by aws), I expected that this is stable enough but somehow it isn't.

2021-01-12 15:58 UTC, jtattermusch commented
Can you measure what is the docker image size increase caused by this? I'm afraid it's going to be very significant (and we should be making the image sizes smaller, not larger - they are already pretty bloated).

2021-01-12 15:59 UTC, jtattermusch commented on tools/dockerfile/test/sanity/Dockerfile
> +# Warm-up Bazel (prefetching required files so that it can use cached ones later)
What are actually the files that are going to be cached by this?

2021-01-12 16:03 UTC, jtattermusch commented
> @jtattermusch I guess `remotejdk11_linux` comes from the bazel. [code](https://github.com/bazelbuild/bazel/blob/b413479d79550f77e2f4f562be1ff71c73230e0d/src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE#L23) I assume that this is required to run to build the compilation database for the clang-tidy. Not sure this file is the only one that failed to download. Since this is on `mirror.bazel.build` (seems to be hosted by aws), I expected that this is stable enough but somehow it isn't.

Not understanding what really behind the flaky mirrored download AND the workaround being a cryptic and hacky is what's making me nervous and therefore I don't feel comfortable approving this.

Can you reproduce the flakiness problem locally? (and also are we sure that the workaround would actually fix the flake?).

2021-03-04 17:39 UTC, veblush commented
Let's close this PR since it significantly increases the size of the docker image.

2021-03-04 17:39 UTC, closed without merging