Xds cluster resolver
grpc/grpc pull request #24922
Opened 2020-12-07 08:25 UTC by donnadionne

- Based on eds.cc (kept changes in eds.cc for easier comparison, will start new files in the final draft)
- Implemented new xds cluster resolver config
- Separated policy and discovery mechanism 

This is very initial draft, to be used a base of discussions. 

@markdroth

2020-12-07 21:14 UTC, markdroth requested changes
This is a reasonable start.  My main comment is that the separation between the LB policy and the discovery mechanism is not very clean; most of my suggestions are about how to improve that.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MNz0pqt13vjWfKrsyrd:b-zddl46)* status: all files reviewed, 30 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNySzs06O1QqLC7HLBF:-MNySzs1CpiOHGvFOQAp:bwmk9xc) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L58)):*
> ```cpp
> constexpr char kXdsClusterResolver[] = "xds_cluster_resolver_experimental";
> 
> enum DiscoveryMechanismType {
> ```

This should be moved inside of the `XdsClusterResolverLbConfig::DiscoveryMechanism` struct.  There's no reason to pollute the outer namespace with these names.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 82 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyTrIB38qjNHX38xTH:-MNyTrIB38qjNHX38xTI:bco0fw4) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L82)):*
> ```cpp
>   const char* name() const override { return kXdsClusterResolver; }
> 
>   // TODO@donnadionne: Rewrite all the methods using index 0.
> ```

I think these methods should actually just be removed altogether.  Instead, the fields will be read directly out of the elements of the vector returned by `discovery_mechanisms()`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 111 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyUgu140mtnxxA2oM6:-MNyUgu140mtnxxA2oM7:b-uln1j5) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L111)):*
> ```cpp
> };
> 
> class DiscoveryMechanismInterface
> ```

This should be moved inside of `XdsClusterResolverLb`, in the private section.

As a more general comment: Whenever you are deciding what scope to use for a class or a data member, you should put it in the most restrictive scope where it is actually going to be used.  Here are some rules of thumb to keep in mind:
- If class A is going to be used only inside of another class B, then class A should be nested inside of class B, in the private section.  There is no need to expose it outside of B.  This avoids unnecessarily polluting the namespace outside of B, and it allows class A to access private fields in B, which avoids the need for public accessor methods that expose B's internal state to A.  (This class is an example of this.)
- If class A is going to be used outside of another class B but is only used in conjunction with class B, it should be defined in class B in the public section.  Just as in the previous bullet, this avoids unnecessarily polluting the namespace outside of B, and it allows class A to access private fields in B.  In addition, it makes it clear to callers that A is part of the API of B.  (An example of this is [`XdsClient::ListenerWatcherInterface`](https://github.com/grpc/grpc/blob/8c12cc80e875395e1d69087ede6413001b6558c0/src/core/ext/xds/xds_client.h#L47).)
- The only time that class A should be placed outside of class B is if there are times when A will be used completely independently of B.

Note that these rules of thumb apply at all levels of nesting.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 111 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyYVHn7P9BgkvHTHBp:-MNyYVHn7P9BgkvHTHBq:b-cwjse3) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L111)):*
> ```cpp
> };
> 
> class DiscoveryMechanismInterface
> ```

Please add comments explaining how implementations of this interface are expected to interact with the LB policy.    I assume that the implementation will be responsible for calling some method on the LB policy when an event occurs (e.g., the implementation needs to invoke the LB policy's `OnEndpointChanged()`, `OnError()`, and `OnResourceDoesNotExist()` methods when the corresponding events occur).
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 112 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyWacP0k_x9vgQfLah:-MNyWacP0k_x9vgQfLai:b-t31arp) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L112)):*
> ```cpp
> 
> class DiscoveryMechanismInterface
>     : public RefCounted<DiscoveryMechanismInterface> {
> ```

I think these objects will have only one external owner (the LB policy), so they should be `InternallyRefCounted<>`.  When the LB policy orphans them, they can stop their underlying watch mechanism (for the EDS impl, this is the watcher on the XdsClient; for the DNS impl, this is the result handler from the DNS resolver), and then they will be destroyed when all of their refs go away.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 117 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyUq5M1n2WAakiuggq:-MNyUq5M1n2WAakiuggr:bhhhuwl) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L117)):*
> ```cpp
>       : index_(index), num_of_priorities_(0){};
>   virtual ~DiscoveryMechanismInterface() = default;
>   uint32_t GetIndex() { return index_; }
> ```

Is this method actually needed?  If the discovery mechanism returns its results by calling the LB policy's `OnEndpointChanged()`, `OnError()`, and `OnResourceDoesNotExist()` methods, we can probably just have the discovery mechanism pass its index as a parameter to those methods.  In that case, it would probably make sense to have the subclasses store the index directly, rather than doing it in the base class.

If this does stay for some reason, please call it `index()`, since it's a simple accessor method.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 124 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyUHyZ853XGpszGnSy:-MNyUHyZ853XGpszGnSz:bl88mq0) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L124)):*
> ```cpp
>   // Stores its own index in the vector of DiscoveryMechanismInterface.
>   uint32_t index_;
>   uint32_t num_of_priorities_;
> ```

Suggest just calling this `num_priorities_` -- the "of" doesn't really help the reader understand it.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 124 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyri5dB6aa17jU-vM6:-MNyri5dB6aa17jU-vM7:bmcpokz) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L124)):*
> ```cpp
>   // Stores its own index in the vector of DiscoveryMechanismInterface.
>   uint32_t index_;
>   uint32_t num_of_priorities_;
> ```

The division of responsibilities between the discovery mechanism and the LB policy needs to be clear:
- The discovery mechanism should be responsible for getting new data from whatever the data source is and reporting that data to the LB policy.
- The LB policy should be responsible for figuring out how to combine the data from the various discovery mechanisms.

The number of priorities returned by a given discovery mechanism is used for the latter, not the former, so it should be tracked by the LB policy, not the individual discovery mechanism.

So instead of storing this inside of the discovery mechanism, I suggest having the LB policy track this itself, using something like thi [...]

2020-12-09 10:59 UTC, donnadionne reviewed
addressed all the comments.  PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MO68yZ_5O8H1CBiNhqZ:b-aaog6p)* status: all files reviewed, 30 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNySzs06O1QqLC7HLBF:-MO01x-N3PWpMbqISPcx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be moved inside of the `XdsClusterResolverLbConfig::DiscoveryMechanism` struct.  There's no reason to pollute the outer namespace with these names.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 82 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyTrIB38qjNHX38xTH:-MO4t6C9Cmt0rdgYx8_j:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L82)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think these methods should actually just be removed altogether.  Instead, the fields will be read directly out of the elements of the vector returned by `discovery_mechanisms()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 111 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyUgu140mtnxxA2oM6:-MO0AB_20IbbnjJ2Ofih:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L111)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be moved inside of `XdsClusterResolverLb`, in the private section.

As a more general comment: Whenever you are deciding what scope to use for a class or a data member, you should put it in the most restrictive scope where it is actually going to be used.  Here are some rules of thumb to keep in mind:
- If class A is going to be used only inside of another class B, then class A should be nested inside of class B, in the private section.  There is no need to expose it outside of B.  This avoids unnecessarily polluting the namespace outside of B, and it allows class A to access private fields in B, which avoids the need for public accessor methods that expose B's internal state to A.  (This class is an example of this.)
- If class A is going to be used outside of another class B but is only used in conjunction with class B, it should be defined in class B in the public section.  Just as in the previous bullet, this avoids unnecessarily polluting the namespace outside of B, and it allows class A to access private fields in B.  In addition, it makes it clear to callers that A is part of the API of B.  (An example of this is [`XdsClient::ListenerWatcherInterface`](https://github.com/grpc/grpc/blob/8c12cc80e875395e1d69087ede6413001b6558c0/src/core/ext/xds/xds_client.h#L47).)
- The only time that class A should be placed outside of class B is if there are times when A will be used completely independently of B.

Note that these rules of thumb apply at all levels of nesting.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 111 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyYVHn7P9BgkvHTHBp:-MO0CQGG3WDTpDln07nc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L111)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add comments explaining how implementations of this interface are expected to interact with the LB policy.    I assume that the implementation will be responsible for calling some method on the LB policy when an event occurs (e.g., the implementation needs to invoke the LB policy's `OnEndpointChanged()`, `OnError()`, and `OnResourceDoesNotExist()` methods when the corresponding events occur).
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 112 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyWacP0k_x9vgQfLah:-MO0CUJuDT7JFv50iIsV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L112)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think these objects will have only one external owner (the LB policy), so they should be `InternallyRefCounted<>`.  When the LB policy orphans them, they can stop their underlying watch mechanism (for the EDS impl, this is the watcher on the XdsClient; for the DNS impl, this is the result handler from the DNS resolver), and then they will be destroyed when all of their refs go away.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 117 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyUq5M1n2WAakiuggq:-MO0CWCy2JmoX2uYzbQQ:b-hfpv0l) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L117)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this method actually needed?  If the discovery mechanism returns its results by calling the LB policy's `OnEndpointChanged()`, `OnError()`, and `OnResourceDoesNotExist()` methods, we can probably just have the discovery mechanism pass its index as a parameter to those methods.  In that case, it would probably make sense to have the subclasses store the index directly, rather than doing it in the base class.

If this does stay for some reason, please call it `index()`, since it's a simple accessor method.
</blockquote></details>

removed
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 124 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyUHyZ853XGpszGnSy:-MO0CXLpCkJcSnMZWeq0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest just calling this `num_priorities_` -- the "of" doesn't really help the reader understand it.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 124 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyri5dB6aa17jU-vM6:-MO0CZm_4OZtHkdBJ7O_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The division of responsibilities between the discovery mechanism and the LB policy needs to be clear:
- The discovery mechanism should be responsible for getting new data from whatever the data source is and reporting that data to the LB policy.
- The LB policy should be responsible for figuring out how to combine the data from the various discovery mechanisms.

The number of priorities returned by a given discovery mechanism is used for the latter, not the former, so it should be tracked by the LB policy, not the individual discovery mechanism.

So instead of storing this inside of the discovery mechanism, I suggest having the LB policy track this itself, using something like this:

```
class XdsClusterResolverLb : public LoadBalancingPolicy {
  // ...
 private:
  // Vector of discovery mechanisms.
  struct DiscoveryMechanismEntry {
    OrphanablePtr<DiscoveryMechanismInterface> discovery_mechanism;
    // Number o [...]

2020-12-09 18:52 UTC, markdroth requested changes
This is moving in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MO7qEI8AFAqMJxwlHD8:b-k1b92a)* status: all files reviewed, 31 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 336 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7GDf_9nkBYAW12LB8:-MO7GDf_9nkBYAW12LB9:b-2elliq) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L336)):*
> ```cpp
>       {"clusterName", config_->cluster()},
>       {"max_concurrent_requests", cluster_data.max_concurrent_requests},
>       {"type", 3},
> ```

The value here should be "EDS".  The JSON translation for proto enums is a string, not an integer:

https://developers.google.com/protocol-buffers/docs/proto3#json
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 249 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyw-ZIA7JHjJsRmY52:-MO7Ingo1C9EBo-A_9r4:b-nhe0dn) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L249)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I tried moving this but it didn't seem to need XdsClusterResolverLb info like is_xds_uri and server_name_; furthermore, DiscoveryMechanism does not have access to the config directly where as XdsClusterResolverLb does.  So leaving it but updating with index parameter
</blockquote></details>

I suggest changing the `DiscoveryMechanismInterface` ctor to take a ref to the LB policy, rather than doing that in the subclass.  That way, it can access the LB policy's fields, which include `is_xds_uri_`, `server_name_`, and `config_`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 260 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyw3LX0tAae9xw-cbA:-MO7JHS30aQocpfjMYW3:b2nreh6) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L260)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I tried moving this but it didn't seem to need XdsClusterResolverLb info like is_xds_uri and server_name_; furthermore, DiscoveryMechanism does not have access to the config directly where as XdsClusterResolverLb does.  So leaving it but updating with index parameter
</blockquote></details>

Same as above.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 96 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7GirX1UGWuAIaQ3_w:-MO7GirX1UGWuAIaQ3_x:b-usd20j) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L96)):*
> ```cpp
>     return endpoint_picking_policy_;
>   }
>   const std::vector<DiscoveryMechanism>& discovery_mechanisms() const {
> ```

Please move this above the previous two methods, so that the methods are in the same order as the data members.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 121 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7H95DDofrmWa2auys:-MO7H95DDofrmWa2auyt:b-tmj0ug) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L121)):*
> ```cpp
>   // Implemented by EDS and LOGICAL_DNS.
>   //
>   // Contains a watcher object which will get notified for events like
> ```

I think this should say something like the following:

Implementations are responsible for calling the LB policy's OnEndpointChanged(), OnError(), and OnResourceDoesNotExist() methods when the corresponding events occur.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 124 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7HXwm9TqZjeimaV-m:-MO7HXwm9TqZjeimaV-n:b-9f06v7) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L124)):*
> ```cpp
>   // OnEndpointChanged, OnResourceDoesNotExist, and OnError.
>   //
>   // Must implement Shutdown() method to cancel the watches.
> ```

I think you mean `Orphan()`, not `Shutdown()`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 125 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7JL9z7WbwBNFxtXcW:-MO7JL9z7WbwBNFxtXcX:b-c3uls3) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L125)):*
> ```cpp
>   //
>   // Must implement Shutdown() method to cancel the watches.
>   class DiscoveryMechanismInterface
> ```

The `Interface` suffix probably isn't needed here.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 136 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7K9x85z0W8gZjiQF1:-MO7K9x85z0W8gZjiQF2:bkyke26) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L136)):*
> ```cpp
>    private:
>     // Number of priorities this mechanism contributes.
>     uint32_t num_priorities_;
> ```

This is no longer needed, since it's now being tracked in the `DiscoveryMechanismEntry` struct instead.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 193 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7JzAK3sPeH-nxLCIP:-MO7JzAK3sPeH-nxLCIQ:bautbfz) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L193)):*
> ```cpp
>     // Stores its own index in the vector of DiscoveryMechanismInterface.
>     uint32_t index_;
>     EndpointWatcher* watcher_ = nullptr;
> ```

Please add the following comment here:

Note that this is not owned, so this pointer must never be dereferenced.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 225 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7MueK-zahXZfTNNXD:-MO7MueK-zahXZfTNNXE:b-vwxhzh) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L225)):*
> ```cpp
>   void ShutdownLocked() override;
> 
>   void OnEndpointChanged(uint32_t index, XdsApi::EdsUpdate update);
> ```

The type of the index parameter on these methods should be `size_t`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 275 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7JX-R16TDr_G9BLUU:-MO7JX-R16TDr_G9BLUV:bxfm0d9) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L275)):*
> ```cpp
> 
>   // Vector of discovery mechansism entries in priority order.
>   struct DiscoveryMechanismEntry {
> ```

Structs should be defined above methods and data members.  Suggest moving this up to line 196.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 276 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7Jinb0MKh1Hw3gNyD:-MO7Jinb0MKh1Hw3gNyE:b36qso4) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L276)):*
> ```cpp
>   // Vector of discovery mechansism entries in priority order.
>   struct DiscoveryMechanismEntry {
>     // Note that this is not owned, so this pointer must never be dereferenced.
> ```

This comment is incorrect.  An `OrphanablePtr<>` is always owned.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 338 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7KoL_7E-J98omaI72:-MO7KoL_7E-J98omaI73:bd0g3l2) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11 [...]

2020-12-10 07:49 UTC, donnadionne reviewed
addressed all comments, PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MOAc-Y_2R-cPbFXDH-R:b-mgiugg)* status: 1 of 4 files reviewed, 31 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 336 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7GDf_9nkBYAW12LB8:-MO8NZq-6eBx8hdcL83F:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L336)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The value here should be "EDS".  The JSON translation for proto enums is a string, not an integer:

https://developers.google.com/protocol-buffers/docs/proto3#json
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 249 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyw-ZIA7JHjJsRmY52:-MOAEfxPC0UXS_NbLKL-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L249)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest changing the `DiscoveryMechanismInterface` ctor to take a ref to the LB policy, rather than doing that in the subclass.  That way, it can access the LB policy's fields, which include `is_xds_uri_`, `server_name_`, and `config_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 260 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyw3LX0tAae9xw-cbA:-MOAEgNW3ZWBYpy75487:bgrnon1) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L260)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

this method is only called by XdsClusterResolverLb::CreateChildPolicyConfigLocked(), if we move it, then the calling site seems a bit strange indexing into discovery_mechanisms?
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 96 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7GirX1UGWuAIaQ3_w:-MO8Nlw_9C8Q1xI0r9Vw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L96)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this above the previous two methods, so that the methods are in the same order as the data members.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 121 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7H95DDofrmWa2auys:-MO8O7GQBjyRU7Z_V-ug:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L121)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this should say something like the following:

Implementations are responsible for calling the LB policy's OnEndpointChanged(), OnError(), and OnResourceDoesNotExist() methods when the corresponding events occur.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 124 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7HXwm9TqZjeimaV-m:-MO8O7rZ65hGOqq5o-AR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you mean `Orphan()`, not `Shutdown()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 125 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7JL9z7WbwBNFxtXcW:-MO9MQOl65NqcrNjJ0lr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L125)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `Interface` suffix probably isn't needed here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 136 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7K9x85z0W8gZjiQF1:-MO9M8Y-CRJBDitbGTk2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L136)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is no longer needed, since it's now being tracked in the `DiscoveryMechanismEntry` struct instead.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 193 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7JzAK3sPeH-nxLCIP:-MO9Oe049-01rKZn_AfA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L193)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add the following comment here:

Note that this is not owned, so this pointer must never be dereferenced.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 225 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7MueK-zahXZfTNNXD:-MO9TUTL8Ulr4de8W9_W:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L225)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The type of the index parameter on these methods should be `size_t`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 275 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7JX-R16TDr_G9BLUU:-MO9ObLK-3OXopf2VOQn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L275)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Structs should be defined above methods and data members.  Suggest moving this up to line 196.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 276 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7Jinb0MKh1Hw3gNyD:-MO9ObstAHtv4tKpzSVK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L276)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment is incorrect.  An `OrphanablePtr<>` is always owned.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 338 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7KoL_7E-J98omaI72:-MOAYd3XBn1bwaaC2w_Q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f3e4f1977765606812551f7c684a8f744ddf2c11/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L338)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All log messages in this file should start with `[xds_cluster_resolver_lb %p]`, showing the address of the LB policy.  You can log the address of the discovery mechanism as the next thing on the log line.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 549 at r2](https://reviewable.io/reviews/grpc/grpc/24922#-MO7Mmej2n-8boUUzH7J:-MO9TYAA5tXIiD2nye8K:b-896fix) ([raw file](https://github.com/ [...]

2020-12-10 16:09 UTC, markdroth requested changes
This is looking pretty good!  Just a few more edge cases that need to be handled.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MOCPU0O1q3W0oy2rU87:bsao28y)* status: all files reviewed, 8 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 260 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyw3LX0tAae9xw-cbA:-MOCJafi5SGUHyghpTMF:bvfmjle) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L260)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

this method is only called by XdsClusterResolverLb::CreateChildPolicyConfigLocked(), if we move it, then the calling site seems a bit strange indexing into discovery_mechanisms?
</blockquote></details>

I don't understand why that's strange.  There's already a bunch of code in `CreateChildPolicyConfigLocked()` that is looking at attributes of the `DiscoveryMechanism` object.  Why wouldn't it make sense to do the same thing for this attribute?
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 129 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCI4RaDm8nrm79B_a1:-MOCI4RaDm8nrm79B_a2:b-btc1xj) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L129)):*
> ```cpp
>    public:
>     DiscoveryMechanism(RefCountedPtr<XdsClusterResolverLb> parent)
>         : parent_(std::move(parent)){};
> ```

No need for the semicolon.

Also, please add a space before the `{`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 135 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCJQC41E9Th2HiBjT6:-MOCIK68ABGzpL7pjImM:bjyre73) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L135)):*
> ```cpp
>     // Caller must ensure that config_ is set before calling.
>     const absl::string_view GetXdsClusterResolverResourceName(
>         size_t index) const {
> ```

Instead of passing in the `index` parameter here, let's move the `index_` member from the subclass back to the base class, so that we already have that info here without passing it in.

(Sorry for the run-around here -- I know I asked you to move it to the subclass before, but now that we actually need it here, it makes more sense to have it in the base class.)
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 144 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCIc8b-lxQKSAAgZvF:-MOCIc8b-lxQKSAAgZvG:b82uprt) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L144)):*
> ```cpp
>     }
> 
>    protected:
> ```

Data members must be private.  Instead, please add a protected accessor method to give subclasses access.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 339 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCK8E_B6bJM5X80WII:-MOCK8E_B6bJM5X80WIJ:b-o5lec3) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L339)):*
> ```cpp
>     gpr_log(
>         GPR_INFO,
>         "[xds_cluster_resolver_lb %p] discovery mechanism %lu:%p starting xds "
> ```

Instead of `%lu`, I think you'll need to use `PRIuPTR` for portability.

Same thing for all places where you're logging a `size_t`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 578 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCLbZr9xf_DubJBFlK:-MOCLbZr9xf_DubJBFlL:b-hx4m3e) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L578)):*
> ```cpp
>   discovery_mechanisms_[index].drop_config = std::move(update.drop_config);
>   // Update child policy.
>   UpdatePriorityList(std::move(priority_list));
> ```

I think we need to avoid calling this until we've gotten an update from the first discovery mechanism in the list.  In other words, if we get an update for index 1 but have not yet gotten an update for index 0, we should hold off on calling `UpdatePriorityList()`.

I suggest adding a `bool received_update = false` field to `DiscoveryMechanismEntry`, which we set to true when we get an update from that mechanism.  And when we get the first update for mechanism 0, we will need to look at the data for *all* mechanisms to construct the priority list, because we will not have populated the list before that point.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 589 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCM8ebCUHxuzSYPAxH:-MOCM8ebCUHxuzSYPAxI:b-275w7r) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L589)):*
> ```cpp
>   // policy (i.e., we have not yet received data from xds).  Otherwise,
>   // we keep running with the data we had previously.
>   if (child_policy_ == nullptr) {
> ```

I think the behavior here needs to be a little different now.  I think we need to know whether or not we've already received an update from this discovery mechanism (the `received_update` bool in `DiscoveryMechanismEntry` that I suggested above).  If we have, then we just ignore this event.  But if we haven't,  then we should do the same thing as in `OnResourceDoesNotExist()` (i.e., call `OnEndpointChanged(index, XdsApi::EdsUpdate())`).
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 599 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCLKGe7wFEdosSL4S0:-MOCLKGe7wFEdosSL4S1:b2zbh2j) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L599)):*
> ```cpp
> 
> void XdsClusterResolverLb::OnResourceDoesNotExist(size_t index) {
>   if (shutting_down_) return;
> ```

If this is necessary here, why isn't it also necessary in `OnEndpointChanged()` and `OnError()`?


<!-- Sent from Reviewable.io -->

2020-12-11 06:35 UTC, donnadionne reviewed
addressed all comments, PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MOFUsdB0rKCcLJumVY0:bab5nrk)* status: all files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 260 at r1](https://reviewable.io/reviews/grpc/grpc/24922#-MNyw3LX0tAae9xw-cbA:-MOFOTLi7sWkhbgwODt0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3324840023ce1c435b819d04304b53b3defd8d63/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L260)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't understand why that's strange.  There's already a bunch of code in `CreateChildPolicyConfigLocked()` that is looking at attributes of the `DiscoveryMechanism` object.  Why wouldn't it make sense to do the same thing for this attribute?
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 129 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCI4RaDm8nrm79B_a1:-MOFUrRVEAJvAmI6wJcv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L129)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the semicolon.

Also, please add a space before the `{`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 135 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCJQC41E9Th2HiBjT6:-MOFORB07lBsuI6DR5by:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L135)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of passing in the `index` parameter here, let's move the `index_` member from the subclass back to the base class, so that we already have that info here without passing it in.

(Sorry for the run-around here -- I know I asked you to move it to the subclass before, but now that we actually need it here, it makes more sense to have it in the base class.)
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 144 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCIc8b-lxQKSAAgZvF:-MOFOS3wBwDXqJmLJpMt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Data members must be private.  Instead, please add a protected accessor method to give subclasses access.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 339 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCK8E_B6bJM5X80WII:-MOFUqDHBXabURb8t9Qr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L339)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of `%lu`, I think you'll need to use `PRIuPTR` for portability.

Same thing for all places where you're logging a `size_t`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 578 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCLbZr9xf_DubJBFlK:-MOFHA2O0wWhVXWaRxr_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L578)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we need to avoid calling this until we've gotten an update from the first discovery mechanism in the list.  In other words, if we get an update for index 1 but have not yet gotten an update for index 0, we should hold off on calling `UpdatePriorityList()`.

I suggest adding a `bool received_update = false` field to `DiscoveryMechanismEntry`, which we set to true when we get an update from that mechanism.  And when we get the first update for mechanism 0, we will need to look at the data for *all* mechanisms to construct the priority list, because we will not have populated the list before that point.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 589 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCM8ebCUHxuzSYPAxH:-MOFGUOkBlH7iBEd8Ffq:b-6nwfte) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L589)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the behavior here needs to be a little different now.  I think we need to know whether or not we've already received an update from this discovery mechanism (the `received_update` bool in `DiscoveryMechanismEntry` that I suggested above).  If we have, then we just ignore this event.  But if we haven't,  then we should do the same thing as in `OnResourceDoesNotExist()` (i.e., call `OnEndpointChanged(index, XdsApi::EdsUpdate())`).
</blockquote></details>

fixed; but for index 0, i think we do need to put the channel in TRANSIENT FAILURE since we have no child to do it in this case.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 599 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCLKGe7wFEdosSL4S0:-MOFGnf89guH1Owx4Zdk:b-2dhb88) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L599)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If this is necessary here, why isn't it also necessary in `OnEndpointChanged()` and `OnError()`?
</blockquote></details>

i tested and it is necessary elsewhere too.  added.  


<!-- Sent from Reviewable.io -->

2020-12-11 16:00 UTC, markdroth requested changes
This is getting close!  Only two noteworthy comments remaining: one about not storing duplicate copies of the priority list, and another about not having a special case for index 0 reporting an error.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MOHWxRo38Mie7s2JIan:bvsskuz)* status: all files reviewed, 11 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 589 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCM8ebCUHxuzSYPAxH:-MOHSLZ085nK6C_hsZ4S:bvjmldl) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L589)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

fixed; but for index 0, i think we do need to put the channel in TRANSIENT FAILURE since we have no child to do it in this case.
</blockquote></details>

I don't think we need to special-case index 0.  If we just send an empty update for it, then the child for this priority will have no endpoints, so the child will report TRANSIENT_FAILURE anyway.

Also, special-casing index 0 is the wrong thing here, because if we have received an update for index 1, then we should create the child policy with an empty priority list for index 0, so that the priority policy can fail over to priority 1.

I think we should just remove this special case.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 155 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHLzsN3cNt5VoQZWvi:-MOHLzsN3cNt5VoQZWvj:b-1cnel7) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L155)):*
> ```cpp
> 
>    protected:
>     RefCountedPtr<XdsClusterResolverLb> parent() const { return parent_; }
> ```

It looks like most places where this is called, the caller does not need its own ref, so by returning a `RefCountedPtr<>`, we're needlessly reffing and unreffing this object every time this method is called.  Instead, let's return a raw pointer.  (If there are any callers that do need to take a ref, they can do so by calling the object's `Ref()` method.)
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 226 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHNJ2m-VpE60scyRel:-MOHNJ2m-VpE60scyRem:b7ffkpa) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L226)):*
> ```cpp
>     // the number of priorities in priority_list_.)
>     uint32_t num_priorities = 0;
>     // The latest update from this discovery mechanism.
> ```

The priority list should be populated only as a temporary holding spot when we get an update for a mechanism that has not yet been added to the combined priority list.  Once we do add the pending update to the combined priority list, we should remove it from here.  Otherwise, we're basically storing all of the data twice (once with each mechanism and again in the combined list), which is going to be very expensive when there are a really large number of endpoints.

I think we should have two separate fields here:

```
RefCountedPtr<XdsApi::EdsUpdate::DropConfig> drop_config;
// Populated only when an update has been delivered by the mechanism
// but has not yet been applied to the LB policy's combined priority_list_.
absl::optional<XdsApi::EdsUpdate::PriorityList> pending_priority_list;
```
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 297 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHLhNi3IB3rI5YhPhf:-MOHLhNi3IB3rI5YhPhg:b-wow1og) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L297)):*
> ```cpp
> 
>   OrphanablePtr<LoadBalancingPolicy> child_policy_;
> };  // namespace
> ```

This comment is incorrect -- this isn't the end of a namespace, it's the end of a class.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 341 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHLwsm6ZxSwufl-kz7:-MOHLwsm6ZxSwufl-kz8:b-gx1xn4) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L341)):*
> ```cpp
> XdsClusterResolverLb::EdsDiscoveryMechanism::EdsDiscoveryMechanism(
>     RefCountedPtr<XdsClusterResolverLb> parent, size_t index)
>     : DiscoveryMechanism(parent, index) {
> ```

`std::move(parent)`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 346 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHLnKf0KRyoOnfTkRb:-MOHLnKf0KRyoOnfTkRc:b-czwc4w) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L346)):*
> ```cpp
>             "[xds_cluster_resolver_lb %p] discovery mechanism %" PRIuPTR
>             ":%p starting xds "
>             "watch for %s",
> ```

This can be combined with the string on the previous line.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 362 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHMRH7ASUKKU6hucvS:-MOHMRH7ASUKKU6hucvT:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L362)):*
> ```cpp
>             "[xds_cluster_resolver_lb %p] discovery mechanism %" PRIuPTR
>             ":%p cancelling "
>             "xds watch for %s",
> ```

Same here.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 564 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHVh2DAKCfSLcUlOvY:-MOHVh2DAKCfSLcUlOvZ:bf6t26b) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L564)):*
> ```cpp
>   // have a child in which to create the xds_cluster_impl policy.  This ensures
>   // that we properly handle the case of a discovery mechanism dropping 100% of
>   // calls.
> ```

Please add "and the OnError() and OnResourceDoesNotExist() cases".
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 567 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHMjDV5sGAyTsHWQlH:-MOHMjDV5sGAyTsHWQlI:b-jwci45) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L567)):*
> ```cpp
>   if (update.priorities.empty()) update.priorities.emplace_back();
>   // Save this latest update.
>   discovery_mechanisms_[index].update = std::move(update);
> ```

As mentioned above, we do not want to always store the updated priority list here; we want to do this only in the case where this update is for index 1 or greater and we have not yet received an update for index 0.  I think the logic should be something like this:

```
discovery_mechanisms_[index].drop_config = std::move(update.drop_config);
discovery_mechanisms_[index].pending_priority_list = std::move(update.priority_list);
discovery_mechanisms_[index].first_update_received = true;
if (!discovery_mechanisms_[0].first_update_received) {
  // We have not yet received an update for index 0, so wait until that
  // happens to create the child policy.
  return;
}
// Construct new priority list.
XdsApi::EdsUpdate::PriorityList priority_list;
size_t priority_index = 0;
for (DiscoveryMechanismEntry& mechanism : discovery_mechanisms_) {
  // If the mechanism has a pending update, use that.
  // Otherwise, use the priorities that it previously contributed to the
  // combined list.
  if (mechanism.pending_priority_list.has_value()) {
    priority_list.insert(priority_list.end(),
                         mechanism.pending_priority_list->begin(),
                         mechanis [...]

2020-12-14 06:37 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922)* status: all files reviewed, 11 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 589 at r4](https://reviewable.io/reviews/grpc/grpc/24922#-MOCM8ebCUHxuzSYPAxH:-MOItkPHD7hIiJQBahny:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/610e9515fe3f78873af30ca926e3f688dce56ff6/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L589)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need to special-case index 0.  If we just send an empty update for it, then the child for this priority will have no endpoints, so the child will report TRANSIENT_FAILURE anyway.

Also, special-casing index 0 is the wrong thing here, because if we have received an update for index 1, then we should create the child policy with an empty priority list for index 0, so that the priority policy can fail over to priority 1.

I think we should just remove this special case.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 155 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHLzsN3cNt5VoQZWvi:-MOJ86bL3vS_5l-QUxAk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L155)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like most places where this is called, the caller does not need its own ref, so by returning a `RefCountedPtr<>`, we're needlessly reffing and unreffing this object every time this method is called.  Instead, let's return a raw pointer.  (If there are any callers that do need to take a ref, they can do so by calling the object's `Ref()` method.)
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 226 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHNJ2m-VpE60scyRel:-MOJ888Y4x9Towb_3ypA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L226)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The priority list should be populated only as a temporary holding spot when we get an update for a mechanism that has not yet been added to the combined priority list.  Once we do add the pending update to the combined priority list, we should remove it from here.  Otherwise, we're basically storing all of the data twice (once with each mechanism and again in the combined list), which is going to be very expensive when there are a really large number of endpoints.

I think we should have two separate fields here:

```
RefCountedPtr<XdsApi::EdsUpdate::DropConfig> drop_config;
// Populated only when an update has been delivered by the mechanism
// but has not yet been applied to the LB policy's combined priority_list_.
absl::optional<XdsApi::EdsUpdate::PriorityList> pending_priority_list;
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 297 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHLhNi3IB3rI5YhPhf:-MOJ8hCiAbVtlq8mQrDs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L297)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment is incorrect -- this isn't the end of a namespace, it's the end of a class.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 341 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHLwsm6ZxSwufl-kz7:-MOUTpk92iLRunqkPcu2:br8nlt8) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L341)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move(parent)`
</blockquote></details>

i hope to log the pointer value below so i need a copy
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 346 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHLnKf0KRyoOnfTkRb:-MOUU-2PA0IJeaTLspRZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L346)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be combined with the string on the previous line.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 362 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHMRH7ASUKKU6hucvS:-MOUU-wZ3Qkitq877M2u:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L362)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 564 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHVh2DAKCfSLcUlOvY:-MOUUIPyEqnfIaw67_2Z:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L564)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add "and the OnError() and OnResourceDoesNotExist() cases".
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 567 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHMjDV5sGAyTsHWQlH:-MOJ6CgqE4aI3SF3I1H6:b-7rl0kd) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L567)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned above, we do not want to always store the updated priority list here; we want to do this only in the case where this update is for index 1 or greater and we have not yet received an update for index 0.  I think the logic should be something like this:

```
discovery_mechanisms_[index].drop_config = std::move(update.drop_config);
discovery_mechanisms_[index].pending_priority_list = std::move(update.priority_list);
discovery_mechanisms_[index].first_update_received = true;
if (!discovery_mechanisms_[0].first_update_received) {
  // We have not yet received an update for index 0, so wait until that
  // happens to create the child policy.
  return;
}
// Construct new priority list.
XdsApi::EdsUpdate::PriorityList priority_list;
size_t priority_index = 0;
for (DiscoveryMechanismEntry& mechanism : discovery_mechanisms_) {
  // If the mechanism has a pending update, use that.
  // Otherwise, use the priorities that it previously contributed to the
  // combined list.
  if (mechanism.pending_priority_list.has_value()) {
    priority_list.insert(priority_list.end(),
                         mechanism.pending_priority_list->begin(),
                         mechanism.pending_priority_list->end());
    priority_index += mechanism.num_priorities;
    mechanism.num_priorities = mechanism.pending_priority_list.size();
    mechanism.pending_priority_list.reset();
  } else {
    priority_list.insert(priority_list.end(),
                         priority_list_.begin() + priority_index,
                         priority_list_.begin() + priority_index + mechanism.num_priorities);
    priority_index += mechanism.num_priorities;
  }
}
```
</blockquote></details>

done
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 621 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHVaJ-C5ebPTesSzDd:-MOUUUNI5Sr9lw_MWt0g:b- [...]

2020-12-14 06:38 UTC, donnadionne reviewed
Fixed; PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MOUy6KkCu4YMQTENLFV:baauzxx)* status: all files reviewed, 11 unresolved discussions (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2020-12-14 16:39 UTC, markdroth requested changes
This looks really good!  Just a couple of minor nits remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MOX6fDbBPC1wJlREG4i:b7m8sie)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 341 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHLwsm6ZxSwufl-kz7:-MOX5Cka5X0L9epkoCEp:bgejcn6) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L341)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i hope to log the pointer value below so i need a copy
</blockquote></details>

You're logging the pointer value below by calling the base class's `parent()` method, so you don't need the local variable to be valid for that.

The only place I see that you're using the local variable is the last statement in this function, and that can be changed to use `parent()` instead.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 611 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOX6LB0E6K6R10AnvYX:-MOX6LB0E6K6R10AnvYY:bt6c9on) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L611)):*
> ```cpp
>   discovery_mechanisms_[index].num_priorities =
>       discovery_mechanisms_[index].update.priorities.size();
>   // Update child policy.
> ```

Please keep this comment.


<!-- Sent from Reviewable.io -->

2020-12-14 20:49 UTC, donnadionne reviewed
fixed!  and did the move of the files as well.  PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MOY-q3P4OofgFcX_GkG:bgfs3ju)* status: all files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 341 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOHLwsm6ZxSwufl-kz7:-MOY-nTc-Qh2hFNe107p:b-7ql1td) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L341)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You're logging the pointer value below by calling the base class's `parent()` method, so you don't need the local variable to be valid for that.

The only place I see that you're using the local variable is the last statement in this function, and that can be changed to use `parent()` instead.
</blockquote></details>

fixed
___
*[src/core/ext/filters/client_channel/lb_policy/xds/eds.cc, line 611 at r5](https://reviewable.io/reviews/grpc/grpc/24922#-MOX6LB0E6K6R10AnvYX:-MOY-p3EEmHSbRnqCgf8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5cc0cb8c262da90204cfaf251bb8beb24508d9c7/src/core/ext/filters/client_channel/lb_policy/xds/eds.cc#L611)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please keep this comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-14 21:08 UTC, markdroth approved these changes
This looks great!  There are a couple of remainig nits, but feel free to merge once those are resolved.

> Reviewed 21 of 21 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24922#-:-MOY4KEI3vHeEt1vM6-O:b5v4a2d)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 50 at r7](https://reviewable.io/reviews/grpc/grpc/24922#-MOY42ch0kbMnQMbC-0c:-MOY42ch0kbMnQMbC-0d:b50uf44) ([raw file](https://github.com/grpc/grpc/blob/d0f528d16dceed1e103a7dccdf07239770f9f29e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L50)):*
> ```cpp
> namespace grpc_core {
> 
> TraceFlag grpc_lb_xds_cluster_resolver_trace(false, "xds_cluster_resolver_lb");
> ```

Please also update this name in doc/environment_variables.md.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 132 at r7](https://reviewable.io/reviews/grpc/grpc/24922#-MOY3nVF5vl2KSRpnlZF:-MOY3nVF5vl2KSRpnlZG:b-hithny) ([raw file](https://github.com/grpc/grpc/blob/d0f528d16dceed1e103a7dccdf07239770f9f29e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L132)):*
> ```cpp
>         size_t index)
>         : parent_(std::move(xds_cluster_resolver_lb)), index_(index) {}
>     ~DiscoveryMechanism() override{};
> ```

If the dtor isn't actually doing anything, then it's not necessary to override at all.


<!-- Sent from Reviewable.io -->

2020-12-15 02:12 UTC, merged