Xds server cont
grpc/grpc pull request #25008
Opened 2020-12-15 22:29 UTC by yashykt

2021-01-08 00:48 UTC, markdroth requested changes
This looks like a great start!

The only really significant comment is the one about creating the security connector on a per-connection basis without plumbing it through the handshaker API.

Please let me know if you have any questions.  Thanks!

> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008#-:-MQUSfrx5N6_yNPsWevY:b-g96ti7)* status: all files reviewed, 35 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTYewO1h-1X7Gq-vRJ:-MQTYewO1h-1X7Gq-vRK:bb3rl3) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/transport/chttp2/server/chttp2_server.cc#L194)):*
> ```cpp
>       interested_parties_(grpc_pollset_set_create()) {
>   grpc_pollset_set_add_pollset(interested_parties_, accepting_pollset_);
>   grpc_error* error = HandshakerRegistry::AddHandshakers(
> ```

It looks like the reason for the handshaker API change is to move the security connector creation into the security handshaker's factory.  However, that seems like a fairly invasive change (as evidenced by the number of files that needed to be changed in this PR, and I believe it would also require internal changes), and it doesn't really seem like a natural conceptual fit, because creating the security connector for the connection doesn't really have anything to do with adding handshakers.

Instead, I suggest plumbing in a function of the following type:

```
// A function to modify channel args for an individual connection.
// Takes ownership of the args.  Caller takes ownership of returned args.
// On failure, the error parameter will be set.
using Chttp2ServerConnectionArgModifier = std::function<grpc_channel_args*(grpc_channel_args*, grpc_error**)>;
```

In server_secure_chttp2.cc, we can pass in a function that will create the security connector and add it to the args.  In server_chttp2.cc (the insecure case), where no security connector is needed, we can use a no-op function that just returns the args that are passed to it.

The code here can invoke that function to modify before populating the handshake manager.

I think this approach will accomplish the same thing in a much cleaner and less invasive way.
___
*[src/core/ext/xds/xds_api.h, line 282 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTpiUC7Brl3UuWlzuS:-MQTpiUC7Brl3UuWlzuT:b-vqsopr) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.h#L282)):*
> ```objc
>   // TODO(roth): When we can use absl::variant<>, consider using that
>   // here, to enforce the fact that only one of the two fields can be set.
>   struct LdsUpdate {
> ```

I think this struct should now have its own `ToString()` method, and we should use that method here:

https://github.com/grpc/grpc/blob/e745f8cb558798f1c8b91baa42d46228a9d4a0c4/src/core/ext/xds/xds_client.cc#L884
___
*[src/core/ext/xds/xds_api.cc, line 625 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQToff08YEk2MXZod38:-MQToff08YEk2MXZod39:b-q1k06p) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L625)):*
> ```cpp
> 
> bool XdsApi::DownstreamTlsContext::Empty() const {
>   return common_tls_context.Empty();
> ```

Should it also be considered non-empty if `require_client_certificate` is set?
___
*[src/core/ext/xds/xds_api.cc, line 1545 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUBJlD3mvmpHKliDXe:-MQUBJlD3mvmpHKliDXf:bl0ciu5) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1545)):*
> ```cpp
> grpc_error* LdsResponseParseClient(
>     XdsClient* client, TraceFlag* tracer, upb_symtab* symtab, upb_arena* arena,
>     XdsApi::LdsUpdate& lds_update,
> ```

`lds_update` is an output parameter, so it should be passed as a pointer instead of a reference, and it should be the last parameter.
___
*[src/core/ext/xds/xds_api.cc, line 1615 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUA0nT5FuR8R-6wiIz:-MQUA0nT5FuR8R-6wiJ-:bl0ciu5) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1615)):*
> ```cpp
> 
> grpc_error* LdsResponseParseServer(
>     upb_arena* arena, XdsApi::LdsUpdate& lds_update,
> ```

`lds_update` is an output parameter, so it should be passed as a pointer instead of a reference, and it should be the last parameter.
___
*[src/core/ext/xds/xds_api.cc, line 1619 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQU7wYWB2QSEQjTn-0I:-MQU7wYX6zJ0dDLFGp4I:bwv4uso) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1619)):*
> ```cpp
>     const std::string& listener_name,
>     const envoy_config_core_v3_Address* address) {
>   // Get address from listener name
> ```

As per discussion in the gRFC, I think we've decided not to check this, since we will be using a template from the bootstrap file to determine the resource name, which means that we can't know exactly what format the name will be in.  So let's just remove this check.
___
*[src/core/ext/xds/xds_api.cc, line 1642 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQU8Bjj8AfjMOzdzt7b:-MQU8Bjj8AfjMOzdzt7c:b8n03zz) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1642)):*
> ```cpp
>         "Addresses from listener name and listener address do not match");
>   }
>   // Right now, we are supporting and expecting only one entry in filter_chains.
> ```

As per the gRFC, we should actually look at every entry in `filter_chains` use the first one that matches, or else use `default_filter_chain` instead.
___
*[src/core/ext/xds/xds_api.cc, line 1650 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTp66L7TM0aZ2pgnA_:-MQTp66L7TM0aZ2pgnAa:b-aekg4v) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1650)):*
> ```cpp
>         "Only one filter_chain supported.");
>   }
>   // Expect to find "h2" as an application protocol
> ```

I believe the gRFC says that we aren't supposed to look at this field at all.
___
*[src/core/ext/xds/xds_api.cc, line 1755 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTqjhQ4suErwSlIAza:-MQTqjhQ4suErwSlIAzb:bqc9ju6) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1755)):*
> ```cpp
>     }
>     XdsApi::LdsUpdate& lds_update = (*lds_update_map)[listener_name];
>     // Get api_listener and decode it to http_connection_manager.
> ```

I think this comment should say something like "Check whether it's a client or server listener.".
___
*[src/core/ext/xds/xds_certificate_provider.h, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUBq7DEad_RpPcRbab:-MQUBq7DEad_RpPcRbac:bvw2g99) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_certificate_provider.h#L75)):*
> ```objc
> 
>   void set_require_client_certificates(bool require_client_certificates) {
>     require_client_certificates_ = require_client_certificates;
> ```

If `require_client_certificates_` is an atomic, don't the setter and getter methods need to use atomic ops to access it?
___
*[src/core/ext/xds/xds_certificate_provider.h, line 118 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUBelU3TyN7jcw_lqB:-MQUBelU3TyN7jcw_lqC:b-jygwor) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_certificate_provider.h#L118)):*
> ```objc
>   std::vector<XdsApi::StringMatcher> san_matchers_;
>   // Not guarded by mu_ to avoid deadlocks.
>   std::atomic<bool> require_client_certificates_{false};
> ```

Please use `Atomic<bool>` instead.
___
*[src/core/ext/xds/xds_server [...]

2021-01-08 19:28 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008)* status: 18 of 34 files reviewed, 35 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTYewO1h-1X7Gq-vRJ:-MQYSja0D8oD8SBIl2b8:b5s46e9) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/transport/chttp2/server/chttp2_server.cc#L194)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like the reason for the handshaker API change is to move the security connector creation into the security handshaker's factory.  However, that seems like a fairly invasive change (as evidenced by the number of files that needed to be changed in this PR, and I believe it would also require internal changes), and it doesn't really seem like a natural conceptual fit, because creating the security connector for the connection doesn't really have anything to do with adding handshakers.

Instead, I suggest plumbing in a function of the following type:

```
// A function to modify channel args for an individual connection.
// Takes ownership of the args.  Caller takes ownership of returned args.
// On failure, the error parameter will be set.
using Chttp2ServerConnectionArgModifier = std::function<grpc_channel_args*(grpc_channel_args*, grpc_error**)>;
```

In server_secure_chttp2.cc, we can pass in a function that will create the security connector and add it to the args.  In server_chttp2.cc (the insecure case), where no security connector is needed, we can use a no-op function that just returns the args that are passed to it.

The code here can invoke that function to modify before populating the handshake manager.

I think this approach will accomplish the same thing in a much cleaner and less invasive way.
</blockquote></details>

I like it! and I think there was a related issue around where the security connector is created. Looks like the same security connector needs to be shared across connections to allow for ssl reuse. 
___
*[src/core/ext/xds/xds_api.cc, line 625 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQToff08YEk2MXZod38:-MQYDX1IDZ-BERK8jgvH:bq9k7qu) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L625)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Should it also be considered non-empty if `require_client_certificate` is set?
</blockquote></details>

Yes, `require_client_certificate` is of no consequence if there is no way to verify client certificates.
___
*[src/core/ext/xds/xds_api.cc, line 1545 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUBJlD3mvmpHKliDXe:-MQYRR4F8mlBjQUs65-T:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1545)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`lds_update` is an output parameter, so it should be passed as a pointer instead of a reference, and it should be the last parameter.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1615 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUA0nT5FuR8R-6wiIz:-MQYRRuaBEtXdU66iwhX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1615)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`lds_update` is an output parameter, so it should be passed as a pointer instead of a reference, and it should be the last parameter.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1619 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQU7wYWB2QSEQjTn-0I:-MQYRSp_Be6Wlx8diPF6:ba3dfob) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1619)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per discussion in the gRFC, I think we've decided not to check this, since we will be using a template from the bootstrap file to determine the resource name, which means that we can't know exactly what format the name will be in.  So let's just remove this check.
</blockquote></details>

Removed
___
*[src/core/ext/xds/xds_api.cc, line 1642 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQU8Bjj8AfjMOzdzt7b:-MQYRUVg2qENUKfuAfjk:bq1kp6j) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1642)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per the gRFC, we should actually look at every entry in `filter_chains` use the first one that matches, or else use `default_filter_chain` instead.
</blockquote></details>

I agree that that's what we should be doing but I'm not sure our current infrastructure supports that. Let me confirm this.
___
*[src/core/ext/xds/xds_api.cc, line 1650 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTp66L7TM0aZ2pgnA_:-MQYRb390UlMnST5FsjG:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1650)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I believe the gRFC says that we aren't supposed to look at this field at all.
</blockquote></details>

Removed.
___
*[src/core/ext/xds/xds_certificate_provider.h, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUBq7DEad_RpPcRbab:-MQYHete3WtOL2jw8Qmw:bwwlsoh) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_certificate_provider.h#L75)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If `require_client_certificates_` is an atomic, don't the setter and getter methods need to use atomic ops to access it?
</blockquote></details>

std::atomic is convenient that way. You don't need to use explicit Store/Load
___
*[src/core/ext/xds/xds_certificate_provider.h, line 118 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUBelU3TyN7jcw_lqB:-MQYHOxBD_jk4vbpwMrD:b-fkvmoh) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_certificate_provider.h#L118)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `Atomic<bool>` instead.
</blockquote></details>

Do we want to avoid using std::atomic?
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 102 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUE-xoDueCQvxVWaMZ:-MQYHr57DKAV-Owe09q7:b-qg8iog) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_server_config_fetcher.cc#L102)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should just use `LdsUpdate::ToString()` (which doesn't currently exist, but should).
</blockquote></details>

This is slightly awkward since not only fields matter to the server, but I guess that's fine
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 110 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUEqdd4cTeTV6_s8a_:-MQYRn0P5-tOeY0KCBE3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_server_config_fetcher.cc#L110)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should probably just call `OnError()`, since we'll want to handle it the same way (including notifying the application somehow when we eventually address that TODO).
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 147 at r1](https://reviewable.io [...]

2021-01-11 18:02 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008)* status: 17 of 33 files reviewed, 35 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 282 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTpiUC7Brl3UuWlzuS:-MQYdhfNEz4rXwW0xqWw:b-57yt1) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.h#L282)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this struct should now have its own `ToString()` method, and we should use that method here:

https://github.com/grpc/grpc/blob/e745f8cb558798f1c8b91baa42d46228a9d4a0c4/src/core/ext/xds/xds_client.cc#L884
</blockquote></details>

It seems a bit awkward to have 
___
*[src/core/ext/xds/xds_api.cc, line 1755 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTqjhQ4suErwSlIAza:-MQmb7g0DvUrrsHNzceR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1755)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this comment should say something like "Check whether it's a client or server listener.".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-11 20:22 UTC, markdroth requested changes
This looks pretty good!  I think the security connector creation still needs a bit of work.

Please let me know if you have any questions.  Thanks!

> Reviewed 12 of 21 files at r2, 1 of 2 files at r3, 6 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008#-:-MQn649hDo4INVD4cjxr:btj888d)* status: all files reviewed, 15 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTYewO1h-1X7Gq-vRJ:-MQmf_MBEvzuZ_foM9Os:b6pc84q) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/transport/chttp2/server/chttp2_server.cc#L194)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I like it! and I think there was a related issue around where the security connector is created. Looks like the same security connector needs to be shared across connections to allow for ssl reuse. 
</blockquote></details>

If we lose SSL state when switching security connectors, then that implies that we'll lose this state every time we get an LDS update.  Is that going to cause any problems?
___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2.cc, line 32 at r3](https://reviewable.io/reviews/grpc/grpc/25008#-MQmafH93WvkVSMFKGmL:-MQmafHAANVR-2XLrp75:bjmqxhs) ([raw file](https://github.com/grpc/grpc/blob/da0a1fb31516a868a7dfe2d99661707f3a069729/src/core/ext/transport/chttp2/server/insecure/server_chttp2.cc#L32)):*
> ```cpp
> namespace {
> 
> grpc_channel_args* connection_args_modifier(grpc_channel_args* args,
> ```

Please call this `ModifyArgsForConnection()`.
___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 43 at r3](https://reviewable.io/reviews/grpc/grpc/25008#-MQmai3UCBlQE7znp-EX:-MQmai3VBKmjlHphm_DH:b-orvcc6) ([raw file](https://github.com/grpc/grpc/blob/da0a1fb31516a868a7dfe2d99661707f3a069729/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L43)):*
> ```cpp
> namespace {
> 
> grpc_channel_args* connection_args_modifier(grpc_channel_args* args,
> ```

`ModifyArgsForConnection()`
___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 87 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmef2LB21UQ-PKcoWk:-MQmef2LB21UQ-PKcoWl:bak02dx) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L87)):*
> ```cpp
>     goto done;
>   }
>   if (server->core_server->config_fetcher() != nullptr) {
> ```

This approach would mean that callers are required to call `grpc_server_set_config_fetcher()` before calling `grpc_server_add_secure_http2_port()`.  I don't think there is currently any such API requirement, and it seems better not to add that requirement.  In general, the API for servers has always been that you can set all the parameters in any order, and nothing actually happens to put all of those parameters together until you call `grpc_server_start()`.

Given this, I think it would be better to create the security connector via the connection arg modifier function even if there is no config fetcher.
___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 114 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmd2pm9lp7qYFUoiCT:-MQmd2pm9lp7qYFUoiCU:bh1w4w3) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L114)):*
> ```cpp
> done:
>   sc.reset(DEBUG_LOCATION, "server");
> ```

Please remove blank line.
___
*[src/core/ext/xds/xds_api.h, line 282 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTpiUC7Brl3UuWlzuS:-MQmgM8CATBKgt97kNWb:bdrrhd2) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.h#L282)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

It seems a bit awkward to have 
</blockquote></details>

I assume you meant to finish that sentence, but I'm not sure what the end was going to be. :)

Anyway, this looks good.
___
*[src/core/ext/xds/xds_api.cc, line 642 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmgjDL9HB9RDP4YY_m:-MQmgjDL9HB9RDP4YY_n:bkk7mpb) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/ext/xds/xds_api.cc#L642)):*
> ```cpp
>         absl::StrFormat("route_config_name=%s", route_config_name.c_str()));
>   }
>   contents.push_back(absl::StrFormat("http_max_stream_duration=%s",
> ```

How about adding a `ListenerType` enum to the `LdsUpdate` struct, so that we can differentiate between TCP listeners and HTTP API listeners?  That way, we can include only the relevant fields for each type.
___
*[src/core/ext/xds/xds_certificate_provider.h, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUBq7DEad_RpPcRbab:-MQmlVLc8frCv9TrpmO5:b-2n81vl) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_certificate_provider.h#L75)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

std::atomic is convenient that way. You don't need to use explicit Store/Load
</blockquote></details>

What memory order gets used in this case for setting and getting?  Is it the one we want?
___
*[src/core/ext/xds/xds_certificate_provider.h, line 118 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUBelU3TyN7jcw_lqB:-MQmlakH0ntUms-OcJ6Y:bcmcvp4) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_certificate_provider.h#L118)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Do we want to avoid using std::atomic?
</blockquote></details>

Historically, we have preferred to use our own `Atomic<>` API.  But it may be that there's less reason for that now that we can use STL.

I suggest checking with Esun and Soheil to see what they think about this.  If everyone is okay with changing our code to directly use `std::atomic<>`, then we can probably just get rid of our own `Atomic<>` API.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 102 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUE-xoDueCQvxVWaMZ:-MQmbSzJEY33PV4W1VVz:blkm5cf) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_server_config_fetcher.cc#L102)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

This is slightly awkward since not only fields matter to the server, but I guess that's fine
</blockquote></details>

I assume that was meant to say "none of the other fields".

I think that `LdsUpdate::ToString()` should report different fields depending on whether it's a TCP listener or an API listener.  So this should wind up being basically right for the server as well as the client.
___
*[src/core/lib/security/transport/security_handshaker.cc, line 27 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmcSCL1BejH4or2cGI:-MQmcSCL1BejH4or2cGJ:bav9om4) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/lib/security/transport/security_handshaker.cc#L27)):*
> ```cpp
> #include <limits>
> 
> #include "absl/strings/str_cat.h"
> ```

No longer needed.
___
*[src/core/lib/security/transport/security_handshaker.cc, line 533 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmcENvASAUuyhQBE_u:-MQmcENvASAUuyhQBE_v:bsvn5lj) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/lib/security/transport/security_handshaker.cc#L533)):*
> ```cpp
>                       HandshakeManager* handshake_mgr) override {
>     // Add the security connector handshakers
>     grpc_server_credentials* creds = grpc_find_server_cre [...]

2021-01-11 21:54 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008)* status: 25 of 33 files reviewed, 15 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTYewO1h-1X7Gq-vRJ:-MQn86E0AWYn39sVvxiV:b-u3bgag) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/transport/chttp2/server/chttp2_server.cc#L194)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we lose SSL state when switching security connectors, then that implies that we'll lose this state every time we get an LDS update.  Is that going to cause any problems?
</blockquote></details>

I don't believe that is going to be an issue. On the other hand, I do believe it would be a good to have if we can somehow share the SSL state between security connectors that did not have any relevant change. @zhenlian @jiangtaoli2016 
___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2.cc, line 32 at r3](https://reviewable.io/reviews/grpc/grpc/25008#-MQmafH93WvkVSMFKGmL:-MQnN2ptDkvm5W4Dyvs8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/da0a1fb31516a868a7dfe2d99661707f3a069729/src/core/ext/transport/chttp2/server/insecure/server_chttp2.cc#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `ModifyArgsForConnection()`.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 43 at r3](https://reviewable.io/reviews/grpc/grpc/25008#-MQmai3UCBlQE7znp-EX:-MQnN4N7009KAqklRv8y:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/da0a1fb31516a868a7dfe2d99661707f3a069729/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`ModifyArgsForConnection()`
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 87 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmef2LB21UQ-PKcoWk:-MQn8gV4AR9kW2jO6h36:b-ggyiy5) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L87)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This approach would mean that callers are required to call `grpc_server_set_config_fetcher()` before calling `grpc_server_add_secure_http2_port()`.  I don't think there is currently any such API requirement, and it seems better not to add that requirement.  In general, the API for servers has always been that you can set all the parameters in any order, and nothing actually happens to put all of those parameters together until you call `grpc_server_start()`.

Given this, I think it would be better to create the security connector via the connection arg modifier function even if there is no config fetcher.
</blockquote></details>

This is the workaround to the problem of reloading ssl creds that we discussed on Friday. In an earlier version of the code, I had tried creating the security connector with the connection arg modifier even when there is no config fetcher but that ran into issues with h2_ssl_cred_reload.cc which assumes that there is only one security connector. After we decide on how the SSL creds fetcher API needs to look like in the future, we can clean this up, but in the mean time since this is an experimental Core API, I think it should be fine for now. What do you think?
___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 114 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmd2pm9lp7qYFUoiCT:-MQnN59c2vUR9hS8O4yl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L114)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank line.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 282 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTpiUC7Brl3UuWlzuS:-MQn9n1n8kONf6tNDSOn:bkomp1j) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.h#L282)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume you meant to finish that sentence, but I'm not sure what the end was going to be. :)

Anyway, this looks good.
</blockquote></details>

Haha! It was supposed to - "It seems a bit awkward to have client specific fields in the server listener and vice versa"
___
*[src/core/ext/xds/xds_api.cc, line 642 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmgjDL9HB9RDP4YY_m:-MQnN9v86EZHnIm4kuQ-:b-896fja) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/ext/xds/xds_api.cc#L642)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about adding a `ListenerType` enum to the `LdsUpdate` struct, so that we can differentiate between TCP listeners and HTTP API listeners?  That way, we can include only the relevant fields for each type.
</blockquote></details>

Done!
___
*[src/core/ext/xds/xds_certificate_provider.h, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUBq7DEad_RpPcRbab:-MQnAFYA-gDH6vK9zu2u:b-j1caej) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_certificate_provider.h#L75)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What memory order gets used in this case for setting and getting?  Is it the one we want?
</blockquote></details>

The default is std::memory_order_seq_cst which is also the default for grpc_core::Atomic
___
*[src/core/ext/xds/xds_certificate_provider.h, line 118 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUBelU3TyN7jcw_lqB:-MQnNCsT8xH_-nHxpw3M:bxkkzu1) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_certificate_provider.h#L118)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Historically, we have preferred to use our own `Atomic<>` API.  But it may be that there's less reason for that now that we can use STL.

I suggest checking with Esun and Soheil to see what they think about this.  If everyone is okay with changing our code to directly use `std::atomic<>`, then we can probably just get rid of our own `Atomic<>` API.
</blockquote></details>

Changed to `Atomic`
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 102 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQUE-xoDueCQvxVWaMZ:-MQnNGgQDhcMAdrN1gYD:bkh1v47) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_server_config_fetcher.cc#L102)):*
> I assume that was meant to say "none of the other fields".

Yeah, it did. Modified `ToString()` to use an enum
___
*[src/core/lib/security/transport/security_handshaker.cc, line 27 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmcSCL1BejH4or2cGI:-MQnPzxm7MrkkoF-uDXK:b-wnfmk9) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/lib/security/transport/security_handshaker.cc#L27)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No longer needed.
</blockquote></details>

Done. Removed.
___
*[src/core/lib/security/transport/security_handshaker.cc, line 533 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmcENvASAUuyhQBE_u:-MQnBCA87YzcwW3J1-Oj:banglzg) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/lib/security/tra [...]

2021-01-12 00:06 UTC, yashykt commented
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTYewO1h-1X7Gq-vRJ:-MQnuW1K1pWvLKxuyHR_:b-75rjds) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/transport/chttp2/server/chttp2_server.cc#L194)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I don't believe that is going to be an issue. On the other hand, I do believe it would be a good to have if we can somehow share the SSL state between security connectors that did not have any relevant change. @zhenlian @jiangtaoli2016 
</blockquote></details>

I can atleast optimize this to not create a new security connector when there is no change.


<!-- Sent from Reviewable.io -->

2021-01-12 18:20 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008)* status: 23 of 33 files reviewed, 15 unresolved discussions (waiting on @jiangtaoli2016 and @markdroth)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTYewO1h-1X7Gq-vRJ:-MQrm_uoEdAF_IJimR1_:by5bizd) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/transport/chttp2/server/chttp2_server.cc#L194)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I can atleast optimize this to not create a new security connector when there is no change.
</blockquote></details>

Hi Yash, can I see the code for the SSL state that is currently being shared across connections? I think ideally, it would be great if we can create new security connector only when needed, but I'd like to see exactly what's stored in SSL state, and what are the things being shared.
Also, does the client side share SSL state among connections?


<!-- Sent from Reviewable.io -->

2021-01-12 18:40 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008)* status: 23 of 33 files reviewed, 15 unresolved discussions (waiting on @jiangtaoli2016 and @markdroth)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTYewO1h-1X7Gq-vRJ:-MQrqoH6AaXqvOFgPnAq:bpb8bcm) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/transport/chttp2/server/chttp2_server.cc#L194)):*
For now, I've updated the code to only create the new security connector when the grpc_tls_credentials_options would change. I guess if the options change then we can't really share the SSL session either.

> Hi Yash, can I see the code for the SSL state that is currently being shared across connections?
I haven't dug deep enough in the security code to figure out how that happens yet, but the current state might be an optimal one, because even with regular LDS updates, changes that would affect the options would be less common anyway.


<!-- Sent from Reviewable.io -->

2021-01-12 19:45 UTC, markdroth requested changes
This is getting close!  As soon as I merge #25120, you can merge those changes in here.

Please let me know if you have any questions.  Thanks!

> Reviewed 7 of 9 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008#-:-MQs7KPG1d2B2w5eJ7Iv:b-dzsqt4)* status: all files reviewed, 10 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQTYewO1h-1X7Gq-vRJ:-MQs3pYq8S1zTNPS4V2k:bbgyc20) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/transport/chttp2/server/chttp2_server.cc#L194)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

For now, I've updated the code to only create the new security connector when the grpc_tls_credentials_options would change. I guess if the options change then we can't really share the SSL session either.

> Hi Yash, can I see the code for the SSL state that is currently being shared across connections?
I haven't dug deep enough in the security code to figure out how that happens yet, but the current state might be an optimal one, because even with regular LDS updates, changes that would affect the options would be less common anyway.
</blockquote></details>

This change looks good, thanks!
___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 87 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmef2LB21UQ-PKcoWk:-MQs-nmW3knnYDPFsmPF:b-svvg0w) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L87)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

This is the workaround to the problem of reloading ssl creds that we discussed on Friday. In an earlier version of the code, I had tried creating the security connector with the connection arg modifier even when there is no config fetcher but that ran into issues with h2_ssl_cred_reload.cc which assumes that there is only one security connector. After we decide on how the SSL creds fetcher API needs to look like in the future, we can clean this up, but in the mean time since this is an experimental Core API, I think it should be fine for now. What do you think?
</blockquote></details>

Ah, okay, I didn't realize that that was the reason for this change.  Please add a detailed TODO comment to explain why this is being done, what the drawback is, and what we plan to do about it.

I don't want this to block this PR, but I would really prefer to find a way to address this before we de-experimentalize the server xDS API.
___
*[src/core/ext/xds/xds_api.h, line 285 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs-Gq2-6-UNRNeBjD0:-MQs-Gq2-6-UNRNeBjD1:b-vguqfp) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_api.h#L285)):*
> ```objc
>     enum class ListenerType {
>       kTcpListener = 0,
>       kApiListener,
> ```

Let's call this `kHttpApiListener`.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 104 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs0bFW0LBxH-sSF9Xy:-MQs0bFW0LBxH-sSF9Xz:b-xdmgq5) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L104)):*
> ```cpp
>       }
>       auto* prev_provider = xds_certificate_provider_.get();
>       bool provides_root_certs = false, provides_identity_certs = false,
> ```

Please declare each variable on its own line.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 119 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs2cWy8dbm-K3s4LsQ:-MQs2cWy8dbm-K3s4LsR:b1o5pk2) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L119)):*
> ```cpp
>       }
>       // Only send an update, if something changed.
>       if (updated_once_ && xds_certificate_provider_.get() == prev_provider &&
> ```

Instead of checking the before and after conditions here, would it make sense to have `UpdateXdsCertificateProvider()` return a bool indicating if something changed?
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 120 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs1BS23bINJ8jn53Vf:-MQs1BS23bINJ8jn53Vg:b-w94xi2) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L120)):*
> ```cpp
>       // Only send an update, if something changed.
>       if (updated_once_ && xds_certificate_provider_.get() == prev_provider &&
>           ((prev_provider == nullptr) ||
> ```

No need for the parens around `prev_provider == nullptr`.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 120 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs56J89dXqzV_l0agx:-MQs56J89dXqzV_l0agy:bh6psbt) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L120)):*
> ```cpp
>       // Only send an update, if something changed.
>       if (updated_once_ && xds_certificate_provider_.get() == prev_provider &&
>           ((prev_provider == nullptr) ||
> ```

With the current logic in `UpdateXdsCertificateProvider()`, I don't think this part of the expression is actually necessary, because the cases where we'd need to change the tls_credentials_options are also the cases where `UpdateXdsCertificateProvider()` will create a new `XdsCertificateProvider()`, so the check on the line above should be sufficient by itself.

That having been said, once #25120 is merged, I think the logic in `UpdateXdsCertificateProvider()` will need to change such that it just updates the map inside of the `XdsCertificateProvider` and never replaces the object itself, in which case you will need the additional logic here.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 180 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs4by75DA5RcML_ofN:-MQs4by75DA5RcML_ofO:b-hr3tk3) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L180)):*
> ```cpp
>           listener.downstream_tls_context.common_tls_context
>               .tls_certificate_certificate_provider_instance.certificate_name;
>       RefCountedPtr<XdsCertificateProvider> new_root_provider;
> ```

I just noticed that this should use `grpc_tls_certificate_provider`, not `XdsCertificateProvider`.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 195 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs4fz74ECpkVnPEtW_:-MQs4fz74ECpkVnPEtWa:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L195)):*
> ```cpp
>         root_certificate_provider_ = std::move(new_root_provider);
>       }
>       RefCountedPtr<XdsCertificateProvider> new_identity_provider;
> ```

Same here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7975 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmjGEF1FAmM83dFgva:-MQs5xdmAYoC_Zv7hv0w:b-hgcnq6) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/test/cpp/end2end/xds_end2end_test.cc#L7975)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

The reason for this is that grpc shutdown can potentially happen in the background which causes issues when we want to register certificate providers. It often happens that when the new test suite tries to run and register certificate providers, the shutdown from the previous suite hasn't finished. This actually means in normal test runs, grpc shutdown would never actually happen if the init from the next test suite runs before the asynchronous shutdown  [...]

2021-01-14 02:52 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008)* status: 27 of 33 files reviewed, 10 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 285 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs-Gq2-6-UNRNeBjD0:-MQynIBh7d_kLjb1ALaZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_api.h#L285)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's call this `kHttpApiListener`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 104 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs0bFW0LBxH-sSF9Xy:-MQynK3j4cZ6IJ2U5dIl:b-wsu8s3) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L104)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please declare each variable on its own line.
</blockquote></details>

Outdated
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 119 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs2cWy8dbm-K3s4LsQ:-MQynKzz8_iTmL2jK8uH:b-wsu8s3) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of checking the before and after conditions here, would it make sense to have `UpdateXdsCertificateProvider()` return a bool indicating if something changed?
</blockquote></details>

Outdated
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 120 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs1BS23bINJ8jn53Vf:-MQynM5Z33vQJIMgs00f:b-wsu8s3) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L120)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the parens around `prev_provider == nullptr`.
</blockquote></details>

Outdated
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 120 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs56J89dXqzV_l0agx:-MQynNuh-e9d723FzL0v:b-h360jw) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L120)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

With the current logic in `UpdateXdsCertificateProvider()`, I don't think this part of the expression is actually necessary, because the cases where we'd need to change the tls_credentials_options are also the cases where `UpdateXdsCertificateProvider()` will create a new `XdsCertificateProvider()`, so the check on the line above should be sufficient by itself.

That having been said, once #25120 is merged, I think the logic in `UpdateXdsCertificateProvider()` will need to change such that it just updates the map inside of the `XdsCertificateProvider` and never replaces the object itself, in which case you will need the additional logic here.
</blockquote></details>

Updated and moved the logic to `UpdateXdsCertificateProvider()`. Note that earlier, we were not ALWAYS creating a different XdsCertificateProvider object.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 180 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs4by75DA5RcML_ofN:-MQyn_P07m2bYvWtOwZn:b-7pdx6d) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L180)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I just noticed that this should use `grpc_tls_certificate_provider`, not `XdsCertificateProvider`.
</blockquote></details>

Done. Thanks!
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 195 at r6](https://reviewable.io/reviews/grpc/grpc/25008#-MQs4fz74ECpkVnPEtW_:-MQynah1DX1PQoPgXUf9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fe9ce77d7930557dfc455308e14d7508e3ca861d/src/core/ext/xds/xds_server_config_fetcher.cc#L195)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7975 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmjGEF1FAmM83dFgva:-MQycBORCW566ffcFsbu:b-lx41wp) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/test/cpp/end2end/xds_end2end_test.cc#L7975)):*
> Why is this problem showing up now and hasn't shown up before? For example, the XdsClient itself takes a while to shut down, and that gets created and destroyed between every test. Although admittedly, use of UnsetGlobalXdsClientForTest() forces that to work right even if the shutdown doesn't happen.

I don't think there were tests earlier which depended on `grpc_shutdown()` finishing deterministically. Now, since we have multiple suites that require registering certificate providers I can either forcefully do a shutdown() at the end of each suite with `grpc_shutdown_blocking()` or by simply not doing an init()/shutdown() per test suite. Since `grpc_shutdown_blocking()`

> Can we convince ourselves that there's no state that is going to fail to be reset between tests by doing this that would affect the test outcomes?

Without an explicit `grpc_init()`/`grpc_shutdown()` there is going to be some state that does not get reset, but that should not affect test outcomes atleast currently. There is a chance that in the future that we might have such state that needs to be reset between tests and a blocking shutdown is the only solution I can think of for now (though it would potentially slow down our tests).


<!-- Sent from Reviewable.io -->

2021-01-14 02:56 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008)* status: 26 of 33 files reviewed, 10 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 87 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmef2LB21UQ-PKcoWk:-MQyoUDc0zsiku3kxQ2j:bgiv2wu) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L87)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ah, okay, I didn't realize that that was the reason for this change.  Please add a detailed TODO comment to explain why this is being done, what the drawback is, and what we plan to do about it.

I don't want this to block this PR, but I would really prefer to find a way to address this before we de-experimentalize the server xDS API.
</blockquote></details>

TODO added. Note that this would only really impact the Core API. Wrapped language APIs should be able to get around this.


<!-- Sent from Reviewable.io -->

2021-01-14 20:02 UTC, markdroth requested changes
This looks really good!  Only minor comments remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r7, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008#-:-MR1UJhk-7xR8Dg1qm8S:b-p1dirg)* status: all files reviewed, 8 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 87 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmef2LB21UQ-PKcoWk:-MR1Qt6I0FvU63AecZkb:bs2x7d7) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L87)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

TODO added. Note that this would only really impact the Core API. Wrapped language APIs should be able to get around this.
</blockquote></details>

It depends on how directly the wrapped language APIs expose the C-core API.  If the specific semantics of the C-core API are abstracted away, then it's  probably not an issue.  But, for example, I know that the C# API pretty directly exposes the C-core API, so depending on how we design the xDS-enabled APIs, we may need to expose some constraints to users.  We'll have to see how it goes.

Anyway, this looks good for now.
___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 21 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1RDua2JSfMOigyeb1:-MR1RDua2JSfMOigyeb2:b-g4z6xt) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L21)):*
> ```cpp
> #include <grpc/support/port_platform.h>
> 
> #include <grpc/grpc.h>
> ```

This include should actually be moved down to right above <grpc/support/alloc.h>.
___
*[src/core/ext/xds/xds_api.cc, line 1642 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQU8Bjj8AfjMOzdzt7b:-MR1PI56-PmB66W_Robq:b-qou4hr) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1642)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I agree that that's what we should be doing but I'm not sure our current infrastructure supports that. Let me confirm this.
</blockquote></details>

Are you going to do this as part of the current PR or defer this to a separate one?
___
*[src/core/ext/xds/xds_certificate_provider.h, line 57 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1Q4Ql35ngs2ug5RGd:-MR1Q4Ql35ngs2ug5RGe:bdg3640) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/ext/xds/xds_certificate_provider.h#L57)):*
> ```objc
>       const std::string& cluster, std::vector<XdsApi::StringMatcher> matchers);
> 
>   bool GetRequireClientCertificate(const std::string& cert_name);
> ```

Please move these two up above the SAN matcher methods, so that all of the methods whose data is stored in `certificate_state_map_` are next to each other.
___
*[src/core/ext/xds/xds_certificate_provider.h, line 113 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1Rmhj-bwGGevpP-WY:-MR1Rmhj-bwGGevpP-WZ:b-q5r7q6) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/ext/xds/xds_certificate_provider.h#L113)):*
> ```objc
> 
>    private:
>     XdsCertificateProvider* xds_certificate_provider_;
> ```

Good catch -- you're right that this didn't need to be holding a ref.  I'm not sure why I thought that was necessary.

Does this change mean that we can address the TODO I added?

https://github.com/grpc/grpc/blob/652d10cd1dfbf190483c7620eaa95d8e561e899b/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L276
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 335 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1QTxs2jBJ6ZuYnVI4:-MR1QTxs2jBJ6ZuYnVI5:b-wz37vi) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/ext/xds/xds_certificate_provider.cc#L335)):*
> ```cpp
> }
> 
> bool XdsCertificateProvider::GetRequireClientCertificate(
> ```

Same as in the .h file:  Please move these up above the SAN matcher methods.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 348 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1QZnu0jGYLSnkuRG3:-MR1QZnu0jGYLSnkuRG4:b-4wtv2h) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/ext/xds/xds_certificate_provider.cc#L348)):*
> ```cpp
>   auto it = certificate_state_map_.find(cert_name);
>   if (it == certificate_state_map_.end()) return;
>   return it->second->set_require_client_certificate(require_client_certificate);
> ```

No need for `return`.
___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 214 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1Tl9C3qadVf5pEmkM:-MR1Tl9C3qadVf5pEmkN:b-cnkldq) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/lib/security/credentials/xds/xds_credentials.cc#L214)):*
> ```cpp
>       tls_credentials_options->set_watch_root_cert(true);
>     }
>     if (xds_certificate_provider->ProvidesRootCerts("")) {
> ```

This is exactly the same condition as the previous block, so let's just merge the two.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7975 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmjGEF1FAmM83dFgva:-MR1U59v8P3apEfb6DA1:b-xblu08) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/test/cpp/end2end/xds_end2end_test.cc#L7975)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> Why is this problem showing up now and hasn't shown up before? For example, the XdsClient itself takes a while to shut down, and that gets created and destroyed between every test. Although admittedly, use of UnsetGlobalXdsClientForTest() forces that to work right even if the shutdown doesn't happen.

I don't think there were tests earlier which depended on `grpc_shutdown()` finishing deterministically. Now, since we have multiple suites that require registering certificate providers I can either forcefully do a shutdown() at the end of each suite with `grpc_shutdown_blocking()` or by simply not doing an init()/shutdown() per test suite. Since `grpc_shutdown_blocking()`

> Can we convince ourselves that there's no state that is going to fail to be reset between tests by doing this that would affect the test outcomes?

Without an explicit `grpc_init()`/`grpc_shutdown()` there is going to be some state that does not get reset, but that should not affect test outcomes atleast currently. There is a chance that in the future that we might have such state that needs to be reset between tests and a blocking shutdown is the only solution I can think of for now (though it would potentially slow down our tests).
</blockquote></details>

Okay.  Did you run the test suite 1000x on RBE to verify that it's not more flaky?


<!-- Sent from Reviewable.io -->

2021-01-14 21:24 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008)* status: 29 of 34 files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc, line 21 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1RDua2JSfMOigyeb1:-MR1kfg0-oTs5ySwsJvy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc#L21)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This include should actually be moved down to right above <grpc/support/alloc.h>.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1642 at r1](https://reviewable.io/reviews/grpc/grpc/25008#-MQU8Bjj8AfjMOzdzt7b:-MR1kuzh3x1mJfWeLZjb:b-sk6du7) ([raw file](https://github.com/grpc/grpc/blob/b8e1eabaacc6804946d3e2b7846d67d6017a0689/src/core/ext/xds/xds_api.cc#L1642)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Are you going to do this as part of the current PR or defer this to a separate one?
</blockquote></details>

As a separate one
___
*[src/core/ext/xds/xds_certificate_provider.h, line 57 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1Q4Ql35ngs2ug5RGd:-MR1l-Rk85oK3t8bg-Gn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/ext/xds/xds_certificate_provider.h#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move these two up above the SAN matcher methods, so that all of the methods whose data is stored in `certificate_state_map_` are next to each other.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_certificate_provider.h, line 113 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1Rmhj-bwGGevpP-WY:-MR1l0GTDvLSaPoBJdiW:b3itn3r) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/ext/xds/xds_certificate_provider.h#L113)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Good catch -- you're right that this didn't need to be holding a ref.  I'm not sure why I thought that was necessary.

Does this change mean that we can address the TODO I added?

https://github.com/grpc/grpc/blob/652d10cd1dfbf190483c7620eaa95d8e561e899b/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L276
</blockquote></details>

Yeah, removed it
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 335 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1QTxs2jBJ6ZuYnVI4:-MR1m4NSB3HuDO_c9HRp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/ext/xds/xds_certificate_provider.cc#L335)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as in the .h file:  Please move these up above the SAN matcher methods.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_certificate_provider.cc, line 348 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1QZnu0jGYLSnkuRG3:-MR1m5bo3F-xcWjq9KNv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/ext/xds/xds_certificate_provider.cc#L348)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `return`.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 214 at r9](https://reviewable.io/reviews/grpc/grpc/25008#-MR1Tl9C3qadVf5pEmkM:-MR1m7HM7pmdDevX89-_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d7f7de6109218c2c2c96b22c0b41150b6e9a2421/src/core/lib/security/credentials/xds/xds_credentials.cc#L214)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is exactly the same condition as the previous block, so let's just merge the two.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7975 at r4](https://reviewable.io/reviews/grpc/grpc/25008#-MQmjGEF1FAmM83dFgva:-MR1m7zD7RKU_gdxFJw0:b5nxh8m) ([raw file](https://github.com/grpc/grpc/blob/4ed756a5a37fd0ce967c3de02bedf6b61c290f51/test/cpp/end2end/xds_end2end_test.cc#L7975)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  Did you run the test suite 1000x on RBE to verify that it's not more flaky?
</blockquote></details>

Yes, I did. For the sanitizers, I could just 100x runs in. This test takes a long time


<!-- Sent from Reviewable.io -->

2021-01-14 21:33 UTC, markdroth approved these changes
This looks great!

> Reviewed 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25008#-:-MR1oOoP2CUr0ibJuZT8:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-15 17:26 UTC, yashykt commented
Thanks for reviewing!!

2021-01-15 17:26 UTC, merged