Support Default Root Certs in Tls Credentials
grpc/grpc pull request #25018
Opened 2020-12-17 01:29 UTC by ZhenLian

2020-12-17 16:22 UTC, markdroth requested changes
I don't think this is exactly the right direction.  I think we need to either change our API to allow using different provider instances for root vs. identity certs, or else we need to make it such that the provider is completely optional in the plain TLS case where the client is using system root certs.

Please let me know if you have any questions.  Thanks!

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25018#-:-MOlVLElBGGHZKtk3aNC:b-u7qvhp)* status: all files reviewed, 6 unresolved discussions (waiting on @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 146 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlLnmGAwn2A2LzyCe3:-MOlLnmGAwn2A2LzyCe4:b-x6tusn) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L146)):*
> ```objc
>       std::unique_ptr<TlsCertificatesWatcherInterface> watcher,
>       absl::optional<std::string> root_cert_name,
>       absl::optional<std::string> identity_cert_name, bool use_default_roots);
> ```

I don't think it makes sense to plumb this into the distributor.  The job of the distributor is to distribute the cert data from the provider to the security connectors, but in this case we are not getting the data from a provider in the first place, so the distributor has nothing to do with it.

I can think of two reasonable alternatives:

1. Handle this directly in the security connector.  If we're not getting root certs from the provider, don't use the distributor at all for this.
2. Create a new provider impl for the system root certs (or maybe just use the existing static provider impl?), and change tls_credentials_options to allow specifying a different provider for each of root and identity certs.

Option 2 is more work but would probably wind up being cleaner.
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.h, line 140 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlSKPK7e2W1r6mBp7c:-MOlSKPLBQRUbRs-cX88:b-ehjnq7) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/src/core/lib/security/security_connector/tls/tls_security_connector.h#L140)):*
> ```objc
>   absl::optional<absl::string_view> pem_root_certs_;
>   absl::optional<grpc_core::PemKeyCertPairList> pem_key_cert_pair_list_;
>   bool use_default_roots_ = false;
> ```

I don't think this is needed.  This is always set to the opposite of `options_->watch_root_cert()`, so I think you can just look at that.
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 335 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlRrvg7gsZfe5Wm1PH:-MOlRrvg7gsZfe5Wm1PI:b-7mdchj) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L335)):*
> ```cpp
>   }
>   bool root_being_watched = security_connector_->options_->watch_root_cert();
>   bool root_ready =
> ```

I suggest writing this a little more clearly:

```
const bool root_ready =
    !security_connector_->options_->watch_root_cert() ||
    security_connector_->pem_root_certs_.has_value();
const bool identity_ready =
    !security_connector_->options_->watch_identity_pair() ||
    security_connector_->pem_key_cert_pair_list_.has_value();
if (root_ready && identity_ready) {
  // ...create handshaker...
}
```
___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 141 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlUW865k0IHWnUU9_W:-MOlUW865k0IHWnUU9_X:b-2ur05d) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/test/core/security/grpc_tls_credentials_options_test.cc#L141)):*
> ```cpp
>        ClientOptionsWithStaticDataProviderOnDefaultRootCerts) {
>   auto options = MakeRefCounted<grpc_tls_credentials_options>();
>   auto provider = MakeRefCounted<StaticDataCertificateProvider>(
> ```

In the case where the client is using normal TLS (not mTLS) and is using the system root certs, why would they need to specify a provider at all?  It's not actually going to be used for anything.
___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 321 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlUo3ICLemTRL56uHZ:-MOlUo3ICLemTRL56uH_:b-54jfle) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/test/core/security/grpc_tls_credentials_options_test.cc#L321)):*
> ```cpp
> 
> TEST_F(GrpcTlsCredentialsOptionsTest,
>        ClientOptionsWithCertWatcherProviderOnDefaultRootCerts) {
> ```

The functionality being tested here really has nothing to do with the provider type, so there's no need to test it with both the static and file-watcher providers.
___
*[test/core/security/tls_security_connector_test.cc, line 153 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlV-wCEalPRct2uHBz:-MOlV-wCEalPRct2uHC-:b-fcxmd4) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/test/core/security/tls_security_connector_test.cc#L153)):*
> ```cpp
>   grpc_core::RefCountedPtr<grpc_tls_certificate_distributor> distributor =
>       grpc_core::MakeRefCounted<grpc_tls_certificate_distributor>();
>   grpc_core::RefCountedPtr<::grpc_tls_certificate_provider> provider =
> ```

As mentioned elsewhere, it doesn't make sense to require the user to create a provider in this case, since it's not actually going to be used for anything.


<!-- Sent from Reviewable.io -->

2020-12-17 22:30 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25018)* status: all files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 146 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlLnmGAwn2A2LzyCe3:-MOliDNl81Hf136FU6Ay:b-cvji6o) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L146)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think it makes sense to plumb this into the distributor.  The job of the distributor is to distribute the cert data from the provider to the security connectors, but in this case we are not getting the data from a provider in the first place, so the distributor has nothing to do with it.

I can think of two reasonable alternatives:

1. Handle this directly in the security connector.  If we're not getting root certs from the provider, don't use the distributor at all for this.
2. Create a new provider impl for the system root certs (or maybe just use the existing static provider impl?), and change tls_credentials_options to allow specifying a different provider for each of root and identity certs.

Option 2 is more work but would probably wind up being cleaner.
</blockquote></details>

Yeah,  I've already updated the code. Alternative 2 seems more work, so I will follow the alternative 1 first :).
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.h, line 140 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlSKPK7e2W1r6mBp7c:-MOm2D8L9dZjKT188Dph:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/src/core/lib/security/security_connector/tls/tls_security_connector.h#L140)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is needed.  This is always set to the opposite of `options_->watch_root_cert()`, so I think you can just look at that.
</blockquote></details>

Done.
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 335 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlRrvg7gsZfe5Wm1PH:-MOmnlm9BdEbT-Z4L-x_:bx1voqc) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L335)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest writing this a little more clearly:

```
const bool root_ready =
    !security_connector_->options_->watch_root_cert() ||
    security_connector_->pem_root_certs_.has_value();
const bool identity_ready =
    !security_connector_->options_->watch_identity_pair() ||
    security_connector_->pem_key_cert_pair_list_.has_value();
if (root_ready && identity_ready) {
  // ...create handshaker...
}
```
</blockquote></details>

Yeah it looks better. Thanks for the suggestions!
___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 141 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlUW865k0IHWnUU9_W:-MOmGIoT03PxKjGsrjx-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/test/core/security/grpc_tls_credentials_options_test.cc#L141)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In the case where the client is using normal TLS (not mTLS) and is using the system root certs, why would they need to specify a provider at all?  It's not actually going to be used for anything.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 321 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlUo3ICLemTRL56uHZ:-MOmGLYWEoVg2pbIO0Jq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/test/core/security/grpc_tls_credentials_options_test.cc#L321)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The functionality being tested here really has nothing to do with the provider type, so there's no need to test it with both the static and file-watcher providers.
</blockquote></details>

Done.
___
*[test/core/security/tls_security_connector_test.cc, line 153 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlV-wCEalPRct2uHBz:-MOmN6vN3Ld2mrM0BUQT:b-crf6k3) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/test/core/security/tls_security_connector_test.cc#L153)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned elsewhere, it doesn't make sense to require the user to create a provider in this case, since it's not actually going to be used for anything.
</blockquote></details>

Done. I've also updated the C++ API, since before it was taking the provider a mandatory field.


<!-- Sent from Reviewable.io -->

2020-12-18 00:55 UTC, markdroth requested changes
After the holidays, I'd like us to think through the implications of moving the system root certs into their own provider, since I think that might be a much cleaner way of layering the functionality here.

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25018#-:-MOnKuQt9Nop8O30NZ3E:befkq9o)* status: all files reviewed, 4 unresolved discussions (waiting on @jiangtaoli2016, @yashykt, and @ZhenLian)

___
*[include/grpcpp/security/tls_credentials_options.h, line 158 at r2](https://reviewable.io/reviews/grpc/grpc/25018#-MOnINCT8oYMPGGqKsoG:-MOnINCT8oYMPGGqKsoH:b-lwdtce) ([raw file](https://github.com/grpc/grpc/blob/c8636e4e3cae34648bcfddbe9a960ba14fac3771/include/grpcpp/security/tls_credentials_options.h#L158)):*
> ```objc
>   // @param certificate_provider the provider which fetches TLS credentials that
>   // will be used in the TLS handshake
>   explicit TlsCredentialsOptions();
> ```

This no longer needs to be `explicit`.
___
*[include/grpcpp/security/tls_credentials_options.h, line 210 at r2](https://reviewable.io/reviews/grpc/grpc/25018#-MOnIRv1EwfwYnDtWdUJ:-MOnIRv1EwfwYnDtWdUK:b-oeo7k3) ([raw file](https://github.com/grpc/grpc/blob/c8636e4e3cae34648bcfddbe9a960ba14fac3771/include/grpcpp/security/tls_credentials_options.h#L210)):*
> ```objc
>   // in the system default locations, and assume client won't provide any
>   // identity certificates(single side TLS).
>   TlsChannelCredentialsOptions() : TlsCredentialsOptions() {}
> ```

This ctor is the default, so it's no longer needed.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 146 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlLnmGAwn2A2LzyCe3:-MOnIfutD3IhNaN5hf5m:b-42fmb8) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L146)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Yeah,  I've already updated the code. Alternative 2 seems more work, so I will follow the alternative 1 first :).
</blockquote></details>

I'm fine with this for now, but before we make the new TLS creds API non-experimental, I think we should carefully think through whether or not we want to pursue option 2.   If we do, we should do it before we make the API non-experimental.
___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 317 at r2](https://reviewable.io/reviews/grpc/grpc/25018#-MOnKKw5C7FRAKy9s9wG:-MOnKKw67XrDfkdO97et:b-keorcz) ([raw file](https://github.com/grpc/grpc/blob/c8636e4e3cae34648bcfddbe9a960ba14fac3771/test/core/security/grpc_tls_credentials_options_test.cc#L317)):*
> ```cpp
> 
> TEST_F(GrpcTlsCredentialsOptionsTest,
>        ClientOptionsWithDefaultRootAndCertWatcherProviderOnIdentityCerts) {
> ```

This is basically a duplicate of the test above that uses the static provider.  I don't think this is necessary.
___
*[test/cpp/client/credentials_test.cc, line 497 at r2](https://reviewable.io/reviews/grpc/grpc/25018#-MOnKoHXBGEy4xCppPaJ:-MOnKoHXBGEy4xCppPaK:b3sszur) ([raw file](https://github.com/grpc/grpc/blob/c8636e4e3cae34648bcfddbe9a960ba14fac3771/test/cpp/client/credentials_test.cc#L497)):*
> ```cpp
> TEST(
>     CredentialsTest,
>     TlsChannelCredentialsWithFileWatcherCertificateProviderLoadingIdentityOnly) {
> ```

This is a duplicate of the test with the static provider above.  We don't need to test this twice.


<!-- Sent from Reviewable.io -->

2020-12-23 07:47 UTC, ZhenLian reviewed
Sure! I will document some of my thoughts here in case I forget them, but feel free to reply to me next week(btw happy holidays ahead!).
If we are going to allow specifying two different providers, I think the next question is, shall we also make the underlying distributor separate for root and identity? 
Having two providers while still keeping one distributor would probably make it hard to decide when to create the distributor. Right now the distributor is created by the provider. In the two-provider design, if the provider is still going to create the distributor, then which one of the two is going to create it? If we are going to let some other classes, such as the security connector, to create the distributor, then the lifetime of the distributor would change(Previously, the distributor is created by the provider and controlled by the application; after the change, it will be attached to a particular channel). It just gives me a feeling that this would change so many things, and we probably don't want to go this way?
It's probably ok if we make two distributors here, but I am wondering if it is worth the effort...The distributor is designed to incorporate both the root and identity certs, and if we completely break it down, some of the watcher API semantics might be changed(e.g. if the root cert and identity cert both get updated, we will have two updates instead of one).
Also, if we have a provider implementation specifically for system roots, isn't the implication of system root API going to change? Right now, we will speculate if system root is needed by checking if user watches root certs. Under this change, users has to specify explicitly a system root provider, which probably mean the use of system root is no more transparent to the user?
Feel free to let me know your thoughts. Thanks! 

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25018#-:-MOrvaQg3vdHd__MW3wn:bnmloo6)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @yashykt)

___
*[include/grpcpp/security/tls_credentials_options.h, line 158 at r2](https://reviewable.io/reviews/grpc/grpc/25018#-MOnINCT8oYMPGGqKsoG:-MOsLg0R5WBsnhOkI4sh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8636e4e3cae34648bcfddbe9a960ba14fac3771/include/grpcpp/security/tls_credentials_options.h#L158)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This no longer needs to be `explicit`.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_credentials_options.h, line 210 at r2](https://reviewable.io/reviews/grpc/grpc/25018#-MOnIRv1EwfwYnDtWdUJ:-MOsM29f4Dza2EMBFZlx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8636e4e3cae34648bcfddbe9a960ba14fac3771/include/grpcpp/security/tls_credentials_options.h#L210)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This ctor is the default, so it's no longer needed.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 146 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlLnmGAwn2A2LzyCe3:-MOrwSxn7RxKwCsGs75Y:b33txym) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L146)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'm fine with this for now, but before we make the new TLS creds API non-experimental, I think we should carefully think through whether or not we want to pursue option 2.   If we do, we should do it before we make the API non-experimental.
</blockquote></details>

OK. Let's think through alternative 2 then, since this will very likely to be an API change, and I'd rather to have such changes earlier than later. 
If we are going to allow specifying two different providers, I think the next question is, shall we also make the underlying distributor separate for root and identity? 
Having two providers while still keeping one distributor would probably make it hard to decide when to create the distributor. Right now the distributor is created by the provider. In two provider design, if the provider is still going to create the distributor, then which one of the two is going to create it? If we are going to let some other classes, such as the security connector, to create the distributor, then the lifetime of the distributor would change(Previously, the distributor is created by the provider and controlled by the application; after the change, it will be attached to a particular channel). It just gives me a feeling that this would change so many things, and we probably don't want to go this way?
It's probably ok if we make two distributors here, but I am wondering if it is worth the effort...The distributor is designed to incorporate both the root and identity certs, and if we completely break it down, some of the watcher API semantics might be changed(e.g. if the root cert and identity cert both get updated, we will have two updates instead of one).
Also, isn't the implications of system root API going to change, if we have a provider impl specifically for system roots? Right now, we will speculate if system root is needed by checking if user watches root certs. Under this change, users has to specify explicitly a system root provider, which probably mean the use of system root is no more transparent to the user?
Feel free to let me know your thoughts. Thanks! 
___
*[test/core/security/grpc_tls_credentials_options_test.cc, line 317 at r2](https://reviewable.io/reviews/grpc/grpc/25018#-MOnKKw5C7FRAKy9s9wG:-MOsNEk05FagNg6s9MY8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8636e4e3cae34648bcfddbe9a960ba14fac3771/test/core/security/grpc_tls_credentials_options_test.cc#L317)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is basically a duplicate of the test above that uses the static provider.  I don't think this is necessary.
</blockquote></details>

Done.
___
*[test/cpp/client/credentials_test.cc, line 497 at r2](https://reviewable.io/reviews/grpc/grpc/25018#-MOnKoHXBGEy4xCppPaJ:-MPDY7iS6XIXvdkFVBkn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8636e4e3cae34648bcfddbe9a960ba14fac3771/test/cpp/client/credentials_test.cc#L497)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is a duplicate of the test with the static provider above.  We don't need to test this twice.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-06 17:45 UTC, markdroth approved these changes
This PR looks great!  We can continue talking about the other approach after this is merged.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25018#-:-MQNnSeo4Fd0KuREUX84:b-oy9zzu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiangtaoli2016 and @yashykt)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h, line 146 at r1](https://reviewable.io/reviews/grpc/grpc/25018#-MOlLnmGAwn2A2LzyCe3:-MQNlS1I0syhWhHdkQc3:b-dvxyxk) ([raw file](https://github.com/grpc/grpc/blob/742ce598d4095b2bcf48e777eb999a3b61a8b666/src/core/lib/security/credentials/tls/grpc_tls_certificate_distributor.h#L146)):*
> If we are going to allow specifying two different providers, I think the next question is, shall we also make the underlying distributor separate for root and identity?

I think we could handle this via a level of indirection.  Each provider would continue to have its own distributor.  The TlsCreds object would register a watcher with each one, and it would create a separate distributor to pass down to the security connectors.  When the watchers get updates from the providers, they feed that data into the distributor to feed the security connector.

This approach allows the security connector code to still get the update for both root and identity certs at once, so the code there doesn't need to change.  It just requires a little more work in the TlsCreds object itself.

Note that this is exactly what we're already doing in the XdsCreds case, because we already support having a separate provider for root vs. identity cert in that case.

> Also, isn't the implications of system root API going to change, if we have a provider impl specifically for system roots? Right now, we will speculate if system root is needed by checking if user watches root certs. Under this change, users has to specify explicitly a system root provider, which probably mean the use of system root is no more transparent to the user?

I'm sure we can still find a way to make this default in a reasonable way.  For example, maybe we could say that if the user does not specify any provider for the root cert, we default to the system root plugin.


<!-- Sent from Reviewable.io -->

2021-01-07 17:40 UTC, ZhenLian commented
Great, I will merge this PR then. Thanks again for the review!

2021-01-07 17:40 UTC, merged