[WIP] CSDS Implementation
grpc/grpc pull request #25038
Opened 2020-12-21 18:36 UTC by lidizheng

The xDS config dump in JSON is done. But the surface API for C++ is work-in-progress.

2020-12-22 00:43 UTC, markdroth reviewed
Here's an early review.  This looks like a good start.

Please let me know if you have any questions.  Thanks!

> Reviewed 325 of 325 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MP6tY8J-Ddqv9VmENRB:b-1o2v2h)* status: all files reviewed, 24 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/xds/xds_api.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6eEHO48jILTqmho27:-MP6eEHO48jILTqmho28:bcsjqo9) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L46)):*
> ```objc
> // default.
> bool XdsSecurityEnabled();
> bool XdsCsdsEnabled();
> ```

I don't think this is needed.  The presence of the CSDS implementation doesn't actually affect our communication with the xDS server, so I don't think it needs to be gated.
___
*[src/core/ext/xds/xds_api.h, line 426 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6aRO1DzBnMZBdyLmC:-MP6aRO1DzBnMZBdyLmD:b-jyav38) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L426)):*
> ```objc
> 
>   // Synchronization status of xDS configs against the management server.
>   enum ClientConfigStatus {
> ```

As per the style guide, enums and typedefs need to be declared before methods:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
___
*[src/core/ext/xds/xds_api.h, line 454 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6dgOI1RzriocOCBVE:-MP6dgOJ3ttgUPuHAvuD:b-76ekq7) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L454)):*
> ```objc
>     CdsUpdateMap cds_update_map;
>     EdsUpdateMap eds_update_map;
>     XdsJsonMap xds_json_map;
> ```

It does not make sense to have a separate map for this.  We already have a way to return data for each individual resource, and this JSON string is just another piece of information for the individual resource.  So instead, let's just add a `Json` field to each of the `LdsUpdate`, `RdsUpdate`, `CdsUpdate`, and `EdsUpdate` structs.
___
*[src/core/ext/xds/xds_api.h, line 478 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6elLZDqibdfs8Kaka:-MP6elLZDqibdfs8Kakb:b5alh0l) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L478)):*
> ```objc
> 
>   // Creates a ClientConfig message and returns it in JSON.
>   std::string CreateClientConfigInJson(
> ```

This method should not need to take so many different maps as input.  It should basically just need one map per resource type, and those maps should basically be the existing maps in the `XdsClient` that contain all of the necessary data.
___
*[src/core/ext/xds/xds_api.cc, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6fwtuCEb8E-LcFWbd:-MP6fwtuCEb8E-LcFWbe:b76m9pe) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L122)):*
> ```cpp
> }
> 
> // TODO(lidiz): Check to see if xDS security is enabled. This will be removed
> ```

This is not for xDS security. :)

Also, as mentioned in the .h file, I don't think we need this to begin with.
___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MP6gJzDCDlCBUASX9j3:b-w3q7iw) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
> ```cpp
>   size_t estimated_length = upb_json_encode(msg, m, ext_pool, 0, nullptr, 0, &status);
>   // If encode failed
>   if (estimated_length == (size_t)-1) {
> ```

What can cause this to fail?  Can we just make this an assert?
___
*[src/core/ext/xds/xds_api.cc, line 932 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gNrF5HWHEi8ebpFM:-MP6gNrF5HWHEi8ebpFN:b-3n7kyz) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L932)):*
> ```cpp
>   if (estimated_length == (size_t)-1) {
>     const char *error_message = upb_status_errmsg(&status);
>     gpr_log(GPR_DEBUG, "SerializeToJsonString!!! ERR %s", error_message);
> ```

We should not log in low-level library code like this.  We're returning the error message to the caller, and they can log it if they want to.
___
*[src/core/ext/xds/xds_api.cc, line 936 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hKWn2pTN5Nnd2Dmj:-MP6hKWn2pTN5Nnd2Dmk:bi3nf3x) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L936)):*
> ```cpp
>     return "";
>   }
>   char* data = (char*)upb_arena_malloc(arena, estimated_length + 1);
> ```

Please use C++-style casts.
___
*[src/core/ext/xds/xds_api.cc, line 940 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gvbj0Ejx2NwqChpo:-MP6gvbj0Ejx2NwqChpp:bpphjz6) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L940)):*
> ```cpp
>   size_t output_length = upb_json_encode(msg, m, ext_pool, 0, data, estimated_length + 1, &status);
>   GPR_ASSERT(estimated_length == output_length);
>   *error = GRPC_ERROR_NONE;
> ```

No need to do this explicitly.  The caller should initialize to this value before calling this function, so this function can set it only if there's an error.
___
*[src/core/ext/xds/xds_api.cc, line 941 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6giBV5wrIpM85UHVy:-MP6giBV5wrIpM85UHVz:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L941)):*
> ```cpp
>   GPR_ASSERT(estimated_length == output_length);
>   *error = GRPC_ERROR_NONE;
>   gpr_log(GPR_DEBUG, "SerializeToJsonString!!! %p %zu %s", msg, estimated_length, data);
> ```

Please remove.
___
*[src/core/ext/xds/xds_api.cc, line 942 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gjyP9cSQU7ZveRrb:-MP6gjyP9cSQU7ZveRrc:b-szrtxg) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L942)):*
> ```cpp
>   *error = GRPC_ERROR_NONE;
>   gpr_log(GPR_DEBUG, "SerializeToJsonString!!! %p %zu %s", msg, estimated_length, data);
>   return std::string(data);
> ```

Please use `std::string(data, output_length)` to avoid having the `std::string` ctor figure out the length of the string on its own.
___
*[src/core/ext/xds/xds_api.cc, line 945 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hTAS9eTF68EyqAcg:-MP6hTAS9eTF68EyqAch:bjlzt1z) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L945)):*
> ```cpp
> }
> 
> inline grpc_error* ParseFromJsonString(const std::string& json_str, upb_msg *msg, const upb_msgdef *m, upb_arena* arena, const upb_symtab *ext_pool) {
> ```

Why do we need to parse JSON?  This shouldn't be necessary.
___
*[src/core/ext/xds/xds_api.cc, line 955 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hX9T2EwGpyID1c_k:-MP6hX9T2EwGpyID1c_l:bbhncs1) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L955)):*
> ```cpp
> }
> 
> google_protobuf_Timestamp* GrpcMillisToTimestamp(upb_arena* arena, const grpc_millis& value) {
> ```

`grpc_millis` is a POD type, so it can be passed in by value.
___
*[src/core/ext/xds/xds_api.cc, line 957 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6jIM8Bm2mjDL4SoQ8:-MP6jIM8Bm2mjDL4SoQ9:b-ey7z4d) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L957)):*
> ```cpp
> google_protobuf_Timestamp* GrpcMillisToTimestamp(upb_arena* arena, const grpc_millis& value) {
>   google_protobuf_Timestamp* timestamp = google_protobuf_Timestamp_new(arena);
>   // TODO(lidiz): not sure which type of clock to use.
> ```

I think the way you have this is fine.
___
*[src/core/ext/xds/xds_api.cc, [...]

2020-12-22 03:02 UTC, lidizheng reviewed
Thanks for the early review! I need advice about several trade-offs. Once we settled the direction, I will continue to resolve other comments.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MP7O13252Y8BZYjRqLM:blm0epy)* status: all files reviewed, 24 unresolved discussions (waiting on @lidizheng and @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6eEHO48jILTqmho27:-MP7HMQ8Bxkx2iwKCd6S:bjjhucl) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is needed.  The presence of the CSDS implementation doesn't actually affect our communication with the xDS server, so I don't think it needs to be gated.
</blockquote></details>

Removed.

With CSDS, it consumes slightly more memory and cycles. Well, it's always better to have it work out-of-box.
___
*[src/core/ext/xds/xds_api.h, line 426 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6aRO1DzBnMZBdyLmC:-MP7IB2u7xWMpSWXa4oW:b-8gglng) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L426)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per the style guide, enums and typedefs need to be declared before methods:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
</blockquote></details>

Reordered the enum before the first method (the ctor). Following this rule, `AdsParseResult` looks like a counter example?
___
*[src/core/ext/xds/xds_api.h, line 454 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6dgOI1RzriocOCBVE:-MP7IR_M5v0dxv4QtOiF:b2al18u) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L454)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It does not make sense to have a separate map for this.  We already have a way to return data for each individual resource, and this JSON string is just another piece of information for the individual resource.  So instead, let's just add a `Json` field to each of the `LdsUpdate`, `RdsUpdate`, `CdsUpdate`, and `EdsUpdate` structs.
</blockquote></details>

It did create some difficulty to find the right abstraction to avoid adding JSON-related field to `*Update` structs. The idea was commented in the CSDS design doc.

https://docs.google.com/document/d/15a2ohrjOlpbazSJXqh-aFUXmi9uKAIygoZJDrR-ctqw/edit?disco=AAAAG8DgxyI

I'm okay either way. The implemented way (or the solution proposed in the CSDS comment) has a good separation between CSDS and existing code, so it's less coupled. The latest commented solution can simplify the logic. Which solution would you prefer? It affects many other choices below.
___
*[src/core/ext/xds/xds_api.cc, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6fwtuCEb8E-LcFWbd:-MP7JatE76_dGY7p_nMd:b-hsjlea) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L122)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is not for xDS security. :)

Also, as mentioned in the .h file, I don't think we need this to begin with.
</blockquote></details>

Removed.

Good catch. Copied the comment from XdsSecurity...
___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MP7JgGs8X6Y5CrougNb:bxu8o2s) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What can cause this to fail?  Can we just make this an assert?
</blockquote></details>

I did encountered one failure: the Any encoded type wasn't presented in the symbol table. From the [json_encode.c](https://github.com/protocolbuffers/upb/blob/master/upb/json_encode.c#L38), there are many other possible failures:

* Out-of-range date, timestamp, duration
* Several bad Any packaging problem (bad type url, unrecognized type, etc.)
* Some snake case enforcement
* Field exist but value is missing

Assert seems too harsh? Alternatively, we can log the error and move on. So, even if the cache failed, xDS is still usable. What's your recommended way of handling this?
___
*[src/core/ext/xds/xds_api.cc, line 932 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gNrF5HWHEi8ebpFM:-MP7LdZC1yqrPB62WwOj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L932)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should not log in low-level library code like this.  We're returning the error message to the caller, and they can log it if they want to.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 936 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hKWn2pTN5Nnd2Dmj:-MP7LiXEAFD4GXl2h88S:b76fc7z) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L936)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style casts.
</blockquote></details>

Using `static_cast`.
___
*[src/core/ext/xds/xds_api.cc, line 940 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gvbj0Ejx2NwqChpo:-MP7LlNq75Ai9n6h7WL-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L940)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to do this explicitly.  The caller should initialize to this value before calling this function, so this function can set it only if there's an error.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 941 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6giBV5wrIpM85UHVy:-MP7LkuC1GD4zC8c2qnj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L941)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 942 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gjyP9cSQU7ZveRrb:-MP7LyJREL2grcflrxRP:b-nrxo7k) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L942)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `std::string(data, output_length)` to avoid having the `std::string` ctor figure out the length of the string on its own.
</blockquote></details>

Done. TIL.
___
*[src/core/ext/xds/xds_api.cc, line 945 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hTAS9eTF68EyqAcg:-MP7M1VU2OxPa_AOYFrq:b-m8o90u) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L945)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why do we need to parse JSON?  This shouldn't be necessary.
</blockquote></details>

If we cache the resources in JSON, then when we are trying assemble the `ClientConfig` proto message, we will need to parse the JSON string and build the huge proto, and finally convert it back to JSON. Alternatively, we could store the xDS resources in upb? WDYT?
___
*[src/core/ext/xds/xds_api.cc, line 955 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hX9T2EwGpyID1c_k:-MP7MRqU06LskLlh8Y34:b-mvxkxk) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L [...]

2020-12-22 16:57 UTC, markdroth reviewed
Looks like you didn't push any new commits, so I don't see any of the changes that you said were done.  So I'm leaving those comments unresolved for now.

Please let me know if you have any questions.  Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MPANONe6_jsNfK4PKEK:b-5tccjr)* status: all files reviewed, 23 unresolved discussions (waiting on @lidizheng and @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6eEHO48jILTqmho27:-MPAMReZAclym3_gOKyt:b-xvma0u) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L46)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Removed.

With CSDS, it consumes slightly more memory and cycles. Well, it's always better to have it work out-of-box.
</blockquote></details>

The main reason for adding env var guards for new features is that if we add code that starts to use an existing xDS field that we were not previously using, then if an existing xDS server is populating that field, gRPC will automatically start using it.  If we have not yet done enough integration testing to prove that the new feature works right, we don't want people to get the new behavior yet.

This isn't an issue for CSDS, because it doesn't change the behavior of the client, so that's why I don't think this guard is needed.  Storing the data doesn't hurt anything if no one actually makes a CSDS request.
___
*[src/core/ext/xds/xds_api.h, line 426 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6aRO1DzBnMZBdyLmC:-MPAH1dQA56L2RUotQNn:bcwamge) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L426)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Reordered the enum before the first method (the ctor). Following this rule, `AdsParseResult` looks like a counter example?
</blockquote></details>

You're right, that one is in the wrong place.  Feel free to move it up to right before the ctor.
___
*[src/core/ext/xds/xds_api.h, line 454 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6dgOI1RzriocOCBVE:-MPAHRqL6e45tk7UiKkp:b81h4gh) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L454)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

It did create some difficulty to find the right abstraction to avoid adding JSON-related field to `*Update` structs. The idea was commented in the CSDS design doc.

https://docs.google.com/document/d/15a2ohrjOlpbazSJXqh-aFUXmi9uKAIygoZJDrR-ctqw/edit?disco=AAAAG8DgxyI

I'm okay either way. The implemented way (or the solution proposed in the CSDS comment) has a good separation between CSDS and existing code, so it's less coupled. The latest commented solution can simplify the logic. Which solution would you prefer? It affects many other choices below.
</blockquote></details>

You're right, I had forgotten about the issue of not wanting to copy the JSON fields when we return the data to the watchers.  What I said in the design doc comment was right: we don't want to add the fields to the the `?dsUpdate` structs themselves.

This leaves two questions:
1. How do we return the JSON from the `XdsApi::ParseAdsResponse()` method?
2. How do we store the JSON in the `XdsClient` object?

For (2), what I said in the design doc comment is also correct: we should store the JSON as a new field in the `XdsClient::{Listener,RouteConfig,Cluster,Endpoint}State` structs.

For (1), I think the right way to do this is to change the definition of the `[LRCE]dsUpdateMap` such that the map value is a struct containing both the corresponding `[LRCE]dsUpdate` struct and the JSON string.  For example, for `LdsUpdateMap`, we can change the definition to this:

```
struct LdsResourceData {
  LdsUpdate resource;
  std::string json;
};
using LdsUpdateMap = std::map<std::string /* resource_name */, LdsResourceData>;
```

My rule of thumb here is that we should never create more than one map with the same key.  There's basically never any good reason to do that; it makes the code less efficient and harder to understand.  If we already have an existing map with that key, add the new value you want to track to the map's value rather than creating a new map.
___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MPAJuXh2vC7vEYtHOFk:bm2hrp5) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

I did encountered one failure: the Any encoded type wasn't presented in the symbol table. From the [json_encode.c](https://github.com/protocolbuffers/upb/blob/master/upb/json_encode.c#L38), there are many other possible failures:

* Out-of-range date, timestamp, duration
* Several bad Any packaging problem (bad type url, unrecognized type, etc.)
* Some snake case enforcement
* Field exist but value is missing

Assert seems too harsh? Alternatively, we can log the error and move on. So, even if the cache failed, xDS is still usable. What's your recommended way of handling this?
</blockquote></details>

I guess you're right, an assert is too harsh.  This is fine then.

Does this mean that if the proto we're dumping contains an Any field and the content of that Any field is unknown, that the entire proto will fail to be dumped to JSON?  That seems sub-optimal.  Maybe talk to Josh to see if there's some way we can avoid that?
___
*[src/core/ext/xds/xds_api.cc, line 945 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hTAS9eTF68EyqAcg:-MPAK_0r4ntez0LFz255:b-aobcvd) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L945)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

If we cache the resources in JSON, then when we are trying assemble the `ClientConfig` proto message, we will need to parse the JSON string and build the huge proto, and finally convert it back to JSON. Alternatively, we could store the xDS resources in upb? WDYT?
</blockquote></details>

It is not necessary to parse and then re-dump the JSON.  There are two reasonable ways to do this:
1. Store the dumped JSON for the individual resources as `Json` objects instead of as `std::string`.  Then we can construct the overall JSON for CSDS as a large `Json` object, and dump it to a string just once at the end.
2. Store the dumped JSON for the indivudual resources as `std::string` and construct the overall JSON for CSDS by directly concatenating strings.

Either of those approaches allows doing exactly what we want with doing any extra parsing or conversions.
___
*[src/core/ext/xds/xds_api.cc, line 1080 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hqEV35mVkV6ARIW2:-MPALn6P6m7qhl3jiZWz:bo1ur7b) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L1080)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Technically, with ProtoBuf, we have more contract enforcement. If we want to build JSON string directly, should we use string concatenation or our `json.h`?
</blockquote></details>

See my comment above.  Either of those approaches is fine.

Node that the actual CSDS service implementation in the wrapped language layer is going to need to convert the JSON string returned by C-core into a proto anyway, so we will still have proto contract enforcement here.


<!-- Sent from Reviewable.io -->

2020-12-29 00:33 UTC, lidizheng reviewed
This new batch contains the fix of the caching mechanism (literally map reduce) and CSDS response construction (from upb to `Json`). Previous fixes for comments are also included, sorry for the confusion.

The test case and C++ wrapper is still WIP.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MPfthjx3RKBnEmKSomX:bmxme03)* status: all files reviewed, 23 unresolved discussions (waiting on @lidizheng and @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 426 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6aRO1DzBnMZBdyLmC:-MPfnsyU7pxMpdvj_UTR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L426)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You're right, that one is in the wrong place.  Feel free to move it up to right before the ctor.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 454 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6dgOI1RzriocOCBVE:-MPfntyU-RMLEa-HGPIm:b-1pce8p) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L454)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You're right, I had forgotten about the issue of not wanting to copy the JSON fields when we return the data to the watchers.  What I said in the design doc comment was right: we don't want to add the fields to the the `?dsUpdate` structs themselves.

This leaves two questions:
1. How do we return the JSON from the `XdsApi::ParseAdsResponse()` method?
2. How do we store the JSON in the `XdsClient` object?

For (2), what I said in the design doc comment is also correct: we should store the JSON as a new field in the `XdsClient::{Listener,RouteConfig,Cluster,Endpoint}State` structs.

For (1), I think the right way to do this is to change the definition of the `[LRCE]dsUpdateMap` such that the map value is a struct containing both the corresponding `[LRCE]dsUpdate` struct and the JSON string.  For example, for `LdsUpdateMap`, we can change the definition to this:

```
struct LdsResourceData {
  LdsUpdate resource;
  std::string json;
};
using LdsUpdateMap = std::map<std::string /* resource_name */, LdsResourceData>;
```

My rule of thumb here is that we should never create more than one map with the same key.  There's basically never any good reason to do that; it makes the code less efficient and harder to understand.  If we already have an existing map with that key, add the new value you want to track to the map's value rather than creating a new map.
</blockquote></details>

Rule noted. Added `*ResourceData` struct, and updated the corresponding code.
___
*[src/core/ext/xds/xds_api.h, line 478 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6elLZDqibdfs8Kaka:-MPfoFSv6ds3g_4NG589:b8c0j5) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.h#L478)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This method should not need to take so many different maps as input.  It should basically just need one map per resource type, and those maps should basically be the existing maps in the `XdsClient` that contain all of the necessary data.
</blockquote></details>

This method is removed, as its logic being hauled into `xds_client.cc`.
___
*[src/core/ext/xds/xds_api.cc, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6fwtuCEb8E-LcFWbd:-MPfoOfuEMNSpDhCUPPS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L122)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Removed.

Good catch. Copied the comment from XdsSecurity...
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MPFvb7l-pC_N-VMyZH0:bcob096) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I guess you're right, an assert is too harsh.  This is fine then.

Does this mean that if the proto we're dumping contains an Any field and the content of that Any field is unknown, that the entire proto will fail to be dumped to JSON?  That seems sub-optimal.  Maybe talk to Josh to see if there's some way we can avoid that?
</blockquote></details>

Updated the serialization error handling to log only. It should not block the proceeding of the entire xDS-flow.

About the Any problem, it should be orthogonal to this thread. Let's wait for Josh's reply.
___
*[src/core/ext/xds/xds_api.cc, line 936 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hKWn2pTN5Nnd2Dmj:-MPfqSVT7zQKDdIc1eLM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L936)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Using `static_cast`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 945 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hTAS9eTF68EyqAcg:-MPfqWAT-wf1a6Jx4ioi:bm3ojh3) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L945)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It is not necessary to parse and then re-dump the JSON.  There are two reasonable ways to do this:
1. Store the dumped JSON for the individual resources as `Json` objects instead of as `std::string`.  Then we can construct the overall JSON for CSDS as a large `Json` object, and dump it to a string just once at the end.
2. Store the dumped JSON for the indivudual resources as `std::string` and construct the overall JSON for CSDS by directly concatenating strings.

Either of those approaches allows doing exactly what we want with doing any extra parsing or conversions.
</blockquote></details>

Used `Json` from `json.h` to construct the string. I hope the compiler can prevent as much error as possible, while concatenating strings might hide small errors that tolerated by the JSON parser.
___
*[src/core/ext/xds/xds_api.cc, line 955 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hX9T2EwGpyID1c_k:-MPfqwZLES3jaL7V5VkG:b5yrudt) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L955)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

TIL. Done.
</blockquote></details>

Function removed.
___
*[src/core/ext/xds/xds_api.cc, line 957 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6jIM8Bm2mjDL4SoQ8:-MPfqyBY4KDtaEw1nqoT:b-yikk4j) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L957)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

TODO removed.
</blockquote></details>

TIL we should better use REALTIME for timestamp that might be used outside of the gRPC library. Today, we only have `gpr_format_timespec` which assumes the `timespec` is using REALTIME.
___
*[src/core/ext/xds/xds_api.cc, line 1080 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6hqEV35mVkV6ARIW2:-MPfs09YEMSCVA_20GkY:b-9ml45t) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L1080)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

See my comment above.  Either of those approaches is fine.

Node that the actual CSDS service implementation in the wrapped language layer is going to need to convert the JSON string returned by C-core into a  [...]

2021-01-09 00:52 UTC, markdroth reviewed
This looks really good!

I have two significant comments.  One is about how upb handles `Any` fields.  The other is about making sure we come to consensus on the right behavior of CSDS w.r.t. per-resource status reporting.  If we need to add fields to the CSDS protos, let's send a PR to do that instead of waiting for someone else to do it. :)

Please let me know if you have any questions about any of this.  Thanks!

> Reviewed 22 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MQZc54N02Ki_o_YlLo5:b-gd1265)* status: all files reviewed, 23 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/xds/xds_api.h, line 437 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZSnSS1LEBCeeSJthQ:-MQZSnSS1LEBCeeSJthR:b7f3dlx) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.h#L437)):*
> ```objc
> 
>   // Synchronization status of xDS configs against the management server.
>   enum ClientConfigStatus {
> ```

This doesn't appear to be used anywhere in the `XdsApi` code.  Is it still needed?
___
*[src/core/ext/xds/xds_api.h, line 441 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZLOXSDv0SbzKsrz0a:-MQZLOXT5o-Qu-PNekbE:b-5v42gx) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.h#L441)):*
> ```objc
>     CLIENT_UNKNOWN,
>     // Client requested the config but hasn't received any config from
>     // management
> ```

Please move this back to the previous line where it was.
___
*[src/core/ext/xds/xds_api.h, line 448 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZLRRP1XHsFXh0oLSd:-MQZLRRP1XHsFXh0oLSe:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.h#L448)):*
> ```objc
>     // Client received the config and replied with NACK. Notably, the attached
>     // config dump is not the NACKed version, but the most recent accepted one.
>     // If
> ```

Same here.
___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MQZN9YJ84FO4YRsIyDD:b-grjlv5) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Updated the serialization error handling to log only. It should not block the proceeding of the entire xDS-flow.

About the Any problem, it should be orthogonal to this thread. Let's wait for Josh's reply.
</blockquote></details>

Leaving this one unresolved pending resolution of the Any problem.  My suspicion is that we need to somehow add all embedded message types into the upb symtab in order to make this work properly.
___
*[src/core/ext/xds/xds_api.cc, line 935 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZMtHN76U_UWnTMMHJ:-MQZMtHS2-QOIM7fHHSd:b-m20rgl) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L935)):*
> ```cpp
>   GPR_ASSERT(estimated_length == output_length);
>   // Parse the string into JSON structs
>   return Json::Parse(std::string(data, output_length), error);
> ```

The parameter here can use `absl::string_view` instead of `std::string`,  to avoid making an unnecessary allocation and copy of the string.
___
*[src/core/ext/xds/xds_api.cc, line 1489 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZOdhh6hktxFneukiZ:-MQZOdhh6hktxFneuki_:b-1tidqv) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1489)):*
> ```cpp
>     // Serialize into JSON and store it in the LdsUpdateMap
>     grpc_error* error = GRPC_ERROR_NONE;
>     envoy_extensions_filters_network_http_connection_manager_v3_HttpConnectionManager_getmsgdef(
> ```

What exactly does this call do?  Is this needed to load the `HttpConnectionManager` msgdef into the symtab so that it can be dumped to JSON from inside the `Any` field?  If so, does this mean that we're going to need to explicitly call the equivalent function for every message type that might possibly be embedded in an `Any` field of any xDS proto?

Does this actually need to be invoked once for every call to `LdsResponseParse()`?  I believe that the symtab has the same lifetime as the `XdsApi` object, so once this message type is loaded, maybe it doesn't need to be loaded again?
___
*[src/core/ext/xds/xds_api.cc, line 1495 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZOkyQ2XbkU_mDIHR9:-MQZOkyQ2XbkU_mDIHRA:bmijsig) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1495)):*
> ```cpp
>         symtab, &error);
>     if (error != GRPC_ERROR_NONE) {
>       gpr_log(GPR_ERROR, "Failed to serialize LDS: %s",
> ```

This should not log.  Just return the error.
___
*[src/core/ext/xds/xds_api.cc, line 1499 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPMJVBGdev1grKRKo:-MQZPMJVBGdev1grKRKp:b860f6w) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1499)):*
> ```cpp
>       GRPC_ERROR_UNREF(error);
>     } else {
>       (*lds_update_map)[listener_name].json = std::move(parsed_json);
> ```

Let's not do the map lookup twice.

```
XdsApi::LdsResourceData& lds_resource_data = (*lds_update_map)[listener_name];
lds_resource_data.json = std::move(parsed_json);
XdsApi::LdsUpdate& lds_update = lds_resource_data.resource;
```
___
*[src/core/ext/xds/xds_api.cc, line 1624 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPnHc2w2hCWBMLonV:-MQZPnHc2w2hCWBMLonW:bu9yud0) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1624)):*
> ```cpp
>         &error);
>     if (error != GRPC_ERROR_NONE) {
>       gpr_log(GPR_ERROR, "Failed to serialize RDS: %s",
> ```

Don't log, just return the error.
___
*[src/core/ext/xds/xds_api.cc, line 1628 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPoybB6PrGFBBqMjW:-MQZPoybB6PrGFBBqMjX:b-k6tpaf) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1628)):*
> ```cpp
>       GRPC_ERROR_UNREF(error);
>     } else {
>       (*rds_update_map)[route_config_name].json = std::move(parsed_json);
> ```

Don't do the map lookup twice.
___
*[src/core/ext/xds/xds_api.cc, line 1794 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPu5OAjAHzZP6bcl0:-MQZPu5OAjAHzZP6bcl1:bu9yud0) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1794)):*
> ```cpp
>         symtab, &error);
>     if (error != GRPC_ERROR_NONE) {
>       gpr_log(GPR_ERROR, "Failed to serialize CDS: %s",
> ```

Don't log, just return the error.
___
*[src/core/ext/xds/xds_api.cc, line 1798 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPzBP9DrPA4P6Mwxb:-MQZPzBP9DrPA4P6Mwxc:b-k6tpaf) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1798)):*
> ```cpp
>       GRPC_ERROR_UNREF(error);
>     } else {
>       (*cds_update_map)[cluster_name].json = std::move(parsed_json);
> ```

Don't do the map lookup twice.
___
*[src/core/ext/xds/xds_api.cc, line 2075 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPuwr7c8V7cHElU04:-MQZPuwr7c8V7cHElU05:bu9yud0) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L2075)):*
> ```cpp
>         symtab, &error);
>     if (error != GRPC_ERROR_NONE) {
>       gpr_log(GPR_ERROR, "Failed to serialize EDS: %s",
> ```

Don't log, just return the error.
___
*[src/core/ext/xds/xds_api.cc, line 2079 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZQ-AH1V8fhCcn2GR3:-MQZQ-AH1V8fhCcn2GR4:b-k6tpaf) ([raw file](https://github.com/ [...]

2021-01-11 23:24 UTC, lidizheng reviewed
Thanks for the thorough review. The handling of `Any` fields may require some processing in `XdsApi` ctor. As for adding fields, see comments below.

> Reviewed 6 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MQnhqmT229nBgcZRYZk:b-kyk9sa)* status: all files reviewed, 23 unresolved discussions (waiting on @lidizheng and @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 437 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZSnSS1LEBCeeSJthQ:-MQn-AeZCWcAu3SUqJ4R:bqv4gb5) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.h#L437)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't appear to be used anywhere in the `XdsApi` code.  Is it still needed?
</blockquote></details>

It's used in the `XdsClient`. It's the C++ representation of the client config status in CSDS, so I found it makes more sense to stay in `XdsApi`?
___
*[src/core/ext/xds/xds_api.h, line 441 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZLOXSDv0SbzKsrz0a:-MQn-XWb9aJU0CUjTwTT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.h#L441)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this back to the previous line where it was.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 448 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZLRRP1XHsFXh0oLSd:-MQn-Z712QPFYgA3v201:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.h#L448)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MQnkU219gBlp1AOpleJ:b8nrsa0) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Leaving this one unresolved pending resolution of the Any problem.  My suspicion is that we need to somehow add all embedded message types into the upb symtab in order to make this work properly.
</blockquote></details>

Added as `PreloadUpbSymbols` to be invoked by `XdsApi`'s ctor. What do you think the severity of serialization failure should be?
___
*[src/core/ext/xds/xds_api.cc, line 935 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZMtHN76U_UWnTMMHJ:-MQn-pzGEA_MYlUI-MXI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L935)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The parameter here can use `absl::string_view` instead of `std::string`,  to avoid making an unnecessary allocation and copy of the string.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1489 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZOdhh6hktxFneukiZ:-MQn13lgES7s1fQmnFjQ:b-7lkzn3) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1489)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What exactly does this call do?  Is this needed to load the `HttpConnectionManager` msgdef into the symtab so that it can be dumped to JSON from inside the `Any` field?  If so, does this mean that we're going to need to explicitly call the equivalent function for every message type that might possibly be embedded in an `Any` field of any xDS proto?

Does this actually need to be invoked once for every call to `LdsResponseParse()`?  I believe that the symtab has the same lifetime as the `XdsApi` object, so once this message type is loaded, maybe it doesn't need to be loaded again?
</blockquote></details>

Yes, we will need to load the symbols for embedded `Any` fields, but the number is not huge.

This is lifted into an individual function `PreloadUpbSymbols`, which loads all symbols needed for parsing  `Any`. Currently, the only the `HttpConnectionManager` message symbols missing is complained by upb. In foreseeable future, we need to preload all `HTTPFilters` as they are encoded as `Any`.

On the other hand, `google.protobuf.Any` present in 93 xDS protobuf files across versions to date. It could be quite verbose to preload all of them, and potentially slowing us down. Since the size needed to preload is small, I would recommend to just preload the ones needed immediately.
___
*[src/core/ext/xds/xds_api.cc, line 1495 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZOkyQ2XbkU_mDIHR9:-MQn2FbI5AKK9MXbmea1:btvjlvb) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1495)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should not log.  Just return the error.
</blockquote></details>

Changed to return the error.

If we return the error, the xDS flow will be interrupted by failed JSON serialization. Do you think that's a good tradeoff?
___
*[src/core/ext/xds/xds_api.cc, line 1499 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPMJVBGdev1grKRKo:-MQn5c_g3G2sY1sv9qLY:b1siewe) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1499)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's not do the map lookup twice.

```
XdsApi::LdsResourceData& lds_resource_data = (*lds_update_map)[listener_name];
lds_resource_data.json = std::move(parsed_json);
XdsApi::LdsUpdate& lds_update = lds_resource_data.resource;
```
</blockquote></details>

Good idea! Changed.
___
*[src/core/ext/xds/xds_api.cc, line 1624 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPnHc2w2hCWBMLonV:-MQnV-Wl0ph-NCq0CRJa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1624)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't log, just return the error.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1628 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPoybB6PrGFBBqMjW:-MQnV-tB5m58zdikpEJ2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1628)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't do the map lookup twice.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1794 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPu5OAjAHzZP6bcl0:-MQnV0Rc5wknsy3DJ9qk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1794)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't log, just return the error.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1798 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPzBP9DrPA4P6Mwxb:-MQnV0lUA5FZJ1ypQsuo:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1798)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't do the map lookup twice.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2075 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZPuwr7c8V7cHElU04:-MQnV1AF4NofftyQwMYw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L2075)):*
<details><sum [...]

2021-01-12 22:49 UTC, markdroth reviewed
This is moving in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MQsmSU89kF9npjWbIR6:b-k1b92a)* status: all files reviewed, 8 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/xds/xds_api.h, line 437 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZSnSS1LEBCeeSJthQ:-MQsazEHCe2dqXwYVLq8:bwc7g2c) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.h#L437)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

It's used in the `XdsClient`. It's the C++ representation of the client config status in CSDS, so I found it makes more sense to stay in `XdsApi`?
</blockquote></details>

If it's not used here, I would say just move it to xds_client.cc.
___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MQsbiOD9nZDSWyMChnI:bwnmevg) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Added as `PreloadUpbSymbols` to be invoked by `XdsApi`'s ctor. What do you think the severity of serialization failure should be?
</blockquote></details>

The core problem is that if we can't get a valid JSON dump here, then we can't include the resource in the CSDS response.  We need to figure out how to handle that.

I think there are two main cases to worry about here:

1. The proto contains an `Any` field that we don't look at, so we don't actually have any code to look at that field, which means that we probably don't have the proto linked in to begin with.  (I'm not worried about the case where a new `Any` field gets added to the API, because our code wouldn't print that field anyway.  But I am worried about the case where the server starts populating an existing `Any` field with a new payload type that we don't know about.)

2. The proto contains an `Any` field that we do look at, and we do have that proto linked in, but we forgot to add that proto to the symtab, so upb can't dump it to JSON.

The only reasonable way I can see to handle case 1 would be to have upb format the content of the `Any` field as bytes in the JSON output.  But I don't know if upb can do that, and I also don't know if the protobuf library will be able to handle that format when it converts the JSON back to proto in the wrapped language layer.  This would be something you'd need to investigate with Josh.

For case 2, we might be able to ameliorate it by having some sort of presubmit check that ensures that if we add a new proto, we remember to add it to the symtab.  Although if we solve case 1 by encoding as bytes, then that would also be a reasonable fallback for this case as well.

If we address those two cases, then I think serialization failures should be very rare.  If so, then we can probably handle serialization failures by just returning an error, which will cause the update to be NACKed.
___
*[src/core/ext/xds/xds_api.cc, line 1495 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZOkyQ2XbkU_mDIHR9:-MQseyGeEB9uTi_gRRbO:b5ajtf6) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1495)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Changed to return the error.

If we return the error, the xDS flow will be interrupted by failed JSON serialization. Do you think that's a good tradeoff?
</blockquote></details>

See above.  I think it's a question of how common a case this is.  If it's rare, then I think we could tolerate just failing here.

I do agree that it would be better to not reject a config for which JSON serialization fails if we can actually parse and use the config.  But if we do that, then it seems like the resource would just wind up being missing in the CSDS response, which doesn't seem like a good state to be in either.  I don't see any other reasonable options.
___
*[src/core/ext/xds/xds_client.h, line 348 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6cpeS-7loJYe_GuDY:-MQsgpvd1SNC2Ux1NbXQ:b-2w06wb) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_client.h#L348)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

We haven't heard from them for https://github.com/envoyproxy/envoy/issues/14431 for a while. For the first version we ship, as comment above, we can have per-resource version, but it would be challenging to get per-resource synchronization status:

The first issue of per-resource synchronization status is circular dependency. The dumped config is defined in `config_dump.proto` and sync status is defined in `csds.proto`, which depends on `config_dump.proto`.

The second issue is overlap. We could know which resource has been NACKed by comparing the config dump from the gRPC process and the management server.

The third issue is compatibility with existing config dumps. Since the change is going to happen in the config dump, it will apply to Envoy and all xDS servers. Do we want them to ignore this field or implement it in future?
</blockquote></details>

Taking your issues one at a time:

1. If we have to, we can define a new enum in config_dump.proto.  Or maybe we can move the enum definition to a new file that is used by both csds.proto and config_dump.proto.

2. I don't understand the problem here.  The goal of this effort is to expose the client's state.  We should not need to compare with the management server's state to determine that (and it would basically be impossible to get both states in any sort of atomic way anyway).  We want to know whether or not the client has NACKed the resource, and the client should be able to tell us that directly.

3. This is no different than any other place where we add a new field to an existing API.  It's fine for existing implementations not to populate the new field.

I've made a proposal in envoyproxy/envoy#14431 about what changes we need.  Please go ahead and create a PR proposing something, and we can iterate on that.
___
*[src/core/ext/xds/xds_client.h, line 261 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZT2U05zR0-fCRxF7z:-MQsfYtz1TWg8B0IkVvs:b-bncyvb) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_client.h#L261)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

What's the rule of thumb here? I'm using `gpr_timespec` here because previous use case (Channelz trace) uses `gpr_format_timespec` to convert time into RFC3339 and stores the timestamp in `gpr_timespec`.
</blockquote></details>

You can store it as `grpc_millis` and then convert to `gpr_timestamp` when generating the JSON, so that you can still use `gpr_format_timespec()`.

In general, we use `grpc_millis` internally.
___
*[src/core/ext/xds/xds_client.h, line 263 at r3](https://reviewable.io/reviews/grpc/grpc/25038#-MQsk1Pi14OVzXSGyR5Y:-MQsk1Pi14OVzXSGyR5Z:b-ytwxta) ([raw file](https://github.com/grpc/grpc/blob/c331f63161e05df2f6ca5f89760699769f67e212/src/core/ext/xds/xds_client.h#L263)):*
> ```objc
>     gpr_timespec update_time;
>     // The version of the resource
>     std::string version;
> ```

As per my proposal in envoyproxy/envoy#14431, I think we should record both the version that we're currently using and the most recent version that we've seen.
___
*[src/core/ext/xds/xds_client.h, line 353 at r3](https://reviewable.io/reviews/grpc/grpc/25038#-MQskycI2YUGob0kHSS5:-MQskycI2YUGob0kHSS6:bjch117) ([raw file](https://github.com/grpc/grpc/blob/c331f63161e05df2f6ca5f89760699769f67e212/src/core/ext/xds/xds_client.h#L353)):*
> ```objc
> 
>   // Stores the sync [...]

2021-02-09 03:30 UTC, lidizheng commented
PR https://github.com/grpc/grpc/pull/25272 might not be merged quickly. So, for testing, I guess I will create a method to abstract out how the test case get the config dump. The method will access internal method (`XdsClient`) for now, and fetch info using CSDS stub in future.

2021-02-09 23:07 UTC, markdroth commented
Instead of trying to abstract this out, for now, let's just add a core test that tests the XdsClient API directly.  As part of a subsequent PR that actually implements the CSDS RPC service in C++, you can add separate tests for the RPC service.

2021-02-18 00:28 UTC, lidizheng commented
Update: after copying the Proto from Envoy to gRPC, I'm able to get the CSDS service running in gRPC++. However, there is yet another mismatched field somewhere between the ground truth proto and our copied version, which caused segfault:

```
Thread 1 "xds_end2end_tes" received signal SIGSEGV, Segmentation fault.
0x000000000063f382 in google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<envoy::service::status::v3::PerXdsConfig>::TypeHandler> (this=0x807160, index=0) at external/com_google_protobuf/src/google/protobuf/repeated_field.h:1707
1707	external/com_google_protobuf/src/google/protobuf/repeated_field.h: No such file or directory.
(gdb) bt
#0  0x000000000063f382 in google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<envoy::service::status::v3::PerXdsConfig>::TypeHandler> (this=0x807160, index=0)
    at external/com_google_protobuf/src/google/protobuf/repeated_field.h:1707
#1  0x000000000063f1ee in google::protobuf::RepeatedPtrField<envoy::service::status::v3::PerXdsConfig>::Get (this=0x807160, index=0)
    at external/com_google_protobuf/src/google/protobuf/repeated_field.h:2173
#2  0x000000000063f1c4 in envoy::service::status::v3::ClientConfig::_internal_xds_config (this=0x807150, index=0)
    at bazel-out/k8-dbg/bin/src/proto/grpc/testing/xds/v3/csds.pb.h:1293
#3  0x000000000063ec3b in envoy::service::status::v3::ClientConfig::xds_config (this=0x807150, index=0)
    at bazel-out/k8-dbg/bin/src/proto/grpc/testing/xds/v3/csds.pb.h:1297
#4  0x00000000005b4af8 in grpc::testing::(anonymous namespace)::ClientStatusDiscoveryServiceTest_TestXdsClientJsonDump_Test::TestBody (this=0x7e01c0) at test/cpp/end2end/xds_end2end_test.cc:8760
...
```

Also, pasting the dumped client config:

```json
{
  "xdsConfig": [{
    "listenerConfig": {
      "dynamicListeners": [{
        "activeState": {
          "lastUpdated": "2021-02-17T16:24:40.124707135Z",
          "listener": {
            "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
            "apiListener": {
              "apiListener": {
                "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                "httpFilters": [{
                  "name": "router",
                  "typedConfig": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                  }
                }],
                "rds": {
                  "configSource": {
                    "ads": {}
                  },
                  "routeConfigName": "route_config_name"
                }
              }
            },
            "name": "server.example.com"
          },
          "versionInfo": "1"
        },
        "clientStatus": 3,
        "name": "server.example.com"
      }],
      "versionInfo": "1"
    }
  }, {
    "routeConfig": {
      "dynamicRouteConfigs": [{
        "clientStatus": 3,
        "lastUpdated": "2021-02-17T16:24:40.136707143Z",
        "routeConfig": {
          "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
          "name": "route_config_name",
          "virtualHosts": [{
            "domains": ["*"],
            "routes": [{
              "match": {
                "prefix": ""
              },
              "route": {
                "cluster": "cluster_name"
              }
            }]
          }]
        },
        "versionInfo": "1"
      }]
    }
  }, {
    "clusterConfig": {
      "dynamicActiveClusters": [{
        "clientStatus": 4,
        "cluster": {
          "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
          "edsClusterConfig": {
            "edsConfig": {
              "ads": {}
            },
            "serviceName": "eds_service_name"
          },
          "name": "cluster_name",
          "type": "EDS"
        },
        "errorState": {
          "details": "{\"created\":\"@1613607880.171090360\",\"description\":\"errors parsing CDS response\",\"file\":\"src/core/ext/xds/xds_api.cc\",\"file_line\":2295,\"referenced_errors\":[{\"created\":\"@1613607880.171083628\",\"description\":\"cluster_name: DiscoveryType is not valid.\",\"file\":\"src/core/ext/xds/xds_api.cc\",\"file_line\":2053}]}",
          "lastUpdateAttempt": "2021-02-17T16:24:40.170707208Z",
          "versionInfo": "3"
        },
        "lastUpdated": "2021-02-17T16:24:40.147707209Z",
        "versionInfo": "1"
      }],
      "versionInfo": "1"
    }
  }, {
    "endpointConfig": {
      "dynamicEndpointConfigs": [{
        "clientStatus": 3,
        "endpointConfig": {
          "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
          "clusterName": "eds_service_name",
          "endpoints": [{
            "lbEndpoints": [{
              "endpoint": {
                "address": {
                  "socketAddress": {
                    "address": "127.0.0.1",
                    "portValue": 7303
                  }
                }
              }
            }],
            "loadBalancingWeight": 3,
            "locality": {
              "region": "xds_default_locality_region",
              "subZone": "locality0",
              "zone": "xds_default_locality_zone"
            }
          }]
        },
        "lastUpdated": "2021-02-17T16:24:40.158707209Z",
        "versionInfo": "1"
      }]
    }
  }]
}
```

2021-02-22 23:31 UTC, markdroth reviewed
This is looking really good!

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 23 files at r2, 16 of 23 files at r6, 28 of 28 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MUB4ELY31IcFs9QP0-g:b-jvgm50)* status: all files reviewed, 30 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/xds/xds_api.h, line 420 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAU4NIEUC9k3NLLyR0:-MUAU4NIEUC9k3NLLyR1:b-ya3dkz) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_api.h#L420)):*
> ```objc
>       ClusterLoadReport>;
> 
>   // Parses an ADS response.
> ```

The first line of this comment should go next to `ParseAdsResponse()`, since it's about the method, not the struct.
___
*[src/core/ext/xds/xds_bootstrap.h, line 91 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAcTiJ6TBqOk_Hhcpc:-MUAcTiJ6TBqOk_Hhcpd:b-bsceo3) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_bootstrap.h#L91)):*
> ```objc
>   const XdsServer& server() const { return servers_[0]; }
>   const Node* node() const { return node_.get(); }
>   const Json& raw_node() const { return raw_node_; }
> ```

I don't think the changes to `XdsBootstrap` are needed, since we don't need to populate the node field in the CSDS response.
___
*[src/core/ext/xds/xds_client.h, line 352 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAX-id3DJpJPXPq-iJ:-MUAX-id3DJpJPXPq-iK:bq6nxjl) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.h#L352)):*
> ```objc
>       bool send_all_clusters, const std::set<std::string>& clusters);
> 
>   static void UpdateResourceMetadataAcked(ResourceMetadata& resource_metadata,
> ```

If this method is modifying `resource_metadata`, then that parameter should (a) be passed in as a pointer instead of a reference and (b) should be the last parameter of the method instead of the first.
___
*[src/core/ext/xds/xds_client.h, line 352 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAy0C47Q3QwkNBs2WI:-MUAy0C47Q3QwkNBs2WJ:byt2bp6) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.h#L352)):*
> ```objc
>       bool send_all_clusters, const std::set<std::string>& clusters);
> 
>   static void UpdateResourceMetadataAcked(ResourceMetadata& resource_metadata,
> ```

These two static methods (this one and `CreateUpdateFailureStateJson()` below) do not need to be methods on this class.  Instead, they can be standalone functions in an anonymous namespace in the .cc file.
___
*[src/core/ext/xds/xds_client.h, line 355 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAX8lsBzDaErMb_PBk:-MUAX8lsBzDaErMb_PBl:bg8l0l9) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.h#L355)):*
> ```objc
>                                           std::string version,
>                                           grpc_millis update_time);
>   void UpdatePerResourceStatesByParsedResult(XdsApi::AdsParseResult& result);
> ```

This parameter should be passed in as either a const reference or a non-const pointer.
___
*[src/core/ext/xds/xds_client.cc, line 1181 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAzE3I5u3xx43U9F2l:-MUAzE3I5u3xx43U9F2m:bx19y1v) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.cc#L1181)):*
> ```cpp
> }
> 
> void XdsClient::UpdateResourceMetadataAcked(ResourceMetadata& resource_metadata,
> ```

These two methods are methods on `XdsClient`, but they're in the middle of a bunch of methods on `XdsClient::ChannelState::AdsCallState`.  Please move them down to the appropriate place in the file.  Note that methods should be defined in the .cc file in the same order in which they are declared in the .h file.
___
*[src/core/ext/xds/xds_client.cc, line 1197 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAZo8r4fBCGLkzlmAz:-MUAZo8r4fBCGLkzlmB-:b7t9456) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.cc#L1197)):*
> ```cpp
>   if (result.parse_error == GRPC_ERROR_NONE) {
>     // ADS update is accepted
>     for (auto& p : result.lds_update_map) {
> ```

In the ACK case, which should be the common case, this will cause us to iterate over every resource in the response twice, once here and a second time in the `Acccept?dsUpdate()` methods.  I think it would be better to just call `UpdateResourceMetadataAcked()` from inside of those methods, where we are already iterating over the result.

This method, `UpdatePerResourceStatesByParsedResult()`, should be called only in the NACK case (and you can rename it accordingly).
___
*[src/core/ext/xds/xds_client.cc, line 1220 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAZHLy3dz616kGLNOb:-MUAZHLz789_HZcBoEkq:b27x7v2) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.cc#L1220)):*
> ```cpp
>     // ADS update is rejected and the resource names in the failed update is
>     // available.
>     const std::string& details = grpc_error_string(result.parse_error);
> ```

`grpc_error_string()` returns a `const char*`, so this is not a reference, it's actually a new string.  And the new string isn't actually necessary here, because we're making a new copy for each resource below anyway.

Instead, I suggest making this an `absl::string_view` to avoid unnecessary allocation.
___
*[src/core/ext/xds/xds_client.cc, line 2302 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAdFoXAXhC97WZ6uV7:-MUAdFoXAXhC97WZ6uV8:b-ou5p6v) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.cc#L2302)):*
> ```cpp
> }
> 
> std::string XdsClient::DumpClientConfigInJson() {
> ```

This function needs to acquire the mutex before reading the internal state of the `XdsClient`.
___
*[src/core/ext/xds/xds_client.cc, line 2332 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAaRCc8RBUzxFG5PNj:-MUAaRCc8RBUzxFG5PNk:b36rkxc) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.cc#L2332)):*
> ```cpp
>     dynamic_listeners.push_back(std::move(dynamic_listener));
>   }
>   // Dump the "requested" listeners
> ```

Why are we doing this only for listeners and not for the other resource types?
___
*[src/core/ext/xds/xds_client.cc, line 2334 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAaUnp6MvIx7wzSnfs:-MUAaUnp6MvIx7wzSnft:b-oz2ovn) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.cc#L2334)):*
> ```cpp
>   // Dump the "requested" listeners
>   for (auto& name :
>        chand_->ads_calld()->GetPendingResourceNames(XdsApi::kLdsTypeUrl)) {
> ```

Consider the case where the client gets a resource from the server, then the xDS stream is terminated and the client reestablishes it, and then the client sends the initial request for the resources it was previously subscribed to on the original stream.  In this case, the client will continue caching and using the old resources, so the same resource name will show up in both `listener_map_` and in `chand_->ads_calld()->GetPendingResourceNames(XdsApi::kLdsTypeUrl)`.  This will result in duplicate entries for the same resource name.

To fix this, I think we need to get the set of pending resources first, then remove entries from that set as we iterate over `listener_map_`.  That way, when we're done iterating over `listener_map_`, we know that anything left in the set of pending resources is actually a new pending resource that wasn't already in the cache.
___
*[src/core/ext/xds/xds_client.cc, line 2425 at r7](https://reviewable.io/reviews/grpc/grpc/2503 [...]

2021-03-03 02:57 UTC, lidizheng reviewed
Thanks for the detailed review!

Turned out, the ProtoBuf segfault was caused by a rookie mistake (https://github.com/grpc/grpc/pull/25568). I'm embarrassed. Anyway, I'm still working on tests. Testing CSDS is kind of verbose. Hopefully, I can get the testing work done tomorrow.

> Reviewed 28 of 325 files at r1, 15 of 18 files at r4, 13 of 23 files at r6, 21 of 28 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MUR4R_x9B7QTEsPlrUR:bykvcyf)* status: 54 of 57 files reviewed, 30 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 437 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZSnSS1LEBCeeSJthQ:-MQtA-VIEu9xNG2Szv6D:b-xgstnm) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.h#L437)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If it's not used here, I would say just move it to xds_client.cc.
</blockquote></details>

Moved to xds_client.h.
___
*[src/core/ext/xds/xds_api.h, line 420 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAU4NIEUC9k3NLLyR0:-MUUyW1xAmsnzh5U-I-v:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_api.h#L420)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The first line of this comment should go next to `ParseAdsResponse()`, since it's about the method, not the struct.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MUUyjZO518CAic0B8HJ:b-8yxh4c) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The core problem is that if we can't get a valid JSON dump here, then we can't include the resource in the CSDS response.  We need to figure out how to handle that.

I think there are two main cases to worry about here:

1. The proto contains an `Any` field that we don't look at, so we don't actually have any code to look at that field, which means that we probably don't have the proto linked in to begin with.  (I'm not worried about the case where a new `Any` field gets added to the API, because our code wouldn't print that field anyway.  But I am worried about the case where the server starts populating an existing `Any` field with a new payload type that we don't know about.)

2. The proto contains an `Any` field that we do look at, and we do have that proto linked in, but we forgot to add that proto to the symtab, so upb can't dump it to JSON.

The only reasonable way I can see to handle case 1 would be to have upb format the content of the `Any` field as bytes in the JSON output.  But I don't know if upb can do that, and I also don't know if the protobuf library will be able to handle that format when it converts the JSON back to proto in the wrapped language layer.  This would be something you'd need to investigate with Josh.

For case 2, we might be able to ameliorate it by having some sort of presubmit check that ensures that if we add a new proto, we remember to add it to the symtab.  Although if we solve case 1 by encoding as bytes, then that would also be a reasonable fallback for this case as well.

If we address those two cases, then I think serialization failures should be very rare.  If so, then we can probably handle serialization failures by just returning an error, which will cause the update to be NACKed.
</blockquote></details>

I think this is addressed by your ADS parsing logic update.
___
*[src/core/ext/xds/xds_api.cc, line 1495 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZOkyQ2XbkU_mDIHR9:-MUUyo6yCwlZDl6C-Ag9:b-rjoddg) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_api.cc#L1495)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

See above.  I think it's a question of how common a case this is.  If it's rare, then I think we could tolerate just failing here.

I do agree that it would be better to not reject a config for which JSON serialization fails if we can actually parse and use the config.  But if we do that, then it seems like the resource would just wind up being missing in the CSDS response, which doesn't seem like a good state to be in either.  I don't see any other reasonable options.
</blockquote></details>

This is also addressed by the ADS parsing logic. Now, the parsing won't fail immediately and will collect all errors.
___
*[src/core/ext/xds/xds_bootstrap.h, line 91 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAcTiJ6TBqOk_Hhcpc:-MUUzL33ChjNNy-rbtqQ:b-bdpjgb) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_bootstrap.h#L91)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think the changes to `XdsBootstrap` are needed, since we don't need to populate the node field in the CSDS response.
</blockquote></details>

This change will depend on the discussion in A40 gRFC
___
*[src/core/ext/xds/xds_client.h, line 261 at r2](https://reviewable.io/reviews/grpc/grpc/25038#-MQZT2U05zR0-fCRxF7z:-MQt8e-w21oLIAPanhKl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aabca0625807b7ce4dea17248ec6de3dda2b87e4/src/core/ext/xds/xds_client.h#L261)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can store it as `grpc_millis` and then convert to `gpr_timestamp` when generating the JSON, so that you can still use `gpr_format_timespec()`.

In general, we use `grpc_millis` internally.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.h, line 263 at r3](https://reviewable.io/reviews/grpc/grpc/25038#-MQsk1Pi14OVzXSGyR5Y:-MUUzTn1Ama2hK-DZoXk:b-2yyrgf) ([raw file](https://github.com/grpc/grpc/blob/c331f63161e05df2f6ca5f89760699769f67e212/src/core/ext/xds/xds_client.h#L263)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per my proposal in envoyproxy/envoy#14431, I think we should record both the version that we're currently using and the most recent version that we've seen.
</blockquote></details>

This is addressed by `failed_version`.
___
*[src/core/ext/xds/xds_client.h, line 352 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAX-id3DJpJPXPq-iJ:-MUVEhfa5ifLtmUgfa8Z:bg3gc2v) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.h#L352)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If this method is modifying `resource_metadata`, then that parameter should (a) be passed in as a pointer instead of a reference and (b) should be the last parameter of the method instead of the first.
</blockquote></details>

Updated. Just curious, what's the rationale for preferring pointer and placing as the last parameter? It works the same for structs.
___
*[src/core/ext/xds/xds_client.h, line 352 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAy0C47Q3QwkNBs2WI:-MUVFWRL1wXnDeqNJ_wi:bf3skbw) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.h#L352)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two static methods (this one and `CreateUpdateFailureStateJson()` below) do not need to be methods on this class.  Instead, they can be standalone functions in an anonymous namespace in the .cc file.
</blockquote></details>

Done. Moved to anonymous namespace. But this change also moved `ClientResourceStatus` and `ResourceMetadata` from private to public.
___
*[src/core/ext/xds/xds_client.h, line  [...]

2021-03-04 17:00 UTC, markdroth requested changes
This is looking pretty good!  Most of my comments are fairly minor, but I think there are some bugs here that are not being caught by the test, which suggests to me that the test needs improvement.

Please let me know if you have any questions.  Thanks!

> Reviewed 14 of 14 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MUyAh7p-VxAPxkmYOZL:bwwlp6p)* status: all files reviewed, 21 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MUuNwssALarsF2jHtBr:bi7ilt1) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

I think this is addressed by your ADS parsing logic update.
</blockquote></details>

I don't think the ADS parsing update actually addresses this at all.  The ADS parsing change means that we'll report errors from each individual resource instead of stopping at the first resource with an error.  But it does not address the problem of rejecting a valid resource simply because it includes an unknown type in an `Any` field that we're not using that will cause a JSON serialization failure.

I think we need to investigate whether how upb's JSON printing will handle the case of unknown types in `Any` fields, and we need to figure out how protobuf's JSON parsing will interpret whatever upb produces.
___
*[src/core/ext/xds/xds_bootstrap.h, line 91 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAcTiJ6TBqOk_Hhcpc:-MUxkNbT4mXUn5yGuZen:b-tm9x6g) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_bootstrap.h#L91)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

This change will depend on the discussion in A40 gRFC
</blockquote></details>

It looks like you're now having `XdsClient` get this from `XdsApi`, so there's no need for the changes to `XdsBootstrap`.
___
*[src/core/ext/xds/xds_client.h, line 352 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAX-id3DJpJPXPq-iJ:-MUxkmvX9XUVG1flisvr:b-wmo0ts) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.h#L352)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Updated. Just curious, what's the rationale for preferring pointer and placing as the last parameter? It works the same for structs.
</blockquote></details>

https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs

Until recently, the style guide recommended that parameters modified by the function be pointers instead of references.  That was recently changed, but our code-base still uses the old style.
___
*[src/core/ext/xds/xds_client.h, line 352 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAy0C47Q3QwkNBs2WI:-MUxlfX-6x9kCaHD_ahs:b7d7kc4) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.h#L352)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Done. Moved to anonymous namespace. But this change also moved `ClientResourceStatus` and `ResourceMetadata` from private to public.
</blockquote></details>

We shouldn't make `ClientResourceStatus` and `ResourceMetadata` public.  If they're required by these functions, then please move them back to being private static methods.
___
*[src/core/ext/xds/xds_client.h, line 118 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUxofpy1s3E62394pv8:-MUxofpy1s3E62394pv9:b-3qjbb4) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.h#L118)):*
> ```objc
>     std::string failed_version;
>     // Details about the last failed update attempt.
>     const char* failed_details;
> ```

Please use `std::string` here.
___
*[src/core/ext/xds/xds_client.h, line 120 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUxndVX6bntks8CdrgB:-MUxndVX6bntks8CdrgC:b-a86wd) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.h#L120)):*
> ```objc
>     const char* failed_details;
>     // Timestamp of the last failed update attempt.
>     grpc_millis failed_update_time;
> ```

Suggest initializing this to 0.
___
*[src/core/ext/xds/xds_client.cc, line 1220 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAZHLy3dz616kGLNOb:-MUxqCvp56eL8DyDMim2:b-h3li3o) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.cc#L1220)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Changed the field type of `failed_details` to `const char*`, since it would remove the need to convert the type. What's cost of making `absl::string_view` a `const char*` or `std::string`? Should we be aware of the original type of the string?
</blockquote></details>

Converting the type is not expensive; making a copy of the string is.  In general, whenever you need to make a copy, you should use `std::string` for the copy, and whenever you don't need a copy, you should use `absl::string_view`.  There is no need to preserve the type you are assigning from.

But in any case, you should not declare a `std::string&` (a reference) when assigning from a `const char*`, because assigning from a `const char*` means creating a new `std::string` object, not referencing an existing one.  And creating a new `std::string` means making a copy of the string.

I've added comments elsewhere for what to fix, so I'll resolve this one.
___
*[src/core/ext/xds/xds_client.cc, line 98 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUxmwrF-IiYa3kj4urX:-MUxmwrF-IiYa3kj4urY:bkwi0pv) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.cc#L98)):*
> ```cpp
>   void OnCallFinishedLocked();
> 
>   T* calld() const { return calld_ != nullptr ? calld_.get() : nullptr; }
> ```

This change is not necessary.  `calld_.get()` will work fine when the value is null.
___
*[src/core/ext/xds/xds_client.cc, line 691 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUxnSp10P1nCGu_75R5:-MUxnSp10P1nCGu_75R6:bupd1ez) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.cc#L691)):*
> ```cpp
> namespace {
> 
> XdsClient::ResourceMetadata UpdateResourceMetadataAcked(
> ```

Suggest calling this `CreateResourceMetadataAcked()`, since it's actually creating a whole new struct.
___
*[src/core/ext/xds/xds_client.cc, line 697 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUy9vlh3ht2z44yeDyY:-MUy9vlh3ht2z44yeDyZ:b4huwk6) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.cc#L697)):*
> ```cpp
>   resource_metadata.update_time = update_time;
>   resource_metadata.version = version;
>   resource_metadata.failed_version = "";
> ```

No need to explicitly set these to the empty string, since that's the default value for `std::string`.
___
*[src/core/ext/xds/xds_client.cc, line 699 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUyA-Og9oz_dvnF3b1h:-MUyA-Og9oz_dvnF3b1i:bf8e31f) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.cc#L699)):*
> ```cpp
>   resource_metadata.failed_version = "";
>   resource_metadata.failed_details = "";
>   resource_metadata.failed_update_time = 0;
> ```

If you initialize this to 0 in the struct definition, then you don't need to explicitly set it here.
___
*[src/core/ext/xds/xds_client.cc, line 2281 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUy--rgEghuUGTGYPSM:-MUy--rgEghuUGTGYPSN:b-ntoev7) ([raw file](https://github.com/grpc/grpc/blob [...]

2021-03-05 07:03 UTC, lidizheng reviewed
Thanks for the review! I have tested the newly added test cases with 1000x sanitizors, and the same `~XdsClient` tsan flake appeared (see https://paste.googleplex.com/5283774037229568) (this flake also appears in the fault injection PR).

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MUztLwV4UzpQnzrwutu:basl5r4)* status: 52 of 57 files reviewed, 21 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MUzB-1M7ATVfaCrBv5c:bioakwi) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think the ADS parsing update actually addresses this at all.  The ADS parsing change means that we'll report errors from each individual resource instead of stopping at the first resource with an error.  But it does not address the problem of rejecting a valid resource simply because it includes an unknown type in an `Any` field that we're not using that will cause a JSON serialization failure.

I think we need to investigate whether how upb's JSON printing will handle the case of unknown types in `Any` fields, and we need to figure out how protobuf's JSON parsing will interpret whatever upb produces.
</blockquote></details>

In current logic, serialization failure will be recognized as parsing error, and lead to NACK the ADS update.

For case 1, unknown user-provided protos: I think NACK unknown protos is the right thing to do here. The complex cases are xDS HTTP filters. E.g., users provide an optional filter config with concrete values, if gRPC failed to parse it, I think gRPC should reject this update; if users provide an optional filter config with only the filter name but left the `config` field empty, gRPC should accept the update.

For case 2, I think it is handled in the xDS HTTP Filters PR. That new filters need to implement the symbol-propagating method.

We should be in good shape here, no changes needed.
___
*[src/core/ext/xds/xds_bootstrap.h, line 91 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAcTiJ6TBqOk_Hhcpc:-MUysMoZBN3oN4IMP3dZ:b-6eoh4c) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_bootstrap.h#L91)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like you're now having `XdsClient` get this from `XdsApi`, so there's no need for the changes to `XdsBootstrap`.
</blockquote></details>

Removed in latest commit.
___
*[src/core/ext/xds/xds_client.h, line 352 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAX-id3DJpJPXPq-iJ:-MUzEC9n41BC81bfntwC:bpd1xkb) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.h#L352)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs

Until recently, the style guide recommended that parameters modified by the function be pointers instead of references.  That was recently changed, but our code-base still uses the old style.
</blockquote></details>

Interesting read.
___
*[src/core/ext/xds/xds_client.h, line 352 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAy0C47Q3QwkNBs2WI:-MUzFNfm5g8VZJei80Rs:b5a2nqu) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.h#L352)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We shouldn't make `ClientResourceStatus` and `ResourceMetadata` public.  If they're required by these functions, then please move them back to being private static methods.
</blockquote></details>

Changed back.
___
*[src/core/ext/xds/xds_client.h, line 118 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUxofpy1s3E62394pv8:-MUysOt3-uPYI1FVwRyg:bv2i3cf) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.h#L118)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `std::string` here.
</blockquote></details>

Done in the latest commit.
___
*[src/core/ext/xds/xds_client.h, line 120 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUxndVX6bntks8CdrgB:-MUyskzU6ERDGf5dWJ1w:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.h#L120)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest initializing this to 0.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 1220 at r7](https://reviewable.io/reviews/grpc/grpc/25038#-MUAZHLy3dz616kGLNOb:-MUu_BEj6zAA3x-xC-uz:bxacz0y) ([raw file](https://github.com/grpc/grpc/blob/fb43c8bfe259e2adf4b0c58cb7220bbe695ed908/src/core/ext/xds/xds_client.cc#L1220)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Converting the type is not expensive; making a copy of the string is.  In general, whenever you need to make a copy, you should use `std::string` for the copy, and whenever you don't need a copy, you should use `absl::string_view`.  There is no need to preserve the type you are assigning from.

But in any case, you should not declare a `std::string&` (a reference) when assigning from a `const char*`, because assigning from a `const char*` means creating a new `std::string` object, not referencing an existing one.  And creating a new `std::string` means making a copy of the string.

I've added comments elsewhere for what to fix, so I'll resolve this one.
</blockquote></details>

 I have updated the receiving type to `absl::string_view`, and convert to std::string before coping.

Thanks for detailed explanation!
___
*[src/core/ext/xds/xds_client.cc, line 98 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUxmwrF-IiYa3kj4urX:-MUytCgR8u6XTU5rAMXw:be47yta) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.cc#L98)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This change is not necessary.  `calld_.get()` will work fine when the value is null.
</blockquote></details>

Done.

It was `HasActiveAdsCall` that won't handle null values.
___
*[src/core/ext/xds/xds_client.cc, line 691 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUxnSp10P1nCGu_75R5:-MUytQ5_EZrREqnFF1-D:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.cc#L691)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `CreateResourceMetadataAcked()`, since it's actually creating a whole new struct.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 697 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUy9vlh3ht2z44yeDyY:-MUyuMf09WqdpaUxj8sn:br64a21) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.cc#L697)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to explicitly set these to the empty string, since that's the default value for `std::string`.
</blockquote></details>

TIL, only primitive types will be indeterministic in stack allocation. Done. 
___
*[src/core/ext/xds/xds_client.cc, line 699 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUyA-Og9oz_dvnF3b1h:-MUyu_smCByDaqEJuaHI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.cc#L699)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I [...]

2021-03-06 00:07 UTC, markdroth requested changes
This is getting closer.  I think the main things to resolve are the NACK problem and improving the tests.

The TSAN failure you reported was recently fixed by Alex in #25485.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MV3911zCm9cJ23OuZRT:b148yjf)* status: all files reviewed, 19 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MV39tz05TaZEUPzt7eK:b-llko69) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

In current logic, serialization failure will be recognized as parsing error, and lead to NACK the ADS update.

For case 1, unknown user-provided protos: I think NACK unknown protos is the right thing to do here. The complex cases are xDS HTTP filters. E.g., users provide an optional filter config with concrete values, if gRPC failed to parse it, I think gRPC should reject this update; if users provide an optional filter config with only the filter name but left the `config` field empty, gRPC should accept the update.

For case 2, I think it is handled in the xDS HTTP Filters PR. That new filters need to implement the symbol-propagating method.

We should be in good shape here, no changes needed.
</blockquote></details>

I don't think NACKing is the right thing to do here.

For HTTP filters, the whole point of the `is_optional` field is to allow the client to accept a config when it does not support the filter.  If it does not support the filter, then it also will not know about the filter's config.  So basically, any case with an optional filter will cause us to NACK.  This completely defeats the purpose of `is_optional`.

But this issue is really not just about HTTP filters.  That's one particular case of an `Any` field, but it's not the only case we need to worry about here.  Consider what would happen if a new extension point is added to xDS that we don't support yet.  There would be an `Any` field in the proto, but we would not looking be at that field at all, so it shouldn't matter to us if there's an unknown proto type inside of it.  But because the type is unknown, the JSON serialization would fail, which would cause us to NACK a config that we would otherwise be totally capable of using.

For case 2, the HTTP filter PR addresses the problem for HTTP filters specifically, but it doesn't help for other types of `Any` fields.

If we can't figure out a way to make this work with JSON, we may have to give up on the JSON approach and instead export the data as serialized protobufs.
___
*[src/core/ext/xds/xds_api.cc, line 822 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV39ivF888CA6h9nqj7:-MV39ivG3AqxtMbkTFrb:b5kem23) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_api.cc#L822)):*
> ```cpp
>                             std::vector<grpc_error*>* errors) {
>   upb_status status;
>   // This placeholder is needed to make UBSAN happy.
> ```

This smells like a upb bug.  @haberman, any reason why we can't pass null to `upb_json_encode()` here?
___
*[src/core/ext/xds/xds_api.cc, line 2358 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3dok524I7an8o2HB-:-MV3dok524I7an8o2HB0:b-504f2m) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_api.cc#L2358)):*
> ```cpp
>           locality_lb_endpoints);
>   if (locality == nullptr) {
>     // Otherwise, it might cause segfault.
> ```

No need for this comment; it's clear from the code what's going on here.
___
*[src/core/ext/xds/xds_bootstrap.h, line 111 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3dw2K14xOBB5gCZok:-MV3dw2K14xOBB5gCZol:bvp45uw) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_bootstrap.h#L111)):*
> ```objc
>   absl::InlinedVector<XdsServer, 1> servers_;
>   std::unique_ptr<Node> node_;
>   Json raw_node_;
> ```

This is no longer needed.
___
*[src/core/ext/xds/xds_client.h, line 295 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3g9w42jCieM2e3YiJ:-MV3g9w42jCieM2e3YiK:b3thplw) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_client.h#L295)):*
> ```objc
>     grpc_millis failed_update_time = 0;
>     // The client status of this resource.
>     ClientResourceStatus client_status;
> ```

This should be initialized to `UNKNOWN`.
___
*[src/core/ext/xds/xds_client.cc, line 2281 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUy--rgEghuUGTGYPSM:-MV3euAJAjcY4xW_uN5a:bt9zbgd) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7adad1619df3a81/src/core/ext/xds/xds_client.cc#L2281)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Removed. I thought it could save the string allocation of parse_error.
</blockquote></details>

There is no string allocation to avoid here, since `grpc_error_string()` does not return a new string.

Anyway, this looks good now.
___
*[src/core/ext/xds/xds_client.cc, line 689 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3eTqP4pTHIZJv75vk:-MV3eTqP4pTHIZJv75vl:b-wxwkel) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_client.cc#L689)):*
> ```cpp
> //
> 
> XdsClient::ResourceMetadata XdsClient::CreateResourceMetadataAcked(
> ```

These are methods of `XdsClient`.  Please move them to the appropriate place in the file, rather than sticking them on their own here, in between two other classes.
___
*[src/core/ext/xds/xds_client.cc, line 2279 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3hHdN3QnC5_MWCoQv:-MV3hHdN3QnC5_MWCoQw:bnc6dfz) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_client.cc#L2279)):*
> ```cpp
>   for (auto& name : result.resource_names_failed) {
>     ResourceMetadata* resource_metadata = nullptr;
>     if (listener_map_.find(name) != listener_map_.end()) {
> ```

Instead of searching in every one of these maps, you can figure out which one to look in by checking the value of `result.type_url`.
___
*[src/core/ext/xds/xds_client.cc, line 2291 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3hZuVEqTRtHxgKMig:-MV3hZuVEqTRtHxgKMih:badenp6) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_client.cc#L2291)):*
> ```cpp
>       resource_metadata = &endpoint_map_[name].meta;
>     }
>     if (resource_metadata == nullptr) {
> ```

Will this ever actually be null?  In what case will that happen?
___
*[src/core/ext/xds/xds_client.cc, line 2412 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3ftIRAMcx5eoOFLg6:-MV3f_UU9c-fHxEOJ743:b-buxl6k) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_client.cc#L2412)):*
> ```cpp
>       // active.
>       if (listener_map_.find(name) != listener_map_.end()) {
>         if (listener_map_[name].meta.client_status !=
> ```

This basically duplicates the map lookup that you've already done on the previous line.  Instead of doing the lookup again, you should save the iterator returned from `find()` and reuse it here.

That having been said, it's not clear to me why you need to check if the status is UNKNOWN here in the first place.  I don't think that can happen here, can it?

Same thing for all of the resource types here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8775 at r9](https://reviewable.io/reviews/grpc/grpc/25038#-MUy6L1sCktLNzBTI_E8:-MV3l4aY0VtgDQP8KPO9:b3zxj2q) ([raw file](https://github.com/grpc/grpc/blob/e2c5cc534b98e79e9e4b79c7a7ad [...]

2021-03-09 02:36 UTC, lidizheng reviewed
Updated the cache format. I will try to get to the gMock matcher tomorrow.

> Reviewed 13 of 325 files at r1, 6 of 23 files at r6, 17 of 28 files at r7, 5 of 14 files at r9, 15 of 22 files at r12, 12 of 14 files at r14.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MVJn9Mn5Jg_JHrayYTj:bu2o9sb)* status: 49 of 56 files reviewed, 18 unresolved discussions (waiting on @haberman, @lidizheng, and @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 930 at r1](https://reviewable.io/reviews/grpc/grpc/25038#-MP6gJzDCDlCBUASX9j2:-MV4TpAuCJiIMBhj4fta:bw84tn4) ([raw file](https://github.com/grpc/grpc/blob/4678f53af403b57deac1bc428efe4aba8f6f6d6f/src/core/ext/xds/xds_api.cc#L930)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think NACKing is the right thing to do here.

For HTTP filters, the whole point of the `is_optional` field is to allow the client to accept a config when it does not support the filter.  If it does not support the filter, then it also will not know about the filter's config.  So basically, any case with an optional filter will cause us to NACK.  This completely defeats the purpose of `is_optional`.

But this issue is really not just about HTTP filters.  That's one particular case of an `Any` field, but it's not the only case we need to worry about here.  Consider what would happen if a new extension point is added to xDS that we don't support yet.  There would be an `Any` field in the proto, but we would not looking be at that field at all, so it shouldn't matter to us if there's an unknown proto type inside of it.  But because the type is unknown, the JSON serialization would fail, which would cause us to NACK a config that we would otherwise be totally capable of using.

For case 2, the HTTP filter PR addresses the problem for HTTP filters specifically, but it doesn't help for other types of `Any` fields.

If we can't figure out a way to make this work with JSON, we may have to give up on the JSON approach and instead export the data as serialized protobufs.
</blockquote></details>

As discussed in emails, ProtoBuf-JSON does have forward compatibility issues. Using ProtoBuf wire format as message cache instead. This should defer the parsing the unknown Any fields to the end consumers.
___
*[src/core/ext/xds/xds_api.cc, line 822 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV39ivF888CA6h9nqj7:-MV4A5hf2382NBZcR3Wl:bcj4ac8) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_api.cc#L822)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This smells like a upb bug.  @haberman, any reason why we can't pass null to `upb_json_encode()` here?
</blockquote></details>

Just adding info here: It's caused by this line: https://github.com/protocolbuffers/upb/blob/97e2aeb7ee62a979f4b0a7c2bb9325d77cac0ae4/upb/json_encode.c#L701
___
*[src/core/ext/xds/xds_api.cc, line 2358 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3dok524I7an8o2HB-:-MV4AYWi54zlEkWYKWvg:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_api.cc#L2358)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this comment; it's clear from the code what's going on here.
</blockquote></details>

Removed.
___
*[src/core/ext/xds/xds_bootstrap.h, line 111 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3dw2K14xOBB5gCZok:-MV4Ab2l8VJptxG7akTF:b6zrrk4) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_bootstrap.h#L111)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is no longer needed.
</blockquote></details>

Good catch!
___
*[src/core/ext/xds/xds_client.h, line 295 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3g9w42jCieM2e3YiJ:-MV4AiS26NqZdjZYorqR:bx09m8t) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_client.h#L295)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be initialized to `UNKNOWN`.
</blockquote></details>

Done. So, `enum` are also primitive types that won't be initialized by C++?
___
*[src/core/ext/xds/xds_client.cc, line 689 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3eTqP4pTHIZJv75vk:-MV4B5iw4FUihdMPHPGw:bp0w93s) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_client.cc#L689)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These are methods of `XdsClient`.  Please move them to the appropriate place in the file, rather than sticking them on their own here, in between two other classes.
</blockquote></details>

Moved to above `DumpClientConfigInJson`.

(I put them here because they are used by methods of `AdsCallState`, I thought it's better to define before use.)
___
*[src/core/ext/xds/xds_client.cc, line 2279 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3hHdN3QnC5_MWCoQv:-MV4BtvcBklfZExvaIEg:b-ydonj4) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_client.cc#L2279)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of searching in every one of these maps, you can figure out which one to look in by checking the value of `result.type_url`.
</blockquote></details>

Done. Good idea!
___
*[src/core/ext/xds/xds_client.cc, line 2291 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3hZuVEqTRtHxgKMig:-MV4BvQN1qZApUUtN9fU:bmwhqz8) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_client.cc#L2291)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Will this ever actually be null?  In what case will that happen?
</blockquote></details>

It won't be null, but sanitizers complain that there is a risk.
___
*[src/core/ext/xds/xds_client.cc, line 2412 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3ftIRAMcx5eoOFLg6:-MV4Zxig47EmFdFUEDvi:b2jqhtx) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/src/core/ext/xds/xds_client.cc#L2412)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This basically duplicates the map lookup that you've already done on the previous line.  Instead of doing the lookup again, you should save the iterator returned from `find()` and reuse it here.

That having been said, it's not clear to me why you need to check if the status is UNKNOWN here in the first place.  I don't think that can happen here, can it?

Same thing for all of the resource types here.
</blockquote></details>

Updated to use iterator.

The UNKNOWN check is needed for all REQUESTED test cases. Based on gdb, when `ResourceState::Start` is invoked, the xDS resource already exists in the map. I haven't gone through all the code here, but the map entry is indeed created somewhere, probably by accident.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 38 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3iT6PBgSsdSyFE5T8:-MV4CPtD5o_pNMVQ23_3:b-d83aar) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/test/cpp/end2end/xds_end2end_test.cc#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This include should go up next to the gmock and gtest includes.
</blockquote></details>

Removed. This `time_util` isn't used in the latest commit.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1766 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3jsib4OxI0S1o2IFl:-MV4CY7_6kjaIP7RZ6sp:b1mc7pz) ([raw file](https://github.com/grpc/grp [...]

2021-03-10 01:43 UTC, lidizheng reviewed
Thanks to the review comments, the logic of porting `ResourceMetadata` from xds_client.cc to xds_api.cc is simpler now.

Apart from resolving the comments, there is also some update for testing logic:

1. Added a TestType variety "use_csds_streaming", which tells CSDS to fetch configs via streaming calls instead of unary calls;
2. Used gMock matchers to validate CSDS responses.

PTALA.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MVO6Aii-fRRL-DgqXRv:b-d44awv)* status: 32 of 56 files reviewed, 26 unresolved discussions (waiting on @lidizheng and @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 315 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVMx8UD3zVOlegG41sf:-MVO78a-A1daVVE7sBTt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.h#L315)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this field `serialized_proto`.

Same for all resource types.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 479 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVMzF6a1fiFZn1mPWEo:-MVO8BH5A3M4mSDN8uK7:b55uj2u) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.h#L479)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be moved inside of `ResourceMetadata`.
</blockquote></details>

This is used directly in xds_client.cc. If we further nest it, it might make the line setting the status quite long. Can we keep current layering?
___
*[src/core/ext/xds/xds_api.h, line 500 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVMxVxc80E2en6RPIAu:-MVOMCu_0LKsOoJHFNEh:b700f6d) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.h#L500)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of making this a field in `ResourceMetadata`, let's make it part of the map structure, so that we're using a two-level map (type_url -> resource_name -> value).
</blockquote></details>

Done. Updated to be part of `PerXdsResourceMetadataMap`.
___
*[src/core/ext/xds/xds_api.h, line 502 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVMzAO_9pK3GvWW7ULY:-MVO9ahu0b8FShat0BbV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.h#L502)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `serialized_proto`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 504 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN9Y6U6UPOVj2nDxO8:-MVO9bgUC99sK0vZ5wDr:b6zrrk4) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.h#L504)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be initialized to 0.
</blockquote></details>

Good catch!
___
*[src/core/ext/xds/xds_api.h, line 514 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVMzvrq8ePkU1RorIOp:-MVO9dY63YYaDrZo_nZz:b-yu6lyf) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.h#L514)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's make this the first field in this struct, since its value dictates which of the other fields will be populated.
</blockquote></details>

Make sense. Done.
___
*[src/core/ext/xds/xds_api.h, line 518 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN-iQlCaDpBf6aD1aF:-MVOjCdsBQ708MCH2WpA:bag5iby) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.h#L518)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should not need to create a copy for either the key or the value here.  The key can be `absl::string_view`, and the value can be `const ResourceMetadata*`.  Both of them can point into the data stored in the `XdsClient`.
</blockquote></details>

Updated. With the removal of "pending" related logic, this change is much easier.
___
*[src/core/ext/xds/xds_api.h, line 574 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN07GK3gbz9_Rx6KUB:-MVOaIlsDz-Yc3NXRsKn:bcvjgzp) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.h#L574)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest combining these two parameters into a single data structure to avoid repeated map lookups.  We can do something like this:

```
struct ResourceTypeMetadata {
  ResourceMetadataMap resource_metadata_map;
  absl::string_view resource_type_version;
};
using ResourceTypeMetadataMap =
    std::map<absl::string_view /* type_url */, ResourceTypeMetadata>;
```

Then we can just pass in a `ResourceTypeMetadataMap` containing everything we need.
</blockquote></details>

Good idea. Done.
___
*[src/core/ext/xds/xds_api.cc, line 1320 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN1TTmE5XaRKUhGcnP:-MVOaU94Au62w0E-8Dk0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.cc#L1320)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to add braces here.  This was fine the way it was, all on one line.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2981 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN23tg3Q6T-bgcHpTC:-MVOayq65bS85JyIa5ky:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.cc#L2981)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please pass `EncodingContext` into this function instead of passing in the arena directly.  Even though we currently don't need any of the other fields, we may need them in the future, and this keeps the APIs consistent across all of the helper functions.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2990 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN2FSt7xyN5yzd5ia8:-MVOazATCGxHqNx4E3D4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.cc#L2990)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please pass `EncodingContext` into this function instead of passing in the arena directly.  Even though we currently don't need any of the other fields, we may need them in the future, and this keeps the APIs consistent across all of the helper functions.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 3050 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN2O3nCBQzJSA4yfaK:-MVOgtMM4FkJAPDec9CV:bwdkntt) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.cc#L3050)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`find()` does not return a reference, it returns new iterator instance by value.  This should just be `auto`, not `const auto&`.

The fact that this works is a very bizarre special case in the compiler, and not something we want to be depending on.  For details, see https://abseil.io/tips/101 (case 8) and https://abseil.io/tips/107.

I've noticed that you seem to make this mistake systematically everywhere.  Please fix throughout this PR, and try to remember for the future.  Thanks!
</blockquote></details>

Done. This is a good article. I always wonder how this 3x3 combination impact the copy behavior.
___
*[src/core/ext/xds/xds_api.cc, line 3052 at r [...]

2021-03-11 01:06 UTC, markdroth requested changes
This is getting closer.  The structure of the matchers in the tests still needs some work.

Please let me know if you have any questions.  Thanks!

> Reviewed 19 of 24 files at r16, 5 of 5 files at r17.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MVToJFaAmuuEX3S1qoD:b-wc9ddy)* status: all files reviewed, 24 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/xds/xds_api.h, line 479 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVMzF6a1fiFZn1mPWEo:-MVS4M_9A7_8bIcEroYc:b52gyli) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.h#L479)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

This is used directly in xds_client.cc. If we further nest it, it might make the line setting the status quite long. Can we keep current layering?
</blockquote></details>

I think it's more important to make the API understandable than it is to minimize line length.  Putting this enum inside of the only struct where it is ever used makes clear that it's not something anyone needs to know about if they're not using that struct.  If that weren't important, then we'd never have any nested structs, and everything would always be defined at the global level.
___
*[src/core/ext/xds/xds_api.h, line 496 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVS4x8JAJrE3_QIlSKX:-MVS4x8JAJrE3_QIlSKY:b-6g4xsr) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_api.h#L496)):*
> ```objc
>     NACKED
>   };
>   static_assert(static_cast<int>(envoy_admin_v3_UNKNOWN) ==
> ```

I don't think we're actually using the `UNKNOWN` value anywhere anymore, so this particular assert isn't needed.  We probably don't need that element in our enum, either.
___
*[src/core/ext/xds/xds_api.h, line 533 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVS597i9sbimjMs1xCI:-MVS597i9sbimjMs1xCJ:b-w9835u) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_api.h#L533)):*
> ```objc
>       std::map<absl::string_view /*resource_name*/, const ResourceMetadata*>;
> 
>   struct PerXdsResourceMetadata {
> ```

Please call this `ResourceTypeMetadata`.  The prefix `PerXds` doesn't really tell the reader what this is for.
___
*[src/core/ext/xds/xds_api.h, line 538 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVS5Ca851EHvOsCKaka:-MVS5Ca851EHvOsCKakb:b-eea17g) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_api.h#L538)):*
> ```objc
>   };
> 
>   using PerXdsResourceMetadataMap =
> ```

Please call this `ResourceTypeMetadataMap`.
___
*[src/core/ext/xds/xds_api.cc, line 2981 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN23tg3Q6T-bgcHpTC:-MVS8YI04xdUk44YQQQc:bh4dwe1) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.cc#L2981)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For consistency with the other helper functions, please make the `EncodingContext` the first argument.
___
*[src/core/ext/xds/xds_api.cc, line 2990 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN2FSt7xyN5yzd5ia8:-MVSAqO_Eu0jrTFc0_ys:bg6g367) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.cc#L2990)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same here: Please make `EncodingContext` the first argument.
___
*[src/core/ext/xds/xds_api.cc, line 3052 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN5v2u55MSh2l4Ux0g:-MVSQTJ95SiKUGjgtEIC:b-3fw528) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.cc#L3052)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Envoy's ConfigDump only has "version_info" field in LDS and CDS, but not RDS and EDS. The ultimate solution might be updating their proto again.
</blockquote></details>

Ah, I see -- for RDS and EDS, it's in the nested `Dynamic{Route,Endpoint}Config` struct instead.  Okay, that's fine.
___
*[src/core/ext/xds/xds_api.cc, line 3034 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVSTw5i5aIcAtA6l0oy:-MVSTw5i5aIcAtA6l0oz:bjat7uo) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_api.cc#L3034)):*
> ```cpp
>   // Create the "containers" for xDS configs
>   auto* client_config = envoy_service_status_v3_ClientConfig_new(arena.ptr());
>   auto* listener_per_xds_config =
> ```

How about reordering this code to do everything related to a given resource type together in one place?  I think that would make it easier to follow.

```
auto* client_config = envoy_service_status_v3_ClientConfig_new(arena.ptr());
for (const auto& p : per_xds_resource_metadata_map) {
  absl::string_view resource_type = p.first;
  const PerXdsResourceMetadata& resource_type_metadata = p.second;
  if (resource_type == kLdsUri) {
    auto* listener_per_xds_config =
        envoy_service_status_v3_ClientConfig_add_xds_config(client_config,
                                                            arena.ptr());
    auto* listener_config_dump =
        envoy_admin_v3_ListenersConfigDump_new(arena.ptr());
    envoy_service_status_v3_PerXdsConfig_set_listener_config(
        listener_per_xds_config, listener_config_dump);
    for (const auto& q : resource_type_metadata.metadata_map) {
      absl::string_view resource_name = q.first;
      const ResourceMetadata& metadata = *q.second;
      // ...add LDS resource to listener_config_dump...
    }
  } else if (resource_type == kRdsUri) {
    // ...
  } else if (resource_type == kCdsUri) {
    // ...
  } else if (resource_type == kEdsUri) {
     // ...
  }
}
```

You might even be able to move some of the code for the individual resources into a templated helper function to avoid some of the duplication.
___
*[src/core/ext/xds/xds_api.cc, line 3082 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVSTPQt26Duc7aZvYsV:-MVSTPQt26Duc7aZvYsW:bw7pvc6) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_api.cc#L3082)):*
> ```cpp
>   // Put the xDS configs into "containers"
>   for (auto& per_xds_resource_metadata : per_xds_resource_metadata_map) {
>     const absl::string_view& type_url = per_xds_resource_metadata.first;
> ```

`absl::string_view` has sufficiently small storage size that there's no real overhead of copying, so it should be treated as a POD type.  No need to make this a const reference.

Same thing throughout.
___
*[src/core/ext/xds/xds_client.cc, line 54 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVNNxBB0s14EZojBiTg:-MVSUmZkB2y0sFP-Dx5V:b28zi1k) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_client.cc#L54)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

You removed it from xds_client.h, but it's still here in xds_client.cc.
___
*[src/core/ext/xds/xds_client.cc, line 2274 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVNCUFe7CzstvSPppUw:-MVSe4En9QY3ZY86I-Uu:bwh0aqq) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_client.cc#L2274)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Done. Just curious here, when I'm using the type url, I wonder why don't we use an `enum` type in most part and have a enum-string map if the real value is needed?
</blockquote></details>

Please use `else` for the `kRdsTypeUrl` case as well.

I thought about using an enum originally, but it t [...]

2021-03-13 01:08 UTC, lidizheng reviewed
Thanks for the review! I have updated the structure of the matchers and addressed other comments. (If the matchers still doesn't work, can you point me to an ideal usage of matchers?)

> Reviewed 16 of 24 files at r16.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MVd6PDn30EytOxDhjZs:b56lxpb)* status: all files reviewed, 24 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 479 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVMzF6a1fiFZn1mPWEo:-MVYWiNY3SLqQGuWVsmJ:b-u7qdx8) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.h#L479)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think it's more important to make the API understandable than it is to minimize line length.  Putting this enum inside of the only struct where it is ever used makes clear that it's not something anyone needs to know about if they're not using that struct.  If that weren't important, then we'd never have any nested structs, and everything would always be defined at the global level.
</blockquote></details>

Done. Previously, I found `XdsApi::ACKED` looks nice, and hoped to use it for other scenarios. But in this case, the `ClientResourceStatus` enum is only used by `ResourceMetadata`. I agree it is indeed a better idea to nest the struct.
___
*[src/core/ext/xds/xds_api.h, line 496 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVS4x8JAJrE3_QIlSKX:-MVTwstv4yTZsQr5GFG8:bd929qn) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_api.h#L496)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we're actually using the `UNKNOWN` value anywhere anymore, so this particular assert isn't needed.  We probably don't need that element in our enum, either.
</blockquote></details>

Removed the `UNKNOWN` enum.
___
*[src/core/ext/xds/xds_api.h, line 533 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVS597i9sbimjMs1xCI:-MVTx-Rf74QAjTS1rdT6:b-jkjy14) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_api.h#L533)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `ResourceTypeMetadata`.  The prefix `PerXds` doesn't really tell the reader what this is for.
</blockquote></details>

Updated. `PerXds` is following Envoy's naming style `envoy.service.status.v3.PerXdsConfig`.
___
*[src/core/ext/xds/xds_api.h, line 538 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVS5Ca851EHvOsCKaka:-MVTy_ZQ7SGuuknG9vgs:b-bw8e14) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_api.h#L538)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `ResourceTypeMetadataMap`.
</blockquote></details>

Updated.
___
*[src/core/ext/xds/xds_api.cc, line 2981 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN23tg3Q6T-bgcHpTC:-MVTyi0--LkdHPSAdrj6:b-bw8e14) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.cc#L2981)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

For consistency with the other helper functions, please make the `EncodingContext` the first argument.
</blockquote></details>

Updated.
___
*[src/core/ext/xds/xds_api.cc, line 2990 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVN2FSt7xyN5yzd5ia8:-MVTyj9z5iNBsdaZly8h:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_api.cc#L2990)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here: Please make `EncodingContext` the first argument.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 3034 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVSTw5i5aIcAtA6l0oy:-MVYdv_M0OuAvEAmY5M0:b-g2eod6) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_api.cc#L3034)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about reordering this code to do everything related to a given resource type together in one place?  I think that would make it easier to follow.

```
auto* client_config = envoy_service_status_v3_ClientConfig_new(arena.ptr());
for (const auto& p : per_xds_resource_metadata_map) {
  absl::string_view resource_type = p.first;
  const PerXdsResourceMetadata& resource_type_metadata = p.second;
  if (resource_type == kLdsUri) {
    auto* listener_per_xds_config =
        envoy_service_status_v3_ClientConfig_add_xds_config(client_config,
                                                            arena.ptr());
    auto* listener_config_dump =
        envoy_admin_v3_ListenersConfigDump_new(arena.ptr());
    envoy_service_status_v3_PerXdsConfig_set_listener_config(
        listener_per_xds_config, listener_config_dump);
    for (const auto& q : resource_type_metadata.metadata_map) {
      absl::string_view resource_name = q.first;
      const ResourceMetadata& metadata = *q.second;
      // ...add LDS resource to listener_config_dump...
    }
  } else if (resource_type == kRdsUri) {
    // ...
  } else if (resource_type == kCdsUri) {
    // ...
  } else if (resource_type == kEdsUri) {
     // ...
  }
}
```

You might even be able to move some of the code for the individual resources into a templated helper function to avoid some of the duplication.
</blockquote></details>

Split the config dump logic to 4 sub-functions, like other parts of the code. And updated the main function to the suggested flow.
___
*[src/core/ext/xds/xds_api.cc, line 3082 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVSTPQt26Duc7aZvYsV:-MVU14et3c1RzuJv2HRo:bwmx8j) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_api.cc#L3082)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`absl::string_view` has sufficiently small storage size that there's no real overhead of copying, so it should be treated as a POD type.  No need to make this a const reference.

Same thing throughout.
</blockquote></details>

TIL, done. It's like a pointer. Here we don't need to worry about lifespan of the "name" field strings, so we can use them.
___
*[src/core/ext/xds/xds_client.cc, line 54 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVNNxBB0s14EZojBiTg:-MVU27bRBwcyxui0_IfU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_client.cc#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You removed it from xds_client.h, but it's still here in xds_client.cc.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2274 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVNCUFe7CzstvSPppUw:-MVU4kKLCuFkA7nAPB3Z:b-3xorgy) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/src/core/ext/xds/xds_client.cc#L2274)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `else` for the `kRdsTypeUrl` case as well.

I thought about using an enum originally, but it turns out not to buy us much.  We'd basically be constantly converting back and forth between them, and there are a couple of cases where the code also needs to be able to handle arbitrary resource types, although they shouldn't happen in practice.
</blockquote></details>

Done. Sounds good.
___
*[src/core/ext/xds/xds_client.cc, line 886 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVSd3mF7ZElOOP2UB8B:-MVU2TzGCv2YIdTyXmKe:b-896fix) ([ [...]

2021-03-15 20:53 UTC, markdroth requested changes
This is getting closer!

The matcher structure is much nicer now.  I've added a few comments to make it even clearer.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r18.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MVreU_n698BpDgyvVDg:bsrb44n)* status: all files reviewed, 22 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/xds/xds_api.h, line 522 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVqzk603R0T8raShTNy:-MVqzk603R0T8raShTNz:bcfmelx) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_api.h#L522)):*
> ```objc
>       std::map<absl::string_view /*type_url*/, ResourceTypeMetadata>;
>   static_assert(
>       static_cast<int>(envoy_admin_v3_REQUESTED) ==
> ```

Instead of casting both enum values to ints, just cast one to the other:

```
static_assert(
    static_cast<ResourceMetadata::ClientResourceStatus>(envoy_admin_v3_REQUESTED) ==
        ResourceMetadata::ClientResourceStatus::REQUESTED,
    "");
```
___
*[src/core/ext/xds/xds_api.h, line 592 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVr1eWXBZak1plvOMLZ:-MVr1eWXBZak1plvOML_:b-ls3821) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_api.h#L592)):*
> ```objc
>   // Assemble the client config proto message and return the serialized result.
>   std::string AssembleClientConfig(
>       const ResourceTypeMetadataMap& per_xds_resource_metadata_map);
> ```

Please call the parameter `resource_type_metadata_map`.
___
*[src/core/ext/xds/xds_api.cc, line 2997 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVr-7OB0JOlUhC2qTX4:-MVr-7OB0JOlUhC2qTX5:bcev24l) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_api.cc#L2997)):*
> ```cpp
> namespace {
> google_protobuf_Timestamp* GrpcMillisToTimestamp(const EncodingContext& context,
>                                                  const grpc_millis& value) {
> ```

`grpc_millis` is a pod type, so it can be passed in by value instead of as a const reference.
___
*[src/core/ext/xds/xds_api.cc, line 3124 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrOId50xgSQGQD72CR:-MVrOId50xgSQGQD72CS:bbvg7dz) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_api.cc#L3124)):*
> ```cpp
>   upb_strview kCdsTypeUrlUpb = upb_strview_makez(XdsApi::kCdsTypeUrl);
>   auto* cluster_config_dump =
>       envoy_admin_v3_ClustersConfigDump_new(context.arena);
> ```

Can't this just call `envoy_service_status_v3_PerXdsConfig_mutable_cluster_config()` instead of creating the `ClusterConfig` object and then adding it into the `PerXdsConfig`?
___
*[src/core/ext/xds/xds_api.cc, line 3178 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrIF2B4ScFkJ0ULJqN:-MVrIF2B4ScFkJ0ULJqO:b-gdv234) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_api.cc#L3178)):*
> ```cpp
>   envoy_service_status_v3_PerXdsConfig_set_endpoint_config(
>       per_xds_config, endpoint_config_dump);
> ```

Please remove blank lines within functions.
___
*[src/core/ext/xds/xds_client.cc, line 2289 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVSfYvW-EBCGVMuzcm1:-MVrQ1F1-I3Qrb7bE3pM:b-fusc0e) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_client.cc#L2289)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please set the `version` field for each resource type separately instead of having a separate loop for it, since this avoids duplicate map lookups in `per_xds_resource_metadata_map`.
___
*[src/core/ext/xds/xds_client.cc, line 2283 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrPjaEC-38ImFSWvvt:-MVrPjaEC-38ImFSWvvu:b-a1k483) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_client.cc#L2283)):*
> ```cpp
> std::string XdsClient::DumpClientConfigBinary() {
>   MutexLock lock(&mu_);
>   XdsApi::ResourceTypeMetadataMap per_xds_resource_metadata_map;
> ```

Please call this `resource_type_metadata_map`.
___
*[src/core/ext/xds/xds_client.cc, line 2368 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrQHB5EmbCeK6tN0L5:-MVrQHB5EmbCeK6tN0L6:bctport) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_client.cc#L2368)):*
> ```cpp
> 
> // The returned bytes may contain NULL(0), so we can't use c-string.
> grpc_slice grpc_dump_xds_configs() {
> ```

This is part of the C-core API, so you need to declare a `grpc_core::ExecCtx` instance at the start of the function.
___
*[src/cpp/server/csds/csds.cc, line 29 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrR2qp8djC0gZxGqap:-MVrR2qp8djC0gZxGqaq:b-we9nfk) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/cpp/server/csds/csds.cc#L29)):*
> ```cpp
> #include <string>
> 
> #include "src/core/ext/xds/xds_client.h"
> ```

This include is no longer needed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9120 at r11](https://reviewable.io/reviews/grpc/grpc/25038#-MV3klT4-8lQPmpPdvGs:-MVrdaJHDHx6XsQYtvSu:b-xa81wu) ([raw file](https://github.com/grpc/grpc/blob/e5ef6677d46f3c88c2fb1144e5deb68bac2856fa/test/cpp/end2end/xds_end2end_test.cc#L9120)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

When the RPC fail with UNAVAILABLE, it means the xDS configs are in DOES_NOT_EXIST status. But this test case hopes to verify if the xDS configs will have an intermediate REQUESTED state, so it only gives a 1 second timeout here.
</blockquote></details>

Good point.  Okay, I guess we'll just have to see if this causes flakiness.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8701 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVNNBmbEDoCi_p7PYrQ:-MVrRDCM0g9T81wkuwZe:b23xu13) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/test/cpp/end2end/xds_end2end_test.cc#L8701)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Added a new test class `CsdsShortAdsTimeoutTest`. Good catch!
</blockquote></details>

The condition check on the test name is still here.  Please remove it.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9725 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrRwD99R67IMuuY2_Y:-MVrRwD99R67IMuuY2_Z:b-o1gu8o) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/test/cpp/end2end/xds_end2end_test.cc#L9725)):*
> ```cpp
> };
> 
> #define XDS_FIELD(name) \
> ```

Please don't use macros like this.  Just inline the corresponding expressions.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9752 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrVl-V4ghsbbMaUJFM:-MVrVl-V4ghsbbMaUJFN:bp0hywa) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/test/cpp/end2end/xds_end2end_test.cc#L9752)):*
> ```cpp
>            "equals DynamicListener") {
>   bool ok = true;
>   ok &= XDS_MATCH(has_warming_state, false);
> ```

These two should use `::testing::ElementsAre()` instead.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9769 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrWMmK7w8xSpSP9e5J:-MVrWMmK7w8xSpSP9e5K:b-gct067) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/test/cpp/end2end/xds_end2end_test.cc#L9769)):*
> ```cpp
> }
> 
> MATCHER_P2(EqListener, name, api_listener, "equals Listener") {
> ```

Please call this `EqApiListener`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9789 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrY-Om-TK62Z-MWGS8:-MVrY-Om-TK62Z-MWGS9:b-5hwo3p) ([raw file](https://github.com/grpc/g [...]

2021-03-16 15:33 UTC, markdroth requested changes
Almost there!

Please let me know if you have any questions.  Thanks!

> Reviewed 9 of 9 files at r19.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MVvepEq8khpR0C-uITS:b6nc2a9)* status: all files reviewed, 5 unresolved discussions (waiting on @lidizheng)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 9752 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrVl-V4ghsbbMaUJFM:-MVvcAcrDP0C3SCAbfib:bzgzxjm) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/test/cpp/end2end/xds_end2end_test.cc#L9752)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two should use `::testing::ElementsAre()` instead.
</blockquote></details>

Sorry, nevermind this -- for some reason, I thought these were repeated fields.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10021 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrcuSJ-Z2ZXsJRP9Ls:-MVvejok4G8oJHiGwf6f:b-stbhcb) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/test/cpp/end2end/xds_end2end_test.cc#L10021)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should check that the original listener resource is still reported here.

Same thing for all resource type NACK tests.
</blockquote></details>

Still need to take care of this.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9860 at r19](https://reviewable.io/reviews/grpc/grpc/25038#-MVvbpqN8JmXVwwsZ60J:-MVvbpqN8JmXVwwsZ60K:b-e2sjpi) ([raw file](https://github.com/grpc/grpc/blob/9650d949dcdd3a64bee30255f85f3f2ed3640b0d/test/cpp/end2end/xds_end2end_test.cc#L9860)):*
> ```cpp
> MATCHER_P(UnpackListener, matcher, "is a Listener") {
>   Listener config;
>   arg.UnpackTo(&config);
> ```

This matcher should fail if `UnpackTo()` returns false.

Same for all of the `Unpack*` matchers.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9891 at r19](https://reviewable.io/reviews/grpc/grpc/25038#-MVvakb79Wv5IXMXmhw2:-MVvakb79Wv5IXMXmhw3:b-hodcz4) ([raw file](https://github.com/grpc/grpc/blob/9650d949dcdd3a64bee30255f85f3f2ed3640b0d/test/cpp/end2end/xds_end2end_test.cc#L9891)):*
> ```cpp
>            api_listener_matcher, error_state, "equals DynamicListener") {
>   bool ok = true;
>   ok &= !arg.has_warming_state();
> ```

This should either use `::testing::ExplainMatchResult()` or manually add output to `result_listener` when the check fails.

Same for the next one.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9994 at r19](https://reviewable.io/reviews/grpc/grpc/25038#-MVvdcDO3ErwSJo8YEIJ:-MVvdcDO3ErwSJo8YEIK:botnsmd) ([raw file](https://github.com/grpc/grpc/blob/9650d949dcdd3a64bee30255f85f3f2ed3640b0d/test/cpp/end2end/xds_end2end_test.cc#L9994)):*
> ```cpp
>                          "envoy.lb.does_not_support_overprovisioning")));
>   // Prepare matches for RDS on or off
>   ::testing::Matcher<google::protobuf::Any> api_listener_matcher = ::testing::_;
> ```

Might as well not bother initializing either of these to `::testing::_`, since we're now setting them below in all cases.


<!-- Sent from Reviewable.io -->

2021-03-16 17:48 UTC, lidizheng reviewed
Thanks again for the reviews! Introduced more matchers and test cases, hopefully, it can make the test more readable.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MVw8Ekj4nZLYVfFkluY:b-jmrygu)* status: all files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 522 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVqzk603R0T8raShTNy:-MVrkizP5pborO7g4en2:b-ovwawk) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_api.h#L522)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of casting both enum values to ints, just cast one to the other:

```
static_assert(
    static_cast<ResourceMetadata::ClientResourceStatus>(envoy_admin_v3_REQUESTED) ==
        ResourceMetadata::ClientResourceStatus::REQUESTED,
    "");
```
</blockquote></details>

Good idea!
___
*[src/core/ext/xds/xds_api.h, line 592 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVr1eWXBZak1plvOMLZ:-MVrkwp6-xqLaIY2qVtx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_api.h#L592)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call the parameter `resource_type_metadata_map`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2997 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVr-7OB0JOlUhC2qTX4:-MVrl24u4UrRHvqHmRlF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_api.cc#L2997)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`grpc_millis` is a pod type, so it can be passed in by value instead of as a const reference.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 3124 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrOId50xgSQGQD72CR:-MVrlVd2CPemQEx0i03U:b-h3j7t6) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_api.cc#L3124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can't this just call `envoy_service_status_v3_PerXdsConfig_mutable_cluster_config()` instead of creating the `ClusterConfig` object and then adding it into the `PerXdsConfig`?
</blockquote></details>

Good catch! Updated, I used the suggested pattern for LDS/RDS, but forgot to update CDS/EDS as well.
___
*[src/core/ext/xds/xds_api.cc, line 3178 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrIF2B4ScFkJ0ULJqN:-MVrljANEAy86HpeiMII:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_api.cc#L3178)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank lines within functions.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2289 at r17](https://reviewable.io/reviews/grpc/grpc/25038#-MVSfYvW-EBCGVMuzcm1:-MVrmXqh2MdJumSGo5Gz:b-br5dyo) ([raw file](https://github.com/grpc/grpc/blob/f22d57e4c647f326e1476dc45f7f8c2f835723e1/src/core/ext/xds/xds_client.cc#L2289)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please set the `version` field for each resource type separately instead of having a separate loop for it, since this avoids duplicate map lookups in `per_xds_resource_metadata_map`.
</blockquote></details>

Can we keep the way it is? The `resource_version_map_` isn't guaranteed to have an entry for each of the 4 xDS types. If we don't use a loop, we will need to use the iterator-find pattern.

More specifically, we may save the lookups for `resource_type_metadata_map` but it costs us to lookup 4 times for `resource_version_map_` which is more expensive than iterating and less cache friendly than iterating through it.
___
*[src/core/ext/xds/xds_client.cc, line 2283 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrPjaEC-38ImFSWvvt:-MVrlkXk0RPPVXjM8Tns:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_client.cc#L2283)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `resource_type_metadata_map`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2368 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrQHB5EmbCeK6tN0L5:-MVroHdh5nNvTb0fCz4g:b6be5zp) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_client.cc#L2368)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is part of the C-core API, so you need to declare a `grpc_core::ExecCtx` instance at the start of the function.
</blockquote></details>

Added both ExecCtx and ApplicationCallbackExecCtx. Just curious, I was referencing Channelz's surface API, should Channelz also add these two context?
___
*[src/cpp/server/csds/csds.cc, line 29 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrR2qp8djC0gZxGqap:-MVrofnDA1wPtm1jP7UE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/cpp/server/csds/csds.cc#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This include is no longer needed.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8701 at r15](https://reviewable.io/reviews/grpc/grpc/25038#-MVNNBmbEDoCi_p7PYrQ:-MVw2Rxn5Z51-hduIa4D:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/c8f37b88dfc63c33bb61875fafea54f7e46d8e3e/test/cpp/end2end/xds_end2end_test.cc#L8701)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The condition check on the test name is still here.  Please remove it.
</blockquote></details>

Removed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9725 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrRwD99R67IMuuY2_Y:-MVsJx0s-68laDM8B3fK:b-wmtw03) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/test/cpp/end2end/xds_end2end_test.cc#L9725)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please don't use macros like this.  Just inline the corresponding expressions.
</blockquote></details>

Done. As discussed offline, we should not add new macros to Core or tests.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9769 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrWMmK7w8xSpSP9e5J:-MVrsibR0tEjqZvFEI-D:bslkegi) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/test/cpp/end2end/xds_end2end_test.cc#L9769)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `EqApiListener`.
</blockquote></details>

Technically, this matcher expects a `envoy.config.listener.v3.Listener` message.  Should we still need to rename it to `EqApiListener`?

https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/listener/v3/listener.proto#L39
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9789 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrY-Om-TK62Z-MWGS8:-MVruxIQ8Y74Rt_R2G_a:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/test/cpp/end2end/xds_end2end_test.cc#L9789)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of hard-coding the indexes here, this should be something like:

```
ok &= ::testing::ExplainMatchResult(
    ::testing::ElementsAre(
        ::testing::ElementsAre(
            ::testing::Property(
                &envoy::config::route::v3::Route::route,
                ::testing::Property(
                    &envoy::config:: [...]

2021-03-16 20:37 UTC, markdroth approved these changes
There's just one small nit remaining.  Feel free to merge after addressing.

Thanks for doing this!

> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MVwkO1rA9edWZwFbyyN:b-w13uyi)* status: all files reviewed, 1 unresolved discussion (waiting on @lidizheng)

___
*[src/core/ext/xds/xds_client.cc, line 2368 at r18](https://reviewable.io/reviews/grpc/grpc/25038#-MVrQHB5EmbCeK6tN0L5:-MVwkDE10U1dawvZRxmj:bhrvmxw) ([raw file](https://github.com/grpc/grpc/blob/77730d85690c0a32bc2401f07215bec7c8b82866/src/core/ext/xds/xds_client.cc#L2368)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Added both ExecCtx and ApplicationCallbackExecCtx. Just curious, I was referencing Channelz's surface API, should Channelz also add these two context?
</blockquote></details>

If it's not already doing so, it should be, yes.  Feel free to send me a separate PR for that.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9860 at r19](https://reviewable.io/reviews/grpc/grpc/25038#-MVvbpqN8JmXVwwsZ60J:-MVwjPWY7cAIqwu1SC-X:bx791cy) ([raw file](https://github.com/grpc/grpc/blob/9650d949dcdd3a64bee30255f85f3f2ed3640b0d/test/cpp/end2end/xds_end2end_test.cc#L9860)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Good catch! Done.
</blockquote></details>

I think that if `ok` is false after `UnpackTo()` runs, then there's no point in invoking the matcher for the contents, because we know it will fail.


<!-- Sent from Reviewable.io -->

2021-03-16 21:02 UTC, lidizheng reviewed
Thanks for the 20 rounds of review and hundreds of comments! Really appreciate the help!

> Reviewed 4 of 9 files at r19.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25038#-:-MVwoeA1EALVx4YER_Y8:bfo3ah0)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 9860 at r19](https://reviewable.io/reviews/grpc/grpc/25038#-MVvbpqN8JmXVwwsZ60J:-MVwo7ufBJPmeaIGRtLJ:b-896fja) ([raw file](https://github.com/grpc/grpc/blob/9650d949dcdd3a64bee30255f85f3f2ed3640b0d/test/cpp/end2end/xds_end2end_test.cc#L9860)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think that if `ok` is false after `UnpackTo()` runs, then there's no point in invoking the matcher for the contents, because we know it will fail.
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2021-03-17 01:17 UTC, lidizheng commented
Known failure: both interop tests failed due to https://github.com/grpc/grpc/issues/25737.

2021-03-17 01:17 UTC, merged