Cds Watchers changes to support aggregate Cds.
grpc/grpc pull request #25078
Opened 2020-12-31 07:54 UTC by donnadionne

2021-01-05 06:32 UTC, donnadionne commented
While I still have some TODOs, the framework of the change is ready to be reviewed.  I am also working on a test to be completed with this PR.

2021-01-05 19:25 UTC, markdroth requested changes
This looks like a reasonable start!  My main comment is that I think the data structures and the logic in the CDS policy need to be simplified.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078#-:-MQJ-V8X09gbs9wjHhUo:b-p8tc2m)* status: 4 of 5 files reviewed, 12 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 50 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIigaY7St-qomFusjE:-MQIigaY7St-qomFusjF:b-ynkeg6) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L50)):*
> ```cpp
>  public:
>   explicit CdsLbConfig(std::string cluster) : cluster_(std::move(cluster)) {}
>   CdsLbConfig(XdsApi::CdsUpdate::ClusterType type, std::string cluster,
> ```

I don't think we should be changing the `CdsLbConfig` class.  This class represents the config for the CDS LB policy itself, and that config is not changing in this PR.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 92 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIjURuBr2wlIIA0EnV:-MQIjURuBr2wlIIA0EnW:b-lwdtce) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L92)):*
> ```cpp
>   class ClusterWatcher : public XdsClient::ClusterWatcherInterface {
>    public:
>     explicit ClusterWatcher(RefCountedPtr<CdsLb> parent, std::string name)
> ```

This no longer needs to be `explicit`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIj_x54JIG5DzhhmN9:-MQIj_x54JIG5DzhhmNA:blrgvl) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L122)):*
> ```cpp
>       XdsApi::CdsUpdate update_;
>       Type type_;
>       std::string name_;
> ```

Please move this up to right after `parent_`, since those two fields come from the same place.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 129 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIjtK69bXH1_Plz_d8:-MQIjtK69bXH1_Plz_d9:bgowfbb) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L129)):*
> ```cpp
>   };
> 
>   struct Watcher {
> ```

This data structure seems to be designed to represent the parent and the children differently, and that seems unnecessarily confusing.  Instead, how about something like this:

```
struct WatcherState {
  // Pointer to watcher, to be used when cancelling.
  // Not owned, so do not dereference.
  ClusterWatcher* watcher = nullptr;
  // Most recent update obtained from this watcher.
  absl::optional<XdsApi::CdsUpdate> update;
};

// Maps from cluster name to the state for that cluster.
// The root of the tree is config_->cluster().
std::map<std::string, WatcherState> watchers_;
```

This way, when a watcher for a given cluster name returns new data, we can handle it the same way, regardless of whether it's the parent or a child.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 168 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIoJ4B92AN6BZ8aMqz:-MQIoJ4B92AN6BZ8aMr-:bax6v94) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L168)):*
> ```cpp
>   void UpdateAggregateCluster(RefCountedPtr<CdsLbConfig> config);
>   void UpdateChildPolicy(absl::optional<XdsApi::CdsUpdate> cluster_data);
>   void OnClusterChanged(XdsApi::CdsUpdate cluster_data, std::string name);
> ```

The `name` parameter should be the first parameter for these two methods.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 238 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQImEF92lOY3j2iGE3v:-MQImEF92lOY3j2iGE3w:b-e8gnbf) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L238)):*
> ```cpp
>   switch (type_) {
>     case kUpdate:
>       parent_->OnClusterChanged(std::move(update_), name_);
> ```

For all three cases here, we are making an unnecessary copy of `name_` here.  I suggest either using `std::move()` here or changing  the `OnClusterChanged()`, `OnError()`, and `OnResourceDoesNotExist()` methods to take the parameter as a const reference.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 570 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQInrv13zZ0kP2OOpK5:-MQInrv13zZ0kP2OOpK6:b-3uru9j) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L570)):*
> ```cpp
> }
> 
> void CdsLb::OnClusterChanged(XdsApi::CdsUpdate cluster_data, std::string name) {
> ```

I think the logic here should be structured in a way that it can be very generic and will work for any cluster type.  I think it should be structured something like this:

```
void CdsLb::OnClusterChanged(std::string name, XdsApi::CdsUpdate cluster_data) {
  // Store the update in the map.
  watchers_[name].update = std::move(cluster_data);
  // Scan the map starting from the root cluster to generate the list of discovery mechanisms.
  // If we don't have some of the data we need (i.e., we just started up and not all watchers
  // have returned data yet), then don't update the child policy at all.
  Json::Array discovery_mechanisms;
  std::set<std::string> clusters_needed;
  if (GenerateDiscoveryMechanismForCluster(config_->cluster(), &discovery_mechanisms, &clusters_needed)) {
    // ...populate child policy config and update child policy (i.e., most of the original code from OnClusterChanged())...
  }
  // ...remove entries in watchers_ for any clusters not in clusters_needed...
}

// Appends discovery mechanism for name to discovery_mechanisms.
// Inserts name into clusters_needed.
// Returns false if no update present for the specified cluster name.
bool CdsLb::GenerateDiscoveryMechanismForCluster(
    const std::string& name, Json::Array* discovery_mechanisms, std::set<std::string>* clusters_needed) {
  clusters_needed->insert(name);
  auto& state = watchers_[name];
  // Create a new watcher if needed.
  if (state.update.watcher == nullptr) {
     // ...create new watcher for name...
    return false;
  }
  if (!state.update.has_value()) return false;
  // For AGGREGATE clusters, recursively expand to child clusters.
  if (state.update.cluster_type == AGGREGATE) {
    bool missing_cluster = false;
    for (const std::string& child_name : state.update.prioritized_cluster_names) {
      if (!GenerateDiscoveryMechanismForCluster(child_name, child_config)) {
        missing_cluster = true;
      }
    }
    if (missing_cluster) return false;
  }
  // ...append entry to (*child_config)["discovery_mechanisms"] for this cluster...
  return true;
}
```
___
*[src/core/ext/xds/xds_api.cc, line 1737 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIhhgJ0FyhOMh8M0LB:-MQIhhgJ0FyhOMh8M0LC:b9tk65o) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/xds/xds_api.cc#L1737)):*
> ```cpp
>     }
>     if (envoy_config_cluster_v3_Cluster_type(cluster) ==
>         envoy_config_cluster_v3_Cluster_EDS) {
> ```

I think the existing code below that reads the `eds_cluster_config` field should be moved into this block, since we only way to look at that field if the cluster type is EDS.
___
*[src/core/ext/xds/xds_api.cc, line 1740 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIiJ-d-NU21gLTwgbe:-MQIiJ-d-NU21gLTwgbf:b-qc7byp) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/xds/xds_api.c [...]

2021-01-08 03:36 UTC, donnadionne reviewed
Fixed according to code review suggestions.  Finished all necessary functionalities and added a basic test.

Please review.

More tests will be coming.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078#-:-MQV374_3nqJerEb0SoL:bspw03v)* status: 2 of 30 files reviewed, 12 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 50 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIigaY7St-qomFusjE:-MQV2LZ5Ab8DMMtRS_Y-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we should be changing the `CdsLbConfig` class.  This class represents the config for the CDS LB policy itself, and that config is not changing in this PR.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 92 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIjURuBr2wlIIA0EnV:-MQQaQf02sCvdSP19E03:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L92)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This no longer needs to be `explicit`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIj_x54JIG5DzhhmN9:-MQQa_XY4oV-JAzOgua6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L122)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this up to right after `parent_`, since those two fields come from the same place.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 129 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIjtK69bXH1_Plz_d8:-MQV2MGe0e1Yqufx3ndE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L129)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This data structure seems to be designed to represent the parent and the children differently, and that seems unnecessarily confusing.  Instead, how about something like this:

```
struct WatcherState {
  // Pointer to watcher, to be used when cancelling.
  // Not owned, so do not dereference.
  ClusterWatcher* watcher = nullptr;
  // Most recent update obtained from this watcher.
  absl::optional<XdsApi::CdsUpdate> update;
};

// Maps from cluster name to the state for that cluster.
// The root of the tree is config_->cluster().
std::map<std::string, WatcherState> watchers_;
```

This way, when a watcher for a given cluster name returns new data, we can handle it the same way, regardless of whether it's the parent or a child.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 168 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIoJ4B92AN6BZ8aMqz:-MQQbCkBBx62Db2wv0hF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L168)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `name` parameter should be the first parameter for these two methods.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 238 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQImEF92lOY3j2iGE3v:-MQV2N4uBolQYaYUCc7P:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L238)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

For all three cases here, we are making an unnecessary copy of `name_` here.  I suggest either using `std::move()` here or changing  the `OnClusterChanged()`, `OnError()`, and `OnResourceDoesNotExist()` methods to take the parameter as a const reference.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 570 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQInrv13zZ0kP2OOpK5:-MQV2O1EBx7SjeXjIYX9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L570)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the logic here should be structured in a way that it can be very generic and will work for any cluster type.  I think it should be structured something like this:

```
void CdsLb::OnClusterChanged(std::string name, XdsApi::CdsUpdate cluster_data) {
  // Store the update in the map.
  watchers_[name].update = std::move(cluster_data);
  // Scan the map starting from the root cluster to generate the list of discovery mechanisms.
  // If we don't have some of the data we need (i.e., we just started up and not all watchers
  // have returned data yet), then don't update the child policy at all.
  Json::Array discovery_mechanisms;
  std::set<std::string> clusters_needed;
  if (GenerateDiscoveryMechanismForCluster(config_->cluster(), &discovery_mechanisms, &clusters_needed)) {
    // ...populate child policy config and update child policy (i.e., most of the original code from OnClusterChanged())...
  }
  // ...remove entries in watchers_ for any clusters not in clusters_needed...
}

// Appends discovery mechanism for name to discovery_mechanisms.
// Inserts name into clusters_needed.
// Returns false if no update present for the specified cluster name.
bool CdsLb::GenerateDiscoveryMechanismForCluster(
    const std::string& name, Json::Array* discovery_mechanisms, std::set<std::string>* clusters_needed) {
  clusters_needed->insert(name);
  auto& state = watchers_[name];
  // Create a new watcher if needed.
  if (state.update.watcher == nullptr) {
     // ...create new watcher for name...
    return false;
  }
  if (!state.update.has_value()) return false;
  // For AGGREGATE clusters, recursively expand to child clusters.
  if (state.update.cluster_type == AGGREGATE) {
    bool missing_cluster = false;
    for (const std::string& child_name : state.update.prioritized_cluster_names) {
      if (!GenerateDiscoveryMechanismForCluster(child_name, child_config)) {
        missing_cluster = true;
      }
    }
    if (missing_cluster) return false;
  }
  // ...append entry to (*child_config)["discovery_mechanisms"] for this cluster...
  return true;
}
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1737 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIhhgJ0FyhOMh8M0LB:-MQQe0Qx38uR-98ycdms:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/xds/xds_api.cc#L1737)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the existing code below that reads the `eds_cluster_config` field should be moved into this block, since we only way to look at that field if the cluster type is EDS.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1740 at r1](https://reviewable.io/reviews/grpc/grpc/25078#-MQIiJ-d-NU21gLTwgbe:-MQV34XQ4N8KKNm-dU2q:b-bsqjmf) ([raw file](https://github.com/grpc/grpc/blob/1f314539ecda9528cb7b6cb2574a03f0929dc159/src/core/ext/xds/xds_api.cc#L1740)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We'll need to guard the new handling of LOGICAL_DNS and AGGREGATE clusters with an env var.  Please  [...]

2021-01-08 19:16 UTC, markdroth requested changes
This looks really good!

The only really significant issue is the one about the xDS certificate provider.  We'll have to discuss the best way to solve that.

Please let me know if you have any questions.  Thanks!

> Reviewed 25 of 28 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078#-:-MQYPu-5BBMG0XV8vQGs:bbn64jg)* status: all files reviewed, 18 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 289 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXergDC6Tsd0yx5Vwg:-MQXergDC6Tsd0yx5Vwh:b-c6wkiw) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L289)):*
> ```cpp
>   if (xds_client_ != nullptr) {
>     for (auto& watcher : watchers_) {
>       if (watcher.second.watcher != nullptr) {
> ```

I think this should never be null.  We should always create the watcher at the same time that we add the entry to `watchers_`, and we should always cancel the watcher at the same time that we remove the entry from `watchers_`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 332 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXWWMGDxJGWnL70uga:-MQXWD2LDTkoVucvj32L:bmnv4m7) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L332)):*
> ```cpp
>     if (old_config != nullptr) {
>       for (auto& watcher : watchers_) {
>         if (watcher.second.watcher != nullptr) {
> ```

As mentioned above, I think this should never be null.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 349 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXWoHWAtzuUSN0Ur99:-MQXWoHWAtzuUSN0Ur9A:b-qbf46n) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L349)):*
> ```cpp
> }
> 
> bool CdsLb::GenerateDiscoveryMechanismForCluster(
> ```

Please add a comment documenting this method:

```
// Appends discovery mechanism for name to discovery_mechanisms.
// Inserts name into clusters_needed.
// Returns false if no update present for the specified cluster name.
```
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 378 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXX9qyA3g_zRS7miEV:-MQXX9qyA3g_zRS7miEW:b4a0k33) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L378)):*
> ```cpp
>     }
>     return !missing_cluster;
>   } else {
> ```

No need for the `else`, since the `if` block above always returns.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 394 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXXSeE6myJ1hb-1L3c:-MQXXSeE6myJ1hb-1L3d:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L394)):*
> ```cpp
>         {"clusterName", name},
>         {"max_concurrent_requests", state.update->max_concurrent_requests},
>         {"type", type},
> ```

`std::move()`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 404 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXYIRMDX2kBcW_9Mu6:-MQXYIRMDX2kBcW_9Mu7:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L404)):*
> ```cpp
>     }
>     discovery_mechanisms->emplace_back(std::move(mechanism));
>     gpr_log(GPR_INFO, "DONNA debug: added discovery mechanism for %s",
> ```

Please remove.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 413 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXYMzG7KYTfde21JUB:-MQXYMzG7KYTfde21JUC:bf4moza) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L413)):*
> ```cpp
>                              XdsApi::CdsUpdate cluster_data) {
>   if (GRPC_TRACE_FLAG_ENABLED(grpc_cds_lb_trace)) {
>     gpr_log(GPR_INFO, "[cdslb %p] received CDS update from xds client %p: %s",
> ```

This should also log which cluster the update was for.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 417 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXZALv8qSeP09fn_dF:-MQXZALv8qSeP09fn_dG:b-lfxtmo) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L417)):*
> ```cpp
>   }
>   grpc_error* error = GRPC_ERROR_NONE;
>   error = UpdateXdsCertificateProvider(cluster_data);
> ```

Ugh... Seeing this code made me realize that we didn't consider how to handle the mTLS certificate code as part of this design.  I don't think this is going to work as-is, because this code is setting the certificate provider as a single channel arg for all children, but each cluster might have a different TLS certificate config, so this actually needs to be set on a per-underlying-cluster basis.

As per discussion in the chat room, we'll need to figure out a new way to handle this.  I've got the start to one possible approach in #25120, but I still need to debug some failing tests.  CC @yashykt 

Once we resolve this, please make sure that we have a test for the case of an aggregate cluster where the underlying clusters have two different mTLS configs.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 422 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXbd9w7cWeFbXafxHW:-MQXbd9w7cWeFbXafxHX:bjegc91) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L422)):*
> ```cpp
>   }
>   // Store the update in the map.
>   watchers_[name].update = std::move(cluster_data);
> ```

Because the notifications are scheduled asynchronously to get back into the `WorkSerializer`, it's possible that we may have already cancelled the watch for `name` by the time this notification comes in.  In that case, we don't want to re-add the entry to `watchers_`.

To handle this, I think we'll need to do something like this:

```
auto it = watchers_.find(name);
// If we've already deleted this entry, then this is an update notification that was
// scheduled before the deletion, so we can just ignore it.
if (it == watchers_.end()) return;
it->update = std::move(cluster_data);
```
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 449 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXe1HV4SiUkqYS_gZD:-MQXe1HW5A8p71bAll7e:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L449)):*
> ```cpp
>          }},
>     };
>     child_config["discoveryMechanisms"] = discovery_mechanisms;
> ```

`std::move()`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 504 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXbOu7EWHU9V8Oilfy:-MQXbOu7EWHU9V8Oilfz:bmnv4m7) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L504)):*
> ```cpp
>       continue;
>     }
>     if (it->second.watcher != nullptr) {
> ```

As mentioned above, I think this should never be null.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 921 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXVQj52MI5B8A1C_SY:-MQXVQj60iolcZeduHXB:bxpjeu1) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L921)):*
> ```cpp
>   // priorities, num_priorities_remaining should be down to 0, and index should
>   [...]

2021-01-12 09:23 UTC, donnadionne reviewed
Will follow up with certificate issue (and add test)
Still need to add Logical DNS test and nested aggregate cluster test
Wanted to get another round of review to ensure there are no other issues.
Thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078#-:-MQptg0w03pZvqwZBulD:b-sf2sb)* status: 12 of 30 files reviewed, 18 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 289 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXergDC6Tsd0yx5Vwg:-MQZ_jBuE2C7EmWfrDli:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L289)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this should never be null.  We should always create the watcher at the same time that we add the entry to `watchers_`, and we should always cancel the watcher at the same time that we remove the entry from `watchers_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 332 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXWWMGDxJGWnL70uga:-MQZ_i6Q7OVb2elemSjw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L332)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned above, I think this should never be null.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 349 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXWoHWAtzuUSN0Ur99:-MQZgj9W4rac8x0fwUDD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L349)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment documenting this method:

```
// Appends discovery mechanism for name to discovery_mechanisms.
// Inserts name into clusters_needed.
// Returns false if no update present for the specified cluster name.
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 378 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXX9qyA3g_zRS7miEV:-MQZgjbj7AOcUSB-Iu7o:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L378)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the `else`, since the `if` block above always returns.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 394 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXXSeE6myJ1hb-1L3c:-MQZgrOg-NGba6aGtrOh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L394)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 404 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXYIRMDX2kBcW_9Mu6:-MQptUK76UJKxPFywd4s:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L404)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 413 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXYMzG7KYTfde21JUB:-MQZh9UF-bj9UYl0kZqr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L413)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should also log which cluster the update was for.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 417 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXZALv8qSeP09fn_dF:-MQptWG5732iB6Mys8AV:b-nmvq9z) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L417)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ugh... Seeing this code made me realize that we didn't consider how to handle the mTLS certificate code as part of this design.  I don't think this is going to work as-is, because this code is setting the certificate provider as a single channel arg for all children, but each cluster might have a different TLS certificate config, so this actually needs to be set on a per-underlying-cluster basis.

As per discussion in the chat room, we'll need to figure out a new way to handle this.  I've got the start to one possible approach in #25120, but I still need to debug some failing tests.  CC @yashykt 

Once we resolve this, please make sure that we have a test for the case of an aggregate cluster where the underlying clusters have two different mTLS configs.
</blockquote></details>

will follow up with this
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 422 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXbd9w7cWeFbXafxHW:-MQZkzHpBk-zprDyE0iz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L422)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Because the notifications are scheduled asynchronously to get back into the `WorkSerializer`, it's possible that we may have already cancelled the watch for `name` by the time this notification comes in.  In that case, we don't want to re-add the entry to `watchers_`.

To handle this, I think we'll need to do something like this:

```
auto it = watchers_.find(name);
// If we've already deleted this entry, then this is an update notification that was
// scheduled before the deletion, so we can just ignore it.
if (it == watchers_.end()) return;
it->update = std::move(cluster_data);
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 449 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXe1HV4SiUkqYS_gZD:-MQZl447Dn_Pgxd8034V:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L449)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 504 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXbOu7EWHU9V8Oilfy:-MQZlBsr4qDefjDQ2169:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L504)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned above, I think this should never be null.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 921 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXVQj52MI5B8A1C_SY:-MQptdKQ4Mtq4bd8vDDo:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L921)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume the changes in this file were just  [...]

2021-01-12 17:52 UTC, markdroth requested changes
This looks really good!  Other than the two issues you're already looking at, my remaining comments are all minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 15 of 18 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078#-:-MQriVJiDX21nxITBn1L:bcpjzfi)* status: all files reviewed, 18 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 417 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXZALv8qSeP09fn_dF:-MQrPINi4Epc3FKcSCu4:b8c5i5g) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L417)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

will follow up with this
</blockquote></details>

Once #25120 is merged, I think we'll need to merge that into this PR, and then we'll need to make a couple of additional changes.

First, we'll need to pass the cluster name down into `UpdateXdsCertificateProvider()` and change that method to use the passed-in cluster name instead of `config_->cluster()`.

Second, whenever we stop watching a cluster, we will also need to clear that cluster's data from the `XdsCertificateProvider`, using something like this:

```
    xds_certificate_provider_->UpdateRootCertNameAndDistributor(
        cluster_name, "", nullptr);
    xds_certificate_provider_->UpdateIdentityCertNameAndDistributor(
        cluster_name, "", nullptr);
    xds_certificate_provider_->UpdateSubjectAlternativeNameMatchers(
        cluster_name, {});
```
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 350 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrK4Hb-xDg692W5sIq:-MQrK4Hb-xDg692W5sIr:b7107ne) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L350)):*
> ```cpp
> // mechanism recursively:
> // For cluster types EDS or LOGICAL_DNS, one discovery mechanism entry may be
> // genrated: cluster name, type and other data from the CdsUpdate inserted into
> ```

s/genrated/generated/
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 352 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrK7Sy7xgxp-mxMkqU:-MQrK7Sy7xgxp-mxMkqV:bcccvyg) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L352)):*
> ```cpp
> // genrated: cluster name, type and other data from the CdsUpdate inserted into
> // the entry and the entry appended to the array of entries.
> // Note, discovery mechanism entry can be gnerated if an CdsUpdate is available;
> ```

s/gnerated/generated/
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 354 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrKJjT2MuMHG8wu4zK:-MQrKJjT2MuMHG8wu4zL:bouu5uu) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L354)):*
> ```cpp
> // Note, discovery mechanism entry can be gnerated if an CdsUpdate is available;
> // otherwise, just return false.
> // For cluster type AGGREGATE, recurively call the method for each child
> ```

s/recurively/recursively/
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 427 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrOsVd99h9UGHF8klM:-MQrOsVd99h9UGHF8klN:br1ykb6) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L427)):*
> ```cpp
>     return OnError(name, error);
>   }
>   // Store the update in the map if we are still interested in watching this
> ```

I think this comment and the following 3 lines of code should be moved up to line 422, because if the cluster watch was already deleted before we receive this notification, we don't want to re-add the certificate provider config for the cluster.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1 at r2](https://reviewable.io/reviews/grpc/grpc/25078#-MQrGOcJ0dB8G-kYicmC:-MQrGOcJ0dB8G-kYicmD:b-n3sgne) ([raw file](https://github.com/grpc/grpc/blob/a44de5552fc54a1ce012b57b518f0e6b7e5e80b7/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1)):*
> ```cpp
> //
> ```

I assume that removing this comment line was accidental.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 906 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrGbJO8tzpPt2DjTho:-MQrGbJO8tzpPt2DjThp:bb843qr) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L906)):*
> ```cpp
>         {"ignore_reresolution_requests", true},
>     };
>     // Each prioirty in the priority_list_ should correspond to a priority in a
> ```

s/prioirty/priority/
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 909 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrHKi8EX8KMTm_cA9l:-MQrHKi8EX8KMTm_cA9m:b-a9kl2x) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L909)):*
> ```cpp
>     // discovery mechanism in discovery_mechanisms_ (both in the same order).
>     // Keeping track of the discovery_mechanism each prioirty belongs to.
>     if (num_priorities_remaining_in_discovery == 0) {
> ```

Suggest writing this as:

```
--num_priorities_remaining_in_discovery;
while (num_priorities_remaining_in_discovery == 0) {
  ++discovery_index;
  num_priorities_remaining_in_discovery =
      discovery_mechanisms_[discovery_index].num_priorities;
}
```
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 930 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrIujo6Ep7qucPKsRA:-MQrIujo6Ep7qucPKsRB:bve96dw) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L930)):*
> ```cpp
>   // in priority_list_; therefore at the end of looping through all the
>   // priorities, num_priorities_remaining should be down to 0, and index should
>   // be the last index in discovery_mechanisms_.
> ```

s/last index in/number of/
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 932 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrIA1L1zOjvP-nnEZB:-MQrIA1L1zOjvP-nnEZC:bsnmp0y) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L932)):*
> ```cpp
>   // be the last index in discovery_mechanisms_.
>   GPR_ASSERT(num_priorities_remaining_in_discovery == 0);
>   GPR_ASSERT(discovery_index == discovery_mechanisms_.size() - 1);
> ```

With the change I suggested above, I think you'll need to remove the `- 1` here.
___
*[src/core/ext/xds/xds_api.cc, line 107 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrFDXyEOagwqbqBGeq:-MQrFDXyEOagwqbqBGer:b-5fu1a0) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/xds/xds_api.cc#L107)):*
> ```cpp
> // removed once the cluster types are fully integration-tested and enabled by
> // default.
> bool XdsAggregateAndLogicalClusterEnabled() {
> ```

s/Logical/LogicalDns/
___
*[src/core/ext/xds/xds_api.cc, line 109 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrFFPg2Hj7waHMd9PT:-MQrFFPg2Hj7waHMd9PU:b880a03) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/xds/xds_api.cc#L109)):*
> ```cpp
> bool XdsAggregateAndLogicalClusterEnabled() {
>   char* value =
>       gpr_getenv("GRPC_XDS_EXPERIMENTA [...]

2021-01-19 07:59 UTC, donnadionne reviewed
PTAL Thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078#-:-MROdkSl14xMqZBkFr5F:bfqdzl0)* status: 8 of 31 files reviewed, 18 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 417 at r3](https://reviewable.io/reviews/grpc/grpc/25078#-MQXZALv8qSeP09fn_dF:-MROdr-OB0GM3Lyv3WvA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c025ea3fba13f60df0f004792089573313de08f2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L417)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Once #25120 is merged, I think we'll need to merge that into this PR, and then we'll need to make a couple of additional changes.

First, we'll need to pass the cluster name down into `UpdateXdsCertificateProvider()` and change that method to use the passed-in cluster name instead of `config_->cluster()`.

Second, whenever we stop watching a cluster, we will also need to clear that cluster's data from the `XdsCertificateProvider`, using something like this:

```
    xds_certificate_provider_->UpdateRootCertNameAndDistributor(
        cluster_name, "", nullptr);
    xds_certificate_provider_->UpdateIdentityCertNameAndDistributor(
        cluster_name, "", nullptr);
    xds_certificate_provider_->UpdateSubjectAlternativeNameMatchers(
        cluster_name, {});
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 350 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrK4Hb-xDg692W5sIq:-MRO-z_9Ear25oULJX_O:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L350)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/genrated/generated/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 352 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrK7Sy7xgxp-mxMkqU:-MRO-zqe7xmwCfcdTfZt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L352)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/gnerated/generated/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 354 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrKJjT2MuMHG8wu4zK:-MRO0Cz23JJTid9OZXcM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L354)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/recurively/recursively/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 427 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrOsVd99h9UGHF8klM:-MRO3OGa5bHEfRXvS7QW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L427)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this comment and the following 3 lines of code should be moved up to line 422, because if the cluster watch was already deleted before we receive this notification, we don't want to re-add the certificate provider config for the cluster.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1 at r2](https://reviewable.io/reviews/grpc/grpc/25078#-MQrGOcJ0dB8G-kYicmC:-MRO3csi0Y-D6uKy3DNP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a44de5552fc54a1ce012b57b518f0e6b7e5e80b7/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume that removing this comment line was accidental.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 906 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrGbJO8tzpPt2DjTho:-MRO3qvZ0_PpJH_EOyIz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L906)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/prioirty/priority/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 909 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrHKi8EX8KMTm_cA9l:-MROGs7cCUcuItLybymr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L909)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as:

```
--num_priorities_remaining_in_discovery;
while (num_priorities_remaining_in_discovery == 0) {
  ++discovery_index;
  num_priorities_remaining_in_discovery =
      discovery_mechanisms_[discovery_index].num_priorities;
}
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 930 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrIujo6Ep7qucPKsRA:-MRO3yPZ7w1VNRmp6F48:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L930)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/last index in/number of/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 932 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrIA1L1zOjvP-nnEZB:-MROGszY5iLETjE9-Eyr:b-xz9af7) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L932)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

With the change I suggested above, I think you'll need to remove the `- 1` here.
</blockquote></details>

i had to make a small modification to the above suggestion guarding against going beyond the number of discovery mechanisms.  so that guard will ensure the index will be size()-1
___
*[src/core/ext/xds/xds_api.cc, line 107 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrFDXyEOagwqbqBGeq:-MROJrMADcREQBpj_nBj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/xds/xds_api.cc#L107)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/Logical/LogicalDns/
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 109 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrFFPg2Hj7waHMd9PT:-MROJqHjBskP1tjPdlzh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/xds/xds_api.cc#L109)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/LOGICAL/LOGICAL_DNS/
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1771 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrFaTM0NgeSZpPSP9b:-MRONIA9-7-q68GN-1pm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/xds/xds_api.cc#L1771)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest just writing this as:

```
} else if (!XdsAggregateAndLogicalClusterEnabled()) {
  return GRPC_ERROR_CREATE_FROM_STATIC_STRING(
      "DiscoveryType is not valid.");
} else [...]

2021-01-19 19:37 UTC, markdroth requested changes
This is getting close!  I think the test still needs a bit of work, but I think all of the building blocks we need are there now.

Please let me know if you have any questions.  Thanks!

> Reviewed 20 of 23 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078#-:-MRR8UbU4X1b5_BeBoEu:b-hangoz)* status: all files reviewed, 30 unresolved discussions (waiting on @donnadionne)

___
*[BUILD, line 1486 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR-ndr8Dqy1t9AZ6bE:-MRR-ndr8Dqy1t9AZ6bF:b3mmzpk) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/BUILD#L1486)):*
> ```Starlark
>         "grpc_lb_address_filtering",
>         "grpc_lb_xds_common",
>         "grpc_resolver_fake",
> ```

I think we also need to add `grpc_lb_xds_channel_args` as a dependency here.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 463 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRQzt0c6EBQJ039X0hB:-MRQzt0c6EBQJ039X0hC:bb697i2) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L463)):*
> ```cpp
>          }},
>     };
>     child_config["discoveryMechanisms"] = std::move(discovery_mechanisms);
> ```

This can be set as part of the initializer list above rather than as a separate statement.

```
    {"discoveryMechanisms", std::move(discovery_mechanisms)},
```
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 530 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR-OAk7nxgEaaE_50J:-MRR-OAk7nxgEaaE_50K:bayh6c2) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L530)):*
> ```cpp
> void CdsLb::OnError(const std::string& name, grpc_error* error) {
>   gpr_log(GPR_ERROR, "[cdslb %p] xds error obtaining data for cluster %s: %s",
>           this, config_->cluster().c_str(), grpc_error_string(error));
> ```

This should use `name` instead of `config_->cluster()`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 547 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR-RfH7uAV6zwdVxWo:-MRR-RfH7uAV6zwdVxWp:bayh6c2) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L547)):*
> ```cpp
>           "[cdslb %p] CDS resource for %s does not exist -- reporting "
>           "TRANSIENT_FAILURE",
>           this, config_->cluster().c_str());
> ```

This should use `name` instead of `config_->cluster()`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 662 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRQyHodCVZyRZw88Z5q:-MRQyHoeAaLJYwW8ygKe:b-gtv2rc) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L662)):*
> ```cpp
>                                    bool delay_unsubscription) {
>   if (xds_certificate_provider_ != nullptr) {
>     std::string name = std::string(cluster_name);
> ```

`std::string name(cluster_name);`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h, line 25 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRQxDBu55txetQ_4x9s:-MRQxDBu55txetQ_4x9t:b-fav35q) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h#L25)):*
> ```objc
> 
> // Channel arg indicating xds_cluster_resolver LB policy should use the fake
> // DNS resolver to resolve logical dns cluster.
> ```

Please document that this is for testing only.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h, line 26 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRQxIIQ1RbICzU95sZS:-MRQxIIQ1RbICzU95sZT:bg4uvfr) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h#L26)):*
> ```objc
> // Channel arg indicating xds_cluster_resolver LB policy should use the fake
> // DNS resolver to resolve logical dns cluster.
> #define GRPC_ARG_XDS_LOGICAL_DNS_CLUSTER_RESOLVER_RESPONSE_GENERATOR \
> ```

s/RESOLVER/FAKE_RESOLVER/
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h, line 27 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRQxMO02F8WNNs9ooqR:-MRQxMO02F8WNNs9ooqS:bqp36w7) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h#L27)):*
> ```objc
> // DNS resolver to resolve logical dns cluster.
> #define GRPC_ARG_XDS_LOGICAL_DNS_CLUSTER_RESOLVER_RESPONSE_GENERATOR \
>   "grpc.internal.xds_logical_dns_cluster_resolver_response_generator"
> ```

s/resolver/fake_resolver/
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 930 at r5](https://reviewable.io/reviews/grpc/grpc/25078#-MQrIujo6Ep7qucPKsRA:-MRR1EMP4J-eznXHSaS7:b-6qp553) ([raw file](https://github.com/grpc/grpc/blob/8255fcac855245d83ccf819c1fb9bea6edadc4fc/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L930)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

With the modification you made to avoid incrementing on the last element, this comment was correct the way it was.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 476 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR1kI45ny-hbEJVZpd:-MRR0aOAAzDIWbEpT5Jc:b714c9f) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L476)):*
> ```cpp
>   std::string target;
>   grpc_channel_args* args = nullptr;
>   const grpc_arg* arg = grpc_channel_args_find(
> ```

Suggest using `grpc_channel_args_find_pointer<FakeResolverResponseGenerator>()` here, so you don't need to check whether the arg is a pointer below, and you won't need to cast when you create the new arg.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 481 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR2rl1DwS_zxg8yFjG:-MRR2rl1DwS_zxg8yFjH:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L481)):*
> ```cpp
>   if (arg != nullptr) {
>     if (arg->type == GRPC_ARG_POINTER) {
>       gpr_log(
> ```

Please remove.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 487 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR0QvfCCWosCw_1QN4:-MRR0QvfCCWosCw_1QN5:b-pu4p7x) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L487)):*
> ```cpp
>           "use target fake",
>           arg->value.pointer.p);
>       target = absl::StrCat("fake:///", target);
> ```

`target` does not already have a value here.  Did you mean to use `parent()->server_name_`?

Also, no need for the "///" -- it's sufficient to just use "fake:".
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 490 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR1_F8BegBNI5HtN4C:-MRR1_F8BegBNI5HtN4D:b-lfmtnt) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L490)):*
> ```cpp
>       // change it to GRPC_ARG_FAKE_RESOLVER_RESPONSE_GENERATOR
>       grpc_arg new_arg = FakeResolverResponseGenerator::MakeChannelArg(
>           static_cast<grpc_core::FakeResolverResponseGenerator*>(
> ```

No need for `grpc_core::` here.
___
*[src/core/ext/filters/cli [...]

2021-01-21 09:23 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078)* status: 27 of 31 files reviewed, 30 unresolved discussions (waiting on @markdroth)

___
*[BUILD, line 1486 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR-ndr8Dqy1t9AZ6bE:-MRYSSeWEs61zF8C3vgg:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/BUILD#L1486)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we also need to add `grpc_lb_xds_channel_args` as a dependency here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 463 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRQzt0c6EBQJ039X0hB:-MRYSlmd9mjfEYiZagzD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L463)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be set as part of the initializer list above rather than as a separate statement.

```
    {"discoveryMechanisms", std::move(discovery_mechanisms)},
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 530 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR-OAk7nxgEaaE_50J:-MRYStAnBlzHK8zeHrUO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L530)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should use `name` instead of `config_->cluster()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 547 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR-RfH7uAV6zwdVxWo:-MRYSthAAKO76qT5dxaU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L547)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should use `name` instead of `config_->cluster()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 662 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRQyHodCVZyRZw88Z5q:-MRYT-eo6xH_pqluvm5j:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L662)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::string name(cluster_name);`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h, line 25 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRQxDBu55txetQ_4x9s:-MRYTKF09ZSDCyJ6i5SH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h#L25)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document that this is for testing only.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h, line 26 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRQxIIQ1RbICzU95sZS:-MRYTKXxAIsR7SWAO_7t:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h#L26)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/RESOLVER/FAKE_RESOLVER/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h, line 27 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRQxMO02F8WNNs9ooqR:-MRYTKwb43JMdDw9E5sq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_args.h#L27)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/resolver/fake_resolver/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 476 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR1kI45ny-hbEJVZpd:-MRYolic1m4-qV3EaQ0-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L476)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest using `grpc_channel_args_find_pointer<FakeResolverResponseGenerator>()` here, so you don't need to check whether the arg is a pointer below, and you won't need to cast when you create the new arg.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 481 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR2rl1DwS_zxg8yFjG:-MRZ8RQB7lridJkKIpZe:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L481)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 487 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR0QvfCCWosCw_1QN4:-MRYomQB5YiSnQ0HY1Or:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L487)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`target` does not already have a value here.  Did you mean to use `parent()->server_name_`?

Also, no need for the "///" -- it's sufficient to just use "fake:".
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 490 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR1_F8BegBNI5HtN4C:-MRYomvFC7tiYbJnehoK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L490)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `grpc_core::` here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 499 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR0BeW8YDyDq9Imnb1:-MRZ6t6A3031J4m6OX0y:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L499)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't take ownership of `args`, so you need to destroy it after this call.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 534 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR2qC77SFlGvSEaVKB:-MRZ8OyF8vAHh7D_qv7l:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L534)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1511 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR3sfZ0WHt9JZFQFA-:-MRYqeuS-eOWMl2-E_CA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/test/cpp/end2end/xds_end2end_test.cc#L1511)):*
<details><summary><i>Previously, markdr [...]

2021-01-21 16:19 UTC, markdroth requested changes
Only a few minor tweaks remaining!

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 4 files at r8, 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078#-:-MR_jQQg4BFjJpwjw0g2:bojmnre)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 1514 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR3f2FEZHEYDbL5BWx:-MR_cjzp-BJDww2Rrgj8:b-8obn13) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/test/cpp/end2end/xds_end2end_test.cc#L1514)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

this change cause a ThreadSanitizer: heap-use-after-free
</blockquote></details>

That's very surprising.  Eliminating the temporary variable should not have any effect on the output at all.  Can you show me the error?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1528 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR44lc0h4CJBlShe7Q:-MR_e9v26fhY-Ag37hU9:behgwxy) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/test/cpp/end2end/xds_end2end_test.cc#L1528)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5440 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR7qG10R3pzYCMKeiC:-MR_imbp6hSaEKgWo009:bnprcmn) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/test/cpp/end2end/xds_end2end_test.cc#L5440)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.  I also removed the resource state check; as sometimes the state for the logical_dns_cds is SENT, but not ACKED yet.  Which i think is possible but can cause flakes if we check it?
</blockquote></details>

Is it still flaky if you move the check until after the falilover to backend 2?  If not, I'd prefer to keep this check in, both in this test and in the previous one.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5347 at r9](https://reviewable.io/reviews/grpc/grpc/25078#-MR_fXgnEUC8TuLt1V_d:-MR_fXgnEUC8TuLt1V_e:b61q427) ([raw file](https://github.com/grpc/grpc/blob/82224d682cf24fc152c7c72acc231caf8ce0f34d/test/cpp/end2end/xds_end2end_test.cc#L5347)):*
> ```cpp
>   gpr_setenv("GRPC_XDS_EXPERIMENTAL_ENABLE_AGGREGATE_AND_LOGICAL_DNS_CLUSTER",
>              "true");
>   const char* kLogicalDNSClusterName = "logical_dns_cluster";
> ```

If you use the existing `kDefaultClusterName` instead of creating a new name here, then there will be no need to change the RouteConfiguration.


<!-- Sent from Reviewable.io -->

2021-01-21 18:11 UTC, donnadionne reviewed
PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078#-:-MRa8HpZ45uHONu3UNbb:b-h8gvr0)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 1514 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR3f2FEZHEYDbL5BWx:-MRa1rIG4EQZuEOlCCJp:b-7ql1td) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/test/cpp/end2end/xds_end2end_test.cc#L1514)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That's very surprising.  Eliminating the temporary variable should not have any effect on the output at all.  Can you show me the error?
</blockquote></details>

fixed
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5440 at r7](https://reviewable.io/reviews/grpc/grpc/25078#-MRR7qG10R3pzYCMKeiC:-MRa1vO-A7Y_zQc8QV8x:bcxsnbw) ([raw file](https://github.com/grpc/grpc/blob/9f4cb546511ea2fec8ec24b081b236b5642ac90e/test/cpp/end2end/xds_end2end_test.cc#L5440)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is it still flaky if you move the check until after the falilover to backend 2?  If not, I'd prefer to keep this check in, both in this test and in the previous one.
</blockquote></details>

no flake if checked after, so added them back to 2/3 tests.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5347 at r9](https://reviewable.io/reviews/grpc/grpc/25078#-MR_fXgnEUC8TuLt1V_d:-MRa8FVZ1NQYK8p8uYx0:bc6b549) ([raw file](https://github.com/grpc/grpc/blob/82224d682cf24fc152c7c72acc231caf8ce0f34d/test/cpp/end2end/xds_end2end_test.cc#L5347)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you use the existing `kDefaultClusterName` instead of creating a new name here, then there will be no need to change the RouteConfiguration.
</blockquote></details>

Done. nice to cut code :)


<!-- Sent from Reviewable.io -->

2021-01-21 18:15 UTC, markdroth approved these changes
Looks great!

> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25078#-:-MRa9-1B73K9fxbMW3H2:b9bkkp1)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5412 at r10](https://reviewable.io/reviews/grpc/grpc/25078#-MRa8o3C4GUT6cXQ9U1Y:-MRa8o3C4GUT6cXQ9U1Z:b-n7c0sn) ([raw file](https://github.com/grpc/grpc/blob/48171d8207d5decd408d46e29de75203124a8458/test/cpp/end2end/xds_end2end_test.cc#L5412)):*
> ```cpp
>   EXPECT_EQ(balancers_[0]->ads_service()->cds_response_state().state,
>             AdsServiceImpl::ResponseState::ACKED);
> ```

Please remove unnecessary blank line.


<!-- Sent from Reviewable.io -->

2021-01-22 00:48 UTC, merged