Convert grpc_ares_wrapper.h APIs to C++
grpc/grpc pull request #25108
Opened 2021-01-07 02:25 UTC by apolcyn

The primary change here is to have `grpc_dns_lookup_ares_locked` return a `unique_ptr<AresRequestInterface>`.

Conversion of the remaining C-code in `grpc_ares_wrapper.cc` is left for more followups.

2021-01-13 00:02 UTC, markdroth requested changes
This looks like a step in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108#-:-MQt26uu-YJmR3X4Sa3K:bxm0p1e)* status: all files reviewed, 10 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 104 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt1rvlAkuAsUzaaG2X:-MQt1rvlAkuAsUzaaG2Y:bzgd0bd) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L104)):*
> ```cpp
>   bool resolving_ = false;
>   /// the pending resolving request
>   std::unique_ptr<AresRequestInterface> pending_request_ = nullptr;
> ```

No need for `= nullptr`.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQsymRe91M4XK_cRlC9:-MQsymRe91M4XK_cRlCA:b-96s66) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L47)):*
> ```objc
> namespace grpc_core {
> 
> class AresRequestInterface {
> ```

This doesn't really need to be an interface, since there's only ever one concrete implementation of it.  If the goal here is just to hide the internal state, then let's just make all of the data members private (which they should be in a class anyway).
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQsxxWx84lXp7A7KWqO:-MQsxxWz4xleJ-VBa43D:briuy4h) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L53)):*
> ```objc
> };
> 
> /* Asynchronously resolve \a name. Use \a default_port if a port isn't
> ```

Might as well switch to C++-style comments while we're at it.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 54 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQsyCYo9_O3Zxetsw5O:-MQsyCYo9_O3Zxetsw5P:b9nhsq9) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L54)):*
> ```objc
> 
> /* Asynchronously resolve \a name. Use \a default_port if a port isn't
>    designated in \a name, otherwise use the port in \a name. grpc_ares_init()
> ```

Please update comments to refer to the new function names (e.g., `AresInit()` instead of `grpc_ares_init()`).
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 71 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt-Jqc2MgiSrkbPj-a:-MQt-Jqc2MgiSrkbPj-b:b-wpmz7u) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L71)):*
> ```objc
>   being held by the caller. The returned AresRequestInterface object is owned
>   by the caller and it is safe to destroy after on_done is called back. */
> extern std::unique_ptr<AresRequestInterface> (*LookupAresLocked)(
> ```

Can this be a static method of `AresRequestInterface`?  Or would that be too hard, given that it needs to be overridable in tests?
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 81 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt-i1FD4f0N84wYW1m:-MQt-i1FD4f0N84wYW1n:bk7nuo8) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L81)):*
> ```objc
> /* Initialize gRPC ares wrapper. Must be called at least once before
>    grpc_resolve_address_ares(). */
> grpc_error* AresInit(void);
> ```

Can these two be static methods of `AresRequestInterface`?
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 96 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt-qyK8mufDHWpzRuf:-MQt-qyK8mufDHWpzRug:b9au4lt) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L96)):*
> ```objc
> 
> /* Exposed in this header for C-core tests only */
> extern void (*AresTestOnlyInjectConfig)(ares_channel channel);
> ```

This can be in a nested `internal` namespace.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 67 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt0ft75fiaGyRPoAJO:-MQt0ft75fiaGyRPoAJP:b-xmhtcf) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L67)):*
> ```cpp
> 
> struct grpc_ares_request : public AresRequestInterface {
>   explicit grpc_ares_request(
> ```

No need for `explicit` here.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 581 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt147SDwKmXMza_zOF:-MQt147SDwKmXMza_zOG:bvkodo2) ([raw file](https://github.com/grpc/grpc/blob/66ee197a1acf95857e44c01fc895e6b7cd211a2d/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L581)):*
> ```cpp
>                                              ServerAddressList* addresses) {
>   if (GRPC_TRACE_FLAG_ENABLED(grpc_trace_cares_address_sorting)) {
>     log_address_sorting_list(r, *addresses, "input");
> ```

Why move this from here into the callers?  Seems like this adds duplication.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 1118 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt1JpD0ShTP0BeXeS4:-MQt1JpD0ShTP0BeXeS5:b-1ue5vp) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L1118)):*
> ```cpp
>   if (resolve_as_ip_literal_locked(name, default_port, addrs)) {
>     grpc_ares_complete_request_locked(r.get());
>     return std::move(r);
> ```

No need for `std::move()` in a `return` statement.  That happens automatically.

Same thing throughout.


<!-- Sent from Reviewable.io -->

2021-01-13 18:27 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: all files reviewed, 10 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 104 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt1rvlAkuAsUzaaG2X:-MQwspXL5o6YgDqEyflI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L104)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `= nullptr`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQsymRe91M4XK_cRlC9:-MQwsqfa44prqffNUnF1:b-viyh8z) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L47)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't really need to be an interface, since there's only ever one concrete implementation of it.  If the goal here is just to hide the internal state, then let's just make all of the data members private (which they should be in a class anyway).
</blockquote></details>

I just did that to avoid needing to declare classes in the header file, but I've updated to put the `grpc_ares_request` into the header (renamed into `AresRequest`).

I haven't yet made any data members of `AresRequest` private though, only since that would expand the scope of this PR a lot.

PLMK if you'd like to do that in this PR, though.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQsxxWx84lXp7A7KWqO:-MQwuRxg9Qv5lDkbb-N3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L53)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Might as well switch to C++-style comments while we're at it.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 54 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQsyCYo9_O3Zxetsw5O:-MQwuTCz1MZR9yyuY7aR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please update comments to refer to the new function names (e.g., `AresInit()` instead of `grpc_ares_init()`).
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 71 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt-Jqc2MgiSrkbPj-a:-MQwuUZgDe1Xxhhjb3IN:b-ehai54) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L71)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can this be a static method of `AresRequestInterface`?  Or would that be too hard, given that it needs to be overridable in tests?
</blockquote></details>

Right, the global method seems easiest to override for tests, so I'll tend to keep as is if OK.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 81 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt-i1FD4f0N84wYW1m:-MQwyJ490O6Tb85eOJWM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can these two be static methods of `AresRequestInterface`?
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 96 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt-qyK8mufDHWpzRuf:-MQwyJd85CapY17QANwZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L96)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be in a nested `internal` namespace.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 67 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt0ft75fiaGyRPoAJO:-MQwyKKpD9DRqTEO1ZVj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L67)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `explicit` here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 581 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt147SDwKmXMza_zOF:-MQwyLAiDtkJdtqfEuBP:b-qshtc8) ([raw file](https://github.com/grpc/grpc/blob/66ee197a1acf95857e44c01fc895e6b7cd211a2d/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L581)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why move this from here into the callers?  Seems like this adds duplication.
</blockquote></details>

I moved this out since I wanted to log service addresses and grpclb addresses with slightly differently, but I've put this back into the sorting helper by adding a parameter to differentiate the logs.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 1118 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt1JpD0ShTP0BeXeS4:-MQwybMNCKlB6bByQRF6:b-praz2y) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L1118)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `std::move()` in a `return` statement.  That happens automatically.

Same thing throughout.
</blockquote></details>

I had issues with a distrib test using an old gcc, which motivated this. I think that issue is no longer relevant though now that `AresRequest` isn't a derived class.;


<!-- Sent from Reviewable.io -->

2021-01-14 17:55 UTC, markdroth requested changes
Thanks for doing this!

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108#-:-MR11OFG5r7r_y1AxykT:b-pevjuw)* status: all files reviewed, 7 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQsymRe91M4XK_cRlC9:-MR0ztHd82QjSedILPCL:brqqj18) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L47)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I just did that to avoid needing to declare classes in the header file, but I've updated to put the `grpc_ares_request` into the header (renamed into `AresRequest`).

I haven't yet made any data members of `AresRequest` private though, only since that would expand the scope of this PR a lot.

PLMK if you'd like to do that in this PR, though.
</blockquote></details>

It does seem like it would be better to just convert the whole module to C++ in a single PR, if that's not too hard.  But I can live with it being split up if you'd prefer; if so, just add a TODO comment here indicating that we plan to finish converting it to idiomatic C++ in a subsequent PR.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 49 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR0zQ0H2W5l1YSpUB8K:-MR0zQ0H2W5l1YSpUB8L:bypeh8s) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L49)):*
> ```objc
> typedef struct grpc_ares_ev_driver grpc_ares_ev_driver;
> 
> struct AresRequest {
> ```

Please document what this struct represents, how it's expected to be used, lifetime semantics, etc.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 61 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR0zfPu5TV-Evp4_-6J:-MR0zfPu5TV-Evp4_-6K:b-9xjmdj) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L61)):*
> ```objc
> 
>   /// Initialize the gRPC ares wrapper. Must be called at least once before
>   /// grpc_core::ResolveAddressAres().
> ```

No need for `grpc_core::` in any of these comments, since we're already in that namespace.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 68 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR0zYJN6gDfAfxqgD-h:-MR0zYJN6gDfAfxqgD-i:b-rglhl) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L68)):*
> ```objc
>   /// wrapper only if it has been called the same number of times as
>   /// grpc_core::AresInit().
>   static void Cleanup(void);
> ```

Suggest calling this `Shutdown()`, for consistency with the term we use throughout core.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR0zEZC-Oby3hLBMZ1V:-MR0zEZC-Oby3hLBMZ1W:b-lkd0xe) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L103)):*
> ```objc
> /// designated in \a name, otherwise it uses the port in \a name. AresInit()
> /// must be called at least once before this function. The returned
> /// AresRequest object is owned by the caller and it is safe to destroy
> ```

Since the return value is a `unique_ptr<>`, we don't need to explicitly state that ownership is transferred; that's implicit in the API now.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 581 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt147SDwKmXMza_zOF:-MR118HYDlfBR-zlpAqM:b72q64m) ([raw file](https://github.com/grpc/grpc/blob/66ee197a1acf95857e44c01fc895e6b7cd211a2d/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L581)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I moved this out since I wanted to log service addresses and grpclb addresses with slightly differently, but I've put this back into the sorting helper by adding a parameter to differentiate the logs.
</blockquote></details>

Are there external callers of this API, or is it only exposed for testing purposes?  If the former, then it might be better to just have the caller log a separate message with the context before calling this function.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MR1-Yi8AzQyNhocQl4E:b-blm0ws) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
> ```cpp
> } grpc_ares_hostbyname_request;
> 
> static void AresRequest_ref_locked(AresRequest* r);
> ```

When we do finish converting this to C++, we should probably just make `AresRequest` inherit from `InternallyRefCounted<>`.  (Internally, see go/grpc-c-core-ref-counted-types-update for expected usage.)


<!-- Sent from Reviewable.io -->

2021-01-20 19:05 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQsymRe91M4XK_cRlC9:-MRW7lkU-4y6yoXQjZZc:bn10thf) ([raw file](https://github.com/grpc/grpc/blob/39a4d82dec3a4fc88ceb3f74b347cde4e14cbc97/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L47)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It does seem like it would be better to just convert the whole module to C++ in a single PR, if that's not too hard.  But I can live with it being split up if you'd prefer; if so, just add a TODO comment here indicating that we plan to finish converting it to idiomatic C++ in a subsequent PR.
</blockquote></details>

I've went ahead and converted the rest of the module to C++
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 49 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR0zQ0H2W5l1YSpUB8K:-MRW6LcREduUHRcOl0nd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L49)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document what this struct represents, how it's expected to be used, lifetime semantics, etc.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 61 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR0zfPu5TV-Evp4_-6J:-MRW6MXi5oHztBKd4wWv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L61)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `grpc_core::` in any of these comments, since we're already in that namespace.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 68 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR0zYJN6gDfAfxqgD-h:-MRW6N7P9oroh6bDr0Ec:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L68)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `Shutdown()`, for consistency with the term we use throughout core.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR0zEZC-Oby3hLBMZ1V:-MRW7rNY6GlmRa61RQ1-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L103)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since the return value is a `unique_ptr<>`, we don't need to explicitly state that ownership is transferred; that's implicit in the API now.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 581 at r1](https://reviewable.io/reviews/grpc/grpc/25108#-MQt147SDwKmXMza_zOF:-MRW7vCg9_s6I3rz1t4Q:b-h6cp49) ([raw file](https://github.com/grpc/grpc/blob/66ee197a1acf95857e44c01fc895e6b7cd211a2d/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L581)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Are there external callers of this API, or is it only exposed for testing purposes?  If the former, then it might be better to just have the caller log a separate message with the context before calling this function.
</blockquote></details>

This is only exposed for testing purposes
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MRW7ydY-ZqxkTHckk7b:bmjgm4f) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

When we do finish converting this to C++, we should probably just make `AresRequest` inherit from `InternallyRefCounted<>`.  (Internally, see go/grpc-c-core-ref-counted-types-update for expected usage.)
</blockquote></details>

Thanks for the link to go/grpc-c-core-ref-counted-types-update.

After looking at this for a while, the IMO cleanest setup I've found is to keep `AresRequest` as a `unique_ptr` in it's external owner, and to introduce a small internal wrapper (which is `DualRefCounted`) over the `AresRequest`, and this wrapper is responsible for deciding when to schedule `on_done`.

My argument is that there are three different sets of owners of the `AresRequest` object:

1) The single external owner, i.e. the caller of `LookupAresLocked`

2) All pending DNS resolutions (e.g. one ref for A records, another for AAAA, SRV, etc.)

3) Timer and I/O callbacks

The contract with the external owner is that the `AresRequest` object is safe to delete as soon as `on_done` is scheduled, so we just need to make sure that owners 2) and 3) are all gone first, and then we're safe to schedule `on_done`.

Owners 2) and 3) are different though, because as soon as all owners in 2) are gone, we want to cancel/shutdown/remove all owners in 3) as soon as possible.

So, the internal wrapper object uses owners in 2) as strong refs and owners in 3) as weak refs, and we schedule `on_done` in the wrapper object's dtor.

PLMK


<!-- Sent from Reviewable.io -->

2021-01-20 23:26 UTC, markdroth requested changes
Thanks for doing this!  I'm really excited to see this code being modernized.

My only really significant comment is the one about the ref-counting semantics.  Most of the others are relatively minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108#-:-MRX6B-i1ys3DwK9WwAu:birb0hn)* status: all files reviewed, 27 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 55 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWDDEq5PYSj96xnFul:-MRWDDEq5PYSj96xnFum:bjwuagd) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L55)):*
> ```objc
> /// (A queries, AAAA queries, etc.). An AresRequest is created with a call
> /// to LookupAresLocked, and it's safe to destroy as soon as the \a on_done
> /// callback passed to LookupAresLocked is ran. Meanwhile, a name resolution
> ```

s/is ran/has been run/
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 59 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWDNpFAJJmmBWakh5i:-MRWDNpFAJJmmBWakh5j:b9ysip2) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L59)):*
> ```objc
> class AresRequest final {
>  public:
>   static std::unique_ptr<AresRequest> LookupAresLockedImpl(
> ```

Suggest calling this `Create()`.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 60 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWkgqSAAF_k_fZhZsz:-MRWkgqSAAF_k_fZhZt-:bzbuznr) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L60)):*
> ```objc
>  public:
>   static std::unique_ptr<AresRequest> LookupAresLockedImpl(
>       const char* dns_server, const char* name, const char* default_port,
> ```

Please pass in all three of these parameters as `absl::string_view`.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 61 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWE-gn3DZnHavt8wjO:-MRWE-go6HH3JaV9wFUB:b-d5b75b) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L61)):*
> ```objc
>   static std::unique_ptr<AresRequest> LookupAresLockedImpl(
>       const char* dns_server, const char* name, const char* default_port,
>       grpc_pollset_set* interested_parties, grpc_closure* on_done,
> ```

Let's use `std::function<>` instead of `grpc_closure`.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 64 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWjOJW7CYc4INcQIFR:-MRWjOJW7CYc4INcQIFS:b5m1mu0) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L64)):*
> ```objc
>       std::unique_ptr<grpc_core::ServerAddressList>* addrs,
>       std::unique_ptr<grpc_core::ServerAddressList>* balancer_addrs,
>       char** service_config_json, int query_timeout_ms,
> ```

Let's use `std::string*` for `service_config_json`.

Same thing throughout.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 65 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWDXxiEmd-yQqIDK5k:-MRWDXxiEmd-yQqIDK5l:bhwcfvp) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L65)):*
> ```objc
>       std::unique_ptr<grpc_core::ServerAddressList>* balancer_addrs,
>       char** service_config_json, int query_timeout_ms,
>       std::shared_ptr<grpc_core::WorkSerializer> work_serializer);
> ```

As part of our long-term strategy to move the c-ares integration out of the client_channel code and into the iomgr code, it might be a good idea to remove the `WorkSerializer` here and instead just use a mutex internally.  That way, callers that don't use a `WorkSerializer` (basically everything *except* the client_channel code) can use this API without needing to provide one, and the client_channel code can be responsible for hopping back into the `WorkSerializer` when its callback function is invoked.

This doesn't need to be done as part of this PR, though.  We can just add a TODO for now.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 69 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWEKjY59M6FcuIg7nD:-MRWEKjY59M6FcuIg7nE:b-p5ocw5) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L69)):*
> ```objc
>   /// Cancel the pending request. Must be called while holding the
>   /// WorkSerializer that was used to call \a LookupAresLocked.
>   void ShutdownLocked();
> ```

I think the original name made more sense here.  This is for cancelling an individual request, not shutting down the whole subsystem.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 92 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWGCoZBZkU6Dtu0hdT:-MRWGCoZBZkU6Dtu0hdU:b-vbpj2v) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L92)):*
> ```objc
>   /// AresRequest object (the one that invoked LookupAresLocked) can safely
>   /// destroy it.
>   class OnDoneScheduler final : public DualRefCounted<OnDoneScheduler> {
> ```

If we do keep this class for some reason (see my comment elsewhere for why I don't think we should have it), it should be private within `AresRequest`, since it's not needed outside of the implementation.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 109 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWm1-kDOF0lIh1024m:-MRWm1-kDOF0lIh1024n:b-qb37l6) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L109)):*
> ```objc
> 
>  private:
>   explicit AresRequest(
> ```

No need for `explicit`, since there is more than one argument here.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 109 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWm3oR6nmIaquwU-MV:-MRWm3oR6nmIaquwU-MW:b33dtd0) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L109)):*
> ```objc
> 
>  private:
>   explicit AresRequest(
> ```

If we make `AresRequest` `InternallyRefCounted<>` as I suggested elsewhere, then we'll probably want to make this ctor public.  We can document that callers should use the factory method instead of instantiating this directly, but making this private will make it impossible to use `MakeOrphanable<>` even from within the factory method.

For related discussion, see https://abseil.io/tips/134.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 154 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWij6sApHrPk9nz8-J:-MRWij6sApHrPk9nz8-K:b-j5wvsv) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L154)):*
> ```objc
>   }
> 
>   struct FdNode {
> ```

Let's make this a class (private data members with appropriate names, etc).
___
*[src/core/ext/filters/client_channel/resolver/dns/ [...]

2021-01-21 22:45 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: 9 of 11 files reviewed, 27 unresolved discussions (waiting on @apolcyn and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MRb4pW93Y9qKywV0gK0:b4vvtqs) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This ownership model seems very different from the way we typically do things, and I think it's a lot more complex than what we really need.  I don't think we should need to differentiate between the refs held by individual DNS queries and those that correspond to timers and I/O callbacks.

I am assuming here that we have the following properties:
- When a DNS query is started, that triggers I/O, which will eventually invoke a callback.
- When a DNS query finishes, all I/O associated with that query has been completed.  (There may be additional I/O callbacks outstanding at this point, but if so they can be cancelled as soon as we know that they're not needed.)

If those properties hold, then I don't think we actually need to hold any refs for the DNS queries themselves; it should be sufficient to hold refs only for the underlying I/O callbacks.  We just need to make sure that the last I/O callback for a given DNS query processes the result of the DNS query before it releases its ref.

To say this another way, it seems like we actually have two distinct problems here:
1. Deciding when it's safe to destroy the `AresRequest` object.
2. Deciding when to invoke the on-done callback.

I think this will be simpler if we pull those two problems apart and have a separate solution for each of them.  I think we should use ref-counting for (1) but a separate mechanism for (2).

For (1), I think we should make the `AresRequest` object itself be `InternallyRefCounted<>`.  The internal refs will be held by the I/O and timer callbacks, but the caller doesn't have to know or care about any of that.  The caller can just use an `OrphanablePtr<>` to hold this object, and it can orphan the object whenever it's done with the request.  Orphaning the object will cancel any in-flight DNS queries, so the underlying I/O callbacks will return failures, which will cause us to invoke the on-done callback with an error.  It will also release the caller's ref.

For (2), I think we can simply have the `AresRequest` object contain an integer data member that indicates the number of in-flight queries.  Whenever we launch a query, we increment it; whenever a query completes, we decrement it.  At the end of completing a query (after starting any subsequent queries that may be needed), if the count is zero, then we invoke the on-done callback.  (Or if we need something more complex for some reason, we could do something like having a separate bool for each DNS query to indicate if it's complete.)

This approach will de-couple the logic for invoking the on-done callback from the ref-counting logic.  It will avoid the need for this `OnDoneScheduler` class.  And it will allow us to invoke the on-done callback as soon as we have the result, independently of whether we're still waiting for some straggling callbacks to run before destroying the `AresRequest` object itself.
</blockquote></details>

The main problem I'm worried about with de-coupling the scheduling of `on_done` and the destruction of the `AresRequest` is that this makes it harder to reason about the correctness of the `AresRequest` lifetime.

If they `on_done` and the `AresRequest` dtor are coupled, then because we don't schedule `on_done` until the `AresRequest` has no internal refs left, the entity that constructed the `AresRequest` also manages its deletion, and in this way we can basically guarantee that DNS resolutions don't leave any leaks.

If we leave around stray timer and I/O callbacks after scheduling `on_done`, I'd be worried running into a hard-to-debug scenario where e.g. timer or I/O callbacks don't getting cleaned up in a timely manner after the resolution is done, and this kind of leak might not be easily caught in e.g. unit tests.


<!-- Sent from Reviewable.io -->

2021-01-22 19:01 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: 9 of 11 files reviewed, 27 unresolved discussions (waiting on @apolcyn and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MRfSbVSBWwcCmHQoV8e:b3j8xss) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

The main problem I'm worried about with de-coupling the scheduling of `on_done` and the destruction of the `AresRequest` is that this makes it harder to reason about the correctness of the `AresRequest` lifetime.

If they `on_done` and the `AresRequest` dtor are coupled, then because we don't schedule `on_done` until the `AresRequest` has no internal refs left, the entity that constructed the `AresRequest` also manages its deletion, and in this way we can basically guarantee that DNS resolutions don't leave any leaks.

If we leave around stray timer and I/O callbacks after scheduling `on_done`, I'd be worried running into a hard-to-debug scenario where e.g. timer or I/O callbacks don't getting cleaned up in a timely manner after the resolution is done, and this kind of leak might not be easily caught in e.g. unit tests.


</blockquote></details>

Handling these remaining timer and I/O callbacks is actually the exact case that the `InternallyRefCounted<>` pattern was created for.  If we were always afraid that there might be a bug that prevents us from cleaning the object up, then we'd never be able to use this pattern anywhere.

Is there some reason that it's somehow more likely that a stray timer or I/O callback might not be cleaned up in this case than in any other case where we use `InternallyRefCounted<>`?  If not, I don't think this is a good reason not to use that pattern.


<!-- Sent from Reviewable.io -->

2021-01-23 00:06 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: 9 of 11 files reviewed, 27 unresolved discussions (waiting on @apolcyn and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 55 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWDDEq5PYSj96xnFul:-MRcfeM9CT6zavrza9fu:b-ods88m) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L55)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/is ran/has been run/
</blockquote></details>

Done. But changed to "has began to run" to make it clear that it can be destroyed from within the callback
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 59 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWDNpFAJJmmBWakh5i:-MRcfvsM1P62jMNvxgCs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `Create()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 60 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWkgqSAAF_k_fZhZsz:-MRcg5KFC1Mug74b_zaa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please pass in all three of these parameters as `absl::string_view`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MRgVkf1AfKKoxWkHDIj:bue3sns) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Handling these remaining timer and I/O callbacks is actually the exact case that the `InternallyRefCounted<>` pattern was created for.  If we were always afraid that there might be a bug that prevents us from cleaning the object up, then we'd never be able to use this pattern anywhere.

Is there some reason that it's somehow more likely that a stray timer or I/O callback might not be cleaned up in this case than in any other case where we use `InternallyRefCounted<>`?  If not, I don't think this is a good reason not to use that pattern.
</blockquote></details>

There's not a particular reason that makes this code more likely to have timer or fd leaks, but the interactions are complicated enough that I'd be weary of at least introducing new bugs.

For example, with the approach that delays `on_done` until the object is safe to delete, one nice thing is that if a code change introduces a bug that causes such a leak, nothing will work at all and we'll catch it right away. But if we leave around stray refs, such a bug could more easily go undetected -- i.e. it makes it now difficult to test that the code is correct.

I can get behind the desire to be consistent with other cases in the code base, but I also think that the approach of delaying `on_done` until the object is safe to delete fits better with the C++ style guide's recommendation that objects be deleted by the code that creates them if it's possible.

What do you think if we got rid of the `OnDoneScheduler` object, but still delayed `on_done` until the object is safe to delete (we could perhaps do this with a counter of pending queries, and some kind of `MaybeScheduleOnDone` helper at the end of every query, timer, and I/O callback) ?

Thanks for the review so far though, I'm still working on getting back to the rest of the comments.


<!-- Sent from Reviewable.io -->

2021-01-26 08:05 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: 5 of 11 files reviewed, 27 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 61 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWE-gn3DZnHavt8wjO:-MRxZjdl78ELOoK6gwCT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L61)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's use `std::function<>` instead of `grpc_closure`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 64 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWjOJW7CYc4INcQIFR:-MRxZmjwEksAMgubsTU9:b-sgb79) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L64)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's use `std::string*` for `service_config_json`.

Same thing throughout.
</blockquote></details>

Done, but changed to `absl::optional<std::string>*`, since it looks like we need to differentiate no service config with empty string service config
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 65 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWDXxiEmd-yQqIDK5k:-MRxZyWRCfG0vIfaBbTw:b37yi71) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As part of our long-term strategy to move the c-ares integration out of the client_channel code and into the iomgr code, it might be a good idea to remove the `WorkSerializer` here and instead just use a mutex internally.  That way, callers that don't use a `WorkSerializer` (basically everything *except* the client_channel code) can use this API without needing to provide one, and the client_channel code can be responsible for hopping back into the `WorkSerializer` when its callback function is invoked.

This doesn't need to be done as part of this PR, though.  We can just add a TODO for now.
</blockquote></details>

Added a TODO.

While we can definitely make this not take a `WorkSerializer` as a parameter, I'm a little worried that using a `Mutex` internally may cause more complicated code than with a `WorkSerializer`, but we can feasibly use either one internally.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 69 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWEKjY59M6FcuIg7nD:-MRx_hBm4HFfYNA32iKS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L69)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the original name made more sense here.  This is for cancelling an individual request, not shutting down the whole subsystem.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 92 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWGCoZBZkU6Dtu0hdT:-MRx_i76D2OicuVUDBnG:bq1qlhp) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L92)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we do keep this class for some reason (see my comment elsewhere for why I don't think we should have it), it should be private within `AresRequest`, since it's not needed outside of the implementation.
</blockquote></details>

Latest approach gets rid of this class
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 109 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWm1-kDOF0lIh1024m:-MRx_lCYA_SljDske-4R:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L109)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `explicit`, since there is more than one argument here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 109 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWm3oR6nmIaquwU-MV:-MRx_wyW-Lak7yPacfuv:biy1qkl) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L109)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we make `AresRequest` `InternallyRefCounted<>` as I suggested elsewhere, then we'll probably want to make this ctor public.  We can document that callers should use the factory method instead of instantiating this directly, but making this private will make it impossible to use `MakeOrphanable<>` even from within the factory method.

For related discussion, see https://abseil.io/tips/134.
</blockquote></details>

Made this public
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 154 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWij6sApHrPk9nz8-J:-MRxa-UQ7L4CcE_8PegI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L154)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's make this a class (private data members with appropriate names, etc).
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 154 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWl-9DBbsPkNNh7457:-MRxa0cD7-xRCRxpHf8T:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L154)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per the style guide, within each section (public, private, etc), types (including structs and classes) should be defined before methods.

https://google.github.io/styleguide/cppguide.html#Declaration_Order
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 202 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWjHaxD5foK598DtLk:-MRxa21L6RnuwSgBhEkE:b-htujgt) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L202)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Would be nice to use `std::string*` here.
</blockquote></details>

changed to `absl::optional<std::string>*` to differentiate non-existant and empty as described above.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 210 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWisMn0VrgGtaxprcV:-MRxaBYV4r5oThIzL3eS:b3buiuf) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L210)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can we use an STL container here instead of the current C-style linked list approach?  Also, ca [...]

2021-01-26 08:06 UTC, apolcyn commented
Comments addresses (though with the ref counting scheme still in discussion).

Thanks for the review so far. A heads up that there still seems to be something happening wrong on Windows, but I think this PR can still otherwise be good for another look.

2021-01-27 00:55 UTC, markdroth requested changes
This is really shaping up nicely!

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 6 files at r6, 2 of 2 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108#-:-MS0KZhz9153AK-ppuqb:b-793kax)* status: all files reviewed, 20 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 422 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS01quv3OWPEZw-RsPz:-MS01quv3OWPEZw-RsQ-:b-59ueh9) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L422)):*
> ```cpp
>   auto on_done = [this](grpc_error* error) {
>     OnResolvedLocked(error);
>     GRPC_ERROR_UNREF(error);
> ```

Ownership of this error should be passed to `OnResolvedLocked()`, as per https://github.com/grpc/grpc/blob/master/doc/core/grpc-error.md#ownership-rules.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 425 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS08WhW3A_Jw7FFq9bC:-MS08WhW3A_Jw7FFq9bD:b7sa7o6) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L425)):*
> ```cpp
>   };
>   pending_request_ = LookupAresLocked(
>       dns_server_, name_to_resolve_, kDefaultPort, interested_parties_, on_done,
> ```

`std::move(on_done)`, or just declare the lambda inline here.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 55 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWDDEq5PYSj96xnFul:-MS031bA-lOb0WxNU1vn:bwddn9q) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L55)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Done. But changed to "has began to run" to make it clear that it can be destroyed from within the callback
</blockquote></details>

How about "has been called"?
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 64 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWjOJW7CYc4INcQIFR:-MS03M-SELcRIw4MrMJ_:b6zrrk4) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L64)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Done, but changed to `absl::optional<std::string>*`, since it looks like we need to differentiate no service config with empty string service config
</blockquote></details>

Good catch!
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 71 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS037LHEmpnwvEhpX8-:-MS037LHEmpnwvEhpX80:b-essxzo) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L71)):*
> ```objc
>       std::shared_ptr<grpc_core::WorkSerializer> work_serializer);
> 
>   static std::unique_ptr<AresRequest> Create(
> ```

As per style guide, factory methods should go before ctors.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 103 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS04tX8ANyp1quXjBlp:-MS04tX8ANyp1quXjBlq:b-65vfwg) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L103)):*
> ```objc
>   class AresQuery {
>    protected:
>     explicit AresQuery(AresRequest* r);
> ```

Please call the parameter `request`, as per general naming rules:

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

Same thing throughout (parameter names, data members, etc).
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 105 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS0491b3QMoY_7fc-N6:-MS0491b3QMoY_7fc-N7:b-sa2kmk) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L105)):*
> ```objc
>     explicit AresQuery(AresRequest* r);
> 
>     ~AresQuery();
> ```

Base class dtor must be virtual, as per style guide.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 110 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS03tCi2GVwHlu0cKpr:-MS03tCi2GVwHlu0cKps:bjrc6vw) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L110)):*
> ```objc
>   };
> 
>   class AddressQuery : AresQuery {
> ```

All inheritence must be `public`, as per style guide.

Same thing throughout.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 200 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS0EwN_-8wrnS4QCcdi:-MS0EwNa9TU6v4OvXnvY:bik6xu2) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L200)):*
> ```objc
>     bool writable_registered_ = false;
>     // if the fd has been shutdown yet from grpc iomgr perspective
>     bool already_shutdown_ = false;
> ```

Suggest removing the `already_` prefix here.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MS05ktPEfJtIBNnw2Yq:bh5g1av) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

The latest approach gets rid of the `OnDoneScheduler` class and the `DualRefCounted` idea, but replaces with a more manual approach which uses a `MaybeCallOnDone` helper function, and the new `pending_queries_`, `timeout_done_` and `backup_poller_done_` fields. 

I'm wondering if you think this new approach can look simpler and more reasonable. Please let me know.
</blockquote></details>

I'd still prefer to just make this `InternallyRefCounted<>`, for the following reasons:
- We have a standard pattern in C-core for how we handle cases like these, and I think we need to have a compelling reason to do something different here.  I'm not really seeing one in this case.
- I don't think this code is that much more complex than any of the other classes inside C-core that have internal refs for pending callbacks, so I don't think it's actually that much more likely to cause a leak.
- If we did have a bug and it did cause a leak, the asan tests would catch it anyway, so delaying the on-done callback doesn't actually give us any additional safety.  But it can delay sending the response back to the caller, which can hurt latency.
- The approach of having to depend on 3 different fields here is actually more complex and harder to understand than simply using `InternallyRefCounted<>`.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 96 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWndn88IrPSmNp8uDA:-MS08G4o7sFdH7S9B-wI:btfeupy) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L96)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can split them out by class -- e.g., define the methods of `AresRequest::AresQuery` first, then the methods of `AresRequest::AddressQuery`, then `AresRequest::SRVQuery` [...]

2021-01-28 00:10 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: 9 of 12 files reviewed, 20 unresolved discussions (waiting on @apolcyn and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 422 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS01quv3OWPEZw-RsPz:-MS5BJafECcml705Z1ZG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L422)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ownership of this error should be passed to `OnResolvedLocked()`, as per https://github.com/grpc/grpc/blob/master/doc/core/grpc-error.md#ownership-rules.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 425 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS08WhW3A_Jw7FFq9bC:-MS5BK5x802Ow5wVsrcU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L425)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move(on_done)`, or just declare the lambda inline here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 55 at r4](https://reviewable.io/reviews/grpc/grpc/25108#-MRWDDEq5PYSj96xnFul:-MS5BLjU14Cy0t1NvvKc:bb7f2mf) ([raw file](https://github.com/grpc/grpc/blob/2e51347f27a23378a9bd282490754e013d220ad6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L55)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about "has been called"?
</blockquote></details>

done
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 71 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS037LHEmpnwvEhpX8-:-MS5BP872urZunZID9G_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L71)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per style guide, factory methods should go before ctors.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 103 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS04tX8ANyp1quXjBlp:-MS5BV_j2YC90H5JbO4z:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L103)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call the parameter `request`, as per general naming rules:

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

Same thing throughout (parameter names, data members, etc).
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 105 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS0491b3QMoY_7fc-N6:-MS5CMk37GL0iB3-JToH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L105)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Base class dtor must be virtual, as per style guide.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 110 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS03tCi2GVwHlu0cKpr:-MS5CNSQ3rl-sPBKJGn3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L110)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All inheritence must be `public`, as per style guide.

Same thing throughout.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 200 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS0EwN_-8wrnS4QCcdi:-MS5COPN32SstU-UVo0e:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L200)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest removing the `already_` prefix here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MS5Cx8R560bpT1twjln:bnlgej) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'd still prefer to just make this `InternallyRefCounted<>`, for the following reasons:
- We have a standard pattern in C-core for how we handle cases like these, and I think we need to have a compelling reason to do something different here.  I'm not really seeing one in this case.
- I don't think this code is that much more complex than any of the other classes inside C-core that have internal refs for pending callbacks, so I don't think it's actually that much more likely to cause a leak.
- If we did have a bug and it did cause a leak, the asan tests would catch it anyway, so delaying the on-done callback doesn't actually give us any additional safety.  But it can delay sending the response back to the caller, which can hurt latency.
- The approach of having to depend on 3 different fields here is actually more complex and harder to understand than simply using `InternallyRefCounted<>`.
</blockquote></details>

I'm open to using `InternallyRefCounted` if we still want to use it. I can see the consistency motivation. But I still have a couple of arguments against it:

```
If we did have a bug and it did cause a leak, the asan tests would catch it anyway, so delaying the on-done callback doesn't actually give us any additional safety.
```

There are still a number of potential leaks which won't be caught by asan.

I experimented with using `InternallyRefCounted`, and then applied the following patch to induce bugs that leak both our timers and our fd's:

```
diff --git a/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc b/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc
index aec44ba4afe..b2ae4b3d0fc 100644
--- a/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc
+++ b/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc
@@ -489,7 +489,7 @@ AresRequest::~AresRequest() {
 }
 
 void AresRequest::Orphan() {
-  CancelLocked();
+  //CancelLocked();
   Unref();
 }
 
@@ -720,9 +720,9 @@ void AresRequest::DecrementPendingQueries() {
     // shut down any remaining fds.
     // TODO(apolcyn): just run CancelLocked() ?
     // Unref();
-    shutting_down_ = true;
-    grpc_timer_cancel(&query_timeout_);
-    grpc_timer_cancel(&ares_backup_poll_alarm_);
+    //shutting_down_ = true;
+    //grpc_timer_cancel(&query_timeout_);
+    //grpc_timer_cancel(&ares_backup_poll_alarm_);
     ServerAddressList* addresses = addresses_out_->get();
     if (addresses != nullptr) {
       AddressSortingSort(this, addresses, "service-addresses");
```

.... and I confirmed that even with these bugs, `//test/cpp/naming:resolver_component_tests_runner_invoker` will pass without any complaints from asan.

FWIW, the timer leaks won't be caught  [...]

2021-01-28 17:05 UTC, markdroth requested changes
This is looking really good!

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108#-:-MS8u7EQ0BJhm5bJNTiW:b-jvgm50)* status: all files reviewed, 4 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 422 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS01quv3OWPEZw-RsPz:-MS8p-Nv9M7csq-Zkqtx:b-vjqqco) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L422)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You also need to change `OnResolvedLocked()` to unref it.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 101 at r9](https://reviewable.io/reviews/grpc/grpc/25108#-MS8pD-GApBlvFIIsxUD:-MS8pD-GApBlvFIIsxUE:b-6wd2mc) ([raw file](https://github.com/grpc/grpc/blob/6fa62c83927cb62ab171c264424e55f9190732b6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L101)):*
> ```objc
>   // some book keeping on the relevant AresRequest that's needed to carry
>   // out the overall resolution.
>   class AresQuery {
> ```

Do we actually need this base class?  Why not just have each subclass store the request itself?
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MS8pcWVAgaqFDpN5bei:b-brzxwf) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I'm open to using `InternallyRefCounted` if we still want to use it. I can see the consistency motivation. But I still have a couple of arguments against it:

```
If we did have a bug and it did cause a leak, the asan tests would catch it anyway, so delaying the on-done callback doesn't actually give us any additional safety.
```

There are still a number of potential leaks which won't be caught by asan.

I experimented with using `InternallyRefCounted`, and then applied the following patch to induce bugs that leak both our timers and our fd's:

```
diff --git a/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc b/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc
index aec44ba4afe..b2ae4b3d0fc 100644
--- a/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc
+++ b/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc
@@ -489,7 +489,7 @@ AresRequest::~AresRequest() {
 }
 
 void AresRequest::Orphan() {
-  CancelLocked();
+  //CancelLocked();
   Unref();
 }
 
@@ -720,9 +720,9 @@ void AresRequest::DecrementPendingQueries() {
     // shut down any remaining fds.
     // TODO(apolcyn): just run CancelLocked() ?
     // Unref();
-    shutting_down_ = true;
-    grpc_timer_cancel(&query_timeout_);
-    grpc_timer_cancel(&ares_backup_poll_alarm_);
+    //shutting_down_ = true;
+    //grpc_timer_cancel(&query_timeout_);
+    //grpc_timer_cancel(&ares_backup_poll_alarm_);
     ServerAddressList* addresses = addresses_out_->get();
     if (addresses != nullptr) {
       AddressSortingSort(this, addresses, "service-addresses");
```

.... and I confirmed that even with these bugs, `//test/cpp/naming:resolver_component_tests_runner_invoker` will pass without any complaints from asan.

FWIW, the timer leaks won't be caught because during `grpc_shutdown`, we cancel any still-pending timer callbacks as a part of timer thread shutdown.

And the fd leaks won't be caught I believe because they're registered in some global data structures which bypass asans checks.

We could perhaps catch the fd leaks in our tests if we ran them under `GRPC_ABORT_ON_LEAKS=true` (we might want be doing this for all tests anyways).

I'm not sure about the timer leaks, but there <i>might</i> be something similar to `GRPC_ABORT_ON_LEAKS` that could catch them too.

But overall, these bugs couldn't sneak in as easily if we avoided the stray refs, so I think there are real safety benefits to avoiding them.

```
it can delay sending the response back to the caller, which can hurt latency.
```

I'm not keen on doing this for performance reasons, since this would only be a micro-optimization and it's on the control plane anyways.

```
The approach of having to depend on 3 different fields here is actually more complex and harder to understand than simply using InternallyRefCounted<>.
```

FWIW, the `InternallyRefCounted` approach will still rely on the same `pending_queries_` field and surrounding logic. We can, however, delete the `timeout_done_` and `backup_poller_done_` fields by using `InternallyRefCounted`.



</blockquote></details>

All of your concerns about asan not catching these problems would also apply to almost every other place where we use `InternallyRefCounted<>`, so I don't think that's a good argument for doing something different here.  We have an established pattern for how we handle this kind of use-case in C-core, and I think that to justify doing something different, there needs to be an argument why this case is actually different from all of the others.  Right now, I'm not hearing such an argument.

I'd be fine using `GRPC_ABORT_ON_LEAKS=true` to run `resolver_component_tests_runner_invoker`.  You could also investigate using it for other tests if you want.  I assume that there are reasons why it's not enabled by default for all of our tests, but I'm not sure.

I don't know if there's an equivalent to `GRPC_ABORT_ON_LEAKS` for timers, but I'm also not too worried about timer callbacks leaking.  Even if we forget to cancel a timer, the timer itself will fire normally at some point, and the resources will get cleaned up then.

However, if the timer is set to something like 5 minutes, that can cause significant latency for RPCs.  That seems like a bad failure mode -- we can live with delaying that long to free resources a lot more easily than we can live with delaying RPCs for that long.

I understand that we'll still need `pending_queries_`, but I think that's better, because we'll have two different mechanisms for two different things.  The `pending_queries_` mechanism will be used for deciding when to invoke on_done, and the ref-counting mechanism will be used to decide when to clean up the object.  The two mechanisms don't really need to interact directly at all, so they're both simpler to understand.

Please go ahead and change this code to use `InternallyRefCounted<>`.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 262 at r9](https://reviewable.io/reviews/grpc/grpc/25108#-MS8sNrPE0-vtLPHU8YU:-MS8sNrPE0-vtLPHU8YV:b-1wmsqv) ([raw file](https://github.com/grpc/grpc/blob/6fa62c83927cb62ab171c264424e55f9190732b6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L262)):*
> ```cpp
>     }
>   }
>   // Foquery und a service config record.
> ```

Looks like an accidental edit -- should say "Found".


<!-- Sent from Reviewable.io -->

2021-01-28 19:59 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 422 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS01quv3OWPEZw-RsPz:-MS9Yp3745YhVzWwEK7V:b-99cq7v) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L422)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You also need to change `OnResolvedLocked()` to unref it.
</blockquote></details>

`OnResolvedLocked` is currently unreffing it.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 101 at r9](https://reviewable.io/reviews/grpc/grpc/25108#-MS8pD-GApBlvFIIsxUD:-MS9YjuU1YtSmB682D7a:b-3kf83k) ([raw file](https://github.com/grpc/grpc/blob/6fa62c83927cb62ab171c264424e55f9190732b6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L101)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Do we actually need this base class?  Why not just have each subclass store the request itself?
</blockquote></details>

yeah this base class isn't providing a lot, latest updates get rid of it
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MS9Yvuy32e-YDI_U6zU:bmztjg0) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All of your concerns about asan not catching these problems would also apply to almost every other place where we use `InternallyRefCounted<>`, so I don't think that's a good argument for doing something different here.  We have an established pattern for how we handle this kind of use-case in C-core, and I think that to justify doing something different, there needs to be an argument why this case is actually different from all of the others.  Right now, I'm not hearing such an argument.

I'd be fine using `GRPC_ABORT_ON_LEAKS=true` to run `resolver_component_tests_runner_invoker`.  You could also investigate using it for other tests if you want.  I assume that there are reasons why it's not enabled by default for all of our tests, but I'm not sure.

I don't know if there's an equivalent to `GRPC_ABORT_ON_LEAKS` for timers, but I'm also not too worried about timer callbacks leaking.  Even if we forget to cancel a timer, the timer itself will fire normally at some point, and the resources will get cleaned up then.

However, if the timer is set to something like 5 minutes, that can cause significant latency for RPCs.  That seems like a bad failure mode -- we can live with delaying that long to free resources a lot more easily than we can live with delaying RPCs for that long.

I understand that we'll still need `pending_queries_`, but I think that's better, because we'll have two different mechanisms for two different things.  The `pending_queries_` mechanism will be used for deciding when to invoke on_done, and the ref-counting mechanism will be used to decide when to clean up the object.  The two mechanisms don't really need to interact directly at all, so they're both simpler to understand.

Please go ahead and change this code to use `InternallyRefCounted<>`.
</blockquote></details>

While updating to use `InternallyRefCounted`, I ran into another reason to not use it: the c-ares lookup takes a `grpc_pollset_set` parameter, and `GrpcPolledFd`'s need to use that pollset set. In particular, the posix `GrpcPolledFd` implementation needs to add its fds to the pollset set and then remove them later (it does this in the `GrpcPolledFd` dtor).

The `on_done` callback holds an implicit ref over this pollset set param, and thus calling `on_done` before we're done using the pollset set is unsafe (I noticed this with crashes un the `resolver_component_tests_runner_invoker` under epollex). 
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 807 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS0K3qu6FVfLtP-dm8D:-MS9YYJwArGXw3pcdjIl:bx514z0) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L807)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It would be nice to avoid the `goto`.  In this case, there's only two statements after the `goto`, so we can probably just inline them in the places where we're currently using `goto`.
</blockquote></details>

goto removed from earlier updates
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 262 at r9](https://reviewable.io/reviews/grpc/grpc/25108#-MS8sNrPE0-vtLPHU8YU:-MS9YVMk-HIyMYD_cHax:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6fa62c83927cb62ab171c264424e55f9190732b6/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L262)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like an accidental edit -- should say "Found".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-28 21:43 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MS9w_yK41r4mLzLLeL8:b-dve3gn) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

While updating to use `InternallyRefCounted`, I ran into another reason to not use it: the c-ares lookup takes a `grpc_pollset_set` parameter, and `GrpcPolledFd`'s need to use that pollset set. In particular, the posix `GrpcPolledFd` implementation needs to add its fds to the pollset set and then remove them later (it does this in the `GrpcPolledFd` dtor).

The `on_done` callback holds an implicit ref over this pollset set param, and thus calling `on_done` before we're done using the pollset set is unsafe (I noticed this with crashes un the `resolver_component_tests_runner_invoker` under epollex). 

</blockquote></details>

We can perhaps fix this latter issue by creating a new pollset set that belongs to the `AresRequest` object, adding it to the pollset_set param passed to `LookupAresLocked`, and having internal `GrpcPolledFd` objects use the  pollset set belonging to the `AresRequest` object.

Working on this...


<!-- Sent from Reviewable.io -->

2021-01-29 00:30 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: 8 of 13 files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MSAX-z_01oU1PbR8QmL:bgaror3) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

We can perhaps fix this latter issue by creating a new pollset set that belongs to the `AresRequest` object, adding it to the pollset_set param passed to `LookupAresLocked`, and having internal `GrpcPolledFd` objects use the  pollset set belonging to the `AresRequest` object.

Working on this...
</blockquote></details>

It turns out that creating a pollset_set internal to the `AresRequest` object won't work actually, because, at least under the `poll` poller, we need to delete pollset set B from pollset set A, before destroying B, if we ever previously added B to A. Otherwise, we wind up with a dangling pointer from pollset set A to B.

This bug was caught by `//test/core/http:httpcli_test@poller=poll` FTR, see https://source.cloud.google.com/results/invocations/4498d7e7-b1fe-41b7-9b6f-c53f27d92b3f/targets/%2F%2Ftest%2Fcore%2Fhttp:httpcli_test@poller%3Dpoll/log

So we need to leverage the implicit ref that `on_done` holds over the `LookupAresLocked` pollset set parameter, so long as we need to use that pollset set for anything.

I think this is reason for sticking with the non-refcounted approach.


<!-- Sent from Reviewable.io -->

2021-01-29 07:40 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: 8 of 13 files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MSC3zpi-Wek8qofmxy2:bd8lpf5) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

It turns out that creating a pollset_set internal to the `AresRequest` object won't work actually, because, at least under the `poll` poller, we need to delete pollset set B from pollset set A, before destroying B, if we ever previously added B to A. Otherwise, we wind up with a dangling pointer from pollset set A to B.

This bug was caught by `//test/core/http:httpcli_test@poller=poll` FTR, see https://source.cloud.google.com/results/invocations/4498d7e7-b1fe-41b7-9b6f-c53f27d92b3f/targets/%2F%2Ftest%2Fcore%2Fhttp:httpcli_test@poller%3Dpoll/log

So we need to leverage the implicit ref that `on_done` holds over the `LookupAresLocked` pollset set parameter, so long as we need to use that pollset set for anything.

I think this is reason for sticking with the non-refcounted approach.
</blockquote></details>

Sorry for the back and forth here.

I've fixed this last issue with `InternallyRefCounted` by deleting the fds from the `LookupAresLocked` pollset set param during `GrpcPolledFd::ShutdownLocked`, which is guaranteed to be called on every fd, before `on_done` is called, ensuring liveness of the pollset set during the deletion.

So the code now uses `InternallyRefCounted` again.

PTAL


<!-- Sent from Reviewable.io -->

2021-02-01 23:30 UTC, markdroth requested changes
This looks really good!  Remaining comments are mostly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 5 files at r10, 8 of 8 files at r11.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108#-:-MSUvig5EHBtUHuPivMx:b-eeivja)* status: all files reviewed, 5 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 422 at r8](https://reviewable.io/reviews/grpc/grpc/25108#-MS01quv3OWPEZw-RsPz:-MSUpvSYB9-cBPKdy8hR:b-h7f4xk) ([raw file](https://github.com/grpc/grpc/blob/f635ba63ce256d567f0a678d5dd71ad6e5ca6873/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L422)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

`OnResolvedLocked` is currently unreffing it.
</blockquote></details>

You're right.  Sorry, somehow I thought it wasn't.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h, line 59 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MSUq5VcApO6QyVkZuIX:-MSUq5VcApO6QyVkZuIY:bk4ey47) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h#L59)):*
> ```objc
>  public:
>   virtual ~GrpcPolledFdFactory() {}
>   /* Creates a new wrapped fd for the current platform.
> ```

Please use C++-style comments.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 135 at r2](https://reviewable.io/reviews/grpc/grpc/25108#-MR1-Yi8AzQyNhocQl4D:-MSUr59DESr7GQkSJwYc:b-6suqca) ([raw file](https://github.com/grpc/grpc/blob/bee07447111f8db072f340e7aead46fcbdac8bac/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L135)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Sorry for the back and forth here.

I've fixed this last issue with `InternallyRefCounted` by deleting the fds from the `LookupAresLocked` pollset set param during `GrpcPolledFd::ShutdownLocked`, which is guaranteed to be called on every fd, before `on_done` is called, ensuring liveness of the pollset set during the deletion.

So the code now uses `InternallyRefCounted` again.

PTAL
</blockquote></details>

This looks good!

I agree that the pollset_set lifetime nonsense is annoying.  I hope that all of that will go away as part of moving to the new polling model.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 288 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MSUt0W01e6EfOb6XIei:-MSUt0W182YjSozF0LLI:bl0snpz) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L288)):*
> ```cpp
> AresRequest::FdNode::FdNode(RefCountedPtr<AresRequest> request,
>                             std::unique_ptr<GrpcPolledFd> grpc_polled_fd)
>     : request_(request), grpc_polled_fd_(std::move(grpc_polled_fd)) {
> ```

`std::move(request)`
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 289 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MSUt3uE017xx4p48VhX:-MSUt3uE017xx4p48VhY:b-yuth7e) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L289)):*
> ```cpp
>                             std::unique_ptr<GrpcPolledFd> grpc_polled_fd)
>     : request_(request), grpc_polled_fd_(std::move(grpc_polled_fd)) {
>   GRPC_CARES_TRACE_LOG("request:%p new fd: %s", request.get(),
> ```

This will need to look at `request_` if we use `std::move()` above.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 731 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MSUvOxaDOXHGvtCOzWQ:-MSUvOxaDOXHGvtCOzWR:b-e4m5bz) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L731)):*
> ```cpp
>     // After setting shutting_down_ = true, NotifyOnEventLocked will
>     // shut down any remaining fds.
>     // TODO(apolcyn): just run CancelLocked() ?
> ```

Any reason not to do this?
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 732 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MSUvLta5vG0j9Mxikmz:-MSUvLtb7NaRvHVWoIi8:b-8hh3sw) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L732)):*
> ```cpp
>     // shut down any remaining fds.
>     // TODO(apolcyn): just run CancelLocked() ?
>     // Unref();
> ```

Why is this comment needed?


<!-- Sent from Reviewable.io -->

2021-02-02 22:26 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: 11 of 15 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h, line 59 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MSUq5VcApO6QyVkZuIX:-MSZq7PV0IdwbyXAHUoY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style comments.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 288 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MSUt0W01e6EfOb6XIei:-MSZqCSA-y9tJ50K6i-L:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L288)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move(request)`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 289 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MSUt3uE017xx4p48VhX:-MSZqCqm8XiWdqU-Txy0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L289)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This will need to look at `request_` if we use `std::move()` above.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 731 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MSUvOxaDOXHGvtCOzWQ:-MSZqDhl0fKEGClMeJM6:bjhvcs0) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L731)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Any reason not to do this?
</blockquote></details>

Done. I've changed this method to `ShutdownIOLocked` though, just since this is now a private method and `ShutdownIOLocked` seemed to reflect what it does better.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 732 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MSUvLta5vG0j9Mxikmz:-MSZqcoe-LKwyWCSydBK:b-8awg6w) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L732)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this comment needed?
</blockquote></details>

whoops! removed


<!-- Sent from Reviewable.io -->

2021-03-16 20:01 UTC, markdroth approved these changes
Thanks for the ping on this -- I'm sorry it fell off my radar!

The remaining comments are minor, so feel free to merge after addressing them.

Thanks!

> Reviewed 2 of 4 files at r12, 7 of 7 files at r13.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108#-:-MVwbsl7AmOtALwihmnh:b-aa0l7e)* status: all files reviewed, 4 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h, line 1 at r13](https://reviewable.io/reviews/grpc/grpc/25108#-MVwbeoo8yefAADsQ-9o:-MVwbeoo8yefAADsQ-9p:b-hnyr0r) ([raw file](https://github.com/grpc/grpc/blob/41b3672531338d63c775f09cb113df6a51d6a570/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h#L1)):*
> ```objc
> /*
> ```

Please use C++-style comments here.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h, line 81 at r13](https://reviewable.io/reviews/grpc/grpc/25108#-MVwbhRBBTQ_G3jtcKBp:-MVwbhRBBTQ_G3jtcKBq:b-94z0wx) ([raw file](https://github.com/grpc/grpc/blob/41b3672531338d63c775f09cb113df6a51d6a570/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h#L81)):*
> ```objc
> }  // namespace grpc_core
> 
> #endif /* GRPC_CORE_EXT_FILTERS_CLIENT_CHANNEL_RESOLVER_DNS_C_ARES_GRPC_ARES_EV_DRIVER_H \
> ```

Please use a C++-style comment here as well.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 55 at r13](https://reviewable.io/reviews/grpc/grpc/25108#-MVwaHSTEB1AIy6PrsEU:-MVwaHSTEB1AIy6PrsEV:b-l67trk) ([raw file](https://github.com/grpc/grpc/blob/41b3672531338d63c775f09cb113df6a51d6a570/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L55)):*
> ```objc
> /// An AresRequest is a handle over a complete name resolution process
> /// (A queries, AAAA queries, etc.). An AresRequest is created with a call
> /// to LookupAresLocked, and it the name resolution process begins when
> ```

s/it the/the/
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 799 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MVwbR_DD-m08kC9uID5:-MVwbR_DD-m08kC9uID6:bxm7syj) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L799)):*
> ```cpp
>                        nullptr /* args */);
>     // Let the address sorter figure out which one should be tried first.
>     AddressSortingSort(this, addresses_out_->get(), "service-addresses");
> ```

Why don't we need this anymore?


<!-- Sent from Reviewable.io -->

2021-03-16 23:11 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25108)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h, line 1 at r13](https://reviewable.io/reviews/grpc/grpc/25108#-MVwbeoo8yefAADsQ-9o:-MVxIc6K0i_KuCzLxadP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/41b3672531338d63c775f09cb113df6a51d6a570/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style comments here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h, line 81 at r13](https://reviewable.io/reviews/grpc/grpc/25108#-MVwbhRBBTQ_G3jtcKBp:-MVxIcUa-v4MsY8Uvnp8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/41b3672531338d63c775f09cb113df6a51d6a570/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use a C++-style comment here as well.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 55 at r13](https://reviewable.io/reviews/grpc/grpc/25108#-MVwaHSTEB1AIy6PrsEU:-MVxIbeA2wUyE9NaMq7W:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/41b3672531338d63c775f09cb113df6a51d6a570/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L55)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/it the/the/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 799 at r11](https://reviewable.io/reviews/grpc/grpc/25108#-MVwbR_DD-m08kC9uID5:-MVxI4u0DWvqMsBLcZKo:bw0b9dt) ([raw file](https://github.com/grpc/grpc/blob/f84d6c53ca7de0a4f1f66c9b6b124761924a85ab/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L799)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why don't we need this anymore?
</blockquote></details>

We now only schedule the user-provided `on_done` callback effectively from `DecrementPendingQueries`, and that method first sorts the to-be-returned addresses.


<!-- Sent from Reviewable.io -->

2021-03-17 17:38 UTC, apolcyn commented
Manually squashed commits and force pushed

2021-03-17 20:38 UTC, apolcyn commented
artifact build windows: https://github.com/grpc/grpc/issues/25545

2021-03-17 20:46 UTC, apolcyn commented
basic tests c#: #25748
python windows: https://github.com/grpc/grpc/issues/25749
portability tests windows: https://github.com/grpc/grpc/issues/25751

2021-03-17 20:47 UTC, merged