Change xds_cluster_resolver LB policy config to support combined loca…
grpc/grpc pull request #25270
Opened 2021-01-26 01:15 UTC by donnadionne

…lity- and endpoint-picking policies

- remove unnecessary configs to get ready for new changes.

2021-01-26 21:18 UTC, markdroth requested changes
Sorry for reviewing this before you were ready.  Hope this early review is useful.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MS-YwiT1bXblFcs5NGV:btv3eu9)* status: all files reviewed, 7 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 448 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-Rkq_4pLeoJL5T7kX:-MS-Rkq_4pLeoJL5T7kY:b-pewqwl) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L448)):*
> ```cpp
>     Json::Object xds_lb_policy;
>     if (cluster_data.lb_policy == XdsApi::CdsUpdate::LbPolicy::ROUND_ROBIN) {
>       xds_lb_policy = Json::Object{{"ROUND_ROBIN", Json::Object()}};
> ```

`xds_lb_policy["ROUND_ROBIN"] = Json::Object();`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 451 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-Rp0-3q7Ce877pTVK:-MS-Rp0-3q7Ce877pTVL:bloahf2) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L451)):*
> ```cpp
>     } else if (cluster_data.lb_policy ==
>                XdsApi::CdsUpdate::LbPolicy::RING_HASH) {
>       xds_lb_policy = Json::Object{
> ```

`xds_lb_policy["RING_HASH"] = Json::Object{...};`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 455 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-SwXJ1BAGKDNuPCZI:-MS-SwXJ1BAGKDNuPCZJ:b4bkh6o) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L455)):*
> ```cpp
>                             // TODO@donnadionne: create empty object like
>                             // RingHashLoadBalancingConfig
>                             {"typed_config", Json::Object()},
> ```

I don't think we need the "typed_config" here.  In proto form, this is an `Any` field, but in JSON, it just gets converted to the type embedded in the `Any` field.

So this should basically wind up looking like this in JSON form:

```
"xdsLbPolicy": [
  {"RING_HASH": {
    "minRingSize": <number>,
    "maxRingSize": <number>,
    "hashFunction": <either "XX_HASH" or "MURMUR_HASH_2">
  }}
]
```
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 459 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-S9kfDjrfbS8KMLZe:-MS-S9kfDjrfbS8KMLZf:b-a93bym) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L459)):*
> ```cpp
>     }
>     Json::Object child_config = {
>         {"XdsLbPolicy",
> ```

The "x" should be lower-case here.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 85 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-TlX8EwBuF70XJuxv:-MS-TlX8EwBuF70XJuxw:b3fcc8c) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L85)):*
> ```cpp
> 
>   XdsClusterResolverLbConfig(
>       std::vector<DiscoveryMechanism> discovery_mechanisms)
> ```

This still needs a parameter for the child policy config as a `Json` object.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 845 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-VgGGDDjhRx6BMCQx:-MS-VgGGDDjhRx6BMCQy:byw9731) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L845)):*
> ```cpp
>     const auto& localities = priority_list_[priority].localities;
>     Json::Object weighted_targets;
>     for (const auto& p : localities) {
> ```

This code is going to need to be conditional.  The existing code is fine for the ROUND_ROBIN case, but for the RING_HASH case, we'll need to generate a single-level child for the `xds_cluster_impl` policy.

Also, note that this will also be the place to add the feature we forgot for the fallback design, where the discovery mechanism can override the child policy (which will be used by the logical DNS discovery mechanism to set the child to `pick_first`).  So when both pieces are implemented, the logic here should be something like this:

```
if (discovery_mechanism_overrides_child) {
  // ... use child specified by discovery mechanism ...
} else if (using_round_robin) {
  // ... use existing code ...
} else {  // RING_HASH
  // ... use ring_hash policy ...
}
```
___
*[src/core/ext/xds/xds_api.h, line 235 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-RKX28MQtWAsKzg5_:-MS-RKX28MQtWAsKzg5a:b2254xt) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/xds/xds_api.h#L235)):*
> ```objc
>     enum LbPolicy { ROUND_ROBIN, RING_HASH };
>     ClusterType cluster_type;
>     LbPolicy lb_policy;
> ```

As per the design doc, this should be a string instead of an enum, because in the future we'll want to be able to configure arbitrary LB policies via xDS.

Also, we need to add a bunch of other fields here too.  Please see the design doc for details.


<!-- Sent from Reviewable.io -->

2021-01-29 03:18 UTC, donnadionne reviewed
Thank you for the initial comments! very helpful!  Ready for another review.  Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MSB8TKs5tcMHbHg67vq:bzayq6m)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 448 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-Rkq_4pLeoJL5T7kX:-MS0a3zd935rxyEnoqfg:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L448)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`xds_lb_policy["ROUND_ROBIN"] = Json::Object();`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 451 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-Rp0-3q7Ce877pTVK:-MS0a4PaC129ocwuAYvX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L451)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`xds_lb_policy["RING_HASH"] = Json::Object{...};`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 455 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-SwXJ1BAGKDNuPCZI:-MS0a4v-Ai_QSYF6FFE6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L455)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need the "typed_config" here.  In proto form, this is an `Any` field, but in JSON, it just gets converted to the type embedded in the `Any` field.

So this should basically wind up looking like this in JSON form:

```
"xdsLbPolicy": [
  {"RING_HASH": {
    "minRingSize": <number>,
    "maxRingSize": <number>,
    "hashFunction": <either "XX_HASH" or "MURMUR_HASH_2">
  }}
]
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 459 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-S9kfDjrfbS8KMLZe:-MS0a5D6DSzEEm1SWMdh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L459)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The "x" should be lower-case here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 85 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-TlX8EwBuF70XJuxv:-MS0a6VM1yP2rIMM5qLu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This still needs a parameter for the child policy config as a `Json` object.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 845 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-VgGGDDjhRx6BMCQx:-MSB8EJz5RXZziRS_khm:bs35z9y) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L845)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This code is going to need to be conditional.  The existing code is fine for the ROUND_ROBIN case, but for the RING_HASH case, we'll need to generate a single-level child for the `xds_cluster_impl` policy.

Also, note that this will also be the place to add the feature we forgot for the fallback design, where the discovery mechanism can override the child policy (which will be used by the logical DNS discovery mechanism to set the child to `pick_first`).  So when both pieces are implemented, the logic here should be something like this:

```
if (discovery_mechanism_overrides_child) {
  // ... use child specified by discovery mechanism ...
} else if (using_round_robin) {
  // ... use existing code ...
} else {  // RING_HASH
  // ... use ring_hash policy ...
}
```
</blockquote></details>

will fix the logical dns case separate, but started the cases for round robin and ring hash
___
*[src/core/ext/xds/xds_api.h, line 235 at r1](https://reviewable.io/reviews/grpc/grpc/25270#-MS-RKX28MQtWAsKzg5_:-MSB8CSQ-VtjvDJ1kgKs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7de58e623f6d6b24ff5a03be64f148e51def75d2/src/core/ext/xds/xds_api.h#L235)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per the design doc, this should be a string instead of an enum, because in the future we'll want to be able to configure arbitrary LB policies via xDS.

Also, we need to add a bunch of other fields here too.  Please see the design doc for details.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-29 23:55 UTC, markdroth requested changes
This is moving in the right direction!

Most of my comments are about making sure we're clear on where we're referring to an xDS LB policy and where we're referring to a gRPC LB policy.  It is a little confusing, but I've tried to point out which places should be which.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MSFZM-PApkbNYHfMtmh:b16ueq2)* status: all files reviewed, 20 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/server_address.h, line 112 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFUd57EgTdnX8wbIMj:-MSFUd57EgTdnX8wbIMk:b-mj4x0d) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/server_address.h#L112)):*
> ```objc
> typedef absl::InlinedVector<ServerAddress, 1> ServerAddressList;
> 
> extern const char* kServerAddressWeightAttributeKey;
> ```

Please add a comment header above this line:

```
//
// ServerAddressWeightAttribute
//
```
___
*[src/core/ext/filters/client_channel/server_address.h, line 127 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFThLH334LEDXGpTEu:-MSFThLH334LEDXGpTEv:b-naa9f5) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/server_address.h#L127)):*
> ```objc
>     const auto* other_locality_attr =
>         static_cast<const ServerAddressWeightAttribute*>(other);
>     return weight_ == other_locality_attr->weight_;
> ```

This isn't an "equals" function (i.e., return true if equal, false otherwise); it's a "cmp" function (i.e., returns less than, equal to, or greater than 0 if the first object is less than, equal to, or greater than the second).

I suggest using `GPR_ICMP(weight_, other.weight_)`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 447 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFV5-m6Y8QQiDCIFcK:-MSFV5-m6Y8QQiDCIFcL:b3togl5) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L447)):*
> ```cpp
>     // Construct config for child policy.
>     Json::Object xds_lb_policy;
>     if (cluster_data.lb_policy == "ring_hash_experimental") {
> ```

This should be `RING_HASH`.  It's an xDS policy name, not a gRPC policy name.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 448 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFUoQi448Oj9hTgzJX:-MSFUoQi448Oj9hTgzJY:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L448)):*
> ```cpp
>     Json::Object xds_lb_policy;
>     if (cluster_data.lb_policy == "ring_hash_experimental") {
>       xds_lb_policy["ring_hash_experimental"] = Json::Object{
> ```

Same here.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 454 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFV6HM9fT6MA1ooDR5:-MSFV6HM9fT6MA1ooDR6:bp5cz04) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L454)):*
> ```cpp
>       };
>     } else {
>       xds_lb_policy["round_robin"] = Json::Object();
> ```

This should be `ROUND_ROBIN`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 56 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFVDBd5D_IwmlF52RQ:-MSFVDBd5D_IwmlF52RR:b-rujl87) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L56)):*
> ```cpp
> 
> const char* kXdsLocalityNameAttributeKey = "xds_locality_name";
> const char* kServerAddressWeightAttributeKey = "server_address_weight";
> ```

This should be defined in server_address.cc, not here, since it's declared in server_address.h.  Otherwise, if some other code tried to use this attribute without linking in the xds_cluster_resolver policy, they'd get a link error.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 87 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFVZF-3urWHxPqJqzH:-MSFVZF-3urWHxPqJqzI:bpwxxcq) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L87)):*
> ```cpp
>   XdsClusterResolverLbConfig(
>       std::vector<DiscoveryMechanism> discovery_mechanisms,
>       std::string xds_lb_policy_name, Json xds_lb_policy)
> ```

I don't think we need these to be two separate parameters.  The policy name can be part of the JSON -- just pass the whole JSON object from this policy's config.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 856 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFW0RNC18ZQp1QpPHN:-MSFW0RNC18ZQp1QpPHO:b-x6zt6m) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L856)):*
> ```cpp
>   for (size_t priority = 0; priority < priority_list_.size(); ++priority) {
>     Json child_policy;
>     if (config_->xds_lb_policy_name() == "round_robin") {
> ```

`ROUND_ROBIN`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 899 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFW8np28_RmYOqf-U2:-MSFW8np28_RmYOqf-U3:b40r33y) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L899)):*
> ```cpp
>       GPR_ASSERT(it != config.end());
>       (*it->second.mutable_object())["targets"] = std::move(weighted_targets);
>     } else if (config_->xds_lb_policy_name() == "ring_hash_experimental") {
> ```

`RING_HASH`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1135 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFYAxdAU7BVnol_nj9:-MSFYAxdAU7BVnol_njA:b-f2wbsu) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1135)):*
> ```cpp
>           "field:xdsLbPolicy error:type should be array"));
>     } else {
>       xds_lb_policy = it->second;
> ```

I don't think we want to set `xds_lb_policy` to this overall object.  Instead, I think we want to iterate through the entries in this array, stopping at the first policy we recognize (either `ROUND_ROBIN`  or `RING_HASH`), and then set `xds_lb_policy` to that inner object.

This means doing a little more work when we construct the real child policy config for the ring_hash policy, but it means that we have a cleaner separation between the xDS LB policy selection (done here) and the gRPC LB policy selection (done in the child policy config that we construct above).
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1144 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFXpdFEyhmyW8wekvI:-MSFXpdFEyhmyW8wekvJ:b40r33y) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1144)):*
> ```cpp
>             "field:xdsLbPolicy error:element should be of type object"));
>       } else {
>         auto it = array[0].object_value().find("ring_hash_experimental");
> ```

`RING_HASH`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1146 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFXq_w96zlOkVTJFy9:-MSFXq_w96zlOkVTJFyA:b-x6zt6m) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc# [...]

2021-02-02 06:25 UTC, donnadionne reviewed
Fixed according to comments, PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MSWOfAX1lyvUuTPUwPe:bfq5e0b)* status: 1 of 7 files reviewed, 20 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/server_address.h, line 112 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFUd57EgTdnX8wbIMj:-MSRX8Ju1C6agqSxF3oa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/server_address.h#L112)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment header above this line:

```
//
// ServerAddressWeightAttribute
//
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/server_address.h, line 127 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFThLH334LEDXGpTEu:-MSRX8knErQ-libRLHkt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/server_address.h#L127)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This isn't an "equals" function (i.e., return true if equal, false otherwise); it's a "cmp" function (i.e., returns less than, equal to, or greater than 0 if the first object is less than, equal to, or greater than the second).

I suggest using `GPR_ICMP(weight_, other.weight_)`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 447 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFV5-m6Y8QQiDCIFcK:-MSRXJZJ4qoYmN16yecX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L447)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be `RING_HASH`.  It's an xDS policy name, not a gRPC policy name.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 448 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFUoQi448Oj9hTgzJX:-MSRXJuq7sdfLrkGTkBN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L448)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 454 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFV6HM9fT6MA1ooDR5:-MSRXOQC4yD283jQ2dU5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L454)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be `ROUND_ROBIN`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 56 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFVDBd5D_IwmlF52RQ:-MSVDvqnAhCkKVOI_Vy4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be defined in server_address.cc, not here, since it's declared in server_address.h.  Otherwise, if some other code tried to use this attribute without linking in the xds_cluster_resolver policy, they'd get a link error.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 87 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFVZF-3urWHxPqJqzH:-MSWH4RG9bQ_aXH-Q4Ir:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L87)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need these to be two separate parameters.  The policy name can be part of the JSON -- just pass the whole JSON object from this policy's config.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 856 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFW0RNC18ZQp1QpPHN:-MSRXgt72IUABm_OHoDl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L856)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`ROUND_ROBIN`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 899 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFW8np28_RmYOqf-U2:-MSRXqsI5jjZJQB1CVZJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L899)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`RING_HASH`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1135 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFYAxdAU7BVnol_nj9:-MSWFeap6-05TwOcD7yi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1135)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we want to set `xds_lb_policy` to this overall object.  Instead, I think we want to iterate through the entries in this array, stopping at the first policy we recognize (either `ROUND_ROBIN`  or `RING_HASH`), and then set `xds_lb_policy` to that inner object.

This means doing a little more work when we construct the real child policy config for the ring_hash policy, but it means that we have a cleaner separation between the xDS LB policy selection (done here) and the gRPC LB policy selection (done in the child policy config that we construct above).
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1144 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFXpdFEyhmyW8wekvI:-MSRXzn_-XJr9QRthrmh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`RING_HASH`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1146 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFXq_w96zlOkVTJFy9:-MSRY1Th3S-vCwmFEVEL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1146)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`ROUND_ROBIN`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1149 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFXgKV2kROt_uGYXiC:-MSWFZI9EotgF7p2D5Kr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1149)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is not an error; it just means to move on to the next policy in the list.  We stop at the first one we know.
</blockquote></details> [...]

2021-02-02 16:51 UTC, markdroth requested changes
This is continuing to move in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 6 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MSYdyrh8-DhxWKlZmKs:btr6vl6)* status: all files reviewed, 8 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/server_address.h, line 116 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYbIDLAm1oSmvTxL08:-MSYbIDLAm1oSmvTxL09:b5qj7j3) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/server_address.h#L116)):*
> ```objc
> // The attribute containing endpoint weight.
> //
> extern const char* kServerAddressWeightAttributeKey;
> ```

This doesn't need its own section comment; it's just the attribute key for `ServerAddressWeightAttribute` below.  Suggest just moving this declaration down into that section.

Actually, you might even make this a static data member of `ServerAddressWeightAttribute`, since that will make it clearer that it's part of that class.
___
*[src/core/ext/filters/client_channel/server_address.cc, line 35 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYbYns4XbJT23YXvQ6:-MSYbYns4XbJT23YXvQ7:bug0d0i) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/server_address.cc#L35)):*
> ```cpp
> 
> //
> // The attribute containing endpoint weight.
> ```

This can just say `ServerAddressWeightAttribute`, since this is basically part of that class.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 101 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYc6iGBKaD-KHFdktU:-MSYc6iGBKaD-KHFdktV:b-m9obfm) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L101)):*
> ```cpp
>   }
> 
>   const std::string xds_lb_policy_name() const { return xds_lb_policy_name_; }
> ```

This method shouldn't be needed.  The caller can get this out of the JSON themselves.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 908 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYcOQ46g9iUnjPHB7a:-MSYcOQ46g9iUnjPHB7b:bbcowcb) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L908)):*
> ```cpp
>       child_policy = Json::Array{
>           Json::Object{
>               {"ring_hash_experimental", config_->xds_lb_policy()},
> ```

`config_->xds_lb_policy()` points to JSON like this:

```
{
  "RING_HASH": {
    "min_ring_size": 1234,
    "max_ring_size": 1234,
    "hash_function": "XX_HASH"
   }
}
```

We want the inner object here, not the outer object.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1143 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYcZZT9lpEmv9_4NIU:-MSYcZZT9lpEmv9_4NIV:b-x6zt6m) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1143)):*
> ```cpp
>     } else {
>       xds_lb_policy = Json::Object{
>           {"round_robin", Json::Object()},
> ```

`ROUND_ROBIN`
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1155 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYd0Rc7BTGJCNf2tQ6:-MSYd0Rc7BTGJCNf2tQ7:biyebxe) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1155)):*
> ```cpp
>               array[i].object_value().find("ROUND_ROBIN") !=
>                   array[i].object_value().end()) {
>             xds_lb_policy = array[i];
> ```

In the `RING_HASH` case, we need to validate that we understand all of the config fields here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 151 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFXC3ZCHzoaUCzfdgo:-MSYdq-VABFjLDU61zul:bczappy) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/test/cpp/end2end/xds_end2end_test.cc#L151)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The `xdsLbPolicy` line itself is not needed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 167 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFXG7C0dnt6ppYVYMr:-MSYdtj55TyT6WJlWjPc:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/test/cpp/end2end/xds_end2end_test.cc#L167)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same here.


<!-- Sent from Reviewable.io -->

2021-02-03 19:36 UTC, donnadionne reviewed
PTAL, thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MSdONSl9zBfgA83ME1d:bmah08w)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/server_address.h, line 116 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYbIDLAm1oSmvTxL08:-MSZTq1rCaxMwpVjMP9J:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/server_address.h#L116)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't need its own section comment; it's just the attribute key for `ServerAddressWeightAttribute` below.  Suggest just moving this declaration down into that section.

Actually, you might even make this a static data member of `ServerAddressWeightAttribute`, since that will make it clearer that it's part of that class.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/server_address.cc, line 35 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYbYns4XbJT23YXvQ6:-MSZTwud0Y1RHvqQ8vHe:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/server_address.cc#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can just say `ServerAddressWeightAttribute`, since this is basically part of that class.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 101 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYc6iGBKaD-KHFdktU:-MSZ9u0ADhb5BNWYseja:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L101)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This method shouldn't be needed.  The caller can get this out of the JSON themselves.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 908 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYcOQ46g9iUnjPHB7a:-MSZU-AU33R9wVECCl4H:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L908)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`config_->xds_lb_policy()` points to JSON like this:

```
{
  "RING_HASH": {
    "min_ring_size": 1234,
    "max_ring_size": 1234,
    "hash_function": "XX_HASH"
   }
}
```

We want the inner object here, not the outer object.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1143 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYcZZT9lpEmv9_4NIU:-MSZAEpQ95zbwjcJnlh0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1143)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`ROUND_ROBIN`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1155 at r5](https://reviewable.io/reviews/grpc/grpc/25270#-MSYd0Rc7BTGJCNf2tQ6:-MSdOGtE9yEl2M3lwRjs:bwxx0e6) ([raw file](https://github.com/grpc/grpc/blob/158b9d04dff4a8a84b5ad4a65ecba626f622da83/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1155)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In the `RING_HASH` case, we need to validate that we understand all of the config fields here.
</blockquote></details>


added validation
___
*[test/cpp/end2end/xds_end2end_test.cc, line 151 at r3](https://reviewable.io/reviews/grpc/grpc/25270#-MSFXC3ZCHzoaUCzfdgo:-MSZU1slBBJfwmYHzenh:b-95ps9u) ([raw file](https://github.com/grpc/grpc/blob/3a21b3639b8680316b50d7c6f1efb1e033808efe/test/cpp/end2end/xds_end2end_test.cc#L151)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `xdsLbPolicy` line itself is not needed.
</blockquote></details>

ok, also modified the parser in xds_cluster_resolver to provide default


<!-- Sent from Reviewable.io -->

2021-02-04 16:04 UTC, markdroth requested changes
This is getting closer!  I have a few comments about validating the config values; all of the other comments are cosmetic.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 2 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MShmJ1n3-kmMF2hRhDC:b6lbm85)* status: all files reviewed, 13 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/server_address.h, line 136 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShdG1D5fNZQqBjansM:-MShdG1D5fNZQqBjansN:batbqam) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/server_address.h#L136)):*
> ```objc
>   }
> 
>   static const char* kServerAddressWeightAttributeKey;
> ```

This should go at the top of the public section, as per https://google.github.io/styleguide/cppguide.html#Declaration_Order.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 854 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MSheKp3-vilUhENd_q1:-MSheKp3-vilUhENd_q2:b-mh95b1) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L854)):*
> ```cpp
>     Json::Object ring_hash_experimental_policy;
>     auto it = config_->xds_lb_policy().object_value().find("RING_HASH");
>     if (it != config_->xds_lb_policy().object_value().end()) {
> ```

This if/else block is checking exactly the same thing as the following one.  Instead of doing this twice and using temporary variables to communicate the choice from the first one to the second one, let's just combine them:

```
const auto& xds_lb_policy = config_->xds_lb_policy().object_value();
if (xds_lb_policy.find("ROUND_ROBIN") != xds_lb_policy.end()) {
  //...round_robin case...
} else {
  auto it = xds_lb_policy.find("RING_HASH");
  GPR_ASSERT(it != xds_lb_policy.end());
  // ...ring_hash case using config from it->second...
}
```
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1145 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShg44qE15Sz1muEHpf:-MShg44qE15Sz1muEHpg:b-g7z3m7) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1145)):*
> ```cpp
>         for (size_t i = 0; i < array.size(); ++i) {
>           if (array[i].type() != Json::Type::OBJECT) {
>             error_list.push_back(GRPC_ERROR_CREATE_FROM_STATIC_STRING(
> ```

Suggest doing a `continue` after this, so that we don't need the `else` immediately below.  This will reduce the amount of indentation for the rest of the code here, making it easier to follow.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1148 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShgdDp6UKlCtiaCXDi:-MShgdDp6UKlCtiaCXDj:b-jl3kc9) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1148)):*
> ```cpp
>                 "field:xdsLbPolicy error:element should be of type object"));
>           } else {
>             if (array[i].object_value().find("ROUND_ROBIN") !=
> ```

Suggest using a local reference variable to make the code more readable:

```
const Json::Object& policy = array[i].object_value();
```

Then the rest of the code can use `policy` instead of `array[i].object_value()`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1150 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShgDvO5LTxbr-TFloE:-MShgDvO5LTxbr-TFloF:b-qbt6z) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1150)):*
> ```cpp
>             if (array[i].object_value().find("ROUND_ROBIN") !=
>                 array[i].object_value().end()) {
>               break;
> ```

We should also check that the value is of type `Json::Type::OBJECT`, even though we're not going to read any fields from it.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1155 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShh2DM9v3f2mO5kcOC:-MShh2DM9v3f2mO5kcOD:b-g7z3m7) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1155)):*
> ```cpp
>               if (policy_it != array[i].object_value().end()) {
>                 if (policy_it->second.type() != Json::Type::OBJECT) {
>                   error_list.push_back(GRPC_ERROR_CREATE_FROM_STATIC_STRING(
> ```

Suggest doing a `continue` after this, so that we don't need the `else` immediately below.  This will reduce the amount of indentation for the rest of the code here, making it easier to follow.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1158 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShlkAR6rLycEcm_mQp:-MShlkAS9hefCYbSbxdQ:b-9lej00) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1158)):*
> ```cpp
>                       "field:RING_HASH error:type should be object"));
>                 } else {
>                   const Json::Object& ring_hash =
> ```

Consider moving all of this validation code into the ring_hash policy itself.  If you do that, then the code here can just call the ring_hash policy's validation code.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1160 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShh7V34zJLnkuwZsNs:-MShh7V34zJLnkuwZsNt:b-q3haso) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1160)):*
> ```cpp
>                   const Json::Object& ring_hash =
>                       policy_it->second.object_value();
>                   if (ring_hash.size() != 3) {
> ```

We should not check this.  Unknown fields are okay -- we should just ignore those.  Otherwise, we will break forward-compatibility if we add optional fields later.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1173 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShhgJh745LJwT5N0-v:-MShhgJi06-jYNV_BI2k:b-7tezjn) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1173)):*
> ```cpp
>                           "field:min_ring_size missing"));
>                     } else {
>                       if (ring_hash_it->second.type() != Json::Type::NUMBER) {
> ```

Instead of saying `else { if (...) { ... } }`, we can just say `else if (...) { ...}`.  This reduces the indentation and makes the code easier to read.

Same thing for the next two fields as well.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1198 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShi5U6-X_hcKR8VMkR:-MShi5U6-X_hcKR8VMkS:bu8rkw5) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1198)):*
> ```cpp
>                       }
>                     }
>                     // TODO(donnadionne): do we check for non-zero?
> ```

Yes, I think zero is an invalid value.

See my comments in xds_api.cc about the value constraints here.  We should impose the same restrictions here.
___
*[src/core/ext/xds/xds_api.h, line 248 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShimRgBVNgGLIlHLL1:-MShimRgBVNgGLIlHLL2:b-epu10u) ([raw file](https [...]

2021-02-04 21:56 UTC, donnadionne reviewed
fixed.  PTAL thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MSj1vpT-hpR-WQVmEXd:b-ldgvrb)* status: all files reviewed, 13 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/server_address.h, line 136 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShdG1D5fNZQqBjansM:-MSiNHW4CVJSssXFgo-W:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/server_address.h#L136)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should go at the top of the public section, as per https://google.github.io/styleguide/cppguide.html#Declaration_Order.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 854 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MSheKp3-vilUhENd_q1:-MSiT_UT1URlGfSgk_p1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L854)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This if/else block is checking exactly the same thing as the following one.  Instead of doing this twice and using temporary variables to communicate the choice from the first one to the second one, let's just combine them:

```
const auto& xds_lb_policy = config_->xds_lb_policy().object_value();
if (xds_lb_policy.find("ROUND_ROBIN") != xds_lb_policy.end()) {
  //...round_robin case...
} else {
  auto it = xds_lb_policy.find("RING_HASH");
  GPR_ASSERT(it != xds_lb_policy.end());
  // ...ring_hash case using config from it->second...
}
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1145 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShg44qE15Sz1muEHpf:-MSipCuyD8YGuJKiL8BZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1145)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest doing a `continue` after this, so that we don't need the `else` immediately below.  This will reduce the amount of indentation for the rest of the code here, making it easier to follow.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1148 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShgdDp6UKlCtiaCXDi:-MSipDx91pP_mZp6-78d:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1148)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest using a local reference variable to make the code more readable:

```
const Json::Object& policy = array[i].object_value();
```

Then the rest of the code can use `policy` instead of `array[i].object_value()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1150 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShgDvO5LTxbr-TFloE:-MSipEO1AZ9cKCCmgyRb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1150)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should also check that the value is of type `Json::Type::OBJECT`, even though we're not going to read any fields from it.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1155 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShh2DM9v3f2mO5kcOC:-MSiqxaY1M0OsSO1HaDB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1155)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest doing a `continue` after this, so that we don't need the `else` immediately below.  This will reduce the amount of indentation for the rest of the code here, making it easier to follow.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1158 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShlkAR6rLycEcm_mQp:-MSitnowD-V9nfuJqOms:b-nr3x06) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1158)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Consider moving all of this validation code into the ring_hash policy itself.  If you do that, then the code here can just call the ring_hash policy's validation code.
</blockquote></details>

how about we move it after ring_hash_experimental policy is done, i'll add a todo here
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1160 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShh7V34zJLnkuwZsNs:-MSitHvmB17yCscIYUbG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1160)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should not check this.  Unknown fields are okay -- we should just ignore those.  Otherwise, we will break forward-compatibility if we add optional fields later.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1173 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShhgJh745LJwT5N0-v:-MSiu7EvB7bGt7sornsF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1173)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of saying `else { if (...) { ... } }`, we can just say `else if (...) { ...}`.  This reduces the indentation and makes the code easier to read.

Same thing for the next two fields as well.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1198 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShi5U6-X_hcKR8VMkR:-MSivBCp8hgR0Y4sjILj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1198)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes, I think zero is an invalid value.

See my comments in xds_api.cc about the value constraints here.  We should impose the same restrictions here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 248 at r7](https://reviewable.io/reviews/grpc/grpc/25270#-MShimRgBVNgGLIlHLL1:-MSivCe06-qj57KT8RRh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/380215256b10a8d006d83f665b7a4f7c9d774ad4/src/core/ext/xds/xds_api.h#L248)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

To match Envoy defaults, this should [default to 1024](https://github.com/envoyproxy/envoy/blob/a2a8f65ec8d95fa292dfda3f789c4b055c3ecd08/api/envoy/config/cluster/v3/cluster.proto#L393), and `max_ring_size` should [default to 8388608](https://github.com/envoyproxy/envoy/blob/a2a8f65ec8d95fa292dfda3f789c4b055c3ecd08/api/envoy/config/cluster/v3/cluster.proto#L401).
</blockquote></details>

Done.
___
*[src/core/ext [...]

2021-02-04 22:19 UTC, markdroth requested changes
Just a few minor cosmetic comments remaining!

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MSj76P_D-E8OzX_yuEl:b-j6h3n6)* status: all files reviewed, 7 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1148 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj5_qG4zEFfUppDB3d:-MSj5_qG4zEFfUppDB3e:b-oamfsz) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1148)):*
> ```cpp
>             }
>             break;
>           } else {
> ```

No need for the `else`, since the previous block does a `break`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1160 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj5vHLC9hr2IFIJ6EQ:-MSj5vHLC9hr2IFIJ6ER:b-4zeb29) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1160)):*
> ```cpp
>               const Json::Object& ring_hash = policy_it->second.object_value();
>               xds_lb_policy = array[i];
>               size_t min_ring_size = 0;
> ```

Initializing these to 0 means that the values are invalid if the fields are not present in the config at all.  Should we give them the same defaults here as in xds_api.cc?
___
*[src/core/ext/xds/xds_api.cc, line 1729 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj6QF99SWho4l-Jcye:-MSj6QF99SWho4l-Jcyf:b1l8xdf) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/xds/xds_api.cc#L1729)):*
> ```cpp
>               ring_hash_config);
>       if (max_ring_size != nullptr) {
>         auto max = google_protobuf_UInt64Value_value(max_ring_size);
> ```

Please use `uint64_t` instead of `auto` here.

Actually, why use a local variable at all?  Why not just directly assign to `cds_update.max_ring_size`, so that we don't need to it below?
___
*[src/core/ext/xds/xds_api.cc, line 1730 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj6aY0-M4SHkf4Xd8p:-MSj6aY0-M4SHkf4Xd8q:b-gjm06j) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/xds/xds_api.cc#L1730)):*
> ```cpp
>       if (max_ring_size != nullptr) {
>         auto max = google_protobuf_UInt64Value_value(max_ring_size);
>         if (max > 8388608 || max <= 0) {
> ```

It's an unsigned type, so it can't be less than 0.
___
*[src/core/ext/xds/xds_api.cc, line 1740 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj6Vb88gtqD-h4M4Ev:-MSj6Vb88gtqD-h4M4Ew:b7mbjy) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/xds/xds_api.cc#L1740)):*
> ```cpp
>               ring_hash_config);
>       if (min_ring_size != nullptr) {
>         auto min = google_protobuf_UInt64Value_value(min_ring_size);
> ```

`uint64_t`, or just directly assign to `cds_update.min_ring_size`.
___
*[src/core/ext/xds/xds_api.cc, line 1741 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj6ccG2GW75Ovq_GeN:-MSj6ccG2GW75Ovq_GeO:b-7u7ic) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/xds/xds_api.cc#L1741)):*
> ```cpp
>       if (min_ring_size != nullptr) {
>         auto min = google_protobuf_UInt64Value_value(min_ring_size);
>         if (min > 8388608 || min <= 0) {
> ```

Unsigned type, can't be less than 0.
___
*[src/core/ext/xds/xds_api.cc, line 1744 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj6vb4EJPLsovGwWB3:-MSj6vb4EJPLsovGwWB4:boalxnl) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/xds/xds_api.cc#L1744)):*
> ```cpp
>           return GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>               "min_ring_size is not in the range of 1 to 8388608.");
>         } else if (min > cds_update.max_ring_size) {
> ```

No need for the `else`, since the previous block returns.


<!-- Sent from Reviewable.io -->

2021-02-04 22:47 UTC, donnadionne reviewed
PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MSjDYIH2xOAbRpfgu-W:bxtaph9)* status: all files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1148 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj5_qG4zEFfUppDB3d:-MSj80xs7Zv41TLOOjPl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1148)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the `else`, since the previous block does a `break`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1160 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj5vHLC9hr2IFIJ6EQ:-MSj8FSY4CE3S75bbQV6:bc3uj69) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1160)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Initializing these to 0 means that the values are invalid if the fields are not present in the config at all.  Should we give them the same defaults here as in xds_api.cc?
</blockquote></details>

yes we should, i missed this
___
*[src/core/ext/xds/xds_api.cc, line 1729 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj6QF99SWho4l-Jcye:-MSj9a-tACpOZouATzsA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/xds/xds_api.cc#L1729)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `uint64_t` instead of `auto` here.

Actually, why use a local variable at all?  Why not just directly assign to `cds_update.max_ring_size`, so that we don't need to it below?
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1730 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj6aY0-M4SHkf4Xd8p:-MSj9loEEzs54HOCYaOw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/xds/xds_api.cc#L1730)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's an unsigned type, so it can't be less than 0.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1740 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj6Vb88gtqD-h4M4Ev:-MSj9eqT87lPvlVCDgfy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/xds/xds_api.cc#L1740)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`uint64_t`, or just directly assign to `cds_update.min_ring_size`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1741 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj6ccG2GW75Ovq_GeN:-MSj9l226sgOLaAw5Yc3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/xds/xds_api.cc#L1741)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Unsigned type, can't be less than 0.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1744 at r8](https://reviewable.io/reviews/grpc/grpc/25270#-MSj6vb4EJPLsovGwWB3:-MSjA255E5L0Qtbc6Gao:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4e8724ae93e856f974164abea172b53658da5910/src/core/ext/xds/xds_api.cc#L1744)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the `else`, since the previous block returns.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-04 23:52 UTC, markdroth approved these changes
Looks great!

> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25270#-:-MSjSXQjAxWLC-9WyR0Y:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-05 07:13 UTC, donnadionne commented
known issue #25360 (interop tests)

2021-02-05 11:27 UTC, merged