Made grpc_core::Mutex compatible to absl::Mutex
grpc/grpc pull request #25325
Opened 2021-02-02 18:12 UTC by veblush

Made following classes compatible to absl::Mutex so that those will be able to be replaced in future.

```
using Mutex = absl::Mutex;
using MutexLock = absl::MutexLock;
using ReleasableMutexLock = absl::ReleasableMutexLock;
using CondVar = absl::CondVar;
```

2021-02-03 19:02 UTC, veblush commented
[grpc_build_artifacts_multiplatform](https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod%3Agrpc%2Fcore%2Fexperimental%2Fgrpc_build_artifacts_multiplatform): running

2021-02-04 17:06 UTC, markdroth requested changes
Thanks so much for doing this!

Will this PR also allow us to use the absl lock annotations, or is there some subsequent step needed before we can do that?

Please let me know if you have any questions.  Thanks!

> Reviewed 28 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25325#-:-MSi-PLPAgwbOhoRwgwx:bqxywp8)* status: all files reviewed, 14 unresolved discussions (waiting on @veblush)

___
*[src/core/ext/filters/max_age/max_age_filter.cc, line 236 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShtjEN1jJIugE4VTlz:-MShtjEOAWJrWCiplAU_:b-ihv8jq) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/ext/filters/max_age/max_age_filter.cc#L236)):*
> ```cpp
>     if (new_state != GRPC_CHANNEL_SHUTDOWN) return;
>     {
>       MutexLockForGprMu lock(&chand_->max_age_timer_mu);
> ```

Instead of using `MutexLockForGprMu`, can we just change this code to use `Mutex` instead of `gpr_mu`?  It looks like the only necessary change would be to change `max_age_init_channel_elem()` to use placement-new to construct the `channel_data` struct and `max_age_destroy_channel_elem()` to invoke the struct's dtor.
___
*[src/core/lib/channel/handshaker.h, line 147 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShuSeDDq0CmmKsKNzG:-MShuSeE5WsuMhthVteL:bxqetkw) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/channel/handshaker.h#L147)):*
> ```objc
>   static const size_t HANDSHAKERS_INIT_SIZE = 2;
> 
>   grpc_core::Mutex mu_;
> ```

No need for `grpc_core::`, since we're already in that namespace.
___
*[src/core/lib/gprpp/sync.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShzPCW06ID_2-2RRSx:-MShzPCW06ID_2-2RRSy:bjgpxh8) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/gprpp/sync.h#L52)):*
> ```objc
> // Returns the underlying gpr_mu from Mutex. This should be used only when
> // it has to like passing the C++ mutex to C-core API.
> inline gpr_mu* GetUnderlyingGprMu(Mutex* mutex) {
> ```

Please explicitly add a TODO here saying that this should be removed when we migrate all of C-core from `gpr_mu` to `Mutex`.
___
*[src/core/lib/gprpp/sync.h, line 81 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShzVwrDbuBnAQYOwRa:-MShzVwrDbuBnAQYOwRb:bp1s4d5) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/gprpp/sync.h#L81)):*
> ```objc
> // Returns the underlying gpr_mu from Mutex. This should be used only when
> // it has to like passing the C++ mutex to C-core API.
> inline gpr_mu* GetUnderlyingGprMu(Mutex* mutex) { return &mutex->mu_; }
> ```

Same TODO here.
___
*[src/core/lib/gprpp/sync.h, line 174 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShzYmB3iYDSDsibf_-:-MShzYmB3iYDSDsibf_0:b-cj9g2i) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/gprpp/sync.h#L174)):*
> ```objc
> 
> // Deprecated. Prefer MutexLock
> class MutexLockForGprMu {
> ```

I'd really like it if this wasn't needed.  It looks like all the places where we're using this, we could actually just replace `gpr_mu` with `Mutex` instead.
___
*[src/core/lib/gprpp/sync.h, line 187 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MSi-Fi4-pWQ3qLbx5Pr:-MSi-Fi4-pWQ3qLbx5Ps:b-q2hgtn) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/gprpp/sync.h#L187)):*
> ```objc
> 
> // Deprecated. Prefer MutexLock or ReleasableMutexLock
> class ABSL_SCOPED_LOCKABLE LockableAndReleasableMutexLock {
> ```

Is this actually needed?  I only see two spots where we're using it, and it's not clear to me why we need it in those places.
___
*[src/core/lib/iomgr/ev_apple.cc, line 166 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShukIM72d0JuVELTSF:-MShukIM72d0JuVELTSG:bi0y1ra) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/iomgr/ev_apple.cc#L166)):*
> ```cpp
> /// shutdown.
> static void GlobalRunLoopFunc(void* arg) {
>   grpc_core::LockableAndReleasableMutexLock lock(&gGlobalRunLoopContext->mu);
> ```

Why is this change needed?  I don't see anywhere that we're actually re-locking it.
___
*[src/core/lib/iomgr/ev_apple.cc, line 243 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShv5gXD3nnHRSRUOWh:-MShv5gY3fjhDdCPfsFR:boyvw89) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/iomgr/ev_apple.cc#L243)):*
> ```cpp
>     while (!actual_worker.kicked && !apple_pollset->is_shutdown) {
>       if (actual_worker.cv.WaitWithTimeout(&apple_pollset->mu,
>                                            absl::Milliseconds(deadline))) {
> ```

It looks like `deadline` is an absolute time, not a timeout.  Shouldn't this use `WaitWithDeadline()` instead?
___
*[src/core/lib/iomgr/ev_epollex_linux.cc, line 540 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShvkrSDUfe_Brmq-hm:-MShvkrSDUfe_Brmq-hn:b-se6102) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/iomgr/ev_epollex_linux.cc#L540)):*
> ```cpp
> static bool fd_has_pollset(grpc_fd* fd, grpc_pollset* pollset) {
>   const int epfd = pollset->active_pollable->epfd;
>   grpc_core::MutexLockForGprMu lock(&fd->pollable_mu);
> ```

Instead of using `MutexLockForGprMu`, can we change `fd->pollable_mu` from `gpr_mu` to `Mutex`?
___
*[src/core/lib/iomgr/ev_epollex_linux.cc, line 687 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShvuLM2yWLulCBsCS8:-MShvuLM2yWLulCBsCS9:b-itwmky) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/iomgr/ev_epollex_linux.cc#L687)):*
> ```cpp
>   GPR_TIMER_SCOPE("kick_one_worker", 0);
>   pollable* p = specific_worker->pollable_obj;
>   grpc_core::MutexLockForGprMu lock(&p->mu);
> ```

Similar question for `p->mu`.
___
*[src/core/lib/slice/slice_intern.cc, line 72 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShwo-XC76Nm4GvIG79:-MShwo-YB-fejC4J-VzQ:b-qjm9fx) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/slice/slice_intern.cc#L72)):*
> ```cpp
> InternedSliceRefcount::~InternedSliceRefcount() {
>   slice_shard* shard = &g_shards[SHARD_IDX(this->hash)];
>   MutexLockForGprMu lock(&shard->mu);
> ```

Instead of using `MutexLockForGprMu`, can we change the type of `shard->mu` from `gpr_mu` to `grpc_core::Mutex`?

I guess in this particular case, the complication is that it would violate the style guide's edict against global objects that are not trivially destructible, but I suspect the existing code effectively already has that problem anyway.  Maybe instead we can have some function called at `grpc_init()` time to dynamically allocate the global shard structs instead of declaring them statically?
___
*[src/core/tsi/alts/handshaker/alts_handshaker_client.cc, line 153 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShyCVp15qxgUOk97Fo:-MShyCVq1ciZgPplO-Mh:b-p462rt) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/tsi/alts/handshaker/alts_handshaker_client.cc#L153)):*
> ```cpp
>   recv_message_result* r;
>   {
>     grpc_core::MutexLockForGprMu lock(&client->mu);
> ```

Instead of using `MutexLockForGprMu`, can we change `client->mu` from `gpr_mu` to `grpc_core::Mutex`?
___
*[src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc, line 434 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShyKjz2luJ2s3EQ1kO:-MShyKk-1NlTuAqgv4_t:b-k6jrhq) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc#L434)):*
> ```cpp
>     }
>     {
>       grpc_core::MutexLockForGprMu lock(&handshaker->mu);
> ```

Instead of using `MutexLockForGpuMu`, can we change `handshaker->mu` from `gpr_mu` to `Mutex`?
___
*[src/cpp/thread_man [...]

2021-02-04 18:54 UTC, veblush reviewed
Yeah, this enables thread annotations. As an example, I added annotations to max_age_filter.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25325#-:-MSiLHGA2t_4ckyhdFdI:b1llkcc)* status: all files reviewed, 14 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/max_age/max_age_filter.cc, line 236 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShtjEN1jJIugE4VTlz:-MSiD9YdBEXUtLZDn_VS:b-l4pkoa) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/ext/filters/max_age/max_age_filter.cc#L236)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of using `MutexLockForGprMu`, can we just change this code to use `Mutex` instead of `gpr_mu`?  It looks like the only necessary change would be to change `max_age_init_channel_elem()` to use placement-new to construct the `channel_data` struct and `max_age_destroy_channel_elem()` to invoke the struct's dtor.
</blockquote></details>

Oh it looks doable. Done.
___
*[src/core/lib/channel/handshaker.h, line 147 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShuSeDDq0CmmKsKNzG:-MSiDG3U2Ce5TyiwkmS6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/channel/handshaker.h#L147)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `grpc_core::`, since we're already in that namespace.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/sync.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShzPCW06ID_2-2RRSx:-MSiDQs77cCSKVaE3-lJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/gprpp/sync.h#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please explicitly add a TODO here saying that this should be removed when we migrate all of C-core from `gpr_mu` to `Mutex`.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/sync.h, line 81 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShzVwrDbuBnAQYOwRa:-MSiDREVEWaBMSMSGu7-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/gprpp/sync.h#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same TODO here.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/sync.h, line 174 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShzYmB3iYDSDsibf_-:-MSiDUfX5Wd9tqoDyQMl:bcw8i04) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/gprpp/sync.h#L174)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'd really like it if this wasn't needed.  It looks like all the places where we're using this, we could actually just replace `gpr_mu` with `Mutex` instead.
</blockquote></details>

Yep, I like to do but can we do it in separate PRs?
___
*[src/core/lib/gprpp/sync.h, line 187 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MSi-Fi4-pWQ3qLbx5Pr:-MSiDiJ1-AK_A1ncX0la:b1hzpaj) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/gprpp/sync.h#L187)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this actually needed?  I only see two spots where we're using it, and it's not clear to me why we need it in those places.
</blockquote></details>

They actually need. All twos need lock function.
___
*[src/core/lib/iomgr/ev_apple.cc, line 166 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShukIM72d0JuVELTSF:-MSiDuG6-DYWq8pl5N0w:bq639yo) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/iomgr/ev_apple.cc#L166)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this change needed?  I don't see anywhere that we're actually re-locking it.
</blockquote></details>

Line 180 calls lock.
___
*[src/core/lib/iomgr/ev_apple.cc, line 243 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShv5gXD3nnHRSRUOWh:-MSiG6yBA0Bo8qS54LCd:b-o7vuhc) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/iomgr/ev_apple.cc#L243)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like `deadline` is an absolute time, not a timeout.  Shouldn't this use `WaitWithDeadline()` instead?
</blockquote></details>

Good catch! Done.
___
*[src/core/lib/iomgr/ev_epollex_linux.cc, line 540 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShvkrSDUfe_Brmq-hm:-MSiHjD9AC-0zluMpnvN:bgkxm4y) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/iomgr/ev_epollex_linux.cc#L540)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of using `MutexLockForGprMu`, can we change `fd->pollable_mu` from `gpr_mu` to `Mutex`?
</blockquote></details>

I guess it's doable but can we do it in a separate CL due to complexity of pooling this uses.
___
*[src/core/lib/iomgr/ev_epollex_linux.cc, line 687 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShvuLM2yWLulCBsCS8:-MSiI-jS67s9xUnZmGR8:b-3cz4ey) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/iomgr/ev_epollex_linux.cc#L687)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similar question for `p->mu`.
</blockquote></details>

Same above.
___
*[src/core/lib/slice/slice_intern.cc, line 72 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShwo-XC76Nm4GvIG79:-MSiO3ONCfZCXxVxrg1s:b-j2quze) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/slice/slice_intern.cc#L72)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of using `MutexLockForGprMu`, can we change the type of `shard->mu` from `gpr_mu` to `grpc_core::Mutex`?

I guess in this particular case, the complication is that it would violate the style guide's edict against global objects that are not trivially destructible, but I suspect the existing code effectively already has that problem anyway.  Maybe instead we can have some function called at `grpc_init()` time to dynamically allocate the global shard structs instead of declaring them statically?
</blockquote></details>

Like the above, shall we do this later because I want to keep this PR from introducing too much change related to lock.
___
*[src/core/tsi/alts/handshaker/alts_handshaker_client.cc, line 153 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShyCVp15qxgUOk97Fo:-MSiJI2-C9mdmpmiCStV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/tsi/alts/handshaker/alts_handshaker_client.cc#L153)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of using `MutexLockForGprMu`, can we change `client->mu` from `gpr_mu` to `grpc_core::Mutex`?
</blockquote></details>

Done.
___
*[src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc, line 434 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShyKjz2luJ2s3EQ1kO:-MSiJgQb4VJ9JHoB_Rcs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc#L434)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of using `MutexLockForGpuMu`, can we change `handshaker->mu` from `gpr_mu` to `Mutex`?
</blockquote></details>

Done.
___
*[src/cpp/thread_manager/thread_manager.cc, line 155 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShynOT5uG6g8qqGME0:-MSiJkgT5jf8cSllUWa7:b-keq8wm) ([raw file](https://github.com/grpc/grpc/blob/1 [...]

2021-02-04 19:29 UTC, markdroth requested changes
Thanks for doing this!  Only minor comments remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25325#-:-MSiW92m916Tw1xLx2bi:b-v42rqb)* status: all files reviewed, 9 unresolved discussions (waiting on @veblush)

___
*[src/core/ext/filters/max_age/max_age_filter.cc, line 433 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiTX1P09oOGo54mT-9:-MSiTX1P09oOGo54mT-A:bpwlbgb) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/ext/filters/max_age/max_age_filter.cc#L433)):*
> ```cpp
> static grpc_error* max_age_init_channel_elem(grpc_channel_element* elem,
>                                              grpc_channel_element_args* args)
>     ABSL_NO_THREAD_SAFETY_ANALYSIS {
> ```

Why is this needed?

Would it eliminate the need for this if we move the body of this function into a `channel_data` ctor?
___
*[src/core/ext/filters/max_age/max_age_filter.cc, line 435 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiT2q70JFhsf5AxKu9:-MSiT2q70JFhsf5AxKuA:b-sskbuu) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/ext/filters/max_age/max_age_filter.cc#L435)):*
> ```cpp
>     ABSL_NO_THREAD_SAFETY_ANALYSIS {
>   channel_data* chand = static_cast<channel_data*>(elem->channel_data);
>   new (&chand->max_age_timer_mu) grpc_core::Mutex();
> ```

I think this can call placement-new on the entire struct, not just the one field:

```
new (chand) channel_data;
```
___
*[src/core/ext/filters/max_age/max_age_filter.cc, line 522 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiT7uxB0OkvFNEH1LK:-MSiT7uy3dgVdi0ow9iK:b-b5jvk) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/ext/filters/max_age/max_age_filter.cc#L522)):*
> ```cpp
> static void max_age_destroy_channel_elem(grpc_channel_element* elem) {
>   channel_data* chand = static_cast<channel_data*>(elem->channel_data);
>   chand->max_age_timer_mu.~Mutex();
> ```

Similarly, this should be:

```
chand->~channel_data();
```
___
*[src/core/lib/gprpp/sync.h, line 174 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MShzYmB3iYDSDsibf_-:-MSiTxf824PuZKVUF5Xj:b-iox5jg) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/gprpp/sync.h#L174)):*
<details><summary><i>Previously, veblush (Esun Kim) wrote…</i></summary><blockquote>

Yep, I like to do but can we do it in separate PRs?
</blockquote></details>

Okay, I guess that's fine.
___
*[src/core/lib/gprpp/sync.h, line 187 at r1](https://reviewable.io/reviews/grpc/grpc/25325#-MSi-Fi4-pWQ3qLbx5Pr:-MSiVy5uAh6y3-9KeXf2:b-irz7zg) ([raw file](https://github.com/grpc/grpc/blob/159e510f3d731bc6d6b3259b0d0f53f8d0d399f9/src/core/lib/gprpp/sync.h#L187)):*
<details><summary><i>Previously, veblush (Esun Kim) wrote…</i></summary><blockquote>

They actually need. All twos need lock function.
</blockquote></details>

You're right.  Sorry for missing that.

Let's try to clean this up in a subsequent PR.  This seems like an anti-pattern to me.
___
*[src/core/lib/gprpp/sync.h, line 52 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiTncF1esmLE9NvwoB:-MSiTncF1esmLE9NvwoC:b-smi0in) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/lib/gprpp/sync.h#L52)):*
> ```objc
> // Returns the underlying gpr_mu from Mutex. This should be used only when
> // it has to like passing the C++ mutex to C-core API.
> // TODO(veblush): Remove this once all C-core mutexs are gone.
> ```

"all C-core mutexes" is a little vague.  Let's explicitly say "after C-core no longer uses gpr_mu".
___
*[src/core/lib/gprpp/sync.h, line 82 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiTu8W0swIKLMclcZt:-MSiTu8W0swIKLMclcZu:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/lib/gprpp/sync.h#L82)):*
> ```objc
> // Returns the underlying gpr_mu from Mutex. This should be used only when
> // it has to like passing the C++ mutex to C-core API.
> // TODO(veblush): Remove this once all C-core mutexs are gone.
> ```

Same here.
___
*[src/core/tsi/alts/handshaker/alts_handshaker_client.cc, line 144 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiVZ9A2BNkozN_T7Db:-MSiVZ9A2BNkozN_T7Dc:brmhg90) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/tsi/alts/handshaker/alts_handshaker_client.cc#L144)):*
> ```cpp
>     grpc_slice_unref_internal(client->handshake_status_details);
>     client->mu.~Mutex();
>     gpr_free(client);
> ```

This can just say `delete client`, so there's no need to manually call the mutex's dtor.
___
*[src/core/tsi/alts/handshaker/alts_handshaker_client.cc, line 698 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiUMioCiZ9CJlx22Xh:-MSiUMioCiZ9CJlx22Xi:btbzxxl) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/tsi/alts/handshaker/alts_handshaker_client.cc#L698)):*
> ```cpp
>     return nullptr;
>   }
>   alts_grpc_handshaker_client* client =
> ```

Let's just new C++-style `new` to construct this object:

```
auto* client = new alts_grpc_handshaker_client();
```

That way, there's no need to use placement-new on the mutex itself.
___
*[src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc, line 596 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiUy_DDoqBP6pITD66:-MSiUy_E5-kwzVhNTjXw:b-s3rnfw) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc#L596)):*
> ```cpp
>   gpr_free(handshaker->handshaker_service_url);
>   handshaker->mu.~Mutex();
>   gpr_free(handshaker);
> ```

This can just say `delete handshaker`, so there's no need to manually call the mutex's dtor.
___
*[src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc, line 631 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiVDO7CiTGXo3c0LgR:-MSiVDO7CiTGXo3c0LgS:b-au7pxu) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc#L631)):*
> ```cpp
>     return TSI_INVALID_ARGUMENT;
>   }
>   alts_tsi_handshaker* handshaker =
> ```

This can say:

```
auto* handshaker = new alts_tsi_handshaker;
```

Then there's no need to use placement-new on the mutex.


<!-- Sent from Reviewable.io -->

2021-02-04 21:41 UTC, veblush reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25325)* status: all files reviewed, 9 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/max_age/max_age_filter.cc, line 433 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiTX1P09oOGo54mT-9:-MSitdS9Cn1d6AkxvSi7:bjg6x97) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/ext/filters/max_age/max_age_filter.cc#L433)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this needed?

Would it eliminate the need for this if we move the body of this function into a `channel_data` ctor?
</blockquote></details>

Yep. Done.
___
*[src/core/ext/filters/max_age/max_age_filter.cc, line 435 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiT2q70JFhsf5AxKu9:-MSitdBfA_cwLMib5kf2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/ext/filters/max_age/max_age_filter.cc#L435)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can call placement-new on the entire struct, not just the one field:

```
new (chand) channel_data;
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/max_age/max_age_filter.cc, line 522 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiT7uxB0OkvFNEH1LK:-MSitf42-V9lWMbP5_yO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/ext/filters/max_age/max_age_filter.cc#L522)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similarly, this should be:

```
chand->~channel_data();
```
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/sync.h, line 52 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiTncF1esmLE9NvwoB:-MSitxs34qhLJqj6jRIb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/lib/gprpp/sync.h#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

"all C-core mutexes" is a little vague.  Let's explicitly say "after C-core no longer uses gpr_mu".
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/sync.h, line 82 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiTu8W0swIKLMclcZt:-MSityHB1wGp0a_w_16M:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/lib/gprpp/sync.h#L82)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/tsi/alts/handshaker/alts_handshaker_client.cc, line 144 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiVZ9A2BNkozN_T7Db:-MSix1wR7jhs1vOdLuxB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/tsi/alts/handshaker/alts_handshaker_client.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can just say `delete client`, so there's no need to manually call the mutex's dtor.
</blockquote></details>

Done.
___
*[src/core/tsi/alts/handshaker/alts_handshaker_client.cc, line 698 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiUMioCiZ9CJlx22Xh:-MSix1_Z1Gfz6VydoDt-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/tsi/alts/handshaker/alts_handshaker_client.cc#L698)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's just new C++-style `new` to construct this object:

```
auto* client = new alts_grpc_handshaker_client();
```

That way, there's no need to use placement-new on the mutex itself.
</blockquote></details>

Done.
___
*[src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc, line 596 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiUy_DDoqBP6pITD66:-MSixt5l3rvQLki_0yCa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc#L596)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can just say `delete handshaker`, so there's no need to manually call the mutex's dtor.
</blockquote></details>

Done.
___
*[src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc, line 631 at r2](https://reviewable.io/reviews/grpc/grpc/25325#-MSiVDO7CiTGXo3c0LgR:-MSixvOm-NSDdo4DvMgr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2546c02d132bf4c8bb82db00d0995dacb1572188/src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc#L631)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can say:

```
auto* handshaker = new alts_tsi_handshaker;
```

Then there's no need to use placement-new on the mutex.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-04 22:25 UTC, markdroth approved these changes
This looks great!  Feel free to merge after addressing remaining comments.

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25325#-:-MSj8VMP2P1jkaHShkW6:b602gs8)* status: all files reviewed, 3 unresolved discussions (waiting on @veblush)

___
*[src/core/ext/filters/max_age/max_age_filter.cc, line 54 at r3](https://reviewable.io/reviews/grpc/grpc/25325#-MSj7aqx1FGXonPFWzEz:-MSj7aqx1FGXonPFWzF-:b-i4s9ew) ([raw file](https://github.com/grpc/grpc/blob/b69bc342a1b6a616f4baf91fb3d8b7b8adde10b0/src/core/ext/filters/max_age/max_age_filter.cc#L54)):*
> ```cpp
> struct channel_data {
>   channel_data() {
>     max_age_timer_pending = false;
> ```

You can probably actually just initialize these where the fields are declared below, rather than in the body of the ctor.
___
*[src/core/tsi/alts/handshaker/alts_handshaker_client.cc, line 704 at r3](https://reviewable.io/reviews/grpc/grpc/25325#-MSj84-pDGEWPRaXL24T:-MSj84-q5Xa8ZHv_pXJJ:b-uhsg7s) ([raw file](https://github.com/grpc/grpc/blob/b69bc342a1b6a616f4baf91fb3d8b7b8adde10b0/src/core/tsi/alts/handshaker/alts_handshaker_client.cc#L704)):*
> ```cpp
>   client->handshaker = handshaker;
>   client->grpc_caller = grpc_call_start_batch_and_execute;
>   client->send_buffer = nullptr;
> ```

All of the fields that are initialized to constants could just be set where the fields are declared in the struct.
___
*[src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc, line 640 at r3](https://reviewable.io/reviews/grpc/grpc/25325#-MSj8JjhDfahSUc865rF:-MSj8JjhDfahSUc865rG:b-det7lw) ([raw file](https://github.com/grpc/grpc/blob/b69bc342a1b6a616f4baf91fb3d8b7b8adde10b0/src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc#L640)):*
> ```cpp
>                                 : grpc_slice_from_static_string(target_name);
>   handshaker->is_client = is_client;
>   handshaker->has_sent_start_message = false;
> ```

The fields that are set to constants can be initialized where they are declared.


<!-- Sent from Reviewable.io -->

2021-02-05 01:52 UTC, veblush reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25325)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth and @veblush)

___
*[src/core/ext/filters/max_age/max_age_filter.cc, line 54 at r3](https://reviewable.io/reviews/grpc/grpc/25325#-MSj7aqx1FGXonPFWzEz:-MSjqvTVCvGRQTaT-D3I:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b69bc342a1b6a616f4baf91fb3d8b7b8adde10b0/src/core/ext/filters/max_age/max_age_filter.cc#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can probably actually just initialize these where the fields are declared below, rather than in the body of the ctor.
</blockquote></details>

Done.
___
*[src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc, line 640 at r3](https://reviewable.io/reviews/grpc/grpc/25325#-MSj8JjhDfahSUc865rF:-MSjrN4E93YPgMYAMawf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b69bc342a1b6a616f4baf91fb3d8b7b8adde10b0/src/core/tsi/alts/handshaker/alts_tsi_handshaker.cc#L640)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The fields that are set to constants can be initialized where they are declared.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 07:08 UTC, merged