Initial commit
grpc/grpc pull request #25321
Opened 2021-02-02 08:37 UTC by yashykt

2021-02-10 22:03 UTC, markdroth requested changes
This looks like a great start!

Please let me know if you have any questions.  Thanks!

> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321#-:-MTCxhWnDffI0BIKNcgr:b9kv8rc)* status: all files reviewed, 25 unresolved discussions (waiting on @yashykt)

___
*[include/grpc/grpc.h, line 414 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCJjGbCPJ6Xg2txX3F:-MTCJPo_2cHLKZ73wyXD:b-ukddhi) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpc/grpc.h#L414)):*
> ```objc
>                                                    void* reserved);
> 
> // There might be more methods added later, so users should take care to memset
> ```

Unlike the C++ API, we can make non-backward-compatible changes to the C-core API, so this isn't such a big deal.  In fact, we can probably not have this struct at all and instead just pass the function pointer and the user_data arg as separate parameters to `grpc_server_config_fetcher_xds_create()`.

Just a thought -- this is fine as-is too.
___
*[include/grpcpp/xds_server_builder.h, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCKFCB2bqmiTTj2Zu6:-MTCKFCB2bqmiTTj2Zu7:bd1kcab) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpcpp/xds_server_builder.h#L29)):*
> ```objc
> namespace experimental {
> 
> class XdsServerBuilderServingStatusNotifierInterface {
> ```

Suggest removing the "Builder" from this name, since this object will actually outlive the builder.
___
*[include/grpcpp/xds_server_builder.h, line 68 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCYXp78k_drWPUJnoR:-MTCYXp78k_drWPUJnoS:b-3uc2n1) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpcpp/xds_server_builder.h#L68)):*
> ```objc
>                                     grpc_status_code code,
>                                     const char* error_message) {
>     XdsServerBuilderServingStatusNotifierInterface* ptr =
> ```

Suggest calling this notifier.
___
*[include/grpcpp/xds_server_builder.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCYZTEEF671V-SuR3j:-MTCYZTEEF671V-SuR3k:brx85g) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpcpp/xds_server_builder.h#L70)):*
> ```objc
>     XdsServerBuilderServingStatusNotifierInterface* ptr =
>         static_cast<XdsServerBuilderServingStatusNotifierInterface*>(user_data);
>     ptr->OnServingStatusChange(
> ```

If the user hasn't set a notifier, this will be null.
___
*[include/grpcpp/xds_server_builder.h, line 74 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCK5Hr96aPcASUatnF:-MTCK5Hr96aPcASUatnG:bmbwf75) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpcpp/xds_server_builder.h#L74)):*
> ```objc
>   }
> 
>   grpc_server_xds_status_notifier c_notifier_;
> ```

As currently written, the C-core API passes the `grpc_server_xds_status_notifier` struct to `grpc_server_config_fetcher_xds_create()` by value, which means that there actually isn't any reason we need a copy of the struct here in the C++ object; all we really need here is an `XdsServerBuilderServingStatusNotifierInterface*`.  We can construct the `grpc_server_xds_status_notifier` on the stack when we call `grpc_server_config_fetcher_xds_create()`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 128 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCREZFEb90A-kEDhAx:-MTCREZFEb90A-kEDhAy:b-e2dm8v) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L128)):*
> ```cpp
>       MutexLock lock(&listener_->mu_);
>       listener_->stop_serving_ = true;
>       for (auto& iterator : listener_->connections_) {
> ```

This isn't an iterator, it's actually a `ConnectionState*`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 170 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCO5mICsZv2J4mWkKs:-MTCO5mICsZv2J4mWkKt:b-bif326) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L170)):*
> ```cpp
>     grpc_pollset_set* const interested_parties_;
>     std::list<ConnectionState*>::iterator position_;
>     bool stop_serving_ = false;
> ```

The double-negative here is a little confusing.  Maybe call this `is_serving_` and negate the value?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 193 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCODHP2Tegc9T1IPwF:-MTCODHP2Tegc9T1IPwG:buqyrfo) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L193)):*
> ```cpp
>   grpc_channel_args* args_;  // guarded by mu_
>   ConfigFetcherWatcher* config_fetcher_watcher_ = nullptr;
>   bool stop_serving_ = false;
> ```

Same comment as above regarding the double-negative.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 195 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCObjG9fRa-aFJDp2a:-MTCObjG9fRa-aFJDp2b:behxctn) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L195)):*
> ```cpp
>   bool stop_serving_ = false;
>   bool shutdown_ = true;
>   std::list<ConnectionState*> connections_;
> ```

If we change this to use `std::set<>`, then I don't think we need the `ConnectionState` object to hold an iterator to its own position, because the lookup should be fairly quick just based on its address.

I suppose we could also consider something like `std::unordered_set<>` or maybe one of the absl containers if we think this could get really large.  But I suspect that shutdown and startup are going to be rare enough that we don't need to optimize for run-time here; minimizing memory usage is probably more important.

Speaking of which, have we considered how much memory this will add to really busy servers (e.g., those with 10K+ connections)?  Are there alternatives that might not require us to keep this list at all?  I don't see any obvious alternative, but maybe you can think of something I can't.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 242 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCRZAKEC2p9QKYV2C2:-MTCRZAKEC2p9QKYV2C3:b-phyf22) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L242)):*
> ```cpp
>   stop_serving_ = true;
>   grpc_transport_op* op = grpc_make_transport_op(nullptr);
>   op->goaway_error = GRPC_ERROR_CREATE_FROM_STATIC_STRING(
> ```

How does this interact with #24237 and internal issue b/135458602?  Are we going to do the right GOAWAY behavior here?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 244 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCU3g9Cd1pAid5pbZh:-MTCU3g9Cd1pAid5pbZi:b-g8k1qp) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L244)):*
> ```cpp
>   op->goaway_error = GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>       "Server is stopping to serve requests.");
>   grpc_transport_perform_op(&transport_->base, op);
> ```

What happens if the connection is still handshaking and has not yet created the transport?

I think in that case, we just need to shut down the endpoint and let the handshaking fail.  Note that we also probably need to check `stop_serving_` in `OnHandshakeDone()` to handle the race condition where handshaking is already complete but `OnHandshakeDone()` has not yet been invoked.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 337 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCSbzB6E5JV2qQp5aE:-MTCSbzB6E5JV2qQp5a [...]

2021-02-10 23:17 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 25 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[include/grpcpp/xds_server_builder.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCYZTEEF671V-SuR3j:-MTD1SoZ46WrlsMSOR8v:b-gcbw8t) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpcpp/xds_server_builder.h#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If the user hasn't set a notifier, this will be null.
</blockquote></details>

If the user hasn't set a notifier, OnServingStatusChange will not be invoked.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 195 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCObjG9fRa-aFJDp2a:-MTD33nPBjldxJsdyOMI:bp53xit) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L195)):*
I chose to use a std::list instead of an std::set primarily to avoid a lookup without adding a lot of additional state which would be the case with an unordered_set.

> I suppose we could also consider something like std::unordered_set<> or maybe one of the absl containers if we think this could get really large. But I suspect that shutdown and startup are going to be rare enough that we don't need to optimize for run-time here; minimizing memory usage is probably more important.

I am considering servers where the connections themselves are short-lived, something like a client starts a connection, performs a unary RPC and deletes the channel. Using a std::list where we can just save the position seems like a good match.

> Speaking of which, have we considered how much memory this will add to really busy servers (e.g., those with 10K+ connections)? Are there alternatives that might not require us to keep this list at all? I don't see any obvious alternative, but maybe you can think of something I can't.

I haven't found one yet. It seems that we need some way to delete all active connections for a particular listener, so it seems like we won't be able to avoid storing this association somehow.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 242 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCRZAKEC2p9QKYV2C2:-MTD4skU2f0bBsIkww4w:bma57w6) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L242)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How does this interact with #24237 and internal issue b/135458602?  Are we going to do the right GOAWAY behavior here?
</blockquote></details>

If I am not making a mistake, the server will send a GOAWAY immediately. Nice gRPC clients will eventually respect that GOAWAY and not try to create new RPCs, but this assumes that we are talking to a nice client. A malicious/bad client might very well ignore the GOAWAY and continue creating new RPCs forever. Due to the existing bug, our server will keep accepting those new streams and the connection will never close.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 244 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCU3g9Cd1pAid5pbZh:-MTD7GyG0U4SkbvSf9R7:bnwrmdz) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L244)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What happens if the connection is still handshaking and has not yet created the transport?

I think in that case, we just need to shut down the endpoint and let the handshaking fail.  Note that we also probably need to check `stop_serving_` in `OnHandshakeDone()` to handle the race condition where handshaking is already complete but `OnHandshakeDone()` has not yet been invoked.
</blockquote></details>

I thought I had added that. Evidently not.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 337 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCSbzB6E5JV2qQp5aE:-MTD9V9K0hG8OjHTZszO:b-xk95k) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L337)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is it possible that the transport closes before the initial SETTINGS frame is received?  If so, then I think we need both refs.
</blockquote></details>

If the transport closes before the settings frame is received, both of the closures are invoked, and so if we are sure about them being invoked from the same thread one after another, we might not need the ref


<!-- Sent from Reviewable.io -->

2021-02-10 23:42 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 24 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[include/grpcpp/xds_server_builder.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCYZTEEF671V-SuR3j:-MTDFrso3bD6r9z6KFZg:b-s7zjlj) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpcpp/xds_server_builder.h#L70)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

If the user hasn't set a notifier, OnServingStatusChange will not be invoked.
</blockquote></details>

I don't think that's true.  The notifier struct has two fields: `on_serving_status_change` and `user_data`.  The code here always sets the first to non-null and sets the second to non-null only if the caller sets a notifier.  However, the code in xds_server_config_fetcher.cc checks that the first field is non-null before invoking the callback, which means that this will always be invoked.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 195 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCObjG9fRa-aFJDp2a:-MTDGgG16EtwCEEteuW-:b-i6jbey) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L195)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I chose to use a std::list instead of an std::set primarily to avoid a lookup without adding a lot of additional state which would be the case with an unordered_set.

> I suppose we could also consider something like std::unordered_set<> or maybe one of the absl containers if we think this could get really large. But I suspect that shutdown and startup are going to be rare enough that we don't need to optimize for run-time here; minimizing memory usage is probably more important.

I am considering servers where the connections themselves are short-lived, something like a client starts a connection, performs a unary RPC and deletes the channel. Using a std::list where we can just save the position seems like a good match.

> Speaking of which, have we considered how much memory this will add to really busy servers (e.g., those with 10K+ connections)? Are there alternatives that might not require us to keep this list at all? I don't see any obvious alternative, but maybe you can think of something I can't.

I haven't found one yet. It seems that we need some way to delete all active connections for a particular listener, so it seems like we won't be able to avoid storing this association somehow.
</blockquote></details>

I don't think we should optimize for the case of short-lived connections, since that's not the common case, and any application doing that is going to behave very inefficiently anyway.  I think it's more important to optimize for the common case of long-lived connections and servers that need to scale up to a large number of clients.

I don't understand what you mean by "adding a lot of additional state" for a set.  It seems to me that the `std::list<>` approach requires additional state, because it means that the `ConnectionState` object has to store the iterator.  That becomes unnecessary with the `std::set<>` approach; the `ConnectionState` object can just do `connections_.find(this)`.  I think that approach should use less memory.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 242 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCRZAKEC2p9QKYV2C2:-MTDHs0x90t87ShQYecj:b-iky2r6) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L242)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

If I am not making a mistake, the server will send a GOAWAY immediately. Nice gRPC clients will eventually respect that GOAWAY and not try to create new RPCs, but this assumes that we are talking to a nice client. A malicious/bad client might very well ignore the GOAWAY and continue creating new RPCs forever. Due to the existing bug, our server will keep accepting those new streams and the connection will never close.
</blockquote></details>

Okay, I see -- so we're depending on the client to close the connection when the last in-flight RPC finishes.

I guess that could work, but it seems a little sub-optimal, because it allows the existing connection to remain open for as long as the existing RPCs are still in flight.  If those are long-running streams, the connection could remain around indefinitely.  It seems like what we really ought to do here is to do a safe shutdown -- i.e., send a GOAWAY, wait for a grace period, and then close the connection.

As I said on the internal bug, it would be really nice to change our transport op semantics to allow callers to do this without setting their own timers, since there are a lot of places we trigger this kind of behavior from.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 337 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCSbzB6E5JV2qQp5aE:-MTDIFfW4JQR-mx1-kqM:b-hhzruh) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L337)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

If the transport closes before the settings frame is received, both of the closures are invoked, and so if we are sure about them being invoked from the same thread one after another, we might not need the ref
</blockquote></details>

Ah, right, good point -- I had forgotten that `OnReceiveSettings()` will be invoked regardless.

Yeah, I guess this does come down to a question of whether there's a guarantee that the two closures will be invoked in the right order.  But it seems like we don't really have any such guarantee; even if the current code happens to behave that way, there's no guarantee it will stay that way in the future, so depending on it seems brittle.

Also, this problem may be moot if you take my suggestion below about splitting the `OnClose()` functionality into a different object.


<!-- Sent from Reviewable.io -->

2021-02-12 22:50 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 16 of 23 files reviewed, 23 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[include/grpcpp/xds_server_builder.h, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCKFCB2bqmiTTj2Zu6:-MTNMl2REE4ANU80RGJn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpcpp/xds_server_builder.h#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest removing the "Builder" from this name, since this object will actually outlive the builder.
</blockquote></details>

Done.
___
*[include/grpcpp/xds_server_builder.h, line 68 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCYXp78k_drWPUJnoR:-MTNMmGH8odtrLY6rVX9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpcpp/xds_server_builder.h#L68)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this notifier.
</blockquote></details>

Done.
___
*[include/grpcpp/xds_server_builder.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCYZTEEF671V-SuR3j:-MTNMmlTD8rz09MkbX_Q:b7nn2dv) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpcpp/xds_server_builder.h#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think that's true.  The notifier struct has two fields: `on_serving_status_change` and `user_data`.  The code here always sets the first to non-null and sets the second to non-null only if the caller sets a notifier.  However, the code in xds_server_config_fetcher.cc checks that the first field is non-null before invoking the callback, which means that this will always be invoked.
</blockquote></details>

Ah you are right. Added a null check.
___
*[include/grpcpp/xds_server_builder.h, line 74 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCK5Hr96aPcASUatnF:-MTNMraND-fqA4NCPBv3:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/include/grpcpp/xds_server_builder.h#L74)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As currently written, the C-core API passes the `grpc_server_xds_status_notifier` struct to `grpc_server_config_fetcher_xds_create()` by value, which means that there actually isn't any reason we need a copy of the struct here in the C++ object; all we really need here is an `XdsServerBuilderServingStatusNotifierInterface*`.  We can construct the `grpc_server_xds_status_notifier` on the stack when we call `grpc_server_config_fetcher_xds_create()`.
</blockquote></details>

Done
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 128 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCREZFEb90A-kEDhAx:-MTNMwcH6buIgWpkSzu1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L128)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This isn't an iterator, it's actually a `ConnectionState*`.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 195 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCObjG9fRa-aFJDp2a:-MTNPvrS9XgiU3owfBsD:b9n1535) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L195)):*
> I don't understand what you mean by "adding a lot of additional state" for a set.
This is for an unordered_set which would use more memory. I do agree though that using std::set is better in terms of memory usage when compared to std::list, and if we want to optimize for long lived connections then it makes sense.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 244 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCU3g9Cd1pAid5pbZh:-MTNQUF-7_VaPB6ltIB2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L244)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I thought I had added that. Evidently not.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 337 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCSbzB6E5JV2qQp5aE:-MTNQZca52ZIrAdM6n8i:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L337)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ah, right, good point -- I had forgotten that `OnReceiveSettings()` will be invoked regardless.

Yeah, I guess this does come down to a question of whether there's a guarantee that the two closures will be invoked in the right order.  But it seems like we don't really have any such guarantee; even if the current code happens to behave that way, there's no guarantee it will stay that way in the future, so depending on it seems brittle.

Also, this problem may be moot if you take my suggestion below about splitting the `OnClose()` functionality into a different object.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 340 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCbjPfEJS6ZePmRjsy:-MTNQbj6-UcvvxAlA6oS:b-e75dm4) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L340)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's worth noting that this basically means that this `ConnectionState` object is no longer just about handshaking; it actually lives until the transport is closed.  But the `ConnectionState` object has a lot of data members that aren't relevant once handshaking is complete, so this seems like it will unnecessarily increase memory usage for servers.

Instead, can we create a separate object that contains just the state we need, and let *that* object share the lifetime of the connection, so that we can destroy the `ConnectionState` object when the handshaking is complete?  I think after that we don't need to keep anything other than the transport itself and maybe a closure (although the latter might be eliminated by using `std::function<>` instead).
</blockquote></details>

I like this idea! Done!
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 527 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCSyJ6EuhtBW7ZEifA:-MTNQg8CBGZroNpM4Yr3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L527)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'd prefer to avoid `goto` in new code.   Instead, I suggest moving the body of this function into a helper function that returns a bool to indicate if it failed, in which case we can do the error cleanup.

See my next comment about moving some of this code into `CreateHandshakeManager()`.  It may be that that function is the helper function we want, and that we just need to move some more code into it.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 535 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCTGP24_OfbaEsImu5:-MTNQhu7A9thH0k5saOQ:bcq35b0) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L535)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like we're now grabbing and  [...]

2021-02-12 22:54 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 16 of 23 files reviewed, 23 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 170 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCO5mICsZv2J4mWkKs:-MTNRARp4KKmnsmSR6cP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L170)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The double-negative here is a little confusing.  Maybe call this `is_serving_` and negate the value?
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 193 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCODHP2Tegc9T1IPwF:-MTNRC0q-GeG-Ntlmdrt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L193)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same comment as above regarding the double-negative.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6816 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCw_lW-LFX4TJ-vhbW:-MTNRDId8eB1xxaZU8nj:b-s6kij6) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/test/cpp/end2end/xds_end2end_test.cc#L6816)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In this test, how do we know that the update has actually been seen by the client by the time the test is complete?  Could this test fail to catch a failure?
</blockquote></details>

You are right.  There is a chance that the test could fail to catch the failure.
One way I can increase the confidence is to do it in a loop for 10 times. 
Alternatively, I can simply add the `OnWarning()` callback for such cases


<!-- Sent from Reviewable.io -->

2021-02-13 00:41 UTC, markdroth requested changes
This is getting closer!  The only significant issue is that we're still not cancelling handshakes the way we should be.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321#-:-MTNpJ-_2ED6TnPfpdmC:b1xpdk0)* status: all files reviewed, 13 unresolved discussions (waiting on @yashykt)

___
*[include/grpcpp/xds_server_builder.h, line 51 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNV4M62CuVYwMs-YDr:-MTNV4M7Cix35gyv8lwo:b-ku750t) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/include/grpcpp/xds_server_builder.h#L51)):*
> ```objc
> 
>   std::unique_ptr<Server> BuildAndStart() override {
>     grpc_server_xds_status_notifier c_notifier;
> ```

Could just say `= { OnServingStatusChange, notifier_ };`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 128 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCREZFEb90A-kEDhAx:-MTNVQLb3D3G8gtRe9QL:b-m3oaaf) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/src/core/ext/transport/chttp2/server/chttp2_server.cc#L128)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please also use `ActiveConnection*` instead of `auto&`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 168 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNjazTCExpCV7upiKB:-MTNjazTCExpCV7upiKC:b-cfnm5h) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L168)):*
> ```cpp
> 
>     void StopServing();
>     static void OnClose(void* arg, grpc_error* error);
> ```

This can be private.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 203 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNWuOx7yBktQwFVcB2:-MTNWuOx7yBktQwFVcB3:bl971y4) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L203)):*
> ```cpp
>   Chttp2ServerArgsModifier args_modifier_;
>   Mutex mu_;
>   grpc_channel_args* args_;  // guarded by mu_
> ```

While you're in here, maybe start using some of the absl lock annotations, so that the compiler can enforce that certain fields are accessed only while the mutex is held?  @veblush just recently enabled this, so he can probably advise if you have questions about this.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 377 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTN_1iV1DJ6DwRThrzo:-MTN_1iWDRZzJoBCA7-r:bsew7qf) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L377)):*
> ```cpp
>     Chttp2ServerListener* listener, grpc_chttp2_transport* transport)
>     : listener_(listener), transport_(transport) {
>   // The constructor should be called while holding a lock on listener_->mu
> ```

Here's another case where a lock annotation would be good.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 388 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNlbof-FKmY4uQdmty:-MTNlbogEaWb0btzJWR9:b-dekazs) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L388)):*
> ```cpp
>   op->goaway_error = GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>       "Server is stopping to serve requests.");
>   grpc_transport_perform_op(&transport_->base, op);
> ```

As per my comment below about creating the `ActiveConnection` object as soon as the TCP connection is established instead of waiting until handshaking is complete, I think this needs to handle the case where `StopServing()` is called while we are still in the process of handshaking.  In that case, the transport hasn't been created yet (`transport_` will be null), so sending a transport op to generate a GOAWAY isn't the right thing.  Instead, I think we need to call the `HandshakeManager`'s `Shutdown()` method to stop handshaking.  (I think I previously said that we need to shut down the endpoint, but I realized that we can't do that directly; while handshaking is going on, the endpoint is owned by the handshake manager, so we have to shut down the handshake manager and let it shut down the endpoint for us.)
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 521 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNZo0SBag6RJTxzraX:-MTNZo0SBag6RJTxzraY:bkdy458) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L521)):*
> ```cpp
> }
> 
> bool Chttp2ServerListener::CreateHandshakeManager(
> ```

Suggest renaming this to `StartHandshaking()`, to better reflect what it now does.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 543 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNlsObDLrYlHade7r-:-MTNlsObDLrYlHade7r0:b-6zvfgh) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L543)):*
> ```cpp
>   }
>   // Deletes itself when done.
>   new ActiveConnection::HandshakingState(this, accepting_pollset, acceptor,
> ```

I think we need to create the `ActiveConnection` object at this point and register it in `connections_`, rather than waiting until handshaking is complete to do so.  Otherwise, if `StopListening()` is called while handshaking is going on, we won't cancel the handshake.  (We will still fail the connection once handshaking is complete, but we shouldn't just let it run to completion when we can cancel it.)

Note that if we do this, then this may eliminate the need for `pending_handshake_mgrs_`.  As this PR is currently written, we are referencing the connection in `pending_handshake_mgrs_` until it finishes handshaking, and then moving it to `connections_`.  Instead, I think we can store all connections in `connections_`, and when we shut down a connection, we can have the `ActiveConnection` object decide whether it needs to kill its handshake or tell the transport to send a GOAWAY.  This would also allow us to eliminate the `prev_` and `next_` fields in the `HandshakeManager` class.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 553 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNZeCqDnQEipjhmEwQ:-MTNZeCqDnQEipjhmEwR:bvp45uw) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L553)):*
> ```cpp
>                                     grpc_tcp_server_acceptor* acceptor) {
>   Chttp2ServerListener* self = static_cast<Chttp2ServerListener*>(arg);
>   RefCountedPtr<HandshakeManager> handshake_mgr;
> ```

This is no longer needed.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 150 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNU_GjAEBhxSXRMOJ3:-MTNU_GjAEBhxSXRMOJ4:b-1tjeys) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/xds/xds_server_config_fetcher.cc#L150)):*
> ```cpp
>               GRPC_STATUS_UNAVAILABLE, grpc_error_string(error));
>         } else {
>           gpr_log(GPR_INFO,
> ```

I just noticed that we're already generating a `GPR_ERROR` log at the top of this method.  Maybe just change that to include the listening address, and then remove this one?
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 174 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNUfWG1fjoSz7yOjBB:-MTNUfWG1fjoSz7yOjBC:bwhbgh2) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/xds/xds_server_config_fetcher.cc#L174)):*
> ```cpp
>             GRPC_STATUS_NOT_FOUND, "Requested listener does not exist");
>       } else {
>     [...]

2021-02-21 06:04 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 19 of 25 files reviewed, 13 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[include/grpcpp/xds_server_builder.h, line 51 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNV4M62CuVYwMs-YDr:-MU27qE626ReOh0WH5Wb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/include/grpcpp/xds_server_builder.h#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Could just say `= { OnServingStatusChange, notifier_ };`.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 388 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNlbof-FKmY4uQdmty:-MU282X9CWGIdOdufwXW:b-vwo8pm) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L388)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per my comment below about creating the `ActiveConnection` object as soon as the TCP connection is established instead of waiting until handshaking is complete, I think this needs to handle the case where `StopServing()` is called while we are still in the process of handshaking.  In that case, the transport hasn't been created yet (`transport_` will be null), so sending a transport op to generate a GOAWAY isn't the right thing.  Instead, I think we need to call the `HandshakeManager`'s `Shutdown()` method to stop handshaking.  (I think I previously said that we need to shut down the endpoint, but I realized that we can't do that directly; while handshaking is going on, the endpoint is owned by the handshake manager, so we have to shut down the handshake manager and let it shut down the endpoint for us.)
</blockquote></details>

Updated.

To make sure that refs are being handled properly and that ActiveConnection does not go away before HandshakingState, I made ActiveConnection a refcounted object.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 521 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNZo0SBag6RJTxzraX:-MU28UM3BBmFjN8gouXE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L521)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest renaming this to `StartHandshaking()`, to better reflect what it now does.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 543 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNlsObDLrYlHade7r-:-MU28WRl8gXomwZ33X6h:b-mip9nh) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L543)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we need to create the `ActiveConnection` object at this point and register it in `connections_`, rather than waiting until handshaking is complete to do so.  Otherwise, if `StopListening()` is called while handshaking is going on, we won't cancel the handshake.  (We will still fail the connection once handshaking is complete, but we shouldn't just let it run to completion when we can cancel it.)

Note that if we do this, then this may eliminate the need for `pending_handshake_mgrs_`.  As this PR is currently written, we are referencing the connection in `pending_handshake_mgrs_` until it finishes handshaking, and then moving it to `connections_`.  Instead, I think we can store all connections in `connections_`, and when we shut down a connection, we can have the `ActiveConnection` object decide whether it needs to kill its handshake or tell the transport to send a GOAWAY.  This would also allow us to eliminate the `prev_` and `next_` fields in the `HandshakeManager` class.
</blockquote></details>

Done. prev_ and next_ fields removed
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 553 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNZeCqDnQEipjhmEwQ:-MU28am479CFjfPZto2X:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L553)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is no longer needed.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 150 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNU_GjAEBhxSXRMOJ3:-MU28cxO8pPr8C7fnL8k:b-tojsuz) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/xds/xds_server_config_fetcher.cc#L150)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I just noticed that we're already generating a `GPR_ERROR` log at the top of this method.  Maybe just change that to include the listening address, and then remove this one?
</blockquote></details>

In this case, the two might not necessarily mean the same thing. The difference would be the same as the difference between `OnWarning` and `NotServing`
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 174 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNUfWG1fjoSz7yOjBB:-MU28vVU53Zk5NNE8rVa:b-b24zlf) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/xds/xds_server_config_fetcher.cc#L174)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similar comment here -- maybe just combine this with the `GPR_ERROR` log at the top of the method?
</blockquote></details>

It makes sense here. Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6816 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCw_lW-LFX4TJ-vhbW:-MU2AlTr0sY3TsrFXFid:b-5pp5it) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/test/cpp/end2end/xds_end2end_test.cc#L6816)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about sending the RPC before calling `WaitOnServingStatusChange()`?  That may at least give it more time to register.

Can we at least manually inspect the logs and verify that the test is running long enough for the change to register?
</blockquote></details>

Adding another RPC did not help. Adding a 100ms sleep does help
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7514 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNosCBEuPOGRWjlSBB:-MU29-GHBIlBJYwv-C16:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/test/cpp/end2end/xds_end2end_test.cc#L7514)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-21 07:22 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 19 of 25 files reviewed, 13 unresolved discussions (waiting on @markdroth and @veblush)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 168 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNjazTCExpCV7upiKB:-MU2BEGQ7T66Hzb2Axvw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L168)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be private.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 203 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNWuOx7yBktQwFVcB2:-MU2SG95DMBfI-TyKvzh:b-us8lzc) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L203)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

While you're in here, maybe start using some of the absl lock annotations, so that the compiler can enforce that certain fields are accessed only while the mutex is held?  @veblush just recently enabled this, so he can probably advise if you have questions about this.
</blockquote></details>

I was able to add lock annotations, but i've not been able to fix one remaining warning 

```
src/core/ext/transport/chttp2/server/chttp2_server.cc:555:17: warning: calling function 'StopServingLocked' requires holding mutex 'connection->listener_->mu_' exclusively [-Wthread-safety-precise]
    connection->StopServingLocked();
                ^
src/core/ext/transport/chttp2/server/chttp2_server.cc:555:17: note: found near match 'mu_'

```

Unless I'm making a mistake, I think it does not realize that `mu_` is the same as `connection->listener_->mu_` and I'm not sure how to get it to understand that.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 377 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTN_1iV1DJ6DwRThrzo:-MU2SqGhDhrNrgjAJ2nI:b-bu91xm) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L377)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Here's another case where a lock annotation would be good.
</blockquote></details>

Updated


<!-- Sent from Reviewable.io -->

2021-02-23 23:35 UTC, markdroth requested changes
This is looking pretty good structurally!  My main noteworthy comments are about the need to clean up the locking semantics in the chttp2 listener code.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 6 files at r4, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321#-:-MUGEayQE-TBit6vZ-Kz:b3plvyv)* status: all files reviewed, 14 unresolved discussions (waiting on @veblush and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 203 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNWuOx7yBktQwFVcB2:-MUFNl7p9BXZiHGKKoV2:bjgud1a) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L203)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I was able to add lock annotations, but i've not been able to fix one remaining warning 

```
src/core/ext/transport/chttp2/server/chttp2_server.cc:555:17: warning: calling function 'StopServingLocked' requires holding mutex 'connection->listener_->mu_' exclusively [-Wthread-safety-precise]
    connection->StopServingLocked();
                ^
src/core/ext/transport/chttp2/server/chttp2_server.cc:555:17: note: found near match 'mu_'

```

Unless I'm making a mistake, I think it does not realize that `mu_` is the same as `connection->listener_->mu_` and I'm not sure how to get it to understand that.
</blockquote></details>

Try using `ABSL_EXCLUSIVE_LOCKS_REQUIRED(&Chttp2ServerListener::mu_)`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 134 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUF3cRGDRZl6Bg49QCc:-MUF3cRGDRZl6Bg49QCd:bje1o7s) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L134)):*
> ```cpp
>   };
> 
>   class ActiveConnection : public RefCounted<ActiveConnection> {
> ```

Can this be `InternallyRefCounted<>`?  I think there's only one external owner, right?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 136 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFgVtD-4o5DMF2ZgW7:-MUFgVtE5kIWxE8RyHNf:bq5bd1h) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L136)):*
> ```cpp
>   class ActiveConnection : public RefCounted<ActiveConnection> {
>    public:
>     class HandshakingState : public RefCounted<HandshakingState> {
> ```

Similar question here: Can this be `InternallyRefCounted<>`?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 174 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG2pqu9edaaa-9K-at:-MUG2pqu9edaaa-9K-au:b41s7ak) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L174)):*
> ```cpp
>     // does not go away before we expect.
>     Chttp2ServerListener* const listener_;
>     RefCountedPtr<HandshakeManager> handshake_mgr_
> ```

It seems strange to have the handshake manager owned by `ActiveConnection` instead of by `HandshakingState`, since the latter is the object that exists while handshaking is in progress.  Instead, I suggest moving this to `HandshakingState` and adding a data member here in `ActiveConnection` that holds a ref to `HandshakingState` for cancellation purposes.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 176 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG1iEH-cB2qzrMLtOd:-MUG1iEH-cB2qzrMLtOe:b-f5x16o) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L176)):*
> ```cpp
>     RefCountedPtr<HandshakeManager> handshake_mgr_
>         ABSL_GUARDED_BY(listener_->mu_);
>     // Guarding with atomics instead of mutex to avoid running into deadlocks.
> ```

What was the deadlock issue that required use of an atomic here?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG759HE04-5P3tWBZY:-MUG759HE04-5P3tWBZZ:b-xq7lkz) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L181)):*
> ```cpp
>     Atomic<grpc_chttp2_transport*> transport_;
>     grpc_closure on_close_;
>     bool is_serving_ ABSL_GUARDED_BY(listener_->mu_) = true;
> ```

Is this field actually needed?  It seems like it will always have the same value as `listener_->is_serving_`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 244 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFd8GG2KkRVEoW4YhH:-MUFd8GG2KkRVEoW4YhI:b54yt5u) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L244)):*
> ```cpp
>                              OnHandshakeDone, this);
>   MutexLock lock(&connection_->listener_->mu_);
>   // If the listener's stopped serving, then shutdown the handshake early.
> ```

I think this check should actually be moved to `Chttp2ServerListener::StartHandshake()`.  If we already know that we're not serving when we accept the connection, we should not bother to create the `ActiveConnection` or `HandshakingState` objects to begin with.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 267 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG477A4T-oDekMDk1U:-MUG477A4T-oDekMDk1V:b-ip98o7) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L267)):*
> ```cpp
>   // Note that we may be called with GRPC_ERROR_NONE when the timer fires
>   // or with an error indicating that the timer system is being shut down.
>   if (error != GRPC_ERROR_CANCELLED) {
> ```

I think this also needs to check `connection_->is_shutdown_` to handle race conditions.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 349 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG6KkhCwOZY39DTcFZ:-MUG6KkhCwOZY39DTcF_:b-jychp2) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L349)):*
> ```cpp
>                             self, grpc_schedule_on_exec_ctx);
>           // Refs helds by OnClose()
>           self->connection_->Ref().release();
> ```

Can we avoid registering the on-close callback in the case where there is no config fetcher?  That way, we won't increase the memory usage for each connection in non-xDS use-cases.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MUFeYLE66bQtkIeca45:bend4vt) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
> ```cpp
>     : listener_(listener) {
>   {
>     MutexLock lock(&listener_->mu_);
> ```

It looks like this code is now acquiring and releasing this same lock 3 times for every incoming connection: once in `Chttp2ServerListener::StartHandshake()`, once here in the `ActiveConnection` ctor, and again in the `HandshakingState` ctor.  This seems pretty sub-optimal.

What was the reason for this change?  When I last reviewed (snapshot 3 in reviewable), we were acquiring it just once.  Can we change this to acquire the lock just once?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 546 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG7qlW9BWX_-SAUfY8:-MUG7qlW9BWX_-SAUfY9:bdaoy6y) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L546)):*
> ```cpp
>   } else {
>     {
>       MutexLock lock(&mu_);
> ```

Here we're acquiring the lock, rel [...]

2021-02-24 20:58 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 14 unresolved discussions (waiting on @markdroth, @veblush, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 174 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG2pqu9edaaa-9K-at:-MUKj_oNDNJ9Hpz5sSBE:b-yuul7) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L174)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It seems strange to have the handshake manager owned by `ActiveConnection` instead of by `HandshakingState`, since the latter is the object that exists while handshaking is in progress.  Instead, I suggest moving this to `HandshakingState` and adding a data member here in `ActiveConnection` that holds a ref to `HandshakingState` for cancellation purposes.
</blockquote></details>

I wanted to avoid adding a data member. So, keeping this in one location made sense.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG759HE04-5P3tWBZY:-MUKk-8k-6Cj4SM9l_I9:b-wd5o2k) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L181)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this field actually needed?  It seems like it will always have the same value as `listener_->is_serving_`.
</blockquote></details>

No, it is possible that the listener was in the NOT SERVING state for a very short time which required all existing connections to go down. When the listener goes back to the SERVING state, we would want to avoid any inconsistent state here from the view of the connection.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 244 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFd8GG2KkRVEoW4YhH:-MUKkPB77m4_LkgMG1JY:b4p53fg) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L244)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this check should actually be moved to `Chttp2ServerListener::StartHandshake()`.  If we already know that we're not serving when we accept the connection, we should not bother to create the `ActiveConnection` or `HandshakingState` objects to begin with.
</blockquote></details>

So, the reason for this is that I wanted to avoid calling `DoHandshake` from within the critical region of `mu_`. We can do a single check at the start of StartHandshake but then it would mean that whole thing would need to be in a single critical region.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 267 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG477A4T-oDekMDk1U:-MUKnQri-wOV5EkFDPq1:b5cz7kl) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L267)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this also needs to check `connection_->is_shutdown_` to handle race conditions.
</blockquote></details>

Which race condition? If you are talking about the transport receiving two separate ops, then the transport is capable of handling it.


<!-- Sent from Reviewable.io -->

2021-02-24 21:15 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 14 unresolved discussions (waiting on @markdroth, @veblush, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MUKt8dI44aDGm5qJLYD:b1u6pkh) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like this code is now acquiring and releasing this same lock 3 times for every incoming connection: once in `Chttp2ServerListener::StartHandshake()`, once here in the `ActiveConnection` ctor, and again in the `HandshakingState` ctor.  This seems pretty sub-optimal.

What was the reason for this change?  When I last reviewed (snapshot 3 in reviewable), we were acquiring it just once.  Can we change this to acquire the lock just once?
</blockquote></details>

I basically wanted to avoid long critical regions especially the region where we start performing a handshake. 


<!-- Sent from Reviewable.io -->

2021-02-25 19:53 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 13 unresolved discussions (waiting on @markdroth, @veblush, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 181 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG759HE04-5P3tWBZY:-MUPjlyu5JgoVqeNGAyc:bdcv6l8) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L181)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

No, it is possible that the listener was in the NOT SERVING state for a very short time which required all existing connections to go down. When the listener goes back to the SERVING state, we would want to avoid any inconsistent state here from the view of the connection.
</blockquote></details>

Good point.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 267 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG477A4T-oDekMDk1U:-MUPjpNHCGwjifsua0z7:b7424ia) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L267)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Which race condition? If you are talking about the transport receiving two separate ops, then the transport is capable of handling it.
</blockquote></details>

I mean the race condition described internally in go/grpc-c-core-closure-slides (problem 4).


<!-- Sent from Reviewable.io -->

2021-02-25 23:10 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 20 of 27 files reviewed, 13 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, @veblush, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 203 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNWuOx7yBktQwFVcB2:-MUQGyRd-ILGCcTmk42D:b-w2x6ri) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L203)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Try using `ABSL_EXCLUSIVE_LOCKS_REQUIRED(&Chttp2ServerListener::mu_)`.
</blockquote></details>

Wow, that worked! What's the logic behind this?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 136 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFgVtD-4o5DMF2ZgW7:-MUQPM1m0-oTV7a-QJtI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L136)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similar question here: Can this be `InternallyRefCounted<>`?
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 267 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG477A4T-oDekMDk1U:-MUPnsLl92TZvNFp4cW7:b-telfa9) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L267)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I mean the race condition described internally in go/grpc-c-core-closure-slides (problem 4).
</blockquote></details>

There doesn't seem to be a race condition here with respect to `connection_->listener_->shutdown_` because the TCP server might not have completed its shutdown yet and we would still want to complete any remaining cleanup operations here.  The cleanup would happen either due to a timeout or due to the `OnReceiveSettings()` callback being invoked
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 349 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG6KkhCwOZY39DTcFZ:-MUQI1RfBX41bFmn3gDF:bnedoca) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L349)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can we avoid registering the on-close callback in the case where there is no config fetcher?  That way, we won't increase the memory usage for each connection in non-xDS use-cases.
</blockquote></details>

I like the idea. Done!
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 575 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUGEI_D4aBDgbHZKKCO:-MUQPIE07O2ybBI-9BPq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L575)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is no longer needed.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 150 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNU_GjAEBhxSXRMOJ3:-MUQPJI-2_h2Fpkb6aNR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/xds/xds_server_config_fetcher.cc#L150)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Sure, but the cases where this log occurs are always a strict subset of the cases where the other one occurs.  This doesn't seem very friendly to users, because it means a single event will cause two different log messages at two different log levels.

How about this:
- Change the log at the top of this function to occur only if `have_resource_` is true.
- Change this log message to use `GPR_ERROR`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6816 at r1](https://reviewable.io/reviews/grpc/grpc/25321#-MTCw_lW-LFX4TJ-vhbW:-MUQPKCC7rWVHf2_fm0y:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf96812c7b76023436f2c679f39957853fb2b73d/test/cpp/end2end/xds_end2end_test.cc#L6816)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That still seems pretty fragile.

Hmm... how about checking to see that the xDS server sees a NACK first, so that we know the client has seen the new resource?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-25 23:15 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 20 of 27 files reviewed, 13 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, and @veblush)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 134 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUF3cRGDRZl6Bg49QCc:-MUQSQ8I0pODXfp_cnM5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L134)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can this be `InternallyRefCounted<>`?  I think there's only one external owner, right?
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 176 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG1iEH-cB2qzrMLtOd:-MUQSRHlBnYrEyPlr1_D:b-v8dw8x) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L176)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What was the deadlock issue that required use of an atomic here?
</blockquote></details>

I actually don't remember. Reverted it to let the tests run on it.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MUQSoHu13kpTwaqE_mw:bqrzlai) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I basically wanted to avoid long critical regions especially the region where we start performing a handshake. 
</blockquote></details>

I moved most of this logic to `HandshakingState()`. I was able to reduce it 2 mainly 
One for copying the channel args before we add the handshakers.
Second for checking whether the listener has stopped serving after we are done initializing the handshakers.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 546 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG7qlW9BWX_-SAUfY8:-MUQTPHW3LbAA90taQ_Q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L546)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Here we're acquiring the lock, releasing it, and then immediately reacquiring it in `StartListening()`.  Can we change this to acquire the lock just once?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-26 06:06 UTC, yashykt commented
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MURtkkZ1hDUzqMOuZYz:bd0yj8v) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I moved most of this logic to `HandshakingState()`. I was able to reduce it 2 mainly 
One for copying the channel args before we add the handshakers.
Second for checking whether the listener has stopped serving after we are done initializing the handshakers.
</blockquote></details>

Some thoughts here after some debugging -
`ActiveConnection` objects need a ref on `tcp_server` so that it can safely access `listener_` for its duration. This ref can only be safely taken in the critical region of `mu_` after verifying that the server has not been shutdown. So, now I have a two-phase approach where -
1) In the first phase, we first enter the critical region, check whether the server has not been shutdown, take a ref to `tcp_server_`, exit the critical region and create the ActiveConnection object (which unrefs the `tcp_server_` object on destruction)
2) The `ActiveConnection` object creates `HandshakingState` which creates the `HandshakeManager` and adds the handshakers. Then, enters the critical region, and only starts the handshake if the server is still listening, and then registers `ActiveConnection` with the list of connections at the listener.


Also, `HandshakingState` needs access to fields from `ActiveConnection` so it makes sense for it to hold a ref to `ActiveConnection`. `ActiveConnection` on the other hand does not need to hold a ref to `HandshakingState`, it just needs a way to know whether handshaking is in progress or not. This can be done with a raw pointer too. For now, I've structured it in a way that `ActiveConnection` and `HandshakingState` both hold OrphanablePtrs to each other but there's no shutdown issue here because the ref held by `ActiveConnection` goes away as soon as handshake is done.


<!-- Sent from Reviewable.io -->

2021-03-02 17:13 UTC, markdroth requested changes
This is getting closer!  I'd still like to see the structure of the objects in the chttp2 listener code get a little cleaner.  Let me know if you want to chat about that.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 7 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321#-:-MUnvJLs0gO7T8cky9T4:b-e4f5hq)* status: all files reviewed, 13 unresolved discussions (waiting on @apolcyn, @jtattermusch, @nicolasnoble, @soheilhy, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 203 at r3](https://reviewable.io/reviews/grpc/grpc/25321#-MTNWuOx7yBktQwFVcB2:-MUkMqtM5Hc1DSWQiyIs:b-6bx3pc) ([raw file](https://github.com/grpc/grpc/blob/d89a71e2291e692cf6515c1f7905498763671c51/src/core/ext/transport/chttp2/server/chttp2_server.cc#L203)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Wow, that worked! What's the logic behind this?
</blockquote></details>

It's actually a bit of an under-specified requirement this way -- the compiler checks that the code is holding that field in *some* `Chttp2ServerListener` object, but not necessarily the one pointed to by `listener_`.  In theory, this could miss problems if we had a bug where we were calling the function while holding the mutex from the wrong `Chttp2ServerListener` instance, but that seems unlikely here, so the slightly weaker check is fine (and is certainly better than no check at all).
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 267 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG477A4T-oDekMDk1U:-MUnu3xg-YeR-2e4M4DD:b-iux430) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L267)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

There doesn't seem to be a race condition here with respect to `connection_->listener_->shutdown_` because the TCP server might not have completed its shutdown yet and we would still want to complete any remaining cleanup operations here.  The cleanup would happen either due to a timeout or due to the `OnReceiveSettings()` callback being invoked
</blockquote></details>

You're right, I guess we're basically handling this by checking `error != GRPC_ERROR_CANCELLED` instead of checking `error == GRPC_ERROR_NONE`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MUnWpHSDhKCmra4HSgS:bi10ll4) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Some thoughts here after some debugging -
`ActiveConnection` objects need a ref on `tcp_server` so that it can safely access `listener_` for its duration. This ref can only be safely taken in the critical region of `mu_` after verifying that the server has not been shutdown. So, now I have a two-phase approach where -
1) In the first phase, we first enter the critical region, check whether the server has not been shutdown, take a ref to `tcp_server_`, exit the critical region and create the ActiveConnection object (which unrefs the `tcp_server_` object on destruction)
2) The `ActiveConnection` object creates `HandshakingState` which creates the `HandshakeManager` and adds the handshakers. Then, enters the critical region, and only starts the handshake if the server is still listening, and then registers `ActiveConnection` with the list of connections at the listener.


Also, `HandshakingState` needs access to fields from `ActiveConnection` so it makes sense for it to hold a ref to `ActiveConnection`. `ActiveConnection` on the other hand does not need to hold a ref to `HandshakingState`, it just needs a way to know whether handshaking is in progress or not. This can be done with a raw pointer too. For now, I've structured it in a way that `ActiveConnection` and `HandshakingState` both hold OrphanablePtrs to each other but there's no shutdown issue here because the ref held by `ActiveConnection` goes away as soon as handshake is done.
</blockquote></details>

Would it be better to acquire the lock only once but have the critical section be longer?  I think we could do that by just holding the lock while we create the handshakers and create the `ActiveConnection` and `HandshakingState` objects.  But I'm honestly not sure which one would actually result in less lock contention on busy servers.  Is there some way to benchmark this?  Maybe @soheilhy has some suggestions here?

In terms of the ref-counting structure, I don't think it makes sense for `HandshakingState` to hold the external ref to `ActiveConnection`, because `HandshakingState` is internal to `ActiveConnection`; it should hold an internal ref instead (i.e., `RefCountedPtr<>` instead of `OrphanablePtr<>`).  The external ref to `ActiveConnection` should be in `Chttp2ServerListener::connections_`, and we can have `ActiveConnection::OnClose()` remove the entry from `connections_` if it's still present at that point.  (You may need to change `connections_` to `std::map<ActiveConnection*, OrphanablePtr<ActiveConnection>>` in order to make erasing elements feasible, since we can't yet use C++14 heterogenous lookups.)
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 546 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG7qlW9BWX_-SAUfY8:-MUnkoAU-1AHM4Pr2oM5:b6tkc74) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L546)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it safe to set `shutdown_` to false before we actually start listening?  Will that cause problems if we acquire the lock in another thread between the time that we release the lock here and the time that we actually call `grpc_tcp_server_start()`?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 172 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkMKFD4ljAOMY5U6Yi:-MUkMKFD4ljAOMY5U6Yj:batkc2g) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L172)):*
> ```cpp
>     ~ActiveConnection() override;
> 
>     void Orphan() override { Unref(); }
> ```

Shouldn't this call `StopServingLocked()` before unreffing?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 259 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkNxmC7kF1bd7hc5vs:-MUkNxmDD00jL-jOOYMN:b5b1c3u) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L259)):*
> ```cpp
>     if (connection_->listener_->shutdown_ ||
>         !connection_->listener_->is_serving_) {
>       handshake_mgr_->Shutdown(
> ```

I don't think we need to call `Shutdown()` here, because we haven't actually called `DoHandshake()` yet.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 279 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkOiWB7orvOaaKnM1y:-MUkOiWB7orvOaaKnM1z:bf21crf) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L279)):*
> ```cpp
>                                        GRPC_RESOURCE_QUOTA_CHANNEL_SIZE)) {
>       gpr_log(GPR_ERROR,
>               "Memory quota exhausted, rejecting connection, no handshaking.");
> ```

In this case, we need to actually shut things down (i.e., run the same code as if `shutting_down` was true above).
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 295 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkPPxYCbB4k2F9eNj6:-MUkPPxYC [...]

2021-03-02 22:15 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 13 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, @soheilhy, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MUoyDQL9rAj6nKt2eME:b-h6hpjq) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
> Would it be better to acquire the lock only once but have the critical section be longer? I think we could do that by just holding the lock while we create the handshakers and create the ActiveConnection and HandshakingState objects. But I'm honestly not sure which one would actually result in less lock contention on busy servers. Is there some way to benchmark this? Maybe @soheilhy has some suggestions here?

I would prefer selecting one approach here while punting the question of benchmarks to the future. If we are optimizing the case of long-lived connections rather than many short-lived connections, then spending much deciding this doesn't make much sense.

> In terms of the ref-counting structure, I don't think it makes sense for HandshakingState to hold the external ref to ActiveConnection, because HandshakingState is internal to ActiveConnection; it should hold an internal ref instead (i.e., RefCountedPtr<> instead of OrphanablePtr<>). The external ref to ActiveConnection should be in Chttp2ServerListener::connections_, and we can have ActiveConnection::OnClose() remove the entry from connections_ if it's still present at that point. (You may need to change connections_ to std::map<ActiveConnection*, OrphanablePtr<ActiveConnection>> in order to make erasing elements feasible, since we can't yet use C++14 heterogenous lookups.)

We don't need `connections_` to hold the external ref to this. `ActiveConnection` is a self-deleting object that goes away when the connection goes away. Changing the ref in `HandshakingState` from `OrphanablePtr` to `RefCountedPtr`
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 172 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkMKFD4ljAOMY5U6Yi:-MUofnV26R1Xh9gkMsag:bj1a2ym) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L172)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Shouldn't this call `StopServingLocked()` before unreffing?
</blockquote></details>

We don't need `StopServingLocked()` to be invoked when `ActiveConnection` gets orphaned normally. It only needs to be invoked when the listener stops serving.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 301 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUnlxCnCnAlqucMpqeL:-MUox7QN4TWXaEDYm0z-:b-7fe9kp) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L301)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this method is necessary.  I think that this shutdown should just happen in `Orphan()`.

Note that there's no reason that we need to pass in a `grpc_error*` here, because it's only ever being passed in as a single value, so we can just hard-code the error in `Orphan()`.
</blockquote></details>

This method is just convenient. We would want to avoid doing it in `Orphan()` since `Orphan()` also needs to `Unref()` and we don't want to `Unref()` from within the critical region. With the current structure, we can perform the entire `StopServingLocked()` for a listener without giving up the lock.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 486 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkQUg--awQVzBo0HBi:-MUoiNdNDJInqtQqpcqH:b3jrn9e) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L486)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this method should be necessary.  Initializing the closure should be done in the `ActiveConnection` ctor, and the refs can be taken in `OnHandshakeDone()` where this is being called.
</blockquote></details>

I had to do this because of a compiler complaint in Windows on the call for `Ref()` from `HandshakingState` due to access restrictions. The error doesn't make sense because `HandshakingState` is a nested class, so I'm guessing it is a compiler error.


<!-- Sent from Reviewable.io -->

2021-03-02 22:21 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 23 of 27 files reviewed, 13 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, @soheilhy, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 259 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkNxmC7kF1bd7hc5vs:-MUp-rQzBfITPbXqAe8L:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L259)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need to call `Shutdown()` here, because we haven't actually called `DoHandshake()` yet.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 279 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkOiWB7orvOaaKnM1y:-MUp0Z8J5jh4tnmUe56q:b-3yi8lq) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L279)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In this case, we need to actually shut things down (i.e., run the same code as if `shutting_down` was true above).
</blockquote></details>

Ah, you are right!
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 295 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkPPxYCbB4k2F9eNj6:-MUp0eV81piNuCzL9YXN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L295)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It seems strange for `HandshakingState` to be unreffing the transport.  Instead, I think only `ActiveConnection` should hold a ref to the transport, and `HandshakingState` should have a ref to `ActiveConnection`.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 401 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUnuWB59JAmw92BHmzK:-MUp0fxi4ZkARDyV0sZU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L401)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as:

```
grpc_closure* on_close = nullptr;
if (self->connection_->listener_->config_fetcher_watcher_ !=
    nullptr) {
  self->connection_->InitializeOnCloseLocked();
  on_close = &self->connection_->on_close_;
}
grpc_chttp2_transport_start_reading(transport, args->read_buffer,
                                    &self->on_receive_settings_, on_close);
```
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 646 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUnkaE62yfSuVWqiY7b:-MUp0hlnBNBVhBhanMdH:b-10a3q7) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L646)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of having `ActiveState` directly hold a ref to `listener_->tcp_server_`, how about changing `Chttp2ServerListener` to provide the same interface as `RefCounted<>`, so that `ActiveConnection` can just hold a `RefCountedPtr<>` to `Chttp2ServerListener` itself?  The `IncrementRefCount()` and `Unref()` methods can actually ref and unref `tcp_server_`.  But this way, it's clearer to the readers of the code that what's really happening is that `ActiveConnection` is holding a ref to the listener.
</blockquote></details>

Done.
We can change it to `InternallyRefCounted()` since `ActiveConnection` is internal to `Chttp2ServerListener`
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 144 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUnsLpL8BR_7r7oXYge:-MUp0rqS4iB2Hh_0nNzi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/xds/xds_server_config_fetcher.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's have this message say something like "; ignoring in favor of existing resource" at the end.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 153 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUnsHdH-jn_Qu22emJM:-MUp0sBJ-hDska41args:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/xds/xds_server_config_fetcher.cc#L153)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please also include the error message in this log.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7021 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUntDZw3A-GKYAVCH-b:-MUp0u5-3ikDd1KhyMQu:b-xt9nss) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/test/cpp/end2end/xds_end2end_test.cc#L7021)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of sleeping, how about sending an RPC here?  That ensures that the polling will happen on the client channel, so that we're not just falling back on the backup poller.
</blockquote></details>

Works!


<!-- Sent from Reviewable.io -->

2021-03-02 22:26 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 23 of 27 files reviewed, 13 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, and @soheilhy)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 546 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG7qlW9BWX_-SAUfY8:-MUp1Q058HbFOYKULU7h:b-gui2k3) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L546)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is it safe to set `shutdown_` to false before we actually start listening?  Will that cause problems if we acquire the lock in another thread between the time that we release the lock here and the time that we actually call `grpc_tcp_server_start()`?
</blockquote></details>

If we are not listening, then we won't be accepting connections and so won't be checking the value of `shutdown_`. One problematic case would be if the applications shuts down the server before we start.

If we want to handle that, we can split this into two fields - `started_` and `shutdown_` where started_ signifies whether we've started listening and `shutdown_` checks whether the application has shut us down.


<!-- Sent from Reviewable.io -->

2021-03-04 19:58 UTC, markdroth requested changes
I'm still not crazy about the structure of the code in `Chttp2ServerListener`, but I'm having trouble coming up with specific suggestions for what to change in the code to make it better.

Stepping back, what I'd really like to see is a structure that has the following properties:
- Every object has clear ownership semantics.  It can be single-owner, `RefCounted<>`, `InternallyRefCounted<>`, or whatever, but it needs to be clear who owns (refs to) what.  (For the `InternallyRefCounted<>` case, that means that internal refs are held only by the object itself or its internal children.)
- Every object properly encapsulates its own state.  When an object is nested inside of another one, it can modify the outer object's state, but we should minimize the cases where this happens -- it should basically be used only when there's no other reasonable way to do it, because the state in question belongs to the outer object.  (For example, it would be fine for `ActiveConnection` to remove itself from `Chttp2ServerListener::connections_` when the connection is closed.  But, as I mentioned in one of my comments, I suspect that having `ActiveConnection` use the top-level mutex in `Chttp2ServerListener` is causing us a lot of complications that we really shouldn't have to be dealing with.)
- Shutting down each object should be done by releasing refs (or orphaning) whenever possible, rather than having a separate method to shut down and then orphan later.  We should avoid having two-phase shutdown, since this tends to complicate the code.  (Two-phase initialization is usually okay though; that tends to cause fewer problems than two-phase shutdown.)

I think it might also help to write down a state diagram for this code, particularly in terms of the state changes that require interactions between the various objects.  I think that might help us find the right set of rules for how the objects interact that will let us more clearly separate things without causing deadlocks or ref-counting headaches.

If it would help, we can discuss this in realtime, maybe using a doc as a virtual whiteboard to put together a structure that makes sense.

Please let me know what you think.  Thanks!

> Reviewed 3 of 4 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321#-:-MUykqo44XHnfFgkm7JI:b-sk8q7w)* status: all files reviewed, 9 unresolved discussions (waiting on @apolcyn, @jtattermusch, @nicolasnoble, @soheilhy, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MUyUgrL8xslKSzMrOfZ:b-c81nq1) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
> I would prefer selecting one approach here while punting the question of benchmarks to the future. If we are optimizing the case of long-lived connections rather than many short-lived connections, then spending much deciding this doesn't make much sense.

I don't think this is a question of long-lived vs. short-lived connections; it's a question about the rate at which new connections come in.  Even if connections are long-lived (which is the case we should be optimizing for), a server with a very large number of clients may still have new connections coming in at a fairly high rate, just because of the distribution of client start times, so I think it's worth optimizing for that case.

In the absence of a benchmark or any intuition from @soheilhy (and please check with him about this), I would prefer to hold the lock just once, because I think it will make the code simpler to understand.

See also my suggestion above about using two different mutexes here.  That might be another way to address this problem, which would actually be a little closer to what you have here now.

> We don't need `connections_` to hold the external ref to this. `ActiveConnection` is a self-deleting object that goes away when the connection goes away. Changing the ref in `HandshakingState` from `OrphanablePtr` to `RefCountedPtr`

If we're not holding an `OrphanablePtr<>` in `connections_`, and we're no longer holding it in `HandshakingState`, then what is holding the external ref to `ActiveConnection`?  How will it ever get orphaned?  And if it's not being orphaned, then how is it ever losing its last ref?  Or do we have a ref-counting bug here somewhere, where we're expecting `Orphan()` to drop a ref that doesn't actually exist, and it's okay because `Orphan()` is never actually being called?

If we really don't need an external ref-holder, then maybe we should make it `RefCounted<>`, and just have its dtor remove it from `connections_`?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 546 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG7qlW9BWX_-SAUfY8:-MUygl-tDyz-2wgt_Pqv:b-nqfilo) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L546)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

If we are not listening, then we won't be accepting connections and so won't be checking the value of `shutdown_`. One problematic case would be if the applications shuts down the server before we start.

If we want to handle that, we can split this into two fields - `started_` and `shutdown_` where started_ signifies whether we've started listening and `shutdown_` checks whether the application has shut us down.
</blockquote></details>

That does sound like a case we need to handle.

Isn't `started_` the same as `is_serving_`?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 172 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkMKFD4ljAOMY5U6Yi:-MUybvI2C_ShYXF2BfrV:bfemyf0) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L172)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

We don't need `StopServingLocked()` to be invoked when `ActiveConnection` gets orphaned normally. It only needs to be invoked when the listener stops serving.
</blockquote></details>

Sure, but it looks to me like `StopServingLocked()` is idempotent -- i.e., if we've already stopped serving, then calling it again is a no-op.  So calling it again if it's already stopped serving shouldn't be a problem.

In general, I think we want a pattern here where resetting the `OrphanablePtr<>` for each object automatically triggers any necessary shutdown for that object.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 301 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUnlxCnCnAlqucMpqeL:-MUycNq33FkrT2ZQ3xYG:belnqdr) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L301)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

This method is just convenient. We would want to avoid doing it in `Orphan()` since `Orphan()` also needs to `Unref()` and we don't want to `Unref()` from within the critical region. With the current structure, we can perform the entire `StopServingLocked()` for a listener without giving up the lock.
</blockquote></details>

Hmm.  This makes me wonder if maybe we should have two different mutexes here, one in `Chttp2ServerListener` and another in `ActiveConnection`.  I think we could avoid deadlocks by saying that we always acquire the `ActiveConnection` lock before the `Chttp2ServerListener` lock.  In `Chttp2ServerListener`, when we stop listening, we can do something like this:

```
std::map<ActiveConnection*, OrphanablePtr<ActiveConnection>> connections;
{
  MutexLock lock(&mu_);
  connections = std::move(connections_);
}
// This drops refs to the ActiveConnection objects after releas [...]

2021-03-04 22:34 UTC, soheilhy reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 9 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MUzMIS7A8H06xGGJozg:b-1q8b9t) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

> I would prefer selecting one approach here while punting the question of benchmarks to the future. If we are optimizing the case of long-lived connections rather than many short-lived connections, then spending much deciding this doesn't make much sense.

I don't think this is a question of long-lived vs. short-lived connections; it's a question about the rate at which new connections come in.  Even if connections are long-lived (which is the case we should be optimizing for), a server with a very large number of clients may still have new connections coming in at a fairly high rate, just because of the distribution of client start times, so I think it's worth optimizing for that case.

In the absence of a benchmark or any intuition from @soheilhy (and please check with him about this), I would prefer to hold the lock just once, because I think it will make the code simpler to understand.

See also my suggestion above about using two different mutexes here.  That might be another way to address this problem, which would actually be a little closer to what you have here now.

> We don't need `connections_` to hold the external ref to this. `ActiveConnection` is a self-deleting object that goes away when the connection goes away. Changing the ref in `HandshakingState` from `OrphanablePtr` to `RefCountedPtr`

If we're not holding an `OrphanablePtr<>` in `connections_`, and we're no longer holding it in `HandshakingState`, then what is holding the external ref to `ActiveConnection`?  How will it ever get orphaned?  And if it's not being orphaned, then how is it ever losing its last ref?  Or do we have a ref-counting bug here somewhere, where we're expecting `Orphan()` to drop a ref that doesn't actually exist, and it's okay because `Orphan()` is never actually being called?

If we really don't need an external ref-holder, then maybe we should make it `RefCounted<>`, and just have its dtor remove it from `connections_`?
</blockquote></details>

Thanks for CCing me. Sorry i didn't notice the question.

It's best not hold any lock when allocating.  The problem is that new can have large delays and can block other threads from making process when they could.  For example, if tcamalloc runs out of cpu-local cache, it will pull from a global pull, and if we hold the lock, we will block other CPUs even when they have buffers available locally.  This happens quite often for low CPU jobs.  We always avoid allocating inside the critical region.  

PS. Related to this topic, this lock will be a bottleneck during connection stress tests. We'll need to shard this state, as part of the connection scaling project.


<!-- Sent from Reviewable.io -->

2021-03-04 23:09 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 9 unresolved discussions (waiting on @apolcyn, @jtattermusch, @nicolasnoble, @soheilhy, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MUzTp3L79Gvj3IpMZky:b-7l5e9j) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
<details><summary><i>Previously, soheilhy (Soheil Hassas Yeganeh) wrote…</i></summary><blockquote>

Thanks for CCing me. Sorry i didn't notice the question.

It's best not hold any lock when allocating.  The problem is that new can have large delays and can block other threads from making process when they could.  For example, if tcamalloc runs out of cpu-local cache, it will pull from a global pull, and if we hold the lock, we will block other CPUs even when they have buffers available locally.  This happens quite often for low CPU jobs.  We always avoid allocating inside the critical region.  

PS. Related to this topic, this lock will be a bottleneck during connection stress tests. We'll need to shard this state, as part of the connection scaling project.
</blockquote></details>

Thanks for the feedback, Soheil!

We should talk about ways that we can avoid allocating while holding the lock.  One possibility would to to have `OnAccept()` allocate `ActiveConnection` and `HandshakingState` and even creating and populating `HandshakeManager` before we grab the lock.  Then we grab the lock to check whether we're accepting connections; if so, we add `ActiveConnection` to `connections_`.  Then we release the lock, and if we weren't accepting connections, we free the objects we just allocated, but if we are accepting connections, we start the handshaking process.

I think the above approach would still work if we use a separate lock in `ActiveConnection`.

Soheil, I haven't heard about the "connection scaling project".  Can you fill me in?


<!-- Sent from Reviewable.io -->

2021-03-05 00:01 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 9 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MUzeMhw5oZkcX3z00By:bbgmxl8) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
> One possibility would to to have OnAccept() allocate ActiveConnection and HandshakingState and even creating and populating HandshakeManager before we grab the lock.

we can definitely allocate `ActiveConnection` and `HandshakingState` earlier, but we cannot populate `HandshakeManager` beforehand since that needs access to the listener's channel args and would hence need to acquire the lock once before populating it.

> If we're not holding an OrphanablePtr<> in connections_, and we're no longer holding it in HandshakingState, then what is holding the external ref to ActiveConnection? How will it ever get orphaned? And if it's not being orphaned, then how is it ever losing its last ref? Or do we have a ref-counting bug here somewhere, where we're expecting Orphan() to drop a ref that doesn't actually exist, and it's okay because Orphan() is never actually being called?

Yeah, the way it is being held right now is that we don't create an OrphanablePtr for `ActiveConnection` at all which thinking about it, makes it very confusing to have an `Orphan()` method. I would prefer making it a `RefCounted`, since we really don't need a ref here.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 546 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG7qlW9BWX_-SAUfY8:-MUzbsGE3jMybt4r54hp:b-qofmzr) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L546)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That does sound like a case we need to handle.

Isn't `started_` the same as `is_serving_`?
</blockquote></details>

No, `is_serving_` and `started_` are different in that, `started_` will be set only once when `grpc_tcp_server_start` has been called while `is_serving_` can be reset multiple times during the lifetime of the server.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 132 at r10](https://reviewable.io/reviews/grpc/grpc/25321#-MUykXpG-lYxA1gk8YvV:-MUz_aQx7r1tm-QkjOpz:biir0x3) ([raw file](https://github.com/grpc/grpc/blob/0b66090a9aa41bfd05ecb5bb71e968f685873f7b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L132)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should probably hold a ref now.
</blockquote></details>

It doesn't need to since we cancel the watch on `Orphan`, unless we fear that the cancellation mechanism might become asynchronous in the future.


<!-- Sent from Reviewable.io -->

2021-03-05 00:18 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 9 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MUzht5A-F6g9anu9xEh:b-jja3bn) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> One possibility would to to have OnAccept() allocate ActiveConnection and HandshakingState and even creating and populating HandshakeManager before we grab the lock.

we can definitely allocate `ActiveConnection` and `HandshakingState` earlier, but we cannot populate `HandshakeManager` beforehand since that needs access to the listener's channel args and would hence need to acquire the lock once before populating it.

> If we're not holding an OrphanablePtr<> in connections_, and we're no longer holding it in HandshakingState, then what is holding the external ref to ActiveConnection? How will it ever get orphaned? And if it's not being orphaned, then how is it ever losing its last ref? Or do we have a ref-counting bug here somewhere, where we're expecting Orphan() to drop a ref that doesn't actually exist, and it's okay because Orphan() is never actually being called?

Yeah, the way it is being held right now is that we don't create an OrphanablePtr for `ActiveConnection` at all which thinking about it, makes it very confusing to have an `Orphan()` method. I would prefer making it a `RefCounted`, since we really don't need a ref here.
</blockquote></details>

To further explain, `HandshakingState` and `OnClose` are the only two owners of refs for `ActiveConnection`. We could add an external ref for `connections_` and use the `OrphanablePtr` as the alternative.  That way we can avoid a `StopServingLocked` method on `ActiveConnection` and use `Orphan` instead to disconnect the transport if needed
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 301 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUnlxCnCnAlqucMpqeL:-MUzgYOG115U-J9UlfKb:b-wu8en9) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L301)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hmm.  This makes me wonder if maybe we should have two different mutexes here, one in `Chttp2ServerListener` and another in `ActiveConnection`.  I think we could avoid deadlocks by saying that we always acquire the `ActiveConnection` lock before the `Chttp2ServerListener` lock.  In `Chttp2ServerListener`, when we stop listening, we can do something like this:

```
std::map<ActiveConnection*, OrphanablePtr<ActiveConnection>> connections;
{
  MutexLock lock(&mu_);
  connections = std::move(connections_);
}
// This drops refs to the ActiveConnection objects after releasing the lock.
connections.clear();
```

WDYT?
</blockquote></details>

Yes, we can do that. The reason I was trying to avoid that is to avoid increasing per connection memory state.


<!-- Sent from Reviewable.io -->

2021-03-05 07:39 UTC, yashykt reviewed
I've made some changes based on all the feedback till now.
So, the current design is like so -
`Chttp2ServerListener` holds a map of `connections_ std::map<ActiveConnection*, OrphanablePtr<ActiveConnection>>` thereby making it the external owner for `ActiveConnection`. This allows us to get rid of the `StopServingLocked()` methods and we can simply empty the `connections_` structure when the listener needs to stop listening, which will result in `Orphan` being called on each `ActiveConnection` which should also trigger cleanup of that connection.

`ActiveConnection` holds the state for each active connection on the listener. It is the creator and the external owner of `HandshakingState` which is responsible for performing the handshake. When `HandshakingState` is done with its handshake, it populates the `transport_` field of `ActiveConnection` with the connected transport and orphans itself by resetting `handshaking_state_` on `ActiveConnection` (signifying that the handshake is done).

The connected transport is setup to invoke `OnClose()` on `ActiveConnection` when it goes away. At this point `ActiveConnection` orphans itself by deleting its entry from `connections_`, if it was not already orphaned.

Also, when `ActiveConnection` is orphaned, it also orphans `HandshakingState` so that the handshake can clean itself up if it was still in progress.

Also to make sure that parent objects outlive their child objects, `HandshakingState` holds an internal ref to`ActiveConnection` which in turn holds an internal ref to `Chttp2ServerListener`.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321#-:-MV0EueR4Nv5N0Sfsn6a:b5ito30)* status: all files reviewed, 9 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, and @yashykt)



<!-- Sent from Reviewable.io -->

2021-03-05 07:51 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 25 of 27 files reviewed, 9 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 172 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkMKFD4ljAOMY5U6Yi:-MV0KF1rDshl9LLb3PS5:b-eoj45q) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L172)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Sure, but it looks to me like `StopServingLocked()` is idempotent -- i.e., if we've already stopped serving, then calling it again is a no-op.  So calling it again if it's already stopped serving shouldn't be a problem.

In general, I think we want a pattern here where resetting the `OrphanablePtr<>` for each object automatically triggers any necessary shutdown for that object.
</blockquote></details>

Removed `StopServingLocked` and replaced it with a design where `Orphan` triggers shutdown.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 646 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUnkaE62yfSuVWqiY7b:-MV0LQq7ElrsH9J8kgSI:bu8jp45) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L646)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yeah, I agree that conceptually, what we want here is `InternallyRefCounted<>` instead of `RefCounted<>`.  I was speaking a little vaguely, because from the perspective of `RefCountedPtr<>`, the two are basically the same.

I see that you've changed `grpc_core::Server::ListnerInterface` to be `InternallyRefCounted<>` instead of `Orphanable`.  That's fine if you want to go that route, although it's actually not what I intended to suggest.  I was thinking of a more custom solution like adding the following to `Chttp2ServerListener`:

```
 private:
  template <typename T>
  friend class RefCountedPtr;

  RefCountedPtr<Chttp2ServerListener> Ref() {
    IncrementRefCount();
    return this;
  }
  void IncrementRefCount() {
    grpc_tcp_server_ref(tcp_server_);
  }
  void Unref() {
    grpc_tcp_server_unref(tcp_server_);
  }
```

That way, it would basically act like `InternallyRefCounted<>`, but instead of having its own atomic, it would just piggy-back on the ref count of the underlying TCP server.

The approach you've taken here is arguably a little cleaner, since the approach I suggested would require additional changes here if we ever have a reason to change `ListenerInterface` to use `InternallyRefCounted<>` in the future (e.g., if some other transport needed it).  But the approach you've taken here does use an additional atomic, and it will require internal changes.

Ultimately, either way is fine with me, so it's totally up to you.
</blockquote></details>

I think simply changing it from `Orphanable` to `InternallyRefCounted` would not require any internal changes, but even if it did, it should be fine. 
Also, I think adding an additional atomic per listener is fine since we don't expect a process to have many listeners.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 643 at r10](https://reviewable.io/reviews/grpc/grpc/25321#-MUyZUDQ5avX62e9kZi_:-MV0M_up2D3dIIY69GUJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0b66090a9aa41bfd05ecb5bb71e968f685873f7b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L643)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of handling this ref manually, let's pass a `RefCountedPtr<>` down to the `ActiveState` ctor, so that the compiler can enforce ownership.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 144 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUnsLpL8BR_7r7oXYge:-MV0KBLW29776lp4TRf6:b-x3gz86) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/xds/xds_server_config_fetcher.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This `l` should be a `;`.
</blockquote></details>

Thanks for catching that!


<!-- Sent from Reviewable.io -->

2021-03-05 09:20 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 25 of 27 files reviewed, 9 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, and @nicolasnoble)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 486 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkQUg--awQVzBo0HBi:-MV0fkpH86Ps0MQk5zbo:bnphve0) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L486)):*
> That seems very odd. Can you show me the code and the error?

Created #25632 to show the compiler issue on windows
https://source.cloud.google.com/results/invocations/6dad388f-ece4-46e9-a4d7-b5f66e66efc8/log


<!-- Sent from Reviewable.io -->

2021-03-08 18:22 UTC, markdroth requested changes
Thanks for making all of those changes!  The overall structure of this code makes a lot more sense now.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 2 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321#-:-MVI3K1w6z3XoZLqkkHp:b7hphiv)* status: all files reviewed, 15 unresolved discussions (waiting on @apolcyn, @jtattermusch, @nicolasnoble, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 402 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUFeYLD35TaNlUJ7OAZ:-MVI-JAc4MXK9FdsCT_V:b-ncp8ou) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L402)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

To further explain, `HandshakingState` and `OnClose` are the only two owners of refs for `ActiveConnection`. We could add an external ref for `connections_` and use the `OrphanablePtr` as the alternative.  That way we can avoid a `StopServingLocked` method on `ActiveConnection` and use `Orphan` instead to disconnect the transport if needed
</blockquote></details>

This looks really good now!
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 546 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG7qlW9BWX_-SAUfY8:-MVHoIOh31EkmvyfjoVF:b799lxd) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L546)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

No, `is_serving_` and `started_` are different in that, `started_` will be set only once when `grpc_tcp_server_start` has been called while `is_serving_` can be reset multiple times during the lifetime of the server.
</blockquote></details>

It looks to me like there's still a race condition between this and `Orphan()`.  Consider the following case:

- Thread 1 invokes `Start()`, which acquires the lock, sets `started_` to true, and releases the lock.
- Thread 2 invokes `Orphan()`, which acquires the lock, sets `shutdown_` to true, releases the lock, and then calls `grpc_tcp_server_shutdown_listeners()` and `grpc_tcp_server_unref()`.
- Thread 1 then calls `grpc_tcp_server_start()`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 486 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkQUg--awQVzBo0HBi:-MVI0SA70Mkisj4GDxcn:bjmwez8) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L486)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> That seems very odd. Can you show me the code and the error?

Created #25632 to show the compiler issue on windows
https://source.cloud.google.com/results/invocations/6dad388f-ece4-46e9-a4d7-b5f66e66efc8/log
</blockquote></details>

Yeah, that does look like a compiler bug of some sort.

However, now that we're explicitly exposing the `Ref()` method with the `using` statement above, I think this should no longer be an issue.  So let's go ahead and get rid of this method.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 646 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUnkaE62yfSuVWqiY7b:-MVI2VfTErU6oMfjXwTL:bcx2ghm) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L646)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I think simply changing it from `Orphanable` to `InternallyRefCounted` would not require any internal changes, but even if it did, it should be fine. 
Also, I think adding an additional atomic per listener is fine since we don't expect a process to have many listeners.
</blockquote></details>

I think it will actually require internal changes, since we'll need to change the `Orphan()` method of existing `ListenerInterface` implementations to call `Unref()`.

But I'm fine with this.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 111 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVHmTav5ugEtiUszukh:-MVHmTav5ugEtiUszuki:b-lu30pk) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L111)):*
> ```cpp
>         }
>         {
>           MutexLock lock(&listener_->channel_args_mu_);
> ```

Can we wait until after we release `mu_` to acquire `channel_args_mu_`, just to minimize lock contention?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 167 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVI-tXC-RJxmsOADS4m:-MVHnPXp7mjtOF6-OkZL:bpebuwm) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L167)):*
> ```cpp
>       void Start(grpc_endpoint* endpoint, grpc_channel_args* args);
> 
>       using InternallyRefCounted<HandshakingState>::Ref;
> ```

Please add a comment explaining that this is needed for grabbing the ref externally in `ActiveConnection::Start()`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 195 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVHlovJ-PZ989bDpjim:-MVHlovJ-PZ989bDpjin:b-s0ynm2) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L195)):*
> ```cpp
>     void Start(grpc_endpoint* endpoint, grpc_channel_args* args);
> 
>     using InternallyRefCounted<ActiveConnection>::Ref;
> ```

Please add a comment that this is needed for grabbing the ref externally in `Chttp2ServerListener::OnAccept()`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 210 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MV41Ik76u0mpKxznzY6:-MV41Ik76u0mpKxznzY7:bemyp6e) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L210)):*
> ```cpp
>     grpc_chttp2_transport* transport_ ABSL_GUARDED_BY(&mu_) = nullptr;
>     grpc_closure on_close_;
>     bool is_serving_ ABSL_GUARDED_BY(&mu_) = true;
> ```

I think this can be called `shutdown_`,  because the connection will never exit this state once it occurs.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 230 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MV40CQjCO9AsCpXaBis:-MV40CQk2xVXOkUasCTv:b-tjwwmk) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L230)):*
> ```cpp
>   Chttp2ServerArgsModifier args_modifier_;
>   ConfigFetcherWatcher* config_fetcher_watcher_ = nullptr;
>   Mutex channel_args_mu_ ACQUIRED_AFTER(&mu_);
> ```

I'd prefer to not acquire the two mutexes at the same time if possible.  The only place I see where this is done is in `UpdateConfig()` above, where I suggested changing the code to avoid that overlap.   If we do that, then this annotation can go away.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 236 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MV40QsWD1SYghb59iD9:-MV40QsWD1SYghb59iDA:b9p04if) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L236)):*
> ```cpp
>   bool started_ ABSL_GUARDED_BY(mu_) = false;
>   // Signals whether grpc_tcp_server_start() is in progress.
>   bool start_in_progress_ ABSL_GUARDED_BY(mu_) = false;
> ```

Do we need both `started_` and `start_in_progress_`?  When are they set differently, and does anything need to know when they are set differently?

Maybe we could assume the start is in progress if `is_serving_` is true but `started_` is not yet true?
___
*[src/core/ext/transport/chttp2/serve [...]

2021-03-08 20:00 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: all files reviewed, 15 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, @nicolasnoble, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 546 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG7qlW9BWX_-SAUfY8:-MVI6-BBD6uTa-AR9fjB:b-u3w1p0) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L546)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks to me like there's still a race condition between this and `Orphan()`.  Consider the following case:

- Thread 1 invokes `Start()`, which acquires the lock, sets `started_` to true, and releases the lock.
- Thread 2 invokes `Orphan()`, which acquires the lock, sets `shutdown_` to true, releases the lock, and then calls `grpc_tcp_server_shutdown_listeners()` and `grpc_tcp_server_unref()`.
- Thread 1 then calls `grpc_tcp_server_start()`.
</blockquote></details>

Chttp2ServerListener::Start() happens as part of `grpc_server_start()` which happens as part of `ServerBuilder::BuildAndStart`. In other words, we don't expect Shutdown to be called before Start returns.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 111 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVHmTav5ugEtiUszukh:-MVIFe-P-XBaTaXnYSas:b-c5s6nm) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L111)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can we wait until after we release `mu_` to acquire `channel_args_mu_`, just to minimize lock contention?
</blockquote></details>

That can cause races where the listener state is different from the channel_args state.
Consider the case where the listener has started accepting connections i.e. `tcp_server_start` has been called but it has stopped serving due to the resource being deleted. In this case, if it receives a good update and if we receive a new connection before we update the channel args, we would be starting the connection with older channel args..

But, I think if we modify channel args before updating the listener state, we should be fine.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 236 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MV40QsWD1SYghb59iD9:-MVIIDjD2P1x55Rz1a0u:b-8uafbv) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L236)):*
>`Do we need both started_ and start_in_progress_? When are they set differently, and does anything need to know when they are set differently?`

`started` is used just in `UpdateConfig` to know whether we need to start listening or not. `start_in_progress` is used to denote the time where we are about to start, i.e., calling `tcp_server_start`.

> Maybe we could assume the start is in progress if is_serving_ is true but started_ is not yet true?
Yes, we can if we want. Since this is state on the listener on though, I didn't really care about adding another bool. Done
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 499 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVI0vTx6gVAbWwPsrhO:-MVIL97_CAW59YALEKdR:b-kwkri8) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L499)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Would it be more performant to grab the connection lock first, since it's less likely to be contended?
</blockquote></details>

I'm not sure which is more performant, but the common approach seems to be to grab the higher lock first. (For example https://g3doc.corp.google.com/borg/borglet/g3doc/developers/containermgr_locks.md#lock-ordering)
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 647 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVI2N0aCvyTVM4MvkRR:-MVINjoC8Exnz1kfDBc_:bndul05) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L647)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This variable isn't necessary, because you can instead check whether `connection` is null.
</blockquote></details>

Done, but code readability took a hit with that, since this is not immediately obvious.


<!-- Sent from Reviewable.io -->

2021-03-08 20:01 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 26 of 27 files reviewed, 15 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, and @nicolasnoble)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 486 at r8](https://reviewable.io/reviews/grpc/grpc/25321#-MUkQUg--awQVzBo0HBi:-MVIQS0t-O-eKCvfmKtK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/53500a85cab68870af91e145443f19b2482356aa/src/core/ext/transport/chttp2/server/chttp2_server.cc#L486)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yeah, that does look like a compiler bug of some sort.

However, now that we're explicitly exposing the `Ref()` method with the `using` statement above, I think this should no longer be an issue.  So let's go ahead and get rid of this method.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 167 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVI-tXC-RJxmsOADS4m:-MVIQZF2BNT26GWB3Vo-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L167)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment explaining that this is needed for grabbing the ref externally in `ActiveConnection::Start()`.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 195 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVHlovJ-PZ989bDpjim:-MVIQIwdA_VC1CY5kWbN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L195)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment that this is needed for grabbing the ref externally in `Chttp2ServerListener::OnAccept()`.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 210 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MV41Ik76u0mpKxznzY6:-MVIQLP02xX48JPX895u:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L210)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can be called `shutdown_`,  because the connection will never exit this state once it occurs.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 230 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MV40CQjCO9AsCpXaBis:-MVIQMLLBTkoMbdyeQ39:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L230)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'd prefer to not acquire the two mutexes at the same time if possible.  The only place I see where this is done is in `UpdateConfig()` above, where I suggested changing the code to avoid that overlap.   If we do that, then this annotation can go away.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 236 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MV40QsWD1SYghb59iD9:-MVIQNEhDZScuk-yPQtj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L236)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

>`Do we need both started_ and start_in_progress_? When are they set differently, and does anything need to know when they are set differently?`

`started` is used just in `UpdateConfig` to know whether we need to start listening or not. `start_in_progress` is used to denote the time where we are about to start, i.e., calling `tcp_server_start`.

> Maybe we could assume the start is in progress if is_serving_ is true but started_ is not yet true?
Yes, we can if we want. Since this is state on the listener on though, I didn't really care about adding another bool. Done
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 367 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MV41x8c1KE_QmahkWzE:-MVIQP4K-VU-yEpqOrKt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L367)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I would move this back down to line 386, since it isn't needed before then.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 425 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVHxIqy9illsFZcokck:-MVIQPzbCXIhHcerKEdx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L425)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

For efficiency, I suggest writing this as:

```
auto it = self->connection_->listener_->connections_.find(self->connection_.get());
if (it != self->connection_->listener_->connections_.end()) {
  connection = std::move(it->second);
  self->connection_->listener_->connections_.erase(it);
}
```

This way, we're only doing the map lookup once instead of twice.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 503 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVI10gB9sa-dQCzIOQU:-MVIQUmv46QbPy8Nly_K:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L503)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similar to my comment on line 425 above, suggest rewriting this to avoid doing the map lookup twice.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 644 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVI1QaxD6oPWpFVrlZs:-MVIQW242uuARyE1MB2S:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L644)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can just use `auto` here, since the type is obvious from the RHS.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 666 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVI1aLg7vuY_9t8eybz:-MVIQXU137m442sh4fwu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L666)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This ref can be taken before acquiring the lock.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-09 00:49 UTC, markdroth approved these changes
This looks fabulous!

Remaining comments are all minor, so I'll go ahead and approve.

Thanks for doing this!

> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321#-:-MVJSFuw2VDiC5_kXRv2:brnwnai)* status: all files reviewed, 4 unresolved discussions (waiting on @apolcyn, @jtattermusch, @nicolasnoble, and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 546 at r6](https://reviewable.io/reviews/grpc/grpc/25321#-MUG7qlW9BWX_-SAUfY8:-MVJL-CVD4MHVMwWiUSr:b-i2wr8k) ([raw file](https://github.com/grpc/grpc/blob/f1d9eacd8212a25c54ac3a189d2f9aace0eda09c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L546)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Chttp2ServerListener::Start() happens as part of `grpc_server_start()` which happens as part of `ServerBuilder::BuildAndStart`. In other words, we don't expect Shutdown to be called before Start returns.
</blockquote></details>

Ah, you're right!  Okay, then this seems fine.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 499 at r12](https://reviewable.io/reviews/grpc/grpc/25321#-MVI0vTx6gVAbWwPsrhO:-MVJKC0f-HvWmTh_6AkP:b-oh1ism) ([raw file](https://github.com/grpc/grpc/blob/bf55fd7bf8158bd01f47f004f702b59db0abdb90/src/core/ext/transport/chttp2/server/chttp2_server.cc#L499)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I'm not sure which is more performant, but the common approach seems to be to grab the higher lock first. (For example https://g3doc.corp.google.com/borg/borglet/g3doc/developers/containermgr_locks.md#lock-ordering)
</blockquote></details>

That page looks like it's just describing the rule established for that particular piece of code, not a general style rule.

Logically, if there is contention when acquiring the second lock, then we're going to hold the first lock longer than we need to.  It seems better to hold the connection lock longer than we need to than to hold the top-level lock longer than we need to, since it's better to hold up work for an individual connection than it is to hold up work for *all* connections.  That's why I was thinking the opposite order would be more performant.

It might be a good idea to check with @soheilhy about this too.  But I'll go ahead and resolve, since this is something we can easily change later.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 96 at r13](https://reviewable.io/reviews/grpc/grpc/25321#-MVJFMft2lUQWxT_8-kb:-MVJFMft2lUQWxT_8-kc:b-vvva8j) ([raw file](https://github.com/grpc/grpc/blob/d2af91925cccdf0b7bbf1026ec8dce23eb881149/src/core/ext/transport/chttp2/server/chttp2_server.cc#L96)):*
> ```cpp
>         : listener_(std::move(listener)) {}
> 
>     void UpdateConfig(grpc_channel_args* args) override {
> ```

The implementation of these methods is now long enough that it would probably make sense to just declare them here and then define them below, just like we're doing for the other classes.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 176 at r13](https://reviewable.io/reviews/grpc/grpc/25321#-MVJLlsG72fgEaJWhbtH:-MVJLlsG72fgEaJWhbtI:b-v7bccz) ([raw file](https://github.com/grpc/grpc/blob/d2af91925cccdf0b7bbf1026ec8dce23eb881149/src/core/ext/transport/chttp2/server/chttp2_server.cc#L176)):*
> ```cpp
>       grpc_pollset* const accepting_pollset_;
>       grpc_tcp_server_acceptor* const acceptor_;
>       RefCountedPtr<HandshakeManager> handshake_mgr_;
> ```

Please add appropriate lock annotations for these data members.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 390 at r13](https://reviewable.io/reviews/grpc/grpc/25321#-MVJJmM84WYBRTIBynmu:-MVJJmM84WYBRTIBynmv:bd2lw7f) ([raw file](https://github.com/grpc/grpc/blob/d2af91925cccdf0b7bbf1026ec8dce23eb881149/src/core/ext/transport/chttp2/server/chttp2_server.cc#L390)):*
> ```cpp
>             // Refs helds by OnClose()
>             self->connection_->Ref().release();
>             GRPC_CLOSURE_INIT(
> ```

This should move to the `ActiveConnection` ctor.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 654 at r13](https://reviewable.io/reviews/grpc/grpc/25321#-MVJL9cd126FmCr6bu4N:-MVJL9cd126FmCr6bu4O:b-756it7) ([raw file](https://github.com/grpc/grpc/blob/d2af91925cccdf0b7bbf1026ec8dce23eb881149/src/core/ext/transport/chttp2/server/chttp2_server.cc#L654)):*
> ```cpp
>   {
>     MutexLock lock(&self->mu_);
>     // Shutdown the the conncetion if listener's stopped serving.
> ```

s/conncetion/connection/


<!-- Sent from Reviewable.io -->

2021-03-09 05:43 UTC, yashykt commented
Interop seems to be failing on master due to `build_docker_dart`

2021-03-09 05:44 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321)* status: 22 of 27 files reviewed, 4 unresolved discussions (waiting on @apolcyn, @jtattermusch, @markdroth, and @nicolasnoble)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 96 at r13](https://reviewable.io/reviews/grpc/grpc/25321#-MVJFMft2lUQWxT_8-kb:-MVKVmDk1WyJAkbfJj8j:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d2af91925cccdf0b7bbf1026ec8dce23eb881149/src/core/ext/transport/chttp2/server/chttp2_server.cc#L96)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The implementation of these methods is now long enough that it would probably make sense to just declare them here and then define them below, just like we're doing for the other classes.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 176 at r13](https://reviewable.io/reviews/grpc/grpc/25321#-MVJLlsG72fgEaJWhbtH:-MVKVmu4DSZ1qIq-nc9h:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d2af91925cccdf0b7bbf1026ec8dce23eb881149/src/core/ext/transport/chttp2/server/chttp2_server.cc#L176)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add appropriate lock annotations for these data members.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 390 at r13](https://reviewable.io/reviews/grpc/grpc/25321#-MVJJmM84WYBRTIBynmu:-MVKVnoh91bmXsDQkxXM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d2af91925cccdf0b7bbf1026ec8dce23eb881149/src/core/ext/transport/chttp2/server/chttp2_server.cc#L390)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should move to the `ActiveConnection` ctor.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 654 at r13](https://reviewable.io/reviews/grpc/grpc/25321#-MVJL9cd126FmCr6bu4N:-MVKVqO5ENkU0edK_0gl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d2af91925cccdf0b7bbf1026ec8dce23eb881149/src/core/ext/transport/chttp2/server/chttp2_server.cc#L654)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/conncetion/connection/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-09 05:46 UTC, yashykt commented
Thanks for reviewing!

2021-03-09 05:47 UTC, merged

2021-03-09 17:03 UTC, markdroth reviewed
One quick comment to address in a follow-up PR.  Thanks!

> Reviewed 5 of 5 files at r14.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25321#-:-MVMwRaS8b8LPcbzojpf:b-1j8rin)* status: all files reviewed, 1 unresolved discussion

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 303 at r14](https://reviewable.io/reviews/grpc/grpc/25321#-MVMvsucAPgAmy3ZQWlJ:-MVMvsucAPgAmy3ZQWlK:b-q3154z) ([raw file](https://github.com/grpc/grpc/blob/1db566c4be32c4deb6dc7b41e7f28792a42701f2/src/core/ext/transport/chttp2/server/chttp2_server.cc#L303)):*
> ```cpp
> void Chttp2ServerListener::ActiveConnection::HandshakingState::Start(
>     grpc_endpoint* endpoint,
>     grpc_channel_args* args) ABSL_NO_THREAD_SAFETY_ANALYSIS {
> ```

I'm not too keen on disabling the lock analaysis.  Let's just go ahead and acquire the connection lock here.  Nothing else in the connection is running yet at this point, so the lock should not be contended, so I don't think this will affect performance that much.


<!-- Sent from Reviewable.io -->

2021-03-14 21:51 UTC, yashykt commented
This PR was reverted because it introduced an issue where transports were not completely cleaned up until shutdown for servers when no server config is set.