SDK authorization policy translator.
grpc/grpc pull request #25361
Opened 2021-02-05 13:47 UTC by ashithasantosh

Translates SDK authorization policy to Envoy RBAC protos (represented as structs).

[PR is WIP]

2021-02-12 22:42 UTC, markdroth requested changes
This looks like a great start!

Please let me know if you have any questions.  Thanks!

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25361#-:-MTNPDQq9YdZIsbD6KIh:b9kv8rc)* status: all files reviewed, 45 unresolved discussions (waiting on @ashithasantosh and @jiangtaoli2016)

___
*[BUILD, line 1963 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMHZn0-ZiGN-40WWe8:-MTMHZn0-ZiGN-40WWe9:bdixkbn) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/BUILD#L1963)):*
> ```Starlark
> )
> 
> grpc_cc_library(
> ```

Please add a comment here that this target pulls in a dependency on RE2 and should not be linked into grpc by default for binary-size reasons.

Same comment on the `grpc_rbac_engine` and `grpc_authorization_provider` targets.
___
*[BUILD, line 1966 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMEYMhD9dtPPImDIQG:-MTMEYMhD9dtPPImDIQH:by3gf5r) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/BUILD#L1966)):*
> ```Starlark
>     name = "grpc_matchers",
>     srcs = [
>         "src/core/lib/security/authorization/matchers.cc",
> ```

These matchers aren't actually specific to authz (as evidenced by the fact that they're also used by the xDS code), so let's put this library in its own directory in src/core/lib/matchers.
___
*[BUILD, line 1984 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMImsq3-3wVtjQVStS:-MTMImsq3-3wVtjQVStT:b7vpa8l) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/BUILD#L1984)):*
> ```Starlark
>     srcs = [
>         "src/core/lib/security/authorization/evaluate_args.cc",
>         "src/core/lib/security/authorization/rbac.cc",
> ```

Suggest renaming rbac.{h,cc} to rbac_policy.{h,cc}, so that it's clear that this is the policy type, not the implementation.
___
*[src/core/lib/security/authorization/rbac.h, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMNzU43qYlKnX1pKgP:-MTMNzU43qYlKnX1pKgQ:bey0lob) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac.h#L30)):*
> ```objc
> struct Rbac {
>   struct CidrRange {
>     CidrRange() = default;
> ```

Suggest also adding a ctor that takes the two parameters, so that it can be constructed and initialized at the same time:

```
CidrRange(std::string address_prefix, uint32_t prefix_len)
    : address_prefix(std::move(address_prefix)), prefix_len(prefix_len) {}
```

Same thing for all of these structs.
___
*[src/core/lib/security/authorization/rbac.cc, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMFmJ11oHRxEWwArih:-MTMFmJ11oHRxEWwArii:b-gldigy) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac.cc#L41)):*
> ```cpp
>   contents.push_back(absl::StrFormat(
>       "Rbac action=%s{", action == Rbac::Action::ALLOW ? "Allow" : "Deny"));
>   for (auto it = policies.begin(); it != policies.end(); it++) {
> ```

`for (const auto& p : policies) {`
___
*[src/core/lib/security/authorization/rbac.cc, line 129 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMJHjVAg0fpcwrvuHO:-MTMJHjVAg0fpcwrvuHP:b-hrjn2r) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac.cc#L129)):*
> ```cpp
>       contents.reserve(permissions.size());
>       for (const auto& permission : permissions) {
>         contents.push_back(absl::StrFormat("%s", permission->ToString()));
> ```

No need for `absl::StrFormat()` here; just use `permission->ToString()` directly.
___
*[src/core/lib/security/authorization/rbac_translator.h, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMJqr14KGRKIb6BdPS:-MTMJqr14KGRKIb6BdPT:b3c7to6) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.h#L34)):*
> ```objc
> // failure.
> // authz_policy: Authorization Policy string in JSON format.
> absl::StatusOr<std::unique_ptr<RbacPolicies>> GenerateRbacPolicies(
> ```

Why use `unique_ptr<>` here rather than returning by value?
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMtvHS5gbuB-aVmzx9:-MTMOiRk4aqOzfT_AG-D:b-pkchjq) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L29)):*
> ```cpp
> namespace {
> 
> std::string GetMatcherType(const std::string& value,
> ```

Please use `absl::string_view` for both the return value and the `value` parameter, to avoid unnecessary copies.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMK5C37qPzgXV2JTVS:-MTMK5C37qPzgXV2JTVT:b-ar83d6) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L32)):*
> ```cpp
>                            StringMatcher::Type* type) {
>   if (value == "*") {
>     *type = StringMatcher::Type::SAFE_REGEX;
> ```

I think it would be more efficient to use `PREFIX` with a value of "" here.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 45 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMQdvC4d7SsGoeYWjR:-MTMLusm51Xv0zXZoOMo:b-jx3ynm) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L45)):*
> ```cpp
> }
> 
> absl::StatusOr<StringMatcher> GetStringMatcher(const std::string value) {
> ```

Please use `absl::string_view` for the parameter.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMu4Pn8OsCbM-G6qea:-MTMu4Pn8OsCbM-G6qeb:b-2uqfdc) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L48)):*
> ```cpp
>   StringMatcher::Type type;
>   std::string matcher = GetMatcherType(value, &type);
>   return StringMatcher::Create(type, matcher);
> ```

While we're at it, it would probably make sense to change the matcher factory methods and ctors to use `absl::string_view` instead of `const std::string&`.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMuHT1DQpNz4Nsrbsh:-MTMuHT1DQpNz4Nsrbsi:bjmr6x4) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L51)):*
> ```cpp
> }
> 
> absl::StatusOr<HeaderMatcher> GetHeaderMatcher(const std::string name,
> ```

Parameters should be `absl::string_view`.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMLMLZ4nS_S2pKO3Ke:-MTMLMLZ4nS_S2pKO3Kf:b1c5g6j) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L59)):*
> ```cpp
> }
> 
> absl::Status ParsePrincipalsArray(Json* json, Rbac::Principal* principals) {
> ```

How about having this return `absl::StatusOr<Rbac::Principal>`, rather than returning the principle via the parameter?
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMMW2z9uJzmQIZczeg:-MTMMW2z9uJzmQIZczeh:b-dvgzvl) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L59)):*
> ```cpp
> }
> 
> absl::Status ParsePrincipalsArray(Json* json, Rbac::Principal* principals) {
> ```

The `Json` object should be passed in as a const reference instead of a mutable pointer, since this function is not modifying it.

Same thing for all of [...]

2021-02-13 00:41 UTC, jiangtaoli2016 commented
@ZhenLian Could you please also review this PR?

2021-02-19 23:18 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25361)* status: 2 of 26 files reviewed, 45 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[BUILD, line 1963 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMHZn0-ZiGN-40WWe8:-MTO4qdC3la95IUEuGM9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/BUILD#L1963)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment here that this target pulls in a dependency on RE2 and should not be linked into grpc by default for binary-size reasons.

Same comment on the `grpc_rbac_engine` and `grpc_authorization_provider` targets.
</blockquote></details>

Done.
___
*[BUILD, line 1966 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMEYMhD9dtPPImDIQG:-MTO3eeFCDs-93CGgAOZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/BUILD#L1966)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These matchers aren't actually specific to authz (as evidenced by the fact that they're also used by the xDS code), so let's put this library in its own directory in src/core/lib/matchers.
</blockquote></details>

Done.
___
*[BUILD, line 1984 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMImsq3-3wVtjQVStS:-MTO5W8SASiWvbh7Pzs6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/BUILD#L1984)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest renaming rbac.{h,cc} to rbac_policy.{h,cc}, so that it's clear that this is the policy type, not the implementation.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac.h, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMNzU43qYlKnX1pKgP:-MTt4unoACvkLqZtCnXZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest also adding a ctor that takes the two parameters, so that it can be constructed and initialized at the same time:

```
CidrRange(std::string address_prefix, uint32_t prefix_len)
    : address_prefix(std::move(address_prefix)), prefix_len(prefix_len) {}
```

Same thing for all of these structs.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.h, line 34 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMJqr14KGRKIb6BdPS:-MTT02_32Vwz9Vf6w5Td:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.h#L34)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why use `unique_ptr<>` here rather than returning by value?
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMtvHS5gbuB-aVmzx9:-MTOInLT8uAYz7VHt0N4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `absl::string_view` for both the return value and the `value` parameter, to avoid unnecessary copies.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMK5C37qPzgXV2JTVS:-MTXUoUd4MXpGCOh_beX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think it would be more efficient to use `PREFIX` with a value of "" here.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 45 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMQdvC4d7SsGoeYWjR:-MTOJGFS5PaWwf6b_DDN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L45)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `absl::string_view` for the parameter.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMu4Pn8OsCbM-G6qea:-MTOK3xK-mW2RdJqJHyu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

While we're at it, it would probably make sense to change the matcher factory methods and ctors to use `absl::string_view` instead of `const std::string&`.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMuHT1DQpNz4Nsrbsh:-MTOK4e2CVvMqlEbpniY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Parameters should be `absl::string_view`.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMLMLZ4nS_S2pKO3Ke:-MTg2uQ0COJ7AKy5RyHk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about having this return `absl::StatusOr<Rbac::Principal>`, rather than returning the principle via the parameter?
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMMW2z9uJzmQIZczeg:-MTT0AdIDXVLSm7suK-c:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `Json` object should be passed in as a const reference instead of a mutable pointer, since this function is not modifying it.

Same thing for all of these parsing functions.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMKUh-4IFun130Gxph:-MTg2wii2YQpoSp722E_:b-54snbz) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can use `auto` here, since the type is obvious from the RHS.
</blockquote></details>

Acknowledged.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 63 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMNMkG16WJOT233llV:-MTOMMj60IFigtRGKUs7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L63)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Use `array_value()` instead of `mutable_array()`, since we're not actually modifying the value here.

Same thing throughout.
</blockquote></details>

Done.
___
*[src/core/lib/sec [...]

2021-02-24 07:23 UTC, ZhenLian requested changes
The overall structure looks good to me! Just made some nit comments. 

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25361#-:-MUHuQvoDPpCvc04L6-5:b-t25xg7)* status: 2 of 26 files reviewed, 48 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @markdroth)

___
*[src/core/lib/security/authorization/rbac_policy.h, line 28 at r2](https://reviewable.io/reviews/grpc/grpc/25361#-MUGV1Yx8_hEpoByxk80:-MUGV1Yx8_hEpoByxk81:bvfltn6) ([raw file](https://github.com/grpc/grpc/blob/87a3a8b31e49bd2af2d403535466c18682e4b9f7/src/core/lib/security/authorization/rbac_policy.h#L28)):*
> ```objc
> // Represents Envoy RBAC Proto. [See
> // https://github.com/envoyproxy/envoy/blob/release/v1.17/api/envoy/config/rbac/v3/rbac.proto]
> struct Rbac {
> ```

Can I know the reason why we are using struct(instead of class, etc) to represent Envoy RBAC proto? 

And one thing(irrelevant to this) just came to my mind: what is the story for supporting other wrap languages other than C++? We just don't care about them at this moment?
___
*[src/core/lib/security/authorization/rbac_policy.h, line 61 at r2](https://reviewable.io/reviews/grpc/grpc/25361#-MUGXYQW8IhTs7mFL--S:-MUGXYQX1GurL8ueqQSx:bytz74n) ([raw file](https://github.com/grpc/grpc/blob/87a3a8b31e49bd2af2d403535466c18682e4b9f7/src/core/lib/security/authorization/rbac_policy.h#L61)):*
> ```objc
> 
>     Permission() = default;
>     // For AND/OR RuleType.
> ```

Do we have sanity checks for callers who mistakenly pass in wrong `RuleType`? Same for other constructors...
___
*[src/core/lib/security/authorization/rbac_policy.h, line 157 at r2](https://reviewable.io/reviews/grpc/grpc/25361#-MUGUg9V8Yt-WA96ptqm:-MUGUg9WAX9wZOdJ7bVD:btunfu5) ([raw file](https://github.com/grpc/grpc/blob/87a3a8b31e49bd2af2d403535466c18682e4b9f7/src/core/lib/security/authorization/rbac_policy.h#L157)):*
> ```objc
> }  // namespace grpc_core
> 
> #endif /* GRPC_CORE_LIB_SECURITY_AUTHORIZATION_RBAC_POLICY_H */
> ```

Nit: what is the two little red boxes at the end of the line? Does it indicate there is no new line at the end of this file? Same thing throughout...


<!-- Sent from Reviewable.io -->

2021-02-25 09:09 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25361)* status: 2 of 26 files reviewed, 47 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/rbac_policy.h, line 28 at r2](https://reviewable.io/reviews/grpc/grpc/25361#-MUGV1Yx8_hEpoByxk80:-MUNB3UQ4jYcqE_jZhEs:b-wo5jq9) ([raw file](https://github.com/grpc/grpc/blob/87a3a8b31e49bd2af2d403535466c18682e4b9f7/src/core/lib/security/authorization/rbac_policy.h#L28)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Can I know the reason why we are using struct(instead of class, etc) to represent Envoy RBAC proto? 

And one thing(irrelevant to this) just came to my mind: what is the story for supporting other wrap languages other than C++? We just don't care about them at this moment?
</blockquote></details>

I used a struct here, since Rbac is a passive object and to keep the members public, else we will need to add getters for each member field. 
Based on  go/cstyle#Structs_vs._Classes, since there is relationship between fields, it would make sense to use a Class here instead.

I haven't looked into other wrapped languages (mostly in Q4). Currently the focus is C++. 
___
*[src/core/lib/security/authorization/rbac_policy.h, line 61 at r2](https://reviewable.io/reviews/grpc/grpc/25361#-MUGXYQW8IhTs7mFL--S:-MULq5Za3KdV7J0EANpg:bk6yr8n) ([raw file](https://github.com/grpc/grpc/blob/87a3a8b31e49bd2af2d403535466c18682e4b9f7/src/core/lib/security/authorization/rbac_policy.h#L61)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Do we have sanity checks for callers who mistakenly pass in wrong `RuleType`? Same for other constructors...
</blockquote></details>

I had considered this, but felt it does not add much value. Correct me if I am wrong.
Assume, the caller used HEADER instead of PATH. In the PATH/REQ_SERVER_NAME ctor seeing this we don't initialize type and string_matcher. Now, type for this Permission would be the default value AND, which again would be incorrect. We could add UNKNOWN type.
Without the sanity checks, now if the same happened. We would have HEADER type with string_matcher value, which is incorrect. During any further processing (like in RBAC Engine) for this permission, we will end up looking into header_matcher based on type.

Since the users of this struct are going to be xds and sdk authorization path, we could make it the caller's responsibility to use the right ctors for initialization. Or use factory functions, which could return an error if the rule type is wrong.


<!-- Sent from Reviewable.io -->

2021-02-25 22:19 UTC, markdroth requested changes
This looks really good!  My only really significant comment is the one about defining custom gmock matchers to make the tests more readable.

Please let me know if you have any questions.  Thanks!

> Reviewed 20 of 25 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25361#-:-MUQGV1l9-8-KhuqYxO-:br0qjb)* status: all files reviewed, 12 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/rbac_policy.h, line 28 at r2](https://reviewable.io/reviews/grpc/grpc/25361#-MUGV1Yx8_hEpoByxk80:-MUQ9YxM0AH-38Gmz8kw:bkqdjs0) ([raw file](https://github.com/grpc/grpc/blob/87a3a8b31e49bd2af2d403535466c18682e4b9f7/src/core/lib/security/authorization/rbac_policy.h#L28)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

I used a struct here, since Rbac is a passive object and to keep the members public, else we will need to add getters for each member field. 
Based on  go/cstyle#Structs_vs._Classes, since there is relationship between fields, it would make sense to use a Class here instead.

I haven't looked into other wrapped languages (mostly in Q4). Currently the focus is C++. 
</blockquote></details>

I think structs are probably okay for now, especially since there really aren't any methods on these objects.  And the objects themselves should never be modified once they're created, so it's not like we need to enforce invariants as fields are changed.

Wrapped languages will need to provide simple wrappers for the built-in `grpc_authorization_policy_provider` types.  We don't plan to expose an API to allow users to write their own providers, at least initially, so we won't need anything more complicated.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 356 at r1](https://reviewable.io/reviews/grpc/grpc/25361#-MTMzxnYD0vdlRicAO4F:-MUQE1tC0z3fAIJuSzDI:bw1ybsc) ([raw file](https://github.com/grpc/grpc/blob/b1d10a0e11320a081fcf93a73b1b97ba376f812d/src/core/lib/security/authorization/rbac_translator.cc#L356)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

I had tried that earlier. But it errors out
error: could not convert 'rbac_policies' from 'grpc_core::RbacPolicies' to 'absl::lts_2020_09_23::StatusOr<grpc_core::RbacPolicies>'
   return rbac_policies;

</blockquote></details>

Oh, right, because it's returning `StatusOr<RbacPolicies>` instead of just `RbacPolicies`.  Makes sense.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 70 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQBzu3CLuzzuYSX9K7:-MUQBzu3CLuzzuYSX9K8:blg6o3a) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L70)):*
> ```cpp
>     if (!matcher_or.ok()) {
>       return absl::Status(matcher_or.status().code(),
>                           absl::StrCat("\"principals\" ", i, " ",
> ```

In all cases where you include a numeric index in an error message, please add a ":" after it, so that it's easier for humans to understand what the error means.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 312 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDnVa5hEuvqhDpAKw:-MUQDnVa5hEuvqhDpAKx:bxxn34z) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L312)):*
> ```cpp
>         "SDK authorization policy is not an object.");
>   }
>   RbacPolicies rbac_policies;
> ```

This can be moved down to line 322.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 313 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDfdo6D7rmyhE8DpV:-MUQDfdo6D7rmyhE8DpW:b-xo7z13) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L313)):*
> ```cpp
>   }
>   RbacPolicies rbac_policies;
>   absl::string_view name;
> ```

This can be declared down where it's actually set.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 317 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDbvh2L2MhxmabwEv:-MUQDbvh2L2MhxmabwEw:b-ovwwqm) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L317)):*
> ```cpp
>   if (it == json.mutable_object()->end()) {
>     return absl::InvalidArgumentError("\"name\" field is not present.");
>   } else if (it->second.type() != Json::Type::STRING) {
> ```

No need for `else`, since the previous condition returns.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 319 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDaC-BAqcMAysiaIc:-MUQDaC-BAqcMAysiaId:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L319)):*
> ```cpp
>   } else if (it->second.type() != Json::Type::STRING) {
>     return absl::InvalidArgumentError("\"name\" is not a string.");
>   } else {
> ```

Same here.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 338 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDyXl10dXqPJGrR-N:-MUQDyXl10dXqPJGrR-O:bd8jkao) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L338)):*
> ```cpp
>   if (it == json.mutable_object()->end()) {
>     return absl::InvalidArgumentError("\"allow_rules\" is not present.");
>   } else if (it->second.type() != Json::Type::ARRAY) {
> ```

No need for `else`.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 340 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDzi2ANeGGznmcroc:-MUQDzi2ANeGGznmcrod:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L340)):*
> ```cpp
>   } else if (it->second.type() != Json::Type::ARRAY) {
>     return absl::InvalidArgumentError("\"allow_rules\" is not an array.");
>   } else {
> ```

Same here.
___
*[test/core/security/rbac_translator_test.cc, line 254 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQFMXH64uXiiMUlyZP:-MUQFMXH64uXiiMUlyZQ:b-602xqf) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/test/core/security/rbac_translator_test.cc#L254)):*
> ```cpp
>   EXPECT_THAT(
>       rbac_policies.value().allow_policy.policies,
>       ::testing::ElementsAre(::testing::Pair(
> ```

For a case like this, where the raw gmock matchers wind up with insanely deep nesting, consider writing your own custom gmock matchers for some of the nested objects.  For example, if you write a custom matcher for each of `Rbac`, `Rbac::Policy`, `Rbac::Permission`, `Rbac::Principal`, etc, then you can combine them pretty easily, and each individual test will get a lot shorter.
___
*[test/core/security/rbac_translator_test.cc, line 290 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQEvx67YaB88bT6DDb:-MUQEvx67YaB88bT6DDc:bhgv8rd) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/test/core/security/rbac_translator_test.cc#L290)):*
> ```cpp
>                                                       &StringMatcher::
>                                                           string_matcher,
>                                                       "spiffe://"
> ```

I assume the reason for splitting up the string constants here was to avoid having long lines.  In this particular case, I think it's probably better to keep the string constant in one piece, even if that means the line is over 80 characters.

Same thing throughout.
___
*[src/core/lib/matchers/matchers.cc, line 51 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQ9EU_8TJMecXNJWXF:-MUQ9EU_8TJ [...]

2021-03-01 02:27 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25361)* status: 18 of 26 files reviewed, 12 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/rbac_policy.h, line 28 at r2](https://reviewable.io/reviews/grpc/grpc/25361#-MUGV1Yx8_hEpoByxk80:-MUbUsE9CG32j0S-RNZO:brxp9sq) ([raw file](https://github.com/grpc/grpc/blob/87a3a8b31e49bd2af2d403535466c18682e4b9f7/src/core/lib/security/authorization/rbac_policy.h#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think structs are probably okay for now, especially since there really aren't any methods on these objects.  And the objects themselves should never be modified once they're created, so it's not like we need to enforce invariants as fields are changed.

Wrapped languages will need to provide simple wrappers for the built-in `grpc_authorization_policy_provider` types.  We don't plan to expose an API to allow users to write their own providers, at least initially, so we won't need anything more complicated.
</blockquote></details>

Sounds good.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 70 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQBzu3CLuzzuYSX9K7:-MURP-0n4avFVmRrGPf5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In all cases where you include a numeric index in an error message, please add a ":" after it, so that it's easier for humans to understand what the error means.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 312 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDnVa5hEuvqhDpAKw:-MURP4Gf5-sH1DzbnifX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L312)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be moved down to line 322.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 313 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDfdo6D7rmyhE8DpV:-MURP4kgE7GgIoEvykB5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L313)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be declared down where it's actually set.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 317 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDbvh2L2MhxmabwEv:-MURP5iD5Iz7zEYyjC1W:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L317)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `else`, since the previous condition returns.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 319 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDaC-BAqcMAysiaIc:-MURPEYP-tU_bZqAHn-O:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L319)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 338 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDyXl10dXqPJGrR-N:-MURPNtB8WIuSByp04C8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L338)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `else`.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/rbac_translator.cc, line 340 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQDzi2ANeGGznmcroc:-MURPOGmDK06owzUp2EG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/security/authorization/rbac_translator.cc#L340)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[test/core/security/rbac_translator_test.cc, line 254 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQFMXH64uXiiMUlyZP:-MUbSoqGBZ4whLIfECZF:b-1ix8ft) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/test/core/security/rbac_translator_test.cc#L254)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

For a case like this, where the raw gmock matchers wind up with insanely deep nesting, consider writing your own custom gmock matchers for some of the nested objects.  For example, if you write a custom matcher for each of `Rbac`, `Rbac::Policy`, `Rbac::Permission`, `Rbac::Principal`, etc, then you can combine them pretty easily, and each individual test will get a lot shorter.
</blockquote></details>

I wrote custom matchers for principal_name, path and header fields. This helped reduce some of the nesting.
I feel if we try to write custom matcher for fields like Permission, it over-complicates the custom matcher. Plus we would have to pass expected values (includes ruletype, string matchers, header matchers) to custom matcher, and manage nesting too. I would prefer the current structure. Wdyt?
___
*[test/core/security/rbac_translator_test.cc, line 290 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQEvx67YaB88bT6DDb:-MURPbWR60bc_f20h6NE:b-909xs0) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/test/core/security/rbac_translator_test.cc#L290)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume the reason for splitting up the string constants here was to avoid having long lines.  In this particular case, I think it's probably better to keep the string constant in one piece, even if that means the line is over 80 characters.

Same thing throughout.
</blockquote></details>

The formatting script split the strings. This is not a problem now, with custom matchers.
___
*[src/core/lib/matchers/matchers.cc, line 51 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQ9EU_8TJMecXNJWXF:-MURp5Gf6uQHwIw2y50q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/src/core/lib/matchers/matchers.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is the `std::string()` actually needed here?  I think the compiler might not need it, since it knows that that's the type of `string_matcher_`.

Same comment throughout.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-02 17:42 UTC, markdroth approved these changes
This looks great!

> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25361#-:-MUo15q10blfswoI7lf_:b-j45s0z)* status: all files reviewed, 2 unresolved discussions (waiting on @jiangtaoli2016 and @ZhenLian)

___
*[test/core/security/rbac_translator_test.cc, line 254 at r3](https://reviewable.io/reviews/grpc/grpc/25361#-MUQFMXH64uXiiMUlyZP:-MUo0opq9WG5WBtKJB6d:bgx6rw0) ([raw file](https://github.com/grpc/grpc/blob/43a0afaba4defcfbb2f296ff2fb9c06921667ff8/test/core/security/rbac_translator_test.cc#L254)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

I wrote custom matchers for principal_name, path and header fields. This helped reduce some of the nesting.
I feel if we try to write custom matcher for fields like Permission, it over-complicates the custom matcher. Plus we would have to pass expected values (includes ruletype, string matchers, header matchers) to custom matcher, and manage nesting too. I would prefer the current structure. Wdyt?
</blockquote></details>

Looks like a good compromise.  Thanks!


<!-- Sent from Reviewable.io -->

2021-03-02 19:13 UTC, ashithasantosh commented
Thanks for the review, @markdroth !:)

2021-03-03 21:38 UTC, ZhenLian approved these changes
LGTM!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25361#-:-MUu0hDU7m9P03qsZHL0:b-85i648)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiangtaoli2016)



<!-- Sent from Reviewable.io -->

2021-03-03 22:16 UTC, ashithasantosh commented
Thanks for the review, @ZhenLian !:)

2021-03-05 04:52 UTC, jiangtaoli2016 reviewed
Thanks @ashithasantosh for the PR. It is very nice. Thanks Mark and Zhen for careful review. I only have a few minor comments.

2021-03-05 04:52 UTC, jiangtaoli2016 commented on src/core/lib/security/authorization/rbac_translator.cc
> +  if (it != json.mutable_object()->end()) {
When there is no deny_rules, the `rbac_policies.deny_policy` is empty. In RBAC engine, the default enum is ALLOW. We may end up have deny_policy set ALLOW action by mistake (as default value). We shall explicitly set `rbac_policies.deny_policy` action to DENY to be self-contain. 

Please also update unit test accordingly.

2021-03-05 04:52 UTC, jiangtaoli2016 commented on src/core/lib/security/authorization/rbac_translator.cc
> +      absl::StartsWith(header_name, "grpc-") || header_name == "host") {
Please also remove "Host" header as well. 
Both "host" and "Host" are supported in HTTP 1.1

2021-03-05 04:52 UTC, jiangtaoli2016 commented on test/core/security/rbac_translator_test.cc
> +TEST(GenerateRbacPoliciesTest, UnsupportedPseudoHeaders) {
nit: could you add a test on "host" and/or "Host" headers.

2021-03-05 06:53 UTC, ashithasantosh commented
Thanks for the review, @jiangtaoli2016!:) I resolved all comments.

2021-03-05 16:57 UTC, jiangtaoli2016 approved these changes
Thanks Ashitha for quick revision!

2021-03-05 17:05 UTC, merged