Simplify subchannel ref counting and pool registration
grpc/grpc pull request #25485
Opened 2021-02-18 03:25 UTC by apolcyn

Also removes the CAS loops in the global subchannel pool register/unregister methods

2021-02-26 08:23 UTC, markdroth requested changes
This looks like it's heading in the right direction.  My main comment is that I don't think we need `SubchannelRef`; instead, we can just check whether the entry points to the right subchannel before we remove it.  I think this will actually restore most of the logic to the way it was originally, so that the only real logic changes will be in the global subchannel pool.  The other files should be mostly just type changes.

Please let me know if you have any questions.  Thanks!

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485#-:-MUSQT8s35up0O2hFnav:blu9d7p)* status: all files reviewed, 18 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/client_channel_factory.h, line 35 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUQiFG48lKDc1kM36Rx:-MUQiFG58-3mYO9ye9RN:b-bprlq3) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/client_channel_factory.h#L35)):*
> ```objc
> 
>   // Creates a subchannel with the specified args.
>   virtual std::unique_ptr<SubchannelRef> CreateSubchannel(
> ```

Note that the change to this interface will require some internal changes, so you'll need to do a cherry-pick import.
___
*[src/core/ext/filters/client_channel/global_subchannel_pool.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSLMll4NE905GYnKPN:-MUSLMll4NE905GYnKPO:b-b53o06) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/global_subchannel_pool.h#L73)):*
> ```objc
> 
>   // A map from subchannel key to subchannel.
>   std::map<SubchannelKey, WeakRefCountedPtr<Subchannel>> subchannel_map_;
> ```

Have we done any analysis to suggest what the performance difference will be between `grpc_avl` and  `std::map<>`?
___
*[src/core/ext/filters/client_channel/global_subchannel_pool.cc, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSLfWqD4q4Zd46nxvy:-MUSLfWqD4q4Zd46nxvz:b-fwsi7) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/global_subchannel_pool.cc#L53)):*
> ```cpp
>     const SubchannelKey& key, RefCountedPtr<Subchannel> constructed) {
>   MutexLock lock(&mu_);
>   auto p = subchannel_map_.find(key);
> ```

This should be called `it`, since it's an iterator.
___
*[src/core/ext/filters/client_channel/global_subchannel_pool.cc, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSMbMZ5yq_uX_ewtZW:-MUSMbMZ5yq_uX_ewtZX:b-lhybpf) ([raw file](https://github.com/grpc/grpc/blob/90b565f17ade1d34d7e93f54a51f1ecc54677724/src/core/ext/filters/client_channel/global_subchannel_pool.cc#L122)):*
> ```cpp
> }
> 
> void GlobalSubchannelPool::UnregisterSubchannel(SubchannelKey* key) {
> ```

I think we still need this, but it will need to look something like this:

```
void GlobalSubchannelPool::UnregisterSubchannel(
    const SubchannelKey& key, Subchannel* subchannel) {
  MutexLock lock(&mu_);
  auto it = subchannel_map_.find(key);
  if (it != subchannel_map_.end() &&
      it->second.get() == subchannel) {
     subchannel_map_.erase(it);
  }
}
```

By checking that the entry we're removing is actually pointing to the subchannel that we are removing, this avoids the race condition that you mentioned without the need for `SubchannelRef`.
___
*[src/core/ext/filters/client_channel/global_subchannel_pool.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSMtFZ-xfjmy9tGnaa:-MUSMtFZ-xfjmy9tGnab:bv2g5ev) ([raw file](https://github.com/grpc/grpc/blob/90b565f17ade1d34d7e93f54a51f1ecc54677724/src/core/ext/filters/client_channel/global_subchannel_pool.cc#L149)):*
> ```cpp
> }
> 
> Subchannel* GlobalSubchannelPool::FindSubchannel(SubchannelKey* key) {
> ```

We'll still need this as well, but it can be much simpler:

```
RefCountedPtr<Subchannel> GlobalSubchannelPool::FindSubchannel(
     const SubchannelKey& key) {
  MutexLock lock(&mu_);
  auto it = subchannel_map_.find(key);
  if (it == subchannel_map_.end()) return nullptr;
  return it->second->RefIfNonZero();
}
```
___
*[src/core/ext/filters/client_channel/local_subchannel_pool.cc, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUQXj7H3hlyeSe7w6gR:-MUQXj7H3hlyeSe7w6gS:b-fwsi7) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/local_subchannel_pool.cc#L30)):*
> ```cpp
>     const SubchannelKey& key, RefCountedPtr<Subchannel> constructed) {
>   // Check to see if a subchannel already exists.
>   auto p = subchannel_map_.find(key);
> ```

This should be called `it`, since it's an iterator.
___
*[src/core/ext/filters/client_channel/local_subchannel_pool.cc, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUQXlSJ8q7rf9rrY72s:-MUQXlSKEYGVbe2UoZcF:bwgtvmx) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/local_subchannel_pool.cc#L32)):*
> ```cpp
>   auto p = subchannel_map_.find(key);
>   RefCountedPtr<Subchannel> c;
>   if (p != subchannel_map_.end()) {
> ```

I think this can be more easily written as:

```
if (it != subchannel_map_.end()) {
  auto existing = it->second->RefIfNonZero();
  if (existing != nullptr) return existing;
}
subchannel_map_[key] = constructed->WeakRef();
return constructed;
```
___
*[src/core/ext/filters/client_channel/subchannel.h, line 354 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSGj2m5qSKffDTT7xC:-MUSGj2m5qSKffDTT7xD:bvp45uw) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/subchannel.h#L354)):*
> ```objc
>   //    - upper remaining bits are for public references: these do
>   //      keep the subchannel open
>   gpr_atm ref_pair_;
> ```

This is no longer needed.
___
*[src/core/ext/filters/client_channel/subchannel.h, line 377 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSGnNr6NLeTP5xwEoG:-MUSGnNr6NLeTP5xwEoH:bhri8ng) ([raw file](https://github.com/grpc/grpc/blob/90b565f17ade1d34d7e93f54a51f1ecc54677724/src/core/ext/filters/client_channel/subchannel.h#L377)):*
> ```objc
> 
>   // The subchannel pool this subchannel is in.
>   RefCountedPtr<SubchannelPoolInterface> subchannel_pool_;
> ```

I think this and `key_` are still necessary, since we need to unregister the subchannel from the pool in `Orphan()`.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 423 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSHYF-90ZBmUUPY9fa:-MUSHYF-90ZBmUUPY9fb:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/subchannel.cc#L423)):*
> ```cpp
>                 std::string health_check_service_name,
>                 grpc_connectivity_state subchannel_state)
>       : subchannel_(c),
> ```

`std::move()`
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 523 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSH7cY0gslU3_VgrRf:-MUSH7cY0gslU3_VgrRg:bnyqb8t) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/subchannel.cc#L523)):*
> ```cpp
>   if (it == map_.end()) {
>     auto w = MakeOrphanable<HealthWatcher>(
>         subchannel, health_check_service_name, subchannel->state_);
> ```

`std::move(subchannel)`

You may need to grab `subchannel->state_` first in order to keep the 3rd argument working.  Or maybe just eliminate the 3rd argument completely and have `HealthWatcher` check the subchannel's `state_` field itself.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 643 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSGEZe0S09ezJ16iBw:-MUSGEZe0S09ezJ16iBx:bqu6wub) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/subchann [...]

2021-03-01 19:59 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485)* status: 1 of 13 files reviewed, 18 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel_factory.h, line 35 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUQiFG48lKDc1kM36Rx:-MUjMj0dEVgD3g9iD0vd:bo28g1p) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/client_channel_factory.h#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Note that the change to this interface will require some internal changes, so you'll need to do a cherry-pick import.
</blockquote></details>

Thanks for the heads up, I will make sure to coordinate those changes.
___
*[src/core/ext/filters/client_channel/global_subchannel_pool.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSLMll4NE905GYnKPN:-MUjLp2A5QoKqLBJK2S1:bxa5hj5) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/global_subchannel_pool.h#L73)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Have we done any analysis to suggest what the performance difference will be between `grpc_avl` and  `std::map<>`?
</blockquote></details>

I haven't done any microbenchmarks yet, but I have plugged this change  as a whole into my test that I used to repro b/178127983 (where I earlier reproduced the excessive CAS loop spinning), and saw that the test ran faster.

I will do some microbenchmarks to compare `std::map` with `grpc_avl` next.
___
*[src/core/ext/filters/client_channel/global_subchannel_pool.cc, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSLfWqD4q4Zd46nxvy:-MUjGqa-3vaa6p25NBCN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/global_subchannel_pool.cc#L53)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be called `it`, since it's an iterator.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/global_subchannel_pool.cc, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSMbMZ5yq_uX_ewtZW:-MUjHW2E8OgYRcsJyW-f:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/90b565f17ade1d34d7e93f54a51f1ecc54677724/src/core/ext/filters/client_channel/global_subchannel_pool.cc#L122)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we still need this, but it will need to look something like this:

```
void GlobalSubchannelPool::UnregisterSubchannel(
    const SubchannelKey& key, Subchannel* subchannel) {
  MutexLock lock(&mu_);
  auto it = subchannel_map_.find(key);
  if (it != subchannel_map_.end() &&
      it->second.get() == subchannel) {
     subchannel_map_.erase(it);
  }
}
```

By checking that the entry we're removing is actually pointing to the subchannel that we are removing, this avoids the race condition that you mentioned without the need for `SubchannelRef`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/global_subchannel_pool.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSMtFZ-xfjmy9tGnaa:-MUjHcMW0apF3CcemNf1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/90b565f17ade1d34d7e93f54a51f1ecc54677724/src/core/ext/filters/client_channel/global_subchannel_pool.cc#L149)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We'll still need this as well, but it can be much simpler:

```
RefCountedPtr<Subchannel> GlobalSubchannelPool::FindSubchannel(
     const SubchannelKey& key) {
  MutexLock lock(&mu_);
  auto it = subchannel_map_.find(key);
  if (it == subchannel_map_.end()) return nullptr;
  return it->second->RefIfNonZero();
}
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/local_subchannel_pool.cc, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUQXj7H3hlyeSe7w6gR:-MUjHvLi5R9NOZU5GJjc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/local_subchannel_pool.cc#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be called `it`, since it's an iterator.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/local_subchannel_pool.cc, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUQXlSJ8q7rf9rrY72s:-MUjHyRi6Zbu7t3JT3fI:b-20w7yn) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/local_subchannel_pool.cc#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can be more easily written as:

```
if (it != subchannel_map_.end()) {
  auto existing = it->second->RefIfNonZero();
  if (existing != nullptr) return existing;
}
subchannel_map_[key] = constructed->WeakRef();
return constructed;
```
</blockquote></details>

I ended up actually simplifying further here, because it looks like due to the fact that the manipulation of the local subchannel pool and subchannel refs is synchronized by the client channel, there are a couple of invariants:

a) Any subchannel we find in the map in `RegisterSubchannel` must still have existing strong refs (because `Subchannel::Unref`'ing and `LocalSubchannelPool::UnregisterSubchannelPool` are effectively atomic).

b) If we're calling `RegisterSubchannelPool`, then an equivalent subchannel must not exist in the map. This is because `FindSubchannel`, which we just checked, returned `nullptr`. And because `FindSubchannel` and `RegisterSubchannelPool` are atomic w.r.t. the client channel's synchronization, it's not possible to register a new subchannel in the interim.
___
*[src/core/ext/filters/client_channel/subchannel.h, line 354 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSGj2m5qSKffDTT7xC:-MUjJmVQAlVf0-Lrv392:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/subchannel.h#L354)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is no longer needed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/subchannel.h, line 377 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSGnNr6NLeTP5xwEoG:-MUjJcm457zd1JXHtMqV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/90b565f17ade1d34d7e93f54a51f1ecc54677724/src/core/ext/filters/client_channel/subchannel.h#L377)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this and `key_` are still necessary, since we need to unregister the subchannel from the pool in `Orphan()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 423 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSHYF-90ZBmUUPY9fa:-MUjJrFG-lZiCmxijAxK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/subchannel.cc#L423)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 523 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSH7cY0gslU3_VgrRf:-MUjJy5902wEci_-464r:b-ax9ij0) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/subchannel.cc#L523)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move(subchannel)`

You may need to grab `subchannel->state_` first in order to keep the 3rd argument working.  Or maybe just eli [...]

2021-03-02 23:07 UTC, markdroth requested changes
This looks fabulous!

Remaining comments are minor.  Mainly just waiting for the benchmark results before approving.

Please let me know if you have any questions.  Thanks!

> Reviewed 7 of 12 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485#-:-MUp9IWzCpC8TMxw5gkc:bi41bm6)* status: all files reviewed, 8 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/global_subchannel_pool.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSLMll4NE905GYnKPN:-MUp3oPt0VJ2UIu1sbIu:b-d9bqhm) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/global_subchannel_pool.h#L73)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I haven't done any microbenchmarks yet, but I have plugged this change  as a whole into my test that I used to repro b/178127983 (where I earlier reproduced the excessive CAS loop spinning), and saw that the test ran faster.

I will do some microbenchmarks to compare `std::map` with `grpc_avl` next.
</blockquote></details>

Super, thanks!  I just want to make sure that we're not making this a lot more pessimum than we expect.  In principle, it should be about the same, because both are sorted data structures.

It would have been nice to be able to use a hash-based map here, which I would have expected would perform better in cases where there are a huge number of subchannels.  But given that channel args provide a cmp() function but don't provide a hash() function, it's not clear how we could do that. :(
___
*[src/core/ext/filters/client_channel/global_subchannel_pool.h, line 63 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp4kAO8XbkmzGOg50K:-MUp4kAO8XbkmzGOg50L:bka5cx2) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/global_subchannel_pool.h#L63)):*
> ```objc
> 
>   // A map from subchannel key to subchannel.
>   std::map<SubchannelKey, Subchannel*> subchannel_map_;
> ```

We now have the ability to use lock annotations here.  Please add `ABSL_GUARDED_BY(mu_)` here, and add `ABSL_LOCKS_EXCLUDED(mu_)` on each of the three methods above.
___
*[src/core/ext/filters/client_channel/local_subchannel_pool.cc, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUQXlSJ8q7rf9rrY72s:-MUp2u-a409RcVT5S640:b-kzrse) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/local_subchannel_pool.cc#L32)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I ended up actually simplifying further here, because it looks like due to the fact that the manipulation of the local subchannel pool and subchannel refs is synchronized by the client channel, there are a couple of invariants:

a) Any subchannel we find in the map in `RegisterSubchannel` must still have existing strong refs (because `Subchannel::Unref`'ing and `LocalSubchannelPool::UnregisterSubchannelPool` are effectively atomic).

b) If we're calling `RegisterSubchannelPool`, then an equivalent subchannel must not exist in the map. This is because `FindSubchannel`, which we just checked, returned `nullptr`. And because `FindSubchannel` and `RegisterSubchannelPool` are atomic w.r.t. the client channel's synchronization, it's not possible to register a new subchannel in the interim.
</blockquote></details>

Good point!  This looks good.
___
*[src/core/ext/filters/client_channel/local_subchannel_pool.cc, line 41 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp31xh5ckkvFScvwwm:-MUp31xh5ckkvFScvwwn:brgecoq) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/local_subchannel_pool.cc#L41)):*
> ```cpp
>                                                Subchannel* subchannel) {
>   auto it = subchannel_map_.find(key);
>   // Because Subchannel::Orphan this subchannel pool are only called under
> ```

This doesn't parse grammatically.  Maybe you meant "Because this subchannel pool is accessed only under"?
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 313 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp9Y-eEmFwDf3lainV:-MUp9Y-eEmFwDf3lainW:bgqjen7) ([raw file](https://github.com/grpc/grpc/blob/90b565f17ade1d34d7e93f54a51f1ecc54677724/src/core/ext/filters/client_channel/subchannel.cc#L313)):*
> ```cpp
> 
>   ~ConnectedSubchannelStateWatcher() override {
>     GRPC_SUBCHANNEL_WEAK_UNREF(subchannel_, "state_watcher");
> ```

In order to avoid losing the additional data for ref-count debugging, I suggest having a dtor like this:

```
~ConnectedSubchannelStateWatcher() override {
  subchannel_.reset(DEBUG_LOCATION, "state_watcher");
}
```
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 439 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp9l220kiqHN25Iwej:-MUp9l220kiqHN25Iwek:bpmaonv) ([raw file](https://github.com/grpc/grpc/blob/90b565f17ade1d34d7e93f54a51f1ecc54677724/src/core/ext/filters/client_channel/subchannel.cc#L439)):*
> ```cpp
> 
>   ~HealthWatcher() override {
>     GRPC_SUBCHANNEL_WEAK_UNREF(subchannel_, "health_watcher");
> ```

Similar issue here:

```
~HealthWatcher() override {
  subchannel_.reset(DEBUG_LOCATION, "health_watcher");
}
```
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 706 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp6hQGA2gRj9JpW4oT:-MUp6hQGA2gRj9JpW4oU:b-2oexzq) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L706)):*
> ```cpp
>     OrphanablePtr<SubchannelConnector> connector,
>     const grpc_channel_args* args) {
>   SubchannelKey* key = new SubchannelKey(args);
> ```

It looks like there really isn't any reason that we need to dynamically allocate this, especially now that you've made this type movable.  Instead, let's  change the `key_` data member from `SubchannelKey*` to `SubchannelKey` and pass the key into the ctor by value using `std::move()`.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 789 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUpA1OqDMQ81YvA90Yx:-MUpA1OqDMQ81YvA90Yy:b-v792wt) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L789)):*
> ```cpp
>     watcher_list_.AddWatcherLocked(std::move(watcher));
>   } else {
>     health_watcher_map_.AddWatcherLocked(WeakRef(), initial_state,
> ```

To retain ref-count debugging info, please use `WeakRef(DEBUG_LOCATION, "health_watcher")`.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 936 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUpB5eB223YTQzpmgFW:-MUpB5eB223YTQzpmgFX:bb02ev0) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L936)):*
> ```cpp
>   }
>   connecting_ = true;
>   WeakRef().release();  // ref held by pending connect
> ```

To retain ref-count debug logging, please use `WeakRef(DEBUG_LOCATION, "connecting")`.


<!-- Sent from Reviewable.io -->

2021-03-03 04:08 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485)* status: all files reviewed, 8 unresolved discussions (waiting on @apolcyn and @markdroth)

___
*[src/core/ext/filters/client_channel/global_subchannel_pool.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSLMll4NE905GYnKPN:-MUqAZlE-_YpQq9i94H9:b-ik6v49) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/global_subchannel_pool.h#L73)):*
So I ended up writing the following simple benchmark code, which performs the following steps in a loop:
1) inserts a random sequence of unique integers into the data structure of choice (before first checking that it doesn't exist in the set)
2) performs a lookup on each integer
3) deletes each integer.

The code looks like this:

```
#include "src/core/lib/avl/avl.h"

#include <stdio.h>
#include <string.h>

#include <map>
#include <set>

#include "absl/flags/flag.h"

#include <grpc/support/alloc.h>
#include <grpc/support/log.h>

#include "src/core/lib/gpr/useful.h"
#include "test/core/util/test_config.h"
#include "test/cpp/util/test_config.h"

int* box(int value) {
  int* ret = static_cast<int*>(gpr_malloc(sizeof(*ret)));
  *ret = value;
  return ret;
}

static long int_compare(void* int1, void* int2, void* /*unused*/) {
  return (*static_cast<int*>(int1)) - (*static_cast<int*>(int2));
}
static void* int_copy(void* p, void* /*unused*/) {
  return box(*static_cast<int*>(p));
}

static void destroy(void* p, void* /*unused*/) { gpr_free(p); }

static const grpc_avl_vtable int_int_vtable = {destroy, int_copy, int_compare,
                                               destroy, int_copy};

ABSL_FLAG(int, num_loops, 0, "");
ABSL_FLAG(int, num_items_per_loop, 0, "");
ABSL_FLAG(bool, use_avl, false, "");

int main(int argc, char* argv[]) {
  grpc::testing::TestEnvironment env(argc, argv);
  grpc::testing::InitTest(&argc, &argv, false);
  grpc_avl avl = grpc_avl_create(&int_int_vtable);
  std::map<int, int> map;
  srand(static_cast<unsigned>(time(nullptr)));
  std::vector<int> values;
  values.reserve(absl::GetFlag(FLAGS_num_items_per_loop));
  {
    // pre-allocate random sequence of ints
    std::set<int> values_no_dups;
    for (int i = 0; i < absl::GetFlag(FLAGS_num_items_per_loop); i++) {
      int value = rand();
      values.push_back(value);
      values_no_dups.emplace(value);
    }
    if (values.size() != values_no_dups.size()) {
      gpr_log(GPR_ERROR, "Wanted %d unique values but got %d",
              absl::GetFlag(FLAGS_num_items_per_loop), values.size());
      GPR_ASSERT(values.size() == values_no_dups.size());
    }
  }
  for (int i = 0; i < absl::GetFlag(FLAGS_num_loops); i++) {
    GPR_ASSERT(map.size() == 0);
    // unsucessful lookup followed by insert
    for (const int& value : values) {
      if (absl::GetFlag(FLAGS_use_avl)) {
        GPR_ASSERT(grpc_avl_get(avl, const_cast<int*>(&value), nullptr) ==
                   nullptr);
        avl = grpc_avl_add(avl, box(value), box(value + 1), nullptr);
      } else {
        auto it = map.find(value);
        GPR_ASSERT(it == map.end());
        map[value] = value + 1;
      }
    }
    // successful lookup
    for (const int& value : values) {
      if (absl::GetFlag(FLAGS_use_avl)) {
        GPR_ASSERT(*(int*)grpc_avl_get(avl, const_cast<int*>(&value),
                                       nullptr) == value + 1);
      } else {
        GPR_ASSERT(map[value] == value + 1);
      }
    }
    // delete
    for (const int& value : values) {
      if (absl::GetFlag(FLAGS_use_avl)) {
        avl = grpc_avl_remove(avl, const_cast<int*>(&value), nullptr);
      } else {
        auto it = map.find(value);
        GPR_ASSERT(it != map.end());
        map.erase(it);
      }
    }
  }
  return 0;
}
```

I ran this after building the test with cmake in `Release` config, and compared `--use_avl=true` and --use_avl=false` (`std::map`) for dataset sizes of 100, 1K, and 10K. This gave the following results:

```
===== 100 items per round =====

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=true
real	0m0.241s
user	0m0.215s
sys	0m0.031s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=true
real	0m0.233s
user	0m0.217s
sys	0m0.021s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=true
real	0m0.231s
user	0m0.208s
sys	0m0.028s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=false
real	0m0.056s
user	0m0.031s
sys	0m0.030s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=false
real	0m0.055s
user	0m0.039s
sys	0m0.020s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=false
real	0m0.054s
user	0m0.038s
sys	0m0.020s

===== 1K items per round =====

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=true
real	0m3.165s
user	0m3.149s
sys	0m0.020s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=true
real	0m3.158s
user	0m3.145s
sys	0m0.018s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=true
real	0m3.172s
user	0m3.157s
sys	0m0.020s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=false
real	0m0.532s
user	0m0.520s
sys	0m0.016s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=false
real	0m0.533s
user	0m0.527s
sys	0m0.011s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=false
real	0m0.528s
user	0m0.521s
sys	0m0.012s

==== 10K items per round ====

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=true
real	0m52.122s
user	0m52.068s
sys	0m0.032s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=true
real	0m51.553s
user	0m51.522s
sys	0m0.027s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=true
real	0m51.962s
user	0m51.943s
sys	0m0.021s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=false
real	0m8.525s
user	0m8.504s
sys	0m0.025s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=false
real	0m8.533s
user	0m8.518s
sys	0m0.019s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=false
real	0m8.574s
user	0m8.551s
sys	0m0.028s
``` 

So, even though the time taken by `grpc_avl` and `std::map` scales up roughly linearly for all dataset sizes, `std::map` appears to be roughly 5-8 times faster than `grpc_avl` at all dataset sizes.

Note that this benchmark does dynamically allocate memory when doing `grpc_avl` insertions, but it doesn't when doing `std::map` insertions. While this certainly adds some overhead, I think it's still a relatively fair benchmark, because the `grpc_avl` API typically necessitates dynamic allocations of keys and values anyways.

That said, even if we optimize the benchmark's usage of `grpc_avl` to avoid dynamic allocations, e.g. by changing the benchmark's `grpc_avl_vtable` to look like this:

```
static long int_compare(void* int1, void* int2, void* /*unused*/) {
  return (*static_cast<int*>(int1)) - (*static_cast<int*>(int2));
}
static void* int_copy(void* p, void* /*unused*/) {
  return p;
}

static void destroy(void* p, void* /*unused*/) {}

static const grpc_avl_vtable int_int_vtable = {destroy, int_copy, int_compare,
                                               destroy, int_copy};
```

.... then `grpc_avl` improves but it's still roughly 4 times slower than `std::map`. For example, we get the following data from the benchmark using `grpc_avl` <i>without</i> dynamic allocations of keys or values.

```
==== 100 items per round ====

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=true
real	0m0.160s
user	0m0.135s
sys	0m0.031s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=true
real	0m0.161s
user	0m0.145s
sys	0m0.021s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=true
real	0m0.162s
user	0m0.134s
sys	0m0.033s

==== 1K items per round ====

$ tim [...]

2021-03-03 04:35 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485)* status: all files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/global_subchannel_pool.h, line 63 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp4kAO8XbkmzGOg50K:-MUqIDd54C24T-rj3HKi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/global_subchannel_pool.h#L63)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We now have the ability to use lock annotations here.  Please add `ABSL_GUARDED_BY(mu_)` here, and add `ABSL_LOCKS_EXCLUDED(mu_)` on each of the three methods above.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/local_subchannel_pool.cc, line 41 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp31xh5ckkvFScvwwm:-MUqIWFFCuYp-HLmKTPr:b-45j6zd) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/local_subchannel_pool.cc#L41)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't parse grammatically.  Maybe you meant "Because this subchannel pool is accessed only under"?
</blockquote></details>

whoops, fixed
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 313 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp9Y-eEmFwDf3lainV:-MUqIthiD8XvUaC2LYvA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/90b565f17ade1d34d7e93f54a51f1ecc54677724/src/core/ext/filters/client_channel/subchannel.cc#L313)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In order to avoid losing the additional data for ref-count debugging, I suggest having a dtor like this:

```
~ConnectedSubchannelStateWatcher() override {
  subchannel_.reset(DEBUG_LOCATION, "state_watcher");
}
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 439 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp9l220kiqHN25Iwej:-MUqJ21C10i2ZO77wxCL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/90b565f17ade1d34d7e93f54a51f1ecc54677724/src/core/ext/filters/client_channel/subchannel.cc#L439)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similar issue here:

```
~HealthWatcher() override {
  subchannel_.reset(DEBUG_LOCATION, "health_watcher");
}
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 706 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp6hQGA2gRj9JpW4oT:-MUqJrlM-Eyh6Y2uS7ZG:br78ekl) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L706)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like there really isn't any reason that we need to dynamically allocate this, especially now that you've made this type movable.  Instead, let's  change the `key_` data member from `SubchannelKey*` to `SubchannelKey` and pass the key into the ctor by value using `std::move()`.
</blockquote></details>

Done. AFAICS we can't pass the `SubchannelKey` to the ctor with `std::move` though, because we need to still provide the `SubchannelKey` to `RegisterSubchannel`, after constructing the `Subchannel`.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 789 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUpA1OqDMQ81YvA90Yx:-MUqK7Rk6fx7usWyjfsN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L789)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

To retain ref-count debugging info, please use `WeakRef(DEBUG_LOCATION, "health_watcher")`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 936 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUpB5eB223YTQzpmgFW:-MUqK7ln6aC45bqLmK0h:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L936)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

To retain ref-count debug logging, please use `WeakRef(DEBUG_LOCATION, "connecting")`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-03 18:21 UTC, markdroth approved these changes
This looks great!

Only a few minor comments remaining.  I'll go ahead and approve, and you can merge once you've addressed them.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485#-:-MUtJUHaC0htCPetA0aS:b6qjsu0)* status: all files reviewed, 4 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/global_subchannel_pool.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/25485#-MUSLMll4NE905GYnKPN:-MUtI5Wz1BMmXssDDz3V:b8nbcsg) ([raw file](https://github.com/grpc/grpc/blob/12335ae475b6cc0a9c78f864f5d4d2875610da44/src/core/ext/filters/client_channel/global_subchannel_pool.h#L73)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

So I ended up writing the following simple benchmark code, which performs the following steps in a loop:
1) inserts a random sequence of unique integers into the data structure of choice (before first checking that it doesn't exist in the set)
2) performs a lookup on each integer
3) deletes each integer.

The code looks like this:

```
#include "src/core/lib/avl/avl.h"

#include <stdio.h>
#include <string.h>

#include <map>
#include <set>

#include "absl/flags/flag.h"

#include <grpc/support/alloc.h>
#include <grpc/support/log.h>

#include "src/core/lib/gpr/useful.h"
#include "test/core/util/test_config.h"
#include "test/cpp/util/test_config.h"

int* box(int value) {
  int* ret = static_cast<int*>(gpr_malloc(sizeof(*ret)));
  *ret = value;
  return ret;
}

static long int_compare(void* int1, void* int2, void* /*unused*/) {
  return (*static_cast<int*>(int1)) - (*static_cast<int*>(int2));
}
static void* int_copy(void* p, void* /*unused*/) {
  return box(*static_cast<int*>(p));
}

static void destroy(void* p, void* /*unused*/) { gpr_free(p); }

static const grpc_avl_vtable int_int_vtable = {destroy, int_copy, int_compare,
                                               destroy, int_copy};

ABSL_FLAG(int, num_loops, 0, "");
ABSL_FLAG(int, num_items_per_loop, 0, "");
ABSL_FLAG(bool, use_avl, false, "");

int main(int argc, char* argv[]) {
  grpc::testing::TestEnvironment env(argc, argv);
  grpc::testing::InitTest(&argc, &argv, false);
  grpc_avl avl = grpc_avl_create(&int_int_vtable);
  std::map<int, int> map;
  srand(static_cast<unsigned>(time(nullptr)));
  std::vector<int> values;
  values.reserve(absl::GetFlag(FLAGS_num_items_per_loop));
  {
    // pre-allocate random sequence of ints
    std::set<int> values_no_dups;
    for (int i = 0; i < absl::GetFlag(FLAGS_num_items_per_loop); i++) {
      int value = rand();
      values.push_back(value);
      values_no_dups.emplace(value);
    }
    if (values.size() != values_no_dups.size()) {
      gpr_log(GPR_ERROR, "Wanted %d unique values but got %d",
              absl::GetFlag(FLAGS_num_items_per_loop), values.size());
      GPR_ASSERT(values.size() == values_no_dups.size());
    }
  }
  for (int i = 0; i < absl::GetFlag(FLAGS_num_loops); i++) {
    GPR_ASSERT(map.size() == 0);
    // unsucessful lookup followed by insert
    for (const int& value : values) {
      if (absl::GetFlag(FLAGS_use_avl)) {
        GPR_ASSERT(grpc_avl_get(avl, const_cast<int*>(&value), nullptr) ==
                   nullptr);
        avl = grpc_avl_add(avl, box(value), box(value + 1), nullptr);
      } else {
        auto it = map.find(value);
        GPR_ASSERT(it == map.end());
        map[value] = value + 1;
      }
    }
    // successful lookup
    for (const int& value : values) {
      if (absl::GetFlag(FLAGS_use_avl)) {
        GPR_ASSERT(*(int*)grpc_avl_get(avl, const_cast<int*>(&value),
                                       nullptr) == value + 1);
      } else {
        GPR_ASSERT(map[value] == value + 1);
      }
    }
    // delete
    for (const int& value : values) {
      if (absl::GetFlag(FLAGS_use_avl)) {
        avl = grpc_avl_remove(avl, const_cast<int*>(&value), nullptr);
      } else {
        auto it = map.find(value);
        GPR_ASSERT(it != map.end());
        map.erase(it);
      }
    }
  }
  return 0;
}
```

I ran this after building the test with cmake in `Release` config, and compared `--use_avl=true` and --use_avl=false` (`std::map`) for dataset sizes of 100, 1K, and 10K. This gave the following results:

```
===== 100 items per round =====

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=true
real	0m0.241s
user	0m0.215s
sys	0m0.031s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=true
real	0m0.233s
user	0m0.217s
sys	0m0.021s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=true
real	0m0.231s
user	0m0.208s
sys	0m0.028s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=false
real	0m0.056s
user	0m0.031s
sys	0m0.030s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=false
real	0m0.055s
user	0m0.039s
sys	0m0.020s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=false
real	0m0.054s
user	0m0.038s
sys	0m0.020s

===== 1K items per round =====

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=true
real	0m3.165s
user	0m3.149s
sys	0m0.020s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=true
real	0m3.158s
user	0m3.145s
sys	0m0.018s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=true
real	0m3.172s
user	0m3.157s
sys	0m0.020s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=false
real	0m0.532s
user	0m0.520s
sys	0m0.016s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=false
real	0m0.533s
user	0m0.527s
sys	0m0.011s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=1000 --use_avl=false
real	0m0.528s
user	0m0.521s
sys	0m0.012s

==== 10K items per round ====

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=true
real	0m52.122s
user	0m52.068s
sys	0m0.032s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=true
real	0m51.553s
user	0m51.522s
sys	0m0.027s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=true
real	0m51.962s
user	0m51.943s
sys	0m0.021s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=false
real	0m8.525s
user	0m8.504s
sys	0m0.025s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=false
real	0m8.533s
user	0m8.518s
sys	0m0.019s

$ time ./avl_test --num_loops=2000 --num_items_per_loop=10000 --use_avl=false
real	0m8.574s
user	0m8.551s
sys	0m0.028s
``` 

So, even though the time taken by `grpc_avl` and `std::map` scales up roughly linearly for all dataset sizes, `std::map` appears to be roughly 5-8 times faster than `grpc_avl` at all dataset sizes.

Note that this benchmark does dynamically allocate memory when doing `grpc_avl` insertions, but it doesn't when doing `std::map` insertions. While this certainly adds some overhead, I think it's still a relatively fair benchmark, because the `grpc_avl` API typically necessitates dynamic allocations of keys and values anyways.

That said, even if we optimize the benchmark's usage of `grpc_avl` to avoid dynamic allocations, e.g. by changing the benchmark's `grpc_avl_vtable` to look like this:

```
static long int_compare(void* int1, void* int2, void* /*unused*/) {
  return (*static_cast<int*>(int1)) - (*static_cast<int*>(int2));
}
static void* int_copy(void* p, void* /*unused*/) {
  return p;
}

static void destroy(void* p, void* /*unused*/) {}

static const grpc_avl_vtable int_int_vtable = {destroy, int_copy, int_compare,
                                               destroy, int_copy};
```

.... then `grpc_avl` improves but it's still roughly 4 times slower than `std::map`. For example, we get the following data from the benchmark using `grpc_avl` <i>without</i> dynamic allocations of keys or values.

```
==== 100 items per round ====

$ time ./avl_test --num_loops=2000 --num_items_per_loop=100 --use_avl=true
rea [...]

2021-03-03 18:49 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/subchannel.cc, line 706 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp6hQGA2gRj9JpW4oT:-MUtPl9ADcP0QPRE4txw:b-k7v037) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L706)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Once you move it into the `Subchannel` object, you can access it as `c->key_` for the call to `RegisterSubchannel()`.  (This function may be a static method, but it's still a member of the `Subchannel` class, so it can access the private data members  of the `Subchannel` object.)
</blockquote></details>

Ah, good point. Done.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 789 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUpA1OqDMQ81YvA90Yx:-MUtPnsv3pYeKoZu13EU:b-ywoe84) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L789)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

Whoops, I put this tracing info on the unref but not on the ref. Done.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 936 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUpB5eB223YTQzpmgFW:-MUtPstl5kt6l95RrG-p:b-x9c7yu) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L936)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

Sorry, done now.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 1068 at r4](https://reviewable.io/reviews/grpc/grpc/25485#-MUtGuK990618vwKash3:-MUtPue_10bzexJMAqEf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/38b4dea752c6edab6d62e7ef294734aee38ad7ed/src/core/ext/filters/client_channel/subchannel.cc#L1068)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `WeakRef(DEBUG_LOCATION, "state_watcher")`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-03 18:50 UTC, apolcyn commented
Thanks for the review!

2021-03-03 19:59 UTC, markdroth approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485)* status: all files reviewed, 1 unresolved discussion (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/subchannel.cc, line 706 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp6hQGA2gRj9JpW4oT:-MUteuqt3yuCZAR7QcRB:bdwewng) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L706)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Ah, good point. Done.
</blockquote></details>

Note that in order to make this useful, you also need to change the `Subchannel` ctor to take the parameter by value instead of as a reference.


<!-- Sent from Reviewable.io -->

2021-03-03 20:00 UTC, markdroth approved these changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485)* status: all files reviewed, 2 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/subchannel.cc, line 655 at r5](https://reviewable.io/reviews/grpc/grpc/25485#-MUtfFWS0JmYeW9qKpAy:-MUtfFWS0JmYeW9qKpAz:b-yosv7h) ([raw file](https://github.com/grpc/grpc/blob/93e795dd64ee478795397b82b86e1890b88bd673/src/core/ext/filters/client_channel/subchannel.cc#L655)):*
> ```cpp
>           GRPC_TRACE_FLAG_ENABLED(grpc_trace_subchannel_refcount) ? "Subchannel"
>                                                                   : nullptr),
>       key_(key),
> ```

Also, this will need to use `std::move()`.


<!-- Sent from Reviewable.io -->

2021-03-03 20:36 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485)* status: all files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/subchannel.cc, line 706 at r3](https://reviewable.io/reviews/grpc/grpc/25485#-MUp6hQGA2gRj9JpW4oT:-MUtnd1n-oKDWyuQb_ZX:bb7f2mf) ([raw file](https://github.com/grpc/grpc/blob/c004b6048d34c900f8ba0d84fc880d91e70ac0c4/src/core/ext/filters/client_channel/subchannel.cc#L706)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Note that in order to make this useful, you also need to change the `Subchannel` ctor to take the parameter by value instead of as a reference.
</blockquote></details>

done
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 655 at r5](https://reviewable.io/reviews/grpc/grpc/25485#-MUtfFWS0JmYeW9qKpAy:-MUtneCN1FslqOQAFum4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/93e795dd64ee478795397b82b86e1890b88bd673/src/core/ext/filters/client_channel/subchannel.cc#L655)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Also, this will need to use `std::move()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-03 20:44 UTC, markdroth approved these changes
Looks great!

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25485#-:-MUtpLlO2W1CQyZE5fOd:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-04 02:09 UTC, lidizheng commented
CC @lidizheng

2021-03-04 05:35 UTC, apolcyn commented
Force pushed to manually fix rebase conflicts on some early commits related to submodule versions

2021-03-05 03:26 UTC, apolcyn commented
python macos failure is https://github.com/grpc/grpc/issues/25368
ios binary size diff failure is https://github.com/grpc/grpc/issues/25431

2021-03-05 04:29 UTC, merged