Client context test peer
grpc/grpc pull request #25610
Opened 2021-03-04 01:20 UTC by shangwu-google

A mock up class for testing client context.

@vjpai

2021-03-04 16:40 UTC, vjpai requested changes
In addition to my comments, do you have a unit test for the test peer? I think we have a test peer unit test for the ServerContextTestSpouse.

2021-03-04 16:40 UTC, vjpai commented on include/grpcpp/test/client_context_test_peer.h
> +  /// Inject metadata to the ClientContext for the test. The test spouse
peer

2021-03-04 16:40 UTC, vjpai commented on include/grpcpp/test/client_context_test_peer.h
> +  /// ##must be alive when \ a ClientContext::recv_initial_metadata is called.
Also the method is called GetServerInitialMetadata

2021-03-04 18:00 UTC, shangwu-google commented on include/grpcpp/test/client_context_test_peer.h
> +  /// Inject metadata to the ClientContext for the test. The test spouse
Done. Thanks for the catch.

2021-03-04 18:17 UTC, shangwu-google commented on include/grpcpp/test/client_context_test_peer.h
> +  /// ##must be alive when \ a ClientContext::recv_initial_metadata is called.
Done. Thanks.

2021-03-05 06:54 UTC, shangwu-google commented
@vjpai Unit test for client_context_test_peer.h is added. Thanks for the attention.

2021-03-16 17:18 UTC, vjpai approved these changes
LGTM. grpc::testing is not considered API, so this is ok for merging without a gRFC.

2021-03-16 17:35 UTC, vjpai commented
Have you run `tools/buildgen/generate_projects.sh` ? Looks like some parts of it are still missing.

2021-04-15 17:36 UTC, vjpai commented
Following up: what is the status here? It looks like the change requested in my previous commit was never added, and the PR is now in a conflict state.

2021-05-07 19:34 UTC, shangwu-google commented
> Have you run `tools/buildgen/generate_projects.sh` ? Looks like some parts of it are still missing.

Could you take another look? I've fixed the conflict part and the system check is passed. However, when I ran `tools/buildgen/generate_projects.sh`, I got quite a few errors related to grpc_python_dependencies as follows
```
error loading package 'src/proto/grpc/testing': Unable to find package for @grpc_python_dependencies//:requirements.bzl: The repository '@grpc_python_dependencies' could not be resolved. and referenced by '//test/cpp/util:metrics_server_lib'
```

2021-05-13 19:58 UTC, lidizheng commented
@shangwu-google Many build failed due to compilation errors, PTAL.

2021-05-26 01:50 UTC, vjpai commented
This is building now. I think it's mergeable.

2021-05-26 01:51 UTC, vjpai commented
@nupurkot I'm going to merge this.

2021-05-26 01:51 UTC, merged

2021-06-01 22:17 UTC, nupurkot commented
> @nupurkot I'm going to merge this.

Thanks @vjpai for taking care of this!