custom verification proposed C core changes
grpc/grpc pull request #25631
Opened 2021-03-05 07:30 UTC by ZhenLian

2021-03-05 08:14 UTC, ZhenLian reviewed
Hi Mark, this PR is far from ready yet, but could you please take a first glance(especially at `grpc_tls_custom_verification_check_request` and the hostname verifier) since it contains a lot of changes not reflected in the design? Just wanted to make sure I am not going too far away from the correct direction...
Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MV0QsWr0kI5W26X06B-:b-hmi00y)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2021-03-16 07:30 UTC, ZhenLian reviewed
Mark, the latest push contains all the changes and tests I'd like to make in core. I manually tested all the tests, and they all passed locally. This PR contains many changes that we haven't covered in the design doc, so I will push out for review first and then start to work on the C++ part.
There is one particular thing I want to mention here: in security_handshaker.cc, we will have mutex deadlock problem in e2e tests if we don't comment out the mutex locking code as I did in this PR. I think that was due to the fact that in `OnHandshakeDataReceivedFromPeerFn` and `OnHandshakeDataSentToPeerFn` we hold the lock, and later in `OnPeerCheckedInner` we were trying to grab the lock again. One possible way to solve this is to grant finer locks, but I am not sure how to do that exactly.
I've attached the log: https://gist.github.com/ZhenLian/c8a8ad5630f1aab85f274ff397f88217.
Feel free to take a look and let me know if you have any questions. Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MVttAwtDO2iCE4pfNiK:b-wkjxqk)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @jiangtaoli2016 and @markdroth)



<!-- Sent from Reviewable.io -->

2021-03-19 22:13 UTC, markdroth requested changes
This looks like a good start!

Please let me know if you have any questions.  Thanks!

> Reviewed 7 of 13 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MWBY7Xd33WbOGQANptL:bntdxje)* status: all files reviewed, 68 unresolved discussions (waiting on @jiangtaoli2016 and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 915 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5tTPZE3P9FSBqePsX:-MW5tTPZE3P9FSBqePsY:b-lst5sd) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L915)):*
> ```objc
> /**
>  * The request information exposed in a verification call.
>  * It would only stay within the check_peer() call of the security connector.
> ```

The security connector is an internal implementation detail, not something that should be described as part of this API.  I think this line can just be removed.
___
*[include/grpc/grpc_security.h, line 920 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5xY7VBszoBY8snhTR:-MW5xY7VBszoBY8snhTS:b-keretg) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L920)):*
> ```objc
>  * object at the end of custom verification.
>  */
> struct grpc_tls_custom_verification_check_request {
> ```

Please note on every new struct, type, and function that they are experimental.
___
*[include/grpc/grpc_security.h, line 924 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5t4bkAu3ZciUXXkjl:-MW5t4bkAu3ZciUXXkjm:b-7ax4bo) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L924)):*
> ```objc
>   /* The target name of the server when the client initiates the connection. */
>   /* This field will be nullptr if on the server side. */
>   const char* target_name = nullptr;
> ```

Unfortunately, I don't think it's legal in old-style C to initialize data members where they are defined.  We'll need to set these all manually inside of core when we create an instance of this struct.
___
*[include/grpc/grpc_security.h, line 975 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5uE_6C5wEPL5z-zp1:-MW5uE_6C5wEPL5z-zp2:b-pozy5n) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L975)):*
> ```objc
>  */
> struct grpc_tls_certificate_verifier_external {
>   void* user_data;
> ```

Why do we need this?  I thought we decided in the design that we don't need it, because implementations can use the address of the `grpc_tls_certificate_verifier_external` struct instead.

If we keep this, please document what it's for.
___
*[include/grpc/grpc_security.h, line 982 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5uXsn9y8DFcqPJU7_:-MW5uXsn9y8DFcqPJU7a:b-bz787p) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L982)):*
> ```objc
>    * external_verifier: a pointer to the struct itself
>    * request: request information exposed to the function implementer.
>    * user_data: used for binding any caller-specified states. Whatever passed
> ```

If `user_data` is stored in `grpc_tls_certificate_verifier_external` and we're already passing a pointer to that struct to these methods, then why do we need to pass `user_data` as a separate parameter?  Can't the implementation just access it as `external_verifier->user_data`?

Or better yet, if we actually do need `user_data`, then why pass the `grpc_tls_certificate_verifier_external` struct to these methods at all?  Why not just pass `user_data` instead, since that's the only field from the struct that the implementations will ever actually use?

Whichever of these two arguments we keep should be the first argument to all three methods, since they're basically the "self" pointer.
___
*[include/grpc/grpc_security.h, line 993 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5xzPJ1XnsQFfrXixh:-MW5xzPJ1XnsQFfrXixi:btz2yb0) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L993)):*
> ```objc
>    * grpc_tls_certificate_verifier_external during construction time can be
>    * retrieved later here.
>    * return: return a non-zero value if |verify| is expected to be executed
> ```

We need to explicitly document the requirement that the implementation of this method must not invoke the async callback in the thread in which it's invoked before it returns.  That can lead to deadlocks.
___
*[include/grpc/grpc_security.h, line 1004 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5yRt5Al7Da6B6c8ia:-MW5yRt5Al7Da6B6c8ib:bocuuxa) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L1004)):*
> ```objc
>    * verifier is still running but the whole connection got cancelled. This
>    * could happen when the verifier is doing some async operations, and the
>    * whole handshaker object got destroyed because of connetion time limit is
> ```

s/connetion/connection/
___
*[include/grpc/grpc_security.h, line 1009 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5ybjTBnTRkmhslxZ_:-MW5ybjTBnTRkmhslxZa:b-z8pgv2) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L1009)):*
> ```objc
>    *
>    * external_verifier: a pointer to the struct itself.
>    * request: request information exposed to the function implementer.
> ```

We need to document that this will be the same request object that was passed to verify(), and that it tells the verifier which request to cancel.
___
*[include/grpc/grpc_security.h, line 1046 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5xqDX2txTcC2HvHBO:-MW5xqDX2txTcC2HvHBP:b-fyyo0j) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L1046)):*
> ```objc
>  * check.
>  */
> grpc_tls_certificate_verifier* grpc_tls_certificate_verifier_host_name_create();
> ```

Do we also need to declare the one for the SAN verifier?  Or is that not included in this PR?
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 22 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5zhOC8gsMbJBrq9T8:-MW5zhODAR1pq8nx8aOV:b-nwjrls) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L22)):*
> ```objc
> #include <grpc/support/port_platform.h>
> 
> #include <grpc/grpc_security.h>
> ```

This include should be moved down to after the absl include.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 47 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW68b4o57IPFoNASOBS:-MW68b4p-hlHbUMS3V3L:b-glq6nd) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L47)):*
> ```objc
>   // Otherwise, populate the results synchronously and return false.
>   // The caller is expected to populate verification results by setting request.
>   virtual bool Verify(grpc_tls_custom_verification_check_request* request,
> ```

The internal API was supposed to take a struct that contained both this request struct and a ref to the security connector.  Why didn't we do that?

We do need to make sure that we're holding a ref to the security connector until this request is complete.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 48 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWApTDwAnc9fmXfCYpn:-MWApTDwAnc9fmXfCYpo:brvii4p) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L48)):*
> ```objc
>   // The caller is expected to populate verification results by setting r [...]

2021-03-29 06:18 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: all files reviewed, 68 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 74 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW67pWbEL3Kq_oV4b63:-MWwbqTV58FkqMJJN71I:b-vncy3h) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/xds/xds_credentials.cc#L74)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Should `XdsVerifySubjectAlternativeNames()` take a parameter that tells it which type of SANs it's being given?  @yashykt 
</blockquote></details>

Sorry I missed this earlier. Yes, we would ideally want to know whether the SAN has a DNS type or not. The SAN matcher should only be doing a DNS style verification (for example, wildcard matching) for DNS names.


<!-- Sent from Reviewable.io -->

2021-04-07 23:13 UTC, ZhenLian reviewed
Thanks @markdroth for the carefully review, and sorry for the delay of this PR! It took me some time to resolve some of the threading issues while using the shared verifier classes for all the tests. The tests look much cleaner now.
I've replied to almost all the comments, but let me make a quick summary:

These things will go into another PR:
1. (optional) slight change the SAN name verification logic to match the old verification implementation
2. security connector's cancel() function
3. plumbings of more SAN fields and their types in TSI

I will do 2 next, and depending on the reply will probably do 1. For 3, Ashitha had a PR(https://github.com/grpc/grpc/pull/25874) to plumb DNS field which should meet xds's case, but the way we plumb is not very clean and in our case here we need all other fields(ip address, etc). I will need to talk to @jiangtaoli2016 to see how we want to proceed.
This PR still has some pending comments in the main code that might change the overall structure significantly. I will be working on the C++ implementation once those comments are solved.
Thanks again for the guidance!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MX9FMCvBufXTPOv7_m3:b-pqlgev)* status: 4 of 17 files reviewed, 68 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 915 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5tTPZE3P9FSBqePsX:-MWthBMK0arMXIkpERIV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L915)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The security connector is an internal implementation detail, not something that should be described as part of this API.  I think this line can just be removed.
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 920 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5xY7VBszoBY8snhTR:-MWtjEy4CLDxHFw_RMVk:b9lsn7y) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L920)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please note on every new struct, type, and function that they are experimental.
</blockquote></details>

Sounds good! I changed all the TLS cred API to the new form with a `EXPERIMENTAL API - Subject to change` header. I think it might be more concise.
___
*[include/grpc/grpc_security.h, line 924 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5t4bkAu3ZciUXXkjl:-MX43OEQD4Z7CAKGRKeu:b-uahj3l) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L924)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Unfortunately, I don't think it's legal in old-style C to initialize data members where they are defined.  We'll need to set these all manually inside of core when we create an instance of this struct.
</blockquote></details>

Done. I added one `CertificateVerificationRequestInit` function in `grpc_tls_certificate_verifier.h` for the set up work.
___
*[include/grpc/grpc_security.h, line 975 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5uE_6C5wEPL5z-zp1:-MX43s-_DEekxsQOCQCr:b-tv3qws) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L975)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why do we need this?  I thought we decided in the design that we don't need it, because implementations can use the address of the `grpc_tls_certificate_verifier_external` struct instead.

If we keep this, please document what it's for.
</blockquote></details>

Yeah, this is mainly used for the tests to pass some extra data when constructing  `grpc_tls_certificate_verifier_external`, and then retrieve it in `verify` or `destruct` functions. 
For example in `grpc_tls_certificate_verifier_test.cc`, I want to start a thread in the `verify` function and return immediately(kind of like simulating how the async mode works), and later in the `destruct` or main thread to join this thread to avoid memory leaks. I don't have a good idea how to achieve this using the old design, since there is no way to make a connection among `verify`, `destruct` and the main thread. So my solution is to have this user_data to be the bridge of three of them. In that test, we will create a dummy thread memory in main thread, and pass it through user_data; in `verify`, we will replace that thread memory with the actual memory we want to run, and then when back to the main thread we will join that thread. This is a bit ugly but is the best way I could think of.
And it becomes even more useful when it comes to e2e tests. in `h2_tls.cc`, we are passing `fullstack_secure_fixture_data` to the user_data so that we can access it in any of the member functions of the external verifier.
___
*[include/grpc/grpc_security.h, line 982 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5uXsn9y8DFcqPJU7_:-MX8hPDv3YX7AAwWnOy4:b-19t50x) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L982)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If `user_data` is stored in `grpc_tls_certificate_verifier_external` and we're already passing a pointer to that struct to these methods, then why do we need to pass `user_data` as a separate parameter?  Can't the implementation just access it as `external_verifier->user_data`?

Or better yet, if we actually do need `user_data`, then why pass the `grpc_tls_certificate_verifier_external` struct to these methods at all?  Why not just pass `user_data` instead, since that's the only field from the struct that the implementations will ever actually use?

Whichever of these two arguments we keep should be the first argument to all three methods, since they're basically the "self" pointer.
</blockquote></details>

Sure, I updated the `user_data` to be the first parameter and removed the `grpc_tls_certificate_verifier_external` parameter.
___
*[include/grpc/grpc_security.h, line 993 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5xzPJ1XnsQFfrXixh:-MX8iT-h61SPojP7lT1A:b-brrno) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L993)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We need to explicitly document the requirement that the implementation of this method must not invoke the async callback in the thread in which it's invoked before it returns.  That can lead to deadlocks.
</blockquote></details>

SG. I added some lines at the beginning of this comment.
___
*[include/grpc/grpc_security.h, line 1004 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5yRt5Al7Da6B6c8ia:-MX8itp33fJPglB37SMV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L1004)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/connetion/connection/
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 1009 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5ybjTBnTRkmhslxZ_:-MX8jEwl0Lc5dnK5C6Dl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L1009)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We need to document that this will be the same request object that was passed to verify(), and that it tells the verifier which request to cancel.
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 1046 at r2](https://reviewable.io/reviews/grpc/grpc/25631# [...]

2021-04-08 23:58 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: 4 of 19 files reviewed, 68 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 222 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW6G2Zz7kyyfebbr07Y:-MXnuDGY3aIXo8sf4wAh:bfn7tv4) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L222)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sorry,  I didn't see anywhere else you wanted me to have a map of pending `check_peer()` requests in the security connector. Did I miss it?
In my original design, I made a copy of every peer information string in `grpc_tls_custom_verification_check_request` because `tsi_peer` is a bit hard to parse and extract information from(from the user's perspective). 
`grpc_tls_custom_verification_check_request` is in the core API(`grpc_security.h`). If we store TSI peer pointers directly in  `grpc_tls_custom_verification_check_request`, that will mean the callers will need to extract information from `tsi_peer*`. Are we OK with that?

</blockquote></details>

Oh, for the first part, I just saw the place where you wanted to me have a map in the security connector, as I was adding a `cancel_check_peer` function in another PR. So I am now clear on that part.
I still have some concerns on exposing `tsi_peer*` directly in `grpc_security.h`. Hope I can get some clarifications on that. Thank you so much!


<!-- Sent from Reviewable.io -->

2021-04-09 05:32 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: 4 of 19 files reviewed, 68 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 51 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW61W9K4vcPh3yon_Jj:-MXp62lqCoPaoDiUlsRa:bai1ld0) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L51)):*
> virtual void cancel_check_peer(grpc_closure* on_peer_checked) = 0;
BTW, I noticed that the `cancel_check_host` function was defined with an extra `grpc_error` param.
Maybe we can also have something like:
`virtual void cancel_check_peer(grpc_closure* on_peer_checked, grpc_error* error) = 0;`?


<!-- Sent from Reviewable.io -->

2021-04-09 20:50 UTC, markdroth requested changes
This is moving in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 9 of 14 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MXsO_Ev4PHSfMef1aJD:b-k1b92a)* status: all files reviewed, 41 unresolved discussions (waiting on @jiangtaoli2016 and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 924 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5t4bkAu3ZciUXXkjl:-MXrHjaW0mKt9aGAarcg:b1bdz46) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L924)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Done. I added one `CertificateVerificationRequestInit` function in `grpc_tls_certificate_verifier.h` for the set up work.
</blockquote></details>

Still need to remove the `= nullptr` or `= 0` on all of the fields here.  That's not legal in C89.
___
*[include/grpc/grpc_security.h, line 975 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5uE_6C5wEPL5z-zp1:-MXrIoej8jDa6pi49G3p:b-2dxvbf) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L975)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Yeah, this is mainly used for the tests to pass some extra data when constructing  `grpc_tls_certificate_verifier_external`, and then retrieve it in `verify` or `destruct` functions. 
For example in `grpc_tls_certificate_verifier_test.cc`, I want to start a thread in the `verify` function and return immediately(kind of like simulating how the async mode works), and later in the `destruct` or main thread to join this thread to avoid memory leaks. I don't have a good idea how to achieve this using the old design, since there is no way to make a connection among `verify`, `destruct` and the main thread. So my solution is to have this user_data to be the bridge of three of them. In that test, we will create a dummy thread memory in main thread, and pass it through user_data; in `verify`, we will replace that thread memory with the actual memory we want to run, and then when back to the main thread we will join that thread. This is a bit ugly but is the best way I could think of.
And it becomes even more useful when it comes to e2e tests. in `h2_tls.cc`, we are passing `fullstack_secure_fixture_data` to the user_data so that we can access it in any of the member functions of the external verifier.
</blockquote></details>

I don't see why any of this requires a separate `user_data` pointer.  Anything you can do by having `user_data` here you can also do without `user_data` by storing that same pointer in the wrapping-layer object that contains the `grpc_tls_verifier_external` struct.

That having been said, I'm fine with this approach.  It does allow the caller to not have to play pointer games with the `grpc_tls_certificate_external_verifier` struct being the first data member of the wrapping-layer object.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 48 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWApTDwAnc9fmXfCYpn:-MXrMZqs2b7qrZ03wZ0m:bd6195z) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L48)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Currently the callback will only be invoked when executed in the async mode(when we return `true` for the Verify() function). Just to make sure I understand, we will need to also invoke the callback in sync mode if we change this way, right?
</blockquote></details>

No, it won't work to use the callback in sync mode, because the callback function would not know whether it was being called synchronously or asynchronously, and its behavior would need to be different in the two cases (e.g., in terms of avoiding mutex deadlocks and the need to create an `ExecCtx`).

Instead, I think we would need to add an `absl::Status*` output parameter to the function.  For sync returns, the verifier will return the status via the output parameter and return true; for async returns, it will return false and then pass the status via the callback later.

Note that this is consistent with what we do in existing APIs such as [`grpc_channel_security_connector::check_call_host()`](https://github.com/grpc/grpc/blob/912515384e069c8e99ebe7be5eda3105b080bf11/src/core/lib/security/security_connector/security_connector.h#L103) (although that uses `grpc_error` instead of `absl::Status`).
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 51 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW61W9K4vcPh3yon_Jj:-MXrPAm4AtHbjfpKvrZH:b-s0os26) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L51)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

> virtual void cancel_check_peer(grpc_closure* on_peer_checked) = 0;
BTW, I noticed that the `cancel_check_host` function was defined with an extra `grpc_error` param.
Maybe we can also have something like:
`virtual void cancel_check_peer(grpc_closure* on_peer_checked, grpc_error* error) = 0;`?
</blockquote></details>

Yes, passing in the error for cancellation is a good idea.  Looks like you're doing that in #25941.

Is the plan here is to merge #25941 first, then merge those changes into this PR?  Or will you handle the cancellation code in a third PR that depends on both this PR and #25941?
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 74 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW6-PSRAfzSNXDkBALM:-MXrQiGu4OTBVchiI0Rc:b-6lpxbb) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L74)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Ah I see. I think we talked about this before when designing the `error_details` field in `grpc_tls_custom_verification_check_request`. I updated the code based on the suggestions.
Just to confirm,  in core API,  that will mean we are actually not able to ask the callers to pass their ownership and we later clean up the resource for them, without the help of `gpr_*` functions, right? From my understanding this kind of ownership design will always have similar problems. We will need to either ask them to allocate the object in a common grpc space trough `gpr_*`, or ask them to write a clean-up callback function(just like the way we are doing here).
</blockquote></details>

Yes.  To say this another way, any time something needs to be allocated by the application and then owned by core, there are only two options:

1. Require the caller to allocate it via core using `gpr_malloc()`, so that core can internally delete it via `gpr_free()`.
2. Allow the caller to allocate it externally however they want, and provide a destruction callback so that core can tell the caller when to destroy it.

Option 1 does the allocation and deallocation on the core side; option 2 does the allocation and deallocation on the caller side.  It doesn't really matter which side they happen on, as long as they both happen on the same side.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 45 at r4](https://reviewable.io/reviews/grpc/grpc/25631#-MXrM0Io2P9eaLfZ7nYA:-MXrM0Io2P9eaLfZ7nYB:b-p5014n) ([raw file](https://github.com/grpc/grpc/blob/20570f4d4e54c6e3eb4279ebda337172c5f64aa4/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L45)):*
> ```objc
>   }
> 
>   CertificateVerificationRequest(RefCountedPtr<grpc_security_connector> sc)
> ```

Single-argument ctors need to be declared `explicit`, as per:

https://google.github.io/styleguide/cppguide.html#Implici [...]

2021-04-20 21:17 UTC, ZhenLian reviewed
Thanks for the detailed review, Mark! 
Please see my replies in comments. There is still one outstanding question(whether we want to make a copy of request field, or simply point to `tsi_peer`) that might change the core interface. I will work on the C++ implementation once that is addressed.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MYl3xPX2nQ4BXKkZygl:b-vtvb4h)* status: 8 of 20 files reviewed, 41 unresolved discussions (waiting on @jiangtaoli2016 and @markdroth)

___
*[include/grpc/grpc_security.h, line 924 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5t4bkAu3ZciUXXkjl:-MXt9PcmCpMP--H8gjSn:b-8omiww) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L924)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Still need to remove the `= nullptr` or `= 0` on all of the fields here.  That's not legal in C89.
</blockquote></details>

Sorry, I forgot to clean this up. Updated.
___
*[include/grpc/grpc_security.h, line 975 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW5uE_6C5wEPL5z-zp1:-MXtBbNQ280iA2SrSefJ:bp19wr1) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/include/grpc/grpc_security.h#L975)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see why any of this requires a separate `user_data` pointer.  Anything you can do by having `user_data` here you can also do without `user_data` by storing that same pointer in the wrapping-layer object that contains the `grpc_tls_verifier_external` struct.

That having been said, I'm fine with this approach.  It does allow the caller to not have to play pointer games with the `grpc_tls_certificate_external_verifier` struct being the first data member of the wrapping-layer object.
</blockquote></details>

Yeah, you are right. I think  I was not used to design classes utilizing that first-data-member memory tricks. Having a `user_data` makes me understand things much easier :)
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 48 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWApTDwAnc9fmXfCYpn:-MY2bmrT5o-CqEPaV-eD:b2fbmgl) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No, it won't work to use the callback in sync mode, because the callback function would not know whether it was being called synchronously or asynchronously, and its behavior would need to be different in the two cases (e.g., in terms of avoiding mutex deadlocks and the need to create an `ExecCtx`).

Instead, I think we would need to add an `absl::Status*` output parameter to the function.  For sync returns, the verifier will return the status via the output parameter and return true; for async returns, it will return false and then pass the status via the callback later.

Note that this is consistent with what we do in existing APIs such as [`grpc_channel_security_connector::check_call_host()`](https://github.com/grpc/grpc/blob/912515384e069c8e99ebe7be5eda3105b080bf11/src/core/lib/security/security_connector/security_connector.h#L103) (although that uses `grpc_error` instead of `absl::Status`).
</blockquote></details>

OK, I think I get the idea. Just one more thing to confirm: is the parameter going to be an `absl::Status**`instead of `absl::Status*`(just like in `check_call_host()` we are using `grpc_error**`)?
I could be wrong, but my current understanding is like this: if the parameter is defined as `absl::Status*`, then it will mean the caller will only need to feed in an `absl::Status` on stack and the `Verify(...., absl::Status*)` function should finish before the stack variable goes out of scope; but in our case we cannot use a stack variable because of the async nature; we have to create one with `new` and in `Verify(...., absl::Status**)` clean up the old memory and change the pointer to point to a new address. Is that right?

(If `absl::Status**` is needed, then would `grpc_error**` be better? Since it seems there are very rare cases which use a pointer to a pointer to`absl::Status`...)
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 51 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW61W9K4vcPh3yon_Jj:-MY2gwce4yVsCq0y6gXz:brwzxgs) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes, passing in the error for cancellation is a good idea.  Looks like you're doing that in #25941.

Is the plan here is to merge #25941 first, then merge those changes into this PR?  Or will you handle the cancellation code in a third PR that depends on both this PR and #25941?
</blockquote></details>

Sounds good! I plan to merge #25941 first, and then merge those changes into this PR.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 74 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW6-PSRAfzSNXDkBALM:-MY2lXDl1yVO_kS3IU3g:b-1qgyhv) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L74)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes.  To say this another way, any time something needs to be allocated by the application and then owned by core, there are only two options:

1. Require the caller to allocate it via core using `gpr_malloc()`, so that core can internally delete it via `gpr_free()`.
2. Allow the caller to allocate it externally however they want, and provide a destruction callback so that core can tell the caller when to destroy it.

Option 1 does the allocation and deallocation on the core side; option 2 does the allocation and deallocation on the caller side.  It doesn't really matter which side they happen on, as long as they both happen on the same side.
</blockquote></details>

Got it! Thank you so much for the great summary!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 45 at r4](https://reviewable.io/reviews/grpc/grpc/25631#-MXrM0Io2P9eaLfZ7nYA:-MXtDdGg2rglqq9Q-jK0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/20570f4d4e54c6e3eb4279ebda337172c5f64aa4/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L45)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Single-argument ctors need to be declared `explicit`, as per:

https://google.github.io/styleguide/cppguide.html#Implicit_Conversions
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 56 at r4](https://reviewable.io/reviews/grpc/grpc/25631#-MXrLnsP1P2XJ5PjffFQ:-MY26y4fB1qznY7k93xd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/20570f4d4e54c6e3eb4279ebda337172c5f64aa4/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why do we need these as separate static methods?  Can't we just do this initialization and destruction in the ctor and dtor directly?
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 82 at r4](https://reviewable.io/reviews/grpc/grpc/25631#-MXrNd5_8tq_YLmK1UGS:-MY2I4CgEQcoOOdETmIQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/20570f4d4e54c6e3eb4279ebda337172c5f64aa4/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L82)):*
<details><summary><i>Previously, markdroth (Mark  [...]

2021-04-21 22:36 UTC, markdroth requested changes
This is moving in the right direction.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 6 files at r5, 4 of 10 files at r6, 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MYqZzeD72YZX9O6HED7:b-qjvg5x)* status: all files reviewed, 45 unresolved discussions (waiting on @jiangtaoli2016, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 48 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWApTDwAnc9fmXfCYpn:-MYpZGmB-55lLK56owDs:b3kkg76) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L48)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

OK, I think I get the idea. Just one more thing to confirm: is the parameter going to be an `absl::Status**`instead of `absl::Status*`(just like in `check_call_host()` we are using `grpc_error**`)?
I could be wrong, but my current understanding is like this: if the parameter is defined as `absl::Status*`, then it will mean the caller will only need to feed in an `absl::Status` on stack and the `Verify(...., absl::Status*)` function should finish before the stack variable goes out of scope; but in our case we cannot use a stack variable because of the async nature; we have to create one with `new` and in `Verify(...., absl::Status**)` clean up the old memory and change the pointer to point to a new address. Is that right?

(If `absl::Status**` is needed, then would `grpc_error**` be better? Since it seems there are very rare cases which use a pointer to a pointer to`absl::Status`...)

</blockquote></details>

`absl::Status` replaces `grpc_error*`.  So while `check_call_host()` uses `grpc_error**`, here we would use `absl::Status*`.

There is no need to dynamically allocate the `absl::Status`.  In the async case, the local status variable will not be used; instead, the status will be passed to the callback.  This is exactly how `check_call_host()` works: the `grpc_error**` parameter is used only in the sync case; in the async case, the error is passed to the callback.

The idea here is that we should be able to do this:

```
absl::Status status;
bool is_done = certificate_verifier->Verify(&request, cb, &status);
if (is_done) {
  if (!status.ok()) {
    // ...verification failed...
  } else {
    // ...verification succeeded...
  }
} else {
  // async, wait for callback
  // (local status variable not used; status will be passed to callback)
}
```

Note that we're ultimately going to be completely replacing `grpc_error*` with `absl::Status` everywhere in our code-base, so this is consistent with our long-term direction.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 51 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW61W9K4vcPh3yon_Jj:-MYpa8k35mMIb3PG9VLJ:b1phzba) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L51)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sounds good! I plan to merge #25941 first, and then merge those changes into this PR.
</blockquote></details>

Looks like #25941 has been merged, so you should be able to make these changes now.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 37 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpYxsv0vUNlVmT52lU:-MYpYxsv0vUNlVmT52lV:b-53lk8l) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L37)):*
> ```objc
> 
> // The abstract class of a pending request.
> class PendingVerifierRequest {
> ```

I think this can now be moved into the security connector code.  Now that it's not part of the `grpc_tls_certificate_verifier` API, it shouldn't be needed outside of the security connector.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 44 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpY7lmDajsXsh13ljX:-MYpY7lmDajsXsh13ljY:b2qknl7) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L44)):*
> ```objc
> 
>   // Starts the synchronous or asynchronous verification.
>   virtual void Start() = 0;
> ```

Why is this `virtual`?  We should not be subclassing this class.

If we *are* going to subclassing this, then the dtor needs to be `virtual` as well.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 53 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpXT4L26m-B2LMf7Pz:-MYpXT4L26m-B2LMf7Q-:b56nfrd) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L53)):*
> ```objc
>       grpc_tls_custom_verification_check_request* request);
> 
>  protected:
> ```

Data members must be private, as per the style guide:

https://google.github.io/styleguide/cppguide.html#Access_Control

It's not clear to me why these are protected in the first place.  As I mentioned above, I don't think we should be creating any subclasses of this class.

If these do need to be accessed in a subclass, then you'll need to add protected accessor methods.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 106 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW627ff74C_s0aOLFG5:-MYpdFrF-XmcOT0C0m4Y:b-d7s2ka) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L106)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Haha, got it. I think this is just a minor difference. The old logic will treat `*.com` as an invalid case, but the new logic will treat it as valid. `.*` is invalid in both cases, though. So I think the question is actually if we want to allow `*` in the second level domain.  
I thought in a real production environment, it would be rare(and a bit suspicious) to have  a cert with `*.com`, but the application should be fine if designed with proper authentication and revocation infrastructure.
</blockquote></details>

I could go either way on this, but I suspect that we should be consistent between the xDS and non-xDS use-cases.  @yashykt may have insight as to the requirements in the xDS case.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 51 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpbusq--88Lr0yoLzq:-MYpbusq--88Lr0yoLzr:b-nazv9) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L51)):*
> ```cpp
>   // We will make a copy of each field and destroy them when request_ is
>   // destroyed.
>   // TODO(ZhenLian): avoid the copy when the underlying core implementation used
> ```

If we don't actually do this, then there's no point in storing the `tsi_peer` inside this object in the first place.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 77 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpam8H1ZkBJB19mOlV:-MYpam8H1ZkBJB19mOlW:bfjoq95) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L77)):*
> ```cpp
>       char* dns = CopyCoreString(prop->value.data, prop->value.length);
>       dns_names.emplace_back(dns);
>       continue;
> ```

No need for this.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 81 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpapUu-WW0--H5iqAQ:-MYpapUu-WW0--H5iqAR:bfjoq95) ([raw file](https://github. [...]

2021-04-26 07:29 UTC, ZhenLian reviewed
Thanks for the review! 
I haven't finished all the fixes, but I asked some follow-up questions and changed the code structure based on two significant problems mentioned. Could you please take a look at them first please? Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MZC3Y0z6mX_-0aMZd2n:b9pg3hc)* status: all files reviewed, 45 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 48 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWApTDwAnc9fmXfCYpn:-MYvt0Lq5judWPqK7I7i:bv0rblm) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`absl::Status` replaces `grpc_error*`.  So while `check_call_host()` uses `grpc_error**`, here we would use `absl::Status*`.

There is no need to dynamically allocate the `absl::Status`.  In the async case, the local status variable will not be used; instead, the status will be passed to the callback.  This is exactly how `check_call_host()` works: the `grpc_error**` parameter is used only in the sync case; in the async case, the error is passed to the callback.

The idea here is that we should be able to do this:

```
absl::Status status;
bool is_done = certificate_verifier->Verify(&request, cb, &status);
if (is_done) {
  if (!status.ok()) {
    // ...verification failed...
  } else {
    // ...verification succeeded...
  }
} else {
  // async, wait for callback
  // (local status variable not used; status will be passed to callback)
}
```

Note that we're ultimately going to be completely replacing `grpc_error*` with `absl::Status` everywhere in our code-base, so this is consistent with our long-term direction.
</blockquote></details>

Sounds good, thank you so much for the detailed explanation! I've updated the code. Could you please take a look to see if it is what you want?
Looking at this new way of structuring the code, I am wondering if it would make more sense to completely remove the `status` and `error_details` in `grpc_tls_custom_verification_check_request`, and add two output parameters for verify(), so that it becomes:
```
int (*verify)(void* user_data,
                grpc_tls_custom_verification_check_request* request,
                grpc_tls_on_custom_verification_check_done_cb callback,
                void* callback_arg, grpc_status* sync_status, char** sync_error_details);
```.
In our current implementation, the two fields in `request` are merely for sync verification, and the semantics of how to pass error out is a bit different from the classes that could use `absl::Status* `. It might be better to make the idea of how we pass error out consistent?
```

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 37 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpYxsv0vUNlVmT52lU:-MYviJz2B_8niefok795:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can now be moved into the security connector code.  Now that it's not part of the `grpc_tls_certificate_verifier` API, it shouldn't be needed outside of the security connector.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 44 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpY7lmDajsXsh13ljX:-MYvjKjH95FSZebDSIOg:b-l6qwo0) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this `virtual`?  We should not be subclassing this class.

If we *are* going to subclassing this, then the dtor needs to be `virtual` as well.
</blockquote></details>

I make this a pure virtual function because while implementing `Start()`, we will need to do `security_connector_->options_`. If in `PendingVerifierRequest` we decided to cache the base `grpc_security_connector`, we are not able to get the `options_`. We will need to cache concrete types `TlsChannelSecurityConnector` or `TlsServerSecurityConnector`.
I think there are many solutions. We could cache two of them, and in `Start()` we just use whichever is not empty. Or we could have a bool indicating whether on client side or server side, and  in `Start()` we cast that to concrete types. Can I know what do you suggest? 
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 51 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpbusq--88Lr0yoLzq:-MZBsxidBjxr8GTknXFX:blp1xc2) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we don't actually do this, then there's no point in storing the `tsi_peer` inside this object in the first place.
</blockquote></details>

I think we could do this if it makes sense. @jiangtaoli2016 is considering cleaning up the some of the TSI code-base, and I think it would be great if we could eliminate many of the old C code that uses pointer arithmetic,  non-null-terminated string, etc.
These type of work might be relatively easy; to make the code easier to maintain, we might want to restructure files like `ssl_transport_security.cc` to introduce class and inheritance design. Right now this file has so many components stuffed together, and becomes harder and harder to maintain. 
If these fields one day become null-terminated, I think it makes sense to directly take the pointers, since it saves space and doesn't change the API.
It is just from resource-wise that we didn't find a person who has bandwidth to do that. But yeah it's in our radar.


<!-- Sent from Reviewable.io -->

2021-04-27 20:00 UTC, markdroth requested changes
This is moving in the right direction.

Please let me know if you have any questions.  Thanks!

> Reviewed 10 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MZJujN88WRuBHxkpMxZ:b-qjvg5x)* status: all files reviewed, 54 unresolved discussions (waiting on @jiangtaoli2016, @yashykt, and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 1019 at r8](https://reviewable.io/reviews/grpc/grpc/25631#-MZJlnbC1TkaybcuqhRv:-MZJlnbC1TkaybcuqhRw:bcf0yh5) ([raw file](https://github.com/grpc/grpc/blob/addb7557e62172a862401814c32258c40f8f2cd4/include/grpc/grpc_security.h#L1019)):*
> ```objc
>    * false immediately, and then in the asynchronous thread invoke |callback|
>    * with the verification result. The implementer MUST NOT invoke the async
>    * |callback| before |verify| returns, otherwise it can lead to deadlocks.
> ```

Let's be a bit more precise here: The implementation must not invoke the async callback *in the same thread*  before `verify()` returns.  It's okay if the async callback is invoked in a different thread and happens to be called before `verify()` returns in the original thread.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 48 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWApTDwAnc9fmXfCYpn:-MZJm_A44CT9LjLkD03a:by5s5jd) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L48)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sounds good, thank you so much for the detailed explanation! I've updated the code. Could you please take a look to see if it is what you want?
Looking at this new way of structuring the code, I am wondering if it would make more sense to completely remove the `status` and `error_details` in `grpc_tls_custom_verification_check_request`, and add two output parameters for verify(), so that it becomes:
```
int (*verify)(void* user_data,
                grpc_tls_custom_verification_check_request* request,
                grpc_tls_on_custom_verification_check_done_cb callback,
                void* callback_arg, grpc_status* sync_status, char** sync_error_details);
```.
In our current implementation, the two fields in `request` are merely for sync verification, and the semantics of how to pass error out is a bit different from the classes that could use `absl::Status* `. It might be better to make the idea of how we pass error out consistent?


</blockquote></details>

Yes, I had intended that we remove the `status` and `error_details` fields from `grpc_tls_custom_verification_check_request` and instead return them from the `verify()` method, exactly as you described.

In other words, the semantics should be the same in the internal API and in the C-core API.  The only difference is that the C-core API uses a separate status code and string instead of using `absl::Status`.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 44 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpY7lmDajsXsh13ljX:-MZJtPps3bKMMzJfb_3O:b8zt884) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L44)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I make this a pure virtual function because while implementing `Start()`, we will need to do `security_connector_->options_`. If in `PendingVerifierRequest` we decided to cache the base `grpc_security_connector`, we are not able to get the `options_`. We will need to cache concrete types `TlsChannelSecurityConnector` or `TlsServerSecurityConnector`.
I think there are many solutions. We could cache two of them, and in `Start()` we just use whichever is not empty. Or we could have a bool indicating whether on client side or server side, and  in `Start()` we cast that to concrete types. Can I know what do you suggest? 
</blockquote></details>

See my comment in tls_security_connector.h line 222.  I don't think it's helpful to share the interface between the client and server in the first place.  The only part of the code that you're actually sharing between the two is the code to initialize the fields in the request struct and then free those fields later, and I think whatever sharing is needed there can be done via standalone helper functions.

In other words, I think that `TlsChannelSecurityConnector::ChannelPendingVerifierRequest` and `TlsServerSecurityConnector::ServerPendingVerifierRequest` should be independent classes instead of inheritting from the same base class.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 51 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpbusq--88Lr0yoLzq:-MZJuJvY80tqen-Dduw_:b-b27c97) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L51)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I think we could do this if it makes sense. @jiangtaoli2016 is considering cleaning up the some of the TSI code-base, and I think it would be great if we could eliminate many of the old C code that uses pointer arithmetic,  non-null-terminated string, etc.
These type of work might be relatively easy; to make the code easier to maintain, we might want to restructure files like `ssl_transport_security.cc` to introduce class and inheritance design. Right now this file has so many components stuffed together, and becomes harder and harder to maintain. 
If these fields one day become null-terminated, I think it makes sense to directly take the pointers, since it saves space and doesn't change the API.
It is just from resource-wise that we didn't find a person who has bandwidth to do that. But yeah it's in our radar.
</blockquote></details>

I agree with the long-term direction of changing the TSI API from C to C++.  However, I don't think that's actually a prerequisite for sharing these strings.  It seems like we should be able to change the existing C-based TSI implementation to generate nul-terminated strings even in the existing API.  Just change them to allocate one extra byte and populate it with nul.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 46 at r8](https://reviewable.io/reviews/grpc/grpc/25631#-MZJo2AL5ozRM5-ctNYm:-MZJo2AL5ozRM5-ctNYn:b-cwz1h) ([raw file](https://github.com/grpc/grpc/blob/addb7557e62172a862401814c32258c40f8f2cd4/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L46)):*
> ```cpp
>   if (is_done) {
>     if (request->status != GRPC_STATUS_OK) {
>       *sync_status = absl::Status(absl::StatusCode::kUnauthenticated,
> ```

This should use `request->status` rather than hard-coding `kUnauthenticated`.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 73 at r8](https://reviewable.io/reviews/grpc/grpc/25631#-MZJoJaG0Cvqs-qJcqz6:-MZJoJaG0Cvqs-qJcqz7:b-jur4al) ([raw file](https://github.com/grpc/grpc/blob/addb7557e62172a862401814c32258c40f8f2cd4/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L73)):*
> ```cpp
>     if (status != GRPC_STATUS_OK) {
>       return_status =
>           absl::Status(absl::StatusCode::kUnauthenticated, error_details);
> ```

This should use `status` instead of hard-coding `kUnauthenticated`.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 160 at r8](https://reviewable.io/reviews/grpc/grpc/25631#-MZJosXLC76_Qo4ti3sg:-MZJosXLC76_Qo4ti3sh:b-r12u7i) ([raw file](https://github.com/grpc/grpc/blob/addb7557e62172a862401814c32258c40f8f2cd4/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L160)):*
> ```cpp
>           callback(request, callback_arg, GRPC_STATUS_OK, "");
>         } else {
>           callback(request, callback_ar [...]

2021-05-05 07:08 UTC, ZhenLian reviewed
Thanks Mark for the review so far, and for bringing up the awesome test change to use a thread loop! I've fixed most of them.
I also added the C++ implementations, but haven't got a time to work on the test yet(but I've made sure they are at least syntax right). Feel free to take a look and see if you have any early comments on that, or it's also fine to wait for more tests to show up.
Thanks again!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MZvKVJJ0dzblCubpc1Z:bcr9h9p)* status: 5 of 20 files reviewed, 54 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @yashykt, and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 1019 at r8](https://reviewable.io/reviews/grpc/grpc/25631#-MZJlnbC1TkaybcuqhRv:-MZPNN3pBVYLbVXNtArC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/addb7557e62172a862401814c32258c40f8f2cd4/include/grpc/grpc_security.h#L1019)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's be a bit more precise here: The implementation must not invoke the async callback *in the same thread*  before `verify()` returns.  It's okay if the async callback is invoked in a different thread and happens to be called before `verify()` returns in the original thread.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 48 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWApTDwAnc9fmXfCYpn:-MZPLyBa6Pi9wY1yhfDS:bmjz5at) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes, I had intended that we remove the `status` and `error_details` fields from `grpc_tls_custom_verification_check_request` and instead return them from the `verify()` method, exactly as you described.

In other words, the semantics should be the same in the internal API and in the C-core API.  The only difference is that the C-core API uses a separate status code and string instead of using `absl::Status`.
</blockquote></details>

Sounds good! I've made the change accordingly.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 51 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW61W9K4vcPh3yon_Jj:-MZH3IJZ9ap8QvdOeqyX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like #25941 has been merged, so you should be able to make these changes now.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 44 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpY7lmDajsXsh13ljX:-MZQsk0b8rt2PPBZZf3z:b5s4owj) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

See my comment in tls_security_connector.h line 222.  I don't think it's helpful to share the interface between the client and server in the first place.  The only part of the code that you're actually sharing between the two is the code to initialize the fields in the request struct and then free those fields later, and I think whatever sharing is needed there can be done via standalone helper functions.

In other words, I think that `TlsChannelSecurityConnector::ChannelPendingVerifierRequest` and `TlsServerSecurityConnector::ServerPendingVerifierRequest` should be independent classes instead of inheritting from the same base class.
</blockquote></details>

Done. Please take a look. Thank you so much!
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 53 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpXT4L26m-B2LMf7Pz:-MZQsrh3Epj94ggX_B_T:bg4yltg) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L53)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Data members must be private, as per the style guide:

https://google.github.io/styleguide/cppguide.html#Access_Control

It's not clear to me why these are protected in the first place.  As I mentioned above, I don't think we should be creating any subclasses of this class.

If these do need to be accessed in a subclass, then you'll need to add protected accessor methods.
</blockquote></details>

No longer have this anymore.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 51 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpbusq--88Lr0yoLzq:-MZMISpPCTDi89Xo4j8v:b-wi5l1t) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I agree with the long-term direction of changing the TSI API from C to C++.  However, I don't think that's actually a prerequisite for sharing these strings.  It seems like we should be able to change the existing C-based TSI implementation to generate nul-terminated strings even in the existing API.  Just change them to allocate one extra byte and populate it with nul.
</blockquote></details>

Oh, sorry for causing the confusion. The thing we intended to do is to make the *code inside TSI* a bit more C++-like, instead of changing the TSI interface. Generating nul-terminated strings is one relatively simpler goal we wanted to achieve, but we also wanted to see if it is possible to restructure some of the code inside TSI layer to make them look like written in modern C++(using class, inheritance, reduce the use of pointer arithmetic, using `std::*` or `absl::*` when possible, etc). 
The reason for this change was because the transport security code was written a long time ago, and possibly before the time we can use C++11 in core. That code seems harder to maintain and make changes, and with the possible future work of CRL and SPIFFE trust domain, we will probably tend to modify TSI code more frequently. So we are trying to see if we could re-write some parts of it, to at least mitigate the maintenance burden.  
I will probably change to use nul-terminated strings after this PR goes in, so I think we can keep this TODO at this moment. 

(while I think it's a good idea to  change the TSI API from C to C++, I would imagine it could be a huge amount of work. We will need to change different transport protocols using TSI internally. That's why we didn't even think about it :) ). 
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 77 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpam8H1ZkBJB19mOlV:-MZERb7I-fkK9yVLPTE1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L77)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 81 at r7](https://reviewable.io/reviews/grpc/grpc/25631#-MYpapUu-WW0--H5iqAQ:-MZERbcr8NScoDAA2nOl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ea2caf27c77cf64e80535255769b9ef9a580c55c/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this.
</blockquote></details>

Done.
___
*[src/core/lib/secur [...]

2021-05-06 18:26 UTC, markdroth requested changes
This is getting closer!

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 15 files at r9, 13 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-M_1tNuY7XcvXOXkosgm:b79zqk9)* status: all files reviewed, 32 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @yashykt, and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 1022 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_16tq4DnGV2YQC5hQD:-M_16tq4DnGV2YQC5hQE:b-tqmt9n) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpc/grpc_security.h#L1022)):*
> ```objc
>    * mainly used as an argument in |callback|, if want to invoke |callback| in
>    * async mode.
>    * status: indicates if a connection should be allowed. This should only be
> ```

s/status/sync_status/
___
*[include/grpc/grpc_security.h, line 1023 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_16eiM-9VWHxynVau0:-M_16eiN9w9aWl--tyfF:b-lyhdip) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpc/grpc_security.h#L1023)):*
> ```objc
>    * async mode.
>    * status: indicates if a connection should be allowed. This should only be
>    * used if the verification check is done synchronously. error_details: the
> ```

Please move "error_details:" to the start of the next line, since it's a separate parameter.  Also change it to "sync_error_details", to match the parameter name.
___
*[include/grpc/grpc_security.h, line 1024 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_1p6-uD21iz3-PV6Ak:-M_1p6-uD21iz3-PV6Al:b3u66zq) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpc/grpc_security.h#L1024)):*
> ```objc
>    * status: indicates if a connection should be allowed. This should only be
>    * used if the verification check is done synchronously. error_details: the
>    * error generated while verifying a connection. This should only be used if
> ```

Please document the fact that the implementation must allocate the string via `gpr_malloc()` or `gpr_strdup()`.
___
*[include/grpc/grpc_security.h, line 1025 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_16mhSCDrE0uSqHWJI:-M_16mhSCDrE0uSqHWJJ:bq5oqk7) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpc/grpc_security.h#L1025)):*
> ```objc
>    * used if the verification check is done synchronously. error_details: the
>    * error generated while verifying a connection. This should only be used if
>    * the verification check is done synchronously. return: return 0 if |verify|
> ```

Please move "return:" to the start of the next line.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 70 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_17EG07XOAKvn7srzK:-M_17EG07XOAKvn7srzL:bmc5qh2) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L70)):*
> ```objc
>  private:
>   grpc_tls_custom_verification_check_request* c_request_ = nullptr;
>   std::string target_name_;
> ```

Instead of allocating these at construction time, it might make more sense to store only `c_request_` and construct these return values dynamically in the accessor methods.  That way, we won't bother allocating the fields that aren't actually going to be used.  I would expect the common case here to be that the verifier only looks at a subset of the fields, so that seems more optimal.

@veblush is currently investigating whether it will be possible to use absl in the C++ API.  If we can do that, then we can use `absl::string_view` for all of the non-vector accessor methods, which would avoid the allocation entirely.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 80 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_186pA2_U2qAjSu0u7:-M_186pA2_U2qAjSu0u8:b-ywpyfg) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L80)):*
> ```objc
> };
> 
> class CertificateVerifier {
> ```

This needs comments explaining the purpose of this class and showing how to use it.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 101 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_17Zp41U82WxutvCCl:-M_17Zp41U82WxutvCCm:b-nep804) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L101)):*
> ```objc
> 
>   grpc_tls_certificate_verifier* verifier_ = nullptr;
>   std::mutex mu_;
> ```

Please use `grpc::internal::Mutex`.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 107 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_188Aw3p3jaxu9LlW7:-M_188Ax8P2MwGCYxgVV:b-ywpyfg) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L107)):*
> ```objc
> };
> 
> class ExternalCertificateVerifier {
> ```

This needs comments explaining the purpose of this class and showing how to use it.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 120 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_17t7B2p-_DFYFdUtG:-M_17t7B2p-_DFYFdUtH:b-chbiex) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L120)):*
> ```objc
>   // bind its lifetime to the core objects.
>   template <typename Subclass, typename... Args>
>   static std::shared_ptr<CertificateVerifier> Create(Args&&... args);
> ```

This is effectively a factory function, so it should be the first one declared, as per the style guide:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 128 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_18Iiy054FmyBOlk9f:-M_18Iiy054FmyBOlk9g:b-1jq7wv) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L128)):*
> ```objc
> 
>  private:
>   struct AsyncCallbackProfile {
> ```

Suggest calling this `AsyncRequestState`.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 134 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_18OlnEOVDrGFRhR2L:-M_18OlnEOVDrGFRhR2M:b-io65w3) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L134)):*
> ```objc
>         : callback(cb), callback_arg(arg), cpp_request(request) {}
> 
>     grpc_tls_on_custom_verification_check_done_cb callback = nullptr;
> ```

No reason to initialize these fields to nullptr if they are always going to be set by the ctor.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 150 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_1jZPXC7NNOasUwwHe:-M_1jZPXC7NNOasUwwHf:b-m1itq5) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L150)):*
> ```objc
>   static void DestructInCoreExternalVerifier(void* user_data);
> 
>   // We have to use a pointer here, because
> ```

This is really unfortunate.  But I guess we can make this a TODO for now, assigned to @yihuazhang, and we can clean it up as part of eliminating insecure builds.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 155 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_18UqY6iRdehvBlQ2F:-M_18UqY6iRdehvBlQ2G:bvdq16f) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L155)):*
> ```objc
>   // to bypass this?
>   grpc_tls_certificate_verifier_external* base_ = nullptr;
>   std::mutex mu_;
> ```

`grpc::internal::Mutex`
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verif [...]

2021-05-13 06:52 UTC, ZhenLian reviewed
Thanks for the review so far! Finally, I think I've completed most of the code required in this PR.  I added more tests in C++, and have one  more question left to resolve. Once it's resolved, I can start to re-build the whole project and fix any issues in the pre-submit tests. 

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-M_ZQFsn-fXx4TP0b5CO:b-bp6wgj)* status: 19 of 35 files reviewed, 32 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @veblush, @yashykt, and @yihuazhang)

___
*[include/grpc/grpc_security.h, line 1022 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_16tq4DnGV2YQC5hQD:-M_HMUTU96Ny6iIr0ZeW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpc/grpc_security.h#L1022)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/status/sync_status/
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 1023 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_16eiM-9VWHxynVau0:-M_HMUxTCm6ptDrn6T_4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpc/grpc_security.h#L1023)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move "error_details:" to the start of the next line, since it's a separate parameter.  Also change it to "sync_error_details", to match the parameter name.
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 1024 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_1p6-uD21iz3-PV6Ak:-M_Hhpwu6ASGvtjiFHJp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpc/grpc_security.h#L1024)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document the fact that the implementation must allocate the string via `gpr_malloc()` or `gpr_strdup()`.
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 1025 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_16mhSCDrE0uSqHWJI:-M_HN1Dh9UHfVgEDk2RX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpc/grpc_security.h#L1025)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move "return:" to the start of the next line.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 70 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_17EG07XOAKvn7srzK:-M_HmYQN-OKZrTuWCCG_:b-j4lpeo) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of allocating these at construction time, it might make more sense to store only `c_request_` and construct these return values dynamically in the accessor methods.  That way, we won't bother allocating the fields that aren't actually going to be used.  I would expect the common case here to be that the verifier only looks at a subset of the fields, so that seems more optimal.

@veblush is currently investigating whether it will be possible to use absl in the C++ API.  If we can do that, then we can use `absl::string_view` for all of the non-vector accessor methods, which would avoid the allocation entirely.
</blockquote></details>

Sounds good. If so, I think it's better to return `std::string` instead of `std::string&` for the getter functions, because now we don't cache strings to the class?
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 80 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_186pA2_U2qAjSu0u7:-M_MvEIjCAGBhtJzSWo8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L80)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs comments explaining the purpose of this class and showing how to use it.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 101 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_17Zp41U82WxutvCCl:-M_N61tm8Ccrt8tJDBv2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L101)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `grpc::internal::Mutex`.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 107 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_188Aw3p3jaxu9LlW7:-M_MvG7dDcg3p6uOeVCE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L107)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs comments explaining the purpose of this class and showing how to use it.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 120 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_17t7B2p-_DFYFdUtG:-M_MvHYJ8oyOLim7Amdh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L120)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is effectively a factory function, so it should be the first one declared, as per the style guide:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 128 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_18Iiy054FmyBOlk9f:-M_N6IJ18_K5bCJAmj79:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L128)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `AsyncRequestState`.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 134 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_18OlnEOVDrGFRhR2L:-M_N6WH502_IuOJys7mX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L134)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No reason to initialize these fields to nullptr if they are always going to be set by the ctor.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 150 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_1jZPXC7NNOasUwwHe:-M_N6YBh7Zj8lieV399_:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L150)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is really unfortunate.  But I guess we can make this a TODO for now, assigned to @yihuazhang, and we can clean it up as part of eliminating insecure builds.
</blockquote></details>

Done
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 155 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_18UqY6iRdehvBlQ2F:-M_N76rr9IDSQIm8vv3X:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L155)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`grpc::internal::Mutex`
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_v [...]

2021-05-13 17:48 UTC, markdroth requested changes
This is continuing to get closer!

Please let me know if you have any questions.  Thanks!

> Reviewed 16 of 16 files at r11.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-M_apxtS0crWqMV8F0_b:b8sugde)* status: all files reviewed, 46 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @veblush, @yashykt, and @ZhenLian)

___
*[include/grpcpp/security/tls_certificate_verifier.h, line 70 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_17EG07XOAKvn7srzK:-M_aGrRq7CNj-5bDCBM0:brzql6x) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L70)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sounds good. If so, I think it's better to return `std::string` instead of `std::string&` for the getter functions, because now we don't cache strings to the class?
</blockquote></details>

Yes, that looks right.

Please add a TODO for veblush to change the return type of these methods to `absl::string_view` if we wind up being able to use absl in the C++ API before we wind up de-experimentalizing this API.  (If we de-experimentalize this API first, then we'll be stuck with `std::string` here.)
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 53 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aHlJoCHnbDSh-C2Rm:-M_aHlJoCHnbDSh-C2Rn:b-xwf6vu) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L53)):*
> ```objc
> // request. Users should not directly create or destroy this request object, but
> // shall interact with it through CertificateVerifier's Verify() and Cancel().
> // The object of this class should not outlive the underlying c object.
> ```

This line is an implementation detail, not something users need to know, so I don't think it should be here.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 77 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aI2et2hu5LhyrzuGh:-M_aI2et2hu5LhyrzuGi:bkhg3p6) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L77)):*
> ```objc
> // The base class of all internal verifier implementations, and the ultimate
> // class that all external verifiers will eventually be transformed into.
> // - If you are a gRPC contributor and want to add an internal gRPC verifier,
> ```

This bullet point can be removed.  This API documentation is for users, but this comment is for our internal use.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 92 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aIIV-09w4DGJLkrF7:-M_aIIV-09w4DGJLkrF8:b-wjd01z) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L92)):*
> ```objc
>   // verifier. The check on each internal verifier could be either synchronous
>   // or asynchronous, and we will need to use return value to know.
>   // Internally we invoke the verify() function of the c verifier object.
> ```

This line is not necessary; it's an implementation detail.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 93 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aMm5o6JeU59s118tT:-M_aMm5o6JeU59s118tU:bnj62lh) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L93)):*
> ```objc
>   // or asynchronous, and we will need to use return value to know.
>   // Internally we invoke the verify() function of the c verifier object.
>   // One typical usage of this function is to compose external verifiers with
> ```

I think the comment about composability actually belongs on `ExternalCertificateVerifier`, not here.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 95 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aILfU8qMCqqDtjKYc:-M_aILfU8qMCqqDtjKYd:b-so6gc0) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L95)):*
> ```objc
>   // One typical usage of this function is to compose external verifiers with
>   // internal verifiers. For example, users can compose their verifiers with a
>   // |HostNameCertificateVerifier|. See "tls_test_utils.h" for some examples.
> ```

The reference to tls_test_utils.h should be removed, since that file is not part of the public API.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 111 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aIYI7BQEwLAUmD4Vf:-M_aIYI7BQEwLAUmD4Vg:b-dcl9dm) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L111)):*
> ```objc
>               grpc::Status* sync_status);
> 
>   // Cancels a connection request. This is usually used to cleans up the
> ```

The wording here is a little confusing.  I suggest the following:

Cancels a verification request previously started via Verify().  Used when the connection attempt times out or is cancelled while an async verification request is pending.  The implementation should abort whatever async operation it is waiting for and quickly invoke the callback that was passed to Verify() with a status indicating the cancellation.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 138 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aN2-p6Zc_JdDMJQ-T:-M_aN2-p6Zc_JdDMJQ-U:bfo5zen) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L138)):*
> ```objc
> 
> // The base class of all external, user-specified verifiers. Users should
> // inherit this class if a custom verifier is expected to be used.
> ```

s/if a custom verifier is expected to be used/to implement a custom verifier/
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 144 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aNSE47CMsrYRhuXrd:-M_aNSE47CMsrYRhuXre:b-4vo7dt) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L144)):*
> ```objc
>   // the user-implemented verifiers should use this function to be converted to
>   // verifiers compatible with |TlsCredentialsOptions|.
>   // Subclass is created here, but it will be destroyed when the core
> ```

I think the rest of this comment can just say "The resulting CertificateVerifier takes ownership of the newly instantiated Subclass."
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 158 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aNddW3AByFuwED4nN:-M_aNddW3AByFuwED4nO:b-1dxfg0) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L158)):*
> ```objc
>   // The verification logic that will be performed after the TLS handshake
>   // completes. Implementers can choose to do their checks synchronously or
>   // asynchronously, and return different values.
> ```

I think the "and return different values" can be removed.  It's a bit confusing to read, and I think what it's actually referring to is already covered below.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 176 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aO59j3S5GvSOfc0aQ:-M_aO59j3S5GvSOfc0aR:bqymy9n) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L176)):*
> ```objc
>                       grpc::Status* sync_status) = 0;
> 
>   // The cancellation logic that will be performed when the verifier is still
> ```

Suggest the same wording here as on line 111 above.
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, lin [...]

2021-05-20 17:39 UTC, ZhenLian reviewed
I fixed the comments and re-built the project. I am stuck in fixing a bug caused by introducing new changes to `xds_end2end_test.cc`(some tests would just go timeout without any errors printed after the change). I will keep working on fixing that, but feel free to let me know any suspicious spot in the code that might cause the problem. Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-Ma9pRcwDGMHKSr8pCUf:b-7z85cz)* status: all files reviewed, 46 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @veblush, and @yashykt)

___
*[include/grpcpp/security/tls_certificate_verifier.h, line 70 at r10](https://reviewable.io/reviews/grpc/grpc/25631#-M_17EG07XOAKvn7srzK:-M_cKz5n6QrufFfdTyPu:b95g8n0) ([raw file](https://github.com/grpc/grpc/blob/a39a0b398f9a92a140d96873761f29b3326b8494/include/grpcpp/security/tls_certificate_verifier.h#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes, that looks right.

Please add a TODO for veblush to change the return type of these methods to `absl::string_view` if we wind up being able to use absl in the C++ API before we wind up de-experimentalizing this API.  (If we de-experimentalize this API first, then we'll be stuck with `std::string` here.)
</blockquote></details>

OK, I added a TODO to myself. I will check with @veblush before trying to de-experimentalizing this API.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 53 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aHlJoCHnbDSh-C2Rm:-M_bRVxQ6q9x4dmtl4Zr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L53)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This line is an implementation detail, not something users need to know, so I don't think it should be here.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 77 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aI2et2hu5LhyrzuGh:-M_cN7uE2THNmTc3jhnb:b92hqed) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L77)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This bullet point can be removed.  This API documentation is for users, but this comment is for our internal use.
</blockquote></details>

Sure, I've revised the wording a bit. PTAL, thanks!
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 92 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aIIV-09w4DGJLkrF7:-M_cNHkC6L4Vr0_f290Z:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L92)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This line is not necessary; it's an implementation detail.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 93 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aMm5o6JeU59s118tT:-M_cOG6FC13akU-wymCp:b-qp2kk4) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L93)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the comment about composability actually belongs on `ExternalCertificateVerifier`, not here.
</blockquote></details>

Hmm...actually I think both `CertificateVerifier.Verify()` and `ExternalCertificateVerifier.Verify()` can be composed.
My original intention for commenting was that, users might wonder what they could do with `CertificateVerifier.Verify()`, since it is public, but `CertificateVerifier`'s direct use is not involved with this `Verify()` API(users just need to create it, set it in the options, and then they are good to go). The answer for that is, there exists an indirect use of`CertificateVerifier.Verify()` to compose internal verifiers into the user-implemented ones.  I just wanted to point that out.

(And also, the semantics of `CertificateVerifier.Verify()` and `ExternalCertificateVerifier.Verify()` are a bit different. `CertificateVerifier.Verify()`is a function users can invoke during their composition, while `ExternalCertificateVerifier.Verify()` is a function users should implement while making their own verifiers. I wanted to make this clear as well, but not sure if the comment is clear enough. Feel free to make any suggestions on how we can improve the comments. Thank you so much!)
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 95 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aILfU8qMCqqDtjKYc:-M_dCWAf9wH4AB0witwM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L95)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The reference to tls_test_utils.h should be removed, since that file is not part of the public API.
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 111 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aIYI7BQEwLAUmD4Vf:-M_dEBXgDYq1-ZL2HHIf:b1hfmzw) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L111)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The wording here is a little confusing.  I suggest the following:

Cancels a verification request previously started via Verify().  Used when the connection attempt times out or is cancelled while an async verification request is pending.  The implementation should abort whatever async operation it is waiting for and quickly invoke the callback that was passed to Verify() with a status indicating the cancellation.
</blockquote></details>

Thanks for the suggestion! Just one minor thing, I think  the sentence` The implementation should ...` is speaking to users who might want to implement `CertificateVerifier.Cancel()`, while in `CertificateVerifier.Cancel()` users mostly likely won't need to implement it. They would just need to invoke it in a composition scenario. So it seems not appropriate to put it here.
But I find it a perfect statement for `ExternalCertificateVerifier.Cancel()`.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 138 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aN2-p6Zc_JdDMJQ-T:-M_dFde51Ey0EPhmnSi1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L138)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/if a custom verifier is expected to be used/to implement a custom verifier/
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 144 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aNSE47CMsrYRhuXrd:-M_dGIm_12IHB_1k2Lc0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the rest of this comment can just say "The resulting CertificateVerifier takes ownership of the newly instantiated Subclass."
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 158 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aNddW3AByFuwED4nN:-M_dJ6Ki-LsPTilxITSy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L158)):*
<details><summar [...]

2021-05-20 20:39 UTC, markdroth requested changes
If you can point me at which tests are failing, I might be able to suggest where to look.

Otherwise, this looks really good!  What's left is mainly fixing the `cmp()` method on the security connectors and addressing the problem of the per-call host check.

Please let me know if you have any questions.  Thanks!

> Reviewed 31 of 31 files at r12.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MaAUu7Z3wQ3s6RV97aX:b2dwqi7)* status: all files reviewed, 5 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @yashykt, and @ZhenLian)

___
*[include/grpcpp/security/tls_certificate_verifier.h, line 77 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aI2et2hu5LhyrzuGh:-MaAQoeZAkurNwmDqY-H:b8pqrw9) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L77)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sure, I've revised the wording a bit. PTAL, thanks!
</blockquote></details>

Suggest the following wording instead:

"""
To implement a custom verifier, do not extend this class; instead, implement a subclass of ExternalCertificateVerifier.  Note that custom verifier implementations can compose their functionality with existing implementations of this interface, such as HostnameVerifier, by delegating to an instance of that class.
"""
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 93 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aMm5o6JeU59s118tT:-MaARPtR4UfJV7g8Oy1g:b-2ldrjs) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L93)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Hmm...actually I think both `CertificateVerifier.Verify()` and `ExternalCertificateVerifier.Verify()` can be composed.
My original intention for commenting was that, users might wonder what they could do with `CertificateVerifier.Verify()`, since it is public, but `CertificateVerifier`'s direct use is not involved with this `Verify()` API(users just need to create it, set it in the options, and then they are good to go). The answer for that is, there exists an indirect use of`CertificateVerifier.Verify()` to compose internal verifiers into the user-implemented ones.  I just wanted to point that out.

(And also, the semantics of `CertificateVerifier.Verify()` and `ExternalCertificateVerifier.Verify()` are a bit different. `CertificateVerifier.Verify()`is a function users can invoke during their composition, while `ExternalCertificateVerifier.Verify()` is a function users should implement while making their own verifiers. I wanted to make this clear as well, but not sure if the comment is clear enough. Feel free to make any suggestions on how we can improve the comments. Thank you so much!)
</blockquote></details>

I don't think we need to talk about composition here.  We don't need to justify the existence of this method, we just need to document how to use it.  The composition mechanism is covered by the comment above about custom implementations being able to delegate to other `CertificateVerfier` instances.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 111 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aIYI7BQEwLAUmD4Vf:-MaARy9y7nnOSgWcTC7d:b-dkjq2) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L111)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Thanks for the suggestion! Just one minor thing, I think  the sentence` The implementation should ...` is speaking to users who might want to implement `CertificateVerifier.Cancel()`, while in `CertificateVerifier.Cancel()` users mostly likely won't need to implement it. They would just need to invoke it in a composition scenario. So it seems not appropriate to put it here.
But I find it a perfect statement for `ExternalCertificateVerifier.Cancel()`.

</blockquote></details>

You're right, it looks good that way.


<!-- Sent from Reviewable.io -->

2021-05-20 22:31 UTC, ZhenLian reviewed
The log for one of the failing tests is here: https://gist.github.com/ZhenLian/e47f5cbb031d7127c70f98d50b3c2745. I noticed that for the failing e2e tests, the channel security connector is not destructed, and the error is a `Handshake timed out`, so I guess something is wrongly holding a ref to the security connector when not needed and hence causing the problem.

I didn't push the updated changes for `xds_end2end_test.cc` yet(because it has this bug), but I can push it if you want me to do that.

BTW, this e2e test is super long, and since the error is a timeout issue, it takes very long to get the log result. I am wondering if there is any way to run a particular test? Take the above failing test(`XdsTest/XdsSecurityTest.TestMtlsConfigurationWithRootPluginUpdate/XdsResolverV3XdsCreds`) for example, I tried to run `bazel test //test/cpp/end2end:xds_end2end_test --test_output=all --config=asan --test_filter="TestMtlsConfigurationWithRootPluginUpdate"`, but it just passed.  Did I do anything wrong here?

Any help is very much appreciated!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MaAjDD61lhojzXEuANj:b8q7dgd)* status: all files reviewed, 5 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @yashykt, and @ZhenLian)



<!-- Sent from Reviewable.io -->

2021-05-21 07:00 UTC, ZhenLian reviewed
I pushed the latest changes, and the most recent commit includes the part for `xds_end2end_test.cc`. It will generate the error linked above if I ran `bazel test //test/cpp/end2end:xds_end2end_test --test_output=all --config=asan`. Any guess/suggestion on how to fix the problem is really appreciated. Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MaChXKWBT-XmpoygCbB:bodr08k)* status: 53 of 57 files reviewed, 5 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @yashykt, and @ZhenLian)



<!-- Sent from Reviewable.io -->

2021-05-23 22:47 UTC, ZhenLian reviewed
Update: I've fixed some small issues in code which solves the previous `Handshake timed out` error, but the test would still time out after all the handshakes are complete(See updated logs https://gist.github.com/ZhenLian/e47f5cbb031d7127c70f98d50b3c2745).

From the logs, it seems the security connector and all the external verifiers, including `grpc::experimental::ExternalCertificateVerifier` and  `grpc_core::ExternalCertificateVerifier, are never destroyed.  `grpc::experimental::CertificateVerifier` is created and then immediately destroyed, though. Most of the failing tests seem to be related to `XdsSecurityTest`.

I am not very familiar with how the Xds are structured on top. The only thing I could tell that might be relevant to this ownership problem is the way we manage our C++ classes. We use `Create(...)` to transfer the subclass of `grpc::experimental::ExternalCertificateVerifier` to `grpc::experimental::CertificateVerifier`, but we don't want the former to be destroyed when the latter get destroyed; instead, we associate the ownership of the former to the core objects. But when would the core objects be destroyed then? Without a bond to the C++ classes, we can't rely on users to tell us when to destroy the object. If we will have to do it ourselves, what is the right timing to destroy the core objects, and hence `grpc::experimental::ExternalCertificateVerifier`? I didn't find anywhere in code we are doing this right now.

I am almost out of way for how to debug this. So any way we could even get closer to the solution would be very much appreciated. Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MaQDfamEU-gaD8-TMCz:bxvoyqy)* status: 53 of 57 files reviewed, 5 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @yashykt, and @ZhenLian)



<!-- Sent from Reviewable.io -->

2021-05-24 15:27 UTC, markdroth requested changes
The fact that we don't link the lifetime of the C++ object to the lifetime of the core object is intentional.  We discussed this in the design doc: we need to do it that way, because we can't pass the C++ `shared_ptr<>` into core.  That's why they need to be separate objects in the first place.

For the core object, each channel that the object is used for should be holding a ref to it.  When those channels shut down, they should drop the refs, and the object should be destroyed at that point.

I've added a suggestion below for how to debug the ref-counting problem.  If you can't figure it out, I suggest asking @yashykt to help, since he wrote all of the xDS security code and the corresponding tests.

> Reviewed 1 of 10 files at r14.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MaTxzf265U-lP1kAI3Q:b-1dk550)* status: 47 of 57 files reviewed, 15 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, @yashykt, and @ZhenLian)

___
*[include/grpcpp/security/tls_certificate_verifier.h, line 87 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTtgLR-_S00fKMOyOT:-MaTtgLR-_S00fKMOyOU:b-abt70v) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/include/grpcpp/security/tls_certificate_verifier.h#L87)):*
> ```objc
>  public:
>   CertificateVerifier(grpc_tls_certificate_verifier* v) : verifier_(v) {
>     gpr_log(GPR_ERROR,
> ```

It looks like you've added a bunch of these log messages, presumably for debugging.  Please make sure to remove these before merging.
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h, line 40 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTxRF-8_H9InJZpxEx:-MaTxRF-8_H9InJZpxEy:b-bk6yl2) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.h#L40)):*
> ```objc
>     : public grpc_core::RefCounted<grpc_tls_certificate_verifier> {
>  public:
>   grpc_tls_certificate_verifier() = default;
> ```

For ref-count debugging, I suggest temporarily changing this to:

```
grpc_tls_certificate_verifier() : grpc_core::RefCounted("core cert verifier") {}
```

This will provide trace logging messages whenever the refs of this object change, so you can trace where the refs and unrefs are happening and see where we're failing to drop a ref.
___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 71 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTwEo9DqMOEQeOPUuu:-MaTwEo9DqMOEQeOPUuv:b99lv9f) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/src/core/lib/security/credentials/xds/xds_credentials.cc#L71)):*
> ```cpp
>       : cluster_name_(std::move(cluster_name)) {
>     gpr_log(GPR_ERROR, "XdsCertificateVerifier ctor is called");
>     xds_matcher_ = xds_certificate_provider->GetSanMatchers(cluster_name_);
> ```

I don't think it's correct to get the SAN matchers from the `XdsCertificateProvider` only at instantiation time, because they can change over the lifetime of the object.  We need to use the current value each time there is a connection attempt.

I assume that you made this change to avoid holding a ref to the `XdsCertificateProvider` here, but I don't see why that would be necessary.  The certificate provider isn't holding a ref to the certificate verifier, so there's no circular reference here that would prevent everything from being shut down.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 97 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvy7dAPgQe2KdZVj-:-MaTvy7dAPgQe2KdZVj0:bgafnsr) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L97)):*
> ```cpp
> #include "test/cpp/util/tls_test_utils.h"
> 
> #include "test/core/util/tls_utils.h"
> ```

Doesn't look like this include is actually needed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1544 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTv6eRBYXnMFEGo9Yx:-MaTv6eRBYXnMFEGo9Yy:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L1544)):*
> ```cpp
>       ReadFile(kCaCertPath), identity_key_cert_pairs);
>   grpc::experimental::TlsChannelCredentialsOptions options;
>   options.set_certificate_provider(certificate_provider);
> ```

`std::move()`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1550 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvC4t-5cWAy2n1YI0:-MaTvC4t-5cWAy2n1YI1:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L1550)):*
> ```cpp
>       ExternalCertificateVerifier::Create<SyncCertificateVerifier>(true);
>   options.set_verify_server_certs(true);
>   options.set_certificate_verifier(verifier);
> ```

`std::move()`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7598 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvK4k9EJA4DWtfTC7:-MaTvK4k9EJA4DWtfTC8:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L7598)):*
> ```cpp
>         ReadFile(kCaCertPath), identity_key_cert_pairs);
>     grpc::experimental::TlsChannelCredentialsOptions options;
>     options.set_certificate_provider(certificate_provider);
> ```

`std::move()`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7604 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvMK4AWTOIUTtHN4g:-MaTvMK4AWTOIUTtHN4h:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L7604)):*
> ```cpp
>         ExternalCertificateVerifier::Create<SyncCertificateVerifier>(true);
>     options.set_verify_server_certs(true);
>     options.set_certificate_verifier(verifier);
> ```

`std::move()`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7622 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvPA64V18LOHRiLP1:-MaTvPA64V18LOHRiLP2:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L7622)):*
> ```cpp
>         std::make_shared<StaticDataCertificateProvider>(ReadFile(kCaCertPath));
>     grpc::experimental::TlsChannelCredentialsOptions options;
>     options.set_certificate_provider(certificate_provider);
> ```

`std::move()`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7627 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvQqtA2gFRvAbgcEW:-MaTvQqtA2gFRvAbgcEX:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L7627)):*
> ```cpp
>         ExternalCertificateVerifier::Create<SyncCertificateVerifier>(true);
>     options.set_verify_server_certs(true);
>     options.set_certificate_verifier(verifier);
> ```

`std::move()`


<!-- Sent from Reviewable.io -->

2021-05-27 23:15 UTC, jiangtaoli2016 reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: 47 of 57 files reviewed, 15 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 331 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWAuOOJDrPm2QsvjcL1:-Mak6-iv2HydC4MxpFzq:bj2dw0) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L331)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Just because we don't have a case right now where we'll want to determine this dynamically doesn't mean that there will never be any such case in the future.  I would allow it to be set via both sync and async APIs.

Bleh... I still really don't like having this in the verifier API at all.  I guess an alternative might be to have a separate option in `grpc_tls_credentials_options`,  as you mentioned above.  The reason I had originally not wanted to do that is that it basically puts the work on the application instead of on the verifier implementation, which in general is the wrong trade-off, since there are going to be a lot more applications than there will be verifier implementations.  But given how invasive this change is likely to be, I wonder if it would be better to just make the application set this.  If we default it to true, then only applications that configure a verifier that does *not* include hostname verification will need to set this option, which might not be too bad if we think that will be a rare case.   But if we think that will be common in the future (e.g., if people move more to spiffe and away from hostname-based certs), then we probably want to stick with making the verifier impl deal with this.

It might be useful to get some input from @jiangtaoli2016 on this when he gets back.
</blockquote></details>

I am fine with adding a separate option field to specify if application wants check_per_call_host.


<!-- Sent from Reviewable.io -->

2021-05-28 23:02 UTC, ZhenLian reviewed
Thanks for the suggestions so far! I've fixed the minor comments and made the temporary changes to debug the ref-counting issue, but didn't get time to take a look at the logs. Just FYI, I will be OOO next week. Once I am back, I will continue on debugging this issue and maybe have a meeting with @yashykt.
Thanks everyone for the contribution so far!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MapBzK3AayjQOhjHnL7:b-bu33a)* status: 47 of 57 files reviewed, 15 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)

___
*[include/grpcpp/security/tls_certificate_verifier.h, line 77 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aI2et2hu5LhyrzuGh:-Manv17k1K--5oj735D5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L77)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest the following wording instead:

"""
To implement a custom verifier, do not extend this class; instead, implement a subclass of ExternalCertificateVerifier.  Note that custom verifier implementations can compose their functionality with existing implementations of this interface, such as HostnameVerifier, by delegating to an instance of that class.
"""
</blockquote></details>

Done.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 93 at r11](https://reviewable.io/reviews/grpc/grpc/25631#-M_aMm5o6JeU59s118tT:-ManzxYO0k86mTGm0WsZ:b-uqakmg) ([raw file](https://github.com/grpc/grpc/blob/db789da3a8da84ebe26e9ac6f4fa0dc825bb6dc7/include/grpcpp/security/tls_certificate_verifier.h#L93)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need to talk about composition here.  We don't need to justify the existence of this method, we just need to document how to use it.  The composition mechanism is covered by the comment above about custom implementations being able to delegate to other `CertificateVerfier` instances.
</blockquote></details>

OK, sounds good. Removed the paragraph talking about composition.
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 87 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTtgLR-_S00fKMOyOT:-Manv67TDyEQELsYxmBw:b-cda495) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/include/grpcpp/security/tls_certificate_verifier.h#L87)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like you've added a bunch of these log messages, presumably for debugging.  Please make sure to remove these before merging.
</blockquote></details>

Yeah, they are mainly used for debugging purpose. Let's keep this open, and I've reply to this comment again once all of them get removed.
___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 71 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTwEo9DqMOEQeOPUuu:-Mao-KtqA9JFZk6SaBjw:b-p1nvmu) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/src/core/lib/security/credentials/xds/xds_credentials.cc#L71)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think it's correct to get the SAN matchers from the `XdsCertificateProvider` only at instantiation time, because they can change over the lifetime of the object.  We need to use the current value each time there is a connection attempt.

I assume that you made this change to avoid holding a ref to the `XdsCertificateProvider` here, but I don't see why that would be necessary.  The certificate provider isn't holding a ref to the certificate verifier, so there's no circular reference here that would prevent everything from being shut down.
</blockquote></details>

Yeah, that was my original intention. It did seem have nothing to do with the timeout error. I will change the code back.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 97 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvy7dAPgQe2KdZVj-:-Mao0t8nCX_KdbesgIDb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L97)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this include is actually needed.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1544 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTv6eRBYXnMFEGo9Yx:-Mao1MU55z9A99TSLh5M:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L1544)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1550 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvC4t-5cWAy2n1YI0:-Mao1N0z3SNzpsazE870:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L1550)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7598 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvK4k9EJA4DWtfTC7:-Mao1_dU0ddUWnOcqfJm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L7598)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7604 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvMK4AWTOIUTtHN4g:-Mao1aOG22YDdbYpbWxD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L7604)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7622 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvPA64V18LOHRiLP1:-Mao1m4t88mmjkFeWY1B:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L7622)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7627 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTvQqtA2gFRvAbgcEW:-Mao1mfgBAEEB9ydj3nd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/test/cpp/end2end/xds_end2end_test.cc#L7627)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-03 00:34 UTC, ZhenLian reviewed
Hi @markdroth, as discussed earlier, I solved the ref-counting issue, but there was another TSAN error related to `AsyncExternalVerifier` in core coming up. My RBE results are here[1](from the main page it will show all tests passed; but click on the "target Details"[2] will give you the full logs including errors)

Originally I thought it happened because the async processing thread was still running while  `AsyncExternalVerifier::Destruct()` is called. But after fixing that, I could still see the TSAN errors. I've spent a while on this issue now. May I know if you could spot any issues related to this in `test/core/util/tls_utils.cc`?

Thank you so much!

[1] https://source.cloud.google.com/results/invocations/e77a3c7a-fc2e-4e9a-b1bc-db65272074de/targets
[2] https://source.cloud.google.com/results/invocations/e77a3c7a-fc2e-4e9a-b1bc-db65272074de/targets/%2F%2Ftest%2Fcore%2Fsecurity:tls_security_connector_test@poller%3Depollex/log

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MddNy1R0zuemgZXydK6:bnquolf)* status: 47 of 57 files reviewed, 15 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)



<!-- Sent from Reviewable.io -->

2021-07-07 18:05 UTC, markdroth requested changes
The thing to notice in the tsan error report is that `AsyncExternalVerifier::WorkerThread()` is being invoked in the same thread as the verifier is being destroyed (both from thread T4 in the first tsan report).  It looks to me like the problem is that `AsyncExternalVerifier::Destruct()` is being called from within the worker thread itself.

(I'm not sure why it's causing this tsan failure instead of a deadlock. `thread_.Join()` should not return until the thread is terminated, and here we're calling `thread_.Join()` on a thread from within itself, which should block forever.  But instead, `thread_.Join()` seems to be returning, so we proceed to delete the `AsyncExternalVerifier` object, but then the worker thread moves on to the next iteration of the loop, whereupon it hits the use-after-free crash trying to acquire the mutex to read the next item out of the queue.  I'm not sure why `thread_.Join()` is returning here, but I also don't think it's worth trying to figure this out; if we fix the underlying problem, we won't hit this case in the first place.)

If you look at the stack trace of where the verifier is destroyed, I think what's happening is that the verifier request is holding the last ref to the `TlsChannelSecurityConnector`, so when we invoke the `on_complete` callback, that ref is released, and the `TlsChannelSecurityConnector` is destroyed.  However, that in turn releases the last ref to the verifier, so we wind up trying to destroy the verifier inline.

I think the simplest way to avoid this is to change `AsyncExternalVerifier::Destruct` to spawn a detached thread to do the deletion, so that it will never happen from within the thread itself.  See my suggestion below for how to do that.

> Reviewed 1 of 4 files at r13, 5 of 10 files at r14, 4 of 4 files at r15, 42 of 42 files at r16.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-Me1-stY-MKrWgQnyrsv:ba0vzm6)* status: all files reviewed, 8 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/tls_credentials.cc, line 48 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0v0Nv4vDvG1l1sYl0:-Me0v0Nv4vDvG1l1sYl1:b-o4yb98) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/src/core/lib/security/credentials/tls/tls_credentials.cc#L48)):*
> ```cpp
>   if (is_client && options->cert_request_type() !=
>                        GRPC_SSL_DONT_REQUEST_CLIENT_CERTIFICATE) {
>     gpr_log(GPR_INFO,
> ```

Why are these messages being downgraded from `GPR_ERROR` to `GPR_INFO`?
___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 85 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0vC5n7MOYsKGWfm1Z:-Me0vC5n7MOYsKGWfm1_:buecatj) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/src/core/lib/security/credentials/xds/xds_credentials.cc#L85)):*
> ```cpp
>             xds_certificate_provider_->GetSanMatchers(cluster_name_)) &&
>         !XdsVerifySubjectAlternativeNames(
>             request->peer_info.san_names.dns_names,
> ```

Is this the right behavior?  Does xDS's list of SAN matchers handle both IP and DNS matches?  Or is there some sort of type encoded in the xDS SAN matchers, in which case we'd need to pass both sets of info from the request into a single call to `XdsVerifySubjectAlternativeNames()`?

CC @yashykt 
___
*[test/core/util/tls_utils.cc, line 110 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0wcn48WohlCkrfZjq:-Me0wcn48WohlCkrfZjr:b-pihovb) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/test/core/util/tls_utils.cc#L110)):*
> ```cpp
> 
> void AsyncExternalVerifier::Destruct(void* user_data) {
>   // Tell the thread to shut down.
> ```

I think the code to shut down the worker thread needs to move back to the dtor, where it was before.  And the code here should be:

```
namespace {

void DestroyExternalVerifier(void* arg) {
  auto* verifier = static_cast<AsyncExternalVerifier*>(arg);
  delete verifier;
}

}  // namespace

void AsyncExternalVerifier::Destruct(void* user_data) {
  auto* self = static_cast<AsyncExternalVerifier*>(user_data);
  // Spawn a detached thread to destroy the verifier, to make sure that we don't
  // try to join the worker thread from within the worker thread.
  grpc_core::Thread thread(
      "DestroyExternalVerifier", DestroyExternalVerifier, self, nullptr,
      grpc_core::Thread::Options().set_joinable(false));
}
```
___
*[test/cpp/util/tls_test_utils.cc, line 25 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0xDuD8vaYRcBO6VzX:-Me0xDuD8vaYRcBO6VzY:b-vwd17f) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/test/cpp/util/tls_test_utils.cc#L25)):*
> ```cpp
> #include "test/core/util/test_config.h"
> 
> namespace {
> ```

There's no need to put these `using` statements in an anonymous namespace block.  The statements won't cause anything to be exported from this module anyway.


<!-- Sent from Reviewable.io -->

2021-07-09 07:19 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: all files reviewed, 8 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/tls_credentials.cc, line 48 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0v0Nv4vDvG1l1sYl0:-Me93oTd1IHsygOIPGpT:b-mojbaz) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/src/core/lib/security/credentials/tls/tls_credentials.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why are these messages being downgraded from `GPR_ERROR` to `GPR_INFO`?
</blockquote></details>

Ah, that's probably for debugging purposes. Thanks for the catch! I've changed them back.
___
*[test/core/util/tls_utils.cc, line 110 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0wcn48WohlCkrfZjq:-Me9-YnzAvmyxy3R0wgP:b-ahs5rl) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/test/core/util/tls_utils.cc#L110)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the code to shut down the worker thread needs to move back to the dtor, where it was before.  And the code here should be:

```
namespace {

void DestroyExternalVerifier(void* arg) {
  auto* verifier = static_cast<AsyncExternalVerifier*>(arg);
  delete verifier;
}

}  // namespace

void AsyncExternalVerifier::Destruct(void* user_data) {
  auto* self = static_cast<AsyncExternalVerifier*>(user_data);
  // Spawn a detached thread to destroy the verifier, to make sure that we don't
  // try to join the worker thread from within the worker thread.
  grpc_core::Thread thread(
      "DestroyExternalVerifier", DestroyExternalVerifier, self, nullptr,
      grpc_core::Thread::Options().set_joinable(false));
}
```
</blockquote></details>

Thanks for the suggestions! It does seem to solve the problem, but it also introduces another `data race` problem in `//test/core/end2end:h2_tls_test@filter_init_fails`(see [1]) and `//test/core/security:grpc_tls_certificate_verifier_test`(see [2]).

One thing I noticed is that if we move the code to shut down the worker thread to the Destruct() function, that `data race` problem will go away, but it introduces another `thread leak` issue in `//test/core/security:tls_security_connector_test`, as shown in [3]. 

Actually, I am a bit confused on why we need to move the shut down code back to the dtor. Shouldn't we join the worker thread before we fire the detached destroying thread? Otherwise there might be a chance that the verifier is already destroyed, while the worker thread is still running. Do you have any clues on what is causing that `thread leak` error?

[1] https://source.cloud.google.com/results/invocations/45561f33-b253-486c-8748-7ddd2fdad1c8/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_tls_test@filter_init_fails@poller%3Depollex/log
[2] https://source.cloud.google.com/results/invocations/45561f33-b253-486c-8748-7ddd2fdad1c8/targets/%2F%2Ftest%2Fcore%2Fsecurity:grpc_tls_certificate_verifier_test@poller%3Depollex/log
[3] https://source.cloud.google.com/results/invocations/92fe21c0-3dd1-4a90-a173-168e486c693d/targets/%2F%2Ftest%2Fcore%2Fsecurity:tls_security_connector_test@poller%3Depollex/log
___
*[test/cpp/util/tls_test_utils.cc, line 25 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0xDuD8vaYRcBO6VzX:-Me93jKg3T4mWoOm48o8:b-kyqvd3) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/test/cpp/util/tls_test_utils.cc#L25)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need to put these `using` statements in an anonymous namespace block.  The statements won't cause anything to be exported from this module anyway.
</blockquote></details>

Sure, removed that.


<!-- Sent from Reviewable.io -->

2021-07-09 22:47 UTC, markdroth requested changes
> Reviewed 3 of 3 files at r17.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: all files reviewed, 7 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/tls_credentials.cc, line 48 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0v0Nv4vDvG1l1sYl0:-MeCHu_yBVELP4naa4lh:b-fqhmbl) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/src/core/lib/security/credentials/tls/tls_credentials.cc#L48)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Ah, that's probably for debugging purposes. Thanks for the catch! I've changed them back.
</blockquote></details>

There's still one more to be changed back.
___
*[test/core/util/tls_utils.cc, line 110 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0wcn48WohlCkrfZjq:-MeCKTK_2emFLzhvlTfp:b4j0fz4) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/test/core/util/tls_utils.cc#L110)):*
> Thanks for the suggestions! It does seem to solve the problem, but it also introduces another data race problem in //test/core/end2end:h2_tls_test@filter_init_fails(see [1]) and //test/core/security:grpc_tls_certificate_verifier_test(see [2]).

In `//test/core/security:tls_security_connector_test`, the problem is that you're creating the `ExternalCertificateVerifier` objects as local stack variables within the test, but since the destruction of that object (the core verifier object) no longer blocks until the worker thread is terminated, you no longer have any guarantee that the async verifier result is actually finished before the `ExternalCertificateVerifier` object is destroyed.  To avoid this, I think you're going to have to use a `gpr_event` to prevent from exiting from the test until after the callback runs.

The problem in `//test/core/end2end:h2_tls_test@filter_init_fails` looks like it may be that `grpc_shutdown()` is being triggered before the worker thread gets cleaned up.  To avoid that, try calling `grpc_init()` right before spawning the destruction thread and then calling `grpc_shutdown()` at the end of `DestroyExternalVerifier()`.  (I'm not entirely sure that that's the right fix, but let's start with that and see.)

> Actually, I am a bit confused on why we need to move the shut down code back to the dtor. Shouldn't we join the worker thread before we fire the detached destroying thread? 

The problem that I pointed out previously is that `Destruct()` is being called from within the worker thread, so we were joining the worker thread from within the worker thread.  That will not work, so we cannot do the join from inside of `Destruct()`.  The whole point of the detached destruction thread is to move that join to a different thread than the thread being joined.

> Otherwise there might be a chance that the verifier is already destroyed, while the worker thread is still running.

No, because the call to `thread_.Join()` ensures that the worker thread is terminated before the object is deleted.  We're still waiting for the worker thread to terminate before we destroy the object; we're just doing that waiting in a detached thread instead of in `Destruct()`, so that we're not doing it from within the worker thread.

> Do you have any clues on what is causing that thread leak error?

I still don't understand why `thread_.Join()` is not deadlocking in this case, so I don't understand this behavior.  But calling `thread_.Join()` in `Destruct()` is clearly wrong, so I don't think it makes sense to worry about this.


<!-- Sent from Reviewable.io -->

2021-07-16 05:22 UTC, ZhenLian reviewed
Thanks for guiding me this far! There is still one remaining issue in `//test/cpp/security:tls_certificate_verifier_test` for Windows system though: https://source.cloud.google.com/results/invocations/d1f39a8c-b122-4b0d-91d3-78ec19426e5c/targets/%2F%2Ftest%2Fcpp%2Fsecurity:tls_certificate_verifier_test/tests

`SEH exception with code 0xc0000005 thrown in the test body`

I vaguely remembered we talked about using `gpr_malloc()` for `error_details` long time ago, or else there would be problems on Windows, where objects allocated by one DLL might be released by another DLL. Is that related to this issue?

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-Mehh3n69ON9L787jGt5:b-yevvdk)* status: 56 of 57 files reviewed, 7 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)

___
*[src/core/lib/security/credentials/tls/tls_credentials.cc, line 48 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0v0Nv4vDvG1l1sYl0:-Me_uwIS8iFUfn9hL-o2:buxtd5o) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/src/core/lib/security/credentials/tls/tls_credentials.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's still one more to be changed back.
</blockquote></details>

Oh, that one is left `GPR_INFO` intentionally, because when users don't specify any verifiers on the client side, we will use a default host name verifier for them(on server side, if that happens, we will just skip any additional checks).
This is to keep consistent with the current behaviors, and to make sure users won't skip the host name check just by accidentally ignoring the verifiers. If such case happens, it is an intended behavior, so I just use  `GPR_INFO` here.
___
*[test/core/util/tls_utils.cc, line 110 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0wcn48WohlCkrfZjq:-MegcwzqDvhtRAgnMUyL:b-wq8ytx) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/test/core/util/tls_utils.cc#L110)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

> Thanks for the suggestions! It does seem to solve the problem, but it also introduces another data race problem in //test/core/end2end:h2_tls_test@filter_init_fails(see [1]) and //test/core/security:grpc_tls_certificate_verifier_test(see [2]).

In `//test/core/security:tls_security_connector_test`, the problem is that you're creating the `ExternalCertificateVerifier` objects as local stack variables within the test, but since the destruction of that object (the core verifier object) no longer blocks until the worker thread is terminated, you no longer have any guarantee that the async verifier result is actually finished before the `ExternalCertificateVerifier` object is destroyed.  To avoid this, I think you're going to have to use a `gpr_event` to prevent from exiting from the test until after the callback runs.

The problem in `//test/core/end2end:h2_tls_test@filter_init_fails` looks like it may be that `grpc_shutdown()` is being triggered before the worker thread gets cleaned up.  To avoid that, try calling `grpc_init()` right before spawning the destruction thread and then calling `grpc_shutdown()` at the end of `DestroyExternalVerifier()`.  (I'm not entirely sure that that's the right fix, but let's start with that and see.)

> Actually, I am a bit confused on why we need to move the shut down code back to the dtor. Shouldn't we join the worker thread before we fire the detached destroying thread? 

The problem that I pointed out previously is that `Destruct()` is being called from within the worker thread, so we were joining the worker thread from within the worker thread.  That will not work, so we cannot do the join from inside of `Destruct()`.  The whole point of the detached destruction thread is to move that join to a different thread than the thread being joined.

> Otherwise there might be a chance that the verifier is already destroyed, while the worker thread is still running.

No, because the call to `thread_.Join()` ensures that the worker thread is terminated before the object is deleted.  We're still waiting for the worker thread to terminate before we destroy the object; we're just doing that waiting in a detached thread instead of in `Destruct()`, so that we're not doing it from within the worker thread.

> Do you have any clues on what is causing that thread leak error?

I still don't understand why `thread_.Join()` is not deadlocking in this case, so I don't understand this behavior.  But calling `thread_.Join()` in `Destruct()` is clearly wrong, so I don't think it makes sense to worry about this.
</blockquote></details>

I finally managed to make that TSAN issue away by adding the `gpr_event`(see the commit before the latest commit for the code change), but it appears there are more issues ahead of us(ASAN[1], MSAN[2] and UBSAN[3]). All of those 3 failures come from `grpc_tls_certificate_verifier_test`.
That makes me wondering if we really want that test at all. The verifier is expected to be put into a credential options afterwards, while in `grpc_tls_certificate_verifier_test`, it is created, and then we are done. It gives me a sense that we are just partially test its behavior. Besides, we already have the tests covering the whole process in  `tls_security_connector_test` and `h2_tls.cc`(though I also feel a bit disappointed by knowing our test only works for "creating async verifier and then putting it to options" as a whole, but doesn't work for creating a single async verifier object).
Another incentive for removing those tests is that we will need to add the `gpr_event` to our async verifier, to possibly support them. Other tests won't have the similar issue. So the `gpr_event` is added specifically for `grpc_tls_certificate_verifier_test`.
I've removed the async verifier tests in `grpc_tls_certificate_verifier_test` to be able to move forward, but feel free to let me know if you feel differently and I could add those tests back.


[1] https://source.cloud.google.com/results/invocations/71f837b8-3728-446b-acee-466ca5663a4b/targets
[2] https://source.cloud.google.com/results/invocations/d586074f-5bf0-415b-a6ad-87f0cc1c427a/targets
[3] https://source.cloud.google.com/results/invocations/bbb871ea-8d45-45f7-806c-6fe6034783fc/targets


<!-- Sent from Reviewable.io -->

2021-08-02 05:40 UTC, ZhenLian reviewed
`//test/cpp/security:tls_certificate_verifier_test` is a newly added test file(actually, the whole directory is newly added). It is really weird that if I appended all the tests to an existing test file(e.g. `//test/cpp/server:credentials_test`, as the most recent commit), the error won't appear.
By adding some debugging messages, I found out that the error appeared in `//test/cpp/security:tls_certificate_verifier_test` was last seen after L148 in  `grpc/include/grpcpp/security/tls_certificate_verifier.h`, when calling
```
auto* external_verifier = new Subclass(std::forward<Args>(args)...);
```
and L149 was not logged.
However, I have no idea why it didn't show up if I added those tests to an existing test file. 
@markdroth Mark, do you have any suggestions on how we should proceed?

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-Mg4JvYD9DvMiG0tm3AA:b-vcnn2b)* status: 55 of 57 files reviewed, 7 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)



<!-- Sent from Reviewable.io -->

2021-08-06 16:56 UTC, ZhenLian reviewed
OK, by appending those tests to an existing test file, I could see the problem is solved. 
@markdroth Can you please take a final look on this and see if this change looks good to you? I will go ahead and fix the internal call-sites once this gets approved. We have quite a few call-sites and it might take a while to fix them.
Note that this is intended to solve problems like https://github.com/grpc/grpc/issues/24684, and we also have some internal users reporting similar issues as well.
Once this PR is finally merged, I will create finish these leftover works in separate PRs:
1. add a compare() function to grpc_tls_credentials_options, and complete the compare() function in the security connector
2. add a separate option field to specify if application wants check_per_call_host().

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MgRKkDEClU0VqoURWk6:b-cxkndt)* status: 55 of 57 files reviewed, 7 unresolved discussions (waiting on @markdroth, @yashykt, and @ZhenLian)

___
*[include/grpcpp/security/tls_certificate_verifier.h, line 87 at r14](https://reviewable.io/reviews/grpc/grpc/25631#-MaTtgLR-_S00fKMOyOT:-MgRMQ2v-gy6puJu24l_:b-gjabv2) ([raw file](https://github.com/grpc/grpc/blob/12fe5122306b08f6ba043a65071d6abf401bc991/include/grpcpp/security/tls_certificate_verifier.h#L87)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Yeah, they are mainly used for debugging purpose. Let's keep this open, and I've reply to this comment again once all of them get removed.
</blockquote></details>

All the log messages shall be removed.
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 322 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWAtY1Z3Tr_aUgDXGb5:-MgRO3CL8XehFmqNAbrv:b-3v1kcq) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L322)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I see, that's pretty clear now! I will add a `compare()` function in `grpc_tls_credentials_options` in another PR and then update code here.
</blockquote></details>

I will finish this in a separate PR once this goes in.
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 331 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWAuOOJDrPm2QsvjcL1:-MgRO9PX7WvHXY1FNWP6:b-3v1kcq) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L331)):*
<details><summary><i>Previously, jiangtaoli2016 (Jiangtao Li) wrote…</i></summary><blockquote>

I am fine with adding a separate option field to specify if application wants check_per_call_host.
</blockquote></details>

I will finish this in a separate PR once this goes in.


<!-- Sent from Reviewable.io -->

2021-08-06 17:06 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: 32 of 57 files reviewed, 7 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 85 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0vC5n7MOYsKGWfm1Z:-MgRPaMJ5DpOrrBbI7sA:b-blrpt9) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/src/core/lib/security/credentials/xds/xds_credentials.cc#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this the right behavior?  Does xDS's list of SAN matchers handle both IP and DNS matches?  Or is there some sort of type encoded in the xDS SAN matchers, in which case we'd need to pass both sets of info from the request into a single call to `XdsVerifySubjectAlternativeNames()`?

CC @yashykt 
</blockquote></details>

This is not optimal, but I believe this maintains the existing functionality. There is a TODO in the function `XdsVerifySubjectAlternativeNames` to fix this. Specifically, we want to perform DNS style matching only for DNS names. I can fix this later to unblock this PR


<!-- Sent from Reviewable.io -->

2021-08-06 17:21 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: 32 of 57 files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 106 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW627ff74C_s0aOLFG5:-MgRSCBZ9cbd30x-5SsC:bg2zgo6) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L106)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I could go either way on this, but I suspect that we should be consistent between the xDS and non-xDS use-cases.  @yashykt may have insight as to the requirements in the xDS case.
</blockquote></details>

I'm not sure I understand. The logic in `VerifySubjectAlternativeName` does accept `*.com` as a valid SAN. There is a test for the same https://github.com/grpc/grpc/blob/2ea6aefd4b2fb14dee032197bcf969f24c525c3c/test/core/security/xds_credentials_test.cc#L191

For the matching here, xDS does not have any special requirements. I agree with Mark that we should be consistent here.


<!-- Sent from Reviewable.io -->

2021-08-10 05:29 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: 32 of 57 files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 106 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW627ff74C_s0aOLFG5:-MgiWdOj82S4BlgsBC8j:b84j2zj) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L106)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I'm not sure I understand. The logic in `VerifySubjectAlternativeName` does accept `*.com` as a valid SAN. There is a test for the same https://github.com/grpc/grpc/blob/2ea6aefd4b2fb14dee032197bcf969f24c525c3c/test/core/security/xds_credentials_test.cc#L191

For the matching here, xDS does not have any special requirements. I agree with Mark that we should be consistent here.
</blockquote></details>

Yes, the current implementation matches the logic we have for xDS. Our old implementation is a bit different, but it's minor. I think it's ok to just keep the code as it is right now, which is to use xDS as a reference for traditional host name checking.


<!-- Sent from Reviewable.io -->

2021-08-17 22:42 UTC, markdroth requested changes
We need to understand what's causing the problem here before we can merge this.  It's not okay to just delete tests that are failing or move tests around randomly until they work.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r19, 23 of 23 files at r20.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MhLGoNX2z2rUYec8X7G:bpras05)* status: all files reviewed, 9 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 331 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWAuOOJDrPm2QsvjcL1:-MhLBE_a2xft3RV-8zzS:b6n5ndj) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L331)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I will finish this in a separate PR once this goes in.
</blockquote></details>

Okay.  Please make this comment a TODO.
___
*[test/core/security/grpc_tls_certificate_verifier_test.cc, line 75 at r12](https://reviewable.io/reviews/grpc/grpc/25631#-MhLE5GyAfWb0_u7P2iE:-MhLE5GyAfWb0_u7P2iF:bs0icr4) ([raw file](https://github.com/grpc/grpc/blob/e0a1beb5b29f5e0ae6b1ffb8f62914e3991ad598/test/core/security/grpc_tls_certificate_verifier_test.cc#L75)):*
> ```cpp
> }
> 
> TEST_F(GrpcTlsCertificateVerifierTest, AsyncExternalVerifierSucceeds) {
> ```

These tests should not be removed.  If they are failing, we need to figure out why and address the underlying problem.
___
*[test/core/util/tls_utils.cc, line 110 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0wcn48WohlCkrfZjq:-MhLEsVb3RYMWdt1XMw8:b-hdn5qm) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/test/core/util/tls_utils.cc#L110)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I finally managed to make that TSAN issue away by adding the `gpr_event`(see the commit before the latest commit for the code change), but it appears there are more issues ahead of us(ASAN[1], MSAN[2] and UBSAN[3]). All of those 3 failures come from `grpc_tls_certificate_verifier_test`.
That makes me wondering if we really want that test at all. The verifier is expected to be put into a credential options afterwards, while in `grpc_tls_certificate_verifier_test`, it is created, and then we are done. It gives me a sense that we are just partially test its behavior. Besides, we already have the tests covering the whole process in  `tls_security_connector_test` and `h2_tls.cc`(though I also feel a bit disappointed by knowing our test only works for "creating async verifier and then putting it to options" as a whole, but doesn't work for creating a single async verifier object).
Another incentive for removing those tests is that we will need to add the `gpr_event` to our async verifier, to possibly support them. Other tests won't have the similar issue. So the `gpr_event` is added specifically for `grpc_tls_certificate_verifier_test`.
I've removed the async verifier tests in `grpc_tls_certificate_verifier_test` to be able to move forward, but feel free to let me know if you feel differently and I could add those tests back.


[1] https://source.cloud.google.com/results/invocations/71f837b8-3728-446b-acee-466ca5663a4b/targets
[2] https://source.cloud.google.com/results/invocations/d586074f-5bf0-415b-a6ad-87f0cc1c427a/targets
[3] https://source.cloud.google.com/results/invocations/bbb871ea-8d45-45f7-806c-6fe6034783fc/targets
</blockquote></details>

I am not comfortable with just removing problematic tests -- or moving tests from one file to another to magically make them work -- without actually understanding what's causing the problem.  If we don't understand this, then how do we know that there are not actual bugs in the implementation?

All three of these failures look like basically exactly the same problem.  There is an `OnVerifyDone()` callback that is being invoked after gRPC is shutting down.

Did you try what I suggested above about calling `grpc_init()` before spawning the destruction thread and then calling `grpc_shutdown()` at the end of `DestroyExternalVerifier()`?

If that doesn't work, try moving the call to `grpc_init()` to the `AsyncExternalVerifier` ctor.
___
*[test/core/util/tls_utils.cc, line 132 at r20](https://reviewable.io/reviews/grpc/grpc/25631#-MhLETgU5ieS1SpVRA_i:-MhLETgU5ieS1SpVRA_j:b-s3p07l) ([raw file](https://github.com/grpc/grpc/blob/3a0d589fd380860969d521518556c8ec9917c628/test/core/util/tls_utils.cc#L132)):*
> ```cpp
>   grpc_core::Thread destroy_thread(
>       "DestroyExternalVerifier", DestroyExternalVerifier, self, nullptr,
>       grpc_core::Thread::Options().set_joinable(false).set_tracked(false));
> ```

There is no need to set this to non-tracked.  The "tracked" bit is only used for fork support in wrapped languages like python, and those languages will never use this test file.
___
*[test/cpp/server/credentials_test.cc, line 164 at r20](https://reviewable.io/reviews/grpc/grpc/25631#-MhLGU3REpWucpqt9Oo8:-MhLGU3REpWucpqt9Oo9:b1zy7vj) ([raw file](https://github.com/grpc/grpc/blob/3a0d589fd380860969d521518556c8ec9917c628/test/cpp/server/credentials_test.cc#L164)):*
> ```cpp
> }
> 
> TEST(TlsCertificateVerifierTest, SyncCertificateVerifierSucceeds) {
> ```

Please move these back to their own test file where they belong.  If that is triggering a bug, then we need to figure out what's causing that, not work around it by moving tests around randomly until things happen to work.


<!-- Sent from Reviewable.io -->

2021-08-19 02:22 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: 36 of 57 files reviewed, 9 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[test/core/util/tls_utils.cc, line 110 at r16](https://reviewable.io/reviews/grpc/grpc/25631#-Me0wcn48WohlCkrfZjq:-MhMwrpo7UcJ-BJVhO9o:b5hozsc) ([raw file](https://github.com/grpc/grpc/blob/abfaf09afdd8abc5b41c29f0083cd4c0dd266fb6/test/core/util/tls_utils.cc#L110)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I am not comfortable with just removing problematic tests -- or moving tests from one file to another to magically make them work -- without actually understanding what's causing the problem.  If we don't understand this, then how do we know that there are not actual bugs in the implementation?

All three of these failures look like basically exactly the same problem.  There is an `OnVerifyDone()` callback that is being invoked after gRPC is shutting down.

Did you try what I suggested above about calling `grpc_init()` before spawning the destruction thread and then calling `grpc_shutdown()` at the end of `DestroyExternalVerifier()`?

If that doesn't work, try moving the call to `grpc_init()` to the `AsyncExternalVerifier` ctor.
</blockquote></details>


I made the changes to put `grpc_init()` in `AsyncExternalVerifier` ctor, and `grpc_shutdown()` at the end of `DestroyExternalVerifier()`, but since `AsyncExternalVerifier` is a class that is shared by multiple tests, it caused many tests in `h2_tls.cc` to fail. I added a guardian if-else in the latest commit, and here are the failing tests:

Bazel RBE MSAN C/C++: https://source.cloud.google.com/results/invocations/049f548c-ef3a-4892-9174-1f11ceff40e0/targets/%2F%2Ftest%2Fcore%2Fsecurity:grpc_tls_certificate_verifier_test@poller%3Depoll1/log
Bazel RBE Windows Debug C/C++: https://source.cloud.google.com/results/invocations/e3aadb46-9833-47a2-a182-2805fa7e3be6/targets/%2F%2Ftest%2Fcore%2Fsecurity:grpc_tls_certificate_verifier_test/log

I don't see how adding `grpc_shutdown()` would help the situation...If our problem is that the original `grpc_shutdown()` happens earlier than our `DestroyExternalVerifier()`, how could adding another `grpc_shutdown()` solve the problem? The first `grpc_shutdown()` would still be invoked beforehand, and it would remove some resources that `DestroyExternalVerifier()` might need.
One way to tackle this might be to notify the `gpr_event` at the end of `DestroyExternalVerifier`? Though I observed some other problems while making the code change.
Any help is really appreciated. Thanks Mark!


<!-- Sent from Reviewable.io -->

2021-09-10 21:53 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: 50 of 57 files reviewed, 13 unresolved discussions (waiting on @markdroth and @ZhenLian)

___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 331 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWAuOOJDrPm2QsvjcL1:-MicvuDuDwHPPpFIG4Sd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L331)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  Please make this comment a TODO.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_verifier_test.cc, line 82 at r22](https://reviewable.io/reviews/grpc/grpc/25631#-MhTypWpEulvjGnHccs1:-MjG_wrO1FQjMBrq6mKI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fd8272618614a69719368e40e97d28fba652d0d3/test/core/security/grpc_tls_certificate_verifier_test.cc#L82)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be a local variable; it does not need to be dynamically allocated.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_verifier_test.cc, line 79 at r24](https://reviewable.io/reviews/grpc/grpc/25631#-Mi7OBMg00N0Vf9Ceyzn:-MjG_ucP5mUDIBQM1sAr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf6071bf8f8592abcbb291dd8d45abc501421c90/test/core/security/grpc_tls_certificate_verifier_test.cc#L79)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is needed anymore.  Now that you're ensuring that the test won't exit until the callback is invoked, the shutdown can continue beyond the end of this test without hurting anything.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_verifier_test.cc, line 86 at r24](https://reviewable.io/reviews/grpc/grpc/25631#-Mi7OEtc6RQbu-9_KAvB:-MjG_vvzC74bbdQFUfMO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf6071bf8f8592abcbb291dd8d45abc501421c90/test/core/security/grpc_tls_certificate_verifier_test.cc#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you can just have the callback below set this event, so that `AsyncExternalVerifier` itself does not need to be aware of it at all.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_verifier_test.cc, line 116 at r24](https://reviewable.io/reviews/grpc/grpc/25631#-Mi7Ojp42_dqXZVO8-oT:-MjG_xgPAvFLcxJFJwRF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf6071bf8f8592abcbb291dd8d45abc501421c90/test/core/security/grpc_tls_certificate_verifier_test.cc#L116)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as above: this is not necessary.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_verifier_test.cc, line 123 at r24](https://reviewable.io/reviews/grpc/grpc/25631#-Mi7PEes9T5NJINj_xR1:-MjG_yP76cE-8efopmQB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf6071bf8f8592abcbb291dd8d45abc501421c90/test/core/security/grpc_tls_certificate_verifier_test.cc#L123)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as above: This event can be set in the callback below, so that `AsyncExternalVerifier` does not need to be aware of it.
</blockquote></details>

Done.
___
*[test/core/security/grpc_tls_certificate_verifier_test.cc, line 125 at r24](https://reviewable.io/reviews/grpc/grpc/25631#-Mi7POREATXv6-vP7IKq:-MjG_z-T7RwevXsl2vso:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf6071bf8f8592abcbb291dd8d45abc501421c90/test/core/security/grpc_tls_certificate_verifier_test.cc#L125)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as above: This can be a local variable instead of being dynamically allocated.
</blockquote></details>

Done.
___
*[test/core/util/tls_utils.h, line 95 at r24](https://reviewable.io/reviews/grpc/grpc/25631#-Mi7Pa-U0yevX-jxUTRY:-MjGa-Hn6JbhpUoGPXF5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf6071bf8f8592abcbb291dd8d45abc501421c90/test/core/util/tls_utils.h#L95)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned elsewhere, I don't think either of these parameters are needed.
</blockquote></details>

Done.
___
*[test/core/util/tls_utils.cc, line 135 at r24](https://reviewable.io/reviews/grpc/grpc/25631#-Mi7PjdU5sakleSuZO46:-MjGa6cm92mKqUGKUuOG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf6071bf8f8592abcbb291dd8d45abc501421c90/test/core/util/tls_utils.cc#L135)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned elsewhere, I don't think we actually need this shutdown event at all.  But if we did, this would be the wrong place for it: instead, it should have actually gone in the dtor, because that's where the shutdown thread is actually finishing.
</blockquote></details>

Done.
___
*[test/core/util/tls_utils.cc, line 176 at r24](https://reviewable.io/reviews/grpc/grpc/25631#-Mi7Q4o33h9ChvaIBz8e:-MjGa7Tt-ckcKmicfFmQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cf6071bf8f8592abcbb291dd8d45abc501421c90/test/core/util/tls_utils.cc#L176)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be checking `self->callback_completed_event_`, not `self->thread_shutdown_event_`.

But as mentioned elsewhere, I don't think we need this to begin with.
</blockquote></details>

Done.
___
*[test/cpp/server/credentials_test.cc, line 164 at r20](https://reviewable.io/reviews/grpc/grpc/25631#-MhLGU3REpWucpqt9Oo8:-MjGa8HEBGWf8IcsD0oy:b-u12k62) ([raw file](https://github.com/grpc/grpc/blob/3a0d589fd380860969d521518556c8ec9917c628/test/cpp/server/credentials_test.cc#L164)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see any obvious problem.  Have you tried using gdb?
</blockquote></details>

I've finally reproduced the problem on my Mac successfully, and found the root cause of the problem. I am still confused on the reason behind though, but I already found some alternatives to solve this problem. 
The culprit is [1], where the `g_core_codegen_interface` is nullptr when Mutex() is called. I am not sure why though, especially when this only happens to Mac system. (BTW, I don't see how `g_core_codegen_interface` is constructed. Is it a global variable, and what's its use?) 

I found two ways to solve the problem:
1. add a dummy test as shown in the latest commit. I have no idea why this can "magically" solve the issue(Shouldn't each TEST(...) be independent??). I guess the extra test called some global functions, which in turn set up the value of `g_core_codegen_interface`. And the result is not order-dependent: even if I move this test to the end of the file, the result was the same
2. we use `grpc_core::Mutex` or `absl::Mutex` in `grpc/include/grpcpp/security/tls_certificate_verifier.h`. But is it allowed?

Any other thoughts on this? I've been stuck here for a week and has run out of my ways. In the worst case, I thought we could probably disable the whole API use on Mac first, as well as keep looking for the solution, to make the entire thing moving forward?

Any help is really appreciated!

[1] https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/sync.h#L61


<!-- Sent from Reviewable.io -->

2021-09-11 00:30 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: 50 of 57 files reviewed, 13 unresolved discussions (waiting on @markdroth and @ZhenLian)

___
*[test/cpp/server/credentials_test.cc, line 164 at r20](https://reviewable.io/reviews/grpc/grpc/25631#-MhLGU3REpWucpqt9Oo8:-MjHEI04CUgmcj3STx4u:bemvtws) ([raw file](https://github.com/grpc/grpc/blob/3a0d589fd380860969d521518556c8ec9917c628/test/cpp/server/credentials_test.cc#L164)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I've finally reproduced the problem on my Mac successfully, and found the root cause of the problem. I am still confused on the reason behind though, but I already found some alternatives to solve this problem. 
The culprit is [1], where the `g_core_codegen_interface` is nullptr when Mutex() is called. I am not sure why though, especially when this only happens to Mac system. (BTW, I don't see how `g_core_codegen_interface` is constructed. Is it a global variable, and what's its use?) 

I found two ways to solve the problem:
1. add a dummy test as shown in the latest commit. I have no idea why this can "magically" solve the issue(Shouldn't each TEST(...) be independent??). I guess the extra test called some global functions, which in turn set up the value of `g_core_codegen_interface`. And the result is not order-dependent: even if I move this test to the end of the file, the result was the same
2. we use `grpc_core::Mutex` or `absl::Mutex` in `grpc/include/grpcpp/security/tls_certificate_verifier.h`. But is it allowed?

Any other thoughts on this? I've been stuck here for a week and has run out of my ways. In the worst case, I thought we could probably disable the whole API use on Mac first, as well as keep looking for the solution, to make the entire thing moving forward?

Any help is really appreciated!

[1] https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/sync.h#L61
</blockquote></details>

Oh, it suddenly came to my mind that could this be related to the fact that the creation of two classes(`CertificateVerifier` and `ExternalCertificateVerifier`)was at the complied time(in the `.h` file), not the runtime(in the `.cc` file)? Maybe at the compile time `g_core_codegen_interface` was not fully set up yet. Just throwing out some random ideas, in case any of them could help...


<!-- Sent from Reviewable.io -->

2021-10-08 21:32 UTC, markdroth requested changes
This looks really good!  I did one more complete pass and found a few minor things to be cleaned up, but then we can get this merged!

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 23 files at r20, 5 of 7 files at r25, 32 of 32 files at r26, 4 of 4 files at r27.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MlWo_2vB0p72SkX-xfJ:b54rwyi)* status: all files reviewed, 6 unresolved discussions (waiting on @yashykt and @ZhenLian)

___
*[include/grpc/grpc_security.h, line 938 at r27](https://reviewable.io/reviews/grpc/grpc/25631#-MlWS5w-7fQIxEmK6WP9:-MlWS5w-7fQIxEmK6WPA:b-sc504h) ([raw file](https://github.com/grpc/grpc/blob/7306d2c80f293e9aa2b924eacb55d9833e48b285/include/grpc/grpc_security.h#L938)):*
> ```objc
>  * The read-only request information exposed in a verification call.
>  * Callers should not directly manage the ownership of it. We will make sure it
>  * is always available inside schedule() or cancel() call, and will destroy the
> ```

s/schedule()/verify()/
___
*[include/grpcpp/security/tls_certificate_verifier.h, line 60 at r27](https://reviewable.io/reviews/grpc/grpc/25631#-MlWUBHP4CIiasN4_l7t:-MlWUBHP4CIiasN4_l7u:b-ezekxi) ([raw file](https://github.com/grpc/grpc/blob/7306d2c80f293e9aa2b924eacb55d9833e48b285/include/grpcpp/security/tls_certificate_verifier.h#L60)):*
> ```objc
>   ~TlsCustomVerificationCheckRequest() {}
> 
>   // TODO(ZhenLian): change the return type to absl::string_view if we wind up
> ```

It was pointed out to me recently that we have a `grpc::string_ref` class that does basically the same thing as `absl::string_view`, so let's go ahead and use that here.

https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/string_ref.h
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 106 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MW627ff74C_s0aOLFG5:-MlWebMZAgWkd4UQTX-x:b1wnl6d) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L106)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Yes, the current implementation matches the logic we have for xDS. Our old implementation is a bit different, but it's minor. I think it's ok to just keep the code as it is right now, which is to use xDS as a reference for traditional host name checking.
</blockquote></details>

Looks like this never got resolved.  Can we do something to make this behavior consistent between the xDS and non-xDS cases, and share as much of the implementation as reasonable?
___
*[src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc, line 160 at r27](https://reviewable.io/reviews/grpc/grpc/25631#-MlWf70e5FqjUhLxre59:-MlWf70e5FqjUhLxre5A:beh8lg6) ([raw file](https://github.com/grpc/grpc/blob/7306d2c80f293e9aa2b924eacb55d9833e48b285/src/core/lib/security/credentials/tls/grpc_tls_certificate_verifier.cc#L160)):*
> ```cpp
>   std::function<void(absl::Status)> async_cb =
>       [callback, request, callback_arg](absl::Status async_status) {
>         if (async_status.ok()) {
> ```

Is this conditional actually needed?  I think if `ok()` is true, then `code()` will return OK and `message()` will return the empty string, so we could just unconditionally pass those values to the callback.
___
*[src/core/lib/security/credentials/tls/tls_credentials.cc, line 63 at r27](https://reviewable.io/reviews/grpc/grpc/25631#-MlWfkW_D-QDKpWKzSeZ:-MlWfkWa9X4UOB2PRT6J:b-93c7sh) ([raw file](https://github.com/grpc/grpc/blob/7306d2c80f293e9aa2b924eacb55d9833e48b285/src/core/lib/security/credentials/tls/tls_credentials.cc#L63)):*
> ```cpp
>             "No verifier specified on the client side. Using default hostname "
>             "verifier");
>     grpc_tls_certificate_verifier* hostname_verifier =
> ```

These next three statements can be combined into one:

```
options->set_certificate_verifier(
    grpc_core::MakeRefCounted<grpc_core::HostNameCertificateVerifier>());
```
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 322 at r2](https://reviewable.io/reviews/grpc/grpc/25631#-MWAtY1Z3Tr_aUgDXGb5:-MlWk8tn1CJEaGAOTWW1:b-5vvrw) ([raw file](https://github.com/grpc/grpc/blob/1479e420a2731d2b5ffcc59460d419108de619b0/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L322)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I will finish this in a separate PR once this goes in.
</blockquote></details>

We really need to fix this, or it will be a security problem.  Can you please put together another PR to do this ASAP?  Thanks!
___
*[src/core/lib/security/security_connector/tls/tls_security_connector.cc, line 408 at r27](https://reviewable.io/reviews/grpc/grpc/25631#-MlWkLdgB_JI6uZsFEJH:-MlWkLdgB_JI6uZsFEJI:b-obxoqb) ([raw file](https://github.com/grpc/grpc/blob/7306d2c80f293e9aa2b924eacb55d9833e48b285/src/core/lib/security/security_connector/tls/tls_security_connector.cc#L408)):*
> ```cpp
>     absl::string_view host, grpc_auth_context* auth_context,
>     grpc_closure* /*on_call_host_checked*/, grpc_error_handle* error) {
>   // TODO(ZhenLian): Add explicitly in tls_credentials_options saying if a
> ```

We need to make sure to follow up on this as well.


<!-- Sent from Reviewable.io -->

2021-10-20 04:49 UTC, ZhenLian reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631)* status: all files reviewed, 2 unresolved discussions (waiting on @markdroth and @ZhenLian)

___
*[include/grpcpp/security/tls_certificate_verifier.h, line 60 at r27](https://reviewable.io/reviews/grpc/grpc/25631#-MlWUBHP4CIiasN4_l7t:-MmQiRym7g-TQDuI4m65:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7306d2c80f293e9aa2b924eacb55d9833e48b285/include/grpcpp/security/tls_certificate_verifier.h#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The methods that return vectors can use `grpc::string_ref` as well.

Also, you can remove the TODO now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-21 04:49 UTC, ZhenLian reviewed
Thanks for the comments so far!
It's pretty weird that this PR begins to fail on Sanity Checks (internal CI): https://source.cloud.google.com/results/invocations/4de759c1-e198-45ff-81d5-2fc00cbb8425/targets, while my latest change has nothing to do with the build system. I ran `./tools/buildgen/generate_projects.sh` locally but it didn't give me any diff as shown in the pre-submit checks.
@markdroth do you know any recent changes on the build files,  especially `./CMakeLists.txt`? Maybe @veblush can comment on this as well.

(P.S: I will put this PR as my highest priority, as it periodically caused headaches when I tried to keep up with the latest changes/resolve conflicts. Once it gets approved, I also need to cherry-pick it to fix internal call-sites, and I am not sure if some weird bugs would happen. I am very concerned that this PR becomes too big to merge in and we have an endless string of problems to fix. Hopefully we can make some progress soon!)

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25631#-:-MmW6YJV5vKqYJTZkJ57:b-swrfhk)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 166 at r28](https://reviewable.io/reviews/grpc/grpc/25631#-MmPkC3X9b8XUHm8R4r2:-MmW60ST5NfGiMGr6-gm:biki62c) ([raw file](https://github.com/grpc/grpc/blob/c383b46b3269542aae57d67dbb2d08d5bcf47820/src/core/lib/security/credentials/xds/xds_credentials.cc#L166)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I *think* this is right, since we're using the SAN verification here instead of a secure naming check, but I'd like @yashykt to give me a sanity check here.

Have we considered what happens if a user sets the host on a per-call basis when using xDS?
</blockquote></details>

@yashykt Hi Yash, would you mind leaving some of your inputs here?


<!-- Sent from Reviewable.io -->

2021-11-10 21:08 UTC, ZhenLian commented
The Windows tests are failing because of a known issue, and the error logs seems related to the setup settings, not this PR.
The Interop cloud-to-cloud tests failing is a known issue: https://github.com/grpc/grpc/issues/24375
I am going to merge this soon.

2021-11-10 21:45 UTC, merged