Rbac AuthorizationEngine implementation.
grpc/grpc pull request #25653
Opened 2021-03-09 04:35 UTC by ashithasantosh

Rbac AuthorizationEngine implementation [WIP - Do not Review]

2021-03-16 18:15 UTC, ashithasantosh commented
@ZhenLian @jiangtaoli2016 @markdroth Friendly ping!:)

2021-03-17 06:59 UTC, ZhenLian requested changes
Thanks Ashitha for the pull request. Looks pretty good overall! I left some comments. Feel free to let me know any questions/concerns. Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653#-:-MVyyY-b2TCdmFpa44L4:b-wha6fh)* status: 0 of 22 files reviewed, 18 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @markdroth)

___
*[src/core/lib/security/authorization/evaluate_args.h, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxJiDs9UbRN3oy_6aV:-MVxJiDs9UbRN3oy_6aW:b-5mq2wz) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.h#L53)):*
> ```objc
>   absl::optional<absl::string_view> GetHeaderValue(
>       absl::string_view key, std::string* concatenated_value) const;
>   std::string GetLocalAddress() const;
> ```

Can I know why we are changing from an `absl::string_view` to a `std::string` here? 
___
*[src/core/lib/security/authorization/evaluate_args.h, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxMAVf6L4pQTvMHv9g:-MVxMAVf6L4pQTvMHv9h:bjrzm57) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.h#L58)):*
> ```objc
>   int GetPeerPort() const;
>   absl::string_view GetSpiffeId() const;
>   absl::string_view GetCertServerName() const;
> ```

What is the cert server name? 
___
*[src/core/lib/security/authorization/evaluate_args.h, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxKpg_8yDjTTZkY-D8:-MVxKpg_8yDjTTZkY-D9:btdhgfx) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.h#L59)):*
> ```objc
>   absl::string_view GetSpiffeId() const;
>   absl::string_view GetCertServerName() const;
>   absl::string_view GetTransportSecurityType() const;
> ```

Is this `EvaluateArgs` going to be used by multiple transport security types, like "tls" or "ssl"? If so, I think it might make sense for this class to contain a 1:1 mapping with what we have in the peer certificate, instead of we parse things like SPIFFE ID ahead of time. For example, instead of 
```
absl::string_view GetSpiffeId() const;
```
It probably makes more sense to have:
```
std::vector<absl::string_view>  GetPeerURIFields() const;
```
and leave the authz logic to the caller of `EvaluateArgs`.
___
*[src/core/lib/security/authorization/evaluate_args.h, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxMsfM34-vZ3sftlK-:-MVxMsfM34-vZ3sftlK0:bx9ikgf) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.h#L62)):*
> ```objc
> 
>  private:
>   grpc_metadata_batch* metadata_;
> ```

nit: for these pointers, can we initialize them with `nullptr`? Otherwise they will be undefined, and hard to debug if something goes wrong.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 107 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxP_4E2IuFiCE8iqEv:-MVxP_4E2IuFiCE8iqEw:b-6kyqm6) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L107)):*
> ```cpp
>       URI::Parse(grpc_endpoint_get_local_address(endpoint_));
>   absl::string_view host;
>   absl::string_view port;
> ```

nit: maybe we could cache `host` and `port`(or `uri`) to this class(instead of `endpoint_`), to avoid writing the similar logic twice. 
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxPtKe6cthmxsgyZY6:-MVxPtKe6cthmxsgyZY7:bn579t8) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L122)):*
> ```cpp
>     return "";
>   }
>   absl::StatusOr<URI> uri = URI::Parse(grpc_endpoint_get_peer(endpoint_));
> ```

Nit: we could probably cache a peer_uri and a local_uri...
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 166 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxQGTM1Z-FyQay_MQ9:-MVxQGTM1Z-FyQay_MQA:b-d3p5pi) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L166)):*
> ```cpp
>   }
>   grpc_auth_property_iterator it = grpc_auth_context_find_properties_by_name(
>       auth_context_, GRPC_X509_CN_PROPERTY_NAME);
> ```

OK, now I get this is to get the common name... Let's find a better name for it, maybe `GetCommonNameInPeerCerts` or `GetPeerCommonName`? 
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 168 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxR4ShCB3gCVoLcal4:-MVxR4Si-DmUiSpCM1vQ:b4xp70e) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L168)):*
> ```cpp
>       auth_context_, GRPC_X509_CN_PROPERTY_NAME);
>   const grpc_auth_property* prop = grpc_auth_property_iterator_next(&it);
>   if (prop == nullptr || grpc_auth_property_iterator_next(&it) != nullptr) {
> ```

nit: I know this is some previous code, but IIRC, the CN should alway be unique. If it is not, there might be something wrong... we could probably do a GPR_ASSERT() here if multiple CN(s) exist? 
Returning an empty string when there are multiple CNs doesn't look straightforward to me, and IMO will be hard to debug if something goes wrong...
Same for the security type as well.
___
*[src/core/lib/security/authorization/matchers.h, line 180 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVywf3sCIt9iGSbcoU-:-MVywf3sCIt9iGSbcoU0:befi54k) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.h#L180)):*
> ```objc
>   const StringMatcher matcher_;
>   // Negates matching the provided permission/principal.
>   const bool not_rule_;
> ```

Is it aligned with the envoy proto that every matcher has a pairing not rule?
I vaguely remembered the envoy implementation had a "Not" matcher. Logically speaking, if you want to negate the result of a matcher, you can incorporate it with a "not" matcher, right? Did we consider that?
___
*[test/core/security/authorization_matchers_test.cc, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVyonWD-3WN6jETHe7A:-MVyonWECTyHHSQLyNtk:bqy3avx) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/test/core/security/authorization_matchers_test.cc#L56)):*
> ```cpp
> 
> TEST(AuthorizationMatchersTest, AndMatcherSuccessfulMatch) {
>   grpc_init();
> ```

We've repeated this multiple times...Can we move this the the main function to avoid that?
___
*[test/core/security/authorization_matchers_test.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVyp5c81wylMCPmdnCc:-MVyp5c92brZ-F7yvOXp:b6ev8ie) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/test/core/security/authorization_matchers_test.cc#L62)):*
> ```cpp
>   AddPairToMetadataBatch(&metadata, &storage, /*key=*/"foo",
>                          /*value=*/"bar");
>   MockEvalArgsEndpoint endpoint(/*local_uri=*/"ipv4:255.255.255.255:123",
> ```

We have a lot of the similar test settings. Maybe we can have a fixture that initiates everything, and here in `TEST_F` we just call in the corresponding fields? That might save lots of code as well.
___
*[test/core/security/authorization_matchers_test.cc, line 79 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVyqTQC51r-wnnMEYKA:-MVyqTQC51r-wnnMEYKB:b-7veta3) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/test/core/security/authorization_matchers_test.cc#L79)):*
> ```cpp
> }
> 
> TEST(AuthorizationMatchersTest, AndMatcherFailsMatch) {
> ```

nit: s/Fails/Failed/g
___
*[test/core/security/authorization_matcher [...]

2021-03-18 19:29 UTC, markdroth requested changes
Sorry for the delay on this.  This looks like a great start!

Please let me know if you have any questions.  Thanks!

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653#-:-MW5nx4w4Yi9ikRh-1XW:bt138t)* status: all files reviewed, 24 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.h, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxKpg_8yDjTTZkY-D8:-MW5gbQ73OQlkfQ3Od1H:b-h5pv2p) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.h#L59)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Is this `EvaluateArgs` going to be used by multiple transport security types, like "tls" or "ssl"? If so, I think it might make sense for this class to contain a 1:1 mapping with what we have in the peer certificate, instead of we parse things like SPIFFE ID ahead of time. For example, instead of 
```
absl::string_view GetSpiffeId() const;
```
It probably makes more sense to have:
```
std::vector<absl::string_view>  GetPeerURIFields() const;
```
and leave the authz logic to the caller of `EvaluateArgs`.
</blockquote></details>

Note that this is going to be used on a per-call basis, so performance is important.  I don't think we want to allocate a new `std::vector<>` for every call.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 90 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5hHDm4q5sF3mqH1Nv:-MW5hHDm4q5sF3mqH1Nw:b-on8myg) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L90)):*
> ```cpp
>     return "";
>   }
>   absl::StatusOr<URI> uri =
> ```

This new code is definitely the right way to extract the local address from the endpoint.  However, doing this requires a lot of memory allocation and parsing that we don't want to do on a per-call basis, especially since the result will always be the same for every call on a given channel.

I think that we need to restructure this such that the per-channel data is constructed only once, probably in the authz filter's channel data.  We can then pass a pointer to that state into the `EvaluateArgs` struct that we instantiate for each individual call.

The thing that made me notice this was that this function changed to return a `std::string` instead of an `absl::string_view`.  But even creating the `URI` object also allocates memory.  All of this overhead should be moved out of the per-call path, and this method should go back to returning an `absl::string_view`.

Similar thing for all per-channel data.
___
*[src/core/lib/security/authorization/matchers.h, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5itiD1JLhpeUiwgAa:-MW5itiD1JLhpeUiwgAb:bayknq1) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.h#L29)):*
> ```objc
> 
> // Matchers describe the rules for matching permission or principal.
> class Matcher {
> ```

This name is a little too generic for the `grpc_core` namespace.  Let's either call it something like `AuthorizationMatcher` or else move it into some nested namespace.

Same for all of the classes in this file.
___
*[src/core/lib/security/authorization/matchers.h, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5kyPR3QOd_BCElPLZ:-MW5kyPR3QOd_BCElPL_:bqadn9w) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.h#L60)):*
> ```objc
>  public:
>   explicit AndMatcher(
>       const std::vector<std::unique_ptr<Rbac::Permission>>& rules,
> ```

All of these ctors should take their parameters by value instead of as const references.  That way, we can use `std::move()` to save the parts of the policy that we need instead of having to make unnecessary copies all over the place.
___
*[src/core/lib/security/authorization/matchers.h, line 126 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5jyKz3mcvH2m-4H71:-MW5jyKz3mcvH2m-4H72:b-pwhu18) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.h#L126)):*
> ```objc
> class PortMatcher : public Matcher {
>  public:
>   explicit PortMatcher(const int port, bool not_rule = false)
> ```

No need for `const` here.
___
*[src/core/lib/security/authorization/matchers.cc, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5lKSE75Z4YEGvhCZe:-MW5lKSF6yPBZOnXDolz:bwc5lb4) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.cc#L70)):*
> ```cpp
>           permission.string_matcher, permission.not_rule);
>   }
>   gpr_log(GPR_ERROR, "Unexpected Permission rule type.");
> ```

Logging inside of library code like this isn't generally a good idea.  Instead, you'll need to return null and have the caller figure out how to handle the error.
___
*[src/core/lib/security/authorization/matchers.cc, line 97 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5lZvG9TaocPjb4KSc:-MW5lZvG9TaocPjb4KSd:b-w8dsft) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.cc#L97)):*
> ```cpp
>                                             principal.not_rule);
>   }
>   gpr_log(GPR_ERROR, "Unexpected Principal rule type.");
> ```

Same as above: return null instead of logging.
___
*[test/core/security/authorization_matchers_test.cc, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVyonWD-3WN6jETHe7A:-MW5lxj68R12kWNTVeyp:b-3nbk6d) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/test/core/security/authorization_matchers_test.cc#L56)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

We've repeated this multiple times...Can we move this the the main function to avoid that?
</blockquote></details>

Agreed, let's just move `grpc_init()` and `grpc_shutdown()` to `main()`.
___
*[test/core/security/authorization_matchers_test.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVyp5c81wylMCPmdnCc:-MW5m6no6JevxPGpSwHZ:b-wa14mb) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/test/core/security/authorization_matchers_test.cc#L62)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

We have a lot of the similar test settings. Maybe we can have a fixture that initiates everything, and here in `TEST_F` we just call in the corresponding fields? That might save lots of code as well.
</blockquote></details>

It's definitely a good idea to create helper functions in a test suite class to avoid boilerplate in individual tests.  But please make sure to do this in a way that does not move any of the actual test data out of the individual tests, even if that's a little repetetive.  The goal here should be that each test can be easily understood just by reading the test; you should not have to keep jumping back up to the test suite class to see a bunch of global defines in order to understand the inputs and outputs covered in an individual test.
___
*[test/core/util/mock_eval_args_endpoint.h, line 24 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVymVTd7PQObM4lfCZt:-MW5nrnG63AjDHBgJCjU:b-pbdqz3) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/test/core/util/mock_eval_args_endpoint.h#L24)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

optional: if it is a class only used by one test, I slightly prefer to move it directly to that file, to keep files in test/core/util clean...when in the future it is shared, we could move it out to test utils.
</blockquote></details>

Agreed.


<!-- S [...]

2021-03-24 21:57 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653)* status: 8 of 22 files reviewed, 20 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.h, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxMAVf6L4pQTvMHv9g:-MWAv5zDBQ6gIB_OnoVH:bczfqf) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.h#L58)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

What is the cert server name? 
</blockquote></details>

This returns common name in subject field of peer certificate.
___
*[src/core/lib/security/authorization/evaluate_args.h, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxKpg_8yDjTTZkY-D8:-MW_Nuo75UeFi3astz_3:b4fqg77) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.h#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Note that this is going to be used on a per-call basis, so performance is important.  I don't think we want to allocate a new `std::vector<>` for every call.
</blockquote></details>

By adding specific getters, we are only going to parse parameters that are present in authorization policy. Also, like Mark said, since this is going to be per RPC basis, we may not want to allocate a vector.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 90 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5hHDm4q5sF3mqH1Nv:-MWa2EI083uBM9mx_pHm:b-6yyrrp) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L90)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This new code is definitely the right way to extract the local address from the endpoint.  However, doing this requires a lot of memory allocation and parsing that we don't want to do on a per-call basis, especially since the result will always be the same for every call on a given channel.

I think that we need to restructure this such that the per-channel data is constructed only once, probably in the authz filter's channel data.  We can then pass a pointer to that state into the `EvaluateArgs` struct that we instantiate for each individual call.

The thing that made me notice this was that this function changed to return a `std::string` instead of an `absl::string_view`.  But even creating the `URI` object also allocates memory.  All of this overhead should be moved out of the per-call path, and this method should go back to returning an `absl::string_view`.

Similar thing for all per-channel data.
</blockquote></details>

Sounds good. Do correct me if I am wrong. So, we can do all the extraction, to get local (and peer) address and port from endpoint in channel_data in authz filter, and pass a pointer to this channel data to EvaluateArgs. This structure can be used instead of grpc_endpoint in EvaluateArgs. This way we avoid doing all the logic every time an address/port appears in policy and on a per-call basis, and instead do it just once per-channel. Based on my understanding, even the fields in auth_context can be handled similarly. But do we really want separate fields like spiffe_id, transport_security_type etc in channel_data, or we just incur the cost of iterating through the list and let channel_data have grpc_auth_context as a whole.

About the absl::string_view to std::string change, for some reason SplitHostPort returns the entire host:port as host, if we don't use std::string version. I haven't really looked into it yet, will check it out now and update.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 166 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxQGTM1Z-FyQay_MQ9:-MWAvU-gAvYvsXo5deU3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L166)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

OK, now I get this is to get the common name... Let's find a better name for it, maybe `GetCommonNameInPeerCerts` or `GetPeerCommonName`? 
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/matchers.h, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5itiD1JLhpeUiwgAa:-MWB9dUc5kt3jZrOTADv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.h#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This name is a little too generic for the `grpc_core` namespace.  Let's either call it something like `AuthorizationMatcher` or else move it into some nested namespace.

Same for all of the classes in this file.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/matchers.h, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5kyPR3QOd_BCElPLZ:-MW_nNpkADHGbp9WO3pF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.h#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All of these ctors should take their parameters by value instead of as const references.  That way, we can use `std::move()` to save the parts of the policy that we need instead of having to make unnecessary copies all over the place.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/matchers.h, line 126 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5jyKz3mcvH2m-4H71:-MWBBDRgAqp3fLbdB8vF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.h#L126)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `const` here.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/matchers.h, line 180 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVywf3sCIt9iGSbcoU-:-MW_TfZ1DBqCaYjx8rUD:b-92oorw) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.h#L180)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Is it aligned with the envoy proto that every matcher has a pairing not rule?
I vaguely remembered the envoy implementation had a "Not" matcher. Logically speaking, if you want to negate the result of a matcher, you can incorporate it with a "not" matcher, right? Did we consider that?

</blockquote></details>

Yes, both permission and principal fields have not_rule(or not_id) that negates the matching. You are right, Envoy implements a NotMatcher. In our case, since we are representing it as a struct, that would add an additional nesting, which seemed inefficient, hence included the boolean variable for negation.
___
*[src/core/lib/security/authorization/matchers.cc, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5lKSE75Z4YEGvhCZe:-MWAoH7K2ZMeq9ejWm3C:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/matchers.cc#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Logging inside of library code like this isn't generally a good idea.  Instead, you'll need to return null and have the caller figure out how to handle the error.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/matchers.cc, line 97 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5lZvG9TaocPjb4KSc:-MWAoHmJ9snMQjr2ZX9i:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415e [...]

2021-03-24 22:00 UTC, ashithasantosh reviewed
Sorry for the delay. I was mostly OOO, as I was busy with shifting to new apartment. I have resolved majority of the comments. grpc_endpoint related comments are pending.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653#-:-MWaEYlYDxVGrU_r9jDK:bg61l1a)* status: 8 of 22 files reviewed, 20 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, @markdroth, and @ZhenLian)



<!-- Sent from Reviewable.io -->

2021-04-01 07:32 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653)* status: 8 of 22 files reviewed, 20 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.h, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxJiDs9UbRN3oy_6aV:-MXBJPqXATFp3dFGFR40:b-ekfy1i) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.h#L53)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Can I know why we are changing from an `absl::string_view` to a `std::string` here? 
</blockquote></details>

Not sure what is happening, but I get address sanitizer issue on using string_view here. I have added a TODO for now.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 90 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5hHDm4q5sF3mqH1Nv:-MXBJnk23oBCqJSfFiGk:bpaku9j) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L90)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

Sounds good. Do correct me if I am wrong. So, we can do all the extraction, to get local (and peer) address and port from endpoint in channel_data in authz filter, and pass a pointer to this channel data to EvaluateArgs. This structure can be used instead of grpc_endpoint in EvaluateArgs. This way we avoid doing all the logic every time an address/port appears in policy and on a per-call basis, and instead do it just once per-channel. Based on my understanding, even the fields in auth_context can be handled similarly. But do we really want separate fields like spiffe_id, transport_security_type etc in channel_data, or we just incur the cost of iterating through the list and let channel_data have grpc_auth_context as a whole.

About the absl::string_view to std::string change, for some reason SplitHostPort returns the entire host:port as host, if we don't use std::string version. I haven't really looked into it yet, will check it out now and update.
</blockquote></details>

I am getting address sanitizer issues, on using string_view. I am working on debugging it, added a TODO for now.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 168 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxR4ShCB3gCVoLcal4:-MXBICb9D6d3uAwq805Q:bs3y3l7) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L168)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

nit: I know this is some previous code, but IIRC, the CN should alway be unique. If it is not, there might be something wrong... we could probably do a GPR_ASSERT() here if multiple CN(s) exist? 
Returning an empty string when there are multiple CNs doesn't look straightforward to me, and IMO will be hard to debug if something goes wrong...
Same for the security type as well.
</blockquote></details>

I added logs to help with debugging.


<!-- Sent from Reviewable.io -->

2021-04-02 17:19 UTC, ashithasantosh commented
@markdroth @ZhenLian PTAL. Thank you!

2021-04-05 22:56 UTC, ashithasantosh commented
@markdroth @ZhenLian Friendly Ping!:)

2021-04-06 17:50 UTC, markdroth requested changes
Sorry for the delay on this!

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 14 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653#-:-MXcIembE2vbagwPPqjl:b-hnohzg)* status: all files reviewed, 15 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.cc, line 90 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5hHDm4q5sF3mqH1Nv:-MXc1n_I-_YIp8Ju3Brs:brn0jpv) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L90)):*
> So, we can do all the extraction, to get local (and peer) address and port from endpoint in channel_data in authz filter, and pass a pointer to this channel data to EvaluateArgs. This structure can be used instead of grpc_endpoint in EvaluateArgs. This way we avoid doing all the logic every time an address/port appears in policy and on a per-call basis, and instead do it just once per-channel.

Yes, exactly.

> Based on my understanding, even the fields in auth_context can be handled similarly. But do we really want separate fields like spiffe_id, transport_security_type etc in channel_data, or we just incur the cost of iterating through the list and let channel_data have grpc_auth_context as a whole.

I think that we should move as much of this work as possible into channel_data, so that we're doing it once per connection instead of once per call.  The per-call overhead is much more expensive, because there are typically a huge number of calls per connection.

> About the absl::string_view to std::string change, for some reason SplitHostPort returns the entire host:port as host, if we don't use std::string version. I haven't really looked into it yet, will check it out now and update.

I am guessing that the problem you're running into here is that you're trying to treat `host->data()` as a C-style NUL-terminated string.  When you do that, it does not stop at `host->size()`; instead, it continues until it sees a NUL byte, but in this case the byte after the end of the string_view is not NUL, so it gets more than it should.

In general, when you use an `absl::string_view`, you can't just treat it as a C-style string, because there is no guarantee that the byte after the last one is actually a NUL byte.  In fact, there's not even any guarantee that there is a NUL byte anywhere after the end of the string_view; you could just run off the end of your stack and cause a segfault.  If you need to pass a `string_view` to a function expecting a C-style string, you need to do something to ensure that it is NUL-terminated, like `std::string(host).c_str()` (although keep in mind that doing that allocates memory, which is expensive).

> I am getting address sanitizer issues, on using string_view. I am working on debugging it, added a TODO for now.

Note that you can't change this to use string_view without making the other changes I suggested here, because if the value you're returning is a string in the local scope of this function, it will go out of scope when the function returns, and the resulting string_view will point to a string that is no longer allocated.  I think the right approach here is to move the URI parsing into channel_data, which can store a string, and then this method can return a string_view of that string, which remains allocated in channel_data even after this method returns.
___
*[src/core/lib/security/authorization/matchers.cc, line 165 at r3](https://reviewable.io/reviews/grpc/grpc/25653#-MXcDczQ-HIHrp7ejuuB:-MXcDczQ-HIHrp7ejuuC:b-v738fk) ([raw file](https://github.com/grpc/grpc/blob/d3126aeb393c1041925f829c8b1aae27983ea7ac/src/core/lib/security/authorization/matchers.cc#L165)):*
> ```cpp
> }
> 
> // TODO(ashithasantosh): Implement IpAuthorizationMatcher::Matches.
> ```

FYI, @yashykt has recently written some code to do something similar to this as part of the server-side xDS filter chain matching logic.  You may want to work with him to see if there's a useful way to refactor that code so that it can be reused here.
___
*[test/core/security/authorization_matchers_test.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVyp5c81wylMCPmdnCc:-MXcE6514QRdIsBhAaxo:bonetym) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/test/core/security/authorization_matchers_test.cc#L62)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

Here its essentially setting the EvaluateArgs structures and then setting rules. I don't think helper functions would be very helpful. If we say have a helper function for the setting args part, it would mean passing several parameters like header key, values, local uri etc, which seem unrelated, plus it does not reduce much code, and would make the tests less readable. Similarly for the rules. I would prefer the current structure.
</blockquote></details>

I do think a test class would be very useful here in reducing the amount of boilerplate in individual tests.  For example, consider something like the following:

```
class AuthorizationMatchersTest : public ::testing::Test {
 protected:
  void SetUp() override {
    grpc_metadata_batch_init(&metadata_);
  }

  void TearDown() override {
    grpc_metadata_batch_destroy(&metadata_);
  }

  void AddMetadata(const char* key, const char* value) {
    metadata_storage_.emplace_back();
    auto& storage = metadata_storage_.back();
    ASSERT_EQ(grpc_metadata_batch_add_tail(
                  &metadata_, &storage,
                  grpc_mdelem_from_slices(
                      grpc_slice_intern(grpc_slice_from_static_string(key)),
                      grpc_slice_intern(grpc_slice_from_static_string(value)))),
              GRPC_ERROR_NONE);
  }

  EvaluateArgs MakeEvaluateArgs() {
    return EvaluateArgs(&metadata_, nullptr, nullptr);
  }

  grpc_metadata_batch metadata_;
  std::list<grpc_linked_mdelem> metadata_storage_;  
};
```

Now an individual test that wants to add metadata can construct `EvaluateArgs` just by doing this:

```
TEST_F(AuthorizationMatchersTest, AndAuthorizationMatcherSuccessfulMatch) {
  AddMetadata("foo", "bar");
  EvaluateArgs evaluate_args = MakeEvaluateArgs();
  // ...
}
```

That adds the metadata in 1 line of code instead of the current 6 lines.  IMHO, this makes the test *much* more readable.

I think the test class can have similar methods for setting the attributes of the auth context and the endpoint.  That way, each individual test can set only the fields it needs with minimal boilerplate.


<!-- Sent from Reviewable.io -->

2021-04-07 17:19 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653)* status: 20 of 22 files reviewed, 15 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.cc, line 90 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5hHDm4q5sF3mqH1Nv:-MXhJRZG5CmOnj5iJKgU:bpifca9) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L90)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

> So, we can do all the extraction, to get local (and peer) address and port from endpoint in channel_data in authz filter, and pass a pointer to this channel data to EvaluateArgs. This structure can be used instead of grpc_endpoint in EvaluateArgs. This way we avoid doing all the logic every time an address/port appears in policy and on a per-call basis, and instead do it just once per-channel.

Yes, exactly.

> Based on my understanding, even the fields in auth_context can be handled similarly. But do we really want separate fields like spiffe_id, transport_security_type etc in channel_data, or we just incur the cost of iterating through the list and let channel_data have grpc_auth_context as a whole.

I think that we should move as much of this work as possible into channel_data, so that we're doing it once per connection instead of once per call.  The per-call overhead is much more expensive, because there are typically a huge number of calls per connection.

> About the absl::string_view to std::string change, for some reason SplitHostPort returns the entire host:port as host, if we don't use std::string version. I haven't really looked into it yet, will check it out now and update.

I am guessing that the problem you're running into here is that you're trying to treat `host->data()` as a C-style NUL-terminated string.  When you do that, it does not stop at `host->size()`; instead, it continues until it sees a NUL byte, but in this case the byte after the end of the string_view is not NUL, so it gets more than it should.

In general, when you use an `absl::string_view`, you can't just treat it as a C-style string, because there is no guarantee that the byte after the last one is actually a NUL byte.  In fact, there's not even any guarantee that there is a NUL byte anywhere after the end of the string_view; you could just run off the end of your stack and cause a segfault.  If you need to pass a `string_view` to a function expecting a C-style string, you need to do something to ensure that it is NUL-terminated, like `std::string(host).c_str()` (although keep in mind that doing that allocates memory, which is expensive).

> I am getting address sanitizer issues, on using string_view. I am working on debugging it, added a TODO for now.

Note that you can't change this to use string_view without making the other changes I suggested here, because if the value you're returning is a string in the local scope of this function, it will go out of scope when the function returns, and the resulting string_view will point to a string that is no longer allocated.  I think the right approach here is to move the URI parsing into channel_data, which can store a string, and then this method can return a string_view of that string, which remains allocated in channel_data even after this method returns.
</blockquote></details>

Sounds good! Thank you, Mark! You are right, once we make the other changes, only then we will be able to change the return types.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 107 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVxP_4E2IuFiCE8iqEv:-MXhKQ4HB1YypkqfySt5:b-1ad8jq) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L107)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

nit: maybe we could cache `host` and `port`(or `uri`) to this class(instead of `endpoint_`), to avoid writing the similar logic twice. 
</blockquote></details>

We will be moving all the endpoint logic into channel_data of authorization filter, so that it is done on a per-channel basis. I have added a TODO.
___
*[test/core/security/authorization_matchers_test.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVyp5c81wylMCPmdnCc:-MXhKoEZ3SAlpoC1DrDX:by1ey0a) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/test/core/security/authorization_matchers_test.cc#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I do think a test class would be very useful here in reducing the amount of boilerplate in individual tests.  For example, consider something like the following:

```
class AuthorizationMatchersTest : public ::testing::Test {
 protected:
  void SetUp() override {
    grpc_metadata_batch_init(&metadata_);
  }

  void TearDown() override {
    grpc_metadata_batch_destroy(&metadata_);
  }

  void AddMetadata(const char* key, const char* value) {
    metadata_storage_.emplace_back();
    auto& storage = metadata_storage_.back();
    ASSERT_EQ(grpc_metadata_batch_add_tail(
                  &metadata_, &storage,
                  grpc_mdelem_from_slices(
                      grpc_slice_intern(grpc_slice_from_static_string(key)),
                      grpc_slice_intern(grpc_slice_from_static_string(value)))),
              GRPC_ERROR_NONE);
  }

  EvaluateArgs MakeEvaluateArgs() {
    return EvaluateArgs(&metadata_, nullptr, nullptr);
  }

  grpc_metadata_batch metadata_;
  std::list<grpc_linked_mdelem> metadata_storage_;  
};
```

Now an individual test that wants to add metadata can construct `EvaluateArgs` just by doing this:

```
TEST_F(AuthorizationMatchersTest, AndAuthorizationMatcherSuccessfulMatch) {
  AddMetadata("foo", "bar");
  EvaluateArgs evaluate_args = MakeEvaluateArgs();
  // ...
}
```

That adds the metadata in 1 line of code instead of the current 6 lines.  IMHO, this makes the test *much* more readable.

I think the test class can have similar methods for setting the attributes of the auth context and the endpoint.  That way, each individual test can set only the fields it needs with minimal boilerplate.
</blockquote></details>

This is a great idea! Thanks! Updated the tests.


<!-- Sent from Reviewable.io -->

2021-04-07 18:36 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653)* status: 20 of 22 files reviewed, 15 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/matchers.cc, line 165 at r3](https://reviewable.io/reviews/grpc/grpc/25653#-MXcDczQ-HIHrp7ejuuB:-MXhbRD79UAznFaoMo6l:b3a60fb) ([raw file](https://github.com/grpc/grpc/blob/d3126aeb393c1041925f829c8b1aae27983ea7ac/src/core/lib/security/authorization/matchers.cc#L165)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

FYI, @yashykt has recently written some code to do something similar to this as part of the server-side xDS filter chain matching logic.  You may want to work with him to see if there's a useful way to refactor that code so that it can be reused here.
</blockquote></details>

Are we matching Ip Addresses to Cidr ranges here in that case, we already have https://github.com/grpc/grpc/blob/1784e6c96258f41e6dce6c00bc5120ab4915d6bb/src/core/lib/iomgr/sockaddr_utils.h#L87 and https://github.com/grpc/grpc/blob/1784e6c96258f41e6dce6c00bc5120ab4915d6bb/src/core/lib/iomgr/sockaddr_utils.h#L96 for helping with this


<!-- Sent from Reviewable.io -->

2021-04-07 18:46 UTC, markdroth approved these changes
This looks good!  I've got one minor nit remaining in the test, but feel free to merge once that's addressed.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653#-:-MXhdoT13jtmBIDpxr49:bxzcvjq)* status: all files reviewed, 15 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.cc, line 90 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5hHDm4q5sF3mqH1Nv:-MXhdcIIAdXDCJ1VVV0L:b-7ptnqf) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L90)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

Sounds good! Thank you, Mark! You are right, once we make the other changes, only then we will be able to change the return types.
</blockquote></details>

Okay.  I'm assuming you intend to make those changes in a subsequent PR, so I'll resolve this comment.
___
*[test/core/security/authorization_matchers_test.cc, line 80 at r4](https://reviewable.io/reviews/grpc/grpc/25653#-MXhcpa62Oq3XhFzTtbx:-MXhcpa62Oq3XhFzTtby:b-jod2g8) ([raw file](https://github.com/grpc/grpc/blob/731be760d2c3e08195b824a51d1d6c6112b16f42/test/core/security/authorization_matchers_test.cc#L80)):*
> ```cpp
> 
> TEST_F(AuthorizationMatchersTest, AndAuthorizationMatcherSuccessfulMatch) {
>   AddPairToMetadata(/*key=*/"foo",
> ```

I don't think there's any need for comments on the two parameters anymore; they're pretty self-explanatory now.

Same thing for all calls to these helper methods.


<!-- Sent from Reviewable.io -->

2021-04-08 07:23 UTC, ZhenLian approved these changes
Thanks for the update, and sorry for the delay! I have one nit style-comment left, but overall looks pretty good! I will approve right away. 

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653#-:-MXkLaV18_rBqOZg3Nhu:b2spx1h)* status: 21 of 22 files reviewed, 2 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @markdroth)

___
*[test/core/security/authorization_matchers_test.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVyp5c81wylMCPmdnCc:-MXkJFtC5l_cSdVbL3Kk:b-h9qo0d) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/test/core/security/authorization_matchers_test.cc#L62)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

This is a great idea! Thanks! Updated the tests.
</blockquote></details>

Thanks Mark for the detailed suggestion! It looks much cleaner now!
___
*[test/core/security/authorization_matchers_test.cc, line 96 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MVyqq0b616y_yiIHV20:-MXkKyJD8vzwXSnzaFR0:b-15rypw) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/test/core/security/authorization_matchers_test.cc#L96)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

I think helper functions would make the tests difficult to understand, plus we will end up passing several parameters to the function, like header name, header value, type, port number, which don't seem very related. I would prefer the current structure, even though it means duplicating code.
</blockquote></details>

Yeah, I just noticed that for this specific helper function, the input has to be a vector as well. Then I think it doesn't worth the effort.
___
*[test/core/security/authorization_matchers_test.cc, line 300 at r4](https://reviewable.io/reviews/grpc/grpc/25653#-MXkL2rc7Goh08UjXkwc:-MXkL2rc7Goh08UjXkwd:bjophgo) ([raw file](https://github.com/grpc/grpc/blob/731be760d2c3e08195b824a51d1d6c6112b16f42/test/core/security/authorization_matchers_test.cc#L300)):*
> ```cpp
>        HeaderAuthorizationMatcherFailedMatchMultivaluedHeader) {
>   AddPairToMetadata(/*key=*/"key123",
>                     /*value=*/"foo");
> ```

nit: after the change, we don't need to put the above into two lines, right? Same thing throughout.


<!-- Sent from Reviewable.io -->

2021-04-08 18:30 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653)* status: 21 of 22 files reviewed, 2 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.cc, line 90 at r1](https://reviewable.io/reviews/grpc/grpc/25653#-MW5hHDm4q5sF3mqH1Nv:-MXmXeDD80F9Bd7zxtNi:b-64gylt) ([raw file](https://github.com/grpc/grpc/blob/1a01a8b4392415eba851adb62750d0b44b133006/src/core/lib/security/authorization/evaluate_args.cc#L90)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  I'm assuming you intend to make those changes in a subsequent PR, so I'll resolve this comment.
</blockquote></details>

Yes, I will make the above changes in subsequent PRs. Thanks a lot Mark for the detailed review!:)
___
*[src/core/lib/security/authorization/matchers.cc, line 165 at r3](https://reviewable.io/reviews/grpc/grpc/25653#-MXcDczQ-HIHrp7ejuuB:-MXiCBCdDoDB4O6iGUlH:b-goi7gt) ([raw file](https://github.com/grpc/grpc/blob/d3126aeb393c1041925f829c8b1aae27983ea7ac/src/core/lib/security/authorization/matchers.cc#L165)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Are we matching Ip Addresses to Cidr ranges here in that case, we already have https://github.com/grpc/grpc/blob/1784e6c96258f41e6dce6c00bc5120ab4915d6bb/src/core/lib/iomgr/sockaddr_utils.h#L87 and https://github.com/grpc/grpc/blob/1784e6c96258f41e6dce6c00bc5120ab4915d6bb/src/core/lib/iomgr/sockaddr_utils.h#L96 for helping with this
</blockquote></details>

Thanks Yash!
Yes, we will be matching IP address to Cidr range. The addresses will be in string format though. 
We will have to do conversion using
https://github.com/grpc/grpc/blob/5c49bf4209f6e8e864f3f2a8c5f41ffbe450abb2/src/core/lib/iomgr/sockaddr_utils.h#L71 
We could store grpc_resolved_address in our structures instead of string then, to avoid repeating this operation.
___
*[test/core/security/authorization_matchers_test.cc, line 80 at r4](https://reviewable.io/reviews/grpc/grpc/25653#-MXhcpa62Oq3XhFzTtbx:-MXmTXY8DNim74pM2hcG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/731be760d2c3e08195b824a51d1d6c6112b16f42/test/core/security/authorization_matchers_test.cc#L80)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think there's any need for comments on the two parameters anymore; they're pretty self-explanatory now.

Same thing for all calls to these helper methods.
</blockquote></details>

Done.
___
*[test/core/security/authorization_matchers_test.cc, line 300 at r4](https://reviewable.io/reviews/grpc/grpc/25653#-MXkL2rc7Goh08UjXkwc:-MXmTcqABT6Dl1CIJALe:bw9l3g9) ([raw file](https://github.com/grpc/grpc/blob/731be760d2c3e08195b824a51d1d6c6112b16f42/test/core/security/authorization_matchers_test.cc#L300)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

nit: after the change, we don't need to put the above into two lines, right? Same thing throughout.
</blockquote></details>

Did you mean combine two adds to metadata? So the helper method "AddPairToMetadata" here takes a (key,value) pair each time, hence we called the method twice.


<!-- Sent from Reviewable.io -->

2021-04-08 20:02 UTC, markdroth approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiangtaoli2016)

___
*[test/core/security/authorization_matchers_test.cc, line 300 at r4](https://reviewable.io/reviews/grpc/grpc/25653#-MXkL2rc7Goh08UjXkwc:-MXn3mM_5Q0HETgHqlOg:bla3uqo) ([raw file](https://github.com/grpc/grpc/blob/731be760d2c3e08195b824a51d1d6c6112b16f42/test/core/security/authorization_matchers_test.cc#L300)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

Did you mean combine two adds to metadata? So the helper method "AddPairToMetadata" here takes a (key,value) pair each time, hence we called the method twice.
</blockquote></details>

I think he just meant that the second parameter of each `AddPairToMetadata()` call did not need to be on a separate line.  It looks good the way you have it now.


<!-- Sent from Reviewable.io -->

2021-04-08 20:05 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25653)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiangtaoli2016)

___
*[test/core/security/authorization_matchers_test.cc, line 300 at r4](https://reviewable.io/reviews/grpc/grpc/25653#-MXkL2rc7Goh08UjXkwc:-MXn4TbO13Ooae9p43Be:b-krmjeh) ([raw file](https://github.com/grpc/grpc/blob/731be760d2c3e08195b824a51d1d6c6112b16f42/test/core/security/authorization_matchers_test.cc#L300)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think he just meant that the second parameter of each `AddPairToMetadata()` call did not need to be on a separate line.  It looks good the way you have it now.
</blockquote></details>

Oh! Sorry got confused, as it wasn't in a separate line in the latest screenshot (after removing in the parameter comments).


<!-- Sent from Reviewable.io -->

2021-04-08 20:14 UTC, ashithasantosh commented
Thanks @markdroth and @ZhenLian for the detailed review!:)

2021-04-09 01:44 UTC, jiangtaoli2016 approved these changes
Thanks Ashitha for the PR!

2021-04-09 02:15 UTC, ashithasantosh commented
Thanks for the review, Jiangtao!:)

2021-04-09 05:33 UTC, merged