Hash 2
grpc/grpc pull request #25697
Opened 2021-03-12 00:28 UTC by donnadionne

@drfloob

2021-03-18 06:31 UTC, donnadionne commented
While this is drafty, there is enough code to start and confirm that main structure of the new ring hash policy.  I think I have captured the latest design for failure cases.

2021-03-18 18:26 UTC, markdroth requested changes
This looks like a great start!

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-MW5X98WDNB_9KkrpIro:b9kv8rc)* status: all files reviewed, 38 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5ArWG2sULayxf7Yk_:-MW5ArWG2sULayxf7Yka:bfnxo5z) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L38)):*
> ```cpp
> #include "src/core/lib/transport/static_metadata.h"
> 
> #define XXH_INLINE_ALL
> ```

These two lines should be moved up next to the absl include above.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 44 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5AyPoCJdyfXbjA1Bz:-MW5AyPoCJdyfXbjA1C-:b-1iyrzg) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L44)):*
> ```cpp
> 
> const char* kRequestRingHashAttribute = "request_ring_hash";
> TraceFlag grpc_lb_ring_hash_trace(false, "ring_hash");
> ```

Please make the tracer name "ring_hash_lb".
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5WjaK0s2EvLsnqJnd:-MW5WjaK0s2EvLsnqJne:bkwk76z) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L48)):*
> ```cpp
> namespace {
> 
> constexpr char kRingHash[] = "ring_hash";
> ```

This should be "ring_hash_experimental".
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5BAfm0fyU0zyeYIua:-MW5BAfm0fyU0zyeYIub:b-sw2z7e) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L52)):*
> ```cpp
> class RingHashLbConfig : public LoadBalancingPolicy::Config {
>  public:
>   RingHashLbConfig(const size_t min_ring_size, const size_t max_ring_size)
> ```

No need for `const` for these parameters.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 163 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5C2fm8fTtB2n1fvNU:-MW5C2fm8fTtB2n1fvNV:b-n4r931) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L163)):*
> ```cpp
>   class Picker : public SubchannelPicker {
>    public:
>     struct RingEntry {
> ```

This struct also needs to store the connectivity state of the subchannel, so that we don't need synchronization to access that data in the picker.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 164 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5Hsm17HvF-i0GFqNY:-MW5Hsm17HvF-i0GFqNZ:b-nobie2) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L164)):*
> ```cpp
>    public:
>     struct RingEntry {
>       uint64_t hash_;
> ```

This is a struct, not a class, so this should not have an `_` suffix.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 173 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5CFPtAfru6IM7iHRn:-MW5CFPtAfru6IM7iHRo:bx6i6pv) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L173)):*
> ```cpp
> 
>    private:
>     // Using pointer value only, no ref held -- do not dereference!
> ```

I think we actually do need to hold a ref here, because the picker is going to need to trigger connection attempts of individual subchannels in the LB policy.  This will be done in a similar way to how QueuePicker does it:

https://github.com/grpc/grpc/blob/a737ff86128f055f0cfd086703146bbb566af7c2/src/core/ext/filters/client_channel/lb_policy.cc#L100

Although in this case, instead of calling the LB policy's `ExitIdleLocked()` method, we'll need to call a different method that starts a connection attempt for one particular subchannel.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 185 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5Cmgs04K9YF8RIcB5:-MW5Cmgs04K9YF8RIcB6:b-1n810a) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L185)):*
> ```cpp
>   RefCountedPtr<RingHashLbConfig> config_;
> 
>   /** list of subchannels */
> ```

Please use C++-style comments.

Same thing for the next field.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 213 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5Dshk8WQnuwdSWGY7:-MW5Dshk8WQnuwdSWGY8:bh8zsod) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L213)):*
> ```cpp
>         const ServerAddressWeightAttribute*>(sd->address().GetAttribute(
>         ServerAddressWeightAttribute::kServerAddressWeightAttributeKey));
>     if (weight_attribute != nullptr && weight_attribute->weight() != 0) {
> ```

I don't think this value should ever be 0.  We should reject that case when we validate the config.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 215 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5FCna2ItBd12KS4vm:-MW5FCna2ItBd12KS4vn:b-h9ypmi) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L215)):*
> ```cpp
>     if (weight_attribute != nullptr && weight_attribute->weight() != 0) {
>       AddressWeights address_weights;
>       address_weights.address = std::string(sd->address().address().addr);
> ```

This is trying to turn a binary object (a sockaddr struct), which may contain nul bytes, into a string, but it's doing it using a `std::string` ctor that assumes a nul-terminated string.  If we actually wanted to do this, we would need to instead use the `std::string` ctor that explicitly takes the length of the string as a parameter.

However, I don't think we want to use the binary sockaddr object here in the first place.  The Envoy implementation uses the human-readable address for this string rather than using the sockaddr form as the string:

https://github.com/envoyproxy/envoy/blob/177ea9c7a3ed5d8d96e078738a1ac6a1ee2fd507/source/common/upstream/ring_hash_lb.cc#L153

That ultimately calls this:

https://github.com/envoyproxy/envoy/blob/177ea9c7a3ed5d8d96e078738a1ac6a1ee2fd507/include/envoy/network/address.h#L157

Given that this string is the main input to the hashing algorithm, I think we should do the same thing here.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 218 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5E1WS8oycyVytY-as:-MW5E1WS8oycyVytY-at:b-yn1wp5) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L218)):*
> ```cpp
>       address_weights.weight = weight_attribute->weight();
>       sum += weight_attribute->weight();
>       gpr_log(GPR_INFO, "donna retrieve weight %d", weight_attribute->weight());
> ```

Please make sure to remove all of these log lines before merging.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 221 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5EEyk1htrGumvlTGg:-MW5EEyk1htrGumvlTGh: [...]

2021-03-18 22:44 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697)* status: all files reviewed, 38 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 338 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5KWgGAw-ZCMWEiufb:-MW6Nsfu98oMrUKRMl42:b-3e4pvw) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L338)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest a helper function to make this more readable:

```
// Returns false if subchannel is in TRANSIENT_FAILURE, true otherwise.
bool MaybePickSubchannel(const RingEntry& entry, PickResult* result) {
  if (entry.state == GRPC_CHANNEL_READY) {
    result->type = PickResult::PICK_COMPLETE;
    result->subchannel = entry.subchannel;
    return true;
  }
  if (entry.state == GRPC_CHANNEL_IDLE) {
    // ...trigger connection attempt...
    result->type = PickResult::PICK_QUEUE;
    return true;
  }
  if (entry.state == GRPC_CHANNEL_CONNECTING) {
    result->type = PickResult::PICK_QUEUE;
    return true;
  }
  // TRANSIENT_FAILURE
  // ...trigger connection attempt...
  return false;
}
```

Then the code here can become:

```
if (MaybePickSubchannel(ring_[midp], &result)) {
  return result;
}
// Subchannel is in TRANSIENT_FAILURE.
// Check the next one.
midp = (midp + 1) % ring_.size();
if (MaybePickSubchannel(ring_[midp], &result)) {
  return result;
}
// Second subchannel was in TRANSIENT_FAILURE.
// Check the third one.
midp = (midp + 1) % ring_.size();
if (ring_[midp].state == GRPC_CHANNEL_IDLE ||
    ring_[midp].state == GRPC_CHANNEL_TRANSIENT_FAILURE) {
  // ...trigger connection attempt...
}
//  Search forward through the ring for any subchannel in state READY.
for (size_t i = 0; i < ring_.size() - 2; ++i) {
  const RingEntry& entry = ring_[(midp + i) % ring_.size()];
  if (entry.state == GRPC_CHANNEL_READY) {
    result.type = PickResult::PICK_COMPLETE;
    result.subchannel = entry.subchannel;
    return result;
  }
}
result.type = PickResult::PICK_FAILED;
return result;
```
</blockquote></details>

After discussion with @ejona86, I think the last part should actually be different from what I said above:

```
if (MaybePickSubchannel(ring_[midp], &result)) {
  return result;
}
// Subchannel is in TRANSIENT_FAILURE.
// Check the next one.
midp = (midp + 1) % ring_.size();
if (MaybePickSubchannel(ring_[midp], &result)) {
  return result;
}
// Second subchannel was in TRANSIENT_FAILURE.
// Loop through remaining subchannels to find one in READY.
// On the way, we make sure the right set of connection attempts
// will happen.
midp = (midp + 1) % ring_.size();
bool found_first_non_failed = false;
for (size_t i = 0; i < ring_.size() - 2; ++i) {
  const RingEntry& entry = ring_[(midp + i) % ring_.size()];
  if (entry.state == GRPC_CHANNEL_READY) {
    result.type = PickResult::PICK_COMPLETE;
    result.subchannel = entry.subchannel;
    return result;
  }
  if (!found_first_non_failed) {
    if (entry.state != TRANSIENT_FAILURE) {
      // ...trigger connection attempt...
    } else {
      if (entry.state == IDLE) {
        // ...trigger connection attempt...
      }
      found_first_non_failed = true;
    }
  }
}
result.type = PickResult::PICK_FAILED;
return result;
```
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 471 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5OrbiD-UbjHQNU_uK:-MW6Ncs48nIMKlaf-Ffw:be0wnn3) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L471)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is right.  Just because there are less than 2 subchannels in TRANSIENT_FAILURE does not mean we're READY; we could be IDLE or CONNECTING instead.

The algorithm here should be (psuedo-code):

```
if (num_ready_ > 0) return READY;
if (num_connecting_ > 0) return CONNECTING;
if (num_transient_failure_ > 2) return TRANSIENT_FAILURE;
return IDLE;
```
</blockquote></details>

@ejona86 pointed out to me that this is incorrect.  It should be:

```
if (num_ready_ > 0) return READY;
if (num_connecting_ > 0) return CONNECTING;
if (num_transient_failure_ > 2) return TRANSIENT_FAILURE;
if (num_idle_ > 0) return IDLE;
return TRANSIENT_FAILURE;
```

Note that this means that we'll also need a counter for the number in IDLE state.


<!-- Sent from Reviewable.io -->

2021-03-24 07:17 UTC, donnadionne reviewed
I think I have captured all the suggestions and made all the modifications.  PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-MWY4w_y3q-NnjTeG4O-:bwsd3fw)* status: 1 of 4 files reviewed, 38 unresolved discussions (waiting on @ejona86 and @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5ArWG2sULayxf7Yk_:-MW6nrNS-kkiMl4cziaD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two lines should be moved up next to the absl include above.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 44 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5AyPoCJdyfXbjA1Bz:-MW6o2ByB6vBgf7QPC0l:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please make the tracer name "ring_hash_lb".
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5WjaK0s2EvLsnqJnd:-MW6o2RFC58t5w-DdY6N:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be "ring_hash_experimental".
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5BAfm0fyU0zyeYIua:-MW6o78t-RS5eOpjvxlU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `const` for these parameters.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 163 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5C2fm8fTtB2n1fvNU:-MWQAK8BDXE7rYhElxvi:b-8je37q) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L163)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This struct also needs to store the connectivity state of the subchannel, so that we don't need synchronization to access that data in the picker.
</blockquote></details>

added and calling CheckConnectivityState in Picker creation
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 164 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5Hsm17HvF-i0GFqNY:-MW6oSsIDUe3hRqgQ5Ww:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L164)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is a struct, not a class, so this should not have an `_` suffix.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 173 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5CFPtAfru6IM7iHRn:-MWXwYHbB7iajcZTMf3u:bscmvk5) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L173)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we actually do need to hold a ref here, because the picker is going to need to trigger connection attempts of individual subchannels in the LB policy.  This will be done in a similar way to how QueuePicker does it:

https://github.com/grpc/grpc/blob/a737ff86128f055f0cfd086703146bbb566af7c2/src/core/ext/filters/client_channel/lb_policy.cc#L100

Although in this case, instead of calling the LB policy's `ExitIdleLocked()` method, we'll need to call a different method that starts a connection attempt for one particular subchannel.
</blockquote></details>

I think i got it, let me know what you think of the AttemptToConnectInExecCtx method
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 185 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5Cmgs04K9YF8RIcB5:-MW6pCoJ4XSAdJW1MzyH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L185)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style comments.

Same thing for the next field.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 213 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5Dshk8WQnuwdSWGY7:-MWGtWj13iUtphfXb-UX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L213)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this value should ever be 0.  We should reject that case when we validate the config.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 215 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5FCna2ItBd12KS4vm:-MWGz094CzmyRsEZ4KMR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L215)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is trying to turn a binary object (a sockaddr struct), which may contain nul bytes, into a string, but it's doing it using a `std::string` ctor that assumes a nul-terminated string.  If we actually wanted to do this, we would need to instead use the `std::string` ctor that explicitly takes the length of the string as a parameter.

However, I don't think we want to use the binary sockaddr object here in the first place.  The Envoy implementation uses the human-readable address for this string rather than using the sockaddr form as the string:

https://github.com/envoyproxy/envoy/blob/177ea9c7a3ed5d8d96e078738a1ac6a1ee2fd507/source/common/upstream/ring_hash_lb.cc#L153

That ultimately calls this:

https://github.com/envoyproxy/envoy/blob/177ea9c7a3ed5d8d96e078738a1ac6a1ee2fd507/include/envoy/network/address.h#L157

Given that this string is the main input to the hashing algorithm, I think we should do the same thing here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 218 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5E1WS8oycyVytY-as:-MWLz2Bc30dsM-jaLeSy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L218)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please make sure to remove all of these log lines before merging.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 221 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5EEyk1htrGumvlTGg:-MWLpSOc8uoSLbFyzilw:b-896fix) ([raw file](https://gith [...]

2021-03-24 19:01 UTC, markdroth requested changes
This looks pretty good!

There are a few edge cases that still need to be addressed, especially related to TRANSIENT_FAILURE.  Otherwise, the main thing missing here is tests.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 3 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-MW_aqWv4CLN9xNMYCov:b-ooss6w)* status: all files reviewed, 21 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 173 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5CFPtAfru6IM7iHRn:-MW_Bsk-7CCjNXmUSkGN:b-4r0khu) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L173)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I think i got it, let me know what you think of the AttemptToConnectInExecCtx method
</blockquote></details>

This is the right general idea, but I think we can both simplify the interface and make it more efficient.  I think what we want is something like this:

```
// A fire-and-forget class that schedules subchannel connection attempts
// on the control plane WorkSerializer.
class SubchannelConnectionAttemper
    : public Orphanable<SubchannelConnectionAttempter> {
 public:
  explicit SubchannelConnectionAttempter(
      RefCountedPtr<RingHash> ring_hash_lb)
      : ring_hash_lb_(std::move(ring_hash_lb)) {
    GRPC_CLOSURE_INIT(&closure_, RunInExecCtx, this, nullptr);
  }

  void AddSubchannel(RefCountedPtr<SubchannelInterface> subchannel) {
    subchannels_.push_back(std::move(subchannel));
  }

  void Orphan() override {
    // Hop into ExecCtx, so that we're not holding the data plane mutex
    // while we run control-plane code.
    ExecCtx::Run(DEBUG_LOCATION, &closure_, GRPC_ERROR_NONE);
  }

 private:
  static void RunInExecCtx(void* arg, grpc_error* /*error*/) {
    auto* self = static_cast<SubchannelConnectionAttemper*>(arg);
    self->ring_hash_lb_->work_serializer()->Run(
        [self]() {
          if (!self->ring_hash_lb_->shutdown_) {
            for (auto& subchannel : self->subchannels_) {
              subchannel->AttemptToConnect();
            }
          }
          delete self;
        },
        DEBUG_LOCATION);
  }

  RefCountedPtr<RingHash> ring_hash_lb_;
  grpc_closure closure_;
  absl::InlinedVector<RefCountedPtr<SubchannelInterface>, 10> subchannels_;
};
```

Then, in `Pick()`, we can do something like this:

```
OrphanablePtr<SubchannelConnectionAttemper> subchannel_connection_attempter;
auto ScheduleSubchannelConnectionAttempt =
    [&](RefCountedPtr<SubchannelInterface> subchannel) {
      if (subchannel_connection_attempter == nullptr) {
        subchannel_connection_attempter = MakeOrphanable<SubchannelConnectionAttemper>(parent_);
      }
      subchannel_connection_attempter->AddSubchannel(std::move(subchannel));
    };
```

Then, whenever we need to schedule a connection attempt for a subchannel, we just do this:

```
ScheduleSubchannelConnectionAttempt(subchannel);
```

And when `Pick()` returns, the connection attempts will be automatically scheduled on the `WorkSerializer`.

This way, in cases where the picker needs to trigger a connection attempt on multiple subchannels for the same pick, it can do them all at once instead of hopping into the `WorkSerializer` for each individual subchannel.  This also means that in the common case (a small number of subchannels needing reconnection), there will be only two memory allocations needed for this (one for the `SubchannelConnectionAttemper` object and another for the lambda) -- it avoids the second lambda and the call to `GRPC_CLOSURE_CREATE()`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 215 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5FCna2ItBd12KS4vm:-MW_73nI-lncaAX0YR3h:b3az61m) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L215)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like you've changed this to use `ServerAddress::ToString()`, but that includes any channel args and attributes that are attached the address.  In this case, I think we want to use just the IP:port string.  So I think we want something like `grpc_sockaddr_to_string(sd->address().address(), false)`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 44 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_4uiOBCsSSeypdH_8:-MW_4uiPCzFpwCfvZoYS:b-p8v12x) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L44)):*
> ```cpp
> 
> const char* kRequestRingHashAttribute = "request_ring_hash";
> TraceFlag grpc_lb_ring_hash_trace(false, "ring_hash_lb");
> ```

Please document this tracer in doc/environment_variables.md.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 161 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_5FlP2PxkGNy5LSaW:-MW_5FlQ4HLAmhKuJhZl:b-npgbb3) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L161)):*
> ```cpp
>   class Picker : public SubchannelPicker {
>    public:
>     struct RingEntry {
> ```

All of the structs and methods here except for the ctor and the `Pick()` method can be private.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 164 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_8b1Z6iBZ8aXwW-p3:-MW_8b1Z6iBZ8aXwW-p4:bu1efs5) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L164)):*
> ```cpp
>       uint64_t hash;
>       RefCountedPtr<SubchannelInterface> subchannel;
>       grpc_connectivity_state last_connectivity_state;
> ```

Don't need the `last_` prefix here -- from the picker's perspective, it's the current connectivity state.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 171 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_BIhX-SfzMLCxzlTJ:-MW_BIhX-SfzMLCxzlTK:b-v0vaw3) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L171)):*
> ```cpp
>     // the ring hash policy which contains the serializer and the subchannel to
>     // be connected.
>     class AttemptToConnectArgs
> ```

I don't think this is necessary.  Instead, we can pre-bind parameters in the lambda.  See below.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 181 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_5QFhDZoIoYP0mWZX:-MW_5QFi7HnMe5iJbdEY:b-8xympj) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L181)):*
> ```cpp
>       using InternallyRefCounted<AttemptToConnectArgs>::Unref;
>       void Orphan() override { Unref(); }
>       RefCountedPtr<RingHash> parent_;
> ```

Data members must be private.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 224 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_8qqV0ItFxPr8alq7:-MW_8qqV0ItFxPr8alq8:bdofu1y) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L224)):*
> ```cpp
>   size_t num_subchannels = subchannel_list->num_subchannels();
>   // Store the weights while finding the sum.
>   struct AddressWeights {
> ```

Suggest calling this `AddressWeight` (singular instead of plural), s [...]

2021-03-24 23:49 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697)* status: all files reviewed, 21 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 558 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_JZcy1YZ1ietsJOJk:-MWac_oI77BX-E7hRst0:b-s9cna5) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L558)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This case needs to start the same rotating reconnection behavior as the previous TRANSIENT_FAILURE case.

It might be easiest to just combine the two TRANSIENT_FAILURE cases by doing something like this:

```
} else if (num_connecting_ > 0) {
  // ...CONNECTING...
} else if (num_idle_ > 0 && num_transient_failure_ < 2) {
  // ...IDLE...
} else {
  // ...TRANSIENT_FAILURE...
}
```
</blockquote></details>

As per my latest comment in the design doc, we realized that we need the special case for TF to take precedence over CONNECTING as well.  So the logic here will actually need to be something like:

```
if (num_ready_ > 0) {
  // ...READY...
} else if (num_connecting_ > 0 && num_transient_failure_ < 2) {
  // ...CONNECTING...
} else if (num_idle_ > 0 && num_transient_failure_ < 2) {
  // ...IDLE...
} else {
  // ...TRANSIENT_FAILURE...
}
```


<!-- Sent from Reviewable.io -->

2021-03-25 07:09 UTC, donnadionne reviewed
Fixed according to suggestions.  Please let me know if you have any comments.  I will work on tests now.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-MWcCcCiAyEc1gf0dbov:b-egwy2n)* status: 4 of 10 files reviewed, 21 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 173 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5CFPtAfru6IM7iHRn:-MWbhVGTExWByB5xwgKS:b1hl8vc) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L173)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is the right general idea, but I think we can both simplify the interface and make it more efficient.  I think what we want is something like this:

```
// A fire-and-forget class that schedules subchannel connection attempts
// on the control plane WorkSerializer.
class SubchannelConnectionAttemper
    : public Orphanable<SubchannelConnectionAttempter> {
 public:
  explicit SubchannelConnectionAttempter(
      RefCountedPtr<RingHash> ring_hash_lb)
      : ring_hash_lb_(std::move(ring_hash_lb)) {
    GRPC_CLOSURE_INIT(&closure_, RunInExecCtx, this, nullptr);
  }

  void AddSubchannel(RefCountedPtr<SubchannelInterface> subchannel) {
    subchannels_.push_back(std::move(subchannel));
  }

  void Orphan() override {
    // Hop into ExecCtx, so that we're not holding the data plane mutex
    // while we run control-plane code.
    ExecCtx::Run(DEBUG_LOCATION, &closure_, GRPC_ERROR_NONE);
  }

 private:
  static void RunInExecCtx(void* arg, grpc_error* /*error*/) {
    auto* self = static_cast<SubchannelConnectionAttemper*>(arg);
    self->ring_hash_lb_->work_serializer()->Run(
        [self]() {
          if (!self->ring_hash_lb_->shutdown_) {
            for (auto& subchannel : self->subchannels_) {
              subchannel->AttemptToConnect();
            }
          }
          delete self;
        },
        DEBUG_LOCATION);
  }

  RefCountedPtr<RingHash> ring_hash_lb_;
  grpc_closure closure_;
  absl::InlinedVector<RefCountedPtr<SubchannelInterface>, 10> subchannels_;
};
```

Then, in `Pick()`, we can do something like this:

```
OrphanablePtr<SubchannelConnectionAttemper> subchannel_connection_attempter;
auto ScheduleSubchannelConnectionAttempt =
    [&](RefCountedPtr<SubchannelInterface> subchannel) {
      if (subchannel_connection_attempter == nullptr) {
        subchannel_connection_attempter = MakeOrphanable<SubchannelConnectionAttemper>(parent_);
      }
      subchannel_connection_attempter->AddSubchannel(std::move(subchannel));
    };
```

Then, whenever we need to schedule a connection attempt for a subchannel, we just do this:

```
ScheduleSubchannelConnectionAttempt(subchannel);
```

And when `Pick()` returns, the connection attempts will be automatically scheduled on the `WorkSerializer`.

This way, in cases where the picker needs to trigger a connection attempt on multiple subchannels for the same pick, it can do them all at once instead of hopping into the `WorkSerializer` for each individual subchannel.  This also means that in the common case (a small number of subchannels needing reconnection), there will be only two memory allocations needed for this (one for the `SubchannelConnectionAttemper` object and another for the lambda) -- it avoids the second lambda and the call to `GRPC_CLOSURE_CREATE()`.
</blockquote></details>

This is really cool!  doing the work in Orphan
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 215 at r1](https://reviewable.io/reviews/grpc/grpc/25697#-MW5FCna2ItBd12KS4vm:-MWbn7An9ndz4PLITdVK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7863067d6a0470dae476b1170ac4e169d50f165a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L215)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like you've changed this to use `ServerAddress::ToString()`, but that includes any channel args and attributes that are attached the address.  In this case, I think we want to use just the IP:port string.  So I think we want something like `grpc_sockaddr_to_string(sd->address().address(), false)`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 44 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_4uiOBCsSSeypdH_8:-MWbfr6c8TnIbwrTXXmP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document this tracer in doc/environment_variables.md.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 161 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_5FlP2PxkGNy5LSaW:-MWbgyQC-g7u-3HO0GXR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L161)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All of the structs and methods here except for the ctor and the `Pick()` method can be private.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 164 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_8b1Z6iBZ8aXwW-p3:-MWbhPOw30Z6Pk9_jgG_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L164)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't need the `last_` prefix here -- from the picker's perspective, it's the current connectivity state.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 171 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_BIhX-SfzMLCxzlTJ:-MWbhNc25UpGneEek22E:b-hfpv0l) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L171)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is necessary.  Instead, we can pre-bind parameters in the lambda.  See below.
</blockquote></details>

removed
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 181 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_5QFhDZoIoYP0mWZX:-MWbhTBs-S-gP16tUYVx:b-hfpv0l) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L181)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Data members must be private.
</blockquote></details>

removed
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 224 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_8qqV0ItFxPr8alq7:-MWbhqjqEmE3SspToQaX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e8130cf885/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L224)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `AddressWeight` (singular instead of plural), since it's the weight for a single address.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 228 at r3](https://reviewable.io/reviews/grpc/grpc/25697#-MW_A-8o0h5TDlSm2Vrg:-MWbiei_ACwh3Mqoy0yN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5572961ed28dc19d878405662897f3e813 [...]

2021-03-29 17:22 UTC, markdroth requested changes
This looks really good!  Remaining comments are minor; just waiting for the tests.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 6 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-MWz-Pcd-8Pq2dh-cct4:b-5a5udf)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 277 at r5](https://reviewable.io/reviews/grpc/grpc/25697#-MWyts5GEiNMtZgcWLPG:-MWyts5HC2Hqs1uEmNmL:b-udapd9) ([raw file](https://github.com/grpc/grpc/blob/ba77b9cedc89c6a92737235b5b14a96df6b4c6d3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L277)):*
> ```cpp
>     address.normalized_weight = static_cast<double>(address.weight) / sum;
>     min_normalized_weight =
>         GPR_MIN(address.normalized_weight, min_normalized_weight);
> ```

Why `GPR_MIN()` and `GPR_MAX()` instead of `std::min()` and `std::max()`?  I think we should prefer the latter if possible.

Same thing throughout.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 323 at r5](https://reviewable.io/reviews/grpc/grpc/25697#-MWyu37W6pwLdUWkrS2r:-MWyu37W6pwLdUWkrS2s:b-goi558) ([raw file](https://github.com/grpc/grpc/blob/ba77b9cedc89c6a92737235b5b14a96df6b4c6d3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L323)):*
> ```cpp
>                        subchannel_list->subchannel(i)
>                            ->subchannel()
>                            ->CheckConnectivityState()});
> ```

If we're going to add this subchannel to the ring multiple times, we should call `CheckConnectivityState()` just once, since that function performs synchronization internally.  I suggest calling this before the `while` loop on line 313 above and then reusing the same value every time through this loop.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 461 at r5](https://reviewable.io/reviews/grpc/grpc/25697#-MWywnuVAacVVB-IZhWO:-MWywnuVAacVVB-IZhWP:b6mldxw) ([raw file](https://github.com/grpc/grpc/blob/ba77b9cedc89c6a92737235b5b14a96df6b4c6d3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L461)):*
> ```cpp
>   result.error = grpc_error_set_int(
>       GRPC_ERROR_CREATE_FROM_COPIED_STRING(
>           absl::StrCat("xds ring hash unable to hash to a subchannel").c_str()),
> ```

This error message is a little misleading -- it's not that we couldn't hash to a subchannel, it's that the subchannel we hashed to was in state TRANSIENT_FAILURE.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 677 at r5](https://reviewable.io/reviews/grpc/grpc/25697#-MWyz67mEpJy5dQbyUdj:-MWyz67n-R431URl6ZXO:b8bkjgw) ([raw file](https://github.com/grpc/grpc/blob/ba77b9cedc89c6a92737235b5b14a96df6b4c6d3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L677)):*
> ```cpp
>   }
>   config_ = std::move(args.config);
>   ServerAddressList addresses = std::move(args.addresses);
> ```

Might be a bit cleaner to move only the addresses that we actually want to use:

```
ServerAddressList addresses;
addresses.reserve(args.addresses.size());
for (ServerAddress& address : args.addresses) {
  const ServerAddressWeightAttribute* weight_attribute =
      static_cast<const ServerAddressWeightAttribute*>(it->GetAttribute(
          ServerAddressWeightAttribute::kServerAddressWeightAttributeKey));
  if (weight_attribute == nullptr || weight_attribute->weight() > 0) {
    addresses.push_back(std::move(address));
  }
}
```


<!-- Sent from Reviewable.io -->

2021-04-14 10:17 UTC, donnadionne reviewed
added tests

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-MYEse86-tBoygLxcUsP:bq3jnj0)* status: 4 of 16 files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 277 at r5](https://reviewable.io/reviews/grpc/grpc/25697#-MWyts5GEiNMtZgcWLPG:-MXjbjNE4xFmt2AuzmQC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ba77b9cedc89c6a92737235b5b14a96df6b4c6d3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L277)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why `GPR_MIN()` and `GPR_MAX()` instead of `std::min()` and `std::max()`?  I think we should prefer the latter if possible.

Same thing throughout.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 323 at r5](https://reviewable.io/reviews/grpc/grpc/25697#-MWyu37W6pwLdUWkrS2r:-MXjir2r4Hb-0x8aEf_t:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ba77b9cedc89c6a92737235b5b14a96df6b4c6d3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L323)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're going to add this subchannel to the ring multiple times, we should call `CheckConnectivityState()` just once, since that function performs synchronization internally.  I suggest calling this before the `while` loop on line 313 above and then reusing the same value every time through this loop.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 461 at r5](https://reviewable.io/reviews/grpc/grpc/25697#-MWywnuVAacVVB-IZhWO:-MXjcRnECTG6p2mLoLg2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ba77b9cedc89c6a92737235b5b14a96df6b4c6d3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L461)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This error message is a little misleading -- it's not that we couldn't hash to a subchannel, it's that the subchannel we hashed to was in state TRANSIENT_FAILURE.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 677 at r5](https://reviewable.io/reviews/grpc/grpc/25697#-MWyz67mEpJy5dQbyUdj:-MXji2vUEfuqtsYGeLXH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ba77b9cedc89c6a92737235b5b14a96df6b4c6d3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L677)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Might be a bit cleaner to move only the addresses that we actually want to use:

```
ServerAddressList addresses;
addresses.reserve(args.addresses.size());
for (ServerAddress& address : args.addresses) {
  const ServerAddressWeightAttribute* weight_attribute =
      static_cast<const ServerAddressWeightAttribute*>(it->GetAttribute(
          ServerAddressWeightAttribute::kServerAddressWeightAttributeKey));
  if (weight_attribute == nullptr || weight_attribute->weight() > 0) {
    addresses.push_back(std::move(address));
  }
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-14 20:44 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697)* status: 4 of 16 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 8910 at r6](https://reviewable.io/reviews/grpc/grpc/25697#-MYH6yFW2T0vZ-NYWflU:-MYH6yFW2T0vZ-NYWflV:bi3vr9z) ([raw file](https://github.com/grpc/grpc/blob/5ba4d66cd58646f3e68ae7c6ee82543d58987bde/test/cpp/end2end/xds_end2end_test.cc#L8910)):*
> ```cpp
> // move on to the next ring hash entry.  And if the next ring hash entry is also
> // down, we will look for any connected subchannel.
> // This test will definitely test the first attempt to use the next ring hash
> ```

Based on the latest design where we should pick the next unique subchannel, as oppose to just the next entry in the ring, this test will only test that we tried the next subchannel (there are only 2 subchannels in the test).  I will write a separate test to try to do that "second" pick next


<!-- Sent from Reviewable.io -->

2021-04-14 20:47 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697)* status: 4 of 16 files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 426 at r7](https://reviewable.io/reviews/grpc/grpc/25697#-MYH7XEFBrY2cN2WM2PZ:-MYH7XEFBrY2cN2WM2P_:bwfb6ld) ([raw file](https://github.com/grpc/grpc/blob/8d6b200bb921288e1a2eab0bc6724ae41221aa67/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L426)):*
> ```cpp
>   }
>   // Subchannel is in TRANSIENT_FAILURE.
>   // Check the next one.
> ```

I will update this logic to look for the next unique subchannel not just the next entry
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 446 at r7](https://reviewable.io/reviews/grpc/grpc/25697#-MYH7g8UA2eTF8lCMkCU:-MYH7g8UA2eTF8lCMkCV:b-iixgkh) ([raw file](https://github.com/grpc/grpc/blob/8d6b200bb921288e1a2eab0bc6724ae41221aa67/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L446)):*
> ```cpp
>   for (size_t i = 0; i < ring_.size() - 2; ++i) {
>     const RingEntry& entry = ring_[(midp + i) % ring_.size()];
>     if (entry.connectivity_state == GRPC_CHANNEL_READY) {
> ```

I think this case is fine as-is, since we will be looking for a ready entry so we will skip the same TF subchannel entries


<!-- Sent from Reviewable.io -->

2021-04-14 20:49 UTC, donnadionne reviewed
I will make the change to look for the next unique subchannel; but i think the changes here can still be reviewed and i will include the change and the test in the next round.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-MYH8EnB9qFLHZQA2D9u:b-4pgi09)* status: 4 of 16 files reviewed, 7 unresolved discussions (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2021-04-22 18:12 UTC, markdroth requested changes
Sorry it took me so long to get to this!

The tests you added look pretty good; my comments there are fairly minor.  But I think there are a number of additional test cases that we still need to add.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 12 files at r6, 1 of 1 files at r7, 6 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-MYuluXa8Rcp3LNa-9WM:b-6nkiro)* status: all files reviewed, 28 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 406 at r5](https://reviewable.io/reviews/grpc/grpc/25697#-MYqgrQmBc0gRayJBN0t:-MYqgrQmBc0gRayJBN0u:b-kdcssi) ([raw file](https://github.com/grpc/grpc/blob/ba77b9cedc89c6a92737235b5b14a96df6b4c6d3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L406)):*
> ```cpp
>   if (GRPC_TRACE_FLAG_ENABLED(grpc_lb_ring_hash_trace)) {
>     gpr_log(GPR_INFO,
>             "[RH %p picker %p] hashed to index %" PRIdPTR ", subchannel=%p",
> ```

If you do add a second tracer for more detailed info, this might be a good message to keep around in that second tracer.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 446 at r7](https://reviewable.io/reviews/grpc/grpc/25697#-MYH7g8UA2eTF8lCMkCU:-MYqhX_p5EiS2jPeocf7:b-4lus1r) ([raw file](https://github.com/grpc/grpc/blob/8d6b200bb921288e1a2eab0bc6724ae41221aa67/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L446)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I think this case is fine as-is, since we will be looking for a ready entry so we will skip the same TF subchannel entries
</blockquote></details>

I think we can actually just combine the second-subchannel case into this loop.  See the pseudo-code in the design doc.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 341 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqgbXO9UOHH_IeTM8G:-MYqgbXO9UOHH_IeTM8H:b-pip251) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L341)):*
> ```cpp
>             parent_.get(), this, subchannel_list, ring_.size());
>     for (const auto& r : ring_) {
>       gpr_log(GPR_INFO, "ring hash: %" PRIx64 " subchannel: %p state: %d",
> ```

I suspect this is going to be way too much logging to do every time we return a new picker.  If you really want this, maybe add a second tracer for this, so that it can be enabled/disabled independently of the other trace messages in this LB policy?
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 498 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqhmmJ5Rx_HtN2K5uE:-MYqhmmJ5Rx_HtN2K5uF:b-q8qu7z) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L498)):*
> ```cpp
>   GPR_ASSERT(new_state != GRPC_CHANNEL_SHUTDOWN);
>   if (old_state == GRPC_CHANNEL_IDLE) {
>     if (num_idle_ > 0) {
> ```

This change looks wrong.  How could this ever be 0 if we were just in IDLE state?
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 647 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqf7G699CCdVTEpXWH:-MYqf7G699CCdVTEpXWI:b-11sehq) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L647)):*
> ```cpp
>         case XdsApi::Route::HashPolicy::CHANNEL_ID:
>           new_hash =
>               (static_cast<uint64_t>(reinterpret_cast<uintptr_t>(resolver))
> ```

This seems like a very strange algorithm.  Doesn't this bias heavily toward higher values, because the more significant bits are more likely to be 1 than 0?  Any given bit will be 1 if that bit was 1 in either its original octet or in any of the less-significant octets.

@voidzcy, what are you doing for this in Java?
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 682 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqedEG5xb8qbJUPpNI:-MYqedEH56saRJk7u9RJ:bgdl89g) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L682)):*
> ```cpp
>     }
>     call_config.call_attributes[kXdsClusterAttribute] = it->first;
>     std::string hash_string = absl::StrCat("", hash.value());
> ```

No need for the first argument to `absl::StrCat()`.  It's fine to pass it just one.
___
*[src/proto/grpc/testing/xds/v3/route.proto, line 256 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqiJWrDNY_u9dXXKNy:-MYqiJWrDNY_u9dXXKNz:byrgzo1) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/proto/grpc/testing/xds/v3/route.proto#L256)):*
> ```protobuf
>       string header_name = 1;
> 
>       // If specified, the request header value will be rewritten and used
> ```

This looks like the comment for the `regex_rewrite` field.  Why is that field not actually being added here?  We should probably be testing that case too.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 489 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYuLCpZ11rbG2Bd_-EU:-MYuLCpZ11rbG2Bd_-EV:b-yik119) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/test/cpp/end2end/xds_end2end_test.cc#L489)):*
> ```cpp
>                int priority = kDefaultLocalityPriority,
>                std::vector<HealthStatus> health_statuses = {},
>                std::vector<int> endpoint_lb_weights = {})
> ```

We've now got 3 different vectors here, each of which contains a different field for the individual endpoints.  I think it may be time to change this to have a separate object to represent the fields of an endpoint and then pass in a vector of those objects here.

In other words, consider something like this:

```
struct Endpoint {
  explicit Endpoint(int port, HealthStatus health_status = HealthStatus::UNKNOWN, int lb_weight = 1)
      : port(port), health_status(health_status), lb_weight(lb_weight) {}

  int port;
  HealthStatus health_status;
  int lb_weight;
};

struct Locality {
  Locality(std::string sub_zone, std::vector<Endpoint> endpoints,
           int lb_weight = kDefaultLocalityWeight,
           int prioruty = kDefaultLocalityPriority)
      : sub_zone(std::move(sub_zone)),
        endpoints(std::move(endpoints)),
        lb_weight(lb_weight),
        priority(priority) {}

  std::string sub_zone;
  std::vector<Endpoint> endpoints;
  int lb_weight;
  int priority;
};
```

You can then add a utility method to `XdsEnd2endTest` to help construct the endpoints:

```
std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> CreateEndpointsForBackends(
    size_t start_index = 0, size_t stop_index = 0,
    HealthStatus health_status = HealthStatus::UNKNOWN, int lb_weight = 1) {
  if (stop_index == 0) stop_index = backends_.size();
  std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints;
  for (size_t i = start_index; i < stop_index; ++i) {
    endpoints.emplace_back(backends_[i]->port(), health_status, lb_weight);
  }
  return endpoints;
}
```

So an individual test wanting to create an EDS resource can do this:

```
  AdsServiceImpl::EdsResourceArgs args({
      {"locality0",
       CreateEndpointsForBackends()}});
  balancers_[0]->ads_service()->SetEdsResource(
      BuildEdsResource(args, DefaultEdsServiceName()));
```

Or, if they want to set the health status and/or weight for each individual endpoint, they can do something like this:

```
  std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints = {
    { backends_[0]->port(), HealthStatus::UNKNOWN, 1 },
    { backends_[1]->port(), HealthStatus::UNKNOWN, 2 },
    { backends_[2]->port(), HealthStatus::UNKNOWN, 3 },
    { backe [...]

2021-04-26 07:48 UTC, voidzcy reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697)* status: 6 of 16 files reviewed, 28 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 647 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqf7G699CCdVTEpXWH:-MZC7F7kBxC2MDwRF9pM:b-low922) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L647)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This seems like a very strange algorithm.  Doesn't this bias heavily toward higher values, because the more significant bits are more likely to be 1 than 0?  Any given bit will be 1 if that bit was 1 in either its original octet or in any of the less-significant octets.

@voidzcy, what are you doing for this in Java?
</blockquote></details>

Where does this algorithm come from? Why are we duplicating the lower 16 bits in an uint64_t and use that number as the hash? In Java, we simply use the xx_hash function to compute the hash for the channel ID and do the post-processing below.


<!-- Sent from Reviewable.io -->

2021-04-30 23:44 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697)* status: 6 of 16 files reviewed, 29 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 2866 at r10](https://reviewable.io/reviews/grpc/grpc/25697#-MZ_73iD16IVbfI9Fy_o:-MZ_73iD16IVbfI9Fy_p:b-58xfs1) ([raw file](https://github.com/grpc/grpc/blob/068468f059e86cd9fc2e1d566f606a2f4a7e54d5/src/core/ext/xds/xds_api.cc#L2866)):*
> ```cpp
>           envoy_config_cluster_v3_Cluster_RingHashLbConfig_hash_function(
>               ring_hash_config) ==
>           envoy_config_cluster_v3_Cluster_RingHashLbConfig_MURMUR_HASH_2) {
> ```

One thing I just noticed while working on something else: We decided not to support anything other than XX_HASH for the hash function, so we can just NACK any config that specifies any other value.  And that means that we don't actually need the `hash_function` field in the `CdsUpdate` struct, nor do we need the code in the xds_cluster_resolver policy that adds this field to the ring_hash policy's config.

Please make sure we have a test that verifies that we NACK in this case.


<!-- Sent from Reviewable.io -->

2021-05-03 23:46 UTC, donnadionne reviewed
Addressed all comments and added new tests.
Please excuse the logs still in the code, any log that starts with "donna" i will remove in the final version.
PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-MZoc-XJ7VymTUv6KJC7:b-5qxlyd)* status: 6 of 16 files reviewed, 29 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 406 at r5](https://reviewable.io/reviews/grpc/grpc/25697#-MYqgrQmBc0gRayJBN0t:-MZ-AGZI8ULVy6xqaOSy:bef6x1q) ([raw file](https://github.com/grpc/grpc/blob/ba77b9cedc89c6a92737235b5b14a96df6b4c6d3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L406)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you do add a second tracer for more detailed info, this might be a good message to keep around in that second tracer.
</blockquote></details>

i removed all those, inside the pick which is for every rpc, i try not to add any thing in the final product.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 446 at r7](https://reviewable.io/reviews/grpc/grpc/25697#-MYH7g8UA2eTF8lCMkCU:-MZPPjVpDB1RrVbmSGWC:b-e9kfh5) ([raw file](https://github.com/grpc/grpc/blob/8d6b200bb921288e1a2eab0bc6724ae41221aa67/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L446)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we can actually just combine the second-subchannel case into this loop.  See the pseudo-code in the design doc.
</blockquote></details>

combined the 2 cases code match pesudo in design .
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 341 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqgbXO9UOHH_IeTM8G:-MZ-9JFG0USVcPA9q9zK:b-c1rwxn) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L341)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suspect this is going to be way too much logging to do every time we return a new picker.  If you really want this, maybe add a second tracer for this, so that it can be enabled/disabled independently of the other trace messages in this LB policy?
</blockquote></details>

good point i think i'll remove, i have updated the previous log with the size of the ring 
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 498 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqhmmJ5Rx_HtN2K5uE:-MZ6u3VN3hUkLl-eclyn:b-erfzjc) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L498)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This change looks wrong.  How could this ever be 0 if we were just in IDLE state?
</blockquote></details>

restored, and i started increment num_idle_ via UpdateConnectivityStateLocked when i started the watch 
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 647 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqf7G699CCdVTEpXWH:-MZVN9D8C5oYdwt1Zkok:bd28xj3) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L647)):*
<details><summary><i>Previously, voidzcy (Chengyuan Zhang) wrote…</i></summary><blockquote>

Where does this algorithm come from? Why are we duplicating the lower 16 bits in an uint64_t and use that number as the hash? In Java, we simply use the xx_hash function to compute the hash for the channel ID and do the post-processing below.
</blockquote></details>

fixed to just use XXH64 on the resolver addressed (turned into a string)
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 682 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqedEG5xb8qbJUPpNI:-MZ6uXY5EBr1eRpIFQI9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L682)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the first argument to `absl::StrCat()`.  It's fine to pass it just one.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2866 at r10](https://reviewable.io/reviews/grpc/grpc/25697#-MZ_73iD16IVbfI9Fy_o:-MZft08vE7DLrpS8pr2R:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/068468f059e86cd9fc2e1d566f606a2f4a7e54d5/src/core/ext/xds/xds_api.cc#L2866)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

One thing I just noticed while working on something else: We decided not to support anything other than XX_HASH for the hash function, so we can just NACK any config that specifies any other value.  And that means that we don't actually need the `hash_function` field in the `CdsUpdate` struct, nor do we need the code in the xds_cluster_resolver policy that adds this field to the ring_hash policy's config.

Please make sure we have a test that verifies that we NACK in this case.
</blockquote></details>

Done.
___
*[src/proto/grpc/testing/xds/v3/route.proto, line 256 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqiJWrDNY_u9dXXKNy:-MZoE-1I8xyRIFZG2Sav:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/proto/grpc/testing/xds/v3/route.proto#L256)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This looks like the comment for the `regex_rewrite` field.  Why is that field not actually being added here?  We should probably be testing that case too.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 489 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYuLCpZ11rbG2Bd_-EU:-MZGdBah7S2CsdqP8b8w:b-tlkisf) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/test/cpp/end2end/xds_end2end_test.cc#L489)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We've now got 3 different vectors here, each of which contains a different field for the individual endpoints.  I think it may be time to change this to have a separate object to represent the fields of an endpoint and then pass in a vector of those objects here.

In other words, consider something like this:

```
struct Endpoint {
  explicit Endpoint(int port, HealthStatus health_status = HealthStatus::UNKNOWN, int lb_weight = 1)
      : port(port), health_status(health_status), lb_weight(lb_weight) {}

  int port;
  HealthStatus health_status;
  int lb_weight;
};

struct Locality {
  Locality(std::string sub_zone, std::vector<Endpoint> endpoints,
           int lb_weight = kDefaultLocalityWeight,
           int prioruty = kDefaultLocalityPriority)
      : sub_zone(std::move(sub_zone)),
        endpoints(std::move(endpoints)),
        lb_weight(lb_weight),
        priority(priority) {}

  std::string sub_zone;
  std::vector<Endpoint> endpoints;
  int lb_weight;
  int priority;
};
```

You can then add a utility method to `XdsEnd2endTest` to help construct the endpoints:

```
std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> CreateEndpointsForBackends(
    size_t start_index = 0, size_t stop_index = 0,
    HealthStatus health_status = HealthStatus::UNKNOWN, int lb_weight = 1) {
  if (stop_index == 0) stop_index = backends_.size();
  std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints;
  for (size_t i = start_index; i < stop_index; ++i) {
    endpoints.emplace_back(backends_[i]->port(), health_status, lb_weight);
  }
  return endpoints;
}
```

So an individual test wanting to create an EDS resource can do this: [...]

2021-05-05 22:53 UTC, markdroth requested changes
This is getting closer!

Please let me know if you have any questions.  Thanks!

> Reviewed 15 of 15 files at r12.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-MZyj4kf0zDngTSIi18W:b79zqk9)* status: all files reviewed, 31 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 498 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqhmmJ5Rx_HtN2K5uE:-MZxz94v8LydX_touAXL:b-dwar47) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L498)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

restored, and i started increment num_idle_ via UpdateConnectivityStateLocked when i started the watch 
</blockquote></details>

I don't think we need to check that `new_state` is not IDLE.  That shouldn't happen here, but even if it does, it's fine to decrement here, because the counter will get re-incremented below.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 349 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxetfuBfSPfP8yDKiB:-MZxetfuBfSPfP8yDKiC:b-fwdmpr) ([raw file](https://github.com/grpc/grpc/blob/7d35ec993d3c15e93aa3083585afec5487d83fa3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L349)):*
> ```cpp
> }
> 
> bool RingHash::Picker::ConnectAndPickHelper(const RingEntry& entry,
> ```

This is now being called in only one place, so there's probably no point in having the code in a separate function.  Let's just inline the code in `Pick()`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 385 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZx_2By68wxZs1NXn0G:-MZx_2Bz2AdVFm4tTL-F:b-9q775c) ([raw file](https://github.com/grpc/grpc/blob/7d35ec993d3c15e93aa3083585afec5487d83fa3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L385)):*
> ```cpp
>   }
>   // Ported from https://github.com/RJ/ketama/blob/master/libketama/ketama.c
>   // (ketama_get_server) I've generally kept the variable names to make the code
> ```

This comment needs updating, since you've renamed `midp` to `first_index`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 434 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxeZT-AvIFnncBYA6w:-MZxeZT-AvIFnncBYA6x:b-sk1244) ([raw file](https://github.com/grpc/grpc/blob/7d35ec993d3c15e93aa3083585afec5487d83fa3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L434)):*
> ```cpp
>   // On the way, we make sure the right set of connection attempts
>   // will happen.
>   auto first_channel = ring_[first_index].subchannel;
> ```

This is taking a ref to the subchannel for no real benefit.  Let's remove this variable and instead just refer to `ring_[first_index].subchannel` where we use this below.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 487 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxlFaG1dBjW5lPppP1:-MZxlFaG1dBjW5lPppP2:b4onw9t) ([raw file](https://github.com/grpc/grpc/blob/7d35ec993d3c15e93aa3083585afec5487d83fa3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L487)):*
> ```cpp
>     if (subchannel(i)->subchannel() != nullptr) {
>       subchannel(i)->StartConnectivityWatchLocked();
>       subchannel(i)->UpdateConnectivityStateLocked(GRPC_CHANNEL_IDLE);
> ```

This is incorrect, for two reasons:
1. We can't assume IDLE here, because the subchannel could already be connected because it's in use by another channel.
2. It's not safe to call `UpdateConnectivityStateLocked()` after `StartConnectivityWatchLocked()`, because there's no guarantee that `ProcessConnectivityChangeLocked()` won't be called with some other state value from inside of `StartConnectivityWatchLocked()`, in which case this call will change the state back to IDLE incorrectly.

Instead, we should handle this in a similar way to what round_robin does, where we have a separate loop to set the initial connectivity state of each subchannel before we start the watches:

https://github.com/grpc/grpc/blob/88322f4e67ee275a83603c2d3d1658686a52cb99/src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc#L258

However, unlike round_robin, we need to also handle subchannels in IDLE state.  The round_robin code doesn't do that, so it initializes `last_connectivity_state_` to IDLE, and then before it starts a connectivity watch for each subchannel, it checks the current state, and if that state is not IDLE, it calls `UpdateConnectivityStateLocked()` to change it, which also updates the counters.  That works for round_robin, because there is no `num_idle` counter, so changing from IDLE to (e.g.) READY will increment `num_ready_` and not do anything else.  But in our case, it won't work, because it would both increment `num_ready_` and decrement `num_idle_`, which is already 0, thus leaving it with a negative value.

So in this case, what I suggest is to change the default value of `last_connectivity_state_` from IDLE to SHUTDOWN.  Then we can just unconditionally call `UpdateConnectivityStateLocked()` after calling `CheckConnectivityStateLocked()`, since the transition from SHUTDOWN to IDLE will increment `num_idle_` and have no other effect (since subchannels never actually report SHUTDOWN).

In other words, we can just add the following loop above this one:

```
  for (size_t i = 0; i < num_subchannels(); ++i) {
    grpc_connectivity_state state =
        subchannel(i)->CheckConnectivityStateLocked();
    subchannel(i)->UpdateConnectivityStateLocked(state);
  }
```

You'll also need to remove the assertions that `old_state != GRPC_CHANNEL_SHUTDOWN` at the top of `UpdateStateCountersLocked()`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 640 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxlmKOC_2Cct2rFVfl:-MZxlmKOC_2Cct2rFVfm:b-xjys7m) ([raw file](https://github.com/grpc/grpc/blob/7d35ec993d3c15e93aa3083585afec5487d83fa3/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L640)):*
> ```cpp
>   // ring.
>   bool reattempt = subchannel_list()->UpdateRingHashConnectivityStateLocked();
>   // While the ring_hash policy is reporting TRANSIENT_FAILURE or IDLE, it will
> ```

This looks wrong.  We should not do this proactive reconnecting in state IDLE, only in state TRANSIENT_FAILURE.  The priority policy will still be sending us traffic if we're in IDLE, because it treats IDLE and READY the same.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1216 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxY5GK2PkFcwAg9A4P:-MZxY5GK2PkFcwAg9A4Q:b4vp3ir) ([raw file](https://github.com/grpc/grpc/blob/7d35ec993d3c15e93aa3083585afec5487d83fa3/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1216)):*
> ```cpp
>               continue;
>             }
>             // TODO(donnadionne): Move this to a method in
> ```

We should probably address this TODO as part of this PR.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 682 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqedEG5xb8qbJUPpNI:-MZxZKyZ622bkY16cqcu:bocb2l1) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L682)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 646 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxYjcT-2AhS3SD78sd:-MZxYjcT-2AhS3SD78se:b-3x23ps) ([raw file](https://github.com/grpc/grpc/blob/7d35ec993d3c15e93aa3083585afec5487d83fa3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L646)):*
>  [...]

2021-05-07 05:14 UTC, donnadionne reviewed
PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-M_4Eq_g9MYlfaeUGNNB:b-h8gvr0)* status: 13 of 20 files reviewed, 28 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 498 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqhmmJ5Rx_HtN2K5uE:-MZztFPu3FomgIc0DoIa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L498)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need to check that `new_state` is not IDLE.  That shouldn't happen here, but even if it does, it's fine to decrement here, because the counter will get re-incremented below.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 349 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxetfuBfSPfP8yDKiB:-MZzhtElDQOW9q-Rwfl3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L349)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is now being called in only one place, so there's probably no point in having the code in a separate function.  Let's just inline the code in `Pick()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 385 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZx_2By68wxZs1NXn0G:-MZzhtYF0WnAUpdPE08P:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L385)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment needs updating, since you've renamed `midp` to `first_index`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 434 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxeZT-AvIFnncBYA6w:-MZziLBlA9qzC0NXGrNv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L434)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is taking a ref to the subchannel for no real benefit.  Let's remove this variable and instead just refer to `ring_[first_index].subchannel` where we use this below.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 487 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxlFaG1dBjW5lPppP1:-MZzsBS_9fKinWn4tioR:b-7ql1td) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L487)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is incorrect, for two reasons:
1. We can't assume IDLE here, because the subchannel could already be connected because it's in use by another channel.
2. It's not safe to call `UpdateConnectivityStateLocked()` after `StartConnectivityWatchLocked()`, because there's no guarantee that `ProcessConnectivityChangeLocked()` won't be called with some other state value from inside of `StartConnectivityWatchLocked()`, in which case this call will change the state back to IDLE incorrectly.

Instead, we should handle this in a similar way to what round_robin does, where we have a separate loop to set the initial connectivity state of each subchannel before we start the watches:

https://github.com/grpc/grpc/blob/88322f4e67ee275a83603c2d3d1658686a52cb99/src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc#L258

However, unlike round_robin, we need to also handle subchannels in IDLE state.  The round_robin code doesn't do that, so it initializes `last_connectivity_state_` to IDLE, and then before it starts a connectivity watch for each subchannel, it checks the current state, and if that state is not IDLE, it calls `UpdateConnectivityStateLocked()` to change it, which also updates the counters.  That works for round_robin, because there is no `num_idle` counter, so changing from IDLE to (e.g.) READY will increment `num_ready_` and not do anything else.  But in our case, it won't work, because it would both increment `num_ready_` and decrement `num_idle_`, which is already 0, thus leaving it with a negative value.

So in this case, what I suggest is to change the default value of `last_connectivity_state_` from IDLE to SHUTDOWN.  Then we can just unconditionally call `UpdateConnectivityStateLocked()` after calling `CheckConnectivityStateLocked()`, since the transition from SHUTDOWN to IDLE will increment `num_idle_` and have no other effect (since subchannels never actually report SHUTDOWN).

In other words, we can just add the following loop above this one:

```
  for (size_t i = 0; i < num_subchannels(); ++i) {
    grpc_connectivity_state state =
        subchannel(i)->CheckConnectivityStateLocked();
    subchannel(i)->UpdateConnectivityStateLocked(state);
  }
```

You'll also need to remove the assertions that `old_state != GRPC_CHANNEL_SHUTDOWN` at the top of `UpdateStateCountersLocked()`.
</blockquote></details>

fixed
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 640 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxlmKOC_2Cct2rFVfl:-MZztGK92ql3Hgqm0vdp:b-8xqkn0) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L640)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This looks wrong.  We should not do this proactive reconnecting in state IDLE, only in state TRANSIENT_FAILURE.  The priority policy will still be sending us traffic if we're in IDLE, because it treats IDLE and READY the same.
</blockquote></details>

here only the comment is wrong, i restored the change for IDLE after https://github.com/grpc/grpc/pull/26131
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1216 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxY5GK2PkFcwAg9A4P:-M_26UheBw45szut7z-z:bs7wumx) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1216)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should probably address this TODO as part of this PR.
</blockquote></details>

Done. 
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 682 at r8](https://reviewable.io/reviews/grpc/grpc/25697#-MYqedEG5xb8qbJUPpNI:-M_-EoLJD_-rBZG0_ncJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aa2f8167849bc76e18712a6b945aecdbd12eb7dc/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L682)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 646 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxYjcT-2AhS3SD78sd:-M_-JZrH7k-1nuB2cv9R:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L646)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to declare this up here.  You can do it inside of the `switch` statement by adding braces around the code under the `case` statement.

Also, "seed" is the wrong term her [...]

2021-05-07 16:51 UTC, markdroth requested changes
I think we've got all the right test cases now, so there's just a bit of cleanup work remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 7 files at r15, 5 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-M_6jJHoAdZDl1QoRA5m:b-kmzm8u)* status: all files reviewed, 33 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h, line 29 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6SZz1CMfa3aL70Cdu:-M_6SZz1CMfa3aL70Cdv:b-ty3a55) ([raw file](https://github.com/grpc/grpc/blob/9921d3b91c34bb75cf0baef6cc4fa20dc19997d0/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h#L29)):*
> ```objc
> namespace grpc_core {
> extern const char* kRequestRingHashAttribute;
> extern std::vector<grpc_error*> ParseRingHash(const Json& json,
> ```

No need for `extern`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h, line 29 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6SaYCDbCGRoejR55N:-M_6SaYCDbCGRoejR55O:b-7suh8j) ([raw file](https://github.com/grpc/grpc/blob/9921d3b91c34bb75cf0baef6cc4fa20dc19997d0/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h#L29)):*
> ```objc
> namespace grpc_core {
> extern const char* kRequestRingHashAttribute;
> extern std::vector<grpc_error*> ParseRingHash(const Json& json,
> ```

Suggest calling this `ParseRingHashLbConfig()`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h, line 29 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6Siwk2HzpJ5mnjGbt:-M_6Siwk2HzpJ5mnjGbu:bt3yo88) ([raw file](https://github.com/grpc/grpc/blob/9921d3b91c34bb75cf0baef6cc4fa20dc19997d0/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h#L29)):*
> ```objc
> namespace grpc_core {
> extern const char* kRequestRingHashAttribute;
> extern std::vector<grpc_error*> ParseRingHash(const Json& json,
> ```

Please document this function.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 640 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxlmKOC_2Cct2rFVfl:-M_6Xd0yE0jhtmYRm3Xn:bx190wk) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L640)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

here only the comment is wrong, i restored the change for IDLE after https://github.com/grpc/grpc/pull/26131
</blockquote></details>

Unless I'm missing something here, I don't think this has anything to do with #26131.  That PR affected the xds_cluster_manager policy, but the behavior we're talking about here is in the priority policy.

You changed the comment here, but you still need to change `UpdateRingHashConnectivityStateLocked()` back to returning false if the aggregated state is IDLE.  And you should rename the local variable here from `reattempt` back to `is_transient_failure`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 431 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6VMQvBhTJ2mqLMLzB:-M_6VMQvBhTJ2mqLMLzC:b-x6tehp) ([raw file](https://github.com/grpc/grpc/blob/9921d3b91c34bb75cf0baef6cc4fa20dc19997d0/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L431)):*
> ```cpp
>         subchannel_connection_attempter->AddSubchannel(std::move(subchannel));
>       };
>   bool attempt_to_connect = true;
> ```

Suggest writing this as:

```
switch (ring_[first_index].connectivity_state) {
  case GRPC_CHANNEL_READY:
    result.type = PickResult::PICK_COMPLETE;
    result.subchannel = ring_[first_index].subchannel;
    return result;
  case GRPC_CHANNEL_IDLE:
    ScheduleSubchannelConnectionAttempt(ring_[first_index].subchannel);
    // fallthrough
  case GRPC_CHANNEL_CONNECTING:
    result.type = PickResult::PICK_QUEUE;
    return result;
  default:  // TRANSIENT_FAILURE
    break;
}
ScheduleSubchannelConnectionAttempt(ring_[first_index].subchannel);
// Loop through remaining subchannels to find one in READY.
// On the way, we make sure the right set of connection attempts
// will happen.
```
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 589 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6XKFr5eo_4CG3VPpN:-M_6XKFr5eo_4CG3VPpO:bkuhr9l) ([raw file](https://github.com/grpc/grpc/blob/9921d3b91c34bb75cf0baef6cc4fa20dc19997d0/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L589)):*
> ```cpp
>     return false;
>   }
> ```

Please remove blank lines within functions, both here and below.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 684 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6YHa59UWFj8_bnSIJ:-M_6YHa59UWFj8_bnSIK:b3c4yfp) ([raw file](https://github.com/grpc/grpc/blob/9921d3b91c34bb75cf0baef6cc4fa20dc19997d0/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L684)):*
> ```cpp
>   // successfully connects, at which point it will report READY and stop
>   // proactively trying to connect.  The policy will remain in
>   // TRANSIENT_FAILURE or IDLE until at least one subchannel becomes connected,
> ```

Need to remove "or IDLE" here.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 768 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6TkUI7_dY1yVvZjp-:-M_6TkUI7_dY1yVvZjp0:b-zd552a) ([raw file](https://github.com/grpc/grpc/blob/9921d3b91c34bb75cf0baef6cc4fa20dc19997d0/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L768)):*
> ```cpp
>   RefCountedPtr<LoadBalancingPolicy::Config> ParseLoadBalancingConfig(
>       const Json& json, grpc_error** error) const override {
>     if (json.type() != Json::Type::OBJECT) {
> ```

This check can probably be moved into the `ParseRingHash()` function, since it's common to both sites where that function is called.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 773 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6UTnS358vHmJfNBoQ:-M_6UTnS358vHmJfNBoR:b75kyfv) ([raw file](https://github.com/grpc/grpc/blob/9921d3b91c34bb75cf0baef6cc4fa20dc19997d0/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L773)):*
> ```cpp
>       return nullptr;
>     }
>     const Json::Object& ring_hash = json.object_value();
> ```

No need to extra the `Json::Object` from inside the `Json` object here.  The parameter to `ParseRingHash()` is a `Json` object, so this is basically unwrapping the `Json::Object` just to wrap it back up again and then unwrap it again inside of the function.  Instead, just pass `json` directly to `ParseRingHash()`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 774 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6V04x-paFVKS1Z_Ui:-M_6V04yE5xtoGwtrHjQ:b5cfjc2) ([raw file](https://github.com/grpc/grpc/blob/9921d3b91c34bb75cf0baef6cc4fa20dc19997d0/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L774)):*
> ```cpp
>     }
>     const Json::Object& ring_hash = json.object_value();
>     size_t min_ring_size = 1024;
> ```

Suggest setting these default values inside of `ParseRingHash()`, so that we don't need to encode them in two different places.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1218 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6TytX0rRVDsc9_xMw:-M_6TytX0rRVDsc9_xMx:b-vjl909) ([raw file](https://github.com/grpc/grpc/blob/9921d3b91c34bb75cf0baef6cc4fa20dc19997d0/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1218)):*
> ```cpp
>             }
>             xds_lb_policy = array[i];
>             const Json::Object& ring_hash = policy_it->second.object_value();
> ```

No need to extra the `Json::Object` from inside the `Json` object here.  The parameter to `ParseRing [...]

2021-05-12 04:53 UTC, donnadionne reviewed
Addressed all comments; adjusted/added code/test.  Let me know what you think

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-M_TurCD3KbxwKpjhOxN:bcl0eew)* status: 15 of 20 files reviewed, 33 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h, line 29 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6SZz1CMfa3aL70Cdu:-M_MtjpT5SDnVLjCw-4L:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `extern`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h, line 29 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6SaYCDbCGRoejR55N:-M_MtkA64Od_mCGZHnRA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `ParseRingHashLbConfig()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h, line 29 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6Siwk2HzpJ5mnjGbt:-M_Mtkb11IWHfDiFdP8s:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.h#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document this function.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 640 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxlmKOC_2Cct2rFVfl:-M_P_axqAMVlMY6MqnO8:b-c7tna5) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L640)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Unless I'm missing something here, I don't think this has anything to do with #26131.  That PR affected the xds_cluster_manager policy, but the behavior we're talking about here is in the priority policy.

You changed the comment here, but you still need to change `UpdateRingHashConnectivityStateLocked()` back to returning false if the aggregated state is IDLE.  And you should rename the local variable here from `reattempt` back to `is_transient_failure`.
</blockquote></details>

you are right, i thought 26131 handled the idle case, but not exactly.

once we are not doing a reattempt in ring hash in idle case in UpdateRingHashConnectivityStateLocked() , we are stuck not connecting.

I added implementation for ExitIdleStateLocked for ring hash, let me know if that is the correct apporach 
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 431 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6VMQvBhTJ2mqLMLzB:-M_Pdj01-QG6ZF9YrMEs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L431)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as:

```
switch (ring_[first_index].connectivity_state) {
  case GRPC_CHANNEL_READY:
    result.type = PickResult::PICK_COMPLETE;
    result.subchannel = ring_[first_index].subchannel;
    return result;
  case GRPC_CHANNEL_IDLE:
    ScheduleSubchannelConnectionAttempt(ring_[first_index].subchannel);
    // fallthrough
  case GRPC_CHANNEL_CONNECTING:
    result.type = PickResult::PICK_QUEUE;
    return result;
  default:  // TRANSIENT_FAILURE
    break;
}
ScheduleSubchannelConnectionAttempt(ring_[first_index].subchannel);
// Loop through remaining subchannels to find one in READY.
// On the way, we make sure the right set of connection attempts
// will happen.
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 589 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6XKFr5eo_4CG3VPpN:-M_Pdq5TBNWK0-QDYATX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L589)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank lines within functions, both here and below.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 684 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6YHa59UWFj8_bnSIJ:-M_Pa18DD3VEl6KpX_DQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L684)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to remove "or IDLE" here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 768 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6TkUI7_dY1yVvZjp-:-M_RQ2Ca7Jwos6nx_P9M:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L768)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check can probably be moved into the `ParseRingHash()` function, since it's common to both sites where that function is called.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 773 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6UTnS358vHmJfNBoQ:-M_RP0SH-t6wFhukC6LN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L773)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to extra the `Json::Object` from inside the `Json` object here.  The parameter to `ParseRingHash()` is a `Json` object, so this is basically unwrapping the `Json::Object` just to wrap it back up again and then unwrap it again inside of the function.  Instead, just pass `json` directly to `ParseRingHash()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 774 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6V04x-paFVKS1Z_Ui:-M_RQ0HQ2VLLsUsY8Fm5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L774)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest setting these default values inside of `ParseRingHash()`, so that we don't need to encode them in two different places.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1218 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6TytX0rRVDsc9_xMw:-M_RQ4G91HBihaNZ1VCf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1218)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to extra the `Json::Object` from inside the `Json` object here.  The parameter to `ParseRingHash()` is a `Json` object, so this is basically unwrapping the `Json::Object` just to wrap it back up again and then unwrap it again inside of the function.  Instead,  [...]

2021-05-12 18:26 UTC, markdroth requested changes
This is getting closer!  I think the IDLE handling still needs a bit of work.  But other than that, the other comments are mostly cosmetic.

Please let me know if you have any questions.  Thanks

> Reviewed 4 of 5 files at r17, 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-M_Wp2Ac-HLfy3e4iS4F:b-dt3o3d)* status: all files reviewed, 11 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 640 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxlmKOC_2Cct2rFVfl:-M_Wd39jCPttKUWq8xIB:bukc71w) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L640)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

you are right, i thought 26131 handled the idle case, but not exactly.

once we are not doing a reattempt in ring hash in idle case in UpdateRingHashConnectivityStateLocked() , we are stuck not connecting.

I added implementation for ExitIdleStateLocked for ring hash, let me know if that is the correct apporach 
</blockquote></details>

Ah, okay, I see the problem.  In `RingHashSubchannelList::UpdateRingHashConnectivityStateLocked()`, when we choose IDLE state, we return a `QueuePicker` instead of a ring-hash picker.  The `QueuePicker` calls `ExitIdleLocked()` and expects that to cause the policy to exit idle, which wasn't happening because `ExitIdleLocked()` was a no-op, so the policy was never actually trying to connect any subchannels.

However, I don't think the right solution here is to implement `ExitIdleLocked()`, because that won't necessarily connect to the specific subchannel that the request is actually hashed to.  Consider the following case:

1. The policy starts up with a ring containing 2 subchannels.  (For simplicity, let's assume only one ring entry for each subchannel.)  It starts in IDLE state, so it returns a `QueuePicker`.
2. A request comes in that would hash to the second subchannel.  The `QueuePicker` sees the request and calls `ExitIdleLocked()`, which attempts to connect to the first subchannel.
3. The first subchannel becomes connected and moves to state READY, so the policy now returns a ring-hash picker.
4. The channel retries the request with the new picker.  The picker hashes to the second subchannel and tells that subchannel to connect.
5. When the second subchannel becomes connected, we return a new picker, and the request is finally sent to the second subchannel.

In this scenario, we didn't need to connect to the first subchannel at all.  But even worse, we doubled the latency of the RPC, because we required it to wait until we connected to both the first and second subchannels, and those connection attempts were done serially, not in parallel.

I think the right way to fix this is to change `RingHashSubchannelList::UpdateRingHashConnectivityStateLocked()` such that when we're in IDLE state, we return a ring-hash picker, just like we do in READY state.  That way, regardless of whether the state is IDLE or READY, a pick for any request will cause connections for the subchannel that that request actually hashes to.

Once we make that change, there should be no more need for `ExitIdleLocked()`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 154 at r19](https://reviewable.io/reviews/grpc/grpc/25697#-M_Wgojh3-I1KAYoKqVM:-M_Wgojh3-I1KAYoKqVN:b-f34hff) ([raw file](https://github.com/grpc/grpc/blob/2276846c555eeea64f193f85086a5a6cdcfe4b9a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L154)):*
> ```cpp
>     // Attempts to connect to the next subchannel to keep at least one
>     // connection in flight.
>     void AttemptToConnectNextSubChannel();
> ```

This method doesn't make sense on `RingHashSubchannelData`, because it's not about connecting to *this* subchannel; it's about connecting to the next one.  If you want to keep this, then I'd suggest making it a method of `RingHashSubchannelList` and having it take the index of the current subchannel as a parameter.

That having been said, given my comment below about not needing `ExitIdleLocked()`, I suspect that this method isn't needed in the first place.  I think you can just move this code back into `RingHashSubchannelData::ProcessConnectivityChangeLocked()`, which should be the only place it's needed.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 208 at r19](https://reviewable.io/reviews/grpc/grpc/25697#-M_WhOSE7GE77D6oniWM:-M_WhOSE7GE77D6oniWN:bmumm2x) ([raw file](https://github.com/grpc/grpc/blob/2276846c555eeea64f193f85086a5a6cdcfe4b9a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L208)):*
> ```cpp
>     size_t num_connecting_ = 0;
>     size_t num_transient_failure_ = 0;
>     grpc_connectivity_state connectivity_state_ = GRPC_CHANNEL_SHUTDOWN;
> ```

As mentioned elsewhere, I don't think we actually need `ExitIdleLocked()`, so I don't think this field is needed.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 646 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxYjcT-2AhS3SD78sd:-M_WhjjL4CURKVCviJuk:b-l4u0cw) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L646)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i moved it down a bit into the loop, i can't put it inside the case coz it's then its a compile error about "cannot jump from switch statement to this case label default"
</blockquote></details>

As I mentioned above, you can put it inside the case statement if you add braces around the contents of the case statement.  In other words, do this:

```
  case XdsApi::Route::HashPolicy::CHANNEL_ID: {
    std::string address_str = absl::StrFormat(
        "%" PRIu64,
        static_cast<uint64_t>(reinterpret_cast<uintptr_t>(resolver)));
    new_hash = XXH64(address_str.c_str(), address_str.length(), 0);
    break;
  }
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 678 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxZEWXEKxLrMLmmJ1E:-M_WiazCBeH6Q1X3x2C_:baq5ojc) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L678)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

you mean "hash = rand();"?  i find that rand() cannot generate a 64 bit number, it's too small so it's hashing to 1 entry

i didn't find a rand_uint64 that i could use, i could write one or do what i did?
</blockquote></details>

Ah, okay -- that makes sense.  Thanks!
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 680 at r19](https://reviewable.io/reviews/grpc/grpc/25697#-M_WiegHCfPu74uUEU_r:-M_WiegHCfPu74uUEU_s:b-cqbg4j) ([raw file](https://github.com/grpc/grpc/blob/2276846c555eeea64f193f85086a5a6cdcfe4b9a/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L680)):*
> ```cpp
>     if (!hash.has_value()) {
>       // If there is no hash, we just choose a random value as a default.
>       // hash = rand();  hash generated is too mall, not 64-bit long so it's not
> ```

Please change this comment to say something like this:

We cannot directly use the result of rand() as the hash value, since it is not a 64-bit number and will therefore not be evenly distributed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7092 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZyiFU3BgkWULghBMu9:-M_WoRzs71AGwsuN54Xz:b9bkkp1) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/test/cpp/end2end/xds_end2end_test.cc#L7092)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

ok separated the 2 cases now: R [...]

2021-05-13 07:33 UTC, donnadionne reviewed
Fixed according to comments; did have a couple of questions and clarifications for corner cases, i added my comments inline.  Please let me know what you think.  Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-M_Zd4Qq8JoKubZIJR0b:bzi6pop)* status: 17 of 20 files reviewed, 13 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 640 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxlmKOC_2Cct2rFVfl:-M_XZGNX4B6ilgdfTAJQ:b-kriy57) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L640)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ah, okay, I see the problem.  In `RingHashSubchannelList::UpdateRingHashConnectivityStateLocked()`, when we choose IDLE state, we return a `QueuePicker` instead of a ring-hash picker.  The `QueuePicker` calls `ExitIdleLocked()` and expects that to cause the policy to exit idle, which wasn't happening because `ExitIdleLocked()` was a no-op, so the policy was never actually trying to connect any subchannels.

However, I don't think the right solution here is to implement `ExitIdleLocked()`, because that won't necessarily connect to the specific subchannel that the request is actually hashed to.  Consider the following case:

1. The policy starts up with a ring containing 2 subchannels.  (For simplicity, let's assume only one ring entry for each subchannel.)  It starts in IDLE state, so it returns a `QueuePicker`.
2. A request comes in that would hash to the second subchannel.  The `QueuePicker` sees the request and calls `ExitIdleLocked()`, which attempts to connect to the first subchannel.
3. The first subchannel becomes connected and moves to state READY, so the policy now returns a ring-hash picker.
4. The channel retries the request with the new picker.  The picker hashes to the second subchannel and tells that subchannel to connect.
5. When the second subchannel becomes connected, we return a new picker, and the request is finally sent to the second subchannel.

In this scenario, we didn't need to connect to the first subchannel at all.  But even worse, we doubled the latency of the RPC, because we required it to wait until we connected to both the first and second subchannels, and those connection attempts were done serially, not in parallel.

I think the right way to fix this is to change `RingHashSubchannelList::UpdateRingHashConnectivityStateLocked()` such that when we're in IDLE state, we return a ring-hash picker, just like we do in READY state.  That way, regardless of whether the state is IDLE or READY, a pick for any request will cause connections for the subchannel that that request actually hashes to.

Once we make that change, there should be no more need for `ExitIdleLocked()`.
</blockquote></details>

thank you this works!
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 154 at r19](https://reviewable.io/reviews/grpc/grpc/25697#-M_Wgojh3-I1KAYoKqVM:-M_XZDnDAqOlqduHj86E:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2276846c555eeea64f193f85086a5a6cdcfe4b9a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L154)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This method doesn't make sense on `RingHashSubchannelData`, because it's not about connecting to *this* subchannel; it's about connecting to the next one.  If you want to keep this, then I'd suggest making it a method of `RingHashSubchannelList` and having it take the index of the current subchannel as a parameter.

That having been said, given my comment below about not needing `ExitIdleLocked()`, I suspect that this method isn't needed in the first place.  I think you can just move this code back into `RingHashSubchannelData::ProcessConnectivityChangeLocked()`, which should be the only place it's needed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 208 at r19](https://reviewable.io/reviews/grpc/grpc/25697#-M_WhOSE7GE77D6oniWM:-M_XZFBpA1wnF2qQCU7f:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2276846c555eeea64f193f85086a5a6cdcfe4b9a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L208)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned elsewhere, I don't think we actually need `ExitIdleLocked()`, so I don't think this field is needed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 502 at r20](https://reviewable.io/reviews/grpc/grpc/25697#-M_ZboEe4VEC9D6jS_-D:-M_ZboEe4VEC9D6jS_-E:b-e9g8zw) ([raw file](https://github.com/grpc/grpc/blob/fbe2e9d10e12b68cb7e67f6a2b8b269eefe37f0c/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L502)):*
> ```cpp
>     }
>   }
>   if (found_first_non_failed) {
> ```

It's possible that after a down backend, we will loop through but only found idle or TF.  IF we had idle ones, we should not fail the pick right?

This can be seen with test RingHashTransientFailureCheckNextOne, if we fail the pick outside the loop unconditionally, we will see TF when we do WaitForBackend(1, WaitForBackendOptions(), rpc_options);  At this point, there are idle backends still.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 646 at r12](https://reviewable.io/reviews/grpc/grpc/25697#-MZxYjcT-2AhS3SD78sd:-M_Xcbkp9NRSPLT9JtIH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0cb30a8b7d4d92fc2aeb57ed3715032f6d2eeb50/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L646)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As I mentioned above, you can put it inside the case statement if you add braces around the contents of the case statement.  In other words, do this:

```
  case XdsApi::Route::HashPolicy::CHANNEL_ID: {
    std::string address_str = absl::StrFormat(
        "%" PRIu64,
        static_cast<uint64_t>(reinterpret_cast<uintptr_t>(resolver)));
    new_hash = XXH64(address_str.c_str(), address_str.length(), 0);
    break;
  }
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 680 at r19](https://reviewable.io/reviews/grpc/grpc/25697#-M_WiegHCfPu74uUEU_r:-M_XczaDBRoa28hmqCUL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2276846c555eeea64f193f85086a5a6cdcfe4b9a/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L680)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please change this comment to say something like this:

We cannot directly use the result of rand() as the hash value, since it is not a 64-bit number and will therefore not be evenly distributed.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7293 at r16](https://reviewable.io/reviews/grpc/grpc/25697#-M_6iG-_-fv7vL1adI1z:-M_XHOVWA63qtzP8xuMM:bs7wumx) ([raw file](https://github.com/grpc/grpc/blob/036492734dffaffb5d8c83c704562c8804fde895/test/cpp/end2end/xds_end2end_test.cc#L7293)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`EXPECT_EQ(GRPC_CHANNEL_TRANSIENT_FAILURE, channel_->GetState(false));`
</blockquote></details>

Done. 
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1956 at r19](https://reviewable.io/reviews/grpc/grpc/25697#-M_WjnQ--mMBhKmHX4fF:-M_YTLzX9YL0lB0a4NIr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2276846c555eeea64f193f85086a5a6cdcfe4b9a/test/cpp/end2end/xds_end2end_test.cc#L1956)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we want this to return the whole metadata vector, because this may [...]

2021-05-13 15:00 UTC, markdroth requested changes
This is very close now!  I think the latest change to the picker logic is not quite right, but other than that, only a couple of minor comments.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r20.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-M_aEOvd1Px00k0YPrIz:b-s8nsfh)* status: all files reviewed, 3 unresolved discussions (waiting on @donnadionne, @ejona86, and @voidzcy)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 208 at r19](https://reviewable.io/reviews/grpc/grpc/25697#-M_WhOSE7GE77D6oniWM:-M_a49Fi4-ZsYTaNDvvB:b-aqxdxf) ([raw file](https://github.com/grpc/grpc/blob/2276846c555eeea64f193f85086a5a6cdcfe4b9a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L208)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look like you actually removed this field.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 502 at r20](https://reviewable.io/reviews/grpc/grpc/25697#-M_ZboEe4VEC9D6jS_-D:-M_a8Kab1TJHwqY05XPV:b-bw6s57) ([raw file](https://github.com/grpc/grpc/blob/fbe2e9d10e12b68cb7e67f6a2b8b269eefe37f0c/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L502)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

It's possible that after a down backend, we will loop through but only found idle or TF.  IF we had idle ones, we should not fail the pick right?

This can be seen with test RingHashTransientFailureCheckNextOne, if we fail the pick outside the loop unconditionally, we will see TF when we do WaitForBackend(1, WaitForBackendOptions(), rpc_options);  At this point, there are idle backends still.
</blockquote></details>

Hmmm, this doesn't seem quite right to me.

I think you're right that we should not fail if the first subchannel is in TF and the second subchannel is in IDLE or CONNECTING, because we want to give each RPC a chance to connect to at least two subchannels before failing.  But I don't think we want to queue if we found *any* subchannel that's not in TF, because the whole point of allowing only two subchannels is that if there are a large number of subchannels in the ring, we don't want to queue the pick for the huge amount of time it might take to attempt every single subchannel one at a time.  So I think what we want is to queue only if the second subchannel is in state IDLE.

So instead of this change, I think what we need to do here is to replace the following code from above:

```
    if (entry.connectivity_state == GRPC_CHANNEL_CONNECTING &&
        !found_second_subchannel) {
      result.type = PickResult::PICK_QUEUE;
      return result;
    }
    found_second_subchannel = true;
```

with this:

```
    if (!found_second_subchannel) {
      switch (entry.connectivity_state) {
        case GRPC_CHANNEL_IDLE:
          ScheduleSubchannelConnectionAttempt(entry.subchannel);
          // fallthrough
        case GRPC_CHANNEL_CONNECTING:
          result.type = PickResult::PICK_QUEUE;
          return result;
        default:
          break;
      }
      found_second_subchannel = true;
    }
```

@ejona86, please double-check my logic here to make sure I'm not forgetting anything from when you and I worked out the pseudo-code in the design doc.  We'll probably need to update the pseudo-code once we figure out the right behavior here.

@voidzcy, how is the Java impl handling this case?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7327 at r20](https://reviewable.io/reviews/grpc/grpc/25697#-M_Zaw5fEhE7zZHoQUHY:-M_a6FZW9do3VDCGVjf2:bb4nkjj) ([raw file](https://github.com/grpc/grpc/blob/fbe2e9d10e12b68cb7e67f6a2b8b269eefe37f0c/test/cpp/end2end/xds_end2end_test.cc#L7327)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I saw flakes where when we are waiting for backend 1, we didn't see backend 0 as already brought down and picked it again.  When the TF for backend 0 propagates up we will get a TF.  We recover of course, but if we don't allow this failure the test will fail when this occurs leading to flakes
</blockquote></details>

A better way to fix this is to do `CheckRpcSendFailure()` after shutting down backend 0 before bringing backend 1 back up.  That way, we know that the channel will have already seen backend 0 is down before we get here, and we should never see any failures here.


<!-- Sent from Reviewable.io -->

2021-05-13 16:41 UTC, donnadionne reviewed
all fixed, retested to ensure no flakes, and removed debugs.  PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-M_aafaA4wTqXfB7UpER:bgqc1lt)* status: 15 of 20 files reviewed, 3 unresolved discussions (waiting on @ejona86, @markdroth, and @voidzcy)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 208 at r19](https://reviewable.io/reviews/grpc/grpc/25697#-M_WhOSE7GE77D6oniWM:-M_aQ2XV2qfmjyn7Cqwz:b-q93m35) ([raw file](https://github.com/grpc/grpc/blob/2276846c555eeea64f193f85086a5a6cdcfe4b9a/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L208)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like you actually removed this field.
</blockquote></details>

sorry i missed, remove it now
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 502 at r20](https://reviewable.io/reviews/grpc/grpc/25697#-M_ZboEe4VEC9D6jS_-D:-M_aSWnHEcOdDCYhL33w:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fbe2e9d10e12b68cb7e67f6a2b8b269eefe37f0c/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L502)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hmmm, this doesn't seem quite right to me.

I think you're right that we should not fail if the first subchannel is in TF and the second subchannel is in IDLE or CONNECTING, because we want to give each RPC a chance to connect to at least two subchannels before failing.  But I don't think we want to queue if we found *any* subchannel that's not in TF, because the whole point of allowing only two subchannels is that if there are a large number of subchannels in the ring, we don't want to queue the pick for the huge amount of time it might take to attempt every single subchannel one at a time.  So I think what we want is to queue only if the second subchannel is in state IDLE.

So instead of this change, I think what we need to do here is to replace the following code from above:

```
    if (entry.connectivity_state == GRPC_CHANNEL_CONNECTING &&
        !found_second_subchannel) {
      result.type = PickResult::PICK_QUEUE;
      return result;
    }
    found_second_subchannel = true;
```

with this:

```
    if (!found_second_subchannel) {
      switch (entry.connectivity_state) {
        case GRPC_CHANNEL_IDLE:
          ScheduleSubchannelConnectionAttempt(entry.subchannel);
          // fallthrough
        case GRPC_CHANNEL_CONNECTING:
          result.type = PickResult::PICK_QUEUE;
          return result;
        default:
          break;
      }
      found_second_subchannel = true;
    }
```

@ejona86, please double-check my logic here to make sure I'm not forgetting anything from when you and I worked out the pseudo-code in the design doc.  We'll probably need to update the pseudo-code once we figure out the right behavior here.

@voidzcy, how is the Java impl handling this case?
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7327 at r20](https://reviewable.io/reviews/grpc/grpc/25697#-M_Zaw5fEhE7zZHoQUHY:-M_aSxzi4wz1nXh3E7d-:b-ey41w1) ([raw file](https://github.com/grpc/grpc/blob/fbe2e9d10e12b68cb7e67f6a2b8b269eefe37f0c/test/cpp/end2end/xds_end2end_test.cc#L7327)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

A better way to fix this is to do `CheckRpcSendFailure()` after shutting down backend 0 before bringing backend 1 back up.  That way, we know that the channel will have already seen backend 0 is down before we get here, and we should never see any failures here.
</blockquote></details>

great idea


<!-- Sent from Reviewable.io -->

2021-05-13 18:16 UTC, ejona86 commented
@markdroth, I agree with your amended logic. Yes, we need to check for IDLE for the second subchannel.

2021-05-13 18:24 UTC, markdroth approved these changes
Thanks, Eric.  I've updated the pseudo-code internal design doc.

Donna, this looks great!

> Reviewed 5 of 5 files at r21, 1 of 1 files at r22.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25697#-:-M_axOzxEvGK07PTC7iz:b-pfsrhp)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne)



<!-- Sent from Reviewable.io -->

2021-05-13 19:55 UTC, merged