Reduce xds_end2end_test's error tolerance to 0.05
grpc/grpc pull request #25738
Opened 2021-03-16 23:00 UTC by lidizheng

As discussed in https://github.com/grpc/grpc/pull/24354, it's fully viable to tune down the error tolerance from 0.2/0.3 to 0.05 (5%). It should not only apply to fault injection, but other test cases that need to validate a distribution (like weighted load-balance). But let's see if tests are happy first.

2021-04-16 21:02 UTC, markdroth requested changes
Thanks for doing this!  I really like this approach.

One question about this:

> TIL our `ExecCtx::Get()->Now()` returns a cached timestamp, which made the 1.6k concurrent RPC with different start time sharing the same delay-finishing time (resulting in ms-level error). Fault injection is not on the critical path, adding <100ns to fetch time should not impact performance badly.

I don't quite understand this.  Even if all of the RPCs shared the same start time, what problem does that cause?

Otherwise, my comments are mostly minor.  Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25738#-:-MYRPDHa2Ju8jOUNh4te:btf84n9)* status: all files reviewed, 9 unresolved discussions (waiting on @lidizheng)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 36 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR7aew3JBnvllmy5YO:-MYR7aew3JBnvllmy5YP:b-iwimaa) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L36)):*
> ```cpp
> #include "absl/strings/str_cat.h"
> #include "absl/strings/str_join.h"
> #include "absl/synchronization/notification.h"
> ```

According to https://github.com/grpc/grpc/blob/master/third_party/ABSEIL_MANUAL.md, we're not supposed to use absl/synchronization libraries yet.  @veblush, has that changed?

If we can't use this yet, you may need to use `gpr_event` instead.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1636 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYRD1Xm2jZoGPebN-Qh:-MYRD1Xm2jZoGPebN-Qi:b-cg6dbf) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L1636)):*
> ```cpp
> // E.g., with p=0.5 k=0.1, n >= 378; with p=0.5 k=0.05, n >= 1513; with p=0.5
> // k=0.01, n >= 37830.
> size_t ComputeIdealNumRpcs(double p, double error_tolerance) {
> ```

Can you please have this function log its arguments and return value (e.g., "for percentage=0.5 error_tolerance=0.05, will send 1513 RPCs")?  That way, it's clear from the log what's actually happening for each test.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1637 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR7m2p5x_SoKZ5Rxrs:-MYR7m2p5x_SoKZ5Rxrt:b5l2o5t) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L1637)):*
> ```cpp
> // k=0.01, n >= 37830.
> size_t ComputeIdealNumRpcs(double p, double error_tolerance) {
>   ExpectBetween(p, 0, 1);
> ```

I think you can use `GPR_ASSERT()` here.  It's a programming error in the test if we get some value outside of this range.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2523 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR9MTc-X5WLnIVsuGk:-MYR9MTc-X5WLnIVsuGl:b-m1uw9e) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L2523)):*
> ```cpp
>     // Using unique_ptr here, because we can't copy ClientContext. We allocate
>     // it on heap and let C++ handle its life cycle.
>     std::vector<std::unique_ptr<ConcurrentRpc>> rpcs;
> ```

There's no need to use `unique_ptr<>` here.  You just need to reserve enough space in the vector before you start appending to it, so that it doesn't need to reallocate (thus moving around the existing objects) as it goes:

```
std::vector<ConcurrentRpcs> rpcs;
rpcs.reserve(num_rpcs);
```
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2539 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYRBFtf85jsSkBuH7wJ:-MYRBFtf85jsSkBuH7wK:b-kypyi6) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L2539)):*
> ```cpp
>           [rpc, &mu, &completed, &notification, num_rpcs, t0](Status s) {
>             rpc->status = s;
>             rpc->elapsed_time = NowFromCycleCounter() - t0;
> ```

This doesn't seem accurate, because you're setting `t0` just once before you start the first RPC, but each RPC will actually have its own start time.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2540 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR8LorE57MGZLSjtI5:-MYR8LorE57MGZLSjtI6:b-xjamo6) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L2540)):*
> ```cpp
>             rpc->status = s;
>             rpc->elapsed_time = NowFromCycleCounter() - t0;
>             mu.Lock();
> ```

Suggest writing this as:

```
bool done;
{
  MutexLock lock(&mu);
  done = (++completed) == num_rpcs;
}
if (done) notification.Notify();
```
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4628 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYRG-PB-4bT63mR6y_x:-MYRG-PB-4bT63mR6y_y:b-2g3rpw) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L4628)):*
> ```cpp
>   gpr_log(GPR_INFO, "target_75 received %d rpcs and target_25 received %d rpcs",
>           weight_75_request_count, weight_25_request_count);
>   ExpectBetween(static_cast<double>(weight_75_request_count) / kNumEcho1Rpcs,
> ```

Instead of writing your own `ExpectBetween()` function, I suggest just using the gmock `::testing::DoubleNear()` matcher (see https://google.github.io/googletest/gmock_cheat_sheet.html#FpMatchers).  With that, this becomes:

```
EXPECT_THAT(static_cast<double>(weight_75_request_count) / kNumEcho1Rpcs,
            ::testing::DoubleNear(kWeight75Percent, kErrorTolerance));
```

Same thing throughout.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10128 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYROn5070D2E1SPuUjN:-MYROn5070D2E1SPuUjO:bau5erb) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L10128)):*
> ```cpp
>   const double seen_abort_rate = static_cast<double>(num_aborted) / kNumRpcs;
>   EXPECT_THAT(seen_abort_rate,
>               ::testing::AllOf(::testing::Ge(kAbortRate - kErrorTolerance),
> ```

The fault injection tests should also use `::testing::DoubleNear()`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10207 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYROJNU0RgHxXB64wA4:-MYROJNU0RgHxXB64wA5:bzicufn) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L10207)):*
> ```cpp
>     if (rpc->status.error_code() == grpc::OK) continue;
>     EXPECT_EQ(grpc::DEADLINE_EXCEEDED, rpc->status.error_code());
>     num_delayed++;
> ```

Prefer pre-increment syntax, as per:

https://google.github.io/styleguide/cppguide.html#Preincrement_and_Predecrement

Same thing throughout.


<!-- Sent from Reviewable.io -->

2021-04-16 23:23 UTC, lidizheng commented
Reviewable is having an outage. Most comments are resolved, except the removal of `std::unique_ptr`.

The compiler will complain: https://paste.googleplex.com/6203683218915328

There should not be any copy after changing to:

```
std::vector<ConcurrentRpcs> rpcs;
rpcs.reserve(num_rpcs);
```

But I guess the complaining `static_assert` is a protection that will always be run against the input type of a vector.

2021-04-19 15:07 UTC, markdroth requested changes
I have a couple of suggestions below for how to avoid that compiler error.

Also, I'd still like an answer to my question about the `ExecCtx::Now()` change.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25738#-:-MYee_8lC7_Mevj9m0vg:b9r03ix)* status: all files reviewed, 3 unresolved discussions (waiting on @lidizheng)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 2523 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR9MTc-X5WLnIVsuGk:-MYecYz990RzMcjPvkbl:b6majlj) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L2523)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need to use `unique_ptr<>` here.  You just need to reserve enough space in the vector before you start appending to it, so that it doesn't need to reallocate (thus moving around the existing objects) as it goes:

```
std::vector<ConcurrentRpcs> rpcs;
rpcs.reserve(num_rpcs);
```
</blockquote></details>

Try just saying `std::vector<ConcurrentRpcs> rpcs(num_rpcs);`.  Then there's no need to call `push_back()` for each RPC in the loop below; all the elements are already in the vector.

If that doesn't work, try using `std::list<>` instead of `std::vector<>`.  That shouldn't require any copying at all, because each element in the list is in its own allocation.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2540 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR8LorE57MGZLSjtI5:-MYec4QM4mbxH7nHjZA9:bocb2l1) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L2540)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as:

```
bool done;
{
  MutexLock lock(&mu);
  done = (++completed) == num_rpcs;
}
if (done) notification.Notify();
```
</blockquote></details>

I don't see this change.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1635 at r4](https://reviewable.io/reviews/grpc/grpc/25738#-MYeabdX4f36WhbvqbvG:-MYeabdX4f36WhbvqbvH:b7lxltv) ([raw file](https://github.com/grpc/grpc/blob/bd7a558083a9836dea43bb445fe8b1925a409322/test/cpp/end2end/xds_end2end_test.cc#L1635)):*
> ```cpp
>   size_t num_rpcs =
>       ceil(p * (1 - p) * 3.89 * 3.89 / error_tolerance / error_tolerance);
>   gpr_log(GPR_INFO, "sending %zu RPCs for percentage=%.3f error_tolerance=%.3f",
> ```

The `%z` token is not portable.  Please use `PRIuPTR` instead.


<!-- Sent from Reviewable.io -->

2021-04-19 17:58 UTC, lidizheng reviewed
Thanks for the detailed review!

MSAN still has flake. I guess the increased volume of RPCs slows down each other and causing unexpected timed outs. Increasing the RPC timeouts to 4s. This still runs faster than existing version, thanks to callback API.

> Even if all of the RPCs shared the same start time, what problem does that cause?

When all of the RPCs shared the same start time, they will share the same delay deadline, because the delay deadline is simply start time + delayed microseconds.

For example:
```shell
# 0 ms
Start the for-loop to send RPC A, B, C
Always inject delay 10ms
# 1 ms
RPC A started
ExecCtx caches "Now" as 1 ms
RPC A will delay until 1 + 10 = 11ms
# 2 ms
RPC B started
Fetched start time from ExecCtx::Now() as 1ms
RPC B will delay until 1 + 10 = 11ms
# 3 ms
RPC C started
Fetched start time from ExecCtx::Now() as 1ms
RPC C will delay until 1 + 10 = 11ms
# 11 ms
RPC A, B, C finished
RPC A actually got delayed 10ms
RPC B actually got delayed 9ms
RPC C actually got delayed 8ms

The test case marks RPC B/C as failed.
```

The scale of the error depends on how many RPCs ran on a given `ExecCtx`. The existing test only run RPC in sequence, each `ExecCtx` should only be used by 1 RPC. But it we bump up the number of RPCs to 10^3 and use callback API, this error will be > 1ms, hence detectable by our test case.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25738#-:-MYRbZYPCsDU3F5EC_ii:b-eqi7oe)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 36 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR7aew3JBnvllmy5YO:-MYRsPZXEvX-Ppu8eGF1:b-1moi03) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

According to https://github.com/grpc/grpc/blob/master/third_party/ABSEIL_MANUAL.md, we're not supposed to use absl/synchronization libraries yet.  @veblush, has that changed?

If we can't use this yet, you may need to use `gpr_event` instead.
</blockquote></details>

Changed to use `CondVar` which we are using already in this test file.

It seems compile just fine, passing all the tests. What will go wrong if we use another absl/synchrnoization?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1636 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYRD1Xm2jZoGPebN-Qh:-MYf8xHU0jOe-gy6p1Nc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L1636)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can you please have this function log its arguments and return value (e.g., "for percentage=0.5 error_tolerance=0.05, will send 1513 RPCs")?  That way, it's clear from the log what's actually happening for each test.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1637 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR7m2p5x_SoKZ5Rxrs:-MYf8zqd3toodx0CnD8c:buknftd) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L1637)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you can use `GPR_ASSERT()` here.  It's a programming error in the test if we get some value outside of this range.
</blockquote></details>

Using GPR_ASSERT.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2523 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR9MTc-X5WLnIVsuGk:-MYfASaJEPzXgBsA77Vk:b-4kctyb) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L2523)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Try just saying `std::vector<ConcurrentRpcs> rpcs(num_rpcs);`.  Then there's no need to call `push_back()` for each RPC in the loop below; all the elements are already in the vector.

If that doesn't work, try using `std::list<>` instead of `std::vector<>`.  That shouldn't require any copying at all, because each element in the list is in its own allocation.
</blockquote></details>

Thanks! `std::vector<ConcurrentRpcs> rpcs(num_rpcs);` solved the compiler complaint.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2539 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYRBFtf85jsSkBuH7wJ:-MYReMA365UBILosf2pD:b-c28398) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L2539)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't seem accurate, because you're setting `t0` just once before you start the first RPC, but each RPC will actually have its own start time.
</blockquote></details>

Re-captured `t0` in every loop.

The error here should be negligible, since it's C++. But we could broke it if the invocation of C++ callback API is expensive. So, new t0 is strictly better.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2540 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR8LorE57MGZLSjtI5:-MYfAt6z5EkCu8ILn3LR:b2wd0wu) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L2540)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

Done. This is simpler and easier to read.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4628 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYRG-PB-4bT63mR6y_x:-MYRganWDwoemBWygEpC:b-uaurq5) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L4628)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of writing your own `ExpectBetween()` function, I suggest just using the gmock `::testing::DoubleNear()` matcher (see https://google.github.io/googletest/gmock_cheat_sheet.html#FpMatchers).  With that, this becomes:

```
EXPECT_THAT(static_cast<double>(weight_75_request_count) / kNumEcho1Rpcs,
            ::testing::DoubleNear(kWeight75Percent, kErrorTolerance));
```

Same thing throughout.
</blockquote></details>

TIL there is `::testing::DoubleNear`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10128 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYROn5070D2E1SPuUjN:-MYfB2531GRwnDSOS5dW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L10128)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The fault injection tests should also use `::testing::DoubleNear()`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10207 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYROJNU0RgHxXB64wA4:-MYRgUGS6WM0zejpGkDo:bb741ss) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L10207)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Prefer pre-increment syntax, as per:

https://google.github.io/styleguide/cppguide.html#Preincrement_and_Predecrement

Same thing throughout.
</blockquote></details>

TIL.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1635 at r4](https://reviewable.io/reviews/grpc/grpc/25738#-MYeabdX4f36WhbvqbvG:-MYf91ql9KUdMlU3VmTr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bd7a558083a9836dea43bb445fe8b1925a409322/test/cpp/end2end/xds_end2end_test.cc#L1635)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `%z` token is not portable.  Please use `PRIuPTR` instead.
</blockquote></details>

Done.


<! [...]

2021-04-26 23:32 UTC, lidizheng commented
@markdroth PTAL. The MSAN flake solution is allowing extra time if memory sanitizer is turned on.

MSAN 1000x: https://source.cloud.google.com/results/invocations/e043faea-4e18-4515-8816-35b24782eb4f

2021-04-27 17:27 UTC, markdroth requested changes
Why is `ExecCtx::Now()` caching occurring in the first place here?  Each RPC that we start is its own entry point into C-core, so each one should get its own `ExecCtx` instance and therefore its own value of `Now()`.  I'd like to understand why that's not happening before we switch to using a different clock type in the FI code.

Otherwise, this looks pretty good!  Remaining comments are relatively minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25738#-:-MZJGqa52ar1s0x1EyJ5:b7xomex)* status: all files reviewed, 6 unresolved discussions (waiting on @lidizheng and @veblush)

___
*[include/grpc/impl/codegen/port_platform.h, line 625 at r5](https://reviewable.io/reviews/grpc/grpc/25738#-MZJAYAC9ngOUlKtiKDc:-MZJAYAC9ngOUlKtiKDd:birtoqi) ([raw file](https://github.com/grpc/grpc/blob/7ccc678b891ab2192655037c3a139403a6bca20d/include/grpc/impl/codegen/port_platform.h#L625)):*
> ```objc
> /* GRPC_MSAN_ENABLED will be defined, when compiled with address sanitizer. */
> #ifndef GRPC_MSAN_SUPPRESSED
> #if defined(__SANITIZE_ADDRESS__)
> ```

Shouldn't this be something like `__SANITIZE_MEMORY__`?  I think `__SANITIZE_ADDRESS__` is specific to asan.  But I don't know what sets this macro.

Actually, why do we need this at all?  It looks like we already have code that we can use to detect msan:

https://github.com/grpc/grpc/blob/9977bef14b5eaf48406f2a3996204f56cb5dea56/test/core/util/test_config.cc#L95

If we do need this for some reason, please have @nicolasnoble review the change to this file to make sure this will work right in a portable way.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 36 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR7aew3JBnvllmy5YO:-MZJCpEE4alSFJwnEIgY:bm76l6b) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L36)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Changed to use `CondVar` which we are using already in this test file.

It seems compile just fine, passing all the tests. What will go wrong if we use another absl/synchrnoization?
</blockquote></details>

I think it didn't work on all platforms.  If the tests are all passing now, then this restriction may have gone away.  Please confirm with @veblush; if it has, I'd prefer to use the absl API.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2539 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYRBFtf85jsSkBuH7wJ:-MZJLdK98rpOz015rN1_:b-73k50) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L2539)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Re-captured `t0` in every loop.

The error here should be negligible, since it's C++. But we could broke it if the invocation of C++ callback API is expensive. So, new t0 is strictly better.
</blockquote></details>

Is it possible that this bug was the reason that you needed to switch to the cycle counter clock in the FI filter?  Now that we've fixed this, is that change still needed?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2599 at r5](https://reviewable.io/reviews/grpc/grpc/25738#-MZJBvDUA996ek5A04xx:-MZJBvDUA996ek5A04xy:biz4irk) ([raw file](https://github.com/grpc/grpc/blob/7ccc678b891ab2192655037c3a139403a6bca20d/test/cpp/end2end/xds_end2end_test.cc#L2599)):*
> ```cpp
>       const RpcOptions& rpc_options) {
>     // Variables for RPC.
>     // Using unique_ptr here, because we can't copy ClientContext. We allocate
> ```

This comment can go away now.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9335 at r5](https://reviewable.io/reviews/grpc/grpc/25738#-MZJDmYY1Ss0xxY-h71q:-MZJDmYY1Ss0xxY-h71r:b-rhppbb) ([raw file](https://github.com/grpc/grpc/blob/7ccc678b891ab2192655037c3a139403a6bca20d/test/cpp/end2end/xds_end2end_test.cc#L9335)):*
> ```cpp
>   const double kDropRateForLb = kDropPerMillionForLb / 1000000.0;
>   const double kDropRateForThrottle = kDropPerMillionForThrottle / 1000000.0;
>   const double KDropRateForLbAndThrottle =
> ```

Pre-existing problem, not related to this PR, but please change the leading `K` here to be lower-case.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10236 at r5](https://reviewable.io/reviews/grpc/grpc/25738#-MZJEeTwCeBNFzPf9HM7:-MZJEeTwCeBNFzPf9HM8:bfj5oxh) ([raw file](https://github.com/grpc/grpc/blob/7ccc678b891ab2192655037c3a139403a6bca20d/test/cpp/end2end/xds_end2end_test.cc#L10236)):*
> ```cpp
> TEST_P(FaultInjectionTest, XdsFaultInjectionPercentageDelay) {
>   const uint32_t kFixedDelaySeconds = 100;
> #ifdef GRPC_MSAN_ENABLED
> ```

Instead of a specialized hack for msan here, can we use the existing `grpc_test_slowdown_factor()` code?

https://github.com/grpc/grpc/blob/9977bef14b5eaf48406f2a3996204f56cb5dea56/test/core/util/test_config.cc#L135

Note that we're already using `grpc_timeout_seconds_to_deadline()` when setting the deadlines for the RPCs, which takes the test slowdown factor into account:

https://github.com/grpc/grpc/blob/9977bef14b5eaf48406f2a3996204f56cb5dea56/test/cpp/end2end/xds_end2end_test.cc#L1899
https://github.com/grpc/grpc/blob/9977bef14b5eaf48406f2a3996204f56cb5dea56/test/core/util/test_config.cc#L140


<!-- Sent from Reviewable.io -->

2021-04-27 20:21 UTC, lidizheng reviewed
Before this PR, the number of RPCs sent in partial delay test cases are in the order of hundreds. This PR bumped them into thousands. With other slowing factors like MSAN/TSAN, the time error became observable to the test case.

I'm still trying to figure out why `ExecCtx` is shared. Might end up having another PR fixing it.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25738#-:-MZJyu_y0BNdYYxb5gij:b-hashow)* status: all files reviewed, 6 unresolved discussions (waiting on @markdroth, @nicolasnoble, and @veblush)

___
*[include/grpc/impl/codegen/port_platform.h, line 625 at r5](https://reviewable.io/reviews/grpc/grpc/25738#-MZJAYAC9ngOUlKtiKDc:-MZJRstQDaq4UleXCLLU:b-krvru3) ([raw file](https://github.com/grpc/grpc/blob/7ccc678b891ab2192655037c3a139403a6bca20d/include/grpc/impl/codegen/port_platform.h#L625)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Shouldn't this be something like `__SANITIZE_MEMORY__`?  I think `__SANITIZE_ADDRESS__` is specific to asan.  But I don't know what sets this macro.

Actually, why do we need this at all?  It looks like we already have code that we can use to detect msan:

https://github.com/grpc/grpc/blob/9977bef14b5eaf48406f2a3996204f56cb5dea56/test/core/util/test_config.cc#L95

If we do need this for some reason, please have @nicolasnoble review the change to this file to make sure this will work right in a portable way.
</blockquote></details>

Good idea! Changed to use existing method `grpc_test_slowdown_factor`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 36 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYR7aew3JBnvllmy5YO:-MZJUtLz3e_7adY2PFy8:b-7immee) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think it didn't work on all platforms.  If the tests are all passing now, then this restriction may have gone away.  Please confirm with @veblush; if it has, I'd prefer to use the absl API.
</blockquote></details>

Pinged Esun offline.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2539 at r2](https://reviewable.io/reviews/grpc/grpc/25738#-MYRBFtf85jsSkBuH7wJ:-MZJSpiq6adSDw6vLoN4:b-66au4z) ([raw file](https://github.com/grpc/grpc/blob/97f041a26f9edab5513ee1556b89b90570bfe309/test/cpp/end2end/xds_end2end_test.cc#L2539)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is it possible that this bug was the reason that you needed to switch to the cycle counter clock in the FI filter?  Now that we've fixed this, is that change still needed?
</blockquote></details>

I don't think that's the case, the `t0` is captured before the loop start. So, the measured elapsed_time will be longer. It actually hides the `ExecCtx::Now()` issue until we run a large number of RPCs concurrently.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2599 at r5](https://reviewable.io/reviews/grpc/grpc/25738#-MZJBvDUA996ek5A04xx:-MZJSiTH3uJ5nhdBgnVU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7ccc678b891ab2192655037c3a139403a6bca20d/test/cpp/end2end/xds_end2end_test.cc#L2599)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment can go away now.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9335 at r5](https://reviewable.io/reviews/grpc/grpc/25738#-MZJDmYY1Ss0xxY-h71q:-MZJTMUP5pieg4-htFcy:bb7pglz) ([raw file](https://github.com/grpc/grpc/blob/7ccc678b891ab2192655037c3a139403a6bca20d/test/cpp/end2end/xds_end2end_test.cc#L9335)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Pre-existing problem, not related to this PR, but please change the leading `K` here to be lower-case.
</blockquote></details>

They look so similar, good catch, done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10236 at r5](https://reviewable.io/reviews/grpc/grpc/25738#-MZJEeTwCeBNFzPf9HM7:-MZJTxN061rMHgBV9pWq:bugclfz) ([raw file](https://github.com/grpc/grpc/blob/7ccc678b891ab2192655037c3a139403a6bca20d/test/cpp/end2end/xds_end2end_test.cc#L10236)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of a specialized hack for msan here, can we use the existing `grpc_test_slowdown_factor()` code?

https://github.com/grpc/grpc/blob/9977bef14b5eaf48406f2a3996204f56cb5dea56/test/core/util/test_config.cc#L135

Note that we're already using `grpc_timeout_seconds_to_deadline()` when setting the deadlines for the RPCs, which takes the test slowdown factor into account:

https://github.com/grpc/grpc/blob/9977bef14b5eaf48406f2a3996204f56cb5dea56/test/cpp/end2end/xds_end2end_test.cc#L1899
https://github.com/grpc/grpc/blob/9977bef14b5eaf48406f2a3996204f56cb5dea56/test/core/util/test_config.cc#L140
</blockquote></details>

Ah, this is why the tests run much slower than the multiply result of timeouts. Using `grpc_test_slowdown_factor`.


<!-- Sent from Reviewable.io -->

2021-04-27 20:42 UTC, markdroth requested changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25738)* status: all files reviewed, 2 unresolved discussions (waiting on @lidizheng and @veblush)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 10236 at r5](https://reviewable.io/reviews/grpc/grpc/25738#-MZJEeTwCeBNFzPf9HM7:-MZK35io7E1767e4KaRe:bbb5u4a) ([raw file](https://github.com/grpc/grpc/blob/7ccc678b891ab2192655037c3a139403a6bca20d/test/cpp/end2end/xds_end2end_test.cc#L10236)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Ah, this is why the tests run much slower than the multiply result of timeouts. Using `grpc_test_slowdown_factor`.
</blockquote></details>

Super!  Please run 1000x again on RBE to make sure there are no new flakes with this approach.


<!-- Sent from Reviewable.io -->

2021-04-27 21:59 UTC, lidizheng commented
From the trace log, I can confirm that all RPCs are run on one single thread (or at least the fault injection filter is) (see [log in gpaste](https://paste.googleplex.com/4629992035057664). I think the log succeeded because the printing action of `gpr_log` covers the missing injected delay time or similar side effect.

Each thread will have only one `ExecCtx`, which stored in thread local storage.

https://github.com/grpc/grpc/blob/dc6948cf35d95a0bf7a9fcce0fa91e613dd05ca3/src/core/lib/iomgr/exec_ctx.h#L223

The `Now()` value will be valid until any other methods on the same thread calls `InvalidateNow()`.

https://github.com/grpc/grpc/blob/dc6948cf35d95a0bf7a9fcce0fa91e613dd05ca3/src/core/lib/iomgr/exec_ctx.h#L197

However, searching the code base, the `InvalidateNow()` won't be involved again for each RPC. It is usually called when spawning a new thread.

What do you think we should do about existing mechanism? @markdroth 
(Related https://github.com/grpc/grpc/issues/26079)

2021-04-27 22:28 UTC, markdroth commented
It's not surprising that all RPCs are running on the same thread, because they are all being started by the main thread in this test.  However, the fact that they are all being started in the same thread does not mean that they should all be started using the same `ExecCtx` object.  Each time the thread calls into C-core (which it must do once for each RPC it wants to start), there should be a new `ExecCtx` created.  It should be the one created in `grpc_call_start_batch()`:

https://github.com/grpc/grpc/blob/dc6948cf35d95a0bf7a9fcce0fa91e613dd05ca3/src/core/lib/surface/call.cc#L1981

That having been said, it now occurs to me that the FI filter is actually *not* being invoked before `grpc_call_start_batch()` returns, because it doesn't happen until after name resolution happens.  In other words, it's actually being kicked off not a result of the application starting the RPC, but rather as a result of the xDS communication completing.  The calls are being queued in the client channel code pending the resolver result, and then when the resolver result comes in, they're all being restarted from within the same thread, and *that* is when the FI filter is being called.  So I guess it's not surprising that they are all being started from the same thread.

I suggest the following experiment: Before you start sending RPCs, call `channel.WaitForConnected()` with some reasonable deadline.  That will ensure that name resolution completes and the channel has connected to at least one backend before you start sending RPCs.  Then you can start the async RPCs to test the FI filter.  In that scenario, name resolution will have completed before the RPCs are started, which means that the FI filter *will* actually be called from within `grpc_call_start_batch()`, which means that each call will use its own `ExecCtx`.

If the above works, then we can decide whether we're okay with this behavior for real production use or whether we need to do something about it.  Another approach might be to change the client channel code to call `InvalidateNow()` before it processes each queued RPC.

I do agree that this is fundamentally the same issue as #26079.  But I don't think that changing the FI code to use the cycle timer clock is the right solution.

2021-04-28 01:28 UTC, lidizheng commented
> ...The calls are being queued in the client channel code pending the resolver result, and then when the resolver result comes in, they're all being restarted from within the same thread, and that is when the FI filter is being called.

Without `WaitForConnected`, the flake rate is 3.7% for TSAN runs; with it, it passed 1000 TSAN runs. However, if I print the trace log, almost all RPCs are still being executed on the same thread. It's possible that `WaitForConnected` didn't entirely solved the shared context issue, but the error became undetectable by our tests.

> If the above works, then we can decide whether we're okay with this behavior for real production use or whether we need to do something about it.

I'm okay with either solution. The solution to fix #26079 will also fix this flake. So, we can merge the discussion to #26079 about when and where should we call `InvalidateNow()`.

---

1000 runs for "*Fault*": [opt](//source.cloud.google.com/results/invocations/28b86fa9-6698-4ab5-a2a1-198953faf8af), [msan-ongoing](//source.cloud.google.com/results/invocations/2c5192c6-7821-4aee-b5d3-5552d606c133), [tsan](//source.cloud.google.com/results/invocations/a8a2076a-9618-4374-aba5-7bca8ddc76f0), [ubsan](//source.cloud.google.com/results/invocations/e8b2815b-f80e-4f2d-beec-4304b9ab7126), [asan](//source.cloud.google.com/results/invocations/47c62e97-0337-4e98-ba49-5a2b9e398ca2)

2021-04-28 16:32 UTC, markdroth requested changes
It's not surprising that the RPCs are still hitting the FI filter in the same thread.  As I said before, now that they're no longer all queued waiting for the resolver result, the FI filter will actually be invoked when the RPCs are started from the main thread here in the test.  But the key question is not whether they are executed in the same thread; it's whether they're executed using the same `ExecCtx` instance.  Now that the FI filter is being run from inside of `grpc_call_start_batch()`, each RPC will have a different `ExecCtx` instance.

Anyway, this looks good, modulo a few minor remaining nits.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25738#-:-MZOIuBZ6wJemAkHHHQH:b11y1u6)* status: all files reviewed, 4 unresolved discussions (waiting on @lidizheng)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 10351 at r7](https://reviewable.io/reviews/grpc/grpc/25738#-MZOHcmbDhViPBT8zHTL:-MZOHcmbDhViPBT8zHTM:bu44tng) ([raw file](https://github.com/grpc/grpc/blob/6ecc5a81b4119f74ba389b6c18ad0f6d5b0d3b14/test/cpp/end2end/xds_end2end_test.cc#L10351)):*
> ```cpp
>   SetFilterConfig(http_fault);
>   // Allow the channel to connect to one backends, so the herd of queued RPCs
>   // won't be executed on the same thread causing millisecond level delay error.
> ```

It's not that they're running on the same thread; it's that they're running with the same `ExecCtx` instance, thus using the same cached value of "now".
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10353 at r7](https://reviewable.io/reviews/grpc/grpc/25738#-MZOIior8mu--Oikq-B4:-MZOIior8mu--Oikq-B5:bail4cs) ([raw file](https://github.com/grpc/grpc/blob/6ecc5a81b4119f74ba389b6c18ad0f6d5b0d3b14/test/cpp/end2end/xds_end2end_test.cc#L10353)):*
> ```cpp
>   // won't be executed on the same thread causing millisecond level delay error.
>   channel_->WaitForConnected(
>       grpc_timeout_milliseconds_to_deadline(kRpcTimeoutMilliseconds));
> ```

100s seems like a long delay here.  This really shouldn't take longer than 10s at the most.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10405 at r7](https://reviewable.io/reviews/grpc/grpc/25738#-MZOHgAB8CcxXLCXlGwe:-MZOHgAB8CcxXLCXlGwf:b2nreh6) ([raw file](https://github.com/grpc/grpc/blob/6ecc5a81b4119f74ba389b6c18ad0f6d5b0d3b14/test/cpp/end2end/xds_end2end_test.cc#L10405)):*
> ```cpp
>   SetFilterConfig(http_fault);
>   // Allow the channel to connect to one backends, so the herd of queued RPCs
>   // won't be executed on the same thread causing millisecond level delay error.
> ```

Same as above.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10407 at r7](https://reviewable.io/reviews/grpc/grpc/25738#-MZOIpee96H36pVLGIw1:-MZOIpee96H36pVLGIw2:b2nreh6) ([raw file](https://github.com/grpc/grpc/blob/6ecc5a81b4119f74ba389b6c18ad0f6d5b0d3b14/test/cpp/end2end/xds_end2end_test.cc#L10407)):*
> ```cpp
>   // won't be executed on the same thread causing millisecond level delay error.
>   channel_->WaitForConnected(
>       grpc_timeout_milliseconds_to_deadline(kRpcTimeoutMilliseconds));
> ```

Same as above.


<!-- Sent from Reviewable.io -->

2021-04-28 17:39 UTC, lidizheng commented
When I print the address of the `ExecCtx` object, it's the same across RPCs: https://paste.googleplex.com/4688416659734528

However, if we look closer, the `ExecCtx` object is reset properly: https://paste.googleplex.com/4688416659734528

Since `ExecCtx` object is created on the stack, I think the compiler happen to create it every time at the same spot. Without `WaitForConnected`, all RPCs will be executed in one of the `grpc_call_start_batch` invocations.

That means with `WaitForConnected`, we do solve the issue of sharing `ExecCtx` object (though they have the same address).

2021-04-28 17:46 UTC, lidizheng reviewed
Thanks for the review!

Confirmed what you said, my experiment above proved that we are using different `ExecCtx` instance if we first connect to one of the backends.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25738#-:-MZO_HUN3OMWemYrkRPt:bmc8tw2)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 10351 at r7](https://reviewable.io/reviews/grpc/grpc/25738#-MZOHcmbDhViPBT8zHTL:-MZOZNci7QTQQWh3IyRx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ecc5a81b4119f74ba389b6c18ad0f6d5b0d3b14/test/cpp/end2end/xds_end2end_test.cc#L10351)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not that they're running on the same thread; it's that they're running with the same `ExecCtx` instance, thus using the same cached value of "now".
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10353 at r7](https://reviewable.io/reviews/grpc/grpc/25738#-MZOIior8mu--Oikq-B4:-MZOZqt487bX2Zig0vNw:b-ex64ye) ([raw file](https://github.com/grpc/grpc/blob/6ecc5a81b4119f74ba389b6c18ad0f6d5b0d3b14/test/cpp/end2end/xds_end2end_test.cc#L10353)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

100s seems like a long delay here.  This really shouldn't take longer than 10s at the most.
</blockquote></details>

Done.

(Either 100s nor 10s should be reached. Since it is not the test subject here, I just set it to a number that if reached, something is seriously wrong.)
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10405 at r7](https://reviewable.io/reviews/grpc/grpc/25738#-MZOHgAB8CcxXLCXlGwe:-MZOZrDp6wq-swVpPpVx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ecc5a81b4119f74ba389b6c18ad0f6d5b0d3b14/test/cpp/end2end/xds_end2end_test.cc#L10405)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 10407 at r7](https://reviewable.io/reviews/grpc/grpc/25738#-MZOIpee96H36pVLGIw1:-MZOZrfQ4DThtwd9Qtco:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6ecc5a81b4119f74ba389b6c18ad0f6d5b0d3b14/test/cpp/end2end/xds_end2end_test.cc#L10407)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-28 18:56 UTC, markdroth approved these changes
Looks great!

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25738#-:-MZOpm0Y-WXlcvVB10Gh:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lidizheng)



<!-- Sent from Reviewable.io -->

2021-04-29 00:47 UTC, merged