Filterchainmatch
grpc/grpc pull request #25757
Opened 2021-03-18 13:07 UTC by yashykt

2021-03-23 18:31 UTC, markdroth requested changes
This looks like a great start!

My only really substantive comments are about how we're returning the filter chain info in the `LdsResponse` struct; it seems like we're actually returning the raw form (a list of `FilterChain`s) in addition to the new struct, but that raw form is never going to be used for anything else, so it seems a little pointless to have it there.

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 16 files at r1, 4 of 6 files at r2, 2 of 4 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757#-:-MWVL4f02bqBIh7KHnxJ:bb43y13)* status: all files reviewed, 55 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 97 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWV0rC81t-toX5oRr2i:-MWV0rC97bk4BPMq2-6I:bs227ew) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/transport/chttp2/server/chttp2_server.cc#L97)):*
> ```cpp
> 
>     void UpdateConnectionManager(
>         RefCountedPtr<grpc_server_config_fetcher::ConnectionManager> manager)
> ```

Please call this argument `connection_manager`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 721 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWV13NcAqEg9gE8Pgzx:-MWV13NcAqEg9gE8Pgzy:b-4hokec) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/transport/chttp2/server/chttp2_server.cc#L721)):*
> ```cpp
>       grpc_error* error = GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>           "No ConnectionManager configured. Closing connection.");
>       endpoint_cleanup(error);
> ```

Need to return after this.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 721 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWV1g8Z40NGQqxdDtR2:-MWV1g8Z40NGQqxdDtR3:ba60vgk) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/transport/chttp2/server/chttp2_server.cc#L721)):*
> ```cpp
>       grpc_error* error = GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>           "No ConnectionManager configured. Closing connection.");
>       endpoint_cleanup(error);
> ```

I think this also needs to destroy `args`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 723 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWV1HRu3pEKS8cmQWmN:-MWV1HRu3pEKS8cmQWmO:bwe6y8g) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/transport/chttp2/server/chttp2_server.cc#L723)):*
> ```cpp
>       endpoint_cleanup(error);
>     }
>     // TODO(yashykt): Maybe combine the following two arg modifiers into a
> ```

Unfortunately, doesn't look like there's an easy way to do this.  Although the second one will probably go away once insecure builds are gone.
___
*[src/core/ext/xds/xds_api.h, line 341 at r2](https://reviewable.io/reviews/grpc/grpc/25757#-MWQMDDD7hj5ffMGorXV:-MWQMDDD7hj5ffMGorXW:b-cdpveh) ([raw file](https://github.com/grpc/grpc/blob/ba747d244d8be44d173b583391ab19558a0de7d3/src/core/ext/xds/xds_api.h#L341)):*
> ```objc
>     };
> 
>     using SourcePortsMap =
> ```

It might be helpful to have an overall comment here indicating the high-level view of this data structure.  Something like this (if I understand correctly):

```
A multi-level map used to determine which filter chain to use for a given incoming connection.
Determining the right filter chain for a given connection checks the following properties, in order:
- destination port (never matched, so not present in map)
- destination IP range
- server name (never matched, so not present in map)
- transport protocol (allows only "raw_buffer" or unset, prefers the former)
- application protocol (never matched, so not present in map)
- connection source type
- source IP
- source port
```
___
*[src/core/ext/xds/xds_api.h, line 354 at r2](https://reviewable.io/reviews/grpc/grpc/25757#-MWQO1Fi83RJGVhDegLh:-MWQO1Fi83RJGVhDegLi:bbwakfw) ([raw file](https://github.com/grpc/grpc/blob/ba747d244d8be44d173b583391ab19558a0de7d3/src/core/ext/xds/xds_api.h#L354)):*
> ```objc
>     };
>     using SourceIpMap = std::map<std::string, SourceIp>;
>     using SourceTypesArray = std::array<SourceIpMap, 3>;
> ```

Suggest calling this `ConnectionSourceTypesArray`, to better match the enum type name used in `FilterChainMatch` above.
___
*[src/core/ext/xds/xds_api.h, line 383 at r2](https://reviewable.io/reviews/grpc/grpc/25757#-MWQMkJ846pJKm1CUNFl:-MWQMkJ846pJKm1CUNFm:bhwtym8) ([raw file](https://github.com/grpc/grpc/blob/ba747d244d8be44d173b583391ab19558a0de7d3/src/core/ext/xds/xds_api.h#L383)):*
> ```objc
>     // host:port listening_address set when type is kTcpListener
>     std::string address;
>     std::vector<FilterChain> filter_chains;
> ```

Do we still need this field if we're returning `destination_ip_map`?  Doesn't that field contain the same thing, and won't the code that uses these fields only look at that one?
___
*[src/core/ext/xds/xds_api.h, line 346 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUkO1CCMqtTchqyqLo:-MWUkO1CCMqtTchqyqLp:b-itajph) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_api.h#L346)):*
> ```objc
>     };
> 
>     struct FilterChainDataSharedPtr {
> ```

Having a separate struct just to hold a shared_ptr seems a little cumbersome.  It looks like the reason it's here is to allow comparisons for the overall struct to work correctly.  But I wonder if we can avoid this by not using a shared_ptr to begin with.  I'm thinking that we could instead do something like this:

```
struct SourcePortsMap {
  // Stores the data entries.
  std::vector<FilterChainData> storage;
  // Map from ports to entries in the storage field.
  std::map<uint16_t, FilterChainData*> map;
};
```

This both cleans up this struct and avoids the locking overhead of shared_ptr.
___
*[src/core/ext/xds/xds_api.cc, line 2246 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUnSEcCm62SpxKh2Um:-MWUnSEcCm62SpxKh2Un:b-od9mk3) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_api.cc#L2246)):*
> ```cpp
>                                            ports_map, 0);
>   } else {
>     for (const auto& port : filter_chain_match.source_ports) {
> ```

Please change `auto&` to `uint32_t`.
___
*[src/core/ext/xds/xds_api.cc, line 2310 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUuGzAEgkqvPxaUtow:-MWUuDPEAQxr0Vz13l4X:b-84wgo) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_api.cc#L2310)):*
> ```cpp
>   return AddFilterChainDataForSourceIpRange(
>       filter_chain_match, std::move(filter_chain_data),
>       &destination_ip->source_types_array[static_cast<int>(
> ```

Is the cast actually needed here?
___
*[src/core/ext/xds/xds_api.cc, line 2332 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUoUtN0nnSZQBvTbbk:-MWUoUtN0nnSZQBvTbbl:b-savtm5) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_api.cc#L2332)):*
> ```cpp
>         filter_chain_data,
>     XdsApi::LdsUpdate::DestinationIp* destination_ip) {
>   auto& transport_protocol = filter_chain_match.transport_protocol;
> ```

`std::string&`
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 70 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUyYzv0s6HHI6tr16W:-MWUyYzv0s6HHI6tr16X:b-rm5u1w) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L70)):*
> ```cpp
>  private:
>   struct CertificateProviders {
>     RefCountedPtr<grpc_tls_certificate_provider> root;
> ```

Why do we need to save our own refs to the root and instance providers?  Doesn't `XdsCertificateProvider` already internally hold refs to those?
___
*[src/core/ext/xds/xds_serv [...]

2021-03-24 08:06 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: all files reviewed, 55 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 162 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUvIiD-FbUXjpwiCR9:-MWW1nQ51yCPumvvJBhF:bwrtjw7) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L162)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about just using `grpc_parse_uri()` here?
</blockquote></details>

We want to compare on the port separately and not as part of the `grpc_resolved_address`, so this was just convenient.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 169 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUuJgD8qh4xwhnE-Ot:-MWW2HRXCXlvcXj8WTTU:bv9v380) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L169)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Are the casts actually needed here?
</blockquote></details>

Yes, enum classes cannot be converted to int without an explicit cast. (I could use C style enums though but this seemed fine)
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 203 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUw-Nv-Np-DUJHypoI:-MWW30q-CtLULObzYxUP:b-ucfknh) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L203)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to first check that `destination_uri.ok()` is true.
</blockquote></details>

Thanks!
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 209 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUw4_Z3cMzRJUtKDwt:-MWW31ey0AA5c1yirIK2:b78a1a6) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L209)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about just using `grpc_parse_uri()` here?
</blockquote></details>

I'm doing it this way mainly to avoid the port being added to the address
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 320 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUy36B-vuHApI_ZaHu:-MWW4JPq-qXIhlC7WL1W:b-2uv4bs) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L320)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why are we removing the credentials from args if they're not XdsCreds?  Won't this break the ability to use xDS in the server without using XdsCreds?  I think we still want to support that.

Let's make sure we have a test for this case.
</blockquote></details>

This is not removing the credentials arg. It is removing the filter chain manager arg. (It's an artifact from a previous code iteration.) Removing. 

Note that we do test an xDS enabled server without using Xds Creds. `XdsEnabledServerTest` does that.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 431 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWV-OpUE9eyjXBUH1YG:-MWW6yOm5B11YJHC8ZNi:b-mgrcde) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L431)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can be written a little more clearly by inverting the second condition:

```
if (filter_chain_match_manager_ == nullptr ||
    listener.destination_ip_map !=
        filter_chain_match_manager_->destination_ip_map() ||
    listener.default_filter_chain !=
        filter_chain_match_manager_->default_filter_chain()) {
```
</blockquote></details>

I get an error of the form 
```
src/core/ext/xds/xds_server_config_fetcher.cc:427:43: error: invalid operands to binary expression ('absl::optional<FilterChain>' and 'const absl::optional<XdsApi::LdsUpdate::FilterChain>')
            listener.default_filter_chain !=
```

absl::optional does not like operator!= here.
___
*[src/core/lib/gprpp/atomic.h, line 84 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUqVlp5IKyLg0n7nbO:-MWW7u7B5nP0mbzLg2m_:bkuxxqi) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/lib/gprpp/atomic.h#L84)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why was this change necessary?
</blockquote></details>

This was a very strange error, and I sequentially reverted different parts of my code to figure out what exactly was causing this.

So, the error itself is this -
```In file included from /usr/include/c++/4.9/atomic:41:0,
                 from /var/local/git/grpc/src/core/lib/gprpp/atomic.h:24,
                 from /var/local/git/grpc/src/core/lib/gprpp/arena.h:38,
                 from /var/local/git/grpc/src/core/lib/channel/channel_stack.h:57,
                 from /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel_channelz.h:27,
                 from /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.h:24,
                 from /var/local/git/grpc/src/core/ext/xds/xds_client.cc:35:
/usr/include/c++/4.9/bits/atomic_base.h: In member function 'bool grpc_core::Atomic<T>::IncrementIfNonzero(grpc_core::MemoryOrder) [with T = long int]':
/usr/include/c++/4.9/bits/atomic_base.h:538:70: error: failure memory model cannot be stronger than success memory model for '__atomic_compare_exchange'
  return __atomic_compare_exchange_n(&_M_i, &__i1, __i2, 1, __m1, __m2);```

and this seems to happen only with gcc-4.9. With some google search, turns out other folks have run into the same error (https://bugzilla.mozilla.org/show_bug.cgi?id=1029245 for example).

With all my code reversion, I narrowed it down some struct additions to xds_api.h. It looks like when the code structure gets complicated enough, gcc-4.9 fails to realize that we never use `IncrementIfNonzero` with a memory model other than `ACQUIRE`. Using a model other than ACQUIRE would probably be wrong in the first place for the manner that we are using it in, so I just removed the parameter. We can probably revisit this later if we need to do something special here. I suspect we will not need to.
```

___
*[src/core/lib/iomgr/sockaddr_utils.cc, line 383 at r2](https://reviewable.io/reviews/grpc/grpc/25757#-MWQTqdb8sppwPA5G8SM:-MWWAPDh1h0-56NTN8jx:b-viuli3) ([raw file](https://github.com/grpc/grpc/blob/ba747d244d8be44d173b583391ab19558a0de7d3/src/core/lib/iomgr/sockaddr_utils.cc#L383)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These `memcmp()`s are going to fail if the ports differ.  I guess that's okay, though, since we'll only tend to use this in cases where the ports are the same.

This makes me wonder whether `grpc_resolved_address`, which does include a port, is really the right type on which to be providing these functions.  In principle, is seems like these operations should be done on only the addresses, not the ports.  But I guess we don't have a better type on which to provide these methods, so I guess this is okay.
</blockquote></details>

`sin_addr` does not include the port, so it should not fail. The same for `sin6_addr`.

But, I do agree that `grpc_resolved_address` is not ideal here. I was looking for a more concise type and we may want to add that in the future. For now, `grpc_resolved_address` and its utility functions are convenient :)


<!-- Sent from Reviewable.io -->

2021-03-24 09:34 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: 8 of 17 files reviewed, 54 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 97 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWV0rC81t-toX5oRr2i:-MWYUNZcAmkp54zseyc5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/transport/chttp2/server/chttp2_server.cc#L97)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this argument `connection_manager`.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 721 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWV13NcAqEg9gE8Pgzx:-MWYUPEI2ocy9cUIv8Wd:bnhtqu4) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/transport/chttp2/server/chttp2_server.cc#L721)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to return after this.
</blockquote></details>

You are right. Thanks!
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 721 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWV1g8Z40NGQqxdDtR2:-MWYUR5F5ff07Ag3o_gR:b-cmt4a6) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/transport/chttp2/server/chttp2_server.cc#L721)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this also needs to destroy `args`.
</blockquote></details>

Done! Thanks!
___
*[src/core/ext/xds/xds_api.h, line 341 at r2](https://reviewable.io/reviews/grpc/grpc/25757#-MWQMDDD7hj5ffMGorXV:-MWYUhhp5m4PoNCrHP0E:b-4nmb5k) ([raw file](https://github.com/grpc/grpc/blob/ba747d244d8be44d173b583391ab19558a0de7d3/src/core/ext/xds/xds_api.h#L341)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It might be helpful to have an overall comment here indicating the high-level view of this data structure.  Something like this (if I understand correctly):

```
A multi-level map used to determine which filter chain to use for a given incoming connection.
Determining the right filter chain for a given connection checks the following properties, in order:
- destination port (never matched, so not present in map)
- destination IP range
- server name (never matched, so not present in map)
- transport protocol (allows only "raw_buffer" or unset, prefers the former)
- application protocol (never matched, so not present in map)
- connection source type
- source IP
- source port
```
</blockquote></details>

I like it. Added the comment.
___
*[src/core/ext/xds/xds_api.h, line 354 at r2](https://reviewable.io/reviews/grpc/grpc/25757#-MWQO1Fi83RJGVhDegLh:-MWYVWh1CJxp659NAc2R:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ba747d244d8be44d173b583391ab19558a0de7d3/src/core/ext/xds/xds_api.h#L354)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `ConnectionSourceTypesArray`, to better match the enum type name used in `FilterChainMatch` above.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 383 at r2](https://reviewable.io/reviews/grpc/grpc/25757#-MWQMkJ846pJKm1CUNFl:-MWYVXFo0gzmYanHIRsK:b-px3n4g) ([raw file](https://github.com/grpc/grpc/blob/ba747d244d8be44d173b583391ab19558a0de7d3/src/core/ext/xds/xds_api.h#L383)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Do we still need this field if we're returning `destination_ip_map`?  Doesn't that field contain the same thing, and won't the code that uses these fields only look at that one?
</blockquote></details>

I only intended to use it for logging purposes. I thought that this struct has a limited lifetime (until the update is propagated to the config fetcher). I didn't realize that this is actually cached by the xds_client. Removed this, and added a logging function for the built nested map
___
*[src/core/ext/xds/xds_api.h, line 346 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUkO1CCMqtTchqyqLo:-MWYUlcu6Jz4_Xa-oc3J:brivaf5) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_api.h#L346)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Having a separate struct just to hold a shared_ptr seems a little cumbersome.  It looks like the reason it's here is to allow comparisons for the overall struct to work correctly.  But I wonder if we can avoid this by not using a shared_ptr to begin with.  I'm thinking that we could instead do something like this:

```
struct SourcePortsMap {
  // Stores the data entries.
  std::vector<FilterChainData> storage;
  // Map from ports to entries in the storage field.
  std::map<uint16_t, FilterChainData*> map;
};
```

This both cleans up this struct and avoids the locking overhead of shared_ptr.
</blockquote></details>

Yes, the reason for the separate struct is to allow for comparison. As discussed on GVC, accessing the shared_ptr is cheap and it makes the build algorithm really simple and straightforward compared to using a vector for storage (which would require a separate pass after building to remove the unused entries). Keeping the shared_ptr approach for now
___
*[src/core/ext/xds/xds_api.cc, line 2246 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUnSEcCm62SpxKh2Um:-MWYZtrP1ci-rIJSYCmk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_api.cc#L2246)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please change `auto&` to `uint32_t`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2310 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUuGzAEgkqvPxaUtow:-MWYRqnW1f-SjlLRv0We:b-tj3prd) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_api.cc#L2310)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is the cast actually needed here?
</blockquote></details>

Yes, enum classes are not implicitly convertible to int
___
*[src/core/ext/xds/xds_api.cc, line 2332 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUoUtN0nnSZQBvTbbk:-MWYW0UI0Yb7u-Wm8FTq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_api.cc#L2332)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::string&`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 70 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUyYzv0s6HHI6tr16W:-MWYSHds9lwMFx5_jMwp:bun2ndc) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why do we need to save our own refs to the root and instance providers?  Doesn't `XdsCertificateProvider` already internally hold refs to those?
</blockquote></details>

No, it just takes a ref to their distributors.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 114 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUr6VP5q0f18D8dQSm:-MWYW2wV-soCdxANBr9x:b-xc6aa0) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L114)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should not be a reference, and `const` is unnecessary.  Using a const reference here winds up triggering case 8 as described in https://abseil.io/tips/101.  For more details, see https://abseil.io [...]

2021-03-24 09:39 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: 8 of 17 files reviewed, 54 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 157 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUrraR3NrO3uoLEqNH:-MWYaXcP6pIMvrgomeBi:b-7pdx6d) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L157)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to check that `source_uri.ok()` is true first.
</blockquote></details>

Done. Thanks!
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 209 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUw4_Z3cMzRJUtKDwt:-MWY_hU0DH4NCSgrqMJk:b-whi6tw) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L209)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

well, actually, in this case, we don't need the port so we should just use `grpc_parse_uri`. Thanks!
</blockquote></details>

no, we still need the host to pass to the other function. So SplitHostPort remains convenient here


<!-- Sent from Reviewable.io -->

2021-03-24 10:23 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: 8 of 17 files reviewed, 54 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 8610 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWVK_mF48ZUx2XQDLs5:-MWYkcOn6v1UIh0GKF-H:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/test/cpp/end2end/xds_end2end_test.cc#L8610)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We'll want these error messages to be a bit more specific.  They should at least indicate which filter chain entry (by index) caused the problem.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-24 10:28 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: 8 of 17 files reviewed, 54 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 320 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUy36B-vuHApI_ZaHu:-MWYksVdBmpdhhpLMsky:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L320)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

This is not removing the credentials arg. It is removing the filter chain manager arg. (It's an artifact from a previous code iteration.) Removing. 

Note that we do test an xDS enabled server without using Xds Creds. `XdsEnabledServerTest` does that.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 431 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWV-OpUE9eyjXBUH1YG:-MWYkxst-hhIyITlIakp:b-uaikyx) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L431)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I get an error of the form 
```
src/core/ext/xds/xds_server_config_fetcher.cc:427:43: error: invalid operands to binary expression ('absl::optional<FilterChain>' and 'const absl::optional<XdsApi::LdsUpdate::FilterChain>')
            listener.default_filter_chain !=
```

absl::optional does not like operator!= here.
</blockquote></details>

maybe it expects the operator!= to be implemented
___
*[src/core/lib/gprpp/atomic.h, line 84 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUqVlp5IKyLg0n7nbO:-MWYlFsWCZg5US_YVRxm:b5w08bo) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/lib/gprpp/atomic.h#L84)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

This was a very strange error, and I sequentially reverted different parts of my code to figure out what exactly was causing this.

So, the error itself is this -
```In file included from /usr/include/c++/4.9/atomic:41:0,
                 from /var/local/git/grpc/src/core/lib/gprpp/atomic.h:24,
                 from /var/local/git/grpc/src/core/lib/gprpp/arena.h:38,
                 from /var/local/git/grpc/src/core/lib/channel/channel_stack.h:57,
                 from /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel_channelz.h:27,
                 from /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.h:24,
                 from /var/local/git/grpc/src/core/ext/xds/xds_client.cc:35:
/usr/include/c++/4.9/bits/atomic_base.h: In member function 'bool grpc_core::Atomic<T>::IncrementIfNonzero(grpc_core::MemoryOrder) [with T = long int]':
/usr/include/c++/4.9/bits/atomic_base.h:538:70: error: failure memory model cannot be stronger than success memory model for '__atomic_compare_exchange'
  return __atomic_compare_exchange_n(&_M_i, &__i1, __i2, 1, __m1, __m2);```

and this seems to happen only with gcc-4.9. With some google search, turns out other folks have run into the same error (https://bugzilla.mozilla.org/show_bug.cgi?id=1029245 for example).

With all my code reversion, I narrowed it down some struct additions to xds_api.h. It looks like when the code structure gets complicated enough, gcc-4.9 fails to realize that we never use `IncrementIfNonzero` with a memory model other than `ACQUIRE`. Using a model other than ACQUIRE would probably be wrong in the first place for the manner that we are using it in, so I just removed the parameter. We can probably revisit this later if we need to do something special here. I suspect we will not need to.


</blockquote></details>

(continuing previous comment.. bad formatting issues)
and this seems to happen only with gcc-4.9. With some google search, turns out other folks have run into the same error (https://bugzilla.mozilla.org/show_bug.cgi?id=1029245 for example).
 
With all my code reversion, I narrowed it down some struct additions to xds_api.h. It looks like when the code structure gets complicated enough, gcc-4.9 fails to realize that we never use `IncrementIfNonzero` with a memory model other than `ACQUIRE`. Using a model other than ACQUIRE would probably be wrong in the first place for the manner that we are using it in, so I just removed the parameter. We can probably revisit this later if we need to do something special here. I suspect we will not need to.


<!-- Sent from Reviewable.io -->

2021-03-24 15:50 UTC, markdroth requested changes
This looks really good!  My only remaining significant comments are about cleaning up the data structures in xds_api.h.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 9 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757#-:-MWZvQ2X9IhMlUffTeUo:b-fzpplr)* status: all files reviewed, 13 unresolved discussions (waiting on @soheilhy and @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 279 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZlR763ikKDqaVMNgC:-MWZlR763ikKDqaVMNgD:b-fqztvw) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L279)):*
> ```objc
>     };
> 
>     struct FilterChain {
> ```

This struct is no longer needed outside of the .cc file, so I suggest moving it there.

We'll need to leave `ConnectionSourceType` and `FilterChainData` here, since they're used below.
___
*[src/core/ext/xds/xds_api.h, line 309 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZnZoO0mOLAbunOsEe:-MWZnZoO0mOLAbunOsEf:bz3teki) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L309)):*
> ```objc
>         std::vector<std::string> application_protocols;
> 
>         bool operator==(const FilterChainMatch& other) const {
> ```

These two methods are probably not needed anymore once this struct moves to the .cc file.
___
*[src/core/ext/xds/xds_api.h, line 335 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZo_Qt7s_gUTBrX9l1:-MWZo_Qt7s_gUTBrX9l2:b-c5h36s) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L335)):*
> ```objc
> 
>         std::string ToString() const;
>       } filter_chain_data;
> ```

When you move this struct to the .cc file, consider making this field a `shared_ptr<>`.  That way, you can just grab a ref when populating the new data structure, without having to make any copies.
___
*[src/core/ext/xds/xds_api.h, line 352 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZlDB_7XXzxJ9WR_rx:-MWZlDBa5l18sccKAhaC:bi8je5p) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L352)):*
> ```objc
>     };
> 
>     // A multi-level map used to determine which filter chain to use for a given
> ```

Please move this comment above `FilterChainDataSharedPtr`, since that type is part of this data structure too.

Actually, would it make sense to move all of these types into a nested struct, so that it's clear that they're all related?
___
*[src/core/ext/xds/xds_api.h, line 359 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZlsIC48FB4pt8-KR4:-MWZlsIC48FB4pt8-KR5:b-spdcc3) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L359)):*
> ```objc
>     // - server name (never matched, so not present in map)
>     // - transport protocol (allows only "raw_buffer" or unset, prefers the
>     // former)
> ```

Please indent this word two spaces, to line up with the text above.
___
*[src/core/ext/xds/xds_api.h, line 409 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZm5AO04E7xLa2YI6i:-MWZm5APDGe_pQozgAIo:b-5z65r4) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L409)):*
> ```objc
>     std::string address;
>     DestinationIpMap destination_ip_map;
>     absl::optional<FilterChain> default_filter_chain;
> ```

I think this can be `FilterChainData`, since it doesn't need any of the fields from `FilterChainMatch`.
___
*[src/core/ext/xds/xds_api.cc, line 682 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZoAGT9-foV8DBrkga:-MWZoAGT9-foV8DBrkgb:b-tkqhfs) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.cc#L682)):*
> ```cpp
>               absl::StrCat("filter_chain_match={",
>                            absl::StrJoin(filter_chain_match_content, ", "),
>                            "}, ", source_port_pair.second.data->ToString()));
> ```

I think we don't need the comma after the close-brace here, since we'll add the commas in `absl::StrJoin()` below.
___
*[src/core/ext/xds/xds_api.cc, line 2276 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZponN9QyloXriyRc5:-MWZponN9QyloXriyRc6:buzdk9m) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.cc#L2276)):*
> ```cpp
> 
> grpc_error* AddFilterChainDataForSourcePort(
>     const XdsApi::LdsUpdate::FilterChain::FilterChainMatch& filter_chain_match,
> ```

How about just passing in the `FilterChain` struct, combining these first two parameters?

Same for most of these helper functions.
___
*[src/core/ext/xds/xds_api.cc, line 2470 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZqNPj5PKgK_zXaU4-:-MWZqNPj5PKgK_zXaU40:bmi1n57) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.cc#L2470)):*
> ```cpp
> 
> grpc_error* BuildFilterChainMatchStructure(
>     const std::vector<XdsApi::LdsUpdate::FilterChain> filter_chains,
> ```

This should be a reference to avoid an unnecessary copy.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 70 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUyYzv0s6HHI6tr16W:-MWZqp2I3PtILojop01W:b5wyrkk) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L70)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

No, it just takes a ref to their distributors.
</blockquote></details>

Okay.  Please add a comment about that.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 431 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWV-OpUE9eyjXBUH1YG:-MWZsPY_63gEXVUugCcX:b-ydvl4y) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L431)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

maybe it expects the operator!= to be implemented
</blockquote></details>

Ah, right -- we're not implementing `!=` for these structs.  Okay.
___
*[src/core/lib/gprpp/atomic.h, line 84 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUqVlp5IKyLg0n7nbO:-MWZv4rM8eu5LoOTF5Xb:be1kgdd) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/lib/gprpp/atomic.h#L84)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

(continuing previous comment.. bad formatting issues)
and this seems to happen only with gcc-4.9. With some google search, turns out other folks have run into the same error (https://bugzilla.mozilla.org/show_bug.cgi?id=1029245 for example).
 
With all my code reversion, I narrowed it down some struct additions to xds_api.h. It looks like when the code structure gets complicated enough, gcc-4.9 fails to realize that we never use `IncrementIfNonzero` with a memory model other than `ACQUIRE`. Using a model other than ACQUIRE would probably be wrong in the first place for the manner that we are using it in, so I just removed the parameter. We can probably revisit this later if we need to do something special here. I suspect we will not need to.

</blockquote></details>

Okay.  This looks fine to me, but just to be safe, let's ask @soheilhy to make sure there are no hidden gotchas here.
___
*[test/core/iomgr/sockaddr_utils_test.cc, line 18 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZssZACfcbgHmhzYJ_:-MWZssZB7npBjq9UDd2d:b-deyevk) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/test/core/iomgr/sockaddr_utils_test.cc#L18)):*
> ```cpp
> 
> // With the addition of a libuv endpoint, sockaddr.h now includes uv.h when
> //   using that endpoint. Because  [...]

2021-03-24 16:04 UTC, soheilhy reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: all files reviewed, 13 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/lib/gprpp/atomic.h, line 84 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUqVlp5IKyLg0n7nbO:-MWZy3gu8c6Au9jsnYRC:b-usfoh1) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/lib/gprpp/atomic.h#L84)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  This looks fine to me, but just to be safe, let's ask @soheilhy to make sure there are no hidden gotchas here.
</blockquote></details>

Thanks for checking. I have no objection.

That error should only show up if `load_order` is an invalid ordering with respect to failures.  Using `ACQUIRE` is safe but it's unnecessary for some cases that have a fast path on `cmpxchg` failure. That's why there was an option to set this.  If there are currently no user of this API, it's probably not as useful as we thought it would be.


<!-- Sent from Reviewable.io -->

2021-03-24 20:54 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: 13 of 17 files reviewed, 13 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 279 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZlR763ikKDqaVMNgC:-MW_zvBs8VVw4I2bMBuQ:bhwbua3) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L279)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This struct is no longer needed outside of the .cc file, so I suggest moving it there.

We'll need to leave `ConnectionSourceType` and `FilterChainData` here, since they're used below.
</blockquote></details>

Right, moved it.
___
*[src/core/ext/xds/xds_api.h, line 309 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZnZoO0mOLAbunOsEe:-MWa-KiT9Uyg2Vmrk64d:bpmje50) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L309)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two methods are probably not needed anymore once this struct moves to the .cc file.
</blockquote></details>

true for operator== but the `ToString()` method is still being used
___
*[src/core/ext/xds/xds_api.h, line 335 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZo_Qt7s_gUTBrX9l1:-MWa-Tg_9Nx2vvYSUWoX:bohqzsr) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L335)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

When you move this struct to the .cc file, consider making this field a `shared_ptr<>`.  That way, you can just grab a ref when populating the new data structure, without having to make any copies.
</blockquote></details>

Agreed, done.
___
*[src/core/ext/xds/xds_api.h, line 352 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZlDB_7XXzxJ9WR_rx:-MWa-b5cC7SfkhZYTSse:bqvtst8) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L352)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this comment above `FilterChainDataSharedPtr`, since that type is part of this data structure too.

Actually, would it make sense to move all of these types into a nested struct, so that it's clear that they're all related?
</blockquote></details>

I like that suggestion. Adopted it. Moved them under `FilterChainMap`
___
*[src/core/ext/xds/xds_api.h, line 359 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZlsIC48FB4pt8-KR4:-MWa-ggiCjd5q1CLTDHa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L359)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please indent this word two spaces, to line up with the text above.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 409 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZm5AO04E7xLa2YI6i:-MWa-iAH5q1WMf02kGzm:b-owisu5) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.h#L409)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can be `FilterChainData`, since it doesn't need any of the fields from `FilterChainMatch`.
</blockquote></details>

You are right. Done!
___
*[src/core/ext/xds/xds_api.cc, line 682 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZoAGT9-foV8DBrkga:-MW_vY1Y03BlySNOXWD8:bfzd58j) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.cc#L682)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we don't need the comma after the close-brace here, since we'll add the commas in `absl::StrJoin()` below.
</blockquote></details>

Note that we are adding `source_port_pair.second.data->ToString()`after the comma.  (FilterChainData, but not mentioning FilterChainData to avoid user confusion since the proto does not have that) 
___
*[src/core/ext/xds/xds_api.cc, line 2276 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZponN9QyloXriyRc5:-MWa-qEkAvhCk62SPoL6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.cc#L2276)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about just passing in the `FilterChain` struct, combining these first two parameters?

Same for most of these helper functions.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2470 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZqNPj5PKgK_zXaU4-:-MW_yG3x0I7OAYLXAlW3:b6zrrk4) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.cc#L2470)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be a reference to avoid an unnecessary copy.
</blockquote></details>

Good catch!
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 70 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUyYzv0s6HHI6tr16W:-MWa-rHsEefHV-b6NO7b:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/ext/xds/xds_server_config_fetcher.cc#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  Please add a comment about that.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/atomic.h, line 84 at r4](https://reviewable.io/reviews/grpc/grpc/25757#-MWUqVlp5IKyLg0n7nbO:-MW_yapMAOoJG_he3DWt:b2nhb2c) ([raw file](https://github.com/grpc/grpc/blob/4832ab5512eac98af08a1b0f9cba4dd4e5068652/src/core/lib/gprpp/atomic.h#L84)):*
<details><summary><i>Previously, soheilhy (Soheil Hassas Yeganeh) wrote…</i></summary><blockquote>

Thanks for checking. I have no objection.

That error should only show up if `load_order` is an invalid ordering with respect to failures.  Using `ACQUIRE` is safe but it's unnecessary for some cases that have a fast path on `cmpxchg` failure. That's why there was an option to set this.  If there are currently no user of this API, it's probably not as useful as we thought it would be.
</blockquote></details>

Ack
___
*[test/core/iomgr/sockaddr_utils_test.cc, line 18 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZssZACfcbgHmhzYJ_:-MW_ykwc60LJt1EUEvpC:b6ms5mi) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/test/core/iomgr/sockaddr_utils_test.cc#L18)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The rest of this comment doesn't need to be indented anymore.
</blockquote></details>

I usually just leave it to clang-format to figure out the right thing to do :)
___
*[test/core/iomgr/sockaddr_utils_test.cc, line 166 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZtGBLBL8OoRgWx1jF:-MWa-tfDDYqzMUubFd9d:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/test/core/iomgr/sockaddr_utils_test.cc#L166)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `true` and `false` instead of `0` and `1` for the `normalize` argument.

Same throughout.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-24 22:30 UTC, markdroth requested changes
This is pretty close now!  Remaining comments are mostly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 4 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757#-:-MWaM2nt-xWLhjnWBrjN:b-mu8kxm)* status: all files reviewed, 12 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 286 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaC8qQCDtXKOtrWZoa:-MWaC8qR3oj1gd6jmUi4:b-j14fqa) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.h#L286)):*
> ```objc
>     std::string address;
> 
>     enum class ConnectionSourceType { kAny = 0, kSameIpOrLoopback, kExternal };
> ```

This can be moved into `FilterChainMap`.
___
*[src/core/ext/xds/xds_api.cc, line 682 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZoAGT9-foV8DBrkga:-MWaFOTZBh4mElaphnKp:b-oi3gc7) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.cc#L682)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Note that we are adding `source_port_pair.second.data->ToString()`after the comma.  (FilterChainData, but not mentioning FilterChainData to avoid user confusion since the proto does not have that) 
</blockquote></details>

Oh, sorry, I misread this.

If we stick with this flattened representation (see my comment elsewhere), then I think we should format it as "{filter_chain_match={...}, filter_chain={...}}".  That will be more readable when logged, especially when there are multiple entries combined together.
___
*[src/core/ext/xds/xds_api.cc, line 580 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaKNCEEHwIWlTsbA5c:-MWaKNCEEHwIWlTsbA5d:bkzqfvn) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L580)):*
> ```cpp
>            destination_ip_pair.second.source_types_array[source_type]) {
>         for (const auto& source_port_pair : source_ip_pair.second.ports_map) {
>           absl::InlinedVector<std::string, 5> filter_chain_match_content;
> ```

It looks like we're flattening this map out for logging.  Why not just log it the way it actually is represented in this data structure?
___
*[src/core/ext/xds/xds_api.cc, line 628 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaGfAm8a6ayhwZHSRx:-MWaGfAm8a6ayhwZHSRy:bxaci93) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L628)):*
> ```cpp
>     contents.push_back(absl::StrCat("address=", address));
>     contents.push_back(
>         absl::StrCat("filter_chains=", filter_chain_map.ToString()));
> ```

Suggest changing "filter_chains="  to "filter_chain_map=".
___
*[src/core/ext/xds/xds_api.cc, line 2027 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaHJffAHffJ-c_BUC7:-MWaHJffAHffJ-c_BUC8:bx63m6l) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2027)):*
> ```cpp
> 
>     struct CidrRange {
>       std::string address_prefix;
> ```

Would it make sense to just use `grpc_resolved_address` here, so that we don't have to convert to that form later?
___
*[src/core/ext/xds/xds_api.cc, line 2030 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaGnlk06qGFtIqwQwQ:-MWaGnlk06qGFtIqwQwR:b-ci3cjz) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2030)):*
> ```cpp
>       uint32_t prefix_len;
> 
>       bool operator==(const CidrRange& other) const {
> ```

Is this still needed?  I don't see it being used anywhere.
___
*[src/core/ext/xds/xds_api.cc, line 2047 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaKqdu-Arun9vjH1Sa:-MWaKqdu-Arun9vjH1Sb:bxhc72p) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2047)):*
> ```cpp
>     std::vector<std::string> application_protocols;
> 
>     std::string ToString() const;
> ```

I don't see this actually being called anywhere, so I don't think we need it.

Same for `CidrRange::ToString()` above.
___
*[src/core/ext/xds/xds_api.cc, line 2301 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJ-jkCBMcmr7X425O:-MWaJ-jkCBMcmr7X425P:b-127d3c) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2301)):*
> ```cpp
>     XdsApi::LdsUpdate::FilterChainMap::SourcePortsMap* ports_map,
>     uint32_t port) {
>   std::pair<XdsApi::LdsUpdate::FilterChainMap::SourcePortsMap::iterator, bool>
> ```

This is a good case in which to use `auto`.
___
*[src/core/ext/xds/xds_api.cc, line 2334 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJ6dS1hkH9xiby-lF:-MWaJ6dS1hkH9xiby-lG:b-tri2yy) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2334)):*
> ```cpp
>     XdsApi::LdsUpdate::FilterChainMap::SourceIpMap* source_ip_map) {
>   if (filter_chain.filter_chain_match.source_prefix_ranges.empty()) {
>     std::pair<XdsApi::LdsUpdate::FilterChainMap::SourceIpMap::iterator, bool>
> ```

`auto`
___
*[src/core/ext/xds/xds_api.cc, line 2359 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJ2os2NpaQevb-_jJ:-MWaJ2os2NpaQevb-_jK:b-tri2yy) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2359)):*
> ```cpp
>               ? uint32_t(32)
>               : uint32_t(128));
>       std::pair<XdsApi::LdsUpdate::FilterChainMap::SourceIpMap::iterator, bool>
> ```

`auto`
___
*[src/core/ext/xds/xds_api.cc, line 2436 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJBgF1S4NTc_jTx5Y:-MWaJBgF1S4NTc_jTx5Z:b-tri2yy) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2436)):*
> ```cpp
>     XdsApi::LdsUpdate::FilterChainMap::DestinationIpMap* destination_ip_map) {
>   if (filter_chain.filter_chain_match.prefix_ranges.empty()) {
>     std::pair<XdsApi::LdsUpdate::FilterChainMap::DestinationIpMap::iterator,
> ```

`auto`
___
*[src/core/ext/xds/xds_api.cc, line 2461 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJEg68txj3CqWajd-:-MWaJEg68txj3CqWajd0:b-tri2yy) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2461)):*
> ```cpp
>               ? uint32_t(32)
>               : uint32_t(128));
>       std::pair<XdsApi::LdsUpdate::FilterChainMap::DestinationIpMap::iterator,
> ```

`auto`


<!-- Sent from Reviewable.io -->

2021-03-24 22:52 UTC, yashykt reviewed
> Reviewed 2 of 16 files at r1, 1 of 9 files at r5, 3 of 4 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: 14 of 17 files reviewed, 12 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 286 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaC8qQCDtXKOtrWZoa:-MWaQko0D5rSEoxZ1nP8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.h#L286)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be moved into `FilterChainMap`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 682 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZoAGT9-foV8DBrkga:-MWaQpSs5sr3T-v2Xm5d:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.cc#L682)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Oh, sorry, I misread this.

If we stick with this flattened representation (see my comment elsewhere), then I think we should format it as "{filter_chain_match={...}, filter_chain={...}}".  That will be more readable when logged, especially when there are multiple entries combined together.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 580 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaKNCEEHwIWlTsbA5c:-MWaP_uyBk7sAqT130Sz:bsfh51f) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L580)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like we're flattening this map out for logging.  Why not just log it the way it actually is represented in this data structure?
</blockquote></details>

I'm not sure if that would be readable/understandable
___
*[src/core/ext/xds/xds_api.cc, line 628 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaGfAm8a6ayhwZHSRx:-MWaQqZN0PXDLCdjb96C:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L628)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest changing "filter_chains="  to "filter_chain_map=".
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2027 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaHJffAHffJ-c_BUC7:-MWaMt3G8vBwFVxhk3Qv:b-lo5z0o) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2027)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Would it make sense to just use `grpc_resolved_address` here, so that we don't have to convert to that form later?
</blockquote></details>

We can, but then we'll need to convert it back using `grpc_sockaddr_to_string` in that one place for logging (when we find it to be a duplicate). 
___
*[src/core/ext/xds/xds_api.cc, line 2030 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaGnlk06qGFtIqwQwQ:-MWaNPiHBFOAySXG2t9v:bulqgqa) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2030)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this still needed?  I don't see it being used anywhere.
</blockquote></details>

Right, we don't. Removing.
___
*[src/core/ext/xds/xds_api.cc, line 2047 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaKqdu-Arun9vjH1Sa:-MWaNNZqAhgB0RAxJoeZ:b-fo0n1y) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2047)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this actually being called anywhere, so I don't think we need it.

Same for `CidrRange::ToString()` above.
</blockquote></details>

We do in one place for logging purposes (when we find it to be a duplicate..)
___
*[src/core/ext/xds/xds_api.cc, line 2301 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJ-jkCBMcmr7X425O:-MWaOTsC8ndSI_Ib2e8h:b-575dym) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2301)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is a good case in which to use `auto`.
</blockquote></details>

I don't know. The declaration for 'emplace' is not immediately obvious atleast to me, and I always have to look it up. Changed it anyway.
___
*[src/core/ext/xds/xds_api.cc, line 2334 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJ6dS1hkH9xiby-lF:-MWaR0UVEyNw-R5W0Hmy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2334)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`auto`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2359 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJ2os2NpaQevb-_jJ:-MWaR6Z56rvYZ1CafhgZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2359)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`auto`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2436 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJBgF1S4NTc_jTx5Y:-MWaR6vk8yZRDghVmtIa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2436)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`auto`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2461 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJEg68txj3CqWajd-:-MWaR7dw0z-h1t_V_B25:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2461)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`auto`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-24 23:20 UTC, markdroth requested changes
Getting very close!  The only significant remaining issues are about the representation of the IP prefixes and avoiding duplicate logging code.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757#-:-MWaXEZN2HoADJOR2W3L:bowaa1q)* status: all files reviewed, 7 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 332 at r9](https://reviewable.io/reviews/grpc/grpc/25757#-MWaW4sC74iFTl7Lx4hk:-MWaW4sC74iFTl7Lx4hl:b-t0f64u) ([raw file](https://github.com/grpc/grpc/blob/e0b1c130de8022b8ca785609cbae1c05f3cc8168/src/core/ext/xds/xds_api.h#L332)):*
> ```objc
>         }
>       };
>       using SourceIpMap = std::map<std::string, SourceIp>;
> ```

I just noticed this: Why is this a map instead of a vector?  It looks like our code needs to iterate over every entry anyway, so there's no reason it needs to be a map, and no real benefit to storing the human-readable string as a key.
___
*[src/core/ext/xds/xds_api.h, line 359 at r9](https://reviewable.io/reviews/grpc/grpc/25757#-MWaWKX_1j6bYrpPMpvC:-MWaWKX_1j6bYrpPMpvD:b-n545af) ([raw file](https://github.com/grpc/grpc/blob/e0b1c130de8022b8ca785609cbae1c05f3cc8168/src/core/ext/xds/xds_api.h#L359)):*
> ```objc
>       };
>       // We always fail match on destination ports map
>       using DestinationIpMap = std::map<std::string, DestinationIp>;
> ```

Same question here.
___
*[src/core/ext/xds/xds_api.cc, line 682 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZoAGT9-foV8DBrkga:-MWaTTOOCzb53C-KqGwf:b-u176wk) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.cc#L682)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please also add braces around the entire thing.  Otherwise, it's hard to tell where one ends and the next begins when we log the entire map.
___
*[src/core/ext/xds/xds_api.cc, line 2027 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaHJffAHffJ-c_BUC7:-MWaWRac4Spj0hGFyzU5:butawk3) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2027)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

We can, but then we'll need to convert it back using `grpc_sockaddr_to_string` in that one place for logging (when we find it to be a duplicate). 
</blockquote></details>

I'm fine with converting it back for logging purposes.  I think that we'll need to do the same thing in `FilterChainMap::ToString()` once you change the maps to vectors for the IP prefixes.
___
*[src/core/ext/xds/xds_api.cc, line 2047 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaKqdu-Arun9vjH1Sa:-MWaWmKm4KboRZqoA5aZ:b-8ccjrd) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2047)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

We do in one place for logging purposes (when we find it to be a duplicate..)
</blockquote></details>

Hmm.  Can we do something to eliminate the duplication between this and `FilterChainMap::ToString()`?  They're both logging basically the same data, so it would be nice to not have to have essentially the same code twice.
___
*[src/core/ext/xds/xds_api.cc, line 2436 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJBgF1S4NTc_jTx5Y:-MWaUNdjBxrQzDKu9k3w:behgwxy) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2436)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change here.
___
*[src/core/ext/xds/xds_api.cc, line 2461 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJEg68txj3CqWajd-:-MWaUPeP-2zl3D-uSfcc:behgwxy) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2461)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change here.


<!-- Sent from Reviewable.io -->

2021-03-24 23:46 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: all files reviewed, 7 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 332 at r9](https://reviewable.io/reviews/grpc/grpc/25757#-MWaW4sC74iFTl7Lx4hk:-MWa_nPFBtlIPPdqVr6o:b-ucfhqs) ([raw file](https://github.com/grpc/grpc/blob/e0b1c130de8022b8ca785609cbae1c05f3cc8168/src/core/ext/xds/xds_api.h#L332)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I just noticed this: Why is this a map instead of a vector?  It looks like our code needs to iterate over every entry anyway, so there's no reason it needs to be a map, and no real benefit to storing the human-readable string as a key.
</blockquote></details>

Well, the benefit is mainly at build time where we can detect duplicate matches thanks to the match on the string address. That being said, I can also change this to a map which goes from SourceIP to SourcePortsMap 
___
*[src/core/ext/xds/xds_api.h, line 359 at r9](https://reviewable.io/reviews/grpc/grpc/25757#-MWaWKX_1j6bYrpPMpvC:-MWabEUeEbJCBKas0_gj:bkln5uu) ([raw file](https://github.com/grpc/grpc/blob/e0b1c130de8022b8ca785609cbae1c05f3cc8168/src/core/ext/xds/xds_api.h#L359)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same question here.
</blockquote></details>

I can change it to a map which goes from DestinationIp to another middle type that holds the bool and source_types_array
___
*[src/core/ext/xds/xds_api.cc, line 2047 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaKqdu-Arun9vjH1Sa:-MWabjm4BtTckLrqzOZ-:boe7ok7) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2047)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hmm.  Can we do something to eliminate the duplication between this and `FilterChainMap::ToString()`?  They're both logging basically the same data, so it would be nice to not have to have essentially the same code twice.
</blockquote></details>

It's the same data but from a different structure. I can construct a `FilterChainMatch` from each `FilterChainMap` entry but that seems unnecessary


<!-- Sent from Reviewable.io -->

2021-03-24 23:54 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: all files reviewed, 7 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 332 at r9](https://reviewable.io/reviews/grpc/grpc/25757#-MWaW4sC74iFTl7Lx4hk:-MWadmfZA_jtWhim_d4b:bokox8f) ([raw file](https://github.com/grpc/grpc/blob/e0b1c130de8022b8ca785609cbae1c05f3cc8168/src/core/ext/xds/xds_api.h#L332)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Well, the benefit is mainly at build time where we can detect duplicate matches thanks to the match on the string address. That being said, I can also change this to a map which goes from SourceIP to SourcePortsMap 
</blockquote></details>

Well, actually I remembered why I'm storing a std::string as the key instead of SouceIp. It was handle the case of no prefix range being mentioned for a filter chain


<!-- Sent from Reviewable.io -->

2021-03-24 23:59 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: all files reviewed, 7 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 332 at r9](https://reviewable.io/reviews/grpc/grpc/25757#-MWaW4sC74iFTl7Lx4hk:-MWadsk_EstW3uxrQtos:b-9kqij1) ([raw file](https://github.com/grpc/grpc/blob/e0b1c130de8022b8ca785609cbae1c05f3cc8168/src/core/ext/xds/xds_api.h#L332)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Well, actually I remembered why I'm storing a std::string as the key instead of SouceIp. It was handle the case of no prefix range being mentioned for a filter chain
</blockquote></details>

I don't think it makes sense to have the extra overhead of a map and all of the human-readable keys beyond validation time if that's the only time that they're needed.  If the map is really useful at validation time, then how about creating the map as a local variable during validation and then converting it into a smaller form once we're done validating?

Once we're done with validation, I think it can just be a vector of `SourceIp` structs.  If we're not doing any random access into the map, it doesn't need to be a map in the first place.

I think we can handle the case of no prefix range being mentioned in a filter change by using `absl::optional<>`.  For example, you could move the `address` and `prefix_len` fields into their own struct, and then both `SourceIp` and `DestinationIp` could have an `absl::optional<>` of that struct.
___
*[src/core/ext/xds/xds_api.h, line 359 at r9](https://reviewable.io/reviews/grpc/grpc/25757#-MWaWKX_1j6bYrpPMpvC:-MWae1ppEItupGq5-6Nt:b-6lzvga) ([raw file](https://github.com/grpc/grpc/blob/e0b1c130de8022b8ca785609cbae1c05f3cc8168/src/core/ext/xds/xds_api.h#L359)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I can change it to a map which goes from DestinationIp to another middle type that holds the bool and source_types_array
</blockquote></details>

Same here -- I think it can just be a vector of `DestinationIp` structs once validation is done.
___
*[src/core/ext/xds/xds_api.cc, line 2047 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaKqdu-Arun9vjH1Sa:-MWadgI2-rqcXZbQ4wx0:b-pd8xpi) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2047)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

It's the same data but from a different structure. I can construct a `FilterChainMatch` from each `FilterChainMap` entry but that seems unnecessary
</blockquote></details>

That may actually be less code than the amount that we're currently duplicating.  Maybe try it and see how it compares?


<!-- Sent from Reviewable.io -->

2021-03-25 00:06 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: all files reviewed, 7 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 332 at r9](https://reviewable.io/reviews/grpc/grpc/25757#-MWaW4sC74iFTl7Lx4hk:-MWafMoZ0k4kTAK6Ab6O:baq0kc5) ([raw file](https://github.com/grpc/grpc/blob/e0b1c130de8022b8ca785609cbae1c05f3cc8168/src/core/ext/xds/xds_api.h#L332)):*
> If the map is really useful at validation time, then how about creating the map as a local variable during validation and then converting it into a smaller form once we're done validating?

The local variable needs to be at the scope of the respective map. So, there are two ways I can do that -
1) Create another temporary field (maybe a unique_ptr) which stores the map at build time, and when we are done building the map, we loop through the map and convert each map to a std::vector
2) Create a whole new type like `TemporaryFilterChainMap` which holds this temporary map and then converts it to `FilterChainMap` later when we are done validating


<!-- Sent from Reviewable.io -->

2021-03-25 12:02 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: 13 of 17 files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 332 at r9](https://reviewable.io/reviews/grpc/grpc/25757#-MWaW4sC74iFTl7Lx4hk:-MWdDhg7Cv4LUpl7NNln:bl3kot5) ([raw file](https://github.com/grpc/grpc/blob/e0b1c130de8022b8ca785609cbae1c05f3cc8168/src/core/ext/xds/xds_api.h#L332)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> If the map is really useful at validation time, then how about creating the map as a local variable during validation and then converting it into a smaller form once we're done validating?

The local variable needs to be at the scope of the respective map. So, there are two ways I can do that -
1) Create another temporary field (maybe a unique_ptr) which stores the map at build time, and when we are done building the map, we loop through the map and convert each map to a std::vector
2) Create a whole new type like `TemporaryFilterChainMap` which holds this temporary map and then converts it to `FilterChainMap` later when we are done validating
</blockquote></details>

Went with the second approach and created an `InternalFilterChainMap` which is used for validating the filter chain entries and finally building a stripped down `FilterChainMap`
___
*[src/core/ext/xds/xds_api.h, line 359 at r9](https://reviewable.io/reviews/grpc/grpc/25757#-MWaWKX_1j6bYrpPMpvC:-MWdFym-BrSJVz3Xj9cb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e0b1c130de8022b8ca785609cbae1c05f3cc8168/src/core/ext/xds/xds_api.h#L359)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here -- I think it can just be a vector of `DestinationIp` structs once validation is done.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 682 at r6](https://reviewable.io/reviews/grpc/grpc/25757#-MWZoAGT9-foV8DBrkga:-MWdG-Xq4Wbio9PgReBq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b0bdd59dbbe0993d561ba1cd26ae93f6154ccfa/src/core/ext/xds/xds_api.cc#L682)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please also add braces around the entire thing.  Otherwise, it's hard to tell where one ends and the next begins when we log the entire map.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2027 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaHJffAHffJ-c_BUC7:-MWdFY7Z3g_z2brLG9ug:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2027)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'm fine with converting it back for logging purposes.  I think that we'll need to do the same thing in `FilterChainMap::ToString()` once you change the maps to vectors for the IP prefixes.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2047 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaKqdu-Arun9vjH1Sa:-MWdFZWcEC_ATsWoJRy6:b-9pf982) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2047)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That may actually be less code than the amount that we're currently duplicating.  Maybe try it and see how it compares?
</blockquote></details>

It does save 8 lines of code :) Adopted it
___
*[src/core/ext/xds/xds_api.cc, line 2436 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJBgF1S4NTc_jTx5Y:-MWdFmji7gDHXSsZF4qP:bhqcyhb) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2436)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see a change here.
</blockquote></details>

Looks like the search and replace missed it due to spacing. This time for sure
___
*[src/core/ext/xds/xds_api.cc, line 2461 at r8](https://reviewable.io/reviews/grpc/grpc/25757#-MWaJEg68txj3CqWajd-:-MWdFtoC74kQ355AHnG-:buctbik) ([raw file](https://github.com/grpc/grpc/blob/6d1663c132f83bd34a40301775004c84e80044f7/src/core/ext/xds/xds_api.cc#L2461)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see a change here.
</blockquote></details>

This time for sure.


<!-- Sent from Reviewable.io -->

2021-03-25 16:11 UTC, markdroth requested changes
This looks great!  Just a few minor nits remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757#-:-MWe8u639yRNzeLx-lmY:bivaja4)* status: all files reviewed, 3 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 239 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe3VHPBf8HVl9RfY4_:-MWe3VHPBf8HVl9RfY4a:b7wm6dw) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.h#L239)):*
> ```objc
>   };
> 
>   struct CidrRange {
> ```

This should be moved inside of the `FilterChainMap` struct.
___
*[src/core/ext/xds/xds_api.cc, line 598 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe6tWh7rkD4xY9gghK:-MWe6tWh7rkD4xY9gghL:b-bffp13) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.cc#L598)):*
> ```cpp
> 
> //
> // FilterChain::FilterChainMatch
> ```

Please move this comment above the `FilterChain` definition above, and just have it say `FilterChain`.  We can consider `FilterChainMatch` to be part of `FilterChain` for the purposes of this comment.
___
*[src/core/ext/xds/xds_api.cc, line 2094 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe4jsD5ojDhl-4bxcb:-MWe4jsD5ojDhl-4bxcc:byv2mc6) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.cc#L2094)):*
> ```cpp
>   std::string address_prefix = UpbStringToStdString(
>       envoy_config_core_v3_CidrRange_address_prefix(cidr_range_proto));
>   memset(&cidr_range->address, 0, sizeof(grpc_resolved_address));
> ```

This looks almost identical to what `grpc_string_to_sockaddr()` does.  The only difference is that `grpc_string_to_sockaddr()` asserts if the address string can't be parsed, which is actually pretty horrible behavior -- I suggest changing it to return an error in that case, so that we can use it safely here.

If this winds up being non-trivial (e.g., changing `grpc_string_to_sockaddr()` requires changing a bunch of callers), then it's fine to just leave a TODO for now.


<!-- Sent from Reviewable.io -->

2021-03-25 16:40 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 239 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe3VHPBf8HVl9RfY4_:-MWeEhrV9DhaV1Y_IvoV:b-je8tpm) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.h#L239)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be moved inside of the `FilterChainMap` struct.
</blockquote></details>

I actually moved it out earlier since CidrRange is not nested in FilterChain in the proto structure either


<!-- Sent from Reviewable.io -->

2021-03-25 16:41 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: all files reviewed, 3 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 239 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe3VHPBf8HVl9RfY4_:-MWeFh4o7CMVGLBeleiN:bqph3u8) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.h#L239)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I actually moved it out earlier since CidrRange is not nested in FilterChain in the proto structure either
</blockquote></details>

Sure, but that doesn't mean it needs to be separate here.  We can move it out later if we wind up using it somewhere else, but for now let's keep it localized to the only place we're actually using it.


<!-- Sent from Reviewable.io -->

2021-03-25 17:16 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: 13 of 17 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 239 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe3VHPBf8HVl9RfY4_:-MWeNYtq9l4VqY6hL7mK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.h#L239)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Sure, but that doesn't mean it needs to be separate here.  We can move it out later if we wind up using it somewhere else, but for now let's keep it localized to the only place we're actually using it.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 598 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe6tWh7rkD4xY9gghK:-MWeNdn0DkbRETDFA8jk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.cc#L598)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this comment above the `FilterChain` definition above, and just have it say `FilterChain`.  We can consider `FilterChainMatch` to be part of `FilterChain` for the purposes of this comment.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2094 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe4jsD5ojDhl-4bxcb:-MWeNeMMABekYTY4Wp3J:b-2sw513) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.cc#L2094)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This looks almost identical to what `grpc_string_to_sockaddr()` does.  The only difference is that `grpc_string_to_sockaddr()` asserts if the address string can't be parsed, which is actually pretty horrible behavior -- I suggest changing it to return an error in that case, so that we can use it safely here.

If this winds up being non-trivial (e.g., changing `grpc_string_to_sockaddr()` requires changing a bunch of callers), then it's fine to just leave a TODO for now.
</blockquote></details>

Agreed. Added a new variant `grpc_string_to_sockaddr_new` for now


<!-- Sent from Reviewable.io -->

2021-03-25 17:21 UTC, markdroth requested changes
Just one minor nit remaining!

> Reviewed 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757#-:-MWeOta0-0Xpt5mxdCkC:bva76ti)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 2094 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe4jsD5ojDhl-4bxcb:-MWeO69w-j0ZR-U_Z-cP:bueqig) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.cc#L2094)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Agreed. Added a new variant `grpc_string_to_sockaddr_new` for now
</blockquote></details>

Instead of a new variant, how about just adding an optional parameter to control whether it fails on error?  As long as the default is still the current behavior, then it shouldn't break anything.


<!-- Sent from Reviewable.io -->

2021-03-25 17:27 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 2094 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe4jsD5ojDhl-4bxcb:-MWePm1JEDb3NU7_Bxrt:bhliox2) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.cc#L2094)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of a new variant, how about just adding an optional parameter to control whether it fails on error?  As long as the default is still the current behavior, then it shouldn't break anything.
</blockquote></details>

I intend to send a follow-up PR to remove and replace. Didn't want to do it here since there are more cpython usages of it than Core usages. So, let's keep it as it is here.


<!-- Sent from Reviewable.io -->

2021-03-25 17:35 UTC, markdroth approved these changes
This looks fantastic!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25757#-:-MWeS6nmEK2IK6L_-kj9:bcpuwtr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 2094 at r10](https://reviewable.io/reviews/grpc/grpc/25757#-MWe4jsD5ojDhl-4bxcb:-MWeS0Mi4xRsW2Y11IBO:b-1yzv6o) ([raw file](https://github.com/grpc/grpc/blob/fe12acbd50acce044ea4b91c247b1d0733b18e3b/src/core/ext/xds/xds_api.cc#L2094)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I intend to send a follow-up PR to remove and replace. Didn't want to do it here since there are more cpython usages of it than Core usages. So, let's keep it as it is here.
</blockquote></details>

Okay, as long as you make sure to follow up on it.  Thanks!


<!-- Sent from Reviewable.io -->

2021-03-25 21:09 UTC, yashykt commented
Thanks for reviewing!

2021-03-25 21:12 UTC, merged