Add ABSL_LOCKABLE support to WorkSerializer
grpc/grpc pull request #25791
Opened 2021-03-23 17:11 UTC by veblush

2021-03-23 18:57 UTC, markdroth requested changes
Thanks for doing this!  I think this needs a bit more work in order to actually be useful.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25791#-:-MWVRjVY6ftBcc9GlxGk:bhob3ka)* status: all files reviewed, 3 unresolved discussions (waiting on @veblush)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 373 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVQZVD66jqo8aSVdkL:-MWVQZVD66jqo8aSVdkM:b-vpb2ne) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/ext/filters/client_channel/client_channel.cc#L373)):*
> ```cpp
>   //
>   std::shared_ptr<WorkSerializer> work_serializer_;
>   grpc_pollset_set* interested_parties_;
> ```

Can you please add `ABSL_GUARDED_BY` annotations to all of the data members in this section?  That's the main thing I want to get out of this: to make sure that these data members are only ever accessed while holding the work serializer.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1805 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVRTaY17ZPmtsCJV1W:-MWVRTaY17ZPmtsCJV1X:bebgsmo) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/ext/filters/client_channel/client_channel.cc#L1805)):*
> ```cpp
>   void UpdateState(grpc_connectivity_state state, const absl::Status& status,
>                    std::unique_ptr<LoadBalancingPolicy::SubchannelPicker>
>                        picker) override ABSL_NO_THREAD_SAFETY_ANALYSIS {
> ```

I'm not really comfortable with all of these uses of `ABSL_NO_THREAD_SAFETY_ANALYSIS`.  In cases like this one, it seems like it actually eliminates the benefit of using these annotations with the `WorkSerializer`, since it prevents the compiler from verifying that the data members that are protected by the `WorkSerializer` are actually being invoked only from inside of it.

I've just merged #25777.  Can you merge in those changes and see if it allows you to eliminate all of these uses of `ABSL_NO_THREAD_SAFETY_ANALYSIS`?  If not, I'd like to understand what's still requiring that to be used.
___
*[src/core/lib/iomgr/work_serializer.h, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVQm3-8vUR1TdPfLU8:-MWVQm3-8vUR1TdPfLU9:b-81qua4) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/lib/iomgr/work_serializer.h#L62)):*
> ```objc
>   //   void run_callback() {
>   //     work_serializer.Run(
>   //         []() ABSL_EXCLUSIVE_LOCKS_REQUIRED(work_serializer) {
> ```

Is there a way to somehow automatically apply `ABSL_EXCLUSIVE_LOCKS_REQUIRED` to whatever lambda is passed to `Run()`, so that it doesn't need to be explicitly written out in the code every place `Run()` is called?  I suspect not, but I figured I'd ask the question just in case I'm wrong.  If there is a way to do that, I think it would make it much easier to use this mechanism.


<!-- Sent from Reviewable.io -->

2021-03-23 22:29 UTC, veblush reviewed
Yeah, this isn't sufficient to make client_channel race-condition free.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25791#-:-MWWC79K8wVAk3yNcvk4:b-v9hrp4)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 373 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVQZVD66jqo8aSVdkL:-MWWA9g-6O8Byk2JQMYd:b84822e) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/ext/filters/client_channel/client_channel.cc#L373)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can you please add `ABSL_GUARDED_BY` annotations to all of the data members in this section?  That's the main thing I want to get out of this: to make sure that these data members are only ever accessed while holding the work serializer.
</blockquote></details>

I tried it but I couldn't do it because many of them are accessed without work_serializer_. I don't think it's harmful because most of cases are just accessing the pointer but clang doesn't allow any. Can you try it?
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1805 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVRTaY17ZPmtsCJV1W:-MWWAmdu1vi4DpggN8Pm:bv839aq) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/ext/filters/client_channel/client_channel.cc#L1805)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'm not really comfortable with all of these uses of `ABSL_NO_THREAD_SAFETY_ANALYSIS`.  In cases like this one, it seems like it actually eliminates the benefit of using these annotations with the `WorkSerializer`, since it prevents the compiler from verifying that the data members that are protected by the `WorkSerializer` are actually being invoked only from inside of it.

I've just merged #25777.  Can you merge in those changes and see if it allows you to eliminate all of these uses of `ABSL_NO_THREAD_SAFETY_ANALYSIS`?  If not, I'd like to understand what's still requiring that to be used.
</blockquote></details>

That's true and I like you to help on this since it seems non-trivial refactoring to get the best out of this feature. I changed `ABSL_NO_THREAD_SAFETY_ANALYSIS` to `ABSL_EXCLUSIVE_LOCKS_REQUIRED(work_serializer_)` but it actually doesn't change much because clang analysis doesn't cover the case of virtual function. e.g. `Resolver::ResultHandler` which is called by many other places doesn't have annotations but `ResolverResultHandler` has. Clang isn't able to think `Resolver::ResultHandler::ReturnResult` is mapped to `ResolverResultHandler::ReturnResult`so no check will happen on this.

To make clang check on this path, I guess `Resolver::ResultHandler` should have annotation with worker_thread so that all call sites using it can be included when being analyzed.
___
*[src/core/lib/iomgr/work_serializer.h, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVQm3-8vUR1TdPfLU8:-MWWAQX28KB3em8ExMoZ:b-bzcmjl) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/lib/iomgr/work_serializer.h#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is there a way to somehow automatically apply `ABSL_EXCLUSIVE_LOCKS_REQUIRED` to whatever lambda is passed to `Run()`, so that it doesn't need to be explicitly written out in the code every place `Run()` is called?  I suspect not, but I figured I'd ask the question just in case I'm wrong.  If there is a way to do that, I think it would make it much easier to use this mechanism.
</blockquote></details>

Unfortunately not. This is a limitation of clang thread annotation. My guess is that lambda function is passed to the functor variable which is technically not compile-time thing so clang just happens to give up the analysis on that. So lambda should always have annotation.


<!-- Sent from Reviewable.io -->

2021-03-24 21:17 UTC, markdroth requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25791)* status: all files reviewed, 2 unresolved discussions (waiting on @veblush)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 373 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVQZVD66jqo8aSVdkL:-MWa0mb3-W1tLCKC1Rgw:b-driozc) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/ext/filters/client_channel/client_channel.cc#L373)):*
<details><summary><i>Previously, veblush (Esun Kim) wrote…</i></summary><blockquote>

I tried it but I couldn't do it because many of them are accessed without work_serializer_. I don't think it's harmful because most of cases are just accessing the pointer but clang doesn't allow any. Can you try it?
</blockquote></details>

Which ones do you see that are accessed outside the `WorkSerializer`?  I don't think that should be happening in this code.

My understanding is that `ABSL_GUARDED_BY()` requires that the mutex actually be locked.  But `WorkSerializer`, unlike `Mutex`, does not have a `Lock()` method, so how does the compiler know when the `WorkSerializer` is being held?  I'm wondering if what's happening here is that the compiler just doesn't know which code is actually running inside the `WorkSerializer`, so it thinks the lock is never being acquired, and therefore it thinks all data members are being accessed without holding the lock.

IIUC, `ABSL_GUARDED_BY()` is the annotation that is actually important here, because the whole point of synchronization is to guard data members.  I think annotations like `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` are there only to allow the `ABSL_GUARDED_BY()` annotations to work, since the compiler can detect cases where a single function grabs the lock and then accesses a data member, but it needs help to understand what's happening in a case where one function grabs the lock and then calls another function that accesses the data member.  Without `ABSL_GUARDED_BY()`, I don't think there's absolutely any benefit to using `ABSL_EXCLUSIVE_LOCKS_REQUIRED()`.

In fact, does `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` actually do anything by itself without `ABSL_GUARDED_BY()`?  I'm now wondering how the compiler knows that the lambda that we pass to `WorkSerializer::Run()` is actually being invoked while holding the lock.  Is that just a no-op?  Maybe that's why this PR isn't causing any failures yet?

In any case, if we can't make `ABSL_GUARDED_BY()` work, then I think this PR doesn't actually accomplish anything. :(
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1805 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVRTaY17ZPmtsCJV1W:-MWa2Wo7-BGKo6v_HgVl:b-5b9c3y) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/ext/filters/client_channel/client_channel.cc#L1805)):*
<details><summary><i>Previously, veblush (Esun Kim) wrote…</i></summary><blockquote>

That's true and I like you to help on this since it seems non-trivial refactoring to get the best out of this feature. I changed `ABSL_NO_THREAD_SAFETY_ANALYSIS` to `ABSL_EXCLUSIVE_LOCKS_REQUIRED(work_serializer_)` but it actually doesn't change much because clang analysis doesn't cover the case of virtual function. e.g. `Resolver::ResultHandler` which is called by many other places doesn't have annotations but `ResolverResultHandler` has. Clang isn't able to think `Resolver::ResultHandler::ReturnResult` is mapped to `ResolverResultHandler::ReturnResult`so no check will happen on this.

To make clang check on this path, I guess `Resolver::ResultHandler` should have annotation with worker_thread so that all call sites using it can be included when being analyzed.
</blockquote></details>

Hmmm.  Yeah, the resolver result handler is a tricky case.  In principle, the resolver API does actually have a requirement that the result handler methods are called from within the client channel's work serializer, so it seems correct to add the annotations to the base class.  But since `work_serializer_` is an internal data member of `ChannelData`, which is in turn purely internal to this .cc file, it's not clear how to actually add the annotations in resolver.h.

I have actually been meaning to split client_channel.cc into multiple files anyway, which would move the definition of `ChannelData` into the .h file.  Let me take a crack at that first, since that should get us one step closer to what we need here, and then we can see what we need to do for the next step.  I'm not sure how to do it without making `Resolver::ResultHandler` a friend of `ChannelData`, which I'd rather not do.  But let's see what we can come up with.


<!-- Sent from Reviewable.io -->

2021-03-26 00:58 UTC, veblush reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25791)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @markdroth and @veblush)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 373 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVQZVD66jqo8aSVdkL:-MWftXkhD2MBMtw2aGIP:bq31d07) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/ext/filters/client_channel/client_channel.cc#L373)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Which ones do you see that are accessed outside the `WorkSerializer`?  I don't think that should be happening in this code.

My understanding is that `ABSL_GUARDED_BY()` requires that the mutex actually be locked.  But `WorkSerializer`, unlike `Mutex`, does not have a `Lock()` method, so how does the compiler know when the `WorkSerializer` is being held?  I'm wondering if what's happening here is that the compiler just doesn't know which code is actually running inside the `WorkSerializer`, so it thinks the lock is never being acquired, and therefore it thinks all data members are being accessed without holding the lock.

IIUC, `ABSL_GUARDED_BY()` is the annotation that is actually important here, because the whole point of synchronization is to guard data members.  I think annotations like `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` are there only to allow the `ABSL_GUARDED_BY()` annotations to work, since the compiler can detect cases where a single function grabs the lock and then accesses a data member, but it needs help to understand what's happening in a case where one function grabs the lock and then calls another function that accesses the data member.  Without `ABSL_GUARDED_BY()`, I don't think there's absolutely any benefit to using `ABSL_EXCLUSIVE_LOCKS_REQUIRED()`.

In fact, does `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` actually do anything by itself without `ABSL_GUARDED_BY()`?  I'm now wondering how the compiler knows that the lambda that we pass to `WorkSerializer::Run()` is actually being invoked while holding the lock.  Is that just a no-op?  Maybe that's why this PR isn't causing any failures yet?

In any case, if we can't make `ABSL_GUARDED_BY()` work, then I think this PR doesn't actually accomplish anything. :(
</blockquote></details>

I updated the PR to show what can get ABSL_GUARDED_BY now and what cannot. One of example is `interested_parties_` which got errors without the comment.

```
src/core/ext/filters/client_channel/client_channel.cc:2245:51: error: reading variable 'interested_parties_' requires holding mutex 'work_serializer_' [-Werror,-Wthread-safety-analysis]
  grpc_polling_entity_add_to_pollset_set(pollent, interested_parties_);
                                                  ^
src/core/ext/filters/client_channel/client_channel.cc:2251:53: error: reading variable 'interested_parties_' requires holding mutex 'work_serializer_' [-Werror,-Wthread-safety-analysis]
  grpc_polling_entity_del_from_pollset_set(pollent, interested_parties_);
                                                    ^
src/core/ext/filters/client_channel/client_channel.cc:2581:41: error: reading variable 'interested_parties_' requires holding mutex 'chand->work_serializer_' [-Werror,-Wthread-safety-analysis]
    grpc_pollset_set_add_pollset(chand->interested_parties_, op->bind_pollset);
                                        ^
src/core/ext/filters/client_channel/client_channel.cc:2612:51: error: reading variable 'interested_parties_' requires holding mutex 'work_serializer_' [-Werror,-Wthread-safety-analysis]
  grpc_polling_entity_add_to_pollset_set(pollent, interested_parties_);
                                                  ^
src/core/ext/filters/client_channel/client_channel.cc:2618:53: error: reading variable 'interested_parties_' requires holding mutex 'work_serializer_' [-Werror,-Wthread-safety-analysis]
  grpc_polling_entity_del_from_pollset_set(pollent, interested_parties_);
                                                    ^
```

I'm not sure all of them are actually violating something but the one in ChannelData::StartTransportOp looks real.

How it works is like this; Clang doesn't know the lambda function is related to the caller object. So it has no idea about the Run method and its callback function but I annotated all callback functions of Run with `ABSL_EXCLUSIVE_LOCKS_REQUIRED(work_serializer)` so that clang knows that it both requires the lock of work_serializer and guarantees it's now acquired it. This is where magic happens. Clang doesn't know who actually happens to call the callback and only thing it knows is that these callback acquire the lock. That's how this works.

For what needs annotations, intermediate functions which will be called by callback and access variable that needs a protection from work_serializer don't have to have annotation. This is totally optional and I used it because their name (Locked suffix) is pretty clear to me about it's about to access variables in a serialized fashion.


<!-- Sent from Reviewable.io -->

2021-04-15 19:22 UTC, markdroth requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25791)* status: all files reviewed, 2 unresolved discussions (waiting on @veblush)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 373 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVQZVD66jqo8aSVdkL:-MYLwYrO0G7keJuJCxN3:b-6mnpq6) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/ext/filters/client_channel/client_channel.cc#L373)):*
<details><summary><i>Previously, veblush (Esun Kim) wrote…</i></summary><blockquote>

I updated the PR to show what can get ABSL_GUARDED_BY now and what cannot. One of example is `interested_parties_` which got errors without the comment.

```
src/core/ext/filters/client_channel/client_channel.cc:2245:51: error: reading variable 'interested_parties_' requires holding mutex 'work_serializer_' [-Werror,-Wthread-safety-analysis]
  grpc_polling_entity_add_to_pollset_set(pollent, interested_parties_);
                                                  ^
src/core/ext/filters/client_channel/client_channel.cc:2251:53: error: reading variable 'interested_parties_' requires holding mutex 'work_serializer_' [-Werror,-Wthread-safety-analysis]
  grpc_polling_entity_del_from_pollset_set(pollent, interested_parties_);
                                                    ^
src/core/ext/filters/client_channel/client_channel.cc:2581:41: error: reading variable 'interested_parties_' requires holding mutex 'chand->work_serializer_' [-Werror,-Wthread-safety-analysis]
    grpc_pollset_set_add_pollset(chand->interested_parties_, op->bind_pollset);
                                        ^
src/core/ext/filters/client_channel/client_channel.cc:2612:51: error: reading variable 'interested_parties_' requires holding mutex 'work_serializer_' [-Werror,-Wthread-safety-analysis]
  grpc_polling_entity_add_to_pollset_set(pollent, interested_parties_);
                                                  ^
src/core/ext/filters/client_channel/client_channel.cc:2618:53: error: reading variable 'interested_parties_' requires holding mutex 'work_serializer_' [-Werror,-Wthread-safety-analysis]
  grpc_polling_entity_del_from_pollset_set(pollent, interested_parties_);
                                                    ^
```

I'm not sure all of them are actually violating something but the one in ChannelData::StartTransportOp looks real.

How it works is like this; Clang doesn't know the lambda function is related to the caller object. So it has no idea about the Run method and its callback function but I annotated all callback functions of Run with `ABSL_EXCLUSIVE_LOCKS_REQUIRED(work_serializer)` so that clang knows that it both requires the lock of work_serializer and guarantees it's now acquired it. This is where magic happens. Clang doesn't know who actually happens to call the callback and only thing it knows is that these callback acquire the lock. That's how this works.

For what needs annotations, intermediate functions which will be called by callback and access variable that needs a protection from work_serializer don't have to have annotation. This is totally optional and I used it because their name (Locked suffix) is pretty clear to me about it's about to access variables in a serialized fashion.
</blockquote></details>

I've sent you #25983, which builds on this PR and fixes the remaining problems here.

It turns out that `interested_parties_` is not actually protected by the work serializer at all; it was just defined in the wrong section here.

The `state_tracker_` field was interesting, because all but one of its methods require external synchronization and are guarded by the work serializer.  But there is one place where we call the `state()` method, which *is* thread-safe, outside of the work serializer.  I used the `ABSL_TS_UNCHECKED_READ()` macro to inhibit the error in that case.

The other fields were addressed by adding `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` annotations on a few additional functions, most notably the other methods of `ChannelControlHelper` and a few places in `SubchannelWrapper`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1805 at r1](https://reviewable.io/reviews/grpc/grpc/25791#-MWVRTaY17ZPmtsCJV1W:-MYLxWPp1TbPEOS6Tpab:b-pjeli) ([raw file](https://github.com/grpc/grpc/blob/a0773848d53e5fa34eb28d2c01cc241e41d56f14/src/core/ext/filters/client_channel/client_channel.cc#L1805)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hmmm.  Yeah, the resolver result handler is a tricky case.  In principle, the resolver API does actually have a requirement that the result handler methods are called from within the client channel's work serializer, so it seems correct to add the annotations to the base class.  But since `work_serializer_` is an internal data member of `ChannelData`, which is in turn purely internal to this .cc file, it's not clear how to actually add the annotations in resolver.h.

I have actually been meaning to split client_channel.cc into multiple files anyway, which would move the definition of `ChannelData` into the .h file.  Let me take a crack at that first, since that should get us one step closer to what we need here, and then we can see what we need to do for the next step.  I'm not sure how to do it without making `Resolver::ResultHandler` a friend of `ChannelData`, which I'd rather not do.  But let's see what we can come up with.
</blockquote></details>

It looks like the compiler isn't actually requiring the annotations on `Resolver::ResultHandler`.  I didn't do that in #25983, but the compiler isn't complaining.

This does strike me as odd, though, because these methods are being called by the resolver, and although the resolver is holding the work serializer when it calls these methods, the compiler doesn't know that.  So it seems like it should be complaining, although it's not.  Is this inheritence case just a blind spot in the compiler's checks?

Note that we have the same issue with `ChannelControlHelper`: its methods are being called by the LB policy inside the work serializer, but the compiler doesn't have any way to know that.

I'd like to understanding this better, but I will note that even with this problem, these annotations are still useful, because they do still enforce the invariant within the client channel code itself.  They just can't do it uniformly across the resolver and LB policy implementations as well.


<!-- Sent from Reviewable.io -->

2021-04-21 22:49 UTC, markdroth commented
#25983 has been merged, which includes these changes, so this PR is no longer needed.

2021-04-21 22:49 UTC, closed without merging