EventEngine reference implementation: a libuv-based EventEngine that operates inside the iomgr framework
grpc/grpc pull request #26026
Opened 2021-04-20 18:50 UTC by drfloob

Collaboration between @drfloob and @nicolasnoble.

DRAFT. This implementation can be built using `bazel build --cxxopt='-DGRPC_EVENT_ENGINE_TEST' :all`

Shortcuts are being taken to get a working, testable version of the engine. EventEngines are not pluggable, for example.

2021-04-22 22:49 UTC, markdroth reviewed
This looks like a great start!

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 34 files at r1, 34 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MYvlOVxDYompzKQaYSx:b9kv8rc)* status: all files reviewed, 39 unresolved discussions (waiting on @drfloob)

___
*[include/grpc/event_engine/event_engine.h, line 17 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv3aLR56BCGgmfjLet:-MYv3aLR56BCGgmfjLeu:b4jfn24) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/include/grpc/event_engine/event_engine.h#L17)):*
> ```objc
> #define GRPC_EVENT_ENGINE_EVENT_ENGINE_H
> 
> #ifdef GRPC_EVENT_ENGINE_TEST
> ```

Why is this needed?  Where is it being set, and what does it being set indicate?

I see this in a number of files.  The purpose isn't clear to me overall, but even if it is needed for some reason, I don't think it should be needed in these public header files.  The EventEngine API itself should be able to be defined regardless of whether we're using it anywhere.
___
*[include/grpc/event_engine/event_engine.h, line 278 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv3pv59-SiLT8MJAa0:-MYv3pv59-SiLT8MJAa1:bputk0c) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/include/grpc/event_engine/event_engine.h#L278)):*
> ```objc
> std::shared_ptr<EventEngine> GetDefaultEventEngine();
> 
> absl::Status SetDefaultEventEngine(std::shared_ptr<EventEngine> engine);
> ```

Do we actually want to expose this as a public method for applications to use?  If so, what are the requirements in terms of when it can be called?  Can it be called only at program startup, or is it okay that refs to the old global EE instance have already been taken vai `GetDefaultEventEngine()`?  Is this call thread-safe, or does the caller have to lock `GetDefaultEventEngine()` and `SetDefaultEventEngine()`?
___
*[include/grpc/impl/codegen/grpc_types.h, line 420 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv4KxoCbIm6l4uhGer:-MYv4KxoCbIm6l4uhGes:br51fsj) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/include/grpc/impl/codegen/grpc_types.h#L420)):*
> ```objc
> /** gRPC Objective-C channel pooling id. */
> #define GRPC_ARG_CHANNEL_ID "grpc.channel_id"
> /** If set, this is a shared_ptr<EventEngine> that will be used instead of the
> ```

You can't store a `shared_ptr<>` in a channel arg, and `std::shared_ptr<>` has no `release()` method.  How is this going to work?

I think that for now, it would probably make sense to just remove this and not have any way to set the EE instance on a per-channel or per-server basis.  We can add that later, since it will be a lot easier once we eliminate the iomgr API (which is why the roadmap doc doesn't list this step until later).
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_event_engine.cc, line 24 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvjC17B6tuEnSyHli9:-MYvjC17B6tuEnSyHliA:bghcusq) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_event_engine.cc#L24)):*
> ```cpp
> namespace grpc_core {
> 
> std::unique_ptr<GrpcPolledFdFactory> NewGrpcPolledFdFactory(
> ```

Instead of trying to adapt the c-ares code to EventEngine, I suggest simply changing the code that uses c-ares to not be enabled when EventEngine is in use.  That way, we can just have the EE-based iomgr impl delegate DNS lookups to the EventEngine and not worry about the existing c-ares code.

https://github.com/grpc/grpc/blob/8777697c68971a00350e264c175d4adf529d7261/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L486
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper_event_engine.cc, line 22 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv51h70AqjYLf_rpeC:-MYv51h70AqjYLf_rpeD:btub99x) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper_event_engine.cc#L22)):*
> ```cpp
> 
> bool grpc_ares_query_ipv6() {
>   /* The libuv grpc code currently does not have the code to probe for this,
> ```

Isn't this going to cause problems?  I think we may have tests that rely on this.

(Ignore this if you take my suggestion elsewhere about not enabling our c-ares code if EventEngine is being used.)
___
*[src/core/lib/event_engine/resolved_address_internal.h, line 28 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv7JGRDEHamtlV-vej:-MYv7JGRDEHamtlV-vek:b-i8ocef) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/event_engine/resolved_address_internal.h#L28)):*
> ```objc
> namespace experimental {
> 
> std::string ResolvedAddressToURI(const EventEngine::ResolvedAddress* addr);
> ```

This function, unlike the two below, may still be desirable even after iomgr goes away.  However, this is a gRPC-side function, not part of the EE API, so it doesn't really belong here.  Instead, I suggest moving it to src/core/lib/iomgr/sockaddr_utils.h (which will eventually need to move out of the iomgr directory, since we'll still need it once iomgr goes away).
___
*[src/core/lib/event_engine/resolved_address_internal.h, line 30 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv7v3N4gXcCCOzYv3U:-MYv7v3N4gXcCCOzYv3V:b7nm5ao) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/event_engine/resolved_address_internal.h#L30)):*
> ```objc
> std::string ResolvedAddressToURI(const EventEngine::ResolvedAddress* addr);
> 
> EventEngine::ResolvedAddress CreateResolvedAddress(
> ```

These two functions will never be used anywhere other than in the EE-based iomgr impl.  They'll go away when iomgr does, at which point all of gRPC will be using `EventEngine::ResolvedAddress` instead of `grpc_resolved_address`.  So they should be moved to src/core/lib/iomgr/event_engine, and live in the same namespace as the code there.
___
*[src/core/lib/event_engine/resolved_address_internal.h, line 31 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvYUrR6ETWvB3elIws:-MYvYUrR6ETWvB3elIwt:b5paafy) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/event_engine/resolved_address_internal.h#L31)):*
> ```objc
> 
> EventEngine::ResolvedAddress CreateResolvedAddress(
>     const grpc_resolved_address* addr);
> ```

This parameter can be passed as a const reference instead of a pointer, since it should never be null.

Same for the next function.
___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 27 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvBFgj10zZz_mI_QQf:-MYvBFgj10zZz_mI_QQg:browonb) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.h#L27)):*
> ```objc
> #include "src/core/lib/iomgr/resource_quota.h"
> 
> struct grpc_event_engine_endpoint {
> ```

If this code wasn't purely short-lived, I'd insist on writing it in idiomatic C++ instead of adding yet more C-style code that we'll eventually need to convert to C++.  But since this will ultimately go away when iomgr does, I won't insist.

To give you an idea of how this could be done as idiomatic C++, see https://github.com/grpc/grpc/blob/master/test/core/util/mock_authorization_endpoint.h.

This same comment applies to basically every object with a C-style vtable in this PR.
___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 29 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvDKwz33sdmb4eJD9M:-MYvDKwz33sdmb4eJD9N:b-b7q3nm) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.h#L29)):*
> ```objc
> struct grpc_event_engine_endpoint {
>   grpc_endpoint base; [...]

2021-04-22 22:57 UTC, markdroth reviewed
(Came back to make one more comment I'd forgotten, then noticed a few more changes you'd made since I started reviewing...)

> Reviewed 18 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MYvnGXQEGg-BA2h3ewx:bjv7jfx)* status: all files reviewed, 42 unresolved discussions (waiting on @drfloob)

___
*[include/grpc/event_engine/event_engine.h, line 278 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv3pv59-SiLT8MJAa0:-MYvm09p52bWOGEnJ4Vx:b-mbjj6) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/include/grpc/event_engine/event_engine.h#L278)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Do we actually want to expose this as a public method for applications to use?  If so, what are the requirements in terms of when it can be called?  Can it be called only at program startup, or is it okay that refs to the old global EE instance have already been taken vai `GetDefaultEventEngine()`?  Is this call thread-safe, or does the caller have to lock `GetDefaultEventEngine()` and `SetDefaultEventEngine()`?
</blockquote></details>

Also, why does this return a status?  In what situation would this fail?
___
*[include/grpc/event_engine/event_engine.h, line 278 at r4](https://reviewable.io/reviews/grpc/grpc/26026#-MYvmQ8BBc-R3JE6OzqI:-MYvmQ8BBc-R3JE6OzqJ:b-s5e716) ([raw file](https://github.com/grpc/grpc/blob/3fa14a8d62c2a8032105f86cc38d49e6076a1a53/include/grpc/event_engine/event_engine.h#L278)):*
> ```objc
>   ///
>   /// If this method returns a non-OK status, errors are expected to be
>   /// unrecoverable. For example, gRPC's previous I/O implementation could have
> ```

This API should not discuss "gRPC's previous I/O implementation".  People approaching this for the first time are not going to know or care about that, since it has nothing to do with this API.
___
*[include/grpc/event_engine/event_engine.h, line 279 at r4](https://reviewable.io/reviews/grpc/grpc/26026#-MYvmggR8BHnX_-xjJmM:-MYvmggR8BHnX_-xjJmN:bpkae6a) ([raw file](https://github.com/grpc/grpc/blob/3fa14a8d62c2a8032105f86cc38d49e6076a1a53/include/grpc/event_engine/event_engine.h#L279)):*
> ```objc
>   /// If this method returns a non-OK status, errors are expected to be
>   /// unrecoverable. For example, gRPC's previous I/O implementation could have
>   /// warned callers about leaked memory if memory could not be freed within a
> ```

The current implementation waits for a while before declaring this memory to be leaked.  Does that imply that this `Shutdown()` method is expected to be blocking?  That seems a little sub-optimal.

This might be good justification for adding that on-complete callback.  But if we do leave this as-is, we need to *very* clearly document the fact that this is a blocking call and may not return for a while.
___
*[include/grpc/event_engine/event_engine.h, line 293 at r4](https://reviewable.io/reviews/grpc/grpc/26026#-MYvmAl9-D_ySKCUP4R5:-MYvmAl9-D_ySKCUP4R6:bsaxads) ([raw file](https://github.com/grpc/grpc/blob/3fa14a8d62c2a8032105f86cc38d49e6076a1a53/include/grpc/event_engine/event_engine.h#L293)):*
> ```objc
> 
> // Compulsory virtual destructor definitions.
> EventEngine::~EventEngine(){};
> ```

These should be defined inline in the class definitions above (e.g., instead of saying `virtual ~Endpoint() = 0;`, you should say `virtual ~Endpoint() = default;`).


<!-- Sent from Reviewable.io -->

2021-04-23 16:25 UTC, drfloob reviewed
Thank you for the review, Mark! I'm going to respond to your comments in batches as I go through to keep the discussion moving in case some of these take time to work through.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MYzUWL5AweA6jHfUOpJ:bpr2xg7)* status: all files reviewed, 42 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 17 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv3aLR56BCGgmfjLet:-MYvvmWB1ecBe72Ydi9O:b-t9mauz) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/include/grpc/event_engine/event_engine.h#L17)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this needed?  Where is it being set, and what does it being set indicate?

I see this in a number of files.  The purpose isn't clear to me overall, but even if it is needed for some reason, I don't think it should be needed in these public header files.  The EventEngine API itself should be able to be defined regardless of whether we're using it anywhere.
</blockquote></details>

The macro is used to both enable compilation of EE iomgr code, and disable compilation of other code (posix-specific I/O code in most cases). For example, mutual exclusion between platform types is required for things like src/core/lib/iomgr/sockaddr.h to work, which is set up in src/core/lib/iomgr/port.h. But you're right, it should not be in the public interfaces, I've removed those.

As for how it is used, note the build command in the pull request's description: `bazel build --cxxopt='-DGRPC_EVENT_ENGINE_TEST' <targets>`. Do you recommend we approach EventEngine builds in another way?
___
*[include/grpc/event_engine/event_engine.h, line 278 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv3pv59-SiLT8MJAa0:-MYw4EYX7ov9sSxol-Ez:b-2ki9ub) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/include/grpc/event_engine/event_engine.h#L278)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Also, why does this return a status?  In what situation would this fail?
</blockquote></details>

I've removed it, it should not be part of the stable public API. We'll likely enable the libuv EventEngine via compiler flag, and not handle runtime configurability at all for at least the first incarnation of the iomgr EventEngine implementation, the iomgr API complicates it a bit.
___
*[include/grpc/event_engine/event_engine.h, line 278 at r4](https://reviewable.io/reviews/grpc/grpc/26026#-MYvmQ8BBc-R3JE6OzqI:-MYw43oR4t_HwvyChEco:busl3yl) ([raw file](https://github.com/grpc/grpc/blob/3fa14a8d62c2a8032105f86cc38d49e6076a1a53/include/grpc/event_engine/event_engine.h#L278)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This API should not discuss "gRPC's previous I/O implementation".  People approaching this for the first time are not going to know or care about that, since it has nothing to do with this API.
</blockquote></details>

Done. I've made it more general.
___
*[include/grpc/event_engine/event_engine.h, line 279 at r4](https://reviewable.io/reviews/grpc/grpc/26026#-MYvmggR8BHnX_-xjJmM:-MYw4O3U3dA1HcMKCqpT:b-e542oc) ([raw file](https://github.com/grpc/grpc/blob/3fa14a8d62c2a8032105f86cc38d49e6076a1a53/include/grpc/event_engine/event_engine.h#L279)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The current implementation waits for a while before declaring this memory to be leaked.  Does that imply that this `Shutdown()` method is expected to be blocking?  That seems a little sub-optimal.

This might be good justification for adding that on-complete callback.  But if we do leave this as-is, we need to *very* clearly document the fact that this is a blocking call and may not return for a while.
</blockquote></details>

Yes, it was intended to be a blocking call, mirroring the current iomgr implementation. I'm not sure what situations within gRPC currently rely on shutdown being a blocking call, but I had a hunch we'd figure out why before long (once we can exercise an implementation). I agree though, I've added the on_shutdown_complete callback argument, and we'll see if we run into any issues with that approach.
___
*[include/grpc/event_engine/event_engine.h, line 293 at r4](https://reviewable.io/reviews/grpc/grpc/26026#-MYvmAl9-D_ySKCUP4R5:-MYw8R4D6pcYg7At472e:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3fa14a8d62c2a8032105f86cc38d49e6076a1a53/include/grpc/event_engine/event_engine.h#L293)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These should be defined inline in the class definitions above (e.g., instead of saying `virtual ~Endpoint() = 0;`, you should say `virtual ~Endpoint() = default;`).
</blockquote></details>

Done.
___
*[include/grpc/impl/codegen/grpc_types.h, line 420 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv4KxoCbIm6l4uhGer:-MYw8Xs3DHw3hWqfFt25:b7a3dw9) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/include/grpc/impl/codegen/grpc_types.h#L420)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can't store a `shared_ptr<>` in a channel arg, and `std::shared_ptr<>` has no `release()` method.  How is this going to work?

I think that for now, it would probably make sense to just remove this and not have any way to set the EE instance on a per-channel or per-server basis.  We can add that later, since it will be a lot easier once we eliminate the iomgr API (which is why the roadmap doc doesn't list this step until later).
</blockquote></details>

Good catch, that snuck back in accidentally from the earlier interface PR. To your second point, I wholeheartedly agree (see my comment above). It'd add some non-trivial complexity to make per-channel/-server EventEngines work with iomgr as it is.
___
*[src/core/lib/event_engine/resolved_address_internal.h, line 28 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv7JGRDEHamtlV-vej:-MYw9AIkCtjj_7-AwmHM:bqx1y17) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/event_engine/resolved_address_internal.h#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This function, unlike the two below, may still be desirable even after iomgr goes away.  However, this is a gRPC-side function, not part of the EE API, so it doesn't really belong here.  Instead, I suggest moving it to src/core/lib/iomgr/sockaddr_utils.h (which will eventually need to move out of the iomgr directory, since we'll still need it once iomgr goes away).
</blockquote></details>

The src/core/lib/event_engine folder will stick around after iomgr.
The src/core/lib/iomgr/event_engine folder will not.

This is essentially an internal ToString for ResolvedAddress, which I think is generally useful and should stick around as you said. I'm treating it as a non-friend, non-member function that is part of ResolvedAddress, so I feel it does belong here. I thought of making it a public method instead (with no guarantee of any particular string format), but given Hyrum's law, I'm not sure I'd want to expose something vaguely parseable that we don't want to support.

Looking at sockaddr_utils.h, I see what you mean about these functions belonging together. These functions will need to be rewritten to work with ResolvedAddress, but they'll be essentially non-friend non-member functions.  For now, I'd prefer to keep the EventEngine work separate, and we can unify this code later when we remove grpc_resolved_address. How does that sound?
___
*[src/core/lib/event_engine/resolved_address_internal.h, line 30 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv7v3N4gXcCCOzYv3U:-MYwCGK46bTR-m7oHb0R:b-wbvv [...]

2021-04-23 19:49 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: 9 of 44 files reviewed, 42 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_event_engine.cc, line 24 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvjC17B6tuEnSyHli9:-MYzfjsYA_UfF7rBg7El:b14f308) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_event_engine.cc#L24)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of trying to adapt the c-ares code to EventEngine, I suggest simply changing the code that uses c-ares to not be enabled when EventEngine is in use.  That way, we can just have the EE-based iomgr impl delegate DNS lookups to the EventEngine and not worry about the existing c-ares code.

https://github.com/grpc/grpc/blob/8777697c68971a00350e264c175d4adf529d7261/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L486
</blockquote></details>

I've disabled ares in port_platform for EventEngine builds via `#define GRPC_ARES 0`. This code here is a hack to get `//test/core/...` to build, which it still does not for multiple reasons. For example, tests that are not built for windows or mac then assume a posix iomgr, which is no longer a good assumption. A broader cleanup here might be necessary. One option is to add exclusions to the BUILD files for EventEngine builds (e.g. `tags = ["no_event_engine"]`) for all tests that expect posix.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper_event_engine.cc, line 22 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv51h70AqjYLf_rpeC:-MYzjGX540Y5rapsvLEr:b9nctgn) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper_event_engine.cc#L22)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Isn't this going to cause problems?  I think we may have tests that rely on this.

(Ignore this if you take my suggestion elsewhere about not enabling our c-ares code if EventEngine is being used.)
</blockquote></details>

See above. I don't have a great solution yet, but IIUC this will not be used if GRPC_ARES=0.
___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 27 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvBFgj10zZz_mI_QQf:-MYzjQrQAY_Ew7atsAyZ:b-g6birb) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.h#L27)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If this code wasn't purely short-lived, I'd insist on writing it in idiomatic C++ instead of adding yet more C-style code that we'll eventually need to convert to C++.  But since this will ultimately go away when iomgr does, I won't insist.

To give you an idea of how this could be done as idiomatic C++, see https://github.com/grpc/grpc/blob/master/test/core/util/mock_authorization_endpoint.h.

This same comment applies to basically every object with a C-style vtable in this PR.
</blockquote></details>

Understood. To lower (at least my own) cognitive overhead for implementing an iomgr platform, I opted to mirror the current conventions. I feel the consistency in implementation is worth adding less-than-ideal C-style code ... it makes comparison between the handful of current implementations easier as well.
___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 29 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvDKwz33sdmb4eJD9M:-MYzkpWw4Js_LiG-kXu7:b66epzv) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.h#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This makes me realize that we haven't defined the ownership model for `EventEngine::Endpoint`.  Both `OnConnectCallback` and `AcceptCallback` provide a raw pointer to the new endpoint, but they don't say anything about ownership.

We should probably change those two callback types to take `std::unique_ptr<Endpoint>` instead of `Endpoint*`, and we should use the same type here.
</blockquote></details>

The ownership transfer is documented for both OnConnectCallback (https://github.com/grpc/grpc/blob/master/include/grpc/event_engine/event_engine.h#L147-L149) and the AcceptCallback (https://github.com/grpc/grpc/blob/master/include/grpc/event_engine/event_engine.h#L155-L158). It looks like our previous conversation history has been deleted on this already. Regardless, I've changed it to be a unique_ptr and removed those ownership transfer comments.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 124 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvKOCp30JvYJb17BE7:-MZ-1Cv97lQwW-RtZ0xs:b9wlaz1) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.cc#L124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be done more simply:

```
grpc_resource_quota* resource_quota =
    grpc_channel_args_find_pointer<grpc_resource_quota>(channel_args, GRPC_ARG_RESOURCE_QUOTA);
if (resource_quota != nullptr) {
  grpc_resource_quota_ref_internal(resource_quota);  // But see my comment below...
} else {
  resource_quota = grpc_resource_quota_create(nullptr);
}
```

In general, we should not be iterating over channel args in order.  We have a few places in the code where we're doing that today, and I'd really like to get rid of them, because there are some cases where there are actually duplicate entries, and the code today does things differently in terms of which one wins.  I'd eventually like to change channel args to be a `std::map<>` internally, in which case duplicate entries would not be possible.  Using functions like `grpc_channel_args_find_pointer<>()` will make it easier to eventually do that.
</blockquote></details>

Awesome, that's a handy search function. You're right, we don't need to take the extra internal ref, the resource_user creation and destruction does quota reffing & unreffing as well.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 130 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvMfXB93rrGhLgmcv9:-MZ-1umuBko7lYzKPuxY:bzd6zrr) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.cc#L130)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We're winding up with a ref to this resource quota.  Where is that ref being released?  Maybe we don't actually need to take a ref here?
</blockquote></details>

Done. See above.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 60 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvb5bECkRp_UF3RGKS:-MZ-2MeWCULCyuXIcne9:bqsuokd) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'm not sure I'm interpretting this question correctly, but if you're asking whether you need to explicitly store the error in `closure->error_data.error`, the answer is no.  Passing the error to `Closure::Run()` as you're currently doing is all that's needed.
</blockquote></details>

Sort of the reverse. The thought was whether the error passed to `Closure::Run` should include whatever error already existed in the closure data, using something like `grpc_error_add_child` to the error we create with `absl_status_to_grpc_error`. My assumption here was that there won't be any existing errors on the closure (probably none we care abo [...]

2021-04-23 23:16 UTC, markdroth reviewed
This is moving in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 35 of 35 files at r5, 10 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MZ00D8h9goROK1b2x3y:b-k1b92a)* status: all files reviewed, 23 unresolved discussions (waiting on @apolcyn, @drfloob, and @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 17 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv3aLR56BCGgmfjLet:-MZ-73aC8yTujx5fjf3F:bdy3zhy) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/include/grpc/event_engine/event_engine.h#L17)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

The macro is used to both enable compilation of EE iomgr code, and disable compilation of other code (posix-specific I/O code in most cases). For example, mutual exclusion between platform types is required for things like src/core/lib/iomgr/sockaddr.h to work, which is set up in src/core/lib/iomgr/port.h. But you're right, it should not be in the public interfaces, I've removed those.

As for how it is used, note the build command in the pull request's description: `bazel build --cxxopt='-DGRPC_EVENT_ENGINE_TEST' <targets>`. Do you recommend we approach EventEngine builds in another way?
</blockquote></details>

I'll leave it up to @nicolasnoble as to the best way to trigger EE builds in the short term.  If he's happy with using a cpp macro that way, then I'm fine with it.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_event_engine.cc, line 24 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvjC17B6tuEnSyHli9:-MZ-z4cf9tr3HRVlw4dN:b-jyzyw6) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_event_engine.cc#L24)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

I've disabled ares in port_platform for EventEngine builds via `#define GRPC_ARES 0`. This code here is a hack to get `//test/core/...` to build, which it still does not for multiple reasons. For example, tests that are not built for windows or mac then assume a posix iomgr, which is no longer a good assumption. A broader cleanup here might be necessary. One option is to add exclusions to the BUILD files for EventEngine builds (e.g. `tags = ["no_event_engine"]`) for all tests that expect posix.
</blockquote></details>

I suspect that the right way to solve this is to move all of the c-ares code into the iomgr implementation, as we discussed with @apolcyn.  We may need to reprioritize that.
___
*[src/core/lib/event_engine/resolved_address_internal.h, line 28 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv7JGRDEHamtlV-vej:-MZ-oDpM5n3lYp3j78K2:b-xsjms8) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/event_engine/resolved_address_internal.h#L28)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

The src/core/lib/event_engine folder will stick around after iomgr.
The src/core/lib/iomgr/event_engine folder will not.

This is essentially an internal ToString for ResolvedAddress, which I think is generally useful and should stick around as you said. I'm treating it as a non-friend, non-member function that is part of ResolvedAddress, so I feel it does belong here. I thought of making it a public method instead (with no guarantee of any particular string format), but given Hyrum's law, I'm not sure I'd want to expose something vaguely parseable that we don't want to support.

Looking at sockaddr_utils.h, I see what you mean about these functions belonging together. These functions will need to be rewritten to work with ResolvedAddress, but they'll be essentially non-friend non-member functions.  For now, I'd prefer to keep the EventEngine work separate, and we can unify this code later when we remove grpc_resolved_address. How does that sound?
</blockquote></details>

I agree with you about not wanting to expose these in the public API.

I don't actually think this function is part of EventEngine any more than the current sockaddr_utils.h code is part of iomgr.  That library is just some standalone gRPC utility functions that use the iomgr API, and they'll need to be changed to use the EventEngine API instead when the time comes to eliminate the iomgr API.  So the fact that that file is currently in the iomgr tree is IMHO a mistake.  I've sent you #26077 to fix this, and I think that new library is where this new code belongs as well.

I think we're going to find that there are actually a number of things in the iomgr tree that don't really belong there.  For example, I think the call_combiner.h code should move to src/core/lib/channel, and the work_serializer.h code should move to src/core/lib/gprpp.  There are probably others that we'll find need to be cleaned up as we go.
___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 30 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv6vg3DSlibsRDMLdT:-MZ-tA4T1YVdiGYHvAlX:b-a75psk) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.h#L30)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

The iomgr APIs return string_views, so we need some non-temporary strings to reference https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/endpoint.h#L50-L51. The EE Endpoint returns ResolvedAddresses, so anything we do to convert them to strings, the result needs to be stored somewhere.

The `peer_string` and `local_address` names are used in the other iomgr implementation (posix, windows, custom). If it's all the same, I think it's worth staying consistent with the rest of iomgr since we aren't trying to shake anything up there.
</blockquote></details>

You're right about the problem of returning a string_view pointing to a temporary value; see my comment in the .cc file about this.

Please rename this field to `peer_address`.  The suffix `_string` isn't very useful, since that's implied by the type.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 67 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvCrRT5RJH4lwMNDLc:-MZ-qLx89uWSyZt-eKgo:b-jqcj4c) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.cc#L67)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

There is no EventEngine::Endpoint::Shutdown method. Do you know of situations where shutdown operations could not be handled in the Endpiont destructor?
</blockquote></details>

It looks like we're calling the method `Close()` instead of `Shutdown()`.  We should probably rename it -- the latter is what people expect it to be called.

An alternative would be to remove the `Close()` method altogether and to say that freeing the `Endpoint` object is what shuts it down.

Note that either way, though, we have to actually do *something* in this function to trigger the endpoint being shut down, because callers of the iomgr API expect that when the endpoint is shut down, any pending read or write callbacks will ~immediately be invoked with an error.  So we can either call `Close()` here, or if we decide to just say that freeing the EE endpoint is what shuts it down, then we should free the EE endpoint here.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 89 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYval1Z8d5tscLln6IF:-MZ-rZhxBGZrtZWQGorc:bd9pawl) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.cc#L89)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

What would the returned string_view be pointing to after the function ret [...]

2021-04-24 01:01 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: 42 of 45 files reviewed, 23 unresolved discussions (waiting on @apolcyn, @drfloob, and @markdroth)

___
*[src/core/lib/event_engine/resolved_address_internal.h, line 28 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv7JGRDEHamtlV-vej:-MZ03OHc2yBGlRxis3IB:b31zfn8) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/event_engine/resolved_address_internal.h#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I agree with you about not wanting to expose these in the public API.

I don't actually think this function is part of EventEngine any more than the current sockaddr_utils.h code is part of iomgr.  That library is just some standalone gRPC utility functions that use the iomgr API, and they'll need to be changed to use the EventEngine API instead when the time comes to eliminate the iomgr API.  So the fact that that file is currently in the iomgr tree is IMHO a mistake.  I've sent you #26077 to fix this, and I think that new library is where this new code belongs as well.

I think we're going to find that there are actually a number of things in the iomgr tree that don't really belong there.  For example, I think the call_combiner.h code should move to src/core/lib/channel, and the work_serializer.h code should move to src/core/lib/gprpp.  There are probably others that we'll find need to be cleaned up as we go.
</blockquote></details>

SGTM. Thanks for starting that cleanup of iomgr! I'll move this function to the new address_utils folder you've created in #26077 after it's been merged.
___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 30 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv6vg3DSlibsRDMLdT:-MZ041m39VU_Bepnnkiz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You're right about the problem of returning a string_view pointing to a temporary value; see my comment in the .cc file about this.

Please rename this field to `peer_address`.  The suffix `_string` isn't very useful, since that's implied by the type.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 67 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvCrRT5RJH4lwMNDLc:-MZ06Ify8xmy9GgrAW23:b1yroki) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.cc#L67)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like we're calling the method `Close()` instead of `Shutdown()`.  We should probably rename it -- the latter is what people expect it to be called.

An alternative would be to remove the `Close()` method altogether and to say that freeing the `Endpoint` object is what shuts it down.

Note that either way, though, we have to actually do *something* in this function to trigger the endpoint being shut down, because callers of the iomgr API expect that when the endpoint is shut down, any pending read or write callbacks will ~immediately be invoked with an error.  So we can either call `Close()` here, or if we decide to just say that freeing the EE endpoint is what shuts it down, then we should free the EE endpoint here.
</blockquote></details>

Ah, my mistake. So we've already changed the Client & Listener APIs to return `unique_ptr<Endpoint>`s. In searching the code, it seems that endpoint shutdown is almost always followed immediately by destroy (with some TODOs to eliminate the need for that two-step process https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/server/chttp2_server.cc#L395-L398).

While it may be a bit unfriendly in the iomgr world, I'd lean towards saying that EventEngine-iomgr endpoint operations have undefined behavior if they're called after endpoint shutdown. That way we can simply free the Endpoint in `endpoint_shutdown` and remove the `Endpoint::Close/Shutdown` method from the EventEngine API. I've coded that up, let me know what you think.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 89 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYval1Z8d5tscLln6IF:-MZ0NqsS39SIbhawdN-I:b-iry7x8) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.cc#L89)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You're right.  However, we have exactly this problem in `endpoint_get_local_address()`, where we're returning a string_view pointing to a local string temporary variable.  However we handle this, we need to do the same thing in both `endpoint_get_peer()` and `endpoint_get_local_address()`.

I think the cleanest way of doing this would probably be to treat the `peer_string` and `local_address` fields as simple caches, using something like this:

```
if (eeep->peer_string.empty()) {
  const EventEngine::ResolvedAddress* address = eeep->endpoint->GetPeerAddress();
  eeep->peer_string = ResolvedAddressToURI(*address);
}
return eeep->peer_string;
```

Same thing for the local address.
</blockquote></details>

Done, thanks
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 131 at r6](https://reviewable.io/reviews/grpc/grpc/26026#-MZ-ztSm57pKOKb1I2K4:-MZ0DmF3Dd-zSFYe80g5:b-onptoe) ([raw file](https://github.com/grpc/grpc/blob/c3321f2919d4a622ab0707a5d971ba8d130bd8e0/src/core/lib/iomgr/event_engine/endpoint.cc#L131)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In this case, you're creating a new resource quota, which you're holding a ref to.  You'll need to release that ref before returning to avoid a leak.
</blockquote></details>

Right, thanks. This part now takes a ref of any existing RQ if one is found, or creates a new RQ, then unreffs that RQ before returning.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 58 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvb-0H8RB6bjNmF25B:-MZ0NwLRBfaKlEP92WNz:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per my comments in the endpoint code, I don't think this is necessary.
</blockquote></details>

Removed.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 62 at r5](https://reviewable.io/reviews/grpc/grpc/26026#-MZ-tcUXCsI0etWhH2Ng:-MZ0NxOZ4zMQALMxo3RJ:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/18c103509b81230301dd6f6effe15e376803bf16/src/core/lib/iomgr/event_engine/tcp.cc#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This won't be necessary if you take my suggestion elsewhere about treating this field as a cache.
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2021-04-27 18:36 UTC, markdroth reviewed
> Reviewed 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: all files reviewed, 22 unresolved discussions (waiting on @apolcyn, @drfloob, and @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 116 at r7](https://reviewable.io/reviews/grpc/grpc/26026#-MZJZuq6AamHeqHZtNxX:-MZJZuq7CWSjQfRgAXwH:b-2unjhs) ([raw file](https://github.com/grpc/grpc/blob/02de7a4e80dfc8462c67937d9232405771dc5906/include/grpc/event_engine/event_engine.h#L116)):*
> ```objc
>   class Endpoint {
>    public:
>     /// The Endpoint descructor is responsible for shutting down all connections
> ```

s/descructor/destructor/
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 67 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvCrRT5RJH4lwMNDLc:-MZJ_OY3Dk-hxe61piU4:btgznv3) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.cc#L67)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Ah, my mistake. So we've already changed the Client & Listener APIs to return `unique_ptr<Endpoint>`s. In searching the code, it seems that endpoint shutdown is almost always followed immediately by destroy (with some TODOs to eliminate the need for that two-step process https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/server/chttp2_server.cc#L395-L398).

While it may be a bit unfriendly in the iomgr world, I'd lean towards saying that EventEngine-iomgr endpoint operations have undefined behavior if they're called after endpoint shutdown. That way we can simply free the Endpoint in `endpoint_shutdown` and remove the `Endpoint::Close/Shutdown` method from the EventEngine API. I've coded that up, let me know what you think.
</blockquote></details>

This approach looks good!

I think the behavior should be (for both iomgr and EventEngine APIs) that if any operation is attempted on an endpoint that has been shut down, that operation should immediately fail.  In this code, that means failing if `eeep->endpoint` is null.  For `endpoint_get_peer()` and `endpoint_get_local_address()`, you can just return an empty string.  For `endpoint_read()` and `endpoint_write()`, you can immediately invoke the callback with an error.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 137 at r7](https://reviewable.io/reviews/grpc/grpc/26026#-MZJ_wFZDubdFOsw5tgO:-MZJ_wF_30nO-t68Oj-M:b-j9cg5o) ([raw file](https://github.com/grpc/grpc/blob/02de7a4e80dfc8462c67937d9232405771dc5906/src/core/lib/iomgr/event_engine/endpoint.cc#L137)):*
> ```cpp
>   auto endpoint = new grpc_event_engine_endpoint;
>   endpoint->base.vtable = &grpc_event_engine_endpoint_vtable;
>   endpoint->peer_address = std::string(peer_address);
> ```

We don't need to set this here, because it will be obtained via `eeep->endpoint->GetPeerAddress()` in `endpoint_get_peer()`.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 138 at r7](https://reviewable.io/reviews/grpc/grpc/26026#-MZJa6pgAbr5WcIHhc0v:-MZJa6pgAbr5WcIHhc0w:bmd3xdu) ([raw file](https://github.com/grpc/grpc/blob/02de7a4e80dfc8462c67937d9232405771dc5906/src/core/lib/iomgr/event_engine/endpoint.cc#L138)):*
> ```cpp
>   endpoint->base.vtable = &grpc_event_engine_endpoint_vtable;
>   endpoint->peer_address = std::string(peer_address);
>   endpoint->local_address = "";
> ```

This does not need to be explicitly set to the empty string, since that's the default value for a `std::string`.


<!-- Sent from Reviewable.io -->

2021-04-28 02:26 UTC, drfloob reviewed
Progress continues! I've tackled half of the remaining feedback issues, and will continue with the rest this week.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MZLGxgW5x0VDQAlx-dS:b-qkx8u5)* status: all files reviewed, 22 unresolved discussions (waiting on @apolcyn, @drfloob, and @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 116 at r7](https://reviewable.io/reviews/grpc/grpc/26026#-MZJZuq6AamHeqHZtNxX:-MZKa1WT9Iew34l4Kq6E:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/02de7a4e80dfc8462c67937d9232405771dc5906/include/grpc/event_engine/event_engine.h#L116)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/descructor/destructor/
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 67 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvCrRT5RJH4lwMNDLc:-MZKtF9U7CI5p2-zJ4SR:b-yd956f) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.cc#L67)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This approach looks good!

I think the behavior should be (for both iomgr and EventEngine APIs) that if any operation is attempted on an endpoint that has been shut down, that operation should immediately fail.  In this code, that means failing if `eeep->endpoint` is null.  For `endpoint_get_peer()` and `endpoint_get_local_address()`, you can just return an empty string.  For `endpoint_read()` and `endpoint_write()`, you can immediately invoke the callback with an error.
</blockquote></details>

Done, thanks. I've added these shutdown checks to the endpoint stubs
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 137 at r7](https://reviewable.io/reviews/grpc/grpc/26026#-MZJ_wFZDubdFOsw5tgO:-MZL0b6f-Wus87xhRPMM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/02de7a4e80dfc8462c67937d9232405771dc5906/src/core/lib/iomgr/event_engine/endpoint.cc#L137)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We don't need to set this here, because it will be obtained via `eeep->endpoint->GetPeerAddress()` in `endpoint_get_peer()`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 138 at r7](https://reviewable.io/reviews/grpc/grpc/26026#-MZJa6pgAbr5WcIHhc0v:-MZL0bMs2nk_ogj2IVjE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/02de7a4e80dfc8462c67937d9232405771dc5906/src/core/lib/iomgr/event_engine/endpoint.cc#L138)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This does not need to be explicitly set to the empty string, since that's the default value for a `std::string`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 99 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvcD294gMlGGJr6hzs:-MZL2gBIBbtuJOf_QbfS:bquffcu) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L99)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This looks wrong to me.  If the method returns a non-OK status, that means that it failed *synchronously*, so there's no reason we should expect the callback to be invoked.  Otherwise, it's basically returning the same status twice, once as the return value and a second time via the callback, which is redundant.

I think it should only return the status once.  I see two ways of doing this:

1. The return value only indicates whether or not there was a failure in the synchronous part of the processing (i.e., before `Connect()` returned).  If there was a failure at that point, it will return the failure immediately, and it will not invoke the callback later.  Otherwise (if the synchronous part of the processing completed successfully), it will invoke the callback later with the real status (which may or may not be OK, depending on what happens during the async part of the processing).
2. We change the return value to `void`, and the only way for it to return status is by invoking the callback, which it will always do.

I'm assuming that most implementations *will* be able to fail during both the synchronous and asynchronous parts of the processing, so I would lean toward option 1.  In that case, if `Connect()` returns non-OK, we should be responsible for invoking the callback ourselves.

Whatever we decide here, this should be clarified in the EE API comments.
</blockquote></details>

Agreed. Good catch. I've coded up option 1, and I've updated the comments on the EventEngine API.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 126 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYveihY5-CmtL4Fj0A2:-MZL4N6LAWoaDDm_QDRY:b5iiz47) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L126)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead, just say:

```
auto* s = new grpc_tcp_server;
```
</blockquote></details>

Done. For background here: I opted for malloc to forego any potential overhead of calling the default constructor, and (again) to maintain consistency with the other iomgr impls. Neither are strong arguments :-P
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 127 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvfDqM124dPsBL_mcm:-MZL6_UBAb1CyNTGRo3f:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L127)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Consider moving all of this initialization into a `grpc_tcp_server` ctor.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 194 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvfWYJELIjnc7sKGBT:-MZL76eKEZiUM7CSz_aL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L194)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Once you switch to using C++ `new` and `delete` for this object, these two lines will no longer be necessary.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 198 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvf8R461gaw8s4sXHN:-MZL78un-4W1h7SmHG2P:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L198)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you use `new` to allocate this object as I suggested above, then this should just be `delete s`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 206 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvkuw_AVlPXnlzvpea:-MZLAj0r-uQFRZYVpNAb:btfycdg) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L206)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why don't other iomgr implementations do this?  I don't see this in the posix iomgr impl:

https://github.com/grpc/grpc/blob/ca945a58e9ccff69df9815bdb657c4b32e2e6b37/src/core/lib/iomgr/tcp_server_posix.cc#L545

If we do need to flush here, then flushing the existing `ExecCtx` is definitely preferable to creating a new one.  A new `ExecCtx` should be created *only* when entering C-core from the application, no where else.

But I don't think we should have to do anything that the existing iomgr impls aren't doing.
</blockquote></details>

This is also being done in `tcp_server_custom.cc`: https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/tcp_server_custom.cc#L207-L210. [...]

2021-04-28 16:15 UTC, markdroth reviewed
This is continuing to move in the right direction!  Just a few minor comments here.

Please let me know if you have any questions.  Thanks!

> Reviewed 20 of 20 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MZOFnfl586x8dDu-djS:b186lng)* status: all files reviewed, 16 unresolved discussions (waiting on @apolcyn, @drfloob, and @markdroth)

___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 89 at r8](https://reviewable.io/reviews/grpc/grpc/26026#-MZOAv-L-aAfzFinAau1:-MZOAv-L-aAfzFinAau2:b-q61izu) ([raw file](https://github.com/grpc/grpc/blob/abe0225b536674f2ff46c16197a0bf7de5363bf6/src/core/lib/iomgr/event_engine/endpoint.cc#L89)):*
> ```cpp
> // after shutdown. Do not shut down lightly.
> void endpoint_shutdown(grpc_endpoint* ep, grpc_error* why) {
>   // TODO(hork): add a mutex to the endpoint struct
> ```

I don't think this is necessary.  There will generally be only one external owner of an endpoint, so it should be the caller's responsibility to synchronize.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 101 at r8](https://reviewable.io/reviews/grpc/grpc/26026#-MZOB6ji6D8iJhUfMIE-:-MZOB6ji6D8iJhUfMIE0:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/abe0225b536674f2ff46c16197a0bf7de5363bf6/src/core/lib/iomgr/event_engine/endpoint.cc#L101)):*
> ```cpp
> 
> void endpoint_destroy(grpc_endpoint* ep) {
>   // TODO(hork): add a mutex to the endpoint struct
> ```

Same here.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 40 at r8](https://reviewable.io/reviews/grpc/grpc/26026#-MZOC1z33ZTCN9lHADF7:-MZOC1z33ZTCN9lHADF8:b-51p3mi) ([raw file](https://github.com/grpc/grpc/blob/abe0225b536674f2ff46c16197a0bf7de5363bf6/src/core/lib/iomgr/event_engine/tcp.cc#L40)):*
> ```cpp
>   grpc_tcp_server(std::unique_ptr<EventEngine::Listener> listener,
>                   std::shared_ptr<EventEngine> ee, grpc_resource_quota* rq)
>       : listener(std::move(listener)), engine(ee), resource_quota(rq) {
> ```

`std::move(ee)`
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 104 at r8](https://reviewable.io/reviews/grpc/grpc/26026#-MZOBdl_2paAEjoO50YX:-MZOBdl_2paAEjoO50YY:bd93kmv) ([raw file](https://github.com/grpc/grpc/blob/abe0225b536674f2ff46c16197a0bf7de5363bf6/src/core/lib/iomgr/event_engine/tcp.cc#L104)):*
> ```cpp
>   if (!ee->Connect(ee_on_connect, ra, ca, std::move(sa), ee_deadline).ok()) {
>     // EventEngine failed to start an asynchronous connect.
>     grpc_core::ExecCtx::Run(DEBUG_LOCATION, on_connect, GRPC_ERROR_CANCELLED);
> ```

Instead of hard-coding `GRPC_ERROR_CANCELLED`, we should pass the error returned by `Connect()`.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 133 at r8](https://reviewable.io/reviews/grpc/grpc/26026#-MZOBtRFEdoP2isFoe8-:-MZOBtRFEdoP2isFoe80:b-51p3mi) ([raw file](https://github.com/grpc/grpc/blob/abe0225b536674f2ff46c16197a0bf7de5363bf6/src/core/lib/iomgr/event_engine/tcp.cc#L133)):*
> ```cpp
>     return absl_status_to_grpc_error(listener.status());
>   }
>   *server = new grpc_tcp_server(std::move(*listener), ee, rq);
> ```

`std::move(ee)`


<!-- Sent from Reviewable.io -->

2021-04-29 03:41 UTC, drfloob reviewed
Thanks! I've tackled another ~10 feedback items, and I have a few more to go. There is still a non-trivial tcp listener implementation to write, and maybe a dozen smaller TODOs to wrap up. Some of this work would benefit from having a no-op EventEngine to unit test against (exercising the resolver callback code, for example), so I may look into that as well.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MZQgoKD0hEyA8Yh_3-g:bc7s6ov)* status: all files reviewed, 16 unresolved discussions (waiting on @apolcyn, @drfloob, and @markdroth)

___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 89 at r8](https://reviewable.io/reviews/grpc/grpc/26026#-MZOAv-L-aAfzFinAau1:-MZPEs-AElx_98r8d7tE:b-lyury) ([raw file](https://github.com/grpc/grpc/blob/abe0225b536674f2ff46c16197a0bf7de5363bf6/src/core/lib/iomgr/event_engine/endpoint.cc#L89)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is necessary.  There will generally be only one external owner of an endpoint, so it should be the caller's responsibility to synchronize.
</blockquote></details>

Done. I've added a note, even though it should not be a problem in practice.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 101 at r8](https://reviewable.io/reviews/grpc/grpc/26026#-MZOB6ji6D8iJhUfMIE-:-MZPEyXeE4--bvUIJz_U:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/abe0225b536674f2ff46c16197a0bf7de5363bf6/src/core/lib/iomgr/event_engine/endpoint.cc#L101)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/iomgr.cc, line 47 at r5](https://reviewable.io/reviews/grpc/grpc/26026#-MZ-tNIR1dCJcurOqfjG:-MZPxkwd8OqNXpGrH7Jj:b2xecp8) ([raw file](https://github.com/grpc/grpc/blob/18c103509b81230301dd6f6effe15e376803bf16/src/core/lib/iomgr/event_engine/iomgr.cc#L47)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since the iomgr shutdown is blocking, I think this function needs to use a `gpr_event` to not return until after the callback is invoked.
</blockquote></details>

Done. I've used a grpc_core::CondVar to C++-ify this, since absl::Notification isn't available to us yet.
___
*[src/core/lib/iomgr/event_engine/resolver.cc, line 45 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvUFIDBc2epsIF0w1L:-MZQOOzE5-Vh7arFtF9U:b-ajpdj6) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/resolver.cc#L45)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can be implemented as something like this:

```
// A fire-and-forget class representing an individual DNS request.
// This provides a place to store the ownership of the DNSResolver object until the request is complete.
class DnsRequest {
 public:
  DnsRequest(std::unique_ptr<EventEngine::DNSResolver> dns_resolver,
             absl::string_view address, absl::string_view default_port,
             grpc_closure* on_done, grpc_resolved_addresses** addresses)
      : dns_resolver_(std::move(dns_resolver)),
        cb_(on_done),
        addresses_(addresses) {
    // No need to save resulting TaskHandle here, since this iomgr API does not yet support cancellation.
    dns_resolver_->LookupHostname(
        absl::bind_front(OnLookupComplete, this),
        addr, default_port, absl::InfiniteFuture());
  }

 private:
  void OnLookupComplete(absl::Status status, std::vector<EventEngine::ResolvedAddress> addresses) {
    ExecCtx exec_ctx;
    // Convert addresses to iomgr form.
    *addresses_ = static_cast<grpc_resolved_addresses*>(gpr_malloc(sizeof(grpc_resolved_addresses)));
    (*addresses_)->naddrs = addresses.size();
    (*addresses_)->addrs = static_cast<grpc_resolved_address*>(gpr_malloc(sizeof(grpc_resolved_address) * addresses.size()));
    for (size_t i = 0; i < addresses.size(); ++i) {
      (*addresses_)->addrs[i] = CreateGRPCResolvedAddress(addresses[i]);
    }
    // Delete ourselves and invoke closure.
    grpc_closure* cb = cb_;
    delete this;
    Closure::Run(DEBUG_LOCATION, cb, absl_status_to_grpc_error(status));
  }

  std::unique_ptr<EventEngine::DNSResolver> dns_resolver_;
  grpc_closure* cb_;
  grpc_resolved_addresses** addresses_;
};

void resolve_address(const char* addr, const char* default_port,
                     grpc_pollset_set* /*interested_parties*/,
                     grpc_closure* on_done,
                     grpc_resolved_addresses** addresses) {
  std::shared_ptr<EventEngine> event_engine = GetDefaultEventEngine();
  auto dns_resolver = event_engine->GetDNSResolver();
  if (!dns_resolver.ok()) {
    ExecCtx::Run(DEBUG_LOCATION, on_done, absl_status_to_grpc_error(dns_resolver.status()));
    return;
  }
  new DnsRequest(std::move(*dns_resolver), addr, default_port, on_done, addresses);
}
```
</blockquote></details>

Interesting RAII-ish style! I've added this to the PR, modulo a few fixes.
___
*[src/core/lib/iomgr/event_engine/resolver.cc, line 56 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv_V5fEtjt6h_WDCkA:-MZQetBZ5qJvqFdu7CQl:bj7tgwd) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/resolver.cc#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be a wrapper around `resolve_address()` where the callback sets a `gpr_event` that this function waits for before returning the result.
</blockquote></details>

Done. I'll look into testing this with a no-op EventEngine, I think it might be worth it here.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 40 at r8](https://reviewable.io/reviews/grpc/grpc/26026#-MZOC1z33ZTCN9lHADF7:-MZPCa1A8vRfeaLW0s2D:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/abe0225b536674f2ff46c16197a0bf7de5363bf6/src/core/lib/iomgr/event_engine/tcp.cc#L40)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move(ee)`
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 104 at r8](https://reviewable.io/reviews/grpc/grpc/26026#-MZOBdl_2paAEjoO50YX:-MZPuJlj-lGDiIy9RZ3V:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/abe0225b536674f2ff46c16197a0bf7de5363bf6/src/core/lib/iomgr/event_engine/tcp.cc#L104)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of hard-coding `GRPC_ERROR_CANCELLED`, we should pass the error returned by `Connect()`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 133 at r8](https://reviewable.io/reviews/grpc/grpc/26026#-MZOBtRFEdoP2isFoe8-:-MZPCdlD-idpyVpBXNkv:b-t7v9jc) ([raw file](https://github.com/grpc/grpc/blob/abe0225b536674f2ff46c16197a0bf7de5363bf6/src/core/lib/iomgr/event_engine/tcp.cc#L133)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move(ee)`
</blockquote></details>

Good catch, saves an atomic increment/decrement.


<!-- Sent from Reviewable.io -->

2021-04-29 18:31 UTC, markdroth reviewed
This is moving along nicely!

Having a fake EventEngine to test against might be useful.  That's basically what @ctiller was suggesting the other day, when we were talking about having it provide `Now()`.  But for the moment, let's prioritize getting the real implementation done whenever we can, since that's going to be the real proof-of-concept.

Please let me know if you have any questions.  Thanks!

> Reviewed 22 of 22 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MZTqvzy5zu4OKSzE8Kz:b-jas3x4)* status: all files reviewed, 11 unresolved discussions (waiting on @apolcyn, @drfloob, and @markdroth)

___
*[BUILD, line 2686 at r9](https://reviewable.io/reviews/grpc/grpc/26026#-MZTnaaw6s3qRaD0Yx-B:-MZTnaaw6s3qRaD0Yx-C:blzmp8c) ([raw file](https://github.com/grpc/grpc/blob/4fafcd2149056ab0db643112f5bd55cc1d8b77fd/BUILD#L2686)):*
> ```Starlark
> )
> 
> # This is EventEngine-iomgr code that should be removed along with iomgr.
> ```

Why split this out into a separate target?  I'm not sure this will actually make it easier to remove this later, since we will remove this at the same time that we remove all of the iomgr code, so the removal criteria can be "anything under src/core/lib/iomgr".
___
*[src/core/lib/iomgr/event_engine/resolver.cc, line 89 at r9](https://reviewable.io/reviews/grpc/grpc/26026#-MZTq7XP9sNm874Ryz5e:-MZTq7XP9sNm874Ryz5f:b-7jinv7) ([raw file](https://github.com/grpc/grpc/blob/4fafcd2149056ab0db643112f5bd55cc1d8b77fd/src/core/lib/iomgr/event_engine/resolver.cc#L89)):*
> ```cpp
> }
> 
> static void blocking_handle_async_resolve_done(void* arg,
> ```

No need for `static`, since this is inside of an anonymous namespace.
___
*[src/core/lib/iomgr/event_engine/resolver.cc, line 102 at r9](https://reviewable.io/reviews/grpc/grpc/26026#-MZTpyLF5xJu9sR3lCc7:-MZTpyLF5xJu9sR3lCc8:b-s8j3h3) ([raw file](https://github.com/grpc/grpc/blob/4fafcd2149056ab0db643112f5bd55cc1d8b77fd/src/core/lib/iomgr/event_engine/resolver.cc#L102)):*
> ```cpp
>                     grpc_schedule_on_exec_ctx);
>   resolve_address(name, default_port, nullptr, &on_done, addresses);
>   // TODO(hork): decide on an appropriate timeout value.
> ```

This API doesn't support specifying a timeout, so `gpr_inf_future()` is fine.  We're doing the same thing for the async API by passing `absl::InfiniteFuture()` to `dns_resolver_->LookupHostname()` above.


<!-- Sent from Reviewable.io -->

2021-05-04 00:27 UTC, drfloob reviewed
Thanks for the feedback! I still have the tcp server remaining to implement, and about 20 TODO to address/cleanup/rethink.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MZol7dN-mjuULDL_3Pv:b-9h0lco)* status: 38 of 49 files reviewed, 11 unresolved discussions (waiting on @apolcyn, @drfloob, and @markdroth)

___
*[BUILD, line 2686 at r9](https://reviewable.io/reviews/grpc/grpc/26026#-MZTnaaw6s3qRaD0Yx-B:-MZoTdrKEz__BQmudIsY:bnz8oyj) ([raw file](https://github.com/grpc/grpc/blob/4fafcd2149056ab0db643112f5bd55cc1d8b77fd/BUILD#L2686)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why split this out into a separate target?  I'm not sure this will actually make it easier to remove this later, since we will remove this at the same time that we remove all of the iomgr code, so the removal criteria can be "anything under src/core/lib/iomgr".
</blockquote></details>

A matter of preference, I suppose. This is experimental code, so I wanted to maintain some sense of separation from the rest of core. It's also a bit harder now, for example, for anything else in core to accidentally depend on something internal to the EventEngine iomgr impl. I had wanted to separate it out initially, but my experimental branch became the PR branch :-).
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 43 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvOEMF-cfQBk1CYqqZ:-MZoLG9j9F5vLDr9x-S4:b-9o9wgn) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/endpoint.cc#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

For the purposes of this code, I think we can assume that we can do something like this:

```
SliceBuffer slice_buffer_wrapper(slices);
```

However, we have to pass a pointer to the `SliceBuffer` to `Endpoint::Read()`, and the object it points to needs to continue to exist until after the callback is invoked, so we can't just allocate it as a local variable that way.  So I think what we want to do is store the `SliceBuffer` object in the `grpc_event_engine_endpoint` struct, maybe using something like this to avoid dynamic allocation for every read:

```
std::aligned_storage<sizeof(SliceBuffer), alignof(SliceBuffer)> read_buffer;
```

Then the code here can be something like:

```
// Instantiate a new SliceBuffer wrapper in eeep->read_buffer.
SliceBuffer* read_buffer =
    new (&eeep->read_buffer) SliceBuffer(slices);
eeep->endpoint->Read(
    [eeep, cb](absl::Status status) {
      // Destroy SliceBuffer wrapper.
      auto* read_buffer =
          static_cast<SliceBuffer*>(&eeep->read_buffer);
      read_buffer->~SliceBuffer();
      // Invoke original callback.
      Closure::Run(DEBUG_LOCATION, cb, absl_status_to_grpc_error(status));
    },
    read_buffer, absl::InfiniteFuture());
}
```

We can use basically the same pattern for `Write()` as well.
</blockquote></details>

Done for both read & write. Thanks.
___
*[src/core/lib/iomgr/event_engine/resolver.cc, line 89 at r9](https://reviewable.io/reviews/grpc/grpc/26026#-MZTq7XP9sNm874Ryz5e:-MZUATljAvsklfOFYA9t:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4fafcd2149056ab0db643112f5bd55cc1d8b77fd/src/core/lib/iomgr/event_engine/resolver.cc#L89)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `static`, since this is inside of an anonymous namespace.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/resolver.cc, line 102 at r9](https://reviewable.io/reviews/grpc/grpc/26026#-MZTpyLF5xJu9sR3lCc7:-MZUAWJ70dKCI4WnY9hz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4fafcd2149056ab0db643112f5bd55cc1d8b77fd/src/core/lib/iomgr/event_engine/resolver.cc#L102)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This API doesn't support specifying a timeout, so `gpr_inf_future()` is fine.  We're doing the same thing for the async API by passing `absl::InfiniteFuture()` to `dns_resolver_->LookupHostname()` above.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 40 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYveXfC2W9Fhenrh_Xh:-MZZ_lJF1MdYcRY1Dv50:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L40)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `grpc_core::RefCount` instead.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 41 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYveZiSCRh8VL_GknYy:-MZZcPbl-8L-HbAalR7n:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L41)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `grpc_core::Mutex` instead.  And use lock annotations to make it clear what this mutex guards.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/timer.cc, line 36 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvgNfe-97GcnDzCWdb:-MZoRR-w4VQzrlriNMow:b-gy5y6r) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/timer.cc#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I believe that `EventEngine::TaskHandle` should fit in `void*`, since they're both basically `intptr_t`.  If so, you can probably store the task handle directly in the `timer->custom_timer` field instead of allocating a separate object.  That will improve performance.
</blockquote></details>

I've done something like that, adding a union in grpc_timer around a `custom_timer` and a `TaskHandle`. C++ does not support many of the casting contortions you'd expect would be able to cast a void* to a TaskHandle (struct, not pointer) and back, and I did not want to fight the language.


<!-- Sent from Reviewable.io -->

2021-05-04 20:25 UTC, markdroth reviewed
This is moving in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 2 files at r10, 2 of 3 files at r11, 8 of 8 files at r12.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MZt2Uf_-4zbtmfl-31n:b-k1b92a)* status: all files reviewed, 10 unresolved discussions (waiting on @apolcyn, @drfloob, and @markdroth)

___
*[BUILD, line 2686 at r9](https://reviewable.io/reviews/grpc/grpc/26026#-MZTnaaw6s3qRaD0Yx-B:-MZt1YnQ1UO28tg17I8n:btku0fi) ([raw file](https://github.com/grpc/grpc/blob/4fafcd2149056ab0db643112f5bd55cc1d8b77fd/BUILD#L2686)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

A matter of preference, I suppose. This is experimental code, so I wanted to maintain some sense of separation from the rest of core. It's also a bit harder now, for example, for anything else in core to accidentally depend on something internal to the EventEngine iomgr impl. I had wanted to separate it out initially, but my experimental branch became the PR branch :-).
</blockquote></details>

I don't think there's actually any real risk of code depending on it accidentally.  I think it would be more maintainable just to keep it part of the existing target, but I won't insist.
___
*[src/core/lib/event_engine/resolved_address_internal.h, line 28 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv7JGRDEHamtlV-vej:-MZt2PIC0ntyvB36N0kC:bkdpkza) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/event_engine/resolved_address_internal.h#L28)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

SGTM. Thanks for starting that cleanup of iomgr! I'll move this function to the new address_utils folder you've created in #26077 after it's been merged.
</blockquote></details>

It's been merged, so you should be able to proceed with this now.
___
*[src/core/lib/event_engine/slice_allocator.cc, line 33 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZstIuI10wENwhP6ps7:-MZstIuI10wENwhP6ps8:b3t6tus) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/event_engine/slice_allocator.cc#L33)):*
> ```cpp
> 
> SliceAllocator::~SliceAllocator() {
>   if (resource_user_) grpc_resource_user_unref(resource_user_);
> ```

Please say `!= nullptr`, so that it's clear to readers that this is a pointer instead of a bool.
___
*[src/core/lib/event_engine/slice_allocator.cc, line 62 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZstLcdBIAvm578QSxy:-MZstLcdBIAvm578QSxz:by2gdc8) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/event_engine/slice_allocator.cc#L62)):*
> ```cpp
> 
> SliceAllocatorFactory::~SliceAllocatorFactory() {
>   if (resource_quota_) grpc_resource_quota_unref_internal(resource_quota_);
> ```

Same here: `!= nullptr`
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 48 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZsuds19o-9DFnjLIHK:-MZsuds19o-9DFnjLIHL:b-53j1fz) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/iomgr/event_engine/tcp.cc#L48)):*
> ```cpp
>         engine(std::move(ee)),
>         resource_quota(rq) {
>     new (&refcount) grpc_core::RefCount(
> ```

No need to use placement-new here.  Instead, just pass the parameters in the initializer list:

```
grpc_tcp_server(std::unique_ptr<EventEngine::Listener> listener,
                std::shared_ptr<EventEngine> ee, grpc_resource_quota* rq)
    : refcount(1, GRPC_TRACE_FLAG_ENABLED(grpc_tcp_trace) ? "tcp" : nullptr),
      listener(std::move(listener)),
      engine(std::move(ee)),
      resource_quota(rq) {
```
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 68 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZswXLV8fIQxyrc7NZt:-MZswXLV8fIQxyrc7NZu:b4ql74x) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/iomgr/event_engine/tcp.cc#L68)):*
> ```cpp
> 
> #ifndef NDEBUG
> #define TCP_UNREF(tcp, reason) tcp_unref((tcp), (reason), DEBUG_LOCATION)
> ```

I don't think any of this macro machinery is actually necessary.  `DebugLocation` is a no-op in non-debug builds, so we can pass it unconditionally, and the right thing will happen.

I think all we need here is:

```
grpc_tcp_server* tcp_server_ref(grpc_tcp_server* s) {
  s->refcount.Ref(DEBUG_LOCATION, "server ref");
  return s;
}

void tcp_server_unref(grpc_tcp_server* s) {
  if (GPR_UNLIKELY(s->refcount.Unref(DEBUG_LOCATION, "server unref"))) {
    delete s;
  }
}
```
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 223 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZsz4He9xugzIKI39WJ:-MZsz4He9xugzIKI39WK:bpddjce) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/iomgr/event_engine/tcp.cc#L223)):*
> ```cpp
> }
> 
> void tcp_server_destroy(grpc_tcp_server* s) { delete s; }
> ```

I don't think this function is needed.  I think `tcp_server_unref()` should just do the deletion directly.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 225 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZsxiOVC52TkG6kFJQN:-MZsxiOW7XG8fr20TPft:bc1ba06) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/iomgr/event_engine/tcp.cc#L225)):*
> ```cpp
> void tcp_server_destroy(grpc_tcp_server* s) { delete s; }
> 
> void tcp_free(grpc_tcp_server* s) {
> ```

I don't think this function is needed.  The code dealing with the `ExecCtx` can be moved into the dtor, which will be triggered directly from the `delete` statement in `tcp_server_unref()`.


<!-- Sent from Reviewable.io -->

2021-05-05 20:02 UTC, drfloob reviewed
Thanks Mark. For your patience as well :-). The pollset implementation was blocking Nico, so he is working on that currently. I've addressed many of the items below, I have a handful of TODOs left, and I will certainly uncover unfinished/broken bits as we start to get more tests working.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-MZy5z345gn403GBTSdm:b-mnr7pc)* status: all files reviewed, 10 unresolved discussions (waiting on @apolcyn and @markdroth)

___
*[src/core/lib/event_engine/resolved_address_internal.h, line 28 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYv7JGRDEHamtlV-vej:-MZtAdPvChASkdAzHxrE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/event_engine/resolved_address_internal.h#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's been merged, so you should be able to proceed with this now.
</blockquote></details>

Done.
___
*[src/core/lib/event_engine/slice_allocator.cc, line 33 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZstIuI10wENwhP6ps7:-MZtAppn94swHHS-_02Y:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/event_engine/slice_allocator.cc#L33)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please say `!= nullptr`, so that it's clear to readers that this is a pointer instead of a bool.
</blockquote></details>

Done.
___
*[src/core/lib/event_engine/slice_allocator.cc, line 62 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZstLcdBIAvm578QSxy:-MZtAq5y8D8TCHx3hcBi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/event_engine/slice_allocator.cc#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here: `!= nullptr`
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 116 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYveDvX-ZgqcDHLWhOv:-MZtNTM6857sPC7P6q7h:bt3rcm1) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L116)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Another option would be to just have the code here bufffer any callbacks from the EE Listener and then dispatch them later when the iomgr API is used to set the on-accept callback.
</blockquote></details>

We shouldn't need to buffer anything before the server is started. Along the same lines, though, I've added a callback here that relays requests to an `on_accept_internal` closure set on the `grpc_tcp_server` once the server is started.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 48 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZsuds19o-9DFnjLIHK:-MZtJEyL5bWx4Hi74d-s:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/iomgr/event_engine/tcp.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to use placement-new here.  Instead, just pass the parameters in the initializer list:

```
grpc_tcp_server(std::unique_ptr<EventEngine::Listener> listener,
                std::shared_ptr<EventEngine> ee, grpc_resource_quota* rq)
    : refcount(1, GRPC_TRACE_FLAG_ENABLED(grpc_tcp_trace) ? "tcp" : nullptr),
      listener(std::move(listener)),
      engine(std::move(ee)),
      resource_quota(rq) {
```
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 68 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZswXLV8fIQxyrc7NZt:-MZtB08u1TqNpTdGu56t:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/iomgr/event_engine/tcp.cc#L68)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think any of this macro machinery is actually necessary.  `DebugLocation` is a no-op in non-debug builds, so we can pass it unconditionally, and the right thing will happen.

I think all we need here is:

```
grpc_tcp_server* tcp_server_ref(grpc_tcp_server* s) {
  s->refcount.Ref(DEBUG_LOCATION, "server ref");
  return s;
}

void tcp_server_unref(grpc_tcp_server* s) {
  if (GPR_UNLIKELY(s->refcount.Unref(DEBUG_LOCATION, "server unref"))) {
    delete s;
  }
}
```
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 223 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZsz4He9xugzIKI39WJ:-MZtCCLy6WfhCYy7fEgT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/iomgr/event_engine/tcp.cc#L223)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this function is needed.  I think `tcp_server_unref()` should just do the deletion directly.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 225 at r12](https://reviewable.io/reviews/grpc/grpc/26026#-MZsxiOVC52TkG6kFJQN:-MZtGSVbE40ES87RPGd8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/63ea9aee0d21da49c3d203acaa1ed134bab4ba6d/src/core/lib/iomgr/event_engine/tcp.cc#L225)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this function is needed.  The code dealing with the `ExecCtx` can be moved into the dtor, which will be triggered directly from the `delete` statement in `tcp_server_unref()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-06 19:35 UTC, markdroth reviewed
I love seeing all the pieces of this being filled in!

Please let me know if you have any questions.  Thanks!

> Reviewed 30 of 30 files at r13.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-M_2AN6Y5p2IJJXsql8h:baznl1p)* status: all files reviewed, 10 unresolved discussions (waiting on @apolcyn, @drfloob, and @markdroth)

___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 42 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_23Cm-B3EYZji_ZlOi:-M_23Cm-B3EYZji_ZlOj:b-50p2mv) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/endpoint.h#L42)):*
> ```objc
> };
> 
> grpc_event_engine_endpoint* grpc_tcp_create(
> ```

Why do we need to expose two variants of this function?  And why is the return type different?
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 84 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_23UzICqisiqRCMhdV:-M_23UzICqisiqRCMhdW:b-x3p7zd) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/endpoint.cc#L84)):*
> ```cpp
>         write_buffer->~SliceBuffer();
>         // Invoke original callback.
>         grpc_core::Closure::Run(DEBUG_LOCATION, cb,
> ```

Need to declare an `ExecCtx` here too.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 116 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYveDvX-ZgqcDHLWhOv:-M_26NKK9dE3lSYBi428:b-qvr6ti) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/lib/iomgr/event_engine/tcp.cc#L116)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

We shouldn't need to buffer anything before the server is started. Along the same lines, though, I've added a callback here that relays requests to an `on_accept_internal` closure set on the `grpc_tcp_server` once the server is started.
</blockquote></details>

You're right.  This looks good, especially since you need to intercept the callback anyway to create the iomgr endpoint.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 54 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_23nsZ0OdTEJLEqOyt:-M_23nsZ0OdTEJLEqOyu:b-e1znh3) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L54)):*
> ```cpp
>     // TODO(nnoble): see if we can handle this in ~SliceAllocatorFactory
>     grpc_resource_quota_unref_internal(resource_quota);
>     grpc_core::MutexLock lock(&mu);
> ```

I don't think it's necessary to hold a lock here.  If we're in the dtor, then we know by definition that no one else is accessing any of our fields, because no one else is holding a ref to us.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 85 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_24t4qD6In7Vvp3bln:-M_24t4qD6In7Vvp3blo:b-z2ey8h) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L85)):*
> ```cpp
>           grpc_endpoint_out->endpoint = std::move(endpoint);
>         } else {
>           *endpoint_ptr = nullptr;
> ```

Don't we need to free the endpoint this points to first?  Otherwise, I think this will be a leak.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 115 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_253HH-6bqOpJGxZZK:-M_253HH-6bqOpJGxZZL:b-nbdwk9) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L115)):*
> ```cpp
>   if (!connected.ok()) {
>     // EventEngine failed to start an asynchronous connect.
>     *endpoint = nullptr;
> ```

Don't we need to destroy `ee_endpoint` first?  Otherwise, I think this will be a leak.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 136 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_25sqQ38SWxOf4drnB:-M_25sqQ38SWxOf4drnC:b-pt23ld) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L136)):*
> ```cpp
>             grpc_core::ExecCtx exec_ctx;
>             GPR_ASSERT((*server)->on_accept_internal != nullptr);
>             grpc_event_engine_endpoint* g_endpoint =
> ```

Our convention is to use the `g_` prefix for global variables (on the rare occassions we use them).  This isn't global, so it should be named differently.  I suggest calling it `iomgr_endpoint`.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 142 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_27NYE9wsIhAOAYtxE:-M_27NYE9wsIhAOAYtxF:b-q2i55n) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L142)):*
> ```cpp
>                     gpr_zalloc(sizeof(*acceptor)));
>             acceptor->from_server = *server;
>             // TODO(hork): should we add a ports() method on Listener?
> ```

I think that `grpc_tcp_server_acceptor` as a whole is used only internally; IIRC, the whole reason it was added to OSS was to support some weird handshaking edge cases we have internally.

I'd prefer not to broaden the EE API surface just to support this hacky thing that we use only internally.  Let's discuss internally and try to find a better way to handle this.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 162 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_29w_W24KoAs_-y2ar:-M_29w_W24KoAs_-y2as:bxyhi8t) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L162)):*
> ```cpp
>   server->on_accept_internal = on_accept_cb;
>   server->on_accept_internal_arg = cb_arg;
>   std::shared_ptr<EventEngine> ee = GetDefaultEventEngine();
> ```

Why do we need this here?


<!-- Sent from Reviewable.io -->

2021-05-06 21:37 UTC, drfloob reviewed
Thanks Mark! The c-ares comment is unresolved as of yet, I'm leaving the kludge there for now. Otherwise, I'll leave this PR open while I help Nico get the uv-EE impl working, this iomgr code will likely change.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-M_2arjo9Tsx4Es8O0gV:b-pp1ukw)* status: all files reviewed, 10 unresolved discussions (waiting on @apolcyn and @markdroth)

___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 42 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_23Cm-B3EYZji_ZlOi:-M_2PRjiCptnEB1ANrxi:befgxd5) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/endpoint.h#L42)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why do we need to expose two variants of this function?  And why is the return type different?
</blockquote></details>

These are only exposed internally, to be clear, and used in both tcp.cc and endpoint.cc.

The first version here creates grpc_event_engine_endpoint from an EE endpoint, which is useful for the tcp server implementation in the on_accept callback, where an EventEngine::Endpoint is created before a grpc_endpoint is created, and no new RQ or RU needs to be created - the RQ needs to be pulled from the existing SliceAllocatorFactory, RU from SliceAllocator, both of which are implementations TBD. This version is handy as an alternative constructor, and it does not really need to return a generic grpc_endpoint (though it can).

The second one (returning grpc_endpoint) creates a grpc_event_engine_endpoint from scratch before the connection is established. This method needs to be defined for gRPC to function, and it's defined in all iomgr impls. Grep for it in server_chttp2_posix.cc for example. It's used in the EE-iomgr client impl as well, when creating a new endpoint struct before the connection has been established.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 84 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_23UzICqisiqRCMhdV:-M_2S1tE6f8hSsY22aVM:b-7mdnbf) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/endpoint.cc#L84)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to declare an `ExecCtx` here too.
</blockquote></details>

Done, good catch. It existed in Nico's branch, which is why I didn't see it in testing.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 54 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_23nsZ0OdTEJLEqOyt:-M_2SgNd4yGlpD_M5lZT:b-58j7jj) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think it's necessary to hold a lock here.  If we're in the dtor, then we know by definition that no one else is accessing any of our fields, because no one else is holding a ref to us.
</blockquote></details>

Agreed, good catch. Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 85 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_24t4qD6In7Vvp3bln:-M_2ToUSDa9nSbq5gEIJ:b60r506) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't we need to free the endpoint this points to first?  Otherwise, I think this will be a leak.
</blockquote></details>

Yes, done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 115 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_253HH-6bqOpJGxZZK:-M_2W7clCilM8SM_jmzK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L115)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't we need to destroy `ee_endpoint` first?  Otherwise, I think this will be a leak.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 136 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_25sqQ38SWxOf4drnB:-M_2WIZd46N00CEc2B3b:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L136)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Our convention is to use the `g_` prefix for global variables (on the rare occassions we use them).  This isn't global, so it should be named differently.  I suggest calling it `iomgr_endpoint`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 142 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_27NYE9wsIhAOAYtxE:-M_2WOjwBIlmG91dvrU_:b-jxrpek) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L142)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think that `grpc_tcp_server_acceptor` as a whole is used only internally; IIRC, the whole reason it was added to OSS was to support some weird handshaking edge cases we have internally.

I'd prefer not to broaden the EE API surface just to support this hacky thing that we use only internally.  Let's discuss internally and try to find a better way to handle this.
</blockquote></details>

Thanks for the info! If it's internal only, we can probably handle that differently. TODO removed.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 162 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-M_29w_W24KoAs_-y2ar:-M_2WfLzBXdXYgzdzNGY:b-j414wb) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/iomgr/event_engine/tcp.cc#L162)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why do we need this here?
</blockquote></details>

We don't! Removed. It was leftover from some experimentation.


<!-- Sent from Reviewable.io -->

2021-06-11 19:23 UTC, drfloob commented
@markdroth This is ready for another review pass. Please take a look when you can.

There are a few things that are likely to change as we continue develop the libuv-based EventEngine, which I think we can handle in separate PRs:
* the likely migration away from absl::Time
* possible migration away from absl::StatusOr
* the need for c-ares integration

2021-06-15 22:46 UTC, markdroth requested changes
This is looking pretty good!  There are some things that still need to be cleaned up before we can get this merged, but overall it's shaping up nicely.

Please let me know if you have any questions.  Thanks!

> Reviewed 29 of 52 files at r15, 21 of 21 files at r16, 4 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-McGqbtP1mvsjxxwokvz:bcbxgxp)* status: all files reviewed, 39 unresolved discussions (waiting on @drfloob)

___
*[include/grpc/event_engine/event_engine.h, line 121 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGVnK-BbgdmlIK9zas:-McGVnK024msI41G0cLL:b-5atafg) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L121)):*
> ```objc
>     virtual ~Endpoint() = default;
>     /// Return the SliceAllocator's ResourceUser (for internal usage)
>     virtual void* GetResourceUser() = 0;
> ```

This should not be exposed in the API.  I think we already discussed this at one point: I think we need to change the chttp2 code to track this internally so that it does not need to be passed through the EE endpoint object.
___
*[include/grpc/event_engine/event_engine.h, line 282 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGWtWt7-B7QZ631rFH:-McGWtWt7-B7QZ631rFI:borreg2) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L282)):*
> ```objc
>   virtual ~EventEngine() = default;
> 
>   virtual bool IsWorkerThread() = 0;
> ```

Please document.
___
*[include/grpc/event_engine/event_engine.h, line 286 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGX5Gf-p-BBi-QvKey:-McGX5Gf-p-BBi-QvKez:b-fvlhw1) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L286)):*
> ```objc
>   /// Verifies that all expected config settings are correct.
>   ///
>   /// It is fine if the \a EndpointConfig contains settings that the EventEngine
> ```

This first sentence is not necessary.  The `EndpointConfig` API doesn't even allow the EE impl to tell if that's the case, so it can't possibly care.
___
*[include/grpc/event_engine/event_engine.h, line 291 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGXQo_-GYkKtktCxxx:-McGXQoa4zOaXj6WSdxN:b-grqn87) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L291)):*
> ```objc
>   /// other verifications required. If any setting is invalid, this method
>   /// should return an INVALID_ARGUMENT error.
>   virtual absl::Status IsValidEndpointConfig(const EndpointConfig& config);
> ```

Why is this method needed?  Why not just have `CreateListener()` or `Connect()` return a failure if they receive invalid settings?

In general, it's not clear to me how this API can work, since the implementation of this method will not know where the `EndpointConfig` is going to be used.  For example, let's say that an EE impl needs one argument when creating client connections but a different argument when creating a listener on the server side.  This method doesn't know which of those things the `EndpointConfig` is going to be used for, so it can't know whether the config is valid for the use-case it's going to be used for.
___
*[include/grpc/event_engine/event_engine.h, line 336 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGcsRf0NZkhtVaLbwK:-McGcsRf0NZkhtVaLbwL:b-m1f5si) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L336)):*
> ```objc
> };
> 
> std::shared_ptr<EventEngine> DefaultEventEngineFactory();
> ```

This needs to be documented.

Also, I suggest renaming it to something like `CreateDefaultEventEngine()`.
___
*[include/grpc/event_engine/slice_allocator.h, line 50 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGd2NOAmewbhzxnstN:-McGd2NOAmewbhzxnstO:bdgc48q) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/slice_allocator.h#L50)):*
> ```objc
>   ~SliceAllocator();
> 
>   void* GetResourceUser() { return resource_user_; }
> ```

As I mentioned elsewhere, this should not be exposed in this API.  We should instead fix the chttp2 code to track this internally.
___
*[include/grpc/impl/codegen/port_platform.h, line 679 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGdlhF2NWGwWTLmfQS:-McGdlhF2NWGwWTLmfQT:b-vkakrz) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/impl/codegen/port_platform.h#L679)):*
> ```objc
> #undef GPR_SUPPORT_CHANNELS_FROM_FD
> #define GRPC_ARES 0
> #endif  // GRPC_USE_EVENT_ENGINE
> ```

I think this needs to be a C-style comment, since this is a public header for C-core.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_event_engine.cc, line 24 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvjC17B6tuEnSyHli9:-McGeM9i6Tzp9Av2iYpS:b-dpcb54) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_event_engine.cc#L24)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suspect that the right way to solve this is to move all of the c-ares code into the iomgr implementation, as we discussed with @apolcyn.  We may need to reprioritize that.
</blockquote></details>

I'll resolve this for now, but as we've discussed, I think we'll need to move the c-ares code into iomgr before we can migrate to EventEngine.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 531 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGenpp-rACyoVG5qLB:-McGenpp-rACyoVG5qLC:b-dhij9m) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L531)):*
> ```cpp
>     std::shared_ptr<grpc_core::WorkSerializer> work_serializer,
>     grpc_ares_request* request) {
>   grpc_ares_ev_driver* driver = *ev_driver = new grpc_ares_ev_driver();
> ```

Why is this additional variable needed?
___
*[src/core/lib/event_engine/endpoint_config_internal.h, line 32 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGUsze7rBXILgjF0H8:-McGUsze7rBXILgjF0H9:bfpmclt) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/event_engine/endpoint_config_internal.h#L32)):*
> ```objc
>  public:
>   explicit ChannelArgsEndpointConfig(const grpc_channel_args* args)
>       : args_(args){};
> ```

No need for the trailing semicolon.

Also, please add a space before the `{`.
___
*[src/core/lib/event_engine/endpoint_config_internal.h, line 33 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGUyYg2HenLGNrMyWt:-McGUyYh5WbWiEBmaPqU:bh1xa6j) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/event_engine/endpoint_config_internal.h#L33)):*
> ```objc
>   explicit ChannelArgsEndpointConfig(const grpc_channel_args* args)
>       : args_(args){};
>   ~ChannelArgsEndpointConfig() override = default;
> ```

This isn't necessary.
___
*[src/core/lib/event_engine/endpoint_config_internal.h, line 37 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGV0DO6YvS7Ajw8Mfe:-McGV0DO6YvS7Ajw8Mff:bhi41wc) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/event_engine/endpoint_config_internal.h#L37)):*
> ```objc
> 
>  private:
>   const grpc_channel_args* args_ = nullptr;
> ```

No need to initialize to nullptr, since it will always be set by the ctor.
___
*[src/core/lib/event_engine/event_engine.cc, line 76 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGj7gr99qJPC7P3etQ:-McGj7gr99qJPC7P3etR:b-gdv234) ([raw file](https://github.co [...]

2021-06-16 01:53 UTC, ctiller reviewed
> Reviewed 1 of 30 files at r13, 1 of 52 files at r15, 7 of 21 files at r16.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: all files reviewed, 39 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 282 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGWtWt7-B7QZ631rFH:-McHUBDkDGsj9nhLfu1C:b-rhcti7) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L282)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document.
</blockquote></details>

+1, and hoping we don't actually need it.

(I'd much rather change whatever is using this than add this to the EE API)


<!-- Sent from Reviewable.io -->

2021-06-16 01:57 UTC, nicolasnoble commented
Basically, for this:

https://github.com/grpc/grpc/blob/d7954e8300006d9a5850a24f9c72a97f2c454637/src/core/lib/surface/init.cc#L220-L222

On Tue, Jun 15, 2021 at 6:53 PM Craig Tiller ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Reviewed 1 of 30 files at r13, 1 of 52 files at r15, 7 of 21 files at r16.
> *Reviewable <https://reviewable.io/reviews/grpc/grpc/26026>* status: all
> files reviewed, 39 unresolved discussions (waiting on @drfloob
> <https://github.com/drfloob> and @markdroth <https://github.com/markdroth>
> )
>
> ------------------------------
>
> *include/grpc/event_engine/event_engine.h, line 282 at r17
> <https://reviewable.io/reviews/grpc/grpc/26026#-McGWtWt7-B7QZ631rFH:-McHUBDkDGsj9nhLfu1C:b-rhcti7>
> (raw file
> <https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L282>):*
> *Previously, markdroth (Mark D. Roth) wrote…*
>
> Please document.
>
> +1, and hoping we don't actually need it.
>
> (I'd much rather change whatever is using this than add this to the EE API)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/grpc/grpc/pull/26026#pullrequestreview-684652292>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABXRXJSCVOAK5ETJRW3DURTTS77ZBANCNFSM43IZTJBA>
> .
>

2021-06-16 02:20 UTC, drfloob reviewed
Thanks Mark! I've left a few pieces of feedback unaddressed, and I'm replying now with what I have since this PR is being debated on both Reviewable and Github. I'd like to note that some of these changes will essentially need to be done twice when we merge them with the uv-ee impl branch, so we should consider which things may be deferred for the next PR to make life easier.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-McHajKL-4z76mcqn-hZ:b359abp)* status: all files reviewed, 39 unresolved discussions (waiting on @drfloob, @markdroth, and @nicolasnoble)

___
*[include/grpc/event_engine/event_engine.h, line 282 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGWtWt7-B7QZ631rFH:-McHX2U-DF-4o1h1GKFk:bnsfruf) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L282)):*
<details><summary><i>Previously, ctiller (Craig Tiller) wrote…</i></summary><blockquote>

+1, and hoping we don't actually need it.

(I'd much rather change whatever is using this than add this to the EE API)
</blockquote></details>

Pinging @nicolasnoble for libuv implementation details.
___
*[include/grpc/event_engine/event_engine.h, line 286 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGX5Gf-p-BBi-QvKey:-McHXIB19Eg4gXyRV-V1:b33tn1z) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L286)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This first sentence is not necessary.  The `EndpointConfig` API doesn't even allow the EE impl to tell if that's the case, so it can't possibly care.
</blockquote></details>

Removed. See below.
___
*[include/grpc/event_engine/event_engine.h, line 291 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGXQo_-GYkKtktCxxx:-McH5fNaEepzDWeXFyh1:bif84y6) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L291)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this method needed?  Why not just have `CreateListener()` or `Connect()` return a failure if they receive invalid settings?

In general, it's not clear to me how this API can work, since the implementation of this method will not know where the `EndpointConfig` is going to be used.  For example, let's say that an EE impl needs one argument when creating client connections but a different argument when creating a listener on the server side.  This method doesn't know which of those things the `EndpointConfig` is going to be used for, so it can't know whether the config is valid for the use-case it's going to be used for.
</blockquote></details>

Removed. The idea behind this method is to be an isolated, self-documenting bit of code that asserts which config settings some specific EE implementation supports. Given that the EventEngine API is public, this gives EE authors a way to customize their engine's behavior for use outside gRPC internals (alternatively, as we've discussed, they could add methods like CustomConnect and CustomCreateListener). It's not a robust solution for config validation, as you pointed out, but it would replace some code comments with executable code that can be tested and whatnot. I'm not married to it, it does expand the API surface for something that is not absolutely necessary ... I'm not sure we'd use it in gRPC internal code. If that reasoning changes your mind at all, let me know, otherwise it'll stay gone.
___
*[include/grpc/event_engine/event_engine.h, line 336 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGcsRf0NZkhtVaLbwK:-McH8pu4AmhzQWqyNdCM:b-a09537) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L336)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to be documented.

Also, I suggest renaming it to something like `CreateDefaultEventEngine()`.
</blockquote></details>

Pinging @nicolasnoble . Nico felt this was a more appropriate name. I believe the main argument was that this method could be creating engines, returning a singleton, or more creative things (returning some shared engine based on the thread id, for example).

This part of the API has evolved a bit since we started the uv-ee implementation. We don't have a final story for how custom _default_ EventEngines will be provided by users, which is why I removed the documentation. We discussed having application code call something like `SetDefaultEventEngineFactory` before grpc init to override the gRPC-provided default libuv-ee factory. Do you think we need to firm up that story now, or can we revisit this once we've moved on from focusing on the iomgr and reference impl code?
___
*[include/grpc/impl/codegen/port_platform.h, line 679 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGdlhF2NWGwWTLmfQS:-McHCqh5CJaeTOnGt1o_:bolrged) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/impl/codegen/port_platform.h#L679)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this needs to be a C-style comment, since this is a public header for C-core.
</blockquote></details>

Interesting. I've made the change, but there are a handful of C++-style comments in this file. I'm guessing nobody has needed to compile gRPC with a compiler that lacks C99 support. Shall we consider dropping support for C89, enforcing C99 compatibility?
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_event_engine.cc, line 24 at r3](https://reviewable.io/reviews/grpc/grpc/26026#-MYvjC17B6tuEnSyHli9:-McHFF2N27yIGY9J_A7I:bhucqhm) ([raw file](https://github.com/grpc/grpc/blob/e1a570056bd842dfa82861bd9d0a4d7fa4ca91b1/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_event_engine.cc#L24)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'll resolve this for now, but as we've discussed, I think we'll need to move the c-ares code into iomgr before we can migrate to EventEngine.
</blockquote></details>

Totally agreed. Thanks!
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 531 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGenpp-rACyoVG5qLB:-McHFYCgDtHF3Ure1g-V:bgpfbzo) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L531)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this additional variable needed?
</blockquote></details>

`ev_driver` is an output argument, so it must be here. The code beautification below is possible because of the `driver` variable.
___
*[src/core/lib/event_engine/endpoint_config_internal.h, line 32 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGUsze7rBXILgjF0H8:-McHG77r80WTYuaDqSVd:b7os5tv) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/event_engine/endpoint_config_internal.h#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the trailing semicolon.

Also, please add a space before the `{`.
</blockquote></details>

Done. Interesting that no linter/tidy/formatter complained.
___
*[src/core/lib/event_engine/endpoint_config_internal.h, line 33 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGUyYg2HenLGNrMyWt:-McHGJmKEwAPxPEFN8iB:b-owyaf6) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/event_engine/endpoint_config_internal.h#L33)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><bl [...]

2021-06-16 02:36 UTC, ctiller reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: 37 of 70 files reviewed, 39 unresolved discussions (waiting on @ctiller, @drfloob, @markdroth, and @nicolasnoble)

___
*[include/grpc/impl/codegen/port_platform.h, line 679 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGdlhF2NWGwWTLmfQS:-McHf9O5BRoe__Kp_983:b-3pcy5l) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/impl/codegen/port_platform.h#L679)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Interesting. I've made the change, but there are a handful of C++-style comments in this file. I'm guessing nobody has needed to compile gRPC with a compiler that lacks C99 support. Shall we consider dropping support for C89, enforcing C99 compatibility?
</blockquote></details>

Could our c89 compatibility test be broken?


<!-- Sent from Reviewable.io -->

2021-06-16 02:38 UTC, nicolasnoble reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: 37 of 70 files reviewed, 39 unresolved discussions (waiting on @ctiller, @drfloob, @markdroth, and @nicolasnoble)

___
*[include/grpc/event_engine/event_engine.h, line 282 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGWtWt7-B7QZ631rFH:-McHfcR36IHxNy0MrGRB:b-aqlk7p) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L282)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Pinging @nicolasnoble for libuv implementation details.
</blockquote></details>

Basically temporary measure for https://github.com/grpc/grpc/blob/d7954e8300006d9a5850a24f9c72a97f2c454637/src/core/lib/surface/init.cc#L220-L222 until we have a better way of doing this. This still needs to be designed appropriately.


<!-- Sent from Reviewable.io -->

2021-06-16 02:41 UTC, nicolasnoble reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: 37 of 70 files reviewed, 39 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 336 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGcsRf0NZkhtVaLbwK:-McHg5FJ2VxKcpwm7eB0:b-ry9gvc) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L336)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Pinging @nicolasnoble . Nico felt this was a more appropriate name. I believe the main argument was that this method could be creating engines, returning a singleton, or more creative things (returning some shared engine based on the thread id, for example).

This part of the API has evolved a bit since we started the uv-ee implementation. We don't have a final story for how custom _default_ EventEngines will be provided by users, which is why I removed the documentation. We discussed having application code call something like `SetDefaultEventEngineFactory` before grpc init to override the gRPC-provided default libuv-ee factory. Do you think we need to firm up that story now, or can we revisit this once we've moved on from focusing on the iomgr and reference impl code?
</blockquote></details>

I think we coined the word during one of our weekly meetings. This was still in flux as we were discussing how external users can handle creating the same event engine as the one and only we'd ship, and how they'd pass it down during or before grpc_init.


<!-- Sent from Reviewable.io -->

2021-06-16 02:46 UTC, nicolasnoble reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: 37 of 70 files reviewed, 39 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[include/grpc/impl/codegen/port_platform.h, line 679 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGdlhF2NWGwWTLmfQS:-McHhSjB1FjdxHGlXsDq:b78uxbc) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/impl/codegen/port_platform.h#L679)):*
<details><summary><i>Previously, ctiller (Craig Tiller) wrote…</i></summary><blockquote>

Could our c89 compatibility test be broken?
</blockquote></details>

I just checked; yes it's been broken for a little while now.


<!-- Sent from Reviewable.io -->

2021-06-16 15:20 UTC, markdroth requested changes
I'm fine with making additional changes in the follow-up PR, but we should keep things in a consistent state in this PR, so there are still a few things I'd like to see cleaned up before we can merge this.

Please let me know if you have any questions.  Thanks!

> Reviewed 33 of 33 files at r18.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-McKOkdC6IEY4MCZdz30:b9y4lm4)* status: all files reviewed, 14 unresolved discussions (waiting on @ctiller, @drfloob, and @nicolasnoble)

___
*[include/grpc/event_engine/event_engine.h, line 282 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGWtWt7-B7QZ631rFH:-McKDby4Dzu4Hlc0NkBb:b-7gfp3z) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L282)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

Basically temporary measure for https://github.com/grpc/grpc/blob/d7954e8300006d9a5850a24f9c72a97f2c454637/src/core/lib/surface/init.cc#L220-L222 until we have a better way of doing this. This still needs to be designed appropriately.
</blockquote></details>

Craig, is there a particular reason why you wouldn't want this here?  I think even our internal EventManager API has something like this, so it seems fairly common.  And it's not immediately obvious to me how it could be abused.
___
*[include/grpc/event_engine/event_engine.h, line 291 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGXQo_-GYkKtktCxxx:-McKDxZY-j2p5tsgbZ2P:bdxvpnu) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L291)):*
> The idea behind this method is to be an isolated, self-documenting bit of code that asserts which config settings some specific EE implementation supports.

Why would a user care about that?  If they pass in a setting that is not supported by the EE impl, then that setting will just be ignored, because the EE impl will not even have any way of knowing that it's there.  And that would be equally true regardless of whether the validation is done in `Connect()` and `CreateListener()` or whether it's in a separate `IsValidEndpointConfig()` method, so I don't see how adding the latter method would actually accomplish anything.

>  Given that the EventEngine API is public, this gives EE authors a way to customize their engine's behavior for use outside gRPC internals (alternatively, as we've discussed, they could add methods like CustomConnect and CustomCreateListener).

Users can customize the EE behavior for callers by passing in whatever settings are supported by the EE impl.  I don't see how the presence of this method would help with that.  I also don't see why we'd ever need separate `CustomConnect()` or `CustomCreateListener()` methods, given that the existing `Connect()` and `CreateListener()` methods already accept an `EndpointConfig`.

My main point here is that I cannot actually see any use-case where a user would want to use this method.  What would a user gain from calling this method that they would not get from just passing the same `EndpointConfig` to `Connect()` or `CreateListener()` and getting back an error?  If you can give me a concrete example of where this would help, I'm happy to reconsider, but right now I don't see one.
___
*[include/grpc/event_engine/event_engine.h, line 336 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGcsRf0NZkhtVaLbwK:-McKJgWm8KMGZd4u2QMX:b7fbnft) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L336)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

I think we coined the word during one of our weekly meetings. This was still in flux as we were discussing how external users can handle creating the same event engine as the one and only we'd ship, and how they'd pass it down during or before grpc_init.
</blockquote></details>

If you want to defer finalizing this, that's fine; in that case, just add a TODO here about finalizing the API and documenting it.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 531 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGenpp-rACyoVG5qLB:-McKOHaB8ifZ2Hxvh11S:b-wek2th) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L531)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

`ev_driver` is an output argument, so it must be here. The code beautification below is possible because of the `driver` variable.
</blockquote></details>

I don't think the existing code was that hard to read.  And in any case, this kind of code cleanup should be done in a separate PR.

Please revert the changes to this file.
___
*[src/core/lib/event_engine/endpoint_config_internal.h, line 33 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGUyYg2HenLGNrMyWt:-McKK4_cC0NCbiLqrJlM:bnj2drm) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/event_engine/endpoint_config_internal.h#L33)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Which part isn't necessary? Reviewable only highlights the whole line. If you mean the `const` on the return type, I had already removed that, but must not have pushed the change.
</blockquote></details>

I mean the whole line is not needed.  If you're not actually doing anything in the dtor, there's no need to override it.
___
*[src/core/lib/event_engine/slice_allocator.cc, line 51 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-McGjJDn3Rc8hNi1GHkY:-McKOd1uD0U6fubPuVDH:bfkonr9) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/event_engine/slice_allocator.cc#L51)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

I implemented this in the uv-ee branch where we're working on the libuv implementation, since it was needed there. PR for that work will follow this one.
</blockquote></details>

Sure, but in this PR, it's still a TODO.  You can remove the TODO in the follow-up PR where you actually implement this.
___
*[src/core/lib/iomgr/event_engine/iomgr.cc, line 35 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGmMhS3fq-vmvVvDW8:-McKKdMmEpwXYuyi-cH_:bxycll1) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/event_engine/iomgr.cc#L35)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Required by lockfree_event.cc. It's defined in the Windows iomgr as well, probably for the same reason. LockFreeEvent could likely be cleaned up to avoid this.
</blockquote></details>

Okay.  Probably not worth cleaning up at this point, since all of the iomgr code is eventually going to go away.

For now, though, please add a comment indicating that this needs to be defined by all iomgr impls, even if not actually used.
___
*[src/core/lib/surface/init.h, line 36 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGmzRQDJ7drnHvgdoK:-McKMeNV7N03wWhjGgcA:b-2dr9xu) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/surface/init.h#L36)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Thanks. This was temporary code used in the uv-ee branch.
</blockquote></details>

Note that one easy way to avoid this problem would be to do something like this in src/core/lib/iomgr/event_engine/iomgr.cc:

```
namespace {

// Note: This is a pointer to a shared_ptr, so it's trivially destructible.
std::shared_ptr<EventEngine>* g_event_engine;

void iomgr_platform_init() {
  g_event_engine = new std::shared_ptr<EventEngine>(DefaultEventEngineFactory());
 [...]

2021-06-16 17:38 UTC, ctiller reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: all files reviewed, 14 unresolved discussions (waiting on @drfloob, @markdroth, and @nicolasnoble)

___
*[include/grpc/event_engine/event_engine.h, line 282 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGWtWt7-B7QZ631rFH:-McKsikz1VhWCywIFpXL:bayh3mn) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L282)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Craig, is there a particular reason why you wouldn't want this here?  I think even our internal EventManager API has something like this, so it seems fairly common.  And it's not immediately obvious to me how it could be abused.
</blockquote></details>

Decisions based on it are going to be pretty subtle and potentially hard to debug, so if we can move the system away from needing it, I'd prefer we did that.

This code path is only for global shutdown of iomgr, which by design shouldn't interact with EventEngine, nor should it be able to access such - though I appreciate there may be an interim time where such access is necessary.

To handle this case, I'd suggest we simply launch the background cleanup thread always for event engine until we get a chance to refine that decision later?


<!-- Sent from Reviewable.io -->

2021-06-16 18:37 UTC, nicolasnoble reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: all files reviewed, 14 unresolved discussions (waiting on @drfloob, @markdroth, and @nicolasnoble)

___
*[include/grpc/event_engine/event_engine.h, line 282 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGWtWt7-B7QZ631rFH:-McL5fZT6HUPe6W5LuXG:b-224neg) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L282)):*
<details><summary><i>Previously, ctiller (Craig Tiller) wrote…</i></summary><blockquote>

Decisions based on it are going to be pretty subtle and potentially hard to debug, so if we can move the system away from needing it, I'd prefer we did that.

This code path is only for global shutdown of iomgr, which by design shouldn't interact with EventEngine, nor should it be able to access such - though I appreciate there may be an interim time where such access is necessary.

To handle this case, I'd suggest we simply launch the background cleanup thread always for event engine until we get a chance to refine that decision later?
</blockquote></details>

So I tried that originally (always launching the background cleanup thread), and things started to blow up elsewhere in grpc in lots of subtle and horrifying tsan-related manners, which I suspect means it's (1) the right thing to do and (2) requires further debugging / cleanup in the rest of grpc.

I don't mind always doing the background cleanup, but the race conditions would first need to be solved at HEAD, which is totally orthogonal.


<!-- Sent from Reviewable.io -->

2021-06-16 18:54 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: all files reviewed, 14 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 336 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGcsRf0NZkhtVaLbwK:-McKagZPANmGcmBimpKN:bkvtoki) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L336)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you want to defer finalizing this, that's fine; in that case, just add a TODO here about finalizing the API and documenting it.
</blockquote></details>

Sounds good, I've added a TODO to address it.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 531 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGenpp-rACyoVG5qLB:-McKbI461vRUeY4TKOjm:bp3aow6) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L531)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think the existing code was that hard to read.  And in any case, this kind of code cleanup should be done in a separate PR.

Please revert the changes to this file.
</blockquote></details>

Reverted.
___
*[src/core/lib/event_engine/endpoint_config_internal.h, line 33 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGUyYg2HenLGNrMyWt:-McKbPgL1_L4tw7S-IWS:b-7k7vzz) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/event_engine/endpoint_config_internal.h#L33)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I mean the whole line is not needed.  If you're not actually doing anything in the dtor, there's no need to override it.
</blockquote></details>

Dtor removed. I saw this comment attached to the `Setting Get(absl::string_view key) const override;` line in Reviewable. My mistake, Reviewable doesn't automatically switch to the appropriate revision when you navigate to the next discussion awaiting a response.
___
*[src/core/lib/event_engine/slice_allocator.cc, line 51 at r13](https://reviewable.io/reviews/grpc/grpc/26026#-McGjJDn3Rc8hNi1GHkY:-McKcCT15lw51Mj1put9:b-md4frx) ([raw file](https://github.com/grpc/grpc/blob/22d7f00b20f319bd86ece09df5699d681ba104e6/src/core/lib/event_engine/slice_allocator.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Sure, but in this PR, it's still a TODO.  You can remove the TODO in the follow-up PR where you actually implement this.
</blockquote></details>

TODO added.
___
*[src/core/lib/iomgr/exec_ctx.cc, line 32 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGjqCo9fPtxwVcm0T2:-McKdyZe3tGBEpoJtaHR:b-z88iyz) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/exec_ctx.cc#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I am really uncomfortable with this being exposed like this, since it's really an internal implementation detail of `ExecCtx`.  Why is this needed?

Also, note that if this *is* needed, then we need to give it a `grpc_` prefix or put it in the `grpc_core` namespace, or else we're exporting a public symbol in the global namespace that may conflict with applications.
</blockquote></details>

Understood, it made me a bit uncomfortable as well. The idea is to avoid having to call ExecCtx::Run in the GrpcClosureToCallback lambda:

```
EventEngine::Callback GrpcClosureToCallback(grpc_closure* closure,
                                            grpc_error_handle error) {
  return [closure, error](absl::Status status) {
    grpc_error_handle new_error =
        grpc_error_add_child(error, absl_status_to_grpc_error(status));
    exec_ctx_run(closure, new_error);
    grpc_pollset_ee_broadcast_event();
  };
}
```

When not in a debug build, `exec_ctx_run` just calls the closure and unrefs the error. That's trivial enough to duplicate here, instead of reusing the `exec_ctx_run` method. In a debug build however, `exec_ctx_run` also adds logic to `closure.scheduled` that we'd have to otherwise replicate in GrpcClosureToCallback to avoid aborts on repeated closure scheduling for example, and it adds some handy telemetry collection and logging. It seemed worth reusing that code, rather than copying it.

Caveat: this is untested, this branch hasn't been merged to the uv-ee impl branch for over a week due to the ongoing refactoring of the listener.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 35 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGluMK8impc33JrUb3:-McKc_U78OnQrG73ubTQ:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/event_engine/endpoint.cc#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per my comments elsewhere, this should be declared in a header file and included here, rather than hard-coding a forward declaration like this.
</blockquote></details>

Done
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 190 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGllVHA-yHt3FYrzTX:-McL5cEeDxT7XugTRvJR:b-j2ed0r) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/event_engine/endpoint.cc#L190)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why are we setting this here instead of letting it be handled in `endpoint_get_peer()`?
</blockquote></details>

It solves a lifetime issue: the resource_user doesn't make a copy of the name passed to it (see the line below this one).
___
*[src/core/lib/iomgr/event_engine/iomgr.cc, line 35 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGmMhS3fq-vmvVvDW8:-McKcwJjCgSON4V6eTPC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/event_engine/iomgr.cc#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  Probably not worth cleaning up at this point, since all of the iomgr code is eventually going to go away.

For now, though, please add a comment indicating that this needs to be defined by all iomgr impls, even if not actually used.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/pollset.cc, line 26 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGoEKl91REbNycta8y:-McKdBIHDRIkkyeI907W:b-3ic0vp) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/event_engine/pollset.cc#L26)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This need to be of type `gpr_cv` instead of `gpr_mu`.  (Looks like sync_abseil.h defines them both as intptr_t, which is why the compiler isn't complaining.)
</blockquote></details>

ooh, good catch. Done.
___
*[src/core/lib/surface/init.h, line 36 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGmzRQDJ7drnHvgdoK:-McL3jy193NIVZS4B4F2:b98kevl) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/surface/init.h#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Note that one easy way to avoid this problem would be to do something like this in src/core/lib/iomgr/event_engine/iomgr.cc:

```
namespace {

// Note: This is a pointer to a shared_ptr, so it's trivially destructible.
std::shared_ptr<EventEngine>* g_event_engine;

void iomgr_platform_init() {
  g_event_engine = new std::shared_ptr<EventEngine>(DefaultEventEngineFactory());
}

void iomgr_platform_shutdown() {
  grpc_core::Promise<absl::Sta [...]

2021-06-16 18:58 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: all files reviewed, 14 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/lib/iomgr/exec_ctx.cc, line 32 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGjqCo9fPtxwVcm0T2:-McLAwHX4RbaBqYf8Luk:b-973ylw) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/exec_ctx.cc#L32)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Understood, it made me a bit uncomfortable as well. The idea is to avoid having to call ExecCtx::Run in the GrpcClosureToCallback lambda:

```
EventEngine::Callback GrpcClosureToCallback(grpc_closure* closure,
                                            grpc_error_handle error) {
  return [closure, error](absl::Status status) {
    grpc_error_handle new_error =
        grpc_error_add_child(error, absl_status_to_grpc_error(status));
    exec_ctx_run(closure, new_error);
    grpc_pollset_ee_broadcast_event();
  };
}
```

When not in a debug build, `exec_ctx_run` just calls the closure and unrefs the error. That's trivial enough to duplicate here, instead of reusing the `exec_ctx_run` method. In a debug build however, `exec_ctx_run` also adds logic to `closure.scheduled` that we'd have to otherwise replicate in GrpcClosureToCallback to avoid aborts on repeated closure scheduling for example, and it adds some handy telemetry collection and logging. It seemed worth reusing that code, rather than copying it.

Caveat: this is untested, this branch hasn't been merged to the uv-ee impl branch for over a week due to the ongoing refactoring of the listener.
</blockquote></details>

Correction: " ... to properly abort on repeated closure scheduling for example ... ".

LMKWYT. If we do keep this, I'll rename it as you suggested.


<!-- Sent from Reviewable.io -->

2021-06-16 22:36 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026)* status: 48 of 71 files reviewed, 14 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 121 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGVnK-BbgdmlIK9zas:-McLejGRA_Fk7pZ0vKW4:bnhkbbh) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L121)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should not be exposed in the API.  I think we already discussed this at one point: I think we need to change the chttp2 code to track this internally so that it does not need to be passed through the EE endpoint object.
</blockquote></details>

Ignoring the EventEngine for a second: given the "RU-per-Endpoint" model we have today, and given that iomgr implementations create RUs and RQs without the transport's knowledge (for example, endpoints that are created within tcp servers are a few steps removed from any chttp2 code), if we want the transport to track Endpoint-specific RUs without accessing them _through_ the endpoints themselves, we'd probably want to invert the RU ownership and creation responsibilities in iomgr before we introduce an EventEngine at all. We'd be deprecating `grpc_endpoint_get_resource_user`, and likely making changes to the iomgr API around endpoint creation (`grpc_tcp_client_connect` and `grpc_tcp_server_create` at first glance) to accept RUs and some flavor of RU-tracking RQ wrapper that allow those resource objects to be managed externally and injected. This is in addition to changing the chttp2 code to track RUs/RQs.

There's more to think through, I'm happy to brainstorm it if you have ideas. Rethinking the "RU-per-Endpoint" model might be worthwhile.

As an alternative to the iomgr refactor, how would you feel about having `Endpoint::GetSliceAllocator()`, and adding a friend to the SliceAllocator to access the internal resource_user? It's really not ideal either, I'm aware. Chances are we couldn't remove that GetSliceAllocator method after iomgr is gone, since it'd break EventEngine implementations at that point ... I'm not sure if it'll still be experimental at that point. But that'd be a fairly small change compared to the iomgr refactor.


<!-- Sent from Reviewable.io -->

2021-06-16 23:20 UTC, ctiller commented
If we removed RU stuff, who would break?

On Wed, Jun 16, 2021, 3:36 PM AJ Heller ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> *Reviewable <https://reviewable.io/reviews/grpc/grpc/26026>* status: 48
> of 71 files reviewed, 14 unresolved discussions (waiting on @drfloob
> <https://github.com/drfloob> and @markdroth <https://github.com/markdroth>
> )
>
> ------------------------------
>
> *include/grpc/event_engine/event_engine.h, line 121 at r17
> <https://reviewable.io/reviews/grpc/grpc/26026#-McGVnK-BbgdmlIK9zas:-McLejGRA_Fk7pZ0vKW4:bnhkbbh>
> (raw file
> <https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L121>):*
> *Previously, markdroth (Mark D. Roth) wrote…*
>
> This should not be exposed in the API. I think we already discussed this
> at one point: I think we need to change the chttp2 code to track this
> internally so that it does not need to be passed through the EE endpoint
> object.
>
> Ignoring the EventEngine for a second: given the "RU-per-Endpoint" model
> we have today, and given that iomgr implementations create RUs and RQs
> without the transport's knowledge (for example, endpoints that are created
> within tcp servers are a few steps removed from any chttp2 code), if we
> want the transport to track Endpoint-specific RUs without accessing them
> *through* the endpoints themselves, we'd probably want to invert the RU
> ownership and creation responsibilities in iomgr before we introduce an
> EventEngine at all. We'd be deprecating grpc_endpoint_get_resource_user,
> and likely making changes to the iomgr API around endpoint creation (
> grpc_tcp_client_connect and grpc_tcp_server_create at first glance) to
> accept RUs and some flavor of RU-tracking RQ wrapper that allow those
> resource objects to be managed externally and injected. This is in addition
> to changing the chttp2 code to track RUs/RQs.
>
> There's more to think through, I'm happy to brainstorm it if you have
> ideas. Rethinking the "RU-per-Endpoint" model might be worthwhile.
>
> As an alternative to the iomgr refactor, how would you feel about having
> Endpoint::GetSliceAllocator(), and adding a friend to the SliceAllocator
> to access the internal resource_user? It's really not ideal either, I'm
> aware. Chances are we couldn't remove that GetSliceAllocator method after
> iomgr is gone, since it'd break EventEngine implementations at that point
> ... I'm not sure if it'll still be experimental at that point. But that'd
> be a fairly small change compared to the iomgr refactor.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/grpc/grpc/pull/26026#pullrequestreview-685721389>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNG45OWH4BAFG2IWJBM5W3TTERNZANCNFSM43IZTJBA>
> .
>

2021-06-17 00:03 UTC, drfloob commented
> If we removed RU stuff, who would break?

The public C++ ResourceQuota feature would stop working. https://github.com/grpc/grpc/blob/master/include/grpcpp/resource_quota.h. It relies on the transport's reclaimers, which rely on the ability to get RUs from the endpoints.

2021-06-17 17:55 UTC, markdroth requested changes
I don't think we need to remove the RU stuff.  I think we can easily support it without it being visible to EE implementations.

Please let me know if you have any questions.  Thanks!

> Reviewed 23 of 23 files at r19.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-McQ68OOD-4A1b6Xid0K:bv6hdsq)* status: all files reviewed, 8 unresolved discussions (waiting on @ctiller, @drfloob, and @nicolasnoble)

___
*[include/grpc/event_engine/event_engine.h, line 121 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGVnK-BbgdmlIK9zas:-McQ-Dm20_VautU2JrQB:boxb16m) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L121)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Ignoring the EventEngine for a second: given the "RU-per-Endpoint" model we have today, and given that iomgr implementations create RUs and RQs without the transport's knowledge (for example, endpoints that are created within tcp servers are a few steps removed from any chttp2 code), if we want the transport to track Endpoint-specific RUs without accessing them _through_ the endpoints themselves, we'd probably want to invert the RU ownership and creation responsibilities in iomgr before we introduce an EventEngine at all. We'd be deprecating `grpc_endpoint_get_resource_user`, and likely making changes to the iomgr API around endpoint creation (`grpc_tcp_client_connect` and `grpc_tcp_server_create` at first glance) to accept RUs and some flavor of RU-tracking RQ wrapper that allow those resource objects to be managed externally and injected. This is in addition to changing the chttp2 code to track RUs/RQs.

There's more to think through, I'm happy to brainstorm it if you have ideas. Rethinking the "RU-per-Endpoint" model might be worthwhile.

As an alternative to the iomgr refactor, how would you feel about having `Endpoint::GetSliceAllocator()`, and adding a friend to the SliceAllocator to access the internal resource_user? It's really not ideal either, I'm aware. Chances are we couldn't remove that GetSliceAllocator method after iomgr is gone, since it'd break EventEngine implementations at that point ... I'm not sure if it'll still be experimental at that point. But that'd be a fairly small change compared to the iomgr refactor.
</blockquote></details>

The chttp2 code controls creating the TCP connection.  That happens here for the server:

https://github.com/grpc/grpc/blob/9503f03aaf6a9a55bbd9880b516144db0a5fc46c/src/core/ext/transport/chttp2/server/chttp2_server.cc#L589

And here for the client:

https://github.com/grpc/grpc/blob/9503f03aaf6a9a55bbd9880b516144db0a5fc46c/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L74

The chttp2 code will therefore be able to provide its own `SliceAllocator` implementation, which can contain the associated RU.  And on the server side, it can provide its own `SliceAllocatorFactory` implementation, which knows how to create its `SliceAllocator` objects.

I am not aware of any case that would require this to be visible in any way to EE implementations.
___
*[include/grpc/event_engine/event_engine.h, line 282 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGWtWt7-B7QZ631rFH:-McQ5ekkEc8oInmrysyr:b2fu3t) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L282)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

So I tried that originally (always launching the background cleanup thread), and things started to blow up elsewhere in grpc in lots of subtle and horrifying tsan-related manners, which I suspect means it's (1) the right thing to do and (2) requires further debugging / cleanup in the rest of grpc.

I don't mind always doing the background cleanup, but the race conditions would first need to be solved at HEAD, which is totally orthogonal.
</blockquote></details>

For now, let's put a TODO here that we should consider whether we can remove this method before we de-experimentalize this API.
___
*[src/core/lib/iomgr/exec_ctx.cc, line 32 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGjqCo9fPtxwVcm0T2:-McQ0hSP-jBSMVaJVSHi:bpitvwv) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/exec_ctx.cc#L32)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Correction: " ... to properly abort on repeated closure scheduling for example ... ".

LMKWYT. If we do keep this, I'll rename it as you suggested.
</blockquote></details>

If the goal here is to replicate the debug-only guards to prevent closures from being rescheduled, I suggest just duplicating that logic.  It's not a huge amount of code anyway, and it avoids tightly coupling the `ExecCtx` and the EE-based iomgr impl.

(I might not suggest the above if any of this code was going to stick around in the long term, but I think it's fine for now.)
___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 50 at r19](https://reviewable.io/reviews/grpc/grpc/26026#-McQ26GeEh7TxOW65XAx:-McQ26GeEh7TxOW65XAy:bu44x54) ([raw file](https://github.com/grpc/grpc/blob/5d66f01671b48e2873a26ddbe613de31f15fdd48/src/core/lib/iomgr/event_engine/endpoint.h#L50)):*
> ```objc
> /// established.
> grpc_endpoint* grpc_tcp_create(const grpc_channel_args* channel_args,
>                                const char* peer_address);
> ```

Why change this from `absl::string_view` to `const char*`?

Also, I don't see the same change in the .cc file, so I don't think this will build.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 190 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGllVHA-yHt3FYrzTX:-McQ2DKfElxDIRv0Wcla:bobpuh5) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/event_engine/endpoint.cc#L190)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

It solves a lifetime issue: the resource_user doesn't make a copy of the name passed to it (see the line below this one).
</blockquote></details>

Please add a comment explaining this, since it's not obvious to the reader.
___
*[src/core/lib/iomgr/event_engine/iomgr.cc, line 64 at r19](https://reviewable.io/reviews/grpc/grpc/26026#-McQ1VSG6-Kmor_g3Ei_:-McQ1VSG6-Kmor_g3Eia:b-w8pfb9) ([raw file](https://github.com/grpc/grpc/blob/5d66f01671b48e2873a26ddbe613de31f15fdd48/src/core/lib/iomgr/event_engine/iomgr.cc#L64)):*
> ```cpp
>   auto shutdown_status = shutdown_status_promise.Get();
>   GPR_ASSERT(shutdown_status.ok());
>   delete g_event_engine;
> ```

Probably also want to reset `g_event_engine` to null, just in case some lingering callback tries to use it.
___
*[src/core/lib/surface/init.h, line 36 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGmzRQDJ7drnHvgdoK:-McQ4EDuBMXs_WDiP0t6:b-uwmwen) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/surface/init.h#L36)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Thanks. I've added something nearly identical, with the main difference being the signature change to `std::shared_ptr<EventEngine> grpc_iomgr_event_engine()`. Even though we have a singleton default EventEngine, the iomgr code expects to be working with shared_ptr<EventEngines>s; see iomgr/event_engine/tcp.cc, particularly when endpoints need to take refs on user-supplied EventEngines ... once we have a mechanism to support them, that is.
</blockquote></details>

There is no need for the code in the EE-based iomgr impl to ever hold a ref here.  We will not be able to add support for user-supplied EventEngines until after we have eliminated the iomgr code.  The iomgr API is inherently not a per-channel thing; it is global.

It does not make sense to have `grpc_iomgr_event_engine()` return a `std::shared [...]

2021-06-17 19:51 UTC, drfloob reviewed
Thanks as always, Mark! Regarding the the iomgr/chttp2 refactoring around resource users, I've added a bit more to the discussion. I'll plan to get started with the refactoring, let me know if my arguments below change your mind.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-McQVdeRDmc9BtAp6l2S:bwvfvj4)* status: all files reviewed, 8 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 121 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGVnK-BbgdmlIK9zas:-McQIx70AyFKFUEH2Gnm:b-ethbt5) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L121)):*
Well said, no argument!

> The chttp2 code will therefore be able to provide its own SliceAllocator implementation, which can contain the associated RU. And on the server side, it can provide its own SliceAllocatorFactory implementation, which knows how to create its SliceAllocator objects.

That will have to happen when me migrate the chttp2 code away from using iomgr, if not before then. The chttp2 code will ultimately be responsible for RU and RQ creation and ownership, based on the current EE design.

> I am not aware of any case that would require this to be visible in any way to EE implementations.

True, the EE itself doesn't need it, that's what I was trying to convey in the documentation's `(for internal use)` bit. Presuming the EE interface remains experimental even after we've removed iomgr, the `GetResourceUser` method should very well be temporary. Allowing the method to exist temporarily would avoid us having to do the iomgr refactor / chttp2 ownership change now, which would push the immediate EventEngine timeline back a few days, maybe a week (I need to spend time familiarizing myself with the transport code).

Having slept on it, even given the timeline slip, I'm inclined to do the refactoring anyway. Let me know if you've changed your mind on that.
___
*[include/grpc/event_engine/event_engine.h, line 282 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGWtWt7-B7QZ631rFH:-McQMOs38-MhnZ8C38We:b-md4frx) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L282)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

For now, let's put a TODO here that we should consider whether we can remove this method before we de-experimentalize this API.
</blockquote></details>

TODO added.
___
*[src/core/lib/iomgr/exec_ctx.cc, line 32 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGjqCo9fPtxwVcm0T2:-McQRHWB3Yym3kBqdiTB:b-q3wyh) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/exec_ctx.cc#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If the goal here is to replicate the debug-only guards to prevent closures from being rescheduled, I suggest just duplicating that logic.  It's not a huge amount of code anyway, and it avoids tightly coupling the `ExecCtx` and the EE-based iomgr impl.

(I might not suggest the above if any of this code was going to stick around in the long term, but I think it's fine for now.)
</blockquote></details>

Sounds good, I've copied the code over.
___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 50 at r19](https://reviewable.io/reviews/grpc/grpc/26026#-McQ26GeEh7TxOW65XAx:-McQ9QvP92jzp2iMLvYh:b-b323uu) ([raw file](https://github.com/grpc/grpc/blob/5d66f01671b48e2873a26ddbe613de31f15fdd48/src/core/lib/iomgr/event_engine/endpoint.h#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why change this from `absl::string_view` to `const char*`?

Also, I don't see the same change in the .cc file, so I don't think this will build.
</blockquote></details>

It was a mistake, leftover from a (partially) reverted change.
___
*[src/core/lib/iomgr/event_engine/endpoint.cc, line 190 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGllVHA-yHt3FYrzTX:-McQG7tvAe5ggr0fnFGS:b8irffx) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/iomgr/event_engine/endpoint.cc#L190)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment explaining this, since it's not obvious to the reader.
</blockquote></details>

Correction, the resource_user name is an std::string. I've removed this line.
___
*[src/core/lib/iomgr/event_engine/iomgr.cc, line 64 at r19](https://reviewable.io/reviews/grpc/grpc/26026#-McQ1VSG6-Kmor_g3Ei_:-McQGEj3BrB1uzrIAtD7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d66f01671b48e2873a26ddbe613de31f15fdd48/src/core/lib/iomgr/event_engine/iomgr.cc#L64)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Probably also want to reset `g_event_engine` to null, just in case some lingering callback tries to use it.
</blockquote></details>

Done.
___
*[src/core/lib/surface/init.h, line 36 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGmzRQDJ7drnHvgdoK:-McQI9BV8KYDgAL_mVx_:b651p29) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/src/core/lib/surface/init.h#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There is no need for the code in the EE-based iomgr impl to ever hold a ref here.  We will not be able to add support for user-supplied EventEngines until after we have eliminated the iomgr code.  The iomgr API is inherently not a per-channel thing; it is global.

It does not make sense to have `grpc_iomgr_event_engine()` return a `std::shared_ptr<>`, because none of its callers ever need to hold a ref.  So forcing this to be a shared_ptr means that we are needlessly taking a new ref and then immediately releasing that ref every time `grpc_iomgr_event_engine()` is called.
</blockquote></details>

That's right, thanks. I've removed the need for a shared_ptr<EventEngine> in the EE iomgr tcp cod, grpc_iomgr_event_engine now returns an `EventEngine*`


<!-- Sent from Reviewable.io -->

2021-06-17 20:09 UTC, markdroth requested changes
This looks really good!  The only really blocking issue is to remove the `GetResourceUser()` method.

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 8 files at r20.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-McQ_oS-9q0UhBZIXbXZ:bqblutu)* status: all files reviewed, 4 unresolved discussions (waiting on @drfloob)

___
*[include/grpc/event_engine/event_engine.h, line 121 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGVnK-BbgdmlIK9zas:-McQYwN1288ahabrwPbl:b-1s3ph4) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L121)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Well said, no argument!

> The chttp2 code will therefore be able to provide its own SliceAllocator implementation, which can contain the associated RU. And on the server side, it can provide its own SliceAllocatorFactory implementation, which knows how to create its SliceAllocator objects.

That will have to happen when me migrate the chttp2 code away from using iomgr, if not before then. The chttp2 code will ultimately be responsible for RU and RQ creation and ownership, based on the current EE design.

> I am not aware of any case that would require this to be visible in any way to EE implementations.

True, the EE itself doesn't need it, that's what I was trying to convey in the documentation's `(for internal use)` bit. Presuming the EE interface remains experimental even after we've removed iomgr, the `GetResourceUser` method should very well be temporary. Allowing the method to exist temporarily would avoid us having to do the iomgr refactor / chttp2 ownership change now, which would push the immediate EventEngine timeline back a few days, maybe a week (I need to spend time familiarizing myself with the transport code).

Having slept on it, even given the timeline slip, I'm inclined to do the refactoring anyway. Let me know if you've changed your mind on that.
</blockquote></details>

I don't see any reason not to go ahead and do this refactoring now.  I think this is actually a useful code cleanup in its own right, because it centralizes RQ and RU usage to the transport code, where it belongs, rather than sharing responsibility between iomgr and the transport code.

To be clear, though, I'm not saying that we need to block on this; I'm just saying that I don't want to add methods to the EE API that we don't think are a good idea, even temporarily, because the more we do that, the more we have to remember to clean up before we can de-experimentalize it.  But we can still defer this refactoring for a bit if you want without having to add this method here: instead, add the method to the libuv-based EE impl subclass, and have the EE-based iomgr code down-cast to the subclass.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 108 at r20](https://reviewable.io/reviews/grpc/grpc/26026#-McQ_cLyEk08wsG8vUEy:-McQ_cLyEk08wsG8vUEz:b-y21gir) ([raw file](https://github.com/grpc/grpc/blob/61765d715e1877632886727775418ce346f4aeb4/src/core/lib/iomgr/event_engine/tcp.cc#L108)):*
> ```cpp
>       grpc_millis_to_timespec(deadline, GPR_CLOCK_MONOTONIC));
>   ChannelArgsEndpointConfig endpoint_config(channel_args);
>   // TODO(hork): Establish how to take a user-supplied EventEngine here instead
> ```

This TODO can go away.  As we've discussed, this code (the EE-based iomgr impl) will never need to do this.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 129 at r20](https://reviewable.io/reviews/grpc/grpc/26026#-McQ_ggq5umq8dcQ4JvE:-McQ_ggq5umq8dcQ4JvF:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/61765d715e1877632886727775418ce346f4aeb4/src/core/lib/iomgr/event_engine/tcp.cc#L129)):*
> ```cpp
>     rq = grpc_resource_quota_create(nullptr);
>   }
>   // TODO(hork): Establish how to take a user-supplied EventEngine here instead
> ```

Same here.


<!-- Sent from Reviewable.io -->

2021-06-17 22:41 UTC, drfloob reviewed
Thanks for the suggestions! Just a bit of discussion left.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-McR75G0BIuD8K61ViXt:bqbpa94)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 121 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGVnK-BbgdmlIK9zas:-McR6Omy5jp7sgHMsrI5:bo12i0r) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L121)):*
> add the method to the libuv-based EE impl subclass, and have the EE-based iomgr code down-cast to the subclass.

That sounds like a great temporary solution. I'll do that for now (one detail left to discuss in another thread here), and will plan to do the RU refactoring at a better time.
___
*[include/grpc/event_engine/slice_allocator.h, line 50 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGd2NOAmewbhzxnstN:-McR3s3tE_jCqr5x3YHr:b92ou2o) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/slice_allocator.h#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As I mentioned elsewhere, this should not be exposed in this API.  We should instead fix the chttp2 code to track this internally.
</blockquote></details>

If we move the `GetResourceUser` method from the EventEngine API into the `uvEngine` subclass as you suggested above, we'd still benefit from having this to retrieve the resource user from the SliceAllocator. Alternatively, we could overload or create custom Connect methods on the subclass, and do something like this in the tcp iomgr code so that the uvEngine has direct knowledge of the RU:

```
void tcp_connect(...) {
 ...
  uvEngine* engine = dynamic_cast<uvEngine*>(grpc_iomgr_event_engine());
  SliceAllocator sa(ee_endpoint->ru);
  absl::Status connected = engine->ConnectWithRu(
      ee_on_connect, ra, endpoint_config, std::move(sa), ee_deadline, ee_endpoint->ru); // extra RU argument at the end
```

WDYT? I think I'd prefer the latter, but with an overload.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 108 at r20](https://reviewable.io/reviews/grpc/grpc/26026#-McQ_cLyEk08wsG8vUEy:-McR2v8F67VfkQ0uvWNh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/61765d715e1877632886727775418ce346f4aeb4/src/core/lib/iomgr/event_engine/tcp.cc#L108)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This TODO can go away.  As we've discussed, this code (the EE-based iomgr impl) will never need to do this.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 129 at r20](https://reviewable.io/reviews/grpc/grpc/26026#-McQ_ggq5umq8dcQ4JvE:-McR2us91IrRMn0Ul2dZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/61765d715e1877632886727775418ce346f4aeb4/src/core/lib/iomgr/event_engine/tcp.cc#L129)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-17 23:39 UTC, drfloob reviewed
I think I've wrapped up everything. Please let me know if there's anything else that you think needs to be resolved in this PR. Thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-McRKmdpBCWA9F2qoYGg:btvr7z2)* status: 68 of 71 files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[include/grpc/event_engine/event_engine.h, line 121 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGVnK-BbgdmlIK9zas:-McRK3fg13rWftUuNG4I:b-6s94ba) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/event_engine.h#L121)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

> add the method to the libuv-based EE impl subclass, and have the EE-based iomgr code down-cast to the subclass.

That sounds like a great temporary solution. I'll do that for now (one detail left to discuss in another thread here), and will plan to do the RU refactoring at a better time.
</blockquote></details>

This is the solution we'll put in the uv-ee branch, I think. For now, I've left the endpoint's ru unset in the EE iomgr code, since it doesn't much matter at the moment. I left a TODO which I'll take care of as soon as this work is pushed through.
___
*[include/grpc/event_engine/slice_allocator.h, line 50 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGd2NOAmewbhzxnstN:-McRJrAs7gMRZh_kY7GG:bx600ap) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/slice_allocator.h#L50)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

If we move the `GetResourceUser` method from the EventEngine API into the `uvEngine` subclass as you suggested above, we'd still benefit from having this to retrieve the resource user from the SliceAllocator. Alternatively, we could overload or create custom Connect methods on the subclass, and do something like this in the tcp iomgr code so that the uvEngine has direct knowledge of the RU:

```
void tcp_connect(...) {
 ...
  uvEngine* engine = dynamic_cast<uvEngine*>(grpc_iomgr_event_engine());
  SliceAllocator sa(ee_endpoint->ru);
  absl::Status connected = engine->ConnectWithRu(
      ee_on_connect, ra, endpoint_config, std::move(sa), ee_deadline, ee_endpoint->ru); // extra RU argument at the end
```

WDYT? I think I'd prefer the latter, but with an overload.
</blockquote></details>

I've removed the SliceAllocator's GetResourceUser method here since it doesn't much matter at the moment, and we can figure out which way to go in the uv-ee branch.
___
*[include/grpc/impl/codegen/port_platform.h, line 679 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGdlhF2NWGwWTLmfQS:-McRKe7U-SJpPXjNRo6c:b1jgynv) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/impl/codegen/port_platform.h#L679)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

I just checked; yes it's been broken for a little while now.
</blockquote></details>

Nico, did you want to take the AI to look into that?


<!-- Sent from Reviewable.io -->

2021-06-18 16:04 UTC, markdroth approved these changes
This looks great!

> Reviewed 3 of 3 files at r21, 1 of 1 files at r22.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-McUrVlxBOXZ5VVrbCIr:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @drfloob)

___
*[include/grpc/event_engine/slice_allocator.h, line 50 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGd2NOAmewbhzxnstN:-McUqlmC06DdOehCkmUi:bf7608x) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/slice_allocator.h#L50)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

I've removed the SliceAllocator's GetResourceUser method here since it doesn't much matter at the moment, and we can figure out which way to go in the uv-ee branch.
</blockquote></details>

Having an alternative version of `Connect()` is one option.  Another option is to have the EE impl know how to downcast the `SliceAllocator` impl and have the `SliceAllocator` impl provide the `GetResourceUser()` method.

Whichever of those options we choose, this is just a temporary solution until we change the chttp2 code to track the resource user itself, so I don't really care which one we go with.


<!-- Sent from Reviewable.io -->

2021-06-18 16:25 UTC, drfloob reviewed
Thanks Mark!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26026#-:-McUw7O470xjYOUkwBht:b78l10i)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @drfloob)

___
*[include/grpc/event_engine/slice_allocator.h, line 50 at r17](https://reviewable.io/reviews/grpc/grpc/26026#-McGd2NOAmewbhzxnstN:-McUw3iEBYmf1Q8MOX9v:bb73djm) ([raw file](https://github.com/grpc/grpc/blob/eb1850ae41c5ea629cb2a6641d7205bbd6dc3660/include/grpc/event_engine/slice_allocator.h#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Having an alternative version of `Connect()` is one option.  Another option is to have the EE impl know how to downcast the `SliceAllocator` impl and have the `SliceAllocator` impl provide the `GetResourceUser()` method.

Whichever of those options we choose, this is just a temporary solution until we change the chttp2 code to track the resource user itself, so I don't really care which one we go with.
</blockquote></details>

SGTM


<!-- Sent from Reviewable.io -->

2021-06-18 19:30 UTC, merged