Use x64 protoc on macOS arm64
grpc/grpc pull request #26080
Opened 2021-04-24 17:08 UTC by BradBarnich

As a workaround until #25755 is resolved.

@markdroth

2021-05-04 12:53 UTC, jtattermusch commented on src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets
> +      <Protobuf_ToolsCpu Condition=" '$(Protobuf_ToolsCpu)' == 'arm64' and '$(Protobuf_ToolsOs)' == 'macosx' ">x64</Protobuf_ToolsCpu>
If you want to override the cpu architecture, you should do it in the C# code
(e.g. in the https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Tools/ProtoToolsPlatform.cs), not here.

The msbuild files already way too complex, they weren't designed for hacks like this and they are also much harder to test than the C# code.

2021-05-04 12:55 UTC, jtattermusch requested changes
See the comments in the code.

2021-05-04 15:04 UTC, BradBarnich commented
@jtattermusch Thank you, can you give this new version a look?

2021-05-05 08:53 UTC, jtattermusch commented
I started an adhoc run of  package build and distribtest: https://fusion2.corp.google.com/invocations/6aedd5f1-57dc-443f-a335-f2320090f7e2/targets

I will post results later.

2021-05-05 08:54 UTC, jtattermusch approved these changes
LGTM once the tests are green and an adhoc build of Grpc.Tools is tested.

2021-05-05 08:55 UTC, jtattermusch commented
@apolcyn  please add another Gooogler's review.

2021-05-05 14:19 UTC, jtattermusch commented
One more run of distribtests:
https://fusion2.corp.google.com/invocations/d7c3d66c-f92c-4a78-9bba-75f24fcde425/targets

2021-05-05 15:34 UTC, apolcyn approved these changes

2021-05-06 11:45 UTC, jtattermusch commented
Distribtests are green: https://fusion2.corp.google.com/invocations/7a23e587-b8cc-4512-a8dd-8ca0bcaecef3 (except of distribtest.python_linux_x64_ubuntu1604, which is unrelated and is being fixed).

2021-05-06 11:45 UTC, merged