xds_end2end_test Eds Args refactoring
grpc/grpc pull request #26093
Opened 2021-04-27 04:42 UTC by donnadionne

2021-04-27 16:07 UTC, markdroth requested changes
Thanks for doing this!  Overall, this looks good; my comments are all relatively minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26093#-:-MZJ4N5n4U6xFTkvwx-i:b-8hpspo)* status: all files reviewed, 13 unresolved discussions (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 484 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIzan99L1S8OjmbcBw:-MZIzan99L1S8OjmbcBx:bp10o41) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L484)):*
> ```cpp
>   struct EdsResourceArgs {
>     struct Endpoint {
>       Endpoint(int port, HealthStatus health_status = HealthStatus::UNKNOWN,
> ```

`explicit`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 497 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIxcX0BQ4lzCp2vGfG:-MZIxcX0BQ4lzCp2vGfH:b-rajlwv) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L497)):*
> ```cpp
>                int lb_weight = kDefaultLocalityWeight,
>                int priority = kDefaultLocalityPriority,
>                std::vector<HealthStatus> health_statuses = {})
> ```

This argument is no longer needed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1953 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIy6hF0E-f5gTPRvp-:-MZIy6hF0E-f5gTPRvp0:bkrlinb) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L1953)):*
> ```cpp
>     if (stop_index == 0) stop_index = backends_.size();
>     for (size_t i = start_index; i < stop_index; ++i) {
>       switch (rpc_options.service) {
> ```

The body of this loop can now be replaced with a call to `SeenBackend(i)`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1975 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIxqd56lF50DmhYiIf:-MZIxqd56lF50DmhYiIg:b-9rjkxm) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L1975)):*
> ```cpp
> 
>   bool SeenBackend(size_t backend_idx,
>                    const RpcOptions& rpc_options = RpcOptions()) {
> ```

It doesn't really make sense to pass in `RpcOptions` here, since this isn't sending any RPCs.  Instead, let's just pass in the `RpcService` enum.

Same thing for the existing `SeenAllBackends()` method above.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2036 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZJ-RoW3F8mle1Fl-We:-MZJ-RoW3F8mle1Fl-Wf:b-umx459) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L2036)):*
> ```cpp
> 
>   void WaitForBackend(size_t backend_idx, bool reset_counters = true,
>                       bool require_success = false,
> ```

I think it would be useful for `WaitForBackend()` and `WaitForAllBackends()` to take the same list of parameters (other than the initial parameter(s) that specify the set of backend(s) to wait for).  I suggest something like this:

```
struct WaitForBackendOptions {
  bool reset_counters = true;
  bool allow_failures = false;

  WaitForBackendOptions() = default;

  WaitForBackendOptions& set_reset_counters(bool enable) {
    reset_counters = enable;
    return *this;
  }

  WaitForBackendOptions& set_allow_failures(bool enable) {
    allow_failures = enable;
    return *this;
  }
};

std::tuple<int, int, int> WaitForAllBackends(
    size_t start_index = 0, size_t stop_index = 0,
    const RpcOptions& rpc_options = RpcOptions(),
    const WaitForBackendOptions& wait_options = WaitForBackendOptions()) {
  // ...
}

void WaitForBackend(
    size_t backend_idx,
    const RpcOptions& rpc_options = RpcOptions(),
    const WaitForBackendOptions& wait_options = WaitForBackendOptions()) {
  // ...
}
```

That way, it's very easy for each caller to specify only the arguments it actually needs.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2067 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIyZ2m9kj6xIDjxYx1:-MZIyZ2m9kj6xIDjxYx2:b-u1yt7z) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L2067)):*
> ```cpp
> 
>   std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint>
>   CreateEndpointsForBackends(size_t start_index = 0, size_t stop_index = 0,
> ```

Please move this down to line 2219, right before `BuildEdsResource()`.  That way, all of the code for constructing xDS resources is in one place.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2701 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIzDzf1a23zFEkPGVY:-MZIzDzf1a23zFEkPGVZ:bkb3h07) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L2701)):*
> ```cpp
>       {backends_[0]->port(), HealthStatus::UNKNOWN, 1},
>       {backends_[0]->port(), HealthStatus::UNKNOWN, 1}};
>   // std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints;
> ```

These commented-out lines can be removed.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2769 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIzV2G5ZTOwETmulrr:-MZIzV2G5ZTOwETmulrs:b-1r8i65) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L2769)):*
> ```cpp
>   for (size_t i = 0; i < kNumUnreachableServers; ++i) {
>     endpoints.emplace_back(grpc_pick_unused_port_or_die(),
>                            HealthStatus::UNKNOWN, 1);
> ```

No need for these two parameters, since those are the default values.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5002 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZJ-wWW0b4VXtxFpjQC:-MZJ-wWW0b4VXtxFpjQD:b-qzt2b8) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L5002)):*
> ```cpp
>   default_route->mutable_route()->set_cluster(kDefaultClusterName);
>   SetRouteConfiguration(0, new_route_config);
>   WaitForBackend(0, /*reset_counters=*/true, /*require_success=*/true);
> ```

The last two parameters are the default values, so they don't need to be specified here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5190 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZJ3W1s33OH_NaifXnE:-MZJ3W1s33OH_NaifXnF:b7d1iv2) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L5190)):*
> ```cpp
>   // Wait for RPCs to go to the new backend: 1, this ensures that the client has
>   // processed the update.
>   WaitForBackend(1, /*reset_counters=*/false);
> ```

It looks like this change removes `allow_failures` being set to true in the original code.  Won't this cause test flakiness?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5569 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZJ3i3Y5TcImAG8152t:-MZJ3i3Y5TcImAG8152u:b-qzt2b8) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L5569)):*
> ```cpp
>                                             .set_metadata(std::move(metadata));
>   // Make sure all backends are up.
>   WaitForBackend(0, /*reset_counters=*/true, /*require_success=*/true);
> ```

The last two parameters are the default values, so they don't need to be specified here.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5868 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZJ3mrbDhvjGKq3VAvF:-MZJ3mrbDhvjGKq3VAvG:b-50h5m9) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L5868)):*
> ```cpp
>   // Make sure all backends are up and that requests for each RPC
>   // service go to the right backends.
>   WaitForBackend(0, /*reset_counters=*/false, /*require_success=*/true);
> ```

The last  [...]

2021-04-28 05:42 UTC, donnadionne reviewed
fixed, PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26093#-:-MZLzxHz02BjCf7bgGcU:bgm8f9i)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 484 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIzan99L1S8OjmbcBw:-MZKRD9y4tSbJEijxG5Z:b2smnne) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L484)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`explicit`
</blockquote></details>

I could not use explicit, because it then will not be able to initialize endpoint using the code like 
std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints = {
      {backends_[0]->port(), HealthStatus::DRAINING, 1},
      {backends_[1]->port(), HealthStatus::UNKNOWN, 1},
      {backends_[2]->port(), HealthStatus::UNKNOWN, 1},
      {backends_[3]->port(), HealthStatus::UNKNOWN, 1}};

test/cpp/end2end/xds_end2end_test.cc:2668:58: error: no matching constructor for initialization of 'std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint>'
  std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints = {
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_vector.h:401:9: note: candidate constructor template not viable: requires at most 3 arguments, but 4 were provided
        vector(_InputIterator __first, _InputIterator __last,
___
*[test/cpp/end2end/xds_end2end_test.cc, line 497 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIxcX0BQ4lzCp2vGfG:-MZKRvwA8MQCWWnjiCQF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L497)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This argument is no longer needed.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1953 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIy6hF0E-f5gTPRvp-:-MZLjRh85kQpJfXr6BYu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L1953)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The body of this loop can now be replaced with a call to `SeenBackend(i)`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 1975 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIxqd56lF50DmhYiIf:-MZLlJNh7EpynTdFQZxd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L1975)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It doesn't really make sense to pass in `RpcOptions` here, since this isn't sending any RPCs.  Instead, let's just pass in the `RpcService` enum.

Same thing for the existing `SeenAllBackends()` method above.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2036 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZJ-RoW3F8mle1Fl-We:-MZLzwKP3DN6wYjQfH99:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L2036)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think it would be useful for `WaitForBackend()` and `WaitForAllBackends()` to take the same list of parameters (other than the initial parameter(s) that specify the set of backend(s) to wait for).  I suggest something like this:

```
struct WaitForBackendOptions {
  bool reset_counters = true;
  bool allow_failures = false;

  WaitForBackendOptions() = default;

  WaitForBackendOptions& set_reset_counters(bool enable) {
    reset_counters = enable;
    return *this;
  }

  WaitForBackendOptions& set_allow_failures(bool enable) {
    allow_failures = enable;
    return *this;
  }
};

std::tuple<int, int, int> WaitForAllBackends(
    size_t start_index = 0, size_t stop_index = 0,
    const RpcOptions& rpc_options = RpcOptions(),
    const WaitForBackendOptions& wait_options = WaitForBackendOptions()) {
  // ...
}

void WaitForBackend(
    size_t backend_idx,
    const RpcOptions& rpc_options = RpcOptions(),
    const WaitForBackendOptions& wait_options = WaitForBackendOptions()) {
  // ...
}
```

That way, it's very easy for each caller to specify only the arguments it actually needs.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2067 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIyZ2m9kj6xIDjxYx1:-MZLmlgL6ZSLXtgf0D9W:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L2067)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this down to line 2219, right before `BuildEdsResource()`.  That way, all of the code for constructing xDS resources is in one place.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2701 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIzDzf1a23zFEkPGVY:-MZLmvTPESed4Qv5WROx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L2701)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These commented-out lines can be removed.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 2769 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIzV2G5ZTOwETmulrr:-MZLo3161GK2f_ZfyTBf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L2769)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for these two parameters, since those are the default values.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5002 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZJ-wWW0b4VXtxFpjQC:-MZLoHwh3KLHKCJL4D_e:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L5002)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The last two parameters are the default values, so they don't need to be specified here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5190 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZJ3W1s33OH_NaifXnE:-MZLoRpZBzxWkWetY6YT:bumj8gr) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L5190)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like this change removes `allow_failures` being set to true in the original code.  Won't this cause test flakiness?
</blockquote></details>

restored
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5569 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZJ3i3Y5TcImAG8152t:-MZLoXTw5-VDbTGwIiOv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L5569)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The last two parameters are the default values, so they don't need to be specified here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5868 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZJ3mrbDhvjGKq3VAvF:-MZLocrx5Eh5GO0OEm-r:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L5868)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i> [...]

2021-04-28 15:47 UTC, markdroth requested changes
Looks like the change in default for `WaitForBackend()` has identified a number of places where we were allowing failures that we shouldn't be.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26093#-:-MZO9FTQ01a0h5KvZIA5:b-dl0oxe)* status: all files reviewed, 11 unresolved discussions (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 484 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIzan99L1S8OjmbcBw:-MZO2xN40hPVV1nrA0lt:bz3w14j) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L484)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I could not use explicit, because it then will not be able to initialize endpoint using the code like 
std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints = {
      {backends_[0]->port(), HealthStatus::DRAINING, 1},
      {backends_[1]->port(), HealthStatus::UNKNOWN, 1},
      {backends_[2]->port(), HealthStatus::UNKNOWN, 1},
      {backends_[3]->port(), HealthStatus::UNKNOWN, 1}};

test/cpp/end2end/xds_end2end_test.cc:2668:58: error: no matching constructor for initialization of 'std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint>'
  std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints = {
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_vector.h:401:9: note: candidate constructor template not viable: requires at most 3 arguments, but 4 were provided
        vector(_InputIterator __first, _InputIterator __last,
</blockquote></details>

In that case, change that test code to this:

```
std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints = {
  AdsServiceImpl::EdsResourceArgs::Endpoint(backends_[0]->port(), HealthStatus::DRAINING),
  AdsServiceImpl::EdsResourceArgs::Endpoint(backends_[1]->port()),
  AdsServiceImpl::EdsResourceArgs::Endpoint(backends_[2]->port()),
  AdsServiceImpl::EdsResourceArgs::Endpoint(backends_[3]->port()),
};
```

Or better yet, just this:

```
auto endpoints = CreateEndpointsForBackends();
endpoints[0].health_status = HealthStatus::DRAINING;
```
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6432 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO6tno06b195E2s8Fg:-MZO6tno06b195E2s8Fh:bp7lgix) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6432)):*
> ```cpp
>   // Shutdown backend 1 and wait for all traffic to go to backend 2.
>   ShutdownBackend(1);
>   WaitForBackend(2, WaitForBackendOptions().set_allow_failures(true));
> ```

Do we actually see failures here?  If we don't allow them, does the test become flaky?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6437 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO70YD3ohm4Dx533ga:-MZO70YD3ohm4Dx533gb:b-o86wq7) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6437)):*
> ```cpp
>   // Bring backend 1 back and ensure all traffic go back to it.
>   StartBackend(1);
>   WaitForBackend(1, WaitForBackendOptions().set_allow_failures(true));
> ```

This should definitely not allow failures.  Going back to the P0 endpoint will not cause any RPCs to fail.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6488 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7GeF2XXRlT8_COH1:-MZO7GeF2XXRlT8_COH2:b-391bn1) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6488)):*
> ```cpp
>   // Shutdown backend 1 and wait for all traffic to go to backend 2.
>   ShutdownBackend(1);
>   WaitForBackend(2, WaitForBackendOptions().set_allow_failures(true));
> ```

Same question as above -- it would be nice to not allow failures here, if we can do it without causing flakiness.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6493 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7L324xUP3QFFtVFY:-MZO7L324xUP3QFFtVFZ:bi7z0g) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6493)):*
> ```cpp
>   // Bring backend 1 back and ensure all traffic go back to it.
>   StartBackend(1);
>   WaitForBackend(1, WaitForBackendOptions().set_allow_failures(true));
> ```

This one definitely should not allow failures.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6541 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7QuKEXtcu5rGdlOd:-MZO7QuKEXtcu5rGdlOe:bi7z0g) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6541)):*
> ```cpp
>   }
>   // Wait for traffic to go to backend 1.
>   WaitForBackend(1, WaitForBackendOptions().set_allow_failures(true));
> ```

This one definitely should not allow failures.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6544 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7SWnAyq-nhV04IeK:-MZO7SWnAyq-nhV04IeL:b-88v9za) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6544)):*
> ```cpp
>   // Shutdown backend 1 and wait for all traffic to go to backend 2.
>   ShutdownBackend(1);
>   WaitForBackend(2, WaitForBackendOptions().set_allow_failures(true));
> ```

Same question as above -- we shouldn't allow failures here unless doing so will cause test flakiness.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6549 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7YI_6T-V-tj1f6g7:-MZO7YI_6T-V-tj1f6g8:bi7z0g) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6549)):*
> ```cpp
>   // Bring backend 1 back and ensure all traffic go back to it.
>   StartBackend(1);
>   WaitForBackend(1, WaitForBackendOptions().set_allow_failures(true));
> ```

This one definitely should not allow failures.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9142 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7lwt4AU5fBIyI1Yn:-MZO7lwt4AU5fBIyI1Yo:b-ar0zr2) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L9142)):*
> ```cpp
>   // that we received the update.  No RPCs should fail during this
>   // transition.
>   WaitForBackend(1, WaitForBackendOptions().set_allow_failures(true));
> ```

This is a change from the original code -- it was not allowing failures, and we should not change it to do so (as the comment above indicates).
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9261 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO8GWXBGC1atFw1uev:-MZO8GWXBGC1atFw1uew:bzcdnlx) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L9261)):*
> ```cpp
>   ShutdownBackend(0);
>   WaitForBackend(
>       1, WaitForBackendOptions().set_reset_counters(false).set_allow_failures(
> ```

Same question as above: does this test become flaky if we don't allow failures here?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9268 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO8Rx1Dy4zfAGqPybc:-MZO8Rx1Dy4zfAGqPybd:bi7z0g) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L9268)):*
> ```cpp
>   }
>   StartBackend(0);
>   WaitForBackend(0, WaitForBackendOptions().set_allow_failures(true));
> ```

This one definitely should not allow failures.


<!-- Sent from Reviewable.io -->

2021-04-28 20:36 UTC, donnadionne reviewed
dis-allowed a few places and retested.  A few places needed to stay to avoid flakes (i retested).  PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26093#-:-MZP5zLX1_da-Z7gKGCO:bm72h5q)* status: all files reviewed, 11 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 484 at r1](https://reviewable.io/reviews/grpc/grpc/26093#-MZIzan99L1S8OjmbcBw:-MZP5rQ_1ifaFT7N7AS7:b7y46b) ([raw file](https://github.com/grpc/grpc/blob/b31d3343cddf559a43f60467ff9a5d9742cee39a/test/cpp/end2end/xds_end2end_test.cc#L484)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In that case, change that test code to this:

```
std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints = {
  AdsServiceImpl::EdsResourceArgs::Endpoint(backends_[0]->port(), HealthStatus::DRAINING),
  AdsServiceImpl::EdsResourceArgs::Endpoint(backends_[1]->port()),
  AdsServiceImpl::EdsResourceArgs::Endpoint(backends_[2]->port()),
  AdsServiceImpl::EdsResourceArgs::Endpoint(backends_[3]->port()),
};
```

Or better yet, just this:

```
auto endpoints = CreateEndpointsForBackends();
endpoints[0].health_status = HealthStatus::DRAINING;
```
</blockquote></details>

done, and updated a number of init code
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6432 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO6tno06b195E2s8Fg:-MZOgIpR8MsGri_J-v-f:b22p4p3) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6432)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Do we actually see failures here?  If we don't allow them, does the test become flaky?
</blockquote></details>

yes this does make it flaky, gets "Transport closed" about 1/3 of the time; some "go away", "broken pipe", "socket closed"
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6437 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO70YD3ohm4Dx533ga:-MZOgI0eC_8Y2Ey3OQiv:b-hfpv0l) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6437)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should definitely not allow failures.  Going back to the P0 endpoint will not cause any RPCs to fail.
</blockquote></details>

removed
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6488 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7GeF2XXRlT8_COH1:-MZOkJdm5v0yE_ZW-ok1:b-vqanjr) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6488)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same question as above -- it would be nice to not allow failures here, if we can do it without causing flakiness.
</blockquote></details>

yes, causes flaky
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6493 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7L324xUP3QFFtVFY:-MZOkIzV3aalRVML821q:b-7ql1td) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6493)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This one definitely should not allow failures.
</blockquote></details>

fixed
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6541 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7QuKEXtcu5rGdlOd:-MZOkLbz6qp4z7BMDF0v:b-7ql1td) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6541)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This one definitely should not allow failures.
</blockquote></details>

fixed
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6544 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7SWnAyq-nhV04IeK:-MZOkO5NAbsOciMesY1o:b2c92qg) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6544)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same question as above -- we shouldn't allow failures here unless doing so will cause test flakiness.
</blockquote></details>

causes flaky
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6549 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7YI_6T-V-tj1f6g7:-MZOkNSu4fxpkdeviQRG:b-7ql1td) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L6549)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This one definitely should not allow failures.
</blockquote></details>

fixed
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9142 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO7lwt4AU5fBIyI1Yn:-MZOltK949tVfaOG1Val:b-w44nwn) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L9142)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is a change from the original code -- it was not allowing failures, and we should not change it to do so (as the comment above indicates).
</blockquote></details>

my mistake, restored
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9261 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO8GWXBGC1atFw1uev:-MZOnTqN5TfhLBV7o3MY:b9rzzq7) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L9261)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same question as above: does this test become flaky if we don't allow failures here?
</blockquote></details>

yes flaky, gets "Transport closed" about 1/3 of the time; some "go away", "broken pipe", "socket closed"
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9268 at r3](https://reviewable.io/reviews/grpc/grpc/26093#-MZO8Rx1Dy4zfAGqPybc:-MZOnVByE3VWN1Jok4Hi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2b1552be9f3e3ae92a8dc6637cfd96a425dfa7b1/test/cpp/end2end/xds_end2end_test.cc#L9268)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This one definitely should not allow failures.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-28 21:59 UTC, markdroth requested changes
Just a few minor comments remaining!

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26093#-:-MZPUUzpDimcTcemOXD9:b-8o7wzn)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 2699 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPR7Gx-h494WuU2hRB:-MZPR7Gx-h494WuU2hRC:b60yj7n) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L2699)):*
> ```cpp
>   SetNextResolutionForLbChannelAllBalancers();
>   // Same backend listed twice.
>   std::vector<AdsServiceImpl::EdsResourceArgs::Endpoint> endpoints = {
> ```

This can be written as:

```
auto endpoints = CreateEndpointsForBackend(1, 2);
endpoints.push_back(endpoints.front());
```
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5221 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPRgpO9BKqhWuqmM9U:-MZPRgpO9BKqhWuqmM9V:braq3bs) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L5221)):*
> ```cpp
>   // Populate new EDS resources.
>   AdsServiceImpl::EdsResourceArgs args({
>       AdsServiceImpl::EdsResourceArgs::Locality(
> ```

I don't think this requires writing out `AdsServiceImpl::EdsResourceArgs::Locality`.  I think this can just be:

```
{"locality0", {AdsServiceImpl::EdsResourceArgs::Endpoint(grpc_pick_unused_port_or_die())}},
```

Alternatively, consider creating a helper method in `XdsEnd2endTest` like this:

```
AdsServiceImpl::EdsResourceArgs::Endpoint MakeNonExistantEndpoint() {
  return AdsServiceImpl::EdsResourceArgs::Endpoint(
       grpc_pick_unused_port_or_die());
}
```

Then you can just say:

```
{"locality0", {MakeNonExistantEndpoint()}},
```

Same thing throughout.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9026 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPTukQ3ypSA9Yessq1:-MZPTukQ3ypSA9Yessq2:bjnaz42) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L9026)):*
> ```cpp
>     AdsServiceImpl::EdsResourceArgs::Locality locality(
>         name,
>         {AdsServiceImpl::EdsResourceArgs::Endpoint(backends_[0]->port())});
> ```

This can be written as:

```
{CreateEndpointsForBackends(1, 2)});
```

Same thing throughout.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9041 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPSiPdAZlg8WYyCumn:-MZPSiPdAZlg8WYyCumo:b-lblynh) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L9041)):*
> ```cpp
>   // received and handled by the xds policy.
>   WaitForBackend(
>       0, WaitForBackendOptions().set_reset_counters(false).set_allow_failures(
> ```

I don't think we should allow failures here.


<!-- Sent from Reviewable.io -->

2021-04-29 07:38 UTC, donnadionne reviewed
Fixed, except for StressTest needed the allow_failure because I see deadline exceeded errors in msan builds.  Maybe we could fix that separately and have this PR just stay the same as it has been

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26093#-:-MZRYze59tLwSxWtD4eO:bl9fqdx)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 2699 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPR7Gx-h494WuU2hRB:-MZRDiaM0zgrTqCsVNgA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L2699)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be written as:

```
auto endpoints = CreateEndpointsForBackend(1, 2);
endpoints.push_back(endpoints.front());
```
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5221 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPRgpO9BKqhWuqmM9U:-MZRFdro7j_Q4YhC5LJk:bjvtlxb) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L5221)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this requires writing out `AdsServiceImpl::EdsResourceArgs::Locality`.  I think this can just be:

```
{"locality0", {AdsServiceImpl::EdsResourceArgs::Endpoint(grpc_pick_unused_port_or_die())}},
```

Alternatively, consider creating a helper method in `XdsEnd2endTest` like this:

```
AdsServiceImpl::EdsResourceArgs::Endpoint MakeNonExistantEndpoint() {
  return AdsServiceImpl::EdsResourceArgs::Endpoint(
       grpc_pick_unused_port_or_die());
}
```

Then you can just say:

```
{"locality0", {MakeNonExistantEndpoint()}},
```

Same thing throughout.
</blockquote></details>

seems like {} initialization is still not allowed 

AdsServiceImpl::EdsResourceArgs args({
          "locality0", {MakeNonExistantEndpoint()}});

generates this error:
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9026 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPTukQ3ypSA9Yessq1:-MZRQrtW0PKtZ4DEQFk9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L9026)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be written as:

```
{CreateEndpointsForBackends(1, 2)});
```

Same thing throughout.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9041 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPSiPdAZlg8WYyCumn:-MZRQtBs9b-Y9vmXZKbk:b-gvd8fj) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L9041)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we should allow failures here.
</blockquote></details>

i saw deadline_exceeded with msan builds


<!-- Sent from Reviewable.io -->

2021-04-29 15:21 UTC, markdroth requested changes
I think it should be simple to fix that problem: just increase the RPC timeout instead of allowing failures.  But if that turns out not to be simple, then I'm okay with adding a TODO and splitting that into a separate PR.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26093#-:-MZTClFsCXG42vRyA7mg:bmomwpe)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5221 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPRgpO9BKqhWuqmM9U:-MZTC7wbD9xif8Qssl1s:bfcavij) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L5221)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

seems like {} initialization is still not allowed 

AdsServiceImpl::EdsResourceArgs args({
          "locality0", {MakeNonExistantEndpoint()}});

generates this error:



</blockquote></details>

You didn't actually paste the error, but it looks like you've actually got the code this way now, so assuming you're not still seeing a build failure, this looks good.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9041 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPSiPdAZlg8WYyCumn:-MZTCdVq3x0RNWpAhl3M:b-k4c093) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L9041)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i saw deadline_exceeded with msan builds
</blockquote></details>

Then let's increase the RPC timeout instead of allowing failures.


<!-- Sent from Reviewable.io -->

2021-04-29 16:37 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26093)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5221 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPRgpO9BKqhWuqmM9U:-MZTUJBf20rn9nkxDvwN:bf5ps0q) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L5221)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You didn't actually paste the error, but it looks like you've actually got the code this way now, so assuming you're not still seeing a build failure, this looks good.
</blockquote></details>

yeah i got it working, i just missed a pair of {}, no issues here
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9041 at r4](https://reviewable.io/reviews/grpc/grpc/26093#-MZPSiPdAZlg8WYyCumn:-MZTUNPyCw0qtIos5xJV:b-pgi38a) ([raw file](https://github.com/grpc/grpc/blob/f87588476462e4243bfdd03f71aaf695a4043599/test/cpp/end2end/xds_end2end_test.cc#L9041)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Then let's increase the RPC timeout instead of allowing failures.
</blockquote></details>

increase timeout fixed the issue


<!-- Sent from Reviewable.io -->

2021-04-29 17:30 UTC, markdroth approved these changes
Looks great!

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26093#-:-MZTeVS-3NE8WvRdp32E:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donnadionne)



<!-- Sent from Reviewable.io -->

2021-04-29 18:54 UTC, donnadionne commented
known issue #26128

2021-04-29 18:54 UTC, merged