IpAuthorizationMatcher implementation.
grpc/grpc pull request #26132
Opened 2021-04-29 22:12 UTC by ashithasantosh

This PR does the following
1. Implements IpAuthorizationMatcher
2. Adds getter for dns sans in EvaluateArgs, and updates AuthenticatedAuthorizationMatcher to use it.

2021-05-03 22:46 UTC, markdroth requested changes
Thanks for doing this!

My main comment is that we should store both the `grpc_resolved_address` and host/port forms  in `PerChannelArgs`, to both solve the problem of holding a pointer to a temporary string and to avoid conversion overhead on the per-call path.

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132#-:-MZoPBKJ1W2oTpy9IH-I:b3558ti)* status: all files reviewed, 9 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/cel_authorization_engine.cc, line 137 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnjiuO-xugZGdxh-Sb:-MZnjiuO-xugZGdxh-Sc:bgjpv39) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/cel_authorization_engine.cc#L137)):*
> ```cpp
>     } else if (elem == kSourceAddress) {
>       grpc_resolved_address address = args.GetPeerAddress();
>       absl::string_view source_address(
> ```

This isn't safe: you're creating a string view on a temporary string, but the temporary string isn't being saved anywhere, so it will go away immediately.

Note that changing this from `string_view` to `string` would not solve the problem; it would just move it to a slightly different place.  This is because this string would still be destroyed as soon as this scope ends (the end of this `else if` block), but the resulting `Activation` object will have stored a `string_view` pointing to this string.  We need to ensure that the string lives beyond the point at which the `Activation` object is destroyed.

Also, `grpc_sockaddr_to_string()` does some non-trivial work, so I don't think this is something that we want to execute on a per-call basis anyway for performance reasons.

If there are some callers of `EvaluateArgs` that are going to need the raw `grpc_resolved_address` and others that will need the string form, then I suggest caching both forms in `PerChannelArgs` and having two different accessor methods in `EvaluateArgs`.
___
*[src/core/lib/security/authorization/cel_authorization_engine.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnkvU-3w2hUH8RaQpP:-MZnkvU-3w2hUH8RaQpQ:b-5sve5a) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/cel_authorization_engine.cc#L149)):*
> ```cpp
>     } else if (elem == kDestinationAddress) {
>       grpc_resolved_address address = args.GetLocalAddress();
>       absl::string_view destination_address(
> ```

Same issue here.
___
*[src/core/lib/security/authorization/evaluate_args.h, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnkyXh8JJmEgExNST7:-MZnkyXh8JJmEgExNST8:bsh5msg) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.h#L42)):*
> ```objc
>     std::vector<absl::string_view> dns_sans;
>     absl::string_view common_name;
>     grpc_resolved_address local_address;
> ```

As mentioned elsewhere, I think we need to store these addresses in both `grpc_resolved_address` and string forms, since there are some callers that need both forms.

It may be useful to define a struct and use it for both the local and peer addresses:

```
struct Address {
  // The address in sockaddr form.
  grpc_resolved_address address;
  // The same address in host and port form.
  std::string address_string;
  int port;
};

Address local_address;
Address peer_address;
```
___
*[src/core/lib/security/authorization/evaluate_args.h, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnl5Bf7z88WUi85iWu:-MZnl5Bf7z88WUi85iWv:b10uske) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.h#L65)):*
> ```objc
>       absl::string_view key, std::string* concatenated_value) const;
> 
>   grpc_resolved_address GetLocalAddress() const;
> ```

And we'll need two forms of each accessor method, one for each of `grpc_resolved_address` and string forms.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnleSk5Q-Ej_9lKpp-:-MZnleSk5Q-Ej_9lKpp0:b-cj31d9) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.cc#L51)):*
> ```cpp
>   const grpc_auth_property* prop = grpc_auth_property_iterator_next(&it);
>   while (prop != nullptr) {
>     values.push_back(absl::string_view(prop->value, prop->value_length));
> ```

This can be written as:

```
values.emplace_back(prop->value, prop->value_length);
```
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnlqHeE8tcCvg2DUdz:-MZnlqHeE8tcCvg2DUe-:bbcy1nj) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.cc#L60)):*
> ```cpp
> }
> 
> void ParseEndpointUri(absl::string_view uri_text,
> ```

This function will need to return the result in both `grpc_resolved_address` form and as a string.

If you take my suggestion elsewhere about using a `PerChannelArgs::Address` struct, then you can probably just make that the return type here.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnqVs53NG1yI9_qfdJ:-MZnqVs53NG1yI9_qfdK:bruwpzp) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.cc#L75)):*
> ```cpp
>   }
>   grpc_error_handle error =
>       grpc_string_to_sockaddr(address, std::string(host_view).c_str(), 0);
> ```

We should pass `uri->path()` here instead of `host_view`, so that the `grpc_resolved_address` form will include the port.  (This won't make any difference for the subnet case, but it will be less surprising behavior in case someone tries to use the `grpc_resolved_address` form for something else in the future.)
___
*[src/core/lib/security/authorization/matchers.cc, line 24 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnoWpF7nARvIPePx-t:-MZnoWpF7nARvIPePx-u:bor9sxp) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/matchers.cc#L24)):*
> ```cpp
> namespace {
> 
> bool AuthenticatedMatchesHelper(const EvaluateArgs& args,
> ```

Is this function ever going to be used anywhere except in `AuthenticatedAuthorizationMatcher::Matches()`?  If not, I suggest removing this function and moving its contents directly into `AuthenticatedAuthorizationMatcher::Matches()`.
___
*[test/core/security/evaluate_args_test.cc, line 84 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZoNqroABgGn1VmxwyJ:-MZoNqroABgGn1VmxwyK:b3q6zcc) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/test/core/security/evaluate_args_test.cc#L84)):*
> ```cpp
>   EvaluateArgs args = util_.MakeEvaluateArgs();
>   grpc_resolved_address local_address = args.GetLocalAddress();
>   char ntop_buf[GRPC_INET6_ADDRSTRLEN];
> ```

This can be done much more simply:

```
EXPECT_EQ(grpc_sockaddr_to_uri(&local_address),
          "ipv6:[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:456");
```

Same thing in the next test.


<!-- Sent from Reviewable.io -->

2021-05-04 17:44 UTC, ashithasantosh reviewed
Thanks for the review, Mark!:) I resolved all comments.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132#-:-MZpSQc830mr2G8-Zy0B:b-39d9dh)* status: 3 of 8 files reviewed, 9 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/cel_authorization_engine.cc, line 137 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnjiuO-xugZGdxh-Sb:-MZpQdnv4yOnq94ifBaU:bsx06j2) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/cel_authorization_engine.cc#L137)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This isn't safe: you're creating a string view on a temporary string, but the temporary string isn't being saved anywhere, so it will go away immediately.

Note that changing this from `string_view` to `string` would not solve the problem; it would just move it to a slightly different place.  This is because this string would still be destroyed as soon as this scope ends (the end of this `else if` block), but the resulting `Activation` object will have stored a `string_view` pointing to this string.  We need to ensure that the string lives beyond the point at which the `Activation` object is destroyed.

Also, `grpc_sockaddr_to_string()` does some non-trivial work, so I don't think this is something that we want to execute on a per-call basis anyway for performance reasons.

If there are some callers of `EvaluateArgs` that are going to need the raw `grpc_resolved_address` and others that will need the string form, then I suggest caching both forms in `PerChannelArgs` and having two different accessor methods in `EvaluateArgs`.
</blockquote></details>

Oh right! Thank you! I updated the code to store both versions of address. 
___
*[src/core/lib/security/authorization/cel_authorization_engine.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnkvU-3w2hUH8RaQpP:-MZpRi5C5H3GA0Kl_I0X:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/cel_authorization_engine.cc#L149)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same issue here.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/evaluate_args.h, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnkyXh8JJmEgExNST7:-MZpRnGM33MdJFLsKXpe:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.h#L42)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned elsewhere, I think we need to store these addresses in both `grpc_resolved_address` and string forms, since there are some callers that need both forms.

It may be useful to define a struct and use it for both the local and peer addresses:

```
struct Address {
  // The address in sockaddr form.
  grpc_resolved_address address;
  // The same address in host and port form.
  std::string address_string;
  int port;
};

Address local_address;
Address peer_address;
```
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/evaluate_args.h, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnl5Bf7z88WUi85iWu:-MZpRr0iEoGwzv9GgRld:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.h#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

And we'll need two forms of each accessor method, one for each of `grpc_resolved_address` and string forms.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnleSk5Q-Ej_9lKpp-:-MZpRs5zAIIwZyrjidVk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be written as:

```
values.emplace_back(prop->value, prop->value_length);
```
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnlqHeE8tcCvg2DUdz:-MZpRv9U0UI6fAih1NIM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.cc#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This function will need to return the result in both `grpc_resolved_address` form and as a string.

If you take my suggestion elsewhere about using a `PerChannelArgs::Address` struct, then you can probably just make that the return type here.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 75 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnqVs53NG1yI9_qfdJ:-MZpSCZN4ympMHPtkOPz:bcms4kn) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.cc#L75)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should pass `uri->path()` here instead of `host_view`, so that the `grpc_resolved_address` form will include the port.  (This won't make any difference for the subnet case, but it will be less surprising behavior in case someone tries to use the `grpc_resolved_address` form for something else in the future.)
</blockquote></details>

Done. Included port in the method call.
___
*[src/core/lib/security/authorization/matchers.cc, line 24 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnoWpF7nARvIPePx-t:-MZpSO6m-9PTk4n62KRc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/matchers.cc#L24)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this function ever going to be used anywhere except in `AuthenticatedAuthorizationMatcher::Matches()`?  If not, I suggest removing this function and moving its contents directly into `AuthenticatedAuthorizationMatcher::Matches()`.
</blockquote></details>

Done.
___
*[test/core/security/evaluate_args_test.cc, line 84 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZoNqroABgGn1VmxwyJ:-MZpSPWAByXyp-ioyNfb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/test/core/security/evaluate_args_test.cc#L84)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be done much more simply:

```
EXPECT_EQ(grpc_sockaddr_to_uri(&local_address),
          "ipv6:[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:456");
```

Same thing in the next test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-06 00:34 UTC, ZhenLian requested changes
> Reviewed 3 of 8 files at r1, 2 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132)* status: all files reviewed, 13 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @markdroth)

___
*[src/core/lib/security/authorization/evaluate_args.h, line 49 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyrzCc58gZOJSal2ON:-MZyrzCdDv12A7j7WebV:bee5fvu) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.h#L49)):*
> ```objc
>     absl::string_view spiffe_id;
>     std::vector<absl::string_view> dns_sans;
>     absl::string_view common_name;
> ```

I might miss something, but wouldn't we have the similar concern for all the other cached `absl::string_view` in this struct, as Mark mentioned in another comment?
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 44 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyy0GI8CKej8ea1GCw:-MZyy0GI8CKej8ea1GCx:brxp7dj) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.cc#L44)):*
> ```cpp
> }
> 
> std::vector<absl::string_view> GetAuthPropertyArray(grpc_auth_context* context,
> ```

Is the purpose of this function mainly to rewrite `grpc_auth_context_find_properties_by_name` and return a std::vector instead of a `grpc_auth_property_iterator`?
If so, I think you can consider move this function as well as the above `GetAuthPropertyValue` to a more common place, for example, https://github.com/grpc/grpc/blob/master/test/core/util/tls_utils.h, as I believe this function might also benefit a lot other places outside security/authorization in core.

Alternatively, you can also create a utility file under https://github.com/grpc/grpc/tree/master/test/core/util, maybe called something like `authorization_utils.h`.
___
*[src/core/lib/security/authorization/matchers.cc, line 160 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZz0wdz7prJ_b6fzgVK:-MZz0wdz7prJ_b6fzgVL:b7k2tc1) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/matchers.cc#L160)):*
> ```cpp
>   } else {
>     gpr_log(GPR_DEBUG, "CidrRange address %s is not IPv4/IPv6.",
>             range.address_prefix.c_str());
> ```

nit: if `error != GRPC_ERROR_NONE`, shouldn't we log the message contained in `error` as well? Same for other places.
Now we can use `grpc_error_std_string()` tp extract the error string out. 
___
*[src/core/lib/security/authorization/matchers.cc, line 192 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZz2RSN99TWEVWLtzN9:-MZz2RSO8saBE0H-wFVX:b-ndjhhd) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/matchers.cc#L192)):*
> ```cpp
> }
> 
> bool AuthenticatedAuthorizationMatcher::Matches(
> ```

Hmmm looking at the code, it makes me wonder if we want to update the matcher to also return the detailed message on why a matcher is not matched.
For example, from the user's perspective, when seeing an `AuthenticatedAuthorizationMatcher` failed to match, they might wonder what exactly is causing the problem. Is it because the connection failed to authenticate, or is it because the spiffe ID doesn't match? That information might be something they are interested in.
This doesn't have to be with this PR, but I am just thinking about any places we could do better. Or we can also keep it in mind, and work on it until we see actual users request for it...


<!-- Sent from Reviewable.io -->

2021-05-06 20:49 UTC, markdroth requested changes
Just one minor nit remaining.  Otherwise, looks great!

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132#-:-M_2R8sjAZ1UzK0NEucX:b-eu3usk)* status: all files reviewed, 5 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.h, line 49 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyrzCc58gZOJSal2ON:-M_2P1C_3In5-Wdtyoqt:b-hvi6ga) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.h#L49)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I might miss something, but wouldn't we have the similar concern for all the other cached `absl::string_view` in this struct, as Mark mentioned in another comment?
</blockquote></details>

These are all views on strings stored in the underlying auth context, and the filter will hold a ref to the auth context to ensure that it isn't deleted out from under us.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnleSk5Q-Ej_9lKpp-:-M_2Phe2EyUAh7HPjuRi:b59vqvo) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.cc#L51)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No need to say `absl::string_view()` now that you're using `emplace_back()` instead of `push_back()`.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 44 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyy0GI8CKej8ea1GCw:-M_2PSVz1yBRSy20j0h5:b-li3muo) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.cc#L44)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Is the purpose of this function mainly to rewrite `grpc_auth_context_find_properties_by_name` and return a std::vector instead of a `grpc_auth_property_iterator`?
If so, I think you can consider move this function as well as the above `GetAuthPropertyValue` to a more common place, for example, https://github.com/grpc/grpc/blob/master/test/core/util/tls_utils.h, as I believe this function might also benefit a lot other places outside security/authorization in core.

Alternatively, you can also create a utility file under https://github.com/grpc/grpc/tree/master/test/core/util, maybe called something like `authorization_utils.h`.
</blockquote></details>

It's not okay for code under the src directory to depend on code in the test directory.

I don't object to moving this to a common place if it will be useful elsewhere, but it needs to be in the src tree.


<!-- Sent from Reviewable.io -->

2021-05-06 21:15 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132)* status: all files reviewed, 5 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.h, line 49 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyrzCc58gZOJSal2ON:-M_2NZXR6SRgU-l2IMWt:b-93ipz) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.h#L49)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I might miss something, but wouldn't we have the similar concern for all the other cached `absl::string_view` in this struct, as Mark mentioned in another comment?
</blockquote></details>

The string_view cached values are from auth_context. So as long as auth_context outlives PerChannelArgs struct, string_views will be valid, and pointing to the data inside auth context.
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 44 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyy0GI8CKej8ea1GCw:-M_2PZhq7lFWAKmASec-:bmascu) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.cc#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not okay for code under the src directory to depend on code in the test directory.

I don't object to moving this to a common place if it will be useful elsewhere, but it needs to be in the src tree.
</blockquote></details>

That's right! We want to return a vector of values here.

Moving the code to a more accessible location sounds good . I am not sure about the location though. We may not want to do it in test/core, aren't they for testing purposes? Maybe in https://github.com/grpc/grpc/tree/master/src/core/lib/security/context as security_context_utils. Wdyt?
___
*[src/core/lib/security/authorization/matchers.cc, line 192 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZz2RSN99TWEVWLtzN9:-M_2SSRE9hCowIWZJO-L:bnoc5w7) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/matchers.cc#L192)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Hmmm looking at the code, it makes me wonder if we want to update the matcher to also return the detailed message on why a matcher is not matched.
For example, from the user's perspective, when seeing an `AuthenticatedAuthorizationMatcher` failed to match, they might wonder what exactly is causing the problem. Is it because the connection failed to authenticate, or is it because the spiffe ID doesn't match? That information might be something they are interested in.
This doesn't have to be with this PR, but I am just thinking about any places we could do better. Or we can also keep it in mind, and work on it until we see actual users request for it...
</blockquote></details>

RBAC policy can have multiple policies, when we find a match we break early and return, or we go through the entire policy with several failed matches. not_rule adds to the complications. So returning details on why it did not match, may not be feasible. We could maybe add debug logs in all the matchers in the future if necessary.
Plus, do we really want to divulge specific details as to why the user request was rejected?


<!-- Sent from Reviewable.io -->

2021-05-07 00:02 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.cc, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/26132#-MZnleSk5Q-Ej_9lKpp-:-M_2eoY3EYmAlH5Qnde2:b-me52xh) ([raw file](https://github.com/grpc/grpc/blob/177ea4b6a68d309d48d89d3572f390ce3ebbd7c4/src/core/lib/security/authorization/evaluate_args.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to say `absl::string_view()` now that you're using `emplace_back()` instead of `push_back()`.
</blockquote></details>

Missed that. Thanks! Done.


<!-- Sent from Reviewable.io -->

2021-05-07 07:06 UTC, ZhenLian requested changes
There is one remaining suggestion I made about the shared place for the util library, but that's not mandatory so I will just approve this PR. Thanks for the great work!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132#-:-M_4d5AL3912eDzyrCob:b-jvf5n8)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.h, line 49 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyrzCc58gZOJSal2ON:-M_4_4Ox5jBgxDyds7dI:b-1c26dk) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.h#L49)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

The string_view cached values are from auth_context. So as long as auth_context outlives PerChannelArgs struct, string_views will be valid, and pointing to the data inside auth context.
</blockquote></details>

Got it. As long as these strings can live longer than PerChannelArgs then it shouldn't be a problem. Thanks for the explanation!
___
*[src/core/lib/security/authorization/evaluate_args.cc, line 44 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyy0GI8CKej8ea1GCw:-M_4_tB52qQkbcHnHWN6:bdsx1io) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.cc#L44)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

That's right! We want to return a vector of values here.

Moving the code to a more accessible location sounds good . I am not sure about the location though. We may not want to do it in test/core, aren't they for testing purposes? Maybe in https://github.com/grpc/grpc/tree/master/src/core/lib/security/context as security_context_utils. Wdyt?
</blockquote></details>

Ops, sorry I searched for the wrong file. I actually meant this place https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/tls/tls_utils.h, which is the place I bugged Yash to create a while ago(I just realized that we had two tls_util.h, one for the src code and one for the test :)).
___
*[src/core/lib/security/authorization/matchers.cc, line 192 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZz2RSN99TWEVWLtzN9:-M_4btsDDNdKAS4yhFc-:bd7piyw) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/matchers.cc#L192)):*
> or we go through the entire policy with several failed matches

Oh, I thought we would do an early break for the failed match as well. So in the failed cases, what would the users see? A list of all the failed policy names?

> Plus, do we really want to divulge specific details as to why the user request was rejected?

Yeah, the security side is another thing I was concerned about. I don't think I did enough research to answer that question, so let's just skip here and waiting to see if there are any actual user requests for that.


<!-- Sent from Reviewable.io -->

2021-05-07 07:06 UTC, ZhenLian approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132#-:-M_4dYm1EuIINVHQY11v:bnfp4nl)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, @markdroth, and @ZhenLian)



<!-- Sent from Reviewable.io -->

2021-05-07 15:32 UTC, markdroth approved these changes
This looks great!

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132#-:-M_6SJda3K2EH9SB_AYo:b-j45s0z)* status: all files reviewed, 3 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.cc, line 44 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyy0GI8CKej8ea1GCw:-M_6S7iU4ZkipQ4UF4g1:be9o6u2) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.cc#L44)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Ops, sorry I searched for the wrong file. I actually meant this place https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/tls/tls_utils.h, which is the place I bugged Yash to create a while ago(I just realized that we had two tls_util.h, one for the src code and one for the test :)).
</blockquote></details>

Zhen, it might be a good idea to rename the one in test to tls_test_utils, just to avoid confusion.  (That can be done in a separate PR.)


<!-- Sent from Reviewable.io -->

2021-05-07 16:52 UTC, ZhenLian approved these changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132)* status: all files reviewed, 3 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @markdroth)

___
*[src/core/lib/security/authorization/evaluate_args.cc, line 44 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyy0GI8CKej8ea1GCw:-M_6jTnV4-vu3uDaWy8o:b-rqed44) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.cc#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Zhen, it might be a good idea to rename the one in test to tls_test_utils, just to avoid confusion.  (That can be done in a separate PR.)
</blockquote></details>

Sure, sounds good! I will do it in a separate PR.


<!-- Sent from Reviewable.io -->

2021-05-08 05:13 UTC, ashithasantosh reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26132)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.cc, line 44 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZyy0GI8CKej8ea1GCw:-M_9A0DZ84pbqg6_-4SP:b-xz0kmu) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/evaluate_args.cc#L44)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sure, sounds good! I will do it in a separate PR.
</blockquote></details>

Added the methods to tls_utils
___
*[src/core/lib/security/authorization/matchers.cc, line 192 at r4](https://reviewable.io/reviews/grpc/grpc/26132#-MZz2RSN99TWEVWLtzN9:-M_8mXHO5Gv-nm-Q7TUh:b-br1co8) ([raw file](https://github.com/grpc/grpc/blob/f84fbd683283eb304360b176bef917aaf371df9a/src/core/lib/security/authorization/matchers.cc#L192)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

> or we go through the entire policy with several failed matches

Oh, I thought we would do an early break for the failed match as well. So in the failed cases, what would the users see? A list of all the failed policy names?

> Plus, do we really want to divulge specific details as to why the user request was rejected?

Yeah, the security side is another thing I was concerned about. I don't think I did enough research to answer that question, so let's just skip here and waiting to see if there are any actual user requests for that.
</blockquote></details>

If we don't find any match, the matching_policy_name will be empty
https://github.com/grpc/grpc/blob/master/src/core/lib/security/authorization/authorization_engine.h#L35
If the engine is allow engine, we will return deny decision.
If the engine is deny engine, we will return allow decision.
RBAC policy has multiple policies, if the first policy fails to match, we still need to go through the rest of the policies until something matches or we reach the end of the policy.


<!-- Sent from Reviewable.io -->

2021-05-10 19:39 UTC, ashithasantosh commented
Thanks for the review, Mark and Zhen!:) Will merge this PR once the tests are complete.

2021-05-11 16:56 UTC, merged