26137: context.is_active() and context.add_callback() do not work whe…
grpc/grpc pull request #26193
Opened 2021-05-07 06:53 UTC by SameerMahajan-GSLab

…n using grpc.aio

@nicolasnoble

2021-05-07 20:08 UTC, lidizheng requested changes
@SameerMahajan-GSLab Can you also add unit tests, and update the interface?

https://github.com/grpc/grpc/blob/5b035265cee380eea6c163ac08e4a0d62a4340df/src/python/grpcio/grpc/aio/_base_server.py#L134

2021-05-07 20:08 UTC, lidizheng commented on src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi
> +        return self._rpc_state.status_code == StatusCode.ok
This is probably wrong, we might want to check if it is `None` instead. If a status code is given, the RPC is finished.

2021-05-07 20:08 UTC, lidizheng commented on src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi
> +        self._rpc_state.callbacks.append(callback)
Maybe we also need to check if the callbacks are consumed properly?

2021-05-10 06:29 UTC, SameerMahajan-GSLab commented
@lidizheng I have incorporated your review feedback. Can you please guide me with unit tests? How they are organized? Where should I add grpc aio test for these changes?

2021-05-10 06:46 UTC, SameerMahajan-GSLab commented
I signed the CLA clicking on "Details" against EasyCLA - Missing CLA Authorization and also got the  email  stating that it is signed. Why is the check still showed as failing here?

2021-05-11 06:02 UTC, closed without merging

2021-05-11 06:03 UTC, SameerMahajan-GSLab commented
creating another pull request as the first two commits in this do not have git user name  set which is causing the check to  fail.