Adding retry policy
grpc/grpc pull request #26566
Opened 2021-06-28 21:31 UTC by donnadionne

2021-07-09 08:24 UTC, donnadionne reviewed
This is initial draft.  Just did simple parsing and transforming, but wanted to use it as a discussion base.

Question about hedge policy still remains.  I saw the doc listing the pro/cons ,not sure if a conclusion was reached?  So I included the parsing just in case, I can remove or change to NACK

Did not include retriable_header_request as the support is said to be deferred.

Let me know your initial comments; thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-Me9LSlX-xT-hpvxh3Dd:b-3o541r)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2021-07-09 21:58 UTC, markdroth requested changes
This looks like a good start!

We don't need to support hedging.  The underlying retry code doesn't yet have hedging support, so there's no need to parse the xDS config.  We do still need to resolve the design question of how we should handle an xDS config that has a hedging policy (e.g., NACK, just ignore, whatever), but no matter what we decide there, I don't think we need to return anything as part of the RdsUpdate.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-MeCGQJa0aevGrm-zrpl:bp023pi)* status: all files reviewed, 34 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 464 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeBSU5Z9kDjMD1i19oP:-MeBSU5Z9kDjMD1i19oQ:byue7u8) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L464)):*
> ```cpp
>                           route.retry_policy->per_try_timeout->nanos));
>     }
>     if (route.retry_policy->hedge_policy.has_value()) {
> ```

Not needed; we're not going to support hedging for now.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 471 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeBUQp71feFCovdrDzT:-MeBUQp71feFCovdrDzU:b-wjlpz1) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L471)):*
> ```cpp
>           route.retry_policy->hedge_policy->hedge_on_per_try_timeout));
>     }
>     retry_parts.push_back(
> ```

This needs to be done conditionally, because the set of status codes can be empty if perAttemptRecvTimeout is set.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 473 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeBSYlU5E9hiMJU06qk:-MeBSYlV5U2yXi6IiBRE:b-37u93g) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L473)):*
> ```cpp
>     retry_parts.push_back(
>         absl::StrFormat("      \"retryableStatusCodes\": [ \"%s\" ]\n",
>                         route.retry_policy->retry_on));
> ```

Passing this value through as-is isn't going to work.  The xDS `retry_on` field may contain more than one entry -- it's a comma-delimited list, but this would just cram the whole list into a single JSON string.  Also, it may contain things that are not status codes at all, which gRPC does not support.  And even the things that are status codes are not in the right format -- it uses lower-case instead of upper-case, and it uses dashes instead of underscores.

See my comment elsewhere about using `StatusCodeSet` here.  The parsing of the xDS string should be done in xds_api.cc.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 542 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeBUKQt-PL5sMdDKh2W:-MeBUKQu4PMZOzw0GD_k:bp77gdr) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L542)):*
> ```cpp
>         "}");
>     *method_config = ServiceConfig::Create(args, json.c_str(), &error);
>     gpr_log(GPR_INFO, "donna created method config: %s", json.c_str());
> ```

Please remove before merging.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 544 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeBUM3q5BwlnAmVEk4M:-MeBUM3q5BwlnAmVEk4N:bp77gdr) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L544)):*
> ```cpp
>     gpr_log(GPR_INFO, "donna created method config: %s", json.c_str());
>   }
>   gpr_log(GPR_INFO, "donna maybe created method config");
> ```

Please remove before merging.
___
*[src/core/ext/xds/xds_api.h, line 116 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAp_k79XdtHmJhP6dZ:-MeAp_k79XdtHmJhP6d_:bulvwqm) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.h#L116)):*
> ```objc
> 
>     struct RetryPolicy {
>       std::string retry_on;
> ```

This should be of type `StatusCodeSet`:

https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/src/core/lib/channel/status_util.h#L46
___
*[src/core/ext/xds/xds_api.h, line 126 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAovbE2gf-Plfjvf-i:-MeAovbF4xZJSLBgNY3q:b-hwyi1n) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.h#L126)):*
> ```objc
>       RetryBackOff retry_back_off;
> 
>       struct HedgePolicy {
> ```

We don't need this here right now, because we're not going to support hedging initially.
___
*[src/core/ext/xds/xds_api.cc, line 1533 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAxPdZ8Z_ZIAKiENE5:-MeAxPdZ8Z_ZIAKiENE6:bu22g88) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.cc#L1533)):*
> ```cpp
>     const envoy_config_route_v3_RetryPolicy* retry_policy) {
>   XdsApi::Route::RetryPolicy retry;
>   retry.retry_on = UpbStringToStdString(
> ```

We need to actually parse the value of the `retry_on` field and extract the policies that we support, which are all retriable status codes.

We also need to figure out how to handle the case where there are no policies that we support and `per_try_timeout` is unset.  I've started a comment thread about this in the internal design doc, but for now let's not return any retry policy.
___
*[src/core/ext/xds/xds_api.cc, line 1538 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAsMHh6d6NIPYq6wAZ:-MeAsMHh6d6NIPYq6wA_:b-1pcyzs) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.cc#L1538)):*
> ```cpp
>       envoy_config_route_v3_RetryPolicy_num_retries(retry_policy);
>   if (num_retries != nullptr) {
>     retry.num_retries = google_protobuf_UInt32Value_value(num_retries);
> ```

We should reject the config if this value is 0.
___
*[src/core/ext/xds/xds_api.cc, line 1540 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeArXLL8MEyMM5tQ1fa:-MeArXLL8MEyMM5tQ1fb:b-79uz85) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.cc#L1540)):*
> ```cpp
>     retry.num_retries = google_protobuf_UInt32Value_value(num_retries);
>   } else {
>     gpr_log(GPR_DEBUG, "RouteAction RetryPolicy missing num_retries");
> ```

It's not sufficient (nor appropriate) to just log validation errors; they need to be returned as a `grpc_error_handle` so that we can NACK with the right message when there's a validation failure.  Please use the same pattern for this that all of the other validation logic does (keeping a vector of errors and combining them at the end of the function).
___
*[src/core/ext/xds/xds_api.cc, line 1540 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAtYi831n1xtAbBOyG:-MeAtYi96MsABegeyOuC:btgfd8x) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.cc#L1540)):*
> ```cpp
>     retry.num_retries = google_protobuf_UInt32Value_value(num_retries);
>   } else {
>     gpr_log(GPR_DEBUG, "RouteAction RetryPolicy missing num_retries");
> ```

General comment: Please put the error handling code right below the condition that defines the error.  In other words, instead of this:

```
if (no error) {
  // ...handle success...
} else {
  // ...handle error...
}
```

Please instead say:

```
if (error) {
  // ...handle error...
} else {
  // ...handle success...
}
```

This makes the code much more readable.
___
*[src/core/ext/xds/xds_api.cc, line 1540 at r1](https://review [...]

2021-07-15 22:34 UTC, donnadionne reviewed
Fixed code review comments and added tests.

Still need a little clearity about behaviour around per_try_timeout (esp after they are exhausted).  PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-MegIUXDA2EZaqO63ISo:bpt8w0d)* status: 0 of 8 files reviewed, 34 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 464 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeBSU5Z9kDjMD1i19oP:-MeOd_RR4LDLG56F01zd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L464)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Not needed; we're not going to support hedging for now.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 471 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeBUQp71feFCovdrDzT:-MeRkb4x2pgNHRqvwali:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L471)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to be done conditionally, because the set of status codes can be empty if perAttemptRecvTimeout is set.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 473 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeBSYlU5E9hiMJU06qk:-MeRkbvj38CjxUUIXok3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L473)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Passing this value through as-is isn't going to work.  The xDS `retry_on` field may contain more than one entry -- it's a comma-delimited list, but this would just cram the whole list into a single JSON string.  Also, it may contain things that are not status codes at all, which gRPC does not support.  And even the things that are status codes are not in the right format -- it uses lower-case instead of upper-case, and it uses dashes instead of underscores.

See my comment elsewhere about using `StatusCodeSet` here.  The parsing of the xDS string should be done in xds_api.cc.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 542 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeBUKQt-PL5sMdDKh2W:-MegDIdtEpThkIsuGe2o:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L542)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove before merging.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 544 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeBUM3q5BwlnAmVEk4M:-MegDByeDVVkumNMa_Sn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L544)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove before merging.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 116 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAp_k79XdtHmJhP6dZ:-MeOf9m725vy7R20rGkI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.h#L116)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be of type `StatusCodeSet`:

https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/src/core/lib/channel/status_util.h#L46
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 126 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAovbE2gf-Plfjvf-i:-MeOfACQDKaMGy37G0bk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.h#L126)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We don't need this here right now, because we're not going to support hedging initially.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1533 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAxPdZ8Z_ZIAKiENE5:-MeRlNJ21kzEDaOWwCdb:b-z4xabq) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.cc#L1533)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We need to actually parse the value of the `retry_on` field and extract the policies that we support, which are all retriable status codes.

We also need to figure out how to handle the case where there are no policies that we support and `per_try_timeout` is unset.  I've started a comment thread about this in the internal design doc, but for now let's not return any retry policy.
</blockquote></details>

done and added a todo with per_try_timeout
___
*[src/core/ext/xds/xds_api.cc, line 1538 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAsMHh6d6NIPYq6wAZ:-MeRzUZn1-MlJDLhatvA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.cc#L1538)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should reject the config if this value is 0.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1540 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeArXLL8MEyMM5tQ1fa:-MeSqIjy0lk02CrN6r_H:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.cc#L1540)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not sufficient (nor appropriate) to just log validation errors; they need to be returned as a `grpc_error_handle` so that we can NACK with the right message when there's a validation failure.  Please use the same pattern for this that all of the other validation logic does (keeping a vector of errors and combining them at the end of the function).
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1540 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAtYi831n1xtAbBOyG:-MeSqUxf5omvMAXXjkcx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.cc#L1540)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

General comment: Please put the error handling code right below the condition that defines the error.  In other words, instead of this:

```
if (no error) {
  // ...handle success...
} else {
  // ...handle error...
}
```

Please instead say:

```
if (error) {
  // ...handle error...
} else {
  // ...handle success...
}
```

This makes the code much more readable.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1540 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAvnko3UlugAImqeaE:-MeSqY9a3DzZmlTGvLnE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/src/core/ext/xds/xds_api.cc#L1540)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In this particular case, this isn't actually an error.  According to the proto, `num_retries` is optional and defaults to 1 if not present.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1549 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeAtTBFEdRAoz-E8HEz:-MeT0VYf3dUfSCbLyw38:b-8 [...]

2021-07-16 22:25 UTC, markdroth requested changes
This is looking pretty good!  Comments are mostly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 6 files at r2, 2 of 4 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-MelPzUSEYE-h2VDm5x6:b-e7qrnc)* status: all files reviewed, 25 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1064 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Meklht74kBsJVjB6uJu:-Meklht8CPsMWJB1v8Gt:b-iiocr6) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/filters/client_channel/client_channel.cc#L1064)):*
> ```cpp
> namespace {
> 
> bool GetEnableRetries(const grpc_channel_args* args) {
> ```

I suggest removing this function and just inlining its contents into `ClientChannel::UpdateServiceConfigInDataPlaneLocked()`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 216 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mel5X3r8emHXOIRkbpd:-Mel5X3s4gtSvIVGf0oe:b911wql) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L216)):*
> ```cpp
>     }
> 
>     bool GetRetryEnabled() { return retry_enabled_; }
> ```

It doesn't look like this is used anywhere.  I suspect it's not needed.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 514 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MelJvyA1xZeovtOTbEK:-MelJvyA1xZeovtOTbEL:b-ah33hi) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L514)):*
> ```cpp
>     }
>     std::vector<std::string> code_parts;
>     if (!route.retry_policy->retry_on.Empty()) {
> ```

No need to check this now that we're no longer supporting `per_try_timeout`, since `retry_on` will never be empty.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 613 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mel5Jex1UN5eN1RCKHo:-Mel5Jex1UN5eN1RCKHp:bnlx7k8) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L613)):*
> ```cpp
>   // The max number of args to add is 2 so far; when more args need to be added
>   // we will increase the size of args_to_add accordingly;
>   grpc_arg args_to_add[2];
> ```

Please use `absl::InlinedVector<>` here instead of a C-style array.
___
*[src/core/ext/xds/xds_api.h, line 119 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mekn54Z3HfSZXLyJRfv:-Mekn54Z3HfSZXLyJRfw:br49ms5) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.h#L119)):*
> ```objc
>       internal::StatusCodeSet retry_on;
>       uint32_t num_retries;
>       absl::optional<Duration> per_try_timeout;
> ```

As per recent discussion, we're not going to need this field.
___
*[src/core/ext/xds/xds_api.cc, line 140 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MeknCvI8chYqGClDqmK:-MeknCvI8chYqGClDqmL:bwkiris) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L140)):*
> ```cpp
> }
> 
> // TODO(donnadionne): Check to see if retrt policy is enabled, this will be
> ```

s/retrt/retry/
___
*[src/core/ext/xds/xds_api.cc, line 141 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MeknFEc0Vj5p6w0Yg2P:-MeknFEc0Vj5p6w0Yg2Q:birlggm) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L141)):*
> ```cpp
> 
> // TODO(donnadionne): Check to see if retrt policy is enabled, this will be
> // removed once ring hash policy is fully integration-tested and enabled by
> ```

s/ring hash policy/retry functionality/
___
*[src/core/ext/xds/xds_api.cc, line 1577 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Meks0IZ5c9nV39FP6gv:-Meks0IZ5c9nV39FP6gw:bhxj3ag) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1577)):*
> ```cpp
> }
> 
> void DurationParse(const google_protobuf_Duration* proto_duration,
> ```

This should return `XdsApi::Duration` instead of populating the instance passed in via a parameter.
___
*[src/core/ext/xds/xds_api.cc, line 1601 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MekqiV94DTbt31kZlVA:-MekqiV94DTbt31kZlVB:b-adrkcq) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1601)):*
> ```cpp
>       retry->retry_on.Add(GRPC_STATUS_UNAVAILABLE);
>     } else {
>       gpr_log(GPR_DEBUG, "Unsupported retry_on policy.");
> ```

Please pass the `EncodingContext` down into this function and then log this only if the tracer is enabled.

Also, please log at GPR_INFO, and include the name of the unsupported policy in the log message.
___
*[src/core/ext/xds/xds_api.cc, line 1603 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mel69jz8HOA3MFsbufZ:-Mel69jz8HOA3MFsbuf_:b-65453q) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1603)):*
> ```cpp
>       gpr_log(GPR_DEBUG, "Unsupported retry_on policy.");
>     }
>   }
> ```

After this loop, if `retry->retry_on` is empty, then we should ignore the retry policy.  But please add a TODO that when we later add support for `per_try_timeout`, we will need to *not* ignore the retry policy if `per_try_timeout` is set.
___
*[src/core/ext/xds/xds_api.cc, line 1607 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MekrCay8moh08MML4bA:-MekrCay8moh08MML4bB:bbeby53) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1607)):*
> ```cpp
>       envoy_config_route_v3_RetryPolicy_num_retries(retry_policy);
>   if (num_retries != nullptr) {
>     auto num_retries_value = google_protobuf_UInt32Value_value(num_retries);
> ```

`uint32_t`
___
*[src/core/ext/xds/xds_api.cc, line 1609 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mekr_kyEKnaevQEZC_O:-Mekr_kyEKnaevQEZC_P:b-6d9cdf) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1609)):*
> ```cpp
>     auto num_retries_value = google_protobuf_UInt32Value_value(num_retries);
>     if (num_retries_value == 0) {
>       return GRPC_ERROR_CREATE_FROM_COPIED_STRING(
> ```

Instead of returning immediately at the first error, please accumulate a vector of errors and then combine them at the end.  That way, we include all problems in the error message, not just the first one we encounter.
___
*[src/core/ext/xds/xds_api.cc, line 1652 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mel60XzBfCmiVrTQ5lr:-Mel60Y-3qa8ilrm56Iz:b2d2uep) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1652)):*
> ```cpp
>     retry->retry_back_off.max_interval.nanos = 250000000;
>   }
>   const google_protobuf_Duration* per_try_timeout =
> ```

We don't need to look at this field anymore.
___
*[src/proto/grpc/testing/xds/v3/route.proto, line 37 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MelMuYZBoaf6Zwy68sz:-MelMuYZBoaf6Zwy68t-:b-tmu3re) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/proto/grpc/testing/xds/v3/route.proto#L37)):*
> ```protobuf
>   string retry_on = 1;
>   google.protobuf.UInt32Value num_retries = 2;
>   google.protobuf.Duration per_try_timeout = 3;
> ```

Please remove, since we aren't going to support this.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5563 at r1](https://reviewable.io/reviews/grpc/grpc/26566#-MeB0YBC1IFNeQ6oBcqG:-MelNvYpCpFxrpz-IpTR:b2gpngh) ([raw file](https://github.com/grpc/grpc/blob/b432e717526debc71c91fe8046f5db08546c8f80/test/cpp/end [...]

2021-07-20 03:59 UTC, donnadionne reviewed
fixed, PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-Mf13OFl6oHZflmrc7W4:b-d7mksl)* status: 3 of 9 files reviewed, 25 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1064 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Meklht74kBsJVjB6uJu:-Mf-841p61udYDh78zm6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/filters/client_channel/client_channel.cc#L1064)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest removing this function and just inlining its contents into `ClientChannel::UpdateServiceConfigInDataPlaneLocked()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 216 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mel5X3r8emHXOIRkbpd:-Mf-b3CD1zoc19xG1Jxf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L216)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It doesn't look like this is used anywhere.  I suspect it's not needed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 514 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MelJvyA1xZeovtOTbEK:-Mf-dw_33v3Qs3zQOLDr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L514)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to check this now that we're no longer supporting `per_try_timeout`, since `retry_on` will never be empty.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 613 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mel5Jex1UN5eN1RCKHo:-Mf-dwtn8_j2Z-SufWJU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L613)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `absl::InlinedVector<>` here instead of a C-style array.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 119 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mekn54Z3HfSZXLyJRfv:-Mf0ZdYK4kMy9VwKyA3c:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.h#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per recent discussion, we're not going to need this field.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 140 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MeknCvI8chYqGClDqmK:-Mf-e4qE31eYimQXaeOV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L140)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/retrt/retry/
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 141 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MeknFEc0Vj5p6w0Yg2P:-Mf-eDYF86AI4sdQYgky:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L141)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/ring hash policy/retry functionality/
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1577 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Meks0IZ5c9nV39FP6gv:-Mf-foLXBm2ujTIMCmMc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1577)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should return `XdsApi::Duration` instead of populating the instance passed in via a parameter.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1601 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MekqiV94DTbt31kZlVA:-Mf-ySpE2sFS6JAWudPY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1601)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please pass the `EncodingContext` down into this function and then log this only if the tracer is enabled.

Also, please log at GPR_INFO, and include the name of the unsupported policy in the log message.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1603 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mel69jz8HOA3MFsbufZ:-Mf-zxbh44K4vbj5TugQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1603)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

After this loop, if `retry->retry_on` is empty, then we should ignore the retry policy.  But please add a TODO that when we later add support for `per_try_timeout`, we will need to *not* ignore the retry policy if `per_try_timeout` is set.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1607 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MekrCay8moh08MML4bA:-Mf-z2zM9Yclck5hA7kF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1607)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`uint32_t`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1609 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mekr_kyEKnaevQEZC_O:-Mf0Cgmc1ComMsbgzn1f:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1609)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of returning immediately at the first error, please accumulate a vector of errors and then combine them at the end.  That way, we include all problems in the error message, not just the first one we encounter.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1652 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-Mel60XzBfCmiVrTQ5lr:-Mf-zV3eBgPvzrAlLvDY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/core/ext/xds/xds_api.cc#L1652)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We don't need to look at this field anymore.
</blockquote></details>

Done.
___
*[src/proto/grpc/testing/xds/v3/route.proto, line 37 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MelMuYZBoaf6Zwy68sz:-Mf0ZYTIDLoD0WFYhK_5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/src/proto/grpc/testing/xds/v3/route.proto#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove, since we aren't going to support this.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5535 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MelMadDBk48Fi0heIsv:-Mf10pOu2nV_aZ8hk6ar:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/test/cpp/end2end/xds_end2end_test.cc#L5535)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please also add a test that the retry policy is ignored if the env var is not set.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5547 at r4](https://revi [...]

2021-07-20 15:20 UTC, markdroth requested changes
This is getting close!  Remaining comments are all fairly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 6 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-Mf3VHyp8BIPBeRl04w2:b-hbhyps)* status: all files reviewed, 7 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 602 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3TWK108qmPJX-hMMY:-Mf3TWK108qmPJX-hMMZ:balvobk) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L602)):*
> ```cpp
>   // we will increase the size of args_to_add accordingly;
>   absl::InlinedVector<grpc_arg, 2> args_to_add;
>   size_t num_of_args_to_add = 0;
> ```

This is no longer needed.  Instead, just use `args_to_add.size()`.
___
*[src/core/ext/xds/xds_api.cc, line 1602 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3NUCo8mDjKrDNzocP:-Mf3NUCo8mDjKrDNzocQ:byjfb9m) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/src/core/ext/xds/xds_api.cc#L1602)):*
> ```cpp
>     } else {
>       if (GRPC_TRACE_FLAG_ENABLED(*context.tracer) &&
>           gpr_should_log(GPR_LOG_SEVERITY_INFO)) {
> ```

No need to check `gpr_should_log()` here.  That's already done by calling `gpr_log(GPR_INFO, ...)` below.
___
*[src/core/ext/xds/xds_api.cc, line 1608 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3RMfG7pYuGdim2Hm-:-Mf3RMfG7pYuGdim2Hm0:b7t9c30) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/src/core/ext/xds/xds_api.cc#L1608)):*
> ```cpp
>     }
>   }
>   // Until we add support for per_try_timeout, if retry_on is empty, we do not
> ```

Please phrase this as a TODO that when we add support for per_try_timeout, we will need to return a policy if per_try_timeout is set even if retry_on specified no supported policies.
___
*[src/core/ext/xds/xds_api.cc, line 1846 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3SCKx9DEK7YNXhm_x:-Mf3SCKx9DEK7YNXhm_y:b60a5d8) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/src/core/ext/xds/xds_api.cc#L1846)):*
> ```cpp
>         envoy_config_route_v3_RouteAction_retry_policy(route_action);
>     if (retry_policy != nullptr) {
>       absl::optional<XdsApi::Route::RetryPolicy> retry = absl::nullopt;
> ```

No need to explicitly say `= absl::nullopt`, since that's the default value for an `absl::optional<>`.
___
*[src/core/ext/xds/xds_api.cc, line 1899 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3SqjSBF2RymSYQ2V5:-Mf3SqjSBF2RymSYQ2V6:b-vstekf) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/src/core/ext/xds/xds_api.cc#L1899)):*
> ```cpp
>     // Parse retry policy.
>     absl::optional<XdsApi::Route::RetryPolicy> virtual_host_retry_policy =
>         absl::nullopt;
> ```

Same here: no need to say `= absl::nullopt`.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5556 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MelNOXJB-ma7JSVXPqE:-Mf3V60w6WBxdjRYhgYR:bslacs5) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/test/cpp/end2end/xds_end2end_test.cc#L5556)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look like this was actually done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5687 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3Uidw4qm7MTVT0l0Z:-Mf3Uidw4qm7MTVT0l0_:bnx1gzx) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/test/cpp/end2end/xds_end2end_test.cc#L5687)):*
> ```cpp
>   max_interval->set_nanos(250000000);
>   SetRouteConfiguration(0, new_route_config);
>   CheckRpcSendFailure(
> ```

Why is this RPC getting DEADLINE_EXCEEDED instead of UNAVAILABLE?  If we NACK the RDS config, the channel should be in state TRANSIENT_FAILURE, and the RPC should be failed on the client without ever being sent on the wire, so the fact that we're telling the server to fail with DEADLINE_EXCEEDED shouldn't matter.


<!-- Sent from Reviewable.io -->

2021-07-20 22:20 UTC, donnadionne reviewed
PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-Mf5-SbyB3KrPPhSIaxA:b-h8gvr0)* status: all files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 602 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3TWK108qmPJX-hMMY:-Mf4d1L72HJksj3rvFXM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L602)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is no longer needed.  Instead, just use `args_to_add.size()`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1602 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3NUCo8mDjKrDNzocP:-Mf4dQhF1HalvZrFoNqS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/src/core/ext/xds/xds_api.cc#L1602)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to check `gpr_should_log()` here.  That's already done by calling `gpr_log(GPR_INFO, ...)` below.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1608 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3RMfG7pYuGdim2Hm-:-Mf4dbHs76LoaHn3fL-6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/src/core/ext/xds/xds_api.cc#L1608)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please phrase this as a TODO that when we add support for per_try_timeout, we will need to return a policy if per_try_timeout is set even if retry_on specified no supported policies.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1846 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3SCKx9DEK7YNXhm_x:-Mf4duCW-Es8ymHPnDjU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/src/core/ext/xds/xds_api.cc#L1846)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to explicitly say `= absl::nullopt`, since that's the default value for an `absl::optional<>`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1899 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3SqjSBF2RymSYQ2V5:-Mf4du_w6xCKEZycRT_g:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/src/core/ext/xds/xds_api.cc#L1899)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here: no need to say `= absl::nullopt`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5556 at r4](https://reviewable.io/reviews/grpc/grpc/26566#-MelNOXJB-ma7JSVXPqE:-Mf5-Qg66i9x8xFWsiSE:b-ai19v8) ([raw file](https://github.com/grpc/grpc/blob/2942d3540cb18e220d8b9e2f35de3797f6019673/test/cpp/end2end/xds_end2end_test.cc#L5556)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this was actually done.
</blockquote></details>

fixed and added new test
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5687 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3Uidw4qm7MTVT0l0Z:-Mf4e-pa8z3WYmSdz8Ww:b-2g3elq) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/test/cpp/end2end/xds_end2end_test.cc#L5687)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this RPC getting DEADLINE_EXCEEDED instead of UNAVAILABLE?  If we NACK the RDS config, the channel should be in state TRANSIENT_FAILURE, and the RPC should be failed on the client without ever being sent on the wire, so the fact that we're telling the server to fail with DEADLINE_EXCEEDED shouldn't matter.
</blockquote></details>

discussed already


<!-- Sent from Reviewable.io -->

2021-07-21 16:14 UTC, markdroth requested changes
It looks like there are still a few changes needed in the tests.   Other than that, this looks great.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-Mf8ptRw1V8BMDRjM8r1:bvm2k0f)* status: all files reviewed, 3 unresolved discussions (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5687 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3Uidw4qm7MTVT0l0Z:-Mf8nIJnErw5ZNdyPR72:b-hht89w) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/test/cpp/end2end/xds_end2end_test.cc#L5687)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

discussed already
</blockquote></details>

This test still doesn't look right to me.

When we talked, you said that this was the case where there is no supported retry policy in retry_on, but that's not actually what this test is covering -- that scenario is the one covered in the previous test, XdsRetryPolicyUnsupportedStatusCode,  In that case, the right behavior is to ignore the retry policy, so the RPC would fail after just one attempt with DEADLINE_EXCEEDED sent by the server, and there would be no xDS NACK, and that's exactly what the previous test shows.

The case that is actually covered by this test is where num_retries is set to an invalid value.  In that case, we NACK the config, and the RPC should fail with UNAVAILABLE due to the channel being in TRANSIENT_FAILURE.  The request should never reach the backend, so it should not be failing with DEADLINE_EXCEEDED.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5638 at r7](https://reviewable.io/reviews/grpc/grpc/26566#-Mf8lRZ33IcCSlZcPVeW:-Mf8lRZ419ZvrrveudUX:b-i3uz1) ([raw file](https://github.com/grpc/grpc/blob/766875b8796d8ee342266386e3de9156c0d051ec/test/cpp/end2end/xds_end2end_test.cc#L5638)):*
> ```cpp
>   base_interval->set_seconds(1 * grpc_test_slowdown_factor());
>   base_interval->set_nanos(0);
>   auto max_interval =
> ```

Setting max_interval here is basically irrelevant to this particular test, since it never gets used.  Can you instead add a separate test that shows that setting max_interval works properly?  I think we can do that by setting the max interval to be the same as the base interval and then checking that the second retry has approximately (because of the jitter) the same delay as the first.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5779 at r7](https://reviewable.io/reviews/grpc/grpc/26566#-Mf8pVsb9t8-WevT-4Py:-Mf8pVsb9t8-WevT-4Pz:bwiacii) ([raw file](https://github.com/grpc/grpc/blob/766875b8796d8ee342266386e3de9156c0d051ec/test/cpp/end2end/xds_end2end_test.cc#L5779)):*
> ```cpp
>   max_interval->set_nanos(250000000);
>   SetRouteConfiguration(0, new_route_config);
>   CheckRpcSendFailure(
> ```

This is the same problem as in the XdsRetryPolicyInvalidNumRetriesZero test above: If we're NACKing the xDS config, then the channel should be in TRANSIENT_FAILURE and the RPC should fail with UNAVAILABLE without ever being sent to the backend.  If we're actually seeing DEADLINE_EXCEEDED here, then the behavior is wrong.


<!-- Sent from Reviewable.io -->

2021-07-22 05:41 UTC, donnadionne reviewed
Fixed/added tests. PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-MfBioye6xkq1RdymQmN:b46w8uj)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5687 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3Uidw4qm7MTVT0l0Z:-MfB_gYO2qdk9uxJwsGu:bh47dyy) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/test/cpp/end2end/xds_end2end_test.cc#L5687)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This test still doesn't look right to me.

When we talked, you said that this was the case where there is no supported retry policy in retry_on, but that's not actually what this test is covering -- that scenario is the one covered in the previous test, XdsRetryPolicyUnsupportedStatusCode,  In that case, the right behavior is to ignore the retry policy, so the RPC would fail after just one attempt with DEADLINE_EXCEEDED sent by the server, and there would be no xDS NACK, and that's exactly what the previous test shows.

The case that is actually covered by this test is where num_retries is set to an invalid value.  In that case, we NACK the config, and the RPC should fail with UNAVAILABLE due to the channel being in TRANSIENT_FAILURE.  The request should never reach the backend, so it should not be failing with DEADLINE_EXCEEDED.
</blockquote></details>

oh i see the problem, you are right, we should never reach the backend.

what happens here is that the LDS update continues to get NACKED, and xds client eventually times out trying to get resources (this can take about 15 seconds or so) and then we finally fail with code 14: UNAVAILABLE.

Please see this bit of log:

I0722 04:53:26.339399552      29 xds_end2end_test.cc:873]    ADS[0x1ef08f8]: client NACKed resource_type=type.googleapis.com/envoy.config.listener.v3.Listener version=: {"created":"@1626929606.329344684","description":"errors parsing LDS response","file":"src/core/ext/xds/xds_api.cc","file_line":2808,"referenced_errors":[{"created":"@1626929606.329342868","description":"server.example.com: validation error","file":"src/core/ext/xds/xds_api.cc","file_line":2803,"referenced_errors":[{"created":"@1626929606.329339419","description":"errors parsing retry policy","file":"src/core/ext/xds/xds_api.cc","file_line":1663,"referenced_errors":[{"created":"@1626929606.329338668","description":"RouteAction RetryPolicy num_retries set to invalid value 0.","file":"src/core/ext/xds/xds_api.cc","file_line":1617}]}]}]}
I0722 04:53:26.339415612      29 xds_end2end_test.cc:917]    ADS[0x1ef08f8]: client does not need update for type=type.googleapis.com/envoy.config.listener.v3.Listener name=server.example.com
I0722 04:53:41.311000676      27 xds_client.cc:204]          [xds_client 0x1f9beb0] {"created":"@1626929621.310974268","description":"timeout obtaining resource {type=type.googleapis.com/envoy.config.listener.v3.Listener name=server.example.com} from xds server","file":"src/core/ext/xds/xds_client.cc","file_line":200,"grpc_status":14}
E0722 04:53:41.311354093      27 xds_resolver.cc:901]        [xds_resolver 0x1f9b0a0] received error from XdsClient: {"created":"@1626929621.310974268","description":"timeout obtaining resource {type=type.googleapis.com/envoy.config.listener.v3.Listener name=server.example.com} from xds server","file":"src/core/ext/xds/xds_client.cc","file_line":200,"grpc_status":14}
I0722 04:53:41.311674732      21 xds_end2end_test.cc:2244]   donna send failed code 14 and msg timeout obtaining resource {type=type.googleapis.com/envoy.config.listener.v3.Listener name=server.example.com} from xds server


So i have changed the test such that the RPC will never timeout so that we will eventually get the UNAVAILABLE.

Note this is different from the cases where all backends are down, where we will detect transient failure and fail faster.

Also note all existing NACK tests have the same issue, RPC failed due to timeout (as timeouts are set and it's much earlier than xds client will give up getting resources), if you like this fix (setting timeout to 0 thus never timeout) I can fix all the other tests too (maybe separately)
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5638 at r7](https://reviewable.io/reviews/grpc/grpc/26566#-Mf8lRZ33IcCSlZcPVeW:-MfBiRslEkyVF6DlM1Me:b-rs2xg7) ([raw file](https://github.com/grpc/grpc/blob/766875b8796d8ee342266386e3de9156c0d051ec/test/cpp/end2end/xds_end2end_test.cc#L5638)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Setting max_interval here is basically irrelevant to this particular test, since it never gets used.  Can you instead add a separate test that shows that setting max_interval works properly?  I think we can do that by setting the max interval to be the same as the base interval and then checking that the second retry has approximately (because of the jitter) the same delay as the first.
</blockquote></details>

added: 2 retries relatively same delay.  did have a question, what does backoffMultiplier do?  
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5779 at r7](https://reviewable.io/reviews/grpc/grpc/26566#-Mf8pVsb9t8-WevT-4Py:-MfBaUae-DeawiO2ffpq:b-2dcrds) ([raw file](https://github.com/grpc/grpc/blob/766875b8796d8ee342266386e3de9156c0d051ec/test/cpp/end2end/xds_end2end_test.cc#L5779)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is the same problem as in the XdsRetryPolicyInvalidNumRetriesZero test above: If we're NACKing the xDS config, then the channel should be in TRANSIENT_FAILURE and the RPC should fail with UNAVAILABLE without ever being sent to the backend.  If we're actually seeing DEADLINE_EXCEEDED here, then the behavior is wrong.
</blockquote></details>

same fix


<!-- Sent from Reviewable.io -->

2021-07-22 16:27 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5638 at r7](https://reviewable.io/reviews/grpc/grpc/26566#-Mf8lRZ33IcCSlZcPVeW:-MfE1j7K7cThdqkH1Cd3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/766875b8796d8ee342266386e3de9156c0d051ec/test/cpp/end2end/xds_end2end_test.cc#L5638)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

added: 2 retries relatively same delay.  did have a question, what does backoffMultiplier do?  
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-22 16:53 UTC, markdroth requested changes
Thanks for catching the NACK problem!

Just a few remaining updates here.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-MfE7agbCjbREeU-JDak:b-rat7bi)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5687 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3Uidw4qm7MTVT0l0Z:-MfE6WZ-2kB8MCBWTH4w:b107pid) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/test/cpp/end2end/xds_end2end_test.cc#L5687)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

oh i see the problem, you are right, we should never reach the backend.

what happens here is that the LDS update continues to get NACKED, and xds client eventually times out trying to get resources (this can take about 15 seconds or so) and then we finally fail with code 14: UNAVAILABLE.

Please see this bit of log:

I0722 04:53:26.339399552      29 xds_end2end_test.cc:873]    ADS[0x1ef08f8]: client NACKed resource_type=type.googleapis.com/envoy.config.listener.v3.Listener version=: {"created":"@1626929606.329344684","description":"errors parsing LDS response","file":"src/core/ext/xds/xds_api.cc","file_line":2808,"referenced_errors":[{"created":"@1626929606.329342868","description":"server.example.com: validation error","file":"src/core/ext/xds/xds_api.cc","file_line":2803,"referenced_errors":[{"created":"@1626929606.329339419","description":"errors parsing retry policy","file":"src/core/ext/xds/xds_api.cc","file_line":1663,"referenced_errors":[{"created":"@1626929606.329338668","description":"RouteAction RetryPolicy num_retries set to invalid value 0.","file":"src/core/ext/xds/xds_api.cc","file_line":1617}]}]}]}
I0722 04:53:26.339415612      29 xds_end2end_test.cc:917]    ADS[0x1ef08f8]: client does not need update for type=type.googleapis.com/envoy.config.listener.v3.Listener name=server.example.com
I0722 04:53:41.311000676      27 xds_client.cc:204]          [xds_client 0x1f9beb0] {"created":"@1626929621.310974268","description":"timeout obtaining resource {type=type.googleapis.com/envoy.config.listener.v3.Listener name=server.example.com} from xds server","file":"src/core/ext/xds/xds_client.cc","file_line":200,"grpc_status":14}
E0722 04:53:41.311354093      27 xds_resolver.cc:901]        [xds_resolver 0x1f9b0a0] received error from XdsClient: {"created":"@1626929621.310974268","description":"timeout obtaining resource {type=type.googleapis.com/envoy.config.listener.v3.Listener name=server.example.com} from xds server","file":"src/core/ext/xds/xds_client.cc","file_line":200,"grpc_status":14}
I0722 04:53:41.311674732      21 xds_end2end_test.cc:2244]   donna send failed code 14 and msg timeout obtaining resource {type=type.googleapis.com/envoy.config.listener.v3.Listener name=server.example.com} from xds server


So i have changed the test such that the RPC will never timeout so that we will eventually get the UNAVAILABLE.

Note this is different from the cases where all backends are down, where we will detect transient failure and fail faster.

Also note all existing NACK tests have the same issue, RPC failed due to timeout (as timeouts are set and it's much earlier than xds client will give up getting resources), if you like this fix (setting timeout to 0 thus never timeout) I can fix all the other tests too (maybe separately)
</blockquote></details>

Good catch!  I guess a lot of these tests have been failing with DEADLINE_EXCEEDED instead of UNAVAILABLE, but we never knew it, because the tests aren't checking the status code from the failure.

I've sent you #26757 to fix this.  If you merge in the changes from that PR, you should be able to use the new `WaitForRdsNack()` method in these NACK tests.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5638 at r7](https://reviewable.io/reviews/grpc/grpc/26566#-Mf8lRZ33IcCSlZcPVeW:-MfE6xBs4qQ4lv9viZNh:be1r3eb) ([raw file](https://github.com/grpc/grpc/blob/766875b8796d8ee342266386e3de9156c0d051ec/test/cpp/end2end/xds_end2end_test.cc#L5638)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

See https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md for an explanation of the backoff algorithm.  Note that there doesn't appear to be any way to set the backoffMultiplier parameter via xDS.

Please remove max_interval in this test, since it's now covered in the other test you added.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5679 at r8](https://reviewable.io/reviews/grpc/grpc/26566#-MfE7TyE-mOD9t8J1eNy:-MfE7TyE-mOD9t8J1eNz:b-dc2las) ([raw file](https://github.com/grpc/grpc/blob/d426637b28039a4611dfc48498aa9d8064bbdb0e/test/cpp/end2end/xds_end2end_test.cc#L5679)):*
> ```cpp
>   base_interval->set_seconds(1 * grpc_test_slowdown_factor());
>   base_interval->set_nanos(0);
>   auto max_interval =
> ```

Just as a sanity check, please verify that this test fails if you remove the max_interval setting here.


<!-- Sent from Reviewable.io -->

2021-07-22 22:44 UTC, donnadionne reviewed
Fixed according to comments.
Fixed test after the NACK PR was merged, PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-MfFNylxC7hG4BKlFrqe:b-bslwom)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5687 at r6](https://reviewable.io/reviews/grpc/grpc/26566#-Mf3Uidw4qm7MTVT0l0Z:-MfEQ-PpBgcxIq6DSyJO:b-5xfh7t) ([raw file](https://github.com/grpc/grpc/blob/808ae48f239928363213b60172e56182ac8cdc4b/test/cpp/end2end/xds_end2end_test.cc#L5687)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Good catch!  I guess a lot of these tests have been failing with DEADLINE_EXCEEDED instead of UNAVAILABLE, but we never knew it, because the tests aren't checking the status code from the failure.

I've sent you #26757 to fix this.  If you merge in the changes from that PR, you should be able to use the new `WaitForRdsNack()` method in these NACK tests.
</blockquote></details>

ok super cool, i'll merge
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5638 at r7](https://reviewable.io/reviews/grpc/grpc/26566#-Mf8lRZ33IcCSlZcPVeW:-MfEPjvT6hAMsrRO_On7:bb7f2mf) ([raw file](https://github.com/grpc/grpc/blob/766875b8796d8ee342266386e3de9156c0d051ec/test/cpp/end2end/xds_end2end_test.cc#L5638)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

See https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md for an explanation of the backoff algorithm.  Note that there doesn't appear to be any way to set the backoffMultiplier parameter via xDS.

Please remove max_interval in this test, since it's now covered in the other test you added.
</blockquote></details>

done
___
*[test/cpp/end2end/xds_end2end_test.cc, line 5679 at r8](https://reviewable.io/reviews/grpc/grpc/26566#-MfE7TyE-mOD9t8J1eNy:-MfEPkqU7vHQwtcDLney:b-5v0mjo) ([raw file](https://github.com/grpc/grpc/blob/d426637b28039a4611dfc48498aa9d8064bbdb0e/test/cpp/end2end/xds_end2end_test.cc#L5679)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Just as a sanity check, please verify that this test fails if you remove the max_interval setting here.
</blockquote></details>

checked!

also documented in the test the behaviour.

Basically the LongBackOff and MaxBackOff tests are the same except for the max backoff setting, and we expect different number of retries.


<!-- Sent from Reviewable.io -->

2021-07-23 15:29 UTC, markdroth approved these changes
This looks great!

> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26566#-:-MfIyws44JvN5zfl6yf1:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5679 at r8](https://reviewable.io/reviews/grpc/grpc/26566#-MfE7TyE-mOD9t8J1eNy:-MfIybwf3ebof6z_1y0o:blz5bi7) ([raw file](https://github.com/grpc/grpc/blob/d426637b28039a4611dfc48498aa9d8064bbdb0e/test/cpp/end2end/xds_end2end_test.cc#L5679)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

checked!

also documented in the test the behaviour.

Basically the LongBackOff and MaxBackOff tests are the same except for the max backoff setting, and we expect different number of retries.
</blockquote></details>

Yup, this looks great!


<!-- Sent from Reviewable.io -->

2021-07-23 19:17 UTC, donnadionne commented
tsan and c-to-p interop are both known issues in fusion

2021-07-23 19:17 UTC, merged