Move resource_user ownership into chttp2 transport/server/connector
grpc/grpc pull request #26643
Opened 2021-07-09 06:38 UTC by drfloob

WIP

2021-07-12 23:40 UTC, markdroth requested changes
This looks like a great start!

My main comment is that I think the endpoint impls themselves should not be passed the resource_user to begin with; they should use a slice allocator instead, since that's how we're going to want things to be structured when we move to EventEngine.  Structuring them that way now will make the migration easier later.

Please let me know if you have any questions.  Thanks!

> Reviewed 89 of 89 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-MeS4ec721hmSyr4ZtjS:b-4ml1s6)* status: all files reviewed, 21 unresolved discussions (waiting on @drfloob)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 175 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS-ttA27F4TkTO3Dx5:-MeS-ttA27F4TkTO3Dx6:bexqngv) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L175)):*
> ```cpp
>           // pending read/write callbacks.  This should be fixed, at which
>           // point this can be removed.
>           grpc_endpoint_shutdown(args->endpoint, GRPC_ERROR_REF(error));
> ```

This is an example of a place where we will need to clean up the resource_user if we plumb it through the handshakers.  (See my comment in handshaker.h for context.)
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 401 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS004j7-fth62b03fW:-MeS004j7-fth62b03fX:bexqngv) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/server/chttp2_server.cc#L401)):*
> ```cpp
>         // pending read/write callbacks.  This should be fixed, at which
>         // point this can be removed.
>         grpc_endpoint_shutdown(args->endpoint, GRPC_ERROR_NONE);
> ```

This is an example of a place where we will need to clean up the resource_user if we plumb it through the handshakers.  (See my comment in handshaker.h for context.)
___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 474 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeR_rtqEKX_azzf_XRD:-MeR_rtqEKX_azzf_XRE:b-yslcci) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L474)):*
> ```cpp
>   grpc_chttp2_stream_map_init(&stream_map, 8);
> 
>   grpc_resource_user_ref(resource_user);
> ```

It would probably make sense to have the ctor take ownership of a ref passed by the caller, since most callers are just unreffing after they pass this in anyway.  This would avoid a needless ref and unref.
___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 775 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRZBNI5lbxQ2adqV4Z:-MeRJu8XEhwUo7dPgknK:b-5m3tg7) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L775)):*
> ```cpp
>   // accepted since the latter will create the call which costs much memory.
>   GPR_ASSERT(t->resource_user != nullptr);
>   if (!grpc_resource_user_could_alloc(t->resource_user,
> ```

It looks like this is changing from actually allocating memory to instead just checking whether we *could* allocate memory.  Why is that okay?  I think we do actually still need to allocate this memory, because we're still creating a new stream here.

If the goal here is to do this allocation only on the server side (because previously, if I'm reading the code right, that was the only case where `t->resource_user` was non-null -- and it's also the only case where this function gets called), then I think we should instead check `t->is_client`.
___
*[src/core/ext/transport/chttp2/transport/internal.h, line 299 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRJA9k-J7Facl5SVVw:-MeRJA9k-J7Facl5SVVx:buhzhtm) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/internal.h#L299)):*
> ```objc
>   std::string peer_string;
> 
>   grpc_resource_user* resource_user = nullptr;
> ```

Why is this now initialized to nullptr?  Doesn't this always get initialized to a real value when the transport is constructed anyway?
___
*[src/core/lib/channel/handshaker.h, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS4IXe2hEf1E4Ili1w:-MeS4IXe2hEf1E4Ili1x:bln7s2s) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.h#L56)):*
> ```objc
> /// handshaker may modify \a args.
> ///
> /// A handshaker takes ownership of the members while a handshake is in
> ```

If you're adding the resource user to the handshaker API, then you need to change all handshaker implementations and all code that uses the handshakers to comply with ownership the rule documented here.  In particular, that means that everywhere that we clean up the endpoint, we also need to clean up the resource_user.

I think there are actually a fair number of edge cases here.  I've added some other comments pointing out a few of them, but that's not an exhaustive list; you'll have to audit the code to find them all.  If this winds up getting too complicated, then you may want to consider not plumbing the resource_user through the handshakers right now, since we really don't actually need that for anything yet.
___
*[src/core/lib/channel/handshaker.cc, line 110 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS-ckI7J4XF0S-OMpp:-MeS-ckI7J4XF0S-OMpq:bexqngv) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.cc#L110)):*
> ```cpp
>         // pending read/write callbacks.  This should be fixed, at which
>         // point this can be removed.
>         grpc_endpoint_shutdown(args_.endpoint, GRPC_ERROR_REF(error));
> ```

This is an example of a place where we will need to clean up the resource_user if we plumb it through the handshakers.  (See my comment in handshaker.h for context.)
___
*[src/core/lib/http/httpcli.cc, line 67 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS0KRSEKAxT9ygbM82:-MeS0KRSEKAxT9ygbM83:b-63nyfg) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/http/httpcli.cc#L67)):*
> ```cpp
>   grpc_closure connected;
>   grpc_error_handle overall_error;
>   grpc_resource_quota* resource_quota;
> ```

If we're now passing in a resource_user, do we still need the resource_quota here?  I suspect not.
___
*[src/core/lib/iomgr/endpoint.h, line 49 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRAUC_0Kj0uTIoFXCm:-MeRAUC_0Kj0uTIoFXCn:b-oogfow) ([raw file](https://github.com/grpc/grpc/blob/095045b31cf5fbccbd65e71d24617c50fce02d3c/src/core/lib/iomgr/endpoint.h#L49)):*
> ```objc
>   void (*shutdown)(grpc_endpoint* ep, grpc_error_handle why);
>   void (*destroy)(grpc_endpoint* ep);
>   grpc_resource_user* (*get_resource_user)(grpc_endpoint* ep);
> ```

Just FYI, I'm fairly sure that this change will require internal changes, so you'll need to do a cherry-pick import for this.
___
*[src/core/lib/iomgr/endpoint_pair.h, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS1Kf05mWFBBjhIw_T:-MeS1Kf05mWFBBjhIw_U:b-kfholc) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/iomgr/endpoint_pair.h#L30)):*
> ```objc
>   grpc_endpoint* server;
> };
> grpc_endpoint_pair grpc_iomgr_create_endpoint_pair(
> ```

I suggest having this take ownership of the refs to the resource_users, since basically every caller winds up unreffing them immediately after calling this.
___
*[src/core/lib/iomgr/resource_quota.cc, line 780 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRBlFS9naGsIJyPtSz:-MeRBlFS9naGsIJyPtT-:bp77gdr) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/iomgr/resource_quota.cc#L [...]

2021-07-13 05:25 UTC, drfloob reviewed
Thanks for the review, Mark!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-MeStb5K9NmR6FrBCEMi:blio1lc)* status: 78 of 89 files reviewed, 21 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 175 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS-ttA27F4TkTO3Dx5:-MeSL8Wv8t8wjcqcLK_-:b-e1jjni) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L175)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is an example of a place where we will need to clean up the resource_user if we plumb it through the handshakers.  (See my comment in handshaker.h for context.)
</blockquote></details>

Thanks for pointing this out. Please see my reply on handshaker.h.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 401 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS004j7-fth62b03fW:-MeTGNoi5-pxUGfDwgeu:b-854ue6) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/server/chttp2_server.cc#L401)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is an example of a place where we will need to clean up the resource_user if we plumb it through the handshakers.  (See my comment in handshaker.h for context.)
</blockquote></details>

Ack. See related comments.
___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 474 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeR_rtqEKX_azzf_XRD:-MeSM3njA_BBHvN0vxh6:b5dz974) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L474)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It would probably make sense to have the ctor take ownership of a ref passed by the caller, since most callers are just unreffing after they pass this in anyway.  This would avoid a needless ref and unref.
</blockquote></details>

About 1/3 (7 of 24) of the uses of `grpc_create_chttp2_transport` will need an extra `grpc_resource_user_ref` call before transport creation, either because the caller doesn't explicitly own a ref already, or because the RU is still needed by the caller after the transport is created. I've made that change in commit 0201f3db1, but I find the API a bit less intuitive.
___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 775 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRZBNI5lbxQ2adqV4Z:-MeS75nB3GUPR5pisgCx:b-73g3nb) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L775)):*
Right, I spent a good amount of time debugging to figure out that this code would allocate `GRPC_RESOURCE_QUOTA_CALL_SIZE` bytes (15K) on the server-side transport's RU and later try to free those bytes on the client transport's RU. https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L720-L722.

I think your suggestion will work, checking for `is_client` where those bytes would be freed.

> Why is that okay? 

```
// TODO(juanlishen): This is a hack. We need to do real accounting instead of
// hard coding.
constexpr size_t GRPC_RESOURCE_QUOTA_CALL_SIZE = 15 * 1024;
```

Maybe this buffer alloc was a bit speculative. As far as I'm aware, no test suffered from insufficient RU buffer allocation, but I think it could theoretically result in more dynamic memory allocation.
___
*[src/core/ext/transport/chttp2/transport/internal.h, line 299 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRJA9k-J7Facl5SVVw:-MeSC-9mC9nbM1Kjp_r6:b-kxn2cg) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/internal.h#L299)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this now initialized to nullptr?  Doesn't this always get initialized to a real value when the transport is constructed anyway?
</blockquote></details>

Good question. I think it may always be initialized now, but that was not the case in some middle steps for this PR. I spent some unnecessary time debugging what turned out to be a garbage pointer, and this default assignment would have saved me that time. For any future developer on this code (including myself), I think it's valuable to keep this sane default.
___
*[src/core/lib/channel/handshaker.h, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS4IXe2hEf1E4Ili1w:-MeSD_FV7VNYNaG0RGeE:bvsu6u8) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.h#L56)):*
> since we really don't actually need that for anything yet.

See https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/server/chttp2_server.cc#L410-L411 (also linked in the PR description, since we had chatted about it before). The OnHandshakeDone method needs the endpoint's RU here to create the transport. This is the one place it's necessary, and the only thing currently motivating the need for the handshaker API change. I didn't see an obvious way to get the endpoint's RU here without passing it through the handshaker implementations. Can you recommend a clean-ish workaround?  I'd love to avoid changing the handshaker APIs right now, tracking down all the pieces that needed to change in the handshaker impls was pretty tedious.

The comment is out of sync, since the handshaker does not take a ref on an RU.
___
*[src/core/lib/channel/handshaker.cc, line 110 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS-ckI7J4XF0S-OMpp:-MeSFAVu74v8VBGSzhiB:b-mxfubu) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.cc#L110)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is an example of a place where we will need to clean up the resource_user if we plumb it through the handshakers.  (See my comment in handshaker.h for context.)
</blockquote></details>

The handshaker does not take a ref on an RU, and endpoints are responsible for reffing and unreffing the RUs they own. For the most part, wherever the handshaker passes and endpoint, it must also now pass the endpoint's RU, so their lifetimes can be managed together. I don't think there is any extra cleanup required here, and the RU is already plumbed through the handshakers.
___
*[src/core/lib/http/httpcli.cc, line 67 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS0KRSEKAxT9ygbM82:-MeSGsDTDdMefJ2ekDLU:bkkye4j) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/http/httpcli.cc#L67)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're now passing in a resource_user, do we still need the resource_quota here?  I suspect not.
</blockquote></details>

You're right, we can access the resource_quota from the resource_user. Done.
___
*[src/core/lib/iomgr/endpoint.h, line 49 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRAUC_0Kj0uTIoFXCm:-MeSOFni-UCuLqq5xrMw:b2nhb2c) ([raw file](https://github.com/grpc/grpc/blob/095045b31cf5fbccbd65e71d24617c50fce02d3c/src/core/lib/iomgr/endpoint.h#L49)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Just FYI, I'm fairly sure that this change will require internal changes, so you'll need to do a cherry-pick import for this.
</blockquote></details>

Ack
___
*[src/core/lib/iomgr/endpoint_pair.h, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS1Kf05mWFBBjhIw_T:-MeSHx6h2kAW5nzqMSlx:b-jwbx8i) ([raw file](https://git [...]

2021-07-13 16:43 UTC, markdroth requested changes
This is moving in the right direction.  I think the ref handling of the RU needs some more work.

Please let me know if you have any questions.  Thanks!

> Reviewed 42 of 42 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-MeVjWAJ14E5vIv1Q-Np:b-8ruo8p)* status: all files reviewed, 15 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 189 at r3](https://reviewable.io/reviews/grpc/grpc/26643#-MeVJkhlA3dftzI350ha:-MeVJkhlA3dftzI350hb:binoctb) ([raw file](https://github.com/grpc/grpc/blob/3d9350287de2d5e8b5ea73aa22f28dce868606d1/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L189)):*
> ```cpp
>       // The transport expects an RU ref, but none are held in the
>       // HandshakerArgs.
>       grpc_resource_user_ref(args->resource_user);
> ```

If we're not holding a ref here, then we don't know that this object is alive, so it's not safe to take a new ref in the first place.

As it happens, taking this ref probably *does* work, because we're holding a ref in `resource_user_` anyway, so we are guaranteed that this object will still be alive.  However, we're not actually dropping the ref we're holding in `resource_user_`, so it looks to me like this will result in a memory leak.

In general, I find the ref handling throughout this PR to be very confusing.  You seem to be using a model whereby functions take their own ref instead of having them take ownership of a ref from the caller (with an even more confusing semantic for the handshakers of not having them hold a ref at all), and I think that makes the code very hard to follow.  Here's what I see happening now:
- We create the resource user and store it in `resource_user_`, which holds one ref.
- We pass it to `grpc_tcp_client_connect()`, which takes its own ref, leaving us with a ref in `resource_user_`.
- The code in `grpc_tcp_client_connect()` calls `grpc_tcp_create()`, which takes its own ref, and then `grpc_tcp_client_connect()` drops its ref.   This means that the code in `grpc_tcp_client_connect()` needs to drop the ref in two different places, both the success case and the failure case.
- Back here in `Chttp2Connector`, we are *not* passing ownership of that ref to the handshakers, but we're continuing to hold a ref in `resource_user_`.
- When the handshake finishes, we take a new ref of `args->resource_user` (which, as I mentioned, is safe only because we're actually holding a ref to `resource_user_`, so you can basically think of this as taking a ref to `resource_user_` instead) to pass to the chttp2 transport.
- The `Chttp2Connector` code is failing to unref in the success case.

I think this will all get much simpler if you adopt the convention that all new objects will take ownership of a ref passed from the caller.  This is consistent with how things will work in the future when the resource quota code is eventually converted to C++, because then we'll pass this in as a `RefCountedPtr<ResourceUser>`,  and the compiler will enforce that the new object takes ownership of the ref.  The code will flow as follows:
- We create the resource user and store it in `resource_user_`, which holds one ref.
- We take a new ref to pass to `grpc_tcp_client_connect()`, which takes ownership of that new ref.
- In `grpc_tcp_client_connect()`, if the connection succeeds, it passes ownership of the ref it's holding to `grpc_tcp_connect()`.  The only time it needs to unref explicitly is in the failure case.
- Back here in `Chttp2Connector`, we pass ownership of the existing ref in `resource_user_` to the handshakers.  (Once these APIs are converted to C++, this will be basically passing `std::move(resource_user_)` to the handshakers; in the current code, this will involve manually setting `resource_user_` to null after passing ownership of the ref to the handshakers.)
- When the handshake finishes, we pass ownership of `args->resource_user` to the new chttp2 transport instance.  (Once these APIs are converted to C++, this will be basically passing `std::move(args->resource_user)` to the chttp2 transport ctor.)
- The `Chttp2Connector` code no longer needs to free the resource user except on failure cases (i.e., in `Connected()` if the connection attempt fails and here in `OnHandshakeDone()` if we were shut down after the handshaking completed).  This can be done only if `resource_user_` is not null.
___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.h, line 37 at r3](https://reviewable.io/reviews/grpc/grpc/26643#-MeVIjmK93Brk7Acika7:-MeVIjmK93Brk7Acika8:b-zexlpz) ([raw file](https://github.com/grpc/grpc/blob/3d9350287de2d5e8b5ea73aa22f28dce868606d1/src/core/ext/transport/chttp2/transport/chttp2_transport.h#L37)):*
> ```objc
> extern bool g_flow_control_enabled;
> 
> /// Creates a CHTTP2 Transport. This steals a \a resource_user ref from the
> ```

s/steals/takes ownership of/
___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 474 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeR_rtqEKX_azzf_XRD:-MeVIqzW2IfUIp5HpU3h:bwe2mir) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L474)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

About 1/3 (7 of 24) of the uses of `grpc_create_chttp2_transport` will need an extra `grpc_resource_user_ref` call before transport creation, either because the caller doesn't explicitly own a ref already, or because the RU is still needed by the caller after the transport is created. I've made that change in commit 0201f3db1, but I find the API a bit less intuitive.
</blockquote></details>

I don't think most callers actually do need another ref for this.  I think the fact that the code is currently written that way is a symptom of the fact that you're not having the handshakers take ownership of a ref, as per my comments elsewhere.

I think that having this take ownership is actually intuitive if you think about the fact that when we eventually convert the resource quota code to C++, we'll wind up passing this in as a `RefCountedPtr<ResourceUser>`.  That will have the function take ownership of a ref, and the compiler will be able to enforce that fact.
___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 775 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRZBNI5lbxQ2adqV4Z:-MeVd2lTDcLTwNoHIU_F:bo7m2mj) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L775)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Right, I spent a good amount of time debugging to figure out that this code would allocate `GRPC_RESOURCE_QUOTA_CALL_SIZE` bytes (15K) on the server-side transport's RU and later try to free those bytes on the client transport's RU. https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L720-L722.

I think your suggestion will work, checking for `is_client` where those bytes would be freed.

> Why is that okay? 

```
// TODO(juanlishen): This is a hack. We need to do real accounting instead of
// hard coding.
constexpr size_t GRPC_RESOURCE_QUOTA_CALL_SIZE = 15 * 1024;
```

Maybe this buffer alloc was a bit speculative. As far as I'm aware, no test suffered from insufficient RU buffer allocation, but I think it could theoretically result in more dynamic memory allocation.
</blockquote></details>

It wasn't freeing the bytes on the client transport; it was freeing them when the stream was destroyed on the server side.  It was the same RU in both cases -- if it wasn't, then one of the RUs would wind up negative and the other would never free all of its bytes.  Also, if the client and server are not on the same machine, this wouldn't make any sense.

Allocating bytes on the resource user is [...]

2021-07-14 21:45 UTC, drfloob reviewed
Thanks for the feedback. It'll take some time to redo this work, so some of these discussions will continue in a few days.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-MeayaEh-ylPr1T9ClNv:bd3jx5i)* status: all files reviewed, 15 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 189 at r3](https://reviewable.io/reviews/grpc/grpc/26643#-MeVJkhlA3dftzI350ha:-MeVpQGFCNKfrIsfg6hV:bb8k10w) ([raw file](https://github.com/grpc/grpc/blob/3d9350287de2d5e8b5ea73aa22f28dce868606d1/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L189)):*
I'll make that change for you. Responding to a few points for clarity:

> If we're not holding a ref here, then we don't know that this object is alive, so it's not safe to take a new ref in the first place.

Why it works: the non-null endpoint holds a ref to that resource_user, therefore we know it's safe to trust that the object is alive (long enough to ref it here at least, presuming no other async operation kills the endpoint between execution of lines 188 and 189, which ... I think can't happen). They implicitly share a lifetime in the handshaker args (note: that'll change per your feedback). Given that it's not clear to you, it's probably not an intuitive design, so it'll have to change.

> In general, I find the ref handling throughout this PR to be very confusing ... I think this will all get much simpler if you adopt the convention that all new objects will take ownership of a ref passed from the caller. 

Ok, I'll rework the PR and see. Thanks for the suggestion.
___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.h, line 37 at r3](https://reviewable.io/reviews/grpc/grpc/26643#-MeVIjmK93Brk7Acika7:-MeVqIJuBUk3IQv-Nv5b:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3d9350287de2d5e8b5ea73aa22f28dce868606d1/src/core/ext/transport/chttp2/transport/chttp2_transport.h#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/steals/takes ownership of/
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 775 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRZBNI5lbxQ2adqV4Z:-MeVqnX_3VhqwDb7vORY:b-3nt4fo) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L775)):*
> if it wasn't, then one of the RUs would wind up negative and the other would never free all of its bytes

Exactly. Freeing 15k from an 8k buffer failed an assertion, and the other would have never freed its bytes. It's non-obvious, but that's what was happening.

Regarding the second point, if the code calls `grpc_resource_user_alloc_slices`, it'll do an RU allocation if the RU buffer is not large enough, which means the `safe_alloc` step isn't strictly necessary (caveat: unlike safe_alloc, this would trigger reclaimers if the RQ is maxed out).  https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/resource_quota.cc#L1012-L1014. You're right about the malloc piece, my mistake. As for allocating memory outside the RU, I have no argument there.
___
*[src/core/lib/channel/handshaker.h, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS4IXe2hEf1E4Ili1w:-MeaajKPBxYj_uM7Sw_v:b-lbg7xm) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.h#L56)):*
> Since the value is already stored in the resource_user_ data member, that data member can be used directly in (2), without having to pass it through the handshakers at all.

That's true for the `Chttp2Connector` already, I made that change in this PR. The problem is with `Chttp2ServerListener::ActiveConnection::HandshakingState::OnHandshakeDone`, which has no stored `resource_user` member anywhere accessible (afaict). There may be a way that a slice allocator factory can help, but I'm not seeing it in this listener/connection/handshaker flow at the moment.
___
*[src/core/lib/channel/handshaker.cc, line 110 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS-ckI7J4XF0S-OMpp:-MeaYI2EB1Vr4VmkrWn1:b-nkfvfz) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.cc#L110)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned elsewhere, the problem is that the handshakers *should* take ownership of the ref to the RU.
</blockquote></details>

Understood. Restating the plan: if I can avoid the handshaker API changes, I will. Otherwrise, I'll have them hold refs.
___
*[src/core/lib/http/httpcli.cc, line 67 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS0KRSEKAxT9ygbM82:-MeaZtxn-9ARf2FwjUWn:b-cgt3yt) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/http/httpcli.cc#L67)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need to access the resource quota at all.  It looks like the only thing we're using it for is to set a channel arg to pass to `grpc_tcp_client_connect()`, but this PR is changing `grpc_tcp_client_connect()` not to get the RQ from channel args in the first place, so I don't think we need to set that channel arg anymore.
</blockquote></details>

Removed, good call. None of the current tcp client impls rely on getting the grpc_resource_quota from channel_args.
___
*[test/core/end2end/fixtures/h2_sockpair.cc, line 145 at r3](https://reviewable.io/reviews/grpc/grpc/26643#-MeVgBrs3HoJ19qSBVnA:-Mea0-x61qNSK173x1Tu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3d9350287de2d5e8b5ea73aa22f28dce868606d1/test/core/end2end/fixtures/h2_sockpair.cc#L145)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the `ExecCtx` here anymore.
</blockquote></details>

Done.
___
*[test/core/end2end/fixtures/h2_sockpair+trace.cc, line 150 at r3](https://reviewable.io/reviews/grpc/grpc/26643#-MeVgGL1-Wbf5ARrur5f:-Mea01GoCaiks5_llPSE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3d9350287de2d5e8b5ea73aa22f28dce868606d1/test/core/end2end/fixtures/h2_sockpair+trace.cc#L150)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this `ExecCtx` anymore.
</blockquote></details>

Done.
___
*[test/core/end2end/fixtures/h2_sockpair_1byte.cc, line 156 at r3](https://reviewable.io/reviews/grpc/grpc/26643#-MeVgKl97smBIRVAdEAS:-Mea04Kh71QSy1gsjt3A:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3d9350287de2d5e8b5ea73aa22f28dce868606d1/test/core/end2end/fixtures/h2_sockpair_1byte.cc#L156)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this `ExecCtx` anymore.
</blockquote></details>

Done.
___
*[test/cpp/microbenchmarks/bm_chttp2_transport.cc, line 75 at r3](https://reviewable.io/reviews/grpc/grpc/26643#-MeVgywXCc640BAHxkNO:-Mea06KF93g1JSQvU8hK:b-dihxyy) ([raw file](https://github.com/grpc/grpc/blob/3d9350287de2d5e8b5ea73aa22f28dce868606d1/test/cpp/microbenchmarks/bm_chttp2_transport.cc#L75)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Isn't this basically re-adding the endpoint method to get the RU, which is exactly what we're removing in this PR?  Seems like it would be more consistent to instead create this in the fixture and pass it into `PhonyEndpoint` as an argument to the ctor.
</blockquote></details>

Yep, exactly. Missed this hack cleanup. Thanks.
___
*[test/cpp/microbenchmarks/fullstack_streaming_ping_pong.h, line 50 at r3](https://reviewable.io/reviews/grpc/grpc/26643#-MeVhcUV1GRmk7BNfBRp:-Mea0TOAAKvtpRCx9kSu:b-z1upc5) ([raw file](https://github.com/grpc/grpc/blob/3d9350287de2d5e8b5ea73aa22f28dce868606d1/test/cpp/microbenchmarks/fullstack_streaming_ping_pong.h#L50)): [...]

2021-07-16 19:15 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: all files reviewed, 15 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 775 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRZBNI5lbxQ2adqV4Z:-MekTKGP-OeWT17kfl51:b-ehq9gz) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L775)):*
> Regarding the second point, if the code calls grpc_resource_user_alloc_slices, it'll do an RU allocation if the RU buffer is not large enough, which means the safe_alloc step isn't strictly necessary (caveat: unlike safe_alloc, this would trigger reclaimers if the RQ is maxed out).  https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/resource_quota.cc#L1012-L1014.

Sorry, I don't understand what you're saying here.  Why would we change this to use `grpc_resource_user_alloc_slices()`?  We're using the resource_user directly here, not via a slice allocator.  And it looks like the code here wants to fail the allocation if the memory isn't available immediately, rather that running reclaimers and allocating asynchronously.
___
*[src/core/lib/channel/handshaker.h, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS4IXe2hEf1E4Ili1w:-MekXSbe958WiJlqaU0Y:b-oheqdh) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.h#L56)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

> Since the value is already stored in the resource_user_ data member, that data member can be used directly in (2), without having to pass it through the handshakers at all.

That's true for the `Chttp2Connector` already, I made that change in this PR. The problem is with `Chttp2ServerListener::ActiveConnection::HandshakingState::OnHandshakeDone`, which has no stored `resource_user` member anywhere accessible (afaict). There may be a way that a slice allocator factory can help, but I'm not seeing it in this listener/connection/handshaker flow at the moment.
</blockquote></details>

On the server side, the general approach should be:
- Change the `grpc_event_engine::experimental::SliceAllocator` and `grpc_event_engine::experimental::SliceAllocatorFactory` APIs to be interfaces (i.e., the `SliceAllocator::Allocat()` and `SliceAllocatorFactory::CreateSliceAllocator()` methods should be pure virtual).
- Add a parameter to `grpc_tcp_server_start()` to allow passing in a `SliceAllocatorFactory` instance to use.  Also add a parameter to the `OnAccept()` callback type for the resulting `SliceAllocator`.  The idea here is that when a connection comes in, the `grpc_tcp_server` will use the `SliceAllocatorFactory` to create a new `SliceAllocator`.  It will then pass a pointer to that `SliceAllocator` to the endpoint it is creating for the connection, and it will pass the `SliceAllocator` to `OnAccept()`, which will take ownership of it.
- Have the chttp2 code provide implementations of `SliceAllocator` and `SliceAllocatorFactory` called `Chttp2SliceAllocator` and `Chttp2SliceAllocatorFactory`.  The implementation of `Chttp2SliceAllocator` will take a resource_user as a parameter, which it will take ownership of, and will have a method for getting the underlying resource_user.  The implementation of `Chttp2SliceAllocatorFactory` will create a new resource_user, then create a new `Chttp2SliceAllocator` and pass the resource_user to it.
- In `Chttp2ServerListener::StartListening()`, create a `Chttp2SliceAllocatorFactory` and pass it to `grpc_tcp_server_start()`.
- In `Chttp2ServerListener::OnAccept()`, take ownership of the `SliceAllocator`, which can be stored in `Chttp2ServerListener::ActiveConnection::HandshakingState`.  When handshaking is complete, ownership of the `SliceAllocator` can be passed to the resulting transport instance.  (You can down-cast the `SliceAllocator` to `Chttp2SliceAllocator` to access the underlying resource_user.)

Note that this is exactly what we're going to need to do to use `SliceAllocator` and `SliceAllocatorFactory` when we move to EventEngine.  So if it turns out that there's some problem with this, we need to solve it anyway.


<!-- Sent from Reviewable.io -->

2021-07-19 19:21 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 37 of 95 files reviewed, 15 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/lib/channel/handshaker.h, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS4IXe2hEf1E4Ili1w:-Mf-55cg22LoVP1S9IsW:b-ox6a5x) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.h#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

On the server side, the general approach should be:
- Change the `grpc_event_engine::experimental::SliceAllocator` and `grpc_event_engine::experimental::SliceAllocatorFactory` APIs to be interfaces (i.e., the `SliceAllocator::Allocat()` and `SliceAllocatorFactory::CreateSliceAllocator()` methods should be pure virtual).
- Add a parameter to `grpc_tcp_server_start()` to allow passing in a `SliceAllocatorFactory` instance to use.  Also add a parameter to the `OnAccept()` callback type for the resulting `SliceAllocator`.  The idea here is that when a connection comes in, the `grpc_tcp_server` will use the `SliceAllocatorFactory` to create a new `SliceAllocator`.  It will then pass a pointer to that `SliceAllocator` to the endpoint it is creating for the connection, and it will pass the `SliceAllocator` to `OnAccept()`, which will take ownership of it.
- Have the chttp2 code provide implementations of `SliceAllocator` and `SliceAllocatorFactory` called `Chttp2SliceAllocator` and `Chttp2SliceAllocatorFactory`.  The implementation of `Chttp2SliceAllocator` will take a resource_user as a parameter, which it will take ownership of, and will have a method for getting the underlying resource_user.  The implementation of `Chttp2SliceAllocatorFactory` will create a new resource_user, then create a new `Chttp2SliceAllocator` and pass the resource_user to it.
- In `Chttp2ServerListener::StartListening()`, create a `Chttp2SliceAllocatorFactory` and pass it to `grpc_tcp_server_start()`.
- In `Chttp2ServerListener::OnAccept()`, take ownership of the `SliceAllocator`, which can be stored in `Chttp2ServerListener::ActiveConnection::HandshakingState`.  When handshaking is complete, ownership of the `SliceAllocator` can be passed to the resulting transport instance.  (You can down-cast the `SliceAllocator` to `Chttp2SliceAllocator` to access the underlying resource_user.)

Note that this is exactly what we're going to need to do to use `SliceAllocator` and `SliceAllocatorFactory` when we move to EventEngine.  So if it turns out that there's some problem with this, we need to solve it anyway.
</blockquote></details>

`HandshakingState` could work to store the SliceAllocator/RU, I'll code it up and see. I had avoided it because it's not really clear to me where the lines should be drawn between the `HandshakingState` and `HandshakerArgs`. Comparatively, the HandshakingState properties appear to be more aligned with RQ concepts than RU - it stores listener pollsets, the acceptor, etc..

Like the RUs, it seems we may need the SliceAllocators to be ref-counted here, giving shared ownership between endpoints and transports. Otherwise, we'd have to confirm that endpoints cannot outlive their transports, yes? I'd lean towards having the SliceAllocatorFactory return a raw pointer, and the caller wrap it `auto sa = std::shared_ptr<SliceAllocator>(saf->CreateSliceAllocator(name));`. WDYT?


<!-- Sent from Reviewable.io -->

2021-07-19 19:23 UTC, ctiller commented
What about just creating a new slice allocator for each of the transport
and the endpoint? (I suspect RU's should be structured similarly)

On Mon, Jul 19, 2021 at 12:21 PM AJ Heller ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> *Reviewable <https://reviewable.io/reviews/grpc/grpc/26643>* status: 37
> of 95 files reviewed, 15 unresolved discussions (waiting on @drfloob
> <https://github.com/drfloob> and @markdroth <https://github.com/markdroth>
> )
>
> ------------------------------
>
> *src/core/lib/channel/handshaker.h, line 56 at r1
> <https://reviewable.io/reviews/grpc/grpc/26643#-MeS4IXe2hEf1E4Ili1w:-Mf-55cg22LoVP1S9IsW:b-ox6a5x>
> (raw file
> <https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.h#L56>):*
> *Previously, markdroth (Mark D. Roth) wrote…*
>
> On the server side, the general approach should be:
>
>    - Change the grpc_event_engine::experimental::SliceAllocator and
>    grpc_event_engine::experimental::SliceAllocatorFactory APIs to be
>    interfaces (i.e., the SliceAllocator::Allocat() and
>    SliceAllocatorFactory::CreateSliceAllocator() methods should be pure
>    virtual).
>    - Add a parameter to grpc_tcp_server_start() to allow passing in a
>    SliceAllocatorFactory instance to use. Also add a parameter to the
>    OnAccept() callback type for the resulting SliceAllocator. The idea
>    here is that when a connection comes in, the grpc_tcp_server will use
>    the SliceAllocatorFactory to create a new SliceAllocator. It will then
>    pass a pointer to that SliceAllocator to the endpoint it is creating
>    for the connection, and it will pass the SliceAllocator to OnAccept(),
>    which will take ownership of it.
>    - Have the chttp2 code provide implementations of SliceAllocator and
>    SliceAllocatorFactory called Chttp2SliceAllocator and
>    Chttp2SliceAllocatorFactory. The implementation of Chttp2SliceAllocator
>    will take a resource_user as a parameter, which it will take ownership of,
>    and will have a method for getting the underlying resource_user. The
>    implementation of Chttp2SliceAllocatorFactory will create a new
>    resource_user, then create a new Chttp2SliceAllocator and pass the
>    resource_user to it.
>    - In Chttp2ServerListener::StartListening(), create a
>    Chttp2SliceAllocatorFactory and pass it to grpc_tcp_server_start().
>    - In Chttp2ServerListener::OnAccept(), take ownership of the
>    SliceAllocator, which can be stored in
>    Chttp2ServerListener::ActiveConnection::HandshakingState. When
>    handshaking is complete, ownership of the SliceAllocator can be passed
>    to the resulting transport instance. (You can down-cast the
>    SliceAllocator to Chttp2SliceAllocator to access the underlying
>    resource_user.)
>
> Note that this is exactly what we're going to need to do to use
> SliceAllocator and SliceAllocatorFactory when we move to EventEngine. So
> if it turns out that there's some problem with this, we need to solve it
> anyway.
>
> HandshakingState could work to store the SliceAllocator/RU, I'll code it
> up and see. I had avoided it because it's not really clear to me where the
> lines should be drawn between the HandshakingState and HandshakerArgs.
> Comparatively, the HandshakingState properties appear to be more aligned
> with RQ concepts than RU - it stores listener pollsets, the acceptor, etc..
>
> Like the RUs, it seems we may need the SliceAllocators to be ref-counted
> here, giving shared ownership between endpoints and transports. Otherwise,
> we'd have to confirm that endpoints cannot outlive their transports, yes?
> I'd lean towards having the SliceAllocatorFactory return a raw pointer, and
> the caller wrap it auto sa =
> std::shared_ptr<SliceAllocator>(saf->CreateSliceAllocator(name));. WDYT?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/grpc/grpc/pull/26643#pullrequestreview-709897673>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNG45PSIAAJUV3FDDVBDZDTYR3LHANCNFSM5ACERCUA>
> .
>

2021-07-19 20:18 UTC, drfloob commented
> What about just creating a new slice allocator for each of the transport and the endpoint? (I suspect RU's should be structured similarly)

Actually, that might work! Looking at the code again, I now don't see why transports and endpoints _must_ share the same resource user, I may have been wrong about that earlier. If we went with your suggestion, only the transport's RUs would post reclaimers, the endpoints' RUs would have none, but I think that's OK. The transports' reclaimers send goaways or cancel streams, which would have the side effect of making the endpoints' ref-counted slices release their RU allocations when the endpoints are destroyed. As long as both RUs share the same quota, I think it should work out.

2021-07-19 21:39 UTC, markdroth requested changes
I'd also be fine with the endpoint and transport using different RUs, if that makes the code easier without breaking anything.  That might well eliminate the need for a lot of the plumbing here.

Please let me know if you have any questions.  Thanks!

> Reviewed 58 of 58 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-Mf-hBRm9gmQ1o4s0ODw:bjlfdww)* status: all files reviewed, 9 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 775 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRZBNI5lbxQ2adqV4Z:-Mf-Gzpp46_AyBrpVZBV:bd2lsgz) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L775)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

>  it looks like the code here wants to fail the allocation if the memory isn't available immediately, rather that running reclaimers and allocating asynchronously.

Yes, that's my understanding as well. Sorry for the confusion - when we have SliceAllocators in use, I was imagining that all RU accounting would go through the SliceAllocator's Slice allocation method. But I see we could still use the RU directly in cases like this, where we want to account for memory that the SliceAllocator isn't going to work with.
</blockquote></details>

Right.  In essence, a `SliceAllocator` is basically just an abstraction that wraps around the RU and hides its API from the EE impl.  Using the same RU both directly and via a `SliceAllocator` is fine.
___
*[src/core/lib/channel/handshaker.h, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS4IXe2hEf1E4Ili1w:-Mf-HLnhAA9mH-fm6bWZ:blzfvts) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.h#L56)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

`HandshakingState` could work to store the SliceAllocator/RU, I'll code it up and see. I had avoided it because it's not really clear to me where the lines should be drawn between the `HandshakingState` and `HandshakerArgs`. Comparatively, the HandshakingState properties appear to be more aligned with RQ concepts than RU - it stores listener pollsets, the acceptor, etc..

Like the RUs, it seems we may need the SliceAllocators to be ref-counted here, giving shared ownership between endpoints and transports. Otherwise, we'd have to confirm that endpoints cannot outlive their transports, yes? I'd lean towards having the SliceAllocatorFactory return a raw pointer, and the caller wrap it `auto sa = std::shared_ptr<SliceAllocator>(saf->CreateSliceAllocator(name));`. WDYT?
</blockquote></details>

The intent of `HandshakingState` is basically to hold state that is needed while handshaking is occuring for an individual connection -- i.e., between the time that we accept the TCP connection and the time that we create the transport and pass ownership of the endpoint to the transport.  I'm not sure why you say that it's more aligned with RQ concepts than RU; there was no such intention to that structure.  The intent was only that that's memory that can be freed once handshaking is complete.  (In xDS-enabled servers, `ActiveConnection` will stick around for the duration of the connection, so we want to keep it as small as possible to avoid wasting memory.)

The intent of `HandshakerArgs` is to be only state that needs to be visible to the handshakers.  The RU doesn't (at least for now), so it doesn't need to be there.

I don't think we need `SliceAllocators` to be ref-counted.  It's already the case that endpoints don't outlive their transports; the transport takes ownership of the endpoint and destroys it when it (the transport) is destroyed.

Note that if we *were* going to make the `SliceAllocator` ref-counted, I don't think it would make sense for `SliceAllocatorFactory` to return a raw pointer and then have the caller wrap it in a `shared_ptr<>`.  The whole point of smart pointers is to allow the compiler to enforce ownership semantics when passing ownership, so if you intend to use a smart pointer, you should always use it from the moment you create the object, or else you lose that advantage.  There are cases where we have to revert to using raw pointers for performance or syntax reasons -- e.g., it comes up a lot when pre-binding parameters in lambdas or `std::function<>`, especially with things like `unique_ptr<>` -- but unless you hit one of those cases, there's basically no reason to ever use raw pointers when passing ownership.
___
*[src/core/lib/event_engine/slice_allocator.cc, line 35 at r4](https://reviewable.io/reviews/grpc/grpc/26643#-Mf-PKguAQImRLixwExn:-Mf-PKguAQImRLixwExo:bb26wcv) ([raw file](https://github.com/grpc/grpc/blob/5b0345f553eb7d58573ea9e54dbb5972f60aa806/src/core/lib/event_engine/slice_allocator.cc#L35)):*
> ```cpp
>   if (resource_user_ != nullptr) {
>     grpc_resource_user_unref(resource_user_);
>     resource_user_ = nullptr;
> ```

This isn't necessary; the object will be destroyed immediately after this anyway.
___
*[src/core/lib/http/httpcli.cc, line 217 at r4](https://reviewable.io/reviews/grpc/grpc/26643#-Mf-PhO77nHwCu_ga5UT:-Mf-PhO77nHwCu_ga5UU:bnn2kmq) ([raw file](https://github.com/grpc/grpc/blob/5b0345f553eb7d58573ea9e54dbb5972f60aa806/src/core/lib/http/httpcli.cc#L217)):*
> ```cpp
>   grpc_resource_user_ref(req->resource_user);
>   grpc_tcp_client_connect(&req->connected, &req->ep, req->resource_user,
>                           req->context->pollset_set, {}, addr, req->deadline);
> ```

I think this should pass in `nullptr` for args.


<!-- Sent from Reviewable.io -->

2021-07-21 02:05 UTC, ctiller reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 81 of 115 files reviewed, 9 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 474 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeR_rtqEKX_azzf_XRD:-Mf5lPGfDJJzb7b8rMzn:b-jvrjsg) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L474)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think most callers actually do need another ref for this.  I think the fact that the code is currently written that way is a symptom of the fact that you're not having the handshakers take ownership of a ref, as per my comments elsewhere.

I think that having this take ownership is actually intuitive if you think about the fact that when we eventually convert the resource quota code to C++, we'll wind up passing this in as a `RefCountedPtr<ResourceUser>`.  That will have the function take ownership of a ref, and the compiler will be able to enforce that fact.
</blockquote></details>

I'm actually hoping for `InternallyRefCounted<ResourceUser>` depending on how this works out (I'd also like to write `class ResourceUser final : public SliceAllocator`, and `class ResourceQuota : public SliceAllocatorFactory` since these slice types are simply restricted interfaces atop the more general types.
___
*[src/core/lib/iomgr/tcp_posix.cc, line 590 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRGAIJ3zPAHjswA-QD:-Mf5lo1ODoVwZg7MeNP-:b-glhkvl) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/iomgr/tcp_posix.cc#L590)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I didn't realize that we had this code until just now, when I went to check where the endpoint impls are actually using the resource_user, but I think we'll need to figure out how to handle this.  This is a case where the endpoint implementation is not just allocating a slice from the resource user, but rather it's actually looking at the resource quota size and pressure to figure out how big of a buffer to allocate on the resource user.  We're going to need to figure out how to handle this.

A couple of possible options:
1. We decide that this is an optimization that isn't actually necessary and we just remove it.  @ctiller can probably advise as to how important this is.
2. We add a `GetTargetReadSize()` method to the slice allocator API, so that endpoint implementations can do this without accessing the underlying resource user or resource quota.
</blockquote></details>

Option 3 (and I think preferred): we add some kind of notion of intent to Allocate()... versions of this that might work:

`void Allocate(size_t size, Intent intent, AllocateCallback cb);`

`void AllocateForRead(size_t size_hint, AllocateCallback cb);`

The idea being that we move the formula inside of slice allocator, but use the intent of the call as a signal that the size need not be precise.

This optimization (and similar to it) are likely to become increasingly important: we want to be able to scale up our memory usage to improve performance when it is abundant, but scale it back in exchange for CPU when it is not - this avoids dropping more connections than is necessary whilst allowing forward progress to continue.


<!-- Sent from Reviewable.io -->

2021-07-21 16:43 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 81 of 115 files reviewed, 9 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 474 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeR_rtqEKX_azzf_XRD:-Mf8wBhOAsOqtIuBQOP9:b-dhznv1) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L474)):*
> I'm actually hoping for InternallyRefCounted<ResourceUser> depending on how this works out 

Don't we still need callers to own refs to `ResourceUser`?  If so, I don't think `InternallyRefCounted<>` would work.  But maybe you have some idea in mind of how to avoid the callers owning refs?

> (I'd also like to write class ResourceUser final : public SliceAllocator, and class ResourceQuota : public SliceAllocatorFactory since these slice types are simply restricted interfaces atop the more general types.

Conceptually, that seems fine, but we should be careful going down a path that requires multiple inheritence.  If `ResourceUser` needs to inherit from `RefCounted<>` or `InternallyRefCounted<>`, then having it also inherit from `SliceAllocator` isn't ideal.
___
*[src/core/lib/iomgr/tcp_posix.cc, line 590 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRGAIJ3zPAHjswA-QD:-Mf8wlkmAIhRm80uBiQj:b-i735lv) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/iomgr/tcp_posix.cc#L590)):*
<details><summary><i>Previously, ctiller (Craig Tiller) wrote…</i></summary><blockquote>

Option 3 (and I think preferred): we add some kind of notion of intent to Allocate()... versions of this that might work:

`void Allocate(size_t size, Intent intent, AllocateCallback cb);`

`void AllocateForRead(size_t size_hint, AllocateCallback cb);`

The idea being that we move the formula inside of slice allocator, but use the intent of the call as a signal that the size need not be precise.

This optimization (and similar to it) are likely to become increasingly important: we want to be able to scale up our memory usage to improve performance when it is abundant, but scale it back in exchange for CPU when it is not - this avoids dropping more connections than is necessary whilst allowing forward progress to continue.
</blockquote></details>

That approach SGTM.


<!-- Sent from Reviewable.io -->

2021-07-21 17:25 UTC, ctiller reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 81 of 115 files reviewed, 9 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[src/core/lib/iomgr/tcp_posix.cc, line 590 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRGAIJ3zPAHjswA-QD:-Mf94wK58-jifb8ysLUR:b-c632pk) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/iomgr/tcp_posix.cc#L590)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That approach SGTM.
</blockquote></details>

Let's go with adding to SliceAllocator: 
```
enum class Intent { 
  kDefault, // Default intent allocates exactly the memory required
  kReadBuffer // ReadBuffer intent may return a smaller slice than requested if memory pressure is high
};
```


<!-- Sent from Reviewable.io -->

2021-07-26 23:40 UTC, drfloob reviewed
After many days of rewriting and debugging, the linux tests are passing without any memory leaks.

Challenges still: possible leaks in the Windows iomgr impl, python tests are not passing (possibly leaks in the custom iomgr impl), and I haven't looked at the slice_allocator pressure solution yet.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-Mf_Am5ICV4NfqQ5_QWT:b-mryob3)* status: 9 of 131 files reviewed, 9 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 474 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeR_rtqEKX_azzf_XRD:-Mf_3DjeARxB15N6jXF3:bh1wg2i) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L474)):*
> It would probably make sense to have the ctor take ownership of a ref passed by the caller, since most callers are just unreffing after they pass this in anyway.  This would avoid a needless ref and unref.

This is done throughout, objects that need resource_users generally take ownership of a ref from the caller. The rest of the design discussion is happening elsewhere.
___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 775 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRZBNI5lbxQ2adqV4Z:-Mf_3dLF5YMZfYI30ipO:b-vmrj41) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L775)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Right.  In essence, a `SliceAllocator` is basically just an abstraction that wraps around the RU and hides its API from the EE impl.  Using the same RU both directly and via a `SliceAllocator` is fine.
</blockquote></details>

SGTM, thanks.
___
*[src/core/lib/channel/handshaker.h, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS4IXe2hEf1E4Ili1w:-Mf_3uijEP5C8mhUzMdL:b-ob5mdr) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/channel/handshaker.h#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The intent of `HandshakingState` is basically to hold state that is needed while handshaking is occuring for an individual connection -- i.e., between the time that we accept the TCP connection and the time that we create the transport and pass ownership of the endpoint to the transport.  I'm not sure why you say that it's more aligned with RQ concepts than RU; there was no such intention to that structure.  The intent was only that that's memory that can be freed once handshaking is complete.  (In xDS-enabled servers, `ActiveConnection` will stick around for the duration of the connection, so we want to keep it as small as possible to avoid wasting memory.)

The intent of `HandshakerArgs` is to be only state that needs to be visible to the handshakers.  The RU doesn't (at least for now), so it doesn't need to be there.

I don't think we need `SliceAllocators` to be ref-counted.  It's already the case that endpoints don't outlive their transports; the transport takes ownership of the endpoint and destroys it when it (the transport) is destroyed.

Note that if we *were* going to make the `SliceAllocator` ref-counted, I don't think it would make sense for `SliceAllocatorFactory` to return a raw pointer and then have the caller wrap it in a `shared_ptr<>`.  The whole point of smart pointers is to allow the compiler to enforce ownership semantics when passing ownership, so if you intend to use a smart pointer, you should always use it from the moment you create the object, or else you lose that advantage.  There are cases where we have to revert to using raw pointers for performance or syntax reasons -- e.g., it comes up a lot when pre-binding parameters in lambdas or `std::function<>`, especially with things like `unique_ptr<>` -- but unless you hit one of those cases, there's basically no reason to ever use raw pointers when passing ownership.
</blockquote></details>

Thanks for the explanation. HandshakingState now holds a reffed resource_user, and the HandshakerArgs / handshakers don't associate with resource_users.
___
*[src/core/lib/http/httpcli.cc, line 217 at r4](https://reviewable.io/reviews/grpc/grpc/26643#-Mf-PhO77nHwCu_ga5UT:-Mf_4QxU8KoAwwAZidu7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5b0345f553eb7d58573ea9e54dbb5972f60aa806/src/core/lib/http/httpcli.cc#L217)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this should pass in `nullptr` for args.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/endpoint_pair.h, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeS1Kf05mWFBBjhIw_T:-Mf_4VcMAn3hNOqXiT_1:b871xyz) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/iomgr/endpoint_pair.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned elsewhere, I think the endpoints themselves should also take ownership of the ref from the caller.  If you make both of those changes, then the code here doesn't need to change at all; you just need to document the semantics (which you should do anyway, regardless of what those semantics are).
</blockquote></details>

Done. For simplicity's sake, I've passed on some good opportunities to introduce unique_ptr in this PR. Now that I've gotten things roughly working, that might be a nice cleanup (probably for later).
___
*[src/core/lib/iomgr/tcp_client.h, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeREknh25PU-q3PJp6c:-Mf_5-HW6F295OCURpzz:b-brhp81) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/iomgr/tcp_client.h#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think doing this in two steps is going to require more work in the long run.  This is basically going to require changing every piece of code that creates an endpoint twice instead of once (including associated import work), and it's going to make the transition to EventEngine harder in the long run.

I really don't think it will be that hard to change this to use a slice allocator, so I don't see any real benefit in putting it off.  But I'll leave it up to you.
</blockquote></details>

Done. I've created a slice_allocator_factory and integrated it, along with slice_allocator, into these endpoint/transport/server/connector APIs.
___
*[src/core/lib/iomgr/tcp_server.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRDS_15CVdUor0EHLn:-Mf_5FNL1Esv52aqNNay:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/iomgr/tcp_server.h#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Good point.  I think the right way to address this is to use a slice allocator factory, analogous to the way I suggested using a slice allocator on the client side -- and for exactly the same reason.  This will move us to exactly the same semantics that we'll want when we move to EventEngine, so it will save us work down the road.

As I said on the client side, I really don't think it will be that hard to change this to use a slice allocator factory, so I don't see any real benefit in putting this off. But I'll leave it up to you.
</blockquote></details>

Done
___
*[src/core/ext/transport/chttp2/transport/internal.h, line 299 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRJA9k-J7Facl5SVVw:-Mf_5HbBEsv-R5YObvpF:b2yxsst) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/ext/transport/chttp2/transport/internal.h#L299)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

O [...]

2021-07-28 20:48 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 8 of 131 files reviewed, 10 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/surface/channel.cc, line 227 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-Mfir8AS7JPbT24tPxBL:-Mfir8AS7JPbT24tPxBM:b-brmazu) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/lib/surface/channel.cc#L227)):*
> ```cpp
>                                   grpc_channel_stack_type channel_stack_type,
>                                   grpc_transport* optional_transport,
>                                   grpc_resource_user* resource_user,
> ```

@markdroth  I'm trying to decide how to change a channel's relationship to its resource user. Currently, if an RU is passed to a channel, it is assumed that 51K has been allocated to that RU. This is true for the chttp2 server, but not anywhere else. Previously, most places that created channels would pass in a null resource_user to avoid the situation. If we want to plumb RUs into the channel as a hard requirement, I have a few thoughts.

We could break the 51K assumption and move the 51K RU deallocation to somewhere other than the channel destructor. Or, we could add an argument to grpc_channel_create to specify how many bytes the channel is responsible for freeing on destruction.

Thoughts?


<!-- Sent from Reviewable.io -->

2021-07-29 00:22 UTC, markdroth requested changes
This looks really excellent!   I haven't had a chance to review the tests on this pass, but the rest looks really good.

Please let me know if you have any questions.  Thanks!

> Reviewed 29 of 108 files at r7, 16 of 27 files at r8, 11 of 14 files at r9.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-Mfjcoij6g41KL_Gurko:b-bkjphx)* status: 64 of 131 files reviewed, 22 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.h, line 27 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjJ26V-D5gpT9bWgpV:-MfjJ26W8RUwEm5B1Eod:b-8lkmhz) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/chttp2_connector.h#L27)):*
> ```objc
> #include "src/core/lib/channel/handshaker.h"
> #include "src/core/lib/channel/handshaker_registry.h"
> #include "src/core/lib/iomgr/resource_quota.h"
> ```

Doesn't look like this is needed anymore.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 178 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjRQIS0Xo6R25qH4pD:-MfjRQIS0Xo6R25qH4pE:bnp6vl1) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L178)):*
> ```cpp
>     } else if (args->endpoint != nullptr) {
>       grpc_resource_quota* resource_quota =
>           grpc_resource_quota_from_channel_args(args->args, true);
> ```

If there is no RQ in channel args, then this means that we'll use two different RQs here, one for the endpoint and one for the transport.  (There will be two different RUs anyway, but in principle, they should come from the same RQ.)

How about having `Connect()` store the RQ as a data member, so that we're using the same instance in both places?
___
*[src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc, line 53 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjSzRs1HBml8A3ZrFy:-MfjSzRs1HBml8A3ZrFz:b-o5wq5x) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc#L53)):*
> ```cpp
>   GPR_ASSERT(fcntl(fd, F_SETFL, flags | O_NONBLOCK) == 0);
>   grpc_slice_allocator_factory* alloc_factory =
>       grpc_slice_allocator_factory_create(
> ```

There's not actually any need for the slice allocator factory in this case; you can just directly create the slice allocator from the RQ.
___
*[src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc, line 60 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjT6EEDTMy9IErV0gg:-MfjT6EEDTMy9IErV0gh:b-1mkvkf) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc#L60)):*
> ```cpp
>   grpc_endpoint* client = grpc_tcp_client_create_from_fd(
>       grpc_fd_create(fd, "client", true), args, "fd-client", allocator);
>   grpc_resource_user_ref(allocator->resource_user);
> ```

For consistency with the create-channel case that does *not* take an fd, maybe we should create two different RUs here instead of passing the same one to both the endpoint and the transport?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 450 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjZ6Tu2u-C3qqR-V2Y:-MfjZ6Tu2u-C3qqR-V2Z:b-ipoqzl) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L450)):*
> ```cpp
>             // will not be invoked when a config fetcher is set.
>             cleanup_connection = true;
>             free_resource_quota = true;
> ```

It looks like there's no longer any case where we're setting `cleanup_connection` but not setting `free_resource_quota`.  That being the case, the latter is probably no longer needed.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 712 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjXHJdBnqHCp2IUeFo:-MfjXHJdBnqHCp2IUeFp:be8itry) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L712)):*
> ```cpp
> 
> void Chttp2ServerListener::OnAccept(void* arg, grpc_endpoint* tcp,
>                                     grpc_slice_allocator* slice_allocator,
> ```

On the client side, it looks like you've changed the code to use separate RUs for the endpoint and the transport, rather than having them share a single RU.  But here on the server side, you've done a bunch of plumbing to ensure that we can use the same RU for both.  I don't think it matters that much which approach we go with, but I think we should be consistent and use the same approach on both the client and server sides.

If you want to change the client side to use the same RU for both endpoint and transport, then you'll need to change `Chttp2Connector` to store the RU between when it creates the slice allocator for the endpoint and when it creates the transport.

Or, if you want to change the server side to use a separate RU for each of the endpoint and the transport, then there's no longer any need for the TCP server to pass the slice allocator to the `OnAccept()` callback or to store it as a data member of `HandshakingState`.  Instead, you can just grab the RQ from channel args and make a new RU from there when you create the transport.
___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 49 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjZy7Y9dtbUfp_B1dI:-MfjZy7Y9dtbUfp_B1dJ:bo48egp) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L49)):*
> ```cpp
>   std::string name = absl::StrCat("fd:", fd);
>   grpc_slice_allocator_factory* alloc_factory =
>       grpc_slice_allocator_factory_create(
> ```

There's no need for a slice allocator factory here.  Instead, we can create the slice allocator directly from the RQ.
___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 57 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-Mfj_3hbAODix3d50OoZ:-Mfj_3hbAODix3d50Oo_:b8edoua) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L57)):*
> ```cpp
>       grpc_tcp_create(grpc_fd_create(fd, name.c_str(), true), server_args,
>                       name.c_str(), allocator);
>   grpc_resource_user_ref(allocator->resource_user);
> ```

See comments elsewhere about being consistent about whether we use the same RU for both the endpoint and the transport.
___
*[src/core/ext/transport/inproc/inproc_transport.cc, line 1293 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-Mfj_Hg5BYxEC0q7qIc8:-Mfj_Hg5BYxEC0q7qIc9:bd5avi7) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/inproc/inproc_transport.cc#L1293)):*
> ```cpp
>       server->core_server->channel_args(), args_to_remove,
>       GPR_ARRAY_SIZE(args_to_remove));
>   // DO NOT SUBMIT(hork)
> ```

I suspect that the inproc transport doesn't need to anything with RQs at all, since it doesn't actually have endpoints or allocate read buffers.
___
*[src/core/lib/channel/handshaker.h, line 36 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjIlMG-UbUdGr12WJ2:-MfjIlMHDdwjxF_xDTwS:b-w61v06) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/lib/channel/handshaker.h#L36)):*
> ```objc
> #include "src/core/lib/iomgr/endpoint.h"
> #include "src/core/lib/iomgr/exec_ctx.h"
> #include "src/core/lib/iomgr/resource_quota.h"
> ```

This include is not needed anymore.
___
*[src/core/lib/http/httpcli.cc, line 51 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjUSv06sPir3FNMcVx:-MfjUSv06s [...]

2021-07-29 01:13 UTC, ctiller commented
It's ok for the channel to have its own RU I think, that should be fine.

I expect we'll ultimately put some reclamation on channels too: a common
pattern in c++ is to have a std::vector<StuffThatNeedsDealingWith>... For
example calls pending on some constraint. I expect in those cases offering
a first pass very benign reclamation to resize the vector to it's current
size would let us reduce allocations under no pressure, whilst avoiding
over allocating when we see high memory pressure.

On Wed, Jul 28, 2021, 5:22 PM Mark D. Roth ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> This looks really excellent! I haven't had a chance to review the tests on
> this pass, but the rest looks really good.
>
> Please let me know if you have any questions. Thanks!
>
> Reviewed 29 of 108 files at r7, 16 of 27 files at r8, 11 of 14 files at r9.
> *Reviewable
> <https://reviewable.io/reviews/grpc/grpc/26643#-:-Mfjcoij6g41KL_Gurko:b-bkjphx>*
> status: 64 of 131 files reviewed, 22 unresolved discussions (waiting on
> @ctiller <https://github.com/ctiller>, @drfloob
> <https://github.com/drfloob>, and @markdroth
> <https://github.com/markdroth>)
>
> ------------------------------
>
> *src/core/ext/transport/chttp2/client/chttp2_connector.h, line 27 at r9
> <https://reviewable.io/reviews/grpc/grpc/26643#-MfjJ26V-D5gpT9bWgpV:-MfjJ26W8RUwEm5B1Eod:b-8lkmhz>
> (raw file
> <https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/chttp2_connector.h#L27>):*
>
> #include "src/core/lib/channel/handshaker.h"
>
> #include "src/core/lib/channel/handshaker_registry.h"
>
> #include "src/core/lib/iomgr/resource_quota.h"
>
> Doesn't look like this is needed anymore.
> ------------------------------
>
> *src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 178 at r9
> <https://reviewable.io/reviews/grpc/grpc/26643#-MfjRQIS0Xo6R25qH4pD:-MfjRQIS0Xo6R25qH4pE:bnp6vl1>
> (raw file
> <https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L178>):*
>
>     } else if (args->endpoint != nullptr) {
>
>       grpc_resource_quota* resource_quota =
>
>           grpc_resource_quota_from_channel_args(args->args, true);
>
> If there is no RQ in channel args, then this means that we'll use two
> different RQs here, one for the endpoint and one for the transport. (There
> will be two different RUs anyway, but in principle, they should come from
> the same RQ.)
>
> How about having Connect() store the RQ as a data member, so that we're
> using the same instance in both places?
> ------------------------------
>
> *src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc,
> line 53 at r9
> <https://reviewable.io/reviews/grpc/grpc/26643#-MfjSzRs1HBml8A3ZrFy:-MfjSzRs1HBml8A3ZrFz:b-o5wq5x>
> (raw file
> <https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc#L53>):*
>
>   GPR_ASSERT(fcntl(fd, F_SETFL, flags | O_NONBLOCK) == 0);
>
>   grpc_slice_allocator_factory* alloc_factory =
>
>       grpc_slice_allocator_factory_create(
>
> There's not actually any need for the slice allocator factory in this
> case; you can just directly create the slice allocator from the RQ.
> ------------------------------
>
> *src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc,
> line 60 at r9
> <https://reviewable.io/reviews/grpc/grpc/26643#-MfjT6EEDTMy9IErV0gg:-MfjT6EEDTMy9IErV0gh:b-1mkvkf>
> (raw file
> <https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc#L60>):*
>
>   grpc_endpoint* client = grpc_tcp_client_create_from_fd(
>
>       grpc_fd_create(fd, "client", true), args, "fd-client", allocator);
>
>   grpc_resource_user_ref(allocator->resource_user);
>
> For consistency with the create-channel case that does *not* take an fd,
> maybe we should create two different RUs here instead of passing the same
> one to both the endpoint and the transport?
> ------------------------------
>
> *src/core/ext/transport/chttp2/server/chttp2_server.cc, line 450 at r9
> <https://reviewable.io/reviews/grpc/grpc/26643#-MfjZ6Tu2u-C3qqR-V2Y:-MfjZ6Tu2u-C3qqR-V2Z:b-ipoqzl>
> (raw file
> <https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L450>):*
>
>             // will not be invoked when a config fetcher is set.
>
>             cleanup_connection = true;
>
>             free_resource_quota = true;
>
> It looks like there's no longer any case where we're setting
> cleanup_connection but not setting free_resource_quota. That being the
> case, the latter is probably no longer needed.
> ------------------------------
>
> *src/core/ext/transport/chttp2/server/chttp2_server.cc, line 712 at r9
> <https://reviewable.io/reviews/grpc/grpc/26643#-MfjXHJdBnqHCp2IUeFo:-MfjXHJdBnqHCp2IUeFp:be8itry>
> (raw file
> <https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L712>):*
>
> void Chttp2ServerListener::OnAccept(void* arg, grpc_endpoint* tcp,
>
>                                     grpc_slice_allocator* slice_allocator,
>
> On the client side, it looks like you've changed the code to use separate
> RUs for the endpoint and the transport, rather than having them share a
> single RU. But here on the server side, you've done a bunch of plumbing to
> ensure that we can use the same RU for both. I don't think it matters that
> much which approach we go with, but I think we should be consistent and use
> the same approach on both the client and server sides.
>
> If you want to change the client side to use the same RU for both endpoint
> and transport, then you'll need to change Chttp2Connector to store the RU
> between when it creates the slice allocator for the endpoint and when it
> creates the transport.
>
> Or, if you want to change the server side to use a separate RU for each of
> the endpoint and the transport, then there's no longer any need for the TCP
> server to pass the slice allocator to the OnAccept() callback or to store
> it as a data member of HandshakingState. Instead, you can just grab the
> RQ from channel args and make a new RU from there when you create the
> transport.
> ------------------------------
>
> *src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc,
> line 49 at r9
> <https://reviewable.io/reviews/grpc/grpc/26643#-MfjZy7Y9dtbUfp_B1dI:-MfjZy7Y9dtbUfp_B1dJ:bo48egp>
> (raw file
> <https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L49>):*
>
>   std::string name = absl::StrCat("fd:", fd);
>
>   grpc_slice_allocator_factory* alloc_factory =
>
>       grpc_slice_allocator_factory_create(
>
> There's no need for a slice allocator factory here. Instead, we can create
> the slice allocator directly from the RQ.
> ------------------------------
>
> *src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc,
> line 57 at r9
> <https://reviewable.io/reviews/grpc/grpc/26643#-Mfj_3hbAODix3d50OoZ:-Mfj_3hbAODix3d50Oo_:b8edoua>
> (raw file
> <https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L57>):*
>
>       grpc_tcp_create(grpc_fd_create(fd, name.c_str(), true), server_args,
>
>                       name.c_str(), allocator);
>
>   grpc_resource_user_ref(allocator->resource_user);
>
> See comments elsewhere about being consistent about whether we use the
> same RU for both the endpoint and the transport.
> ------------------------------
>
> *src/core/ext/transport/inproc/inproc_transport.cc, line 1293 at r9
> <https://reviewable.io/reviews/grpc/grpc/26643#-Mfj_Hg5BYxEC0q7qIc8:-Mfj_Hg5BYxEC0q7qIc9:bd5a [...]

2021-07-29 04:46 UTC, drfloob reviewed
Thanks for the review thorough Mark, and for your input Craig. I have a few remaining items to handle, but all of the linux ASAN tests are passing now, so that's a big milestone.

TODO:
* I want to evaluate everywhere a resource quota is created and minimize that. I think there should be very few.
* The memory pressure feature is currently unimplemented in the `slice_allocator_factory`
* The EventEngine iomgr is slightly broken due to the SliceAllocator vs slice_allocator APIs in EventEngine and iomgr.
* (and any remaining platform-specific bugs)

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-MfkZPe89tI46atX9EK_:b-capx7i)* status: 64 of 131 files reviewed, 22 unresolved discussions (waiting on @ctiller and @markdroth)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.h, line 27 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjJ26V-D5gpT9bWgpV:-MfjqheE902-3xrF9OFW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/chttp2_connector.h#L27)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this is needed anymore.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 178 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjRQIS0Xo6R25qH4pD:-Mfk6FuI-HaK0d1TcArT:b73fo8y) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L178)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If there is no RQ in channel args, then this means that we'll use two different RQs here, one for the endpoint and one for the transport.  (There will be two different RUs anyway, but in principle, they should come from the same RQ.)

How about having `Connect()` store the RQ as a data member, so that we're using the same instance in both places?
</blockquote></details>

Done. This'll result in RQ unrefs every time `Connect` is called on the same connector. We could alternatively store the RQ on `Chttp2Connector` construction, but do we want to support changing RQs on a connector instance?
___
*[src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc, line 53 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjSzRs1HBml8A3ZrFy:-Mfjykf62qIUs1OJNFW5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc#L53)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's not actually any need for the slice allocator factory in this case; you can just directly create the slice allocator from the RQ.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc, line 60 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjT6EEDTMy9IErV0gg:-Mfjzsp-48JPSVBX0Ssv:bd8rkfa) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

For consistency with the create-channel case that does *not* take an fd, maybe we should create two different RUs here instead of passing the same one to both the endpoint and the transport?
</blockquote></details>

Done. I've ensured all transports, channels, and endpoints have separate RUs. There are no longer any uses of `grpc_resource_user_ref` in the codebase at the moment!
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 450 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjZ6Tu2u-C3qqR-V2Y:-Mfk18gMANUhKgGp2ULl:bwq741j) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L450)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like there's no longer any case where we're setting `cleanup_connection` but not setting `free_resource_quota`.  That being the case, the latter is probably no longer needed.
</blockquote></details>

I've had to roll this line back, it was "coincidentally" working for most, but not all tests. I've changed the channel API a bit to handle deallocating any RU pre-allocation instead of trying to handle it here. Once the RU has reached the channel constructor, the channel will handle deallocating the RU appropriately.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 712 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjXHJdBnqHCp2IUeFo:-Mfk88dc7ZbT120VWK70:b-wgured) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L712)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

On the client side, it looks like you've changed the code to use separate RUs for the endpoint and the transport, rather than having them share a single RU.  But here on the server side, you've done a bunch of plumbing to ensure that we can use the same RU for both.  I don't think it matters that much which approach we go with, but I think we should be consistent and use the same approach on both the client and server sides.

If you want to change the client side to use the same RU for both endpoint and transport, then you'll need to change `Chttp2Connector` to store the RU between when it creates the slice allocator for the endpoint and when it creates the transport.

Or, if you want to change the server side to use a separate RU for each of the endpoint and the transport, then there's no longer any need for the TCP server to pass the slice allocator to the `OnAccept()` callback or to store it as a data member of `HandshakingState`.  Instead, you can just grab the RQ from channel args and make a new RU from there when you create the transport.
</blockquote></details>

I'd like to take the approach of having separate RUs for each endpoint, transport, and channel. `HandshakingState` will still need to carry the RU used for channel buffer pre-allocation since the channel is created later in `OnHandshakeDone`.

The design might change going forward, but thinking of the EventEngine API, the `AcceptCallback` currently takes an`Endpoint` and a `SliceAllocator`. I think we'll need some argument there that lets the callback utilize the resource quota system, but a `SliceAllocator` might be the wrong abstraction.
___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 49 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjZy7Y9dtbUfp_B1dI:-MfjrRPl8iMf-wZgZ_nP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L49)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need for a slice allocator factory here.  Instead, we can create the slice allocator directly from the RQ.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 57 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-Mfj_3hbAODix3d50OoZ:-MfkSEnr30ESlRpYRmad:b-srkyo2) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

See comments elsewhere about being consistent about whether we use the same RU for both the endpoint and the transport.
</blockquote></details>

New resource user created here.
___
*[src/core/ext/transport/inproc/inproc_transport.cc, line 1293 at r9](https://review [...]

2021-07-29 16:55 UTC, markdroth requested changes
This is definitely getting closer -- nice work!

Please let me know if you have any questions.  Thanks!

> Reviewed 49 of 108 files at r7, 5 of 27 files at r8, 1 of 14 files at r9, 36 of 36 files at r10.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-MfnB7RI-L9rakFtaFAB:bqo5p0)* status: all files reviewed, 27 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.h, line 27 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjJ26V-D5gpT9bWgpV:-MfmhmU73rrbWz2WHd5N:b-hvg24) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/chttp2_connector.h#L27)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This probably is needed again now that you've added an RQ data member. :)
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.h, line 71 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmhjapC-JpSyTbODZa:-MfmhjapC-JpSyTbODZb:bodylfw) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/client/chttp2_connector.h#L71)):*
> ```objc
>   absl::optional<grpc_error_handle> notify_error_;
>   RefCountedPtr<HandshakeManager> handshake_mgr_;
>   grpc_resource_quota* rq_;
> ```

Please call this `resource_quota_`, as per general naming rules about avoiding abbreviations:

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 178 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjRQIS0Xo6R25qH4pD:-MfmiDFf0vdMGyFm5ubL:b37whi5) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L178)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Done. This'll result in RQ unrefs every time `Connect` is called on the same connector. We could alternatively store the RQ on `Chttp2Connector` construction, but do we want to support changing RQs on a connector instance?
</blockquote></details>

I think it's fine to store it when `Connect()` is called, since that's where we get channel args.  I would expect that if there is an RQ in channel args, it will be the same one every time, but there's no need to bake that assumption in anywhere.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 44 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmhwN3DpPGCwuLYszD:-MfmhwN4DwHEarfBthIk:b-verfjx) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L44)):*
> ```cpp
> namespace grpc_core {
> 
> Chttp2Connector::Chttp2Connector() : rq_(nullptr) {
> ```

Suggest just initializing the data member to nullptr where it's declared.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 50 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmiVoM1LAW3NHN0Atl:-MfmiVoM1LAW3NHN0Atm:bs0fb82) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L50)):*
> ```cpp
> Chttp2Connector::~Chttp2Connector() {
>   if (rq_ != nullptr) {
>     grpc_resource_quota_unref_internal(rq_);
> ```

Instead of doing this here, I suggest doing it at the end of `OnHandshakeDone()`.  That way, we're not holding the ref any longer once the connection attempt is complete.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 450 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjZ6Tu2u-C3qqR-V2Y:-MfmyU_oBWNbBe3MrqUH:bbzifmv) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L450)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

I've had to roll this line back, it was "coincidentally" working for most, but not all tests. I've changed the channel API a bit to handle deallocating any RU pre-allocation instead of trying to handle it here. Once the RU has reached the channel constructor, the channel will handle deallocating the RU appropriately.
</blockquote></details>

Actually, I think it's probably still not necessary.  You're now resetting `channel_resource_user_` to null when you pass the RU to the channel, and that's basically the only case in which you *don't* want to free the allocation here.  So I think you can just free the allocation if `channel_resource_user_` is non-null.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 76 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmnJJd9jEf-yXt53BG:-Mfmj2EUA5ZE5Db0LFst:b8fzqqs) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/server/chttp2_server.cc#L76)):*
> ```cpp
>   Chttp2ServerListener(Server* server, grpc_channel_args* args,
>                        Chttp2ServerArgsModifier args_modifier,
>                        grpc_resource_quota* rq);
> ```

Please call this `resource_quota`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 241 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmjDKw0yU9CPme-gY5:-MfmjDKw0yU9CPme-gY6:b-mco6cp) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/server/chttp2_server.cc#L241)):*
> ```cpp
>   grpc_closure* on_destroy_done_ ABSL_GUARDED_BY(mu_) = nullptr;
>   RefCountedPtr<channelz::ListenSocketNode> channelz_listen_socket_;
>   grpc_resource_quota* rq_;
> ```

Please call this `resource_quota_`.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 767 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmuLiEDw63bta80Bjp:-MfmuLiEDw63bta80Bjq:b-an2jhf) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/server/chttp2_server.cc#L767)):*
> ```cpp
>     }
>   }
>   grpc_resource_user* channel_resource_user = grpc_resource_user_create(
> ```

(This comment is not a blocker for this PR; it's a broader comment about the design we're discussing for exposing the necessary RU functionality to the EE API.)

It seems like the reason for creating this RU here and plumbing it down into `HandshakingState` (as opposed to letting the channel create the RU internally) is that we want to know whether or not there's enough memory to allocate the channel before we even bother to start handshaking, which makes sense.  However, I notice that we're not doing the same thing for the size of the transport itself -- or, for that matter, for the size of the endpoint itself, although that would need to be checked in the TCP server code, since the endpoint is created there, before this function (`OnAccept()`) is called.

In principle, it seems like the optimal thing to do here is to have the TCP server code somehow allocate the full size it will need for the connection (including endpoint size, transport size, and channel size), and fail the connection attempt immediately if there isn't enough space.  If we check each thing separately, then we might wind up allocating the endpoint and the channel and then discovering that there isn't enough space for the transport, at which point the memory we allocated for the endpoint and channel was effectively wasted, right at a moment when the system is memory-constrained.

I will also note that one of the challenges here is that we need to know the right amount of space to allocate for each object before we actually do the allocation.  In the current code, we have a hack where we hard-code a fixed value for channel size, and this code and the channel code need to both use the same fixed value.  But in reality, the size of the channel will vary -- in particular, the set of channel [...]

2021-07-29 20:28 UTC, drfloob reviewed
I've responded to a handful of items, but I've got a bit of cleanup still to do. I'll let you know when this is again ready for review. Thanks Mark!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-MfnwatY3lAEpBz9O8dJ:bp815xs)* status: all files reviewed, 27 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.h, line 71 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmhjapC-JpSyTbODZa:-MfnhwF9BjD7dVddi1Ce:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/client/chttp2_connector.h#L71)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `resource_quota_`, as per general naming rules about avoiding abbreviations:

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 450 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjZ6Tu2u-C3qqR-V2Y:-MfnjC0h9qh6CpoUe4_K:bfbq99i) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L450)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Actually, I think it's probably still not necessary.  You're now resetting `channel_resource_user_` to null when you pass the RU to the channel, and that's basically the only case in which you *don't* want to free the allocation here.  So I think you can just free the allocation if `channel_resource_user_` is non-null.
</blockquote></details>

Good point, done.
___
*[src/core/ext/transport/inproc/inproc_transport.cc, line 1293 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-Mfj_Hg5BYxEC0q7qIc8:-Mfnjhaq8GQmhMJcrj5a:b-7v7rbl) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/inproc/inproc_transport.cc#L1293)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Sorry, I don't see the connection between the transport RU and the channel RU.  Even if the channel's RU was mandatory, why would that require changes in the transport?
</blockquote></details>

`SetupTransport` creates a channel, a dozen or so lines below this one. If channel resource users were non-optional, we'd either need to create and provide an RU to SetupTransport from here (for the channel), create an RU within SetupTransport from the channel args, or create an RU in the channel constructor itself. To support the preallocation of channel resources within a server's on_accept_cb (which you commented on elsewhere), the simplest way forward is to require an RU argument to SetupTransport. It isn't necessarily a connection between the transport's _RU_ and the channel's _RU_ - the connection is that this function creates both the transport and the channel, both of which would need RUs if we mandated that every channel must have one.
___
*[src/core/lib/channel/channel_stack_builder.h, line 67 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn2zTG9ECb7fq1UKtD:-MfnllH46o8DfkY_jGr4:bob3kk2) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/channel/channel_stack_builder.h#L67)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why does this value need to be plumbed into the channel stack builder?  It doesn't seem like the builder itself is actually using it for anything.
</blockquote></details>

See my arguments in another discussion, around channel.cc's `grpc_channel_create_with_builder`. The builder is also not doing anything with the resource_user.
___
*[src/core/lib/http/httpcli.cc, line 51 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn0mz11-zBPT2-2p_T:-MfnmE-yA3_e9va9u1N-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/http/httpcli.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `resource_quota`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resource_quota.cc, line 747 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn12wI3XwvDQnmkk22:-Mfnm_y89XskjZh9NAx-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/iomgr/resource_quota.cc#L747)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `auto*`, to make it clear that this is a pointer.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resource_quota.cc, line 747 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn15Eu8IGxwxlubHvu:-Mfnmr7z1FMfoXayF7zp:blrtx52) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/iomgr/resource_quota.cc#L747)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `resource_quota`.
</blockquote></details>

I know that's recommended by the style guide, but it's inconsistent with the vast majority of other resource_quota variable names in this file. How about I leave a TODO to rename them all in one pass? Along with `ru` -> `resource_user`.
___
*[src/core/lib/iomgr/tcp_custom.h, line 81 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn1gDIEEZaKANrhHY8:-MfnnaX_2h9iGknLZTP2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/iomgr/tcp_custom.h#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment needs to be updated.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/tcp_server.h, line 51 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn1vBm6v9-TwleaWxj:-Mfnng1V8-EV7hhkjM9Y:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/iomgr/tcp_server.h#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment is no longer needed.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/tcp_server_windows.cc, line 335 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjVoyq-vsSz2h6xACR:-Mfnnun_8tP6XeFh0p08:b70979u) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/lib/iomgr/tcp_server_windows.cc#L335)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The allocator is now used only within one block.  It is created and then immediately passed to the endpoint, and never used again.  So I think this can be declared where it is created.
</blockquote></details>

Uf, my mistake! Thanks.
___
*[src/core/lib/surface/channel.h, line 40 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn4fME6v-ulmrGTvMW:-Mfnorag8XrnUKrpisEg:btzjpwg) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/surface/channel.h#L40)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should go before the `error` parameter, since the latter is an output parameter, which belongs at the end of the list.

https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs
</blockquote></details>

Done. I'm tempted to remove the default values for resource_user and preallocated_bytes since many of the call sites rightfully want to pass an error output parameter anyway. Opinion?
___
*[src/core/lib/surface/channel.cc, line 273 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn3dTgBUdyVwn85fTd:-MfnpBGi7EAjshCmm_Bm:b-rukg00) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/surface/channel.cc#L273)):*
<details><summary><i>Previo [...]

2021-07-29 20:47 UTC, markdroth requested changes
> Reviewed 23 of 23 files at r11.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: all files reviewed, 19 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[examples/cpp/strip_prefix/BUILD, line 1 at r11](https://reviewable.io/reviews/grpc/grpc/26643#-Mfo09LUCsDGYRCWA31O:-Mfo09LV-xZOK-F3Vn6b:b76ailo) ([raw file](https://github.com/grpc/grpc/blob/875d94bdf5e4095bdc47d9a93feab38a100f8e64/examples/cpp/strip_prefix/BUILD#L1)):*
> ```Starlark
> load("//bazel:cc_grpc_library.bzl", "cc_grpc_library")
> ```

I assume this directory was added to the PR by mistake?
___
*[src/core/ext/transport/inproc/inproc_transport.cc, line 1293 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-Mfj_Hg5BYxEC0q7qIc8:-Mfnz0zf6uUtFKX-yLe0:b-f8gywn) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/inproc/inproc_transport.cc#L1293)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

`SetupTransport` creates a channel, a dozen or so lines below this one. If channel resource users were non-optional, we'd either need to create and provide an RU to SetupTransport from here (for the channel), create an RU within SetupTransport from the channel args, or create an RU in the channel constructor itself. To support the preallocation of channel resources within a server's on_accept_cb (which you commented on elsewhere), the simplest way forward is to require an RU argument to SetupTransport. It isn't necessarily a connection between the transport's _RU_ and the channel's _RU_ - the connection is that this function creates both the transport and the channel, both of which would need RUs if we mandated that every channel must have one.
</blockquote></details>

Ah, sorry -- I was looking at the filename and assuming that this was just the transport implementation, not the channel-creation function.  I forgot that the inproc transport basically combines the two.

I agree that if we wind up deciding that the RU should be passed into the channel unconditionally, that we'll need the code here.  Sorry for the confusion!
___
*[src/core/lib/iomgr/resource_quota.cc, line 747 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn15Eu8IGxwxlubHvu:-Mfny4qu0XfQE2-xqqP0:b-jcgm4y) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/iomgr/resource_quota.cc#L747)):*
Quoting the style guide (https://google.github.io/styleguide/cppguide.html#Goals):

> Consistency should not generally be used as a justification to do things in an old style without considering the benefits of the new style, or the tendency of the codebase to converge on newer styles over time.

I think we should not add new variable names that don't match the style guidance.  We don't need to go out of our way to fix the existing names in this PR, but let's not make the problem worse.
___
*[src/core/lib/iomgr/tcp_server_windows.cc, line 335 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjVoyq-vsSz2h6xACR:-Mfnzjl8-GkyNwug1Tpo:b5t7i3l) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/lib/iomgr/tcp_server_windows.cc#L335)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Uf, my mistake! Thanks.
</blockquote></details>

You didn't make a mistake -- I was previously misreading the code.  It just so happened that the other changes you made caused this comment to be relevant when it wasn't before.  Sorry for the confusion on my part.
___
*[src/core/lib/surface/channel.h, line 40 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn4fME6v-ulmrGTvMW:-MfnztrC16U45P-sgxe2:b6ocbjx) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/surface/channel.h#L40)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Done. I'm tempted to remove the default values for resource_user and preallocated_bytes since many of the call sites rightfully want to pass an error output parameter anyway. Opinion?
</blockquote></details>

Yeah, I'd be inclined to remove the default parameter values as well.
___
*[src/core/lib/surface/channel.cc, line 273 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn3dTgBUdyVwn85fTd:-Mfo-G6WCr28cEZpiEnI:bz4sp10) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/surface/channel.cc#L273)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Shouldn't it travel with the resource_user since the two are inherently together? The builder is not directly using the resource_user either, so I don't see how it makes anything messier. Would you prefer both RU and the preallocated bytes became arguments to `grpc_channel_create_with_builder`?
</blockquote></details>

If the builder doesn't use the RU either, then in principle, I would say that the RU doesn't belong in there either.  So yeah, let's make them both arguments to `grpc_channel_create_with_builder()`.


<!-- Sent from Reviewable.io -->

2021-07-29 21:07 UTC, ctiller reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: all files reviewed, 19 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 767 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmuLiEDw63bta80Bjp:-Mfo1V75507MHgw9_PT3:bgo990h) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/server/chttp2_server.cc#L767)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

(This comment is not a blocker for this PR; it's a broader comment about the design we're discussing for exposing the necessary RU functionality to the EE API.)

It seems like the reason for creating this RU here and plumbing it down into `HandshakingState` (as opposed to letting the channel create the RU internally) is that we want to know whether or not there's enough memory to allocate the channel before we even bother to start handshaking, which makes sense.  However, I notice that we're not doing the same thing for the size of the transport itself -- or, for that matter, for the size of the endpoint itself, although that would need to be checked in the TCP server code, since the endpoint is created there, before this function (`OnAccept()`) is called.

In principle, it seems like the optimal thing to do here is to have the TCP server code somehow allocate the full size it will need for the connection (including endpoint size, transport size, and channel size), and fail the connection attempt immediately if there isn't enough space.  If we check each thing separately, then we might wind up allocating the endpoint and the channel and then discovering that there isn't enough space for the transport, at which point the memory we allocated for the endpoint and channel was effectively wasted, right at a moment when the system is memory-constrained.

I will also note that one of the challenges here is that we need to know the right amount of space to allocate for each object before we actually do the allocation.  In the current code, we have a hack where we hard-code a fixed value for channel size, and this code and the channel code need to both use the same fixed value.  But in reality, the size of the channel will vary -- in particular, the set of channel args dictates the set of filters, which directly affects the size of the filter stack -- so the channel code really needs to provide this information somehow.  So we probably need the channel to provide a function that tells us the actual size of a channel that will be created based on a certain set of channel args or other params.  And a similar function for the transport as well.

We need to think through what this means for the EE API.  Maybe we actually need some API where the EE impl's Listener is given some RU-proxy object, on which there is a method like this:

```
absl::StatusOr<std::unique_ptr<EventEngine::Endpoint>> CreateEndpointForIncomingConnection(size_t endpoint_object_size);
```

This would allow the EE impl to tell us the size of its endpoint object, and it would give us a hook to also ask the RU for the space needed for the transport and channel at the same time, so we can immediately fail the connection if there isn't enough space for all three.

@ctiller, thoughts?
</blockquote></details>

We need to make some simplifications here... if we attempt to only create a channel when there is sufficient memory available, then we must outlaw the use of std::vector from the channel implementation (as it's memory allocations cannot be delayed, nor can they be failed).

I don't want to outlaw std::vector.

This is why I write three allocator functions every time I write ResourceTracker: they have different purposes, and we need them all.

async Allocate ought to be the default we turn to for large allocations that need not be immediate, especially where we can stomach the added complexity of adding an async step (promises will help here!)

immediate Allocate will be the default for much of the codebase. It always succeeds allocating, which means a potential for overcommit, which it recovers through reclamation passes.

try Allocate will be rarely used, and mostly for almost-optional steps in an rpc... we might choose to drop a hedged request if there's insufficient memory to expand the arena for example.

There's two architectures for channel creation possible with this scheme:
1. Create everything synchronously, and reserve async allocation for read buffers and the like
2. Create the channel asynchronously, and pause between endpoint, transport, channel creation if there's insufficient memory available at that moment

Both will work, 2 will be (slightly?) less biased towards new connections over old.


<!-- Sent from Reviewable.io -->

2021-07-29 22:40 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 100 of 142 files reviewed, 19 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 767 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmuLiEDw63bta80Bjp:-MfoOoKT9cnshP7iZSbW:bm3i9by) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/server/chttp2_server.cc#L767)):*
<details><summary><i>Previously, ctiller (Craig Tiller) wrote…</i></summary><blockquote>

We need to make some simplifications here... if we attempt to only create a channel when there is sufficient memory available, then we must outlaw the use of std::vector from the channel implementation (as it's memory allocations cannot be delayed, nor can they be failed).

I don't want to outlaw std::vector.

This is why I write three allocator functions every time I write ResourceTracker: they have different purposes, and we need them all.

async Allocate ought to be the default we turn to for large allocations that need not be immediate, especially where we can stomach the added complexity of adding an async step (promises will help here!)

immediate Allocate will be the default for much of the codebase. It always succeeds allocating, which means a potential for overcommit, which it recovers through reclamation passes.

try Allocate will be rarely used, and mostly for almost-optional steps in an rpc... we might choose to drop a hedged request if there's insufficient memory to expand the arena for example.

There's two architectures for channel creation possible with this scheme:
1. Create everything synchronously, and reserve async allocation for read buffers and the like
2. Create the channel asynchronously, and pause between endpoint, transport, channel creation if there's insufficient memory available at that moment

Both will work, 2 will be (slightly?) less biased towards new connections over old.
</blockquote></details>

Couldn't we also choose to compute the total amount we need to create the channel, check if that amount is available, and if not, fail the connection attempt so that we don't need to allocate anything?  It seems like that's the right thing to do under memory pressure -- don't accept more load if we're having trouble handling what we already have (i.e., bias strongly toward existing connections).

I agree that outlawing STL containers doesn't make sense.  However, I wonder how much of the per-channel memory is actually used in such data structures.  Can we maybe do an analysis that sees how much such overhead we actually have?  My off-the-cuff guess would be that the memory allocated in those containers is a small amount relative to the total size of the channel.  Most of the channel memory is probably in the `grpc_channel` struct itself and the channel data for all of the filters in the filter stack.  If there isn't that much overhead in STL containers, maybe we can just estimate it in some reasonable way?


<!-- Sent from Reviewable.io -->

2021-07-29 22:52 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 100 of 142 files reviewed, 19 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.h, line 27 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjJ26V-D5gpT9bWgpV:-MfoP5EW79gD_P7Fzma8:b-leh91x) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/ext/transport/chttp2/client/chttp2_connector.h#L27)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This probably is needed again now that you've added an RQ data member. :)
</blockquote></details>

Thanks, added back. Looks like it's transitively included, it builds just fine without. I might toy with IWYU on this codebase and see what happens.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 44 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmhwN3DpPGCwuLYszD:-MfoRAdHAAdoFZoM4Yxb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest just initializing the data member to nullptr where it's declared.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 50 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmiVoM1LAW3NHN0Atl:-MfoRyS2DPIGHYBDHFVy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of doing this here, I suggest doing it at the end of `OnHandshakeDone()`.  That way, we're not holding the ref any longer once the connection attempt is complete.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 76 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmnJJd9jEf-yXt53BG:-MfoSYv_2zsQk-BK6Gge:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/server/chttp2_server.cc#L76)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `resource_quota`.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 241 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmjDKw0yU9CPme-gY5:-MfoScht2HwgK06kJcZf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/server/chttp2_server.cc#L241)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `resource_quota_`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/endpoint_pair.h, line 33 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn5HIhBAaZVcNECk1v:-Mfo8xCc3qZwtWLCNknC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/iomgr/endpoint_pair.h#L33)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This argument probably isn't needed.  I think it should be sufficient to have `grpc_iomgr_create_endpoint_pair()` get the RQ from channel args internally.  I think doing it that way will avoid a lot of the test changes in this PR.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resource_quota.cc, line 747 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn15Eu8IGxwxlubHvu:-Mfo95Lq7M7LuWyU8ibO:b-9qek2d) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/iomgr/resource_quota.cc#L747)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Quoting the style guide (https://google.github.io/styleguide/cppguide.html#Goals):

> Consistency should not generally be used as a justification to do things in an old style without considering the benefits of the new style, or the tendency of the codebase to converge on newer styles over time.

I think we should not add new variable names that don't match the style guidance.  We don't need to go out of our way to fix the existing names in this PR, but let's not make the problem worse.
</blockquote></details>

You won this round, style guide! I've added the recommended names, and changed the rest in the file for good measure.
___
*[src/core/lib/surface/channel.h, line 40 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn4fME6v-ulmrGTvMW:-MfoC0DA3s0RZxbd3Y5s:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/surface/channel.h#L40)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yeah, I'd be inclined to remove the default parameter values as well.
</blockquote></details>

Done
___
*[src/core/lib/surface/channel.cc, line 273 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn3dTgBUdyVwn85fTd:-MfoEPNZ-EKHZpOA9qkB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/lib/surface/channel.cc#L273)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If the builder doesn't use the RU either, then in principle, I would say that the RU doesn't belong in there either.  So yeah, let's make them both arguments to `grpc_channel_create_with_builder()`.
</blockquote></details>

Done.
___
*[test/core/util/passthru_endpoint.cc, line 200 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn84QfASp4p4344AIO:-MfoEWvqDit-sBswb9mq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/test/core/util/passthru_endpoint.cc#L200)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this argument is necessary.  Instead, you can just call `grpc_slice_allocator_create_unlimited()` below.
</blockquote></details>

Done.
___
*[test/cpp/microbenchmarks/bm_chttp2_transport.cc, line 133 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn75c8A6_CmEYZ8L67:-MfoEpVV5kQHV3JTyvzX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/test/cpp/microbenchmarks/bm_chttp2_transport.cc#L133)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The slice allocator factory isn't necessary here; you can directly use the RQ to create the RU.

Actually, why not just directly use `grpc_resource_user_create_unlimited()` when creating the transport, as you were doing before?
</blockquote></details>

Done.
___
*[examples/cpp/strip_prefix/BUILD, line 1 at r11](https://reviewable.io/reviews/grpc/grpc/26643#-Mfo09LUCsDGYRCWA31O:-MfoOucCDkRSb3UOZeO1:b-kqq9o) ([raw file](https://github.com/grpc/grpc/blob/875d94bdf5e4095bdc47d9a93feab38a100f8e64/examples/cpp/strip_prefix/BUILD#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume this directory was added to the PR by mistake?
</blockquote></details>

Oops, thanks. I was working on another bug.


<!-- Sent from Reviewable.io -->

2021-07-29 23:35 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 100 of 142 files reviewed, 19 unresolved discussions (waiting on @ctiller and @markdroth)

___
*[test/core/util/resource_user_util.cc, line 36 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-Mfn63Q-5CC9p4gVtXzD:-MfoZxiRAJkp9ch9ASkJ:bw9t506) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/test/core/util/resource_user_util.cc#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The slice allocator factory is not necessary here.  Instead, I think you can just do something like this:

```
auto* resource_quota = grpc_resource_quota_create("anonymous mock quota");
auto* slice_allocator = grpc_slice_allocator_create(resource_quota, ...);
grpc_resource_quota_unref_internal(resource_quota);
return slice_allocator;
```

It's also worth considering whether it makes sense to change `grpc_slice_allocator_create()` to take an RU instead of an RQ as its parameter.  If you do that, then this whole function becomes just:

```
return grpc_slice_allocator_create(grpc_resource_user_create_unlimited(nullptr), ...);
```

I think it might make a few things easier.
</blockquote></details>

I've removed most uses of the factory that aren't directly server-related, including here. I left the `grpc_slice_allocator_create` signature as taking a resource_quota. By changing it to take a resource_user instead, we'd be removing one call to `grpc_resource_user_create` from inside this function, and creating resource users in a dozen or so places that call `grpc_slice_allocator_create`.


<!-- Sent from Reviewable.io -->

2021-07-30 00:00 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 100 of 142 files reviewed, 19 unresolved discussions (waiting on @ctiller and @markdroth)

___
*[src/core/lib/iomgr/tcp_posix.cc, line 590 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRGAIJ3zPAHjswA-QD:-MfofS3y4T32sU-daJR0:b-m06tmw) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/iomgr/tcp_posix.cc#L590)):*
<details><summary><i>Previously, ctiller (Craig Tiller) wrote…</i></summary><blockquote>

Let's go with adding to SliceAllocator: 
```
enum class Intent { 
  kDefault, // Default intent allocates exactly the memory required
  kReadBuffer // ReadBuffer intent may return a smaller slice than requested if memory pressure is high
};
```
</blockquote></details>

SGTM too. Given that min and max read chunk sizes are user-configurable via channel_args, do we need to support those values changing between calls to `allocate`? For this PR, I've started going ahead with the approach of setting min and max sizes as attributes of the slice_allocator itself, instead of passing them as parameters for each allocation.


<!-- Sent from Reviewable.io -->

2021-07-30 01:09 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 94 of 142 files reviewed, 19 unresolved discussions (waiting on @ctiller and @markdroth)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 50 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmiVoM1LAW3NHN0Atl:-Mfox6Bs6rfAasIP2yL_:b-yzu4yn) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L50)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually that results in memory leaks, since `Connect` may have never been called.


<!-- Sent from Reviewable.io -->

2021-07-30 01:12 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: 94 of 142 files reviewed, 19 unresolved discussions (waiting on @ctiller and @markdroth)

___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 50 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmiVoM1LAW3NHN0Atl:-MfoxhD_6cCqm_T9LyZx:b-abhcki) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L50)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Actually that results in memory leaks, since `Connect` may have never been called.
</blockquote></details>

Correction: the quota is leaked when Connect _is_ called, but the handshake is never started, if we try to unref the quota in `OnHandshakeDone`.


<!-- Sent from Reviewable.io -->

2021-07-31 01:18 UTC, drfloob commented
/easycla

2021-08-02 16:11 UTC, markdroth requested changes
This is looking really good!  I think it's pretty close to being ready.

Please let me know if you have any questions.  Thanks!

> Reviewed 34 of 42 files at r12, 6 of 11 files at r13, 19 of 19 files at r14.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-Mg6cbQwCE8ggSdr0ufC:b-pql5tn)* status: all files reviewed, 11 unresolved discussions (waiting on @ctiller and @drfloob)

___
*[src/core/lib/iomgr/resource_quota.cc, line 1028 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6X8Dl7OSlOTMfjQcK:-Mg6X8Dl7OSlOTMfjQcL:b-vc16z5) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/src/core/lib/iomgr/resource_quota.cc#L1028)):*
> ```cpp
> }
> 
> size_t grpc_slice_allocator_adjust_allocation_length(
> ```

This should be `static`.
___
*[src/core/lib/iomgr/tcp_posix.cc, line 590 at r1](https://reviewable.io/reviews/grpc/grpc/26643#-MeRGAIJ3zPAHjswA-QD:-Mg6Y5Ax0lRyAuxLWciu:b-4lerfe) ([raw file](https://github.com/grpc/grpc/blob/6eb44b8d048812bd51c8727d6aa3341c2d00b8fb/src/core/lib/iomgr/tcp_posix.cc#L590)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

SGTM too. Given that min and max read chunk sizes are user-configurable via channel_args, do we need to support those values changing between calls to `allocate`? For this PR, I've started going ahead with the approach of setting min and max sizes as attributes of the slice_allocator itself, instead of passing them as parameters for each allocation.
</blockquote></details>

That's probably fine for now, since we'll wind up making subsequent changes to the API here anyway.
___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 45 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjWMQAAoUNX2N9Eyec:-Mg6_L_RC3g_jrDjmGQI:b56wjvl) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/lib/iomgr/event_engine/endpoint.h#L45)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

I believe it should take an EventEngine `SliceAllocator`. The AcceptCallback API seems wrong even based on our current design, I think it should take a `std::unique_ptr<SliceAllocator>`, not a `const SliceAllocator&`. I think we should have the design discussion then figure this out, but in the meantime I'll see about not breaking it.
</blockquote></details>

It doesn't make sense to pass ownership of the `SliceAllocator` to the EE API's `AcceptCallback`, because at that point, the `SliceAllocator` will be owned by the endpoint, and it cannot have two owners.

Given that in this PR, we are now moving to a world where the endpoint and transport do not share RUs, there's not actually any reason to pass the `SliceAllocator` to the `AcceptCallback` at all -- the only reason we had been planning to do that was to allow `Chttp2ServerListener` to extract the RU from the `SliceAllocator` so that it could pass that same RU to the transport, but that's no longer necessary.

We also don't need the parameter for this function.  I think it can just be removed.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 50 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6Z-gUCDA3o7VUkvT0:-Mg6Z-gUCDA3o7VUkvT1:b-y2j9j5) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/src/core/lib/iomgr/event_engine/tcp.cc#L50)):*
> ```cpp
> 
>   absl::Status Allocate(size_t size, SliceBuffer* dest,
>                         SliceAllocator::AllocateCallback cb) {
> ```

I think this needs to be declared as `override`.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 65 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6aCeLEhrq29Pw3EY4:-Mg6aCeMEd6LWEm0oBaM:bjqo8pa) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/src/core/lib/iomgr/event_engine/tcp.cc#L65)):*
> ```cpp
> 
>  private:
>   grpc_slice_allocator* slice_allocator_;
> ```

I assume this is taking ownership.  If so, the dtor needs to destroy the slice allocator.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 81 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6aG_iDY3r6McACX6g:-Mg6aG_iDY3r6McACX6h:b-j5sk32) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/src/core/lib/iomgr/event_engine/tcp.cc#L81)):*
> ```cpp
> 
>  private:
>   grpc_slice_allocator_factory* slice_allocator_factory_;
> ```

Same issue here: The dtor needs to destroy the slice allocator factory.
___
*[test/cpp/microbenchmarks/fullstack_fixtures.h, line 261 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6bpUO73tG3gjvR69X:-Mg6bpUO73tG3gjvR69Y:b-w46vgm) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/test/cpp/microbenchmarks/fullstack_fixtures.h#L261)):*
> ```objc
>  private:
>   static grpc_endpoint_pair MakeEndpoints() {
>     return grpc_iomgr_create_endpoint_pair("test", nullptr);
> ```

This one call can probably be inlined instead of being in a separate static method.
___
*[test/cpp/microbenchmarks/fullstack_streaming_ping_pong.h, line 28 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6bwL5DTXZegZWfQEW:-Mg6bwL69w2rbWsQ9wIa:bpz5spd) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/test/cpp/microbenchmarks/fullstack_streaming_ping_pong.h#L28)):*
> ```objc
> #include "src/core/lib/profiling/timers.h"
> #include "src/proto/grpc/testing/echo.grpc.pb.h"
> #include "test/core/util/resource_user_util.h"
> ```

Doesn't look like this include is needed anymore.
___
*[test/cpp/microbenchmarks/fullstack_streaming_pump.h, line 28 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6bzmEDBP1XR_KV9Ut:-Mg6bzmEDBP1XR_KV9Uu:bpz5spd) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/test/cpp/microbenchmarks/fullstack_streaming_pump.h#L28)):*
> ```objc
> #include "src/core/lib/profiling/timers.h"
> #include "src/proto/grpc/testing/echo.grpc.pb.h"
> #include "test/core/util/resource_user_util.h"
> ```

Doesn't look like this include is needed anymore.
___
*[test/cpp/microbenchmarks/fullstack_unary_ping_pong.h, line 28 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6c1tKCZxLALAK-Rmq:-Mg6c1tKCZxLALAK-Rmr:bpz5spd) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/test/cpp/microbenchmarks/fullstack_unary_ping_pong.h#L28)):*
> ```objc
> #include "src/core/lib/profiling/timers.h"
> #include "src/proto/grpc/testing/echo.grpc.pb.h"
> #include "test/core/util/resource_user_util.h"
> ```

Doesn't look like this include is needed anymore.


<!-- Sent from Reviewable.io -->

2021-08-02 18:37 UTC, drfloob reviewed
Thanks Mark, I believe I've addressed all the comments. I'll do another pass over it, and do a quick inventory of where resource_quotas are being created.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-Mg78XOK2iEqXLQxlfRX:b-aol53j)* status: all files reviewed, 11 unresolved discussions (waiting on @ctiller and @markdroth)

___
*[src/core/lib/iomgr/resource_quota.cc, line 1028 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6X8Dl7OSlOTMfjQcK:-Mg6u__gEICPQnj8ctvZ:b-j2f7t6) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/src/core/lib/iomgr/resource_quota.cc#L1028)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be `static`.
</blockquote></details>

Good catch. thanks.
___
*[src/core/lib/iomgr/event_engine/endpoint.h, line 45 at r9](https://reviewable.io/reviews/grpc/grpc/26643#-MfjWMQAAoUNX2N9Eyec:-Mg77VW40WL-Yhy02wNN:b-2w1smy) ([raw file](https://github.com/grpc/grpc/blob/684399cb33eb29fe0efcad7e38f09ce55a5dc17b/src/core/lib/iomgr/event_engine/endpoint.h#L45)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It doesn't make sense to pass ownership of the `SliceAllocator` to the EE API's `AcceptCallback`, because at that point, the `SliceAllocator` will be owned by the endpoint, and it cannot have two owners.

Given that in this PR, we are now moving to a world where the endpoint and transport do not share RUs, there's not actually any reason to pass the `SliceAllocator` to the `AcceptCallback` at all -- the only reason we had been planning to do that was to allow `Chttp2ServerListener` to extract the RU from the `SliceAllocator` so that it could pass that same RU to the transport, but that's no longer necessary.

We also don't need the parameter for this function.  I think it can just be removed.
</blockquote></details>

You're absolutely right, it isn't needed now. I was able to clean up the EventEngine-iomgr endpoint struct a bit as well.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 50 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6Z-gUCDA3o7VUkvT0:-Mg6tZoLCRx0CL64Joo9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/src/core/lib/iomgr/event_engine/tcp.cc#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this needs to be declared as `override`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 65 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6aCeLEhrq29Pw3EY4:-Mg6ttXvDfSCaB6YI2An:b-29vizu) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/src/core/lib/iomgr/event_engine/tcp.cc#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume this is taking ownership.  If so, the dtor needs to destroy the slice allocator.
</blockquote></details>

Done, thanks. 
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 81 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6aG_iDY3r6McACX6g:-Mg6tutm0XmgFr1cWlMw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/src/core/lib/iomgr/event_engine/tcp.cc#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same issue here: The dtor needs to destroy the slice allocator factory.
</blockquote></details>

Done.
___
*[test/cpp/microbenchmarks/fullstack_fixtures.h, line 261 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6bpUO73tG3gjvR69X:-Mg6u8vW3H7EBGx3sMkn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/test/cpp/microbenchmarks/fullstack_fixtures.h#L261)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This one call can probably be inlined instead of being in a separate static method.
</blockquote></details>

Done.
___
*[test/cpp/microbenchmarks/fullstack_streaming_ping_pong.h, line 28 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6bwL5DTXZegZWfQEW:-Mg6uK9F0teQQIt64o0q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/test/cpp/microbenchmarks/fullstack_streaming_ping_pong.h#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this include is needed anymore.
</blockquote></details>

Done.
___
*[test/cpp/microbenchmarks/fullstack_streaming_pump.h, line 28 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6bzmEDBP1XR_KV9Ut:-Mg6uGMI87yamVT2kjSd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/test/cpp/microbenchmarks/fullstack_streaming_pump.h#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this include is needed anymore.
</blockquote></details>

Done.
___
*[test/cpp/microbenchmarks/fullstack_unary_ping_pong.h, line 28 at r14](https://reviewable.io/reviews/grpc/grpc/26643#-Mg6c1tKCZxLALAK-Rmq:-Mg6uQsvCA_dDAe361Rj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4a81eea28a0acf3877007732621204cbb6ca3200/test/cpp/microbenchmarks/fullstack_unary_ping_pong.h#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this include is needed anymore.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-02 18:53 UTC, markdroth requested changes
This looks fantastic!  Just a couple of very minor nits remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 9 of 9 files at r15.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-Mg7Ch8G1Cj9-XqOKNJu:btb4yl)* status: all files reviewed, 3 unresolved discussions (waiting on @ctiller and @drfloob)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 767 at r10](https://reviewable.io/reviews/grpc/grpc/26643#-MfmuLiEDw63bta80Bjp:-Mg7CTqr1KI8mOgb9lRf:b-4tq065) ([raw file](https://github.com/grpc/grpc/blob/39c90d45e3cfaba6244e022865a23a0fccaa7b06/src/core/ext/transport/chttp2/server/chttp2_server.cc#L767)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Couldn't we also choose to compute the total amount we need to create the channel, check if that amount is available, and if not, fail the connection attempt so that we don't need to allocate anything?  It seems like that's the right thing to do under memory pressure -- don't accept more load if we're having trouble handling what we already have (i.e., bias strongly toward existing connections).

I agree that outlawing STL containers doesn't make sense.  However, I wonder how much of the per-channel memory is actually used in such data structures.  Can we maybe do an analysis that sees how much such overhead we actually have?  My off-the-cuff guess would be that the memory allocated in those containers is a small amount relative to the total size of the channel.  Most of the channel memory is probably in the `grpc_channel` struct itself and the channel data for all of the filters in the filter stack.  If there isn't that much overhead in STL containers, maybe we can just estimate it in some reasonable way?
</blockquote></details>

I'm resolving this comment -- we can follow up on this separately, since it's not a blocker for this PR.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 64 at r15](https://reviewable.io/reviews/grpc/grpc/26643#-Mg7Bm8H-9DhYKrYNRKE:-Mg7Bm8I3BEnmoSA2JuB:babgxjo) ([raw file](https://github.com/grpc/grpc/blob/bcb9c8c28c54cfc214933deb841dd8ec625f8fe8/src/core/lib/iomgr/event_engine/tcp.cc#L64)):*
> ```cpp
>   }
> 
>   ~WrappedInternalSliceAllocator() {
> ```

The dtor should go before other methods, as per:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 85 at r15](https://reviewable.io/reviews/grpc/grpc/26643#-Mg7BtK48kkzao4Maect:-Mg7BtK48kkzao4Maecu:b-qck07r) ([raw file](https://github.com/grpc/grpc/blob/bcb9c8c28c54cfc214933deb841dd8ec625f8fe8/src/core/lib/iomgr/event_engine/tcp.cc#L85)):*
> ```cpp
>   };
> 
>   ~WrappedInternalSliceAllocatorFactory() {
> ```

The dtor should go before other methods.


<!-- Sent from Reviewable.io -->

2021-08-02 19:00 UTC, drfloob reviewed
Aside from within tests, we're potentially creating resource_quotas on chttp2 connect, add/create channel from fd (posix), and in most of the credential acquisition code (ctiller has old TODOs about saving the RQ for reuse). In the first two cases, quotas will be created if none are set in channel_args, where no quotas have explicitly been defined by the application. In the auth credentials, new RQs are always created. For the redesign, I think we should firm up the story around how many quotas of what sorts gRPC will support concurrently. And should quotas be related? For example, we may want to set a maximum allotment per channel or endpoint, also subject to global limits. Alternatively, having just one quota in the current design would give us a better view into how much memory is being used across gRPC at any given time, even if no maximum allotment has been set. I just wanted to call it out now that I'm looking into the resource user system, I'll add some notes on the design doc.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-Mg7AFN41WXKIOah8szB:b2lqhn9)* status: all files reviewed, 3 unresolved discussions (waiting on @ctiller and @drfloob)



<!-- Sent from Reviewable.io -->

2021-08-02 19:01 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643)* status: all files reviewed, 3 unresolved discussions (waiting on @ctiller and @markdroth)

___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 64 at r15](https://reviewable.io/reviews/grpc/grpc/26643#-Mg7Bm8H-9DhYKrYNRKE:-Mg7ESkA-CcCE3SpGjV5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bcb9c8c28c54cfc214933deb841dd8ec625f8fe8/src/core/lib/iomgr/event_engine/tcp.cc#L64)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The dtor should go before other methods, as per:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/tcp.cc, line 85 at r15](https://reviewable.io/reviews/grpc/grpc/26643#-Mg7BtK48kkzao4Maect:-Mg7ESyq9ufb-nqnR571:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bcb9c8c28c54cfc214933deb841dd8ec625f8fe8/src/core/lib/iomgr/event_engine/tcp.cc#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The dtor should go before other methods.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-02 19:06 UTC, markdroth approved these changes
I agree that we should think about where exactly we want to create RQs in the future.  I suspect that we probably want one per channel on the client side and one per server on the server list.  We *may* also want to consider having one per connection on the server side, especially if we provide hooks for the application to decide which one to use for a given connection, to allow some mechanism for isolation.

But none of that is a blocker for this PR.  This looks great!

> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26643#-:-Mg7Eo88BKOsHmlWr0C6:b-drs6f9)* status: all files reviewed, 1 unresolved discussion (waiting on @ctiller)



<!-- Sent from Reviewable.io -->

2021-08-16 20:50 UTC, merged