Add internal API to help trace retries and collect metrics
grpc/grpc pull request #26673
Opened 2021-07-12 23:57 UTC by yashykt

2021-07-13 17:33 UTC, markdroth requested changes
Thanks for doing this!

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673#-:-MeVvR3yDAgSurdDJWa8:b-pevjuw)* status: all files reviewed, 15 unresolved discussions (waiting on @yashykt)

___
*[src/core/lib/channel/call_tracer.h, line 33 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVqjsd4Th1zjHvRwcY:-MeVqjseC_HiSSmfAadX:bsv7qjt) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L33)):*
> ```objc
> // transparent retry attempts.)
> 
> class CallAttemptTracer {
> ```

Please nest this inside of `CallTracer`.
___
*[src/core/lib/channel/call_tracer.h, line 33 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVr7J12ZnYraCrcb_Y:-MeVr7J12ZnYraCrcb_Z:bpa2ymn) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L33)):*
> ```objc
> // transparent retry attempts.)
> 
> class CallAttemptTracer {
> ```

Classes with virtual methods need virtual dtors.
___
*[src/core/lib/channel/call_tracer.h, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVt-n-21q_RL6T-vDd:-MeVt-n-21q_RL6T-vDe:bmge8i1) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L38)):*
> ```objc
>   // arguments.
>   virtual void RecordSendInitialMetadata(
>       grpc_metadata_batch* send_initial_metadata, uint32_t flags) = 0;
> ```

Please pass in the metadata as a const reference.

Same for all methods that take metadata.
___
*[src/core/lib/channel/call_tracer.h, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVstkE8AUP8QuAyRrH:-MeVstkE8AUP8QuAyRrI:b-n6dmtd) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L39)):*
> ```objc
>   virtual void RecordSendInitialMetadata(
>       grpc_metadata_batch* send_initial_metadata, uint32_t flags) = 0;
>   virtual void RecordOnDoneSendInitialMetadata(gpr_atm* peer_string) = 0;
> ```

The parameter should be of type `absl::string_view`.
___
*[src/core/lib/channel/call_tracer.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsTGZ7FcJyryyTZiC:-MeVsTGZ7FcJyryyTZiD:b-i6iwwa) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L43)):*
> ```objc
>       grpc_metadata_batch* send_trailing_metadata) = 0;
>   virtual void RecordSendMessage(
>       grpc_core::OrphanablePtr<grpc_core::ByteStream> send_message) = 0;
> ```

No need for `grpc_core::` prefixes, since we're already in that namespace.

Same for `RecordReceivedMessage()` below.
___
*[src/core/lib/channel/call_tracer.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVt75y6IpSfKGbdNAE:-MeVt75y6IpSfKGbdNAF:b-mft4ve) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L43)):*
> ```objc
>       grpc_metadata_batch* send_trailing_metadata) = 0;
>   virtual void RecordSendMessage(
>       grpc_core::OrphanablePtr<grpc_core::ByteStream> send_message) = 0;
> ```

This isn't going to take ownership of the `OrphanablePtr<>`, so it doesn't make sense to pass it in that way.  I think the parameter should probably just be a `const ByteStream*`.

Same for `RecordReceivedMessage()` below.
___
*[src/core/lib/channel/call_tracer.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVrOAa5O7nCrlOZv5q:-MeVrOAa5O7nCrlOZv5r:bnbpznj) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L46)):*
> ```objc
>   virtual void RecordReceivedInitialMetadata(
>       grpc_metadata_batch* recv_initial_metadata, uint32_t* flags,
>       gpr_atm* peer_string) = 0;
> ```

I think `peer_string` should be passed in as an `absl::string_view`.
___
*[src/core/lib/channel/call_tracer.h, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsaen34TV7H6-CzgB:-MeVsaeo2sp08_47XtWy:b-s6llbm) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L51)):*
> ```objc
>   virtual void RecordReceivedTrailingMetadata(
>       grpc_metadata_batch* recv_trailing_metadata) = 0;
>   virtual void RecordCancel(grpc_error_handle cancel_error) = 0;
> ```

This probably isn't needed here, since cancellation comes from the surface and can be directly seen by the OpenCensus filter.
___
*[src/core/lib/channel/call_tracer.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsZyk0MZ5tSS1uY_6:-MeVsZyk0MZ5tSS1uY_7:b-jhtqo1) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L52)):*
> ```objc
>       grpc_metadata_batch* recv_trailing_metadata) = 0;
>   virtual void RecordCancel(grpc_error_handle cancel_error) = 0;
>   virtual void RecordAnnotation(absl::string_view annotation) = 0;
> ```

Please document this method.
___
*[src/core/lib/channel/call_tracer.h, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVunyF1sE01XQ8WPAK:-MeVunyF1sE01XQ8WPAL:b2btlt8) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L53)):*
> ```objc
>   virtual void RecordCancel(grpc_error_handle cancel_error) = 0;
>   virtual void RecordAnnotation(absl::string_view annotation) = 0;
>   virtual void RecordEnd(const grpc_call_final_info* final_info) = 0;
> ```

Can pass this in as a reference instead of a pointer.
___
*[src/core/lib/channel/call_tracer.h, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVspLB2vhByDcmq5Xl:-MeVspLB2vhByDcmq5Xm:bpa2ymn) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L59)):*
> ```objc
> // this call are traced with CallAttemptTracer after invoking RecordNewAttempt()
> // on the CallTracer object.
> class CallTracer {
> ```

Classes with virtual methods need virtual dtors.
___
*[src/core/lib/channel/call_tracer.h, line 64 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVr0FN3d8rwlLbTdZu:-MeVr0FN3d8rwlLbTdZv:b3spw9m) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L64)):*
> ```objc
>   // whether the attempt is being made as a transparent retry or as a
>   // non-transparent retry/heding attempt.
>   virtual CallAttemptTracer* RecordNewAttempt(bool transparent) = 0;
> ```

What's the ownership story here?  If the caller takes ownership, then we should probably return a `unique_ptr<>`.  Or do we expect that this will be allocated on the arena?  If so, the `CallAttemptTracer` probably needs a virtual `Destroy()` method, so that we can clean it up without deleting it.
___
*[src/core/lib/channel/call_tracer.h, line 64 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVuhIb7de9JiZ9M9jK:-MeVuhIcAleq1R6WzLAg:b95qqzh) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L64)):*
> ```objc
>   // whether the attempt is being made as a transparent retry or as a
>   // non-transparent retry/heding attempt.
>   virtual CallAttemptTracer* RecordNewAttempt(bool transparent) = 0;
> ```

Please call the parameter `is_transparent_retry`.
___
*[src/core/lib/channel/call_tracer.h, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVrCHmCaFnVgm-beXD:-MeVrCHmCaFnVgm-beXE:b-jhtqo1) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L65)):*
> ```objc
>   // non-transparent retry/heding attempt.
>   virtual CallAttemptTracer* RecordNewAttempt(bool transparent) = 0;
>   virtual void RecordAnnotation(absl::string_view annotation) = 0;
> ```

Please document this meth [...]

2021-07-14 22:13 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673)* status: 3 of 5 files reviewed, 15 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/channel/call_tracer.h, line 33 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVqjsd4Th1zjHvRwcY:-Meb06Zf1Pdte5BUUzLQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L33)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please nest this inside of `CallTracer`.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 33 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVr7J12ZnYraCrcb_Y:-Meb06uv5VQSxjft5m0F:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L33)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Classes with virtual methods need virtual dtors.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVt-n-21q_RL6T-vDd:-Meb07T82rDY9hcgG_rL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please pass in the metadata as a const reference.

Same for all methods that take metadata.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVstkE8AUP8QuAyRrH:-Meb2Y7tB3Q244jQiFW0:bjzqki) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L39)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The parameter should be of type `absl::string_view`.
</blockquote></details>

I understand that an atomic load with acquire semantics is not that costly especially on x86-64 processors without much contention, but it would still be atleast as costly as a memory access, and if we don't need it, we shouldn't load it unnecessarily. For example, the OpenCensus tracer would not need it.
___
*[src/core/lib/channel/call_tracer.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsTGZ7FcJyryyTZiC:-Meb3DJDDaHybO62ASbn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `grpc_core::` prefixes, since we're already in that namespace.

Same for `RecordReceivedMessage()` below.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVt75y6IpSfKGbdNAE:-Meb3Dos1X7CjyOixE6P:b-owisu5) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This isn't going to take ownership of the `OrphanablePtr<>`, so it doesn't make sense to pass it in that way.  I think the parameter should probably just be a `const ByteStream*`.

Same for `RecordReceivedMessage()` below.
</blockquote></details>

You are right. Done!
___
*[src/core/lib/channel/call_tracer.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVrOAa5O7nCrlOZv5q:-Meb3K1dEh975KVElAJt:b-34vmyd) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think `peer_string` should be passed in as an `absl::string_view`.
</blockquote></details>

See above
___
*[src/core/lib/channel/call_tracer.h, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsaen34TV7H6-CzgB:-Meb3Lw-CHB6veS4dmi5:b-aam7lh) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This probably isn't needed here, since cancellation comes from the surface and can be directly seen by the OpenCensus filter.
</blockquote></details>

I agree that it is probably not needed, and that the OpenCensus filter can probably record it, but I'm also considering hedging, where the hedging filter would want to cancel pending attempts after the successful completion of some attempt. Also, there is something nice about not having to special case cancellation from the other ops for OpenCensusFilter.
___
*[src/core/lib/channel/call_tracer.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsZyk0MZ5tSS1uY_6:-Meb4JsC2REnzfPf9YT8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document this method.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVunyF1sE01XQ8WPAK:-Meb4KHb1GeG_oQJjvAF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L53)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can pass this in as a reference instead of a pointer.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 59 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVspLB2vhByDcmq5Xl:-Meb4KtHDiuAsoJUA649:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Classes with virtual methods need virtual dtors.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 64 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVr0FN3d8rwlLbTdZu:-MeavHlF8G-WR3VF5hcn:bk8er2p) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L64)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What's the ownership story here?  If the caller takes ownership, then we should probably return a `unique_ptr<>`.  Or do we expect that this will be allocated on the arena?  If so, the `CallAttemptTracer` probably needs a virtual `Destroy()` method, so that we can clean it up without deleting it.
</blockquote></details>

Ownership is not transferred. The census filter/tracer library retains ownership of the `CallAttempTracer` object. `RecordEnd()` serves as an indication that the call stack is done with all API calls, and the tracer library is free to destroy it after that
___
*[src/core/lib/channel/call_tracer.h, line 64 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVuhIb7de9JiZ9M9jK:-Meb02Hw1aQQ1WjjRX3Q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L64)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call the parameter `is_transparent_retry`.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVrCHmCaFnVgm-beXD:-Meb01dUA0yP1Xn9DJSv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Pl [...]

2021-07-14 22:31 UTC, yashykt commented
___
*[src/core/lib/channel/call_tracer.h, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVt-n-21q_RL6T-vDd:-Meb86Up1WcjzoRmBMeA:b-fjy6p5) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L38)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh well, now that I think about it, the census tracer needs to be able to add/remove trace specific metadata


<!-- Sent from Reviewable.io -->

2021-07-16 22:47 UTC, markdroth requested changes
Just a few minor comments remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 2 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673#-:-MelVESI8n8uqPlR1YDh:b-f6s43a)* status: all files reviewed, 10 unresolved discussions (waiting on @yashykt)

___
*[src/core/lib/channel/call_tracer.h, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVt-n-21q_RL6T-vDd:-MelST-KDWQvmBsvmHAv:bdcv6l8) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L38)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Oh well, now that I think about it, the census tracer needs to be able to add/remove trace specific metadata
</blockquote></details>

Good point.
___
*[src/core/lib/channel/call_tracer.h, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVstkE8AUP8QuAyRrH:-MelTpnB3OlH54bPzMTU:b-s3lamc) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L39)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I understand that an atomic load with acquire semantics is not that costly especially on x86-64 processors without much contention, but it would still be atleast as costly as a memory access, and if we don't need it, we shouldn't load it unnecessarily. For example, the OpenCensus tracer would not need it.
</blockquote></details>

Hmmm, okay.  I'm not crazy about this from an API design perspective, though.  How about adding a TODO about improving this later?
___
*[src/core/lib/channel/call_tracer.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVt75y6IpSfKGbdNAE:-MelSlPe0QDoxtEZNiQ9:bmp5ewa) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L43)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

You are right. Done!
</blockquote></details>

Doesn't this need to be a pointer instead of a reference, since the actual object will be a subclass of `ByteStream`?

Same for `RecordReceivedMessage()` below.
___
*[src/core/lib/channel/call_tracer.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVrOAa5O7nCrlOZv5q:-MelUFmJ74vy3Geg7FNY:b-q64pkt) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L46)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

See above
</blockquote></details>

See above.
___
*[src/core/lib/channel/call_tracer.h, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsaen34TV7H6-CzgB:-MelT3lREaOTDfGDpPfO:b-t7z66d) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L51)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I agree that it is probably not needed, and that the OpenCensus filter can probably record it, but I'm also considering hedging, where the hedging filter would want to cancel pending attempts after the successful completion of some attempt. Also, there is something nice about not having to special case cancellation from the other ops for OpenCensusFilter.
</blockquote></details>

Good point.  Even in retries, this will come up once we support `perAttemptRecvTimeout`.
___
*[src/core/lib/channel/call_tracer.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsZyk0MZ5tSS1uY_6:-MelTBPX2eCnuQ_vX9DW:b-iirtu3) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L52)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

How will this be used by the client channel code?  When would this ever be called?

Note that if this needs to be called only by the OpenCensus filter, then it doesn't need to be part of this API; it can be provided by the OpenCensus subclass only.
___
*[src/core/lib/channel/call_tracer.h, line 64 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVr0FN3d8rwlLbTdZu:-MelTLa38ba7JpXWmn07:brys8fi) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L64)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Ownership is not transferred. The census filter/tracer library retains ownership of the `CallAttempTracer` object. `RecordEnd()` serves as an indication that the call stack is done with all API calls, and the tracer library is free to destroy it after that
</blockquote></details>

Okay.  Please document this in the comments.
___
*[src/core/lib/channel/call_tracer.h, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVrCHmCaFnVgm-beXD:-MelTfcdDhico2T7vXhr:bnz0twn) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L65)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same question as above -- it's not clear to me when the client channel code would ever call this.
___
*[src/core/lib/channel/call_tracer.h, line 69 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MelTTow6eeABboUDSgt:-MelTTow6eeABboUDSgu:b-nmf6xs) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L69)):*
> ```objc
>   // Records a new attempt for the associated call. \a transparent denotes
>   // whether the attempt is being made as a transparent retry or as a
>   // non-transparent retry/heding attempt.
> ```

Might be a good idea to clarify that even if a call is not being retried, there will always be at least one attempt (unless the call gets cancelled before it gets down far enough in the stack).
___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 32 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MelUf0jBJ5XORVvWXod:-MelUf0jBJ5XORVvWXoe:bjxyi17) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/cpp/ext/filters/census/open_census_call_tracer.h#L32)):*
> ```objc
>  public:
>   class OpenCensusCallAttemptTracer
>       : public grpc_core::CallTracer::CallAttemptTracer {
> ```

I don't think the `grpc_core::CallTracer::` is needed, since we're already inside of that scope here.
___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 34 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MelUmYa3WdtwKF6Ec6m:-MelUmYa3WdtwKF6Ec6n:b-5fsurj) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/cpp/ext/filters/census/open_census_call_tracer.h#L34)):*
> ```objc
>       : public grpc_core::CallTracer::CallAttemptTracer {
>    public:
>     ~OpenCensusCallAttemptTracer() override {}
> ```

No need to override the dtor if you don't need to do anything in it.


<!-- Sent from Reviewable.io -->

2021-07-16 23:39 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673)* status: all files reviewed, 12 unresolved discussions (waiting on @yashykt)

___
*[src/core/lib/channel/call_tracer.h, line 54 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-Melf8q-2o-qths3fV2h:-Melf8q-2o-qths3fV2i:b-l6jbsq) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L54)):*
> ```objc
>         gpr_atm* peer_string) = 0;
>     virtual void RecordReceivedMessage(const ByteStream& recv_message) = 0;
>     virtual void RecordReceivedTrailingMetadata(
> ```

Does this also need to take the `grpc_error_handle` of the recv_trailing_metadata_ready callback?  I think it will need both pieces of info in order to determine the call's status.

Alternatively, maybe it would be better to just pass an `absl::Status` as a separate argument indicating the call's status.  The client channel code is already figuring this out for other reasons, so it could easily just pass the resulting status to the tracer.
___
*[src/core/lib/channel/call_tracer.h, line 70 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MelezEU5X8dz_8Pv2sT:-MelezEU5X8dz_8Pv2sU:b-f84rxm) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L70)):*
> ```objc
>   // whether the attempt is being made as a transparent retry or as a
>   // non-transparent retry/heding attempt.
>   virtual CallAttemptTracer* RecordNewAttempt(bool is_transparent_retry) = 0;
> ```

Suggest calling this `StartNewAttempt()`, since it's really the start of the attempt, not the end.


<!-- Sent from Reviewable.io -->

2021-07-16 23:50 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673)* status: all files reviewed, 13 unresolved discussions (waiting on @yashykt)

___
*[src/core/lib/channel/call_tracer.h, line 46 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MeliApF-WEJTQpsdWYS:-MeliApF-WEJTQpsdWYT:b-z3m7if) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L46)):*
> ```objc
>     virtual void RecordSendInitialMetadata(
>         grpc_metadata_batch* send_initial_metadata, uint32_t flags) = 0;
>     virtual void RecordOnDoneSendInitialMetadata(gpr_atm* peer_string) = 0;
> ```

Does the census filter need the peer string at the point where send_initial_metadata completes, or can it just get it when recv_initial_metadata completes?  The fact that we've historically exposed this before recv_initial_metadata completes is actually a bug IMHO, and we're probably going to have to change at that some point, since it complicates things for the retry code.  If we can have the census filter get this with recv_initial_metadata instead, it will be one less thing to fix later.


<!-- Sent from Reviewable.io -->

2021-07-16 23:57 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673)* status: all files reviewed, 14 unresolved discussions (waiting on @yashykt)

___
*[src/core/lib/channel/call_tracer.h, line 51 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-Melk8v_0JTAIWhoZ9sc:-Melk8va3zm5h7hNBdqD:b9mm7go) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L51)):*
> ```objc
>     virtual void RecordSendMessage(const ByteStream& send_message) = 0;
>     virtual void RecordReceivedInitialMetadata(
>         grpc_metadata_batch* recv_initial_metadata, uint32_t* flags,
> ```

The flags shouldn't be a pointer.


<!-- Sent from Reviewable.io -->

2021-07-19 19:12 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673)* status: 11 of 13 files reviewed, 14 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/channel/call_tracer.h, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVstkE8AUP8QuAyRrH:-Mf-A6TeDbKX9wFicGt-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L39)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hmmm, okay.  I'm not crazy about this from an API design perspective, though.  How about adding a TODO about improving this later?
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVt75y6IpSfKGbdNAE:-Mexo12cEdkK6qKnx3_n:b-952g89) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L43)):*
> Doesn't this need to be a pointer instead of a reference, since the actual object will be a subclass of ByteStream?

If you are referring to object slicing, then it doesn't matter whether you use a reference or a pointer. it does the right thing either way.
___
*[src/core/lib/channel/call_tracer.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVrOAa5O7nCrlOZv5q:-Mf-AC51EuHkSH4qYV_U:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 51 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsaen34TV7H6-CzgB:-Mf-6ByJ-C0hbcYrH6Y1:b2nhb2c) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Good point.  Even in retries, this will come up once we support `perAttemptRecvTimeout`.
</blockquote></details>

Ack
___
*[src/core/lib/channel/call_tracer.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsZyk0MZ5tSS1uY_6:-Mf-6DlT6Lruaah6Kl90:b-k2nxdw) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How will this be used by the client channel code?  When would this ever be called?

Note that if this needs to be called only by the OpenCensus filter, then it doesn't need to be part of this API; it can be provided by the OpenCensus subclass only.
</blockquote></details>

This came up from a separate discussion I was having internally where the user was trying to figure out why RPCs are taking so long. In that case, logging was not useful since there were too many RPCs going on for it to be deciphered in a sane way. Here, we thought that it might be nice to be able to add annotations in other parts of the code so that we know what's happening when by just looking at the traces. For example, annotations being printed on some filter. Now, since we are already touching this part of the code, I figured it would be nice to include it. For OSS, it'll just be a no-op at present.
___
*[src/core/lib/channel/call_tracer.h, line 64 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVr0FN3d8rwlLbTdZu:-Mf-Ad8y1V_sKVpPx8tv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L64)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  Please document this in the comments.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVrCHmCaFnVgm-beXD:-Mf-7nP_7ySnFGWhfqmU:bv2dbkh) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same question as above -- it's not clear to me when the client channel code would ever call this.
</blockquote></details>

See above. (It doesn't need to right now, but we might want to use it in the future as a debugging tool.)
___
*[src/core/lib/channel/call_tracer.h, line 46 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MeliApF-WEJTQpsdWYS:-MexnIEF8FX2BMRd4EpM:b-3m6n21) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Does the census filter need the peer string at the point where send_initial_metadata completes, or can it just get it when recv_initial_metadata completes?  The fact that we've historically exposed this before recv_initial_metadata completes is actually a bug IMHO, and we're probably going to have to change at that some point, since it complicates things for the retry code.  If we can have the census filter get this with recv_initial_metadata instead, it will be one less thing to fix later.
</blockquote></details>

Not the OSS filter, but the internal filter does log the peer string when send_initial_metadata completes.
___
*[src/core/lib/channel/call_tracer.h, line 51 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-Melk8v_0JTAIWhoZ9sc:-Mf-ABbM0mEA_tXOI9st:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The flags shouldn't be a pointer.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 54 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-Melf8q-2o-qths3fV2h:-Mf-5QGgEoZmIa9JnBIu:b6eez7b) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Does this also need to take the `grpc_error_handle` of the recv_trailing_metadata_ready callback?  I think it will need both pieces of info in order to determine the call's status.

Alternatively, maybe it would be better to just pass an `absl::Status` as a separate argument indicating the call's status.  The client channel code is already figuring this out for other reasons, so it could easily just pass the resulting status to the tracer.
</blockquote></details>

I don't think it is needed. We should simply invoke it when recv_trailing_metadata callback is invoked without any error, i.e, with GRPC_ERROR_NONE. The final call status details will be available at `RecordEnd()`.
___
*[src/core/lib/channel/call_tracer.h, line 69 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MelTTow6eeABboUDSgt:-Mf-AED03yyVF1Qx3EF2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L69)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Might be a good idea to clarify that even if a call is not being retried, there will always be at least one attempt (unless the call gets cancelled before it gets down far enough in the stack).
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 70 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MelezEU5X8dz_8Pv2sT:-Mf-Adgn7cTs0nDU-yUm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `StartNewAttempt()`, since  [...]

2021-07-19 19:34 UTC, markdroth requested changes
Just a few remaining comments.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673#-:-Mf-FplPDJgF45Gte2Di:b4fmc69)* status: all files reviewed, 5 unresolved discussions (waiting on @yashykt)

___
*[src/core/lib/channel/call_tracer.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVt75y6IpSfKGbdNAE:-Mf-Dr81AX_R8yaPePJl:b4ygmw4) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L43)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> Doesn't this need to be a pointer instead of a reference, since the actual object will be a subclass of ByteStream?

If you are referring to object slicing, then it doesn't matter whether you use a reference or a pointer. it does the right thing either way.
</blockquote></details>

Huh, you're right.  For some reason, I had it in my head that C++ would not properly handle virtual methods via a reference instead of a pointer.  TIL.
___
*[src/core/lib/channel/call_tracer.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsZyk0MZ5tSS1uY_6:-Mf-EOAYAqzELu3JvgmQ:bopula) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L52)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

This came up from a separate discussion I was having internally where the user was trying to figure out why RPCs are taking so long. In that case, logging was not useful since there were too many RPCs going on for it to be deciphered in a sane way. Here, we thought that it might be nice to be able to add annotations in other parts of the code so that we know what's happening when by just looking at the traces. For example, annotations being printed on some filter. Now, since we are already touching this part of the code, I figured it would be nice to include it. For OSS, it'll just be a no-op at present.
</blockquote></details>

Where would you expect the client channel code or the transport code or anything else to call this?  If this isn't actually going to be called anywhere, it doesn't seem very useful to have it in the API.

Note that we can easily add this later if/when we have a concrete use-case for it.
___
*[src/core/lib/channel/call_tracer.h, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVrCHmCaFnVgm-beXD:-Mf-Eljt2IeFkHB01g3C:b-q64pkt) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L65)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

See above. (It doesn't need to right now, but we might want to use it in the future as a debugging tool.)
</blockquote></details>

See above.
___
*[src/core/lib/channel/call_tracer.h, line 46 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MeliApF-WEJTQpsdWYS:-Mf-CY960cvCMtsc1uS_:b-t4h4al) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L46)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Not the OSS filter, but the internal filter does log the peer string when send_initial_metadata completes.
</blockquote></details>

Is there a reason it needs to do that at that particular point?  Can we change it to log it when it sees recv_initial_metadata instead?  What would break if we did that?

I'd really rather not add this if we can avoid it.  And actually, given the fact that changing the internal filter to use this API will be a separate effort, it seems like we don't really need this right now anyway.
___
*[src/core/lib/channel/call_tracer.h, line 54 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-Melf8q-2o-qths3fV2h:-Mf-EBw07CBMzkXdyR-s:b-kyz0pl) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L54)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I don't think it is needed. We should simply invoke it when recv_trailing_metadata callback is invoked without any error, i.e, with GRPC_ERROR_NONE. The final call status details will be available at `RecordEnd()`.
</blockquote></details>

Okay.  Please document that expectation.
___
*[src/core/lib/channel/call_tracer.h, line 77 at r6](https://reviewable.io/reviews/grpc/grpc/26673#-Mf-EcEx8E2GtKOIdmvK:-Mf-EcEx8E2GtKOIdmvL:b-ci6o07) ([raw file](https://github.com/grpc/grpc/blob/f3b5865a57f2b7af1ce9ca53567c1f9a9e6e8816/src/core/lib/channel/call_tracer.h#L77)):*
> ```objc
>   // Records a new attempt for the associated call. \a transparent denotes
>   // whether the attempt is being made as a transparent retry or as a
>   // non-transparent retry/heding attempt. (There will be atleast one attempt
> ```

s/atleast/at least/


<!-- Sent from Reviewable.io -->

2021-07-19 20:13 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673)* status: 11 of 13 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/channel/call_tracer.h, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVt75y6IpSfKGbdNAE:-Mf-L1y5Azg_AfH0BFqI:bkmhvz3) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Huh, you're right.  For some reason, I had it in my head that C++ would not properly handle virtual methods via a reference instead of a pointer.  TIL.
</blockquote></details>

I don't think you are alone in that. I did spend some time grokking the docs trying to make sure that was the case. 
___
*[src/core/lib/channel/call_tracer.h, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVsZyk0MZ5tSS1uY_6:-Mf-OUF66JrJULLYUu4m:b-txt5e2) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Where would you expect the client channel code or the transport code or anything else to call this?  If this isn't actually going to be called anywhere, it doesn't seem very useful to have it in the API.

Note that we can easily add this later if/when we have a concrete use-case for it.
</blockquote></details>

Removed as discussed
___
*[src/core/lib/channel/call_tracer.h, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26673#-MeVrCHmCaFnVgm-beXD:-Mf-OgIqDSUrmvsHTBzx:b-x7doru) ([raw file](https://github.com/grpc/grpc/blob/04f1129222b39dee53bff7927d1192a8cb95bc7e/src/core/lib/channel/call_tracer.h#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

removed as discussed
___
*[src/core/lib/channel/call_tracer.h, line 46 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MeliApF-WEJTQpsdWYS:-Mf-O6qM-9aGVN7w59zF:ba3dfob) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is there a reason it needs to do that at that particular point?  Can we change it to log it when it sees recv_initial_metadata instead?  What would break if we did that?

I'd really rather not add this if we can avoid it.  And actually, given the fact that changing the internal filter to use this API will be a separate effort, it seems like we don't really need this right now anyway.
</blockquote></details>

Removed
___
*[src/core/lib/channel/call_tracer.h, line 54 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-Melf8q-2o-qths3fV2h:-Mf-OT6e3kriZSF8DPrx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  Please document that expectation.
</blockquote></details>

Done.
___
*[src/core/lib/channel/call_tracer.h, line 77 at r6](https://reviewable.io/reviews/grpc/grpc/26673#-Mf-EcEx8E2GtKOIdmvK:-Mf-OWFPCuDPkVoP4cdR:b-5pccgv) ([raw file](https://github.com/grpc/grpc/blob/f3b5865a57f2b7af1ce9ca53567c1f9a9e6e8816/src/core/lib/channel/call_tracer.h#L77)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/atleast/at least/
</blockquote></details>

I think my brain is hardwired to write `atleast` instead of `at least`


<!-- Sent from Reviewable.io -->

2021-07-19 21:42 UTC, markdroth requested changes
Just one remaining comment.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673#-:-Mf-i7vi07Ua4xxvr8wa:b5k3y95)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/lib/channel/call_tracer.h, line 46 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MeliApF-WEJTQpsdWYS:-Mf-hsKr5kM49HT1weZL:bwaz4w8) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L46)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Removed
</blockquote></details>

Can we just completely remove the `RecordOnDoneSendInitialMetadata()` method?  It would be nice to not have to intercept yet another callback if there's no reason we actually need to do so.


<!-- Sent from Reviewable.io -->

2021-07-19 22:04 UTC, markdroth requested changes
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673)* status: all files reviewed, 3 unresolved discussions (waiting on @yashykt)

___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 40 at r8](https://reviewable.io/reviews/grpc/grpc/26673#-Mf-n30lAn6AtxwIyf_Z:-Mf-n30lAn6AtxwIyf__:b-afylyj) ([raw file](https://github.com/grpc/grpc/blob/659a14e9652c642f354dcc0f4f5b606017f1c45f/src/cpp/ext/filters/census/open_census_call_tracer.h#L40)):*
> ```objc
>         grpc_metadata_batch* /* send_trailing_metadata */) override {}
>     void RecordSendMessage(
>         const grpc_core::ByteStream& /* send_message */) override {}
> ```

No need for `grpc_core::`.
___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 45 at r8](https://reviewable.io/reviews/grpc/grpc/26673#-Mf-n4ok1WiB71GHdyob:-Mf-n4ok1WiB71GHdyoc:b-afylyj) ([raw file](https://github.com/grpc/grpc/blob/659a14e9652c642f354dcc0f4f5b606017f1c45f/src/cpp/ext/filters/census/open_census_call_tracer.h#L45)):*
> ```objc
>         gpr_atm* /* peer_string */) override {}
>     void RecordReceivedMessage(
>         const grpc_core::ByteStream& /* recv_message */) override {}
> ```

No need for `grpc_core::`.


<!-- Sent from Reviewable.io -->

2021-07-19 22:27 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/channel/call_tracer.h, line 46 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MeliApF-WEJTQpsdWYS:-Mf-rv5Z7phvRgTgpVMN:b-hlp6w7) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can we just completely remove the `RecordOnDoneSendInitialMetadata()` method?  It would be nice to not have to intercept yet another callback if there's no reason we actually need to do so.
</blockquote></details>

I was looking at the same thing, but unfortunately, internally, the tracer adds annotations when the initial metadata is sent. 
___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 40 at r8](https://reviewable.io/reviews/grpc/grpc/26673#-Mf-n30lAn6AtxwIyf_Z:-Mf-rmufCsLw3kwZwyzX:b-n4m508) ([raw file](https://github.com/grpc/grpc/blob/659a14e9652c642f354dcc0f4f5b606017f1c45f/src/cpp/ext/filters/census/open_census_call_tracer.h#L40)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `grpc_core::`.
</blockquote></details>

It is needed. (This is not in the `grpc_core` namespace.)
___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 45 at r8](https://reviewable.io/reviews/grpc/grpc/26673#-Mf-n4ok1WiB71GHdyob:-Mf-rtA069w6Krmg6qB5:b-n4m508) ([raw file](https://github.com/grpc/grpc/blob/659a14e9652c642f354dcc0f4f5b606017f1c45f/src/cpp/ext/filters/census/open_census_call_tracer.h#L45)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `grpc_core::`.
</blockquote></details>

It is needed. (This is not in the `grpc_core` namespace.)


<!-- Sent from Reviewable.io -->

2021-07-19 22:38 UTC, markdroth approved these changes
This looks great!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26673#-:-Mf-up-s-cMLpCKbWLBx:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yashykt)

___
*[src/core/lib/channel/call_tracer.h, line 46 at r4](https://reviewable.io/reviews/grpc/grpc/26673#-MeliApF-WEJTQpsdWYS:-Mf-uVJ6C8vBZVTA7aoB:b-7lzcc4) ([raw file](https://github.com/grpc/grpc/blob/fdf0192004fb0ab1307003e793ce9e19c9bdcc3b/src/core/lib/channel/call_tracer.h#L46)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I was looking at the same thing, but unfortunately, internally, the tracer adds annotations when the initial metadata is sent. 
</blockquote></details>

Okay.  I've added a handler for this callback as well in #26714.

The amount of additional per-call memory being added here is unfortunate, but I guess this will ultimately be taken care of by moving to Craig's promise library.
___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 40 at r8](https://reviewable.io/reviews/grpc/grpc/26673#-Mf-n30lAn6AtxwIyf_Z:-Mf-ukcP8s16jQldiZCK:bdcv6l8) ([raw file](https://github.com/grpc/grpc/blob/659a14e9652c642f354dcc0f4f5b606017f1c45f/src/cpp/ext/filters/census/open_census_call_tracer.h#L40)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

It is needed. (This is not in the `grpc_core` namespace.)
</blockquote></details>

Good point.


<!-- Sent from Reviewable.io -->

2021-07-20 14:05 UTC, yashykt commented
Known Issues: #26723, #26595, #26728

2021-07-20 14:05 UTC, yashykt commented
Thanks for reviewing!

2021-07-20 14:05 UTC, merged