Open census filter stats api
grpc/grpc pull request #26739
Opened 2021-07-20 19:00 UTC by yashykt

2021-07-27 19:45 UTC, markdroth requested changes
This looks good overall, just some details to nail down.

As we discussed, we do need tests here.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739#-:-MfdP-w8Agle9fpRamx2:b-an0z4s)* status: all files reviewed, 16 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 2871 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdIZJuDa5rIgRLH0L6:-MfdIZJuDa5rIgRLH0L7:b-gql0x9) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/core/ext/filters/client_channel/client_channel.cc#L2871)):*
> ```cpp
>     void* arg, grpc_error_handle error) {
>   auto* self = static_cast<LoadBalancedCall*>(arg);
>   self->call_attempt_tracer_->RecordReceivedInitialMetadata(
> ```

Looks like I am not handling this right from my PR: This should be called only if `error == GRPC_ERROR_NONE`.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 2872 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdFbh45n9AHl0e4a03:-MfdFbh45n9AHl0e4a04:b-s2q5js) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/core/ext/filters/client_channel/client_channel.cc#L2872)):*
> ```cpp
>   auto* self = static_cast<LoadBalancedCall*>(arg);
>   self->call_attempt_tracer_->RecordReceivedInitialMetadata(
>       self->recv_initial_metadata_, 0 /* ignored_for_clients */);
> ```

Please change the inline comment to say "recv_initial_metadata_flags", and then add a comment on the line above saying that these aren't used on clients, only on servers.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 2880 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdIhSf7c5qCDi6wwda:-MfdIhSf7c5qCDi6wwdb:bexlc2n) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/core/ext/filters/client_channel/client_channel.cc#L2880)):*
> ```cpp
>     void* arg, grpc_error_handle error) {
>   auto* self = static_cast<LoadBalancedCall*>(arg);
>   self->call_attempt_tracer_->RecordReceivedMessage(**self->recv_message_);
> ```

Similar to above: This should be called only if `*self->recv_message_ != nullptr`.
___
*[src/core/lib/surface/call.cc, line 535 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdFpRW2UtpqM5duUZ3:-MfdFpRW2UtpqM5duUZ4:b-l2ouod) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/core/lib/surface/call.cc#L535)):*
> ```cpp
>   grpc_channel* channel = c->channel;
>   grpc_core::Arena* arena = c->arena;
>   for (int i = 0; i < GRPC_CONTEXT_COUNT; ++i) {
> ```

It might actually make more sense to put this in the `grpc_call` dtor.  I think that would be functionally equivalent to what you're doing here, so it shouldn't cause any problems, but it seems a little cleaner conceptually.
___
*[src/cpp/ext/filters/census/client_filter.h, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdG6COEWgVo8ZptTiS:-MfdG6COEWgVo8ZptTiT:b-us0fa6) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.h#L41)):*
> ```objc
> 
>  private:
>   OpenCensusCallTracer* tracer_;
> ```

Is this actually needed anymore?  Doesn't look like anything's going to use it.
___
*[src/cpp/ext/filters/census/client_filter.h, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdH0CwD4v6h00WYa2Y:-MfdH0CwD4v6h00WYa2Z:bdcxeqr) ([raw file](https://github.com/grpc/grpc/blob/bacf9b1281dba2dc073b9dce1e2896b2f37a8fc5/src/cpp/ext/filters/census/client_filter.h#L60)):*
> ```objc
>                          const grpc_call_element_args* args) override;
> 
>   void Destroy(grpc_call_element* elem, const grpc_call_final_info* final_info,
> ```

We should probably still have this just to keep things clean, even if destruction is a no-op at this point.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdJSFC9q2ob56bfhgr:-MfdJSFC9q2ob56bfhgs:bkmocww) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L46)):*
> ```cpp
> namespace {
> 
> void FilterTrailingMetadata(grpc_metadata_batch* b, uint64_t* elapsed_time) {
> ```

Please move this down to right above `RecordReceivedTrailingMetadata()`, since that's where it's used.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdGRRZCZafSdXoRxan:-MfdGRRZCZafSdXoRxao:b-lmurfs) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L62)):*
> ```cpp
>     grpc_call_element* /* elem */, const grpc_call_element_args* args) {
>   tracer_ = args->arena->New<OpenCensusCallTracer>(args);
>   grpc_call_context_set(
> ```

No need to use `grpc_call_context_set()` or `grpc_call_from_top_element()`.  Instead, just directly set the right entry in `args.context`.  For an example, see:

https://github.com/grpc/grpc/blob/d19802d42c0f5bef6c375756bba9a941be9c2a7a/src/core/lib/security/transport/client_auth_filter.cc#L71
___
*[src/cpp/ext/filters/census/client_filter.cc, line 112 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdOC9S0pFpIzziEh9Q:-MfdOC9S0pFpIzziEh9R:b-pjest6) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L112)):*
> ```cpp
> void OpenCensusCallTracer::OpenCensusCallAttemptTracer::RecordReceivedMessage(
>     const grpc_core::ByteStream& /* recv_message */) {
>   recv_message_count_++;
> ```

Prefer pre-increment over post-increment.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdJj3fBQ7w99ILXDjS:-MfdJj3g3hZZ8J66ZEkB:b-y2rlme) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L119)):*
> ```cpp
>         const grpc_transport_stream_stats& transport_stream_stats) {
>   FilterTrailingMetadata(recv_trailing_metadata, &elapsed_time_);
>   const uint64_t request_size = transport_stream_stats.incoming.data_bytes;
> ```

I think the rest of this code should move to `RecordEnd()`.  It seems like we want to do this on every call, but not every call will actually see trailing metadata.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdK6689bDswmZFPmUm:-MfdK6689bDswmZFPmUn:b-1o96p7) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L119)):*
> ```cpp
>         const grpc_transport_stream_stats& transport_stream_stats) {
>   FilterTrailingMetadata(recv_trailing_metadata, &elapsed_time_);
>   const uint64_t request_size = transport_stream_stats.incoming.data_bytes;
> ```

I think you have incoming and outgoing swapped here relative to the original code.  The request should be outgoing and the response should be incoming.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 163 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdNgPtDbH3PLbw-opW:-MfdNgPtDbH3PLbw-opX:b-a7ysv2) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L163)):*
> ```cpp
> 
> OpenCensusCallTracer::OpenCensusCallTracer(const grpc_call_element_args* args) {
>   path_ = grpc_slice_ref_internal(args->path);
> ```

These can all be initialized in an initializer list.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 185 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdN82D3itzqwPCTas2:-MfdN82D3itzqwPCTas3:beu1nvz) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L185)):*
> ```cpp
> OpenCensus [...]

2021-07-28 06:21 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739)* status: 1 of 7 files reviewed, 16 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 2871 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdIZJuDa5rIgRLH0L6:-MffaS_233IREcfxtOLU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/core/ext/filters/client_channel/client_channel.cc#L2871)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like I am not handling this right from my PR: This should be called only if `error == GRPC_ERROR_NONE`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 2872 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdFbh45n9AHl0e4a03:-MffaU-33N4HLduwQ5Tf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/core/ext/filters/client_channel/client_channel.cc#L2872)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please change the inline comment to say "recv_initial_metadata_flags", and then add a comment on the line above saying that these aren't used on clients, only on servers.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 2880 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdIhSf7c5qCDi6wwda:-MffaVBICG9vfbEALYfq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/core/ext/filters/client_channel/client_channel.cc#L2880)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similar to above: This should be called only if `*self->recv_message_ != nullptr`.
</blockquote></details>

Done.
___
*[src/core/lib/surface/call.cc, line 535 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdFpRW2UtpqM5duUZ3:-Mffb979AM9-qWWq-cWV:bagrtdr) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/core/lib/surface/call.cc#L535)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It might actually make more sense to put this in the `grpc_call` dtor.  I think that would be functionally equivalent to what you're doing here, so it shouldn't cause any problems, but it seems a little cleaner conceptually.
</blockquote></details>

Nice suggestion!
___
*[src/cpp/ext/filters/census/client_filter.h, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdG6COEWgVo8ZptTiS:-MffbLMv4V1pXQetdvKp:bc351rs) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.h#L41)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this actually needed anymore?  Doesn't look like anything's going to use it.
</blockquote></details>

Yeah, not needed. Thanks!
___
*[src/cpp/ext/filters/census/client_filter.h, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdH0CwD4v6h00WYa2Y:-MffbG871Con4p3uq2Qt:bm5ga5) ([raw file](https://github.com/grpc/grpc/blob/bacf9b1281dba2dc073b9dce1e2896b2f37a8fc5/src/cpp/ext/filters/census/client_filter.h#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should probably still have this just to keep things clean, even if destruction is a no-op at this point.
</blockquote></details>

Seems weird to me, but ok
___
*[src/cpp/ext/filters/census/client_filter.cc, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdJSFC9q2ob56bfhgr:-MffbS2_1E8SGq27FNt3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this down to right above `RecordReceivedTrailingMetadata()`, since that's where it's used.
</blockquote></details>

Done.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdGRRZCZafSdXoRxan:-MffbScT497oxfgS0nPV:b-8a66c6) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to use `grpc_call_context_set()` or `grpc_call_from_top_element()`.  Instead, just directly set the right entry in `args.context`.  For an example, see:

https://github.com/grpc/grpc/blob/d19802d42c0f5bef6c375756bba9a941be9c2a7a/src/core/lib/security/transport/client_auth_filter.cc#L71
</blockquote></details>

You're right. Thanks!
___
*[src/cpp/ext/filters/census/client_filter.cc, line 112 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdOC9S0pFpIzziEh9Q:-MffbV658Kb34ws9P04w:bxdg2s1) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L112)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Prefer pre-increment over post-increment.
</blockquote></details>

agreed. Done
___
*[src/cpp/ext/filters/census/client_filter.cc, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdJj3fBQ7w99ILXDjS:-MffdHqm72Zj57Gdp1ks:b-fkzcw6) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the rest of this code should move to `RecordEnd()`.  It seems like we want to do this on every call, but not every call will actually see trailing metadata.
</blockquote></details>

I don't believe that's legal, since `recv_trailing_metadata` callback is our only way of getting the status and transport stream stats.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdK6689bDswmZFPmUm:-MffkC3F827xGwKoSUqE:b4855pb) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you have incoming and outgoing swapped here relative to the original code.  The request should be outgoing and the response should be incoming.
</blockquote></details>

Thanks! Done.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 163 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdNgPtDbH3PLbw-opW:-MffkOdZ9kdQH-opSgiN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L163)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These can all be initialized in an initializer list.
</blockquote></details>

Done.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 185 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdN82D3itzqwPCTas2:-MffkUFQ1iX4e1C8TTv0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L185)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about a compromise: Allocate the first one on the arena and any subsequent ones directly.  That way, in the common case where there is no retry, there's no extra overhead, but in the case where there are retries, we don't use too much extra overhead.
</blockquote></details>

Done.
___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 36 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdLo7E0OBo7C2E5833:-MffkX159QgoD6T5bbXK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob [...]

2021-07-28 16:45 UTC, markdroth requested changes
This is getting closer!

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739#-:-Mfi-IMhBpbLqoRTPUJN:b79zqk9)* status: all files reviewed, 8 unresolved discussions (waiting on @yashykt)

___
*[src/cpp/ext/filters/census/client_filter.h, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdH0CwD4v6h00WYa2Y:-Mfho1gPBu9-O4SWqCBK:b-ota85a) ([raw file](https://github.com/grpc/grpc/blob/bacf9b1281dba2dc073b9dce1e2896b2f37a8fc5/src/cpp/ext/filters/census/client_filter.h#L60)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Seems weird to me, but ok
</blockquote></details>

Oh, wait -- nevermind, this isn't needed.

I was think that we should have method call the object's dtor as a way of future-proofing this in case someone in the future adds some data members to this class that need to be destroyed.  But I forgot that this is actually using the C++ filter API shim, which automatically calls the dtor automatically, so it doesn't need to be done here.

Sorry for the confusion.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdJj3fBQ7w99ILXDjS:-MfhoYFwCT-LeUUBONC_:b-g9zvgj) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L119)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I don't believe that's legal, since `recv_trailing_metadata` callback is our only way of getting the status and transport stream stats.
</blockquote></details>

I think we have to do this, because we need to handle the case where the application cancels the call without ever starting a recv_trailing_metadata op.  Note that in this case, the surface/call.cc code will report the call's final status as `CANCELLED`, but no transport stream stats will ever be returned.  So I don't think we need to worry about the transport stream stats in this case -- that's something we may want to fix later, but it's not a regression in this PR, so we don't need to fix it here -- but we do need to make sure that we get the correct status in this case.

Prior to this PR, the census filter would get the right call status assigned by the surface/call.cc code, because it was getting the status via `final_info` in `destroy_call_elem()`.  However, this new code is instead getting the status reported by the transport via the recv_trailing_metadata op.  So I think that what we need to do is to basically mimic what the surface/call.cc code is doing: if `RecordCancel()` is called and we don't see `RecordReceivedTrailingMetadata()`, then we should assume status `CANCELLED`.

Regardless of what status we use, though, I think we definitely need to record these stats even if we don't see recv_trailing_metadata at all.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 185 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdN82D3itzqwPCTas2:-MfhqJPT-GwqVbcBD6tx:bp7uqtj) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L185)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good.

Please replace this TODO with a comment explaining this compromise.
___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdLHMl2GJsfz0V53Cu:-MfhueKFBlCwQ-YdREj_:b-o9953v) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/open_census_call_tracer.h#L70)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> Do we need a separate context for each call attempt?
Yes we do. This will help distinguish spans of various attempts

>  Is that because the stats aggregation for each call attempt happens within the context code?
From what I'm seeing the stats aggregation is not tied to the context, but rather to the tags we provide when recording the stats.

> Do we have the right linkages in place to make the call attempts look like trace spans for the overall call?
No, I was thinking of adding that, but it seemed unnecessary. If we do that, we would have an additional layer for ALL rpcs. The other alternative where each retry attempt just gets shown to the parent of the overall call seems preferable.
</blockquote></details>

I don't understand how this is supposed to work.  If the whole point of having a separate context is to put each attempt into its own trace span, then how can we *not* make those spans look like children of the overall call?
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 421 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhyshP4w_AY3j4mAB1:-MfhyshP4w_AY3j4mAB2:b-im3wy2) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L421)):*
> ```cpp
> }
> 
> TEST_F(StatsPluginEnd2EndTest, TestRetryStatsWithoutAdditionalRetries) {
> ```

Please also have this test check that client_retry_delay_per_call is 0.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 491 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhybPS0KJnBmfVdm90:-MfhybPS0KJnBmfVdm91:b-o92k4m) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L491)):*
> ```cpp
>                 ::testing::UnorderedElementsAre(
>                     ::testing::Pair(::testing::ElementsAre(client_method_name_),
>                                     ::testing::Eq((i + 1) * 3))));
> ```

There are 3 total attempts configured, which means that there should be a maximum of 2 retries per call.  We probably need to make sure that we're not counting the first attempt as a retry.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 502 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhxGF9AmmDh88t2IAh:-MfhxGF9AmmDh88t2IAi:bzf4ldf) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L502)):*
> ```cpp
>     }
>     // We expect the retry delay to be around 100ms.
>     // TODO(roth): On some runs, the retry_filter does not invoke
> ```

The retry filter doesn't know or care about the call tracer; it's the `LoadBalancedCall` in the client channel that handles it.  There is exactly one `LoadBalancedCall` object per attempt, regardless of whether retries are enabled.  The `LoadBalancedCall` object calls `StartNewAttempt()` in its ctor and `RecordEnd()` in its dtor, so I don't see how it could possibly fail to call `RecordEnd()`.

Can you try to debug this further?  I'd be interested to know what sequence of events triggers this problem.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 509 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-Mfhz5IM7zCKi0i1s8vc:-Mfhz5IM7zCKi0i1s8vd:b-xtps7g) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L509)):*
> ```cpp
>                 ::testing::UnorderedElementsAre(::testing::Pair(
>                     ::testing::ElementsAre(client_method_name_),
>                     ::testing::AllOf(::testing::Property(
> ```

This `::testing::AllOf()` isn't needed, since it has only one argument.


<!-- Sent from Reviewable.io -->

2021-07-28 19:27 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739)* status: all files reviewed, 8 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/cpp/ext/filters/census/client_filter.cc, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdJj3fBQ7w99ILXDjS:-MfiT7CFBxdo18-yVGe7:b-irt89w) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we have to do this, because we need to handle the case where the application cancels the call without ever starting a recv_trailing_metadata op.  Note that in this case, the surface/call.cc code will report the call's final status as `CANCELLED`, but no transport stream stats will ever be returned.  So I don't think we need to worry about the transport stream stats in this case -- that's something we may want to fix later, but it's not a regression in this PR, so we don't need to fix it here -- but we do need to make sure that we get the correct status in this case.

Prior to this PR, the census filter would get the right call status assigned by the surface/call.cc code, because it was getting the status via `final_info` in `destroy_call_elem()`.  However, this new code is instead getting the status reported by the transport via the recv_trailing_metadata op.  So I think that what we need to do is to basically mimic what the surface/call.cc code is doing: if `RecordCancel()` is called and we don't see `RecordReceivedTrailingMetadata()`, then we should assume status `CANCELLED`.

Regardless of what status we use, though, I think we definitely need to record these stats even if we don't see recv_trailing_metadata at all.
</blockquote></details>

Semantics-wise, I think it is just easier to say that the trailing metadata op is necessary. Having the ability to not pass down the receive trailing metadata op does not seem to have much benefit. The alternative would reduce code complexity and I believe is preferable.

The comments agree too - 
```  /** Receive status on the client: one and only one must be made on the client.
      This operation always succeeds, meaning ops paired with this operation
      will also appear to succeed, even though they may not have. In that case
      the status will indicate some failure.
      This op completes after all activity on the call has completed. */```
https://github.com/grpc/grpc/blob/c472a2a58c18e08f8ae8e6710cb071eaf631e98c/include/grpc/impl/codegen/grpc_types.h#L610 Note that the other ops mention if the OP is optional if the call was cancelled.
```

___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdLHMl2GJsfz0V53Cu:-MfiTR7Z2rbAcr4IWK6X:b-jlr62g) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/open_census_call_tracer.h#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't understand how this is supposed to work.  If the whole point of having a separate context is to put each attempt into its own trace span, then how can we *not* make those spans look like children of the overall call?
</blockquote></details>

There is the parent call of the overall call which already has a context. If no such parent exists, we use the default context as the parent. Currently, all attempts will be treated as children of that parent.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 491 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhybPS0KJnBmfVdm90:-MfiYPhD5KMS9vmsZa_I:bv4i2gm) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L491)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There are 3 total attempts configured, which means that there should be a maximum of 2 retries per call.  We probably need to make sure that we're not counting the first attempt as a retry.
</blockquote></details>

It won't be 0 since there would be some delay when the overall call is started and when the first attempt is started. I'll add a reasonable bound - 100ms
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 502 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhxGF9AmmDh88t2IAh:-MfiVnb0-ETsJhrx2LQS:bjo08cw) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L502)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The retry filter doesn't know or care about the call tracer; it's the `LoadBalancedCall` in the client channel that handles it.  There is exactly one `LoadBalancedCall` object per attempt, regardless of whether retries are enabled.  The `LoadBalancedCall` object calls `StartNewAttempt()` in its ctor and `RecordEnd()` in its dtor, so I don't see how it could possibly fail to call `RecordEnd()`.

Can you try to debug this further?  I'd be interested to know what sequence of events triggers this problem.
</blockquote></details>

It is definitely calling `RecordEnd()`. From what I saw, `RecordEnd()` was invoked on the first attempt after the next attempt already began and so the calculation for `retry_delay_per_call` got messed up. I can debug further, but I don't want to block this PR for that.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 509 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-Mfhz5IM7zCKi0i1s8vc:-MfiWCzvABdZFS45vcok:b-oroyox) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L509)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This `::testing::AllOf()` isn't needed, since it has only one argument.
</blockquote></details>

Not right now, but it would be needed after the above "bug" is fixed


<!-- Sent from Reviewable.io -->

2021-07-28 19:27 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739)* status: 3 of 7 files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[src/cpp/ext/filters/census/client_filter.h, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdH0CwD4v6h00WYa2Y:-Mfi_Ss94pEDHJ94eGtu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/bacf9b1281dba2dc073b9dce1e2896b2f37a8fc5/src/cpp/ext/filters/census/client_filter.h#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Oh, wait -- nevermind, this isn't needed.

I was think that we should have method call the object's dtor as a way of future-proofing this in case someone in the future adds some data members to this class that need to be destroyed.  But I forgot that this is actually using the C++ filter API shim, which automatically calls the dtor automatically, so it doesn't need to be done here.

Sorry for the confusion.
</blockquote></details>

Done.
___
*[src/cpp/ext/filters/census/client_filter.cc, line 185 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdN82D3itzqwPCTas2:-Mfi_Us51LYAlt_oJlnt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L185)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks good.

Please replace this TODO with a comment explaining this compromise.
</blockquote></details>

Done.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 421 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhyshP4w_AY3j4mAB1:-Mfi_Xtk7Qp-vfHr7o6d:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L421)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please also have this test check that client_retry_delay_per_call is 0.
</blockquote></details>

Done.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 491 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhybPS0KJnBmfVdm90:-Mfi_Yqx1982exygDeTm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L491)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

It won't be 0 since there would be some delay when the overall call is started and when the first attempt is started. I'll add a reasonable bound - 100ms
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 20:05 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739)* status: 3 of 7 files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[src/cpp/ext/filters/census/client_filter.cc, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdJj3fBQ7w99ILXDjS:-Mfii4Iz5ivNzToEflVh:b-6qw3hi) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L119)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Semantics-wise, I think it is just easier to say that the trailing metadata op is necessary. Having the ability to not pass down the receive trailing metadata op does not seem to have much benefit. The alternative would reduce code complexity and I believe is preferable.

The comments agree too - 
```  /** Receive status on the client: one and only one must be made on the client.
      This operation always succeeds, meaning ops paired with this operation
      will also appear to succeed, even though they may not have. In that case
      the status will indicate some failure.
      This op completes after all activity on the call has completed. */```
https://github.com/grpc/grpc/blob/c472a2a58c18e08f8ae8e6710cb071eaf631e98c/include/grpc/impl/codegen/grpc_types.h#L610 Note that the other ops mention if the OP is optional if the call was cancelled.
</blockquote></details>

```
 /** Receive status on the client: one and only one must be made on the client.
      This operation always succeeds, meaning ops paired with this operation
      will also appear to succeed, even though they may not have. In that case
      the status will indicate some failure.
      This op completes after all activity on the call has completed. */
```


<!-- Sent from Reviewable.io -->

2021-07-28 22:29 UTC, markdroth requested changes
Still a couple of issues left to resolve.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739#-:-MfjE0w51IaAmxQB322m:b-gg9wbu)* status: all files reviewed, 6 unresolved discussions (waiting on @yashykt)

___
*[src/cpp/ext/filters/census/client_filter.cc, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdJj3fBQ7w99ILXDjS:-Mfj9DR3BDdtOMgj67ns:bqfz6ci) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L119)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

```
 /** Receive status on the client: one and only one must be made on the client.
      This operation always succeeds, meaning ops paired with this operation
      will also appear to succeed, even though they may not have. In that case
      the status will indicate some failure.
      This op completes after all activity on the call has completed. */
```

</blockquote></details>

I suspect that that comment is not accurate.  I don't think the C-core API actually requires that recv_trailing_metadata be started if the call is cancelled.  I would be willing to bet that if we tried to change this, we would break a lot of things.

Even if we decide we want to change the semantic this way, I don't think this is something we're going to be able to do quickly.  I think it would be far safer to change this PR as I suggested.
___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdLHMl2GJsfz0V53Cu:-MfjB-OBAQ4HJrm9v3Kf:brk27p6) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/open_census_call_tracer.h#L70)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

There is the parent call of the overall call which already has a context. If no such parent exists, we use the default context as the parent. Currently, all attempts will be treated as children of that parent.
</blockquote></details>

Then won't that make all of the call attempts look like child spans of the overall call?  Earlier you said you didn't implement that, but now it sounds like you did.  I'm confused as to what the intent is here.

Let me ask this question a different way: I see that we are generating spans associated with the context in each attempt.  How are those spans being linked to the context in the overall call?  I don't see any code that ties them together.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 502 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhxGF9AmmDh88t2IAh:-MfjBxAM9hraBTnENPPx:b-ultbx0) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L502)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

It is definitely calling `RecordEnd()`. From what I saw, `RecordEnd()` was invoked on the first attempt after the next attempt already began and so the calculation for `retry_delay_per_call` got messed up. I can debug further, but I don't want to block this PR for that.
</blockquote></details>

Ah, okay -- you're saying that it's just an ordering problem.

I don't think it's surprising for one attempt to not be destroyed until after a subsequent attempt has started, since there can be lingering callbacks on the earlier attempt that haven't completed yet even after we decide to retry it.  And since this test sets the initial backoff to 0.1s, you may be seeing that more here than would be typically seen with the default values.

I don't think there's anything to investigate here; you just need to fix the test to be a little more permissive.  It might also help to increase the initial backoff value in the service config.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 509 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-Mfhz5IM7zCKi0i1s8vc:-MfjCqi57Mye3GC1JFId:bc2wumz) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L509)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Not right now, but it would be needed after the above "bug" is fixed
</blockquote></details>

What additional matcher will be added here?

Note that there are two calls to `::testing::AllOf()` in this expression.  I am not objecting to the second one (the one that will eventually wrap `::testing::Ge()` and `::testing::Le()`); I am objecting to the one that wraps only `::testing::Property()`.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 447 at r3](https://reviewable.io/reviews/grpc/grpc/26739#-MfjBaD-DjBOD_maI44T:-MfjBaD03UJVtrjtUHaD:braq7v8) ([raw file](https://github.com/grpc/grpc/blob/dc7d62006a6e4fa4ad734532e1bfd98209a44328/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L447)):*
> ```cpp
>         ::testing::UnorderedElementsAre(::testing::Pair(
>             ::testing::ElementsAre(client_method_name_), ::testing::Eq(0))));
>     // There is some delay between the start of the overall call and the start
> ```

This is supposed to be retry overhead only, not overhead for things like name resolution and load balancing.  I think this should not count any time that elapses before the first call attempt is started.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 452 at r3](https://reviewable.io/reviews/grpc/grpc/26739#-MfjDnE2ABbTAHBv0qQV:-MfjDnE2ABbTAHBv0qQW:bfvudwc) ([raw file](https://github.com/grpc/grpc/blob/dc7d62006a6e4fa4ad734532e1bfd98209a44328/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L452)):*
> ```cpp
>                 ::testing::UnorderedElementsAre(::testing::Pair(
>                     ::testing::ElementsAre(client_method_name_),
>                     ::testing::AllOf(::testing::Property(
> ```

No need for `::testing::AllOf()` here.


<!-- Sent from Reviewable.io -->

2021-07-28 23:50 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/cpp/ext/filters/census/client_filter.cc, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdJj3fBQ7w99ILXDjS:-MfjWALU-_6L15du42Fv:b-fm8qac) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/client_filter.cc#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suspect that that comment is not accurate.  I don't think the C-core API actually requires that recv_trailing_metadata be started if the call is cancelled.  I would be willing to bet that if we tried to change this, we would break a lot of things.

Even if we decide we want to change the semantic this way, I don't think this is something we're going to be able to do quickly.  I think it would be far safer to change this PR as I suggested.
</blockquote></details>

As discussed, I'll test out what we discussed. In the mean time, I've made the change anyway to unblock this PR
___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdLHMl2GJsfz0V53Cu:-MfjNCwC6mhuIG2ogx6O:b-dss06h) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/open_census_call_tracer.h#L70)):*
> Then won't that make all of the call attempts look like child spans of the overall call?

No context is being created for the overall call, so that won't happen

> Let me ask this question a different way: I see that we are generating spans associated with the context in each attempt. How are those spans being linked to the context in the overall call? I don't see any code that ties them together.

They aren't right now. 
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 502 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhxGF9AmmDh88t2IAh:-MfjNf_r7EHUAuosRWS9:b-u0ocad) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L502)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ah, okay -- you're saying that it's just an ordering problem.

I don't think it's surprising for one attempt to not be destroyed until after a subsequent attempt has started, since there can be lingering callbacks on the earlier attempt that haven't completed yet even after we decide to retry it.  And since this test sets the initial backoff to 0.1s, you may be seeing that more here than would be typically seen with the default values.

I don't think there's anything to investigate here; you just need to fix the test to be a little more permissive.  It might also help to increase the initial backoff value in the service config.
</blockquote></details>

That's the thing. I increased the backoff to a few seconds and it still did not invoke `RecordEnd` before the new attempt started. There definitely seems to be unintentional delaying over here
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 509 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-Mfhz5IM7zCKi0i1s8vc:-MfjWS8S1RLUUjMAT6yI:b-chij37) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L509)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What additional matcher will be added here?

Note that there are two calls to `::testing::AllOf()` in this expression.  I am not objecting to the second one (the one that will eventually wrap `::testing::Ge()` and `::testing::Le()`); I am objecting to the one that wraps only `::testing::Property()`.
</blockquote></details>

Ah ok. Done!
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 447 at r3](https://reviewable.io/reviews/grpc/grpc/26739#-MfjBaD-DjBOD_maI44T:-MfjWOt8C1-FRnGS48wR:b-886gsx) ([raw file](https://github.com/grpc/grpc/blob/dc7d62006a6e4fa4ad734532e1bfd98209a44328/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L447)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is supposed to be retry overhead only, not overhead for things like name resolution and load balancing.  I think this should not count any time that elapses before the first call attempt is started.
</blockquote></details>

Fixed
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 452 at r3](https://reviewable.io/reviews/grpc/grpc/26739#-MfjDnE2ABbTAHBv0qQV:-MfjWPtFCD9eSrS176nn:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/dc7d62006a6e4fa4ad734532e1bfd98209a44328/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L452)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `::testing::AllOf()` here.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-07-29 23:15 UTC, markdroth requested changes
Just a couple of issues remaining.

I'll look into the delay problem tomorrow.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 3 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739#-:-MfoYEUh4taSpBgVJ75W:b-b1x2nr)* status: all files reviewed, 2 unresolved discussions (waiting on @yashykt)

___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdLHMl2GJsfz0V53Cu:-MfoXnklC6gj_M7xyISj:b-oxn73c) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/open_census_call_tracer.h#L70)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> Then won't that make all of the call attempts look like child spans of the overall call?

No context is being created for the overall call, so that won't happen

> Let me ask this question a different way: I see that we are generating spans associated with the context in each attempt. How are those spans being linked to the context in the overall call? I don't see any code that ties them together.

They aren't right now. 
</blockquote></details>

How can we not create a context for the overall call?  Wasn't that being done before this PR?
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 502 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhxGF9AmmDh88t2IAh:-MfoXyyVERht6lFkra1W:b-56p6ke) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L502)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

That's the thing. I increased the backoff to a few seconds and it still did not invoke `RecordEnd` before the new attempt started. There definitely seems to be unintentional delaying over here
</blockquote></details>

That does seem very surprising.  I'll try to look at this tomorrow.


<!-- Sent from Reviewable.io -->

2021-07-30 19:36 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739)* status: all files reviewed, 2 unresolved discussions (waiting on @yashykt)

___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 502 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhxGF9AmmDh88t2IAh:-MfsueEm8LC8z-lKJA7W:bysp7y3) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L502)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That does seem very surprising.  I'll try to look at this tomorrow.
</blockquote></details>

I just sent you #26847 to fix this.


<!-- Sent from Reviewable.io -->

2021-07-30 21:17 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/cpp/ext/filters/census/open_census_call_tracer.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/26739#-MfdLHMl2GJsfz0V53Cu:-MftGlFWBB6n0-FuIioq:bydn7cf) ([raw file](https://github.com/grpc/grpc/blob/a87d3fee1c787177c85699ea0ed83b102e4fb074/src/cpp/ext/filters/census/open_census_call_tracer.h#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How can we not create a context for the overall call?  Wasn't that being done before this PR?
</blockquote></details>

Added as discussed on chat
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 502 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhxGF9AmmDh88t2IAh:-MftGn0AAOMuTuTktRo4:b-ekl8jy) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L502)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I just sent you #26847 to fix this.
</blockquote></details>

Thanks! I'll remove the TODO and fix the test once that PR gets merged


<!-- Sent from Reviewable.io -->

2021-08-02 16:42 UTC, markdroth requested changes
Only a few minor comments remaining!  Hopefully we can get this merged today.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739#-:-Mg6jbxC8Hv4I3oxYP9R:b-dpa1py)* status: all files reviewed, 3 unresolved discussions (waiting on @yashykt)

___
*[src/cpp/ext/filters/census/client_filter.cc, line 188 at r6](https://reviewable.io/reviews/grpc/grpc/26739#-Mg6faRvBbP6CO3R8PIc:-Mg6faRw8m0MQe07nt0C:b-n7c0sn) ([raw file](https://github.com/grpc/grpc/blob/0faff66568942cd7c233c4eefed9220570275e45/src/cpp/ext/filters/census/client_filter.cc#L188)):*
> ```cpp
>       context_.tags().tags();
>   tags.emplace_back(ClientMethodTagKey(), std::string(method_));
> ```

Please remove unnecessary blank line.
___
*[src/cpp/ext/filters/census/context.cc, line 55 at r6](https://reviewable.io/reviews/grpc/grpc/26739#-Mg6i_zu8R4ulS6J7lAc:-Mg6i_zu8R4ulS6J7lAd:bscxous) ([raw file](https://github.com/grpc/grpc/blob/0faff66568942cd7c233c4eefed9220570275e45/src/cpp/ext/filters/census/context.cc#L55)):*
> ```cpp
>     Span span = parent_ctxt->Span();
>     if (span_ctxt.IsValid()) {
>       new (ctxt) CensusContext(method, &span, parent_ctxt->tags());
> ```

This doesn't look right.  Why do we want to inherit all of the tags from the parent context?  That definitely seems wrong for the overall call context, and I'm not even sure it's right for the per-attempt contexts.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 502 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhxGF9AmmDh88t2IAh:-Mg6jYST7w8yIe_jUOs1:b2aodm9) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L502)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Thanks! I'll remove the TODO and fix the test once that PR gets merged
</blockquote></details>

It's been merged, so you should be good to make the changes here now.


<!-- Sent from Reviewable.io -->

2021-08-02 17:21 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/cpp/ext/filters/census/context.cc, line 55 at r6](https://reviewable.io/reviews/grpc/grpc/26739#-Mg6i_zu8R4ulS6J7lAc:-Mg6pbezE6QVR5bOYfwO:b-99bwm) ([raw file](https://github.com/grpc/grpc/blob/0faff66568942cd7c233c4eefed9220570275e45/src/cpp/ext/filters/census/context.cc#L55)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't look right.  Why do we want to inherit all of the tags from the parent context?  That definitely seems wrong for the overall call context, and I'm not even sure it's right for the per-attempt contexts.
</blockquote></details>

This was needed for the per-attempt contexts since we actually have a test `ErrorCount` in `grpc_opencensus_plugin_test` that makes sure that the tags are propagated.

If you look at line 63, you'll notice that the existing code already tries to propagate the tags from the per-thread CensusContext object. It seems to me that we do want to propagate these tags.

Why do we not want it for the overall call context?
Based on my reading at https://g3doc.corp.google.com/stats/census/g3doc/howto.md?cl=head#tags, it seems that propagating tags is desired.


<!-- Sent from Reviewable.io -->

2021-08-02 18:25 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/cpp/ext/filters/census/client_filter.cc, line 188 at r6](https://reviewable.io/reviews/grpc/grpc/26739#-Mg6faRvBbP6CO3R8PIc:-Mg763H5Eg9O4fS-GWiV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0faff66568942cd7c233c4eefed9220570275e45/src/cpp/ext/filters/census/client_filter.cc#L188)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove unnecessary blank line.
</blockquote></details>

Done.
___
*[src/cpp/ext/filters/census/context.cc, line 55 at r6](https://reviewable.io/reviews/grpc/grpc/26739#-Mg6i_zu8R4ulS6J7lAc:-Mg76Fxw07BqTqRjENFv:bn8z72w) ([raw file](https://github.com/grpc/grpc/blob/0faff66568942cd7c233c4eefed9220570275e45/src/cpp/ext/filters/census/context.cc#L55)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

This was needed for the per-attempt contexts since we actually have a test `ErrorCount` in `grpc_opencensus_plugin_test` that makes sure that the tags are propagated.

If you look at line 63, you'll notice that the existing code already tries to propagate the tags from the per-thread CensusContext object. It seems to me that we do want to propagate these tags.

Why do we not want it for the overall call context?
Based on my reading at https://g3doc.corp.google.com/stats/census/g3doc/howto.md?cl=head#tags, it seems that propagating tags is desired.
</blockquote></details>

Changed it such that we only propagate the tags for call attempts.
___
*[test/cpp/ext/filters/census/stats_plugin_end2end_test.cc, line 502 at r2](https://reviewable.io/reviews/grpc/grpc/26739#-MfhxGF9AmmDh88t2IAh:-Mg75yluBKnCA0I-MyYQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/be7c4360a67a4a366a0c6fe7947b5e6c297f9f4c/test/cpp/ext/filters/census/stats_plugin_end2end_test.cc#L502)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's been merged, so you should be good to make the changes here now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-02 18:26 UTC, markdroth approved these changes
This looks great!  Thanks for doing it!

> Reviewed 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26739#-:-Mg76RWF5-R2z0wASrGN:b-2a5bno)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yashykt)



<!-- Sent from Reviewable.io -->

2021-08-02 21:00 UTC, yashykt commented
Known issues: #26595

2021-08-02 21:00 UTC, merged