Add BinderTransport example app
grpc/grpc pull request #26747
Opened 2021-07-21 11:36 UTC by sifmelcara

This commit adds an app that will be served as BinderTransport example
later.

Currently the app simply calls C++ function when button is pressed. In
the future the C++ function will run BinderTransport gRPC example
instead.

Tests not included in this commit, later we will add a build test to
CI to make sure this apk is always build-able. (This app will also be used to make sure our BinderTransport implementation is compile-able with Android toolchain, on GitHub)

Changes are made to WORKSPACE file in order to support android builds.

Build instructions are documented at
examples/android/binder/java/io/grpc/binder/cpp/example/README.md

@nicolasnoble
@markdroth 
@TaWeiTu 
@napathome

2021-07-21 16:56 UTC, sifmelcara commented
Force pushed. Excluding this target in basic build test

2021-07-21 17:04 UTC, sifmelcara commented
I think we will want to have a separate non-blocking build test for our Android apk target. What do you guys think?

2021-07-26 12:40 UTC, sifmelcara commented
"Interop Cloud-to-Prod Tests (internal CI)" is a known CI failure #26595

2021-07-26 12:41 UTC, sifmelcara commented
TaWei can you help give a review and see if we can proceed to merge this?

2021-07-26 13:34 UTC, TaWeiTu requested changes
Overall looks good as long as it doesn't break CI and the build system.

2021-07-26 13:34 UTC, TaWeiTu commented on examples/android/binder/java/io/grpc/binder/cpp/example/README.md
> +1. Install Android SDK and NDK. Currently we only support Sdk version 30.0.3 and
Sdk -> SDK?

2021-07-26 13:34 UTC, TaWeiTu commented on examples/android/binder/java/io/grpc/binder/cpp/example/README.md
> +2. Point environment variables to install locations of Sdk and NDK
Ditto

2021-07-26 13:34 UTC, TaWeiTu commented on examples/android/binder/java/io/grpc/binder/cpp/example/native.cc
> +Java_io_grpc_binder_cpp_example_ButtonPressHandler_native_1entry(
Not familiar with Java JNI, but is this a typo? (`native_1entry` -> `native_entry`)

2021-07-26 13:39 UTC, TaWeiTu commented on examples/android/binder/java/io/grpc/binder/cpp/example/native.cc
> +Java_io_grpc_binder_cpp_example_ButtonPressHandler_native_1entry(
Oh my bad, underscore in function name should be followed by a 1.

2021-07-26 14:01 UTC, sifmelcara commented
> Overall looks good as long as it doesn't break CI and the build system.

Yeah all CI tasks passed except the one I mentioned in https://github.com/grpc/grpc/pull/26747#issuecomment-886666794

2021-07-26 14:08 UTC, TaWeiTu approved these changes
LGTM.

Since this PR also changes the `WORKSPACE` file, have you discussed with @nicolasnoble whether this is OK for us to merge this without his review?

2021-07-27 01:06 UTC, sifmelcara commented
We briefly discussed this PR in chat. I think it is ok to merge as long as it passes CI.

Several CI checks looks flaky though, let me force-push to trigger rerun again to see if they pass or not

2021-07-27 03:18 UTC, sifmelcara commented
Looks like `Basic Tests C# Windows` and `Basic Tests Python Linux` still timeouts. Since I have seen them passed in this pull request in previous run, let's assume it is not related to this change.

2021-07-27 03:18 UTC, merged