Implement TraceFlag.Log and TraceFlag.IfEnabled
grpc/grpc pull request #26954
Opened 2021-08-10 01:32 UTC by drfloob

Motivation: In debug builds, `DebugOnlyTraceFlag`s are hard-coded to be
disabled. This results in unreachable code paths that the compiler can
detect, which prevent us from enabling `-Wunreachable-code-aggressive`
on our builds.

This work aims to reduce the number of places that switch on
`trace_flag.enabled`.

2021-08-10 02:07 UTC, drfloob reviewed
@markdroth This is a draft of the trace flag changes we were chatting about today. Migrating the `DebugOnlyTraceFlag` uses at the moment, there are 4 spots that are not immediately straightforward to solve without changing some of the tracing logic, paying some added costs when not tracing, or adding something of a `TraceFlag.Exec` method for callables to do custom things if tracing is enabled.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-MghlBiw5LV8pr9DziR0:b-rzaieu)* status: 0 of 38 files reviewed, 5 unresolved discussions (waiting on @drfloob)

___
*[src/core/lib/debug/trace.h, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-MghljM72CMQE71k44sG:-MghljM72CMQE71k44sH:b-20oyln) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/debug/trace.h#L94)):*
> ```objc
>   //   /// Executes \a fn if the trace is enabled.
>   //   template <typename F>
>   //   void TraceIfEnabled(F fn) {
> ```

I would rename this `TraceFlag.Exec`.
___
*[src/core/lib/debug/trace.h, line 105 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-MghnYHK1XilKIEQncVE:-MghnYHK1XilKIEQncVF:bq16bi8) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/debug/trace.h#L105)):*
> ```objc
> 
>   template <typename T>
>   T IfEnabled(T arg_true, T arg_false) {
> ```

Taking args by copy is probably never what we want here. I need to refresh my memory on template design, but I'm pushing out this draft PR for feedback on the `DO NOT SUBMIT` pieces.
___
*[src/core/lib/iomgr/executor/mpmcqueue.cc, line 36 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-MghirPV5qr9h-VegJCZ:-MghirPV5qr9h-VegJC_:b-kb1rca) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/iomgr/executor/mpmcqueue.cc#L36)):*
> ```cpp
>   // Updates Stats when trace flag turned on.
>   // DO NOT SUBMIT(hork): trace.exec(callable) or skip warning
>   if (GRPC_TRACE_FLAG_ENABLED(grpc_thread_pool_trace)) {
> ```

@markdroth It's a bit more complicated to remove the `trace.enabled()` call here due to the metrics calculations that only happen when tracing (same for the others in this file). I don't think we want to pay the cost of metrics calculations when not tracing. In this case, the `TraceFlag.exec(callable)` would be a clean solution. Alternative, we could find a cross-platform way to ignore the unreachable code warnings for this file, but I don't believe we have that yet - it'll take a few different kinds of pragma definitions I believe, not as simple as `NOLINT`.
___
*[src/core/lib/surface/completion_queue.cc, line 1220 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-Mghk6Yc0TUdlj0RudRK:-Mghk6Yc0TUdlj0RudRL:bgy0sl0) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/surface/completion_queue.cc#L1220)):*
> ```cpp
> 
>   // DO NOT SUBMIT(hork): trace.exec(callable) or skip warning
>   if (GRPC_TRACE_FLAG_ENABLED(grpc_cq_pluck_trace)) {
> ```

If we unroll the `GRPC_API_TRACE` logic here, this amounts to checking if both `grpc_cq_pluck_trace` and `grpc_api_trace` are enabled. Would consider the lambda approach here as well. Something like:

```
grpc_cq_pluck_trace.Exec([&]() {
  GRPC_API_TRACE(<all the things>);
});
```
___
*[src/core/lib/transport/metadata.cc, line 67 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-Mghi5io6hJtYkAvGsaD:-Mghi5io6hJtYkAvGsaE:bazwzor) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/transport/metadata.cc#L67)):*
> ```cpp
>                            const grpc_slice& value, intptr_t refcnt,
>                            const char* file, int line) {
>   // DO NOT SUBMIT(hork): trace.exec(callable) or skip warning
> ```

@markdroth In this file, we can remove the `*.enabled()` calls if we pay the price of generating log strings that may not get used. It'd look something like:

```
    char* key_str = grpc_slice_to_c_string(key);
    char* value_str = grpc_slice_to_c_string(value);
    grpc_trace_metadata.log(file, line, GPR_LOG_SEVERITY_DEBUG,
            "mdelem   REF:%p:%" PRIdPTR "->%" PRIdPTR ": '%s' = '%s'", md,
            refcnt, refcnt + 1, key_str, value_str);
    gpr_free(key_str);
    gpr_free(value_str);
```


<!-- Sent from Reviewable.io -->

2021-08-10 05:00 UTC, ctiller reviewed
> Reviewed 10 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954)* status: 10 of 38 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/transport/metadata.cc, line 67 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-Mghi5io6hJtYkAvGsaD:-MgiPvZR3Fdp-4A4xvRG:b-mf7vnw) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/transport/metadata.cc#L67)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

@markdroth In this file, we can remove the `*.enabled()` calls if we pay the price of generating log strings that may not get used. It'd look something like:

```
    char* key_str = grpc_slice_to_c_string(key);
    char* value_str = grpc_slice_to_c_string(value);
    grpc_trace_metadata.log(file, line, GPR_LOG_SEVERITY_DEBUG,
            "mdelem   REF:%p:%" PRIdPTR "->%" PRIdPTR ": '%s' = '%s'", md,
            refcnt, refcnt + 1, key_str, value_str);
    gpr_free(key_str);
    gpr_free(value_str);
```
</blockquote></details>

The overhead of generating these strings if they're not used here would be unacceptable.


<!-- Sent from Reviewable.io -->

2021-08-10 16:26 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954)* status: 10 of 38 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/transport/metadata.cc, line 67 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-Mghi5io6hJtYkAvGsaD:-MgkjxSGDJTTUr4JZmi5:b-5sbk46) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/transport/metadata.cc#L67)):*
<details><summary><i>Previously, ctiller (Craig Tiller) wrote…</i></summary><blockquote>

The overhead of generating these strings if they're not used here would be unacceptable.
</blockquote></details>

I believe that. For context, Mark had requested I try to avoid adding the `Trace.Exec()` to the trace flag API. In this case, that leaves us with the option to add some warning-disabling macros around `_Pragma` to use the code as is, or change what we log. Do you have a preference, or alternative suggestion here?


<!-- Sent from Reviewable.io -->

2021-08-10 16:42 UTC, markdroth reviewed
Overall, this looks good.

I think we can handle the cases where we do more than just logging by using `#ifndef NDEBUG` in the calling code.

Please let me know if you have any questions.  Thanks!

> Reviewed 37 of 38 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-Mgkq3_mEGPppUVGbfPc:bvuc20a)* status: all files reviewed, 19 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/lib/debug/trace.h, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-MghljM72CMQE71k44sG:-MgknhP16OeYobIY1foJ:b-bacmkl) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/debug/trace.h#L94)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

I would rename this `TraceFlag.Exec`.
</blockquote></details>

I don't think this is needed.  We can handle these cases with `#ifndef NDEBUG` instead.
___
*[src/core/lib/debug/trace.h, line 105 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-MghnYHK1XilKIEQncVE:-MgkaLnt34XH16t7uOVG:b-ljhqwm) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/debug/trace.h#L105)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Taking args by copy is probably never what we want here. I need to refresh my memory on template design, but I'm pushing out this draft PR for feedback on the `DO NOT SUBMIT` pieces.
</blockquote></details>

Maybe change the parameters and the return type to references to avoid the copy?

Note that this problem goes away if we have only a `const char*` variant.
___
*[src/core/lib/debug/trace.h, line 104 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkpaprEGH-XkxLk1Tl:-Mgkpaps926vhr2O41CH:btp4l32) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/debug/trace.h#L104)):*
> ```objc
>   //   }
> 
>   template <typename T>
> ```

Do we need to use a template here?  It looks like we basically only ever use this with `const char*` arguments.  Couldn't we just provide that variant for now, and add others later if/when they become needed?
___
*[src/core/lib/debug/trace.h, line 106 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkbRxeEyp5F_zDKMAA:-MgkbRxfBbWnMzJKSIXi:bx1zeqh) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/debug/trace.h#L106)):*
> ```objc
>   template <typename T>
>   T IfEnabled(T arg_true, T arg_false) {
>     return enabled() ? arg_true : arg_false;
> ```

This should use `GPR_UNLIKELY()`.
___
*[src/core/lib/debug/trace.h, line 114 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkalKo6LYYWDzgOKIt:-MgkalKo6LYYWDzgOKIu:brhv2b7) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/debug/trace.h#L114)):*
> ```objc
>   }
> 
>   void log(const char* file, int line, gpr_log_severity severity,
> ```

Please call this `Log()` (capital "L").
___
*[src/core/lib/debug/trace.h, line 116 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkcU0y0K1K8j1ovLIH:-MgkcU0z3uKRmSM0FRzV:b-t77pod) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/debug/trace.h#L116)):*
> ```objc
>   void log(const char* file, int line, gpr_log_severity severity,
>            const char* format, ...) {
>     if (enabled()) {
> ```

This also needs `GPR_UNLIKELY()`.
___
*[src/core/lib/debug/trace.h, line 162 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-Mgkbm2vB0omBW6T0ViA:-Mgkbm2vB0omBW6T0ViB:biovdr1) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/debug/trace.h#L162)):*
> ```objc
>   template <typename T>
>   constexpr T* const IfEnabled(T*, std::nullptr_t) {
>     return static_cast<T*>(nullptr);
> ```

I don't think this `static_cast<>` is needed.
___
*[src/core/lib/gpr/log_internal.h, line 23 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-Mgkb1Py5bO5V-H9TYhk:-Mgkb1Py5bO5V-H9TYhl:b27zndx) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/gpr/log_internal.h#L23)):*
> ```objc
> /// Log a message, accepting a variadic argument list. See also \a gpr_log.
> // TODO(hork): look into vprintf format checking
> void vgpr_log(const char* file, int line, gpr_log_severity severity,
> ```

This needs to start with a `gpr_` prefix to avoid polluting the global C symbol namespace, so it should be called `gpr_vlog()`.
___
*[src/core/lib/iomgr/error.cc, line 311 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-Mgkd3qN73AC5d6NxDXu:-Mgkd3qN73AC5d6NxDXv:b-x46go5) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/iomgr/error.cc#L311)):*
> ```cpp
>     *err = static_cast<grpc_error_handle>(gpr_realloc(
>         *err, sizeof(grpc_error) + (*err)->arena_capacity * sizeof(intptr_t)));
> #ifndef NDEBUG
> ```

I suspect that unconditionally checking `if (*err != orig)` isn't going to be a lot of overhead, so we could probably dispense with this `#ifndef NDEBUG`.
___
*[src/core/lib/iomgr/error.cc, line 515 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-Mgkddyx5JamL2vfWh3e:-Mgkddyx5JamL2vfWh3f:bdjc8p) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/iomgr/error.cc#L515)):*
> ```cpp
>     out = static_cast<grpc_error_handle>(
>         gpr_malloc(sizeof(*in) + new_arena_capacity * sizeof(intptr_t)));
> #ifndef NDEBUG
> ```

This `#ifndef NDEBUG` isn't needed.
___
*[src/core/lib/iomgr/ev_epollex_linux.cc, line 174 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-Mgke41C6jDdG3v4Ekqf:-Mgke41C6jDdG3v4Ekqg:b-telfzz) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/iomgr/ev_epollex_linux.cc#L174)):*
> ```cpp
>     std::string fd_name = absl::StrCat(name, " fd=", fd);
>     grpc_iomgr_register_object(&iomgr_object, fd_name.c_str());
> #ifndef NDEBUG
> ```

No need for this `#ifndef NDEBUG`.
___
*[src/core/lib/iomgr/executor/mpmcqueue.cc, line 36 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-MghirPV5qr9h-VegJCZ:-MgknIAA5EBz1ACHaHGi:b-8zdrhx) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/iomgr/executor/mpmcqueue.cc#L36)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

@markdroth It's a bit more complicated to remove the `trace.enabled()` call here due to the metrics calculations that only happen when tracing (same for the others in this file). I don't think we want to pay the cost of metrics calculations when not tracing. In this case, the `TraceFlag.exec(callable)` would be a clean solution. Alternative, we could find a cross-platform way to ignore the unreachable code warnings for this file, but I don't believe we have that yet - it'll take a few different kinds of pragma definitions I believe, not as simple as `NOLINT`.
</blockquote></details>

These cases can probably be wrapped in `#ifndef NDEBUG`.
___
*[src/core/lib/security/context/security_context.h, line 30 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkeiUN92IdqW2gtzGb:-MgkeiUOAIR3-WqFmKUS:bqm7fm0) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/security/context/security_context.h#L30)):*
> ```objc
> #include "src/core/lib/security/credentials/credentials.h"
> 
> extern grpc_core::TraceFlag grpc_trace_auth_context_refcount;
> ```

Why this change?  We do want ref-count tracers to be debug-only.
___
*[src/core/lib/surface/completion_queue.cc, line 1220 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-Mghk6Yc0TUdlj0RudRK:-MgkmHCxBUo--mmrGYrw:b-5lrxp0) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/surface/completion_queue.cc#L1220)):*
<d [...]

2021-08-10 18:19 UTC, drfloob reviewed
Thanks Mark! Good point, I've wrapped the small handful of problematic cases in `NDEBUG` guards. PTAL.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-MglHXzk4IdSRTp9xI-R:b-kjoav0)* status: all files reviewed, 19 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/debug/trace.h, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-MghljM72CMQE71k44sG:-MgkyUlr1lSpFaHE8Kky:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/debug/trace.h#L94)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is needed.  We can handle these cases with `#ifndef NDEBUG` instead.
</blockquote></details>

Removed.
___
*[src/core/lib/debug/trace.h, line 105 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-MghnYHK1XilKIEQncVE:-Mgl-LaU6ZqVIEIBZ0Da:bxn4uxe) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/debug/trace.h#L105)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Maybe change the parameters and the return type to references to avoid the copy?

Note that this problem goes away if we have only a `const char*` variant.
</blockquote></details>

Problem avoided w/ the `const char*` version.
___
*[src/core/lib/debug/trace.h, line 104 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkpaprEGH-XkxLk1Tl:-MgkyW1PDs9vxGrigMlq:bquuxn8) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/debug/trace.h#L104)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Do we need to use a template here?  It looks like we basically only ever use this with `const char*` arguments.  Couldn't we just provide that variant for now, and add others later if/when they become needed?
</blockquote></details>

SGTM, done. Today, we only need the `const char*` flavor. This method is only used in constructors for various `RefCount` types.
___
*[src/core/lib/debug/trace.h, line 106 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkbRxeEyp5F_zDKMAA:-Mgl-Xrw15QC96aOnDR-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/debug/trace.h#L106)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should use `GPR_UNLIKELY()`.
</blockquote></details>

Done.
___
*[src/core/lib/debug/trace.h, line 114 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkalKo6LYYWDzgOKIt:-Mgl2al54AX3W8bCmBPq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/debug/trace.h#L114)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `Log()` (capital "L").
</blockquote></details>

Done.
___
*[src/core/lib/debug/trace.h, line 116 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkcU0y0K1K8j1ovLIH:-Mgl2eViA3Q6kDFS_9kn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/debug/trace.h#L116)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This also needs `GPR_UNLIKELY()`.
</blockquote></details>

Done.
___
*[src/core/lib/debug/trace.h, line 162 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-Mgkbm2vB0omBW6T0ViA:-Mgl3Wau1beio34lRf5Z:bn2nn4q) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/debug/trace.h#L162)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this `static_cast<>` is needed.
</blockquote></details>

This specialization of `IfEnabled` was removed.
___
*[src/core/lib/gpr/log_internal.h, line 23 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-Mgkb1Py5bO5V-H9TYhk:-Mgl3iL8CEQiwsp7-DW2:b4zrpec) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/gpr/log_internal.h#L23)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to start with a `gpr_` prefix to avoid polluting the global C symbol namespace, so it should be called `gpr_vlog()`.
</blockquote></details>

Of course. Thanks.
___
*[src/core/lib/iomgr/error.cc, line 311 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-Mgkd3qN73AC5d6NxDXu:-Mgl44ei6UsgDp9jY_qS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/iomgr/error.cc#L311)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suspect that unconditionally checking `if (*err != orig)` isn't going to be a lot of overhead, so we could probably dispense with this `#ifndef NDEBUG`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/error.cc, line 515 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-Mgkddyx5JamL2vfWh3e:-Mgl4FkY6UID7wZiwnIF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/iomgr/error.cc#L515)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This `#ifndef NDEBUG` isn't needed.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/ev_epollex_linux.cc, line 174 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-Mgke41C6jDdG3v4Ekqf:-MglADK85Nr4-5lBUYGc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/iomgr/ev_epollex_linux.cc#L174)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this `#ifndef NDEBUG`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/executor/mpmcqueue.cc, line 36 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-MghirPV5qr9h-VegJCZ:-Mgl4UGbBzYMbP0X2kaW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/iomgr/executor/mpmcqueue.cc#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These cases can probably be wrapped in `#ifndef NDEBUG`.
</blockquote></details>

Done.
___
*[src/core/lib/security/context/security_context.h, line 30 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkeiUN92IdqW2gtzGb:-Mgl4n1RBxrZZd8a6gaY:befr79o) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/security/context/security_context.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why this change?  We do want ref-count tracers to be debug-only.
</blockquote></details>

Reverted, thanks for calling it out. I was toying with a different solution and hadn't cleaned this up yet.
___
*[src/core/lib/surface/completion_queue.cc, line 1220 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-Mghk6Yc0TUdlj0RudRK:-Mgl5ZCh8NEf3kKEBBqF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/45b7c2cda0fb679c09405b8f61009d96a8e8cc9a/src/core/lib/surface/completion_queue.cc#L1220)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This block can be wrapped in an `#ifndef NDEBUG`.
</blockquote></details>

Done.
___
*[src/core/lib/surface/completion_queue.cc, line 950 at r2](https://reviewable.io/reviews/grpc/grpc/26954#-MgkeusV4Yqlf3NMtpop:-Mgl5X6tDLqhs4Fwe1hD:be17u8d) ([raw file](https://github.com/grpc/grpc/blob/023cbc791d63de94fe2a8f864f8596173f23f7ec/src/core/lib/surface/completion_queue.cc#L950)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Not an issue here, since this function is inside of `#ifndef NDEBUG`.
</blockquote></details>

Ack, thanks.
___
*[src/core/lib/transport/metadata.cc, line 67 at r1](https://reviewable.io/reviews/grpc/grpc/26954#-Mghi5io6hJtYkAvGsaD:- [...]

2021-08-10 19:48 UTC, markdroth approved these changes
Looks great!

> Reviewed 26 of 26 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-MglaxNP1oCUGi0Mhrw7:b9bkkp1)* status: all files reviewed, 2 unresolved discussions (waiting on @ctiller and @drfloob)



<!-- Sent from Reviewable.io -->

2021-08-13 20:57 UTC, markdroth reviewed
This looks great!

Can you go ahead and change all callers to use `TraceFlag::Log()`?  Thanks!

> Reviewed 24 of 24 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-Mh0INnHBG86UAPvp7pY:bcbrojy)* status: all files reviewed, 2 unresolved discussions (waiting on @ctiller and @drfloob)



<!-- Sent from Reviewable.io -->

2021-08-13 23:19 UTC, drfloob reviewed
Done. There were 25 more spots I could clean up for the non-`DebugOnly` TraceFlags. 15 places remain that check `TraceFlag::enabled()` and do something more significant than logging simple values. 

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-Mh0nh9uDjXuOLwOsac9:b-u8azae)* status: 39 of 48 files reviewed, 2 unresolved discussions (waiting on @ctiller, @drfloob, and @markdroth)



<!-- Sent from Reviewable.io -->

2021-08-13 23:25 UTC, markdroth reviewed
Looks like you missed all of the ones using the `GRPC_TRACE_FLAG_ENABLED()` macro.  For example:

https://github.com/grpc/grpc/blob/588df691b01e483f599258a951ff11a87b8f6016/src/core/ext/filters/client_channel/client_channel.cc#L356

> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-Mh0pDHy6JUNqqKjWDTl:b-ecaibv)* status: all files reviewed, 2 unresolved discussions (waiting on @ctiller and @drfloob)



<!-- Sent from Reviewable.io -->

2021-08-13 23:27 UTC, drfloob reviewed
Oh geez, I completely forgot them this pass through. Thanks for reminding me.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-Mh0pZRA5YpmE9g6Q03z:b-qzytzm)* status: all files reviewed, 2 unresolved discussions (waiting on @ctiller and @drfloob)



<!-- Sent from Reviewable.io -->

2021-08-23 23:43 UTC, markdroth requested changes
Overall, this looks fabulous!  Just a few minor comments.

Please let me know if you have any questions.  Thanks!

> Reviewed 70 of 70 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-MhpOH_aEM1ZDB1q2OU5:bx9p86z)* status: all files reviewed, 6 unresolved discussions (waiting on @ctiller and @drfloob)

___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1664 at r6](https://reviewable.io/reviews/grpc/grpc/26954#-MhpL2166Q6MZhY3jZeO:-MhpL2166Q6MZhY3jZeP:bh1w4w3) ([raw file](https://github.com/grpc/grpc/blob/ad346bf9c7b138d54341f36c98ea03691c1777da/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1664)):*
> ```cpp
>   }
>   // Update the policy.
> ```

Please remove blank line.
___
*[src/core/ext/transport/cronet/transport/cronet_transport.cc, line 57 at r6](https://reviewable.io/reviews/grpc/grpc/26954#-MhpNG7i8uJzNGkT01sf:-MhpNG7i8uJzNGkT01sg:b-y1x7qw) ([raw file](https://github.com/grpc/grpc/blob/ad346bf9c7b138d54341f36c98ea03691c1777da/src/core/ext/transport/cronet/transport/cronet_transport.cc#L57)):*
> ```cpp
> 
> grpc_core::TraceFlag grpc_cronet_trace(false, "cronet");
> #define CRONET_LOG(...) grpc_cronet_trace.Log(__VA_ARGS__)
> ```

At this point, is there any reason not to remove this macro and just inline `grpc_cronet_trace.Log()`?
___
*[src/core/lib/surface/call.cc, line 749 at r6](https://reviewable.io/reviews/grpc/grpc/26954#-MhpNiQA8b7WtWgrq5cn:-MhpNiQA8b7WtWgrq5co:b3v272o) ([raw file](https://github.com/grpc/grpc/blob/ad346bf9c7b138d54341f36c98ea03691c1777da/src/core/lib/surface/call.cc#L749)):*
> ```cpp
>   if (GRPC_TRACE_FLAG_ENABLED(grpc_call_error_trace)) {
>     gpr_log(GPR_DEBUG, "set_final_status %s", call->is_client ? "CLI" : "SVR");
>     gpr_log(GPR_DEBUG, "set_final_status %s", call->is_client ? "CLI" : "SVR");
> ```

This doesn't look right.  Looks like you've duplicated the previous line instead of converting these to the new API.
___
*[src/core/lib/surface/call.cc, line 750 at r6](https://reviewable.io/reviews/grpc/grpc/26954#-MhpO--Z8pr9YYioyAIK:-MhpO--Z8pr9YYioyAIL:bj6a9l2) ([raw file](https://github.com/grpc/grpc/blob/ad346bf9c7b138d54341f36c98ea03691c1777da/src/core/lib/surface/call.cc#L750)):*
> ```cpp
>     gpr_log(GPR_DEBUG, "set_final_status %s", call->is_client ? "CLI" : "SVR");
>     gpr_log(GPR_DEBUG, "set_final_status %s", call->is_client ? "CLI" : "SVR");
>     gpr_log(GPR_DEBUG, "%s", grpc_error_std_string(error).c_str());
> ```

While we're at it, we might want to just combine this log line into the previous one, so that we don't need to check the conditional twice.


<!-- Sent from Reviewable.io -->

2021-08-23 23:54 UTC, drfloob reviewed
Thanks! All taken care of.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-MhpQPvh9QXZT10K1hcx:bsz504t)* status: all files reviewed, 5 unresolved discussions (waiting on @ctiller and @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 1664 at r6](https://reviewable.io/reviews/grpc/grpc/26954#-MhpL2166Q6MZhY3jZeO:-MhpQRx97-Mit1hpbojm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ad346bf9c7b138d54341f36c98ea03691c1777da/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L1664)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank line.
</blockquote></details>

Done.
___
*[src/core/ext/transport/cronet/transport/cronet_transport.cc, line 57 at r6](https://reviewable.io/reviews/grpc/grpc/26954#-MhpNG7i8uJzNGkT01sf:-MhpQSlD8ei-3VyC5yJa:bzahyws) ([raw file](https://github.com/grpc/grpc/blob/ad346bf9c7b138d54341f36c98ea03691c1777da/src/core/ext/transport/cronet/transport/cronet_transport.cc#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

At this point, is there any reason not to remove this macro and just inline `grpc_cronet_trace.Log()`?
</blockquote></details>

Good call. Removed.
___
*[src/core/lib/surface/call.cc, line 749 at r6](https://reviewable.io/reviews/grpc/grpc/26954#-MhpNiQA8b7WtWgrq5cn:-MhpQX79-AXEMJWjxjQo:b-xds118) ([raw file](https://github.com/grpc/grpc/blob/ad346bf9c7b138d54341f36c98ea03691c1777da/src/core/lib/surface/call.cc#L749)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't look right.  Looks like you've duplicated the previous line instead of converting these to the new API.
</blockquote></details>

Good catch. Fixed. The first automation tool I wrote for this had that bug in a few scenarios, this instance slipped through.
___
*[src/core/lib/surface/call.cc, line 750 at r6](https://reviewable.io/reviews/grpc/grpc/26954#-MhpO--Z8pr9YYioyAIK:-MhpQoIT6coq7e1HrX0p:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ad346bf9c7b138d54341f36c98ea03691c1777da/src/core/lib/surface/call.cc#L750)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

While we're at it, we might want to just combine this log line into the previous one, so that we don't need to check the conditional twice.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-24 00:26 UTC, markdroth approved these changes
Looks great!

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26954#-:-MhpYIZgAXqwcl_UaCTT:b9bkkp1)* status: all files reviewed, 1 unresolved discussion (waiting on @ctiller)



<!-- Sent from Reviewable.io -->

2021-08-24 16:41 UTC, drfloob commented
Bazel RBE Opt C/C++ - Known bug b/162331415

2021-08-24 16:42 UTC, merged