Event Engine's libuv implementation
grpc/grpc pull request #27194
Opened 2021-08-31 00:00 UTC by nicolasnoble

2021-09-02 02:25 UTC, nicolasnoble commented
We probably still want to clean up the merge (I think I've spotted merge failures), but the main code is clean enough for being seen by other eyes.

2021-09-02 02:25 UTC, nicolasnoble commented
We will also want some more testing, and look for portability, which I know will at least break on Windows.

2021-09-02 17:31 UTC, drfloob requested changes
Thanks Nico! I'm excited to see this come to fruition. I've done a partial first pass, and still need to review the meat of the uv implementation, slice, and slice_buffer.

> Reviewed 36 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27194#-:-MibYqKv9xHz0jYEUT_6:b-6tyeqj)* status: 36 of 39 files reviewed, 8 unresolved discussions (waiting on @ctiller, @gnossen, @jtattermusch, @markdroth, @nicolasnoble, and @veblush)

___
*[include/grpc/event_engine/endpoint_config.h, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibUftW4BMbJB4SlPed:-MibUftW4BMbJB4SlPee:b9lo29y) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/endpoint_config.h#L42)):*
> ```objc
>   /// \a key in the EndpointConfig, an \a absl::monostate type will be
>   /// returned. Caller does not take ownership of resulting value.
>   virtual Setting Get(absl::string_view key) const { abort(); }
> ```

Why did the interface (now base class) need an implementation?
___
*[include/grpc/impl/codegen/port_platform.h, line 682 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibW04K69kwITeeQoWX:-MibW04K69kwITeeQoWY:bb5fl5t) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/impl/codegen/port_platform.h#L682)):*
> ```objc
> #ifdef GRPC_USE_EVENT_ENGINE
> #undef GPR_SUPPORT_CHANNELS_FROM_FD
> #define GRPC_ARES 1
> ```

I think this can be ignored for now, but note that it will cause some tests to fail. Ares is not support on iOS or custom iomgrs yet (gevent, specifically, had issues in the past). I'm refactoring the ares code now, separately.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 546 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibWM6-CHlIJFfiiOl1:-MibWM6-CHlIJFfiiOl2:bpzghet) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L546)):*
> ```cpp
>     return err;
>   }
>   driver->work_serializer = std::move(work_serializer);
> ```

FYI, @markdroth had rejected this cleanup when I introduced it months ago. Probably best to revert.
___
*[src/core/ext/transport/chttp2/transport/chttp2_slice_allocator.cc, line 27 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibWfXx6ze72nBkE7N3:-MibWfXx6ze72nBkE7N4:b-eh856n) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/ext/transport/chttp2/transport/chttp2_slice_allocator.cc#L27)):*
> ```cpp
> #include "src/core/lib/transport/error_utils.h"
> 
> extern grpc_core::TraceFlag grpc_tcp_trace;
> ```

This appears to be unused.
___
*[src/core/lib/iomgr/event_engine/promise.h, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibXACf5BD1va1Jph39:-MibXACf5BD1va1Jph3A:butlzvi) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/iomgr/event_engine/promise.h#L29)):*
> ```objc
> /// .wait() and .notify().
> template <typename T>
> class Promise {
> ```

@ctiller are the other gRPC promises ready to be used yet?
___
*[src/core/lib/iomgr/event_engine/promise.h, line 35 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibXG7R1wGSLWdPVxC9:-MibXG7R1wGSLWdPVxCA:bs1mlt4) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/iomgr/event_engine/promise.h#L35)):*
> ```objc
>   T& Get() {
>     absl::MutexLock lock(&mu_);
>     if (!set_) {
> ```

If we're going to rely on this, it might be worth adding a smoke test for the race condition of Get before Set (a bug caught recently).
___
*[src/core/lib/iomgr/event_engine/uv/impl.cc, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibYVuI3jdZFDdejkwF:-MibYVuI3jdZFDdejkwG:bu1vc7x) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/iomgr/event_engine/uv/impl.cc#L1)):*
> ```cpp
> #include <uv.h>
> ```

Run the sanitizer/auto-fix on this file. Needs a copyright header.
___
*[src/core/lib/iomgr/event_engine/uv/impl.cc, line 5 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibYLmZErVEhqjxUpf3:-MibYLmZErVEhqjxUpf4:bmlaxnb) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/iomgr/event_engine/uv/impl.cc#L5)):*
> ```cpp
> #include <atomic>
> #include <functional>
> #include <future>
> ```

This is a banned construct, see `tools/run_tests/sanity/cpp_banned_constructs.sh`. 
___
*[src/core/lib/surface/init.cc, line 26 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibXaeN53dpI5fsVT5t:-MibXaeN53dpI5fsVT5u:b-jjsngj) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/surface/init.cc#L26)):*
> ```cpp
> #include <memory.h>
> 
> #include <future>
> ```

This is unused, and regardless, `<future>` is banned in the codebase at the moment.


<!-- Sent from Reviewable.io -->

2021-09-02 21:36 UTC, Vignesh2208 commented on src/core/lib/iomgr/event_engine/uv/impl.cc
> +absl::StatusOr<int> LibuvListener::Bind(
Just leaving this comment here to seek some clarification. As per my understanding, the Bind method can be called multiple times with different addresses but it seems like there is only one uv_tcp_t handle per LibuvListener here. Not sure if libuv internally creates and maintains multiple sockets per uv_tcp_t handle or if there should be a linked list of uv_tcp_t handles for each LibuvListener

2021-09-02 22:27 UTC, markdroth requested changes
This looks like a fantastic start, Nico!

Please don't let the number of comments here disturb you -- most of them are cosmetic issues.  There are just a few comments that are more substantive, such as the ones about using a more nested class structure to make the overal map of the code clearer to the reader.

Please let me know if you have any questions.  Thanks!

> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27194#-:-MicbDW966H8x5bedSwA:bujrhvy)* status: all files reviewed, 61 unresolved discussions (waiting on @ctiller, @gnossen, @jtattermusch, @nicolasnoble, and @veblush)

___
*[BUILD, line 1257 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mibyr-sBgeAnxr4pucK:-Mibyr-t4Zm6nuzNrJJg:b-ds6ydv) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/BUILD#L1257)):*
> ```Starlark
>         "src/core/lib/iomgr/event_engine/tcp.cc",
>         "src/core/lib/iomgr/event_engine/timer.cc",
>         "src/core/lib/iomgr/event_engine/uv/impl.cc",
> ```

Would it make sense to put this libuv-base EE impl in its own build target, so that it's not required for applications that want to provide their own EE impl?
___
*[include/grpc/event_engine/slice.h, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic0EXb8se7UvGun3Xg:-Mic0EXb8se7UvGun3Xh:bf0srql) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice.h#L38)):*
> ```objc
> /// slice pointing to a subset of another slice.
> class Slice final {
>   friend class SliceBuffer;
> ```

Could we avoid needing this somehow?  It looks like it's mainly used for move semantics even without using an rvalue reference.  Could we restructure things to avoid that somehow?

If this is needed, please move it down into the `private:` section.
___
*[include/grpc/event_engine/slice.h, line 78 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic-ZIJ0e8Tcwn40_JL:-Mic-ZIJ0e8Tcwn40_JM:bvqhjys) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice.h#L78)):*
> ```objc
> 
>   /// Assignment, reference count is unchanged.
>   Slice& operator=(Slice other) {
> ```

It seems a little counter-intuitive to use move semantics for a normal assignment operator.  Maybe we want two versions of this, one for copy-assignment and one for move-assignment?
___
*[include/grpc/event_engine/slice.h, line 109 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic0VXIBawoE0-odB2V:-Mic0VXIBawoE0-odB2W:bve7j7f) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice.h#L109)):*
> ```objc
> 
>   /// Raw C slice. Caller needs to call grpc_slice_unref when done.
>   grpc_slice c_slice() const { return grpc_slice_ref(slice_); }
> ```

Please explicitly document the fact that this isn't a stable API, just to make sure that people don't get confused about it.
___
*[include/grpc/event_engine/slice.h, line 109 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic0tFd3CYc4K6NYvJk:-Mic0tFd3CYc4K6NYvJl:b-3plp6m) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice.h#L109)):*
> ```objc
> 
>   /// Raw C slice. Caller needs to call grpc_slice_unref when done.
>   grpc_slice c_slice() const { return grpc_slice_ref(slice_); }
> ```

Would it make sense for this to return `const grpc_slice&` and make it the caller's responsibility to take a new ref if they need to?
___
*[include/grpc/event_engine/slice.h, line 112 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic0M9g4v_MqpzmuzgG:-Mic0M9g4v_MqpzmuzgH:b-a0m1d2) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice.h#L112)):*
> ```objc
> 
>  private:
>   friend class ByteBuffer;
> ```

We don't have any such class in the EE API.  I assume this was copied from the C++ Slice API accidentally. :)
___
*[include/grpc/event_engine/slice_allocator.h, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic4igFDdfHgNgDwcI_:-Mic4igFDdfHgNgDwcIa:b-nnbda1) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_allocator.h#L25)):*
> ```objc
> #include <grpc/event_engine/slice_buffer.h>
> 
> // forward-declaring an internal struct, not used publicly.
> ```

Doesn't look like any of these are actually needed.
___
*[include/grpc/event_engine/slice_buffer.h, line 45 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic26FWDw7713hc5nma:-Mic1qnC2t3myV2OqOm6:bxfbvpk) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L45)):*
> ```objc
> class SliceBuffer final {
>  public:
>   SliceBuffer(grpc_slice_buffer* sb) : sb_(sb) {}
> ```

Please add a TODO that we need to change this API to not depend on the C-core type before de-experimentalizing the EE API.  I think we'll want this to happen as part of eliminating the iomgr API.
___
*[include/grpc/event_engine/slice_buffer.h, line 49 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic2OhG2s5kqi2PepEg:-Mic2OhG2s5kqi2PepEh:b-ib6l7v) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L49)):*
> ```objc
>   SliceBuffer(SliceBuffer&& other) : sb_(other.sb_) { other.sb_ = nullptr; }
> 
>   // This easier to write than an iterator, and essentially does the same, in a
> ```

Couldn't the iterator return references to the slices embedded in the `SliceBuffer`, so that there's no copy involved?  I think most STL iterators return references, don't they?
___
*[include/grpc/event_engine/slice_buffer.h, line 68 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic33uW14VWH2n55ryb:-Mic33uW14VWH2n55ryc:bqk5yd9) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L68)):*
> ```objc
>   }
> 
>   void Add(Slice slice) {
> ```

It seems odd to me that this API takes ownership of the slice without it being passed in as an rvalue reference.
___
*[include/grpc/event_engine/slice_buffer.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic3Bbk4jUKl9BqsjKe:-Mic3Bbk4jUKl9BqsjKf:bzdciig) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L73)):*
> ```objc
>   }
> 
>   size_t AddIndexed(Slice slice) {
> ```

Same here -- and this is identical to the next method, which *does* take an rvalue reference.  Why do we need both?
___
*[include/grpc/event_engine/slice_buffer.h, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic47f03d02hSpGyZG9:-Mic47f70Lqegb4XrmfW:b-utmwwd) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L119)):*
> ```objc
>   size_t Length() { return sb_->length; }
> 
>   grpc_slice_buffer* RawSliceBuffer() { return sb_; }
> ```

Suggest calling this `c_slice_buffer()`.
___
*[include/grpc/event_engine/slice_buffer.h, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic4DOp7UBlG_UaNlfC:-Mic4DOp7UBlG_UaNlfD:bej99ec) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L119)):*
> ```objc
>   size_t Length() { return sb_->length; }
> 
>   grpc_slice_buffer* RawSliceBuffer() { return sb_; }
> ```

Please document that this is not a stable API.
___
*[src/core/ext/transport/chttp2/transport/chttp2_slice_allocator.cc, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic4zzT7AIsT1Lr51pe:-Mic4zzT7AIsT1Lr51pf:b-bhrsjr) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/ext/transport/chttp2/transport/chttp2_slice_allocator.cc#L25)):*
> ```cpp
> #i [...]

2021-09-24 06:24 UTC, nicolasnoble reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27194)* status: all files reviewed, 62 unresolved discussions (waiting on @ctiller, @drfloob, @gnossen, @jtattermusch, @markdroth, @nicolasnoble, and @veblush)

___
*[BUILD, line 1257 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mibyr-sBgeAnxr4pucK:-MkLDczZ-NSUecfL_jqD:bru1t60) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/BUILD#L1257)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Would it make sense to put this libuv-base EE impl in its own build target, so that it's not required for applications that want to provide their own EE impl?
</blockquote></details>

Sure, this was easier this way. Any name suggestion for the new target, @drfloob ?
___
*[include/grpc/event_engine/endpoint_config.h, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibUftW4BMbJB4SlPed:-MkLDr7Q3Il-eKliEZF8:b-zh98mc) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/endpoint_config.h#L42)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Why did the interface (now base class) need an implementation?
</blockquote></details>

Settings are used as a first class entity, both in parameters and in the classes. If we wanted to get rid of this, we need the API to change those to unique pointers.
___
*[include/grpc/event_engine/slice.h, line 112 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic0M9g4v_MqpzmuzgG:-MkLFDFj3G1xRsIvfznq:b1cqbxg) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice.h#L112)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We don't have any such class in the EE API.  I assume this was copied from the C++ Slice API accidentally. :)
</blockquote></details>

Right. The whole file was copied over basically, just with a different namespace. The other comments apply for this too in the sense that they weren't brand new APIs.
___
*[include/grpc/event_engine/slice_allocator.h, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic4igFDdfHgNgDwcI_:-MkLFXr5-6gVurwYjnoK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_allocator.h#L25)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like any of these are actually needed.
</blockquote></details>

Done.
___
*[include/grpc/event_engine/slice_buffer.h, line 45 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic26FWDw7713hc5nma:-MkLGJJA3xH1hNIKG8JG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L45)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a TODO that we need to change this API to not depend on the C-core type before de-experimentalizing the EE API.  I think we'll want this to happen as part of eliminating the iomgr API.
</blockquote></details>

Done.
___
*[include/grpc/event_engine/slice_buffer.h, line 49 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic2OhG2s5kqi2PepEg:-MkLG_uC6Ym_2RJGACGm:b-3r5uy6) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L49)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Couldn't the iterator return references to the slices embedded in the `SliceBuffer`, so that there's no copy involved?  I think most STL iterators return references, don't they?
</blockquote></details>

Right, it needs to avoid the pitfall of thinking that just using a Slice itself is fine, because the comments around Slices keep saying that doing copies of them is cheap and should be what people use. I'll augment the comment with this.
___
*[include/grpc/event_engine/slice_buffer.h, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic47f03d02hSpGyZG9:-MkLHlmO2c43vQv6wpi-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `c_slice_buffer()`.
</blockquote></details>

Done.
___
*[include/grpc/event_engine/slice_buffer.h, line 119 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic4DOp7UBlG_UaNlfC:-MkLHm1D3BDo4FUC660B:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document that this is not a stable API.
</blockquote></details>

Done.
___
*[include/grpc/impl/codegen/port_platform.h, line 682 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibW04K69kwITeeQoWX:-MkLI1HN0HLEDC7-tDqC:bq8l751) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/impl/codegen/port_platform.h#L682)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

I think this can be ignored for now, but note that it will cause some tests to fail. Ares is not support on iOS or custom iomgrs yet (gevent, specifically, had issues in the past). I'm refactoring the ares code now, separately.
</blockquote></details>

Symbols wouldn't be found otherwise.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 546 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibWM6-CHlIJFfiiOl1:-MkLI6NjDQFY0raEqYA6:bb6sh2i) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L546)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

FYI, @markdroth had rejected this cleanup when I introduced it months ago. Probably best to revert.
</blockquote></details>

Ack.
___
*[src/core/ext/transport/chttp2/transport/chttp2_slice_allocator.cc, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic4zzT7AIsT1Lr51pe:-MkLJPve2M-5OBHryGio:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/ext/transport/chttp2/transport/chttp2_slice_allocator.cc#L25)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't lool like this is needed.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/transport/chttp2_slice_allocator.cc, line 27 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibWfXx6ze72nBkE7N3:-MkLJQMk0_1T108Jjywf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/ext/transport/chttp2/transport/chttp2_slice_allocator.cc#L27)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

This appears to be unused.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/promise.h, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibXACf5BD1va1Jph39:-MkLJSOo4A6Tk4qc0GKI:b2jxec9) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/iomgr/event_engine/promise.h#L29)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

@ctiller are the other gRPC promises ready to be used yet?
</blockquote></details>

Let's use those for now.
___
*[src/core/lib/iomgr/event_engine/promise.h, line 35 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibXG7R1wGSLWdPVxC9:-MkLJUIW3I72oinPKyf2:bb6sh2i) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/ [...]

2021-09-24 17:10 UTC, drfloob reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27194)* status: 31 of 39 files reviewed, 62 unresolved discussions (waiting on @ctiller, @drfloob, @gnossen, @jtattermusch, @markdroth, @nicolasnoble, and @veblush)

___
*[BUILD, line 1257 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mibyr-sBgeAnxr4pucK:-MkNlt3b0yoAl9hu31Dl:b-cszcj5) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/BUILD#L1257)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

Sure, this was easier this way. Any name suggestion for the new target, @drfloob ?
</blockquote></details>

"grpc_event_engine_libuv"? Feel free to choose one, Nico!


<!-- Sent from Reviewable.io -->

2021-09-24 17:23 UTC, drfloob requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27194)* status: 31 of 39 files reviewed, 59 unresolved discussions (waiting on @ctiller, @drfloob, @gnossen, @jtattermusch, @markdroth, @nicolasnoble, and @veblush)

___
*[include/grpc/event_engine/endpoint_config.h, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibUftW4BMbJB4SlPed:-MkNnjPq8PzBrfOXQnZf:bfqt65o) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/endpoint_config.h#L42)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

Settings are used as a first class entity, both in parameters and in the classes. If we wanted to get rid of this, we need the API to change those to unique pointers.
</blockquote></details>

I think you're right, they should be unique_ptr. Do you want to make that change in this PR? I believe you need to merge the latest master, but there are only 2 signatures that need to be changed, no logic changes required yet afaict.
___
*[src/core/lib/iomgr/event_engine/promise.h, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MibXACf5BD1va1Jph39:-MkNp25B1nTGPB9hROtY:b89ud2d) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/iomgr/event_engine/promise.h#L29)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

Let's use those for now.
</blockquote></details>

You mean we should use this smaller `Promise` implementation for now, instead of the new stuff, right? I think that's what we last discussed.


<!-- Sent from Reviewable.io -->

2021-09-27 22:26 UTC, markdroth requested changes
> Reviewed 2 of 7 files at r2, 4 of 5 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27194)* status: all files reviewed, 43 unresolved discussions (waiting on @ctiller, @drfloob, @gnossen, @jtattermusch, @nicolasnoble, and @veblush)

___
*[BUILD, line 1257 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mibyr-sBgeAnxr4pucK:-MkdM8TaBYNgx1l5bjkf:byvw8jd) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/BUILD#L1257)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

"grpc_event_engine_libuv"? Feel free to choose one, Nico!
</blockquote></details>

That name sounds good to me.
___
*[include/grpc/event_engine/slice.h, line 112 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic0M9g4v_MqpzmuzgG:-MkdIOz9-YkRtHuqKdpQ:b-ons5bp) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice.h#L112)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

Right. The whole file was copied over basically, just with a different namespace. The other comments apply for this too in the sense that they weren't brand new APIs.
</blockquote></details>

Understood.  But let's clean this stuff up before this lands.
___
*[include/grpc/event_engine/slice_allocator.h, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic4igFDdfHgNgDwcI_:-MkdIVysBWuCKRaVxab9:behgwxy) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_allocator.h#L25)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change here.
___
*[include/grpc/event_engine/slice_buffer.h, line 45 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic26FWDw7713hc5nma:-MkdI_ag3DPVc50RXiuk:b-i7dc38) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L45)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please make this a TODO comment.  If it doesn't say TODO, we won't know to go back and do it later. :)
___
*[include/grpc/event_engine/slice_buffer.h, line 49 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic2OhG2s5kqi2PepEg:-MkdIlgo9TuKJUJn4f75:b-lm40d4) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/include/grpc/event_engine/slice_buffer.h#L49)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

Right, it needs to avoid the pitfall of thinking that just using a Slice itself is fine, because the comments around Slices keep saying that doing copies of them is cheap and should be what people use. I'll augment the comment with this.
</blockquote></details>

Right, so doesn't that mean that we can provide an iterator interface instead of `Enumerate()`?
___
*[src/core/lib/iomgr/event_engine/uv/impl.cc, line 171 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-Mic8AwL9yDUGQoiMyKc:-MkdJija6lASda8ZQ-77:b47a3lo) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/iomgr/event_engine/uv/impl.cc#L171)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Dtor should come before other methods, as per:

https://google.github.io/styleguide/cppguide.html#Declaration_Order

Same thing throughout.
</blockquote></details>

Looks like you fixed this here, but not for other classes.
___
*[src/core/lib/iomgr/event_engine/uv/impl.cc, line 543 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MicLaqU-qzPU9ZhGdJm:-MkdLbww1UOY7c6m7deN:bfgtuwn) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/iomgr/event_engine/uv/impl.cc#L543)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

Good question, I don't remember why I didn't have to, but I'll give it a go.
</blockquote></details>

It would matter only if you test it with the C++ callback API, since that's the only thing that uses the `ApplicationCallbackExecCtx`.
___
*[src/core/lib/iomgr/event_engine/uv/impl.cc, line 1054 at r1](https://reviewable.io/reviews/grpc/grpc/27194#-MicY3Dv-MqShDeopVsU:-MkdKrZY5VspHSwM6utt:bovtr32) ([raw file](https://github.com/grpc/grpc/blob/8f3f20bcfbbd634621930c77e319165d0d78017a/src/core/lib/iomgr/event_engine/uv/impl.cc#L1054)):*
<details><summary><i>Previously, nicolasnoble (Nicolas Noble) wrote…</i></summary><blockquote>

Not necessarily. This will make the code fail later in case we didn't actually bind the port if something was already there.
</blockquote></details>

Okay.  But we do need to resolve this before we can actually use this code on the server side.  If we're going to handle that in a separate PR, please make this a TODO comment.
___
*[src/core/lib/iomgr/event_engine/uv/impl.cc, line 39 at r6](https://reviewable.io/reviews/grpc/grpc/27194#-MkdJ1PQBQ6T7qD9EkZf:-MkdJ1PQBQ6T7qD9EkZg:bkqdtlp) ([raw file](https://github.com/grpc/grpc/blob/acc24152ff1acfaf445427d14c8a052f976e78ee/src/core/lib/iomgr/event_engine/uv/impl.cc#L39)):*
> ```cpp
> extern grpc_core::TraceFlag grpc_tcp_trace;
> 
> using namespace grpc_event_engine::experimental;
> ```

The style guide prohibits namespace-level `using namespace` statements:

https://google.github.io/styleguide/cppguide.html#Namespaces

Please use `using grpc_event_engine::experimental::EventEngine;` instead.


<!-- Sent from Reviewable.io -->

2021-10-02 20:57 UTC, ctiller reviewed
Some thoughts on slice apis, since I'm currently doing one for grpc_core - let's get alignment on what these look like.

2021-10-02 20:57 UTC, ctiller commented on include/grpc/event_engine/slice.h
> +  Slice(void* buf, size_t len, void (*destroy)(void*), void* user_data)
Can we change these to factory functions...

```
static Slice CreateWithUserData(...);
static Slice CreateWithCustomDestroy(...);
static Slice CreateWithCustomSizedDestroy(...);
```

advantage: overloads are awful for communicating intent

2021-10-02 20:57 UTC, ctiller commented on include/grpc/event_engine/slice.h
> +class Slice final {
I've been looking at providing a `grpc_core` version of this. Let's try and standardize.

2021-10-02 20:57 UTC, ctiller commented on include/grpc/event_engine/slice.h
> +  Slice(grpc_slice slice, AddRef) : slice_(grpc_slice_ref(slice)) {}
Let's drop this and the steal ref version, and always steal (i.e. prefer `explicit Slice(grpc_slice slice)`)
It's what's needed most of the time anyway, and the ref counting enums get tricky, and one can always write grpc_slice_ref() if they need a different behavior.

2021-10-02 20:57 UTC, ctiller commented on include/grpc/event_engine/slice.h
> +  explicit Slice(size_t len) : slice_(grpc_slice_malloc(len)) {}
```
static Slice CreateUninitialized(size_t len) { return Slice(grpc_slice_malloc(len)); }
```

2021-10-02 20:57 UTC, ctiller commented on include/grpc/event_engine/slice.h
> +  Slice(const std::string& str)
```
static Slice FromCopiedString(const std::string&);
```

2021-10-02 20:57 UTC, ctiller commented on include/grpc/event_engine/slice.h
> +  Slice(const Slice& other) : slice_(grpc_slice_ref(other.slice_)) {}
I think I prefer:

```
Slice(const Slice&) = delete;
Slice& operator=(const Slice&) = delete;
Slice(Slice&& other) : slice_(other.slice_) { other.slice_ = kEmpty; }
Slice& operator=(Slice&& other) {
  std::swap(slice_, other.slice_);
  return *this;
}
Slice Ref() { return Slice(grpc_slice_ref(slice_)); }
Slice Copy() { return Slice(grpc_slice_copy(slice_)); }
```

i.e. slice itself is move only, and has explicit factory functions for reffing and copying.

this clarifies intent at copy sites, and when substituting this type into existing code we don't accidentally end up with an explosion of refcounting.

2021-10-02 20:57 UTC, ctiller commented on include/grpc/event_engine/slice.h
> +  grpc_slice c_slice() const { return grpc_slice_ref(slice_); }
let's make this a borrow... so `return slice_`.

let's also add an `IntoCSlice()` that does something like `return absl::exchange(slice_, kEmpty);`

2021-10-02 20:57 UTC, ctiller commented on include/grpc/event_engine/slice_buffer.h
> +  void Enumerate(std::function<void(uint8_t*, size_t, size_t)> cb) {
Can we name it ForEach, and maybe make it take a template functor... I care about performance for this one

2021-10-02 20:57 UTC, ctiller commented on include/grpc/event_engine/slice_buffer.h
> +    grpc_slice_buffer_add(sb_, slice.slice_);
With the slice recommendations I made this could be `grpc_slice_buffer_add(sb_, slice.IntoCSlice());`

2021-10-02 20:57 UTC, ctiller commented on include/grpc/event_engine/slice.h
> +  friend class SliceBuffer;
I think we can remove this.

2021-10-02 20:58 UTC, ctiller commented
(anything I've written here can be taken as let's do a followup PR)

2022-04-18 18:23 UTC, closed without merging