Server side http filter support
grpc/grpc pull request #27388
Opened 2021-09-17 17:52 UTC by yashykt

@yashykt

2021-09-17 18:22 UTC, ctiller commented on src/core/lib/channel/server_config_selector.h
> +//
src/core/lib/channel is supposed to be generic channel related stuff that doesn't care about client or server.
Suggest a different location for this file.
Also suggest placing it somewhere in ext/? It seems like gRPC ought to be able to function without this.

2021-09-17 18:22 UTC, ctiller commented on src/core/ext/transport/chttp2/server/chttp2_server.cc
>    if (server_->config_fetcher() != nullptr) {
We seem to be tying too many things together here. For this change I'd expect no changes to chttp2 to be necessary. Suggest undoing this dependency prior to making this change.

2021-09-23 21:09 UTC, markdroth commented
Thanks for doing this!

I haven't looked at the code yet, and we chatted earlier today about some changes you're going to make here anyway, so I probably won't look until those are done.  But I do have one quick comment from reading the summary:

> Propagates the list of filters all the way to channel stack builder where the list of filters is prepended to the filter stack.

It seems like we need to actually control the positioning of these filters in the stack, rather than just unconditionally prepending them.  In general, I think we want these filters to be below the census filter but above any other filters in the stack.

Also, I agree with Craig that we should ideally keep the service config APIs in the ext tree.  I suggest creating a new directory src/core/ext/service_config for this.

Craig, I don't think we can avoid the chttp2 listener changes; they're pretty integral to this design, and they were covered in the design doc and the design review.  That's the only place where we can control incoming connections and inject configuration between when a connection is accepted and when the channel stack is built.

Please let me know if you have any questions.  Thanks!

2021-09-23 21:17 UTC, ctiller commented
I agree that we probably need changes in chttp2 to move some data around (and we should probably ensure that we do so for all other transports too). I'm objecting to calls to `server_->service_config()` in chttp2, because I think that ties this feature to chttp2 too strongly.

Can we move that code to the thing that's calling `Listener::Start()`

2021-09-27 17:02 UTC, markdroth commented
Craig, I agree that the chttp2 code shouldn't directly rely on the service config.  I think the other changes I discussed with Yash last week should address that.

2021-10-05 20:31 UTC, yashykt commented
@ctiller Note that I haven't removed calls such as `server_->service_config()` from the chttp2_server.cc code. That's not the aim of this PR. The current change just flows some data around from the perspective of chttp2_server.cc.

We should probably talk about how we want the server config fetcher to interact with the server and the listener objects.

2021-10-06 16:20 UTC, ctiller requested changes
I think we need a cleanup PR before this one to decouple the service config from the transport interface, instead of doubling down and making that coupling tighter.

I also object to channel filters being explicitly named in the transport interfaces, and would like an abstraction added so that these two systems stay decoupled.

2021-10-06 16:20 UTC, ctiller commented on src/core/ext/service_config/server_config_call_data.h
> +class ServerConfigCallData {
Why is this in a different directory to the filter?

2021-10-06 16:20 UTC, ctiller commented on src/core/ext/service_config/server_config_selector.h
> +// Similar to ConfigSelector on the client-side. Invoked by the config selector
Comment directly on what this does, without breadcrumbs to other things.

2021-10-06 16:20 UTC, ctiller commented on src/core/ext/service_config/server_config_selector.h
> +class ServerConfigSelectorProvider
Comment on the purpose of this type

2021-10-06 16:20 UTC, ctiller commented on src/core/ext/transport/chttp2/server/chttp2_server.cc
> +      std::vector<const grpc_channel_filter*> filters_;
Channel filter is a type that'd used above the transport layer and should not be added as a thing that transports need to deal with.

If we need to pass filters through this code, suggest creating a new type that is *opaque* to the transport code and can be manipulated only via higher level types.

2021-10-08 00:32 UTC, markdroth reviewed
This looks like a really fantastic start!

One overall comment is that this PR is really huge and it would probably make sense to split it up into multiple pieces.  Right off the cuff, I can think of a few things that would be good to separate into discrete parts:
- Moving the service config code out of the client channel filter.
- The XdsApi changes, including things like handling the wrong route action type at L7, on both the client and server sides.
- The changes to the server config fetcher API and the plumbing in the chttp2 listener.
- The addition of the server config selector filter and the plumbing of the config selector provider.

Also, this PR doesn't seem to have any tests, and we'll definitely need those.

@ctiller Having now reviewed this code in detail, I'm confused by the discussion about accessing the service config from the chttp2 code.  I don't actually see any place where we're accessing the service config in that code.  Am I missing something here?  Or are we just talking about the channel filters being plumbed through?  I think that piece shouldn't be too hard to abstract away.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 57 files at r1, 25 of 37 files at r2, 6 of 22 files at r3, 30 of 30 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27388#-:-MlSGSdk9lamKUzZKrfF:b-abx6lj)* status: all files reviewed, 59 unresolved discussions (waiting on @ctiller and @yashykt)

___
*[src/core/ext/filters/client_channel/client_channel_plugin.cc, line 42 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlR-i0S77ZUFGO5SxA1:-MlR-i0S77ZUFGO5SxA2:b-z8a8ay) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/client_channel_plugin.cc#L42)):*
> ```cpp
> 
> void grpc_client_channel_init(void) {
>   grpc_core::internal::ClientChannelServiceConfigParser::Register();
> ```

How do we ensure that the service config plugin will be initialized before we register these individual parsers?
___
*[src/core/ext/filters/client_channel/lb_policy.h, line 33 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlR-NMM1Mhza9zHkHXp:-MlR-NMM1Mhza9zHkHXq:bjy1ngh) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/lb_policy.h#L33)):*
> ```objc
> #include "src/core/ext/filters/client_channel/server_address.h"
> #include "src/core/ext/filters/client_channel/subchannel_interface.h"
> #include "src/core/ext/service_config/service_config.h"
> ```

Is this include actually needed?  It doesn't look like anything in this file refers to `ServiceConfig`.

Please also remove BUILD dependency.
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 27 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlR1d1v4L3bMp9LkjoH:-MlR1d1v4L3bMp9LkjoI:b-d2ropf) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/resolver_result_parsing.h#L27)):*
> ```objc
> #include "src/core/ext/filters/client_channel/lb_policy_factory.h"
> #include "src/core/ext/filters/client_channel/resolver.h"
> #include "src/core/ext/service_config/service_config.h"
> ```

I think this actually needs to include service_config_parser.h instead.
___
*[src/core/ext/filters/client_channel/service_config_call_data.h, line 38 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlR1mBs6pH-W8-H3TR4:-MlR1mBs6pH-W8-H3TR5:by21fso) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/service_config_call_data.h#L38)):*
> ```objc
> /// object is also stored in the call_context, so that future filters can
> /// easily access method and global parameters for the call.
> class ServiceConfigCallData {
> ```

I think this file should actually move to the new service config directory, because it's going to be needed by any filter that needs to get its parsed config out of the call context.  Those filters should be able to depend on the service config build target instead of depending on the client channel target.

Note that in order to make this work, this file cannot depend on any client channel internals, which it currently does.  I've sent you #27642 to fix that.
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 36 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRkpFx5Fyr9W7yg2Wo:-MlRkpFx5Fyr9W7yg2Wp:bt860ai) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/subchannel.cc#L36)):*
> ```cpp
> #include "src/core/ext/filters/client_channel/proxy_mapper_registry.h"
> #include "src/core/ext/filters/client_channel/subchannel_pool_interface.h"
> #include "src/core/ext/service_config/service_config.h"
> ```

I don't think this include is actually needed.  Nothing in this file actually refers to `ServiceConfig`.

Please also remove BUILD dependency.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 26 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRkyX7EwED_a58VeZA:-MlRkyX7EwED_a58VeZB:bt860ai) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L26)):*
> ```cpp
> #include "src/core/ext/filters/client_channel/lb_policy_factory.h"
> #include "src/core/ext/filters/client_channel/lb_policy_registry.h"
> #include "src/core/ext/service_config/service_config.h"
> ```

I don't think this include is actually needed.  Nothing in this file actually refers to `ServiceConfig`.

Please also remove BUILD dependency.
___
*[src/core/ext/filters/server_config_selector/server_config_selector_filter.cc, line 60 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRwbEx9APBKqkk6fIG:-MlRwbEx9APBKqkk6fIH:b-6vii0n) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/server_config_selector/server_config_selector_filter.cc#L60)):*
> ```cpp
>   ~ChannelData();
> 
>   // TODO(): Do you need to store the whole arg?
> ```

I'm not sure what you're asking here?
___
*[src/core/ext/filters/server_config_selector/server_config_selector_filter.cc, line 98 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRybkD05iUYFAgYoGM:-MlRybkD05iUYFAgYoGN:bi5m5hq) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/server_config_selector/server_config_selector_filter.cc#L98)):*
> ```cpp
>   grpc_closure* original_recv_trailing_metadata_ready_;
>   grpc_closure recv_trailing_metadata_ready_;
>   grpc_error_handle recv_trailing_metadata_ready_error_;
> ```

Is this actually needed?  It seems like you could just use the `error_` field above for this -- whichever of recv_initial_metadata or recv_trailing_metadata finishes first stores its value in `error_`, and then the second one will merge its error with what's already there.
___
*[src/core/ext/service_config/server_config_selector.h, line 17 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRreqGBUIc4iu05FU5:-MlRreqGBUIc4iu05FU6:b8i2af) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/service_config/server_config_selector.h#L17)):*
> ```objc
> //
> 
> #ifndef GRPC_CORE_EXT_SERVICE_CONFIG_SERVER_CONFIG_SELECTOR_H
> ```

This file should go in the server_config_selector_filter directory, since it's effectively part of the functionality of that filter.  (This is analogous to how config_selector.h lives in the client_channel directory, since it's part of that filter.)
___
*[src/core/ext/service_config/server_config_selector.h, line 29 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlQxB0uvTpTsqBTc3s4-r4-29:-MlRs51U2Qad5oxt49cY:b32v57) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/service_config/server_config_selector.h#L29)):*
<d [...]

2021-10-08 16:10 UTC, yashykt commented
@markdroth I got your review earlier than expected :) I am finally done adding all the tests that I wanted to add, and they are finally in a passing state.

One reason that I wanted to do it in one big PR is first is to make sure that it all works together structurally. But, now that I know that I have this working, I can break this down into smaller PRs.

@ctiller Will schedule a meeting to talk about about your concerns.

2021-10-14 01:48 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27388)* status: 39 of 67 files reviewed, 59 unresolved discussions (waiting on @ctiller, @markdroth, and @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 85 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRls_1Dah14OSKyBq9:-MlwQzxr9Yl7CijXC3ki:bkmvcdx) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/xds/xds_api.h#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should probably move outside of `Route`, since it is used in both `RouteAction` and in `VirtualHost`.
</blockquote></details>

done in #27715
___
*[src/core/ext/xds/xds_api.h, line 170 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRm-do2xMYfqwHOc5a:-MlwR0sI1Jg7BUhyo0rF:bkmvcdx) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/xds/xds_api.h#L170)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of an enum and an `absl::optional<>`, let's use `absl::variant<>` here, now that we're allowed to use it.  We can declare an empty struct for `NonForwardingAction`.
</blockquote></details>

done in #27715
___
*[src/core/ext/xds/xds_api.cc, line 119 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRvSz2--cuk2ml1u0L:-MlwRjgOBJvHX7a0N54K:bkmvcdx) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/xds/xds_api.cc#L119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The grouping of all of these helper methods is a little jumbled now.  Please put them in the same order in which they're declared in the .h file, with appropriate class section-header comments.
</blockquote></details>

done in #27715
___
*[src/core/ext/xds/xds_api.cc, line 1838 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRpqze431DTCJ1dwSl:-MlwRsWv9a4ZgmWX0Lrk:bq5vclt) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/xds/xds_api.cc#L1838)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should guard this new parsing logic with the env var from the authz gRFC.
</blockquote></details>

The update here is based on https://github.com/grpc/proposal/blob/master/A36-xds-for-servers.md which does not require any environmental variable guard
___
*[src/core/ext/xds/xds_api.cc, line 1848 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRpzE_8NK1bsmcVPlx:-MlwS5bRD5GZ7ySIkq7L:bf9iid2) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/xds/xds_api.cc#L1848)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think that we should handle any unknown action type the same way that we're going to handle `NonForwardingAction` on the client or `RouteAction` on the server: instead of NACKing, we should handle the failure at L7.
</blockquote></details>

updated in #27715. 


<!-- Sent from Reviewable.io -->

2021-10-14 02:08 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27388)* status: 39 of 67 files reviewed, 59 unresolved discussions (waiting on @ctiller, @markdroth, and @yashykt)

___
*[src/core/ext/filters/client_channel/client_channel_plugin.cc, line 42 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlR-i0S77ZUFGO5SxA1:-MlwXoIsAXnIbxt3_wuJ:b5z24h6) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/client_channel_plugin.cc#L42)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How do we ensure that the service config plugin will be initialized before we register these individual parsers?
</blockquote></details>

done in https://github.com/grpc/grpc/pull/27683
___
*[src/core/ext/filters/client_channel/lb_policy.h, line 33 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlR-NMM1Mhza9zHkHXp:-MlwXrHr0QP6WHiN0zp6:b5z24h6) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/lb_policy.h#L33)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this include actually needed?  It doesn't look like anything in this file refers to `ServiceConfig`.

Please also remove BUILD dependency.
</blockquote></details>

done in https://github.com/grpc/grpc/pull/27683
___
*[src/core/ext/filters/client_channel/resolver_result_parsing.h, line 27 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlR1d1v4L3bMp9LkjoH:-MlwXsqbDYfmo7iQ0aZn:b5z24h6) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/resolver_result_parsing.h#L27)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this actually needs to include service_config_parser.h instead.
</blockquote></details>

done in https://github.com/grpc/grpc/pull/27683
___
*[src/core/ext/filters/client_channel/service_config_call_data.h, line 38 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlR1mBs6pH-W8-H3TR4:-MlwXtsq0CWylWjU0tuz:b5z24h6) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/service_config_call_data.h#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this file should actually move to the new service config directory, because it's going to be needed by any filter that needs to get its parsed config out of the call context.  Those filters should be able to depend on the service config build target instead of depending on the client channel target.

Note that in order to make this work, this file cannot depend on any client channel internals, which it currently does.  I've sent you #27642 to fix that.
</blockquote></details>

done in https://github.com/grpc/grpc/pull/27683
___
*[src/core/ext/filters/client_channel/subchannel.cc, line 36 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRkpFx5Fyr9W7yg2Wo:-MlwY0aC71Uiv6Yz-_ts:b5z24h6) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/subchannel.cc#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this include is actually needed.  Nothing in this file actually refers to `ServiceConfig`.

Please also remove BUILD dependency.
</blockquote></details>

done in https://github.com/grpc/grpc/pull/27683
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 26 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRkyX7EwED_a58VeZA:-MlwY1P78pPUc_K_twNH:b5z24h6) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L26)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this include is actually needed.  Nothing in this file actually refers to `ServiceConfig`.

Please also remove BUILD dependency.
</blockquote></details>

done in https://github.com/grpc/grpc/pull/27683
___
*[src/core/ext/xds/xds_client.cc, line 36 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRqYyh9LnuPS5dgYb1:-MlwYRXX8GTpeJpJIC4-:b5z24h6) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/ext/xds/xds_client.cc#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this include is actually needed.  Nothing in this file refers to `ServiceConfig`.

Please also remove BUILD dependency.
</blockquote></details>

done in https://github.com/grpc/grpc/pull/27683
___
*[src/core/lib/surface/init.cc, line 117 at r4](https://reviewable.io/reviews/grpc/grpc/27388#-MlRzi-j0JvYva0j7aP-:-MlwYczp9crpsLX1GJIC:b5z24h6) ([raw file](https://github.com/grpc/grpc/blob/00c7737e2cb24981a9c54be37fd5326ffaa9edc7/src/core/lib/surface/init.cc#L117)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this belongs here, because it's not okay for code in src/core/lib to depend on code in src/core/ext.

This needs to be done via a plugin instead.  Or, alternatively, you can move it directly to Craig's new core configuration framework.
</blockquote></details>

done in https://github.com/grpc/grpc/pull/27683


<!-- Sent from Reviewable.io -->

2021-11-19 00:20 UTC, closed without merging