Add alpha tests (subsetting) to xds_k8s_lb
grpc/grpc pull request #27460
Opened 2021-09-23 17:57 UTC by lidizheng

As title.

2021-09-27 22:25 UTC, sergiitk requested changes
If possible, I'd avoid saving alpha.json, so we don't have to keep it in sync. Can we access alpha api discovery doc similar to how we do it for networksecurity/networkservices?

2021-09-28 16:45 UTC, lidizheng commented
@sergiitk PTALA. I have updated the logic to access the Compute alpha API. I considered letting test case decide which version to use, but the scope for each Compute API version is tricky for url-map tests.

2021-09-28 21:57 UTC, lidizheng commented
Test ad-hoc Kokoro run passed.

2021-09-28 22:27 UTC, sergiitk approved these changes
LGTM

2021-09-28 22:27 UTC, sergiitk commented on tools/run_tests/xds_k8s_test_driver/framework/infrastructure/traffic_director.py
> +        compute_api_version: Optional[str] = None,
Should be fine to have a default here too.

```suggestion
        compute_api_version: str = 'v1',
```

2021-09-28 22:27 UTC, sergiitk commented on tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/compute.py
> +        # Version maybe also be v1alpha or v1beta
For now we don't support `v1beta` in GcpApiManager. I think we can skip this comment.
```suggestion
```

2021-09-28 22:32 UTC, sergiitk commented
Thank you so much for making the change with the alpha compute!

2021-09-28 22:55 UTC, merged

2021-09-29 18:42 UTC, dapengzhang0 commented
@lidizheng @sergiitk , this PR seems to cause PSM security tests failing. Can you PTAL? b/201535750