Resource cache replaces with 3 level map: most tests pass
grpc/grpc pull request #27570
Opened 2021-10-03 23:09 UTC by donnadionne

2021-10-04 06:50 UTC, donnadionne commented
Refactored the resource cache to 3 levels.

Moved connecting to xds server from constructor to Subscribe (this did cause one test to no longer pass which I think is expected)

2021-10-04 17:32 UTC, markdroth requested changes
This looks like a good start!

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27570#-:-MlBLltH6dKrm4x0yE2N:bntdxje)* status: all files reviewed, 16 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_client.h, line 88 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlB20rZ6AAe53hy0IA5:-MlB20rZ6AAe53hy0IA6:b-j4e5i4) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.h#L88)):*
> ```objc
>                                               grpc_error_handle* error);
> 
>   static std::string GetAuthorityFromName(absl::string_view name);
> ```

These methods are not needed outside of `XdsClient`, so they should not be part of its public API.  Ideally, they can just be standalone functions in an anonymous namespace in the .cc file.  If that won't work for some reason, let's at least make them private methods.
___
*[src/core/ext/xds/xds_client.h, line 208 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlBBkW83NGe3uflIfpx:-MlBBkW83NGe3uflIfpy:boyt11t) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.h#L208)):*
> ```objc
>   // channel.  Holds a ref to the xds client object.
>   //
>   // Currently, there is only one ChannelState object per XdsClient
> ```

This paragraph can go away now.
___
*[src/core/ext/xds/xds_client.h, line 212 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlBBjUU9aT4i6z9ZzjO:-MlBBjUU9aT4i6z9ZzjP:b-1cdsd6) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.h#L212)):*
> ```objc
>   // future, when we add federation support, a single XdsClient may have
>   // multiple underlying channels to talk to different xDS servers.
>   class ChannelState : public InternallyRefCounted<ChannelState> {
> ```

This class will need to change from `InternallyRefCounted<>` to `DualRefCounted<>`, since it will now have multiple external owners (one for each authority that uses a given xDS server).

All existing `RefCountedPtr<>`s for this should be changed to `WeakRefCountedPtr<>`s, and all existing `Ref()`s should be changed to `WeakRef()`s.  The strong refs will be held in the authorities, as described in my comments below.
___
*[src/core/ext/xds/xds_client.h, line 255 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlB2N8-13QR9kOPU4RN:-MlB2N8-13QR9kOPU4RO:b3cuvdc) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.h#L255)):*
> ```objc
> 
>     // The channel and its status.
>     grpc_channel* channel_ = nullptr;
> ```

This should not need to be initialized to nullptr.  It should be set unconditionally by the ctor.
___
*[src/core/ext/xds/xds_client.h, line 331 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlB9Egq3UM6YsYZusp3:-MlB9Egq3UM6YsYZusp4:bkw7zbd) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.h#L331)):*
> ```objc
> 
>   // The channel for communicating with the xds server.
>   OrphanablePtr<ChannelState> chand_ ABSL_GUARDED_BY(mu_);
> ```

This should be replaced with:

```
// Map of existing xDS server channels.
std::map<XdsBootstrap::XdsServer, ChannelState*> xds_server_channel_map_;
```

The first time we subscribe to a resource for a given authority, we should look up the authority's `XdsServer` entry in this map.  If the entry already exists, we take a new (strong) ref to the `ChannelState` object and store it in the authority's entry in the cache map (see next comment).  If the entry does not already exist, we create a new `ChannelState` object, and we store a pointer to that object in this map.

In `ChannelState::Orphan()` (which is called when all strong refs have been removed), the entry for the `ChannelState` object should be removed from this map.
___
*[src/core/ext/xds/xds_client.h, line 333 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlB9a447EJAePlYPRjc:-MlB9a447EJAePlYPRjd:bg756uw) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.h#L333)):*
> ```objc
>   OrphanablePtr<ChannelState> chand_ ABSL_GUARDED_BY(mu_);
> 
>   struct ResourceMap {
> ```

Suggest calling this `AuthorityState`.

This will need two additional fields:
1. The `XdsBootstrap::XdsServer` for the authority.  This should be set when the `XdsClient` is instantiated.
2. A `RefCountedPtr<ChannelState>`.  This can initially be unset; the first time we subscribe to a resource for this authority, we can look up the `XdsServer` entry in `xds_server_channel_map_`, as I described above.
___
*[src/core/ext/xds/xds_client.cc, line 236 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlB8vQ_1YnkL-4CjvOu:-MlB8vQ_1YnkL-4CjvOv:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.cc#L236)):*
> ```cpp
>                                      ->resource_map_[authority]
>                                      .endpoint_map[resource_name];
>           ;
> ```

Please remove.
___
*[src/core/ext/xds/xds_client.cc, line 563 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlBFO_a0kCpuRBuzKjg:-MlBFO_a0kCpuRBuzKjh:b7yciys) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.cc#L563)):*
> ```cpp
>                                               const std::string& name) {
>   if (channel_ == nullptr) {
>     channel_ = CreateXdsChannel(xds_client_->args_, server_);
> ```

This should move back into the `ChannelState` ctor.  Instead of creating an empty `ChannelState` object initially and creating its channel later, we should simply wait to create the `ChannelState` object until we need it.
___
*[src/core/ext/xds/xds_client.cc, line 754 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlB8Oqo9KqQ8IY1XFcO:-MlB8Oqo9KqQ8IY1XFcP:b-lpq8zg) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.cc#L754)):*
> ```cpp
>     for (const auto& l : a.second.listener_map) {
>       std::string listener_name_str(l.first);
>       if (absl::StartsWith(l.first, "xdstp:")) {
> ```

I suggest moving this check into `ConstructFullResourceName()`, so that it will just return the right name for both old-style and new-style names.
___
*[src/core/ext/xds/xds_client.cc, line 1268 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlBHXsC2pLNdFfuyAyr:-MlBHXsDA42Hka_mkQ_F:b-xz5l62) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.cc#L1268)):*
> ```cpp
> void XdsClient::ChannelState::AdsCallState::RejectAdsUpdateLocked(
>     grpc_millis update_time, const XdsApi::AdsParseResult& result,
>     std::map<std::string, ResourceMap>* resource_map) {
> ```

This parameter is not needed; this method can directly reference `xds_client()->resource_map_`.
___
*[src/core/ext/xds/xds_client.cc, line 1283 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlBH0JMDtwIttM5WeFx:-MlBGWCa0qTnSTTB-k3m:bpcxstj) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.cc#L1283)):*
> ```cpp
>     if (authority_it == resource_map->end()) continue;
>     if (result.type_url == XdsApi::kLdsTypeUrl) {
>       auto resource_it = authority_it->second.listener_map.find(resource_name);
> ```

This part can still be templatized to avoid code duplication.

```
template <typename StateMap>
void XdsClient::ChannelState::AdsCallState::RejectAdsUpdateHelperLocked(
    const std::string& resource_name, grpc_millis update_time,
    const XdsApi::AdsParseResult& result, StateMap* state_map) {
  auto it = state_map->find(resource_name);
  if (it == state_map->end()) r [...]

2021-10-12 08:22 UTC, markdroth requested changes
Looks like this is making progress!

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27570#-:-MlnaAQsEx9X2ABXx_-G:bpp5ylu)* status: all files reviewed, 36 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_bootstrap.h, line 67 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-MllX7Ps-uf184x5_bRV:-MllX7Ps-uf184x5_bRW:b-eikgfd) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_bootstrap.h#L67)):*
> ```objc
>     std::set<std::string> server_features;
> 
>     std::string ToString() const {
> ```

I don't think this is needed.  Instead, we should implement `operator<()`, so that `XdsServer` can directly be used as a map key.
___
*[src/core/ext/xds/xds_client.h, line 320 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-Mllb_8LBT0v_miQ-61R:-Mllb_8LBT0v_miQ-61S:b-jzur7d) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.h#L320)):*
> ```objc
> 
>   // Map of existing xDS server channels.
>   // std::map<std::string, WeakRefCountedPtr<ChannelState>>
> ```

This commented-out definition can go away.
___
*[src/core/ext/xds/xds_client.h, line 322 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-MllbcoO50E8NUv3cS1c:-MllbcoO50E8NUv3cS1d:b-pclu29) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.h#L322)):*
> ```objc
>   // std::map<std::string, WeakRefCountedPtr<ChannelState>>
>   // xds_server_channel_map_;
>   std::map<std::string, ChannelState*> xds_server_channel_map_
> ```

The key to this map should be `XdsBootstrap::XdsServer`.  As I mentioned elsewhere, to make that work, we'll need to define an `operator<()` method on the `XdsServer` struct so that `std::map<>` knows how to order the keys.
___
*[src/core/ext/xds/xds_client.h, line 326 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-MlnO0pH8LfpDILGMP0q:-MlnO0pI6QyhhSlQ60RR:b4f1unk) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.h#L326)):*
> ```objc
> 
>   struct AuthorityState {
>     XdsBootstrap::XdsServer xds_server;
> ```

I guess this field isn't actually going to be used until the PR that adds the bootstrap parsing, so I guess let's remove it for now, and we can add it as part of that PR.
___
*[src/core/ext/xds/xds_client.h, line 327 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-Mllc12r3hDsPvonGtWR:-Mllc12r3hDsPvonGtWS:brp0ws4) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.h#L327)):*
> ```objc
>   struct AuthorityState {
>     XdsBootstrap::XdsServer xds_server;
>     RefCountedPtr<ChannelState> chand;
> ```

Please call this `channel_state`.
___
*[src/core/ext/xds/xds_client.h, line 335 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-MlnLFT-9B3PmUTd-9Mq:-MlnLFT-9B3PmUTd-9Mr:b-y1b83a) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.h#L335)):*
> ```objc
>   };
> 
>   std::map<std::string /*authority*/, AuthorityState> authority_state_
> ```

Please call this `authority_state_map_`.
___
*[src/core/ext/xds/xds_client.cc, line 2035 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlnKzLfEXEu7vt_jhTP:-MlnKzLfEXEu7vt_jhTQ:bjdijcj) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.cc#L2035)):*
> ```cpp
>     shutting_down_ = true;
>     // Orphan ChannelState object.
>     chand_.reset();
> ```

We should instead reset the `ChannelState` refs held in every entry in `authority_state_map_`.
___
*[src/core/ext/xds/xds_client.cc, line 2092 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlBKRlIArn8Q-RZFpLG:-MlnRrVCDgu97Egz2A4B:br09g99) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.cc#L2092)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i am putting a Unref in ChannelState::Unsubscribe, i think it's the right place and just 1 place will work for all.  Let me know if this is not correct
</blockquote></details>

No, that isn't right, as per my comment elsewhere.  I think we need to do this here, because (a) this is the only place where we can tell whether we've unsubscribed to all resources in this particular authority, and (b) instead of just manually unreffing, we need to reset `authority_state.channel_state`.
___
*[src/core/ext/xds/xds_client.cc, line 83 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-MllcMe4EYL67ryuKvtG:-MllcMe4EYL67ryuKvtH:b6juvrj) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.cc#L83)):*
> ```cpp
>                                       absl::string_view name) {
>   if (absl::StartsWith(name, "xdstp:")) {
>     return absl::StrCat("xdstp://", std::string(authority), "/",
> ```

No need to explicitly convert the `absl::string_view` parameters to `std::string` on these 3 lines.  Both `absl::StrCat()` and `absl::StripPrefix()` can deal with `absl::string_view` inputs, so constructing a `std::string` is a needless allocation.
___
*[src/core/ext/xds/xds_client.cc, line 85 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-MllduPD6WvkLcJ4MMEP:-MllduPD6WvkLcJ4MMEQ:b-tkhpb1) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.cc#L85)):*
> ```cpp
>     return absl::StrCat("xdstp://", std::string(authority), "/",
>                         std::string(resource_type), "/",
>                         absl::StripPrefix(std::string(name), "xdstp:/"));
> ```

Why are we stripping off `"xdstp:/"` instead of just `"xdstp:"`?
___
*[src/core/ext/xds/xds_client.cc, line 87 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-MlnCVo06dJi3O7dnMy9:-MlnCVo06dJi3O7dnMyA:b7xr9tn) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.cc#L87)):*
> ```cpp
>                         absl::StripPrefix(std::string(name), "xdstp:/"));
>   } else {
>     return std::string(name);
> ```

This needs to strip off the `"old:"` prefix that should be added in `ParseResourceName()`.
___
*[src/core/ext/xds/xds_client.cc, line 99 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-MlldbZ85ikw-aOO2CAZ:-MlldbZ85ikw-aOO2CA_:baw5p0u) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.cc#L99)):*
> ```cpp
>   // Old-style names use the empty string for authority.
>   // ID is prefixed with "old:" to indicate that it's an old-style name.
>   // if (!absl::StartsWith(name, "xdstp:")) return ResourceNameFields{"",
> ```

Why are these two lines commented out?
___
*[src/core/ext/xds/xds_client.cc, line 102 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-Mlldf6B5KPxvDHQTg0S:-Mlldf6CEOMT58jQDXG-:b-pp86pf) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.cc#L102)):*
> ```cpp
>   // absl::StrCat("old:", name)};
>   if (!absl::StartsWith(name, "xdstp:"))
>     return ResourceNameFields{"", absl::StrCat(name)};
> ```

Always use braces around the body of an `if` statement if it's not on the same line, to avoid serious merge bugs.
___
*[src/core/ext/xds/xds_client.cc, line 109 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-MlnHQfYEsX8wsjfq36I:-MlnHQfYEsX8wsjfq36J:bo8bnf7) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xds_client.cc#L109)):*
> ```cpp
>   std::pair<absl::string_view, absl::string_view> path_parts =
>       absl::StrSplit(uri->path(), absl::MaxSplits('/', 1));
>   if (!absl::StartsWith(path_parts.first, "en [...]

2021-10-18 07:59 UTC, donnadionne reviewed
addressed all comments.

Found the cause of the crash, seems unrelated to this change (but the change exposed it).  Need to discuss on how best to fix ( i added comments and such in the review comments as base for discussion)

PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27570#-:-MmHP9KGEo2YFinGRwg7:b-db9z5a)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_bootstrap.h, line 68 at r4](https://reviewable.io/reviews/grpc/grpc/27570#-Mm3RKVB7joB2cLzxEqG:-MmAN-Dg15RnTYbgO7zI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e801afb89895ada09a7f8cbef916bec2d2868bd4/src/core/ext/xds/xds_bootstrap.h#L68)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Combining all of the strings this way is both inefficient and will yield incorrect results.  If one server has `{server_uri="x", channel_creds_type="yz"}` and another has `{server_uri="xy", channel_creds_type="z"}`, this algorithm would generate the same combined string "xyz" for both of them, so it would consider them equal, even though they're not.

Instead, please just compare the fields one at a time:

```
if (server_uri < other.server_uri) return true;
if (channel_creds_type < other.channel_creds_type) return true;
if (channel_creds_config.Dump() < other.channel_creds_config.Dump()) return true;
if (server_features < other.server_features) return true;
return false;
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.h, line 313 at r4](https://reviewable.io/reviews/grpc/grpc/27570#-Mm3Sq4PAkW00xbMZ4A9:-MmANIB2E2hu48a7i-LH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e801afb89895ada09a7f8cbef916bec2d2868bd4/src/core/ext/xds/xds_client.h#L313)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this up to line 288, right after `EndpointState`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.h, line 322 at r4](https://reviewable.io/reviews/grpc/grpc/27570#-Mm3Sutp8geFEbJA8a7h:-MmAOI742gpdNc2EeD06:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e801afb89895ada09a7f8cbef916bec2d2868bd4/src/core/ext/xds/xds_client.h#L322)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be a method on `AuthorityState`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2035 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlnKzLfEXEu7vt_jhTP:-MmHFcZwEqCOsuAg9Inl:b-1qql69) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.cc#L2035)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't know what's causing that, so you'll have to debug it.

To be fair, releasing the ref to the `ChannelState` object here is just a safety check: the caller should not be releasing its ref to the `XdsClient` without cancelling its watches first, and cancelling the last watch for an authority should release the ref to the `ChannelState` object automatically (due to the code you added in the `Cancel*()` methods), so by the time we get here, the authority's `channel_state` field should always be null already.  But if adding the code is triggering a bug, then clearly something is wrong here, so we need to figure out what.
</blockquote></details>

you are right, doing the reset is not the problem. and i verified that ChannelState is being unreffed at CancelWatch (last watch)

For this crash, it seems that for some reason adding this bit of code (or even adding debug code) exposed another problem:

when we enter this Orphan method, g_mu could already be nullptr and we are doing 
  {
    MutexLock lock(g_mu);
    if (g_xds_client == this) g_xds_client = nullptr;
  }


I have trace that shows this at the end of a test (after test passes and all):

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (3087 ms total)
[  PASSED  ] 1 test.
D1018 07:11:11.558060596      21 init.cc:180]                grpc_shutdown starts clean-up now
I1018 07:11:11.558269326      21 xds_client.cc:2614]         donna global shutdown called???
E1018 07:11:11.560176872      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x7f38cfa01f53 grpc_core::XdsClientGlobalShutdown()
E1018 07:11:11.560293758      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x7f38cfbb8d94 grpc_shutdown_internal_locked()
E1018 07:11:11.560341783      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x7f38cfbb9056 grpc_shutdown
E1018 07:11:11.560972916      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x452a97 main
E1018 07:11:11.561018153      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x7f38cdfdd840 __libc_start_main
E1018 07:11:11.563341268      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x7f38cdfac228 (unknown)
I1018 07:11:11.563477533      21 xds_client.cc:2025]         donna in XdsClient::Orphan
E1018 07:11:11.565331282      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf9fbaca grpc_core::XdsClient::Orphan()
E1018 07:11:11.565450528      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cfa08ba9 grpc_core::(anonymous namespace)::XdsClientArgDestroy()
E1018 07:11:11.565670390      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf43a0d0 grpc_channel_args_destroy()
E1018 07:11:11.565826561      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf5376a0 grpc_core::SubchannelKey::~SubchannelKey()
E1018 07:11:11.565947751      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf534a9b grpc_core::Subchannel::~Subchannel()
E1018 07:11:11.566062021      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf534bae grpc_core::Subchannel::~Subchannel()
E1018 07:11:11.566175889      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf535d01 grpc_core::Subchannel::OnRetryAlarm()
E1018 07:11:11.566261770      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf3e8af9 grpc_core::ExecCtx::Flush()
E1018 07:11:11.566450138      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf45dd22 grpc_iomgr_shutdown()
E1018 07:11:11.566518400      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cfbb8d9b grpc_shutdown_internal_locked()
E1018 07:11:11.566530260      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cfbb9056 grpc_shutdown
E1018 07:11:11.566535567      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x452a97 main
E1018 07:11:11.566541018      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cdfdd840 __libc_start_main
E1018 07:11:11.568873487      21 xds_client.cc:2034]         XdsClient::Orphan stack 0xa3f (unknown)
I1018 07:11:11.568891615      21 xds_client.cc:2037]         [xds_client 0x1483300] shutting down xds client
I1018 07:11:11.568895724      21 xds_client.cc:2043]         donna in XdsClient::Orphan after first lock
I1018 07:11:11.568901956      21 xds_client.cc:2018]         [xds_client 0x1483300] destroying xds client
I1018 07:11:11.569290375      21 test_config.cc:206]         TestEnvironment ends

So the problem is exactly as the backtrace complains, the mutex lock is seg faulting coz g_mu is nullptr

I am not sure what the best fix is for this.  what i have right now does not pass tsan build, there is a deadlock in tsan build between CreateXdsChannel and XdsClient::Orphan

I tried a couple of things like setting g_xds_client = nullptr in global shutdown but that also caused a deadlock in tsan build between CreateXdsChannel and XdsClient::Orphan
___
*[src/core/ext/xds/xds_client.cc, line 575 at r2](https://reviewable.io/reviews/grpc/grpc/27570#-MlnF1G_8Zq9CdpiVQgM:-MmAIv1pAgWZ_ufX_BUQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/73ea426bb09e83532ba0fc0e1f8ad4527798ee23/src/core/ext/xds/xd [...]

2021-10-18 16:23 UTC, markdroth requested changes
This is getting closer!

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27570#-:-MmJCoOx0-IsBCOHl4uK:b79zqk9)* status: all files reviewed, 15 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_api.h, line 45 at r6](https://reviewable.io/reviews/grpc/grpc/27570#-MmJ5G336i6zKq8jqvku:-MmJ5G342WkIYI6VHhqS:b1t5lsh) ([raw file](https://github.com/grpc/grpc/blob/905d24b9719e407ce3ea30b167f78939c7c88608/src/core/ext/xds/xds_api.h#L45)):*
> ```objc
> namespace grpc_core {
> 
> struct ResourceNameFields {
> ```

Please move this inside of the `XdsApi` class.
___
*[src/core/ext/xds/xds_api.h, line 45 at r6](https://reviewable.io/reviews/grpc/grpc/27570#-MmJ79jiCo0aTTTBAzKv:-MmJ79jiCo0aTTTBAzKw:byyk516) ([raw file](https://github.com/grpc/grpc/blob/905d24b9719e407ce3ea30b167f78939c7c88608/src/core/ext/xds/xds_api.h#L45)):*
> ```objc
> namespace grpc_core {
> 
> struct ResourceNameFields {
> ```

Suggest renaming this to just `ResourceName`.
___
*[src/core/ext/xds/xds_api.h, line 53 at r6](https://reviewable.io/reviews/grpc/grpc/27570#-MmJ5IVy3LzfcvMRqj1A:-MmJ5IVy3LzfcvMRqj1B:b-vn5a0f) ([raw file](https://github.com/grpc/grpc/blob/905d24b9719e407ce3ea30b167f78939c7c88608/src/core/ext/xds/xds_api.h#L53)):*
> ```objc
> // id> pair.  Optionally the parser can check the resource type portion of the
> // resource name.
> absl::StatusOr<ResourceNameFields> ParseResourceName(
> ```

This should be a static member of the `XdsApi` class.
___
*[src/core/ext/xds/xds_api.cc, line 3420 at r6](https://reviewable.io/reviews/grpc/grpc/27570#-MmJ5y-K95rfIvTSz92l:-MmJ5y-K95rfIvTSz92m:b-avox2x) ([raw file](https://github.com/grpc/grpc/blob/905d24b9719e407ce3ea30b167f78939c7c88608/src/core/ext/xds/xds_api.cc#L3420)):*
> ```cpp
>     std::string resource_name =
>         UpbStringToStdString(proto_resource_name_function(resource));
>     auto resource_name_status = ParseResourceName(resource_name);
> ```

Let's change this function (`AdsResponseParse()`) to take the expected resource type as a parameter, and then pass that in here, so that we'll NACK if the resource type encoded in the resource name does not match the type that we're parsing here.
___
*[src/core/ext/xds/xds_client.h, line 318 at r6](https://reviewable.io/reviews/grpc/grpc/27570#-MmJ864lC3vOUagZ0Hjm:-MmJ864mApYeIOKzuHS3:b-u5lpph) ([raw file](https://github.com/grpc/grpc/blob/905d24b9719e407ce3ea30b167f78939c7c88608/src/core/ext/xds/xds_client.h#L318)):*
> ```objc
>   // Stores watchers for invalid resource names, we need to make sure these
>   // watchers are not destroyed until caller cancels them.
>   struct InvalidResourceWatchers {
> ```

There's not really any value in having a struct here, since it's only ever used in one place.  I think we can just inline these fields directly in `XdsClient`.
___
*[src/core/ext/xds/xds_client.h, line 340 at r6](https://reviewable.io/reviews/grpc/grpc/27570#-MmJAeM87n_2DFwsl6IN:-MmJAeM87n_2DFwsl6IO:bg54lw1) ([raw file](https://github.com/grpc/grpc/blob/905d24b9719e407ce3ea30b167f78939c7c88608/src/core/ext/xds/xds_client.h#L340)):*
> ```objc
>       ABSL_EXCLUSIVE_LOCKS_REQUIRED(mu_);
> 
>   RefCountedPtr<ChannelState> GetOrCreateChannelState(
> ```

This should have a `Locked` suffix and have an `ABSL_EXCLUSIVE_LOCKS_REQUIRED(mu_)` annotation.
___
*[src/core/ext/xds/xds_client.h, line 369 at r6](https://reviewable.io/reviews/grpc/grpc/27570#-MmJ8CjfERMsfQISOWlj:-MmJ8CjfERMsfQISOWlk:b-xvritf) ([raw file](https://github.com/grpc/grpc/blob/905d24b9719e407ce3ea30b167f78939c7c88608/src/core/ext/xds/xds_client.h#L369)):*
> ```objc
>       ABSL_GUARDED_BY(mu_);
> 
>   InvalidResourceWatchers invalid_resource_watchers_;
> ```

This needs a `ABSL_GUARDED_BY(mu_)` annotation.

(This comment applies to each of the individual maps within the struct if you remove the struct as I suggested above.)
___
*[src/core/ext/xds/xds_client.cc, line 2035 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlnKzLfEXEu7vt_jhTP:-MmJBVcl0ppnZ0DK9Eyl:bqdsytn) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.cc#L2035)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

you are right, doing the reset is not the problem. and i verified that ChannelState is being unreffed at CancelWatch (last watch)

For this crash, it seems that for some reason adding this bit of code (or even adding debug code) exposed another problem:

when we enter this Orphan method, g_mu could already be nullptr and we are doing 
  {
    MutexLock lock(g_mu);
    if (g_xds_client == this) g_xds_client = nullptr;
  }


I have trace that shows this at the end of a test (after test passes and all):

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (3087 ms total)
[  PASSED  ] 1 test.
D1018 07:11:11.558060596      21 init.cc:180]                grpc_shutdown starts clean-up now
I1018 07:11:11.558269326      21 xds_client.cc:2614]         donna global shutdown called???
E1018 07:11:11.560176872      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x7f38cfa01f53 grpc_core::XdsClientGlobalShutdown()
E1018 07:11:11.560293758      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x7f38cfbb8d94 grpc_shutdown_internal_locked()
E1018 07:11:11.560341783      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x7f38cfbb9056 grpc_shutdown
E1018 07:11:11.560972916      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x452a97 main
E1018 07:11:11.561018153      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x7f38cdfdd840 __libc_start_main
E1018 07:11:11.563341268      21 xds_client.cc:2623]         XdsClientGlobalShutdown stack 0x7f38cdfac228 (unknown)
I1018 07:11:11.563477533      21 xds_client.cc:2025]         donna in XdsClient::Orphan
E1018 07:11:11.565331282      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf9fbaca grpc_core::XdsClient::Orphan()
E1018 07:11:11.565450528      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cfa08ba9 grpc_core::(anonymous namespace)::XdsClientArgDestroy()
E1018 07:11:11.565670390      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf43a0d0 grpc_channel_args_destroy()
E1018 07:11:11.565826561      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf5376a0 grpc_core::SubchannelKey::~SubchannelKey()
E1018 07:11:11.565947751      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf534a9b grpc_core::Subchannel::~Subchannel()
E1018 07:11:11.566062021      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf534bae grpc_core::Subchannel::~Subchannel()
E1018 07:11:11.566175889      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf535d01 grpc_core::Subchannel::OnRetryAlarm()
E1018 07:11:11.566261770      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf3e8af9 grpc_core::ExecCtx::Flush()
E1018 07:11:11.566450138      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cf45dd22 grpc_iomgr_shutdown()
E1018 07:11:11.566518400      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cfbb8d9b grpc_shutdown_internal_locked()
E1018 07:11:11.566530260      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cfbb9056 grpc_shutdown
E1018 07:11:11.566535567      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x452a97 main
E1018 07:11:11.566541018      21 xds_client.cc:2034]         XdsClient::Orphan stack 0x7f38cdfdd840 __libc_start_main
E1018 07:11:11.568873487      21 xds_client.cc:2034]         XdsClient::Orphan stack 0xa3f (unknown)
I1018 07:11:11.568891615      21 xds_client.cc:2037]         [xds_client 0x1483300] shutting down xds client
I1018 07:11:11.568895724      21 xds_client.cc:2043]         donna in XdsClient::Orphan after first lock
I1018 07:11:11.568 [...]

2021-10-20 08:11 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27570)* status: 2 of 6 files reviewed, 15 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_client.cc, line 2035 at r1](https://reviewable.io/reviews/grpc/grpc/27570#-MlnKzLfEXEu7vt_jhTP:-MmRkCcy4gxUokQLVWF6:b-eiwsop) ([raw file](https://github.com/grpc/grpc/blob/ef86a819e028949c2f7df3f69e172ac7daf3b3fb/src/core/ext/xds/xds_client.cc#L2035)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Ok, i think i see the problem.

***
old code we do all the following cleanup steps after test is done, triggered by

E1020 06:46:38.595915279      37 xds_client.cc:1965]         XdsClient orphan stack 0x7fec7151a869 grpc_core::(anonymous namespace)::XdsClientArgDestroy()
E1020 06:46:38.596272650      37 xds_client.cc:1965]         XdsClient orphan stack 0x7fec70f41480 grpc_channel_args_destroy()
E1020 06:46:38.596568888      37 xds_client.cc:1965]         XdsClient orphan stack 0x7fec71097740 grpc_core::SubchannelKey::~SubchannelKey()
E1020 06:46:38.597507826      37 xds_client.cc:1965]         XdsClient orphan stack 0x7fec7109490b grpc_core::Subchannel::~Subchannel()
E1020 06:46:38.597840233      37 xds_client.cc:1965]         XdsClient orphan stack 0x7fec71094a1e grpc_core::Subchannel::~Subchannel()
E1020 06:46:38.598722284      37 xds_client.cc:1965]         XdsClient orphan stack 0x7fec71095c2d grpc_core::Subchannel::OnRetryAlarm()
E1020 06:46:38.598976093      37 xds_client.cc:1965]         XdsClient orphan stack 0x7fec70ed2af9 grpc_core::ExecCtx::Flush()
E1020 06:46:38.599172392      37 xds_client.cc:1965]         XdsClient orphan stack 0x7fec70f77e51 timer_thread()

the cleanup steps are:

1. XdsClient::Orphan
2. ChannelState::Orphan
3. ChannelState::~ChannelState
4. XdsClient::~XdsClient
D1020 06:46:38.616919318      37 init.cc:186]                grpc_shutdown spawns clean-up thread
5. grpc_core::XdsClientGlobalShutdown()

Notice that ChannelState::~ChannelState does
grpc_channel_destroy(channel_);

which I believe will trigger destroy_channel and grpc_shutdown in the same thread.

***

New code we added the when there are no more subscribers we will reset ChannelState in Authority Map which contains the strong ref. 

So basically a cancel of a watch can result in ChannelState::Orphan()
And then all weak ref to ChannelState are gone, so ChannelState::~ChannelState is pretty much called right away.
This triggers grpc_channel_destroy(channel_); which will then trigger destroy_channel and grpc_shutdown in the same thread.

grpc_shutdown will null g_mu 

So when XdsClient::Orphan gets called in grpc_shutdown thread, we hit that crash as g_mu is null.

So maybe the solution is like you suggested: never delete the g_mu?





</blockquote></details>

basically new code i see this sequence
1. ChannelState::Orphan
2. ChannelState::~ChannelState
3. grpc_core::XdsClientGlobalShutdown()
4. XdsClient::Orphan -> Leads to crash


<!-- Sent from Reviewable.io -->

2021-10-29 21:07 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27570)* status: 2 of 7 files reviewed, 18 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 3408 at r12](https://reviewable.io/reviews/grpc/grpc/27570#-Mn62EqHCMDinrHZc-wU:-MnCsG6aE8Q0AFWwuMb4:b-pw3qej) ([raw file](https://github.com/grpc/grpc/blob/758ad79f812942d6afe2b99b5d7c08ea6c0322e8/src/core/ext/xds/xds_api.cc#L3408)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

then i am basicaly rewritting ParseResourceName and not reusing a lot of parseResourceNameInternal. So maybe we will just have  2 versions of ParseResourceName with some common code refactored out?
</blockquote></details>

ok, using std::function?


<!-- Sent from Reviewable.io -->

2021-11-01 17:21 UTC, markdroth requested changes
This looks great!  Remaining comments are all minor cosmetic things.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 5 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27570#-:-MnRW4l33eFOcWEMPP7r:b-p8xhi)* status: all files reviewed, 3 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_api.cc, line 3408 at r12](https://reviewable.io/reviews/grpc/grpc/27570#-Mn62EqHCMDinrHZc-wU:-MnRLomDCaqCK15yy6CS:b-849bqo) ([raw file](https://github.com/grpc/grpc/blob/758ad79f812942d6afe2b99b5d7c08ea6c0322e8/src/core/ext/xds/xds_api.cc#L3408)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

ok, using std::function?
</blockquote></details>

Yes, using `std::function<>` is fine.  This looks good.
___
*[src/core/ext/xds/xds_api.cc, line 877 at r14](https://reviewable.io/reviews/grpc/grpc/27570#-MnRKp5b49HKdnW9wtUq:-MnRKp5b49HKdnW9wtUr:b45kyq2) ([raw file](https://github.com/grpc/grpc/blob/400c798722f0749e444fab79d30dd543b8711cb8/src/core/ext/xds/xds_api.cc#L877)):*
> ```cpp
>   std::pair<absl::string_view, absl::string_view> path_parts =
>       absl::StrSplit(uri->path(), absl::MaxSplits('/', 1));
>   if (!((is_expected_type)(path_parts.first, nullptr))) {
> ```

The additional parens here make this harder to read.  This can just be:

```
if (!is_expected_type(path_parts.first, nullptr)) {
```
___
*[src/core/ext/xds/xds_api.cc, line 967 at r14](https://reviewable.io/reviews/grpc/grpc/27570#-MnRLS3p64iHtJDJ8FOC:-MnRLS3p64iHtJDJ8FOD:bkbllj3) ([raw file](https://github.com/grpc/grpc/blob/400c798722f0749e444fab79d30dd543b8711cb8/src/core/ext/xds/xds_api.cc#L967)):*
> ```cpp
>   return ParseResourceNameInternal(
>       name,
>       (std::function<bool(absl::string_view, bool*)>)[is_expected_type](
> ```

No need for the cast here (and if there was, it shouldn't be a C-style cast).  This can just be:

```
return ParseResourceNameInternal(
    name,
    [is_expected_type](absl::string_view type, bool*) { return is_expected_type(type); });
```
___
*[src/core/ext/xds/xds_client.cc, line 2021 at r14](https://reviewable.io/reviews/grpc/grpc/27570#-MnRVY-_8VSNd0195tFE:-MnRVY-_8VSNd0195tFF:bcf0bpc) ([raw file](https://github.com/grpc/grpc/blob/400c798722f0749e444fab79d30dd543b8711cb8/src/core/ext/xds/xds_client.cc#L2021)):*
> ```cpp
>     gpr_log(GPR_INFO, "[xds_client %p] creating xds client", this);
>   }
>   grpc_init();
> ```

Please add a comment here that we call grpc_init() here and grpc_shutdown() in the dtor to make sure that gRPC does not shut down until the XdsClient is destroyed.


<!-- Sent from Reviewable.io -->

2021-11-01 20:23 UTC, donnadionne commented
known issue #27892

2021-11-01 20:28 UTC, donnadionne commented
know issue #27901

2021-11-01 20:29 UTC, donnadionne reviewed
thank you for all your help!  almost here :). PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27570#-:-MnSBBnmDWONXB-W6Hsu:b-up8j82)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 877 at r14](https://reviewable.io/reviews/grpc/grpc/27570#-MnRKp5b49HKdnW9wtUq:-MnS9I2EBjxbLEaeDtsQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/400c798722f0749e444fab79d30dd543b8711cb8/src/core/ext/xds/xds_api.cc#L877)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The additional parens here make this harder to read.  This can just be:

```
if (!is_expected_type(path_parts.first, nullptr)) {
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 967 at r14](https://reviewable.io/reviews/grpc/grpc/27570#-MnRLS3p64iHtJDJ8FOC:-MnS9JVl0oyB_9Orrq2v:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/400c798722f0749e444fab79d30dd543b8711cb8/src/core/ext/xds/xds_api.cc#L967)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the cast here (and if there was, it shouldn't be a C-style cast).  This can just be:

```
return ParseResourceNameInternal(
    name,
    [is_expected_type](absl::string_view type, bool*) { return is_expected_type(type); });
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2021 at r14](https://reviewable.io/reviews/grpc/grpc/27570#-MnRVY-_8VSNd0195tFE:-MnS9kmr6Gjdj51G_EWK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/400c798722f0749e444fab79d30dd543b8711cb8/src/core/ext/xds/xds_client.cc#L2021)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a comment here that we call grpc_init() here and grpc_shutdown() in the dtor to make sure that gRPC does not shut down until the XdsClient is destroyed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-01 20:53 UTC, markdroth approved these changes
This looks fantastic!

> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27570#-:-MnSGg1iD9TAoPux9dcL:bcpuwtr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donnadionne)



<!-- Sent from Reviewable.io -->

2021-11-01 23:32 UTC, merged