Support RDS updates on the server
grpc/grpc pull request #27851
Opened 2021-10-28 15:56 UTC by yashykt

Note that graceful shutdown is still remaining.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc/27851)

2021-10-30 00:04 UTC, markdroth requested changes
Here's my partial review, as we discussed.  I haven't reviewed the tests yet.

Please let me know if you have any questions.  Thanks!

> Reviewed 22 of 25 files at r1, 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851#-:-MnDVgG5-rEDSaYaWooi:b-1d2y1f)* status: 24 of 25 files reviewed, 27 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 625 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7XwJDAI8Kxc1hstjQ:-Mn7XwJDAI8Kxc1hstjR:b-sclm3l) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L625)):*
> ```cpp
>     GetCallConfigArgs args) {
>   for (const auto& entry : route_table_) {
>     // Path matching.
> ```

How about moving this route selection logic into the `XdsRouting` API as well, since it should be common between client and server?  The code for deciding what to do with the selected route will still be different, but the code to select the route itself could be the same.

What I'm thinking is that instead of having `XdsRouting` expose `HeadersMatch()` and `UnderFraction()`, we could instead have it expose a `GetRouteForRequest()` method.  This could work similar to the virtual host iteration interface that I suggested in xds_routing.h (see my comment there for details).  For example:

```
class RouteListIterator {
 public:
  virtual ~RouteListIterator() = default;
  // Number of routes.
  virtual size_t Size() const = 0;
  // Returns the matchers for the route at the specified index.
  virtual const XdsApi::Route::Matchers& GetMatchersForRoute(size_t index) const = 0;
};

// Returns the index in route_list_iterator to use for a request with
// the specified path and metadata, or nullopt if no route matches.
static absl::optional<size_t> GetRouteForRequest(
    RouteListIterator* route_list_iterator,
    absl::string_view path, grpc_metadata_batch* initial_metadata) {
  for (size_t i = 0; i < route_list_iterator->Size(); ++i) {
    const XdsApi::Route::Matchers& matchers =
        route_list_iterator->GetMatchersForRoute(i);
    if (matchers.path_matcher.Match(path) &&
        HeadersMatch(matchers.header_matchers, initial_metadata) &&
        (!matchers.fraction_per_million.has_value() ||
         UnderFraction(*matchers.fraction_per_million))) {
      return i;
    }
  }
  return absl::nullopt;
}
```
___
*[src/core/ext/xds/xds_api.cc, line 2329 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7X4_s7k9IR0tAdhD0:-Mn7X4_s7k9IR0tAdhD1:be3a34o) ([raw file](https://github.com/grpc/grpc/blob/2530c73d449961fd7ab61d6f3d38c8dddd36e517/src/core/ext/xds/xds_api.cc#L2329)):*
> ```cpp
>             "router", {kXdsHttpRouterFilterConfigName, Json()}});
>   }
>   // Guarding parsing of RouteConfig on the server side with the environmental
> ```

I think we still want this env var guard until all of the server-side pieces are in place.
___
*[src/core/ext/xds/xds_client.cc, line 870 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7XLT_2l5-RxJmmw4u:-Mn7XLTa6NmYFNJJ2gq6:b-slvu6h) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/xds/xds_client.cc#L870)):*
> ```cpp
>   auto& state = state_map_[type_url].subscribed_resources[name];
>   if (state == nullptr) {
>     state = MakeOrphanable<ResourceState>(type_url, name, false);
> ```

Let's merge #27860 before this PR, so we can get the right fix in place here.
___
*[src/core/ext/xds/xds_routing.h, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7T3iM9LeKX9y73ClL:-Mn7T3iM9LeKX9y73ClM:bwvq3dh) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/xds/xds_routing.h#L38)):*
> ```objc
>  public:
>   template <typename T>
>   static T* FindVirtualHostForDomain(std::vector<T>* virtual_hosts,
> ```

Instead of making this a template, how about defining an abstract interface for the virtual host object that this acts on:

```
class VirtualHostListIterator {
 public:
  virtual ~VirtualHostListIterator() = default;
  // Returns the number of virtual hosts in the list.
  virtual size_t Size() const = 0;
  // Returns the domain list for the virtual host at the specified index.
  virtual const std::set<std::string>& GetDomainsForVirtualHost(size_t index) const = 0;
};

// Returns the index of the selected virtual host in the list.
static absl::optional<size_t> FindVirtualHostForDomain(
    VirtualHostListIterator* vhost_iterator,
    absl::string_view domain) {
  absl::optional<size_t> target_index;
  for (size_t i = 0; i < vhost_iterator->Size(); ++i) {
    const std::set<std::string> domains = vhost_iterator->GetDomainsForVirtualHost(i);
    for (const std::string& domain_pattern : domains) {
      // ...update target_index instead of target_vhost...
    }
  }  
  return target_index;
}
```

Then callers can just wrap their lists of virtual hosts of whatever type in their own implementation of `VirtualHostListIterator`.
___
*[src/core/ext/xds/xds_routing.h, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7Tc-C-HPEhdzfcRDW:-Mn7Tc-C-HPEhdzfcRDX:b6blr6j) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/xds/xds_routing.h#L38)):*
> ```objc
>  public:
>   template <typename T>
>   static T* FindVirtualHostForDomain(std::vector<T>* virtual_hosts,
> ```

How about passing in `virtual_hosts` as a reference instead of a pointer, given that it should never be null?

(No longer relevant if you take my previous suggestion.)
___
*[src/core/ext/xds/xds_routing.h, line 99 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7WHFRAznvpN3THY_e:-Mn7WHFRAznvpN3THY_f:b-gimcm2) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/xds/xds_routing.h#L99)):*
> ```objc
> 
>  private:
>   enum MatchType {
> ```

All of this private stuff can be in an anonymous namespace in the .cc file, since it's all static anyway.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 50 at r3](https://reviewable.io/reviews/grpc/grpc/27851#-MnBaG2-8mcJEnBBG8ce:-MnBaG2-8mcJEnBBG8cf:b-5jfze8) ([raw file](https://github.com/grpc/grpc/blob/f0472bbd17735e9bc9d9777ca3fdbf3937a94c16/src/core/ext/xds/xds_server_config_fetcher.cc#L50)):*
> ```cpp
> class XdsServerConfigFetcher : public grpc_server_config_fetcher {
>  public:
>   class FilterChainMatchManager
> ```

There are a lot of classes here that interact with each other in complex ways, and it makes the code hard to understand for someone who is first approaching it.  I have a couple of suggestions to try to help future readers understand the code better.

First, where possible, I think it would make this code more readable to use forward declarations to move class definitions out of the enclosing class, like this:

```
class XdsServerConfigFetcher : public grpc_server_config_fetcher {
 public:
  class FilterChainMatchManager;  // Forward declaration.
  // ...other members...
};

class XdsServerConfigFetcher::FilterChainMatchManager
    : public grpc_server_config_fetcher::ConnectionManager {
 public:
  // ...members...
};
```

This makes it easier for the reader to see each class by itself, without having to understand each nested class at the same time.

Second, please add a comment before each class explaining what it is and how it interacts with other classes.  For example, for `FilterChainMatchManager`, you can say something like this:

"""
A connection manager used by the server listener code to inject channel args to be used for each incoming connection.  This implementation chooses the appropriate filter chain from the xDS Listener resource and injects channel args that configure the right mTLS certs and cause the right set of HTTP filters to be injected.
"""
___
*[src/core/ext/xds/xds_server_config_fetch [...]

2021-11-09 04:12 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851)* status: 3 of 27 files reviewed, 27 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 625 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7XwJDAI8Kxc1hstjQ:-Mo1qqzC1fpB5oDHN8JH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L625)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about moving this route selection logic into the `XdsRouting` API as well, since it should be common between client and server?  The code for deciding what to do with the selected route will still be different, but the code to select the route itself could be the same.

What I'm thinking is that instead of having `XdsRouting` expose `HeadersMatch()` and `UnderFraction()`, we could instead have it expose a `GetRouteForRequest()` method.  This could work similar to the virtual host iteration interface that I suggested in xds_routing.h (see my comment there for details).  For example:

```
class RouteListIterator {
 public:
  virtual ~RouteListIterator() = default;
  // Number of routes.
  virtual size_t Size() const = 0;
  // Returns the matchers for the route at the specified index.
  virtual const XdsApi::Route::Matchers& GetMatchersForRoute(size_t index) const = 0;
};

// Returns the index in route_list_iterator to use for a request with
// the specified path and metadata, or nullopt if no route matches.
static absl::optional<size_t> GetRouteForRequest(
    RouteListIterator* route_list_iterator,
    absl::string_view path, grpc_metadata_batch* initial_metadata) {
  for (size_t i = 0; i < route_list_iterator->Size(); ++i) {
    const XdsApi::Route::Matchers& matchers =
        route_list_iterator->GetMatchersForRoute(i);
    if (matchers.path_matcher.Match(path) &&
        HeadersMatch(matchers.header_matchers, initial_metadata) &&
        (!matchers.fraction_per_million.has_value() ||
         UnderFraction(*matchers.fraction_per_million))) {
      return i;
    }
  }
  return absl::nullopt;
}
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2329 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7X4_s7k9IR0tAdhD0:-Mo1tOJr3VP88dn90x3o:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2530c73d449961fd7ab61d6f3d38c8dddd36e517/src/core/ext/xds/xds_api.cc#L2329)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we still want this env var guard until all of the server-side pieces are in place.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_routing.h, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7T3iM9LeKX9y73ClL:-MnlF0DY7k8_aY27gcvx:b-yb4ltm) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/xds/xds_routing.h#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of making this a template, how about defining an abstract interface for the virtual host object that this acts on:

```
class VirtualHostListIterator {
 public:
  virtual ~VirtualHostListIterator() = default;
  // Returns the number of virtual hosts in the list.
  virtual size_t Size() const = 0;
  // Returns the domain list for the virtual host at the specified index.
  virtual const std::set<std::string>& GetDomainsForVirtualHost(size_t index) const = 0;
};

// Returns the index of the selected virtual host in the list.
static absl::optional<size_t> FindVirtualHostForDomain(
    VirtualHostListIterator* vhost_iterator,
    absl::string_view domain) {
  absl::optional<size_t> target_index;
  for (size_t i = 0; i < vhost_iterator->Size(); ++i) {
    const std::set<std::string> domains = vhost_iterator->GetDomainsForVirtualHost(i);
    for (const std::string& domain_pattern : domains) {
      // ...update target_index instead of target_vhost...
    }
  }  
  return target_index;
}
```

Then callers can just wrap their lists of virtual hosts of whatever type in their own implementation of `VirtualHostListIterator`.
</blockquote></details>

Templates seem more compact here since the types can already be iterated on. Suggestion taken anyway since the abstraction seems nice to have.
___
*[src/core/ext/xds/xds_routing.h, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7Tc-C-HPEhdzfcRDW:-Mo1n1vM0e0QJ4IMDx4y:b-xvbsib) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/xds/xds_routing.h#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about passing in `virtual_hosts` as a reference instead of a pointer, given that it should never be null?

(No longer relevant if you take my previous suggestion.)
</blockquote></details>

outdated
___
*[src/core/ext/xds/xds_routing.h, line 99 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7WHFRAznvpN3THY_e:-Mo1n74-95_18TrtmIMa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/xds/xds_routing.h#L99)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All of this private stuff can be in an anonymous namespace in the .cc file, since it's all static anyway.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 50 at r3](https://reviewable.io/reviews/grpc/grpc/27851#-MnBaG2-8mcJEnBBG8ce:-Mo1nA709H2L5QVwRbIt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f0472bbd17735e9bc9d9777ca3fdbf3937a94c16/src/core/ext/xds/xds_server_config_fetcher.cc#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There are a lot of classes here that interact with each other in complex ways, and it makes the code hard to understand for someone who is first approaching it.  I have a couple of suggestions to try to help future readers understand the code better.

First, where possible, I think it would make this code more readable to use forward declarations to move class definitions out of the enclosing class, like this:

```
class XdsServerConfigFetcher : public grpc_server_config_fetcher {
 public:
  class FilterChainMatchManager;  // Forward declaration.
  // ...other members...
};

class XdsServerConfigFetcher::FilterChainMatchManager
    : public grpc_server_config_fetcher::ConnectionManager {
 public:
  // ...members...
};
```

This makes it easier for the reader to see each class by itself, without having to understand each nested class at the same time.

Second, please add a comment before each class explaining what it is and how it interacts with other classes.  For example, for `FilterChainMatchManager`, you can say something like this:

"""
A connection manager used by the server listener code to inject channel args to be used for each incoming connection.  This implementation chooses the appropriate filter chain from the xDS Listener resource and injects channel args that configure the right mTLS certs and cause the right set of HTTP filters to be injected.
"""
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 101 at r3](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7t_IC9MlVhousi_7v:-Mo1nCKn6KpXD5SahbE2:b-bmmcts) ([raw file](https://github.com/grpc/grpc/blob/f0472bbd17735e9bc9d9777ca3fdbf3937a94c16/src/core/ext/xds/xds_server_config_fetcher.cc#L101)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Now that we're not exposing an L7-level watcher API as a part of the server config fetcher API (i.e., it's now invisible to all code except the code in this file), I don't think we actually need this to be an interface anymore.  At this point, it looks like the only users of this  [...]

2021-11-16 00:34 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851)* status: 0 of 27 files reviewed, 27 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_client.cc, line 870 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7XLT_2l5-RxJmmw4u:-Moa9bjgBVcfRUY6QEJH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/xds/xds_client.cc#L870)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's merge #27860 before this PR, so we can get the right fix in place here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-16 17:05 UTC, markdroth requested changes
This is looking really good!  Remaining comments are mostly minor things, no significant structural concerns.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 21 files at r5, 2 of 7 files at r6, 22 of 24 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851#-:-ModhIAg2ak09JpNKwAO:bmcldcw)* status: all files reviewed, 44 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 334 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_wsIY-tIyqnfov0q4:-Mo_wsIY-tIyqnfov0q5:bp10o41) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L334)):*
> ```cpp
>     : public XdsRouting::RouteListIterator {
>  public:
>   RouteListIterator(const RouteTable& route_table)
> ```

`explicit`
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 334 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_xYW_3gp-IT6jmdrZ:-Mo_xYW_3gp-IT6jmdr_:bcom9g1) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L334)):*
> ```cpp
>     : public XdsRouting::RouteListIterator {
>  public:
>   RouteListIterator(const RouteTable& route_table)
> ```

Suggest making this parameter and the corresponding data member be pointers instead of references, so emphasize that there is external ownership.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 565 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_xsYN2iJ1bUeLjyEp:-Mo_xsYN2iJ1bUeLjyEq:bapquht) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L565)):*
> ```cpp
>       RouteListIterator(route_table_), StringViewFromSlice(*args.path),
>       args.initial_metadata);
>   if (route_index.has_value()) {
> ```

Suggest handling the error case first, to keep the error condition and the error result next to each other, and to avoid unnecessary indentation for the rest of the function:

```
if (!route_index.has_value()) return CallConfig();
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 566 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_yAwKC0Bp2GIpyNDU:-Mo_yAwKC0Bp2GIpyNDV:birvchi) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L566)):*
> ```cpp
>       args.initial_metadata);
>   if (route_index.has_value()) {
>     auto& entry = route_table_[route_index.value()];
> ```

Can say `*route_index` here.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 748 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_yNXh2cyED7GiCj5F:-Mo_yNXh2cyED7GiCj5G:bd3uo4n) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L748)):*
> ```cpp
> 
> namespace {
> // TODO(): Should this be moved to xds_api.h?
> ```

No, I think this is the right place for it.  If we ever need to use it somewhere else, we can consider moving it at that point.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 751 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_yRxkAaK5-rOb3F71:-Mo_yRxkAaK5-rOb3F72:bp10o41) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L751)):*
> ```cpp
> class VirtualHostListIterator : public XdsRouting::VirtualHostListIterator {
>  public:
>   VirtualHostListIterator(
> ```

`explicit`
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 752 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_yWRk1XWp4VB8PU3-:-Mo_yWRk1XWp4VB8PU30:b-t8mfbc) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L752)):*
> ```cpp
>  public:
>   VirtualHostListIterator(
>       const std::vector<XdsApi::RdsUpdate::VirtualHost>& virtual_hosts)
> ```

Suggest making this parameter and the corresponding data member be a pointer instead of a reference, to emphasize that it's externally owned.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 785 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_ymd-00s4VqXSgl8Y:-Mo_ymd-00s4VqXSgl8Z:bslj6lh) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L785)):*
> ```cpp
>   // Save the virtual host in the resolver.
>   current_virtual_host_ =
>       std::move(rds_update.virtual_hosts[vhost_index.value()]);
> ```

Can use `*vhost_index` here.
___
*[src/core/ext/xds/xds_routing.h, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/27851#-Mn7T3iM9LeKX9y73ClL:-Mo_uMzX4aJ3B0C-kmTp:b-dt0vcx) ([raw file](https://github.com/grpc/grpc/blob/dbedc4040754c4005ed6664d4e6373457c9d15c3/src/core/ext/xds/xds_routing.h#L38)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Templates seem more compact here since the types can already be iterated on. Suggestion taken anyway since the abstraction seems nice to have.
</blockquote></details>

Thanks, this looks good.

The main reason I suggested this is that we've been getting a lot of user input lately about our binary size going up fairly quickly.  The more templated code we have, the more we multiply our binary size (because we generate the same code once for each unique template expansion).  Using this iterator interface avoids that problem.
___
*[src/core/ext/xds/xds_routing.h, line 81 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_vDML39zUzY46UVef:-Mo_vDML39zUzY46UVeg:bzp2pj) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_routing.h#L81)):*
> ```objc
>   struct GeneratePerHttpFilterConfigsResult {
>     std::map<std::string, std::vector<std::string>>
>         per_filter_configs;  // Map of field name to list of elements for that
> ```

Suggest moving these per-field comments to the line above the field they describe, since that should be more readable.
___
*[src/core/ext/xds/xds_routing.cc, line 98 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_vbOQ0U--dryqr6ZD:-Mo_vbOQ0U--dryqr6ZE:b-kms9ph) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_routing.cc#L98)):*
> ```cpp
> }  // namespace
> 
> absl::optional<size_t> XdsRouting::GetRouteForRequest(
> ```

Please define these methods in the same order in which they are defined in the .h file, and put the helper functions used by each one right before the method it's used by.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 73 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa-EBi0qsC0f5Ubt_j:-Moa-EBi0qsC0f5Ubt_k:b477d8i) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L73)):*
> ```cpp
> 
>   struct WatcherState {
>     std::string listening_address;
> ```

This field also exists in the object pointed to by `listener_watcher`.  Do we need it in both places?
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 85 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_zk20El3uRu3yDl12:-Mo_zk20El3uRu3yDl13:bcmfebb) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L85)):*
> ```cpp
> 
> // A watcher implementation for listening on LDS updates from the xDS control
> // plane. When a good LDS update is received, it creates FilterChainMa [...]

2021-11-17 18:27 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851)* status: 22 of 27 files reviewed, 44 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 334 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_wsIY-tIyqnfov0q4:-Moj5P8J3Fu4cYK-ULjN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L334)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`explicit`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 334 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_xYW_3gp-IT6jmdrZ:-Moj5P_mD84BvO68I6lZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L334)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest making this parameter and the corresponding data member be pointers instead of references, so emphasize that there is external ownership.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 565 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_xsYN2iJ1bUeLjyEp:-Moj5R9646jUs4vMrTqJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L565)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest handling the error case first, to keep the error condition and the error result next to each other, and to avoid unnecessary indentation for the rest of the function:

```
if (!route_index.has_value()) return CallConfig();
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 566 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_yAwKC0Bp2GIpyNDU:-Moj5Ry_A09useV9LmC8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L566)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can say `*route_index` here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 748 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_yNXh2cyED7GiCj5F:-Moj5TIg8a_EG0ehaoOa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L748)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No, I think this is the right place for it.  If we ever need to use it somewhere else, we can consider moving it at that point.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 751 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_yRxkAaK5-rOb3F71:-Moj5TmbA8SvADyFHSF1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L751)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`explicit`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 752 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_yWRk1XWp4VB8PU3-:-Moj5U6SCOQKy4vJNd-c:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L752)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest making this parameter and the corresponding data member be a pointer instead of a reference, to emphasize that it's externally owned.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 785 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_ymd-00s4VqXSgl8Y:-Moj5Uqc7AKM31DuYoIj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L785)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can use `*vhost_index` here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_routing.h, line 81 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_vDML39zUzY46UVef:-Moj5VyYC7CQiNGyweul:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_routing.h#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest moving these per-field comments to the line above the field they describe, since that should be more readable.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_routing.cc, line 98 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_vbOQ0U--dryqr6ZD:-Moj5ZDwAttfqC3ryAc_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_routing.cc#L98)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please define these methods in the same order in which they are defined in the .h file, and put the helper functions used by each one right before the method it's used by.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 73 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa-EBi0qsC0f5Ubt_j:-Moj5bOJBVAquRqJYX3y:b-vo2sgv) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L73)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This field also exists in the object pointed to by `listener_watcher`.  Do we need it in both places?
</blockquote></details>

Just saves some cpu cycles since the name we actually use for the watch is derived from the address and the template found in the bootstrap file, but given that `CancelWatch` will only be invoked when the server is shutdown, I think it's fine to repeat that modification.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 85 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_zk20El3uRu3yDl12:-Moj6GdJ00jbxUOZcR5c:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/FilterChainMatchManager objects/a FilterChainMatchManager object/
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 87 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_zfz59AHStgP2g5nV:-Moj6H3Y8Ooy3_yefxi7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L87)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/referred/referenced/

Same thing throughout all of the comments in this file.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 129 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa0Xny2oIYd1sc4Peq:-Moj6IEKE_nbQSJCOboE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L129)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this field is actually used an [...]

2021-11-17 18:53 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851)* status: 22 of 27 files reviewed, 44 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 186 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa3pHq1wBB1yQbc5K4:-MojEh9A0XdCzkVGPw5N:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L186)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This parameter isn't very intuitive.  Instead, I suggest splitting this method into three parts, one corresponding to each of the methods of the `RouteConfigWatcher`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 294 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa52_o3Tvq1HTYYaw9:-MojEcjRE13lO4FSDR0l:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L294)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`explicit`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 295 at r8](https://reviewable.io/reviews/grpc/grpc/27851#-ModMHOn2bMyA3yxvhFK:-MojEcGOEKSEdYi-1Epr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4529a24b18f88257437367f1b7b77bdd03b2dd30/src/core/ext/xds/xds_server_config_fetcher.cc#L295)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `RouteListIterator` class is simple enough that it can be inlined in `XdsServerConfigSelector::VirtualHost`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-17 19:23 UTC, markdroth requested changes
This is looking very good!  Only a few comments left.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 5 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851#-:-MojLcdT7d97UtYsXzsF:bvhei99)* status: all files reviewed, 8 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_routing.cc, line 98 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_vbOQ0U--dryqr6ZD:-Moj9z7ICb3PAx5oiwof:bsctbtu) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_routing.cc#L98)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please also move `HeadersMatch()` and `UnderFraction()` to their own anonymous namespace that is located between `FindVirtualHostForDomain()` and `GetRouteForRequest()`, since those helper functions are only used by the latter method.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 73 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa-EBi0qsC0f5Ubt_j:-MojJB8uE7RQqvJkdQJG:bdcd5jb) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L73)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Just saves some cpu cycles since the name we actually use for the watch is derived from the address and the template found in the bootstrap file, but given that `CancelWatch` will only be invoked when the server is shutdown, I think it's fine to repeat that modification.
</blockquote></details>

Re-expanding the template seems wrong here.  The value that you're storing in `ListenerWatcher::listening_address_` is actually the expanded template already.  I think re-expanding it will yield the wrong value.

Also, given that it's actually storing the expanded resource name, we should probably change the name of this field from `listening_address` to `resource_name`.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 186 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa3pHq1wBB1yQbc5K4:-MojGS9PERZCKQoeH5Wq:bkf6lmc) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L186)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

To be clear, I didn't actually mean to move the code into the methods of `RouteConfigWatcher`; I just meant that there should be one method here corresponding to each of those methods.  I think the methods of `RouteConfigWatcher` should just delegate to these methods, since they really belong here.

`RouteConfigWatcher` should be simple enough that you can inline it if you want.  The other methods' definitions are long enough that they should be moved below.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 294 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa52_o3Tvq1HTYYaw9:-MojIwJc7jwDUl7ClHXU:bocb2l1) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L294)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 399 at r9](https://reviewable.io/reviews/grpc/grpc/27851#-MojCB54AKcQANOxjxUE:-MojCB54AKcQANOxjxUF:bupi5z0) ([raw file](https://github.com/grpc/grpc/blob/0ac016b79cf28c2f3004a4377cfae6efa6a4a21c/src/core/ext/xds/xds_server_config_fetcher.cc#L399)):*
> ```cpp
>     // Prefer existing update, if any.
>     if (parent_->resource_.ok()) {
>       return;
> ```

Need to unref the error before returning here.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 113 at r10](https://reviewable.io/reviews/grpc/grpc/27851#-MojISfT2i4HU1NMK_o3:-MojISfU1tAuhTfiI0c_:b-9q06yx) ([raw file](https://github.com/grpc/grpc/blob/e667d7084e243b0945f6e28e970d3d9018b46c88/src/core/ext/xds/xds_server_config_fetcher.cc#L113)):*
> ```cpp
>   // pending_filter_chain_match_manager_, it is promoted to be the
>   // filter_chain_match_manager_ in use.
>   void PendingFilterChainMatchManagerReady(
> ```

Might be useful to rename this to `PendingFilterChainMatchManagerReadyLocked()` and add a wrapper version without the `Locked()` suffix that grabs the lock for the caller.  That way, we won't need to grab the lock externally.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9973 at r8](https://reviewable.io/reviews/grpc/grpc/27851#-Modg0XG02qquOFauVen:-MojKM6uCwim9ujzQtg9:b-3k702j) ([raw file](https://github.com/grpc/grpc/blob/4529a24b18f88257437367f1b7b77bdd03b2dd30/test/cpp/end2end/xds/xds_end2end_test.cc#L9973)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Hmm, so the properties that we can vary in the filter chain match are 
```
    // - destination port (never matched, so not present in map)
    // - destination IP address
    // - server name (never matched, so not present in map)
    // - transport protocol (allows only "raw_buffer" or unset, prefers the
    //   former, so only one of those two types is present in map)
    // - application protocol (never matched, so not present in map)
    // - connection source type (any, local or external)
    // - source IP address
    // - source port
```
From these, the source port seems to be the only thing that we can vary for connections on localhost. If we could tell the channel to bind to a particular port, we could do it..
</blockquote></details>

That's unfortunate.  For now, please add a TODO that we should add such a test once #24035 is resolved.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9772 at r10](https://reviewable.io/reviews/grpc/grpc/27851#-MojLBet-hJSVI0wSfD3:-MojLBet-hJSVI0wSfD4:b-6rxjee) ([raw file](https://github.com/grpc/grpc/blob/e667d7084e243b0945f6e28e970d3d9018b46c88/test/cpp/end2end/xds/xds_end2end_test.cc#L9772)):*
> ```cpp
>   }
> 
>   bool WaitForRouteConfigNack(
> ```

This should move into `XdsEnd2endTest`, right above the existing `RouteConfigurationResponseState()` method.  It could be useful in client-side tests too.


<!-- Sent from Reviewable.io -->

2021-11-17 21:25 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851)* status: 24 of 27 files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_routing.cc, line 98 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Mo_vbOQ0U--dryqr6ZD:-Mojm-B1Cpb4Yzjn2JHa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_routing.cc#L98)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please also move `HeadersMatch()` and `UnderFraction()` to their own anonymous namespace that is located between `FindVirtualHostForDomain()` and `GetRouteForRequest()`, since those helper functions are only used by the latter method.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 73 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa-EBi0qsC0f5Ubt_j:-MojhFaDBaepwfWO6keo:bvcka5) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L73)):*
> Re-expanding the template seems wrong here. The value that you're storing in ListenerWatcher::listening_address_ is actually the expanded template already. I think re-expanding it will yield the wrong value.

No, it's not. 
```
  auto listener_watcher = MakeRefCounted<ListenerWatcher>(
      xds_client_, std::move(watcher), serving_status_notifier_,
      listening_address);
  auto* listener_watcher_ptr = listener_watcher.get();
  listening_address = absl::StrReplaceAll(
      xds_client_->bootstrap().server_listener_resource_name_template(),
      {{"%s", listening_address}});
  xds_client_->WatchListenerData(listening_address,
                                 std::move(listener_watcher));
```
We store the address before using the template.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 186 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa3pHq1wBB1yQbc5K4:-Mojm5dEEO2zpkZfL5IT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L186)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

To be clear, I didn't actually mean to move the code into the methods of `RouteConfigWatcher`; I just meant that there should be one method here corresponding to each of those methods.  I think the methods of `RouteConfigWatcher` should just delegate to these methods, since they really belong here.

`RouteConfigWatcher` should be simple enough that you can inline it if you want.  The other methods' definitions are long enough that they should be moved below.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 294 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa52_o3Tvq1HTYYaw9:-MojmCS0EdxoVqiy1FEH:buctbik) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L294)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

This time for sure.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 399 at r9](https://reviewable.io/reviews/grpc/grpc/27851#-MojCB54AKcQANOxjxUE:-MojmHzp9beJCJ2GegQg:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0ac016b79cf28c2f3004a4377cfae6efa6a4a21c/src/core/ext/xds/xds_server_config_fetcher.cc#L399)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to unref the error before returning here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 113 at r10](https://reviewable.io/reviews/grpc/grpc/27851#-MojISfT2i4HU1NMK_o3:-Mojm_3m6Rao5fvW7k3D:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e667d7084e243b0945f6e28e970d3d9018b46c88/src/core/ext/xds/xds_server_config_fetcher.cc#L113)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Might be useful to rename this to `PendingFilterChainMatchManagerReadyLocked()` and add a wrapper version without the `Locked()` suffix that grabs the lock for the caller.  That way, we won't need to grab the lock externally.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9973 at r8](https://reviewable.io/reviews/grpc/grpc/27851#-Modg0XG02qquOFauVen:-MojmY467IwEKGwuNPlg:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4529a24b18f88257437367f1b7b77bdd03b2dd30/test/cpp/end2end/xds/xds_end2end_test.cc#L9973)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That's unfortunate.  For now, please add a TODO that we should add such a test once #24035 is resolved.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9772 at r10](https://reviewable.io/reviews/grpc/grpc/27851#-MojLBet-hJSVI0wSfD3:-MojmXCuCE7Weoa2KP3g:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e667d7084e243b0945f6e28e970d3d9018b46c88/test/cpp/end2end/xds/xds_end2end_test.cc#L9772)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should move into `XdsEnd2endTest`, right above the existing `RouteConfigurationResponseState()` method.  It could be useful in client-side tests too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-17 23:28 UTC, markdroth requested changes
This looks excellent!  Just a couple of minor nits remaining.

Please let me know if you have any questions. Thanks!

> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851#-:-MokDeivBEa7Ozdbrfmh:bcyukpq)* status: all files reviewed, 3 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 73 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa-EBi0qsC0f5Ubt_j:-MokBH_CCJzDpk7W7rJC:bv1jxn7) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L73)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

> Re-expanding the template seems wrong here. The value that you're storing in ListenerWatcher::listening_address_ is actually the expanded template already. I think re-expanding it will yield the wrong value.

No, it's not. 
```
  auto listener_watcher = MakeRefCounted<ListenerWatcher>(
      xds_client_, std::move(watcher), serving_status_notifier_,
      listening_address);
  auto* listener_watcher_ptr = listener_watcher.get();
  listening_address = absl::StrReplaceAll(
      xds_client_->bootstrap().server_listener_resource_name_template(),
      {{"%s", listening_address}});
  xds_client_->WatchListenerData(listening_address,
                                 std::move(listener_watcher));
```
We store the address before using the template.


</blockquote></details>

Ah, okay.  What confused me is that you're storing the resource name in a variable called `listening_address`.  Can you please change that code to either create a new string variable called `resource_name`, or just side-step the issue and pass the result of `absl::StrReplaceAll()` directly to `WatchListenerData()` without storing it in a local variable at all?
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 186 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa3pHq1wBB1yQbc5K4:-MokCBlo37ROOEtnimb1:b-y6uc8b) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L186)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You made this change in `DynamicXdsServerConfigSelectorProvider`, but not here in `FilterChainMatchManager`.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 592 at r11](https://reviewable.io/reviews/grpc/grpc/27851#-MokBv6h1zQ0ryi6cv_V:-MokBv6h1zQ0ryi6cv_W:bqvxjl) ([raw file](https://github.com/grpc/grpc/blob/c906b6d7303c34f8973ef6eae9684543c714c4ca/src/core/ext/xds/xds_server_config_fetcher.cc#L592)):*
> ```cpp
> 
> void XdsServerConfigFetcher::ListenerWatcher::
>     PendingFilterChainMatchManagerReady(
> ```

The definition of this method is short enough that it can be inlined in the class definition above if you'd like.


<!-- Sent from Reviewable.io -->

2021-11-18 00:25 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851)* status: 26 of 27 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 73 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa-EBi0qsC0f5Ubt_j:-MokQg-P9sKzBLVYZXLp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L73)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ah, okay.  What confused me is that you're storing the resource name in a variable called `listening_address`.  Can you please change that code to either create a new string variable called `resource_name`, or just side-step the issue and pass the result of `absl::StrReplaceAll()` directly to `WatchListenerData()` without storing it in a local variable at all?
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 186 at r7](https://reviewable.io/reviews/grpc/grpc/27851#-Moa3pHq1wBB1yQbc5K4:-MokQi8y6EuijxeksrmZ:b-4z4lng) ([raw file](https://github.com/grpc/grpc/blob/86831d9e3ac06314ae42ef6424d9b48eade11cb7/src/core/ext/xds/xds_server_config_fetcher.cc#L186)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You made this change in `DynamicXdsServerConfigSelectorProvider`, but not here in `FilterChainMatchManager`.
</blockquote></details>

Ah, `DynamicXdsServerConfigSelectorProvider` is where I thought the original comment was. It's good to be consistent anyway, so the change is now in both places.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 592 at r11](https://reviewable.io/reviews/grpc/grpc/27851#-MokBv6h1zQ0ryi6cv_V:-MokQr_o8Vr1RHwTrYDd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c906b6d7303c34f8973ef6eae9684543c714c4ca/src/core/ext/xds/xds_server_config_fetcher.cc#L592)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The definition of this method is short enough that it can be inlined in the class definition above if you'd like.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-18 15:56 UTC, markdroth approved these changes
This looks fantastic!

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27851#-:-MonkmPf0Wvl_ynJTqTk:bcpuwtr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yashykt)



<!-- Sent from Reviewable.io -->

2021-11-18 22:58 UTC, yashykt commented
Known issues: https://github.com/grpc/grpc/issues/26886
Thanks for reviewing!

2021-11-19 00:10 UTC, merged