WIP: API to cancel grpc_resolve_address
grpc/grpc pull request #27883
Opened 2021-10-29 23:27 UTC by apolcyn

WIP

2021-11-05 23:02 UTC, markdroth requested changes
This looks good overall.  My only substantive comments are about the API design.

Please let me know if you have any questions.  Thanks!

> Reviewed 34 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27883#-:-MnmKYqZB7aRJ66lNZI6:b-t2675s)* status: all files reviewed, 11 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 1165 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmGJ967iCMnIaig5lg:-MnmGJ97-qD9xJGRMfWo:b4e0ljb) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L1165)):*
> ```cpp
>       }
>     }
>     GRPC_ERROR_REF(error);
> ```

This can move inline into the `ExecCtx::Run()` call on the next line.
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 178 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-Mnm47teBPyR183G2-MV:-Mnm47teBPyR183G2-MW:bmnukvw) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L178)):*
> ```cpp
>   GPR_ASSERT(resolving_);
>   resolving_ = false;
>   async_resolve_address_.reset();
> ```

In principle, we should do this in `ShutdownLocked()` as well, to cancel any pending resolution.
___
*[src/core/lib/iomgr/resolve_address.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-Mnm1UOwABCWHiZGdqT3:-Mnm1UOxDH6mKBdK-02a:b-upywb7) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/src/core/lib/iomgr/resolve_address.h#L73)):*
> ```objc
>    in addr, otherwise use the port in addr. */
> /* TODO(apolcyn): add a timeout here */
> grpc_core::OrphanablePtr<grpc_core::AsyncResolveAddress> grpc_resolve_address(
> ```

Please document the return value and semantics.  I assume that the intent here is that when the caller orphans the returned object, that cancels the call?

This feels like a somewhat cumbersome API, probably because it's a weird hybrid of C and C++ semantics; it's not immediately obvious to the reader what the returned object actually represents.  It might be better to just stick with a C-style API here and do something like this:

```
// Returns an opaque ID that can be passed to grpc_resolve_address_cancel()
// to cancel the request.
intptr_t grpc_resolve_address(...);

// Cancels a pending DNS request.
void grpc_resolve_address_cancel(intptr_t id);
```

Alternatively, maybe convert it fully to a C++ API:

```
class DNSRequest : public InternallyRefCounted<DNSRequest> {
 public:
  static OrphanablePtr<DNSRequest> Start(
      absl::string_view name, absl::string_view default_port,
      grpc_pollset_set* interested_parties,
      std::function<void(absl::StatusOr<grpc_resolved_addresses>)> on_done);

  void Orphan() override;
};
```
___
*[src/core/lib/iomgr/resolve_address_custom.cc, line 143 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmHXid-lG5509K-KYs:-MnmHXid-lG5509K-KYt:bjdy4pc) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/src/core/lib/iomgr/resolve_address_custom.cc#L143)):*
> ```cpp
> namespace grpc_core {
> 
> class CustomAsyncResolveAddress : public AsyncResolveAddress {
> ```

I don't think this class is actually needed.  For implementations that don't support cancellation, you can just have them return null.  The caller will interact with the resulting `OrphanablePtr<>` in exactly the same way.
___
*[test/core/util/fake_udp_and_tcp_server.h, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmHs3UExZLRVHMbhfp:-MnmHs3UExZLRVHMbhfq:bk4ey47) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/test/core/util/fake_udp_and_tcp_server.h#L1)):*
> ```objc
> /*
> ```

Please use C++-style comments.
___
*[test/core/util/fake_udp_and_tcp_server.h, line 37 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmIwE90hWefwvBqm-T:-MnmIwE90hWefwvBqm-U:b9ufdzk) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/test/core/util/fake_udp_and_tcp_server.h#L37)):*
> ```objc
> namespace testing {
> 
> class FakeUdpAndTcpServer {
> ```

Some documentation would help here.  Say what this class does, what it is used for, and maybe some example of how it's used.
___
*[test/core/util/fake_udp_and_tcp_server.h, line 67 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmI5ab-XuCORMDcbat:-MnmI5ab-XuCORMDcbau:bjeo2kf) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/test/core/util/fake_udp_and_tcp_server.h#L67)):*
> ```objc
>                                                         int read_error, int s);
> 
>   class FakeUdpAndTcpServerPeer {
> ```

Classes should go before the ctor or any methods.

https://google.github.io/styleguide/cppguide.html#Declaration_Order
___
*[test/core/util/fake_udp_and_tcp_server.h, line 88 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmIgUP1ZO5kun4ZR9r:-MnmIgUP1ZO5kun4ZR9s:b-b4x9hr) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/test/core/util/fake_udp_and_tcp_server.h#L88)):*
> ```objc
>   //   2) Checks if any data has arrived yet on established connections,
>   //      and reads from them if so, processing the sockets as configured.
>   static void RunServerLoop(FakeUdpAndTcpServer* self);
> ```

Why is this a static method and not a normal method, given that it takes a pointer to the object as its only parameter anyway?
___
*[test/core/util/fake_udp_and_tcp_server.cc, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmIHlD4GSM2sgBx5o_:-MnmIHlD4GSM2sgBx5oa:bk4ey47) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/test/core/util/fake_udp_and_tcp_server.cc#L1)):*
> ```cpp
> /*
> ```

Please use C++-style comments.
___
*[test/core/util/fake_udp_and_tcp_server.cc, line 50 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmIMIoAjJNa2crflAF:-MnmIMIoAjJNa2crflAG:b2toy00) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/test/core/util/fake_udp_and_tcp_server.cc#L50)):*
> ```cpp
>     const std::function<FakeUdpAndTcpServer::ProcessReadResult(int, int, int)>&
>         process_read_cb)
>     : accept_mode_(accept_mode), process_read_cb_(process_read_cb) {
> ```

`std::move(process_read_cb)`
___
*[test/core/util/run_with_poller.sh, line 18 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmJ41B-El7sExMUPwL:-MnmJ41B-El7sExMUPwM:b-1qa0de) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/test/core/util/run_with_poller.sh#L18)):*
> ```Shell
> set -ex
> export GRPC_POLL_STRATEGY=$1
> export GRPC_TRACE=cares_resolver
> ```

Did you mean for this change to actually get merged, or was this just for your own debugging?


<!-- Sent from Reviewable.io -->

2021-12-10 11:26 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27883)* status: 5 of 51 files reviewed, 11 unresolved discussions (waiting on @apolcyn and @markdroth)

___
*[src/core/lib/iomgr/resolve_address.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-Mnm1UOwABCWHiZGdqT3:-MqZ4GD8D53VNNXpIiu9:b-z9ix05) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/src/core/lib/iomgr/resolve_address.h#L73)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please document the return value and semantics.  I assume that the intent here is that when the caller orphans the returned object, that cancels the call?

This feels like a somewhat cumbersome API, probably because it's a weird hybrid of C and C++ semantics; it's not immediately obvious to the reader what the returned object actually represents.  It might be better to just stick with a C-style API here and do something like this:

```
// Returns an opaque ID that can be passed to grpc_resolve_address_cancel()
// to cancel the request.
intptr_t grpc_resolve_address(...);

// Cancels a pending DNS request.
void grpc_resolve_address_cancel(intptr_t id);
```

Alternatively, maybe convert it fully to a C++ API:

```
class DNSRequest : public InternallyRefCounted<DNSRequest> {
 public:
  static OrphanablePtr<DNSRequest> Start(
      absl::string_view name, absl::string_view default_port,
      grpc_pollset_set* interested_parties,
      std::function<void(absl::StatusOr<grpc_resolved_addresses>)> on_done);

  void Orphan() override;
};
```
</blockquote></details>

I've mostly updated this PR to go with a two-phased version of the second approach (the API separates the ctor from starting the async work).

 I still have a fair amount of cleanup left to do, so this PR doesn't currently pass all builds or tests, but I don't expect the new APIs in `src/core/lib/iomgr/resolve_address.h` to be changing any more, if you have a chance to take a look at that in the meantime. Thanks!


<!-- Sent from Reviewable.io -->

2021-12-10 20:49 UTC, markdroth requested changes
> Reviewed 2 of 46 files at r2, 6 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27883)* status: 12 of 57 files reviewed, 16 unresolved discussions (waiting on @apolcyn and @markdroth)

___
*[src/core/lib/iomgr/resolve_address.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-Mnm1UOwABCWHiZGdqT3:-Mqa5hqk6JKRYKMt8ius:bu5ia98) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/src/core/lib/iomgr/resolve_address.h#L73)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I've mostly updated this PR to go with a two-phased version of the second approach (the API separates the ctor from starting the async work).

 I still have a fair amount of cleanup left to do, so this PR doesn't currently pass all builds or tests, but I don't expect the new APIs in `src/core/lib/iomgr/resolve_address.h` to be changing any more, if you have a chance to take a look at that in the meantime. Thanks!
</blockquote></details>

This looks really good!  I've made a few comments, but overall I really like the API structure.
___
*[src/core/lib/iomgr/resolve_address.h, line 47 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa2w_yCeJWj5bGXJ-G:-Mqa2w_yCeJWj5bGXJ-H:bbvmsou) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L47)):*
> ```objc
>   socklen_t len;
> };
> struct grpc_resolved_addresses {
> ```

While we're making changes here anyway, how about replacing this with `std::vector<grpc_resolved_address>`?
___
*[src/core/lib/iomgr/resolve_address.h, line 62 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa2qhW8vVgtva2xLTw:-Mqa2qhW8vVgtva2xLTx:bdfg77a) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L62)):*
> ```objc
> // resolution should be arranged to be cancelled as soon as possible
> // when Orphan is called.
> class DNSRequest : public InternallyRefCounted<DNSRequest> {
> ```

I suggest nesting this inside of `DNSResolver`.
___
*[src/core/lib/iomgr/resolve_address.h, line 68 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa3x7X3wnTBeMCYRQ1:-Mqa3x7X3wnTBeMCYRQ2:b-3yfgqj) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L68)):*
> ```objc
> };
> 
> // A fire and forget class used by DNSRequest implementations to run DNS
> ```

Why is this needed?  I would think that most implementations would be able to invoke the callback directly, since they're doing work asynchronously anyway and therefore wouldn't be holding any locks from the caller.  And it should generally be straightforward for an implementation to invoke the callback after giving up its own lock, if any.

Also, even if a hop through the ExecCtx is needed, I think it should be fairly easy for a `DNSRequest` implementation to do that directly without allocating a separate object, since it's already ref-counted.  All it needs to do is not drop the ref to itself until it's invoked the callback.
___
*[src/core/lib/iomgr/resolve_address.h, line 71 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa3M8_D91R0U8PBiRP:-Mqa3M8_D91R0U8PBiRQ:b-y07en5) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L71)):*
> ```objc
> // resolution callbacks on the ExecCtx, which is frequently necessary to avoid
> // lock inversion related problems.
> class DNSCallbackExecCtxScheduler {
> ```

If we do keep this, it seems like an implementation detail, not really part of the API for using the DNS resolution code, so it would probably make sense to move it out of this file.  Maybe add a separate resolve_address_impl.h file for implementations to use?
___
*[src/core/lib/iomgr/resolve_address.h, line 101 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa2Tct3BOXPQmKF5_d:-Mqa2TcuDX_DVEzv03ib:b7o0vgd) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L101)):*
> ```objc
>   // Asynchronously resolve addr. Use default_port if a port isn't designated
>   // in addr, otherwise use the port in addr.
>   // TODO(apolcyn): add a timeout here.
> ```

Timeout probably isn't needed anymore now that the request is cancellable.  If the caller wants a timeout, they can start a timer and cancel the DNS request when the timer fires (which is all that we'd do in the resolver impl anyway).
___
*[src/core/lib/iomgr/resolve_address.h, line 102 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa5EGM5Tph26-Cs_sc:-Mqa5EGM5Tph26-Cs_sd:b-uhf9m0) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L102)):*
> ```objc
>   // in addr, otherwise use the port in addr.
>   // TODO(apolcyn): add a timeout here.
>   virtual OrphanablePtr<DNSRequest> CreateDNSRequest(
> ```

Suggest calling these two methods `ResolveName()` and `ResolveNameBlocking()`.


<!-- Sent from Reviewable.io -->

2021-12-13 20:48 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27883)* status: 5 of 61 files reviewed, 16 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 1165 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmGJ967iCMnIaig5lg:-MqpUZkG6YYdVGqaJB4H:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L1165)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can move inline into the `ExecCtx::Run()` call on the next line.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 178 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-Mnm47teBPyR183G2-MV:-MqpV6JD1RtAQFru9t0s:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L178)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In principle, we should do this in `ShutdownLocked()` as well, to cancel any pending resolution.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-Mnm1UOwABCWHiZGdqT3:-MqpXOkN0v_RCwdp5YQe:b-ucfknh) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/src/core/lib/iomgr/resolve_address.h#L73)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This looks really good!  I've made a few comments, but overall I really like the API structure.
</blockquote></details>

Thanks!
___
*[src/core/lib/iomgr/resolve_address.h, line 47 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa2w_yCeJWj5bGXJ-G:-MqpV87o6AWU-ddEq3HW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L47)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

While we're making changes here anyway, how about replacing this with `std::vector<grpc_resolved_address>`?
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address.h, line 62 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa2qhW8vVgtva2xLTw:-MqpV9BX3hdLhIHzVq92:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest nesting this inside of `DNSResolver`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address.h, line 68 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa3x7X3wnTBeMCYRQ1:-MqpVQZK6nBtw8NGEoDV:b-knc9km) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L68)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this needed?  I would think that most implementations would be able to invoke the callback directly, since they're doing work asynchronously anyway and therefore wouldn't be holding any locks from the caller.  And it should generally be straightforward for an implementation to invoke the callback after giving up its own lock, if any.

Also, even if a hop through the ExecCtx is needed, I think it should be fairly easy for a `DNSRequest` implementation to do that directly without allocating a separate object, since it's already ref-counted.  All it needs to do is not drop the ref to itself until it's invoked the callback.
</blockquote></details>

I agree it's not really hard for implementations to do this themselves, but I still think having this ends up with a net win:

- this ends up being used by two real DNSResolver::Request implementations (the EE implementation and the custom resolver implementation), as well as two unit test implementations

- if we were to have EE and custom resolver implementations do this themselves, then they would each need to add two more fields: `grpc_closure invoke_on_done` (to schedule invocation of `on_done` on the ExecCtx) and `absl::StatusOr<std::vector<grpc_resolved_address>> destroy` (to temporarily hold the result that will be used from `invoke_on_done`). This is OK, but it does make the code slightly less readable IMO.
___
*[src/core/lib/iomgr/resolve_address.h, line 71 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa3M8_D91R0U8PBiRP:-MqpXDFi4AkUPuZAvFDl:b-vq111b) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L71)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we do keep this, it seems like an implementation detail, not really part of the API for using the DNS resolution code, so it would probably make sense to move it out of this file.  Maybe add a separate resolve_address_impl.h file for implementations to use?
</blockquote></details>

Done. Moved this to resolve_address_impl.h
___
*[src/core/lib/iomgr/resolve_address.h, line 101 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa2Tct3BOXPQmKF5_d:-MqpXN0c7Oq1zzyjfDGa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L101)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Timeout probably isn't needed anymore now that the request is cancellable.  If the caller wants a timeout, they can start a timer and cancel the DNS request when the timer fires (which is all that we'd do in the resolver impl anyway).
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address.h, line 102 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa5EGM5Tph26-Cs_sc:-MqpXNUF4a-BaLGDNQN8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L102)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling these two methods `ResolveName()` and `ResolveNameBlocking()`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address_custom.cc, line 143 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmHXid-lG5509K-KYs:-MqpXRdsE9krDp4n1cqS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/src/core/lib/iomgr/resolve_address_custom.cc#L143)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this class is actually needed.  For implementations that don't support cancellation, you can just have them return null.  The caller will interact with the resulting `OrphanablePtr<>` in exactly the same way.
</blockquote></details>

Done.
___
*[test/core/util/fake_udp_and_tcp_server.h, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmHs3UExZLRVHMbhfp:-MqpXTr0AHr4xAnnpPEQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/test/core/util/fake_udp_and_tcp_server.h#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style comments.
</blockquote></details>

Done.
___
*[test/core/util/fake_udp_and_tcp_server.h, line 37 at r1](https://reviewable.io/reviews/grpc/grpc/27883#-MnmIwE90hWefwvBqm-T:-MqpXXkD4hJS_rrgs5X7:b-5bmmup) ([raw file](https://github.com/grpc/grpc/blob/5321e10f3c554dba9726d7eb95bdaff64842e3c7/test/core/util/fake_udp_and_tcp_server.h#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Some documentation would help here.  Say what this class does, what it is used for, and maybe some example [...]

2021-12-14 20:31 UTC, markdroth requested changes
This is looking really good!  Comments are relatively minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 14 of 46 files at r2, 3 of 25 files at r3, 33 of 39 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27883#-:-Mqud9un20dlRNw4Aa-8:bz02f2s)* status: all files reviewed, 14 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 487 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MquQajN1wgusUOXChMz:-MquQajN1wgusUOXChN-:b-g2gzen) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L487)):*
> ```cpp
> class AresDNSResolver;
> 
> AresDNSResolver* g_ares_dns_resolver;
> ```

You can make this a local static variable inside of `GetOrCreate()`.  That would eliminate the need for the forward declaration above.

Similar comment for all of the resolver implementations.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 601 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MquUGijCxVjfvhFS25_:-MquUGijCxVjfvhFS25a:b5gbhb1) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L601)):*
> ```cpp
>   absl::StatusOr<std::vector<grpc_resolved_address>> ResolveNameBlocking(
>       absl::string_view name, absl::string_view default_port) override {
>     return default_resolver_->ResolveNameBlocking(name, default_port);
> ```

Would it make sense to instead do the same thing as the EventEngine resolver, where we use a promise to wrap the async c-ares code?  That way, there's no need to store a pointer to the previous default DNS resolver, which seems kind of hacky.
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 175 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-Mqu_TCh4o-Zbcviw71V:-Mqu_TCh4o-Zbcviw71W:bvsaol2) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L175)):*
> ```cpp
>     absl::StatusOr<std::vector<grpc_resolved_address>> addresses_or) {
>   work_serializer_->Run(
>       [this, &addresses_or]() { OnResolvedLocked(std::move(addresses_or)); },
> ```

I don't think it's safe to capture `addresses_or` as a reference, since it will no longer be in scope if the callback runs out-of-band.

Right now, we'll have to capture it as a copy.  Later, when we move to C++14, we can capture it using `std::move()`.
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 284 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-Mqu_sj40tpjHaTYj88F:-Mqu_sj40tpjHaTYj88G:bknnfpj) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L284)):*
> ```cpp
>   dns_request_ = GetDNSResolver()->ResolveName(
>       name_to_resolve_, kDefaultSecurePort, interested_parties_,
>       std::bind(&NativeClientChannelDNSResolver::OnResolved, this,
> ```

This can use `absl::BindFront()`.
___
*[src/core/lib/http/httpcli.cc, line 81 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MquPgVY08LTSURl3nTs:-MquPgVY08LTSURl3nTt:b4cjcoe) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/http/httpcli.cc#L81)):*
> ```cpp
>     dns_request_ = GetDNSResolver()->ResolveName(
>         host_.c_str(), handshaker_->default_port, context_->pollset_set,
>         std::bind(&InternalRequest::OnResolved, this, std::placeholders::_1));
> ```

Suggest using `absl::BindFront()` here.
___
*[src/core/lib/iomgr/resolve_address.h, line 68 at r3](https://reviewable.io/reviews/grpc/grpc/27883#-Mqa3x7X3wnTBeMCYRQ1:-MqtbxZR-9xifqfgq28G:b9foj1p) ([raw file](https://github.com/grpc/grpc/blob/267474179830f20003a686f99cc240b1421af194/src/core/lib/iomgr/resolve_address.h#L68)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I agree it's not really hard for implementations to do this themselves, but I still think having this ends up with a net win:

- this ends up being used by two real DNSResolver::Request implementations (the EE implementation and the custom resolver implementation), as well as two unit test implementations

- if we were to have EE and custom resolver implementations do this themselves, then they would each need to add two more fields: `grpc_closure invoke_on_done` (to schedule invocation of `on_done` on the ExecCtx) and `absl::StatusOr<std::vector<grpc_resolved_address>> destroy` (to temporarily hold the result that will be used from `invoke_on_done`). This is OK, but it does make the code slightly less readable IMO.


</blockquote></details>

Okay.  I'm not really convinced that the extra allocation is worth it, but it's probably not worth debating, since this code will go away as part of migrating to EventEngine anyway.
___
*[src/core/lib/iomgr/resolve_address.h, line 50 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MqtbsWV0KwReAutA2CE:-MqtbsWV0KwReAutA2CF:bdvz5bv) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address.h#L50)):*
> ```objc
> // custom resolver API. This type could be deleted as a part of converting
> // that API to C++.
> struct grpc_resolved_addresses {
> ```

Let's move this into resolve_address_custom.h, since that's the only place it's still needed.
___
*[src/core/lib/iomgr/resolve_address_custom.h, line 34 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-Mqt_hn15vxhKgQNwbYC:-Mqt_hn15vxhKgQNwbYD:b-4cwhl1) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_custom.h#L34)):*
> ```objc
> namespace grpc_core {
> 
> class CustomDNSResolver : public DNSResolver {
> ```

Suggest moving this to the bottom of the file, so that we don't need the forward declaration of `grpc_custom_resolver_vtable` above.
___
*[src/core/lib/iomgr/resolve_address_custom.h, line 76 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MqtfTnRB9qpu7j6YUgH:-MqtfTnRB9qpu7j6YUgI:bz3pebl) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_custom.h#L76)):*
> ```objc
> 
>   // Gets the singleton instance, creating it if it hasn't been already.
>   static CustomDNSResolver* GetOrCreate(
> ```

I think this should be split into two methods, one for setting the vtable and another for getting the instance.  Otherwise, the semantics are a little strange if you call it a second time with a different vtable.
___
*[src/core/lib/iomgr/resolve_address_custom.h, line 76 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MqtfdJu7O8mx18WQzrb:-MqtfdJu7O8mx18WQzrc:b138tye) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_custom.h#L76)):*
> ```objc
> 
>   // Gets the singleton instance, creating it if it hasn't been already.
>   static CustomDNSResolver* GetOrCreate(
> ```

Factory methods should be declared before the ctor, as per:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
___
*[src/core/lib/iomgr/resolve_address_custom.cc, line 42 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MqteZYK09p4a_RLvl18:-MqteZYK09p4a_RLvl19:b-hnpklt) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_custom.cc#L42)):*
> ```cpp
> #include "src/core/lib/transport/error_utils.h"
> 
> struct grpc_custom_resolver {
> ```

Instead of defining a separate struct to wrap the `CustomDNSRequest` object, I suggest having `CustomDNSRequest` inherit from `CppImplOf<>`:

https://github.com/g [...]

2021-12-15 02:48 UTC, apolcyn reviewed
Thanks! I believe comments are addressed, PTAL.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27883#-:-MqvxKa-DqLIRYk-_j4H:b-4fdoww)* status: 31 of 62 files reviewed, 14 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 487 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MquQajN1wgusUOXChMz:-MqvxSMx32EkGi_4htS_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L487)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can make this a local static variable inside of `GetOrCreate()`.  That would eliminate the need for the forward declaration above.

Similar comment for all of the resolver implementations.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 601 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MquUGijCxVjfvhFS25_:-MqvxTky45wW1-KDwRJ_:bmc9u4z) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L601)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Would it make sense to instead do the same thing as the EventEngine resolver, where we use a promise to wrap the async c-ares code?  That way, there's no need to store a pointer to the previous default DNS resolver, which seems kind of hacky.
</blockquote></details>

I think this would be a nice cleanup. However, this would add potentially user-visible behavioral changes to this PR (for example, servers could no longer bind to NETBIOS names on Windows, etc.).

Given those slight risks, I'd prefer to make that change as its own PR, so that it can be more easily identified and rolled back if it causes problems.

Added a TODO.
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 175 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-Mqu_TCh4o-Zbcviw71V:-MqvyWi01MOEZuwoXM93:b-npagrs) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L175)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think it's safe to capture `addresses_or` as a reference, since it will no longer be in scope if the callback runs out-of-band.

Right now, we'll have to capture it as a copy.  Later, when we move to C++14, we can capture it using `std::move()`.
</blockquote></details>

Good catch! fixed
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 284 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-Mqu_sj40tpjHaTYj88F:-Mqvyaus8AQDA8ibNJV1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L284)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can use `absl::BindFront()`.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.cc, line 81 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MquPgVY08LTSURl3nTs:-MqvydM22hhTX2A-aQ5f:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/http/httpcli.cc#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest using `absl::BindFront()` here.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address.h, line 50 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MqtbsWV0KwReAutA2CE:-MqvyervBIgaNcKu4gKj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address.h#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's move this into resolve_address_custom.h, since that's the only place it's still needed.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address_custom.h, line 34 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-Mqt_hn15vxhKgQNwbYC:-MqvykL73dYs9QC0H5Ug:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_custom.h#L34)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest moving this to the bottom of the file, so that we don't need the forward declaration of `grpc_custom_resolver_vtable` above.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address_custom.h, line 76 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MqtfTnRB9qpu7j6YUgH:-Mqvyl_F7mNbFdhlDtA3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_custom.h#L76)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this should be split into two methods, one for setting the vtable and another for getting the instance.  Otherwise, the semantics are a little strange if you call it a second time with a different vtable.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address_custom.h, line 76 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MqtfdJu7O8mx18WQzrb:-MqvymLiAEVXUHtA5iR1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_custom.h#L76)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Factory methods should be declared before the ctor, as per:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address_custom.cc, line 42 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MqteZYK09p4a_RLvl18:-MqvynNH4ii8jCty3bRp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_custom.cc#L42)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of defining a separate struct to wrap the `CustomDNSRequest` object, I suggest having `CustomDNSRequest` inherit from `CppImplOf<>`:

https://github.com/grpc/grpc/blob/master/src/core/lib/gprpp/cpp_impl_of.h

See #28112 for an example of how to use it.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address_posix.h, line 1 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MquMs-j8jg3tm-ZMVKh:-MqvyoHUDQRmIp4gXhyv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_posix.h#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style comments for all new files.

Same thing throughout.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/event_engine/resolver.cc, line 58 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MquNyqqCJciA6iWNp9A:-Mqvypit88GoVd-MZYPA:bd7rhu6) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/event_engine/resolver.cc#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Presumably, this should be `dns_resolver_`?

Also, in what case will this be null?
</blockquote></details>

Whoops! Fixed.

I kept this nullptr check mainly just since the existing code has it already, which looks like it's for case where the event engine's `GetDNSResolver` method returns nullptr. I can spot one implementation of event engine `GetDNSResolver` which does currently return nullptr.
___
*[test/core/iomgr/resolve_address_test.cc, lin [...]

2021-12-15 19:29 UTC, markdroth requested changes
This is looking very good!  Just a few minor issues left.

Please let me know if you have any questions.  Thanks!

> Reviewed 27 of 31 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27883#-:-MqzZKKH8yQ0CoarI8RK:bt3w64e)* status: all files reviewed, 5 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 601 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MquUGijCxVjfvhFS25_:-MqzTKDZ4zZK_uL3f6er:b-1z3fxz) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L601)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I think this would be a nice cleanup. However, this would add potentially user-visible behavioral changes to this PR (for example, servers could no longer bind to NETBIOS names on Windows, etc.).

Given those slight risks, I'd prefer to make that change as its own PR, so that it can be more easily identified and rolled back if it causes problems.

Added a TODO.
</blockquote></details>

Good point about the behavior change.  The TODO is fine.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 580 at r7](https://reviewable.io/reviews/grpc/grpc/27883#-MqzT8YH-X7-k-NWmJBR:-MqzT8YH-X7-k-NWmJBS:b-sm5snx) ([raw file](https://github.com/grpc/grpc/blob/05cab498929c71f4e45b538d9c48fbe8dca1c877/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L580)):*
> ```cpp
>   // gets the singleton instance, possibly creating it first
>   static AresDNSResolver* GetOrCreate() {
>     static AresDNSResolver* instance;
> ```

This can just be:

```
static AresDNSResolver* instance = new AresDNSResolver();
return instance;
```

Since it's static, the assignment will be evaluated only once.

Same thing in all implementations.
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 175 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-Mqu_TCh4o-Zbcviw71V:-MqzTYSyApZT0Qzbwymz:bm4neqn) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L175)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Good catch! fixed
</blockquote></details>

Using `std::move()` inside of the lambda is still what we want, or else we're doing two copies instead of just the one that we can't avoid until we migrate to C++14.  To make that possible, you just need to use the `mutable` keyword on the lambda.

```
[this, addresses_or]() mutable { OnResolvedLocked(std::move(addresses_or)); }
```

Later, when we can use C++14, this can become:

```
[this, addresses_or = std::move(addresses_or)]() mutable { OnResolvedLocked(std::move(addresses_or)); }
```
___
*[src/core/lib/iomgr/iomgr_custom.cc, line 23 at r7](https://reviewable.io/reviews/grpc/grpc/27883#-MqzUDkwCn157AX6ZMO0:-MqzUDkwCn157AX6ZMO1:b2xoqpz) ([raw file](https://github.com/grpc/grpc/blob/05cab498929c71f4e45b538d9c48fbe8dca1c877/src/core/lib/iomgr/iomgr_custom.cc#L23)):*
> ```cpp
> #include "src/core/lib/iomgr/iomgr_custom.h"
> 
> #include "absl/functional/bind_front.h"
> ```

Doesn't look like this is used in this file.
___
*[src/core/lib/iomgr/resolve_address_custom.h, line 76 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MqtfTnRB9qpu7j6YUgH:-MqzUfCDAEZvQxVzhjzT:b-e6ydff) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_custom.h#L76)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Instead of `GetOrCreate()` and `set_vtable()`, how about something like this:

```
// Creates the global custom resolver with the specified vtable.
static void CreateCustomResolver(const grpc_custom_resolver_vtable* vtable);

// Gets the global custom resolver.
static CustomDNSResolver* Get();
```

That way, it's not possible to change vtable after creation, which I think is the semantic we want here.

This will require having the static pointer outside of the `Get()` method, but I think that's a worthwhile trade-off in this case.
___
*[test/core/iomgr/resolve_address_test.cc, line 60 at r7](https://reviewable.io/reviews/grpc/grpc/27883#-MqzYJBlBIFbCvxBsWfA:-MqzYJBlBIFbCvxBsWfB:bvtaoh5) ([raw file](https://github.com/grpc/grpc/blob/05cab498929c71f4e45b538d9c48fbe8dca1c877/test/core/iomgr/resolve_address_test.cc#L60)):*
> ```cpp
> bool g_resolver_type_configured;
> 
> class ResolveAddressTest : public ::testing::TestWithParam<const char*> {
> ```

If we're using `TestWithParam<>`, don't we need an `INSTANTIATE_TEST_SUITE_P()` call somewhere for `ResolveAddressTest`, and then use `TEST_P()` instead of `TEST_F()` for the individual test cases?  Otherwise, I'm not sure these tests are actually being run.


<!-- Sent from Reviewable.io -->

2021-12-15 20:55 UTC, apolcyn reviewed
Thanks, I believe I've addressed comments again. PTAL

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27883#-:-MqzsA396g_qxwTOOpqt:b1cfiog)* status: 52 of 62 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc, line 580 at r7](https://reviewable.io/reviews/grpc/grpc/27883#-MqzT8YH-X7-k-NWmJBR:-MqzrLFyB_Bd8Xh2Rn1W:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/05cab498929c71f4e45b538d9c48fbe8dca1c877/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc#L580)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can just be:

```
static AresDNSResolver* instance = new AresDNSResolver();
return instance;
```

Since it's static, the assignment will be evaluated only once.

Same thing in all implementations.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc, line 175 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-Mqu_TCh4o-Zbcviw71V:-MqzrNMO0u8TPFXsOv7n:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L175)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Using `std::move()` inside of the lambda is still what we want, or else we're doing two copies instead of just the one that we can't avoid until we migrate to C++14.  To make that possible, you just need to use the `mutable` keyword on the lambda.

```
[this, addresses_or]() mutable { OnResolvedLocked(std::move(addresses_or)); }
```

Later, when we can use C++14, this can become:

```
[this, addresses_or = std::move(addresses_or)]() mutable { OnResolvedLocked(std::move(addresses_or)); }
```
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/iomgr_custom.cc, line 23 at r7](https://reviewable.io/reviews/grpc/grpc/27883#-MqzUDkwCn157AX6ZMO0:-MqzrXLv125_3A-bVjMC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/05cab498929c71f4e45b538d9c48fbe8dca1c877/src/core/lib/iomgr/iomgr_custom.cc#L23)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this is used in this file.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/resolve_address_custom.h, line 76 at r5](https://reviewable.io/reviews/grpc/grpc/27883#-MqtfTnRB9qpu7j6YUgH:-MqzrZX-7sSTVbkKg7We:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a9ef7e25dcaae3930d44f6aeec6b36d334cc4183/src/core/lib/iomgr/resolve_address_custom.h#L76)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of `GetOrCreate()` and `set_vtable()`, how about something like this:

```
// Creates the global custom resolver with the specified vtable.
static void CreateCustomResolver(const grpc_custom_resolver_vtable* vtable);

// Gets the global custom resolver.
static CustomDNSResolver* Get();
```

That way, it's not possible to change vtable after creation, which I think is the semantic we want here.

This will require having the static pointer outside of the `Get()` method, but I think that's a worthwhile trade-off in this case.
</blockquote></details>

Done.
___
*[test/core/iomgr/resolve_address_test.cc, line 60 at r7](https://reviewable.io/reviews/grpc/grpc/27883#-MqzYJBlBIFbCvxBsWfA:-Mqzr_ez9ixg6hcelYH3:b-mu1ra1) ([raw file](https://github.com/grpc/grpc/blob/05cab498929c71f4e45b538d9c48fbe8dca1c877/test/core/iomgr/resolve_address_test.cc#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're using `TestWithParam<>`, don't we need an `INSTANTIATE_TEST_SUITE_P()` call somewhere for `ResolveAddressTest`, and then use `TEST_P()` instead of `TEST_F()` for the individual test cases?  Otherwise, I'm not sure these tests are actually being run.
</blockquote></details>

I am seeing these test cases get ran. However, `TestWithParam<>` might be making things more complicated to inspect than is needed here.

Refactored to use `TEST_F` on all test cases.


<!-- Sent from Reviewable.io -->

2021-12-15 21:26 UTC, markdroth approved these changes
This looks great!

> Reviewed 9 of 10 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27883#-:-MqzzENSBkFeeIM4B5lg:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @apolcyn)

___
*[test/core/iomgr/resolve_address_test.cc, line 60 at r7](https://reviewable.io/reviews/grpc/grpc/27883#-MqzYJBlBIFbCvxBsWfA:-MqzzAX302sqELE-deca:bepe8q6) ([raw file](https://github.com/grpc/grpc/blob/05cab498929c71f4e45b538d9c48fbe8dca1c877/test/core/iomgr/resolve_address_test.cc#L60)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I am seeing these test cases get ran. However, `TestWithParam<>` might be making things more complicated to inspect than is needed here.

Refactored to use `TEST_F` on all test cases.
</blockquote></details>

Thanks, that's much more readable!


<!-- Sent from Reviewable.io -->

2021-12-20 21:27 UTC, apolcyn commented
objc ios: https://github.com/grpc/grpc/issues/28389

basic tests php: https://github.com/grpc/grpc/issues/28390

pytnon linux/macos/windows/distribution: https://github.com/grpc/grpc/issues/28391

bazel rbe C++ macos actually passed, but are reported as failing here

All interop tests failing on python build issue:  https://github.com/grpc/grpc/issues/28391

2021-12-20 21:55 UTC, apolcyn commented
RBE msan C++ passed in https://source.cloud.google.com/results/invocations/b984a2b3-1d9e-4748-98bc-531c5da23f54/targets, but doesn't show up here on github

2021-12-20 22:01 UTC, merged