xDS Federation: bootstrap and xds_resolver changes
grpc/grpc pull request #27938
Opened 2021-11-04 06:44 UTC by donnadionne

Dusted off the previous PR and took care of code review comments from before.

I did start with a new branch as the old was just too old to bring up-to-date.

Would like for you to take a look for I write tests for the feature.

2021-11-04 17:11 UTC, markdroth requested changes
This looks like a good start.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-Mnfvijl-JZNqu2fU8gu:bhatqfr)* status: all files reviewed, 29 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 21 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfZ28t5wbYctH6fP0j:-MnfZ28u4jyyZxkInGRv:b-ewxz46) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L21)):*
> ```cpp
> #include <grpc/support/port_platform.h>
> 
> #include "absl/strings/escaping.h"
> ```

This include should move to the URI library; it's not needed here.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 273 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfZ8Xh1nqGPgXBK6X-:-MnfZ8Xh1nqGPgXBK6X0:b9631mx) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L273)):*
> ```cpp
>   grpc_pollset_set* interested_parties_;
>   RefCountedPtr<XdsClient> xds_client_;
>   std::string server_name_;
> ```

We don't need this field anymore.  Every place where it's used should actually be using either `lds_resource_name_` or `data_plane_authority_` instead.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 790 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfgMEnEpImbaxfTOT_:-MnfgMEnEpImbaxfTOTa:b-8hybi7) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L790)):*
> ```cpp
> void XdsResolver::StartLocked() {
>   grpc_error_handle error = GRPC_ERROR_NONE;
>   xds_client_ = XdsClient::GetOrCreate(args_, &error);
> ```

If we're passing in the `XdsClient` from the factory, then we shouldn't recreate it here.

That having been said, as per my comment below, I think we want to actually go back to your original approach and move the code from the factory into here rather than passing in the `XdsClient` from there.  If you take that suggestion, then creating the `XdsClient` here is the right thing to do.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 803 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnf_H671WOqZvQIyYAX:-Mnf_H671WOqZvQIyYAY:bfi4v15) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L803)):*
> ```cpp
>   auto watcher = absl::make_unique<ListenerWatcher>(Ref());
>   listener_watcher_ = watcher.get();
>   xds_client_->WatchListenerData(server_name_, std::move(watcher));
> ```

This should be using `lds_resource_name_` instead of `server_name_`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 812 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnf_1ctEabvtKYth1cM:-Mnf_1ctEabvtKYth1cN:bfi4v15) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L812)):*
> ```cpp
>   if (xds_client_ != nullptr) {
>     if (listener_watcher_ != nullptr) {
>       xds_client_->CancelListenerDataWatch(server_name_, listener_watcher_,
> ```

This should be using `lds_resource_name_` instead of `server_name_`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 817 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnf_8Iq73uSMBF0AQne:-Mnf_8Iq73uSMBF0AQnf:b-ft5hwy) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L817)):*
> ```cpp
>     if (route_config_watcher_ != nullptr) {
>       xds_client_->CancelRouteConfigDataWatch(
>           server_name_, route_config_watcher_, /*delay_unsubscription=*/false);
> ```

This looks like a pre-existing bug: It should actually be using `route_config_name_` instead of `server_name_`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 866 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnf_Pk1AJ7AD8Ndhg0i:-Mnf_Pk1AJ7AD8Ndhg0j:b2wc4ag) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L866)):*
> ```cpp
>   // Find the relevant VirtualHost from the RouteConfiguration.
>   XdsApi::RdsUpdate::VirtualHost* vhost =
>       rds_update.FindVirtualHostForDomain(server_name_);
> ```

This should be using `data_plane_authority_` instead of `server_name_`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 869 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnf_a-c8kr56-XrkHly:-Mnf_a-c8kr56-XrkHlz:b2wc4ag) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L869)):*
> ```cpp
>   if (vhost == nullptr) {
>     OnError(GRPC_ERROR_CREATE_FROM_CPP_STRING(
>         absl::StrCat("could not find VirtualHost for ", server_name_,
> ```

This should be using `data_plane_authority_` instead of `server_name_`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 989 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfdOv59UXKot4Z2FSg:-MnfdOv59UXKot4Z2FSh:b-betqa3) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L989)):*
> ```cpp
> class XdsResolverFactory : public ResolverFactory {
>  public:
>   bool IsValidUri(const URI& uri) const override {
> ```

This needs to check that the path part of the URI contains a valid data plane authority:

```
if (uri.path().empty() || uri.path().back() == '/') {
  gpr_log(GPR_ERROR, "URI path does not contain valid data plane authority");
  return false;
}
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 990 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfdKzJ8V04P47TLCgR:-MnfdKzJ8V04P47TLCgS:b-au0dpb) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L990)):*
> ```cpp
>  public:
>   bool IsValidUri(const URI& uri) const override {
>     if (GPR_UNLIKELY(!uri.authority().empty())) {
> ```

This check needs to be removed, since it is now valid to have an authority for an `xds` URI.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 1002 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfaZFh4PRtbLAEKK6v:-MnfaZFh4PRtbLAEKK6w:bwhvhov) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L1002)):*
> ```cpp
>     // We need to take the part of the URI path following the last
>     // "/" character or the entire path if the path contains no "/" character.
>     std::vector<std::string> v = absl::StrSplit(uri.path(), '/');
> ```

This can be done without so much unnecessary dynamic allocation using something like this:

```
size_t pos = uri.path().find_last_of('/');
if (pos == uri.path().npos) return uri.path();
return uri.path().substr(pos + 1);
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 1012 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnfg2pr2ch4PMUtFYJP:-Mnfg2pr2ch4PMUtFYJQ:bq2x3xa) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L1012)):*
> ```cpp
>     RefCountedPtr<XdsClient> xds_client =
>         XdsClient::GetOrCreate(args.args, &error);
>     gpr_log(GPR_INFO, "donna in CreateResolver scheme %s path %s a [...]

2021-11-10 10:04 UTC, donnadionne reviewed
Took care of all the comments; please take another look.  I will be working on tests in parallel.
thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-Mo8IY04BfTb3S88Fb1E:b-ayxepx)* status: 2 of 6 files reviewed, 29 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 21 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfZ28t5wbYctH6fP0j:-Mo0fXya1-Xm9anc34xO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L21)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This include should move to the URI library; it's not needed here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 273 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfZ8Xh1nqGPgXBK6X-:-Mo0guSqCVOdzwt1ZLE1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L273)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We don't need this field anymore.  Every place where it's used should actually be using either `lds_resource_name_` or `data_plane_authority_` instead.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 790 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfgMEnEpImbaxfTOT_:-Mo6HSe1Agj-bcnAwkQ9:bmiif2k) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L790)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're passing in the `XdsClient` from the factory, then we shouldn't recreate it here.

That having been said, as per my comment below, I think we want to actually go back to your original approach and move the code from the factory into here rather than passing in the `XdsClient` from there.  If you take that suggestion, then creating the `XdsClient` here is the right thing to do.
</blockquote></details>

kept here and moved the rest
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 803 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnf_H671WOqZvQIyYAX:-Mo10-sP3i-3RTtRnEY5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L803)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be using `lds_resource_name_` instead of `server_name_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 812 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnf_1ctEabvtKYth1cM:-Mo100G42j5TaTvddHPX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L812)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be using `lds_resource_name_` instead of `server_name_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 817 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnf_8Iq73uSMBF0AQne:-Mo11MAv9q2pyMVXj8vV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L817)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This looks like a pre-existing bug: It should actually be using `route_config_name_` instead of `server_name_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 866 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnf_Pk1AJ7AD8Ndhg0i:-Mo11MYQC2itSQdbbHyb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L866)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be using `data_plane_authority_` instead of `server_name_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 869 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnf_a-c8kr56-XrkHly:-Mo11NK45ls0FJMoT3FU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L869)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be using `data_plane_authority_` instead of `server_name_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 989 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfdOv59UXKot4Z2FSg:-Mo1H27x1dYvNck0n0eg:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L989)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to check that the path part of the URI contains a valid data plane authority:

```
if (uri.path().empty() || uri.path().back() == '/') {
  gpr_log(GPR_ERROR, "URI path does not contain valid data plane authority");
  return false;
}
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 990 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfdKzJ8V04P47TLCgR:-Mo1H1pJDOPM0KrFEaGy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L990)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check needs to be removed, since it is now valid to have an authority for an `xds` URI.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 1002 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfaZFh4PRtbLAEKK6v:-Mo1H2nm48KLkfKWlhf0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L1002)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be done without so much unnecessary dynamic allocation using something like this:

```
size_t pos = uri.path().find_last_of('/');
if (pos == uri.path().npos) return uri.path();
return uri.path().substr(pos + 1);
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 1012 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnfg2pr2ch4PMUtFYJP:-Mo8IImGB1jFq1K95Pa2:boy4ujx) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L1012)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove all of these log messages before merging.
</blockquote></details>

i still have a few left, but i will clean up.  we can keep this comment open just in case
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 1021 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-MnfhFUE01a7nMeGQWDh:-Mo6HPfxBmSWhbIdJxGe:b-7u62np) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L1021) [...]

2021-11-10 23:44 UTC, markdroth requested changes
I think the logic here still needs a bit of work.  It looks like you may be confusing the xDS authority with the data plane authority, which are actually two different things:
- The xDS authority is the authority of the "xds:" target URI and will be used in the authority of the "xdstp:" resource name.
- The data plane authority comes from the "xds:" target URI's path (the part after the last slash) and will be used to select the right virtual host.  (It's also used to populate the `:authority` header sent to the endpoint, although that doesn't happen in the xDS code.)

For example, for the target URI "xds://xds.example.com/path/to/server.example.com", the xDS authority is "xds.example.com" and the data plane authority is "server.example.com".

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-MoBBiS59F5ipX8JF7i7:b-uke6dy)* status: all files reviewed, 25 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 1030 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnfs1yo451OQVu25IoS:-MoAuLoq4MZuLjPNGsDs:brx0u4p) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L1030)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

it's just my comment that is incorrect which I have removed.
I check the uri for authority and commented as such.  please see a few lines below.
I think i captured the logic in the gRFC here.
</blockquote></details>

It's not just the comment; the code is incorrect.  I've pointed out the errors above, so resolving this thread.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 59 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoBAHi9E_nQ8P9cWEPd:-MoBAHi9E_nQ8P9cWEPe:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L59)):*
> ```cpp
>         args_(grpc_channel_args_copy(args.args)),
>         interested_parties_(args.pollset_set),
>         uri_(args.uri) {
> ```

`std::move()`
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 63 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoB8KyM1spIF4BpUR2W:-MoB8KyM1spIF4BpUR2X:b6kzjje) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L63)):*
> ```cpp
>       gpr_log(GPR_INFO,
>               "[xds_resolver %p] created for URI scheme %s path %s authority "
>               "%s lds resource name %s data plane authority %s",
> ```

We can't log the LDS resource name here, because we haven't determined it yet.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 784 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAvXQ07tF6HYMF66fp:-MoAvXQ07tF6HYMF66fq:bek4u4h) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L784)):*
> ```cpp
> //
> 
> std::string XdsResolver::GetDefaultAuthority(const URI& uri) {
> ```

This is basically a duplicate of the same method in `XdsResolverFactory`.  Instead of duplicating it, please replace it with a standalone function that can be called from both places.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 805 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAwGB3BgYzfyTdEjMY:-MoAwGB3BgYzfyTdEjMZ:b-guv46b) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L805)):*
> ```cpp
>     return;
>   }
>   std::string authority;
> ```

This variable is not needed.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 806 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAw2JD0Gba1rDudfCf:-MoAw2JD0Gba1rDudfCg:b-rls23a) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L806)):*
> ```cpp
>   }
>   std::string authority;
>   std::string target_hostname(absl::StripPrefix(uri_.path(), "/"));
> ```

Please call this variable `resource_name_fragment`.  Its only purpose is as the string that we use to replace the `%s` tokens in the resource name template we get from the bootstrap config.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 807 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoB87urAZLB-Mp3rybp:-MoB87urAZLB-Mp3rybq:bn2nmgp) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L807)):*
> ```cpp
>   std::string authority;
>   std::string target_hostname(absl::StripPrefix(uri_.path(), "/"));
>   data_plane_authority_ = GetDefaultAuthority(uri_);
> ```

Let's set this in the constructor instead of here.  And let's also allow the `GRPC_ARG_DEFAULT_AUTHORITY` to override this value if it's set.  We can use a standalone helper function like this:

```
std::string GetDataPlaneAuthority(const grpc_channel_args& args, const URI& uri) {
  const char* authority =
      grpc_channel_args_find_string(&args, GRPC_ARG_DEFAULT_AUTHORITY);
  if (authority != nullptr) return authority;
  return GetDefaultAuthority(uri);
}
```

And then in the ctor's initializer list, we can say `data_plane_authority_(GetDataPlaneAuthority(*args.args, uri_)`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 808 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAuaY-ALffbXPJSlWV:-MoAuaY-ALffbXPJSlWW:b-fpilk7) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L808)):*
> ```cpp
>   std::string target_hostname(absl::StripPrefix(uri_.path(), "/"));
>   data_plane_authority_ = GetDefaultAuthority(uri_);
>   std::vector<std::string> parts_of_uri = absl::StrSplit(target_hostname, "/");
> ```

This split is not needed.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 810 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAv7Xn13x12aj41vkX:-MoAv7Xn13x12aj41vkY:b-j9wf8m) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L810)):*
> ```cpp
>   std::vector<std::string> parts_of_uri = absl::StrSplit(target_hostname, "/");
>   GPR_ASSERT(parts_of_uri.size() == 1 || parts_of_uri.size() == 2);
>   if (parts_of_uri.size() == 2) {
> ```

This should be looking at `uri.authority()`, not at anything derived from `uri.path()`.

```
if (!uri.authority().empty()) {
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 813 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAwezj0k156Jv_SS38:-MoAwezj0k156Jv_SS39:b-f2gw5t) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L813)):*
> ```cpp
>     // target_uri.authority is set case
>     authority = parts_of_uri[0];
>     auto authority_config = xds_client_->bootstrap().LookupAuthority(authority);
> ```

This can use `uri.authority()` as the argument to `LookupAuthority()`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 813 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoB6Wtz-ZTCgWFvgNhN:-MoB6Wtz-ZTCgWFvgNhO:btkhcny) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L813)):*
> ```cpp
>     // target_uri.authority is set [...]

2021-11-12 07:29 UTC, donnadionne reviewed
Thanks Mark!  PTAL.. 
tests are coming, but I thought i'd address all the comments here for another review. 

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-MoI2-Hx9p6epcrTmoIT:bi4lvfy)* status: 6 of 8 files reviewed, 25 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 1030 at r1](https://reviewable.io/reviews/grpc/grpc/27938#-Mnfs1yo451OQVu25IoS:-MoFQ84Z2ki7KijlijPj:b74mcu5) ([raw file](https://github.com/grpc/grpc/blob/572c410badc9eb5728451c4ce52b77502355d40e/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L1030)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not just the comment; the code is incorrect.  I've pointed out the errors above, so resolving this thread.
</blockquote></details>

you are right i was confused about the 2 authority, i think i got it now
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 59 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoBAHi9E_nQ8P9cWEPd:-MoFIju-AZPZPWDOfmS3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 63 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoB8KyM1spIF4BpUR2W:-MoFJ5xiCkBI-kh0WinC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L63)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We can't log the LDS resource name here, because we haven't determined it yet.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 784 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAvXQ07tF6HYMF66fp:-MoFOF7-3JEpUeW6pIhO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L784)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is basically a duplicate of the same method in `XdsResolverFactory`.  Instead of duplicating it, please replace it with a standalone function that can be called from both places.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 805 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAwGB3BgYzfyTdEjMY:-MoFJDFCBnYt7SL6chN1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L805)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This variable is not needed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 806 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAw2JD0Gba1rDudfCf:-MoFJ_ZvBwG4sf9VSGDK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L806)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this variable `resource_name_fragment`.  Its only purpose is as the string that we use to replace the `%s` tokens in the resource name template we get from the bootstrap config.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 807 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoB87urAZLB-Mp3rybp:-MoFQ6aG4ozPspqGjDEL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L807)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's set this in the constructor instead of here.  And let's also allow the `GRPC_ARG_DEFAULT_AUTHORITY` to override this value if it's set.  We can use a standalone helper function like this:

```
std::string GetDataPlaneAuthority(const grpc_channel_args& args, const URI& uri) {
  const char* authority =
      grpc_channel_args_find_string(&args, GRPC_ARG_DEFAULT_AUTHORITY);
  if (authority != nullptr) return authority;
  return GetDefaultAuthority(uri);
}
```

And then in the ctor's initializer list, we can say `data_plane_authority_(GetDataPlaneAuthority(*args.args, uri_)`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 808 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAuaY-ALffbXPJSlWV:-MoFJhsb8GUq1g8TXnAi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L808)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This split is not needed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 810 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAv7Xn13x12aj41vkX:-MoFJiY68452Dx570oJI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L810)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be looking at `uri.authority()`, not at anything derived from `uri.path()`.

```
if (!uri.authority().empty()) {
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 813 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAwezj0k156Jv_SS38:-MoFJjGUB5as_Yit-dEU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L813)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can use `uri.authority()` as the argument to `LookupAuthority()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 813 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoB6Wtz-ZTCgWFvgNhN:-MoFJwNq2xm2vDtBc5tJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L813)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `const auto*` here, to make it clear to the reader that it's const and a pointer.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 824 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAwyMz0EI2Tw0IHakX:-MoFJxfM8CMQ1IP3IMjm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L824)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`uri.authority()`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 828 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoAxwxH3u1paj_JqcJS:-MoFK-GZAi5B7Gdy-4BM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L828)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should use `resource_name_fragment` [...]

2021-11-12 17:06 UTC, markdroth requested changes
This looks much better!  Comments are mostly cosmetic.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-MoK6Av9ET4ufU8PjTyc:b-27jw9)* status: all files reviewed, 18 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 48 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJuGuT9coJmoRvJbPZ:-MoJuGuT9coJmoRvJbP_:b-h3sa5g) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L48)):*
> ```cpp
> namespace {
> 
> static std::string GetDefaultAuthorityInternal(const URI& uri) {
> ```

No need for `static` inside an anonymous namespace.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 58 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJuJKrEY6O1X6a2oeX:-MoJuJKrEY6O1X6a2oeY:b-h3sa5g) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L58)):*
> ```cpp
> }
> 
> static std::string GetDataPlaneAuthority(const grpc_channel_args& args,
> ```

No need for `static` inside an anonymous namespace.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 818 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJuvM_7UASvierNK6_:-MoJuvM_7UASvierNK6a:bbgm5sw) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L818)):*
> ```cpp
>     if (authority_config == nullptr) {
>       gpr_log(GPR_ERROR, "Invalid target URI -- authority not found for %s.",
>               resource_name_fragment.c_str());
> ```

I think this should be logging `uri_.authority()`, not `resource_name_fragment`.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 847 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJvCpvCGFAN2K7Y-Jd:-MoJvCpvCGFAN2K7Y-Je:b-y5eduv) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L847)):*
> ```cpp
>     gpr_log(GPR_INFO,
>             "[xds_resolver %p] Started with lds_resource_name %s, "
>             "data_plane_authority %s, and authority %s",
> ```

There's no need to log the xDS resource name authority here, since that's going to be part of the resource name.  And there's no need to log the data plane authority here, since we already logged that in the ctor where we determined it.

I think it's sufficient to log the LDS resource name here, since that's the only thing we've really determined in this code.
___
*[src/core/ext/xds/xds_api.cc, line 849 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoK4aEX31dqnlxAZHHm:-MoK4aEX31dqnlxAZHHn:bruroxp) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_api.cc#L849)):*
> ```cpp
>   }
>   if (type_url ==
>       absl::StripPrefix(XdsApi::kLdsTypeUrl, "type.googleapis.com/")) {
> ```

I've sent you #28024, which I think is a better approach for this problem.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 45 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJomUYASPeKs1NP8yP:-MoJomUZ-SXwtSk7IdyO:b-5iqp9a) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L45)):*
> ```cpp
> // TODO(donnadionne): check to see if federation is enabled, this will be
> // removed once federation is fully integrated and enabled by default.
> bool XdsFederationEnabled() {
> ```

These three functions can be in an anonymous namespace.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 53 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJpMK24FJ13QQwN5rl:-MoJpMK24FJ13QQwN5rm:b-oh2yap) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L53)):*
> ```cpp
> }
> 
> grpc_error_handle ParseChannelCreds(const Json& json, size_t idx,
> ```

The `json` parameter should be of type `Json::Object`.  That way, you don't have to say `json.object_value()` everywhere you access it inside the function.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 58 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJpDe-4sZrT-B6licT:-MoJpDe-4sZrT-B6licU:bi4iev1) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L58)):*
> ```cpp
>   std::string type;
>   ParseJsonObjectField(json.object_value(), "type", &type, &error_list);
>   Json config;
> ```

This can use the json_util helper code:

```
const Json::Object* config_ptr = nullptr;
ParseJsonObjectField(json, "config", &config_ptr, &error_list, /*required=*/false);
// Select the first channel creds type that we support.
if (server->channel_creds_type.empty() &&
    XdsChannelCredsRegistry::IsSupported(type)) {
  Json config;
  if (config_ptr != nullptr) config = *config_ptr;
  if (!XdsChannelCredsRegistry::IsValidConfig(type, config)) {
    error_list.push_back(GRPC_ERROR_CREATE_FROM_CPP_STRING(absl::StrCat(
        "invalid config for channel creds type \"", type, "\"")));
  }
  server->channel_creds_type = std::move(type);
  server->channel_creds_config = std::move(config);
}
```
___
*[src/core/ext/xds/xds_bootstrap.cc, line 82 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJp5w88QQvNqP7d_bX:-MoJp5w88QQvNqP7d_bY:b-b2oerr) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L82)):*
> ```cpp
> }
> 
> grpc_error_handle ParseChannelCredsArray(const Json& json,
> ```

The `json` parameter should be of type `Json::Array`.  That way, you don't have to say `json.array_value()` every time you access it inside the function.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 91 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJqcjI07nQZO7eVuHP:-MoJqcjJ2gW4Y1M6nEQL:b-q4z08y) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L91)):*
> ```cpp
>           absl::StrCat("array element ", i, " is not an object")));
>     } else {
>       grpc_error_handle parse_error = ParseChannelCreds(child, i, server);
> ```

If you change the parameter type of `ParseChannelCreds()` to `Json::Object` as I suggested above, then this will need to be `child.object_value()`.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 143 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJr1ZxEPpLgNvAaZTJ:-MoJr1ZxEPpLgNvAaZTK:bi81ox8) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L143)):*
> ```cpp
>   ParseJsonObjectField(json.object_value(), "server_uri", &server.server_uri,
>                        &error_list);
>   auto it = json.object_value().find("channel_creds");
> ```

This can use the json_util helper code:

```
  const Json::Array* creds_array = nullptr;
  ParseJsonObjectField(json, "channel_creds", &creds_array, &error_list);
  if (creds_array != nullptr) {
    grpc_error_handle parse_error =
        ParseChannelCredsArray(*creds_array, &server);
    if (parse_error != GRPC_ERROR_NONE) error_list.push_back(parse_error);
  }
```
___
*[src/core/ext/xds/xds_bootstrap.cc, line 151 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJr73D79MhMsibsCgm:-MoJr73D79MhMsibsCgn:b-xwhooh) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L151)):*
> ```cpp
>         "\"channel_creds\" field is not an array"));
>   } else {
>     grpc_error_handle parse_error = ParseChannelCredsArray(it->second, &server);
> ```

If you change the parameter type of `ParseChannelCredsArray()` to `Json::Array` as I suggested a [...]

2021-11-12 17:08 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938)* status: all files reviewed, 19 unresolved discussions (waiting on @donnadionne and @markdroth)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/27938#-MoK6cI101cj6JWqyCeD:-MoK6cI101cj6JWqyCeE:blvocqx) (no related file):*
One more thing: Please also add tests for the bootstrap parsing code in test/core/xds/xds_bootstrap_test.cc.

Thanks!

---


<!-- Sent from Reviewable.io -->

2021-11-19 12:09 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938)* status: 4 of 8 files reviewed, 20 unresolved discussions (waiting on @donnadionne and @markdroth)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/27938#-Mos3dVp0dxttAi7F9_O:-Mos3dVqDAFHYRgHSTiS:b-s595sw) (no related file):*
Address all code review comments except for the new tests in bootstrap and uri.

i need to do a much needed merge to pick up the new changes

I really wanted to show you the test changes in xds_end2end_test.cc.  I did manage to write 1 test but I dont' think i made it very flexible.  So I thought i would check before writing more tests.

I also didn't separate it out into a separate PR as I wanted to see how the changes will work with a real test with authority servers

I am also unsure about the following:

bootstrap seems to be generated once before test starts; if we were to update it and regenerate in test, how will that work?  Would we have to regen the environment variable and args to take care of all cases.  As well, will the xds client pick the changes up? 

---
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 48 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJuGuT9coJmoRvJbPZ:-MorpZ-EAknwhsGzaGeX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `static` inside an anonymous namespace.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 58 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJuJKrEY6O1X6a2oeX:-MorpZNuB6KO2NtRxxeM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `static` inside an anonymous namespace.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 818 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJuvM_7UASvierNK6_:-Morq0AaEc_7dmp2MI9k:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L818)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this should be logging `uri_.authority()`, not `resource_name_fragment`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 847 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJvCpvCGFAN2K7Y-Jd:-MorqTwv1son4HH8TSMC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L847)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need to log the xDS resource name authority here, since that's going to be part of the resource name.  And there's no need to log the data plane authority here, since we already logged that in the ctor where we determined it.

I think it's sufficient to log the LDS resource name here, since that's the only thing we've really determined in this code.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 45 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJomUYASPeKs1NP8yP:-Moryuq1BQ62TIRE3eFC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L45)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These three functions can be in an anonymous namespace.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 53 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJpMK24FJ13QQwN5rl:-Mos0qULE8O6wYW6koAR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L53)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `json` parameter should be of type `Json::Object`.  That way, you don't have to say `json.object_value()` everywhere you access it inside the function.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 58 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJpDe-4sZrT-B6licT:-Mos0qvaCFtWcc5B-EXY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can use the json_util helper code:

```
const Json::Object* config_ptr = nullptr;
ParseJsonObjectField(json, "config", &config_ptr, &error_list, /*required=*/false);
// Select the first channel creds type that we support.
if (server->channel_creds_type.empty() &&
    XdsChannelCredsRegistry::IsSupported(type)) {
  Json config;
  if (config_ptr != nullptr) config = *config_ptr;
  if (!XdsChannelCredsRegistry::IsValidConfig(type, config)) {
    error_list.push_back(GRPC_ERROR_CREATE_FROM_CPP_STRING(absl::StrCat(
        "invalid config for channel creds type \"", type, "\"")));
  }
  server->channel_creds_type = std::move(type);
  server->channel_creds_config = std::move(config);
}
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 82 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJp5w88QQvNqP7d_bX:-Mos18F75M8mT6SgZrNg:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L82)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `json` parameter should be of type `Json::Array`.  That way, you don't have to say `json.array_value()` every time you access it inside the function.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 91 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJqcjI07nQZO7eVuHP:-Mos17xY-qVTRHQTnmOn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L91)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you change the parameter type of `ParseChannelCreds()` to `Json::Object` as I suggested above, then this will need to be `child.object_value()`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 143 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJr1ZxEPpLgNvAaZTJ:-Mos28j50X1SDSft0wnt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L143)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can use the json_util helper code:

```
  const Json::Array* creds_array = nullptr;
  ParseJsonObjectField(json, "channel_creds", &creds_array, &error_list);
  if (creds_array != nullptr) {
    grpc_error_handle parse_error =
        ParseChannelCredsArray(*creds_array, &server);
    if (parse_error != GRPC_ERROR_NONE) error_list.push_back(parse_error);
  }
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 151 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoJr73D79MhMsibsCgm:-Mos2B14BS_gdeGQ1QWX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_bootstrap.cc#L151)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you change the parameter type of `ParseChannelCredsArray()` to `Json::Array` as I suggested above,  [...]

2021-11-19 12:10 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938)* status: 4 of 8 files reviewed, 20 unresolved discussions (waiting on @markdroth)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/27938#-MoK6cI101cj6JWqyCeD:-Mos5eGN4I35OYsF0hMa:bto47eh) (no related file):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

One more thing: Please also add tests for the bootstrap parsing code in test/core/xds/xds_bootstrap_test.cc.

Thanks!
</blockquote></details>

sure i still need add these tests and those for uri parsing

---
___
*[src/core/ext/xds/xds_api.cc, line 849 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoK4aEX31dqnlxAZHHm:-Mos5_in7M-afag6iVaQ:bq7a7en) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_api.cc#L849)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I've sent you #28024, which I think is a better approach for this problem.
</blockquote></details>

i will do a merge shortly


<!-- Sent from Reviewable.io -->

2021-11-19 20:57 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938)* status: 3 of 8 files reviewed, 21 unresolved discussions (waiting on @markdroth)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/27938#-Motz2wB424przZfAzlq:-Motz2wCDsTuxV6vVV8B:bj26etc) (no related file):*
just synched with the latest.  let me know your comments.  But i'll work on more tests at the same time

---


<!-- Sent from Reviewable.io -->

2021-12-01 09:03 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938)* status: 3 of 9 files reviewed, 21 unresolved discussions (waiting on @markdroth)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/27938#-Motz2wB424przZfAzlq:-MppDQIzAYQdun2_04fK:bih2o6w) (no related file):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

just synched with the latest.  let me know your comments.  But i'll work on more tests at the same time
</blockquote></details>

updated test and how we pass in the balancer index to be used to form the xds server uri and authority xds server uri.

And fixed broken tests in xds and bootstrap.

Working on new tests for bootstrap, uri, and new cases.

Please let me know if there are any big changes that still may be needed; thank you!

---


<!-- Sent from Reviewable.io -->

2021-12-01 16:46 UTC, markdroth requested changes
This is moving in the right direction.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 5 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-MpqsTPuDSYd2VOpmuYv:b-qjvg5x)* status: 8 of 9 files reviewed, 22 unresolved discussions (waiting on @donnadionne and @markdroth)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/27938#-Mos3dVp0dxttAi7F9_O:-MpmY3fc5U26YGOCCmEq:bt7fosm) (no related file):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Address all code review comments except for the new tests in bootstrap and uri.

i need to do a much needed merge to pick up the new changes

I really wanted to show you the test changes in xds_end2end_test.cc.  I did manage to write 1 test but I dont' think i made it very flexible.  So I thought i would check before writing more tests.

I also didn't separate it out into a separate PR as I wanted to see how the changes will work with a real test with authority servers

I am also unsure about the following:

bootstrap seems to be generated once before test starts; if we were to update it and regenerate in test, how will that work?  Would we have to regen the environment variable and args to take care of all cases.  As well, will the xds client pick the changes up? 
</blockquote></details>

There should not be any cases where we regenerate the bootstrap file within a test.  We only read the bootstrap file at startup, so there's no reason to ever change it after that.

---
___
*[src/core/ext/xds/xds_api.cc, line 849 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoK4aEX31dqnlxAZHHm:-MplroNN2Cx_q55sNuAg:b-cfo6sb) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_api.cc#L849)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i will do a merge shortly
</blockquote></details>

Now that you've done this merge, I don't think you still need any of the changes in the `Is*dsInternal()` methods.
___
*[src/core/ext/xds/xds_bootstrap.h, line 86 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MplmYWT1EViV0DxG6Pc:-MplmYWT1EViV0DxG6Pd:bqwztvf) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/src/core/ext/xds/xds_bootstrap.h#L86)):*
> ```objc
>     absl::InlinedVector<XdsServer, 1> xds_servers;
> 
>     const XdsServer& server() const { return xds_servers[0]; }
> ```

Let's just remove this method, because it's going to be cumbersome to make it work in the case where the list is empty.  Instead, the caller can just look directly at the `xds_servers` data member.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 267 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mplbm0j0FJDMWnXXGwy:-Mplbm0j0FJDMWnXXGwz:b-5cvtjs) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/src/core/ext/xds/xds_bootstrap.cc#L267)):*
> ```cpp
> const XdsBootstrap::Authority* XdsBootstrap::LookupAuthority(
>     const std::string& name) const {
>   auto it = authorities_.find(std::string(absl::StripPrefix(name, "xdstp:")));
> ```

The API for this method requires the caller to pass in an authority name.  If the caller has a string starting with `xdstp:`, then they should strip off that prefix before calling this method.  This method should not know or care about that, since it's a detail of the caller's implementation.
___
*[src/core/ext/xds/xds_client.cc, line 2139 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mplf-dP53Mk-NHNnm2d:-Mplf-dQ3NF-7jsdfcQY:by18u86) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/src/core/ext/xds/xds_client.cc#L2139)):*
> ```cpp
>     // needed.
>     if (authority_state.channel_state == nullptr) {
>       if (resource->authority == "old:") {
> ```

Good catch about needing to handle old-style names differently here!  But I think there are a couple of additional issues here.

First, if the entry for the authority in the bootstrap file is not found, we should not just crash in `GPR_ASSERT()`; instead, we should handle that error the same way that we handle the resource name failing to parse.

Second, if the authority is found in the bootstrap file, it may not have its servers field set, in which case we need to fall back to the bootstrap config's global server list.

I suggest changing the code above (starting at line 2097) to something like this:

```
// Lambda for handling failure cases.
auto fail = [&](grpc_error_handle error) mutable {
  {
    MutexLock lock(&mu_);
    invalid_listener_watchers_[w] = watcher;
  }
  work_serializer_.Run(
      // TODO(yashykt): When we move to C++14, capture watcher using
      // std::move()
      [watcher, error]() ABSL_EXCLUSIVE_LOCKS_REQUIRED(&work_serializer_) {
        watcher->OnError(error);
      },
      DEBUG_LOCATION);
};
// Parse resource name.
auto resource = XdsApi::ParseResourceName(listener_name, XdsApi::IsLds);
if (!resource.ok()) {
  fail(GRPC_ERROR_CREATE_FROM_CPP_STRING(absl::StrFormat(
      "Unable to parse resource name for listener %s", listener_name)));
  return;
}
// Find server to use.
XdsBootstrap::XdsServer* xds_server = nullptr;
absl::string_view authority_name = resource->authority;
if (absl::ConsumePrefix(&authority_name, "xdstp:")) {
  XdsBootstrap::Authority* authority =
      bootstrap_->LookupAuthority(std::string(authority_name));
  if (authority == nullptr) {
    fail(GRPC_ERROR_CREATE_FROM_CPP_STRING(absl::StrCat(
             "authority \"", authority_name, "\" not present in bootstrap config")));
    return;
  }
  if (!authority->xds_servers.empty()) {
    xds_server = &authority->xds_servers[0];
  }
}
if (xds_server == nullptr) xds_server = &bootstrap_->server();
```

Then the code here can just do the same thing, regardless of whether the name is old or new style:

```
authority_state.channel_state =
    GetOrCreateChannelStateLocked(*xds_server);
```

Same thing for all resource types.
___
*[src/core/ext/xds/xds_client.cc, line 2172 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mplpcz19LKZF1crnaG5:-MplpBYy7JYd3OrEdB9a:b-jr8wpa) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/src/core/ext/xds/xds_client.cc#L2172)):*
> ```cpp
>   if (!listener_state.watchers.empty()) return;
>   authority_state.listener_map.erase(resource->id);
>   if (resource->authority == "old:") {
> ```

In the cancellation case, this conditional is not needed.  Instead, just say this:

```
authority_state.channel_state->UnsubscribeLocked(
    XdsApi::kLdsTypeUrl, *resource, delay_unsubscription);
```

Same thing for all resource types.
___
*[test/core/xds/xds_bootstrap_test.cc, line 327 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MplsIkCEdNZqYcXTa73:-MplsIkCEdNZqYcXTa74:b19ciio) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/core/xds/xds_bootstrap_test.cc#L327)):*
> ```cpp
>       grpc_error_std_string(error),
>       ::testing::ContainsRegex("errors parsing \"xds_servers\" array.*"
>                                "errors parsing xds server.*"
> ```

This looks like a regression.  The error message needs to say which index into the array the error is from, or the user won't know what to fix.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 188 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MpmZshc2wVsBKqUocD7:-MpmZshc2wVsBKqUocD8:b-75g9l3) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L188)):*
> ```cpp
>     "}";
> 
> constexpr char kBootstrapFileHeaderAndXdsServers[] =
> ```

All of these constant strings can move inside of `BootstrapBuilder` now.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 288 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mpm_3sKDZRLxUHsiY7_:-Mpm_3sKDZRLxUHsiY7a:byvg2it) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec4 [...]

2021-12-03 11:04 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938)* status: 8 of 9 files reviewed, 23 unresolved discussions (waiting on @donnadionne and @markdroth)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/27938#-Mos3dVp0dxttAi7F9_O:-MprQf1VAO7sHlMoVFY7:b-q8jzb0) (no related file):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There should not be any cases where we regenerate the bootstrap file within a test.  We only read the bootstrap file at startup, so there's no reason to ever change it after that.
</blockquote></details>

got it

---
*[a discussion](https://reviewable.io/reviews/grpc/grpc/27938#-MpzvkWS1fSaLodI-rTU:-MpzvkWS1fSaLodI-rTV:b5vsjvf) (no related file):*
Addressed all the code review comments and added bootstrap tests now.  PTAL Thank you

Still have 2 questions about the xds_end2end tests:
1. Removing the fake xds server resolver and always use localhost seem to break xdsServer tests
2. where best to store the pointer to the 2nd balancer created to represent the authority xds server; it must be created before the constrction of the base XdsEnd2endTest class as bootstrap is generated there; but any member var in the subclass XdsFederationTest will be created after the base class constructor, so it's hard to find that seam.  Should we have another balancer in the base XdsEnd2endTest?  Please see my comments near this code

---
___
*[src/core/ext/xds/xds_api.cc, line 849 at r4](https://reviewable.io/reviews/grpc/grpc/27938#-MoK4aEX31dqnlxAZHHm:-Mprhu7B8SbMBvYVUyzi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/99f9fda1b5d7554f2ee146d4e3028a475806cb03/src/core/ext/xds/xds_api.cc#L849)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Now that you've done this merge, I don't think you still need any of the changes in the `Is*dsInternal()` methods.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.h, line 86 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MplmYWT1EViV0DxG6Pc:-MprtuyH746wY-Eht5sn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/src/core/ext/xds/xds_bootstrap.h#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's just remove this method, because it's going to be cumbersome to make it work in the case where the list is empty.  Instead, the caller can just look directly at the `xds_servers` data member.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 267 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mplbm0j0FJDMWnXXGwy:-MptNRin4dFyOhR3TY7Y:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/src/core/ext/xds/xds_bootstrap.cc#L267)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The API for this method requires the caller to pass in an authority name.  If the caller has a string starting with `xdstp:`, then they should strip off that prefix before calling this method.  This method should not know or care about that, since it's a detail of the caller's implementation.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2139 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mplf-dP53Mk-NHNnm2d:-MpwdCubDnKDUf7TgtQW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/src/core/ext/xds/xds_client.cc#L2139)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Good catch about needing to handle old-style names differently here!  But I think there are a couple of additional issues here.

First, if the entry for the authority in the bootstrap file is not found, we should not just crash in `GPR_ASSERT()`; instead, we should handle that error the same way that we handle the resource name failing to parse.

Second, if the authority is found in the bootstrap file, it may not have its servers field set, in which case we need to fall back to the bootstrap config's global server list.

I suggest changing the code above (starting at line 2097) to something like this:

```
// Lambda for handling failure cases.
auto fail = [&](grpc_error_handle error) mutable {
  {
    MutexLock lock(&mu_);
    invalid_listener_watchers_[w] = watcher;
  }
  work_serializer_.Run(
      // TODO(yashykt): When we move to C++14, capture watcher using
      // std::move()
      [watcher, error]() ABSL_EXCLUSIVE_LOCKS_REQUIRED(&work_serializer_) {
        watcher->OnError(error);
      },
      DEBUG_LOCATION);
};
// Parse resource name.
auto resource = XdsApi::ParseResourceName(listener_name, XdsApi::IsLds);
if (!resource.ok()) {
  fail(GRPC_ERROR_CREATE_FROM_CPP_STRING(absl::StrFormat(
      "Unable to parse resource name for listener %s", listener_name)));
  return;
}
// Find server to use.
XdsBootstrap::XdsServer* xds_server = nullptr;
absl::string_view authority_name = resource->authority;
if (absl::ConsumePrefix(&authority_name, "xdstp:")) {
  XdsBootstrap::Authority* authority =
      bootstrap_->LookupAuthority(std::string(authority_name));
  if (authority == nullptr) {
    fail(GRPC_ERROR_CREATE_FROM_CPP_STRING(absl::StrCat(
             "authority \"", authority_name, "\" not present in bootstrap config")));
    return;
  }
  if (!authority->xds_servers.empty()) {
    xds_server = &authority->xds_servers[0];
  }
}
if (xds_server == nullptr) xds_server = &bootstrap_->server();
```

Then the code here can just do the same thing, regardless of whether the name is old or new style:

```
authority_state.channel_state =
    GetOrCreateChannelStateLocked(*xds_server);
```

Same thing for all resource types.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2172 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mplpcz19LKZF1crnaG5:-MpwdDvh2HpXtTGWRWnj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/src/core/ext/xds/xds_client.cc#L2172)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In the cancellation case, this conditional is not needed.  Instead, just say this:

```
authority_state.channel_state->UnsubscribeLocked(
    XdsApi::kLdsTypeUrl, *resource, delay_unsubscription);
```

Same thing for all resource types.
</blockquote></details>

Done.
___
*[test/core/xds/xds_bootstrap_test.cc, line 327 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MplsIkCEdNZqYcXTa73:-MpzvdYQ8cqPbuSiwb-G:bv5jr9s) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/core/xds/xds_bootstrap_test.cc#L327)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This looks like a regression.  The error message needs to say which index into the array the error is from, or the user won't know what to fix.
</blockquote></details>

fixed and added more tests
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 188 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MpmZshc2wVsBKqUocD7:-MpyuqkS6JJILSUoggtd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L188)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All of these constant strings can move inside of `BootstrapBuilder` now.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 288 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mpm_3sKDZRLxUHsiY7_:-Mpz3DH2DV4YlWvQE2nW:b-zawsme) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L288)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Now that we're writing these files once per test, I don't think we need a global variable anymor [...]

2021-12-04 00:20 UTC, markdroth requested changes
The existing test infrastructure in xds_end2end_test clearly needs more work.  I do want to see some improvement there, but I think we need to be thoughtful about when to do it.  If we can do something about it relatively quickly now, then I'm fine with setting this PR aside for a bit to improve that and then coming back to this.  But if it is going to turn into a larger project, then I think we should defer it for now and keep limping along with what we have (e.g., going back to using `SetUp()` instead of the ctor for initialization).

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-Mq1nHxs4sIKbdxAf_6t:bxe79v7)* status: all files reviewed, 20 unresolved discussions (waiting on @donnadionne, @markdroth, and @yashykt)

___
*[test/core/xds/xds_bootstrap_test.cc, line 68 at r9](https://reviewable.io/reviews/grpc/grpc/27938#-Mq1E-hXDdHLK3GQ-90e:-Mq1E-hXDdHLK3GQ-90f:b-rlwj3c) ([raw file](https://github.com/grpc/grpc/blob/a2b6ffae5ecd2a8e7f23e6ecdfce0aaa3d0ca437/test/core/xds/xds_bootstrap_test.cc#L68)):*
> ```cpp
>       "    }"
>       "  ],"
>       "  \"authorities\": {"
> ```

Please add checks below that this actually generates the right authorities map in the resulting bootstrap object.
___
*[test/core/xds/xds_bootstrap_test.cc, line 69 at r9](https://reviewable.io/reviews/grpc/grpc/27938#-Mq1EAnE7NXEuPfbapJR:-Mq1EAnE7NXEuPfbapJS:b-texuqp) ([raw file](https://github.com/grpc/grpc/blob/a2b6ffae5ecd2a8e7f23e6ecdfce0aaa3d0ca437/test/core/xds/xds_bootstrap_test.cc#L69)):*
> ```cpp
>       "  ],"
>       "  \"authorities\": {"
>       "    \"xds.example.com\": {"
> ```

Please add multiple authorities here, just to make sure we properly handle that case.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 288 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mpm_3sKDZRLxUHsiY7_:-Mq1FOQA9UnfQZafElOv:bb5r0zg) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L288)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

moved, is gpr_free the right call to clean up?  i got a crash there.
</blockquote></details>

As we discussed, we need to actually delete the file from the filesystem at the end of the test.  It looks like you're using the `remove(3)` libc call to do that, which looks good.  (I wasn't sure it was portable to, e.g., Windows, but it looks like we have other tests using it, so I assume it works.)

I'm not sure why you're seeing a crash in `gpr_free()`.  That looks correct to me.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 408 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mpm_Q6gCArIKaPEgm_R:-Mq1Fyrp7zgogv0zs3CN:byplroc) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L408)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done. I have implemented having XdsEnd2endTest ctor take on Bootstrapbuilder.  But there is a problem.

we need to pass in the xds server port which means we have to go ahead and create that second balancer before XdsEnd2endTest ctor and also hold on to a pointer to this balancer; but where best to do that?  In the subclass like the way i have right now is not right, because the balancer will be created after the XdsEnd2endTest ctor which is too late.  But where to do it then?  It's almost like it should just be in the base class XdsEnd2endTest, then do we still pass in the builder?
</blockquote></details>

As we discussed, let's go ahead and move the logic from the `XdsEnd2endTest` ctor back into the `SetUp()` method, and the corresponding code from the dtor into the `TearDown()` method.  That way, the subclass can do whatever setup it needs to before calling the base class's `SetUp()` method.  Note that @yashykt previously moved this logic from `SetUp()` and `TearDown()` into the ctor and dtor in #27911, so you'll need to be careful not to break any of what he did there.

In the long term, I want to come up with a better structure here that doesn't require such deep integration between `XdsEnd2endTest` and its subclasses.  In particular, I'd like to find a reasonable way to move all of the setup logic into helper functions that can be explicitly called by tests, rather than having it all happen implicitly as soon as the test suite is instantiated.  But I don't want to block this PR on that work.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 803 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MpqqmcnCFbdawrVXNbC:-Mq1bczD16gFKMju5oQv:b-u649qv) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L803)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i was not successful at that caused a lot of failures for server tests that use grpc.TEST_ONLY_DO_NOT_USE_IN_PROD.xds_bootstrap_config
</blockquote></details>

Let's try to figure out what's causing these failures.  In principle, I don't know of any reason why this shouldn't work.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 929 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MpmPSPHCPkzsW-FXy3x:-Mq1eK2DBtWfqcIvTQQN:bqp5d1d) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L929)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
oh i think i wrapped it in string due to this warning: result of comparison against a string literal is unspecified (use an explicit string comparison function instead)
</blockquote></details>

Right, that won't work, because you're comparing pointer addresses, not string contents.  Instead, I suggest `*xds_authority == '\0'`.

Coincidentally, I just sent you #28274, which removes this particular code block entirely, so the problem will go away if we merge in those changes.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1982 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MpqrbxeCc_pkQAh8dak:-Mq1j8hv8vOumVUCjrZr:b-4uv7ut) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L1982)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

hum... i hope to add a few more test like listener_resource_name_template set vs not set, so each test would be a new subclass of base XdsEnd2EndTest as we need to supply a different BootStrapBuilder, it's a bit hard to find a seam 
</blockquote></details>

If I'm understanding your comment correctly, your concern is that you are going to want different bootstrap configs for different individual tests, rather than for different test suites?  If so, I agree that that would make things more flexible here, and it fits in with what I said above about wanting to find a better structure here that doesn't require such deep integration between `XdsEnd2endTest` and its subclasses.  I would very much like to see some resutructuring of these tests to allow that kind of thing, and if you think you can do that without too much delay (e.g., no more than a week or so), I'd fully support that.  But if it's going to turn into a larger project that will delay this PR for longer than that, then I'd prefer that we just live with the limitation for now and create duplicate test suites where we need to do so.

That having been said, I'm not sure if I'm interpretting your comment correctly, since I don't see what the above issue has to do with the `BootstrapBuilder::AddAuthority()` method...
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 597 at r9](https://reviewable.io/reviews/grpc/grpc/27938#-Mq1Hl1b5pxaC8jAP2lF:-Mq1Hl1b5pxaC8jAP2lG:b3wnb8h) ([raw file](https://github.com/grpc/grpc/blob/a2b6ffae5ecd2a8e7f23e6ecdfce0aaa3d0ca43 [...]

2021-12-08 12:36 UTC, donnadionne reviewed
going with the SetUp for now

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-MqOyLm56LDgSqPPqdQf:b-r0kxaa)* status: 7 of 9 files reviewed, 18 unresolved discussions (waiting on @markdroth and @yashykt)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/27938#-MqP1azk0RcT4HtlTs59:-MqP1azk0RcT4HtlTs5A:b3q3hgu) (no related file):*
Addressed code review comments, and fixed all tests to use the new strucutre: SetUp() is back and all tests pass.

 PTAL thank you!

---
___
*[test/core/xds/xds_bootstrap_test.cc, line 68 at r9](https://reviewable.io/reviews/grpc/grpc/27938#-Mq1E-hXDdHLK3GQ-90e:-MqIc75SDP_pTchNsmmA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a2b6ffae5ecd2a8e7f23e6ecdfce0aaa3d0ca437/test/core/xds/xds_bootstrap_test.cc#L68)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add checks below that this actually generates the right authorities map in the resulting bootstrap object.
</blockquote></details>

Done.
___
*[test/core/xds/xds_bootstrap_test.cc, line 69 at r9](https://reviewable.io/reviews/grpc/grpc/27938#-Mq1EAnE7NXEuPfbapJR:-MqIc7TqCCi47MxcOC32:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a2b6ffae5ecd2a8e7f23e6ecdfce0aaa3d0ca437/test/core/xds/xds_bootstrap_test.cc#L69)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add multiple authorities here, just to make sure we properly handle that case.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 288 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mpm_3sKDZRLxUHsiY7_:-MqIcF9N-inMOAtI-0SK:b-lheduy) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L288)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As we discussed, we need to actually delete the file from the filesystem at the end of the test.  It looks like you're using the `remove(3)` libc call to do that, which looks good.  (I wasn't sure it was portable to, e.g., Windows, but it looks like we have other tests using it, so I assume it works.)

I'm not sure why you're seeing a crash in `gpr_free()`.  That looks correct to me.
</blockquote></details>

i don't see the crash anymore and yes I do see other tests doing the same
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 408 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-Mpm_Q6gCArIKaPEgm_R:-MqOyA7WC2qjY0sFiQCd:b-rog6wc) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L408)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As we discussed, let's go ahead and move the logic from the `XdsEnd2endTest` ctor back into the `SetUp()` method, and the corresponding code from the dtor into the `TearDown()` method.  That way, the subclass can do whatever setup it needs to before calling the base class's `SetUp()` method.  Note that @yashykt previously moved this logic from `SetUp()` and `TearDown()` into the ctor and dtor in #27911, so you'll need to be careful not to break any of what he did there.

In the long term, I want to come up with a better structure here that doesn't require such deep integration between `XdsEnd2endTest` and its subclasses.  In particular, I'd like to find a reasonable way to move all of the setup logic into helper functions that can be explicitly called by tests, rather than having it all happen implicitly as soon as the test suite is instantiated.  But I don't want to block this PR on that work.
</blockquote></details>

Added SetUp back and ensured all tests still pass.  Still follwoing Yash's change to start backend close to usage time when possible
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 803 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MpqqmcnCFbdawrVXNbC:-MqNgnRf-MQxTBp9_nhV:b-odrhti) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L803)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's try to figure out what's causing these failures.  In principle, I don't know of any reason why this shouldn't work.
</blockquote></details>

we now return UNAVAILBLE as oppose to DEADLINE_EXCEEDED, tests changed
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 929 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MpmPSPHCPkzsW-FXy3x:-MqNn2lq95357LLkjG1b:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L929)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Right, that won't work, because you're comparing pointer addresses, not string contents.  Instead, I suggest `*xds_authority == '\0'`.

Coincidentally, I just sent you #28274, which removes this particular code block entirely, so the problem will go away if we merge in those changes.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1982 at r7](https://reviewable.io/reviews/grpc/grpc/27938#-MpqrbxeCc_pkQAh8dak:-MqP1UDDDpJi2L58WR0C:bouapxl) ([raw file](https://github.com/grpc/grpc/blob/a0eee2fdec49b31deb442b1e30f939c7c3a6c10c/test/cpp/end2end/xds/xds_end2end_test.cc#L1982)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If I'm understanding your comment correctly, your concern is that you are going to want different bootstrap configs for different individual tests, rather than for different test suites?  If so, I agree that that would make things more flexible here, and it fits in with what I said above about wanting to find a better structure here that doesn't require such deep integration between `XdsEnd2endTest` and its subclasses.  I would very much like to see some resutructuring of these tests to allow that kind of thing, and if you think you can do that without too much delay (e.g., no more than a week or so), I'd fully support that.  But if it's going to turn into a larger project that will delay this PR for longer than that, then I'd prefer that we just live with the limitation for now and create duplicate test suites where we need to do so.

That having been said, I'm not sure if I'm interpretting your comment correctly, since I don't see what the above issue has to do with the `BootstrapBuilder::AddAuthority()` method...
</blockquote></details>

ok i will create multiple suite then
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 597 at r9](https://reviewable.io/reviews/grpc/grpc/27938#-Mq1Hl1b5pxaC8jAP2lF:-MqNgLS61uj0fmiafrqq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a2b6ffae5ecd2a8e7f23e6ecdfce0aaa3d0ca437/test/cpp/end2end/xds/xds_end2end_test.cc#L597)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this should be called `AddAuthority()`, and it should have the ability to add different authorities under different names.  We need to store the authority data in a map rather than in a single set of values.

For example:

```
class BootstrapBuilder {
 public:
  BootstrapBuilder& AddAuthority(
      const std::string& authority, const std::string& server = "",
      const std::string& client_listener_resource_name_template = "") {
    authorities_[authority] = {server, client_listener_resource_name_template};
    return *this;
  }

 private:
  struct AuthorityInfo {
    std::string server;
    std::string client_listener_resource_name_template;
  };
  std::map<std::string /*authority_name*/, AuthorityInfo> authorities_;
}
```
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 605 at r9](https://reviewable.io/reviews/grpc/grpc/27938#-Mq1HyGn9RDxqjRrfXTS:-MqNgNbODK5rmyUULVhe:b-896fix) ([raw file](https://githu [...]

2021-12-08 22:41 UTC, markdroth requested changes
The test structure is looking a lot better now!  There are a few more things we can do to improve it, and then you can get down to writing the actual tests.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-MqRBx4o0uwO0NSGDckf:b4brzbk)* status: all files reviewed, 13 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[test/core/xds/xds_bootstrap_test.cc, line 89 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQvJQuBBFom1R_pJqN:-MqQvJQv54E5bE3SWFUU:bmnjas9) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/core/xds/xds_bootstrap_test.cc#L89)):*
> ```cpp
>       "\"xdstp://xds.example2.com/envoy.config.listener.v3.Listener/grpc/"
>       "server/"
>       "%s\","
> ```

This can probably go on the previous line.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 624 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQvk5R7_M-HDnmspu5:-MqQvk5R7_M-HDnmspu6:b-nhtefm) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L624)):*
> ```cpp
> 
>    private:
>     bool v2_ = false;
> ```

Declaration order should be first types (like structs), then methods, then data members, as per:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 667 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQwP4z5l_PlbIiHLWp:-MqQwP4z5l_PlbIiHLWq:b-yxzxks) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L667)):*
> ```cpp
>           "    }\n"
>           "  }";
>       return absl::StrCat(kXdsNode);
> ```

No need for `absl::StrCat()` here; just return `kXdsNode` directly.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 673 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQwt5s0L7RqIVcCCKA:-MqQwt5s0L7RqIVcCCKB:b-xezlq4) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L673)):*
> ```cpp
>       constexpr char kBootstrapFileCertificateProviders[] =
>           "  \"certificate_providers\": {\n"
>           "    \"fake_plugin1\": {\n"
> ```

Instead of hard-coding all of these plugins, let's give the builder a setter method to add new plugins, just like it has for authorities.  That way, we don't need to set these outside of the security tests.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 797 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQxREZBQJ2-EetOEw7:-MqQxREZBQJ2-EetOEw8:b-lxew2h) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L797)):*
> ```cpp
>     balancer_ = CreateAndStartBalancer();
>     // Create fake resolver response generators used by client.
>     if (GetParam().use_fake_resolver()) {
> ```

Please merge in the changes from #28274, to make sure that there are no conflicts.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 809 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQxvAJEvaxG0eV20yR:-MqQxvAJEvaxG0eV20yS:b4f5krg) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L809)):*
> ```cpp
>     }
>     if (!lb_expected_authority_.empty()) {
>       if (lb_expected_authority_ == "localhost:%s") {
> ```

This should use `%d` instead of `%s`.  That way, you can set it with:

```
lb_expected_authority_ = absl::StrFormat(lb_expected_authority_, balancer_->port());
```
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 825 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQyGc_Ex43yGthjgXE:-MqQyGcaD-ZS_jIOh6MR:bp77gdr) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L825)):*
> ```cpp
>     }
>     bootstrap_ = bootstrap_builder_.Build();
>     gpr_log(GPR_INFO, "donna bootstrap %s", bootstrap_.c_str());
> ```

Please remove before merging.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1230 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQylV9-YAx-VlPfNkj:-MqQylV9-YAx-VlPfNkk:b-haw53d) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L1230)):*
> ```cpp
>   }
> 
>   void SetNextResolutionForLbChannelAllBalancers(
> ```

If we're no longer using the fake resolver for the xDS channel, then this method is no longer needed.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1968 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQyymAAo-IoqhtGZUp:-MqQyymAAo-IoqhtGZUq:b-h1zwjx) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L1968)):*
> ```cpp
>   }
> 
>   void SetBootstrapBuilder(const BootstrapBuilder& bootstrap_builder) {
> ```

This method isn't necessary.  The data members here are protected, not private, so they can be accessed directly in subclasses or in individual tests.  (The style guide has an exception to allow data members to be protected instead of private in tests.)
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1995 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQzO7cCPUtJkfo4Ar7:-MqQzO7cCPUtJkfo4Ar8:b-ehuqrz) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L1995)):*
> ```cpp
>   Cluster default_cluster_;
>   bool use_xds_enabled_server_;
>   std::string lb_expected_authority_;
> ```

It looks like the only purpose for these two data members is to be stored in the ctor and then used in `SetUp()`.  If that's the case, then I don't think we need them.  Instead, I suggest moving the contents of `SetUp()` into a new method that takes these values as parameters, and then having `SetUp()` call that method with default parameters.  In other words:

```
void CreateClientsAndServers(
    BootstrapBuilder builder = BootstrapBuilder(),
    const char* lb_expected_authority = "") {
  // ...contents of SetUp()...
}

void SetUp() { CreateClientsAndServers(); }
```

This way, any subclass that does not want to override these parameters does not need to override `SetUp()` at all, but a subclass that does want to override these parameters can have a `SetUp()` method that calls `CreateClientsAndServers()` with non-default parameters instead of calling the base class's `SetUp()` method.

Note that this approach would actually also allow you to set a different bootstrap config in each individual test if you wanted to, without having to create a separate test suite for each bootstrap file variant.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 8851 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqRB85G0rZ6YErYLPwB:-MqRB85G0rZ6YErYLPwC:b-how6h4) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L8851)):*
> ```cpp
>                                              default_server_route_config_);
>   backends_[0]->Start();
>   ASSERT_TRUE(WaitForLdsNack()) << "timed out waiting for NACK";
> ```

Why exactly did these tests change from failing with DEADLINE_EXCEEDED to failing with UNAVAILABLE?


<!-- Sent from Reviewable.io -->

2021-12-15 10:32 UTC, donnadionne reviewed
Test infrastructure changes settled and old tests are passing no regression.

More tests written!  PTAL, thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-MqxdMXZ7nJyltXmwmIv:b-i8t58j)* status: 4 of 9 files reviewed, 12 unresolved discussions (waiting on @markdroth)

___
*[test/core/xds/xds_bootstrap_test.cc, line 89 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQvJQuBBFom1R_pJqN:-MqutC6C7BiTHjFp9Q4B:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/core/xds/xds_bootstrap_test.cc#L89)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can probably go on the previous line.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 624 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQvk5R7_M-HDnmspu5:-MquujCQEDAc74FGphAG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L624)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Declaration order should be first types (like structs), then methods, then data members, as per:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 667 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQwP4z5l_PlbIiHLWp:-Mqv79YOER6tHckcybXa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L667)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `absl::StrCat()` here; just return `kXdsNode` directly.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 673 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQwt5s0L7RqIVcCCKA:-MqxA6mm2SCnKJ-9JPX9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L673)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of hard-coding all of these plugins, let's give the builder a setter method to add new plugins, just like it has for authorities.  That way, we don't need to set these outside of the security tests.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 797 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQxREZBQJ2-EetOEw7:-MquvNPW5tFfPxO7pc1y:b7jkqcp) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L797)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please merge in the changes from #28274, to make sure that there are no conflicts.
</blockquote></details>

no conflicts all work
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 809 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQxvAJEvaxG0eV20yR:-Mqux6Bk7zWAvXhBqwV7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L809)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should use `%d` instead of `%s`.  That way, you can set it with:

```
lb_expected_authority_ = absl::StrFormat(lb_expected_authority_, balancer_->port());
```
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 825 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQyGc_Ex43yGthjgXE:-MquxE6XDhmESIc1Et_Z:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L825)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove before merging.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1230 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQylV9-YAx-VlPfNkj:-Mqv6waD2r2Qt86xGmjR:b-w9n44) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L1230)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're no longer using the fake resolver for the xDS channel, then this method is no longer needed.
</blockquote></details>

all removed
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1968 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQyymAAo-IoqhtGZUp:-Mqvy6r6A8EUBT50IKcR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L1968)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This method isn't necessary.  The data members here are protected, not private, so they can be accessed directly in subclasses or in individual tests.  (The style guide has an exception to allow data members to be protected instead of private in tests.)
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1995 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqQzO7cCPUtJkfo4Ar7:-MqwP_-OA5L4dOw9J0TZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L1995)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like the only purpose for these two data members is to be stored in the ctor and then used in `SetUp()`.  If that's the case, then I don't think we need them.  Instead, I suggest moving the contents of `SetUp()` into a new method that takes these values as parameters, and then having `SetUp()` call that method with default parameters.  In other words:

```
void CreateClientsAndServers(
    BootstrapBuilder builder = BootstrapBuilder(),
    const char* lb_expected_authority = "") {
  // ...contents of SetUp()...
}

void SetUp() { CreateClientsAndServers(); }
```

This way, any subclass that does not want to override these parameters does not need to override `SetUp()` at all, but a subclass that does want to override these parameters can have a `SetUp()` method that calls `CreateClientsAndServers()` with non-default parameters instead of calling the base class's `SetUp()` method.

Note that this approach would actually also allow you to set a different bootstrap config in each individual test if you wanted to, without having to create a separate test suite for each bootstrap file variant.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 8851 at r11](https://reviewable.io/reviews/grpc/grpc/27938#-MqRB85G0rZ6YErYLPwB:-Mqv7-Nf8pNK2ApOHJZh:b-457n96) ([raw file](https://github.com/grpc/grpc/blob/102a9c821f4b55c19804f19db8302019a48e6765/test/cpp/end2end/xds/xds_end2end_test.cc#L8851)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why exactly did these tests change from failing with DEADLINE_EXCEEDED to failing with UNAVAILABLE?
</blockquote></details>

as discussed separated; fixed by using ENV_VAR bootstrap so that we share xds client.


<!-- Sent from Reviewable.io -->

2021-12-15 17:23 UTC, markdroth requested changes
This is looking really good!  There are some details that still need to be fixed in the tests, and a few missing tests, but the overall structure is great.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 5 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-Mqz6Tid6WUoQ9lohw1A:b-rjyrfa)* status: all files reviewed, 21 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_api.cc, line 63 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-MqyoUNME7JogkjN8W5B:-MqyoUNN4_u-OD2sC15p:b-2j95jk) ([raw file](https://github.com/grpc/grpc/blob/0087990e072acf2d238e0ea4c23139812ca9ae59/src/core/ext/xds/xds_api.cc#L63)):*
> ```cpp
> 
> namespace grpc_core {
> ```

This one-line whitespace-only change is the only remaining change in this file in this PR.  I suggest reverting this so that we're not modifying this file.
___
*[src/core/lib/uri/uri_parser.h, line 59 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoA9iXb-khJJVamrDs0:-MqyqES85HL_OOPzYHTS:b-ywmy8t) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/lib/uri/uri_parser.h#L59)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

will add this along with xds_end2end_test
</blockquote></details>

Still need to add tests for this.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 565 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqyr5715be9orYyfOV-:-Mqyr5721UZOf-UIP_Kz:b-hxd3q7) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L565)):*
> ```cpp
>     }
>     BootstrapBuilder& SetClientDefaultListenerResourceNameTemplate(
>         const std::string& client_default_listener_resource_name_template =
> ```

This parameter should not have a default value.  There's no point in calling a setter method without specifying a value.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 571 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-MqyqT0z1HsJmJpFwxgp:-MqyqT0z1HsJmJpFwxgq:b-h8wwrs) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L571)):*
> ```cpp
>       return *this;
>     }
>     BootstrapBuilder& AddPlugin(const std::string& key, const std::string& name,
> ```

Please call this `AddCertificateProviderPlugin()`.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 572 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-MqyqnKpCkU_mARIGAhe:-MqyqnKpCkU_mARIGAhf:b95nzmd) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L572)):*
> ```cpp
>     }
>     BootstrapBuilder& AddPlugin(const std::string& key, const std::string& name,
>                                 const std::string& certificate_file = "",
> ```

Let's make this a little more general: Instead of assuming that the plugin config will have these three fields, let's just have the caller pass in the plugin config as a JSON string, so that they can format it however they want.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 814 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz4su15sV64I3Z2c-a:-Mqyrmgn0roUov9OQCYK:b-91xpaq) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L814)):*
> ```cpp
>       if (lb_expected_authority == "localhost:%d") {
>         lb_expected_authority =
>             absl::StrFormat("localhost:%d", balancer_->port());
> ```

Please use `lb_expected_authority` as the format string instead of hard-coding the duplicate string.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 853 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz56XmDZIAZvfCAtKM:-Mqz56XmDZIAZvfCAtKN:b-s5kx46) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L853)):*
> ```cpp
>   }
> 
>   void SetUp() { CreateClientsAndServers(); }
> ```

This needs `override`.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2328 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqysyci95BDrK3hZPkr:-Mqysyci95BDrK3hZPks:b-euepc8) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2328)):*
> ```cpp
>   balancer_->ads_service()->SetCdsResource(cluster);
>   auto channel2 = CreateChannel(
>       /*failover_timeout=*/0, /*server_name=*/kServerName);
> ```

These parameters are the default values, so they don't need to be specified.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2542 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz4BLs4vsHPdpolDmP:-Mqz4BLs4vsHPdpolDmQ:b-lpk6f6) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2542)):*
> ```cpp
> }
> 
> class XdsFederationTest : public XdsEnd2endTest {
> ```

These client-side tests look really good!

Please also add a server-side test where the bootstrap config sets `server_listener_resource_name_template` to a new-style name.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2543 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-MqytGQo8Oad0RLLeqz1:-MqytGQo8Oad0RLLeqz2:b-gnm74n) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2543)):*
> ```cpp
> 
> class XdsFederationTest : public XdsEnd2endTest {
>  public:
> ```

This should be `protected`.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2563 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz-IzJ3NZu1LdplClM:-Mqz-IzJ3NZu1LdplClN:b-l2tu9d) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2563)):*
> ```cpp
> };
> 
> // Tests federation basic with URL "server.example.com"
> ```

Let's make this comment a little simpler:

"""
Channel is created with URI "xds:///server.example.com".
Bootstrap config default client listener template uses new-style name with authority "xds.example.com".
"""
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2606 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqyzegb87kj8VusK53K:-Mqyzegc6SGhxPfQR6gw:b-tto8kh) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2606)):*
> ```cpp
>   authority_balancer_->ads_service()->SetCdsResource(new_cluster);
>   // New Route
>   RouteConfiguration new_route_config = default_route_config_;
> ```

As per my comment below, we should also run this test with RDS enabled, which means that we'll need a new-style name for the RDS resource as well.

Same for all of the federation tests.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2628 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz-m9q-JTM82mOGC3S:-Mqz-m9q-JTM82mOGC3T:b-bjcsoe) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2628)):*
> ```cpp
> }
> 
> // Tests federation basic with URL "xds.example.com/new-server.example.com"
> ```

Let's make this comment a little simpler:

"""
Channel is created with URI "xds://xds.example.com/server.example.com".
In bootstrap config, authority has no client listener template, so we use the default.
"""
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2645 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz1RSr8gnjW_m_3K2H:-Mqz1RSr8gnjW_m_3K2I:brhxl4v) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2645)):*
> ```cpp
>       "xdstp://xds.example.com/envoy.config.cluster.v3.Cluster/"
>       "new_cluster_name";
>   const char* kNewTarget = "new_server.example.com";
> ```

I don't think we ne [...]

2022-01-04 06:09 UTC, donnadionne reviewed
fixed according to comments. PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-MsYh4mqEgQo1xyvLPnB:bfey499)* status: 6 of 10 files reviewed, 21 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/uri/uri_parser.h, line 59 at r2](https://reviewable.io/reviews/grpc/grpc/27938#-MoA9iXb-khJJVamrDs0:-MsXSyxk5ZFqOZ2aJx5M:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/12cb3dba187bc3a035cb61e02db6cd791f4bb135/src/core/lib/uri/uri_parser.h#L59)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Still need to add tests for this.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 565 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqyr5715be9orYyfOV-:-Mrrv1vvC8rghBkQ_Irj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L565)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This parameter should not have a default value.  There's no point in calling a setter method without specifying a value.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 571 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-MqyqT0z1HsJmJpFwxgp:-MrrvKlw4q2ijVUYgqaq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L571)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `AddCertificateProviderPlugin()`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 572 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-MqyqnKpCkU_mARIGAhe:-MsYfTXk9bR46OGlQxc7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L572)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's make this a little more general: Instead of assuming that the plugin config will have these three fields, let's just have the caller pass in the plugin config as a JSON string, so that they can format it however they want.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 814 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz4su15sV64I3Z2c-a:-MsXiO5EE4PnMaJSvxCf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L814)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `lb_expected_authority` as the format string instead of hard-coding the duplicate string.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 853 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz56XmDZIAZvfCAtKM:-MrruDkb7Abh-0jI-O0U:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L853)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs `override`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2328 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqysyci95BDrK3hZPkr:-MrrxuudEaMmPcik76lf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2328)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These parameters are the default values, so they don't need to be specified.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2542 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz4BLs4vsHPdpolDmP:-Mrrwd2-2_CKdIbV0_GR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2542)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These client-side tests look really good!

Please also add a server-side test where the bootstrap config sets `server_listener_resource_name_template` to a new-style name.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2543 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-MqytGQo8Oad0RLLeqz1:-Mrs0ZWa8syhxl0T_lp3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2543)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be `protected`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2563 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz-IzJ3NZu1LdplClM:-MsTdiBYEUP40nGGoSRx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2563)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's make this comment a little simpler:

"""
Channel is created with URI "xds:///server.example.com".
Bootstrap config default client listener template uses new-style name with authority "xds.example.com".
"""
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2606 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqyzegb87kj8VusK53K:-MsUOst-Dvh1Jow-xGUr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2606)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per my comment below, we should also run this test with RDS enabled, which means that we'll need a new-style name for the RDS resource as well.

Same for all of the federation tests.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2628 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz-m9q-JTM82mOGC3S:-MsLHtS23xZwYrUmoQ9-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2628)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's make this comment a little simpler:

"""
Channel is created with URI "xds://xds.example.com/server.example.com".
In bootstrap config, authority has no client listener template, so we use the default.
"""
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2645 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz1RSr8gnjW_m_3K2H:-MsLKa5b1rK6vUnw41Lo:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2645)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need this.  We can just use `kServerName` for both channels, because "xds:///server.example.com" and "xds://xds.example.com/server.example.com" are actually different names.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2677 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz2eSz2_GYtYcGljWy:-MsLN-90D-KybGT40DkG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L2677)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think `WaitForAllBackends()` does this for you, so you don't need to do it again here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2698 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz-xrN3sY56_8IOafo:-MsLLk [...]

2022-01-04 18:36 UTC, markdroth requested changes
This looks really good!  Just a few minor comments remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-MsaNF-c20URZEM8Gp9T:b-mb4u0z)* status: all files reviewed, 9 unresolved discussions (waiting on @donnadionne)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 814 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz4su15sV64I3Z2c-a:-MsaDJdv3H5apxN0Ws9g:b-tnwlk4) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L814)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I meant was:

```
if (lb_expected_authority == "localhost:%d") {
  lb_expected_authority = absl::StrFormat(lb_expected_authority, balancer_->port());
}
```
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 629 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaCwYe2IfMEA48BFWX:-MsaCwYe2IfMEA48BFWY:bvp45uw) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L629)):*
> ```cpp
> 
>    private:
>     struct PluginConfig {
> ```

This is no longer needed.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2553 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaI_y71tWJUK3cjFuD:-MsaI_y71tWJUK3cjFuE:b-mjmnho) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2553)):*
> ```cpp
> class XdsFederationTest : public XdsEnd2endTest {
>  protected:
>   XdsFederationTest() : XdsEnd2endTest(4, 100, 0, true) {
> ```

We probably need only 2 backend for these tests, not 4.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2605 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaFhDxC4D6ysfdudFj:-MsaFhDy3dFZZl90uQR5:b-hiuzp0) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2605)):*
> ```cpp
>   // Eds for 2 balancers are set up.
>   EdsResourceArgs args({{"locality0", CreateEndpointsForBackends(0, 1)}});
>   balancer_->ads_service()->SetEdsResource(BuildEdsResource(args));
> ```

I don't think the default balancer will be used at all in this test, so there's no need to populate this EDS resource.

Same thing for all of these tests.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2628 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaKsuX8qtk2xuuPFUz:-MsaKsuX8qtk2xuuPFV-:blmcu9t) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2628)):*
> ```cpp
>                                    new_route_config);
>   // RPCs sent using current stub (without
>   // authority) should go to backend 1 not backend 0; this is because we are
> ```

Since there should be only one EDS resource here, it can just go to all backends.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2843 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaHQ_S2Q207ytspTas:-MsaHQ_S2Q207ytspTat:b-ss9kyl) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2843)):*
> ```cpp
>                                    new_route_config);
>   // New Server Listeners
>   Listener server_listener = default_server_listener_;
> ```

This could be done as a loop for all backends:

```
for (int port : GetBackendPorts()) {
  Listener server_listener = default_server_listener_;
  server_listener.set_name(absl::StrCat(
      "xdstp://xds.example.com/envoy.config.listener.v3.Listener/server/",
      ipv6_only_ ? "[::1]:" : "127.0.0.1:", port, "?psm_project_id=1234"));
  server_listener.mutable_address()->mutable_socket_address()->set_port_value(
      port);
  authority_balancer_->ads_service()->SetLdsResource(server_listener);
}
```
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2876 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaLSbGEJuDeqRNd2pd:-MsaLSbGEJuDeqRNd2pe:blmcu9t) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2876)):*
> ```cpp
>   authority_balancer_->ads_service()->SetLdsResource(server_listener3);
>   // RPCs sent using current stub (without
>   // authority) should go to backend 1 not backend 0; this is because we are
> ```

Since there should be only one EDS resource here, it can just go to all backends.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7293 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaM9vP4ZYf0WwuLgRf:-MsaM9vP4ZYf0WwuLgRg:b8g1u2i) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L7293)):*
> ```cpp
>                                      kCaCertPath));
>     builder.AddCertificateProviderPlugin("file_plugin", "file_watcher",
>                                          absl::StrJoin(fields, "\n"));
> ```

Please make the second argument here `",\n"` (i.e., add a comma at the start of the string), so that you don't need commas in the individual field strings above.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 8440 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaMKNk8q6bIJkB_Tjt:-MsaMKNk8q6bIJkB_Tju:ba9ss1v) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L8440)):*
> ```cpp
>                                      kCaCertPath));
>     builder.AddCertificateProviderPlugin("file_plugin", "file_watcher",
>                                          absl::StrJoin(fields, "\n"));
> ```

Same here: please put the comma here instead of in the individual field strings above.


<!-- Sent from Reviewable.io -->

2022-01-04 20:48 UTC, donnadionne reviewed
Fixed! PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-MsaqNss049ZG0HF35PN:b-3d3ruk)* status: 9 of 10 files reviewed, 9 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 814 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz4su15sV64I3Z2c-a:-MsaPW2g3jbxGzkyQuhu:biqbo8n) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L814)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What I meant was:

```
if (lb_expected_authority == "localhost:%d") {
  lb_expected_authority = absl::StrFormat(lb_expected_authority, balancer_->port());
}
```
</blockquote></details>

i had a compile issue with this: 

test/cpp/end2end/xds/xds_end2end_test.cc:834:29: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char>') through variadic constructor; call will abort at runtime [-Wnon-pod-varargs]
            absl::StrFormat(lb_expected_authority, balancer_->port());
                            ^
test/cpp/end2end/xds/xds_end2end_test.cc:834:29: error: 'FormatSpecTemplate' is unavailable: Format string is not constexpr.
external/com_google_absl/absl/strings/internal/str_format/bind.h:96:3: note: 'FormatSpecTemplate' has been explicitly marked unavailable here
  FormatSpecTemplate(...)  // NOLINT
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 629 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaCwYe2IfMEA48BFWX:-MsaVt507KsnbYcaMBky:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L629)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is no longer needed.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2553 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaI_y71tWJUK3cjFuD:-MsaQEzsBUdnFIfL73z0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2553)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We probably need only 2 backend for these tests, not 4.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2605 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaFhDxC4D6ysfdudFj:-MsaojmdDQDdBHtKCuWK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2605)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think the default balancer will be used at all in this test, so there's no need to populate this EDS resource.

Same thing for all of these tests.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2628 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaKsuX8qtk2xuuPFUz:-MsaokJSDwcXMbjbPP6h:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2628)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since there should be only one EDS resource here, it can just go to all backends.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2843 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaHQ_S2Q207ytspTas:-MsaUhqL-ZSIylc7-HeR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2843)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This could be done as a loop for all backends:

```
for (int port : GetBackendPorts()) {
  Listener server_listener = default_server_listener_;
  server_listener.set_name(absl::StrCat(
      "xdstp://xds.example.com/envoy.config.listener.v3.Listener/server/",
      ipv6_only_ ? "[::1]:" : "127.0.0.1:", port, "?psm_project_id=1234"));
  server_listener.mutable_address()->mutable_socket_address()->set_port_value(
      port);
  authority_balancer_->ads_service()->SetLdsResource(server_listener);
}
```
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2876 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaLSbGEJuDeqRNd2pd:-MsaolRa6aM4WbjLMzuS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2876)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since there should be only one EDS resource here, it can just go to all backends.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7293 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaM9vP4ZYf0WwuLgRf:-MsaqMZ482VAt08WK1ve:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L7293)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please make the second argument here `",\n"` (i.e., add a comma at the start of the string), so that you don't need commas in the individual field strings above.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 8440 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaMKNk8q6bIJkB_Tjt:-MsaqMuo5vSIWe80abTD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L8440)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here: please put the comma here instead of in the individual field strings above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 21:33 UTC, markdroth requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938)* status: all files reviewed, 8 unresolved discussions (waiting on @donnadionne)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 814 at r13](https://reviewable.io/reviews/grpc/grpc/27938#-Mqz4su15sV64I3Z2c-a:-MsarYbZ2YW5MhmrTe_C:b-ofw3pq) ([raw file](https://github.com/grpc/grpc/blob/2fe3c53176e044badb15699692cfc6149c4f5134/test/cpp/end2end/xds/xds_end2end_test.cc#L814)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i had a compile issue with this: 

test/cpp/end2end/xds/xds_end2end_test.cc:834:29: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char>') through variadic constructor; call will abort at runtime [-Wnon-pod-varargs]
            absl::StrFormat(lb_expected_authority, balancer_->port());
                            ^
test/cpp/end2end/xds/xds_end2end_test.cc:834:29: error: 'FormatSpecTemplate' is unavailable: Format string is not constexpr.
external/com_google_absl/absl/strings/internal/str_format/bind.h:96:3: note: 'FormatSpecTemplate' has been explicitly marked unavailable here
  FormatSpecTemplate(...)  // NOLINT

</blockquote></details>

Ah, okay.  Then the way you have this is fine.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 629 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaCwYe2IfMEA48BFWX:-MsarUeK-mKZEZRbBnYr:bocb2l1) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L629)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2605 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaFhDxC4D6ysfdudFj:-Msb-HXs9TUDfr9hCeDe:by8fuso) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2605)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still need to fix this in the other tests.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2605 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-MsarreWCUMSqGNUr8qW:-MsarreWCUMSqGNUr8qX:b-6mrlkk) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2605)):*
> ```cpp
>   // Eds for the new authority balancer.
>   EdsResourceArgs args =
>       EdsResourceArgs({{"locality0", CreateEndpointsForBackends(0, 2)}});
> ```

No need to pass parameters to `CreateEndpointsForBackends()`.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2626 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-MsarnE45isJ8wphPQu3:-MsarnE45isJ8wphPQu4:by3a9uz) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2626)):*
> ```cpp
>   SetListenerAndRouteConfiguration(authority_balancer_.get(), listener,
>                                    new_route_config);
>   // RPCs sent using current stub (without authority) should be
> ```

This comment isn't very useful anymore.  I suggest just removing it.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2630 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-MsariUuALlZ-5bq95Nn:-MsariUuALlZ-5bq95No:b-pyhbyn) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2630)):*
> ```cpp
>   // authority and a xds server to use within that authority. Note we do not use
>   // the client_listener_resource_name_template field.
>   WaitForAllBackends(0, 2);
> ```

No need to specify the arguments here.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2815 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-MsarymsEqxZ2FOqhFOm:-MsarymsEqxZ2FOqhFOn:b-6mrlkk) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2815)):*
> ```cpp
>   // Eds for new authority balancer.
>   EdsResourceArgs args =
>       EdsResourceArgs({{"locality0", CreateEndpointsForBackends(0, 2)}});
> ```

No need to pass parameters to `CreateEndpointsForBackends()`.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2846 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-Msb-UYWDIOFgh9Q6fNh:-Msb-UYWDIOFgh9Q6fNi:b-w0htqp) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2846)):*
> ```cpp
>     authority_balancer_->ads_service()->SetLdsResource(server_listener);
>   }
>   // RPCs sent using current stub (without
> ```

This comment is no longer useful.  I think it can just be removed.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2854 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-Msb-T9322K_BBkM15pc:-Msb-T9322K_BBkM15pd:b-fp4676) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2854)):*
> ```cpp
>   // listener resources requested by the resources specified in
>   // server_listener_resource_name_template.
>   WaitForAllBackends(0, 2);
> ```

No need for the parameters here.


<!-- Sent from Reviewable.io -->

2022-01-05 04:23 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938)* status: all files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 629 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaCwYe2IfMEA48BFWX:-MscTMsyDBrGdLqrHM2A:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L629)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2605 at r14](https://reviewable.io/reviews/grpc/grpc/27938#-MsaFhDxC4D6ysfdudFj:-MscPU5m06uax74R4fdA:b-e6cifn) ([raw file](https://github.com/grpc/grpc/blob/5d0f6ad288d88a77d87f0d1062e3c59195f3be62/test/cpp/end2end/xds/xds_end2end_test.cc#L2605)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Still need to fix this in the other tests.
</blockquote></details>

These 2 tests FederationTargetAuthorityDefaultResourceTemplate and FederationTargetAuthorityWithResourceTemplate, I wanted to use 2 balancers: 1 for xds:server.example.com where there are no template to convert it to new-style; and another 1 for xds://xds.example.com/server.example.com

so i think i do need to populate both with EDS resources.

For these 2 tests, i created a second stub.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2605 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-MsarreWCUMSqGNUr8qW:-MscTJkR49KvCmAIMnGy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2605)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to pass parameters to `CreateEndpointsForBackends()`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2626 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-MsarnE45isJ8wphPQu3:-MscTKCLAie4iXLB9nNE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2626)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment isn't very useful anymore.  I suggest just removing it.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2630 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-MsariUuALlZ-5bq95Nn:-MscTKbu0Zu0JU5lbjgb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2630)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to specify the arguments here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2815 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-MsarymsEqxZ2FOqhFOm:-MscTL7T1T-o6SE1XHCV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2815)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to pass parameters to `CreateEndpointsForBackends()`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2846 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-Msb-UYWDIOFgh9Q6fNh:-MscTLa80qm7fRY0Oh8w:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2846)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment is no longer useful.  I think it can just be removed.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2854 at r15](https://reviewable.io/reviews/grpc/grpc/27938#-Msb-T9322K_BBkM15pc:-MscTM-h8D2eTpTFD3l0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/77d86254a881c71fc8fca32d7620b964a2b29a79/test/cpp/end2end/xds/xds_end2end_test.cc#L2854)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the parameters here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 16:55 UTC, markdroth approved these changes
Looks great!

> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27938#-:-Msf9hZgE4NtRTtgjovw:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donnadionne)



<!-- Sent from Reviewable.io -->

2022-01-05 19:13 UTC, merged