xDS: Add support for RBAC HTTP filter
grpc/grpc pull request #28309
Opened 2021-12-08 14:08 UTC by yashykt

2021-12-10 00:42 UTC, markdroth requested changes
The overall structure here looks excellent!

Please let me know if you have any questions.  Thanks!

> Reviewed 50 of 58 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309#-:-MqWmMpACO_5dELk4nIT:bezuv5m)* status: all files reviewed, 33 unresolved discussions (waiting on @ashithasantosh and @yashykt)

___
*[BUILD, line 449 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVkVqoBpR5pIs6ueVY:-MqVkVqp-4VrIbCpp10N:b-cju9fs) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/BUILD#L449)):*
> ```Starlark
>         "grpc_common",
>         "grpc_lb_policy_grpclb_secure",
>         "grpc_rbac_filter",
> ```

We don't want this dependency here, because it would pull in the RBAC code by default, which adds a dependency on the re2 library.  We don't want to pull in that dependency if we're building without xDS for code bloat reasons.

Since this dependency is already present on the `grpc_xds_client` target, I think it's fine to remove it here.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 45 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVpZnP4nvbM7u4CPwq:-MqVpZnP4nvbM7u4CPwr:b-s1bxgy) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L45)):*
> ```cpp
> 
>   // The index of this filter instance among instances of the same filter.
>   int index_;
> ```

This should probably be type `size_t`.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 50 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVpi6j-OKo8eIR_HD3:-MqVpi6j-OKo8eIR_HD4:b-t007bs) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L50)):*
> ```cpp
> };
> 
> class CallData {
> ```

Suggest nesting this inside of `ChannelData`, so that there's no need for public accessor methods on `ChannelData`.

Note that this will require moving the filter vtable to be a static data member of `ChannelData`, which will in turn require moving the class definition to the .h file.  You can look at the SDK authz filter as a good example of how to structure this.  (I'd like to use this structure for all new filters going forward... for as long as filters still exist. :) )
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 65 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVrwq-BRyMueOTP-ST:-MqVrwq-BRyMueOTP-SU:b-ytxm93) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L65)):*
> ```cpp
>   static void RecvInitialMetadataReady(void* user_data,
>                                        grpc_error_handle error);
>   static void RecvTrailingMetadataReady(void* user_data,
> ```

As we discussed, there's no need to intercept recv_trailing_metadata here.  On the server side, if we call `recv_initial_metadata_ready` with an error, the call will be failed with the status from that error.

I think this will both greatly simplify the logic and remove the need for a lot of the data members.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 106 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVqvAc9WcnoHYoyFKn:-MqVqvAc9WcnoHYoyFKo:bxk5gla) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L106)):*
> ```cpp
>           grpc_channel_stack_filter_instance_number(args->channel_stack, elem)),
>       per_channel_evaluate_args_(
>           grpc_find_auth_context_in_args(args->channel_args),
> ```

It would probably be a good idea to check that the auth context and the transport are both non-null.  If they are null, we should have `Init()` return an error instead of just crashing.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 167 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVstxd-aIJrITV6i7h:-MqVstxe89-0XPND8iiS:bjltqor) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L167)):*
> ```cpp
>   // The http-server filter removes the ':method' header from the metadata which
>   // we need to add back here.
>   grpc_metadata_batch_copy(&source, destination);
> ```

How expensive is this copy?  We're going to be doing this on every single call, so we should make sure it's cheap, or maybe consider alternatives.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 211 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVyDcu1eqsUHPh099Q:-MqVyDcu1eqsUHPh099R:b-jcbtxu) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L211)):*
> ```cpp
>       }
>     } else {
>       calld->error_ =
> ```

Please handle the error case next to the condition that triggers it.  In other words, instead of:

```
if (!error) {
  // ...long block to handle success...
} else {
  // ...handle error...
}
```

Please say:

```
if (error) {
  // ...handle error...
} else {
  // ...handle success...
}
```
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 211 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWV8zJ-ugcAHJJ8dwF:-MqWV8zJ-ugcAHJJ8dwG:b-lmapnb) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L211)):*
> ```cpp
>       }
>     } else {
>       calld->error_ =
> ```

It's not necessarily an error if the policy has no authorization engine.  The filter's override config might disable it, in which case the filter should be a no-op.

It would probably be a good idea to grab the method config in the ctor, so that if there is no policy to enforce, we don't need to intercept `recv_initial_metadata_ready` in the first place.
___
*[src/core/ext/filters/rbac/rbac_service_config_parser.h, line 45 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWDbGg30z1D4AHLOVM:-MqWDbGg30z1D4AHLOVN:b-c0w1we) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_service_config_parser.h#L45)):*
> ```objc
>   // active. The RBAC filter uses this method to get the RBAC policy configured
>   // for a instance at a particular instance. The implementation reverses the
>   // index since the ordering of HTTP filters is reverse on the server side. For
> ```

This same ordering property will apply to any HTTP filter on the server side.  Given that, it probably makes sense to have the xDS server config selector take care of this instead of doing it in the service config parser for each individual server-side filter.  This would be consistent with the fact that the xDS server config selector already handles reversing the order of the filters themselves; it should also do the same thing for the configs.

I think you could do this by simply reversing the order of the elements in the HTTP filter lists somewhere around here:

https://github.com/grpc/grpc/blob/e0c2bb063f931e59479fdc3b744f8768310b62b9/src/core/ext/xds/xds_server_config_fetcher.cc#L1062

Alternatively, maybe you could just reverse the order as soon as you get the LDS result back, so that you don't have to reverse the order separately for both creating the filter list and for generating the service config.
___
*[src/core/ext/filters/rbac/rbac_service_config_parser.cc, line 561 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWel2Z6pF7oozj42Pj:-MqWel2_EQ24tzjI2lXr:b-e82rcg) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_service_config_parser.cc#L561)):*
> ```cpp
> 
> std::unique_ptr<ServiceConfigParser::ParsedConfig>
> RbacServiceConfigParser::ParsePerMethodParams(const grpc_channel_args* args,
> ```

Please add some tests similar to those in https://github.com/grpc/grpc/blob/master/test/core/client_channel/service_config_test.cc for this parser, although you can put them in their own file.   [...]

2021-12-13 20:22 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309)* status: 44 of 62 files reviewed, 33 unresolved discussions (waiting on @ashithasantosh, @ctiller, @ejona86, @markdroth, and @yashykt)

___
*[BUILD, line 449 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVkVqoBpR5pIs6ueVY:-MqpS0eTEhcZOKMCLehK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/BUILD#L449)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We don't want this dependency here, because it would pull in the RBAC code by default, which adds a dependency on the re2 library.  We don't want to pull in that dependency if we're building without xDS for code bloat reasons.

Since this dependency is already present on the `grpc_xds_client` target, I think it's fine to remove it here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 45 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVpZnP4nvbM7u4CPwq:-MqpS6EG6JBUa65pYiYB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L45)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should probably be type `size_t`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 50 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVpi6j-OKo8eIR_HD3:-MqaD8GO7iOt_hv8V6IG:b2pv7qu) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest nesting this inside of `ChannelData`, so that there's no need for public accessor methods on `ChannelData`.

Note that this will require moving the filter vtable to be a static data member of `ChannelData`, which will in turn require moving the class definition to the .h file.  You can look at the SDK authz filter as a good example of how to structure this.  (I'd like to use this structure for all new filters going forward... for as long as filters still exist. :) )
</blockquote></details>

This is one case where I think nesting classes to avoid accessor methods makes things uglier since we have to move stuff to the header. Done anyway
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 65 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVrwq-BRyMueOTP-ST:-MqpS7mb4uf2XshdLkHY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As we discussed, there's no need to intercept recv_trailing_metadata here.  On the server side, if we call `recv_initial_metadata_ready` with an error, the call will be failed with the status from that error.

I think this will both greatly simplify the logic and remove the need for a lot of the data members.
</blockquote></details>

Done.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 106 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVqvAc9WcnoHYoyFKn:-MqaZ1ht0geyePR8sA9i:b-f4qs0h) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L106)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It would probably be a good idea to check that the auth context and the transport are both non-null.  If they are null, we should have `Init()` return an error instead of just crashing.
</blockquote></details>

Hmm after removing insecure builds we wouldn't have this issue, but I support the check irrespective
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 167 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVstxd-aIJrITV6i7h:-MqaA6pRCyJUnHsD-8C-:b-j9s6ui) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L167)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How expensive is this copy?  We're going to be doing this on every single call, so we should make sure it's cheap, or maybe consider alternatives.
</blockquote></details>

@ctiller 
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 211 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWV8zJ-ugcAHJJ8dwF:-MqaU6Fq7WVS-YWHbu6G:b-mpy83y) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L211)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not necessarily an error if the policy has no authorization engine.  The filter's override config might disable it, in which case the filter should be a no-op.

It would probably be a good idea to grab the method config in the ctor, so that if there is no policy to enforce, we don't need to intercept `recv_initial_metadata_ready` in the first place.
</blockquote></details>

The way the code is structured is that an empty RBAC policy is created even if there is no policy to enforce, so this error should not really happen, but i've still handled this case as a defensive mechanism.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 211 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVyDcu1eqsUHPh099Q:-MqpSAn--sCpQRvvZDKq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L211)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please handle the error case next to the condition that triggers it.  In other words, instead of:

```
if (!error) {
  // ...long block to handle success...
} else {
  // ...handle error...
}
```

Please say:

```
if (error) {
  // ...handle error...
} else {
  // ...handle success...
}
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/rbac/rbac_service_config_parser.h, line 45 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWDbGg30z1D4AHLOVM:-MqpIgsD-okAICxPahzN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_service_config_parser.h#L45)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This same ordering property will apply to any HTTP filter on the server side.  Given that, it probably makes sense to have the xDS server config selector take care of this instead of doing it in the service config parser for each individual server-side filter.  This would be consistent with the fact that the xDS server config selector already handles reversing the order of the filters themselves; it should also do the same thing for the configs.

I think you could do this by simply reversing the order of the elements in the HTTP filter lists somewhere around here:

https://github.com/grpc/grpc/blob/e0c2bb063f931e59479fdc3b744f8768310b62b9/src/core/ext/xds/xds_server_config_fetcher.cc#L1062

Alternatively, maybe you could just reverse the order as soon as you get the LDS result back, so that you don't have to reverse the order separately for both creating the filter list and for generating the service config.
</blockquote></details>

Done.
___
*[src/core/ext/filters/rbac/rbac_service_config_parser.cc, line 579 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWS5Zc9pETdM8PT8FZ:-MqpIjH4BEKelFXDUXoA:b-hfpv0l) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_service_config_parser.cc#L579)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume this was added for debugging. :)
</blockquote></details>

removed
___
*[src/core/ext/xds/xds_http_filters.cc [...]

2021-12-14 00:59 UTC, markdroth requested changes
I see that you're still making changes, but wanted to send you what I already reviewed.

Please let me know if you have any questions.  Thanks!

> Reviewed 18 of 18 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309#-:-MqqRoVK8rQ4hXujK-bE:bn6lfru)* status: 61 of 62 files reviewed, 14 unresolved discussions (waiting on @ashithasantosh, @ctiller, @ejona86, @markdroth, and @yashykt)

___
*[src/core/ext/filters/rbac/rbac_filter.h, line 70 at r3](https://reviewable.io/reviews/grpc/grpc/28309#-Mqpz0tJ76wAHYUhKoZM:-Mqpz0tK3Zy8Rr43XNFW:b-381bld) ([raw file](https://github.com/grpc/grpc/blob/4e94ab69c01c7d1041b7ff4680125a0c998e2187/src/core/ext/filters/rbac/rbac_filter.h#L70)):*
> ```objc
> 
>   // The index of this filter instance among instances of the same filter.
>   int index_;
> ```

`size_t`
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 50 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVpi6j-OKo8eIR_HD3:-MqpzAc6CKfgMGU7hE6R:bdesdy0) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L50)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

This is one case where I think nesting classes to avoid accessor methods makes things uglier since we have to move stuff to the header. Done anyway
</blockquote></details>

Thanks.  In the long run, I think we'll want to start writing unit tests for individual modules, in which case having the structure in the .h file will be a win anyway.
___
*[src/core/ext/xds/xds_http_rbac_filter.cc, line 484 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWN4q5-I8H8sTKtjJN:-MqqNH0qAfd98QxRT0F0:b-n1qn7k) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/xds/xds_http_rbac_filter.cc#L484)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Given that an absent RBAC policy is equivalent to a RBAC policy with empty `rules` https://github.com/envoyproxy/envoy/blob/30497202ccfed2a8a20a9da9028bd82e934b50a5/api/envoy/extensions/filters/http/rbac/v3/rbac.proto#L26, I think we can just use the same RBAC JSON object format for both the top-level policy and the override
</blockquote></details>

That comment says:

```
  // If absent, no enforcing RBAC policy will be applied.
  // If present and empty, DENY.
```

Doesn't that imply a different behavior for absent and present but empty?
___
*[src/core/ext/xds/xds_listener.cc, line 274 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWJ0nT7r-PpIbCSi1q:-MqqIBxoCFcs5DCEHVSB:b-vk7upr) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/xds/xds_listener.cc#L274)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Quoting https://github.com/grpc/proposal/blob/master/A41-xds-rbac.md ```
New validation should occur for HttpConnectionManager to allow equating RBAC's direct_remote_ip and remote_ip. If the RBAC implementation does not distinguish between these fields, then HttpConnectionManager.xff_num_trusted_hops must be unset or zero and HttpConnectionManager.original_ip_detection_extensions must be empty. If either field has an incorrect value, the Listener must be NACKed. For simplicity, this behavior applies independent of the Listener type (both client-side and server-side).```
</blockquote></details>

Okay.  In that case, please also add tests that we NACK these fields on the client test.
___
*[src/core/ext/xds/xds_listener.cc, line 308 at r3](https://reviewable.io/reviews/grpc/grpc/28309#-MqqLRCE3UmWG7ha7z43:-MqqLRCE3UmWG7ha7z44:b-xknqp1) ([raw file](https://github.com/grpc/grpc/blob/4e94ab69c01c7d1041b7ff4680125a0c998e2187/src/core/ext/xds/xds_listener.cc#L308)):*
> ```cpp
>             http_connection_manager_proto, &num_filters);
>     std::set<absl::string_view> names_seen;
>     // On the server side, iterate the filters in reverse order since received
> ```

I don't think this is the right place to do this.  The data returned by the XdsClient should have the entries in the same order as in the xDS proto.  I think we should do this reversing in the XdsServerConfigFetcher code, when we get the resource from the XdsClient.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9748 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWl68Q2HnzG1jZcktv:-MqqQMrK7wIWkEFnypxK:bwh05i1) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/test/cpp/end2end/xds/xds_end2end_test.cc#L9748)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I think the `AnyPermissionAnyPrincipal` serves that purpose
</blockquote></details>

Sorry, how does that test do that?  It looks to me like just like all of the other tests, it's still putting all of the rules into either the top-level policy or the override policy, depending on the value of `GetParam().filter_config_setup()`.  Am I missing something here?
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9749 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWlAlm8cO44gK9h9OW:-MqqQkXv98Qu43vaBY3Z:blxy51s) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/test/cpp/end2end/xds/xds_end2end_test.cc#L9749)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

This is not a test that needs to run once. It needs to run for atleast the configurations where - 1) rds is enabled/disabled 2) RouteConfiguration override is enabled/disabled
</blockquote></details>

My point is that it doesn't need to run for all the configurations that it's actually being run for.  If we move it to a different test suite, then we can run it only for the different values of the dimensions that we actually care about.

To say this another way, I think that `if (GetParam().something()) return;` in a test case is an anti-pattern.  Instead of making a test case that we don't care about be a no-op, it's generally better to avoid configuring that test case in the first place.


<!-- Sent from Reviewable.io -->

2021-12-14 01:52 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309)* status: 61 of 62 files reviewed, 14 unresolved discussions (waiting on @ashithasantosh, @ctiller, @ejona86, @markdroth, and @yashykt)

___
*[src/core/ext/xds/xds_http_rbac_filter.cc, line 484 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWN4q5-I8H8sTKtjJN:-MqqbbOF7wG8cvoMFBZQ:b-5g5rsg) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/xds/xds_http_rbac_filter.cc#L484)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That comment says:

```
  // If absent, no enforcing RBAC policy will be applied.
  // If present and empty, DENY.
```

Doesn't that imply a different behavior for absent and present but empty?
</blockquote></details>

Yes, that's correct. I should have said `absent` instead of `empty`. 

The `absent` part is enforced when `rules` field is not set. The `present and empty` part is enforced when the `rules` field is set but none of its fields are set. 

This absent part is exactly the part that I'm proposing we use to also implement a `RBACPerRoute` override with an absent `rbac` field.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9748 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWl68Q2HnzG1jZcktv:-Mqqb-fW2l3n0MpdH_ry:b1sd6yd) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/test/cpp/end2end/xds/xds_end2end_test.cc#L9748)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Sorry, how does that test do that?  It looks to me like just like all of the other tests, it's still putting all of the rules into either the top-level policy or the override policy, depending on the value of `GetParam().filter_config_setup()`.  Am I missing something here?
</blockquote></details>

Oh I misunderstood your comment, you meant a single test which has both the top-level and override policies as non-empty.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9772 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWhRVK7lV1ESDUZdkQ:-MqqbPO96bmjAg5ufIQT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/test/cpp/end2end/xds/xds_end2end_test.cc#L9772)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please have all of these tests check that the RPC fails with the right status code.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9869 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWlV1t1wbns8Ea5evN:-MqqbQlf288pj9YadC4T:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/test/cpp/end2end/xds/xds_end2end_test.cc#L9869)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

For most of these tests where the rules catch one particular attribute of the request, it would be good to also send a request that does *not* have the attribute and verify that it will not be caught by the rule.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 10015 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWjDnJ6ra6xH7A4vES:-Mqq3AJtE3RyvKyLnwWT:b-fiyilj) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/test/cpp/end2end/xds/xds_end2end_test.cc#L10015)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this matching against the authority set in the client request?  Where are we setting that in the test?

Note that there have been some changes related to this in the test framework recently, which is why I ask.  I'm not sure if you've merged master recently.
</blockquote></details>

`requested_server_name` is simply hard-coded to the empty string in gRPC  as per https://github.com/grpc/proposal/blob/master/A41-xds-rbac.md


<!-- Sent from Reviewable.io -->

2021-12-14 16:58 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309)* status: 58 of 63 files reviewed, 14 unresolved discussions (waiting on @ashithasantosh, @ctiller, @ejona86, @markdroth, and @yashykt)

___
*[src/core/ext/filters/rbac/rbac_filter.h, line 70 at r3](https://reviewable.io/reviews/grpc/grpc/28309#-Mqpz0tJ76wAHYUhKoZM:-Mqtrjk07_N-pTjte3kj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4e94ab69c01c7d1041b7ff4680125a0c998e2187/src/core/ext/filters/rbac/rbac_filter.h#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`size_t`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_listener.cc, line 274 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWJ0nT7r-PpIbCSi1q:-Mqtrm95BoDIAhYznpKA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/xds/xds_listener.cc#L274)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay.  In that case, please also add tests that we NACK these fields on the client test.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_listener.cc, line 308 at r3](https://reviewable.io/reviews/grpc/grpc/28309#-MqqLRCE3UmWG7ha7z43:-MqtroG_6KN3eD99f2Gr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/4e94ab69c01c7d1041b7ff4680125a0c998e2187/src/core/ext/xds/xds_listener.cc#L308)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is the right place to do this.  The data returned by the XdsClient should have the entries in the same order as in the xDS proto.  I think we should do this reversing in the XdsServerConfigFetcher code, when we get the resource from the XdsClient.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9716 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWlfHmC7sFzTYEXs5P:-Mqts8JB50o5mX4S_4fA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/test/cpp/end2end/xds/xds_end2end_test.cc#L9716)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should also have a way to test multiple instances of the RBAC filter, since we know we need to support such configs.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9730 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWga_I-E303wzJWFD_:-MqtsAwnDyjKAXdKHsz-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/test/cpp/end2end/xds/xds_end2end_test.cc#L9730)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's make sure to also test the case where the override config just removes the top-level policy.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9749 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWlAlm8cO44gK9h9OW:-MqtsJ9wDqWMZ55Uj1uY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/test/cpp/end2end/xds/xds_end2end_test.cc#L9749)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

My point is that it doesn't need to run for all the configurations that it's actually being run for.  If we move it to a different test suite, then we can run it only for the different values of the dimensions that we actually care about.

To say this another way, I think that `if (GetParam().something()) return;` in a test case is an anti-pattern.  Instead of making a test case that we don't care about be a no-op, it's generally better to avoid configuring that test case in the first place.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-15 03:24 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309)* status: 54 of 63 files reviewed, 14 unresolved discussions (waiting on @ashithasantosh, @ctiller, @ejona86, @markdroth, and @yashykt)

___
*[src/core/ext/filters/rbac/rbac_service_config_parser.cc, line 561 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWel2Z6pF7oozj42Pj:-Mqw6F0BBZDSiAY0cKfZ:brudp93) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_service_config_parser.cc#L561)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add some tests similar to those in https://github.com/grpc/grpc/blob/master/test/core/client_channel/service_config_test.cc for this parser, although you can put them in their own file.  (At some point, we should split up that particular file so that the parsing for each filter or LB policy or whatever is in its own file.)
</blockquote></details>

Added some tests here for the parsing functionality. Still depending on the xds_end2end_test though for testing whether the RBAC policies do what they are supposed to.


<!-- Sent from Reviewable.io -->

2021-12-15 04:43 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309)* status: 54 of 63 files reviewed, 14 unresolved discussions (waiting on @ashithasantosh, @ctiller, @ejona86, @markdroth, and @veblush)

___
*[src/proto/grpc/testing/xds/v3/expr.proto, line 15 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVmDxo7gO8FbOk6UN1:-MqwL8ty44xWEUsdX1d3:b1tf3h) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/proto/grpc/testing/xds/v3/expr.proto#L15)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

@veblush may have some ideas on this.

The CEL protos don't define an RPC service, so their build rules shouldn't depend on gRPC.  So this may just involve taking the external dependency on CEL.
</blockquote></details>

I've tried a few things here, but our `grpc_proto_library` does not play nice with others. There are more things I want to try here but I would prefer not to block this.


<!-- Sent from Reviewable.io -->

2021-12-15 05:09 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309)* status: 54 of 63 files reviewed, 14 unresolved discussions (waiting on @ashithasantosh, @ctiller, @ejona86, @markdroth, and @veblush)

___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 167 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVstxd-aIJrITV6i7h:-MqwP-p07P_WEZRDEn8d:b-9qsvrk) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L167)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

@ctiller 
</blockquote></details>

I guess I could just add the header and later remove it. 


<!-- Sent from Reviewable.io -->

2021-12-15 18:46 UTC, markdroth requested changes
This looks really good!  All remaining comments are minor, except for resolving the handling of the `:method` header, which should be easy to fix now.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 5 files at r5, 1 of 5 files at r6, 23 of 23 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309#-:-MqzPa6y8oJ4XalxtMf0:b43688f)* status: all files reviewed, 9 unresolved discussions (waiting on @ashithasantosh, @ctiller, and @yashykt)

___
*[log, line 1 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-Mqz8_Gp3JpOJa6ocE8K:-Mqz8_Gq2hrfP_dxiPDX:bbuh1mv) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/log#L1)):*
> ```
> Note: Google Test filter = *AnyPermissionOrIdPrincipal*
> ```

I assume this file was added by accident.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 167 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVstxd-aIJrITV6i7h:-Mqz9Dky3XCTU0QmDXi9:b-uima7t) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L167)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I guess I could just add the header and later remove it. 
</blockquote></details>

Now that #28204 has landed, I think the `:method` header will actually already be present in the batch, so we shouldn't need to do anything special for it here at all.
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 57 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzBTNS0RukH83DXVox:-MqzBTNS0RukH83DXVoy:b-kr36dy) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/src/core/ext/filters/rbac/rbac_filter.cc#L57)):*
> ```cpp
>     op->payload->recv_initial_metadata.recv_initial_metadata_ready =
>         &calld->recv_initial_metadata_ready_;
>     calld->payload_ = op->payload;
> ```

We should probably stash just the value of `op->payload->recv_initial_metadata.recv_initial_metadata`, not the whole payload, since a filter further down the stack could change the values in the payload struct between here and where we use it.
___
*[src/core/ext/xds/xds_http_rbac_filter.cc, line 484 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqWN4q5-I8H8sTKtjJN:-MqzJQp837azNUPfuvtV:b-gmful1) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/xds/xds_http_rbac_filter.cc#L484)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Yes, that's correct. I should have said `absent` instead of `empty`. 

The `absent` part is enforced when `rules` field is not set. The `present and empty` part is enforced when the `rules` field is set but none of its fields are set. 

This absent part is exactly the part that I'm proposing we use to also implement a `RBACPerRoute` override with an absent `rbac` field.

</blockquote></details>

Ah, okay, got it.  Thanks for the explanation.
___
*[src/proto/grpc/testing/xds/v3/expr.proto, line 15 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVmDxo7gO8FbOk6UN1:-MqzHQ9x-Y4sFUJyXzfN:b-s9a6ir) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/proto/grpc/testing/xds/v3/expr.proto#L15)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I've tried a few things here, but our `grpc_proto_library` does not play nice with others. There are more things I want to try here but I would prefer not to block this.
</blockquote></details>

That's fine with me if it's okay with @veblush.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 8318 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzKpuvCEAsqt36DGq2:-MqzKpuvCEAsqt36DGq3:b88da7y) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L8318)):*
> ```cpp
>         }
>         if (expected_status.has_value() &&
>             *expected_status != status.error_code()) {
> ```

How about just doing:

```
EXPECT_EQ(*expected_status, status.error_code());
```

That way, the log happens automatically, and the test will fail if the expectation is violated.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9847 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzNhpW42zPtu4FWASO:-MqzNhpW42zPtu4FWASP:b-s3963x) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9847)):*
> ```cpp
>       GetParam().filter_config_setup() ==
>           TestType::FilterConfigSetup::kRouteOverride) {
>     ASSERT_TRUE(WaitForRdsNack(StatusCode::DEADLINE_EXCEEDED))
> ```

As per Donna's discovery in #27938, please run these tests with `TestType::bootstrap_source_` set to `kBootstrapFromEnvVar`, so that the NACKs can expect UNAVAILABLE instead of DEADLINE_EXCEEDED.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9945 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzOeep1rJqyrXHGlHx:-MqzOeep1rJqyrXHGlHy:b-emp4wf) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9945)):*
> ```cpp
> 
> TEST_P(XdsRbacTestWithRouteOverrideAlwaysPresent, EmptyRBACPerRouteOverride) {
>   if (GetParam().filter_config_setup() ==
> ```

Doesn't look like this check is needed anymore.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9954 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzOrpHE4juITBK5YN-:-MqzOrpHE4juITBK5YN0:bzsw01) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9954)):*
> ```cpp
>   auto* filter = http_connection_manager.add_http_filters();
>   filter->set_name("rbac");
>   // Create a top-level RBAC policy with an Allow action but empty matching
> ```

Wouldn't it be more straightforward to just use a deny rule with an any match?
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9984 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzOhub5q3lHOnBOZgz:-MqzOhub5q3lHOnBOZh-:b-emp4wf) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9984)):*
> ```cpp
> TEST_P(XdsRbacTestWithRouteOverrideAlwaysPresent,
>        NonEmptyTopLevelRBACNonEmptyPerRouteOverride) {
>   if (GetParam().filter_config_setup() ==
> ```

Doesn't look like this check is needed anymore.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9993 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzP4Sw9tVArUTaD0d8:-MqzP4Sw9tVArUTaD0d9:bzsw01) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9993)):*
> ```cpp
>   auto* filter = http_connection_manager.add_http_filters();
>   filter->set_name("rbac");
>   // Create a top-level RBAC policy with an Allow action but empty matching
> ```

Wouldn't it be more straightforward to just use a deny rule with an any match?


<!-- Sent from Reviewable.io -->

2021-12-15 20:43 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309)* status: 62 of 66 files reviewed, 9 unresolved discussions (waiting on @ashithasantosh, @ctiller, and @markdroth)

___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 167 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVstxd-aIJrITV6i7h:-MqzovvuCLmOfP08tRZw:b-juldgj) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L167)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Now that #28204 has landed, I think the `:method` header will actually already be present in the batch, so we shouldn't need to do anything special for it here at all.
</blockquote></details>

I'm not sure I understand how that PR #28204 changes things
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 57 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzBTNS0RukH83DXVox:-MqzmKhu-vnsnLbLptiG:b-x80twc) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/src/core/ext/filters/rbac/rbac_filter.cc#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should probably stash just the value of `op->payload->recv_initial_metadata.recv_initial_metadata`, not the whole payload, since a filter further down the stack could change the values in the payload struct between here and where we use it.
</blockquote></details>

Hmm I guess that's legal. Done!
___
*[src/proto/grpc/testing/xds/v3/expr.proto, line 15 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVmDxo7gO8FbOk6UN1:-Mqzhz0Z-EafL_5EAAnh:b-2rizu1) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/proto/grpc/testing/xds/v3/expr.proto#L15)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

That's fine with me if it's okay with @veblush.
</blockquote></details>

Yeah I'm syncing with him on what we want to do over here.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 8318 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzKpuvCEAsqt36DGq2:-Mqzi8oL8EK5pLAjF8u8:b-21whzz) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L8318)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about just doing:

```
EXPECT_EQ(*expected_status, status.error_code());
```

That way, the log happens automatically, and the test will fail if the expectation is violated.
</blockquote></details>

I'm also using the retry loop here to wait for updates to be applied. 
Some tests are of the form -
```
Apply first update;
Test update;
Apply second update;
Test second update
```

When testing the second update, the retry loop gives some time for the new update to be actually applied, and in the meantime we do not want to fail the test.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9847 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzNhpW42zPtu4FWASO:-Mqzp8phA8HKay69FrPo:b-kt0lo5) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9847)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per Donna's discovery in #27938, please run these tests with `TestType::bootstrap_source_` set to `kBootstrapFromEnvVar`, so that the NACKs can expect UNAVAILABLE instead of DEADLINE_EXCEEDED.
</blockquote></details>

Ah you are right. Thanks!
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9945 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzOeep1rJqyrXHGlHx:-MqzpD4D8SbKT6nl0rko:ba3dfob) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9945)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this check is needed anymore.
</blockquote></details>

Removed
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9954 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzOrpHE4juITBK5YN-:-MqzpEFR2EisyLEGHOvK:b-oh7u55) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9954)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Wouldn't it be more straightforward to just use a deny rule with an any match?
</blockquote></details>

Either way works. Changed.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9984 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzOhub5q3lHOnBOZgz:-MqzpIEv2WFDJitXp8kv:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9984)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this check is needed anymore.
</blockquote></details>

Removed.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9993 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzP4Sw9tVArUTaD0d8:-MqzpJom7j1e-KSE7dfS:b-oh7u55) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9993)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Wouldn't it be more straightforward to just use a deny rule with an any match?
</blockquote></details>

Either way works. Changed.
___
*[log, line 1 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-Mqz8_Gp3JpOJa6ocE8K:-MqzpL7H06rA-ZzI6HdZ:b3itlx7) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/log#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume this file was added by accident.
</blockquote></details>

Yeah, removed :)


<!-- Sent from Reviewable.io -->

2021-12-15 21:14 UTC, markdroth requested changes
Just a few minor nits remaining!

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309#-:-MqzwWEqB_GV7mgcJcaA:b-pjksjt)* status: all files reviewed, 4 unresolved discussions (waiting on @ashithasantosh, @ctiller, and @yashykt)

___
*[src/core/ext/filters/rbac/rbac_filter.h, line 56 at r8](https://reviewable.io/reviews/grpc/grpc/28309#-MqztsJuBNgeMIPSEWJI:-MqztsJuBNgeMIPSEWJJ:b2ogvec) ([raw file](https://github.com/grpc/grpc/blob/e4e82193490c895c9f461fcd2eb9f1beeba74b78/src/core/ext/filters/rbac/rbac_filter.h#L56)):*
> ```objc
>     // State for keeping track of recv_initial_metadata
>     grpc_metadata_batch* recv_initial_metadata_ = nullptr;
>     uint32_t* recv_flags_ = nullptr;
> ```

I think this won't be necessary once you make the changes we discussed relative to #28204.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 8318 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzKpuvCEAsqt36DGq2:-MqzuM2A9Wt0OWUg09YN:bnkk06z) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L8318)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I'm also using the retry loop here to wait for updates to be applied. 
Some tests are of the form -
```
Apply first update;
Test update;
Apply second update;
Test second update
```

When testing the second update, the retry loop gives some time for the new update to be actually applied, and in the meantime we do not want to fail the test.
</blockquote></details>

Are there cases where the RPC will fail with the wrong error before the second update?  If not, then this won't hurt anything.

But I guess if the code is wrong, we won't exit the loop, so the test still verifies the right thing.  I'll leave it up to you.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9847 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzNhpW42zPtu4FWASO:-MqzvtMl8Jox7rX6wYjh:b-se30wt) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9847)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Ah you are right. Thanks!
</blockquote></details>

I think we no longer need any parameter to the `WaitFor.*Nack()` methods, since all callers now expect `UNAVAILABLE`.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 13219 at r8](https://reviewable.io/reviews/grpc/grpc/28309#-MqzwJ324Xwb289y32ac:-MqzwJ324Xwb289y32ad:b-qg1xhx) ([raw file](https://github.com/grpc/grpc/blob/e4e82193490c895c9f461fcd2eb9f1beeba74b78/test/cpp/end2end/xds/xds_end2end_test.cc#L13219)):*
> ```cpp
> 
> // We are only testing the server here.
> INSTANTIATE_TEST_SUITE_P(
> ```

Please add a short comment for all of these tests explaining why we need `kBootstrapFromEnvVar`.


<!-- Sent from Reviewable.io -->

2021-12-15 22:45 UTC, yashykt reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309)* status: 63 of 66 files reviewed, 4 unresolved discussions (waiting on @ashithasantosh, @ctiller, and @markdroth)

___
*[src/core/ext/filters/rbac/rbac_filter.h, line 56 at r8](https://reviewable.io/reviews/grpc/grpc/28309#-MqztsJuBNgeMIPSEWJI:-Mr-GAFh1QILViAWP9Xa:b-2iypl4) ([raw file](https://github.com/grpc/grpc/blob/e4e82193490c895c9f461fcd2eb9f1beeba74b78/src/core/ext/filters/rbac/rbac_filter.h#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this won't be necessary once you make the changes we discussed relative to #28204.
</blockquote></details>

Adding a TODO in case https://github.com/grpc/grpc/pull/28369/files takes longer to merge
___
*[src/core/ext/filters/rbac/rbac_filter.cc, line 167 at r2](https://reviewable.io/reviews/grpc/grpc/28309#-MqVstxd-aIJrITV6i7h:-Mr-GMPj-eCC7YZD68B_:b-2iypl4) ([raw file](https://github.com/grpc/grpc/blob/a18c2bbfa2441114be9eb2a45b9609ec7774c2cf/src/core/ext/filters/rbac/rbac_filter.cc#L167)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I'm not sure I understand how that PR #28204 changes things
</blockquote></details>

Adding a TODO in case https://github.com/grpc/grpc/pull/28369/files takes longer to merge
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 8318 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzKpuvCEAsqt36DGq2:-Mr-A6fi2zmeBxYSS5wF:b-i7bd2) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L8318)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Are there cases where the RPC will fail with the wrong error before the second update?  If not, then this won't hurt anything.

But I guess if the code is wrong, we won't exit the loop, so the test still verifies the right thing.  I'll leave it up to you.
</blockquote></details>

If there were a better way to make sure that the update has been applied I would prefer that.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9847 at r7](https://reviewable.io/reviews/grpc/grpc/28309#-MqzNhpW42zPtu4FWASO:-Mr-GNdg1VD1lfoUeq18:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0f8b0a6e04109b431b6606582224cdfe83129dc0/test/cpp/end2end/xds/xds_end2end_test.cc#L9847)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we no longer need any parameter to the `WaitFor.*Nack()` methods, since all callers now expect `UNAVAILABLE`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 13219 at r8](https://reviewable.io/reviews/grpc/grpc/28309#-MqzwJ324Xwb289y32ac:-Mr-GPfvBgXOd6t3rVpn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e4e82193490c895c9f461fcd2eb9f1beeba74b78/test/cpp/end2end/xds/xds_end2end_test.cc#L13219)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a short comment for all of these tests explaining why we need `kBootstrapFromEnvVar`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-16 14:27 UTC, markdroth approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28309)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ashithasantosh)



<!-- Sent from Reviewable.io -->

2021-12-24 04:46 UTC, merged