Add http cancel api
grpc/grpc pull request #28354
Opened 2021-12-14 20:29 UTC by apolcyn

@veblush

2022-01-08 10:23 UTC, apolcyn commented
FTR, added execctx to C++ creds dtors because w/out we have:

```
$ ./interop_client --server_host=grpc-test4.sandbox.googleapis.com --server_port=443 --test_case=oauth2_auth_token --use_tls=true --default_service_account=389806271065-compute@developer.gserviceaccount.com --oauth_scope=https://www.googleapis.com/auth/xapi.zoo
*** SIGSEGV received at time=1641636315 on cpu 3 ***
PC: @     0x55d6a287c610  (unknown)  grpc_closure_list_append()
    @     0x55d6a2de4e92         64  absl::lts_20211102::WriteFailureInfo()
    @     0x55d6a2de5043         96  absl::lts_20211102::AbslFailureSignalHandler()
    @     0x7fc9da1240e0  (unknown)  (unknown)
    @     0x55d6a287bd3d         32  exec_ctx_sched()
    @     0x55d6a287c40f         64  grpc_core::ExecCtx::Run()
    @     0x55d6a2b6f493        144  grpc_core::LockfreeEvent::SetShutdown()
    @     0x55d6a2b66064         48  fd_shutdown()
    @     0x55d6a2b01102         32  grpc_fd_shutdown()
    @     0x55d6a288488a         48  tcp_shutdown()
    @     0x55d6a2b005da         32  grpc_endpoint_shutdown()
    @     0x55d6a2af811b        128  grpc_core::HttpCli::Orphan()
    @     0x55d6a28bcda5         32  grpc_core::OrphanableDelete::operator()<>()
    @     0x55d6a28bbe6b         64  std::unique_ptr<>::~unique_ptr()
    @     0x55d6a28cb842         32  (anonymous namespace)::grpc_compute_engine_token_fetcher_credentials::~grpc_compute_engine_token_fetcher_credentials()
    @     0x55d6a28cb86a         32  (anonymous namespace)::grpc_compute_engine_token_fetcher_credentials::~grpc_compute_engine_token_fetcher_credentials()
    @     0x55d6a27c9310         32  grpc_core::internal::Delete<>::Delete()
    @     0x55d6a27c89b2         48  grpc_core::RefCounted<>::Unref()
    @     0x55d6a27c8583         32  grpc::SecureCallCredentials::~SecureCallCredentials()
    @     0x55d6a27c85aa         32  grpc::SecureCallCredentials::~SecureCallCredentials()
    @     0x55d6a27caa03         32  std::_Sp_counted_ptr<>::_M_dispose()
    @     0x55d6a258d9a2         32  std::_Sp_counted_base<>::_M_release()
    @     0x55d6a25899b5         32  std::__shared_count<>::~__shared_count()
    @     0x55d6a25c1a70         32  std::__shared_ptr<>::~__shared_ptr()
    @     0x55d6a25c1a8c         32  std::shared_ptr<>::~shared_ptr()
    @     0x55d6a25c0983         96  _ZN4grpc7testing20GetOauth2AccessTokenB5cxx11Ev
    @     0x55d6a25c0cf9        816  grpc::testing::CreateChannelForTestCase()
    @     0x55d6a25b234c        112  main::{lambda()#1}::operator()()
    @     0x55d6a25b5017         32  std::_Function_handler<>::_M_invoke()
    @     0x55d6a25cd897         32  std::function<>::operator()()
    @     0x55d6a25c29b9         96  grpc::testing::InteropClient::ServiceStub::ServiceStub()
    @     0x55d6a25c2d6e         96  grpc::testing::InteropClient::InteropClient()
    @     0x55d6a25b27dd       4320  main
    @ ... and at least 2 more frames
Segmentation fault
```

2022-01-11 19:17 UTC, markdroth requested changes
This looks like a great start!  I have a number of comments about the API design, but the overall structure looks very good.

Please let me know if you have any questions.  Thanks!

> Reviewed 23 of 28 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-Mt9ZbAe0zS9Nsn0uH9n:bhoxtbh)* status: all files reviewed, 17 unresolved discussions (waiting on @apolcyn)

___
*[src/core/lib/http/httpcli.h, line 42 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9LPot2vvDVDUYY4OJ:-Mt9LPot2vvDVDUYY4OK:bd3crxk) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L42)):*
> ```objc
> 
> /* A request */
> typedef struct grpc_httpcli_request {
> ```

We can probably just eliminate this struct now.  I suggest passing in channel args when creating the HTTP request, since we already have existing args for `host` (`GRPC_ARG_DEFAULT_AUTHORITY`) and `ssl_host_override` (`GRPC_SSL_TARGET_NAME_OVERRIDE_ARG`).  Then we can just pass in the `grpc_http_request` struct directly.

Note that passing in channel args will also allow us to eliminate the `resource_quota` argument, since the resource quota is already encoded in channel args.
___
*[src/core/lib/http/httpcli.h, line 50 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9RaLaCUk5_2yegvpK:-Mt9RaLaCUk5_2yegvpL:bbc1pxn) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L50)):*
> ```objc
>      The following headers are supplied automatically and MUST NOT be set here:
>      Host, Connection, User-Agent */
>   grpc_http_request http;
> ```

It would be nice to also convert `grpc_http_request` and `grpc_http_response` to idiomatic C++.

As an alternative for `grpc_http_request`, maybe we should just take a `URI` object as input instead?
___
*[src/core/lib/http/httpcli.h, line 76 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt5BzG96kahB7ArJpUp:-Mt5BzGA8dO0o_YBD1f1:b-z46bbu) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L76)):*
> ```objc
> // TODO(ctiller): allow caching and capturing multiple requests for the
> //                same content and combining them
> class HttpCli : public InternallyRefCounted<HttpCli> {
> ```

Please call this `HttpRequest`.
___
*[src/core/lib/http/httpcli.h, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt5CIHJBnGd-S8GtK2_:-Mt5CIHJBnGd-S8GtK2a:bsd91d8) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L86)):*
> ```objc
>   // method. Related: callers must typically synchronize on_done callbacks with
>   // their factory method invocations to ensure refs aren't dropped early.
>   class HttpCliHandshaker : public InternallyRefCounted<HttpCliHandshaker> {};
> ```

Suggest removing `HttpCli` prefix from these nested classes; the prefix isn't really needed, since the nesting provides the necessary namespacing.
___
*[src/core/lib/http/httpcli.h, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9ITxS9dNfsifytxN3:-Mt9ITxS9dNfsifytxN4:b9hmvo7) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L86)):*
> ```objc
>   // method. Related: callers must typically synchronize on_done callbacks with
>   // their factory method invocations to ensure refs aren't dropped early.
>   class HttpCliHandshaker : public InternallyRefCounted<HttpCliHandshaker> {};
> ```

Since we're changing this anyway, how hard would it be to just eliminate the HTTP-specific handshaker API here and just use the normal handshaker code that we use in the channel?  In principle, there's no reason we need a separate API here, and I think this API is a strict subset of the functionality provided by the normal handshaker API.  And using the same handshaker API here that we do in the channel might make it easier to support things like S2A in the future, as per previous discussion with @matthewstevenson88.

I'm thinking that we can probably just use a channel creds object to select SSL or insecure creds and then use the normal security handshaker infrastructure to do this.

If this totally blows up the scope of this PR, then it's fine to defer this until later.  But if it turns out to not be that hard, then it seems better not to introduce these new types that we'll just wind up wanting to eliminate later.
___
*[src/core/lib/http/httpcli.h, line 180 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9RwYc4h2aTFDCRyah:-Mt9RwYc4h2aTFDCRyai:b-69x6s3) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L180)):*
> ```objc
>   // 'resource_quota' allows the caller to specify the quota against which to
>   // allocate
>   // 'request' contains request parameters - these are caller owned and
> ```

Any reason not to have the HTTP request take ownership of this request struct?
___
*[src/core/lib/http/httpcli.h, line 181 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9OHi49uhpFCiG2lMC:-Mt9OHi49uhpFCiG2lMD:b479sst) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L181)):*
> ```objc
>   // allocate
>   // 'request' contains request parameters - these are caller owned and
>   // can be destroyed once the call returns 'deadline' contains a deadline for
> ```

Please fix formatting.
___
*[src/core/lib/http/httpcli.h, line 182 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9OJAG9A_ZPgSG2MDE:-Mt9OJAG9A_ZPgSG2MDF:b-i37iw4) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L182)):*
> ```objc
>   // 'request' contains request parameters - these are caller owned and
>   // can be destroyed once the call returns 'deadline' contains a deadline for
>   // the request (or gpr_inf_future) 'on_response' is a callback to report
> ```

s/on_response/on_done/
___
*[src/core/lib/http/httpcli.h, line 188 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9NgCa2w-O0j75FF8M:-Mt9NgCa2w-O0j75FF8N:b-jpk3i6) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L188)):*
> ```objc
>       const grpc_httpcli_request* request,
>       std::unique_ptr<HttpCliHandshakerFactory> handshaker_factory,
>       grpc_millis deadline, grpc_closure* on_done,
> ```

I suggest changing this to use `std::function<>`, as long as we're at it.
___
*[src/core/lib/http/httpcli.h, line 202 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9O57I6av-9dqgKRWO:-Mt9O57I6av-9dqgKRWP:b7ntmk4) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L202)):*
> ```objc
>   //   When there is no body, pass in NULL as body_bytes.
>   // 'deadline' contains a deadline for the request (or gpr_inf_future)
>   // 'em' points to a caller owned event manager that must be alive for the
> ```

There is no such parameter.
___
*[src/core/lib/http/httpcli.h, line 204 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9ORo80MRqvJg9ZJzQ:-Mt9ORo80MRqvJg9ZJzR:b-i37iw4) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L204)):*
> ```objc
>   // 'em' points to a caller owned event manager that must be alive for the
>   //   lifetime of the request
>   // 'on_response' is a callback to report results to
> ```

s/on_response/on_done/
___
*[src/core/lib/http/httpcli.h, line 231 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9Ov2FEHXKcufETC1R:-Mt9Ov2FEHXKcufETC1S:b-92ut1x) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L231)):*
> ```objc
> 
>   static std::unique_ptr<HttpCli::HttpCliHandshakerFactory>
>   HttpCliHands [...]

2022-01-14 19:37 UTC, apolcyn reviewed
Thanks for the comments! I believe I've addressed them. PTAL

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-MtP4xjFEGQhGkp6I9fi:bc2xwbz)* status: 2 of 46 files reviewed, 17 unresolved discussions (waiting on @markdroth and @matthewstevenson88)

___
*[src/core/lib/http/httpcli.h, line 42 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9LPot2vvDVDUYY4OJ:-MtP0Sxh42u-sZKTLpn3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L42)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We can probably just eliminate this struct now.  I suggest passing in channel args when creating the HTTP request, since we already have existing args for `host` (`GRPC_ARG_DEFAULT_AUTHORITY`) and `ssl_host_override` (`GRPC_SSL_TARGET_NAME_OVERRIDE_ARG`).  Then we can just pass in the `grpc_http_request` struct directly.

Note that passing in channel args will also allow us to eliminate the `resource_quota` argument, since the resource quota is already encoded in channel args.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 50 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9RaLaCUk5_2yegvpK:-MtP0TzT0Slfl0_VZBQJ:b-79bwyy) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L50)):*
> It would be nice to also convert grpc_http_request and grpc_http_response to idiomatic C++.

I agree it would be nice to clean these up.

I propose to separate changes to those structs from this PR, though. Updating those structs would entail a lot of changes to `src/core/lib/http/parser.cc`, `jwt_verifier.cc` and several other places, which could make this PR even larger.

> As an alternative for grpc_http_request, maybe we should just take a URI object as input instead?

I'm not sure if this would make sense because `URI` has no concept of HTTP headers, which `grpc_http_request` does. Likewise, `grpc_http_request` has no concept of query parameters, which `URI` does.
___
*[src/core/lib/http/httpcli.h, line 76 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt5BzG96kahB7ArJpUp:-MtP1ttU3163wYOU6Y8x:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L76)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `HttpRequest`.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt5CIHJBnGd-S8GtK2_:-MtP1ufE5BqgXJl4C0Lq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest removing `HttpCli` prefix from these nested classes; the prefix isn't really needed, since the nesting provides the necessary namespacing.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9ITxS9dNfsifytxN3:-MtP1vUqDm5ggkWuaLmJ:b14equ1) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since we're changing this anyway, how hard would it be to just eliminate the HTTP-specific handshaker API here and just use the normal handshaker code that we use in the channel?  In principle, there's no reason we need a separate API here, and I think this API is a strict subset of the functionality provided by the normal handshaker API.  And using the same handshaker API here that we do in the channel might make it easier to support things like S2A in the future, as per previous discussion with @matthewstevenson88.

I'm thinking that we can probably just use a channel creds object to select SSL or insecure creds and then use the normal security handshaker infrastructure to do this.

If this totally blows up the scope of this PR, then it's fine to defer this until later.  But if it turns out to not be that hard, then it seems better not to introduce these new types that we'll just wind up wanting to eliminate later.
</blockquote></details>

Great idea! This seemed to be a net cleanup.

I did need to separate out `httpcli.cc` etc. from the "grpc_base" library in order to do this, though. The reason is that in order to use the `grpc_channel_credentials` type, we need to depend on "grpc_security_base". But grpc_security_base" already depends on "grpc_base", so we'd have a circular dependency if we left it in there.
___
*[src/core/lib/http/httpcli.h, line 180 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9RwYc4h2aTFDCRyah:-MtP2TAT1KzikHUIK-PQ:bmyfa8t) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L180)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Any reason not to have the HTTP request take ownership of this request struct?
</blockquote></details>

The `grpc_http_request` may or may not be heap allocated, so I think just for that reason it makes sense for the caller to own it.
___
*[src/core/lib/http/httpcli.h, line 181 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9OHi49uhpFCiG2lMC:-MtP2bao6nLa3g_HykNE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L181)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please fix formatting.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 182 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9OJAG9A_ZPgSG2MDE:-MtP2bxt4x0fi7edTFOs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L182)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/on_response/on_done/
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 188 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9NgCa2w-O0j75FF8M:-MtP2fKC7HIPBCdIBWTA:bzgj3gm) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L188)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest changing this to use `std::function<>`, as long as we're at it.
</blockquote></details>

I'm hesitant to make this change because it would increase the size of this PR and I believe only bring us to a temporary stage.

What I think would be best is to change `on_done` to something like `std::function<absl::StatusOr<HttpRequest::Response>>`

But to get to that point, we'd need to first convert `grpc_http_request` and `grpc_http_response` to idiomatic C++ objects.

I.e., I propose leaving this change for when we update the request/response objects. What do you think?
___
*[src/core/lib/http/httpcli.h, line 202 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9O57I6av-9dqgKRWO:-MtP3aU11c_gHf1kZMl1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L202)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There is no such parameter.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 204 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9ORo80MRqvJg9ZJzQ:-MtP3am8-bF_qbpn2Aa2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L204)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/on_response/on_done/
</blockquote></details>

Done.
___
*[src/core/lib/ [...]

2022-01-18 17:50 UTC, markdroth requested changes
This is looking really good!  There are still some details that need fixing, but the overall structure looks great.

Please let me know if you have any questions.  Thanks!

> Reviewed 44 of 44 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-MtiImnb9aSVMS_Fp1g3:b-8j5wrr)* status: all files reviewed, 15 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 138 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiDpRVCISq_S7BMRkl:-MtiDpRVCISq_S7BMRkm:bapqfjb) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L138)):*
> ```cpp
>   // TODO(ctiller): share the quota from whomever instantiates this!
>   http_request_ =
>       HttpRequest::Get("http", args, pollent, &request,
> ```

I think we probably don't want to pass in the parent channel's channel args unmodified here, because if the application sets something like `GRPC_ARG_DEFAULT_AUTHORITY`, they're clearly intending to set the authority for the backend connections, not for the metadata query.

I think we should probably just pass in a new set of channel args here, manually propagating only those few things from the parent channel args that make sense to propagate, such as the resource quota.
___
*[src/core/lib/http/httpcli.h, line 50 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9RaLaCUk5_2yegvpK:-MtPomE563XXlwVkAZ-g:b-48lf61) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L50)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

> It would be nice to also convert grpc_http_request and grpc_http_response to idiomatic C++.

I agree it would be nice to clean these up.

I propose to separate changes to those structs from this PR, though. Updating those structs would entail a lot of changes to `src/core/lib/http/parser.cc`, `jwt_verifier.cc` and several other places, which could make this PR even larger.

> As an alternative for grpc_http_request, maybe we should just take a URI object as input instead?

I'm not sure if this would make sense because `URI` has no concept of HTTP headers, which `grpc_http_request` does. Likewise, `grpc_http_request` has no concept of query parameters, which `URI` does.
</blockquote></details>

Okay, I'm fine with deferring converting those APIs to C++ until later.

Good point about `grpc_http_request` not including query params and `URI` not including headers.  But looking at how this works with `GRPC_ARG_DEFAULT_AUTHORITY`, I think I steered you wrong there: the API is fairly cumbersome, and using a channel arg for a required parameter doesn't seem like the right choice.  So I think we'll wind up wanting both a `URI` and ` grpc_http_request` here.

I suggest the following:
- Replace the `scheme` parameter with a `URI` parameter.
- Remove the `path` data member from `grpc_http_request`.

That way, the `URI` will indicate the host and path (and provide a way to support query params in the future), and the `grpc_http_request` will support setting method, headers, and body, and there's no overlap between the two of them.
___
*[src/core/lib/http/httpcli.h, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9ITxS9dNfsifytxN3:-MtPleEF7Mk51fDmc4sg:bxq3z2a) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L86)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Great idea! This seemed to be a net cleanup.

I did need to separate out `httpcli.cc` etc. from the "grpc_base" library in order to do this, though. The reason is that in order to use the `grpc_channel_credentials` type, we need to depend on "grpc_security_base". But grpc_security_base" already depends on "grpc_base", so we'd have a circular dependency if we left it in there.
</blockquote></details>

Hmmm.  Are you sure this didn't drag an SSL dependency into insecure builds?  I notice that chttp2 depends on the HTTP parser, which is grouped into the same library as the this file.  Do we maybe need to split those up into two separate BUILD targets?

Of course, this problem will go away once #25586 is merged.  But we probably don't want to block this PR on that.
___
*[src/core/lib/http/httpcli.h, line 180 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9RwYc4h2aTFDCRyah:-MtPoNqj-MuIQHtNbvh1:bh91xt3) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L180)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

The `grpc_http_request` may or may not be heap allocated, so I think just for that reason it makes sense for the caller to own it.
</blockquote></details>

Oh, right, I forgot that we have different callers doing different things with regard to ownership of individual fields in that struct.  I guess that's something we'll need to figure out later as part of converting the `grpc_http_request` API to C++.  We'll probably wind up using `absl::string_view` for the fields of `grpc_http_request`, so that it's the caller's problem how to manage the lifetime of those fields.  At that point, `grpc_http_request` can be passed in by value, so ownership of the struct itself becomes a non-issue.

Anyway, this is fine for now.
___
*[src/core/lib/http/httpcli.h, line 188 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9NgCa2w-O0j75FF8M:-MtPmMVj-P5lxn23_rtg:byqteqc) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L188)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I'm hesitant to make this change because it would increase the size of this PR and I believe only bring us to a temporary stage.

What I think would be best is to change `on_done` to something like `std::function<absl::StatusOr<HttpRequest::Response>>`

But to get to that point, we'd need to first convert `grpc_http_request` and `grpc_http_response` to idiomatic C++ objects.

I.e., I propose leaving this change for when we update the request/response objects. What do you think?
</blockquote></details>

Okay, that's fine.
___
*[src/core/lib/http/httpcli.h, line 77 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtPx1BL7Yy4uFUL0xD5:-MtPx1BL7Yy4uFUL0xD6:be57pm0) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/lib/http/httpcli.h#L77)):*
> ```objc
>   //   For secure requests, use CreateHttpRequestSSLCredentials().
>   //   nullptr is treated as insecure credentials.
>   //   TODO(apolcyn): disallow nullptr as a value after unsecure builds
> ```

This TODO can be assigned to @yihuazhang.  Yihua, please take care of this as part of #25586.

Same thing for `Post()` below.
___
*[src/core/lib/http/httpcli.h, line 79 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtPxB43Ck-MB7cMWOJ2:-MtPxB444kR6BBiA7bH8:bhpqmf) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/lib/http/httpcli.h#L79)):*
> ```objc
>   //   TODO(apolcyn): disallow nullptr as a value after unsecure builds
>   //   are removed.
>   //   TODO(apolcyn): make this param optional and by default autodetected
> ```

I just realized that this may wind up being tricky, because it would mean that the HTTP client library would still drag in a dependency on the SSL library.  In principle, it should be possible to depend on the HTTP client library without dragging in that dependency.

How about this as an alternative: Keep this parameter as required, and basically say that the security level always depends on which credentials type you use, not on the URI scheme.  We can require that the URI scheme be either "http" or "https", but not require that it match the credentials us [...]

2022-01-20 17:59 UTC, apolcyn reviewed
I believe I've addressed comments again, PTAL. thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-MtsaPriCuZaWhBRgxVe:b-juapwp)* status: 23 of 47 files reviewed, 15 unresolved discussions (waiting on @markdroth and @yihuazhang)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 138 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiDpRVCISq_S7BMRkl:-MtsaWep7Wzc5PlCCeVK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L138)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we probably don't want to pass in the parent channel's channel args unmodified here, because if the application sets something like `GRPC_ARG_DEFAULT_AUTHORITY`, they're clearly intending to set the authority for the backend connections, not for the metadata query.

I think we should probably just pass in a new set of channel args here, manually propagating only those few things from the parent channel args that make sense to propagate, such as the resource quota.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 50 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9RaLaCUk5_2yegvpK:-Mtsaa8o5mAAPRuHFpJo:by5khsu) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Okay, I'm fine with deferring converting those APIs to C++ until later.

Good point about `grpc_http_request` not including query params and `URI` not including headers.  But looking at how this works with `GRPC_ARG_DEFAULT_AUTHORITY`, I think I steered you wrong there: the API is fairly cumbersome, and using a channel arg for a required parameter doesn't seem like the right choice.  So I think we'll wind up wanting both a `URI` and ` grpc_http_request` here.

I suggest the following:
- Replace the `scheme` parameter with a `URI` parameter.
- Remove the `path` data member from `grpc_http_request`.

That way, the `URI` will indicate the host and path (and provide a way to support query params in the future), and the `grpc_http_request` will support setting method, headers, and body, and there's no overlap between the two of them.
</blockquote></details>

Done.

The only tricky point here was that the `grpc_http_request.path` field is still needed for parsed (i.e. incoming) requests. So I left that field there but added a comment that it is only used for parsed requests.

I then updated all other code to take the path field from the URI instead.
___
*[src/core/lib/http/httpcli.h, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9ITxS9dNfsifytxN3:-MtsazXOEaue0SZKi3QG:b-ii33hn) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hmmm.  Are you sure this didn't drag an SSL dependency into insecure builds?  I notice that chttp2 depends on the HTTP parser, which is grouped into the same library as the this file.  Do we maybe need to split those up into two separate BUILD targets?

Of course, this problem will go away once #25586 is merged.  But we probably don't want to block this PR on that.
</blockquote></details>

The concrete ssl creds dependency is pulled in by `httpcli_ssl_credentials`, but this is kept as a separate target from `httpcli` (one does not depend on the other).

`httpcli` only depends on `grpc_security_base` (for the abstract channel credentials type), which as I understand is fine to have in insecure builds (at least, it passes `tools/run_tests/sanity/check_bad_dependencies.sh`).

Only the few targets which need secure http requests depend on `httpcli_ssl_credentials`
___
*[src/core/lib/http/httpcli.h, line 77 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtPx1BL7Yy4uFUL0xD5:-MtsbZAiBudHNVQEHt47:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/lib/http/httpcli.h#L77)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This TODO can be assigned to @yihuazhang.  Yihua, please take care of this as part of #25586.

Same thing for `Post()` below.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 79 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtPxB43Ck-MB7cMWOJ2:-MtscP-c92KF5t3p2uJQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/lib/http/httpcli.h#L79)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I just realized that this may wind up being tricky, because it would mean that the HTTP client library would still drag in a dependency on the SSL library.  In principle, it should be possible to depend on the HTTP client library without dragging in that dependency.

How about this as an alternative: Keep this parameter as required, and basically say that the security level always depends on which credentials type you use, not on the URI scheme.  We can require that the URI scheme be either "http" or "https", but not require that it match the credentials used.

Same thing for `Post()` below.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 113 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtPzctQBS_TaiojUWvT:-MtscQ7lDx3UyjWY5HqT:b6iolm5) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/lib/http/httpcli.h#L113)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Not a new issue introduced in this PR, but why are we passing in the body here if it's already part of `grpc_http_request`?
</blockquote></details>

Good catch. It was pretty straightforward to pass the body in through the `grpc_http_request` though, so I updated to do that.

There's a couple of cases where the body field isn't actually owned by the request, so we needed to release it before destroying the request, in order to avoid making a copy. But those cases were straightforward to handle.
___
*[src/core/lib/http/httpcli.cc, line 124 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtQ-n3A6s_Un8BPYiRN:-Mtsccuo9YOha8ESajMu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/lib/http/httpcli.cc#L124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please change this to:

```
channel_args_(CoreConfiguration::Get()
                             .channel_args_preconditioning()
                             .PreconditionChannelArgs(channel_args)),
```

This will ensure that the `ResourceQuota` is present in channel args, amongst other things.  Then you can initialize `resource_quota_` like this:

```
resource_quota_(ResourceQuotaFromChannelArgs(channel_args_)),
```
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.cc, line 144 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtQ0V2BBRxP6P_2mS6q:-Mtscqdy6rb6KxNrikZf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/lib/http/httpcli.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

None of this channel args or resource quota manipulation is needed if you make the change I suggested above.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.cc, line 291 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiC3M-57aTxLW6aFuP:-MtscrNNAzxVu6-4MbqG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/lib/http/httpcli.cc#L291)):*
<details><summary><i>Previously, mar [...]

2022-01-20 20:13 UTC, markdroth requested changes
Only one noteworthy issue remaining!

Please let me know if you have any questions.  Thanks!

> Reviewed 24 of 24 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-Mtt6gCm8VTauGKNjn-R:b-f1rz8t)* status: all files reviewed, 5 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 138 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiDpRVCISq_S7BMRkl:-Mtt0s8B5Uj956HDvBHw:byfnk8p) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L138)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This doesn't look right to me, for several reasons:
- Preconditioning channel args is intended to ensure that args are in a sane state when they cross an API boundary.  We do this whenever channel args are passed into the C-core API surface, and the resolver is created well below that point, so there's no need to do it again here.  (The reason I suggested doing preconditioning the args in the `HttpRequest` code is that I expect callers of `HttpRequest` to construct their own channel args rather than using the ones that are passed into C-core from the application, so entering the `HttpRequest` code is essentially analogous to entering C-core: that's the point at which we want to validate that the channel args are sane.)
- The main effect of preconditioning the channel args is to add an arg for the resource quota if such an arg was not already provided by the caller.  The code you added to `StartLocked()` is preconditioning the args, extracing the resulting resource quota, and then adding a duplicate arg for the resource quota to the args that you just extracted the resource quota from, which doesn't actually accomplish anything (and it takes an unnecessary extra ref to the resource quota and adds a duplicate channel arg where there shouldn't be any).
- You are still passing all other args from the parent channel to the HTTP request, which I don't think we want to do.

What I think we should do here is to construct our own set of channel args, and basically the only thing that needs to be there is the resource quota.

I suggest replacing the `channel_arg_` data member with a `ResourceQuotaRefPtr resource_quota_` data member, since that's really the only thing we need to preserve from the passed-in channel args.  You can set it in the initializer list for the `GoogleCloud2ProdResolver` ctor with `resource_quota_(ResourceQuotaFromChannelArgs(args.args))`.

Then, here in the `MetadataQuery` ctor, we can do something like this:

```
grpc_arg resource_quota_arg = grpc_arg_pointer_create(
    const_cast<char*>(GRPC_ARG_RESOURCE_QUOTA),
    resolver_->resource_quota_.get(),
    grpc_resource_quota_arg_vtable());
grpc_channel_args args = {1, &resource_quota_arg};
```

Then just pass `&args` to `HttpRequest::Get()`.

In principle, we should do this everywhere that we create an `HttpRequest`.
___
*[src/core/lib/http/httpcli.h, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9ITxS9dNfsifytxN3:-MtsosOr6_BFeTFOT2LJ:b-a17htl) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L86)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

The concrete ssl creds dependency is pulled in by `httpcli_ssl_credentials`, but this is kept as a separate target from `httpcli` (one does not depend on the other).

`httpcli` only depends on `grpc_security_base` (for the abstract channel credentials type), which as I understand is fine to have in insecure builds (at least, it passes `tools/run_tests/sanity/check_bad_dependencies.sh`).

Only the few targets which need secure http requests depend on `httpcli_ssl_credentials`
</blockquote></details>

Ah, okay.  Historically, insecure builds have not included any of the abstract security-related types, and there was no way to do so without bringing in the SSL dependency, so I was thinking that this was a change.  But it looks like the `grpc_security_base` target was actually introduced in #28408, which is paving the way for eliminating insecure builds, and it does allow adding those abstract types without adding an SSL dependency.  So this may still be a small change, but it's one that we were soon going to be doing anyway.

@yihuazhang, can you think of any problem with this change?
___
*[src/core/lib/http/httpcli.h, line 65 at r4](https://reviewable.io/reviews/grpc/grpc/28354#-Mtsr4gD3lkv8ZcPdMOs:-Mtsr4gEAMRqENYbmWSB:b-t0pek6) ([raw file](https://github.com/grpc/grpc/blob/0194442787f2c9de94183952fc02bc7e8ad9148d/src/core/lib/http/httpcli.h#L65)):*
> ```objc
>  public:
>   // Asynchronously perform a HTTP GET.
>   // 'scheme' can be "http" or "https", but note that the security level
> ```

The `scheme` parameter has been replaced with `uri`.
___
*[src/core/lib/http/httpcli.h, line 90 at r4](https://reviewable.io/reviews/grpc/grpc/28354#-MtsrAkp-3tVSnTBCyRk:-MtsrAkp-3tVSnTBCyRl:b-32nupa) ([raw file](https://github.com/grpc/grpc/blob/0194442787f2c9de94183952fc02bc7e8ad9148d/src/core/lib/http/httpcli.h#L90)):*
> ```objc
> 
>   // Asynchronously perform a HTTP POST.
>   // 'scheme' can be "http" or "https", but note that the security level
> ```

`scheme` has been replaced with `uri`.
___
*[src/core/lib/http/httpcli.cc, line 124 at r4](https://reviewable.io/reviews/grpc/grpc/28354#-MtsxHNI24EQUeV383P1:-MtsxHNI24EQUeV383P2:b-b59rd4) ([raw file](https://github.com/grpc/grpc/blob/0194442787f2c9de94183952fc02bc7e8ad9148d/src/core/lib/http/httpcli.cc#L124)):*
> ```cpp
>       request_text_(request_text),
>       deadline_(deadline),
>       channel_args_(const_cast<grpc_channel_args*>(
> ```

Instead of doing this `const_cast<>`, I suggest changing the data member to be const.
___
*[test/core/http/httpcli_test.cc, line 56 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiGZGi5jieSBi9LbF7:-Mtt69pp699M1Ze576A0:b-a03t72) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/test/core/http/httpcli_test.cc#L56)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

> GlobalSubprocessArgs
This global was actually not used, so deleted
</blockquote></details>

Doesn't look like it was actually removed.


<!-- Sent from Reviewable.io -->

2022-01-20 22:24 UTC, apolcyn reviewed
PTAL, thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-Mtt_SlcE8fE9LVt3caR:babs30w)* status: 41 of 47 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 138 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiDpRVCISq_S7BMRkl:-Mtt_WIVEi2JxhwellXH:b8nbk90) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L138)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't look right to me, for several reasons:
- Preconditioning channel args is intended to ensure that args are in a sane state when they cross an API boundary.  We do this whenever channel args are passed into the C-core API surface, and the resolver is created well below that point, so there's no need to do it again here.  (The reason I suggested doing preconditioning the args in the `HttpRequest` code is that I expect callers of `HttpRequest` to construct their own channel args rather than using the ones that are passed into C-core from the application, so entering the `HttpRequest` code is essentially analogous to entering C-core: that's the point at which we want to validate that the channel args are sane.)
- The main effect of preconditioning the channel args is to add an arg for the resource quota if such an arg was not already provided by the caller.  The code you added to `StartLocked()` is preconditioning the args, extracing the resulting resource quota, and then adding a duplicate arg for the resource quota to the args that you just extracted the resource quota from, which doesn't actually accomplish anything (and it takes an unnecessary extra ref to the resource quota and adds a duplicate channel arg where there shouldn't be any).
- You are still passing all other args from the parent channel to the HTTP request, which I don't think we want to do.

What I think we should do here is to construct our own set of channel args, and basically the only thing that needs to be there is the resource quota.

I suggest replacing the `channel_arg_` data member with a `ResourceQuotaRefPtr resource_quota_` data member, since that's really the only thing we need to preserve from the passed-in channel args.  You can set it in the initializer list for the `GoogleCloud2ProdResolver` ctor with `resource_quota_(ResourceQuotaFromChannelArgs(args.args))`.

Then, here in the `MetadataQuery` ctor, we can do something like this:

```
grpc_arg resource_quota_arg = grpc_arg_pointer_create(
    const_cast<char*>(GRPC_ARG_RESOURCE_QUOTA),
    resolver_->resource_quota_.get(),
    grpc_resource_quota_arg_vtable());
grpc_channel_args args = {1, &resource_quota_arg};
```

Then just pass `&args` to `HttpRequest::Get()`.

In principle, we should do this everywhere that we create an `HttpRequest`.
</blockquote></details>

Makes sense, done
___
*[src/core/lib/http/httpcli.h, line 65 at r4](https://reviewable.io/reviews/grpc/grpc/28354#-Mtsr4gD3lkv8ZcPdMOs:-Mtt_huvCzfheTgXC-AC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0194442787f2c9de94183952fc02bc7e8ad9148d/src/core/lib/http/httpcli.h#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `scheme` parameter has been replaced with `uri`.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 90 at r4](https://reviewable.io/reviews/grpc/grpc/28354#-MtsrAkp-3tVSnTBCyRk:-Mtt_iWe42xK0-9CLo8L:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0194442787f2c9de94183952fc02bc7e8ad9148d/src/core/lib/http/httpcli.h#L90)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`scheme` has been replaced with `uri`.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.cc, line 124 at r4](https://reviewable.io/reviews/grpc/grpc/28354#-MtsxHNI24EQUeV383P1:-Mtt_jDr1eUCNuzAthqn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0194442787f2c9de94183952fc02bc7e8ad9148d/src/core/lib/http/httpcli.cc#L124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of doing this `const_cast<>`, I suggest changing the data member to be const.
</blockquote></details>

Done.
___
*[test/core/http/httpcli_test.cc, line 56 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiGZGi5jieSBi9LbF7:-Mtt_k8y3WXbbg80o1LH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/test/core/http/httpcli_test.cc#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like it was actually removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 23:30 UTC, yihuazhang reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354)* status: 41 of 47 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/http/httpcli.h, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/28354#-Mt9ITxS9dNfsifytxN3:-MttnonB6DrlVCMu2HJ5:bordf5r) ([raw file](https://github.com/grpc/grpc/blob/6090e6fad62cb969dc99c0c1772d9961fd861bb8/src/core/lib/http/httpcli.h#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ah, okay.  Historically, insecure builds have not included any of the abstract security-related types, and there was no way to do so without bringing in the SSL dependency, so I was thinking that this was a change.  But it looks like the `grpc_security_base` target was actually introduced in #28408, which is paving the way for eliminating insecure builds, and it does allow adding those abstract types without adding an SSL dependency.  So this may still be a small change, but it's one that we were soon going to be doing anyway.

@yihuazhang, can you think of any problem with this change?
</blockquote></details>

I do not see any problem of introducing `httpcli_ssl_credentials` with regards to eliminating insecure build. It is similar to `grpc_ssl_credentials` target. 


<!-- Sent from Reviewable.io -->

2022-01-20 23:59 UTC, markdroth requested changes
This looks really good!  Remaining comments are all fairly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-MttvSWv-8pHoXyPxErP:boxsye2)* status: all files reviewed, 6 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 138 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiDpRVCISq_S7BMRkl:-MttvFdHBUFfcNaVPbXX:bu9uf08) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L138)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Makes sense, done
</blockquote></details>

Can you do the same thing in the other places where we create an `HttpRequest`?

Feel free to push back, since that is a bit of a broader change.  But it does seem like a good thing to do in this PR, since we're touching all of those call sites anyway.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 48 at r5](https://reviewable.io/reviews/grpc/grpc/28354#-MttuEIhBoa6Ta-K8Uqp:-MttuEIhBoa6Ta-K8Uqq:b4u33cf) ([raw file](https://github.com/grpc/grpc/blob/6004a82faaba27f32673bf9c337c276d5c67b56e/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L48)):*
> ```cpp
>   class MetadataQuery : public InternallyRefCounted<MetadataQuery> {
>    public:
>     MetadataQuery(ResourceQuotaRefPtr resource_quota,
> ```

This parameter is not needed.  We're already passing in a pointer to the `GoogleCloud2ProdResolver`, and since this class is nested inside of that one, it can access the private data member directly from the parent.
___
*[src/core/lib/http/httpcli.h, line 65 at r4](https://reviewable.io/reviews/grpc/grpc/28354#-Mtsr4gD3lkv8ZcPdMOs:-MtttyER1XyJJA9KK2j7:b8ts5al) ([raw file](https://github.com/grpc/grpc/blob/0194442787f2c9de94183952fc02bc7e8ad9148d/src/core/lib/http/httpcli.h#L65)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still need to document the `uri` parameter.
___
*[src/core/lib/http/httpcli.h, line 90 at r4](https://reviewable.io/reviews/grpc/grpc/28354#-MtsrAkp-3tVSnTBCyRk:-Mttu45wBIASdntFdimG:b8ts5al) ([raw file](https://github.com/grpc/grpc/blob/0194442787f2c9de94183952fc02bc7e8ad9148d/src/core/lib/http/httpcli.h#L90)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still need to document the `uri` parameter.
___
*[src/core/lib/http/httpcli.h, line 65 at r5](https://reviewable.io/reviews/grpc/grpc/28354#-Mttu-W32LNlWtGl-vuN:-Mttu-W48HUfghMYpGkK:b-ps59ij) ([raw file](https://github.com/grpc/grpc/blob/6004a82faaba27f32673bf9c337c276d5c67b56e/src/core/lib/http/httpcli.h#L65)):*
> ```objc
>  public:
>   // Asynchronously perform a HTTP GET.
>   // 'args' are channel args for the request. GRPC_ARG_DEFAULT_AUTHORITY is
> ```

Let's remove the note about `GRPC_ARG_DEFAULT_AUTHORITY`.
___
*[src/core/lib/http/httpcli.h, line 88 at r5](https://reviewable.io/reviews/grpc/grpc/28354#-Mttu2PH0B9K1s1OBD9o:-Mttu2PH0B9K1s1OBD9p:b-ps59ij) ([raw file](https://github.com/grpc/grpc/blob/6004a82faaba27f32673bf9c337c276d5c67b56e/src/core/lib/http/httpcli.h#L88)):*
> ```objc
> 
>   // Asynchronously perform a HTTP POST.
>   // 'args' are channel args for the request. GRPC_ARG_DEFAULT_AUTHORITY is
> ```

Let's remove the note about `GRPC_ARG_DEFAULT_AUTHORITY`.


<!-- Sent from Reviewable.io -->

2022-01-21 00:22 UTC, apolcyn reviewed
PTAL, thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-MttywKTEwoUHYaFHaAl:babs30w)* status: all files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 138 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiDpRVCISq_S7BMRkl:-Mtu-Oqn-lqFQeRseEQY:bnyxl4a) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L138)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can you do the same thing in the other places where we create an `HttpRequest`?

Feel free to push back, since that is a bit of a broader change.  But it does seem like a good thing to do in this PR, since we're touching all of those call sites anyway.
</blockquote></details>

Sorry I might be missing something, but I believe this was actually the only place that we were plumbing through channel args passed from higher layers into the `HttpRequest`. All other call sites pass nullptr channel args (except for a test which passes the one-off ssl override arg)

So I believe there's nothing left to do for other call sites?
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 48 at r5](https://reviewable.io/reviews/grpc/grpc/28354#-MttuEIhBoa6Ta-K8Uqp:-Mtu-Ny-006mPdessq6N:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6004a82faaba27f32673bf9c337c276d5c67b56e/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This parameter is not needed.  We're already passing in a pointer to the `GoogleCloud2ProdResolver`, and since this class is nested inside of that one, it can access the private data member directly from the parent.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 65 at r4](https://reviewable.io/reviews/grpc/grpc/28354#-Mtsr4gD3lkv8ZcPdMOs:-Mtu-oA7-9RmpAvaLYf9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0194442787f2c9de94183952fc02bc7e8ad9148d/src/core/lib/http/httpcli.h#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Still need to document the `uri` parameter.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 90 at r4](https://reviewable.io/reviews/grpc/grpc/28354#-MtsrAkp-3tVSnTBCyRk:-Mtu-p8FBBjOEB7PXxsA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0194442787f2c9de94183952fc02bc7e8ad9148d/src/core/lib/http/httpcli.h#L90)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Still need to document the `uri` parameter.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 65 at r5](https://reviewable.io/reviews/grpc/grpc/28354#-Mttu-W32LNlWtGl-vuN:-Mtu-oPb-5H4y_G7-Jyu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6004a82faaba27f32673bf9c337c276d5c67b56e/src/core/lib/http/httpcli.h#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's remove the note about `GRPC_ARG_DEFAULT_AUTHORITY`.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.h, line 88 at r5](https://reviewable.io/reviews/grpc/grpc/28354#-Mttu2PH0B9K1s1OBD9o:-Mtu-pMJ5y9fpUsJRSSi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6004a82faaba27f32673bf9c337c276d5c67b56e/src/core/lib/http/httpcli.h#L88)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's remove the note about `GRPC_ARG_DEFAULT_AUTHORITY`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-21 17:17 UTC, markdroth requested changes
Just a couple of minor nits remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-Mtxd9_s9C7l7TxfOJM8:bvuzvc3)* status: all files reviewed, 3 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 138 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiDpRVCISq_S7BMRkl:-MtxaiSY-UDMennqNB5Q:bbdszdx) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L138)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Sorry I might be missing something, but I believe this was actually the only place that we were plumbing through channel args passed from higher layers into the `HttpRequest`. All other call sites pass nullptr channel args (except for a test which passes the one-off ssl override arg)

So I believe there's nothing left to do for other call sites?
</blockquote></details>

Right, we're not plumbing anything through today, but in all of those cases, we *should* be plumbing the resource quota through.  In fact, I think there are some TODOs assigned to Craig in a few of the call sites about doing that.  So what I'm suggesting is that we go ahead and change those callers to create channel args that contain only the resource quota, just like we're doing here.

Because those callers are not passing anything down today, I would accept an argument that that's a separate change outside the scope of this PR.  But given that we're touching all of those callers anyway, it seems like the right thing to do to have them pass in the resource quota.

I'll leave it up to you.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 22 at r6](https://reviewable.io/reviews/grpc/grpc/28354#-MtxctPz9eGd2ZfgCZGE:-MtxctQ-0mG6h0b9bkRM:ba8tqiq) ([raw file](https://github.com/grpc/grpc/blob/c107f839d2d6dafd9556681f771d1a8bbc730b04/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L22)):*
> ```cpp
> 
> #include "src/core/ext/xds/xds_client.h"
> #include "src/core/lib/config/core_configuration.h"
> ```

I don't think this include is needed anymore.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 135 at r6](https://reviewable.io/reviews/grpc/grpc/28354#-Mtxa_WBCq7reGOO6jvp:-Mtxa_WBCq7reGOO6jvq:b-ck3go7) ([raw file](https://github.com/grpc/grpc/blob/c107f839d2d6dafd9556681f771d1a8bbc730b04/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L135)):*
> ```cpp
>   grpc_arg resource_quota_arg = grpc_channel_arg_pointer_create(
>       const_cast<char*>(GRPC_ARG_RESOURCE_QUOTA),
>       resolver->resource_quota_.get(), grpc_resource_quota_arg_vtable());
> ```

This needs to use `resolver_` instead of `resolver`, because we've already `std::move()`ed the value from the latter to the former in the initialization list above.


<!-- Sent from Reviewable.io -->

2022-01-21 17:22 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354)* status: all files reviewed, 3 unresolved discussions (waiting on @apolcyn and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 138 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiDpRVCISq_S7BMRkl:-Mtxda-XB478s1xeA3Jk:b-yk1528) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L138)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Right, we're not plumbing anything through today, but in all of those cases, we *should* be plumbing the resource quota through.  In fact, I think there are some TODOs assigned to Craig in a few of the call sites about doing that.  So what I'm suggesting is that we go ahead and change those callers to create channel args that contain only the resource quota, just like we're doing here.

Because those callers are not passing anything down today, I would accept an argument that that's a separate change outside the scope of this PR.  But given that we're touching all of those callers anyway, it seems like the right thing to do to have them pass in the resource quota.

I'll leave it up to you.
</blockquote></details>

The remaining callers are pretty much all from call credentials implementations which AFAICS don't have any pre-existing resource quota.

So passing in nullptr was just a convenient way to use the default resource quota.

Is your suggestion to remove the channel args preconditioning in `HttpRequest` and instead instantiate the default resource quota on the caller side?


<!-- Sent from Reviewable.io -->

2022-01-21 18:43 UTC, apolcyn reviewed
Addressed comments, but I still have a question about the channel args / resource quota suggestion. PTAL, thanks!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-MtxwcmY9pT5D7h1T0Uc:b-glxzht)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 22 at r6](https://reviewable.io/reviews/grpc/grpc/28354#-MtxctPz9eGd2ZfgCZGE:-MtxwmbO1C_-IVXGXVGP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c107f839d2d6dafd9556681f771d1a8bbc730b04/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L22)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this include is needed anymore.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 135 at r6](https://reviewable.io/reviews/grpc/grpc/28354#-Mtxa_WBCq7reGOO6jvp:-MtxwnLY1_3lNyPcI4OD:b-tqj6nh) ([raw file](https://github.com/grpc/grpc/blob/c107f839d2d6dafd9556681f771d1a8bbc730b04/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L135)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to use `resolver_` instead of `resolver`, because we've already `std::move()`ed the value from the latter to the former in the initialization list above.
</blockquote></details>

good catch, done


<!-- Sent from Reviewable.io -->

2022-01-21 19:23 UTC, markdroth approved these changes
This looks great!

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28354#-:-Mty4soQ5Tls4MYCPtgi:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 138 at r3](https://reviewable.io/reviews/grpc/grpc/28354#-MtiDpRVCISq_S7BMRkl:-Mty4et-DTyOfjmVriU4:bbpibwa) ([raw file](https://github.com/grpc/grpc/blob/b0759d697e0903f6bc9bdec708eb868c2021e0f3/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L138)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

The remaining callers are pretty much all from call credentials implementations which AFAICS don't have any pre-existing resource quota.

So passing in nullptr was just a convenient way to use the default resource quota.

Is your suggestion to remove the channel args preconditioning in `HttpRequest` and instead instantiate the default resource quota on the caller side?


</blockquote></details>

Oh, good point -- for some reason, I was thinking that the parent channel's channel args was available in those callers, so we could get the resource quota from there.  But you're right, call creds currently don't have access to channel args, so there's no easy way to do this.

Sorry for the confusion.


<!-- Sent from Reviewable.io -->

2022-01-25 18:35 UTC, apolcyn commented
C# macos and artifact build macos failures are tool failures

2022-01-25 18:37 UTC, merged