LRS changes for federation
grpc/grpc pull request #28504
Opened 2022-01-09 04:01 UTC by donnadionne

Passing xds server object instead of just a string name

2022-01-10 06:40 UTC, donnadionne reviewed
Please take a quick look to make sure I am on the right track.  I am about to make the load reporting API changes: starting with AddClusterDropStats and AddClusterLocalityStats

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-Mt1hUMc2_bv0Tjnrc9B:bui7ao5)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2022-01-11 23:16 UTC, markdroth requested changes
It looks like you're heading in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-MtAQ6mFEcm993Ct34P3:b-9snqvz)* status: all files reviewed, 9 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 370 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-MtAOlLx37V6YuC5RiCr:-MtAOlLx37V6YuC5RiCs:bwguasl) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L370)):*
> ```cpp
>   }
>   if (state.update->lrs_load_reporting_server.has_value()) {
>     mechanism["lrsLoadReportingServerName"] =
> ```

Need to remove the `Name` suffix from the field name here.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 891 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-MtAOxbLEynP6F01byL6:-MtAOxbLEynP6F01byL7:b-wcrfho) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L891)):*
> ```cpp
>     if (config_->discovery_mechanisms()[discovery_index]
>             .lrs_load_reporting_server.has_value()) {
>       xds_cluster_impl_config["lrsLoadReportingServerName"] =
> ```

Need to remove `Name` suffix from the field name here.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1154 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-MtAP5XH5nzv7aV3nQtt:-MtAP5XH5nzv7aV3nQtu:b-wcrfho) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1154)):*
> ```cpp
>     }
>     // LRS load reporting server name.
>     it = json.object_value().find("lrsLoadReportingServerName");
> ```

Need to remove `Name` suffix from the field name here.
___
*[src/core/ext/xds/xds_api.h, line 163 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9s6JD87HdJ5T1oiOZ:-Mt9s6JD87HdJ5T1oiO_:b-wfs8s6) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_api.h#L163)):*
> ```objc
> 
>   // Creates an LRS request sending a client-side load report.
>   grpc_slice CreateLrsRequest(const XdsBootstrap::XdsServer& server,
> ```

It shouldn't be necessary to pass this parameter into this method, since it's not needed by anything called inside of the method.  I think it's fine to leave that field in `XdsEncodingContext` uninitialized (or default-initialized) in this case, since nothing will actually look at it.
___
*[src/core/ext/xds/xds_api.h, line 176 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9sGhn6L4b25xR5poY:-Mt9sGhn6L4b25xR5poZ:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_api.h#L176)):*
> ```objc
>   // Assemble the client config proto message and return the serialized result.
>   std::string AssembleClientConfig(
>       const XdsBootstrap::XdsServer& server,
> ```

Same here.
___
*[src/core/ext/xds/xds_bootstrap.h, line 72 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9sWVq9qrw_llNmPX9:-Mt9sWVq9qrw_llNmPXA:b-wnar78) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_bootstrap.h#L72)):*
> ```objc
>       return (server_uri == other.server_uri &&
>               channel_creds_type == other.channel_creds_type &&
>               channel_creds_config.Dump() ==
> ```

No need to use `Dump()`; you can just directly check for equality of the JSON objects.
___
*[src/core/ext/xds/xds_bootstrap.h, line 87 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9v0Nx4QBlG28qjRJZ:-Mt9v0NyEqyQV2Y3OMgX:b-lsnky4) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_bootstrap.h#L87)):*
> ```objc
>     }
> 
>     Json::Object ToJson() const {
> ```

The JSON format that we output here should be the same as the format that we read from the bootstrap file.  We should test this by making sure that `XdsServer::Parse()` succeeds on the output of `XdsServer::ToJson()`.
___
*[src/core/ext/xds/xds_bootstrap.h, line 88 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9t5FJ3ZST462YMPiy:-Mt9t5FK-BRZEcZvUMwW:bxh1fm0) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_bootstrap.h#L88)):*
> ```objc
> 
>     Json::Object ToJson() const {
>       Json::Object channel_cred = {
> ```

Suggest writing this as:

```
Json::Object channel_creds_json{
    {"type", channel_creds_type}
};
if (channel_creds_config.type() != Json::Type::JSON_NULL) {
  channel_creds_json["config"] = channel_creds_config;
}
Json::Object json{
    {"server_uri", server_uri},
    {"channel_creds", Json::Array{std::move(channel_creds_json)}},
};
if (!server_features.empty()) {
  Json::Array server_features_json;
  for (auto& feature : server_features) {
    server_features_json.emplace_back(feature);
  }
  json["server_features"] = std::move(server_features_json);
}
```
___
*[src/core/ext/xds/xds_bootstrap.h, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9tOkG8uOimN63Y7bp:-Mt9tOkG8uOimN63Y7bq:bo7i7xu) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_bootstrap.h#L94)):*
> ```objc
>       channel_creds.emplace_back(channel_cred);
>       Json::Array server_features;
>       for (auto& feature : server_features) {
> ```

This is not doing what you think it is, because you have a local variable of the same name as the data member.


<!-- Sent from Reviewable.io -->

2022-01-13 07:32 UTC, donnadionne reviewed
Fixed the comments except for adding a bootstrap test.  

I have changed the load reporting api to use xds server now.

Would like to get your review to make sure it's going in the right direction.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-MtHK4Fx-YJhsuUZWGbe:bh5or9q)* status: 8 of 13 files reviewed, 10 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 370 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-MtAOlLx37V6YuC5RiCr:-MtH1uYB21Q10SL3_yiV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L370)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to remove the `Name` suffix from the field name here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 891 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-MtAOxbLEynP6F01byL6:-MtH1vGH9vjDdTkgrmpP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L891)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to remove `Name` suffix from the field name here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1154 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-MtAP5XH5nzv7aV3nQtt:-MtH1vox8mCYWHGLgO7i:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1154)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need to remove `Name` suffix from the field name here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 163 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9s6JD87HdJ5T1oiOZ:-MtHK-Ud8Y4op5EgtOt3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_api.h#L163)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It shouldn't be necessary to pass this parameter into this method, since it's not needed by anything called inside of the method.  I think it's fine to leave that field in `XdsEncodingContext` uninitialized (or default-initialized) in this case, since nothing will actually look at it.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.h, line 176 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9sGhn6L4b25xR5poY:-MtHK0Eo6GkLt14rjudS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_api.h#L176)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.h, line 72 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9sWVq9qrw_llNmPX9:-MtH1ITg-9zFfUCcijcc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_bootstrap.h#L72)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to use `Dump()`; you can just directly check for equality of the JSON objects.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.h, line 88 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9t5FJ3ZST462YMPiy:-MtGz-S2AF_0ai-yPbxu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_bootstrap.h#L88)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as:

```
Json::Object channel_creds_json{
    {"type", channel_creds_type}
};
if (channel_creds_config.type() != Json::Type::JSON_NULL) {
  channel_creds_json["config"] = channel_creds_config;
}
Json::Object json{
    {"server_uri", server_uri},
    {"channel_creds", Json::Array{std::move(channel_creds_json)}},
};
if (!server_features.empty()) {
  Json::Array server_features_json;
  for (auto& feature : server_features) {
    server_features_json.emplace_back(feature);
  }
  json["server_features"] = std::move(server_features_json);
}
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.h, line 94 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9tOkG8uOimN63Y7bp:-MtGyXWQ3IbSR8ry4lZy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_bootstrap.h#L94)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is not doing what you think it is, because you have a local variable of the same name as the data member.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2073 at r2](https://reviewable.io/reviews/grpc/grpc/28504#-MtHL5e878eVRJYdt3OL:-MtHL5e9E_YaXhKGn61N:b-uly45o) ([raw file](https://github.com/grpc/grpc/blob/a2a5b5a21037f7a8b91057807a3d1ad7a890f3a7/src/core/ext/xds/xds_client.cc#L2073)):*
> ```cpp
>   }
>   auto server = xds_server_channel_map_.find(xds_server);
>   if (server != xds_server_channel_map_.end()) {
> ```

design doc says to verify xds server is already configured in the bootstrap file, is a find in xds_server_channel_map_ sufficient?


<!-- Sent from Reviewable.io -->

2022-01-13 17:23 UTC, markdroth requested changes
This is getting closer.  There are a couple of structural issues that need to be addressed.

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-MtJSfMX5miCgM-zm8vp:b-t1mqn7)* status: all files reviewed, 14 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_api.cc, line 512 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJCTbL6k0FTYYLgLSV:-MtJCTbL6k0FTYYLgLSW:b-z91rjb) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_api.cc#L512)):*
> ```cpp
>   upb::Arena arena;
>   const XdsEncodingContext context = {client_,
>                                       // Temporary XdsServer which will go out
> ```

You can avoid the scoping problem by using a local variable:

```
// The xDS server info is not actually needed here, so we seed it with an empty value.
XdsBootstrap::XdsServer empty_server;
const XdsEncodingContext context = {client_, empty_server, ...};
```
___
*[src/core/ext/xds/xds_api.cc, line 639 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJCmyj3V3PkO6eEyyv:-MtJCmyj3V3PkO6eEyyw:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_api.cc#L639)):*
> ```cpp
>                                                                  arena.ptr());
>   const XdsEncodingContext context = {client_,
>                                       // Temporary XdsServer which will go out
> ```

Same here.
___
*[src/core/ext/xds/xds_bootstrap.h, line 86 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJDBpgBQ1n4NCwS9KG:-MtJDBphC6A_BncmSpD0:bzgkmy0) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_bootstrap.h#L86)):*
> ```objc
>     }
> 
>     Json::Object ToJson() const {
> ```

This body of this method is a little too long to be in the .h file.  Please move it to the .cc file.
___
*[src/core/ext/xds/xds_client.cc, line 2073 at r2](https://reviewable.io/reviews/grpc/grpc/28504#-MtHL5e878eVRJYdt3OL:-MtJJBVk1w853Vx9ougw:b-e3vsqd) ([raw file](https://github.com/grpc/grpc/blob/a2a5b5a21037f7a8b91057807a3d1ad7a890f3a7/src/core/ext/xds/xds_client.cc#L2073)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

design doc says to verify xds server is already configured in the bootstrap file, is a find in xds_server_channel_map_ sufficient?
</blockquote></details>

I think it would be cleaner to explicitly check the bootstrap config, because in principle there could be cases where a client sends load reports without actually being subscribed to any xDS resources, in which case there will not be an existing entry in `xds_server_channel_map_`.  (We don't really expect such cases in practice, but I think it's better to do this cleanly in case such a case comes up in the future.)  You can basically check whether the passed-in `xds_server` is equal to either `bootstrap_->xds_server()` or to any entry in the `xds_servers` of any of the entries in `bootstrap_->authorities()`.

This also brings up another point, which is that we need to hold a ref to the relevant `ChannelState` object for load reports, because even in the expected case where the client *is* subscribed to xDS resources, we need the `ChannelState` object to stick around long enough to send the final load report even after the client unsubscribes from the last xDS resource for that authority.  We can do this using the same pattern as we do for xDS resources.  The data structures should look something like this:

```
using LoadReportMap = std::map<
    std::pair<std::string /*cluster_name*/, std::string /*eds_service_name*/>,
    LoadReportState>;

struct LoadReportServer {
  RefCountedPtr<ChannelState> channel_state;
  LoadReportMap load_report_map;
};

std::map<XdsBootstrap::XdsServer, LoadReportServer> xds_load_report_server_map_
    ABSL_GUARDED_BY(mu_);
```

Then, in `AddClusterDropStats()` and `AddClusterLocalityStats()`, when we create a new entry in the map, set the `channel_state` data member similarly to [the way we do it in `WatchResource()`](https://github.com/grpc/grpc/blob/32b087e6741b15d302fc4a4ea0fb205ae1d41954/src/core/ext/xds/xds_client.cc#L1924).
___
*[src/core/ext/xds/xds_client.cc, line 583 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJOzEQ50VjnM6zRFR3:-MtJOzEQ50VjnM6zRFR4:bq293zz) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_client.cc#L583)):*
> ```cpp
> }
> 
> void XdsClient::ChannelState::StopLrsCall() { lrs_calld_.reset(); }
> ```

I think that in this method, we should remove the entry for `server_` from `xds_client->xds_load_report_server_map_`.
___
*[src/core/ext/xds/xds_client.cc, line 1396 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJFiya5R_Jpck3z-kG:-MtJFiya5R_Jpck3z-kH:b-frhpiu) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_client.cc#L1396)):*
> ```cpp
>   if (old_val && last_report_counters_were_zero_) {
>     if (xds_client()
>             ->xds_server_load_report_map_[parent_->chand()->server_]
> ```

This will implicitly add an entry for `parent_->chand()->server_` in `xds_server_load_report_map_` if it doesn't already exist, which isn't what we want.  I think we should instead do something like this:

```
auto it = xds_client()->xds_server_load_report_map_.find(parent_->chand()->server_);
if (it == xds_client()->xds_server_load_report_map_.end() ||
    it->second.empty()) {
```

Similar thing everywhere that we access `xds_server_load_report_map_`, except for `AddClusterDropStats()` and `AddClusterLocalityStats()`, since in those two cases, we *do* want to create the entry if it doesn't already exist.
___
*[src/core/ext/xds/xds_client.cc, line 1906 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJKjY0-H5Jf-hdxt8E:-MtJKjY11hGSWMJVYCPP:b-7kubyf) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_client.cc#L1906)):*
> ```cpp
>     MutexLock lock(&mu_);
>     MaybeRegisterResourceTypeLocked(type);
>     // TODO(donnadionne): If we get a request for an authority that is not
> ```

Not directly related to this PR, but this TODO can go away now.
___
*[src/core/ext/xds/xds_client.cc, line 2045 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJF4Lh-3Nmanm-g7XY:-MtJF4Lh-3Nmanm-g7XZ:bgi7au7) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_client.cc#L2045)):*
> ```cpp
>     const XdsBootstrap::XdsServer& xds_server, absl::string_view cluster_name,
>     absl::string_view eds_service_name) {
>   // TODO(roth): When we add support for direct federation, use the
> ```

This TODO can go away now.
___
*[src/core/ext/xds/xds_client.cc, line 2050 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJRh2R8kCvqV2qU0E0:-MtJRh2R8kCvqV2qU0E1:bu9ekyk) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_client.cc#L2050)):*
> ```cpp
>       std::make_pair(std::string(cluster_name), std::string(eds_service_name));
>   MutexLock lock(&mu_);
>   // We jump through some hoops here to make sure that the absl::string_views
> ```

We need to take this same approach for the `XdsServer` object that we're taking for the cluster name and EDS service name here.  The way this code is written right now, the resulting `XdsClusterDropStats` object will hold a reference to the `XdsServer` object passed in by the caller, but we have no way of knowing that the caller will keep that object alive long enough.  We instead need it to hold a ref to the map key, which we know will live at least as long as the `XdsClusterDropStats` object.
___
*[src/core/ext/xds/xds_client.cc, line 2088 at r3](https://reviewable.io/re [...]

2022-01-19 06:45 UTC, donnadionne reviewed
ready for another round of review!  Fixed previous comments and added tests. Thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-Mtl4Gx-B6xfJYg6C7YL:b7c2xaj)* status: all files reviewed, 14 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 512 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJCTbL6k0FTYYLgLSV:-MtRoSnE9WPheDUde0wz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_api.cc#L512)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can avoid the scoping problem by using a local variable:

```
// The xDS server info is not actually needed here, so we seed it with an empty value.
XdsBootstrap::XdsServer empty_server;
const XdsEncodingContext context = {client_, empty_server, ...};
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 639 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJCmyj3V3PkO6eEyyv:-MtRoTxp19E9lCxZYfcT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_api.cc#L639)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.h, line 87 at r1](https://reviewable.io/reviews/grpc/grpc/28504#-Mt9v0Nx4QBlG28qjRJZ:-Mtl4G6Y79GxYdVgH7Mu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7417bca58d902afe3cd58b7fd57a9e54e4036ad4/src/core/ext/xds/xds_bootstrap.h#L87)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The JSON format that we output here should be the same as the format that we read from the bootstrap file.  We should test this by making sure that `XdsServer::Parse()` succeeds on the output of `XdsServer::ToJson()`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.h, line 86 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJDBpgBQ1n4NCwS9KG:-MtRpZLn0Ijn7X08Lm2B:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_bootstrap.h#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This body of this method is a little too long to be in the .h file.  Please move it to the .cc file.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2073 at r2](https://reviewable.io/reviews/grpc/grpc/28504#-MtHL5e878eVRJYdt3OL:-MtkxqSfAT3LezdcETPb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a2a5b5a21037f7a8b91057807a3d1ad7a890f3a7/src/core/ext/xds/xds_client.cc#L2073)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think it would be cleaner to explicitly check the bootstrap config, because in principle there could be cases where a client sends load reports without actually being subscribed to any xDS resources, in which case there will not be an existing entry in `xds_server_channel_map_`.  (We don't really expect such cases in practice, but I think it's better to do this cleanly in case such a case comes up in the future.)  You can basically check whether the passed-in `xds_server` is equal to either `bootstrap_->xds_server()` or to any entry in the `xds_servers` of any of the entries in `bootstrap_->authorities()`.

This also brings up another point, which is that we need to hold a ref to the relevant `ChannelState` object for load reports, because even in the expected case where the client *is* subscribed to xDS resources, we need the `ChannelState` object to stick around long enough to send the final load report even after the client unsubscribes from the last xDS resource for that authority.  We can do this using the same pattern as we do for xDS resources.  The data structures should look something like this:

```
using LoadReportMap = std::map<
    std::pair<std::string /*cluster_name*/, std::string /*eds_service_name*/>,
    LoadReportState>;

struct LoadReportServer {
  RefCountedPtr<ChannelState> channel_state;
  LoadReportMap load_report_map;
};

std::map<XdsBootstrap::XdsServer, LoadReportServer> xds_load_report_server_map_
    ABSL_GUARDED_BY(mu_);
```

Then, in `AddClusterDropStats()` and `AddClusterLocalityStats()`, when we create a new entry in the map, set the `channel_state` data member similarly to [the way we do it in `WatchResource()`](https://github.com/grpc/grpc/blob/32b087e6741b15d302fc4a4ea0fb205ae1d41954/src/core/ext/xds/xds_client.cc#L1924).
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 583 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJOzEQ50VjnM6zRFR3:-MtRrYNd4Eb0LuM9DJlW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_client.cc#L583)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think that in this method, we should remove the entry for `server_` from `xds_client->xds_load_report_server_map_`.
</blockquote></details>

Done.



_Code quote:_
```cpp
    if (xds_client()
            ->xds_server_load_report_map_[parent_->chand()->server_]
```
___
*[src/core/ext/xds/xds_client.cc, line 1396 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJFiya5R_Jpck3z-kG:-MtRuSHBBwRT5ighKAzw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_client.cc#L1396)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This will implicitly add an entry for `parent_->chand()->server_` in `xds_server_load_report_map_` if it doesn't already exist, which isn't what we want.  I think we should instead do something like this:

```
auto it = xds_client()->xds_server_load_report_map_.find(parent_->chand()->server_);
if (it == xds_client()->xds_server_load_report_map_.end() ||
    it->second.empty()) {
```

Similar thing everywhere that we access `xds_server_load_report_map_`, except for `AddClusterDropStats()` and `AddClusterLocalityStats()`, since in those two cases, we *do* want to create the entry if it doesn't already exist.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 1906 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJKjY0-H5Jf-hdxt8E:-MtRx2Vr1lAOpi_bI48g:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_client.cc#L1906)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Not directly related to this PR, but this TODO can go away now.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2045 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJF4Lh-3Nmanm-g7XY:-MtRx3r20rnTPdeJ5gvh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_client.cc#L2045)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This TODO can go away now.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2050 at r3](https://reviewable.io/reviews/grpc/grpc/28504#-MtJRh2R8kCvqV2qU0E0:-MtRx5eQE9biY7u10GQf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/65075e9572e305966d9c8ea47658b476ea0ad2d8/src/core/ext/xds/xds_client.cc#L2050)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We need to take this same approach for the `XdsServer` object that we're taking for the cluster name and EDS service name here.  The way this code is written right now, the resulting `XdsClusterDropStats` object will hold a reference to the `XdsServer` object passed in by the caller, but we have no way of knowing that the caller will keep that object alive long enough.  We instead need it to hold a ref to the map key, whi [...]

2022-01-19 18:43 UTC, markdroth requested changes
This looks really good!  Remaining comments are mostly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-MtndY-M5odfyrDrvknb:b-eeivja)* status: all files reviewed, 24 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_bootstrap.h, line 126 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-Mtn8BZIE1tCeG45vRX3:-Mtn8BZJBmQerpT7gH4j:b-cjaysd) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_bootstrap.h#L126)):*
> ```objc
>   }
>   // A util method to check that an xds server exists in this bootstrap file.
>   const bool XdsServerExists(const XdsServer& server) const;
> ```

No need to have the return type be `const` here.  That doesn't add any value and may make life more difficult for callers that may not want the value to be const.
___
*[src/core/ext/xds/xds_client.h, line 309 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-Mtn8rZb3K_fGw4yXDZ9:-Mtn8rZb3K_fGw4yXDZA:b-hhljqd) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.h#L309)):*
> ```objc
> 
>   // Load report data.
>   using LoadReportMap = std::map<
> ```

Please move these two types (`LoadReportMap` and `LoadReportServer`) up to line 257, right below `LoadReportState`.

https://google.github.io/styleguide/cppguide.html#Declaration_Order
___
*[src/core/ext/xds/xds_client.cc, line 1767 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-Mtn9c5-8XUjV_5kdjE3:-Mtn9c5-8XUjV_5kdjE4:b7orp7g) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L1767)):*
> ```cpp
>   // Ignore status from a stale call.
>   if (IsCurrentCallOnChannel()) {
>     // GPR_ASSERT(!xds_client()->shutting_down_);
> ```

Why is this commented out?
___
*[src/core/ext/xds/xds_client.cc, line 2048 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-Mtn9r28B8gckazD65iU:-Mtn9r28B8gckazD65iV:b-xluemv) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2048)):*
> ```cpp
>     const XdsBootstrap::XdsServer& xds_server, absl::string_view cluster_name,
>     absl::string_view eds_service_name) {
>   XdsBootstrap::XdsServer map_key = xds_server;
> ```

This local copy is not necessary.  We can just directly use `xds_server` when we add the key to `xds_load_report_server_map_` below.
___
*[src/core/ext/xds/xds_client.cc, line 2057 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnA7yd2Q4K8Im7sWwn:-MtnA7yd2Q4K8Im7sWwo:b-69aew6) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2057)):*
> ```cpp
>   // XdsBootstrap::XdsServer and strings
>   // in the load_report_map_ key, so that they have the same lifetime.
>   auto map_it =
> ```

Suggest calling this `server_it`.
___
*[src/core/ext/xds/xds_client.cc, line 2059 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnA2-t1nmC8QacoA0f:-MtnA2-t1nmC8QacoA0g:bl3gwzk) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2059)):*
> ```cpp
>   auto map_it =
>       xds_load_report_server_map_
>           .emplace(std::make_pair(std::move(map_key), LoadReportServer()))
> ```

No need for `std::make_pair()` here; those arguments can be passed directly to `emplace()`.
___
*[src/core/ext/xds/xds_client.cc, line 2066 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnB_B2-4GmUJEUH3sh:-MtnB_B2-4GmUJEUH3si:bjud0wr) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2066)):*
> ```cpp
>   auto load_report_it =
>       map_it->second.load_report_map
>           .emplace(std::make_pair(std::move(key), LoadReportState()))
> ```

No need for `std::make_pair()` here either.
___
*[src/core/ext/xds/xds_client.cc, line 2085 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnAsLH56IOkLjoL5GP:-MtnAsLH56IOkLjoL5GQ:b9fil0l) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2085)):*
> ```cpp
>   }
>   auto server = xds_server_channel_map_.find(map_it->first);
>   if (bootstrap_->XdsServerExists(server->first)) {
> ```

This check should move up to the top of this method, before we insert any data into `xds_load_report_server_map_`.  If the specified server is not found, we should return null, since there's no point in gathering any load report data that we're never going to report to anyone.

Please make sure to change all callers to handle the case where this method returns null.
___
*[src/core/ext/xds/xds_client.cc, line 2119 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnBsHwEB7IRteLNYaE:-MtnBsHwEB7IRteLNYaF:bthwg09) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2119)):*
> ```cpp
>     absl::string_view eds_service_name,
>     RefCountedPtr<XdsLocalityName> locality) {
>   XdsBootstrap::XdsServer map_key = xds_server;
> ```

This local copy is not necessary.
___
*[src/core/ext/xds/xds_client.cc, line 2130 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnBuN60z4qEeh6cryJ:-MtnBuN60z4qEeh6cryK:b-em52b4) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2130)):*
> ```cpp
>   auto map_it =
>       xds_load_report_server_map_
>           .emplace(std::make_pair(std::move(map_key), LoadReportServer()))
> ```

No need for `std::make_pair()`.
___
*[src/core/ext/xds/xds_client.cc, line 2137 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnBxgt6d2tAXpQBDT5:-MtnBxgt6d2tAXpQBDT6:b-em52b4) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2137)):*
> ```cpp
>   auto load_report_it =
>       map_it->second.load_report_map
>           .emplace(std::make_pair(std::move(key), LoadReportState()))
> ```

No need for `std::make_pair()`.
___
*[src/core/ext/xds/xds_client.cc, line 2158 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnC-yi49v86E1FCVs1:-MtnC-yi49v86E1FCVs2:bvz4hn) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2158)):*
> ```cpp
>   }
>   auto server = xds_server_channel_map_.find(map_it->first);
>   if (bootstrap_->XdsServerExists(server->first)) {
> ```

Same as above: This check should move to the top of the method, before we add anything to `xds_load_report_server_map_`, and if the server is not found, we should return null.

Also need to change callers to handle the case where this method returns null.
___
*[src/core/ext/xds/xds_client.cc, line 2229 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnCXqbEUHxZT57uksI:-MtnCXqbEUHxZT57uksJ:b-30nwe2) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2229)):*
> ```cpp
>   }
>   XdsApi::ClusterLoadReportMap snapshot_map;
>   auto map_it = xds_load_report_server_map_.find(xds_server);
> ```

Please call this `server_it`.
___
*[src/core/ext/xds/xds_client.cc, line 2231 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnCyvt9oHArFnDH-yo:-MtnCyvt9oHArFnDH-yp:bk6l8j1) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2231)):*
> ```cpp
>   auto map_it = xds_load_report_server_map_.find(xds_server);
>   if (map_it == xds_load_report_server_map_.end()) return snapshot_map;
>   for (auto load_report_it = map_it->second.load_report_map.begin();
> ```

Please change this to:

```
auto& load_report_map = server_it->second.load_report_map;
for (auto load_report_it = load_report_map.begin();
     load_report_it != load_repor [...]

2022-01-20 09:51 UTC, donnadionne reviewed
Taken care of the comments. PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-MtqtTNA02OLLHCxVmu0:bnsyvl1)* status: 11 of 16 files reviewed, 24 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_bootstrap.h, line 126 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-Mtn8BZIE1tCeG45vRX3:-MtpZn6S52IkOi03MdQF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_bootstrap.h#L126)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to have the return type be `const` here.  That doesn't add any value and may make life more difficult for callers that may not want the value to be const.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.h, line 309 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-Mtn8rZb3K_fGw4yXDZ9:-Mtp_SeZEp_Hk7F0Es5Y:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.h#L309)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move these two types (`LoadReportMap` and `LoadReportServer`) up to line 257, right below `LoadReportState`.

https://google.github.io/styleguide/cppguide.html#Declaration_Order
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 1767 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-Mtn9c5-8XUjV_5kdjE3:-MtqtWvZ6MdWhWpPFew1:b-rg3uy7) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L1767)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this commented out?
</blockquote></details>

I'll send you an email to explain this
___
*[src/core/ext/xds/xds_client.cc, line 2048 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-Mtn9r28B8gckazD65iU:-Mtp_oS81pxDJJCkGatF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2048)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This local copy is not necessary.  We can just directly use `xds_server` when we add the key to `xds_load_report_server_map_` below.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2057 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnA7yd2Q4K8Im7sWwn:-Mtpa6Wj3p-3yuk8LwWz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2057)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `server_it`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2059 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnA2-t1nmC8QacoA0f:-Mtpa6uCD1GTofpa2TnV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2059)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `std::make_pair()` here; those arguments can be passed directly to `emplace()`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2066 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnB_B2-4GmUJEUH3sh:-MtplnOZ2hoZDv26KfwD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2066)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `std::make_pair()` here either.
</blockquote></details>

Done.



_Code quote:_
```cpp
AddClusterDropStats
```
___
*[src/core/ext/xds/xds_client.cc, line 2085 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnAsLH56IOkLjoL5GP:-MtploQn5M0MB2_zfSm5:b-6vs4kq) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2085)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check should move up to the top of this method, before we insert any data into `xds_load_report_server_map_`.  If the specified server is not found, we should return null, since there's no point in gathering any load report data that we're never going to report to anyone.

Please make sure to change all callers to handle the case where this method returns null.
</blockquote></details>

result is being stored in drop_stats_ and XdsClusterImplLb::Picker::Picker will check it against nullptr before use.
___
*[src/core/ext/xds/xds_client.cc, line 2119 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnBsHwEB7IRteLNYaE:-Mtpn2cl8isukySw2wr2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2119)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This local copy is not necessary.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2130 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnBuN60z4qEeh6cryJ:-Mtpn30y3AUIcTFAA3fC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2130)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `std::make_pair()`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2137 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnBxgt6d2tAXpQBDT5:-MtppRWt5lNJpIWI0R31:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2137)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `std::make_pair()`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2158 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnC-yi49v86E1FCVs1:-MtppSs9EQYljG_4CGu5:b-fhbwex) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2158)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as above: This check should move to the top of the method, before we add anything to `xds_load_report_server_map_`, and if the server is not found, we should return null.

Also need to change callers to handle the case where this method returns null.
</blockquote></details>

This one is a bit more complicated, without this object, we can't wrap the subchannel in StatsSubchannelWrapper, should we just create a regular SubChannel.  I made some changes in xds_cluster_impl.cc, let me know if you like it
___
*[src/core/ext/xds/xds_client.cc, line 2229 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnCXqbEUHxZT57uksI:-MtppqAH3u4NBTIc158S:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2229)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `server_it`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2231 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-MtnCyvt9oHArFnDH-yo:-Mtpt8IJ8T9eqEf5a4W8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L2231)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please change this to:

```
auto& load_report_map = server_it->second.load_report_map;
for (auto load_report_it = load_report_map.begin();
     load_report_it != load_report_map.end();) {
```

Then we can use `load_report_map` below instead of doing a duplicate map lookup.
</blockquote></details>

Done.
___ [...]

2022-01-20 18:40 UTC, markdroth requested changes
Just a few minor comments remaining!

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-MtsmZf15vOLkjENtUhX:b-8o7wzn)* status: all files reviewed, 10 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc, line 466 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtsiGp0A9Gc_xyRL1K8:-MtsiGp1DxL3Gx2noyHH:b-vy3kgy) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L466)):*
> ```cpp
>   if (is_initial_update) {
>     if (config_->lrs_load_reporting_server().has_value()) {
>       drop_stats_ = xds_client_->AddClusterDropStats(
> ```

If this returns null, we should log an error message similar to the one below for locality stats.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc, line 599 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtshiqECb_NwxTCgjth:-MtshiqECb_NwxTCgjti:bfaqqyp) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L599)):*
> ```cpp
>               std::move(address), args),
>           std::move(locality_stats));
>     } else {
> ```

No need for `else`, since the above `if` returns if the condition is true.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc, line 600 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-Mtshq4J3ygigelygZus:-Mtshq4J3ygigelygZut:b-joth9a) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L600)):*
> ```cpp
>           std::move(locality_stats));
>     } else {
>       gpr_log(GPR_INFO,
> ```

Let's log this at GPR_ERROR, since it's really an error situation -- the control plane is telling us to do something that isn't working, so we should be a bit loud about that.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc, line 601 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtshzEw1zLVrLKQY_D1:-MtshzEw1zLVrLKQY_D2:bfryu02) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L601)):*
> ```cpp
>     } else {
>       gpr_log(GPR_INFO,
>               "[xds_cluster_impl_lb %p] No locality stats object, unable to "
> ```

Please change the wording here to something like "Failed to get locality stats object for LRS server %s, cluster %s, EDS service name %s; load reports will not be generated (not wrapping subchannel)".
___
*[src/core/ext/xds/xds_client.cc, line 1767 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-Mtn9c5-8XUjV_5kdjE3:-MtsirCN-sGQtcVRmay7:bs6k312) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L1767)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I'll send you an email to explain this
</blockquote></details>

If the assertion no longer applies, then let's just remove it, rather than leaving it commented out.
___
*[src/core/ext/xds/xds_client.cc, line 2082 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtsjPyL1J6145rPQ7x9:-MtsjPyL1J6145rPQ7xA:b-plhbf1) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/xds/xds_client.cc#L2082)):*
> ```cpp
>     load_report_state.drop_stats = cluster_drop_stats.get();
>   }
>   auto server = xds_server_channel_map_.find(server_it->first);
> ```

This lookup is not necessary.  Instead, just say:

```
server_it->second.channel_state->MaybeStartLrsCall();
```
___
*[src/core/ext/xds/xds_client.cc, line 2147 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-Mtsjp6TBVlQtAG0Xau_:-Mtsjp6TBVlQtAG0Xaua:b-plhbf1) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/xds/xds_client.cc#L2147)):*
> ```cpp
>     locality_state.locality_stats = cluster_locality_stats.get();
>   }
>   auto server = xds_server_channel_map_.find(server_it->first);
> ```

This lookup is not necessary.  Instead, just say:

```
server_it->second.channel_state->MaybeStartLrsCall();
```
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2879 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtslipW6zTMpyxobZyL:-MtslipW6zTMpyxobZyM:bfj5zil) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/test/cpp/end2end/xds/xds_end2end_test.cc#L2879)):*
> ```cpp
> }
> 
> class XdsFederationLrsTest : public XdsEnd2endTest {
> ```

Please call this `XdsFederationLoadReportingTest`.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2879 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-Mtslm7F2DzEBhO9QN-1:-Mtslm7F2DzEBhO9QN-2:b-k6lmvl) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/test/cpp/end2end/xds/xds_end2end_test.cc#L2879)):*
> ```cpp
> }
> 
> class XdsFederationLrsTest : public XdsEnd2endTest {
> ```

Looks like the only difference between this and `XdsFederationTest` is the client load reporting interval.  Since that won't be used in `XdsFederationTest` anyway, I suggest changing the value to 3 in that test class, and then here just saying:

```
using XdsFederationLoadReportingTest = XdsFederationTest;
```
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 13668 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtsmK5nEuV1OnlATeBl:-MtsmK5nEuV1OnlATeBm:bhsk52d) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/test/cpp/end2end/xds/xds_end2end_test.cc#L13668)):*
> ```cpp
>         TestType()
>             .set_bootstrap_source(TestType::kBootstrapFromEnvVar)
>             .set_enable_load_reporting(),
> ```

No need to run `XdsFederationTest` with load reporting enabled.


<!-- Sent from Reviewable.io -->

2022-01-20 22:14 UTC, donnadionne reviewed
thank you so much!  PTAL !

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-MttYNHC0uUKh8Dpmvw7:b-iw9sp0)* status: all files reviewed, 10 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc, line 466 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtsiGp0A9Gc_xyRL1K8:-MttHp_w8c_fvYKdz8mQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L466)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If this returns null, we should log an error message similar to the one below for locality stats.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc, line 599 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtshiqECb_NwxTCgjth:-MttFO3V2XjbfSseXcRL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L599)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `else`, since the above `if` returns if the condition is true.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc, line 600 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-Mtshq4J3ygigelygZus:-MttFPETEhKNF2z02Zkz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L600)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's log this at GPR_ERROR, since it's really an error situation -- the control plane is telling us to do something that isn't working, so we should be a bit loud about that.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc, line 601 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtshzEw1zLVrLKQY_D1:-MttHv-A4UxopinyUrFY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L601)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please change the wording here to something like "Failed to get locality stats object for LRS server %s, cluster %s, EDS service name %s; load reports will not be generated (not wrapping subchannel)".
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 1767 at r4](https://reviewable.io/reviews/grpc/grpc/28504#-Mtn9c5-8XUjV_5kdjE3:-MttIDzR7sU3vfX2Y41u:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/f821dbe5c8b1abee5f6153e6742ff69b71b2b817/src/core/ext/xds/xds_client.cc#L1767)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If the assertion no longer applies, then let's just remove it, rather than leaving it commented out.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2082 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtsjPyL1J6145rPQ7x9:-MttJ0-p6F7xPJ3mMlNX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/xds/xds_client.cc#L2082)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This lookup is not necessary.  Instead, just say:

```
server_it->second.channel_state->MaybeStartLrsCall();
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2147 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-Mtsjp6TBVlQtAG0Xau_:-MttJ1ULC7ULrGUk59qy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/src/core/ext/xds/xds_client.cc#L2147)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This lookup is not necessary.  Instead, just say:

```
server_it->second.channel_state->MaybeStartLrsCall();
```
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2879 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtslipW6zTMpyxobZyL:-MttUUx60uSJW6Wwk6-v:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/test/cpp/end2end/xds/xds_end2end_test.cc#L2879)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `XdsFederationLoadReportingTest`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2879 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-Mtslm7F2DzEBhO9QN-1:-MttYM_I5ufHPbwgMmk5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/test/cpp/end2end/xds/xds_end2end_test.cc#L2879)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like the only difference between this and `XdsFederationTest` is the client load reporting interval.  Since that won't be used in `XdsFederationTest` anyway, I suggest changing the value to 3 in that test class, and then here just saying:

```
using XdsFederationLoadReportingTest = XdsFederationTest;
```
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 13668 at r5](https://reviewable.io/reviews/grpc/grpc/28504#-MtsmK5nEuV1OnlATeBl:-MttUTxJAj7HctUa5Tse:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/eeea6df428f1d3bb6e6ab178527c0c2d860dca41/test/cpp/end2end/xds/xds_end2end_test.cc#L13668)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to run `XdsFederationTest` with load reporting enabled.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 23:50 UTC, markdroth requested changes
Just one wording nit to fix, then we're ready to go!

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-MtttXig0GDuGDaa6YAg:bmou030)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc, line 472 at r6](https://reviewable.io/reviews/grpc/grpc/28504#-Mttt5Ia1aUxpnbG48yM:-Mttt5Ia1aUxpnbG48yN:b-9tb8p9) ([raw file](https://github.com/grpc/grpc/blob/5b1fc168b23603e0e0c61f9d9fc28ffa7d09df07/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L472)):*
> ```cpp
>         gpr_log(GPR_ERROR,
>                 "[xds_cluster_impl_lb %p] Failed to get cluster drop stats for "
>                 "LRS server %s, cluster %s, EDS service name %s",
> ```

This message should explicitly say something like "load reporting for drops will not be done".


<!-- Sent from Reviewable.io -->

2022-01-20 23:57 UTC, donnadionne reviewed
thank you so much!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-Mttv7TrC246OBoVhd5J:boqbpqk)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc, line 472 at r6](https://reviewable.io/reviews/grpc/grpc/28504#-Mttt5Ia1aUxpnbG48yM:-Mttv66u4J6S1tbyeMKi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5b1fc168b23603e0e0c61f9d9fc28ffa7d09df07/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L472)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This message should explicitly say something like "load reporting for drops will not be done".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-21 17:05 UTC, markdroth approved these changes
Looks great!

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28504#-:-MtxaNLB9HO7Dgkiz396:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donnadionne)



<!-- Sent from Reviewable.io -->

2022-01-21 18:55 UTC, merged