Fix google c2p resolver shutdown
grpc/grpc pull request #28519
Opened 2022-01-10 22:42 UTC by apolcyn

Based on https://github.com/grpc/grpc/pull/28354

Fixes internal issue b/182302759

2022-01-25 23:03 UTC, markdroth requested changes
It's nice to see all the work you've done on DNS and HTTP request cancellation finally pay off!

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28519#-:-MuITUcGDXt42OFXdBP2:b77bsqo)* status: all files reviewed, 10 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 108 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIKOEr9NktXxyiif6W:-MuIHSV767h3fvmPQl6g:bbdnhgo) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L108)):*
> ```cpp
>   bool using_dns_ = false;
>   OrphanablePtr<Resolver> child_resolver_;
>   std::string metadata_server_address_ = "metadata.google.internal.";
> ```

I don't think this data member is necessary.  You're already saving the channel args, so you can just have a helper function like this to get the right value:

```
std::string GetMetadataServerName(const grpc_channel_args* args) {
  const char* server_name = grpc_channel_args_find_string(
      args, "grpc.testing.google_c2p_resolver_metadata_server_override");
  if (server_name != nullptr) return server_name;
  return "metadata.google.internal.";
}
```

Then, in the `MetadataQuery` ctor, you can get the server name like this:

```
GetMetadataServerName(resolver_->channel_args_);
```

Note, however, that if you move the instantiation of the xds resolver back to the ctor as I suggest below, then there will be no other need to store the channel args in a data member, at which point it will make sense to use a string data member here.  But in that case, I suggest renaming it to `metadata_server_name_`, since it's actually a name, not an address.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 135 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIKIVQ8nMZZjoIWcLP:-MuIKIVQ8nMZZjoIWcLQ:bha8598) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L135)):*
> ```cpp
>   request.hdr_count = 1;
>   request.hdrs = &header;
>   auto uri = URI::Create("http", "metadata.google.internal.", path,
> ```

Shouldn't this use `resolver_->metadata_server_address_` instead of hard-coding the name?  Otherwise, what's the point in having the channel arg that can override the name?

It looks like the tests are setting this channel arg and expecting that it's being used.  Why are they passing with this bug?  Is the channel arg actually needed?
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 183 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIMhJTEMP6kFCi5S4l:-MuIMhJTEMP6kFCi5S4m:bpc6gn5) ([raw file](https://github.com/grpc/grpc/blob/1cf6b085f2d43649c6d6d475b965e6cea4e4a9a0/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L183)):*
> ```cpp
> 
> //
> // GoogleCloud2ProdResolver::ZoneQuery
> ```

Please restore this block comment.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 200 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuINnMR0CmnnYhRzc3b:-MuINnMR0CmnnYhRzc3c:b-f2lnrm) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L200)):*
> ```cpp
>       zone = absl::UnknownError(
>           absl::StrCat("could not parse zone from metadata server: ", body));
>       gpr_log(GPR_ERROR, "%s", zone.status().ToString().c_str());
> ```

Suggest moving this log statement down to right before the call to `ZoneQueryDone()`, so that it can log in any of the 3 failure cases:

```
if (!zone.ok()) gpr_log(GPR_ERROR, "zone query failed: %s", zone.status.ToString().c_str());
```
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 229 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIOGISEcEKa_8CXUzC:-MuIOGISEcEKa_8CXUzD:bgushgf) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L229)):*
> ```cpp
>   absl::Status status;
>   if (error != GRPC_ERROR_NONE) {
>     status = grpc_error_to_absl_status(error);
> ```

Should probably log the error in this case.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 234 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuINO-b7AAuGphfyy6J:-MuINO-b7AAuGphfyy6K:b-3acg6e) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L234)):*
> ```cpp
>         absl::StrFormat("response status: %d", response->status));
>   } else {
>     status = absl::OkStatus();
> ```

No need for this "else" clause; the default ctor for `absl::Status` sets it to status OK.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 272 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuII0_59uwCClvpqFpC:-MuII0_59uwCClvpqFpD:bskt8t1) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L272)):*
> ```cpp
>   }
>   char* test_only_metadata_server_override =
>       const_cast<char*>(grpc_channel_args_find_string(
> ```

This `const_cast<>` doesn't appear to be needed.  We're not modifying this string, so it can just be `const`.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 326 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIJjiq5daLit05_p69:-MuIJjiq5daLit05_p6A:bkh87zq) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L326)):*
> ```cpp
>     Result result;
>     absl::Status status = absl::CancelledError(absl::StrFormat(
>         "C2P resolver shutdown, IPv6 query status: %s, zone query status: %s",
> ```

I don't think we should need to return a new result if the resolver is shutting down.  It should be fine to just return here.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 378 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIIul7D5uuSM6jRNiT:-MuIIul7D5uuSM6jRNiU:b-yajwkl) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L378)):*
> ```cpp
>   grpc_pollset_set* pollset_set = grpc_polling_entity_pollset_set(&pollent_);
>   GPR_ASSERT(pollset_set != nullptr);
>   child_resolver_ = ResolverRegistry::CreateResolver(
> ```

Why are we deferring creating the xds resolver until this point?  It seems like this requires adding a bunch of new data members, and it's not clear to me what the benefit of doing this is.

Note that instantiating the xds resolver really doesn't do anything by itself; it doesn't actually create the `XdsClient` until you call its `StartLocked()` method.  So it's not clear to me why it would be a problem to create it from the ctor, as it was prior to this PR.
___
*[test/core/client_channel/resolvers/google_c2p_resolver_test.cc, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuILfPt3rFVvK1YJpOD:-MuILfPu41DZQJvxMfHg:bk4ey47) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/test/core/client_channel/resolvers/google_c2p_resolver_test.cc#L1)):*
> ```cpp
> /*
> ```

Please use C++-style comments.


<!-- Sent from Reviewable.io -->

2022-01-26 18:36 UTC, apolcyn reviewed
Thanks! I think I've addressed comments, PTAL

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28519#-:-MuMRMuD-pcUlK2Gn3Eo:b-thrja3)* status: 5 of 6 files reviewed, 10 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 108 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIKOEr9NktXxyiif6W:-MuMRSWJ5YoXTyTIS6Rl:bjihz1v) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L108)):*
> But in that case, I suggest renaming it to metadata_server_name_, since it's actually a name, not an address.

Done - kept the data member but changed the name
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 135 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIKIVQ8nMZZjoIWcLP:-MuMRYgI960DfXMBbsKx:b-j12355) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L135)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Shouldn't this use `resolver_->metadata_server_address_` instead of hard-coding the name?  Otherwise, what's the point in having the channel arg that can override the name?

It looks like the tests are setting this channel arg and expecting that it's being used.  Why are they passing with this bug?  Is the channel arg actually needed?
</blockquote></details>

Good catch!

The test itself is mainly just meant to exercise the code paths involved in cancellation with active metadata server queries. E.g. it's mainly just trying to make sure we don't crash, leak memory, etc. Thus false negatives are possible - I don't see a great way to avoid that though.

I've fixed this though, and have verified with debug logs that the HTTP queries in the test are going to the intended fake TCP server, and that they are being cancelled while they're active, i.e. that the intended code paths are being exercised.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 183 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIMhJTEMP6kFCi5S4l:-MuMSHOm2e1-2aUrZjGj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1cf6b085f2d43649c6d6d475b965e6cea4e4a9a0/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L183)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please restore this block comment.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 200 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuINnMR0CmnnYhRzc3b:-MuMbzhU5TvZ6y8h3CzI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L200)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest moving this log statement down to right before the call to `ZoneQueryDone()`, so that it can log in any of the 3 failure cases:

```
if (!zone.ok()) gpr_log(GPR_ERROR, "zone query failed: %s", zone.status.ToString().c_str());
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 229 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIOGISEcEKa_8CXUzC:-MuMcCtpBg7jJ0yks-ON:b61gdi3) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L229)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Should probably log the error in this case.
</blockquote></details>

Logging in the non-200 status case could cause a lot of spam, because this is actually expected to happen whenever the VM doesn't have IPv6 enabled (i.e. in a common use case).
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 234 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuINO-b7AAuGphfyy6J:-MuMcdFR88uakcS2spo0:bro4qof) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L234)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this "else" clause; the default ctor for `absl::Status` sets it to status OK.
</blockquote></details>

Reverted this code back to previous state, since we're no longer propagating the status info through the result handler upon shutdown. 
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 272 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuII0_59uwCClvpqFpC:-MuMcmEOBagnVN72jsHz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L272)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This `const_cast<>` doesn't appear to be needed.  We're not modifying this string, so it can just be `const`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 326 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIJjiq5daLit05_p69:-MuMcnFADO8OLsU0pWkS:b-rz4thf) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L326)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we should need to return a new result if the resolver is shutting down.  It should be fine to just return here.
</blockquote></details>

My original idea was that this could help to propagate debug info by basically relaying relevant state about the C2P resolver when it was shutdown (e.g. metadata server query error messages might show the the C2P resolver was stuck waiting for a non-responsive metadata server). However, I'm not sure if that would actually propagate up to the error details of pending RPCs that are failed at this time, so it might be needless.

For now, I've changed the code to just return here.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 378 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIIul7D5uuSM6jRNiT:-MuMdvEaBg1wF-bFygF0:bkovr2d) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L378)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why are we deferring creating the xds resolver until this point?  It seems like this requires adding a bunch of new data members, and it's not clear to me what the benefit of doing this is.

Note that instantiating the xds resolver really doesn't do anything by itself; it doesn't actually create the `XdsClient` until you call its `StartLocked()` method.  So it's not clear to me why it would be a problem to create it from the ctor, as it was prior to this PR.
</blockquote></details>

My original reasoning was just related to my above comment about trying to provide a useful error upon shutdown - in order to do that, I needed to save the result handler for the C2P resolver (until the XDS resolver was actually started).

Again though, I'm not sure if that was actually providing value. I've reverted it back.
___
*[test/core/client_channel/resolvers/google_c2p_resolver_test.cc, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuILfPt3rFVvK1YJpOD:-MuMez0x0LJleqITVwym:b-896f [...]

2022-01-26 20:07 UTC, markdroth requested changes
This looks really good!  Just one more small thing to clean up.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28519#-:-MuN-0-XB_bs4Z5hB2b6:b-twznaa)* status: all files reviewed, 2 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 229 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIOGISEcEKa_8CXUzC:-MuMyl-j2NNj5v3YZma6:b-p9d04s) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L229)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Logging in the non-200 status case could cause a lot of spam, because this is actually expected to happen whenever the VM doesn't have IPv6 enabled (i.e. in a common use case).
</blockquote></details>

I didn't mean the non-200 case; I meant the error case.  But it looks like I missed the fact that we're already doing that above.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 326 at r1](https://reviewable.io/reviews/grpc/grpc/28519#-MuIJjiq5daLit05_p69:-MuMz1hHAMy4M0ndawJl:b-73k8vz) ([raw file](https://github.com/grpc/grpc/blob/c4a3185be66d2d8ad93b20fa1ad06d1243043142/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L326)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

My original idea was that this could help to propagate debug info by basically relaying relevant state about the C2P resolver when it was shutdown (e.g. metadata server query error messages might show the the C2P resolver was stuck waiting for a non-responsive metadata server). However, I'm not sure if that would actually propagate up to the error details of pending RPCs that are failed at this time, so it might be needless.

For now, I've changed the code to just return here.
</blockquote></details>

I don't think it would actually get used.  By the time the resolver is shutting down, the client channel is no longer going to use any result it returns anyway.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 91 at r3](https://reviewable.io/reviews/grpc/grpc/28519#-MuMzLU1AAZ1nxkQQWEc:-MuMzLU1AAZ1nxkQQWEd:b-i414hk) ([raw file](https://github.com/grpc/grpc/blob/2fa2d2e069c7cefeb5674bf42d8aecf7a02818df/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L91)):*
> ```cpp
>   };
> 
>   void ZoneQueryDone(absl::StatusOr<std::string> zone);
> ```

We probably don't need to report the status anymore, so this can go back to taking just a `std::string`.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 104 at r3](https://reviewable.io/reviews/grpc/grpc/28519#-MuMzU0q9T1egkzei6lK:-MuMzU0q9T1egkzei6lL:b-5kytsz) ([raw file](https://github.com/grpc/grpc/blob/2fa2d2e069c7cefeb5674bf42d8aecf7a02818df/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L104)):*
> ```cpp
> 
>   OrphanablePtr<ZoneQuery> zone_query_;
>   absl::optional<absl::StatusOr<std::string>> zone_;
> ```

Similarly, this no longer needs to use `StatusOr<>`.


<!-- Sent from Reviewable.io -->

2022-01-26 20:24 UTC, apolcyn reviewed
Thanks for the review! PTAL

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28519#-:-MuN2gGK4WBGUvRcJ8bs:b-6sy5wi)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 91 at r3](https://reviewable.io/reviews/grpc/grpc/28519#-MuMzLU1AAZ1nxkQQWEc:-MuN2kU82PcQrhUcEQ4Z:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fa2d2e069c7cefeb5674bf42d8aecf7a02818df/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L91)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We probably don't need to report the status anymore, so this can go back to taking just a `std::string`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc, line 104 at r3](https://reviewable.io/reviews/grpc/grpc/28519#-MuMzU0q9T1egkzei6lK:-MuN2l6MEDI-IUqY-V-6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2fa2d2e069c7cefeb5674bf42d8aecf7a02818df/src/core/ext/filters/client_channel/resolver/google_c2p/google_c2p_resolver.cc#L104)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similarly, this no longer needs to use `StatusOr<>`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 20:29 UTC, markdroth approved these changes
Looks great!

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28519#-:-MuN40SK8evT6hz6esVT:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @apolcyn)



<!-- Sent from Reviewable.io -->

2022-01-26 23:34 UTC, apolcyn commented
I'll need to debug this more.

There are a couple of issues:

1) Issue seen on [macos](https://source.cloud.google.com/results/invocations/692616eb-c408-466c-aa22-ae2172e63749/targets/%2F%2Ftest%2Fcore%2Fclient_channel%2Fresolvers:google_c2p_resolver_test/log) where we crash in [here](https://github.com/grpc/grpc/blob/d222b5e3944222125bdc2d4aa55bf21bc883eb1f/src/core/ext/xds/xds_client.cc#L591), apparently happens when the fake TCP server isn't actually hanging but instead not listening on the advertised address

2) Occasionally seeing flakes with the following crash signature:

E0126 23:26:05.869935467      25 work_serializer.cc:127]     assertion failed: GetOwners(prev_ref_pair) == 0
*** SIGABRT received at time=1643239565 on cpu 0 ***
E0126 23:26:05.870520286      91 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643239565.869354986","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0126 23:26:05.873736023      92 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643239565.873463911","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0126 23:26:05.874505909      92 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643239565.874290713","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
E0126 23:26:05.876493955      93 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643239565.876290247","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0126 23:26:05.877004550      93 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643239565.876304176","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
PC: @     0x7fac14dad438  (unknown)  raise
    @     0x7fac1baf95fe        224  absl::lts_20211102::WriteFailureInfo()
    @     0x7fac1baf8c11        576  absl::lts_20211102::AbslFailureSignalHandler()
    @     0x7fac15e02390  (unknown)  (unknown)
    @     0x7fac17db5c7e         64  grpc_core::OrphanableDelete::operator()<>()
D0126 23:26:05.880330867      26 fake_udp_and_tcp_server.cc:244] accepted peer socket: 87
D0126 23:26:05.880573595      26 fake_udp_and_tcp_server.cc:189] Fake TCP server received 0 bytes from peer socket: 71. Close the connection.
E0126 23:26:05.880968051      94 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643239565.880328142","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0126 23:26:05.881397617      94 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643239565.880341437","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
    @     0x7fac17db5325         96  std::unique_ptr<>::~unique_ptr()
    @     0x7fac17db4845         32  grpc_core::WorkSerializer::~WorkSerializer()
    @     0x7fac19273299         32  __gnu_cxx::new_allocator<>::destroy<>()
    @     0x7fac19273230         32  std::allocator_traits<>::destroy<>()
E0126 23:26:05.885853468      95 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643239565.885369140","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
    @     0x7fac19272e2c         64  std::_Sp_counted_ptr_inplace<>::_M_dispose()
E0126 23:26:05.886915515      95 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643239565.886393109","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
    @           0x4dda9d         96  std::_Sp_counted_base<>::_M_release()
    @           0x4dd9f9         32  std::__shared_count<>::~__shared_count()
E0126 23:26:05.889482198      96 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643239565.889314927","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0126 23:26:05.889697257      96 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643239565.889325261","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
D0126 23:26:05.890859561      26 fake_udp_and_tcp_server.cc:244] accepted peer socket: 90
D0126 23:26:05.891004115      26 fake_udp_and_tcp_server.cc:189] Fake TCP server received 0 bytes from peer socket: 76. Close the connection.
E0126 23:26:05.894540179      97 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643239565.894316780","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0126 23:26:05.894932073      97 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643239565.894331350","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0126 23:26:05.896475548      98 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643239565.896337631","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0126 23:26:05.897138488      98 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643239565.896859844","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
E0126 23:26:05.900506388      99 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643239565.900341920","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0126 23:26:05.900849577      99 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643239565.900352159","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
D0126 23:26:05.901366032      26 fake_udp_and_tcp_server.cc:244] accepted peer socket: 76
D0126 23:26:05.901515974      26 fake_udp_and_tcp_server.cc:189] Fake TCP server received 0 bytes from peer socket: 87. Close the connection.
E0126 23:26:05.905522184     100 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643239565.905303511","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0126 23:26:05.905874996     100 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643239565.905317306","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
    @     0x7fac1b45382e         32  std::__shared_ptr<>::~__shared_ptr()
    @     0x7fac1b453778         32  std::shared_ptr<>::~shared_ptr()
    @     0x7fac191d3018         96  grpc_core::ClientChannel::~ClientChannel()
E0126 23:26:05.908675837     101 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata serve [...]

2022-01-27 01:26 UTC, apolcyn commented
Another similar stack trace:

```
E0127 01:23:03.581901858      25 work_serializer.cc:127]     assertion failed: GetOwners(prev_ref_pair) == 0
E0127 01:23:03.581984530      33 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.581699281","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
*** SIGABRT received at time=1643246583 on cpu 0 ***
E0127 01:23:03.587690837     115 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.587612455","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.588076461     115 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.587832702","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
E0127 01:23:03.588501526      47 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.588444962","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.588767833      47 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.588537652","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
E0127 01:23:03.589105593      44 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.589039420","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.589472247      88 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.589403304","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.589546926      88 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.589417433","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.589142045      30 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.589083445","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.589851806      30 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.589091022","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
D0127 01:23:03.590061895      26 fake_udp_and_tcp_server.cc:244] accepted peer socket: 10
D0127 01:23:03.590269029      26 fake_udp_and_tcp_server.cc:189] Fake TCP server received 0 bytes from peer socket: 6. Close the connection.
E0127 01:23:03.590616922      45 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.590576078","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.590253979     109 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.590119381","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.591102627     109 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.590127143","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.590839343      45 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.590650449","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
E0127 01:23:03.591504033      43 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.591450110","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.590595403      91 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.590540166","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.592448032      43 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.592301767","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
E0127 01:23:03.592718743      91 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.592442697","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
E0127 01:23:03.589495933      44 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.589411976","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
E0127 01:23:03.593136963     122 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.593011631","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.593488036     122 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.593386163","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
E0127 01:23:03.593825318     118 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.593766778","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.593825290     114 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.593775507","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.595637198     114 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.595552122","description":"HTTP1 request cancelled during read","file":"src/core/lib/http/httpcli.cc","file_line":232}
E0127 01:23:03.593990294     111 google_c2p_resolver.cc:198] zone query failed: UNKNOWN: error fetching zone from metadata server: {"created":"@1643246583.593939634","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.596466683     111 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.593945861","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.594165550      37 google_c2p_resolver.cc:222] error fetching IPv6 address from metadata server: {"created":"@1643246583.594125490","description":"HTTP request cancelled during TCP connection establishment","file":"src/core/lib/http/httpcli.cc","file_line":192}
E0127 01:23:03.596896875     120 google_c2p_resolver.cc:222] error f [...]

2022-02-07 19:27 UTC, markdroth approved these changes
Looks great!

> Reviewed 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28519#-:-MvKduMK2mC8qlr-sciQ:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @apolcyn)



<!-- Sent from Reviewable.io -->

2022-02-07 19:31 UTC, apolcyn commented
artifact macos: https://github.com/grpc/grpc/issues/28260

C# macos issue is a tool failure

2022-02-07 19:36 UTC, merged