Initial structure for RLS
grpc/grpc pull request #28750
Opened 2022-01-30 23:52 UTC by donnadionne

2022-01-31 18:24 UTC, markdroth requested changes
This looks like a reasonable start.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MulNHUA7Mf0FDJwG2_5:bctipna)* status: all files reviewed, 19 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 2 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulAcLA8uI7G73cLumI:-MulAcLA8uI7G73cLumJ:bbli5f0) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L2)):*
> ```objc
> //
> // Copyright 2021 gRPC authors.
> ```

2022 :)
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulI_014N9t7gKsJx_E:-Mul9ajEDK2-zXpiUYMH:b6gwp60) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L41)):*
> ```objc
> class XdsClusterSpecifierPluginImpl {
>  public:
>   struct PluginConfig {
> ```

We don't need either of these structs.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulB2Kl0lL9oV1hgg0r:-MulB2Kl0lL9oV1hgg0s:bkotakc) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L73)):*
> ```objc
> 
>   // Loads the proto message into the upb symtab.
>   virtual void PopulateSymtab(upb_symtab* symtab) const = 0;
> ```

We will still need this method.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 77 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulBF9j4Autwjh6gSL3:-MulBF9kAHsbYTV4JoVQ:b2rc69t) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L77)):*
> ```objc
>   // Generates a Config from the xDS plugin config proto.
>   // Used for the top-level config in the HCM HTTP plugin list.
>   virtual absl::StatusOr<PluginConfig> GeneratePluginConfig(
> ```

We don't need any of these other methods.

We mainly need just one method here, whose signature will look like this:

```
// Generates an LB policy config in JSON form.
virtual absl::StatusOr<std::string> GenerateLoadBalancingPolicyConfig(
    upb_strview serialized_plugin_config, upb_arena* arena) const = 0;
```
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 120 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulAFvL-DaZJaIqJIgl:-MulAFvL-DaZJaIqJIgm:bnj9ql) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L120)):*
> ```objc
>   static void RegisterPlugin(
>       std::unique_ptr<XdsClusterSpecifierPluginImpl> plugin,
>       const std::set<absl::string_view>& config_proto_type_names);
> ```

Unlike the HTTP filter registry, there is no need to register the same plugin under multiple names, so we don't need a set here.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulFMCp0THmHAywldRP:-MulFMCp0THmHAywldRQ:b-yeukjg) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L122)):*
> ```objc
>       const std::set<absl::string_view>& config_proto_type_names);
> 
>   static const XdsClusterSpecifierPluginImpl* GetPluginForType(
> ```

Unlike the HTTP filter registry, where there are multiple methods that may need to be called on each plugin, here we have basically just one, `GenerateLoadBalancingPolicyConfig()`.  So instead of having the caller first call `GetPluginForType()` to get the plugin and then call `GenerateLoadBalancingPolicyConfig()` on that plugin, we should probably wrap that up into a convenient method that does both:

```
// Returns the LB policy config in JSON form.
static absl::StatusOr<std::string> GenerateLoadBalancingPolicyConfig(
    absl::string_view proto_type_name,
    upb_strview serialized_plugin_config, upb_arena* arena);
```
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 134 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulMiYj-6JfWxSTP__J:-MulMiYj-6JfWxSTP__K:bk4ey47) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L134)):*
> ```objc
> }  // namespace grpc_core
> 
> #endif /* GRPC_CORE_EXT_XDS_XDS_CLUSTER_SPECIFIER_PLUGIN_H */
> ```

Please use C++-style comments.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 2 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulAeNVArAMbDRlkYWq:-MulAeNVArAMbDRlkYWr:bbli5f0) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L2)):*
> ```cpp
> //
> // Copyright 2021 gRPC authors.
> ```

2022 :)
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 71 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulApCu01wjHs_GWz4h:-MulApCu01wjHs_GWz4i:b-ma5m53) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L71)):*
> ```cpp
> };
> 
> using PluginOwnerList = std::vector<std::unique_ptr<XdsClusterSpecifierPluginImpl>>;
> ```

Because we don't need to register the same plugin under multiple names, this can be simplified to a single map, instead of a map and a vector.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 95 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulBQNG6QZ_gVd-dGnL:-MulBQNG6QZ_gVd-dGnM:b-dernq3) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L95)):*
> ```cpp
> }
> 
> /*void XdsClusterSpecifierPluginRegistry::PopulateSymtab(upb_symtab* symtab) {
> ```

This will still be needed.
___
*[src/core/ext/xds/xds_route_config.h, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulBWdU8NuBqDDOjMGP:-MulBWdU8NuBqDDOjMGQ:b39jl0t) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_route_config.h#L48)):*
> ```objc
>       std::map<std::string, XdsHttpFilterImpl::FilterConfig>;
> 
>   using TypedPerPluginConfig =
> ```

Unlike HTTP filters, there is no `typed_per_filter_config` map for ClusterSpecifier plugins, and we don't use this same map type in multiple places, so we don't need this typedef.  We can just specify the type inline in the one place where it is used.
___
*[src/core/ext/xds/xds_route_config.h, line 74 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulCM4R-JkCIly0cDtI:-MulCM4R-JkCIly0cDtJ:b-k2k534) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_route_config.h#L74)):*
> ```objc
>   };
> 
>   // TODO(donnadionne): When we can use absl::variant<>, consider using that
> ```

I think this TODO can go away.  The `PathMatcher` and `HeaderMatcher` code has since been moved out of this file, and the `cluster` vs. `weighted_cluster` issue is already covered by a TODO below.
___
*[src/core/ext/xds/xds_route_config.h, line 137 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulC6t1BhHxlGeMIHiu:-MulC6t1BhHxlGeMIHiv:bzdrtm3) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_route_config.h#L137)):*
> ```objc
> 
>       // Action for this route.
>       // TODO(roth): When we can use absl::variant<>, consider using that
> ```

We can use `absl::variant<>` now, so this might be a good time to address this TODO.  This should allow only one of `cluster_name`, `weighted_clusters`, or `cluster_specifier_plugin_name` to be specified.
___
*[src/core/ext/xds/xds_route_config.h, line 148 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulJ1TH9nSeLOAy6NsY:-Mul [...]

2022-02-08 04:50 UTC, donnadionne reviewed
Hi

I still have a few todos and a question about the absl::Variant, but I am ready for you to take another look at what I have done.  Thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MvMebdUDECuotI3eOex:b-9qiju1)* status: 0 of 20 files reviewed, 19 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 2 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulAcLA8uI7G73cLumI:-MutJy2u5_snAEmqp-kQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L2)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

2022 :)
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulI_014N9t7gKsJx_E:-MutJyvMBQboL6y0H4om:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L41)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We don't need either of these structs.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 73 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulB2Kl0lL9oV1hgg0r:-MvM5QXJBbBefpsUdyzD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L73)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We will still need this method.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 77 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulBF9j4Autwjh6gSL3:-MutKZhM6GS2KJoKl3Tj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L77)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We don't need any of these other methods.

We mainly need just one method here, whose signature will look like this:

```
// Generates an LB policy config in JSON form.
virtual absl::StatusOr<std::string> GenerateLoadBalancingPolicyConfig(
    upb_strview serialized_plugin_config, upb_arena* arena) const = 0;
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 120 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulAFvL-DaZJaIqJIgl:-MutKXmB24dylPSZOA2m:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L120)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Unlike the HTTP filter registry, there is no need to register the same plugin under multiple names, so we don't need a set here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulFMCp0THmHAywldRP:-MutKXBw4bNPeMX1DzTJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L122)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Unlike the HTTP filter registry, where there are multiple methods that may need to be called on each plugin, here we have basically just one, `GenerateLoadBalancingPolicyConfig()`.  So instead of having the caller first call `GetPluginForType()` to get the plugin and then call `GenerateLoadBalancingPolicyConfig()` on that plugin, we should probably wrap that up into a convenient method that does both:

```
// Returns the LB policy config in JSON form.
static absl::StatusOr<std::string> GenerateLoadBalancingPolicyConfig(
    absl::string_view proto_type_name,
    upb_strview serialized_plugin_config, upb_arena* arena);
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 134 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulMiYj-6JfWxSTP__J:-MvGehspDKbyTN0-sfPY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L134)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style comments.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 2 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulAeNVArAMbDRlkYWq:-MutKlxK91fM0OmTyWAM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L2)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

2022 :)
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 71 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulApCu01wjHs_GWz4h:-MvM5Ro_4GAHVr7GiCHs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L71)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Because we don't need to register the same plugin under multiple names, this can be simplified to a single map, instead of a map and a vector.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 95 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulBQNG6QZ_gVd-dGnL:-MvM5Sdz9bNnTojpDTHY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L95)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This will still be needed.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.h, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulBWdU8NuBqDDOjMGP:-MutOKQb6Aj_eILy9xwZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_route_config.h#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Unlike HTTP filters, there is no `typed_per_filter_config` map for ClusterSpecifier plugins, and we don't use this same map type in multiple places, so we don't need this typedef.  We can just specify the type inline in the one place where it is used.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.h, line 74 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulCM4R-JkCIly0cDtI:-MvM7GOb-_lrPF9qDn6F:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_route_config.h#L74)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this TODO can go away.  The `PathMatcher` and `HeaderMatcher` code has since been moved out of this file, and the `cluster` vs. `weighted_cluster` issue is already covered by a TODO below.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.h, line 137 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulC6t1BhHxlGeMIHiu:-MvM7-Pm1vMccp3Mafp6:b-2xx86g) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_route_config.h#L137)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We can use `absl::variant<>` now, so this might be a good time to address this TODO.  This should allow only one of `cluster_name`, `weighted_clusters`, or `cluster_specifier_plugin_name` to be specified.
</blockquote></details>

sounds good, just a question, both cluster_name and cluster_specifier_plugin_name ar [...]

2022-02-08 20:22 UTC, markdroth requested changes
This is moving in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MvPzwqJ2o-9QJ-oSc4L:b-k1b92a)* status: all files reviewed, 27 unresolved discussions (waiting on @donnadionne)

___
*[BUILD, line 2897 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPJ9cq0zUBncKCdmc_:-MvPJ9cq0zUBncKCdmca:be1v23a) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/BUILD#L2897)):*
> ```Starlark
>         "protobuf_wrappers_upb",
>         "ref_counted_ptr",
>         "rls_upb",
> ```

I don't think this dependency is needed.  The xDS code doesn't use the RLS RPC API itself, just the RLS config.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 418 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPtGz7-BoOyd9y6waI:-MvPtGz7-BoOyd9y6waJ:b-s515du) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L418)):*
> ```cpp
>                 .http_max_stream_duration;
>       }
>       if (route_action->weighted_clusters.empty()) {
> ```

Suggest restructuring this so that all three of the alternatives are specified at the top level:

```
if (!route_action->cluster_name.empty()) {
  // ...handle cluster_name...
} else if (!route_action->weighted_clusters.empty()) {
  // ...handle weighted_clusters...
} else {
  // ...handle cluster_specifier_plugin...
}
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 622 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPwGHC9_Eum-a0OTjl:-MvPwGHC9_Eum-a0OTjm:b-t6vhy3) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L622)):*
> ```cpp
>   std::string cluster_name;
>   RefCountedPtr<ServiceConfig> method_config;
>   if (route_action->weighted_clusters.empty()) {
> ```

Same here: Suggest restructuring this so that all three of the alternatives are specified at the top level.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 924 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPw_J84WnTpNPha7E5:-MvPw_J84WnTpNPha7E6:b3xkoto) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L924)):*
> ```cpp
>   std::vector<std::string> clusters;
>   for (const auto& cluster : cluster_state_map_) {
>     std::vector<absl::string_view> cluster_elements =
> ```

This can be done without any allocations:

```
absl::string_view child_name = cluster.first;
if (absl::ConsumePrefix(&child_name, "cluster_specifier_plugin:")) {
  // ...handle plugin case...
} else {
  absl::ConsumePrefix(&child_name, "cluster:");
  // ...handle cluster case...
}
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 930 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPxEmgE_Ze6y2JBJxM:-MvPxEmgE_Ze6y2JBJxN:bz36mvz) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L930)):*
> ```cpp
>       clusters.push_back(absl::StrFormat(
>           "      \"%s\":{\n"
>           "        \"childPolicy\":[ {\n"
> ```

The entire value of the `childPolicy` field should be returned by `XdsRouteLookupClusterSpecifierPlugin::GenerateLoadBalancingPolicyConfig()` rather than being hard-coded here.  If in the future we have some other cluster specifier plugin, we will want to use a different LB policy for that, so it needs to be something that the plugin controls.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 937 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPylD-4Cyd8m2D7oB-:-MvPylD-4Cyd8m2D7oB0:b8gr54e) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L937)):*
> ```cpp
>           "             \"cds_experimental\": {}}\n"
>           "           ],\n"
>           "           \"childPolicyConfigTargetFieldName\": \"%s\"\n"
> ```

The value of this field should be "cluster" (a literal string), not the plugin name.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 120 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulAFvL-DaZJaIqJIgl:-MvPp-Fp766_Qih4-TNP:b-xpbzex) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L120)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change.  The parameter should be changed from `std::set<absl::string_view>` to just `absl::string_view`.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulFMCp0THmHAywldRP:-MvPp8h1Bs43amHOoV-P:b-clw2i3) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L122)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change either.  Please replace the `GetPluginForType()` method with the one I suggested above.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 44 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPopEyAYGG790IX3Ss:-MvPopEyAYGG790IX3St:b-u3jzan) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.h#L44)):*
> ```objc
> 
>   // Returns the LB policy config in JSON form.
>   virtual absl::StatusOr<std::string> GenerateLoadBalancingPolicyConfig(
> ```

Please move this below the `PopulateSymtab()` method, since that's the order they will be called in.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 53 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPowPh9XJoIEmEZfxf:-MvPowPh9XJoIEmEZfxg:bkkydac) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.h#L53)):*
> ```objc
> class XdsRouteLookupClusterSpecifierPlugin
>     : public XdsClusterSpecifierPluginImpl {
>   // Overrides the PopulateSymtab method
> ```

This comment is not necessary.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 35 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPpamLCLpNzn6pJNI-:-MvPpamLCLpNzn6pJNI0:b7nis0c) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L35)):*
> ```cpp
>     "grpc.lookup.v1.RouteLookupClusterSpecifier";
> 
> namespace {
> ```

Please move this block down to line 176, since this is part of the registry, not the RLS plugin.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 52 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPsAsm8D-n_vcybrnV:-MvPsAsm8D-n_vcybrnW:b-unu9qy) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L52)):*
> ```cpp
> XdsRouteLookupClusterSpecifierPlugin::GenerateLoadBalancingPolicyConfig(
>     upb_strview serialized_plugin_config, upb_arena* arena) const {
>   const auto* plugin_config = grpc_lookup_v1_RouteLookupConfig_parse(
> ```

This actually needs to parse the `RouteLookupClusterSpecifier` message, not the `RouteLookupConfig` message.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 57 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPrRDb7eaS50h0pcMb:-MvPrRDc0v5OCQ6Uot1X:b-jwpvwk) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L57)):*
> ```cpp [...]

2022-02-25 08:20 UTC, donnadionne reviewed
Fixed according to comments.  Working on tests in parallel now to test this out, but would be great if you could take a look to to make sure there isn't anything major that needs changing.  Thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MwjxdfG1Zhm6q7V7BYu:b-73dx21)* status: 2 of 20 files reviewed, 27 unresolved discussions (waiting on @markdroth)

___
*[BUILD, line 2897 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPJ9cq0zUBncKCdmc_:-MvwZwWsCOeVbXdliFbV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/BUILD#L2897)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this dependency is needed.  The xDS code doesn't use the RLS RPC API itself, just the RLS config.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 418 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPtGz7-BoOyd9y6waI:-MvqsAdO6pZ9TPOQJzRn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L418)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest restructuring this so that all three of the alternatives are specified at the top level:

```
if (!route_action->cluster_name.empty()) {
  // ...handle cluster_name...
} else if (!route_action->weighted_clusters.empty()) {
  // ...handle weighted_clusters...
} else {
  // ...handle cluster_specifier_plugin...
}
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 622 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPwGHC9_Eum-a0OTjl:-MvqsBC08CEjgHpLeuOe:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L622)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here: Suggest restructuring this so that all three of the alternatives are specified at the top level.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 924 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPw_J84WnTpNPha7E5:-Mvw9h090GqLJkZ-e5Vl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L924)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be done without any allocations:

```
absl::string_view child_name = cluster.first;
if (absl::ConsumePrefix(&child_name, "cluster_specifier_plugin:")) {
  // ...handle plugin case...
} else {
  absl::ConsumePrefix(&child_name, "cluster:");
  // ...handle cluster case...
}
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 930 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPxEmgE_Ze6y2JBJxM:-Mw-InU77RRKIokwRbSI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L930)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The entire value of the `childPolicy` field should be returned by `XdsRouteLookupClusterSpecifierPlugin::GenerateLoadBalancingPolicyConfig()` rather than being hard-coded here.  If in the future we have some other cluster specifier plugin, we will want to use a different LB policy for that, so it needs to be something that the plugin controls.
</blockquote></details>

Done.



_Code quote:_
```cpp
childPolicyConfigTargetFieldName
```
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 937 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPylD-4Cyd8m2D7oB-:-Mvr1edI1w5iEYqxpiMp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L937)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The value of this field should be "cluster" (a literal string), not the plugin name.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 120 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulAFvL-DaZJaIqJIgl:-MvwNXUNA0jwWBi2btEC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L120)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.  The parameter should be changed from `std::set<absl::string_view>` to just `absl::string_view`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 122 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulFMCp0THmHAywldRP:-MvwNYPg6opyW_RyoFPd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_cluster_specifier_plugin.h#L122)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change either.  Please replace the `GetPluginForType()` method with the one I suggested above.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 44 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPopEyAYGG790IX3Ss:-Mvr245BB4xAFK1iIShv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.h#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this below the `PopulateSymtab()` method, since that's the order they will be called in.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 53 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPowPh9XJoIEmEZfxf:-Mvr2EVHERbzhlEUYgXr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.h#L53)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment is not necessary.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 35 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPpamLCLpNzn6pJNI-:-MvwQhc5--BzKg6Hlasl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this block down to line 176, since this is part of the registry, not the RLS plugin.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 52 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPsAsm8D-n_vcybrnV:-MvzpQ4ZBBLQv5AAqip5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This actually needs to parse the `RouteLookupClusterSpecifier` message, not the `RouteLookupConfig` message.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 57 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPrRDb7eaS50h0pcMb:-MwjxZOL8kI751rfV1R2:bjeixv5) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As an [...]

2022-02-25 16:37 UTC, markdroth requested changes
This looks really good!  Comments are mostly cosmetic at this point, not structural.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 18 files at r3, 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-Mwljboi0S_sbhGOCls4:b-bs2en7)* status: all files reviewed, 19 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 274 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwlhG2fEXw2CGJsjxlz:-MwlhG2fEXw2CGJsjxm-:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L274)):*
> ```cpp
>         uint32_t range_end;
>         absl::string_view cluster;
>         // std::string cluster;
> ```

Please remove.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 436 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwlhoSt5Vp316Qw2hJo:-MwlhoSt5Vp316Qw2hJp:bp77gdr) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L436)):*
> ```cpp
>         uint32_t end = 0;
>         for (const auto& weighted_cluster : action_weighted_clusters) {
>           gpr_log(GPR_INFO, "donna new name is %s",
> ```

Please remove before merging.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 674 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwliYT38GqWdrNAc6k7:-MwliYT38GqWdrNAc6k8:bp77gdr) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L674)):*
> ```cpp
>         absl::StrCat("cluster:", entry.weighted_cluster_state[index].cluster);
>     method_config = entry.weighted_cluster_state[index].method_config;
>     gpr_log(GPR_INFO, "donna cluster name is %s", cluster_name.c_str());
> ```

Please remove before merging.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 955 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwliwqE8JbisA8w2Mea:-MwliwqE8JbisA8w2Meb:bu82e27) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L955)):*
> ```cpp
>       clusters.push_back(absl::StrFormat(
>           "      \"%s\":{\n"
>           "        \"childPolicy\": \"%s\"\n"
> ```

I don't think we want the quotes around the `%s` here.  The actual returned string will be a JSON array, not a simple string.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 44 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPopEyAYGG790IX3Ss:-MwlfdRG7FBuUh35Rj5o:behgwxy) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.h#L44)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change here.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 53 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPowPh9XJoIEmEZfxf:-MwlffeQ03HcEnqfsfuU:behgwxy) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.h#L53)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change here.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 35 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPpamLCLpNzn6pJNI-:-Mwlg-6k8_4YuKD0B11S:bm3vpf) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L35)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you moved the wrong thing here.  I was not saying to move the definition of `kXdsRouteLookupClusterSpecifierPluginConfigName` down; that's actually part of the `XdsRouteLookupClusterSpecifierPlugin` impl.  What I was saying was to move down this anonymous namespace block containing the global registry map, since that's part of the registry.

In other words, let's put all the code related to the RLS plugin first, then all of the code related to the registry.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 179 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-Mwlgb3T8Yjw7mkc7aZd:-Mwlgb3T8Yjw7mkc7aZe:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L179)):*
> ```cpp
>   // Construct the config
>   Json::Object rls_policy;
>   rls_policy["routeLookupConfig"] = result;
> ```

`std::move()`
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 183 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwlggHHCiJ5y8dUgZrL:-MwlggHHCiJ5y8dUgZrM:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L183)):*
> ```cpp
>   cds_policy["cds_experimental"] = Json();
>   Json::Array child_policy;
>   child_policy.emplace_back(cds_policy);
> ```

`std::move()`
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 184 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwlgjhO72-n3_5Ey5tp:-MwlgjhO72-n3_5Ey5tq:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L184)):*
> ```cpp
>   Json::Array child_policy;
>   child_policy.emplace_back(cds_policy);
>   rls_policy["childPolicy"] = child_policy;
> ```

`std::move()`
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 187 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwlglRwAW7tKI0OBYjB:-MwlglRwAW7tKI0OBYjC:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L187)):*
> ```cpp
>   rls_policy["childPolicyConfigTargetFieldName"] = "cluster";
>   Json::Object policy;
>   policy["rls_experimental"] = rls_policy;
> ```

`std::move()`
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 189 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-Mwlgm_M56LqUxBUjGPY:-Mwlgm_M56LqUxBUjGPZ:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L189)):*
> ```cpp
>   policy["rls_experimental"] = rls_policy;
>   Json::Array policies;
>   policies.emplace_back(policy);
> ```

`std::move()`
___
*[src/core/ext/xds/xds_route_config.h, line 137 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulC6t1BhHxlGeMIHiu:-MwlbKw20cOavl78H6-h:b-pkbx8j) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_route_config.h#L137)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can remove the TODO now.
___
*[src/core/ext/xds/xds_route_config.cc, line 233 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-Mwlbqp89U9gKMqfzDuE:-Mwlbqp89U9gKMqfzDuF:bfm1jk) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_route_config.cc#L233)):*
> ```cpp
>   } else if (action.index() == kWeightedClustersIndex) {
>     auto& action_weighted_clusters = absl::get<
>         XdsRouteConfigResource::Route::RouteAction::kWeightedClustersIndex>(
> ```

No need for `XdsRouteConfigResource::Route::RouteAction::` prefix here, since this code is a member of that struct.
___
*[src/core/ext/xds/xds_route_config.cc, line 339 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwldOol1iZBkrGrw0Ty:-MwldOol1iZBkrGrw0Tz:b-gyumuu) ([raw file](https://github.com/grpc/grpc/blob/5 [...]

2022-03-10 00:39 UTC, donnadionne reviewed
fixed all code review comments

Added tests (separated out rls_server)

PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MxlFxke2oPDziFgwqAB:b54spe2)* status: 0 of 40 files reviewed, 19 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 274 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwlhG2fEXw2CGJsjxlz:-Mx2yHHNAdfdZCQ5Nxkw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L274)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 436 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwlhoSt5Vp316Qw2hJo:-Mx3LWsL21PaO7LkdOCs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L436)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove before merging.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 674 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwliYT38GqWdrNAc6k7:-Mx3LXQTB6-O18oo4DoK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L674)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove before merging.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 955 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwliwqE8JbisA8w2Mea:-Mx2ye0v77-ofDp0JYfh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L955)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we want the quotes around the `%s` here.  The actual returned string will be a JSON array, not a simple string.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 44 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPopEyAYGG790IX3Ss:-Mx2yrJBAMSZ2pCOedH9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.h#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see a change here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 53 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPowPh9XJoIEmEZfxf:-Mx2yvjH0kOk1B3zcnDj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.h#L53)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see a change here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 35 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPpamLCLpNzn6pJNI-:-Mx31ozo9cLaZrDGl-qa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you moved the wrong thing here.  I was not saying to move the definition of `kXdsRouteLookupClusterSpecifierPluginConfigName` down; that's actually part of the `XdsRouteLookupClusterSpecifierPlugin` impl.  What I was saying was to move down this anonymous namespace block containing the global registry map, since that's part of the registry.

In other words, let's put all the code related to the RLS plugin first, then all of the code related to the registry.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 179 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-Mwlgb3T8Yjw7mkc7aZd:-Mx32JQM-tXbUEAnXFVd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L179)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 183 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwlggHHCiJ5y8dUgZrL:-Mx32Jn_7U8mIh2G5yvG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L183)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 184 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwlgjhO72-n3_5Ey5tp:-Mx32K7O5opPketsEVev:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L184)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 187 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwlglRwAW7tKI0OBYjB:-Mx32KU_4eq6R3D5whpY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L187)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 189 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-Mwlgm_M56LqUxBUjGPY:-Mx32KpyBQ1nNCOIepGp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L189)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.h, line 137 at r1](https://reviewable.io/reviews/grpc/grpc/28750#-MulC6t1BhHxlGeMIHiu:-Mx37tuH871zysiCv9OS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9191f5597689400010c4eb5976cc3b8b52789c4c/src/core/ext/xds/xds_route_config.h#L137)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can remove the TODO now.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 233 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-Mwlbqp89U9gKMqfzDuE:-Mx33mn1EeRjmGROr87z:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_route_config.cc#L233)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `XdsRouteConfigResource::Route::RouteAction::` prefix here, since this code is a member of that struct.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 339 at r4](https://reviewable.io/reviews/grpc/grpc/28750#-MwldOol1iZBkrGrw0Ty:-Mx3LYGcDOB1SJ9fCV8q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/52574405dd97ba1c1a018123eda629b1417b0a8b/src/core/ext/xds/xds_route_config.cc#L339)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

(Doesn't look like you addressed this comment from the previous round.  Repeating it here instead of pinging the original thread, since the code has moved.)

Instead of writing this code again, I suggest reusin [...]

2022-03-10 20:11 UTC, markdroth requested changes
This is moving along nicely!

Please let me know if you have any questions.  Thanks!

> Reviewed 40 of 40 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MxpSANy5u2dW5PN5NLg:bjfgowy)* status: all files reviewed, 42 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/rls/rls.cc, line 2533 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-Mxovgvm06c24AQDCYA6:-MxovgvnCl-KC7IRDo3Q:b-68dmdx) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/filters/client_channel/lb_policy/rls/rls.cc#L2533)):*
> ```cpp
> };
> 
> bool RlsEnabled() {
> ```

If we're not checking the env var anymore, then we don't need this function anymore.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 57 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPrRDb7eaS50h0pcMb:-Mxp072CEqB0hUvuOdHo:bv7vlpl) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L57)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i have missed fixing this one, i'll look into this...
</blockquote></details>

Have you looked into using upb to dump the proto to a JSON string?  I think it may wind up being much simpler, especially in light of my comments below about using the existing LB policy config-parsing code instead of replicating that validation here.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 108 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-Mxp0V8x5KnMt3eoQK9V:-Mxp0V8x5KnMt3eoQK9W:by1j1jd) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L108)):*
> ```cpp
>       }
>       header_result["names"] = std::move(header_names_result);
>       if (grpc_lookup_v1_NameMatcher_required_match(headers[k])) {
> ```

I don't think we should check for validation errors here.  Instead, we should leverage the existing config-parsing code in the RLS LB policy.  See my comment below about validating that the resulting config actually parses properly.

As it happens, it looks like this particular check is missing in the RLS LB policy config-parsing code.  Please add it in `ParseJsonHeaders()` instead of adding it here:

https://github.com/grpc/grpc/blob/24dfe21cad83292b2544131a2c8d2cb0fe423962/src/core/ext/filters/client_channel/lb_policy/rls/rls.cc#L2106

Please also add a test for this case in rls_lb_config_parser_test.cc.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 185 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-Mxp0l-o8InSOE-6GP_n:-Mxp0l-o8InSOE-6GP_o:bp77gdr) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L185)):*
> ```cpp
>   Json::Array policies;
>   policies.emplace_back(std::move(policy));
>   gpr_log(GPR_INFO, "donna rls policy dump %s", Json(policies).Dump().c_str());
> ```

Please remove before merging.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 219 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxpNh1nDTBi1etIZ8_g:-MxpNh1nDTBi1etIZ8_h:b-ka689x) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L219)):*
> ```cpp
>         "Unable to locate the cluster specifier plugin in the registry");
>   }
>   return it->second->GenerateLoadBalancingPolicyConfig(serialized_plugin_config,
> ```

We should use the existing LB policy config-parsing code to validate that the config returned by the plugin actually parses.  I think the code here should be something like this:

```
auto lb_policy_config =
    it->second->GenerateLoadBalancingPolicyConfig(serialized_plugin_config, arena);
if (!lb_policy_config.ok()) return lb_policy_config.status();
grpc_error parse_error = GRPC_ERROR_NONE;
LoadBalancingPolicyRegistry::ParseLoadBalancingConfig(*lb_policy_config, &parse_error);
if (parse_error != GRPC_ERROR_NONE) {
  absl::Status status = absl::InvalidArgumentError(
      absl::StrCat(proto_type_name, " ClusterSpecifierPlugin returned invalid LB policy config: ",
                   grpc_error_std_string(parse_error)));
  GRPC_ERROR_UNREF(parse_error);
  return status;
}
return lb_policy_config->Dump();
```

Note that the above code assumes that you change the `XdsClusterSpecifierPluginImpl::GenerateLoadBalancingPolicyConfig()` API to return `absl::StatusOr<Json>` instead of `absl::StatusOr<std::string>`, which would be fine.  But depending on whether or not we can use the upb code to dump the proto to JSON and how that changes the code in `XdsRouteLookupClusterSpecifierPlugin`, it may make sense to leave the return value as it is now and just re-parse the JSON string to a `Json` object here.  We should go with whichever approach winds up having less re-parsing to do here.
___
*[src/core/ext/xds/xds_listener.h, line 216 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-Mxp-1z8DuKIIx8YgeU0:-Mxp-1z96w2V5H1iNOxG:bmy69ba) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_listener.h#L216)):*
> ```objc
>         symtab);
>     XdsHttpFilterRegistry::PopulateSymtab(symtab);
>     XdsClusterSpecifierPluginRegistry::PopulateSymtab(symtab);
> ```

This should be in xds_route_config.h, not here.  The ClusterSpecifierPlugin is used by the RouteConfiguration, not by the Listener.
___
*[src/core/ext/xds/xds_route_config.cc, line 40 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxpJgur8HZqPGTtgMOe:-MxpJgur8HZqPGTtgMOf:b-c1z01i) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_route_config.cc#L40)):*
> ```cpp
> #include "upb/upb.h"
> #include "upb/upb.hpp"
> #include "xds/type/v3/typed_struct.upb.h"
> ```

This include should not be needed here anymore.
___
*[src/core/ext/xds/xds_route_config.cc, line 51 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxpJlCuDo4Vmj4NUEBm:-MxpJlCuDo4Vmj4NUEBn:bjorrij) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_route_config.cc#L51)):*
> ```cpp
> #include "src/core/lib/gpr/string.h"
> #include "src/core/lib/iomgr/error.h"
> #include "src/proto/grpc/lookup/v1/rls_config.upb.h"
> ```

This include should not be needed here.
___
*[src/core/ext/xds/xds_route_config.cc, line 345 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxoyruTCFoKYf1zeYNZ:-MxoyruTCFoKYf1zeYN_:bj25m0h) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_route_config.cc#L345)):*
> ```cpp
>         XdsClusterSpecifierPluginRegistry::GenerateLoadBalancingPolicyConfig(
>             plugin_type, google_protobuf_Any_value(any), context.arena);
>     if (lb_policy_config.ok()) {
> ```

Let's put the error case first, so that we don't need extra braces for the non-error case:

```
if (!lb_policy_config.ok()) {
  // ...error case...
}
// ...okay case...
```
___
*[src/core/ext/xds/xds_route_config.cc, line 349 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-Mxoz1dG7DNA0hwuL3Cp:-Mxoz1dG7DNA0hwuL3Cq:b-w1c7m9) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_route_config.cc#L349)):*
> ```cpp
>           std::move(lb_policy_config.value());
>     } else {
>       return GRPC_ERROR_CREATE_FROM_COPIED_STRING(
> ```

This should just use `absl_status_to_grpc_error()`.
___
*[src/core/ext/xds/xds_route_config.cc, line 770 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxozU7n2KpEgFxy4nLd:-MxozU7n2KpEgFxy4nLe:b36yc7r) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_route_config.cc#L770)):*
> ```cpp
>     }
>     route->action =
>         std::vector<XdsRouteConfigResou [...]

2022-03-17 01:04 UTC, donnadionne reviewed
Fixed according to code review.  PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MyKOonF3zbjCH9Lcthj:b-fb5bcg)* status: 13 of 41 files reviewed, 42 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/rls/rls.cc, line 2533 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-Mxovgvm06c24AQDCYA6:-My9Hi5E4UqVJR6-YMGc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/filters/client_channel/lb_policy/rls/rls.cc#L2533)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're not checking the env var anymore, then we don't need this function anymore.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 57 at r2](https://reviewable.io/reviews/grpc/grpc/28750#-MvPrRDb7eaS50h0pcMb:-MyEJAGIA7ydjLOUo3XQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/e2fc2dfd20454f29b5332b6df4da971bc195b735/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Have you looked into using upb to dump the proto to a JSON string?  I think it may wind up being much simpler, especially in light of my comments below about using the existing LB policy config-parsing code instead of replicating that validation here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 108 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-Mxp0V8x5KnMt3eoQK9V:-MyEJFkE3uj1E3v5gQj8:b-x3vkmo) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L108)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we should check for validation errors here.  Instead, we should leverage the existing config-parsing code in the RLS LB policy.  See my comment below about validating that the resulting config actually parses properly.

As it happens, it looks like this particular check is missing in the RLS LB policy config-parsing code.  Please add it in `ParseJsonHeaders()` instead of adding it here:

https://github.com/grpc/grpc/blob/24dfe21cad83292b2544131a2c8d2cb0fe423962/src/core/ext/filters/client_channel/lb_policy/rls/rls.cc#L2106

Please also add a test for this case in rls_lb_config_parser_test.cc.
</blockquote></details>

this check is there and now my test pass getting the expected error
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 185 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-Mxp0l-o8InSOE-6GP_n:-MyEJO3tAtbJwK9iAC7a:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L185)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove before merging.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 219 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxpNh1nDTBi1etIZ8_g:-MyEJQntCpKtRcfl-d9b:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L219)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should use the existing LB policy config-parsing code to validate that the config returned by the plugin actually parses.  I think the code here should be something like this:

```
auto lb_policy_config =
    it->second->GenerateLoadBalancingPolicyConfig(serialized_plugin_config, arena);
if (!lb_policy_config.ok()) return lb_policy_config.status();
grpc_error parse_error = GRPC_ERROR_NONE;
LoadBalancingPolicyRegistry::ParseLoadBalancingConfig(*lb_policy_config, &parse_error);
if (parse_error != GRPC_ERROR_NONE) {
  absl::Status status = absl::InvalidArgumentError(
      absl::StrCat(proto_type_name, " ClusterSpecifierPlugin returned invalid LB policy config: ",
                   grpc_error_std_string(parse_error)));
  GRPC_ERROR_UNREF(parse_error);
  return status;
}
return lb_policy_config->Dump();
```

Note that the above code assumes that you change the `XdsClusterSpecifierPluginImpl::GenerateLoadBalancingPolicyConfig()` API to return `absl::StatusOr<Json>` instead of `absl::StatusOr<std::string>`, which would be fine.  But depending on whether or not we can use the upb code to dump the proto to JSON and how that changes the code in `XdsRouteLookupClusterSpecifierPlugin`, it may make sense to leave the return value as it is now and just re-parse the JSON string to a `Json` object here.  We should go with whichever approach winds up having less re-parsing to do here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 40 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxpJgur8HZqPGTtgMOe:-MyEXPHo6VYlMdrWUE4b:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_route_config.cc#L40)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This include should not be needed here anymore.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 51 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxpJlCuDo4Vmj4NUEBm:-MyEXPlnC8Qs6Ez2yEiF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_route_config.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This include should not be needed here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 345 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxoyruTCFoKYf1zeYNZ:-MyEZJLWDEvB8Ao64QJI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_route_config.cc#L345)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's put the error case first, so that we don't need extra braces for the non-error case:

```
if (!lb_policy_config.ok()) {
  // ...error case...
}
// ...okay case...
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 349 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-Mxoz1dG7DNA0hwuL3Cp:-MyEakKi9qV_QMxiZ-4L:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_route_config.cc#L349)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should just use `absl_status_to_grpc_error()`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 770 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxozU7n2KpEgFxy4nLd:-MyEakl3CR04dwSp4eer:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/core/ext/xds/xds_route_config.cc#L770)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need to construct a new vector here.  I think this can just be `route->action = std::move(action_weighted_clusters);`.
</blockquote></details>

Done.
___
*[src/proto/grpc/testing/xds/v3/BUILD, line 193 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxoxMmsDj8MWVMC6NNq:-MyJ7T5y1da8PSo5uEEL:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/src/proto/grpc/testing/xds/v3/BUILD#L193)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned elsewhere, this proto file already exists in the right place, so we don't need it here.  This BUILD rule is not needed.
</blockquote></details>

Done.
___
*[test/core/client_channel/rls_lb_config_parser_test.cc, line 39 at [...]

2022-03-17 03:59 UTC, donnadionne reviewed
made a few new changes to fix build/sanity errors

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MyL0uCi3wSRzXYFD7zM:by8361i)* status: 13 of 41 files reviewed, 42 unresolved discussions (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2022-03-17 05:25 UTC, donnadionne reviewed
another small fix for upb encoding

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MyLKSgg5_jkEvtsFKX1:b-j56x3z)* status: 13 of 41 files reviewed, 42 unresolved discussions (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2022-03-17 22:42 UTC, markdroth requested changes
This is looking really good!  The only substantive comment is the one about the NACK case that we need to add.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 20 files at r6, 32 of 32 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MyP1qEq1EYbQs2h75L2:b-4o1ehn)* status: all files reviewed, 14 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 61 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOoZca1TBlc6NxYuMX:-MyOoZca1TBlc6NxYuMY:b-k4n8eq) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L61)):*
> ```cpp
>   const upb_MessageDef* msg_type =
>       grpc_lookup_v1_RouteLookupConfig_getmsgdef(symtab);
>   size_t json_size = upb_JsonEncode(plugin_config, msg_type, symtab, 0, nullptr,
> ```

I think we need to check whether this call succeeds somehow.

@haberman, can you advise as to the right way to do that?  The upb header file isn't all that clear on how to detect an error:

https://github.com/protocolbuffers/upb/blob/e80ac6df59589976d17c884a3e0a108560e24cbe/upb/json_encode.h#L46

I see the following upb test code that's checking for the return value being -1:

https://github.com/protocolbuffers/upb/blob/e80ac6df59589976d17c884a3e0a108560e24cbe/upb/conformance_upb.c#L172

Assuming the test code is right, then it seems like we should do something like this here:

```
if (json_size == reinterpret_cast<size_t>(-1)) {
  return absl::InvalidArgumentError(absl::StrCat(
      "failed to dump proto to JSON: ", upb_Status_ErrorMessage(status.ptr())));
}
```

Is that right?
___
*[src/core/lib/json/json_util.h, line 48 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOsoqlDT2ldA4W2rBu:-MyOsoqlDT2ldA4W2rBv:b9mokf4) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/src/core/lib/json/json_util.h#L48)):*
> ```objc
>                        std::vector<grpc_error_handle>* error_list) {
>   static_assert(std::is_integral<NumericType>::value, "Integral required");
>   if (!(json.type() == Json::Type::NUMBER ||
> ```

This would be easier to read if written as:

```
if (json.type() != Json::Type::NUMBER &&
    json.type() != Json::Type::STRING) {
```
___
*[test/core/client_channel/rls_lb_config_parser_test.cc, line 261 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOtb9E5x_WfercJBSI:-MyOtb9E5x_WfercJBSJ:b4r6hc0) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/core/client_channel/rls_lb_config_parser_test.cc#L261)):*
> ```cpp
>                   "field:maxAge error:type should be STRING.*"
>                   "field:staleAge error:type should be STRING.*"
>                   "field:cacheSizeBytes error:failed to parse.*"
> ```

Shouldn't this be "type should be NUMBER or STRING"?
___
*[test/core/ext/filters/rbac/rbac_service_config_parser_test.cc, line 413 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOtfuT-ZwVPOfOsU6j:-MyOtfuT-ZwVPOfOsU6k:b4r6hc0) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/core/ext/filters/rbac/rbac_service_config_parser_test.cc#L413)):*
> ```cpp
>           "field:destinationIp error:type should be OBJECT.*"
>           "permissions\\[6\\]" CHILD_ERROR_TAG
>           "field:destinationPort error:failed to parse.*"
> ```

Shouldn't this be "type should be NUMBER or STRING"?
___
*[test/core/xds/google_mesh_ca_certificate_provider_factory_test.cc, line 248 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOtHRP1dOi0Tcz0Wyw:-MyOtHRP1dOi0Tcz0Wyx:b4r6hc0) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/core/xds/google_mesh_ca_certificate_provider_factory_test.cc#L248)):*
> ```cpp
>           "given by google.proto.Duration..*"
>           "field:key_type error:type should be STRING.*"
>           "field:key_size error:failed to parse.*"
> ```

Shouldn't this be "type should be NUMBER or STRING"?
___
*[test/cpp/end2end/rls_server.h, line 30 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOu-xPBJCgva0if-K1:-MyOu-xPBJCgva0if-K2:b2l07px) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/cpp/end2end/rls_server.h#L30)):*
> ```objc
>     CountedService<grpc::lookup::v1::RouteLookupService::Service>;
> 
> using ContextProcessingFunc = std::function<void(grpc::ServerContext*)>;
> ```

This can be inside of `RlsServiceImpl`.
___
*[test/cpp/end2end/rls_server.h, line 35 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOu2Sq9mTm4wufrz1K:-MyOu2Sq9mTm4wufrz1L:baipslh) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/cpp/end2end/rls_server.h#L35)):*
> ```objc
>  public:
>   explicit RlsServiceImpl(
>       absl::optional<ContextProcessingFunc> context_proc = absl::nullopt)
> ```

I don't think this needs to use `absl::optional<>`.  I believe you can pass in nullptr for a `std::function<>` parameter, and you can check whether it's null with `context_proc_ != nullptr`.
___
*[test/cpp/end2end/rls_server.h, line 36 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOuC3eAWsIU98G1T7q:-MyOuC3eAWsIU98G1T7r:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/cpp/end2end/rls_server.h#L36)):*
> ```objc
>   explicit RlsServiceImpl(
>       absl::optional<ContextProcessingFunc> context_proc = absl::nullopt)
>       : context_proc_(context_proc) {}
> ```

`std::move()`
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7608 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxpGTdTChBHM2pdTBHf:-MyP0fmV-iqrTzgwp-Jw:b-avmlnv) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/test/cpp/end2end/xds/xds_end2end_test.cc#L7608)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

ok, we will leave this as nack for now?
</blockquote></details>

Eric and Doug and I talked this through.  This test (a route referring to an undefined plugin instance) is fine as-is, but there's another case we need to add handling for, which is the case where the cluster specifier plugin proto message does not correspond to any known cluster specifier plugin -- i.e., the message type packed into the `Any` field is something other than `grpc.lookup.v1.RouteLookupClusterSpecifier`.

Doug is working on adding a new `is_optional` field to `ClusterSpecifierPlugin` in envoyproxy/envoy#20301.  Once that goes in, the behavior we want in this case is that if `is_optional` is true, then we ignore that plugin and ignore any routes that refer to that plugin.  However, if `is_optional` is false, then we want to NACK.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7506 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOwU9f354DzIqBWhId:-MyOwU9f354DzIqBWhIe:b-14mofe) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/cpp/end2end/xds/xds_end2end_test.cc#L7506)):*
> ```cpp
>   };
> 
>  protected:
> ```

Please move this up to the top of the class (above `RlsServerThread`).
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7626 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOznBUC25Ala7rab4h:-MyOznBUC25Ala7rab4i:bqulrbn) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/cpp/end2end/xds/xds_end2end_test.cc#L7626)):*
> ```cpp
> }
> 
> TEST_P(RlsTest, XdsRoutingClusterSpecifierPluginNacksRequiredMatch) {
> ```

Please insert `Rls` before `ClusterSpecifierPlugin`, since this field is specific to the RLS plugin, not relevant to any other plugins that may come in the future.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7700 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyP0CCaCfBAb4Xvjbqu:-MyP0CCaCfBAb4Xvjbqv:bdxjrp7) ([raw file](https://github.com/grpc/grpc/blob/79 [...]

2022-03-18 07:33 UTC, donnadionne reviewed
Fixing according to comments.  added json_encode return value check and and added to do for the required_match case.  PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MyQwQ871flyqPuRCOZ5:b-h9lye2)* status: 30 of 44 files reviewed, 14 unresolved discussions (waiting on @haberman and @markdroth)

___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 61 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOoZca1TBlc6NxYuMX:-MyQl1ki4fW9SBsfKUd3:brgqbns) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L61)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we need to check whether this call succeeds somehow.

@haberman, can you advise as to the right way to do that?  The upb header file isn't all that clear on how to detect an error:

https://github.com/protocolbuffers/upb/blob/e80ac6df59589976d17c884a3e0a108560e24cbe/upb/json_encode.h#L46

I see the following upb test code that's checking for the return value being -1:

https://github.com/protocolbuffers/upb/blob/e80ac6df59589976d17c884a3e0a108560e24cbe/upb/conformance_upb.c#L172

Assuming the test code is right, then it seems like we should do something like this here:

```
if (json_size == reinterpret_cast<size_t>(-1)) {
  return absl::InvalidArgumentError(absl::StrCat(
      "failed to dump proto to JSON: ", upb_Status_ErrorMessage(status.ptr())));
}
```

Is that right?
</blockquote></details>

added the check using static_cast
___
*[src/core/lib/json/json_util.h, line 48 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOsoqlDT2ldA4W2rBu:-MyQl2Sz6hx3T-O42SGu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/src/core/lib/json/json_util.h#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This would be easier to read if written as:

```
if (json.type() != Json::Type::NUMBER &&
    json.type() != Json::Type::STRING) {
```
</blockquote></details>

Done.
___
*[test/core/client_channel/rls_lb_config_parser_test.cc, line 261 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOtb9E5x_WfercJBSI:-MyQl5r3AKWI-YY6JhoI:b-d01327) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/core/client_channel/rls_lb_config_parser_test.cc#L261)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Shouldn't this be "type should be NUMBER or STRING"?
</blockquote></details>

there are 2 checks in the  json_util: 1. check for type STRING or NUMBER, and 2. try to convert string to number. 
we are now failing the 2nd check not the first.   If we were to test to make the 1st check fail i would have to use json object or json array, which I think is not as likely as a bad input as a string that cannot be converted.  So for this reason I think the slight change is ok?
___
*[test/core/ext/filters/rbac/rbac_service_config_parser_test.cc, line 413 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOtfuT-ZwVPOfOsU6j:-MyQgSBp4V02iD3N0Tt9:bssxq8r) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/core/ext/filters/rbac/rbac_service_config_parser_test.cc#L413)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Shouldn't this be "type should be NUMBER or STRING"?
</blockquote></details>

there are 2 checks in the  json_util: 1. check for type STRING or NUMBER, and 2. try to convert string to number. 
 we are now failing the 2nd check not the first.   If we were to test to make the 1st check fail i would have to use json object or json array, which I think is not as likely as a bad input as a string that cannot be converted.  So for this reason I think the slight change is ok?
___
*[test/core/xds/google_mesh_ca_certificate_provider_factory_test.cc, line 248 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOtHRP1dOi0Tcz0Wyw:-MyQhoeXDUnjIm2puBtH:bdmpl8r) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/core/xds/google_mesh_ca_certificate_provider_factory_test.cc#L248)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Shouldn't this be "type should be NUMBER or STRING"?
</blockquote></details>

 there are 2 checks in the  json_util: 1. check for type STRING or NUMBER, and 2. try to convert string to number. 
we are now failing the 2nd check not the first.   If we were to test to make the 1st check fail i would have to use json object or json array, which I think is not as likely as a bad input as a string that cannot be converted.  So for this reason I think the slight change is ok?
___
*[test/cpp/end2end/rls_server.h, line 30 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOu-xPBJCgva0if-K1:-MyQlA0p01c0ysOLcW2c:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/cpp/end2end/rls_server.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be inside of `RlsServiceImpl`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/rls_server.h, line 35 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOu2Sq9mTm4wufrz1K:-MyQlAhK7QLCgvK70IYz:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/cpp/end2end/rls_server.h#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this needs to use `absl::optional<>`.  I believe you can pass in nullptr for a `std::function<>` parameter, and you can check whether it's null with `context_proc_ != nullptr`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/rls_server.h, line 36 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOuC3eAWsIU98G1T7q:-MyQlB3IADT5hJ1tf2Jh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/cpp/end2end/rls_server.h#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7608 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxpGTdTChBHM2pdTBHf:-MyQuTAU88h-EYbeelDu:b-etneg8) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/test/cpp/end2end/xds/xds_end2end_test.cc#L7608)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Eric and Doug and I talked this through.  This test (a route referring to an undefined plugin instance) is fine as-is, but there's another case we need to add handling for, which is the case where the cluster specifier plugin proto message does not correspond to any known cluster specifier plugin -- i.e., the message type packed into the `Any` field is something other than `grpc.lookup.v1.RouteLookupClusterSpecifier`.

Doug is working on adding a new `is_optional` field to `ClusterSpecifierPlugin` in envoyproxy/envoy#20301.  Once that goes in, the behavior we want in this case is that if `is_optional` is true, then we ignore that plugin and ignore any routes that refer to that plugin.  However, if `is_optional` is false, then we want to NACK.
</blockquote></details>

sure!  did you want me to wait?  or i added a todo for now
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7506 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOwU9f354DzIqBWhId:-MyQlTFk0xeineaH5RDB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/cpp/end2end/xds/xds_end2end_test.cc#L7506)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this up to the top of the class (above `RlsServerThread`).
</blockquote></details>

Done.
___
*[test/ [...]

2022-03-18 12:41 UTC, haberman commented
> @haberman, can you advise as to the right way to do that? The upb header file isn't all that clear on how to detect an error:

You are correct, the encoder returns `-1` on failure. This should definitely be better documented and we should have a named constant for this at least.

2022-03-18 17:51 UTC, markdroth requested changes
This looks really good!  Just one more test needed, and moving a TODO to that new test.

Please let me know if you have any questions.  Thanks!

> Reviewed 18 of 18 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MyT8pRc-Aoq8Bca1Zgn:bsxr7mj)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne)

___
*[test/core/client_channel/rls_lb_config_parser_test.cc, line 261 at r7](https://reviewable.io/reviews/grpc/grpc/28750#-MyOtb9E5x_WfercJBSI:-MyT7W9REBhwPDx4cj0p:btj4kym) ([raw file](https://github.com/grpc/grpc/blob/7991f541f2162cdfd838d89d9de18f0938c8e51f/test/core/client_channel/rls_lb_config_parser_test.cc#L261)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

there are 2 checks in the  json_util: 1. check for type STRING or NUMBER, and 2. try to convert string to number. 
we are now failing the 2nd check not the first.   If we were to test to make the 1st check fail i would have to use json object or json array, which I think is not as likely as a bad input as a string that cannot be converted.  So for this reason I think the slight change is ok?

</blockquote></details>

Ah, okay -- you're right, this makes sense.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7608 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxpGTdTChBHM2pdTBHf:-MyT7pBZBONFOoDnwnms:b-wu5sml) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/test/cpp/end2end/xds/xds_end2end_test.cc#L7608)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

sure!  did you want me to wait?  or i added a todo for now
</blockquote></details>

Please go ahead and add a test that we NACK an unknown plugin type that does not have `is_optional` set.  We can have a TODO to add a test that we *don't* NACK and instead ignore the route when `is_optional` is set once Doug's PR is merged.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7635 at r8](https://reviewable.io/reviews/grpc/grpc/28750#-MyT8CL1ECU0TEr03LoX:-MyT8CL1ECU0TEr03LoY:b2n7mgo) ([raw file](https://github.com/grpc/grpc/blob/df8618807f7653d846ef2714ec0adfe0483503d4/test/cpp/end2end/xds/xds_end2end_test.cc#L7635)):*
> ```cpp
> 
> TEST_P(RlsTest, XdsRoutingRlsClusterSpecifierPluginNacksRequiredMatch) {
>   // TODO(donnadionne): Doug is working on adding a new is_optional field to
> ```

This TODO has nothing to do with this test.  The TODO is about the case where the plugin proto message type is not found in the registry, but this test is for the case where the plugin proto message is known but the config is invalid.


<!-- Sent from Reviewable.io -->

2022-03-18 18:59 UTC, donnadionne reviewed
added the new test (moved todo). PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MyTOXus2wwY1mPGlfgq:b-vzsn1q)* status: all files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7608 at r5](https://reviewable.io/reviews/grpc/grpc/28750#-MxpGTdTChBHM2pdTBHf:-MyTOWme5aMeyZqCdaV4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5e652e1557e653b61de5955109b58d0f8d2993b7/test/cpp/end2end/xds/xds_end2end_test.cc#L7608)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please go ahead and add a test that we NACK an unknown plugin type that does not have `is_optional` set.  We can have a TODO to add a test that we *don't* NACK and instead ignore the route when `is_optional` is set once Doug's PR is merged.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7635 at r8](https://reviewable.io/reviews/grpc/grpc/28750#-MyT8CL1ECU0TEr03LoX:-MyTHjEX7_uFvhXheYlC:b-7mmp82) ([raw file](https://github.com/grpc/grpc/blob/df8618807f7653d846ef2714ec0adfe0483503d4/test/cpp/end2end/xds/xds_end2end_test.cc#L7635)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This TODO has nothing to do with this test.  The TODO is about the case where the plugin proto message type is not found in the registry, but this test is for the case where the plugin proto message is known but the config is invalid.
</blockquote></details>

moved


<!-- Sent from Reviewable.io -->

2022-03-18 19:52 UTC, markdroth requested changes
Just a couple of minor nits, and then we can get this merged!

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MyT__Rq1uNBox93_nL4:btmnvx1)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7662 at r9](https://reviewable.io/reviews/grpc/grpc/28750#-MyT_5vdBGmWpqFfmhJd:-MyT_5vdBGmWpqFfmhJe:b-4h8y42) ([raw file](https://github.com/grpc/grpc/blob/5bce88db95aa88d5c82f0e18e2a10fef9f33a5d0/test/cpp/end2end/xds/xds_end2end_test.cc#L7662)):*
> ```cpp
>   // Prepare the RLSLookupConfig and configure all the keys; change route
>   // configurations to use cluster specifier plugin.
>   rls_server_->rls_service()->SetResponse(
> ```

No need for this, since no request is going to be sent to the RLS server in this test.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7669 at r9](https://reviewable.io/reviews/grpc/grpc/28750#-MyT_NY49lQ4QL8VLFd1:-MyT_NY49lQ4QL8VLFd2:b-xlfc8u) ([raw file](https://github.com/grpc/grpc/blob/5bce88db95aa88d5c82f0e18e2a10fef9f33a5d0/test/cpp/end2end/xds/xds_end2end_test.cc#L7669)):*
> ```cpp
>                        {kRlsConstantKey, kRlsConstantValue}}),
>       BuildRlsResponse({kNewClusterName}));
>   RouteLookupConfig route_lookup_config;
> ```

There's no need to actually populate any of the fields of this proto, since it will never be parsed.  Just the fact that it's a proto of the wrong type will be enough for this test.


<!-- Sent from Reviewable.io -->

2022-03-18 20:19 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750)* status: all files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7662 at r9](https://reviewable.io/reviews/grpc/grpc/28750#-MyT_5vdBGmWpqFfmhJd:-MyTfhB4689HYN5TmnFM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5bce88db95aa88d5c82f0e18e2a10fef9f33a5d0/test/cpp/end2end/xds/xds_end2end_test.cc#L7662)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for this, since no request is going to be sent to the RLS server in this test.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7669 at r9](https://reviewable.io/reviews/grpc/grpc/28750#-MyT_NY49lQ4QL8VLFd1:-MyTfiq38M63OOtSl1Vy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5bce88db95aa88d5c82f0e18e2a10fef9f33a5d0/test/cpp/end2end/xds/xds_end2end_test.cc#L7669)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need to actually populate any of the fields of this proto, since it will never be parsed.  Just the fact that it's a proto of the wrong type will be enough for this test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-18 21:17 UTC, markdroth approved these changes
This looks great!

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28750#-:-MyTt8F58Iewo3S2quPH:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donnadionne)



<!-- Sent from Reviewable.io -->

2022-03-22 18:29 UTC, merged