Move TCP Connect into its own handshaker.
grpc/grpc pull request #29111
Opened 2022-03-15 23:01 UTC by anicr7

Currently the tcp connect is performed in chttp2_connector before the handshaking is triggered. For
use cases where the application wants to perform business logic before
the tcp connection, this is problematic. By moving the TCP connect into
its own handshaker and registering it by default at the beginning, this
allows applications to add a new handshaker at the beginning allowing
handshaker logic before a TCP connect.

This approach has the advantage of slightly simplifying the logic in
tcp_connect_handshaker and httpcli as tcp_connect/callback can be
removed.

As the TCP connect needs parameters like resolved_addr,
interested_parties, a new struct called connection args is created as a
member for Handshaker Args.

For server handshakers most of the arguments here are not directly
useful, other than the deadline.

@markdroth

2022-03-16 21:57 UTC, anicr7 reviewed
Thanks for the review Mark!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111#-:-MyJioPQ5hPD_bV8tQRM:b-6kxjlo)* status: all files reviewed, 24 unresolved discussions (waiting on @anicr7 and @markdroth)

___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIK8yLCJagBK22L5Gn:-MyJebPa8z-vhH0qiXM2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L1)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style comments.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 40 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIKFw_62cpOTHr2LP0:-MyJ9iwV4BKNqHVdhUgo:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L40)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think you can remove the `_handshaker` suffix, since that part is implicit in any context in which this name will appear.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIqaLX2ngWZVsmkl-3:-MyJBzyw5dm3nPQAi-vV:botn1z4) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think `args_` and `on_handshake_done_` should also be guarded by `mu_`.
</blockquote></details>

I can do this for on_handshake_done_, but I don't think it makes sense to guard args_ with mu_ as tcp_client_connect has to be called outside of the mutex anyways?
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIWJf5DT8GGB8M9DLZ:-MyJC-oV5qbaddDhYT99:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be initialized to nullptr, just to be defensive.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 54 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIWIm90zohunEJzq2h:-MyJC0qNCv0kRZBSuF4f:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be initialized to nullptr, just to be defensive.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIhoEo5ILVft0Fmnc_:-MyJFlJZ7ZOYMwT_-CeF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L65)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a TODO here that as part of migrating to EventEngine, where the API will allow us to cancel an in-progress TCP connect attempt, we should cancel it here.  (The current iomgr-based API does not support cancellation.)
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 78 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyILRAXApHFUa1tPIig:-MyJCFWT6azbX5U8uTMd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L78)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This isn't needed.  The default value for this field in `HandshakerArgs` is null, so as long as the chttp2 connector code doesn't set it before calling the handshaker, there should be no need to reset it here.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 80 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyILLxQ0BlHaL2L1xzq:-MyJCMXR1Bmxp3KyCBx4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L80)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove unnecessary blank lines within functions.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 107 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyISCEPBJYy1qpRzj6C:-MyJGORQ-bfGENBBA2vk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L107)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This isn't necessary.  If we invoke `on_handshake_done` with an error, the handshake manager will not call any subsequent handshakers anyway.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 109 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyISM-p9AQ3ZRmOrUQz:-MyJGPUH15eYnMuQqCBP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L109)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not okay to do this unref while holding the mutex, since this could be the last ref, which could cause the object to be destroyed while the mutex contained in the object is being held.

To fix this, I suggest changing the first line of the function to declare `self` as a `RefCountedPtr<>`:

```
RefCountedPtr<TcpConnectHandshaker> self(static_cast<TCPConnectHandshaker*>(arg));
```

That will ensure that the object is unreffed when this function returns (after the mutex is released), no matter whether it's a success or failure.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIVdlxAD8rLEgl1ddq:-MyJaB906xBSIg10AX7o:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L149)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We are already passing the pollset_set in here, so I don't think we need to do it again via `ConnectionArgs`.  Instead, we can just pass this into the handshaker via its ctor.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 84 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIYSwo8VmSNeGVCZuR:-MyJFKkBBpACE10_ni8i:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L84)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment should move into the TCP connection handshaker, where we call `grpc_tcp_client_connect()`.  It explains why why need to call `grpc_tcp_client_connect()` after releasing the mutex.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 90 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIrrxe4QlUzmxLCU10:-MyJGy-_63rodMk4aG1O:b-896fix) ([raw file](https:// [...]

2022-03-17 02:45 UTC, anicr7 reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111)* status: 10 of 16 files reviewed, 24 unresolved discussions (waiting on @anicr7, @apolcyn, @ctiller, and @markdroth)

___
*[src/core/lib/http/httpcli.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIjye69uyHcQfmWuKi:-MyKiCIsCPggOLC4yfnK:b7gvd3a) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/http/httpcli.cc#L194)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The current code here is attempting to distinguish between two cases:
1. We're waiting for the TCP connection to be established.
2. The TCP connection has already been established, and we're now waiting for handshakers to run.

In case 2, we shutdown the handshake manager, which will cause the handshake manager to quickly invoke its completion callback, and the HTTP request is finished from that callback.  That's the normal cancellation pattern that we generally want to use for any async operation that gets cancelled.

Unfortunately, we currently handle case 1 differently, because the current iomgr API for TCP connection establishment does not support cancellation.  So in this case, we immediately finish the HTTP request here, and we set `cancelled_` so that when the TCP connection establishment callback is invoked later, that callback looks at `cancelled_` and becomes a no-op.

Note that in the not-too-distant future, we will migrate from the current iomgr API to the new EventEngine API, which does support cancellation for TCP connection attempts.  That's what the TODO below is about.  Once we have that, we can handle case 1 the same way as we handle case 2.

However, given the current iomgr API, the behavior here is no longer quite right with this change, because now that the TCP connection establishment has moved into the handshakers, there's no longer any way to distinguish between these two cases.  Previously, `connecting_` indicated only case 1, but now it indicates both cases, which means that we're basically never going to invoke `handshake_mgr_->Shutdown()` here.

I can see two possible ways of handling this:

A. We retain the current behavior from case 1 above, and we apply that same behavior to case 2.  In this case, we should still call `handshake_mgr_->Shutdown()`, but then we can still call `Finish()` right away, since `OnHandshakeDone()` will be a no-op when it is invoked later.

B. We decide to temporarily live with the fact that cancellation may be delayed if it happens while the TCP connection attempt is in flight, since that problem will go away when we migrate to EventEngine, and it allows us to structure this code in such a way that it will not need any changes later when we migrate to EventEngine.  In this case, we would simply remove case 1 and treat everything as case 2.

My inclination is to go with option B.  @apolcyn or @ctiller, can either of you think of cases where that would be a problem?
</blockquote></details>

Mark, between the two options I like that going with (B) allows us to proceed with no changes. But it does change the behavior when compared to the state when TCP handshaker did not exist. 

We would need to change the existing tests that are specifically confirming this behavior right now. I think considering this is the behavior we want in the future, it might be cleaner to go with (A). Calling handshake_mgr_->Shutdown() on all cases is pretty straight forward and in the future, removing the logic across connecting_ might be simpler. On the other hand we might have to alter all the tests to change them back when we migrate to EventEngine. Considering that (A) seems simpler. WDYT?
___
*[src/core/lib/http/httpcli.cc, line 277 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIl6Oj17BT0J5sFEa2:-MyKYe8oAIVhcrC2fDVy:b9riui3) ([raw file](https://github.com/grpc/grpc/blob/674e938de53259ae43dcc2987e40afe03d5bf104/src/core/lib/http/httpcli.cc#L277)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why remove this?
</blockquote></details>

This log is now more spammy due to the reorganization. Before this would be printed only when handshake fails where as now this will be printed both when TCP connect fails as well as when the handshake fails.

I can add it back, but the number of times this will be printed will be pretty high.

Also, it does cause the no-logging tests to fail which it didn't before because of these extra logs. Do we want to keep this log in case the connection fails?

Alternatively, we could add some logic to figure out if the failure was after TCP connect(not sure if there is a clean way to do this) and log only then.
___
*[src/core/lib/http/httpcli.cc, line 307 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyInwzrCdGAuf7aS2S4:-MyJox5-6YB1dzrUQvkY:bxsaayh) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/http/httpcli.cc#L307)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Now that we're setting this here, at the same point where we set `handshake_mgr_`, I think we no longer need the `connecting_` data member at all.  Instead, we can just check `handshake_mgr_ != nullptr`.
</blockquote></details>

I don't think they are the same. handshake_mgr_ is not a nullptr when the handshake is done, where as connecting_ is set to false when the handshake is done. 

The current logic is to call on_done_ immediately only when the tcp connect is in progress and the request is cancelled, and to emulate this I think we need connecting_.

Let me know if I misunderstood or if you feel there is a better way to structure this logic.  


<!-- Sent from Reviewable.io -->

2022-03-18 06:14 UTC, ctiller commented
Is there a design doc somewhere describing the problem we're trying to solve? I don't feel like I get sufficient context with 'problematic', and I'm not sure that I can give good feedback without context.

2022-03-18 06:34 UTC, apolcyn reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111)* status: 10 of 16 files reviewed, 24 unresolved discussions (waiting on @anicr7, @apolcyn, @ctiller, and @markdroth)

___
*[src/core/lib/http/httpcli.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIjye69uyHcQfmWuKi:-MyQfuduDgpwvea_jDA5:b-qynopb) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/http/httpcli.cc#L194)):*
<details><summary><i>Previously, anicr7 (Anirudh Ramachandra) wrote…</i></summary><blockquote>

Mark, between the two options I like that going with (B) allows us to proceed with no changes. But it does change the behavior when compared to the state when TCP handshaker did not exist. 

We would need to change the existing tests that are specifically confirming this behavior right now. I think considering this is the behavior we want in the future, it might be cleaner to go with (A). Calling handshake_mgr_->Shutdown() on all cases is pretty straight forward and in the future, removing the logic across connecting_ might be simpler. On the other hand we might have to alter all the tests to change them back when we migrate to EventEngine. Considering that (A) seems simpler. WDYT?
</blockquote></details>

The advantage of invoking the user callback quickly is that we can free up references even if we're still waiting for TCP setup to complete, e.g. refs on client channels in the case of http requests in the google c2p resolver. Without quick cancellation, those refs may hang around until TCP connect times out.

We might be able to live with that, if it complicates things a lot to support it.

Have we considered moving this "fake TCP cancellation" logic from the HTTP1 code into the TCP handshaker, to simplify things? 


<!-- Sent from Reviewable.io -->

2022-03-18 19:23 UTC, markdroth requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111)* status: all files reviewed, 10 unresolved discussions (waiting on @anicr7 and @ctiller)

___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIqaLX2ngWZVsmkl-3:-MyTBUTU2PelDTKkMnOl:b-7sumhp) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L52)):*
<details><summary><i>Previously, anicr7 (Anirudh Ramachandra) wrote…</i></summary><blockquote>

I can do this for on_handshake_done_, but I don't think it makes sense to guard args_ with mu_ as tcp_client_connect has to be called outside of the mutex anyways?
</blockquote></details>

Actually, I take this back -- I don't think we need it even for `on_handshake_done_`.  It looks like this requires us to grab the mutex unnecessarily in `DoHandshake()`, which the handshake manager ensures won't be called more than once.

Sorry for steering you wrong here.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 80 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyILLxQ0BlHaL2L1xzq:-MyTBqs5CRYlUblTu2j8:bocb2l1) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L80)):*
<details><summary><i>Previously, anicr7 (Anirudh Ramachandra) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 35 at r2](https://reviewable.io/reviews/grpc/grpc/29111#-MyTAdpR67bUyAeX9Q8-:-MyTAdpR67bUyAeX9Q80:b-s5aqxz) ([raw file](https://github.com/grpc/grpc/blob/ab1055523232138d0318b1773da63f5d1dfc65af/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L35)):*
> ```cpp
> class TCPConnectHandshaker : public Handshaker {
>  public:
>   TCPConnectHandshaker(grpc_pollset_set* interested_parties);
> ```

Single-arg ctors need to be declared `explicit`.

https://google.github.io/styleguide/cppguide.html#Implicit_Conversions
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 120 at r2](https://reviewable.io/reviews/grpc/grpc/29111#-MyTD6CEEmkoDr2RK4-W:-MyTD6CEEmkoDr2RK4-X:bh1w4w3) ([raw file](https://github.com/grpc/grpc/blob/ab1055523232138d0318b1773da63f5d1dfc65af/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L120)):*
> ```cpp
>       return;
>     }
> ```

Please remove blank line.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 83 at r2](https://reviewable.io/reviews/grpc/grpc/29111#-MyTDKIPBZ2bl6NQ_h9F:-MyTDKIPBZ2bl6NQ_h9G:b-gdv234) ([raw file](https://github.com/grpc/grpc/blob/ab1055523232138d0318b1773da63f5d1dfc65af/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L83)):*
> ```cpp
>     memcpy(&connect_args_.address, args.address, sizeof(grpc_resolved_address));
>   }
> ```

Please remove blank lines within functions.
___
*[src/core/lib/channel/handshaker.h, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIXG7K0kIK4gIpB8fP:-MyTE3SeEAa6tWMEiP6z:b-8qiyrn) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/channel/handshaker.h#L42)):*
<details><summary><i>Previously, anicr7 (Anirudh Ramachandra) wrote…</i></summary><blockquote>

We also need the deadline itself, currently the deadline is only used to create the timer but we need to pass this in through to the tcp connect handshaker. Does it make sense to pass in the deadline through HandshakeArgs if we don't want to have a separate struct.
</blockquote></details>

It's fine to make it part of `HandshakerArgs`, with a TODO saying that it should be removed from that struct once we migrate to EventEngine.
___
*[src/core/lib/channel/handshaker.h, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyILVy68ttuPPbaEzzy:-MyTD_K81CA_HTzepfcv:bpxe8g9) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/channel/handshaker.h#L48)):*
<details><summary><i>Previously, anicr7 (Anirudh Ramachandra) wrote…</i></summary><blockquote>

We would still need to pass the deadline through to the TCP Connect handshaker. Would it make sense to create a separate channel arg for it or does it make sense to re-use this and pass it in as part of the Handshake Args?
</blockquote></details>

As mentioned above, it's fine to make it part of `HandshakerArgs`, with a TODO saying that it should be removed from that struct once we migrate to EventEngine.
___
*[src/core/lib/http/httpcli.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIjye69uyHcQfmWuKi:-MyTESCp6NQjmK2h0cfT:bozquu) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/http/httpcli.cc#L194)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

The advantage of invoking the user callback quickly is that we can free up references even if we're still waiting for TCP setup to complete, e.g. refs on client channels in the case of http requests in the google c2p resolver. Without quick cancellation, those refs may hang around until TCP connect times out.

We might be able to live with that, if it complicates things a lot to support it.

Have we considered moving this "fake TCP cancellation" logic from the HTTP1 code into the TCP handshaker, to simplify things? 
</blockquote></details>

I like Alex's idea of moving this into the TCP connection handshaker, if we can make that work.  That handshaker can basically fake its own cancellation, which will solve the problem for both the chttp2 connector code and for the httpcli code.  And it will put all of the fake-cancellation code into one place, where it will be easier to remove when we migrate to EventEngine.

Note that today, the httpcli code does fake the cancellation of the TCP connection attempt, but the chttp2 connector code does not.  So putting this behavior in the TCP connection handshaker will retain the httpcli behavior but change the behavior for the chttp2 connector.  I want to make sure that this isn't going to cause any problems.

One possible concern here is polling.  Once the subchannel is destroyed, its fds will no longer be linked to those of the channel, so do we have any guarantee that we will continue to poll the still-pending TCP connection attempt?  If not, it might never complete.

In principle, this is probably already a problem for the httpcli code, but it probably doesn't actually get triggered very often, since there are only a few places where we use the httpcli code today (e.g., oauth tokens), and the odds of a TCP connection attempt being in progress at the same moment when a channel is destroyed seem fairly low.  But if we have the chttp2 connector code do this, then this could happen whenever there is a subchannel in the middle of trying to connect when it is destroyed, which seems like something that could happen more often.

I'd like input from @ctiller on this.  But if he doesn't object, my inclination is to try it and see what breaks.

Another possible alternative is to change the iomgr API to allow cancellation of TCP connection attempts.  But I'm not sure how hard that would be to do, and it may be more work than we really want to do on iomgr at this point.
___
*[src/core/lib/http/httpcli.cc, line 277 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIl6Oj17BT0J5sFEa2:-MyTSXss7Dmra8lmpmO9:bsa3pyx) ([raw file](https://github.com/grpc/grpc/blob/674e938de53259ae43dcc2987e40afe03d5bf104/src/core/lib/http/httpcli.cc#L277)):*
<details><summary><i>Previously, anicr7 (Anirudh Ramachandra) wrote…</i></summary><blockquote>

This log is now more spammy due to the reorganization. Before this would be printed only when handshake fails where as now this will be printed both when TCP connect [...]

2022-03-25 16:31 UTC, anicr7 reviewed
Currently the application has no way to trigger custom logic before the TCP connect. By moving the TCP connect into its own handshaker, it allows us to just modify the order of handshakers to trigger the custom code either before or after the tcp connect.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111#-:-Mz0uO6h9kkCrfNHZH_6:bju0a1c)* status: 7 of 16 files reviewed, 10 unresolved discussions (waiting on @apolcyn, @ctiller, and @markdroth)

___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 52 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIqaLX2ngWZVsmkl-3:-Myrdd0C5TAKVRsPcH9K:b-821mxm) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Actually, I take this back -- I don't think we need it even for `on_handshake_done_`.  It looks like this requires us to grab the mutex unnecessarily in `DoHandshake()`, which the handshake manager ensures won't be called more than once.

Sorry for steering you wrong here.
</blockquote></details>

No issues! Removed the mutex from on_handshake_done_.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 80 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyILLxQ0BlHaL2L1xzq:-MyrdvNjChWC03Z6FDQ8:b-q64l0g) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L80)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

Sorry removed now.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 35 at r2](https://reviewable.io/reviews/grpc/grpc/29111#-MyTAdpR67bUyAeX9Q8-:-Myrh-fdEglMqaE4--FR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ab1055523232138d0318b1773da63f5d1dfc65af/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L35)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Single-arg ctors need to be declared `explicit`.

https://google.github.io/styleguide/cppguide.html#Implicit_Conversions
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 120 at r2](https://reviewable.io/reviews/grpc/grpc/29111#-MyTD6CEEmkoDr2RK4-W:-Myre5kmD0nZMwYzHK6H:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ab1055523232138d0318b1773da63f5d1dfc65af/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L120)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank line.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 83 at r2](https://reviewable.io/reviews/grpc/grpc/29111#-MyTDKIPBZ2bl6NQ_h9F:-MyreBQI6o_rxPRaKyQI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ab1055523232138d0318b1773da63f5d1dfc65af/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L83)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank lines within functions.
</blockquote></details>

Done.
___
*[src/core/lib/channel/handshaker.h, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIXG7K0kIK4gIpB8fP:-Mz0tVV9AvMucydak3NZ:b-dewkfo) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/channel/handshaker.h#L42)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's fine to make it part of `HandshakerArgs`, with a TODO saying that it should be removed from that struct once we migrate to EventEngine.
</blockquote></details>

Done, moved to HandshakerArgs with a TODO. Also moved the other args out and use channel args to send them across to the tcp handshaker.
___
*[src/core/lib/channel/handshaker.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIWwLIBxolqkadfNjd:-Mz0tl8pBxiMidSzo6vE:befwfy1) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/channel/handshaker.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like the only reason for this is that the httpcli code doesn't handle pollsets the same way that the chttp2 code does.  I'm wondering if we can eliminate the need for this by having the httpcli code do the same pollset manipulation as the chttp2 connector does, but I'm not sure how hard that is.  @apolcyn and @ctiller and I discussed some of this in #27867, so they may have thoughts on how hard that might be to do.

If we do need this, then I think it's better to pass it in via channel args rather than make it a first-class part of the handshaker API, since the only handshaker that needs it is the TCP connect handshaker.  Also, all of the pollset-related code is going to be removed in the not-too-distant future as part of the EventEngine work, so if we add it to this API, we'll just need to remove it later.
</blockquote></details>

Sounds good, removed the connect_args and used channel args to send the required info across.
___
*[src/core/lib/channel/handshaker.h, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyILVy68ttuPPbaEzzy:-MyzKRAZAg2BrHoolGVW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/channel/handshaker.h#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned above, it's fine to make it part of `HandshakerArgs`, with a TODO saying that it should be removed from that struct once we migrate to EventEngine.
</blockquote></details>

Done.
___
*[src/core/lib/http/httpcli.cc, line 307 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyInwzrCdGAuf7aS2S4:-MyrgfzO5lnU3x-LdymG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/http/httpcli.cc#L307)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Once the handshake is done, we can reset `handshake_mgr_`.  The chttp2 connector code already does that; I'm not sure why we aren't doing it here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-04 16:03 UTC, anicr7 reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111)* status: 0 of 29 files reviewed, 10 unresolved discussions (waiting on @apolcyn, @ctiller, and @markdroth)

___
*[src/core/lib/http/httpcli.cc, line 194 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIjye69uyHcQfmWuKi:-MzbPqtU2YOsevSeMytb:bdoqmbj) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/http/httpcli.cc#L194)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I like Alex's idea of moving this into the TCP connection handshaker, if we can make that work.  That handshaker can basically fake its own cancellation, which will solve the problem for both the chttp2 connector code and for the httpcli code.  And it will put all of the fake-cancellation code into one place, where it will be easier to remove when we migrate to EventEngine.

Note that today, the httpcli code does fake the cancellation of the TCP connection attempt, but the chttp2 connector code does not.  So putting this behavior in the TCP connection handshaker will retain the httpcli behavior but change the behavior for the chttp2 connector.  I want to make sure that this isn't going to cause any problems.

One possible concern here is polling.  Once the subchannel is destroyed, its fds will no longer be linked to those of the channel, so do we have any guarantee that we will continue to poll the still-pending TCP connection attempt?  If not, it might never complete.

In principle, this is probably already a problem for the httpcli code, but it probably doesn't actually get triggered very often, since there are only a few places where we use the httpcli code today (e.g., oauth tokens), and the odds of a TCP connection attempt being in progress at the same moment when a channel is destroyed seem fairly low.  But if we have the chttp2 connector code do this, then this could happen whenever there is a subchannel in the middle of trying to connect when it is destroyed, which seems like something that could happen more often.

I'd like input from @ctiller on this.  But if he doesn't object, my inclination is to try it and see what breaks.

Another possible alternative is to change the iomgr API to allow cancellation of TCP connection attempts.  But I'm not sure how hard that would be to do, and it may be more work than we really want to do on iomgr at this point.
</blockquote></details>

Move the logic into the tcp connect handshaker and removed the faking logic from the httpcli.


<!-- Sent from Reviewable.io -->

2022-04-04 18:43 UTC, markdroth requested changes
This is getting closer!

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 26 files at r5, 1 of 14 files at r6, 23 of 23 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111#-:-MzpswZi1rFt7hzPkuKH:b79zqk9)* status: all files reviewed, 14 unresolved discussions (waiting on @anicr7, @apolcyn, and @ctiller)

___
*[include/grpc/impl/codegen/grpc_types.h, line 459 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpfpYcCpU8jEHy97g5:-MzpfpYcCpU8jEHy97g6:b-ob4xgx) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/include/grpc/impl/codegen/grpc_types.h#L459)):*
> ```objc
> /** Channel argument for tcp_connect_handshaker, it indicates the address to
>  * connect to. */
> #define GRPC_ARG_TCP_HANDSHAKER_RESOLVED_ADDRESS \
> ```

These args are for internal use only, so they shouldn't be defined here.  Instead, they should be defined in tcp_connect_handshaker.h.

Also, the strings should start with `grpc.internal.`, since we have protection to ensure that args with that prefix are not passed into core from the outside.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 120 at r2](https://reviewable.io/reviews/grpc/grpc/29111#-MyTD6CEEmkoDr2RK4-W:-Mzpmc9y4q4CWkoGfr49:bocb2l1) ([raw file](https://github.com/grpc/grpc/blob/ab1055523232138d0318b1773da63f5d1dfc65af/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L120)):*
<details><summary><i>Previously, anicr7 (Anirudh Ramachandra) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 54 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpoaOr12ryejTHLLWS:-MzpoaOr12ryejTHLLWT:bb665kr) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L54)):*
> ```cpp
>   Mutex mu_;
>   bool shutdown_ ABSL_GUARDED_BY(mu_) = false;
>   bool connecting_ ABSL_GUARDED_BY(mu_) = false;
> ```

Instead of adding another bool data member, I suggest changing `Finish()` to reset `on_handshake_done_` to null, so that we can simply use `on_handshake_done_ != nullptr` instead of `connected_`.

Note that this will require once again using the mutex to guard `on_handshake_done_`.  But the main reason I suggested undoing that is that it would avoid the need to grab the mutex in `DoHandshake()`, which we now have to grab anyway to set `connected_`, so I think guarding it with the mutex does actually make sense.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 56 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-Mzphh8d7eNqOmbUvAg0:-Mzphh8d7eNqOmbUvAg1:b-14iya5) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L56)):*
> ```cpp
>   bool connecting_ ABSL_GUARDED_BY(mu_) = false;
>   // Endpoint and read buffer to destroy after a shutdown.
>   grpc_endpoint* endpoint_ = nullptr;
> ```

I don't think we need this field.  Instead, we can have `grpc_tcp_client_connect()` directly set `endpoint_to_destroy_`.  In `Connected()`, if the connection attempt succeeds, we can move it from `endpoint_to_destroy_` into `args_->endpoint` to be passed to the next handshaker.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 83 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpmUdfDAASoDMHGEvR:-MzpmUdfDAASoDMHGEvS:b-4o8q8) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L83)):*
> ```cpp
>       shutdown_ = true;
>       // If the TCP connect had ever succeded, shutdown.
>       if (args_->endpoint != nullptr) {
> ```

I don't think this can be checked here, because it's not safe to look at the endpoint being created by `grpc_tcp_client_connect()` until it invokes `Connected()`.  And we're already doing this check in `Connected()`, so I don't think it's needed here.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 107 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpkeO34YJY5IsH8SnB:-MzpkeO34YJY5IsH8SnC:b-w0lr1x) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L107)):*
> ```cpp
>   }
>   on_handshake_done_ = on_handshake_done;
>   args_ = args;
> ```

I suggest adding `GPR_ASSERT(args->endpoint == nullptr)` here, to ensure that this handshaker isn't used in a place where the endpoint has already been created.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 185 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzplSg8EbYYmDtLFUTo:-MzplSg8EbYYmDtLFUTp:bd2r005) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L185)):*
> ```cpp
> 
> void TCPConnectHandshaker::CleanupArgsForFailureLocked() {
>   endpoint_to_destroy_ = args_->endpoint;
> ```

These two lines are not needed, since we will now have the endpoint in `endpoint_to_destroy_` by default, and we won't move it from there to `args_->endpoint` unless the handshake succeeds.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 83 at r2](https://reviewable.io/reviews/grpc/grpc/29111#-MyTDKIPBZ2bl6NQ_h9F:-MzpgVRIDcJhA9NTYhCt:bocb2l1) ([raw file](https://github.com/grpc/grpc/blob/ab1055523232138d0318b1773da63f5d1dfc65af/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L83)):*
<details><summary><i>Previously, anicr7 (Anirudh Ramachandra) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 98 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzphDZp8EkgeWOQWqo4:-MzphDZp8EkgeWOQWqo5:b5nmfvz) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L98)):*
> ```cpp
> 
>   Ref().release();  // Ref held by OnHandshakeDone().
>   handshake_mgr_->DoHandshake(endpoint_, channel_args, args.deadline,
> ```

Could just pass `nullptr` for the endpoint here, since we know it's null at this point.
___
*[src/core/lib/channel/handshaker.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIWwLIBxolqkadfNjd:-MzpfNUgDTvbJCVGpV8q:bcspenk) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/channel/handshaker.h#L46)):*
<details><summary><i>Previously, anicr7 (Anirudh Ramachandra) wrote…</i></summary><blockquote>

Sounds good, removed the connect_args and used channel args to send the required info across.
</blockquote></details>

I'd still like input from @ctiller and @apolcyn as to whether we actually need to do this differently.  It would be nice if we could remove the need for the `bind_endpoint_to_pollset` bool, regardless of how it's passed through.
___
*[src/core/lib/channel/resolved_address_utils.h, line 30 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpMKXpCL7TV6JI4FtS:-MzpMKXq0g2fXF04IS6n:b-bzf818) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/lib/channel/resolved_address_utils.h#L30)):*
> ```objc
> namespace grpc_core {
> 
> // Util to encapsulate a grpc_resolved_address in a channel arg.
> ```

I don't think we should encode a `grpc_resolved_address` directly in a channel arg.  Instead, what we usually do in this case is to use `grpc_sockaddr_to_uri()` to convert the address to a URI string, which is what we encode in a string channel arg.  Then, when we use the channel arg, we use `URI::Parse()` to parse the URI string and then `grpc_parse_uri()` to convert it back to a `grpc_resolved_address`.
___
*[src/core/lib/channel/resolved_ [...]

2022-04-05 02:23 UTC, anicr7 reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111)* status: 25 of 29 files reviewed, 14 unresolved discussions (waiting on @anicr7, @apolcyn, @ctiller, and @markdroth)

___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 120 at r2](https://reviewable.io/reviews/grpc/grpc/29111#-MyTD6CEEmkoDr2RK4-W:-MzqC16s5ABXdCps9dEg:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ab1055523232138d0318b1773da63f5d1dfc65af/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L120)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 54 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpoaOr12ryejTHLLWS:-Mzq1ONp9NbMqztawGHu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L54)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of adding another bool data member, I suggest changing `Finish()` to reset `on_handshake_done_` to null, so that we can simply use `on_handshake_done_ != nullptr` instead of `connected_`.

Note that this will require once again using the mutex to guard `on_handshake_done_`.  But the main reason I suggested undoing that is that it would avoid the need to grab the mutex in `DoHandshake()`, which we now have to grab anyway to set `connected_`, so I think guarding it with the mutex does actually make sense.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 56 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-Mzphh8d7eNqOmbUvAg0:-Mzq5_DQ-Wdp9HCObTb7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need this field.  Instead, we can have `grpc_tcp_client_connect()` directly set `endpoint_to_destroy_`.  In `Connected()`, if the connection attempt succeeds, we can move it from `endpoint_to_destroy_` into `args_->endpoint` to be passed to the next handshaker.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 83 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpmUdfDAASoDMHGEvR:-MzqCCPT-ULej2CIG0Hz:b-grp2or) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L83)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this can be checked here, because it's not safe to look at the endpoint being created by `grpc_tcp_client_connect()` until it invokes `Connected()`.  And we're already doing this check in `Connected()`, so I don't think it's needed here.
</blockquote></details>

The check is being done on args_->endpoint which is not the same as the endpoint being passed to grpc_tcp_client_connect.

In any case, we don't need now that the logic uses temporary endpoint. Removed.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 107 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpkeO34YJY5IsH8SnB:-Mzq1MaJ3JxbIIPtnXmK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L107)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suggest adding `GPR_ASSERT(args->endpoint == nullptr)` here, to ensure that this handshaker isn't used in a place where the endpoint has already been created.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 185 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzplSg8EbYYmDtLFUTo:-Mzq612D1dOPyq2Mvxte:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L185)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two lines are not needed, since we will now have the endpoint in `endpoint_to_destroy_` by default, and we won't move it from there to `args_->endpoint` unless the handshake succeeds.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 83 at r2](https://reviewable.io/reviews/grpc/grpc/29111#-MyTDKIPBZ2bl6NQ_h9F:-MzqD93C0zib5ff0YFDV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ab1055523232138d0318b1773da63f5d1dfc65af/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L83)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see this change.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 98 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzphDZp8EkgeWOQWqo4:-Mzq63w665GIud8OZTnR:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L98)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Could just pass `nullptr` for the endpoint here, since we know it's null at this point.
</blockquote></details>

Done.
___
*[src/core/lib/channel/resolved_address_utils.h, line 30 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpMKXpCL7TV6JI4FtS:-Mzqtwoi6Q46QOB2BsNI:bjozfb8) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/lib/channel/resolved_address_utils.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we should encode a `grpc_resolved_address` directly in a channel arg.  Instead, what we usually do in this case is to use `grpc_sockaddr_to_uri()` to convert the address to a URI string, which is what we encode in a string channel arg.  Then, when we use the channel arg, we use `URI::Parse()` to parse the URI string and then `grpc_parse_uri()` to convert it back to a `grpc_resolved_address`.
</blockquote></details>

Mark, I did move the logic to use this but I think this creates issues for multiple test cases which use percent encoded in abstract UDS(Ex: h2_local_abstract_uds_percent_encoded_test)

After spending some time debugging this I believe one of the problems is "copy_arg". copy_arg uses gpr_strdup for copying strings. gpr_strdup internally uses strlen which does not handle embedded nulls.

In the test as we pass:

address = absl::StrFormat(
      "unix-abstract:grpc_fullstack_test.%%00.%d.%" PRId64 ".%" PRId32 ".%d",
      getpid(), now.tv_sec, now.tv_nsec, ++unique)

But through the channel args, we will only `unix-abstract:grpc_fullstack_test.` as the complete string in tcp_connect_handshaker. 

Am I missing or do we have a way to handle embedded nulls in channel arg strings? Otherwise I think the solution for now would be to pass in resolver address as is, before I made the latest changes. 
___
*[src/core/lib/channel/resolved_address_utils.h, line 31 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-Mzpf2VzEbLxvHmEtERj:-MzqtxD92VbeFYKktnJT:b-jquxov) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/lib/channel/resolved_address_utils.h#L31)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As per my comment above, I suspect this file can just go away, but if we do keep it, please change the function names to be C++-style (e.g., `MakeResolvedAddressChannelArg()`).
</blockquote></details>

This file is now gone. But depending on the comment above, it migh [...]

2022-04-08 20:16 UTC, anicr7 reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111)* status: 6 of 46 files reviewed, 7 unresolved discussions (waiting on @apolcyn, @ctiller, @drfloob, and @markdroth)

___
*[include/grpc/impl/codegen/grpc_types.h, line 459 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpfpYcCpU8jEHy97g5:-N-9k9Kl4iXWgBIbyvrK:b-aebpzb) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/include/grpc/impl/codegen/grpc_types.h#L459)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Still need to move these to tcp_connect_handshaker.h.
</blockquote></details>

Done, moved all handshaker files into lib/transport. Also moved the definition into tcp connect handshaker now that they can be easily imported from chttp2_connector and httpcli.h.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 79 at r10](https://reviewable.io/reviews/grpc/grpc/29111#-MzuDi5TE3IbYQquiA_E:-MzwXVbCCy-0OnWMmG4o:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b6ce44cc6d4ad91a9a022a5b2b5c38fcf59fbe51/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L79)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this needs to be done while holding the lock.  It can be done either before taking the lock or after releasing it.
</blockquote></details>

Done.
___
*[src/core/lib/channel/resolved_address_utils.h, line 30 at r7](https://reviewable.io/reviews/grpc/grpc/29111#-MzpMKXpCL7TV6JI4FtS:-MzwrRhf16vBS931ez_J:bmhrp30) ([raw file](https://github.com/grpc/grpc/blob/1379d5974bf9cc2e83782410671894d69e5997dc/src/core/lib/channel/resolved_address_utils.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think there should be a literal null in the string in the first place.  The `absl::StrFormat()` code you show above looks like it's percent-encoding the null, which is exactly the right thing to do in a URI string, and `gpr_strdup()` should handle that fine -- it will stop at a literal null, but it will handle the string "%00" correctly.  So I'm not sure where the string is getting cut off, but I don't think it's in the channel args copy.  This probably needs more debugging.

@drfloob may have some input here, since he did some work a while back to make sure we were handling these cases properly.
</blockquote></details>

Debugged this further and the issue was a bug in grpc_sockaddr_to_uri which wasn't preserving the encoding. Sent: https://github.com/grpc/grpc/pull/29323 to fix this.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 49 at r10](https://reviewable.io/reviews/grpc/grpc/29111#-Mzu6v9U5uq-4H9qbxLf:-MzwXAfJB1DkXu6cg3qX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b6ce44cc6d4ad91a9a022a5b2b5c38fcf59fbe51/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L49)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `FinishLocked()`, since it is now called only when holding the mutex.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 103 at r10](https://reviewable.io/reviews/grpc/grpc/29111#-Mzu7qVoDARRb7khhfYk:-MzwrP3g71B55WxQVsXk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b6ce44cc6d4ad91a9a022a5b2b5c38fcf59fbe51/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L103)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Once we've grabbed these two channel args, we should remove them from `args->args` so that they aren't retained in the resulting subchannel.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/tcp_connect_handshaker.cc, line 105 at r10](https://reviewable.io/reviews/grpc/grpc/29111#-Mzu7Ioh-5q2say3wjLP:-MzwrPOUBYUBdoRR_51L:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b6ce44cc6d4ad91a9a022a5b2b5c38fcf59fbe51/src/core/ext/filters/client_channel/tcp_connect_handshaker.cc#L105)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of asserting (both here and on the next line), let's just fail the handshake (i.e., call `on_handshake_done_` with an error).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-11 14:51 UTC, markdroth requested changes
This looks really good!  Just one noteworthy issue remaining, which is where we register the HTTP CONNECT and TCP connect handshakers.

Please let me know if you have any questions.  Thanks!

> Reviewed 38 of 40 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111#-:-N-O5j1w5AkiBMMz1WbD:bpsiuk9)* status: all files reviewed, 7 unresolved discussions (waiting on @anicr7, @apolcyn, and @ctiller)

___
*[BUILD, line 2031 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-9yAP11XVhfJp-QjR5:-N-9yAP11XVhfJp-QjR6:b-77w3kq) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/BUILD#L2031)):*
> ```Starlark
>         "src/core/lib/transport/pid_controller.cc",
>         "src/core/lib/transport/status_conversion.cc",
>         "src/core/lib/transport/tcp_connect_handshaker.cc",
> ```

Might be a good idea to also put the TCP connect handshaker in its own BUILD target.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 73 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-9z_eI3ljcp1H20cor:-N-9z_eI3ljcp1H20cos:b2k4c7i) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/src/core/ext/filters/client_channel/client_channel.cc#L73)):*
> ```cpp
> #include "src/core/lib/transport/connectivity_state.h"
> #include "src/core/lib/transport/error_utils.h"
> #include "src/core/lib/transport/http_connect_handshaker.h"
> ```

Is this include actually needed?  Doesn't look like anything in this file actually uses anything in that header, so I think it can just be removed.
___
*[src/core/ext/filters/client_channel/client_channel_plugin.cc, line 39 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-9zs2qECfWj3iO4Jp8:-N-9zs2qECfWj3iO4Jp9:by2qb1b) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/src/core/ext/filters/client_channel/client_channel_plugin.cc#L39)):*
> ```cpp
> #include "src/core/lib/config/core_configuration.h"
> #include "src/core/lib/resolver/resolver_registry.h"
> #include "src/core/lib/transport/http_connect_handshaker.h"
> ```

Since we've moved these handshakers out of the client_channel tree, it seems odd for them to be registered here.  Instead, I suggest registering them in `BuildCoreConfiguration()`:

https://github.com/grpc/grpc/blob/58de9394aacb7b47ae2cf27cd6bc5e038d1f641b/src/core/plugin_registry/grpc_plugin_registry.cc#L103
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 95 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-O4EyQ8k6ax9wp_4ho:-N-O4EyQ8k6ax9wp_4hp:bh1w4w3) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L95)):*
> ```cpp
>       HANDSHAKER_CLIENT, channel_args, args_.interested_parties,
>       handshake_mgr_.get());
> ```

Please remove blank line.
___
*[src/core/lib/transport/http_connect_handshaker.cc, line 32 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-9zSSe2O3PIWwOxNrC:-N-9zSSe2O3PIWwOxNrD:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/src/core/lib/transport/http_connect_handshaker.cc#L32)):*
> ```cpp
> #include <grpc/support/string_util.h>
> 
> // #include "src/core/ext/filters/client_channel/client_channel.h"
> ```

Please remove.
___
*[src/core/lib/transport/tcp_connect_handshaker.h, line 24 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-O4oSO8JwRXx6C0XvR:-N-O4oSO8JwRXx6C0XvS:ba9jdb6) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/src/core/lib/transport/tcp_connect_handshaker.h#L24)):*
> ```objc
> #include "src/core/lib/config/core_configuration.h"
> 
> /** Indicates the address that the tcp connect handshaker should connect to. */
> ```

Please use C++-style comments, both here and below.


<!-- Sent from Reviewable.io -->

2022-04-11 20:51 UTC, anicr7 reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111)* status: all files reviewed, 7 unresolved discussions (waiting on @apolcyn, @ctiller, and @markdroth)

___
*[BUILD, line 2031 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-9yAP11XVhfJp-QjR5:-N-PNkZc7EhxguPol4aB:bs7wumx) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/BUILD#L2031)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Might be a good idea to also put the TCP connect handshaker in its own BUILD target.
</blockquote></details>

Done. 
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 73 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-9z_eI3ljcp1H20cor:-N-OSKmv8a3gvtPqoiYx:b9hjm1l) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/src/core/ext/filters/client_channel/client_channel.cc#L73)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is this include actually needed?  Doesn't look like anything in this file actually uses anything in that header, so I think it can just be removed.
</blockquote></details>

Removed, I don't think it is needed either not sure why it was added.
___
*[src/core/ext/filters/client_channel/client_channel_plugin.cc, line 39 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-9zs2qECfWj3iO4Jp8:-N-PNqf1BPvOXRDrbIMX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/src/core/ext/filters/client_channel/client_channel_plugin.cc#L39)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since we've moved these handshakers out of the client_channel tree, it seems odd for them to be registered here.  Instead, I suggest registering them in `BuildCoreConfiguration()`:

https://github.com/grpc/grpc/blob/58de9394aacb7b47ae2cf27cd6bc5e038d1f641b/src/core/plugin_registry/grpc_plugin_registry.cc#L103
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/client/chttp2_connector.cc, line 95 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-O4EyQ8k6ax9wp_4ho:-N-ORVtz2DnEPAslfHAu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/src/core/ext/transport/chttp2/client/chttp2_connector.cc#L95)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank line.
</blockquote></details>

Done.
___
*[src/core/lib/transport/http_connect_handshaker.cc, line 32 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-9zSSe2O3PIWwOxNrC:-N-ORhBa6FNYnmai1lCQ:b-h2vltq) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/src/core/lib/transport/http_connect_handshaker.cc#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Sorry about that, was making sure I was not missing some dependency on client_channel when I was moving http_connect_handshaker. Removed now.
___
*[src/core/lib/transport/tcp_connect_handshaker.h, line 24 at r12](https://reviewable.io/reviews/grpc/grpc/29111#-N-O4oSO8JwRXx6C0XvR:-N-OS2ta16xvGW9p9Fn4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/83ce7ebe3a2a8f13377c08d6ece20c496cadb533/src/core/lib/transport/tcp_connect_handshaker.h#L24)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use C++-style comments, both here and below.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-12 16:59 UTC, markdroth requested changes
Just one remaining nit!

Please let me know if you have any questions. Thanks!

> Reviewed 10 of 10 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111#-:-N-Thf4j3MJConad5fhc:bnsmzhq)* status: all files reviewed, 1 unresolved discussion (waiting on @anicr7 and @apolcyn)

___
*[BUILD, line 2036 at r13](https://reviewable.io/reviews/grpc/grpc/29111#-N-Th6J705Lo4ImE6D6C:-N-Th6J8EUDJaATy98pJ:byslmms) ([raw file](https://github.com/grpc/grpc/blob/9fc53aa0a1635ef63deda75bc7a5ac6ecfe3f23f/BUILD#L2036)):*
> ```Starlark
>         "src/core/lib/transport/connectivity_state.cc",
>         "src/core/lib/transport/error_utils.cc",
>         "src/core/lib/transport/handshaker.cc",
> ```

Why move this back into `grpc_base`?  It seemed like a step in the right direction to have it be in its own target.
___
*[src/core/lib/channel/handshaker.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIWwLIBxolqkadfNjd:-N-ThY1-2cXnO0WwDeBG:b-fxnggi) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/channel/handshaker.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'd still like input from @ctiller and @apolcyn as to whether we actually need to do this differently.  It would be nice if we could remove the need for the `bind_endpoint_to_pollset` bool, regardless of how it's passed through.
</blockquote></details>

I'll go ahead and resolve this.  We can clean this up later, or it will just go away when we remove the pollset APIs.


<!-- Sent from Reviewable.io -->

2022-04-12 18:21 UTC, anicr7 reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29111)* status: 46 of 47 files reviewed, 1 unresolved discussion (waiting on @apolcyn and @markdroth)

___
*[BUILD, line 2036 at r13](https://reviewable.io/reviews/grpc/grpc/29111#-N-Th6J705Lo4ImE6D6C:-N-U-PM5Er-xDnkNn1AP:b-7vomy8) ([raw file](https://github.com/grpc/grpc/blob/9fc53aa0a1635ef63deda75bc7a5ac6ecfe3f23f/BUILD#L2036)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why move this back into `grpc_base`?  It seemed like a step in the right direction to have it be in its own target.
</blockquote></details>

Done, sorry about that. Forgot to push this change.
___
*[src/core/lib/channel/handshaker.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/29111#-MyIWwLIBxolqkadfNjd:-N-U-V8RC0tQJjMFxXUL:bq6e2yq) ([raw file](https://github.com/grpc/grpc/blob/9a3cda9aea14b0c69bc6b897f5a84a1382368dba/src/core/lib/channel/handshaker.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'll go ahead and resolve this.  We can clean this up later, or it will just go away when we remove the pollset APIs.
</blockquote></details>

Ack, thanks Mark.


<!-- Sent from Reviewable.io -->

2022-05-02 16:21 UTC, merged