Adding is_optional case to RLS
grpc/grpc pull request #29259
Opened 2022-03-30 06:07 UTC by donnadionne

2022-03-30 06:12 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29259)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @markdroth)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/29259#-MzOQu67AsYsN3RE7f0S:-MzOQu67AsYsN3RE7f0T:bqh1e8u) (no related file):*
I just have a small issue where "bool is_optional = 2;" is added to route.proto in envoyproxy/envoy, and we are using envoyproxy/data-plane-api, I need to figure out how to get the added proto field.

For now, I just hard coded is_optional to true to finish the code and test it out.  And I am ready for you to take a look at the code changes while I figure out how to get this new proto field.

---
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 69 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzORf5h8az4N3mpDqB0:-MzORf5h8az4N3mpDqB1:bm1a4oc) ([raw file](https://github.com/grpc/grpc/blob/44167bdfd3912a064696efc04403217d9b0e2314/src/core/ext/xds/xds_cluster_specifier_plugin.h#L69)):*
> ```objc
>   static void PopulateSymtab(upb_DefPool* symtab);
> 
>   static absl::StatusOr<std::string> GenerateLoadBalancingPolicyConfig(
> ```

This method is now broken up so that we can do a GetType for a check, and then Generate and parse.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 115 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzORo9jDqxi6QBkbnMe:-MzORo9jDqxi6QBkbnMf:bdxp9rg) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L115)):*
> ```cpp
>   auto it = g_plugin_registry->find(config_proto_type_name);
>   if (it == g_plugin_registry->end()) return nullptr;
>   return it->second.get();
> ```

returning the raw pointer like this is not ideal but it is safe as we know the unique ptr will not be freed yet.


<!-- Sent from Reviewable.io -->

2022-03-30 15:25 UTC, markdroth requested changes
This looks like a great start!

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29259#-:-MzQPcKb5aT5R3NFwJBB:b9kv8rc)* status: all files reviewed, 12 unresolved discussions (waiting on @donnadionne)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/29259#-MzOQu67AsYsN3RE7f0S:-MzQPUxX6_ovIK21GkqW:b1fknb2) (no related file):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I just have a small issue where "bool is_optional = 2;" is added to route.proto in envoyproxy/envoy, and we are using envoyproxy/data-plane-api, I need to figure out how to get the added proto field.

For now, I just hard coded is_optional to true to finish the code and test it out.  And I am ready for you to take a look at the code changes while I figure out how to get this new proto field.
</blockquote></details>

You can get the new field by upgrading the envoyproxy/data-plane-api dependency to the latest commit from that repo.

---
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 69 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzORf5h8az4N3mpDqB0:-MzQIB6X730P8LJ6rJOM:bb3sg65) ([raw file](https://github.com/grpc/grpc/blob/44167bdfd3912a064696efc04403217d9b0e2314/src/core/ext/xds/xds_cluster_specifier_plugin.h#L69)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

This method is now broken up so that we can do a GetType for a check, and then Generate and parse.
</blockquote></details>

This is fine.  It's a little sub-optimal in that if we ever have a second plugin, we should ideally not make each individual plugin repeat the code to call the gRPC LB policy registry to do the parsing of the resulting config.  But we can refactor that if/when the time comes to add a second plugin.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQNB7g1P1B43JCu__M:-MzQNB7g1P1B43JCu__N:b-114aki) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_cluster_specifier_plugin.h#L70)):*
> ```objc
>       absl::string_view config_proto_type_name);
> 
>   static void PopulateSymtab(upb_DefPool* symtab);
> ```

Please put this method before `GetPluginForType()`, since it will be called first.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 86 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQPxiD5uPjCBHAgXH8:-MzQPxiD5uPjCBHAgXH9:bkw3iby) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L86)):*
> ```cpp
>   Json::Array policies;
>   policies.emplace_back(std::move(policy));
>   Json lb_policy_config = Json(policies);
> ```

`Json lb_policy_config(std::move(policies));`
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 87 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQQ5nf8ItlrzL7bZep:-MzQQ5nf8ItlrzL7bZeq:b-4cvw3o) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L87)):*
> ```cpp
>   policies.emplace_back(std::move(policy));
>   Json lb_policy_config = Json(policies);
>   grpc_error_handle parse_error = GRPC_ERROR_NONE;
> ```

Please add a TODO here:

// TODO(roth): If/when we ever add a second plugin, refactor this code
// somehow such that we automatically validate the resulting config against
// the gRPC LB policy registry instead of requiring each plugin to do that itself.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 115 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzORo9jDqxi6QBkbnMe:-MzQHu7nAiE307XnGoIM:b7lnpz2) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L115)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

returning the raw pointer like this is not ideal but it is safe as we know the unique ptr will not be freed yet.
</blockquote></details>

This is actually fine, since the registry lifetime should exceed that of the usage here.
___
*[src/core/ext/xds/xds_route_config.h, line 182 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQLAnY3L2DZ0TQNJcQ:-MzQH9NPDeWhXC7MoDj4:bwn9nco) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_route_config.h#L182)):*
> ```objc
>            std::string /*LB policy config*/>
>       cluster_specifier_plugin_map;
>   std::set<std::string> ignored_cluster_specifier_plugin_set;
> ```

Instead of adding a separate set here, I suggest just storing these entries in `cluster_specifier_plugin_map` with an empty string as the value.  (The empty string is not a valid LB policy config, so that will not conflict with any value returned by any plugin.)

Please add a comment above the field documenting this usage.
___
*[src/core/ext/xds/xds_route_config.cc, line 311 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQHMeB8HVGPkSlgq8z:-MzQHMeB8HVGPkSlgq9-:bdh2q9v) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_route_config.cc#L311)):*
> ```cpp
>     parts.push_back(it);
>   }
>   parts.push_back("}");
> ```

Need another copy of this line above line 307 to end the previous block.

That having been said, with the change I suggested in the .h file, this should instead just log "<unknown>" if the LB policy config string is empty.
___
*[src/core/ext/xds/xds_route_config.cc, line 330 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQKJfVBxReIpmmhXq6:-MzQKJfVBxReIpmmhXq7:b-b4jzts) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_route_config.cc#L330)):*
> ```cpp
>         envoy_config_route_v3_ClusterSpecifierPlugin_extension(
>             cluster_specifier_plugin[i]);
>     std::string name = UpbStringToStdString(
> ```

I just noticed that we have a pre-existing bug from the previous PR: right after this, we should check that the name does not already exist in `rds_update->cluster_specifier_plugin_map`, and if it does, return an error.

Also, please add a test for this case.
___
*[src/core/ext/xds/xds_route_config.cc, line 348 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQNZZk5XE6UFI4LSSc:-MzQNZZlE480Ih5FgihQ:b-7ffi0p) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_route_config.cc#L348)):*
> ```cpp
>         XdsClusterSpecifierPluginRegistry::GetPluginForType(plugin_type);
>     if (cluster_specifier_plugin_impl == nullptr) {
>       if (is_optional) {
> ```

If `is_optional` is false, we need to return an error here, or else we will fall through to line 356, where we will dereference the null pointer in `cluster_specifier_plugin_impl`.

Suggest writing this as:

```
std::string lb_policy_config;
if (cluster_specifier_plugin_impl == nullptr) {
  if (!is_optional) {
    return GRPC_ERROR_CREATE_FROM_CPP_STRING(
        absl::StrCat("unknown ClusterSpecifierPlugin type ", plugin_type));
  }
  // Optional plugin, leave lb_policy_config empty.
} else {
  auto config =
      cluster_specifier_plugin_impl->GenerateLoadBalancingPolicyConfig(
          google_protobuf_Any_value(any), context.arena, context.symtab);
  if (!config.ok()) {
    return absl_status_to_grpc_error(lb_policy_config.status());
  }
  lb_policy_config = std::move(*config);
}
rds_update->cluster_specifier_plugin_map[std::move(name)] =
    std::move(lb_policy_config);
```
___
*[src/core/ext/xds/xds_route_config.cc, line 792 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQJ9fn6yrkt4tgAyCZ:-MzQJ9fn6yrkt4tgAyC_:b-186nje) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_route_config.cc#L792)):*
> ```cpp
>           "Ro [...]

2022-04-01 00:54 UTC, donnadionne reviewed
Fixed according to code review.  And the envoyproxy/data-plane-api is now updated too.  All tests pass!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29259#-:-MzXbGMt7DJT_EgkuQ4Z:bulhgpy)* status: all files reviewed, 10 unresolved discussions (waiting on @markdroth)

*[a discussion](https://reviewable.io/reviews/grpc/grpc/29259#-MzOQu67AsYsN3RE7f0S:-MzWk0ASD3biJP57AvzQ:b-896fix) (no related file):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can get the new field by upgrading the envoyproxy/data-plane-api dependency to the latest commit from that repo.
</blockquote></details>

Done.

---
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.h, line 70 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQNB7g1P1B43JCu__M:-MzWkNjS3pZu7eAoCbIb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_cluster_specifier_plugin.h#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please put this method before `GetPluginForType()`, since it will be called first.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 86 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQPxiD5uPjCBHAgXH8:-MzWlaXgCqTeS4IT8ahm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`Json lb_policy_config(std::move(policies));`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_cluster_specifier_plugin.cc, line 87 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQQ5nf8ItlrzL7bZep:-MzWlmG47Rcqvkp8KAPV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_cluster_specifier_plugin.cc#L87)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a TODO here:

// TODO(roth): If/when we ever add a second plugin, refactor this code
// somehow such that we automatically validate the resulting config against
// the gRPC LB policy registry instead of requiring each plugin to do that itself.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.h, line 182 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQLAnY3L2DZ0TQNJcQ:-MzXWIPg7I7PiluxJahB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_route_config.h#L182)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of adding a separate set here, I suggest just storing these entries in `cluster_specifier_plugin_map` with an empty string as the value.  (The empty string is not a valid LB policy config, so that will not conflict with any value returned by any plugin.)

Please add a comment above the field documenting this usage.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 311 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQHMeB8HVGPkSlgq8z:-MzXWJVQEPDV_og990im:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_route_config.cc#L311)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Need another copy of this line above line 307 to end the previous block.

That having been said, with the change I suggested in the .h file, this should instead just log "<unknown>" if the LB policy config string is empty.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 330 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQKJfVBxReIpmmhXq6:-MzX6-cl4whq0diYDz7J:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_route_config.cc#L330)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I just noticed that we have a pre-existing bug from the previous PR: right after this, we should check that the name does not already exist in `rds_update->cluster_specifier_plugin_map`, and if it does, return an error.

Also, please add a test for this case.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 348 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQNZZk5XE6UFI4LSSc:-MzX65vX4spO_SLMqMmM:b-chi4ie) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_route_config.cc#L348)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If `is_optional` is false, we need to return an error here, or else we will fall through to line 356, where we will dereference the null pointer in `cluster_specifier_plugin_impl`.

Suggest writing this as:

```
std::string lb_policy_config;
if (cluster_specifier_plugin_impl == nullptr) {
  if (!is_optional) {
    return GRPC_ERROR_CREATE_FROM_CPP_STRING(
        absl::StrCat("unknown ClusterSpecifierPlugin type ", plugin_type));
  }
  // Optional plugin, leave lb_policy_config empty.
} else {
  auto config =
      cluster_specifier_plugin_impl->GenerateLoadBalancingPolicyConfig(
          google_protobuf_Any_value(any), context.arena, context.symtab);
  if (!config.ok()) {
    return absl_status_to_grpc_error(lb_policy_config.status());
  }
  lb_policy_config = std::move(*config);
}
rds_update->cluster_specifier_plugin_map[std::move(name)] =
    std::move(lb_policy_config);
```
</blockquote></details>

one of my test discovered this bug too when I had is_optional on/off 
___
*[src/core/ext/xds/xds_route_config.cc, line 792 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQJ9fn6yrkt4tgAyCZ:-MzXTCuBDi0smz9hzvdm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/src/core/ext/xds/xds_route_config.cc#L792)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

With the change I suggested in the .h file, this can become:

```
auto it = cluster_specifier_plugin_map.find(plugin_name);
if (it == cluster_specifier_plugin_map.end()) {
  return GRPC_ERROR_CREATE_FROM_CPP_STRING(
      absl::StrCat("RouteAction cluster specifier plugin ", plugin_name, " unknown"));
}
if (it->second.empty()) *ignore_route = true;
route->action.emplace<XdsRouteConfigResource::Route::RouteAction::
                          kClusterSpecifierPluginIndex>(
    std::move(plugin_name));
```
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7866 at r1](https://reviewable.io/reviews/grpc/grpc/29259#-MzQPFld0mWmi5llMqdY:-MzXbEcg-t91SW5-4jCu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d395008eec7f8524f71e97679215f8bdd21f8fa1/test/cpp/end2end/xds/xds_end2end_test.cc#L7866)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of failing this, let's add a default route (one that does not use a ClusterSpecifierPlugin at all) after the route that points to the ClusterSpecifierPlugin.  Then we can test that the traffic goes to that route instead of failing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-01 16:13 UTC, markdroth requested changes
This looks great!  Remaining comments are all minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29259#-:-Mz_tcwHDrocopNFS_yY:b-4enycw)* status: all files reviewed, 6 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/xds/xds_route_config.h, line 179 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_p0al4ymAUS4HBlYc:-Mz_p0al4ymAUS4HBlYd:b-nbme13) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/src/core/ext/xds/xds_route_config.h#L179)):*
> ```objc
> 
>   std::vector<VirtualHost> virtual_hosts;
>   // The plugin is unsupported but optional, so it will be ignored.  We
> ```

Actually, I just realized that we don't need this comment at all, because we need the optional entries in this map internally while we're validating the resource, but these entries will be stripped off before the resource is returned by the XdsClient to the watchers.
___
*[src/core/ext/xds/xds_route_config.cc, line 306 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_pXX09NiXS4t-JPd1:-Mz_pXX09NiXS4t-JPd2:bxdust5) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/src/core/ext/xds/xds_route_config.cc#L306)):*
> ```cpp
>   for (const auto& it : cluster_specifier_plugin_map) {
>     parts.push_back(absl::StrFormat("%s={%s}\n", it.first,
>                                     it.second.empty() ? "" : it.second));
> ```

No need to special-case the empty string.  Just log the value unconditionally, even if it's empty.
___
*[src/core/ext/xds/xds_route_config.cc, line 331 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_pifnAe6ImCwm0dWJ:-Mz_pifnAe6ImCwm0dWK:bx4hpa7) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/src/core/ext/xds/xds_route_config.cc#L331)):*
> ```cpp
>     if (rds_update->cluster_specifier_plugin_map.find(name) !=
>         rds_update->cluster_specifier_plugin_map.end()) {
>       return GRPC_ERROR_CREATE_FROM_STATIC_STRING(
> ```

Please include the name of the plugin in this error message:

```
return GRPC_ERROR_FROM_CPP_STRING(
    absl::StrCat("duplicate definition of cluster_specifier_plugin ", name));
```
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7785 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_t2-Y7dcNRWGhGL7t:-Mz_t2-Y7dcNRWGhGL7u:bi25r7q) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/test/cpp/end2end/xds/xds_end2end_test.cc#L7785)):*
> ```cpp
>   const char* kNewClusterName = "new_cluster";
>   const char* kNewEdsServiceName = "new_eds_service_name";
>   // Populate new EDS resources.
> ```

No need to configure any CDS or EDS resources here, since they'll never be used.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7881 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_sFuWCDuQu-m1S__P:-Mz_sFuWCDuQu-m1S__Q:bplofie) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/test/cpp/end2end/xds/xds_end2end_test.cc#L7881)):*
> ```cpp
> 
> TEST_P(RlsTest,
>        XdsRoutingClusterSpecifierPluginNacksUnknownSpecifierProtoOptional) {
> ```

s/Nacks/Ignores/
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7921 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_sQl0-LL3STGjF7Jd:-Mz_sQl0-LL3STGjF7Je:b-75hf80) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/test/cpp/end2end/xds/xds_end2end_test.cc#L7921)):*
> ```cpp
>   // Ensure we ignore the cluster specifier plugin and send traffic according to
>   // the default route.
>   auto rpc_options = RpcOptions().set_metadata({{kRlsTestKey1, kRlsTestValue}});
> ```

There's no need to add the metadata here, since we're not giving the channel a config that would use it.


<!-- Sent from Reviewable.io -->

2022-04-01 16:53 UTC, donnadionne reviewed
addressed all comments.  PTAL, thank you !

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29259#-:-Mza2-SPDwQn2GlM_A9N:btetbjy)* status: all files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_route_config.h, line 179 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_p0al4ymAUS4HBlYc:-Mz_vG2a5BaFgIRo4jM4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/src/core/ext/xds/xds_route_config.h#L179)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Actually, I just realized that we don't need this comment at all, because we need the optional entries in this map internally while we're validating the resource, but these entries will be stripped off before the resource is returned by the XdsClient to the watchers.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 306 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_pXX09NiXS4t-JPd1:-Mz_vXsU1U5IS8pLOtmF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/src/core/ext/xds/xds_route_config.cc#L306)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to special-case the empty string.  Just log the value unconditionally, even if it's empty.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_route_config.cc, line 331 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_pifnAe6ImCwm0dWJ:-Mz_w6i2-KWwLuTWbZdD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/src/core/ext/xds/xds_route_config.cc#L331)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please include the name of the plugin in this error message:

```
return GRPC_ERROR_FROM_CPP_STRING(
    absl::StrCat("duplicate definition of cluster_specifier_plugin ", name));
```
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7785 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_t2-Y7dcNRWGhGL7t:-Mz_wP4K8umb1UsEVPV5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/test/cpp/end2end/xds/xds_end2end_test.cc#L7785)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to configure any CDS or EDS resources here, since they'll never be used.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7881 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_sFuWCDuQu-m1S__P:-Mz_wpdP5k49w1UXpZzl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/test/cpp/end2end/xds/xds_end2end_test.cc#L7881)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/Nacks/Ignores/
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7921 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_sQl0-LL3STGjF7Jd:-Mza1A0F0D9WjTwuwpoQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/test/cpp/end2end/xds/xds_end2end_test.cc#L7921)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need to add the metadata here, since we're not giving the channel a config that would use it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-01 18:15 UTC, markdroth requested changes
Just a couple of small things left.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29259#-:-MzaKhzw3QbGnCGtCFIF:bionhb7)* status: all files reviewed, 3 unresolved discussions (waiting on @donnadionne)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7785 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_t2-Y7dcNRWGhGL7t:-MzaJ9WRB2qiqsuI3hc9:b76zb2n) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/test/cpp/end2end/xds/xds_end2end_test.cc#L7785)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like you removed it in the previous test, but not this one.  That was a good change, but please remove it here too.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7881 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_sFuWCDuQu-m1S__P:-MzaJLYz4VmM0ga5hKaI:b-93b7ox) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/test/cpp/end2end/xds/xds_end2end_test.cc#L7881)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You changed the wrong test.  The previous test does NACK, but this one doesn't.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7868 at r3](https://reviewable.io/reviews/grpc/grpc/29259#-MzaKaUh-UrwGsyuhN1G:-MzaKaUh-UrwGsyuhN1H:b-2l0yoa) ([raw file](https://github.com/grpc/grpc/blob/a7eeab90fea7b16cc9d79698aace507bff0db943/test/cpp/end2end/xds/xds_end2end_test.cc#L7868)):*
> ```cpp
>        XdsRoutingClusterSpecifierPluginNacksUnknownSpecifierProtoOptional) {
>   gpr_setenv("GRPC_EXPERIMENTAL_XDS_RLS_LB", "true");
>   const char* kNewClusterName = "new_cluster";
> ```

No need to configure CDS or EDS resources in this test, either, since they won't be used.


<!-- Sent from Reviewable.io -->

2022-04-01 19:06 UTC, donnadionne reviewed
thank you so much!! PTAL thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29259#-:-MzaWKOV644Fn7ExshfJ:b-lxr6hu)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7785 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_t2-Y7dcNRWGhGL7t:-MzaQ8mxCcxeksqfX_E7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/test/cpp/end2end/xds/xds_end2end_test.cc#L7785)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like you removed it in the previous test, but not this one.  That was a good change, but please remove it here too.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7881 at r2](https://reviewable.io/reviews/grpc/grpc/29259#-Mz_sFuWCDuQu-m1S__P:-MzaQLFbA6ZO9ZAEqBbu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3e3c677ad3d7fc2b2b8d7e38d8dfa8bfbc93b23/test/cpp/end2end/xds/xds_end2end_test.cc#L7881)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You changed the wrong test.  The previous test does NACK, but this one doesn't.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 7868 at r3](https://reviewable.io/reviews/grpc/grpc/29259#-MzaKaUh-UrwGsyuhN1G:-MzaV9dY0dIC8BUydRjZ:brg1ndx) ([raw file](https://github.com/grpc/grpc/blob/a7eeab90fea7b16cc9d79698aace507bff0db943/test/cpp/end2end/xds/xds_end2end_test.cc#L7868)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to configure CDS or EDS resources in this test, either, since they won't be used.
</blockquote></details>

need 1 eds setup, removed rest


<!-- Sent from Reviewable.io -->

2022-04-01 19:33 UTC, merged