Initial skeleton for outlier detection
grpc/grpc pull request #29343
Opened 2022-04-07 09:18 UTC by donnadionne

Inserted Outlier Detection in between Priority and xds_cluster_impl and all priority tests still work as before

2022-04-07 09:20 UTC, donnadionne reviewed
Just wanted to make sure the new policy is inserted in the right spot, I will work on parsing and executing the policy.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N-2Jf7Z2d1tZ_tenVj_:b-ajv8gk)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @markdroth)



<!-- Sent from Reviewable.io -->

2022-04-07 15:51 UTC, markdroth requested changes
It looks like you've created this skeleton by using the priority policy as a model.  However, unlike the priority policy, the outlier_detection policy will only ever have a single child policy, so there's a lot of machinery and a layer of indirection here that we don't need.  You might be better off starting over and using the xds_cluster_impl policy as a model, since that's a good example of a policy with only one child that simply passes the child policy config down from its own config.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N-3aq9AA2uolSv13HjT:bwdtf4w)* status: all files reviewed, 10 unresolved discussions (waiting on @donnadionne)

___
*[BUILD, line 3293 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3_8oi9Z0RvTloF0TG:-N-3_8oi9Z0RvTloF0TH:bwc6y82) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/BUILD#L3293)):*
> ```Starlark
>         "absl/strings",
>         "absl/strings:str_format",
>         "absl/debugging:stacktrace",
> ```

Do we actually need these absl debugging dependencies?
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h, line 44 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3_Xp810lhMqMonab5:-N-3_Xp94-sO_QIhnZ-B:b-vcskum) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h#L44)):*
> ```objc
> class OutlierDetectionLbConfig : public LoadBalancingPolicy::Config {
>  public:
>   struct OutlierDetectionLbChild {
> ```

I don't think we need this struct, since there will not be multiple children here.  Instead, let's just make the child policy config be a member of `OutlierDetectionLbConfig` directly.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3_TfD15ExZCdF1Avj:-N-3_TfD15ExZCdF1Avk:b-av6zy7) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h#L46)):*
> ```objc
>   struct OutlierDetectionLbChild {
>     RefCountedPtr<LoadBalancingPolicy::Config> config;
>     bool ignore_reresolution_requests = false;
> ```

Don't need this field.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3_sbt9jNH-b3ooCSU:-N-3_sbt9jNH-b3ooCSV:b-ydhwj0) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h#L56)):*
> ```objc
> 
>  private:
>   OutlierDetectionLbChild child_;
> ```

The config will need a bunch of additional fields, as per the gRFC.

https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md#lb-policy-config
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h, line 72 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3a0AR3acvn355b10U:-N-3a0AR3acvn355b10V:bmc7g9h) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h#L72)):*
> ```objc
>  private:
>   // Each ChildOutlierDetection holds a ref to the OutlierDetectionLb.
>   class ChildOutlierDetection
> ```

I don't think we need a separate class for this child, since there will not be more than one child in this case.  Instead, all of its data members and methods can be moved directly to the `OutlierDetectionLb` class.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 63 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3cXlxD0U37uY2i7U2:-N-3cXlxD0U37uY2i7U3:b-chzivx) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L63)):*
> ```cpp
> }
> 
> const char* OutlierDetectionLb::name() const { return kOutlierDetection; }
> ```

Please move this down below the dtor.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 280 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3eewK2gnUenq8EX-i:-N-3eewK2gnUenq8EX-j:bej42i2) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L280)):*
> ```cpp
>     const XdsClusterResolverLbConfig::DiscoveryMechanism& config() const;
> 
>     RefCountedPtr<OutlierDetectionLbConfig> outlier_detection_lb_config;
> ```

I don't think this field is in the right struct.  The `DiscoveryMechanismEntry` struct is for containing data that comes from the result of the discovery mechanism returning a new set of endpoints.  This config does not come from the discovery mechanism itself; it comes from the config that the xds_cluster_resolver policy gets from its parent.  So I think this should instead be added to the `XdsClusterResolverLbConfig::DiscoveryMechanism` struct.

Also, I think that you will want to store the raw JSON as a `Json` object rather than storing the parsed config, because you will need it in JSON form in order to include it in the child policy config that will be generated in `CreateChildPolicyConfigLocked()`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 859 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3hMCSESAk7Ogql__L:-N-3hMCSESAk7Ogql__M:balp3ha) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L859)):*
> ```cpp
>             discovery_config.lrs_load_reporting_server->ToJson();
>       }
>       Json locality_picking_policy;
> ```

This can be declared down where it is assigned.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 866 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3hBoX0vwKMEg3k7y8:-N-3hBoX0vwKMEg3k7y9:bzsu4u) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L866)):*
> ```cpp
>       } else {
>         // outlier detection will be a no-op
>         outlier_detection_config["interval"] = absl::StrCat(UINT32_MAX, "s");
> ```

This field is a `google.protobuf.Duration`, not a simple integer.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1093 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3g2xv2BTjkne5WCrU:-N-3g2xv2BTjkne5WCrV:bih21b3) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1093)):*
> ```cpp
> 
>  private:
>   static std::vector<grpc_error_handle> ParseDiscoveryMechanism(
> ```

This method will need to be changed to parse the outlier detection LB config.

Note that the outlier detection policy will require the `childPolicy` field to be set, but that field will not be present here in the config of the xds_cluster_resolver policy.  So you will probably need to write the parsing logic for the outlier detection policy with a bool parameter that indicates whether it should require the `childPolicy` field; in the outlier detection policy itself, the parsing logic will be called with the bool set to true, but here in the xds_cluster_resolver policy, the parsing logic will be called with the bool set to false.


<!-- Sent from Reviewable.io -->

2022-04-14 08:50 UTC, donnadionne reviewed
I have set up the policy now: from the update all the way to an outlier detection policy that is currently just a pass through.  Would like your review to make sure all looks good.

I will be 
1. adding a test just to test out the policy
2. add the algorithm inside outlier_detection to eject addresses

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N-bFFhsBgE8GYo1WA50:bef0yen)* status: 1 of 6 files reviewed, 10 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[BUILD, line 3293 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3_8oi9Z0RvTloF0TG:-N-WQAi44ekJBipQ3VEr:b-hfpv0l) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/BUILD#L3293)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Do we actually need these absl debugging dependencies?
</blockquote></details>

removed
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 63 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3cXlxD0U37uY2i7U2:-N-WPeGr-I2bx7W7hgmv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L63)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this down below the dtor.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 280 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3eewK2gnUenq8EX-i:-N-WQGSDE_P0AtemiCou:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L280)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this field is in the right struct.  The `DiscoveryMechanismEntry` struct is for containing data that comes from the result of the discovery mechanism returning a new set of endpoints.  This config does not come from the discovery mechanism itself; it comes from the config that the xds_cluster_resolver policy gets from its parent.  So I think this should instead be added to the `XdsClusterResolverLbConfig::DiscoveryMechanism` struct.

Also, I think that you will want to store the raw JSON as a `Json` object rather than storing the parsed config, because you will need it in JSON form in order to include it in the child policy config that will be generated in `CreateChildPolicyConfigLocked()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 859 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3hMCSESAk7Ogql__L:-N-WQcAx5NFOgps25Jn6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L859)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be declared down where it is assigned.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 866 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3hBoX0vwKMEg3k7y8:-N-bEpVy7upSjMyH82bf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L866)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This field is a `google.protobuf.Duration`, not a simple integer.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1093 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3g2xv2BTjkne5WCrU:-N-bErahBPBNy8tXG2B-:b-xd7tso) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1093)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This method will need to be changed to parse the outlier detection LB config.

Note that the outlier detection policy will require the `childPolicy` field to be set, but that field will not be present here in the config of the xds_cluster_resolver policy.  So you will probably need to write the parsing logic for the outlier detection policy with a bool parameter that indicates whether it should require the `childPolicy` field; in the outlier detection policy itself, the parsing logic will be called with the bool set to true, but here in the xds_cluster_resolver policy, the parsing logic will be called with the bool set to false.
</blockquote></details>

i did most of the parsing in cds.cc, so here we are just taking the json and then inserting it.   i think i am taking care of the childPolicy correct, but please let me know if i am still missing something
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h, line 44 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3_Xp810lhMqMonab5:-N-QjXIdATYNNAOlxFAl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need this struct, since there will not be multiple children here.  Instead, let's just make the child policy config be a member of `OutlierDetectionLbConfig` directly.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3_TfD15ExZCdF1Avj:-N-QjY11ALMuD-_qZAJj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't need this field.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3_sbt9jNH-b3ooCSU:-N-bF3uP2cR9ZXlPfQ6i:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The config will need a bunch of additional fields, as per the gRFC.

https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md#lb-policy-config
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h, line 72 at r1](https://reviewable.io/reviews/grpc/grpc/29343#-N-3a0AR3acvn355b10U:-N-WPKdF0ZYKjY3Sieb7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c5c8a1e0ede842c8540ff4c9b23c75649c184a14/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h#L72)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need a separate class for this child, since there will not be more than one child in this case.  Instead, all of its data members and methods can be moved directly to the `OutlierDetectionLb` class.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-14 16:00 UTC, markdroth requested changes
This is moving in the right direction!

You may also want to copy the subchannel wrapping code from the xds_cluster_impl policy, since we'll need that in the outlier_detection policy as well.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N-cn2S59oO74m_VWZlQ:b-2vbbmg)* status: all files reviewed, 24 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[BUILD, line 3295 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cQquu1Lyn0JNCJV7S:-N-cQquv8vTYnIEtSirt:bva01up) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/BUILD#L3295)):*
> ```Starlark
>         "grpc_base",
>         "grpc_client_channel",
>         "grpc_lb_xds_channel_args",
> ```

The outlier detection policy is not xDS-specific and should not depend on any xDS-related targets.

It looks like the only thing you're actually using here is the definition of the `XdsClusterResource::OutlierDetection` struct.  Instead, I suggest defining that struct in its own header file in outlier_detection.h and then having the xDS code depend on that file.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 27 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-c_JD93CATbktkAtHI:-N-c_JDA5pBDNuIEzyMd:b-x4c1cn) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L27)):*
> ```cpp
> #include "src/core/ext/filters/client_channel/lb_policy.h"
> #include "src/core/ext/filters/client_channel/lb_policy/child_policy_handler.h"
> #include "src/core/ext/filters/client_channel/lb_policy/xds/xds.h"
> ```

There should not be any xDS-related includes in this file.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 51 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-c_yvz-B76CQRCs224:-N-c_Ocn66DnEFhUpgIq:b-2kopx) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L51)):*
> ```cpp
> 
> //
> // LB policy
> ```

This comment isn't very useful.  Suggest removing it.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 60 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-c_oJb8pGDJHmG-sue:-N-c_oJb8pGDJHmG-suf:bsvslv8) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L60)):*
> ```cpp
>  public:
>   OutlierDetectionLbConfig(
>       XdsClusterResource::OutlierDetection outlier_detection_info,
> ```

Please call this `outlier_detection_config`, and the data member `outlier_detection_config_`.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 83 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-ca4NW7n4JKc_75jns:-N-ca4NW7n4JKc_75jnt:b-n6797d) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L83)):*
> ```cpp
> class OutlierDetectionLb : public LoadBalancingPolicy {
>  public:
>   OutlierDetectionLb(RefCountedPtr<XdsClient> xds_client, Args args);
> ```

This does not need an `XdsClient` instance.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 103 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-caFonAahHu1ECH6G-:-N-caFonAahHu1ECH6G0:b-wgltgi) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L103)):*
> ```cpp
>   };
> 
>   // A picker that wraps the picker from the child to perform drops.
> ```

s/drops/outlier detection/
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 153 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cahBs-uM-94g4Yybe:-N-cahBs-uM-94g4Yybf:b1wk7yr) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L153)):*
> ```cpp
> 
>   // The xds client.
>   RefCountedPtr<XdsClient> xds_client_;
> ```

This is not needed.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 182 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cauY1A0bbMAgzCewc:-N-cauY1A0bbMAgzCewd:bcs7u6e) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L182)):*
> ```cpp
>         "outlier_detection picker not given any child picker"));
>   }
>   // Not dropping, so delegate to child picker.
> ```

Please remove this comment.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 232 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cbFoS-z3ImzRoQx9c:-N-cbFoS-z3ImzRoQx9d:bgo0hzx) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L232)):*
> ```cpp
> 
> void OutlierDetectionLb::ResetBackoffLocked() {
>   // The XdsClient will have its backoff reset by the xds resolver, so we
> ```

This comment can be removed.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 268 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cbZag0n0XuLBE50l_:-N-cbZag0n0XuLBE50la:bedayr3) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L268)):*
> ```cpp
>               "[outlier_detection_lb %p] updating connectivity: state=%s "
>               "status=(%s) "
>               "picker=%p",
> ```

This can be combined with the previous line.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 307 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cc22k8EYOPYUdgiac:-N-cc22k8EYOPYUdgiad:bgo0hzx) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L307)):*
> ```cpp
>     ServerAddress address, const grpc_channel_args& args) {
>   if (outlier_detection_policy_->shutting_down_) return nullptr;
>   // Load reporting not enabled, so don't wrap the subchannel.
> ```

This comment can be removed.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 385 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-ccP8s-yRWseYuujkS:-N-ccP8s-yRWseYuujkT:bti0pts) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L385)):*
> ```cpp
>     std::vector<grpc_error_handle> error_list;
>     // Outlier detection policy
>     XdsClusterResource::OutlierDetection outlier_detection_policy;
> ```

Please call this `outlier_detection_config`.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 386 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-ccWIU375HL4ZlT9AT:-N-ccWIU375HL4ZlT9AU:b19o7b5) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L386)):*
> ```cpp
>     // Outlier detection policy
>     XdsClusterResource::OutlierDetection outlier_detection_policy;
>     Duration temp_ [...]

2022-04-19 07:34 UTC, donnadionne reviewed
I fixed according to comments .  I also did the subchannel wrapping and watcher wrapper and set up to do eject/uneject; i am ready for another round of review, let me know if this all looks ok so far thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N0-ZWfg7DliDzocNriB:b-y5vgqc)* status: 4 of 9 files reviewed, 24 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[BUILD, line 3295 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cQquu1Lyn0JNCJV7S:-N0-cMWe5dowRDYj6X2P:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/BUILD#L3295)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The outlier detection policy is not xDS-specific and should not depend on any xDS-related targets.

It looks like the only thing you're actually using here is the definition of the `XdsClusterResource::OutlierDetection` struct.  Instead, I suggest defining that struct in its own header file in outlier_detection.h and then having the xDS code depend on that file.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 27 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-c_JD93CATbktkAtHI:-N0-cPJk5p8QOW2e-Q1Z:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L27)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There should not be any xDS-related includes in this file.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 51 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-c_yvz-B76CQRCs224:-N0-Fk_Z4nS8UHNokZJH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment isn't very useful.  Suggest removing it.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 60 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-c_oJb8pGDJHmG-sue:-N0-FxG13L4kuNFvZoXm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `outlier_detection_config`, and the data member `outlier_detection_config_`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 83 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-ca4NW7n4JKc_75jns:-N0-GToi2k6EWuFLvP7b:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L83)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This does not need an `XdsClient` instance.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 103 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-caFonAahHu1ECH6G-:-N0-Gy3w-iLtAd8pNYH3:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L103)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/drops/outlier detection/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 153 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cahBs-uM-94g4Yybe:-N0-Gyue5rNpn7aMAGMX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L153)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is not needed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 182 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cauY1A0bbMAgzCewc:-N0-H12g2rza1xr-6Jru:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L182)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove this comment.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 232 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cbFoS-z3ImzRoQx9c:-N0-H5hn5PnXYAz2F3VZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L232)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment can be removed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 268 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cbZag0n0XuLBE50l_:-N0-HHjA2tF14CkKWYlA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L268)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be combined with the previous line.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 307 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cc22k8EYOPYUdgiac:-N0-HNaxElZY3WfruHGI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L307)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment can be removed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 385 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-ccP8s-yRWseYuujkS:-N0-HnA4-6mgrgLoiq0H:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L385)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `outlier_detection_config`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 386 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-ccWIU375HL4ZlT9AT:-N0-jVos7EF2IJz9dHky:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L386)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this temp variable is needed.  Instead, you can directly pass `&outlier_detection_policy.interval` to `ParseJsonObjectFieldAsDuration()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 359 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-ce6qC8H3bzf0 [...]

2022-04-19 15:23 UTC, markdroth requested changes
The subchannel wrapper looks pretty good!  There are only two substantive comments there, one about needing to support multiple watchers and another about passing `ejected_` to the `WatcherWrapper` when you instantiate it.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 5 files at r4, 20 of 20 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N01PeKU6T9lVz1Bjdff:be6plwn)* status: all files reviewed, 23 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[BUILD, line 3295 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cQquu1Lyn0JNCJV7S:-N0168eK6oQQAbtUKp24:bdwmk6s) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/BUILD#L3295)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Instead of having the grpc_xds_client depend on the whole outlier detection LB policy, I suggest outlier_detection.h to its own target and having both grpc_xds_client and the outlier detection LB policy depend on that target.
___
*[BUILD, line 3311 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N016aZk3BywhY__Wf48:-N016aZk3BywhY__Wf49:bs6hzxt) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/BUILD#L3311)):*
> ```Starlark
>         "grpc_base",
>         "grpc_client_channel",
>         "grpc_lb_subchannel_list",
> ```

I don't think this policy should depend on the subchannel list library.  That library should be used only by leaf LB policies.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 29 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N01ACAR3x_HXiKBkeoO:-N01ACAR3x_HXiKBkeoP:b-an2ek5) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L29)):*
> ```cpp
> #include "src/core/ext/filters/client_channel/lb_policy.h"
> #include "src/core/ext/filters/client_channel/lb_policy/child_policy_handler.h"
> #include "src/core/ext/filters/client_channel/lb_policy/subchannel_list.h"
> ```

This include is not needed.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 76 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N017WDc1rKr-c_56voo:-N017WDc1rKr-c_56vop:bp10o41) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L76)):*
> ```cpp
> class OutlierDetectionLb : public LoadBalancingPolicy {
>  public:
>   OutlierDetectionLb(Args args);
> ```

`explicit`
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 85 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N017iIh8m-Vjk-qCSAj:-N017iIh8m-Vjk-qCSAk:bormaoz) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L85)):*
> ```cpp
> 
>  private:
>   class SubchannelWrapper : public SubchannelInterface {
> ```

This can inherit from `DelegatingSubchannel`, so that you don't have to manually define the simple delegating methods, only the methods that you actually want to override (in this case, the connectivity state-related methods).

https://github.com/grpc/grpc/blob/8e0da602a8c1e09666a65de18b93c9ea10669d2d/src/core/ext/filters/client_channel/subchannel_interface.h#L96
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 87 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N017zDE74oVhR75GsKs:-N017zDE74oVhR75GsKt:bp10o41) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L87)):*
> ```cpp
>   class SubchannelWrapper : public SubchannelInterface {
>    public:
>     SubchannelWrapper(RefCountedPtr<SubchannelInterface> subchannel)
> ```

`explicit`
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 94 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N018-iaDe_DhQ_JM_pG:-N018-iaDe_DhQ_JM_pH:bhlffc3) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L94)):*
> ```cpp
>     }
> 
>     void eject();
> ```

Please capitalize the first letter of these two method names.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 113 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N01864GBpUwe_ae-DOj:-N01864GBpUwe_ae-DOk:blx8z3d) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L113)):*
> ```cpp
>     }
> 
>     class WatcherWrapper
> ```

This should be private within `SubchannelWrapper`.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 121 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N018JlGBVootI7K4KJ3:-N018JlGBVootI7K4KJ4:b-23u2ly) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L121)):*
> ```cpp
>           : watcher_(std::move(watcher)) {}
> 
>       ~WatcherWrapper() override {}
> ```

Not needed if it's not actually doing anything.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 125 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N01CtFw4D9Fll7KSD3o:-N01CtFw4D9Fll7KSD3p:bap9a5r) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L125)):*
> ```cpp
>       void eject() {
>         eject_ = true;
>         watcher_->OnConnectivityStateChange(GRPC_CHANNEL_TRANSIENT_FAILURE);
> ```

We should do this only if `last_seen_state_` is not TRANSIENT_FAILURE, so that we don't send an unnecessary duplicate notification.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 130 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N01CghhCPrOfWXa7SDP:-N01CghhCPrOfWXa7SDQ:bex3f6i) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L130)):*
> ```cpp
>       void uneject() {
>         eject_ = false;
>         watcher_->OnConnectivityStateChange(last_seen_state_);
> ```

Same here: Do this only if `last_seen_state_` is not TRANSIENT_FAILURE.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 137 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N01CQoMEL1NcTI5GTDs:-N01CQoMEL1NcTI5GTDt:bsrfczs) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L137)):*
> ```cpp
>         last_seen_state_ = new_state;
>         if (eject_) {
>           watcher_->OnConnectivityStateChange(GRPC_CHANNEL_TRANSIENT_FAILURE);
> ```

When we were ejected, we already sent notification of TRANSIENT_FAILURE, so we don't need to send a duplicate notification for the same state here.  We should send notification only if `eject_` is false.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 144 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N019LbV8wDqal9iUCO-:-N019LbV8wDqal9iUCO0:b-59rw4j) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy [...]

2022-04-20 07:17 UTC, donnadionne reviewed
addressed all the comments so far.

Added the ejection map structure and included call counter.  PTAL thank you

I do have some questions about where and how to increment the call counters (please see TODO in outlier_detection.cc)

Thanks

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N04p0G28Y-hCT6B6kaZ:btksrtj)* status: all files reviewed, 23 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[BUILD, line 3295 at r3](https://reviewable.io/reviews/grpc/grpc/29343#-N-cQquu1Lyn0JNCJV7S:-N048Bis6jQfZ-4zju5B:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c6ffc5c6102d417da2e248eb76a83b4f8279ba51/BUILD#L3295)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of having the grpc_xds_client depend on the whole outlier detection LB policy, I suggest outlier_detection.h to its own target and having both grpc_xds_client and the outlier detection LB policy depend on that target.
</blockquote></details>

Done.
___
*[BUILD, line 3311 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N016aZk3BywhY__Wf48:-N01svCaBnJQqgJaGibf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/BUILD#L3311)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this policy should depend on the subchannel list library.  That library should be used only by leaf LB policies.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 29 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N01ACAR3x_HXiKBkeoO:-N01swFP2IMBxAFAkMwg:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L29)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This include is not needed.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 76 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N017WDc1rKr-c_56voo:-N01t3xC74XgcJmbDVi_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L76)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`explicit`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 85 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N017iIh8m-Vjk-qCSAj:-N04Nkbc8hWohH_dWupe:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can inherit from `DelegatingSubchannel`, so that you don't have to manually define the simple delegating methods, only the methods that you actually want to override (in this case, the connectivity state-related methods).

https://github.com/grpc/grpc/blob/8e0da602a8c1e09666a65de18b93c9ea10669d2d/src/core/ext/filters/client_channel/subchannel_interface.h#L96
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 87 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N017zDE74oVhR75GsKs:-N01tXyYA69O0GHq5dN9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L87)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`explicit`
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 94 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N018-iaDe_DhQ_JM_pG:-N01xMKc24hkU_81ZBkK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L94)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please capitalize the first letter of these two method names.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 113 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N01864GBpUwe_ae-DOj:-N01xm0zA5YUahdNvQhv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L113)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be private within `SubchannelWrapper`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 121 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N018JlGBVootI7K4KJ3:-N01xocE3foM89CIKcSU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L121)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Not needed if it's not actually doing anything.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 125 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N01CtFw4D9Fll7KSD3o:-N023FI_2J2w00O0uWUQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L125)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should do this only if `last_seen_state_` is not TRANSIENT_FAILURE, so that we don't send an unnecessary duplicate notification.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 130 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N01CghhCPrOfWXa7SDP:-N023FZK12GniXI6Lvi2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L130)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here: Do this only if `last_seen_state_` is not TRANSIENT_FAILURE.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 137 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N01CQoMEL1NcTI5GTDs:-N023SX46T06JAXWnCGK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L137)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

When we were ejected, we already sent notification of TRANSIENT_FAILURE, so we don't need to send a duplicate notification for the same state here.  We should send notification only if `eject_` is false.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 144 at r5](https://reviewable.io/reviews/grpc/grpc/29343#-N019LbV8wDqal9iUCO-:-N0247y24Oal5JaoGmfH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/5d2471f29dc7eceb7c133ee5608680fb783f8f11/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D [...]

2022-04-20 07:20 UTC, donnadionne reviewed
According to design doc: "the outlier_detection LB policy will store a map with keys that are subchannel addresses, and values that are objects that contain the following:
The call result counter object (see Call Counter section)
The latest ejection timestamp, or null if the address is currently not ejected
The current ejection time multiplier, starting at 0
A list of subchannel wrapper objects that correspond to this address";  but then for call counter incrementing, it says "when the request finishes, increment the corresponding counter in the map entry referenced by the subchannel wrapper that was picked".  But the map is not referenced by the subchannel wrapper, it is refereced by the subchannel address and each entry could contain a list of subcahnnel wrappers.  Please clarify. 

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N04pXEiDPOXvp-mQ6Po:b-5zb3pl)* status: all files reviewed, 23 unresolved discussions (waiting on @markdroth and @yashykt)



<!-- Sent from Reviewable.io -->

2022-04-20 17:12 UTC, markdroth requested changes
I don't think we want the call counter updates to do a lookup in the map, because that would require further synchronization.  Instead, I think we want the entries in the map to be ref-counted, and the `SubchannelWrapper` will hold a ref to the entry, so we can directly use that entry to update the call counters.  I've added some comments with details.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N06x5eL5oPYZHHmScwO:b4tu6da)* status: all files reviewed, 14 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 88 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06e82EADkHt11s6Ohk:-N06e82EADkHt11s6Ohl:bjghzf1) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L88)):*
> ```cpp
>   class SubchannelWrapper;
>   class CallCounter;
>   struct Ejection {
> ```

Please call this `SubchannelState`.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 88 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06k2RZ3k9H1m41Zode:-N06k2RZ3k9H1m41Zodf:bggwr8q) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L88)):*
> ```cpp
>   class SubchannelWrapper;
>   class CallCounter;
>   struct Ejection {
> ```

I think we're going to want this to be a `RefCounted<>` class.  We will want each `SubchannelWrapper` for a given address to hold a ref to this object, so that the picker can take a ref to it for the `SubchannelCallTrackerInterface` object, so that the `SubchannelCallTrackerInterface` object can update the call success/failure counts without having to look up the right entry in the map (which would require additional synchronization).
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 89 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06pcPaDdQRRuGLwDLe:-N06pcPaDdQRRuGLwDLf:b-be05r8) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L89)):*
> ```cpp
>   class CallCounter;
>   struct Ejection {
>     struct CallResultCounter {
> ```

I think we need to structure this differently for synchronization purposes:

```
struct Bucket {
  struct CallCounters {
    std::atomic<uint64_t> successes;
    std::atomic<uint64_t> failures;
  };
  std::unique_ptr<Bucket> current_bucket;
  std::unique_ptr<Bucket> backup_bucket;
  // The bucket used to update call counts.
  // Points to either current_bucket or active_bucket.
  std::atomic<Bucket*> active_bucket;
};
```

The `SubchannelCallTrackerInterface` returned by the picker will always update the counters in `active_bucket`.

When the timer fires, we can use the same approach that Envoy does to swap the buckets:

https://github.com/envoyproxy/envoy/blob/60a13f30a4e425c907607fab96efee0ed2afcf22/source/common/upstream/outlier_detection_impl.cc#L821

The result of that function gets stored in `active_bucket`.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 177 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06f2H9DjONZcbFD1SH:-N06f2HA5ibTu46zoG06:b-8m25sc) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L177)):*
> ```cpp
>   };
> 
>   class CallCounter {
> ```

This class is really just a thin wrapper around `std::atomic<>`, so I'm not sure it adds any value.  We can just use `std::atomic<>` directly.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 258 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06vYzdE-thzYuBFZ-j:-N06vYzdE-thzYuBFZ-k:b-u468s4) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L258)):*
> ```cpp
>   absl::Status status_;
>   RefCountedPtr<RefCountedPicker> picker_;
>   std::map<std::string, Ejection> ejection_map_;
> ```

Please call this `subchannel_state_map_`.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 290 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06UVzFCF0ErcfC455Q:-N06UVzG4lTi2ES4k2AK:bem8dvt) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L290)):*
> ```cpp
>   ConnectivityStateWatcherInterface* watcher_ptr = watcher.get();
>   auto watcher_wrapper =
>       absl::make_unique<WatcherWrapper>(std::move(watcher), ejected_);
> ```

I think we also need to pass `initial_state` into `WatcherWrapper`, to initialize the `last_seen_state_` data member.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 326 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06WFJfBEH4fXlW8sc7:-N06WFJg1SgHp71NMbjl:bkg1cja) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L326)):*
> ```cpp
>   PickResult result = picker_->Pick(args);
>   auto* complete_pick = absl::get_if<PickResult::Complete>(&result.result);
>   // TODO@donnadionne: I think this is where we increment the call result
> ```

No, the call is not complete here; this is just the LB pick.  The LB pick happens before the call has even been sent on the wire, because we need the LB policy to choose a subchannel before we can send the call on the subchannel.

What you need to do here is to implement a [`SubchannelCallTrackerInterface`](https://github.com/grpc/grpc/blob/5d843c482c685339dcefa691e71912bf9b9c8d1a/src/core/ext/filters/client_channel/lb_policy.h#L181) and have the picker return an instance of that implementation.  When the call is complete, the channel will call the `SubchannelCallTrackerInterface::Finish()` method, so you can record the status of the call there.

As mentioned above, the picker will need to get a ref to the `SubchannelState` object from the `SubchannelWrapper`, and it will pass that ref to the `SubchannelCallTrackerInterface` object.  That way, when `Finish()` is called, we can directly update the counters in the `SubchannelState` object without having to look it up in the map.

For an example of implementing a `SubchannelCallTrackerInterface`, see [the xds_cluster_impl policy](https://github.com/grpc/grpc/blob/5d843c482c685339dcefa691e71912bf9b9c8d1a/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L274).
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 394 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06jBpUAomzKBVerA5O:-N06jBpUAomzKBVerA5P:bvdyg25) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L394)):*
> ```cpp
>     child_policy_ = CreateChildPolicyLocked(args.args);
>   }
>   std::set<std::string> current_addresses;
> ```

This can go inside the `if (args.addresses.ok())` block.
___
*[src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc, line 397 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06iyZ89lVrBffaWZtE:-N06iyZ89lVrBffaWZtF:b-ft218g) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_dete [...]

2022-04-26 06:59 UTC, donnadionne reviewed
Almost there, updated map, added timer and call counting.  Just need a bit more detail for the success and failure algorithm.  Would like another round of review to make sure all things are in the right places while I finish the algorithms.  Thank you !

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N0ZeVl2BnW0V4xppm4F:bmohnc4)* status: 7 of 22 files reviewed, 14 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 88 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06e82EADkHt11s6Ohk:-N0CqQmz5YF8VEIR_bjt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L88)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `SubchannelState`.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 88 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06k2RZ3k9H1m41Zode:-N0CqJVsEViTzuK6xHhb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L88)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we're going to want this to be a `RefCounted<>` class.  We will want each `SubchannelWrapper` for a given address to hold a ref to this object, so that the picker can take a ref to it for the `SubchannelCallTrackerInterface` object, so that the `SubchannelCallTrackerInterface` object can update the call success/failure counts without having to look up the right entry in the map (which would require additional synchronization).
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 89 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06pcPaDdQRRuGLwDLe:-N0ZeUnB2ks58rYB0yEX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L89)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we need to structure this differently for synchronization purposes:

```
struct Bucket {
  struct CallCounters {
    std::atomic<uint64_t> successes;
    std::atomic<uint64_t> failures;
  };
  std::unique_ptr<Bucket> current_bucket;
  std::unique_ptr<Bucket> backup_bucket;
  // The bucket used to update call counts.
  // Points to either current_bucket or active_bucket.
  std::atomic<Bucket*> active_bucket;
};
```

The `SubchannelCallTrackerInterface` returned by the picker will always update the counters in `active_bucket`.

When the timer fires, we can use the same approach that Envoy does to swap the buckets:

https://github.com/envoyproxy/envoy/blob/60a13f30a4e425c907607fab96efee0ed2afcf22/source/common/upstream/outlier_detection_impl.cc#L821

The result of that function gets stored in `active_bucket`.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 177 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06f2H9DjONZcbFD1SH:-N0CuPez0Qa_B8DZxXLm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L177)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This class is really just a thin wrapper around `std::atomic<>`, so I'm not sure it adds any value.  We can just use `std::atomic<>` directly.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 258 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06vYzdE-thzYuBFZ-j:-N0CqlAxAJuVNUlzcwTV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L258)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please call this `subchannel_state_map_`.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 290 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06UVzFCF0ErcfC455Q:-N0SWjJPBDd640GSTgg0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L290)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we also need to pass `initial_state` into `WatcherWrapper`, to initialize the `last_seen_state_` data member.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 326 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06WFJfBEH4fXlW8sc7:-N0SX7kK-k4G6Ogg74B8:b-9vhrbt) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L326)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No, the call is not complete here; this is just the LB pick.  The LB pick happens before the call has even been sent on the wire, because we need the LB policy to choose a subchannel before we can send the call on the subchannel.

What you need to do here is to implement a [`SubchannelCallTrackerInterface`](https://github.com/grpc/grpc/blob/5d843c482c685339dcefa691e71912bf9b9c8d1a/src/core/ext/filters/client_channel/lb_policy.h#L181) and have the picker return an instance of that implementation.  When the call is complete, the channel will call the `SubchannelCallTrackerInterface::Finish()` method, so you can record the status of the call there.

As mentioned above, the picker will need to get a ref to the `SubchannelState` object from the `SubchannelWrapper`, and it will pass that ref to the `SubchannelCallTrackerInterface` object.  That way, when `Finish()` is called, we can directly update the counters in the `SubchannelState` object without having to look it up in the map.

For an example of implementing a `SubchannelCallTrackerInterface`, see [the xds_cluster_impl policy](https://github.com/grpc/grpc/blob/5d843c482c685339dcefa691e71912bf9b9c8d1a/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_impl.cc#L274).
</blockquote></details>

i think i got it.  i see the finish calling increment
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 394 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06jBpUAomzKBVerA5O:-N0SXORT-ffDEB51g3xF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L394)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can go inside the `if (args.addresses.ok())` block.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 397 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06iyZ89lVrBffaWZtE:-N0SYKUb5I2GTLAVj4uJ:biinqx9) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L397)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If the address is already in the map,  [...]

2022-04-26 16:21 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343)* status: all files reviewed, 18 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 665 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0afADb5u4nm29VZTiV:-N0afADb5u4nm29VZTiW:bejkq3m) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L665)):*
> ```cpp
>       // 2. For each address, swap the call counter's buckets in that address's
>       // map entry.
>       entry.second->bucket.backup_bucket->successes = 0;
> ```

This logic to rotate the bucket can be a method on `SubchannelState`.


<!-- Sent from Reviewable.io -->

2022-05-02 04:14 UTC, donnadionne reviewed
Implemented all the algorithms, will work on tests now.  Please let me know if there are major changes still needed.  thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N11yV0-BRXfMT-rVV9n:bhmml0k)* status: 19 of 22 files reviewed, 18 unresolved discussions (waiting on @markdroth, @murgatroid99, and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 397 at r6](https://reviewable.io/reviews/grpc/grpc/29343#-N06jJzz4mGv7RbZiQ72:-N0irOOF7Yo0G9tvI5H9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6753ef348c5fefc6c60bb0f1714a37cee9dc69a1/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L397)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No, we need the args, since they are part of the identity of the subchannel.

It looks like you'll need to use `grpc_channel_args_copy(address.args())`.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 94 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0aSS557zMzpQYL8AHT:-N0gJKLRDdnq3PMnhL_R:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L94)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be initialized where the data member is defined instead of doing it here.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 96 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0acWzp3Bn-H_rGuhwC:-N0gxjxp09chd7n5mWB4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L96)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `SubchannelWrapper` dtor needs to remove the `SubchannelWrapper` from this list.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 174 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0aQiB519JHM9DVk9d1:-N0ivfQ41nULvBMoS1An:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L174)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like what I wrote in my previous comment was a little confused in terms of the struct names.  I don't think we need this outer struct at all -- the fields inside of it can just directly go in `SubchannelState`.  And I think the inner struct should be called `Bucket` instead of `CallCounters`.  So let's have it look like this:

```
struct Bucket {
  std::atomic<uint64_t> successes;
  std::atomic<uint64_t> failures;
};
std::unique_ptr<Bucket> current_bucket_;
std::unique_ptr<Bucket> backup_bucket_;
// The bucket used to update call counts.
// Points to either current_bucket_ or active_bucket_.
std::atomic<Bucket*> active_bucket_;

absl::optional<Timestamp> ejection_time_;
uint32_t multiplier_;
absl::InlinedVector<RefCountedPtr<SubchannelWrapper>, 1> subchannels_;
```
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 190 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0aSHtp6MwvAKTZ7nDz:-N0ivlRu8JRMRU4WaS9r:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L190)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Data members should be private and should have underscore suffixes.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 192 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0acHRt4DSk9Oa2zLdZ:-N0gxia90QGNoLGHJr5G:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L192)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this vector should actually hold raw pointers to the subchannels rather than holding refs.  Otherwise, the subchannels will never get deleted, because their ref-count will never go to zero.

Also, we should probably use `std::set<>` here instead of `absl::InlinedVector<>`, since that will make removing entries more efficient when subchannels are destroyed.

So this should be:

```
std::set<SubchannelWrapper*> subchannels_;
```
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 241 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0adyDl0Suy8vYQRYOA:-N0iwJmEB2SYJWmvEOuM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L241)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `EjectionTimer`.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 257 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0adsSM7ZSued3s6eNV:-N0h8qdf4YMVL8UeAixU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L257)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this down below the dtor.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 384 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0aT9xt1sGIykCdwWp-:-N0h8cpR3kMbzfLEnswW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L384)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since we don't care about started calls, I don't think we need this data member or any of the checks around it.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 414 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0aTsdS4HUzvvOdt7Db:-N0h5Pa57frVvNMbJM76:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L414)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not safe to refer to `subchannel_wrapper` after you reset `complete_pick->subchannel`, since that's where we're holding the ref to the wrapper.  I think this line needs to be moved down to after the next statement.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 428 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0aeHr86JmKv3J7Yby4:-N0h9-7A9N5382VdeD2Y:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L428)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this down so that the methods are defined in t [...]

2022-05-02 17:20 UTC, markdroth requested changes
This is moving in the right direction!

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 3 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N14mGr_Cp5EHx_IY4Jt:b-k1b92a)* status: all files reviewed, 20 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 481 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0aec0h09SuOcOF0Kha:-N14ZMpsDf1NINmNS2p3:b87w9s6) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L481)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I think i may still be missing some details here: reset call counter, cancel existing timer, a little unsure where best to do that
</blockquote></details>

See my comment in the `EjectionTimer` ctor about how to do this.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 662 at r7](https://reviewable.io/reviews/grpc/grpc/29343#-N0aWa9wAFYAHMVOaGBL:-N14UO4mEVtm3sLBHdhR:b-d1lqgc) ([raw file](https://github.com/grpc/grpc/blob/647f3a71cbd835cb74046a9b21364545684adab6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L662)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is still setting the ejection timestamp for each `SubchannelState` unconditionally.  I don't think we want to do that unless we decide to eject it.

I think we should just remove this line.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 168 at r9](https://reviewable.io/reviews/grpc/grpc/29343#-N14Ni2O-zzrWXTGefBz:-N14Ni2O-zzrWXTGefC-:b-edn8lm) ([raw file](https://github.com/grpc/grpc/blob/715d793b942eb238281f86b5666e0c423dc45906/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L168)):*
> ```cpp
>           watcher_;
>       grpc_connectivity_state last_seen_state_;
>       bool ejected_ = false;
> ```

No need to initialize this to false here, since we are unconditionally setting it in the ctor.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 192 at r9](https://reviewable.io/reviews/grpc/grpc/29343#-N14OuQ-2HexyiwBnkVQ:-N14OuQ05TgNiPa8eZRg:b46wn8m) ([raw file](https://github.com/grpc/grpc/blob/715d793b942eb238281f86b5666e0c423dc45906/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L192)):*
> ```cpp
>     }
> 
>     void ResetBucket() {
> ```

I don't think it's safe to reset both the current and backup bucket at the same time for synchronization reasons.  But it doesn't look like this method is actually being called anywhere, so I don't think it's necessary.  I think you can just remove it.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 224 at r9](https://reviewable.io/reviews/grpc/grpc/29343#-N14O9OSDTzJJ38psPkq:-N14O9OSDTzJJ38psPkr:b-jc2vsn) ([raw file](https://github.com/grpc/grpc/blob/715d793b942eb238281f86b5666e0c423dc45906/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L224)):*
> ```cpp
>     void AddFailureCount() { current_bucket_->failures.fetch_add(1); }
> 
>     bool GetEjected() { return ejected_; }
> ```

This is a simple accessor method, so it should be called `ejected()`.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 226 at r9](https://reviewable.io/reviews/grpc/grpc/29343#-N14Y_ccBplIk2rRTfHM:-N14OE-Y8fkxfRnt3UNy:bpniszr) ([raw file](https://github.com/grpc/grpc/blob/715d793b942eb238281f86b5666e0c423dc45906/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L226)):*
> ```cpp
>     bool GetEjected() { return ejected_; }
> 
>     uint32_t Multiplier() const { return multiplier_; }
> ```

These simple accessor/setter methods should be called `multiplier()` and `set_multiplier()`.

That having been said, I think these two methods can just go away if you take my suggestion below about moving some of the logic into a `MaybeUneject()` method.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 230 at r9](https://reviewable.io/reviews/grpc/grpc/29343#-N14YouFCmMVc35MeOUh:-N14OOmPAaCu5kXbBzfI:b1g1b4w) ([raw file](https://github.com/grpc/grpc/blob/715d793b942eb238281f86b5666e0c423dc45906/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L230)):*
> ```cpp
>     void SetMultiplier(uint32_t multiplier) { multiplier_ = multiplier; }
> 
>     absl::optional<Timestamp> EjectionTime() const { return ejection_time_; }
> ```

This simple accessor method should be called `ejection_time()`.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 232 at r9](https://reviewable.io/reviews/grpc/grpc/29343#-N14Y2SL3eebl5U5CbJ3:-N14OQ6iE5_xekE6COWC:b1jy837) ([raw file](https://github.com/grpc/grpc/blob/715d793b942eb238281f86b5666e0c423dc45906/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L232)):*
> ```cpp
>     absl::optional<Timestamp> EjectionTime() const { return ejection_time_; }
> 
>     void SetEjectionTime(const Timestamp& time) { ejection_time_ = time; }
> ```

This method should be called `set_ejection_time()`.

But that having been said, I don't think we need this method to begin with.  We want to set the ejection time only when we eject.  (Notice that the only two places where we should be calling this are right after calls to `Eject()`.)  Given that, I suggest removing this method and instead passing the ejection time as a parameter to the `Eject()` method, so that we always do both things at once.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 234 at r9](https://reviewable.io/reviews/grpc/grpc/29343#-N14YyH_67U1WbycPnUx:-N14PKNCBfFU7Jt53kzw:brwmwy4) ([raw file](https://github.com/grpc/grpc/blob/715d793b942eb238281f86b5666e0c423dc45906/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L234)):*
> ```cpp
>     void SetEjectionTime(const Timestamp& time) { ejection_time_ = time; }
> 
>     absl::Time EjectionTimeStamp() const { return ejection_timestamp_; }
> ```

These two methods should be called `ejection_timestamp()` and `set_ejection_timestamp()`.

That having been said, I don't think we need these at all, as per my comment below about not needing two timestamp fields here.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 263 at r9](https://reviewable.io/reviews/grpc/grpc/29343#-N14OWu39TeMTD_eDCwG:-N14OWu39TeMTD_eDCwH:b-cl07nm) ([raw file](https://github.com/grpc/grpc/blob/715d793b942eb238281f86b5666e0c423dc45906/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L263)):*
> ```cpp
>     uint32_t multiplier_ = 0;
>     absl::optional<Timestamp> ejection_time_;
>     absl::Time ejection_timestamp_;
> ```

Please use our `Timestamp` type instead of the one from absl.

https://github.com/grpc/grpc/blob/2691e9da0189ed66ba08a0da3bd5bf47f326d110/src/core/lib/gprpp/time.h#L61

Actually, why do we have this field at all?  We already have `ejection_time_`.  Why do we need a second timestamp field here?  I think this should probably just be removed.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 354 at r9](https://reviewable.io/reviews/grpc/grpc/29343#-N14PCaC6C_tmxlqlYc9:-N14PCaD5TWSuoO6OS6V:b-tdzbr4) ([raw file](https://github.com/grpc/grpc/blob/715d793b942eb238281f86b5666e0c423dc45906/src/core/ext/filters/client_chann [...]

2022-05-05 15:16 UTC, markdroth requested changes
This is looking really good!

Please let me know if you have any questions.  Thanks!

> Reviewed 22 of 22 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1Jmh5REEg_t1SRi1de:b-jvgm50)* status: all files reviewed, 11 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 196 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JfzXR4oXwigGRCiGx:-N1JfzXR4oXwigGRCiGy:bp77gdr) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L196)):*
> ```cpp
>       uint64_t total_request =
>           backup_bucket_->successes + backup_bucket_->failures;
>       gpr_log(GPR_INFO, "donna total %lu", total_request);
> ```

Please remove before merging.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 263 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JeUhW4gswE6-kPYjG:-N1JeUhW4gswE6-kPYjH:b-ipsbit) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L263)):*
> ```cpp
>     // Points to either current_bucket or active_bucket.
>     std::atomic<Bucket*> active_bucket_;
>     bool ejected_ = false;
> ```

Now that we set `ejection_time_` only when we eject, we could unset it when we uneject, and then we don't need this separate `ejected_` bool at all -- we will know that we are ejected any time `ejection_time_` does not have a value.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 359 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JfU9Q2mi0VXC-Djap:-N1JfU9Q2mi0VXC-Djaq:b-oyk98m) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L359)):*
> ```cpp
>   RefCountedPtr<RefCountedPicker> picker_;
>   std::map<std::string, RefCountedPtr<SubchannelState>> subchannel_state_map_;
>   OrphanablePtr<EjectionTimer> ejection_timer_ = nullptr;
> ```

No need to explicitly initialize to `nullptr`, since that's the default for `OrphanablePtr<>`.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 800 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JgWik2jyLgMbyMWZ_:-N1JgWik2jyLgMbyMWZa:bm33qs3) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L800)):*
> ```cpp
>       for (auto& candidate : success_rate_ejection_candidates) {
>         if (candidate.second < ejection_threshold) {
>           uint32_t random_key = absl::Uniform(absl::BitGen(), 1, 100);
> ```

Constructing the `absl::BitGen` object is somewhat expensive, so we should construct it once and reuse it, as per https://abseil.io/docs/cpp/guides/random (see "Reuse Generators When Possible").

I suggest adding a `absl::BitGen bit_gen_;` data member in the `OutlierDetectionLb` object and using it here.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 846 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JjnXR4b_zZ1yZw8dB:-N1JjnXR4b_zZ1yZw8dC:b2w1lud) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L846)):*
> ```cpp
>     }
>     timer_pending_ = false;
>     // causing a crash:
> ```

What crash is this causing?
___
*[`test/cpp/end2end/xds/BUILD` line 276 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1Jk67k9ULYMw5rYf3b:-N1Jk67k9ULYMw5rYf3c:bxvxu5g) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/BUILD#L276)):*
> ```Starlark
>         "gtest",
>     ],
>     flaky = True,  # TODO(b/144705388)
> ```

Let's make sure that the new tests are not flaky, so this should not be needed.
___
*[`test/cpp/end2end/xds/BUILD` line 278 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1Jk1Ny2Pe2jS8tJGzd:-N1Jk1Ny2Pe2jS8tJGze:b-7y8x43) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/BUILD#L278)):*
> ```Starlark
>     flaky = True,  # TODO(b/144705388)
>     linkstatic = True,  # Fixes dyld error on MacOS
>     shard_count = 10,
> ```

This isn't needed unless there are a really large number of tests in the file.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 36 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JkGuL4bthWyZE1obC:-N1JkGuL4bthWyZE1obD:b-5c6zjj) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L36)):*
> ```cpp
> 
> using ::envoy::config::endpoint::v3::HealthStatus;
> using ::envoy::extensions::filters::http::fault::v3::HTTPFault;
> ```

This shouldn't be needed.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 56 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JkYDy0zCf-VrJEQDC:-N1JkYDy0zCf-VrJEQDD:b-2lcqxy) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L56)):*
> ```cpp
>       ComputeIdealNumRpcs(kWeight33Percent, kErrorTolerance);
>   auto cluster = default_cluster_;
>   // Increasing min ring size for random distribution.
> ```

I don't think we want to use ring_hash here.  This test should use round_robin.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 81 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1Jl4BMBs0UVVq1ojtP:-N1Jl4BMBs0UVVq1ojtQ:b-657c6t) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L81)):*
> ```cpp
>   balancer_->ads_service()->SetEdsResource(BuildEdsResource(args));
>   for (size_t i = 0; i < kNumRpcs; ++i) {
>     SendRpc();
> ```

This should use `CheckRpcSendOk()`, since we want to check that the RPCs are not failing.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 90 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JlGrT9bCOmwJD88MU:-N1JlGrT9bCOmwJD88MV:bk2x92f) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L90)):*
> ```cpp
>   const int weight_66_request_count =
>       backends_[1]->backend_service()->request_count();
>   // Assuming outlier detection will eject 1 out of the 2 endpoints, the request
> ```

I think the test needs to actually cause some number of RPCs to fail on one of the endpoints in order for outlier detection to eject that endpoint.

Note that we have a way for the client to request that the server fail an RPC with a particular status:

https://github.com/grpc/grpc/blob/e963544eef6a76f9f86d43418ee2ac57aebba6f6/src/proto/grpc/testing/echo_messages.proto#L51

However, what we want here is to do that only if the request hits a particular endpoint.  You may need to add a new field to do that.  For example, you could add a new `repeated int32 server_ports_to_fail` field, which you populate with the ports of the backends that you want to fail the requests, and then change the backend service code such that if `server_ports_to_fail` is set, it will honor the `expected_error` field only if it is serving on one of the specified ports.


<!-- Sent from Reviewable.io -->

2022-05-09 05:37 UTC, donnadionne reviewed
Still have a few more tests to write and debugs to remove, but ready for another round.  Thank you!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1bJVuc9qloXBYJPmei:b-bb8k5w)* status: all files reviewed, 11 unresolved discussions (waiting on @donnadionne, @markdroth, and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 263 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JeUhW4gswE6-kPYjG:-N1L_-OH5nbXkCL9y1Ub:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L263)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Now that we set `ejection_time_` only when we eject, we could unset it when we uneject, and then we don't need this separate `ejected_` bool at all -- we will know that we are ejected any time `ejection_time_` does not have a value.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 359 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JfU9Q2mi0VXC-Djap:-N1L_AGO7BBbU-MaOmz5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L359)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to explicitly initialize to `nullptr`, since that's the default for `OrphanablePtr<>`.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 800 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JgWik2jyLgMbyMWZ_:-N1Le3yi-pITR3vpTABr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L800)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Constructing the `absl::BitGen` object is somewhat expensive, so we should construct it once and reuse it, as per https://abseil.io/docs/cpp/guides/random (see "Reuse Generators When Possible").

I suggest adding a `absl::BitGen bit_gen_;` data member in the `OutlierDetectionLb` object and using it here.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 846 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JjnXR4b_zZ1yZw8dB:-N1SVsBu-nsog8rDR4dA:b-bs77re) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L846)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What crash is this causing?
</blockquote></details>

i think it's the std::move(parent_)



_Code quote:_
```cpp
parent_->ejection_timer_ = MakeOrphanable<EjectionTimer>(
```
___
*[`test/cpp/end2end/xds/BUILD` line 276 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1Jk67k9ULYMw5rYf3b:-N1KkIpt1YPa6Ax6oCHu:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/BUILD#L276)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's make sure that the new tests are not flaky, so this should not be needed.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/BUILD` line 278 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1Jk1Ny2Pe2jS8tJGzd:-N1KkJ88A_gKOaucAl_j:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/BUILD#L278)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This isn't needed unless there are a really large number of tests in the file.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 36 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JkGuL4bthWyZE1obC:-N1Kop5xEq__aOKM4-4K:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This shouldn't be needed.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 56 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JkYDy0zCf-VrJEQDC:-N1SMxBP79tzow78yaK7:b-kg7qx2) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we want to use ring_hash here.  This test should use round_robin.
</blockquote></details>

i ended up with ring hash because i wanted predictbility which endpoint the rpc will go to and ring hash can help me with the stickness
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 81 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1Jl4BMBs0UVVq1ojtP:-N1SN4H38vQR13kmhGss:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should use `CheckRpcSendOk()`, since we want to check that the RPCs are not failing.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 90 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JlGrT9bCOmwJD88MU:-N1SN51s5TCGWJVrVjJr:bn1p2g1) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L90)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the test needs to actually cause some number of RPCs to fail on one of the endpoints in order for outlier detection to eject that endpoint.

Note that we have a way for the client to request that the server fail an RPC with a particular status:

https://github.com/grpc/grpc/blob/e963544eef6a76f9f86d43418ee2ac57aebba6f6/src/proto/grpc/testing/echo_messages.proto#L51

However, what we want here is to do that only if the request hits a particular endpoint.  You may need to add a new field to do that.  For example, you could add a new `repeated int32 server_ports_to_fail` field, which you populate with the ports of the backends that you want to fail the requests, and then change the backend service code such that if `server_ports_to_fail` is set, it will honor the `expected_error` field only if it is serving on one of the specified ports.
</blockquote></details>

i ended up doing it slightly differently by making each rpc sticky to a backend and then i can inject error on specific rpcs.

Adding the server_ports_to_fail is slightly tricky as I could not get the port into the rpc server test_service_impl.h


<!-- Sent from Reviewable.io -->

2022-05-09 16:11 UTC, markdroth requested changes
This is looking good!  Mainly just missing a bunch of test cases.

Please let me know if you have any questions.  Thanks!

> Reviewed 20 of 20 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1d_awU4k6B4p4VEPI5:bks3wpk)* status: all files reviewed, 12 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 716 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dLbAy3Ti5oYscofvq:-N1dLbAzEvUg0zrl7b0F:b-yrjjwx) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L716)):*
> ```cpp
>     : parent_(std::move(parent)),
>       start_time_(start_time),
>       bit_gen_(absl::BitGen()) {
> ```

This doesn't need to be initialized here, since it doesn't take any arguments.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 889 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dVJWvEv4J6yu8xZyI:-N1dVJWvEv4J6yu8xZyJ:b-sl67cg) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L889)):*
> ```cpp
>                                    &outlier_detection_config.base_ejection_time,
>                                    &error_list);
>     ParseJsonObjectFieldAsDuration(json.object_value(), "maxEjectionTime",
> ```

If this field is not specified, it needs to default to `max(baseEjectionTime, 300s)`, as per the gRFC.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 90 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JlGrT9bCOmwJD88MU:-N1dT4Lr0z1idoSKrUDo:b-f4m38j) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L90)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i ended up doing it slightly differently by making each rpc sticky to a backend and then i can inject error on specific rpcs.

Adding the server_ports_to_fail is slightly tricky as I could not get the port into the rpc server test_service_impl.h

</blockquote></details>

Okay.  I'm not sure why it was hard to pass the port into the test service impl, but I guess the way you have this now is fine.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 37 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dZEEM8qxatOiMdD0R:-N1dZEEM8qxatOiMdD0S:b-af3e4p) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L37)):*
> ```cpp
> using ::envoy::config::endpoint::v3::HealthStatus;
> 
> using OutlierDetectionTest = XdsEnd2endTest;
> ```

I think we should add the following test cases here:

- backends are unejected after the correct interval
- we don't eject more than `max_ejection_percent` of the backends
- success rate `enforcement_percentage` is honored
- success rate `stdev_factor` is honored
- success rate does not eject if there are less than `minimum_hosts` backends
- success rate does not eject if there are less than `request_volume` requests
- failure percentage `enforcement_percentage` is honored
- failure percentage `threshold` is honored
- failure percentage does not eject if there are less than `minimum_hosts` backends
- failure percentage does not eject if there are less than `request_volume` requests
- configure both success rate and failure percentage at the same time and the behavior is correct
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 50 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dQ_bbDVcsIV72ZwrI:-N1dQ_bbDVcsIV72ZwrJ:b-83yju1) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L50)):*
> ```cpp
> // exactly 1 backend due to ejection and all the loads sticky to that backend
> // should go to 1 other backend.
> TEST_P(OutlierDetectionTest, HeaderHashingEjectionSuccessRate) {
> ```

I think this test should be called `SuccessRate100Percent`.  The fact that the test happens to be implemented using ring_hash is just an implementation detail.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 51 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dZ-DOD63LH2IneTpr:-N1dZ-DOD63LH2IneTps:b-1oomxz) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L51)):*
> ```cpp
> // should go to 1 other backend.
> TEST_P(OutlierDetectionTest, HeaderHashingEjectionSuccessRate) {
>   CreateAndStartBackends(4);
> ```

Does this test actually need 4 backends?  It seems like 2 should be sufficient: one to be ejected, and the other to take traffic in its place.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 55 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dTk2_9vjOnCT4pvqr:-N1dTk2aCquiEKNxZj37:b-tipyug) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L55)):*
> ```cpp
>   cluster.set_lb_policy(Cluster::RING_HASH);
>   // Setup outlier failure percentage parameters.
>   // Any failure will cause an potential ejection with the probability of 50%.
> ```

Looks like you actually have the success rate set to 100%, not 50%.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 83 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dN1J7-DsLbSgamoSa:-N1dN1J81ZSA9KC1LXp1:b-mi75b3) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L83)):*
> ```cpp
>   // to create the entry in the ring.
>   std::vector<std::pair<std::string, std::string>> metadata = {
>       {"address_hash", absl::StrCat(ipv6_only_ ? "[::1]" : "127.0.0.1", ":",
> ```

Instead of hard-coding this logic here, please copy the utility methods from the ring hash tests into the `OutlierDetectionTest` class:

https://github.com/grpc/grpc/blob/17d50f46e1619ef71a50ebe22ac01836a032c645/test/cpp/end2end/xds/xds_ring_hash_end2end_test.cc#L71
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 144 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dQmZp4ZIPcpk69uO1:-N1dQmZp4ZIPcpk69uO2:b-e19xcj) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L144)):*
> ```cpp
> // exactly 1 backend due to ejection and all the loads sticky to that backend
> // should go to 1 other backend.
> TEST_P(OutlierDetectionTest, HeaderHashingEjectionFailurePercent) {
> ```

Similar to above, please call this `FailurePercent100Percent`.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 145 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dYQLTBc4hK6SBl1QJ:-N1dYQLTBc4hK6SBl1QK:byhr1ay) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L145)):*
> ```cpp
> // should go to 1 other backend.
> TEST_P(OutlierDetectionTest, HeaderHashingEjectionFailurePercent) {
>   CreateAndStartBackends(4);
> ```

Why do we need 4 backends in this test?  It seems like 2 should be enough, one to be ejected and the other to take the traffic in its place.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 149 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dWPZsBRPnu0fJ1Dco:-N1dWPZsBRPnu0fJ1Dcp:b2g7n0o) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2en [...]

2022-05-11 06:54 UTC, donnadionne reviewed
PTAL, I am leaving the debugs in just alittle longer until all the new tests are approved!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1ltOw_4jdzno3Ixuz5:b-18yt5i)* status: all files reviewed, 12 unresolved discussions (waiting on @donnadionne, @markdroth, and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 716 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dLbAy3Ti5oYscofvq:-N1eP47_D4OkUaDS3Dg0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L716)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't need to be initialized here, since it doesn't take any arguments.
</blockquote></details>

Done.



_Code quote:_
```cpp
absl::BitGen()
```
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 889 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dVJWvEv4J6yu8xZyI:-N1efJqNCyBcUv_J3OiM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L889)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If this field is not specified, it needs to default to `max(baseEjectionTime, 300s)`, as per the gRFC.
</blockquote></details>

Done.



_Code quote:_
```cpp
ParseJsonObjectFieldAsDuratio
```
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 37 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dZEEM8qxatOiMdD0R:-N1lt9lCEjYm5A4aW1H5:b-ls220n) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we should add the following test cases here:

- backends are unejected after the correct interval
- we don't eject more than `max_ejection_percent` of the backends
- success rate `enforcement_percentage` is honored
- success rate `stdev_factor` is honored
- success rate does not eject if there are less than `minimum_hosts` backends
- success rate does not eject if there are less than `request_volume` requests
- failure percentage `enforcement_percentage` is honored
- failure percentage `threshold` is honored
- failure percentage does not eject if there are less than `minimum_hosts` backends
- failure percentage does not eject if there are less than `request_volume` requests
- configure both success rate and failure percentage at the same time and the behavior is correct
</blockquote></details>

added all the above: combined uneject and enforcement percentage of 100% into the basic test for success rate and failure percentage, the rest of the tests are separate with the right parameters 
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 50 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dQ_bbDVcsIV72ZwrI:-N1fEpeG7lWFXN18gdnN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this test should be called `SuccessRate100Percent`.  The fact that the test happens to be implemented using ring_hash is just an implementation detail.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 51 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dZ-DOD63LH2IneTpr:-N1fNKEJ6fj0GkbVj_XC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L51)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Does this test actually need 4 backends?  It seems like 2 should be sufficient: one to be ejected, and the other to take traffic in its place.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 55 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dTk2_9vjOnCT4pvqr:-N1fE_AG59LULakOlz20:b-jd78dg) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L55)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like you actually have the success rate set to 100%, not 50%.
</blockquote></details>

updated comment, I want to do 100 to eliminate flakiness
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 83 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dN1J7-DsLbSgamoSa:-N1ftcUqCY2XhjdlP8V0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L83)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of hard-coding this logic here, please copy the utility methods from the ring hash tests into the `OutlierDetectionTest` class:

https://github.com/grpc/grpc/blob/17d50f46e1619ef71a50ebe22ac01836a032c645/test/cpp/end2end/xds/xds_ring_hash_end2end_test.cc#L71
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 144 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dQmZp4ZIPcpk69uO1:-N1fF6bS4u6BmLf2mCH2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similar to above, please call this `FailurePercent100Percent`.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 145 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dYQLTBc4hK6SBl1QJ:-N1fNIogB_j3xk202zCA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L145)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why do we need 4 backends in this test?  It seems like 2 should be enough, one to be ejected and the other to take the traffic in its place.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 149 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dWPZsBRPnu0fJ1Dco:-N1fEdhD9bCnXsSwFzN8:blwyhcl) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L149)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like the failure percentage is actually set to 100%, not 50%.
</blockquote></details>

updated comment
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 173 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dYbub3iiubCFOvCEI:-N1fJQTS-I3NEHClbC-l:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L173)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think in this test, you can send all traffic using the metadata for the backend that you want to be ejected.  There's no need to send traffic to any other backend explicitly; the traffic will spill over to the other backend when the first backend is ejected.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-11 16:14 UTC, markdroth requested changes
This is looking really good!  Just a few comments remaining.

Please make sure to run the tests 100x on RBE in each of dbg, opt, asan, msan, tsan, and ubsan to ensure that there is no flakiness.

Please let me know if you have any questions.  Thanks!

> Reviewed 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1ntURXBj8E2XKS5Ucg:b-czpein)* status: all files reviewed, 26 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 338 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1ndpeG586WkFPEDPiN:-N1ndpeG586WkFPEDPiO:b-m2odek) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L338)):*
> ```cpp
>     bool timer_pending_ = true;
>     Timestamp start_time_;
>     absl::BitGen bit_gen_ = absl::BitGen();
> ```

There's no need for `= absl::BitGen()`.  The class's ctor doesn't take any arguments, so it's fine to just say `absl::BitGen bit_gen_;`.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 488 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1neVEF-a6W73dW750d:-N1neVEF-a6W73dW750e:b-d490tt) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L488)):*
> ```cpp
>     // Inject subchannel call tracker to record call completion as long as
>     // not both success_rate_ejection and failure_percentage_ejection are unset.
>     if (!outlier_detection_lb_->config_->outlier_detection_config()
> ```

This is not safe, because (a) you're not holding a ref to the LB policy, so you have no guarantee that it will still exist when you try to deference it here, and (b) the picker does not run in the `WorkSerializer`, so it's not safe to access the LB policy's `config_` field without synchronization.

I think a better approach here would be to remove the `outlier_detection_lb_` field and instead add a `const bool enabled_` field whose value is passed into the ctor.  When the LB policy instantiates the new picker, it can pass in the `enabled` parameter based on whether these two fields are set in the config.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 831 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1ni1nzEIVxRahwnCa6:-N1ni1o-0DiIkIpKVHxN:b5ovz9q) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L831)):*
> ```cpp
>               "alrady ejected",
>               success_rate_ejection_candidates.size(), ejected_host_count);
>       bool first_success_eject = true;
> ```

Why do we need this variable?  Shouldn't we just use `ejected_host_count > 0` instead?
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 866 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1niBBNAfKw_eYkq1bj:-N1niBBNAfKw_eYkq1bk:b-ta61vh) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L866)):*
> ```cpp
>               failure_percentage_ejection_candidates.size(),
>               ejected_host_count);
>       bool first_failure_eject = true;
> ```

Same question as above: Why do we need this variable?  Shouldn't we just use `ejected_host_count > 0` instead?
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 955 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1niTub0uyZpYjdx0cP:-N1niTub0uyZpYjdx0cQ:b-ceaibu) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L955)):*
> ```cpp
>         ParseJsonObjectField(object, "requestVolume",
>                              &success_config.request_volume, &error_list);
>         if (error_list.empty()) {
> ```

I don't think this conditional is needed.  If the error list is non-empty, then the resulting config will never be used, so it should be fine to unconditionally add the success config.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 977 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1niaIX36le7syPxtV2:-N1niaIX36le7syPxtV3:bg478jm) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L977)):*
> ```cpp
>         ParseJsonObjectField(object, "requestVolume",
>                              &failure_config.request_volume, &error_list);
>         if (error_list.empty()) {
> ```

Same as above: I don't think this conditional is needed.  If the error list is non-empty, then the resulting config will never be used, so it should be fine to unconditionally add the failure config.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 982 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1nimzPAHG564VrtWaa:-N1nimzPAHG564VrtWab:b-nxw8s3) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L982)):*
> ```cpp
>       }
>     }
>     if (outlier_detection_config.success_rate_ejection.has_value() ||
> ```

I think we want to parse these fields even if success rate and failure percentage are not present.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 990 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1nix4K7G62fFqCw7_x:-N1nix4L3HQvpMErxv5y:blizki5) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L990)):*
> ```cpp
>           json.object_value(), "baseEjectionTime",
>           &outlier_detection_config.base_ejection_time, &error_list);
>       auto max_ejection_time_it = json.object_value().find("maxEjectionTime");
> ```

I think this can be written as:

```
if (!ParseJsonObjectFieldAsDuration(
         json.object_value(), "maxEjectionTime",
         &outlier_detection_config.max_ejection_time, &error_list,
         /*required=*/false)) {
  outlier_detection_config.max_ejection_time =
      std::max(outlier_detection_config.base_ejection_time,
               Duration::Seconds(300));
}
```
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 37 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dZEEM8qxatOiMdD0R:-N1nqIiDD7Ci1sZ1yrwk:b54iz9n) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L37)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

added all the above: combined uneject and enforcement percentage of 100% into the basic test for success rate and failure percentage, the rest of the tests are separate with the right parameters 
</blockquote></details>

I think we still need a test for `enforcement_percentage` being lower than 100 for both success rate and failure rate.  Otherwise, we have no way of knowing that those fields are actually honored.  We'll need to be careful here to ensure that the tests are not flaky.

Also, I think we need a test for `max_ejection_percent` that includes both ejection algorithms.  If the max would only allow 2 ejections, then if success rate ejects 1 and failure percentage tries to eject 2, we need to know that we will not eject the second one.
___
*[`test/cpp/end2end/xd [...]

2022-05-12 05:49 UTC, donnadionne reviewed
added all the tests, PTAL

I ran all configs 100x regularly and all are good, except for I do have a tsan finding.  I'll debug but I will forward you the error and myabe you can help me while you are code reviewing.  it's the bucket atomic variables.

Thank you so much for all your help!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1qntz_2cVI5BBreOFi:b-xdsjif)* status: 12 of 29 files reviewed, 26 unresolved discussions (waiting on @donnadionne, @markdroth, and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 338 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1ndpeG586WkFPEDPiN:-N1oIcP9EcdCcoXu2XoO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L338)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need for `= absl::BitGen()`.  The class's ctor doesn't take any arguments, so it's fine to just say `absl::BitGen bit_gen_;`.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 488 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1neVEF-a6W73dW750d:-N1oWyTPDmwPeLtLzLD5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L488)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is not safe, because (a) you're not holding a ref to the LB policy, so you have no guarantee that it will still exist when you try to deference it here, and (b) the picker does not run in the `WorkSerializer`, so it's not safe to access the LB policy's `config_` field without synchronization.

I think a better approach here would be to remove the `outlier_detection_lb_` field and instead add a `const bool enabled_` field whose value is passed into the ctor.  When the LB policy instantiates the new picker, it can pass in the `enabled` parameter based on whether these two fields are set in the config.
</blockquote></details>

Done.



_Code quote:_
```cpp
             .success_rate_ejection.has_value() ||
        !outlier_detection_lb_->config_->outlier_detection_config()
             .failure_percentage_ejection.has_value()) {
```
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 831 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1ni1nzEIVxRahwnCa6:-N1oXvc6062O9gQ8jbq1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L831)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why do we need this variable?  Shouldn't we just use `ejected_host_count > 0` instead?
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 866 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1niBBNAfKw_eYkq1bj:-N1oY2sL8fFXnedEvdDM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L866)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same question as above: Why do we need this variable?  Shouldn't we just use `ejected_host_count > 0` instead?
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 955 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1niTub0uyZpYjdx0cP:-N1oYXWZAyx-_yrL86Ab:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L955)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this conditional is needed.  If the error list is non-empty, then the resulting config will never be used, so it should be fine to unconditionally add the success config.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 977 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1niaIX36le7syPxtV2:-N1oYXpS02JASBB-uXlo:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L977)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same as above: I don't think this conditional is needed.  If the error list is non-empty, then the resulting config will never be used, so it should be fine to unconditionally add the failure config.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 982 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1nimzPAHG564VrtWaa:-N1p3O3TAOGVK0DVserM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L982)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we want to parse these fields even if success rate and failure percentage are not present.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 990 at r12](https://reviewable.io/reviews/grpc/grpc/29343#-N1nix4K7G62fFqCw7_x:-N1p6zQS7G75TRMOOpA2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/db52566ce2b735611fc9a8ce1e6a31a443a489e6/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L990)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this can be written as:

```
if (!ParseJsonObjectFieldAsDuration(
         json.object_value(), "maxEjectionTime",
         &outlier_detection_config.max_ejection_time, &error_list,
         /*required=*/false)) {
  outlier_detection_config.max_ejection_time =
      std::max(outlier_detection_config.base_ejection_time,
               Duration::Seconds(300));
}
```
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 37 at r11](https://reviewable.io/reviews/grpc/grpc/29343#-N1dZEEM8qxatOiMdD0R:-N1qndoxECWeGhde-CeO:b7ogl21) ([raw file](https://github.com/grpc/grpc/blob/7eddbc544c1091e7a7f6d8515f8ad0c7940c6796/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we still need a test for `enforcement_percentage` being lower than 100 for both success rate and failure rate.  Otherwise, we have no way of knowing that those fields are actually honored.  We'll need to be careful here to ensure that the tests are not flaky.

Also, I think we need a test for `max_ejection_percent` that includes both ejection algorithms.  If the max would only allow 2 ejections, then if success rate ejects 1 and failure percentage tries to eject 2, we need to know that we will not eject the second one.
</blockquote></details>

added enforcement_percentage test setting it to 0?  do you think that would work?  otherwise, it's hard to be not flaky as the enforcement_percentage is only compared to a random key from 1 to 100

added max_ejection_percent with both algorithms and discovered some bugs along the way which I fixed.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 58 at r12](https://reviewable.io/reviews [...]

2022-05-12 08:17 UTC, donnadionne reviewed
a couple more commits to clean up the build.  My debugs are still in just in case i need them.  I need to fix the new check from iwyu.sh, but otherwise, I think all should be passing

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1rKsAVDpIXyWgsVm-l:bj7wj1z)* status: 12 of 29 files reviewed, 26 unresolved discussions (waiting on @donnadionne, @markdroth, and @yashykt)



<!-- Sent from Reviewable.io -->

2022-05-12 19:23 UTC, donnadionne reviewed
fixed iwyu so i think i should have a pretty clean build now

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1tiI4-EbCBDgivmW7h:b-eezgoo)* status: 12 of 29 files reviewed, 26 unresolved discussions (waiting on @donnadionne, @markdroth, and @yashykt)



<!-- Sent from Reviewable.io -->

2022-05-12 22:48 UTC, markdroth requested changes
This looks fantastic!  The only remaining substantive comment is the one about making sure that the "negative" tests (the ones in which no backend is ejected) actually fail when the code is broken, to make sure that the tests are actually covering what we think they are.

Please let me know if you have any questions.  Thanks!

> Reviewed 13 of 17 files at r13, 1 of 1 files at r15, 6 of 6 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1uSK9-CLe9MJAWHvH4:bj715fv)* status: all files reviewed, 13 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 211 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uKu69DFcT0-WFm4DC:-N1uKu69DFcT0-WFm4DD:b-bz34uj) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L211)):*
> ```cpp
> 
>     SubchannelState() {
>       current_bucket_ = absl::make_unique<Bucket>();
> ```

These should be initialized where the fields are declared instead of creating a ctor.  Note that for `active_bucket_`, you'll need to initialize with curly braces instead of parens.

If that doesn't work for some reason, let's at least set these in the ctor initializer list instead of in the body.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 245 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uM77W95763wW5tnjE:-N1uM77W95763wW5tnjF:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L245)):*
> ```cpp
> 
>     void AddSuccessCount() { active_bucket_.load()->successes.fetch_add(1); }
>     // void AddSuccessCount() { current_bucket_->successes.fetch_add(1); }
> ```

Please remove.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 248 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uM96n-hDkUr69of2o:-N1uM96n-hDkUr69of2p:b-867xyf) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L248)):*
> ```cpp
> 
>     void AddFailureCount() { active_bucket_.load()->failures.fetch_add(1); }
>     // void AddFailureCount() { current_bucket_->failures.fetch_add(1); }
> ```

Please remove.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 596 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uPnIjC9x63gFTYRdb:-N1uPnIjC9x63gFTYRdc:bty8t49) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L596)):*
> ```cpp
>   config_ = std::move(args.config);
>   // Update outlier detection timer.
>   if (config_->outlier_detection_config().interval == Duration::Infinity() ||
> ```

Suggest adding a `CountingEnabled()` method to `OutlierDetectionLbConfig` that checks all of these fields, and then use that same method both here and in `MaybeUpdatePickerLocked()`.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 842 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uMvyN9fDG_rNTrEa8:-N1uMvyN9fDG_rNTrEa9:b-w4s5n5) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L842)):*
> ```cpp
>     }
>     gpr_log(GPR_INFO,
>             "success candidate size %lu and failure candidate size %lu",
> ```

I assume this is meant to be a "donna" log message, which will be removed before merging.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 914 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uNbQu1bqzupheNILH:-N1uNbQv-MCrhcMT06l5:b64rgo) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L914)):*
> ```cpp
>           // Extra check to make sure success rate algorithm didn't already
>           // eject this backend.
>           if (!candidate.first->ejection_time().has_value() &&
> ```

This check can go at the very top of this loop.  If the candidate was already ejected, we can immediately continue to the next candidate, without checking the threshold or computing a random key.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 985 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uOvLz2pcejNXfVIJj:-N1uOvLz2pcejNXfVIJk:bir5yk0) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L985)):*
> ```cpp
>         OutlierDetectionConfig::SuccessRateEjection success_config;
>         const Json::Object& object = it->second.object_value();
>         ParseJsonObjectField(object, "stdevFactor",
> ```

Almost every call to `ParseJsonObjectField()` or `ParseJsonObjectFieldAsDuration()` in this function should set the optional `required` parameter to false, because all of the fields are optional and have default values.  The only field that is required is the `child_policy` field.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 1020 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uNrGv8dnK_KfeLDFT:-N1uNrGv8dnK_KfeLDFU:by42qye) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L1020)):*
> ```cpp
>                                    &outlier_detection_config.interval,
>                                    &error_list);
>     if (outlier_detection_config.interval != Duration::Infinity()) {
> ```

We want to parse these fields even if the duration is infinity.  If there's an error in one of these fields, we need to reject the config even if we're not going to use the value.
___
*[`src/core/lib/json/json_util.cc` line 23 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uKae56JDO5qtNYku0:-N1uKae56JDO5qtNYku1:b-nnl6rj) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/lib/json/json_util.cc#L23)):*
> ```cpp
> #include "src/core/lib/json/json_util.h"
> 
> #include <string.h>  // for strchr, strlen, size_t
> ```

Please remove these comments about what each include is for.  We don't need them.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 121 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uQkiF-jZVYFsgXHNf:-N1uQkiG90q1Cn2qumrW:bvy24s5) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L121)):*
> ```cpp
>   // Let base ejection period pass and see that we are no longer ejecting, rpcs
>   // going to their expectedly hashed backends.
>   gpr_sleep_until(grpc_timeout_milliseconds_to_deadline(2000));
> ```

Here we're waiting 2 seconds, but most of the other tests are only waiting 100ms.  Are we sure the other tests are giving enough time to actually succeed, especially where the test cases expect *nothing* to be ejected?  Those cases could easily pass even when they shouldn't if we don't give them enough time.

Just to make sure, for each test case, please try manually disabling something in the LB policy itself to make the test fail, and then make sure the test actually fails.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 303 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uQL15-g8J0Wy25iPC:- [...]

2022-05-13 04:52 UTC, donnadionne reviewed
made sure the "negative tests" do work and added comments

removed all debugs now!

and took care of all the rest of the comments.

PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1vkP5u8S8H-dPjzBD_:b1p2rn5)* status: all files reviewed, 13 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 196 at r10](https://reviewable.io/reviews/grpc/grpc/29343#-N1JfzXR4oXwigGRCiGx:-N1vKIt199ot4XpkCe2l:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7183f8ca58c52c10ca92ff4cc66f2e678ee2291b/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L196)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove before merging.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 211 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uKu69DFcT0-WFm4DC:-N1vKG1l7Ol-oOuK0XDW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L211)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These should be initialized where the fields are declared instead of creating a ctor.  Note that for `active_bucket_`, you'll need to initialize with curly braces instead of parens.

If that doesn't work for some reason, let's at least set these in the ctor initializer list instead of in the body.
</blockquote></details>

Done.



_Code quote:_
```cpp
absl::make_unique<Bucket>();
```
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 245 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uM77W95763wW5tnjE:-N1vKIIo6917FsjrHAoU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L245)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 248 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uM96n-hDkUr69of2o:-N1vKJnd5ULdxKWIXZ6T:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L248)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 596 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uPnIjC9x63gFTYRdb:-N1vf6Wd43KLNw797ivW:bjzuscg) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L596)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest adding a `CountingEnabled()` method to `OutlierDetectionLbConfig` that checks all of these fields, and then use that same method both here and in `MaybeUpdatePickerLocked()`.
</blockquote></details>

i made 2 methods because what happens if interval is configured but both algorithms are not.  so the CountingEnabled should be not caring about interval.  let me know what you think
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 842 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uMvyN9fDG_rNTrEa8:-N1vKXdY97KLPXdkgpGt:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L842)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume this is meant to be a "donna" log message, which will be removed before merging.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 914 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uNbQu1bqzupheNILH:-N1vLMQgA526XowMfyxN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L914)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check can go at the very top of this loop.  If the candidate was already ejected, we can immediately continue to the next candidate, without checking the threshold or computing a random key.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 985 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uOvLz2pcejNXfVIJj:-N1vcY0c041kPShJuB6u:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L985)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Almost every call to `ParseJsonObjectField()` or `ParseJsonObjectFieldAsDuration()` in this function should set the optional `required` parameter to false, because all of the fields are optional and have default values.  The only field that is required is the `child_policy` field.
</blockquote></details>

Done.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 1020 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uNrGv8dnK_KfeLDFT:-N1vcYuJEZ1_Qy4yLU0w:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L1020)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We want to parse these fields even if the duration is infinity.  If there's an error in one of these fields, we need to reject the config even if we're not going to use the value.
</blockquote></details>

Done.
___
*[`src/core/lib/json/json_util.cc` line 23 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uKae56JDO5qtNYku0:-N1vLegTA-C6fluQNqV-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/lib/json/json_util.cc#L23)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove these comments about what each include is for.  We don't need them.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 121 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uQkiF-jZVYFsgXHNf:-N1vC9HK2EIJeN0jZBzM:b8vt9le) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L121)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Here we're waiting 2 seconds, but most of the other tests are only waiting 100ms.  Are we sure the other tests are giving enough time to actually succeed, especially where the test cases expect *nothing* to be ejected?  Those cases could easily pass even when they shouldn't if we don't give them enough time.

Just to make sure, for each test case, please try manually disabling something in the LB policy itself to make the test fail, and then make sure the test actually fails.
</blockquote></details>

Let me explain:  
For every test we wait 100ms for the ejection policy to kick in because the timer interview is se [...]

2022-05-13 06:47 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343)* status: all files reviewed, 13 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 596 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uPnIjC9x63gFTYRdb:-N1w8fUgAZQ4hBolQcQr:b-9a89n4) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L596)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i made 2 methods because what happens if interval is configured but both algorithms are not.  so the CountingEnabled should be not caring about interval.  let me know what you think
</blockquote></details>

nevermind, 1 method for both: no interval, also no counting


<!-- Sent from Reviewable.io -->

2022-05-13 14:31 UTC, markdroth approved these changes
This looks excellent!  Please feel free to merge after addressing the last two minor comments.

Thanks!

> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1xp81c66y3TlD2FuOd:b-2a4kl)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[`src/core/lib/json/json_util.cc` line 25 at r17](https://reviewable.io/reviews/grpc/grpc/29343#-N1xnl__1f3fS6flrz9I:-N1xnl__1f3fS6flrz9J:ba8tqiq) ([raw file](https://github.com/grpc/grpc/blob/b7dd02eedf825866701e63de30c9336b22e3cebc/src/core/lib/json/json_util.cc#L25)):*
> ```cpp
> #include <string.h>
> 
> #include <grpc/support/log.h>
> ```

I don't think this include is needed anymore.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 745 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uRHrE5jhd0lF-1NIU:-N1xp-E36hWRmDbl7MzN:bg3wzzf) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L745)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look like this one was actually removed.


<!-- Sent from Reviewable.io -->

2022-05-13 14:34 UTC, markdroth requested changes

2022-05-13 14:34 UTC, markdroth commented on src/core/ext/xds/xds_cluster.cc
> +  if (envoy_config_cluster_v3_Cluster_has_outlier_detection(cluster)) {
I just noticed that we're missing the env var guard here.  We'll need to add that before we can merge this.

2022-05-13 16:26 UTC, donnadionne reviewed
thank you for the speedy reviews!  really appreciate it!  PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1yEOyc9NjxV57ZDiFf:b-r8eg6v)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[`src/core/ext/xds/xds_cluster.cc` line 408 at r17](https://reviewable.io/reviews/grpc/grpc/29343#-N-cQ_gMb5TvlvHRkAwB-r17-408:-N1yBU6T7VEWywCElQ-M:b-2u6mmd) ([raw file](https://github.com/grpc/grpc/blob/b7dd02eedf825866701e63de30c9336b22e3cebc/src/core/ext/xds/xds_cluster.cc#L408)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I just noticed that we're missing the env var guard here.  We'll need to add that before we can merge this.
</blockquote></details>

added and added disable tests
___
*[`src/core/lib/json/json_util.cc` line 25 at r17](https://reviewable.io/reviews/grpc/grpc/29343#-N1xnl__1f3fS6flrz9I:-N1yBGwe9gzS4nd1DG6q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b7dd02eedf825866701e63de30c9336b22e3cebc/src/core/lib/json/json_util.cc#L25)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this include is needed anymore.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 745 at r16](https://reviewable.io/reviews/grpc/grpc/29343#-N1uRHrE5jhd0lF-1NIU:-N1yBSnWAwQEC_Nko4ob:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ed1d7c9e1e648d7f95d597875fbe525ff84efbdb/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L745)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this one was actually removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-13 17:16 UTC, markdroth requested changes
Just a few nits remaining -- this is really close!

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1yPwKP9mrH20ELOeaJ:btm9l2j)* status: all files reviewed, 3 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 1019 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yFAtG9X6bJN8F70vp:-N1yFAtG9X6bJN8F70vq:bqakh1e) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L1019)):*
> ```cpp
> 
> void grpc_lb_policy_outlier_detection_init() {
>   grpc_core::LoadBalancingPolicyRegistry::Builder::
> ```

This should also be guarded by the env var.
___
*[`src/core/ext/xds/xds_route_config.cc` line 73 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yEtmGDIM3zYSYsP9v:-N1yEtmGDIM3zYSYsP9w:b-au00nd) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/src/core/ext/xds/xds_route_config.cc#L73)):*
> ```cpp
> 
> // TODO(donnadionne): Remove once outlier detection is no longer experimental
> bool XdsOutlierDetectionEnabled() {
> ```

This doesn't belong in this file.  This file is code for route config parsing, and none of that code needs this env var.

I suggest moving this to outlier_detection.cc instead.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 1237 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yPgGECnuQsEhSBPw-:-N1yPgGECnuQsEhSBPw0:b-95rmk) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L1237)):*
> ```cpp
> }
> 
> // GRPC_EXPERIMENTAL_ENABLE_OUTLIER_DETECTION not configured so feature
> ```

Instead of having two tests for the env var not being set, let's just have one test that includes both success rate and failure percentage, maybe something similar to the `SuccessRateAndFailurePercentage` test above.


<!-- Sent from Reviewable.io -->

2022-05-13 17:19 UTC, markdroth requested changes
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 37 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yQRlzB4NCSBdJn_qW:-N1yQRlzB4NCSBdJn_qX:b-lhgdfv) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L37)):*
> ```cpp
> using ::envoy::config::endpoint::v3::HealthStatus;
> 
> class OutlierDetectionTest : public XdsEnd2endTest {
> ```

It also occurred to me that we should probably have some non-xDS tests that use the outlier detection policy as well, using just round_robin as the child policy.  Those should probably be in a separate file, probably something like test/cpp/end2end/outlier_detection_end2end_test.cc.

If you don't have time for this, then please just put a TODO about this here.  Thanks!


<!-- Sent from Reviewable.io -->

2022-05-13 18:06 UTC, donnadionne reviewed
thank you! PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1yaUuADTswsqHhZyAB:b-rlq1k5)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 1019 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yFAtG9X6bJN8F70vp:-N1ya03d9aWTxgES8CBp:b26o5dd) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L1019)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should also be guarded by the env var.
</blockquote></details>

i don't think i can, coz outlier is now in the policy hierachy in all cases
___
*[`src/core/ext/xds/xds_route_config.cc` line 73 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yEtmGDIM3zYSYsP9v:-N1ya4TdA7yjS0j8RQfZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/src/core/ext/xds/xds_route_config.cc#L73)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't belong in this file.  This file is code for route config parsing, and none of that code needs this env var.

I suggest moving this to outlier_detection.cc instead.
</blockquote></details>

Done.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 37 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yQRlzB4NCSBdJn_qW:-N1ya55t5mYdZI2rF95v:bj67okr) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It also occurred to me that we should probably have some non-xDS tests that use the outlier detection policy as well, using just round_robin as the child policy.  Those should probably be in a separate file, probably something like test/cpp/end2end/outlier_detection_end2end_test.cc.

If you don't have time for this, then please just put a TODO about this here.  Thanks!
</blockquote></details>

added todo
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 1237 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yPgGECnuQsEhSBPw-:-N1y_zJK5QGWkwmY5wqy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L1237)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of having two tests for the env var not being set, let's just have one test that includes both success rate and failure percentage, maybe something similar to the `SuccessRateAndFailurePercentage` test above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-13 18:41 UTC, donnadionne reviewed
fixed IWYU

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N1yiHmi-tySefXES2w5:b3poxiz)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth and @yashykt)



<!-- Sent from Reviewable.io -->

2022-05-13 19:03 UTC, markdroth requested changes
> Reviewed 5 of 5 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 1019 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yFAtG9X6bJN8F70vp:-N1ymju09RHQqC2Os9zz:bbvl7ib) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L1019)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

i don't think i can, coz outlier is now in the policy hierachy in all cases
</blockquote></details>

We need to do this, because the outlier detection policy can be used without xDS, and we can't enable it until it's passed interop tests.

I think we should change the code in the xds_cluster_resolver policy that inserts the outlier detection policy into the tree to be guarded by this same env var.
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 19 at r19](https://reviewable.io/reviews/grpc/grpc/29343#-N1ynHb6CIpefyVuPEmX:-N1ynHb6CIpefyVuPEmY:bwhgpxj) ([raw file](https://github.com/grpc/grpc/blob/6c83d43b4df93018548fd69fcfa28735aa0c8aa4/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L19)):*
> ```cpp
> #include "src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.h"
> 
> #include <grpc/support/port_platform.h>
> ```

Looks like iwyu messed up the include order here.  You will probably need to run clang_format_code.sh.


<!-- Sent from Reviewable.io -->

2022-05-14 06:19 UTC, donnadionne reviewed
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343)* status: all files reviewed, 2 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 1019 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yFAtG9X6bJN8F70vp:-N20CGo6BylDID9G_V6Q:bas919u) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L1019)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We need to do this, because the outlier detection policy can be used without xDS, and we can't enable it until it's passed interop tests.

I think we should change the code in the xds_cluster_resolver policy that inserts the outlier detection policy into the tree to be guarded by this same env var.
</blockquote></details>

ok added the check in xds_cluster_resolver so will insert either outlier detection or cluster_impl based on environment var.
also added to the policy registration.

Updated tests: i couldn't get BuildSpecialConfiguration(), so i just set the environment var in main before grpc_init.   I then turn it off and have individual test having to turn the environment var on specificilly.   I know setting in main means the policy is always registered, I could move the disable out to a new file but not sure if that's necessary.  No other tests will do this so in all those the policy will not be registered and we are working fine.  So with the disable test specific testing behavior and the rest of the test testing when outlier policy is not registered.  I feel like we are covered.  let me know what you think
___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 19 at r19](https://reviewable.io/reviews/grpc/grpc/29343#-N1ynHb6CIpefyVuPEmX:-N20CFoV35PfT9Wzk1SB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6c83d43b4df93018548fd69fcfa28735aa0c8aa4/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L19)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like iwyu messed up the include order here.  You will probably need to run clang_format_code.sh.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-16 16:10 UTC, markdroth approved these changes
This looks great!  Feel free to merge after adding the TODO.

Thanks for all your work on this!

> Reviewed 4 of 4 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N2CcXEq0OSjY00ZUaMX:b-fil17n)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 1019 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yFAtG9X6bJN8F70vp:-N2CcAT72y9-oYXIMYEq:b-oaebaw) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L1019)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

ok added the check in xds_cluster_resolver so will insert either outlier detection or cluster_impl based on environment var.
also added to the policy registration.

Updated tests: i couldn't get BuildSpecialConfiguration(), so i just set the environment var in main before grpc_init.   I then turn it off and have individual test having to turn the environment var on specificilly.   I know setting in main means the policy is always registered, I could move the disable out to a new file but not sure if that's necessary.  No other tests will do this so in all those the policy will not be registered and we are working fine.  So with the disable test specific testing behavior and the rest of the test testing when outlier policy is not registered.  I feel like we are covered.  let me know what you think
</blockquote></details>

Oh, right, I forgot that the LB policy registry hasn't yet been moved to the `CoreConfiguration` system yet, which is why `BuildSpecialConfiguration()` wasn't working here.  Sorry for steering you wrong on that.

Setting the env var just while calling `grpc_init()` is a bit of a hack, but it's probably fine for now, with the TODO I've suggested elsewhere.
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 1302 at r20](https://reviewable.io/reviews/grpc/grpc/29343#-N2Cb3-n7_tHVtzTsc6D:-N2Cb3-n7_tHVtzTsc6E:bz0cgcf) ([raw file](https://github.com/grpc/grpc/blob/8245ff768378889f13f11c4ebcff3766ed00af49/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L1302)):*
> ```cpp
>   gpr_setenv("grpc_cfstream", "0");
> #endif
>   gpr_setenv("GRPC_EXPERIMENTAL_ENABLE_OUTLIER_DETECTION", "true");
> ```

Please add the following comment here:

TODO(roth): This is a hack to ensure that the outlier_detection LB policy is always registered at gRPC init time.  When the LB policy registry is moved to the new CoreConfiguration system, change this to use CoreConfiguration::BuildSpecialConfiguration() instead.


<!-- Sent from Reviewable.io -->

2022-05-16 17:28 UTC, donnadionne reviewed
thank you so much for all your help!  added the TODO

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N2CuWh4D6qsRkks2Y-t:bwgdm1)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth and @yashykt)

___
*[`src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc` line 1019 at r18](https://reviewable.io/reviews/grpc/grpc/29343#-N1yFAtG9X6bJN8F70vp:-N2CuR5VBprSJnCBaMBd:b2kwk0g) ([raw file](https://github.com/grpc/grpc/blob/0420f9f9decebf6fec6b214029ce690a96585dd8/src/core/ext/filters/client_channel/lb_policy/outlier_detection/outlier_detection.cc#L1019)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Oh, right, I forgot that the LB policy registry hasn't yet been moved to the `CoreConfiguration` system yet, which is why `BuildSpecialConfiguration()` wasn't working here.  Sorry for steering you wrong on that.

Setting the env var just while calling `grpc_init()` is a bit of a hack, but it's probably fine for now, with the TODO I've suggested elsewhere.
</blockquote></details>

added the TODO
___
*[`test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc` line 1302 at r20](https://reviewable.io/reviews/grpc/grpc/29343#-N2Cb3-n7_tHVtzTsc6D:-N2CuVW_BE1gZkXQbU8i:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/8245ff768378889f13f11c4ebcff3766ed00af49/test/cpp/end2end/xds/xds_outlier_detection_end2end_test.cc#L1302)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add the following comment here:

TODO(roth): This is a hack to ensure that the outlier_detection LB policy is always registered at gRPC init time.  When the LB policy registry is moved to the new CoreConfiguration system, change this to use CoreConfiguration::BuildSpecialConfiguration() instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-16 17:41 UTC, donnadionne reviewed
added one more small clean up caught at import time.  (I am just trying a cherry pick to make sure all tests in google3 pass without warnings, i prob won't cherry pick if no change is needed and it goes smoothly)

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N2CxG8pEzHjsz2S6sWP:b-wsstqs)* status: 13 of 31 files reviewed, 1 unresolved discussion (waiting on @markdroth and @yashykt)



<!-- Sent from Reviewable.io -->

2022-05-16 17:42 UTC, markdroth approved these changes
Looks great!

> Reviewed 18 of 18 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/29343#-:-N2Cx_UG5nmeGvl6pmEI:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yashykt)



<!-- Sent from Reviewable.io -->

2022-05-17 04:37 UTC, merged