Prevent a gRPC connection from being fatally terminated due to ENOBUFS error
grpc/grpc pull request #29961
Opened 2022-06-09 00:08 UTC by Vignesh2208

Prevent a gRPC connection from being fatally terminated due to ENOBUFS error.

@ctiller

2022-06-28 23:06 UTC, arjunroy requested changes
For the most part, my requested changes are just additions to comments. The actual logic looks good to me. 

Will approve after.

2022-06-29 00:52 UTC, Vignesh2208 commented on src/core/lib/iomgr/tcp_posix.cc
> +                 int additional_flags = 0) {
Done.

2022-06-29 00:53 UTC, Vignesh2208 commented on src/core/lib/iomgr/tcp_posix.cc
> +    OPEN,   // Everything is clear and omem is not full.
Added a state transition diagram

2022-06-29 00:53 UTC, Vignesh2208 commented on src/core/lib/iomgr/tcp_posix.cc
> +  // writable.
Updated the comment

2022-06-29 00:53 UTC, Vignesh2208 commented on src/core/lib/iomgr/tcp_posix.cc
> +    } else if (zcopy_enobuf_state_ != OMemState::OPEN) {
Updated the code to make this more clear.

2022-06-29 00:57 UTC, Vignesh2208 commented on src/core/lib/iomgr/tcp_posix.cc
> +  // returns false.
Updated the comment.

2022-07-12 00:35 UTC, arjunroy approved these changes

2022-07-12 01:46 UTC, merged