Support CIDR blocks in `no_proxy` config
grpc/grpc pull request #31119
Opened 2022-09-24 05:52 UTC by stanhu

This commit adds support for using CIDR blocks defined in the `no_proxy` environment variable. For example:

```
http_proxy=http://localhost:8080 no_proxy=10.10.0.0/8
```

Closes #22681

2022-09-26 17:52 UTC, stanhu commented on src/core/ext/filters/client_channel/http_proxy.cc
> +  auto proxy_address = StringToSockaddr(cidr[0], 0);
We may want to parse port numbers for exact IP matches. Golang does this: https://github.com/golang/go/blob/f771edd7f92a47c276d65fbd9619e16a786c6746/src/vendor/golang.org/x/net/http/httpproxy/proxy.go#L38-L50

2022-12-30 06:27 UTC, stanhu commented
@yashykt Would you be able to review?

2023-02-14 20:49 UTC, yashykt commented
Sorry for the delay. I'll take a look at this this week.

2023-03-07 20:30 UTC, yashykt requested changes
Sorry for the delay! :pray:

2023-03-07 20:30 UTC, yashykt commented on src/core/ext/filters/client_channel/http_proxy.cc
> +
please remove unnecessary blank lines. Or maybe replace them with comments. same thing throughout

2023-03-07 20:30 UTC, yashykt commented on src/core/ext/filters/client_channel/http_proxy.cc
> +  uint32_t mask_bits = atoi(std::string(cidr[1]).c_str());
please use absl::SimpleAtoi instead

2023-03-07 20:30 UTC, yashykt commented on test/core/client_channel/http_proxy_mapper_test.cc
> +
can you add some comments please - something like - "address not matching no_proxy cidr block"

2023-03-07 20:30 UTC, yashykt commented on src/core/ext/filters/client_channel/http_proxy.cc
> +static bool serverInCIDRRange(std::string server_host, absl::string_view no_proxy_entry) {
should be `ServerInCIDRRange`

2023-03-07 20:30 UTC, yashykt commented on test/core/client_channel/http_proxy_mapper_test.cc
> +TEST(NoProxyTest, CIDREntries) {
Rename to CIDREntriesExactMatch maybe?

2023-03-07 20:30 UTC, yashykt commented on test/core/client_channel/http_proxy_mapper_test.cc
> +TEST(NoProxyTest, CIDRClassDEntries) {
This test seems to be repetitive.

2023-03-07 20:30 UTC, yashykt commented on test/core/client_channel/http_proxy_mapper_test.cc
> +  absl::optional<std::string> name_to_resolve;
I suspect this showed up since you probably copied the template of `EmptyEntries` but it does not seem to be needed.

2023-03-07 21:13 UTC, yashykt reviewed
Also, could I request that you do not force-push/delete older commits that were reviewed. It would help maintain review history. The commits would be squashed at merge time anyway.

2023-03-07 21:13 UTC, yashykt commented on src/core/ext/filters/client_channel/http_proxy.cc
> +
missed this :)

2023-03-08 17:32 UTC, stanhu commented
> Also, could I request that you do not force-push/delete older commits that were reviewed. It would help maintain review history. The commits would be squashed at merge time anyway.

Sure, thing. I'm curious, though, how it maintains review history. The pull request still has the comments?

2023-03-08 22:27 UTC, yashykt commented
> Sure, thing. I'm curious, though, how it maintains review history. The pull request still has the comments?
If the previous commits remain, I can do a diff and see what changed from the previous commit, as opposed to having to look at the entire PR again.

2023-03-08 22:28 UTC, yashykt approved these changes

2023-03-08 22:46 UTC, stanhu commented
Trying to reproduce this build failure. Am I just missing this?

```diff
diff --cc BUILD
index 4ec32ff966,4ec32ff966..9159917f7c
--- a/BUILD
+++ b/BUILD
@@@ -2756,10 -2756,10 +2756,12 @@@ grpc_cc_library
          "//src/core:ext/filters/client_channel/lb_policy/child_policy_handler.cc",
          "//src/core:ext/filters/client_channel/lb_policy/oob_backend_metric.cc",
          "//src/core:ext/filters/client_channel/local_subchannel_pool.cc",
++        "//src/core:ext/filters/client_channel/parse_address.cc",
          "//src/core:ext/filters/client_channel/retry_filter.cc",
          "//src/core:ext/filters/client_channel/retry_service_config.cc",
          "//src/core:ext/filters/client_channel/retry_throttle.cc",
          "//src/core:ext/filters/client_channel/service_config_channel_arg_filter.cc",
++        "//src/core:ext/filters/client_channel/sockaddr_utils.cc",
          "//src/core:ext/filters/client_channel/subchannel.cc",
          "//src/core:ext/filters/client_channel/subchannel_pool_interface.cc",
          "//src/core:ext/filters/client_channel/subchannel_stream_client.cc",
@@@ -2782,9 -2782,9 +2784,11 @@@
          "//src/core:ext/filters/client_channel/lb_policy/oob_backend_metric.h",
          "//src/core:ext/filters/client_channel/lb_policy/oob_backend_metric_internal.h",
          "//src/core:ext/filters/client_channel/local_subchannel_pool.h",
++        "//src/core:ext/filters/client_channel/parse_address.h",
          "//src/core:ext/filters/client_channel/retry_filter.h",
          "//src/core:ext/filters/client_channel/retry_service_config.h",
          "//src/core:ext/filters/client_channel/retry_throttle.h",
++        "//src/core:ext/filters/client_channel/sockaddr_utils.h",
          "//src/core:ext/filters/client_channel/subchannel.h",
          "//src/core:ext/filters/client_channel/subchannel_interface_internal.h",
          "//src/core:ext/filters/client_channel/subchannel_pool_interface.h",
```

2023-03-08 22:57 UTC, yashykt commented
oops, looks like I overwrote your commit. My bad! But, I think that should fix the build issues.

2023-03-08 22:58 UTC, stanhu commented
Thanks! I wasn't able to reproduce the error locally with `bazel build :all`.

2023-03-22 21:21 UTC, stanhu commented on src/core/ext/filters/client_channel/http_proxy.cc
> +  std::vector<absl::string_view> cidr =
Thanks!

2023-03-22 21:43 UTC, markdroth commented on src/core/ext/filters/client_channel/http_proxy.cc
> +    absl::StrSplit(no_proxy_entry, absl::MaxSplits('/', 2));
Don't you still want `absl::SkipEmpty()` here?  Note that you can use both that and `MaxSplits()`:

```
absl::StrSplit(no_proxy_entry, absl::MaxSplits('/', 2), absl::SkipEmpty());
```

2023-03-22 21:43 UTC, markdroth commented on src/core/ext/filters/client_channel/http_proxy.cc
> +
Nit: Please remove blank line.

2023-03-22 21:43 UTC, markdroth commented on src/core/ext/filters/client_channel/http_proxy.cc
> +    absl::StrSplit(no_proxy_entry, absl::MaxSplits('/', 2));
This needs to be indented two more spaces.

2023-03-22 22:08 UTC, markdroth approved these changes
I've re-triggered the tests.  @yashykt, I'll let you get this merged once everything is passing.

2023-03-22 22:36 UTC, yashykt commented
@stanhu can you please run -
```
tools/distrib/iwyu.sh
tools/distrib/clang_format_code.sh
```

2023-03-31 06:43 UTC, merged

2023-03-31 06:43 UTC, yashykt commented
Thanks for the contribution!