Remove unused references to absl::Status (aka grpc_error_handle) and absl::StatusOr<>
grpc/grpc pull request #32233
Opened 2023-01-30 14:33 UTC by gankineri

Removing a number of unused variables. This has no behaviour change.

2023-01-31 20:42 UTC, eugeneo commented
@gankineri Thank you for your contribution! Please sign the CLA before our team can review the code.

2023-02-07 20:45 UTC, eugeneo requested changes
Thank you for your contribution. There are a bunch of minor code style nits.

2023-02-07 20:45 UTC, eugeneo commented on src/core/ext/filters/client_channel/lb_policy/xds/cds.cc
> +
nit: Please remove the empty line.

2023-02-07 20:45 UTC, eugeneo commented on src/core/ext/xds/xds_client_grpc.cc
> +
nit: please do not add an empty line.

2023-02-07 20:45 UTC, eugeneo commented on src/core/lib/event_engine/posix_engine/posix_engine_listener_utils.cc
> +
nit: please do not add an empty line.

2023-02-09 12:24 UTC, gankineri commented
Thank you for the review, dropped the extra newlines.

2023-02-14 20:53 UTC, markdroth approved these changes
This looks good.  I've triggered the tests, so we'll see how things look.

2023-02-14 22:40 UTC, markdroth commented
Looks like there are a bunch of test failures here.  I've sent you https://github.com/gankineri/grpc/pull/1 to fix them.  If you merge that PR, it will update this branch.

2023-02-16 01:02 UTC, merged