Add changes to test e2e tests in PR.
grpc/grpc pull request #33224
Opened 2023-05-23 21:27 UTC by mikefan1991

2023-05-24 23:16 UTC, HannahShiSFB commented
It needs to be defined `GRPC_IOS_EVENT_ENGINE_CLIENT` to enable event engine. 
ref: https://github.com/grpc/grpc/pull/32782

@mikefan1991

2023-06-15 23:05 UTC, eugeneo requested changes

2023-06-15 23:05 UTC, eugeneo commented on third_party/cares/cares
Is this intentional? I believe it needs to be reverted.

2023-06-15 23:05 UTC, eugeneo commented on third_party/xds
Is this intentional? I believe it needs to be reverted.

2023-06-21 21:30 UTC, mikefan1991 commented on third_party/xds
This is just a test PR and it will be removed later

2023-07-10 19:54 UTC, closed without merging