Loosen affinity test assertions
grpc/grpc pull request #33648
Opened 2023-07-10 20:13 UTC by gnossen

As part of the dualstack backend designs, subchannels will be created lazily. Therefore, instead of asserting that there is 1 READY channel and `n - 1` IDLE channels, we just assert that there is ` READY channel.

2023-07-10 22:10 UTC, sergiitk approved these changes
LGTM once tests pass:

- [x] [grpc/core/master/linux/grpc_xds_k8s_lb](https://source.cloud.google.com/results/invocations/9a11b2c8-a58d-487c-8cda-4615b35f3d00)
- [ ] [grpc/core/master/linux/grpc_xds_url_map](https://source.cloud.google.com/results/invocations/6e7392a3-367b-4f77-aae2-b150952a6aff) (failed)

2023-07-10 22:10 UTC, sergiitk commented on tools/run_tests/xds_k8s_test_driver/tests/affinity_test.py
> -            # The rest should be IDLE.
Might be helpful to add a note at line 133 that the rest may be in any state.

2023-07-10 23:08 UTC, sergiitk requested changes
We need to update urlmap test as well:

https://source.cloud.google.com/results/invocations/6e7392a3-367b-4f77-aae2-b150952a6aff/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_xds_url_map%2Furl_map/tests

```py
Traceback (most recent call last):
  File "/tmpfs/tmp/tmp.ZGpp6EB8Zy/grpc/tools/run_tests/xds_k8s_test_driver/framework/xds_url_map_testcase.py", line 499, in test_rpc_distribution
    self.rpc_distribution_validate(self.test_client)
  File "/tmpfs/tmp/tmp.ZGpp6EB8Zy/grpc/tools/run_tests/xds_k8s_test_driver/tests/url_map/affinity_test.py", line 129, in rpc_distribution_validate
    self.assertLen(
AssertionError: [] has length of 0, expected 2.
```

2023-07-11 20:04 UTC, gnossen commented
Good catch. Turns out the `url_map` version has several such assertions. Fixed.

2023-07-12 16:58 UTC, gnossen commented
Looks green.

2023-07-12 18:14 UTC, sergiitk approved these changes

2023-07-12 18:26 UTC, merged