[keepalive] Allow server side keepalive_permit_without_calls setting to be overridden without the experiment
grpc/grpc pull request #33917
Opened 2023-07-28 22:53 UTC by yashykt

2023-07-28 22:56 UTC, ctiller approved these changes

2023-07-29 12:44 UTC, Neilblaze approved these changes

2023-07-30 20:00 UTC, ctiller commented
Thinking about this - if the server side needs to roll out prior to client side, let's attach a separate experiment to this so we can monitor rollout %.

2023-07-30 20:01 UTC, ctiller requested changes
(changing approval to get the experiment added)

2023-07-31 18:41 UTC, yashykt commented
Done

2023-07-31 18:56 UTC, ctiller approved these changes

2023-07-31 22:28 UTC, merged