[PSM Interop] Add support to enable CSM Observability and a new test case
grpc/grpc pull request #34835
Opened 2023-10-31 17:40 UTC by stanley-cheung

This PR adds CSM Observability testing capability in the PSM Interop testing framework. This PR mostly changes the framework Python code.

This adds a flag `enable_csm_observability` to the client / server deployment yaml file such that, when enabled, we will create a GMP `PodMonitoring` resource and pass the `--enable_csm_observability` to each language's client / server container (for them to actually enable the Prometheus endpoint)

I added a new test under `tests/csm/csm_observability_test.py`. This is basically a copy of the `tests/baseline_test.py` but with the `enable_csm_observability=True`. 

Other PRs for this whole thing to work:
- https://github.com/grpc/grpc/pull/34752: The `PodMonitoring` resource yaml template
- https://github.com/grpc/grpc/pull/34832: Support for the `--enable_csm_observability` flag in the C++ client/server image

2023-10-31 22:01 UTC, stanley-cheung commented
Running adhoc xds test job again:

- [ ] [grpc_xds_k8s_lb](https://fusion2.corp.google.com/ci/kokoro/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_xds_k8s_lb/activity/a3eeee79-e45a-463e-bbc8-bd0b67370683/log)

2023-11-02 02:09 UTC, stanley-cheung commented
Another adhoc run:

- [ ] [grpc_xds_k8s_lb](https://fusion2.corp.google.com/ci/kokoro/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_xds_k8s_lb/activity/ffa93447-5ad5-4bb7-a7dc-886886f5e3a9/log)

2023-11-07 18:13 UTC, sergiitk requested changes

2023-11-07 18:13 UTC, sergiitk commented on tools/run_tests/xds_k8s_test_driver/tests/csm/csm_observability_test.py
> +
Were you going to run some assertions to check the observability is working? IRRC you were planning to use an API library to get some stats.

2023-11-07 18:53 UTC, sergiitk commented
Notes from the IRL discussion:

```diff
diff --git a/tools/run_tests/xds_k8s_test_driver/framework/test_app/runners/k8s/gamma_server_runner.py b/tools/run_tests/xds_k8s_test_driver/framework/test_app/runners/k8s/gamma_server_runner.py
index b50c6aa487..077ea76c21 100644
--- a/tools/run_tests/xds_k8s_test_driver/framework/test_app/runners/k8s/gamma_server_runner.py
+++ b/tools/run_tests/xds_k8s_test_driver/framework/test_app/runners/k8s/gamma_server_runner.py
@@ -39,2 +39,3 @@ class GammaServerRunner(KubernetesServerRunner):
     termination_grace_period_seconds: Optional[int] = None
+    pod_monitoring: Optional[int] = None
     pre_stop_hook: bool = False
diff --git a/tools/run_tests/xds_k8s_test_driver/kubernetes-manifests/csm/pod-monitoring.yaml b/tools/run_tests/xds_k8s_test_driver/kubernetes-manifests/csm/pod-monitoring.yaml
index bc5e53b35f..3204f0f9a3 100644
--- a/tools/run_tests/xds_k8s_test_driver/kubernetes-manifests/csm/pod-monitoring.yaml
+++ b/tools/run_tests/xds_k8s_test_driver/kubernetes-manifests/csm/pod-monitoring.yaml
@@ -5,3 +5,5 @@ metadata:
   namespace: ${namespace_name}
-  name: ${deployment_id}-gmp
+  name: ${pod_monitoring_name}
+  labels:
+    owner: xds-k8s-interop-test
 spec:
```

2023-12-14 02:26 UTC, stanley-cheung commented
@sergiitk Thanks for the feedback. I think this is ready for another round of review.

Feedback addressed:
 - Now the new test inherited from `xds_gamma_testcase.GammaXdsKubernetesTestCase` and is put in the `tests/gamma` directory.
 - `${pod_monitoring_name}` is now constructed in the code rather than in the template.
 - Added `owner: xds-k8s-interop-test` label.

Feedback _not yet_ addressed:
- Haven't added the `pod_monitoring` resource to be things explicitly clean up for now. There's something a bit complicated for things created by `self._load_dynamic_api(api_name, version, kind)` that I might need additional help. But for now, the resource should be implicitly destroyed after the namespace is deleted.
- Templating the `endpoints[].port`. We talked about this being added a bit later should be fine.
- Adding some assertions to check the observability metrics labels. Will add as separate PR. 

Hopefully this is in an acceptable state to be checked in - I do hope this can be merged soon so that we can run the test regularly first.

Thanks.

2024-01-03 22:15 UTC, sergiitk approved these changes
LGTM. There are a few minor changes I'd like to see before merging this, but at this point we've already migrated to https://github.com/grpc/psm-interop. Let's merge this one for the ease of migration, and then we'll address these minor notes the migration PR.

2024-01-03 22:25 UTC, closed without merging