[fork] Use AnyInvocable for fork handlers
grpc/grpc pull request #38075
Opened 2024-11-06 17:48 UTC by eugeneo

2024-11-06 18:37 UTC, eugeneo commented on src/core/lib/event_engine/posix_engine/ev_poll_posix.cc
> +            reinterpret_cast<void*>(ResetEventManagerOnFork),
```suggestion
            reinterpret_cast<void*>(&ResetEventManagerOnFork),
```

2024-11-06 18:37 UTC, eugeneo commented on src/core/lib/iomgr/ev_poll_posix.cc
> +                reinterpret_cast<void*>(reset_event_manager_on_fork),
```suggestion
                reinterpret_cast<void*>(&reset_event_manager_on_fork),
```

2024-12-02 20:24 UTC, A1exKH requested changes
@eugeneo, Could you add description for your PR to make it clearer and easier to review, please?

2024-12-02 20:49 UTC, eugeneo commented
This PR went nowhere :) Deleting.

2024-12-02 20:49 UTC, closed without merging