increased timeout for windows grpc basictests python
grpc/grpc pull request #38162
Opened 2024-11-20 16:11 UTC by sourabhsinghs

Increase timeout for Python basic tests on Windows

The tests are timing out on kokoro windows

We have added support for 3.12 python version but have not dropped support for any older version. hence overall number of tests have increased.

2024-11-20 16:55 UTC, sreenithi approved these changes

2024-11-20 17:47 UTC, gnossen requested changes
Mirroring portions of the review comment [here](https://github.com/grpc/grpc/pull/38161#pullrequestreview-2449317127).

The basictests have been timing out at the run_tests.py level, not the Kokoro level.

```
2024-11-19 09:36:13,599 TIMEOUT: run_tests_python_windows_opt_native [pid=2464, time=3600.1sec]
2024-11-19 09:36:13,614 FAILED: Some run_tests.py instances have failed.
```

The timeout is happening after 60 minutes. Bumping the higher-level Kokoro timeout from 180 to 240 will do nothing.

2024-11-20 17:48 UTC, gnossen commented
As discussed in the team meeting yesterday, the issue with the distribtests doesn't seem to be a timeout, but instead an issue of too many files opened concurrently.

```
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x86\\cl.exe' failed with exit code 4
```

I think the fix here will be to decrease the parallelism at the run_tests.py level.

2024-11-21 00:00 UTC, closed without merging

2024-11-21 16:01 UTC, gnossen commented
Please revert. How was this even merged with "changes requested" on the PR?